### ISSUE TITLE
Motif tab line crashes

### ISSUE THREAD

**Issue by qsmodo** [vim/vim#10009]
### Steps to reproduce

```
gvim -u NONE +tabnew
```
Right-click a tab and click any of the options from the context-menu.

### Expected behaviour

A tab is closed/created/opened...

### Version of Vim

8.2.4563

### Environment

OS: Gentoo
Terminal: Motif GVIM

### Logs and stack traces

```shell
*** stack smashing detected ***: terminated
Vim: Caught deadly signal ABRT
Vim: Finished.
```
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```
> gvim -u NONE +tabnew
> ```
> Right-click a tab and click any of the options from the context-menu.

I guess this happens because XtVaGetValues with XmNuserData obtains a
value of type XtPointer, but the space on the stack is int.
This must have worked in the past, perhaps something in the library
changed.

-- 
DEAD PERSON:  I'm getting better!
CUSTOMER:     No, you're not -- you'll be stone dead in a moment.
MORTICIAN:    Oh, I can't take him like that -- it's against regulations.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
