### ISSUE TITLE
C and C++ syntax breaking on < if () is around it

### ISSUE THREAD

**Issue by ar1ja** [vim/vim#10091]
### Steps to reproduce

1. Open a C or a C++ file
2. Write anything that has the syntax of for example `.. (... > ...)`
3. Profiy

### Expected behaviour

For it to work

### Version of Vim

vim-8.2.4586

### Environment

OS: Gentoo Linux
Terminal: ST (https://st.suckless.org/)
$TERM: (I use tmux) screen-256color
Shell: bash

### Logs and stack traces

Images: https://imgur.com/a/SeILTUC
Related (maybe?): https://github.com/vim/vim/issues/9436
Vim config: https://github.com/TruncatedDinosour/dotfiles-cleaned/tree/gentoo/dotfiles/editors/vim

**Comment by chrisbra** [comment]
can you please try with `vim --clean`?

**Comment by TruncatedDinosour** [comment]
> can you please try with `vim --clean`?

Seems fine there, is it my plugins or something then?

**Comment by TruncatedDinosour** [comment]
My C++ syntax file: https://pastebin.com/SdwBzgya
/usr/share/vim/vim82/syntax/cpp.vim

**Comment by lacygoill** [comment]
I manually typed all the characters in the image:
```vim
vim9script
var lines =<< trim END
    #include <stdio.h>

    int main(int arg, char *argv[]) {
        if (argc < 2) {
            puts("No args ew");
            return 1;
        }

        puts(argv[1]);

        return 0;
    }
END
lines->writefile('/tmp/c.c')
syntax on
noswapfile edit /tmp/c.c
```
And I can't reproduce the issue:

![gif](https://user-images.githubusercontent.com/8505073/161829084-2f0f32a3-46c9-4495-93c2-f59118179a18.gif)

---

> Seems fine there, is it my plugins or something then?

We don't know, because we don't have a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

---

   > vim-8.2.4586

This is a recent version, but there still have been 2 updates of the runtime files since then:

   - [one 17 days ago](https://github.com/vim/vim/commit/47c532e2bc55e8a48f7f47e1fae1ed30144f2fa1)
   - [another 6 days ago](https://github.com/vim/vim/commit/46eea444d992c2ae985cabb775a5d283f8e16df3)

I doubt it will fix the issue, but updating Vim is worth a try.

---

Which character is wrongly highlighted exactly?  This one:

    if (argc < 2) {
                ^
                ?

What is the stack of syntax items at its position?  You can get the latter by executing this Ex command:

    :vim9 echo synstack('.', col('.'))->map((_, v) => v->synIDattr('name'))->reverse()

**Comment by bfrg** [comment]
You need to remove all your plugins and then start adding one by one to see which one causes this highlighting issue. I have a feeling that it might be your [rainbow plugin](https://github.com/TruncatedDinosour/dotfiles-cleaned/blob/e5cea02f835e3390de84e9038e99fe272d676a37/dotfiles/editors/vim/vimrc#L91).

**Comment by chrisbra** [comment]
> Seems fine there, is it my plugins or something then?

Your plugins I guess. You need to debug your vimrc and all of your plugins. See e.g. the faq: https://vimhelp.org/vim_faq.txt.html#faq-2.5

**Comment by TruncatedDinosour** [comment]
> You need to remove all your plugins and then start adding one by one to see which one causes this highlighting issue. I have a feeling that it might be the [rainbow plugin](https://github.com/TruncatedDinosour/dotfiles-cleaned/blob/e5cea02f835e3390de84e9038e99fe272d676a37/dotfiles/editors/vim/vimrc#L91).

It was, woop, sorry :)
