### ISSUE TITLE
jump list loses > marker

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#10100]
### Steps to reproduce

1. `mkdir -p ~/.vim/plugged/ && cd ~/.vim/plugged`
2.  `git clone https://github.com/mhinz/vim-startify`
3.  `vim --clean -u ~/.viminrc` where `~/.viminrc` reads

```
set nocompatible
let &rtp = '~/.vim/plugged/vim-startify/' . ',' . &rtp
```

4. Type `:e ~/.viminrc` and hit Enter
5. Hit `<C-o>`
6. Type `:jumps` and hit Enter

### Expected behaviour

The output should contain `>`, but does not.

### Version of Vim

8.2.4602

### Environment

OS: Opensuse 15.3
Terminal: XTerm(330)
`$TERM`: xterm-256color
shell: GNU bash 4.4.23(1)

**Comment by chrisbra** [comment]
This happens, because startify sets `:set bufhidden=wipe` which means, Vim will wipe out the first buffer once it opens a new buffer (using the `:e` command). 

Then after step 5, when trying to go backwards in the jump list and printing the jump list again, Vim cannot find that buffer anymore and returns `NULL` as the file name, which means, it will not print out anything and eventually will not mark the current position in the jumplist.

https://github.com/vim/vim/blob/ac72c21da696cf6c31630a9e5ff4c0d3e2049c11/src/mark.c#L872-L879

I am not sure how to handle this. We could add a marker before the known position, something like this:

```diff
diff --git a/src/mark.c b/src/mark.c
index fbb4b9a45..cb3fab725 100644
--- a/src/mark.c
+++ b/src/mark.c
@@ -875,6 +875,8 @@ ex_jumps(exarg_T *eap UNUSED)
            if (name == NULL || message_filtered(name))
            {
                vim_free(name);
+               if (i == curwin->w_jumplistidx)
+                   msg_puts("\n>");
                continue;
            }

```


Which would put out this after step 5:
![image](https://user-images.githubusercontent.com/244927/162303349-9474aca2-84b5-4bc4-a26b-2f4a36f237e3.png)
This basically tells you you are before the first printed jump. But is this helpful? don't know.

**Comment by Konfekt** [comment]
According to `:help jump` the marker is always there:

```
The pointer will be set at the last used jump position.  The next CTRL-O
command will use the entry above it, the next CTRL-I command will use the
entry below it.  If the pointer is below the last entry, this indicates that
you did not use a CTRL-I or CTRL-O before.  In this case the CTRL-O command
will cause the cursor position to be added to the jump list, so you can get
back to the position before the CTRL-O.
```

Perhaps putting `>` to the current jump comes closest to Vim's behavior in other instances:

1.  `vim --clean`
2. Type `:e ~/.viminrc` and hit Enter
3. Hit `<C-o>`
4. Type `:jumps` and hit Enter

Then the output is

```
 Sprung Zeile Sp Datei/Text
>  0     1    0
```

since, right after starting Vim, the current position is already after the first jump

1.  `vim --clean`
2. Type `:e ~/.viminrc` and hit Enter
3. Type `:jumps` and hit Enter

```
:jumps
 Sprung Zeile Sp Datei/Text
   1     1    0
>
```

**Comment by chrisbra** [comment]
Hm, I am not sure. 
okay, maybe make it consistently use `-invalid-` as is done in `mark_line`? 

Would this be any better?
![image](https://user-images.githubusercontent.com/244927/162566323-00c48d44-37cb-47c1-9486-b589d192542e.png)

**Comment by chrisbra** [comment]
```diff
diff --git a/src/mark.c b/src/mark.c
index fbb4b9a45..2ff9207ea 100644
--- a/src/mark.c
+++ b/src/mark.c
@@ -871,8 +871,10 @@ ex_jumps(exarg_T *eap UNUSED)
        {
            name = fm_getname(&curwin->w_jumplist[i].fmark, 16);

+           if (name == NULL)
+               name=vim_strsave((char_u *)"-invalid-");
            // apply :filter /pat/ or file name not available
-           if (name == NULL || message_filtered(name))
+           if (message_filtered(name))
            {
                vim_free(name);
                continue;
```

**Comment by brammool** [comment]
That looks technically correct.  The only thing that might happen is to get a long list of "-invalid-" items.
Perhaps only use "-invalid-" if the mark is on it?  Otherwise the "-invalid-" items are not useful.

**Comment by chrisbra** [comment]
okay, let me prepare a PR for that
