### ISSUE TITLE
Wrong spellcheck colors with termguicolors (fixable with CTRL-L)

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#10177]
### Steps to reproduce

1. Create this `vimrc`:

```
set nocompatible
set termguicolors
set spell spelllang=en
hi SpellBad guifg=#ff0000 guibg=NONE guisp=#ff0000 gui=underline cterm=underline
call setline(1, 'Couleur')
```

2. Execute `vim --clean -u vimrc`. Note that the word is not colored.
3. Press CTRL-L. Now the mispelled word is colored correctly.

### Expected behaviour

The mispelled word should have the right color since startup.

See also this [thread](https://github.com/vim/colorschemes/issues/161), with further examples.

### Version of Vim

8.2.4324

### Environment

macOS, iTerm2, xterm-256color, zsh 5.8

**Comment by brammool** [comment]
I cannot reproduce it in my setup.  Is this specific for Mac, iTerm2, something else?

**Comment by lacygoill** [comment]
I can reproduce on Ubuntu 20.04, XTerm(353), bash 5.0.17.

However, I cannot reproduce consistently (only about once out of two).

**Comment by gdupras** [comment]
I can reproduce the bug in Konsole on Kubuntu 21.04 but doing CTRL-L does *not* fix the colors.

I ran git bisect and found that e023e88bed (v8.2.0863) is the faulty commit:

```
commit e023e88bed3f2e0a7ea4cf10cac2de80bc9c271c
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sun May 31 16:42:30 2020 +0200

    patch 8.2.0863: cannot set a separate color for underline/undercurl
    
    Problem:    Cannot set a separate color for underline/undercurl.
    Solution:   Add the t_AU and t_8u termcap codes. (Timur Celik, closes #6011)
```

**Comment by brammool** [comment]
> I can reproduce the bug in Konsole on Kubuntu 21.04 but doing CTRL-L
> does *not* fix the colors.
> 
> I ran git bisect and found that e023e88bed (v8.2.0863) is the faulty
> commit:
> 
> ```
> commit e023e88bed3f2e0a7ea4cf10cac2de80bc9c271c
> Author: Bram Moolenaar ***@***.***>
> Date:   Sun May 31 16:42:30 2020 +0200
> 
>     patch 8.2.0863: cannot set a separate color for underline/undercurl
>     
>     Problem:    Cannot set a separate color for underline/undercurl.
>     Solution:   Add the t_AU and t_8u termcap codes. (Timur Celik, closes #6011)
> ```

So, what are t_AU and t_8u set to?  What if you make them empty?

-- 
The acknowledged parents of reengineering are Michael Hammer and James Champy.
When I say they're the "parents" I don't mean they had sex - and I apologize
for making you think about it.  I mean they wrote the best-selling business
book _Reengineering the Corporation_, which was published in 1993.
   Businesses flocked to reengineering like frat boys to a drunken
cheerleader.  (This analogy wasn't necessary, but I'm trying to get my mind
off that Hammer and Champy thing.)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gdupras** [comment]
```
:set t_AU? t_8u?
  t_AU=^[[58;5;%dm
  t_8u=^[[58;2;%lu;%lu;%lum
```
If I make them empty in the vimrc like this:
```
set t_AU=
set t_8u=
set nocompatible
set termguicolors
set spell spelllang=en
hi SpellBad guifg=#ff0000 guibg=NONE guisp=#ff0000 gui=underline cterm=underline
call setline(1, 'Couleur')
```
and do `vim --clean -u vimrc`, the word is correctly colored and underlined, without needing to do CTRL-L.

**Comment by brammool** [comment]
> ```
> :set t_AU? t_8u?
>   t_AU=^[[58;5;%dm
>   t_8u=^[[58;2;%lu;%lu;%lum
> ```
> If I make them empty in the vimrc like this:
> ```
> set t_AU=
> set t_8u=
> set nocompatible
> set termguicolors
> set spell spelllang=en
> hi SpellBad guifg=#ff0000 guibg=NONE guisp=#ff0000 gui=underline cterm=underline
> call setline(1, 'Couleur')
> ```
> and do `vim --clean -u vimrc`, the word is correctly colored and
> underlined, without needing to do CTRL-L.

It looks like t_8u is set even though it doesn't work.
What is the output of ":call terminalprops()"?

Also check the output of ":verbose set t_8u".

There was some work done to set t_8u automatically, and clear it when
the term response indicates it might not work.  What is the value of
"v:termresponse"?

-- 
I recommend ordering large cargo containers of paper towels to make up
whatever budget underruns you have.  Paper products are always useful and they
have the advantage of being completely flushable if you need to make room in
the storage area later.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by gdupras** [comment]
```
:echo terminalprops()

{'mouse': '2', 'cursor_style': 'n', 'underline_rgb': 'y', 'cursor_blink_mode': 'n'}

:verbose set t_8u

  t_8u=^[[58;2;%lu;%lu;%lum

:echo v:termresponse

^[[>0;115;0c
```

**Comment by brammool** [comment]
> ```
> :echo terminalprops()
> 
> {'mouse': '2', 'cursor_style': 'n', 'underline_rgb': 'y', 'cursor_blink_mode': 'n'}
> 
> :verbose set t_8u
> 
>   t_8u=^[[58;2;%lu;%lu;%lum
> 
> :echo v:termresponse
> 
> ^[[>0;115;0c
> ```

Thanks.  This means that Vim recognizes the terminal as Konsole,
which supports the t_8u entry, so that is correct.

However, you mentioned using iTerm2, not Konsole.  That is inconsistent,
since iTerm2 is expected to send "0;95;0".

Not sure what is going on here.  You can manually clear t_8u, but it
would be nice if we can have the right default.

-- 
The fastest way to get an engineer to solve a problem is to declare that the
problem is unsolvable.  No engineer can walk away from an unsolvable problem
until it's solved.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> However, you mentioned using iTerm2, not Konsole.

The OP is using iTerm2.  They are using Konsole.

**Comment by brammool** [comment]
>    > However, you mentioned using iTerm2, not Konsole.
> 
> The OP is using iTerm2.  They are using Konsole.

Ehm, then we have very confusing information.

Please describe the problem (or not noticing a problem) together with
the relevant information.  If you have more then one setup, do it for
each separately.

-- 
An alien life briefly visits earth.  Just before departing it leaves a
message in the dust on the back of a white van.  The world is shocked
and wants to know what it means.  After months of studies the worlds
best linguistic scientists are able to decipher the message: "Wash me!".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
In Konsole 19.12.3, on Ubuntu 20.04, the word `Couleur` is never highlighted with the `SpellBad` highlight group.  These are the key codes that Vim sends to the terminal:

    ^[[38;2;255;0;0m^[[58;2;255;0;0mCouleur^[[m

If I send the same key codes outside of Vim, the issue persists (i.e. `Couleur` is not colored):

    $ printf '\e[38;2;255;0;0m\e[58;2;255;0;0mCouleur\e[m\n'

If I remove `t_8u`, the issue disappears (i.e. `Couleur` *is* colored):

    $ printf '\e[38;2;255;0;0mCouleur\e[m\n'

Does Konsole really support `t_8u`?

**Comment by lacygoill** [comment]
So, this works in gnome-terminal and kitty:

    $ printf '\e[4m\e[38;2;255;0;0m\e[58;2;0;255;0mCouleur\e[m\n'

Notice that `Couleur` is highlighted in red, and underlined in green.

But the same command fails in Konsole (nothing is highlighted, and there is no underline).

It seems Konsole simply does not support a color specific to an underline.

According to [kitty's documentation](https://sw.kovidgoyal.net/kitty/underlines/), to detect whether a given terminal supports colored and styled underlines, we need to query the terminfo database for the `Su` boolean capability.  And it's absent from Konsole terminal description:

    $ infocmp -1x konsole | grep Su

Which seems to confirm that Konsole does not support `t_8u`.

However, querying `Su` does not seem reliable.  Because it's also absent from gnome terminal description:

    $ infocmp -1x gnome | grep Su

And yet, gnome does support `t_8u`.

I don't know how to reliably detect this feature.  However, one of these threads might give a clue:

   - [Curly and colored underlines](https://gitlab.com/gnachman/iterm2/-/issues/6382)
   - [Please add undercurl support to VTE with unused SGR code pair](https://bugzilla.gnome.org/show_bug.cgi?id=721761)

**Comment by lacygoill** [comment]
For xterm and iTerm2, I *guess* the issue is that Vim assumes that the terminal supports `t_8u` on startup.  But a few milliseconds later, when it receives more information from the terminal identity/capabilities, it then realizes that actually the terminal does not support `t_8u`, and stops sending the problematic `CSI 58 ; 2` key code.

That would explain why the issue disappears after pressing `C-L` which triggers a redraw.

---

For xterm/iTerm2, I wonder whether clearing [`'t_RV'`](https://vimhelp.org/term.txt.html#t_RV) or resetting [`'xtermcodes'`](https://vimhelp.org/options.txt.html#%27xtermcodes%27)` help:

    set t_RV=
    set noxtermcodes

**Comment by lacygoill** [comment]
> For xterm/iTerm2, I wonder whether clearing 't_RV' or resetting 'xtermcodes'` help:

After some quick test, the answer is no; at least for xterm, they do not help.

**Comment by brammool** [comment]
OK, so for Konsole we should not define t_8u by default.  And for xterm and iTerm2 we should redraw when we make t_8u empty.

**Comment by lacygoill** [comment]
The issue is fixed for Konsole, but for xterm, we still sometimes need to press `CTRL-L`.  Either `redraw_later()` is still called too soon, or maybe we need to clear the screen first (calling `redraw_later_clear()` maybe?).

**Comment by lifepillar** [comment]
Thanks for addressing this and sorry for the lack of feedback: somehow I had notifications disabled for this repo and it went off my radar. I can confirm that the current master fixes the issue for iTerm2 (macOS).

**Comment by brammool** [comment]
> The issue is fixed for Konsole, but for xterm, we still sometimes need to
> press `CTRL-L`.  Either `redraw_later()` is still called too soon, or maybe
> we need to clear the screen first (calling `redraw_later_clear()` maybe?).

Hmm, I don't expect that to make a difference.

Anyway, some tests are failing because of the unexpected redraw.

Perhaps a more complicated solution is needed: when outputting t_8u before the
termresponse is received, do not write it and set a flag.  If then later the
termresponse is received and t_8u is not reset then redraw.  This should give
flicker only for very few cases.  While with the current solution we very often
redraw even though it's not needed.  I mean, how often do you see SpellBad on
startup?

-- 
Me?  A skeptic?  I trust you have proof.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
