### ISSUE TITLE
Garbled first line from output of :filter ... oldfiles

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1018]
To reproduce (assuming you have recently opened your `vimrc`):
1. `:filter /vimrc$/ oldfiles`
2. `:filter vimrc$ oldfiles`

Output:
1. `9: ~/.vim/vimrc/ oldfiles` (note the trailing `oldfiles`);
2. `9: ~/.vim/vimrcoldfiles`

**Comment by brammool** [comment]
Lifepillar wrote:

> To reproduce (assuming you have recently opened your `vimrc`):
> 1. `:filter /vimrc$/ oldfiles`
> 2. `:filter vimrc$ oldfiles`
> 
> Output:
> 1. `9: ~/.vim/vimrc/ oldfiles` (note the trailing `oldfiles`);
> 2. `9: ~/.vim/vimrcoldfiles`

Looks like this problem was always there, but since :oldfiles is short
it was not noticed.

## 

I AM THANKFUL...
...for all the complaining I hear about the government
because it means we have freedom of speech.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Ah ok, it is similar to a problem I had in the past with overlapping echo messages, and I seem to be able to work around the problem in the same way:

```
:echo "\r" | filter vimrc$ oldfiles
```

**Comment by lifepillar** [comment]
I confirm that  patch 7.4.2283 fixes it. Thanks!
