### ISSUE TITLE
Vim9: cannot use funcref variable to refer to imported function for input() completion

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#10197]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var dir = '/tmp/.vim'
        dir->delete('rf')
        &runtimepath = dir
        dir ..= '/autoload'
        dir->mkdir('p')
        var lines =<< trim END
            vim9script
            export def CompleteWords(..._): string
                return getline(1, '$')
                    ->join(' ')
                    ->split('\s\+')
                    ->filter((_, word) => word =~ '^\a\k\+$')
                    ->sort()
                    ->uniq()
                    ->join("\n")
            enddef
        END
        lines->writefile(dir .. '/script.vim')
        import autoload 'script.vim'
        'the quick brown fox jumps over the lazy dog'->setline(1)
        var Ref = script.CompleteWords
        var word: string = input('word: ', '', 'custom,' .. expand('<SID>') .. 'Ref')
    EOF
    )

Vim prompts us for a word.  Press Tab to get a suggestion; an error is given:

    E117: Unknown function: <SNR>1_Ref

**Expected behavior**

No error is given.  The `brown` suggestion is inserted on the command-line.

**Version of Vim**

8.2 Included patches: 1-4753

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

As a workaround, we can use a wrapper function:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def CompleteWords(..._): string
        return getline(1, '$')
            ->join(' ')
            ->split('\s\+')
            ->filter((_, word) => word =~ '^\a\k\+$')
            ->sort()
            ->uniq()
            ->join("\n")
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
'the quick brown fox jumps over the lazy dog'->setline(1)
def Wrapper(..._): string
    return script.CompleteWords()
enddef
var word: string = input('word: ', '', 'custom,' .. expand('<SID>') .. 'Wrapper')
```
---

We can use an intermediate funcref variable to refer to an imported function when the latter is used to set a statusline item:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def StatusLineItem(): string
        return 'my status line item'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
&laststatus = 2
var Ref = script.StatusLineItem
&statusline = '%{' .. expand('<SID>') .. 'Ref()}'
```
Same thing for an imported function used to set the statusline as a whole:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def WholeStatusLine(): string
        return 'my whole status line'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
&laststatus = 2
var Ref = script.WholeStatusLine
&statusline = '%!' .. expand('<SID>') .. 'Ref()'
```
Same thing for an imported function used to set the tabline:
```vim
vim9script
var dir = '/tmp/.vim'
dir->delete('rf')
&runtimepath = dir
dir ..= '/autoload'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def TabLine(): string
        return 'my tab line'
    enddef
END
lines->writefile(dir .. '/script.vim')
import autoload 'script.vim'
&showtabline = 2
var Ref = script.TabLine
&tabline = '%!' .. expand('<SID>') .. 'Ref()'
```

Why can't we do the same for a completion function passed to `input()`?

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
>         var dir = '/tmp/.vim'
>         dir->delete('rf')
>         &runtimepath = dir
>         dir ..= '/autoload'
>         dir->mkdir('p')
>         var lines =<< trim END
>             vim9script
>             export def CompleteWords(..._): string
>                 return getline(1, '$')
>                     ->join(' ')
>                     ->split('\s\+')
>                     ->filter((_, word) => word =~ '^\a\k\+$')
>                     ->sort()
>                     ->uniq()
>                     ->join("\n")
>             enddef
>         END
>         lines->writefile(dir .. '/script.vim')
>         import autoload 'script.vim'
>         'the quick brown fox jumps over the lazy dog'->setline(1)
>         var Ref = script.CompleteWords
>         var word: string = input('word: ', '', 'custom,' .. expand('<SID>') .. 'Ref')
>     EOF
>     )
> 
> Vim prompts us for a word.  Press Tab to get a suggestion; an error is given:
> 
>     E117: Unknown function: <SNR>1_Ref

Which is correct, it's not a function, it is a variable which happens to
be a function reference.  You can't access script-local variables
outside of the script.  However..., see below.

It does work to get the value of "Ref" when calling input():

	var word: string = input('word: ', '', 'custom,' .. string(Ref))

> As a workaround, we can use a wrapper function:

This seems a reasonable alternative, but clumsy.

The problem we need to solve is referring to the function with a string.
So somehow convert "script.CompleteWords()" to a string that can be used
outside of the script to call the function.  Actually, the most
straightforward is doing just that:

	var word: string = input('word: ', '', 'custom,' .. string(script.CompleteWords))

Seems that this works for this example.  Might very well work in other
contexts as well.

> We can use an intermediate funcref variable to refer to an imported
> function when the latter is used to set a statusline item:

> var Ref = script.StatusLineItem
> &statusline = '%{' .. expand('<SID>') .. 'Ref()}'

I'm surprised this works.  Must be because of the added "()", it tries
to find the variable then.  This happens in deref_func_name(), which
calls find_var_also_in_script().  For the completion function
deref_function_name() is used, which works slightly differently...

> Same thing for an imported function used to set the statusline as a whole:
and
> Same thing for an imported function used to set the tabline:

Again with using Ref().

> Why can't we do the same for a completion function passed to `input()`?

Because it is accessing the variable itself, instead of making a
function call.  But I can see that since it works in other places, you
expect it to work here as well.

It would take some time to figure out why deref_func_name() and
deref_function_name() are different and what about that matters.  For
the time being, I think it's safe to call find_var_also_in_script() from
deref_function_name() when evaluating the name fails.

-- 
No engineer can take a shower without wondering if some sort of Teflon coating
would make showering unnecessary.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
