### ISSUE TITLE
Stateful lambdas

### ISSUE THREAD

**Issue by Aster89** [vim/vim#10195]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
No, it's not impossible, but creating a stateful lambda is currently a bit cumbersome.

As soon as I tried:
```viml
export var Stateful = (state) => {
  return (arg) => {
    state += arg
    return state
    }
  }
```
I discovered `E1090: Cannot assign to argument state`. From there, I learned that
> The a: scope and the variables in it cannot be changed, they are fixed. However, if a composite type is used, such as `List` or `Dictionary` , you can change their contents.

So I can make a stateful lambda like this:
```viml
export var Stateful = (state: list<any>) => { # could avoid writing the type
  return (arg) => {
    state[0] += arg
    return state[0]
    }
  }
```

**Describe the solution you'd like**
Ideally, why shouldn't the first syntax work? It would allow more readable stateful lambdas.

**Describe alternatives you've considered**
Well, holding the state in a list, like above.

**Additional context**
Functional programming.

Can't come up with a simple but reasonable example (I'm ok if I'm told there isn't), but here's a lambda that generates Fibonacci numbers:
```viml
export var Fib = ((init: list<list<number>>) => {
  return () => {
    init[0] = [init[0][1], init[0][0] + init[0][1]]
    return init[0][1]
    }
  })([[0, 1]])
```
and here's the same lambda if it was allowed to alter its arguments
```viml
export var Fib = ((init: list<number>) => {
  return () => {
    init = [init[1], init[0] + init[1]]
    return init[1]
    }
  })([0, 1])
```

**Comment by brammool** [comment]
The reason you cannot change an argument is because it does not have the effect as you might expect.
It would only change the value in the function, not for the caller.  E.g.
```
var count = 0
SomeLamda(count)
```
You might think that SomeLambda() could increment the count, but it cannot, because the value is passed, not the variable.
In C you could pass a pointer to "count" to allow for the function to increment the value.  But we don't have pointers in Vim script.  That is why you need to use a list.

In some situations you might want to use a closure, where you don't pass "count" as an argument but the lambda has access to a local variable that it can increment.
