### ISSUE TITLE
events does not exists when vim startup

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#10207]
### Steps to reproduce

The vimrc

```
set nocompatible
    let events = join(filter( ['BufEnter', 'CursorMoved', 'VimResized', 'FocusGained', 'CursorHold', 'WinScrolled' ], 'exists("#" . v:val)'), ',')
    echom 'events is:' . events
```

start vim, you can only see:

```
BufEnter,CursorMoved
```

### Expected behaviour

all these events should be listed

### Version of Vim

vim 8.2.4732

### Environment

windows + gvim

**Comment by lacygoill** [comment]
`CursorHold` is not meant to be fired on startup, because no keys were pressed yet:

   > CursorHold is only triggered after the user has pressed a key, that is documented.
   > If you type ":n" that means some keys were pressed.
   > On startup no keys were pressed.
   > Makes sense?

[source](https://github.com/vim/vim/issues/7017#issuecomment-699066924)

---

`VimResized` is not meant to be fired on startup either:

   > Not when starting up though.

See [`:help VimResized`](https://vimhelp.org/autocmd.txt.html#VimResized).

---

Not sure about `WinScrolled`, but I would think it's not meant to be fired on startup either, just like `VimResized`.

---

`FocusGained` works for me:

    autocmd FocusGained * unsilent echomsg 'FocusGained has been fired'

Tested with Vim 8.2.4760, on Ubuntu 20.04, with the GTK3 GUI.

**Comment by wsdjeg** [comment]
So you mean, `exists(#event)` only return 1 when vim has the patch and the event has been fired?

**Comment by lacygoill** [comment]
Oh, my bad.  You were not talking about the events being fired, but on the output of the `exists()` function.  Let me do more tests.

**Comment by brammool** [comment]
You are checking for which events autocommands exists.  With "vim --clean" you get those two events.
If you want to check which events are supported, double the #.

**Comment by wsdjeg** [comment]
sorry, my bad, it should `exists(##event)`
