### ISSUE TITLE
foldexpr gets called extremely often on undo

### ISSUE THREAD

**Issue by KnoP-01** [vim/vim#10227]
### Steps to reproduce

1. create a file called foldexpr_test.vim:
``` vim
set foldmethod=expr
set foldexpr=Foldexpression()
function Foldexpression() abort
	return "="
endfunction
	" dummyline
" dummyline
	" dummyline
" dummyline
	" dummyline
" dummyline
	" dummyline
" dummyline
	" dummyline
" dummyline
	" dummyline
```
2. start vim/gvim --clean -u NONE
3. :profile start profilevim.txt
4. :profile! file *foldexpr_test.vim
5. :e foldexpr_test.vim
6. :so %
7. =G
8. u
9. :q
10. see profilevim.txt mentions 152 calls of Foldexpression()

### Expected behaviour

Less than 50 calls of Foldexpression()

How do I get to 50 calls? Well, if we :q! vim after step 7 we get 33 calls of Foldexpression(). I would expect Foldexpression() to be called once for every line after an undo. So 33+16=49.

There seems to be an exponential growth. I had a ~10000 line file where 'foldexpr' got called ~200million times after an undo, which was extremely slow.

### Version of Vim

VIM - Vi IMproved 8.2 Included patches: 1-4747

### Environment

Windows 10
Antix Linux

**Comment by KnoP-01** [comment]
If I blow up the testfile to 50 lines, I get 101 calls of 'foldexpr' after step 7 and 1325 after undo. The number of calls is getting big quickly.

**Comment by brammool** [comment]
Patrick Meiser-Knosowski wrote:

> ### Steps to reproduce
> 
> 1. create a file called foldexpr_test.vim:
> ``` vim
> set foldmethod=expr
> set foldexpr=Foldexpression()
> function Foldexpression() abort
> 	return "="
> endfunction
> 	" dummyline
> " dummyline
> 	" dummyline
> " dummyline
> 	" dummyline
> " dummyline
> 	" dummyline
> " dummyline
> 	" dummyline
> " dummyline
> 	" dummyline
> ```
> 2. start vim/gvim --clean -u NONE
> 3. :profile start profilevim.txt
> 4. :profile! file *foldexpr_test.vim
> 5. :e foldexpr_test.vim
> 6. :so %
> 7. =G
> 8. u
> 9. :q
> 10. see profilevim.txt mentions 152 calls of Foldexpression()

There are three things that add to this:
- The fold expression returns "=", which means "same as previous line".
  Thus when getting the fold level of the last line it will go through
  all the previous lines, one by one, until reaching line 1.
- The "=G" operator saves each line separately.
- The "undo" then restores each line, starting with the last one.  Then
  adjusts the fold level, which runs into the first item. That's indeed
  exponential.

The fold expression can work in many ways, not applying it for every
undone change but only afterwards might have undesired effects.  Might
work, I'm not sure.

The simplest would be to tackle the second thing, make "=G" create one
undo for all lines, instead of one for each line.

-- 
How To Keep A Healthy Level Of Insanity:
11. Specify that your drive-through order is "to go".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by KnoP-01** [comment]
This is great! Thanks a lot!
