### ISSUE TITLE
feature request: job_start() cwd option

### ISSUE THREAD

**Issue by still-dreaming-1** [vim/vim#1024]
It would be nice if job_start() accepted a cwd option in the option parameter. This would make it easy to start things with a specific working directory. Currently the Neovim jobstart() has such an option. I am working on adding a feature to the codi.vim plugin where it will start the REPL from the directory of the buffer being edited. In Neovim it is easy, I just pass the correct directory in the cwd option. In Vim I have to change Vim's current working directory to that directory, call job_start() and then change it back to the original working directory. Having such an option would allow this feature to work in Vim in a more side effect free way.

**Comment by grochmal** [comment]
I can assure you that `neovim`'s `jobstart()` performs exactly that: First changes the process CWD, executes the `fork`+`exec` call and then changes the directory back.  This is because the `exec*` group of system calls do not receive a parameter for the CWD.

In the [POSIX spec for exec calls](http://pubs.opengroup.org/onlinepubs/009695399/functions/exec.html) you can see that one parameter that is always inherited from the parent process is CWD:

> The new process shall inherit at least the following attributes from the calling process image:
> ...
> -   Current working directory

Therefore Neovim certainly does the CWD change by the method above.  Whichever way you do it (in Vimscript or C code) you must change the CWD before executing any `exec*` syscall.

I admit, this is a *NIX centred answer, but I do not believe Amiga or MS Windows follow a different `fork`+`exec` convention.

**Comment by bfredl** [comment]
>  First changes the process CWD, executes the fork+exec call and then changes the directory back. 

Not really, neovim (libuv)  first forks, then changes the directory only in the child. No change of directory is done in the parent.  On windows it looks like CreateProcessW takes cwd argument.

**Comment by grochmal** [comment]
> (libuv) first forks, then changes the directory only in the child

Hmm... I guess that does give a slight performance improvement.  Probably not noticeable if the given path is valid, but may be a considerable performance improvement when the path does not exist and `chdir()` fails (and we actually want to give out some warning in that case).

Valid point then.

**Comment by brammool** [comment]
If the directory change happens in the child, how are errors handled?

**Comment by bfredl** [comment]
neovim checks `os_isdir()` before spawning (but not permissions, probably it should). If `chdir()` in the child still fails, libuv sends the errno code back over a dedicated pipe with FD_CLOEXEC. Currently neovim in that case displays an error then that process launch failed, but not specifically that chdir failed. That could be done by also sending an enum over the pipe indicating what step in the child failed.

Relevant code: https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L350

**Comment by euclio** [comment]
I believe this was fixed by https://github.com/vim/vim/commit/05aafed54b50b602315ae55d83a7d089804cecb0.
