### ISSUE TITLE
Broken SELECT mode when remapping `<LeftDrag>`

### ISSUE THREAD

**Issue by noscript** [vim/vim#10249]
### Steps to reproduce

1. Create `~/leftdrag.vim`:
```vim
set selectmode=key,mouse

function! MyFunc()
endfunction
noremap  <LeftDrag> <LeftDrag><Cmd>call MyFunc()<CR>
noremap! <LeftDrag> <LeftDrag><Cmd>call MyFunc()<CR>
```
2. Run vim:
```sh
vim --clean -g +'so ~/leftdrag.vim' README.md
```
3. Do text selection with mouse. Mode shown at the bottom is `-- VISUAL --`.

### Expected behaviour

Mode shown at the bottom is `-- SELECT --`.

### Version of Vim

8.2.4804

### Environment

OS: Debian 11
Terminal: GUI

**Comment by zeertzjq** [comment]
Inferring from the comment in the code this seems to be intentional:
```c
/*
 * Start Select mode, if "c" is in 'selectmode' and not in a mapping or menu.
 */
    void
may_start_select(int c)
{
    VIsual_select = (stuff_empty() && typebuf_typed()
		    && (vim_strchr(p_slm, c) != NULL));
}
```

**Comment by brammool** [comment]
Sergey Vlasov wrote:

> ### Steps to reproduce
> 
> 1. Create `~/leftdrag.vim`:
> ```vim
> set selectmode=key,mouse
> 
> function! MyFunc()
> endfunction
> noremap  <LeftDrag> <LeftDrag><Cmd>call MyFunc()<CR>
> noremap! <LeftDrag> <LeftDrag><Cmd>call MyFunc()<CR>
> ```
> 2. Run vim:
> ```sh
> vim --clean -g +'so ~/leftdrag.vim' README.md
> ```
> 3. Do text selection with mouse. Mode shown at the bottom is `-- VISUAL --`.
> 
> ### Expected behaviour
> 
> Mode shown at the bottom is `-- SELECT --`.

This is not specific for <Cmd>, anything that follows <LeftDrag> in the
mapping will make it not work.

Looking at the code, this was done for typed keys, not for mouse events.
I think we can allow for following typeahead when checking for a mouse
event, since they are not in a regular mapping, only intentional.

I can make a patch, but I'll leave it for someone else to make a test,
that is more work.

Without the patch it should also work when you put <LeftDrag> at the end
of the mapping.

-- 
Micro$oft: where do you want to go today?
    Linux: where do you want to go tomorrow?
  FreeBSD: are you guys coming, or what?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
