### ISSUE TITLE
TeX-syntax highlighting interprets regular text as a length

### ISSUE THREAD

**Issue by albinahlback** [vim/vim#10262]
For example, it highlights "3.2 in" in the following code snippet as it interprets this as a length:
```
See for example Proposition~1.3.2 in~\cite{mycite}
```

**Comment by cecamp** [comment]
Since LaTeX is a programmable language, its impossible to get all the places that a texLength is allowed. I also think its important that texLengths be recognized so that an improperly entered length is indicated by the highlighting's absence.

Not liking texLengths, you could put

    syn clear texLength

in a .vim/after/syntax/tex.vim file. Its easier to subtract (clear) than add generally.

**Comment by albinahlback** [comment]
Unfortunately, I do not agree with this solution. My understanding is that Vim's syntax highlighting for LaTeX is made for regular users writing papers/reports/books/whatever, and not made for people programming LaTeX. As these people mainly focus on the content of their paper/report/book, one often resort to using a copy-paste template that is changed only occasionally, my opinion is that `texLength` should be disabled by default.

**Comment by albinahlback** [comment]
What if you define a length as `LENGTH [plus LENGTH] [minus LENGTH]` and only highlight them if they fall into one of the two following scenarios:

- `= LENGTH`
- `{LENGTH}`

Then you would match all of the following expressions:
```latex
\setlength{\parskip}{10pt plus 5pt minus 3pt}
\mylength=1.5in % plain TeX
\includegraphics[width=      4 em]{mygraphic}
\hspace{2 mm}
```
which is plenty. Perhaps I forgot something, but that would certainly include what most regular users do.

**Comment by cecamp** [comment]
Unfortunately this won't work -- the problem is that you'd have patterns depending on the curly/straight braces. Take your example and put it into a *.tex file. You'll see that there is a lot of highlighting of the braces going on. That by itself is not insurmountable, but then there's also folding and error detection (mismatched {] etc). The syntax matcher is a "greedy algorithm", and once a bit of text has been matched is not available for subsequent matching (at the same level -- contained items are at a deeper level).

So, one could do what you suggest, but at the price of mismatched brace flagging and/or folding.

**Comment by albinahlback** [comment]
Thanks for clarifying this!
