### ISSUE TITLE
when verbose ist set, expand('%') fails

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#10307]
### Steps to reproduce

    vim --clean -c 'set verbose=1' -c ':echo expand("%")'

### Expected behaviour

no error message

### Version of Vim

v8.2.4822

### Environment

not relevant

### Logs and stack traces

Okay, this is a bit annoying. I am maintaining a statusline plugin and it makes use of `expand('%')` quite a bit. By accident I noticed today, that Vim starts throwing many errors, once you `:set verbose=1` to the point, that working with Vim is unusable, because of the many errors. 

Note: here is an example that throws errors: 

https://github.com/vim-airline/vim-airline/blob/be5bda1f1dbfa4e36b2adabaf3f423adfa66c336/autoload/airline/extensions.vim#L112-L130

Is there a reason, that `echo expand('%')` should be considered an error? Isn't that perfectly fine for an unnamed buffer to return an empty text? My guess is also, this will affect very many plugins, but this is just a gut feeling. 

Note: offending patch is: https://github.com/vim/vim/commit/575445200bd35283191ecd7a0d596b37c5b477a4

**Comment by lacygoill** [comment]
> Is there a reason, that echo expand('%') should be considered an error?

It all started from [this comment](https://github.com/vim/vim/pull/10121#issuecomment-1094220636).

I wasn't sure whether we should give an error.  If your experience suggests it's too annoying in practice, then maybe it was a bad idea on my part.

**Comment by brammool** [comment]
> > Is there a reason, that echo expand('%') should be considered an error?
> 
> It all started from [this comment](https://github.com/vim/vim/pull/10121#issuecomment-1094220636).
> 
> I wasn't sure whether we should give an error.  If your experience
> suggests it's too annoying in practice, then maybe it was a bad idea
> on my part.

It depends on how you look at it, or where you use it.  In expression
evaluation it's probably fine to deal with an empty file name.  But when
using ":cmd %" it usually results in a wrong result.

I have now changed it for expand() not to give an error for an empty
result.  The test for expand("%:S") failed, because now it returns in a
quoted empty string, instead of just an empty string.  I don't expect
anything to break from this change, but let me know if it does cause a
problem.

-- 
From "know your smileys":
 :^[/   mean-smiley-with-cigarette

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
yes, makes sense, thanks for fixing!
