### ISSUE TITLE
vim9: unexpected "Error detected while compiling"

### ISSUE THREAD

**Issue by errael** [vim/vim#10320]
### Steps to reproduce

The error
```

Error detected while compiling :source buffer=1[18]..function <SNR>37_Bits2Ascii:
line    1:
E1001: Variable not found: mode_chars
```
is generated when the following is sourced.
```
vim9script

const debug = true

if debug
    var mode_chars = ' v!nxsoictl'

    def Bits2Ascii()
        var x = mode_chars
    enddef

# comment out the else block and it works
else
    def Bits2Ascii()
    enddef
endif

defcompile

finish
```

### Expected behaviour

No error

### Version of Vim

8.2.4845

### Environment

ubuntu, gtk3

**Comment by lacygoill** [comment]
The `mode_chars` variable is local to the `if` block where it's declared.  But `:defcompile` is executed outside this block.

You need to either move `:defcompile` inside the block:
```vim
vim9script
const debug = true

if debug
    var mode_chars = ' v!nxsoictl'

    def Bits2Ascii()
        var x = mode_chars
    enddef
    defcompile

 # comment out the else block and it works
else
    def Bits2Ascii()
    enddef
    defcompile
endif

finish
```
*Which IMO is annoying because it's easier and more reliable to write 1 single `:defcompile` at the end of the script, rather than writing one inside each block.*

Or declare the variable at the script level:
```vim
vim9script
const debug = true

var mode_chars: string
if debug
    mode_chars = ' v!nxsoictl'

    def Bits2Ascii()
        var x = mode_chars
    enddef

 # comment out the else block and it works
else
    def Bits2Ascii()
    enddef
endif

defcompile

finish
```
---

That being said, I can see how one would consider this as a bug, because the exact same code does not give any error when it's moved from a script to a function:
```vim
vim9script
def Func()
    const debug = true

    if debug
        var mode_chars = ' v!nxsoictl'

        def Bits2Ascii()
            var x = mode_chars
        enddef

     # comment out the else block and it works
    else
        def Bits2Ascii()
        enddef
    endif

    defcompile
enddef
Func()
```
    no error

I *think* the issue is that at the script level, there is no real block scope.  For example, at the script level, a function is not local to a block:
```vim
vim9script
if true
    def Func()
        echo 'from Func()'
    enddef
endif
Func()
```
    from Func()

In contrast, the same code would give an error when moved inside a function:
```vim
vim9script
def Foo()
    if true
        def Func()
            echo 'from Func()'
        enddef
    endif
    Func()
enddef
Foo()
```
    E117: Unknown function: Func

As an aside, IMO, this behavior is OK.  Making a function local to a block would be too annoying.  For example, here is some code I have in my refactoring of the matchparen plugin:
```vim
vim9script
if has('textprop')

  def RemoveHighlight()
    silent! prop_remove({type: 'matchparen', all: true}, line('w0'), line('w$'))
  enddef

else

  def RemoveHighlight()
    if get(w:, 'matchparen') != 0
      silent! matchdelete(w:matchparen)
      w:matchparen = 0
    endif
  enddef

endif
```
If a function was local to a block at the script level, I would probably need to write this instead:
```vim
vim9script
var RemoveHighlight: func
if has('textprop')

  def RH()
    silent! prop_remove({type: 'matchparen', all: true}, line('w0'), line('w$'))
  enddef
  RemoveHighlight = RH

else

  def RH()
    if get(w:, 'matchparen') != 0
      silent! matchdelete(w:matchparen)
      w:matchparen = 0
    endif
  enddef
  RemoveHighlight = RH

endif
```
Which looks awkward.

Now, back to your issue which is not about a block-local function, but a block-local variable.
At the script level, Vim emulates the block scope by using the script one:
```vim
vim9script
if true
    var n = 0
    echo s:
endif
echo s:
```
    {'n': 0}
    {}

Notice that even though `n` was declared inside a block, it was actually set in the script-local namespace, then automatically removed when the execution moved outside the block.

How does Vim handle the block scope of a variable declared inside a function?  Is it similar to what happens at the script level?  That is, does Vim actually set it in the function-local namespace, then automatically removes it when the execution moves outside the block?  Or is there a real block-local namespace, completely independent from the function-local one?

In the former case, the fact that the original snippet gives an error looks like a bug.  Why should the same mechanism give an error at the script level, but not inside a function?

In the latter case, it might not be a bug.  Although, maybe it could be improved so that the code works consistently across the script level and the body of a function.

**Comment by lacygoill** [comment]
Actually, there is probably a bug, because as you said, no error is given if the `else` block is removed.
```vim
vim9script
const debug = true
if debug
    var mode_chars = ' v!nxsoictl'
    def Bits2Ascii()
        var x = mode_chars
    enddef
endif
Bits2Ascii()
```
Which seems inconsistent.

**Comment by lacygoill** [comment]
> As an aside, IMO, this behavior is OK. Making a function local to a block would be too annoying.

But it is inconsistent.  Not sure what matters most here.  Being consistent or being convenient...

**Comment by errael** [comment]
Yes, tricky.  A language lawyer could take it to the supreme court.

The following works as expected. It seems to come down to the `if | else` as the culprit.
```
vim9script

const debug = true

if debug
    var mode_chars = ' v!nxsoictl'

    def Bits2Ascii()
        var x = mode_chars
        echo 'in true'
    enddef

endif

if !debug
    def Bits2Ascii()
        echo 'in false'
    enddef
endif

Bits2Ascii()
```
