### ISSUE TITLE
Sourcing a `:mksession` file does not respect `set shortmess+=A`

### ISSUE THREAD

**Issue by mawkler** [vim/vim#10443]
### Steps to reproduce

1. Create the following config file `test.vim`:
   ```vim
   set shortmess+=A
   ```
2. `vim --clean`
3. `:w foo.txt`
4. `:mksession session.vim`
5. Keep this `vim` session running and open a new terminal shell instance
6. (in new terminal shell): `vim -u test.vim`
7. `:source session.vim`

Vim gives an error message after sourcing `session.vim`:

```
Error detected while processing [...]session.vim:
line   42:
E325: ATTENTION
Found a swap file by the name ".foo.txt.swp"
[...]
```

### Expected behaviour

Vim respects `shortmess+=A` and does not give an error message.

### Version of Vim

8.2.4827

### Environment

Operating system: Manjaro Linux x86_64
Terminal: kitty 0.25.0
Value of `$TERM`: tmux-256color
Shell: zsh

**Comment by lacygoill** [comment]
I could be wrong, but I think that even without the `options` item in `'sessionoptions'`, `'shortmess'` is still reset in the session script.

---

A similar issue was fixed in patch [8.2.2776](https://github.com/vim/vim/releases/tag/v8.2.2776).

---

[There might be other options](https://github.com/lacygoill/vim-session/blob/a998eeca6ea3f09b8a1b5820c1a36674b399a926/plugin/session.vim#L576-L637) which are also reset/ignored while a session file is sourced.
