### ISSUE TITLE
Vim reports unmatched `if` and `for` after calling function that throws exception

### ISSUE THREAD

**Issue by ddickstein** [vim/vim#10490]
### Steps to reproduce

Create /tmp/foo.vim with the following contents:
```
function! Throw()
  throw "Failure"
endfunction

function! Foo()
  if 1
    call Throw()
  endif
endfunction
```

Open vim, source /tmp/foo.vim, and then `:call Foo()`. It displays:

```
Error detected while processing function Foo[2]..Throw[1]..function Foo[2]..Throw:
line    1:
E605: Exception not caught: Failure
Error detected while processing function Foo:
line    2:
E171: Missing :endif
```

### Expected behaviour

Errors 170 and 171 are expected in these kinds of situations - because an exception is raised inside the body of a condition or a loop, we don't expect to ever see the end[if/while/for] keyword. Displaying these errors creates a lot of clutter, and doesn't add any informational value. They should be suppressed.

### Version of Vim

8.2.5000

### Environment

Operating System: MacOS 11.5.1
Terminal: iTerm2 3.4.15
Value of $TERM: tmux-256color
Shell: GNU bash, version 5.1.8(1)-release

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Create /tmp/foo.vim with the following contents:
> ```
> function! Throw()
>   throw "Failure"
> endfunction
> 
> function! Foo()
>   if 1
>     call Throw()
>   endif
> endfunction
> ```
> 
> Open vim, source /tmp/foo.vim, and then `:call Foo()`. It displays:
> 
> ```
> Error detected while processing function Foo[2]..Throw[1]..function Foo[2]..Throw:
> line    1:
> E605: Exception not caught: Failure
> Error detected while processing function Foo:
> line    2:
> E171: Missing :endif
> ```
> 
> ### Expected behaviour
> 
> Errors 170 and 171 are expected in these kinds of situations - because
> an exception is raised inside the body of a condition or a loop, we
> don't expect to ever see the end[if/while/for] keyword. Displaying
> these errors creates a lot of clutter, and doesn't add any
> informational value. They should be suppressed.

I think this has been happening for as long as we have exceptions.
I first thought it was going to be difficult to change without breaking
other behavior, but it turns out to be quite simple.  At least all tests
still pass, and since exceptions are quite well tested the fix should be
fine.

-- 
Not too long ago, a program was something you watched on TV...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
