### ISSUE TITLE
No highlight for StatusLineTermNC in doc/syntax.txt

### ISSUE THREAD

**Issue by jdjohnston** [vim/vim#10540]
`:help hl-StatusLineTermNC`
Unlike the other highlight groups, this one isn't highlighted. That's because the group name, `StatusLineTermNC`, is directly followed by spaces rather than a tab.

To highlight the group name, either the text needs to be changed to use a tab or the `matchstr()` in `vimhelp.HighlightGroups()` (in `import/dist/vimhelp.vim`) should be changed from `^\w\+\ze\t` to `^\w\+\ze\s`. Changing the regexp is simpler and would make it less sensitive to the format of `doc/syntax.txt` .

Thanks for Vim! I've been using it for over 25 years.

**Comment by brammool** [comment]
I'll change it to match spaces too.  Let me know if it then matches in too many places.

**Comment by lacygoill** [comment]
> It wrongly matches the statusline word on line 5422. A better fix would be to replace the spaces with a tab:

Another possible fix would be to match a tag on the previous line.  But then we would lose the highlighting on `lCursor` because the latter is not preceded by a tag.  So, we would need to either look further back (how far?), or match a `help-hl-*` text property on the previous line.  That seems too complicated.  Being consistent and using a tab between a highlight group name followed and its description is much simpler.

---

   > That's because match() is sensitive to the 'ignorecase' option. Patch fixing the issue:

Actually, using `index()` seems better than `match()` (which is also what I'm currently using):
```diff
diff --git a/runtime/import/dist/vimhelp.vim b/runtime/import/dist/vimhelp.vim
index e0afd1f97..4654bcaba 100644
--- a/runtime/import/dist/vimhelp.vim
+++ b/runtime/import/dist/vimhelp.vim
@@ -10,7 +10,7 @@ export def HighlightGroups()
     var word: string = getline(lnum)->matchstr('^\w\+\ze\s')
     if word->hlexists()
       var name = 'help-hl-' .. word
-      if prop_type_list({bufnr: buf})->match(name) == -1
+      if prop_type_list({bufnr: buf})->index(name) == -1
 	prop_type_add('help-hl-' .. word, {
 	  bufnr: buf,
 	  highlight: word,
```

**Comment by brammool** [comment]
> > Let me know if it then matches in too many places.
> 
> It wrongly matches the `statusline` word on line 5422.  A better fix
> would be to replace the spaces with a tab:

[...]

> The alignment of the description is already currently broken.  So,
> using a tab or spaces does not matter; consistency seems more
> important.

I see, with any white space it would match in too many places.

> A recent refactoring must have introduced a bug:
> 
>     $ vim -Nu NONE +'set ignorecase | syntax on | help syntax'
>     E971: Property type help-hl-statusline does not exist
> 
> That's because `match()` is sensitive to the `'ignorecase'` option.
> Patch fixing the issue:

I could not reproduce the problem, but since syntax groups are case
insensitive this won't hurt.

> Computing `line('$')` on each iteration is inefficient, because the
> last line is not going to change between 2 iterations:

It should not make much difference.  It would actually help more to stop
below the section.  We can search for the start of the next section,
":highlight-link".  Requires saving and restoring the cursor.

> Writing `'help-hl-' .. word` 3 times creates code duplication (and
> `type` is a better name than `name`, because it's more specific):

OK.

> The `if word->hlexists()` block is too long, and causes most of the
> indentation of the loop to be increased by 1 level.  Inverting the
> test and using a `continue` would let us shorten the block, reducing
> the indentation of most the loop, which makes the code more readable:

Others object to using "continue".  Let's just leave it.

> Using a `:while` loop forces us to handle `lnum` manually.  A `:for`
> loop would do it for free:

That also searches for the end, as I mentioned above.
I do think the cursor position needs to be restored.

> `prop_add()` can currently be called after a `prop_remove()`.  Not
> sure why.  If the property does not exist, an error will probably be
> given.
> 
>       else
> 	# was called before, delete existing properties
> 	prop_remove({type: name, bufnr: buf})
>       endif
>       prop_add(lnum, 1, {length: word->strlen(), type: 'help-hl-' .. word})

You mention "changing the color scheme".  When that happens the property
highlight needs to be changed, thus the type needs to be deleted and
created again.

The result I have now:

```
vim9script

# Extra functionality for displaying Vim help .

# Called when editing the doc/syntax.txt file
export def HighlightGroups()
  var save_cursor = getcurpos()
  var buf: number = bufnr('%')

  var start: number = search('\*highlight-groups\*', 'c')
  var end: number = search('^======')
  for lnum in range(start, end)
    var word: string = getline(lnum)->matchstr('^\w\+\ze\t')
    if word->hlexists()
      var type = 'help-hl-' .. word
      if prop_type_list({bufnr: buf})->match('\C' .. type) != -1
	# was called before, delete existing properties
	prop_remove({type: type, bufnr: buf})
	prop_type_delete(type, {bufnr: buf})
      endif
      prop_type_add(type, {
	bufnr: buf,
	highlight: word,
	combine: false,
	})
      prop_add(lnum, 1, {length: word->strlen(), type: type})
    endif
  endfor

  setpos('.', save_cursor)
enddef
```

-- 
Veni, Vidi, VW -- I came, I saw, I drove around in a little car.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> That also searches for the end, as I mentioned above.
> I do think the cursor position needs to be restored.

We can avoid moving the cursor by:

   - passing the `n` flag to `search()`
   - using the `\%>123l` regex atom, where `123` is `start`

```diff
diff --git a/tmp/t.vim b/tmp/new.vim
index 0ec6fe2..8ce7d21 100644
--- a/tmp/t.vim
+++ b/tmp/new.vim
@@ -7,8 +7,8 @@ export def HighlightGroups()
   var save_cursor = getcurpos()
   var buf: number = bufnr('%')
 
-  var start: number = search('\*highlight-groups\*', 'c')
-  var end: number = search('^======')
+  var start: number = search('\*highlight-groups\*', 'cn')
+  var end: number = search($'^\%>{start}l======', 'n')
   for lnum in range(start, end)
     var word: string = getline(lnum)->matchstr('^\w\+\ze\t')
     if word->hlexists()
@@ -26,6 +26,4 @@ export def HighlightGroups()
       prop_add(lnum, 1, {length: word->strlen(), type: type})
     endif
   endfor
-
-  setpos('.', save_cursor)
 enddef
```
---

> The result I have now:

This looks good.  I would just replace `match()` with `index()`, because the latter is immune to `'ignorecase'` by default.  Also, it's probably more reliable because it doesn't try to match a regex; it just looks for a literal text, which is what we want here.

**Comment by brammool** [comment]
> > That also searches for the end, as I mentioned above.
> > I do think the cursor position needs to be restored.
> 
> We can avoid moving the cursor by:
> 
>    - passing the `n` flag to `search()`
>    - using the `\%>123l` regex atom, where `123` is `start`

Then it searches all the text above again.  Starting at the match with
the header avoids that.


-- 
VOICE OVER: As the horrendous Black Beast lunged forward, escape for Arthur
            and his knights seemed hopeless,  when, suddenly ... the animator
            suffered a fatal heart attack.
ANIMATOR:   Aaaaagh!
VOICE OVER: The cartoon peril was no more ... The Quest for Holy Grail could
            continue.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Then it searches all the text above again.

Not sure what it means.  Maybe it's less efficient, but it does work, and has no side-effect.  Anyway, if we keep moving the cursor, then `getcurpos()` and `setpos()` are probably not good enough, because they don't necessarily restore the topline.  `winsaveview()` and `winrestview()` would be better:
```diff
diff --git a/tmp/old.vim b/tmp/new.vim
index a927e76..7e7fbbc 100644
--- a/tmp/old.vim
+++ b/tmp/new.vim
@@ -4,7 +4,7 @@ vim9script
 
 # Called when editing the doc/syntax.txt file
 export def HighlightGroups()
-  var save_cursor = getcurpos()
+  var view: dict<number> = winsaveview()
   var buf: number = bufnr('%')
 
   var start: number = search('\*highlight-groups\*', 'c')
@@ -27,5 +27,5 @@ export def HighlightGroups()
     endif
   endfor
 
-  setpos('.', save_cursor)
+  winrestview(view)
 enddef
```

**Comment by brammool** [comment]
> > Then it searches all the text above again.
> 
> Not sure what it means.  Maybe it's less efficient, but it does work,
> and has no side-effect.  Anyway, if we keep moving the cursor, then
> `getcurpos()` and `setpos()` are probably not good enough, because
> they don't necessarily restore the topline.  `winsaveview()` and
> `winrestview()` would be better:

I do not think that is necessary, this all happens before the first
redraw.  The cursor is likely on the first line and might be moved soon
too (to jump to the help tag).

-- 
Permission is granted to read this message out aloud on Kings Cross Road,
London, under the condition that the orator is properly dressed.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
