### ISSUE TITLE
Is there Vim whose command can be customized

### ISSUE THREAD

**Issue by abdulbadii** [vim/vim#10554]
Is there a Vim release whose command can be customized by use of Vim itself or other executable tool e.g.
change

`:q `
become `: <ESC key press>` or `:K` 

Thanks before

**Comment by lacygoill** [comment]
Maybe you could try an abbrevation:

    cnoreabbrev <expr> q getcmdtype() == ':' && getcmdpos() == len('q') + 1 ? 'K' : 'q'

---

For more info, see:

   - [`:help :cnoreabbrev`](https://vimhelp.org/map.txt.html#%3Acnoreabbrev)
   - [`:help :map-expression`](https://vimhelp.org/map.txt.html#%3Amap-expression)
   - [`:help getcmdtype()`](https://vimhelp.org/builtin.txt.html#getcmdtype%28%29)
   - [`:help getcmdpos()`](https://vimhelp.org/builtin.txt.html#getcmdpos%28%29)
   - [`:help len()`](https://vimhelp.org/builtin.txt.html#len%28%29)

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by matveyt** [comment]
The commands in Vim are divided into two parts: builtin commands (start with lower case letter) and user commands (start with upper case). The user commands may be (re, un)defined freely. The builtin commands not.

There are some tricks however. With command-line input, as mentioned above, or with auto-commands. E.g. instead of overwriting builtin `quit` command you may choose to do something useful during, say, `QuitPre` event. And this would work also for `ZZ` or `ZQ` and such.

**Comment by abdulbadii** [comment]
Thanks so much, indeed useful, appreciated.
