### ISSUE TITLE
<Esc> from a Visual mode mapping cannot stop Select mode

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10572]
### Steps to reproduce

1. Run `vim --clean`
2. Run `:vnoremap <C-K> <Esc>`
3. Type `gh<C-K>`
4. Select mode is not stopped

### Expected behaviour

Select mode is stopped

### Version of Vim

8.2.5046

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
This change seems to fix the problem:
```diff
diff --git a/src/normal.c b/src/normal.c
index fdbc5c838..b1521ee32 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -6814,10 +6814,9 @@ nv_esc(cmdarg_T *cap)
 
     if (VIsual_active)
     {
-	end_visual_mode();	// stop Visual
+	reset_VIsual();		// stop Visual
 	check_cursor_col();	// make sure cursor is not beyond EOL
 	curwin->w_set_curswant = TRUE;
-	redraw_curbuf_later(INVERTED);
     }
     else if (no_reason)
 	vim_beep(BO_ESC);
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Run `:vnoremap <C-K> <Esc>`
> 3. Type `gh<C-K>`
> 4. Select mode is not stopped
> 
> ### Expected behaviour
> 
> Select mode is stopped

This happens because of using a :vnoremap command.  In Select mode this
goes to Visual mode, executes the mapping, and restores Select mode.
You should use ":snoremap".

I wonder if your suggested change would cause a problem for some
mappings.  It depends on how users interpret the remarks about how
:vmap mappings work in Select mode.

-- 
A special cleaning ordinance bans housewives from hiding dirt and dust under a
rug in a dwelling.
		[real standing law in Pennsylvania, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
Since changing this may cause problems, it's better to keep this and use a Select mode mapping instead.

**Comment by zeertzjq** [comment]
I just noticed appending `gV` to the mapping is the correct way to do this.
