### ISSUE TITLE
msgfmt stopped working with MSVC

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#10590]
### Steps to reproduce

1. Install gettext and adjust `GETTEXT_PATH`.
2. Build the .mo files:
    ```
    cd po
    nmake -f Make_mvc.mak install-all
    ```
3. Raise your eyebrow at the error that appears.

### Expected behaviour

.mo files are generated. (Note that building Vim itself works just fine.)

### Version of Vim

8.2.5125

### Environment

OS: Windows 10
Terminal: PowerShell
MSVC: Visual Studio 2019, all updates

### Logs and stack traces

```shell
Microsoft (R) Program Maintenance Utility, Version 14.29.30141.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

        set OLD_PO_FILE_INPUT=yes
        "C:\Program Files (x86)\GnuWin32\bin\msgfmt" -v -o af.mo af.po
NMAKE : fatal error U1077: ""C:\Program Files (x86)\GnuWin32\bin\msgfmt.EXE"": Rückgabe-Code "0xc0000
135"
Stop.
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Install gettext and adjust `GETTEXT_PATH`.
> 2. Build the .mo files:
>     ```
>     cd po
>     nmake -f Make_mvc.mak install-all
>     ```
> 3. Raise your eyebrow at the error that appears.
> 
> ### Expected behaviour
> 
> .mo files are generated. (Note that building Vim itself works just fine.)
> 
> ### Version of Vim
> 
> 8.2.5125
> 
> ### Environment
> 
> OS: Windows 10
> Terminal: PowerShell
> MSVC: Visual Studio 2019, all updates
> 
> ### Logs and stack traces
> 
> ```shell
> Microsoft (R) Program Maintenance Utility, Version 14.29.30141.0
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
>         set OLD_PO_FILE_INPUT=yes
>         "C:\Program Files (x86)\GnuWin32\bin\msgfmt" -v -o af.mo af.po
> NMAKE : fatal error U1077: ""C:\Program Files (x86)\GnuWin32\bin\msgfmt.EXE"": Rückgabe-Code "0xc0000
> 135"
> Stop.
> ```

Hmm, that doesn't tell us much.  Is that just because af.po happens to
be the first one, or because the c-format lines were removed?

Can anyone reproduce this problem?

-- 
Looking at Perl through Lisp glasses, Perl looks atrocious.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dertuxmalwieder** [comment]
I found the problem: It looks like my installation of msgfmt (GnuWin32) came without two required DLLs. Installing libintl from the same project fixed it. Sorry for the inconveniences!
