### ISSUE TITLE
Unexpected behavior?

### ISSUE THREAD

**Issue by pierreganty** [vim/vim#10693]
### Steps to reproduce

Running `vim --noplugin -n`
with input
```
R
<C-o>
c
:w bla
```
vim ends up in `Insert mode`.
However with the input
```
R
<C-o>
:w bla
```
vim ends up in `Replace mode`.

Remark that playing the first sequence twice (once before the creation of `bla` and once after) the second time around ends up in `Replace mode` (after some message that the file `bla` already exists).

### Expected behaviour

I cannot explain the difference in mode reached after inputting the two sequence

### Version of Vim

8.2.4113

### Environment

MacOS 12.4
Terminal.app
xterm-256color
zsh

**Comment by lacygoill** [comment]
> I cannot explain the difference in mode reached after inputting the two sequence

`c` is an operator.  It expects a text-object or a motion as an operand.  You provide this Ex command as an operand:

    :w bla

The result is that `c` deletes the text from the current cursor position up to whatever new position the cursor occupies after the Ex command has finished its execution.  And then, `c` enters insert mode.  And then, it waits to let you insert some text.  Only once you've finally escaped back to normal mode is the operation completed. Otherwise, the dot command would not work as you probably expect; i.e. it would not repeat the insertion of the text.

Now, by itself, `:w bla<CR>` does not change the cursor position.  So, your `c` does not delete anything; but it still enters insert mode and wait to let you insert something.  That's why you end up in insert mode.

IOW, this is a complete operation:

    :w bla
    <Enter>

And this one too:

    c
    :w bla
    <Enter>
    <Escape>

And this one too:

    c
    :w bla
    <Enter>
    some inserted text
    <Escape>

But not this one:

    c
    :w bla
    <Enter>

a   > I cannot explain the difference in mode reached after inputting the two sequence

`c` is an operator.  It expects a text-object or a motion as an operand.  You provide this Ex command as an operand:

    :w bla

The result is that `c` deletes the text from the current cursor position up to whatever new position the cursor occupies after the Ex command has finished its execution.  And then, `c` enters insert mode.  And then, it waits to let you insert some text.  Only once you've finally escaped back to normal mode is the operation completed. Otherwise, the dot command would not work as you probably expect; i.e. it would not repeat the insertion of the text.

Now, by itself, `:w bla<CR>` does not change the cursor position.  So, your `c` does not delete anything; but it still enters insert mode and wait to let you insert something.  That's why you end up in insert mode.

IOW, this is a complete operation:

    :w bla
    <Enter>

And this one too:

    c
    :w bla
    <Enter>
    <Esc>

And this one too:

    c
    :w bla
    <Enter>
    some inserted text
    <Esc>

But not this one:

    c
    :w bla
    <Enter>

Because `<Esc>` is missing.

**Comment by lacygoill** [comment]
> vim ends in a different mode whether or not the file bla exists when executing the following sequence

When the file exists, `:w` fails to overwrite it (assuming you re-type the exact same command; i.e. you don't append a bang).  `c` was waiting for this command to make the cursor move, and use the latter's new position.  But you've executed a command which fails, so the new cursor position is irrelevant.  You can observe the same behavior like this:

    $ vim -Nu NONE
    c
    /
    ^
    <CR>
    # you're in insert mode

    $ vim -Nu NONE
    c
    /
    nothing
    <CR>
    # you're in normal mode

Depending on whether or not the search succeeds, you end up in different modes.

When you provide an invalid operand, the whole operation fails.  And `<C-O>` only lets you enter normal mode for 1 single command.  There's nothing at [`:help i_CTRL-O`](https://vimhelp.org/insert.txt.html#i_CTRL-O) which suggests that this command must be valid.  And you did provide one (although an invalid one).  So, `<C-O>` is not waiting to give you yet another try, and returns to replace mode.

**Comment by pierreganty** [comment]
Thank you very much. I am thus closing the issue.
