### ISSUE TITLE
Text property columns are not counted in characters

### ISSUE THREAD

**Issue by noscript** [vim/vim#10731]
### Steps to reproduce

When property column range includes the first byte, then the character is colored. When first byte is not included, nothing is colored. This behavior is not useful.

`prop_add()` and `prop_add_list()` should count columns in displayed characters and not bytes. In case of multi-byte characters, setting property to a portion of a character doesn't make sense.

When delivering text properties from external tools (e.g. a shell script), counting column in characters is a zero effort. However counting those in bytes is unjustifiable and almost impossible to do. Recalculating byte offsets in Vim script is a serious bottleneck, as it has to be done for each property.

1. Run vim:
```sh
STR="Hello"
START_COL=1
END_COL=3
echo "$STR" | vim -g --clean +"call prop_type_add('char', {'highlight': 'Error'})" +"call prop_add(1, $START_COL, {'end_lnum': 1, 'end_col': $END_COL, 'type': 'char'})" -
```
Two first characters are colored, as expected.
![image](https://user-images.githubusercontent.com/717109/178514589-6646ad7b-c07e-4a6d-a216-4abf8430f110.png)
2. Change `STR` to multi-byte character string:
```sh
STR="君が代"
START_COL=1
END_COL=3
echo "$STR" | vim -g --clean +"call prop_type_add('char', {'highlight': 'Error'})" +"call prop_add(1, $START_COL, {'end_lnum': 1, 'end_col': $END_COL, 'type': 'char'})" -
```
Only the first character is colored. Expected: two first characters to be colored.
![image](https://user-images.githubusercontent.com/717109/178514818-9d21aa65-7247-4f15-974a-25f438e4d060.png)
3. Change `START_COL` to `2`:
```sh
STR="君が代"
START_COL=2
END_COL=3
echo "$STR" | vim -g --clean +"call prop_type_add('char', {'highlight': 'Error'})" +"call prop_add(1, $START_COL, {'end_lnum': 1, 'end_col': $END_COL, 'type': 'char'})" -
```
Nothing is colored at all. Expected: the second character is colored.
![image](https://user-images.githubusercontent.com/717109/178516141-1330e3c4-c008-44b1-80a4-7c944f52d21a.png)

### Expected behaviour

Characters are colored, as if columns are calculated in characters and not byte index.

### Version of Vim

9.0.0035

### Environment

OS: Debian 11
Terminal: GUI

**Comment by bfrg** [comment]
You can convert to from character indexes to byte indexes with `byteidx({string}, {nr})`.

**Comment by noscript** [comment]
I made a simple benchmark to see how much extra time it takes to convert columns to byte indexes.

As I mentioned in the original post, the external tool returns columns counted in characters, so this is simulated in the benchmark. Then the correction is done with `byteidx()`, as suggested.

This will downloads Japanese translation of `options.txt` from https://github.com/vim-jp/vimdoc-ja-working and set properties to the whole lines.

```sh
vim -g --clean -S <(tee <<'EOF'
    vim9script

    # generate props (simulates the props received from external tool):
    enew
    execute ':%!wget https://raw.githubusercontent.com/vim-jp/vimdoc-ja-working/master/doc/options.jax -q -O -'
    var props = []
    for lnum in range(1, line('$'))
      var line = getline(lnum)
      if empty(line)
        continue
      endif
      props += [[lnum, 1, lnum, line->strchars() + 1]]
    endfor

    # correct byte offset:
    var start1 = reltime()
    for prop in props
      prop[3] = getline(prop[0])->byteidx(prop[3] - 1) + 1
    endfor
    var end1 = reltimestr(reltime(start1))->str2float()

    # add props to buffer:
    prop_type_add('my_prop', {'highlight': 'Error'})
    var start2 = reltime()
    prop_add_list({type: 'my_prop'}, props)
    var end2 = reltimestr(reltime(start2))->str2float()

    echo 'ratio' end1 / end2
EOF
)
```
I get a ratio between 17 and 22. If my math is correct, correcting the columns in vim script adds up additional ~2000% of execution time, comparing to `prop_add_list()` alone. Which is expected.

**Comment by bfrg** [comment]
I think this issue should probably be labeled as an enhancement and not a bug.

**Comment by brammool** [comment]
The property is stored using byte offsets, since recomputing character
offsets is not cheap.

There already are several functions to convert between byte and
character offsets.  Can we use the Unix principle of splitting a task
into smaller pieces, instead of adding byte/character option flags
everywhere?  Many functions work with byte offsets anyway.


-- 
Bare feet magnetize sharp metal objects so they point upward from the
floor -- especially in the dark.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by noscript** [comment]
Computing offsets for a few properties in vim script is not a problem, but doing it for a lot of properties (hundreds or more) has a big overhead. It could be beneficial to do the work inside `prop_add_list()`.

**Comment by noscript** [comment]
I checked, indeed many tools report columns in byte offsets. So I should probably fix my other tools to also count in bytes.

Feel free to close this, if there are no plans to support character columns in `prop_add_list()`.

**Comment by brammool** [comment]
If you use a :def function I would think it is fast enough.  It avoids most of the overhead involved in calling a function.
The computation from character to byte offset itself requires going through the text, that by itself takes a bit of time, no matter if it's done before calling prop_add_list() or inside it.  As mentioned already, the byte offset is stored, so that operations like inserting and deleting text work well.  Storing the character offset would result in doing the computation several times.
