### ISSUE TITLE
Wrong output by :file after moving current file using :!mv

### ISSUE THREAD

**Issue by inPhraZ** [vim/vim#10740]
### Steps to reproduce

1. :!mv /path/to/current-file-name  /path/to/newfilename
2. :file  or :echo @%

OR
1. :!rename current-filename new-filename *
2. :file or :echo @%

### Expected behaviour

After renaming current file using :!mv or :!rename commands, I expect that :file to show new name of the file. But :file still shows the previous name of the file.

### Version of Vim

9.0

### Environment

Operating system: archlinux-2021.09.01
Terminal: xfce4-terminal 1.0.4
Value of $TERM: xterm-256color
Shell: bash 5.1.16

**Comment by lacygoill** [comment]
When I execute `:!mv ...` like this:

    $ mkdir -p /tmp/path/to
    $ echo 'some text' >/tmp/path/to/current-file-name
    $ vim -Nu NONE /tmp/path/to/current-file-name
    :!mv /tmp/path/to/current-file-name /tmp/path/to/newfilename

I get this error:

    E211: File "/tmp/path/to/current-file-name" no longer available

Vim complains that the file from which the current buffer was read no longer exists.  Which is why reloading the buffer with `:edit` makes it empty; because from Vim's point of view, there is no file to read anymore.

`:!` is a Vim command which can be used to execute an arbitrary shell command, which can move the file wherever it wants.  I don't think Vim can know where it was moved.

---

You might be interested in the [`:Rename`](https://github.com/tpope/vim-eunuch/blob/master/doc/eunuch.txt#L39-L41) command provided by the [vim-eunuch](https://github.com/tpope/vim-eunuch) plugin.

**Comment by inPhraZ** [comment]
Thank You @lacygoill
