### ISSUE TITLE
cmdline window falls back with E11

### ISSUE THREAD

**Issue by octaltree** [vim/vim#10756]
### Steps to reproduce

./vim -u min.vim

```vim
nnoremap ; q:a
```

Type `;` twice in v8.2.5043 or later.

I get the error message.
>E11: Invalid in command-line window; <CR> executes, CTRL-C quits

### Expected behaviour

I like the cmdline window because it can be operated like a normal buffer.
I like the behavior of "silently" falling back to cmdline when `q:a` was executed twice.

```vim
nnoremap ; q:a
nnoremap : ;
nnoremap q; :
nnoremap / q/a
nnoremap q/ /
nnoremap ? q?a
nnoremap q? ?
vnoremap ; q:a
vnoremap : ;
```
Is this a spec and has it been buggy so far?

### Version of Vim

v9.0.0055

### Environment

Linux coorie 5.10.129-1-MANJARO #1 SMP PREEMPT Thu Jul 7 16:56:51 UTC 2022 x86_64 GNU/Linux
alacritty 0.11.0-dev (2a676dfa)
tmux 3.3a
tmux-256color
zsh 5.9 (x86_64-pc-linux-gnu)

### Logs and stack traces

```shell
I did a binary search and found that there was a change in patch 5043.
v8.2.4113 No error display
v8.2.4642 No error display
v8.2.4907 No error display
v8.2.5039 No error display
v8.2.5042 No error display
v8.2.5043 E11
v8.2.5047 E11
v8.2.5055 E11
v8.2.5072 E11
v8.2.5105 E11
v8.2.5172 E11
v9.0.0055 E11
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ./vim -u min.vim
> 
> ```vim
> nnoremap ; q:a
> ```
> 
> Type `;` twice in v8.2.5043 or later.
> 
> I get the error message.
> >E11: Invalid in command-line window; <CR> executes, CTRL-C quits

I just get the semicolon inserted.  Which is logical, since after the
first ";" Vim is in Insert mode.

> ### Expected behaviour
> 
> I like the cmdline window because it can be operated like a normal buffer.
> I like the behavior of silently falling back to cmdline when `q:a` was
> executed twice.

You will have to use an Insert mode mapping for that.

-- 
hundred-and-one symptoms of being an internet addict:
95. Only communication in your household is through email.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by octaltree** [comment]
I made a mistake. min.vim is correct, my intended operation is `;<esc>;`.
