### ISSUE TITLE
`expand("%")` returns incorrect value when a file is opened using `:edit {full-path}`

### ISSUE THREAD

**Issue by waivek** [vim/vim#10850]
### Steps to reproduce

1. Create a directory `~/temp`
2. Set this as the working directory via `:cd ~/temp`
3. Open a file with the command `:e file_1.txt`
4. `:echo expand("%")` returns the correct value here, `"file_1.txt"`
5. Open another file with the command `:e ~/temp/file_2.txt`
6. `:echo expand("%")` returns the incorrect value here. Instead of `"file_2.txt"`, it returns the absolute path.
7. If we run `:cd .`, then `:echo expand("%")` returns the correct relative path of `"file_2.txt"`

### Expected behaviour

Doing `:cd .` should not be required to get the correct value from `expand("%")`.

### Version of Vim

8.2.4212

### Environment

Operating System: Windows 10
gvim

**Comment by brammool** [comment]
This is not a bug, expand("%") returns the file name as it was entered.
I can't think of a simple way to get the shorter name.  Do we need it?

**Comment by waivek** [comment]
If it's the intended behavior, I'll close the issue. 

Why does `cd .` change the value of `expand("%")`, even when the working directory doesn't change?

**Comment by brammool** [comment]
> If it's the intended behavior, I'll close the issue. 
> 
> Why does `cd .` change the value of `expand("%")`, even when the
> working directory doesn't change?

Any "cd" command will adjust the short filenames to make them work for
the (new or not) current directory.  It can also be used to shorten the
names with "cd .", as you noticed.

-- 
Emacs is a nice OS - but it lacks a good text editor.
That's why I am using Vim.  --Anonymous

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
