### ISSUE TITLE
Virtual text disappears when joining lines

### ISSUE THREAD

**Issue by bfrg** [vim/vim#10858]
### Steps to reproduce

1. Run `vim --clean -S test.vim`, with
```vim
vim9script
edit foobar
setline(1, ['one', 'two'])
prop_type_add('test', {highlight: 'Special'})
prop_add(1, 0, {
    type: 'test',
    text: 'the quick brown fox jumps over the lazy dog',
    text_align: 'below'
})
```
2. Join the first and second line by pressing `J`.
3. Result: virtual text below the first line disappeared. 
4. After `:undo`, virtual text appears again.

### Expected behaviour

Virtual text should not disappear when joining lines.

### Version of Vim

9.0.151

### Environment

Linux

**Comment by brammool** [comment]
This is intentional.  The virtual text appears after the first line.  When joining lines, there is no "after the first line" anymore.
It's like the two lines get squashed together, and what was in between the lines disappears.
Only virtual text after the second line is kept.

Perhaps there are situations when keeping the text property is better, it's hard to decide.
