### ISSUE TITLE
Window layout is unstable after shrinking the only window

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10890]
### Steps to reproduce

First problem:
1. Run `vim --clean`
2. Run `:set laststatus=2`
3. Run `resize -5`
4. The statusline moves up 5 rows
5. Now increasing `'cmdheight'` causes two statuslines to be shown, and setting `'showtabline'` causes statusline to move back.

### Expected behaviour

Increasing `'cmdheight'` should not cause two statuslines to be shown, and setting `'showtabline'` should not affect where statusline is displayed.

Patch 9.0.0114 "fixed" this problem. This problem is present again after patch 9.0.0187.

### Version of Vim

9.0.0000 or 9.0.0189

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by brammool** [comment]
For some time it was possible to make the command line height zero by making the last window very tall.  That is not right, the command height must only be made zero when the user explicitly sets 'cmdheight' to zero.  Otherwise this may happen accidentally.  Setting 'cmdheight' to zero has some serious implications, thus we should not make it easy.
I'll see if I can make this happen and fix the bug of the double status line.
