### ISSUE TITLE
MatchParen highlighting applied to virtual text at position of matching parens

### ISSUE THREAD

**Issue by puremourning** [vim/vim#10892]
### Steps to reproduce

```viml
hi MatchParen ctermbg=blue guibg=lightblue
runtime! plugin/**/matchparen.vim
call prop_type_add( 'prop', #{ highlight: 'Comment' } )
call prop_add( 3, 19, #{ type: 'prop', text: 'ProperProperty' } )
call cursor( 3, 55 )
```

See that the text `ProperProperty` has the "blue" background, not just the `(`

### Expected behaviour

Just the `(` is highlighted by MatchParen.

I think that perhaps more generally, `matchaddpos` should _not_ apply to the virtual text at that location, as virtual text has its own highlight, but I confess it's not clear cut.

### Version of Vim

9.0.189

### Environment

macOS arm64

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```viml
> hi MatchParen ctermbg=blue guibg=lightblue
> runtime! plugin/**/matchparen.vim
> call prop_type_add( 'prop', #{ highlight: 'Comment' } )
> call prop_add( 3, 19, #{ type: 'prop', text: 'ProperProperty' } )
> call cursor( 3, 55 )
> ```
> 
> See that the text `ProperProperty` has the "blue" background, not just
> the `(`

Also, the search highlight applies to the virtual text.  That seems
wrong, since that text isn't really matched by the search pattern.

> I think that perhaps more generally, `matchaddpos` should _not_ apply
> to the virtual text at that location, as virtual text has its own
> highlight, but I confess it's not clear cut.

I do think that the virtual text highlight should not be overruled by
match or search highlighting.

-- 
   GALAHAD hurries to the door and pushes through it.  As he leaves the room
   we CUT TO the reverse to show that he is now in a room full of bathing
   and romping GIRLIES, all innocent, wide-eyed and beautiful.  They smile
   enchantingly at him as he tries to keep walking without being diverted by
   the lovely sights assaulting his eyeballs.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
