### ISSUE TITLE
In terminal Vim, `execute()` does not capture the output of `:write_c`

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#10900]
### Steps to reproduce

```
vim --clean -c 'call setline(1, "asdf")' -c 'echom execute("w !cat") =~ "asdf"'
```
It prints `0` to `:mess`.

### Expected behaviour

`1` should be printed. That is, `execute("w !cat")` should capture the output `"asdf"`. GVim and Neovim work as expected.

### Version of Vim

9.0.0150

### Environment

* Ubuntu 22.04
* GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD
* $TERM: tmux-256color
* shell: bash

**Comment by brammool** [comment]
This is to be expected.  execute() returns the output of the Vim command, but the "!cat" will invoke a shell to execute "cat" and the output goes to stdout, not to Vim.  Thus it goes to the terminal.
To capture the output of a shell command use system().
In gvim it works, because the shell output is captured to be able to display it in the Vim window.

**Comment by tomtomjhj** [comment]
Understood. Thanks!
