### ISSUE TITLE
Cursor position incorrect when virtual text added to current line in timer callback

### ISSUE THREAD

**Issue by puremourning** [vim/vim#10905]
### Steps to reproduce

```viml
vim9script

prop_type_add( 'prop', { highlight: 'Comment' } )
cursor( 4, 7 )
timer_start( 10, ( id ) => {
  prop_add( 4, 1, { type: 'prop', 'text': 'moveit' } )
} )
```

* `vim --clean -S test.vim test.vim`
* see that the cursor is positioned immediately after the now-added text property
* `l` - move one character to the right
* see that the cursor jumps len( 'moveit' ) + 1 chars.

### Expected behaviour

Cursor is moved when text property is added (i.e. it remains on the `(` after `cursor`

### Version of Vim

9.0.193

### Environment

macOS arm64

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```viml
> vim9script
> 
> prop_type_add( 'prop', { highlight: 'Comment' } )
> cursor( 4, 7 )
> timer_start( 10, ( id ) => {
>   prop_add( 4, 1, { type: 'prop', 'text': 'moveit' } )
> } )
> ```
> 
> * `vim --clean -S test.vim test.vim`
> * see that the cursor is positioned immediately after the now-added text property
> * `l` - move one character to the right
> * see that the cursor jumps len( 'moveit' ) + 1 chars.
> 
> ### Expected behaviour
> 
> Cursor is moved when text property is added (i.e. it remains on the `(` after `cursor`
> 
> ### Version of Vim
> 
> 9.0.193

I cannot reproduce this problem.  I assume it was fixed with patch
9.0.0194.

-- 
You were lucky. We lived for three months in a brown paper bag in a 
septic tank. We used to have to get up at six o'clock in the morning, 
clean the bag, eat a crust of stale bread, go to work down mill for 
fourteen hours a day week in-week out. When we got home, our Dad
would thrash us to sleep with his belt!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by puremourning** [comment]
yes, you're quite right. sincerest apologies, I thought I had pulled the latest before testing.
