### ISSUE TITLE
[vim9script] Allow using imported entities without a prefix 

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#10937]
Currently, if I want to use function `Foo()` and constant `BAR` from imported script `lib.vim` without the `lib` prefix, I have to write:

```vim
const Foo = lib.Foo
const BAR = lib.BAR
```

This quickly becomes tedious when there are many exported items (I am writing a plugin where I do that for a couple dozen items, and in each file where `lib` is imported).

I think that the current behavior is sane, because it encourages separate namespaces. At the same time, there are situations where it may be convenient to pollute the script's namespace with imported items (with all the accompanying caveats), because it makes the syntax terser and the code simpler to write.

So, how about a mechanism that simplifies the task above? Possible syntax:

```vim
import 'lib.vim'
import namespace lib

import `anotherlib.vim` as that
import namespace that
```

or

```vim
import 'lib.vim'
use namespace lib

import `anotherlib.vim` as that
use namespace that
```

The semantics would be equivalent to manually defining names for each exported function and constant.

**Comment by brammool** [comment]
> Currently, if I want to use function `Foo()` and constant `BAR` from imported script `lib.vim` without the `lib` prefix, I have to write:
> 
> ```vim
> const Foo = lib.Foo
> const BAR = lib.BAR
> ```
> 
> This quickly becomes tedious when there are many exported items (I am writing a plugin where I do that for a couple dozen items, and in each file where `lib` is imported).
> 
> I think that the current behavior is sane, because it encourages separate namespaces. At the same time, there are situations where it may be convenient to pollute the script's namespace with imported items (with all the accompanying caveats), because it makes the syntax terser and the code simpler to write.
> 
> So, how about a mechanism that simplifies the task above? Possible syntax:
> 
> ```vim
> import 'lib.vim'
> import namespace lib
> 
> import `anotherlib.vim` as that
> import namespace that
> ```
> 
> or
> 
> ```vim
> import 'lib.vim'
> use namespace lib
> 
> import `anotherlib.vim` as that
> use namespace that
> ```
> 
> The semantics would be equivalent to manually defining names for each
> exported function and constant.

In your case you probably know what you are doing and the script you
import was probably written by you.  However, this mechanism is going to
be used by anybody who thinks it's a great idea, and quickly we have
name space pollution all over the place.  It's the kind of thing that
allows people to should themselves in the foot.

If you import many items, there might be something wrong with your
setup.  That's the first thing to look at.

Otherwise, just bite the dust and use the "name." prefix.  You can use a
short name, thus it's not that much of a problem.



-- 
    With sufficient thrust, pigs fly just fine.
                   -- RFC 1925

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Ok, I've tried :-) I'll live with what Vim 9 script is offering, then. Thanks for taking the time to reply to this request!
