### ISSUE TITLE
E117: Unknown function: StatusBar

### ISSUE THREAD

**Issue by ahnafis** [vim/vim#10948]
I recently migrated my old vimrc (with legacy script) to new vim9. Now when I tried to use my `StatusBar()` function in `statusline`, Vim9 gave me this error.

```vim
def StatusBar(): string
    var s = ''
    s ..= ' '

    if FugitiveIsGitDir()
      s ..= FugitiveHead()
    else
      s ..= '%f'
    endif

    s ..= '%='

    s ..= 'L: %l (%L), C: %v'
    s ..= '  '
    s ..= toupper(&enc)
    s ..= '  '
    s ..= '%Y'
    s ..= ' '

    return s
enddef

set statusline=%!StatusBar()
```

**Comment by lacygoill** [comment]
All items are local to the script by default.  That includes your `StatusBar()` function.  But the [`'statusline'`](https://vimhelp.org/options.txt.html#%27statusline%27) option is processed in global context, where script-local items are not accessible.

Make your `StatusBar()` function global, so that it can be accessed in global context.  Also, prefix the calls to the `Fugitive*()` functions with `g:` so that no error is given at compile time (alternatively, you could try [`exists_compiled()`](https://vimhelp.org/builtin.txt.html#exists_compiled%28%29)).
```diff
--- /tmp/vimrc	2022-08-20 19:06:15.139294109 +0200
+++ /tmp/fixed_vimrc	2022-08-20 19:06:32.591246454 +0200
@@ -1,9 +1,9 @@
-def StatusBar(): string
+def g:StatusBar(): string
     var s = ''
     s ..= ' '
 
-    if FugitiveIsGitDir()
-      s ..= FugitiveHead()
+    if g:FugitiveIsGitDir()
+      s ..= g:FugitiveHead()
     else
       s ..= '%f'
     endif
@@ -20,4 +20,4 @@
     return s
 enddef
 
-set statusline=%!StatusBar()
+set statusline=%!g:StatusBar()
```

**Comment by lacygoill** [comment]
> But the 'statusline' option is processed in global context, where script-local items are not accessible.

I wonder whether that should be documented.  There is this at [`:help 'statusline'`](https://vimhelp.org/options.txt.html#%27statusline%27):

   > Note that the "%!" expression is evaluated in the context of the
   > current window and buffer, while %{} items are evaluated in the
   > context of the window that the statusline belongs to.

But that doesn't explain that we're limited to a global function (or autoload function, which is similar).
