### ISSUE TITLE
Expanding wildcards in directories with several self-referential links is very, very slow

### ISSUE THREAD

**Issue by personalizedrefrigerator** [vim/vim#10946]
### Steps to reproduce

1. In a UNIX shell, create a directory with several self-referential links:
```
$ mkdir foo
$ cd foo
$ ln -s ./ link1
$ ln -s ./ link2
$ ln -s ./ link3
$ ln -s ./ link4
$ ln -s ./ link5
$ ls
link1  link2  link3  link4  link5
```
2. Open `vim` in that directory:
```
$ vim
```
3. Expand `**`:
```vim
:echom expand('**')
```
4. Press enter

### Expected behaviour

 * Vim should expand the wildcard within a reasonable amount of time.
 * Vim should stop attempting to expand the wildcards when I press `Ctrl+C`.
 * Vim should stop attempting to expand the wildcards when I close the terminal tab in GNOME terminal
     * After closing all instances of `vim` (force-closing by closing the tab in GNOME terminal), I still see instances of `vim` running in `gnome-system-monitor`: ![](https://user-images.githubusercontent.com/46334387/185745347-ec9bcf53-cf88-430e-b107-8c2204055ff5.png)

### Version of Vim

8.2.3995

### Environment

Operating system: PoP OS 22.04 LTS
Terminal: `GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD`
Value of $TERM: `xterm-256color`
Shell: bash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. In a UNIX shell, create a directory with several self-referential links:
> ```
> $ mkdir foo
> $ cd foo
> $ ln -s ./ link1
> $ ln -s ./ link2
> $ ln -s ./ link3
> $ ln -s ./ link4
> $ ln -s ./ link5
> $ ls
> link1  link2  link3  link4  link5
> ```
> 2. Open `vim` in that directory:
> ```
> $ vim
> ```
> 3. Expand `**`:
> ```vim
> :echom expand('**')
> ```
> 4. Press enter

And it hangs.  The problem here is that it is very difficult that a
endless recursion exists.  Well, with the example it would be obvious,
but the link could be several directory levels deep, pointing to the
top.

Instead of trying to prevent it, it should at least be possible to
interrupt.  I can make CTRL-C get us out of the loops.  Even that isn't
easy, after stopping to search for files the processing of the many
results also can take quite a bit of time, thus that also needs to be
interruptable.

-- 
There are three kinds of people: Those who can count & those who can't.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
