### ISSUE TITLE
Inconsistent virtual text line ordering

### ISSUE THREAD

**Issue by simplysh** [vim/vim#10958]
### Steps to reproduce

When adding virtual text lines, the ordering seems to be inconsistent between Windows and Linux (Debian). I have run the following:
```
call prop_type_add('test', { 'highlight': 'Normal' })

call prop_add(1, 0, { 'type': 'test', 'text': 'A', 'text_align': 'below' })
call prop_add(1, 0, { 'type': 'test', 'text': 'B', 'text_align': 'below' })
call prop_add(1, 0, { 'type': 'test', 'text': 'C', 'text_align': 'below' })
```
Result on Linux:
```
A
B
C
```
Result on Windows:
```
C
B
A
```

I don't have much experience with vimscript so I apologise in advance if I made any wrong assumptions.

### Expected behaviour

```
A
B
C
```

### Version of Vim

9.0.242

### Environment

Windows 10 and Debian 11 with same version of gVim.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> When adding virtual text lines, the ordering seems to be inconsistent between Windows and Linux (Debian). I have run the following:
> ```
> call prop_type_add('test', { 'highlight': 'Normal' })
> 
> call prop_add(1, 0, { 'type': 'test', 'text': 'A', 'text_align': 'below' })
> call prop_add(1, 0, { 'type': 'test', 'text': 'B', 'text_align': 'below' })
> call prop_add(1, 0, { 'type': 'test', 'text': 'C', 'text_align': 'below' })
> ```
> 
> I don't have much experience with vimscript so I apologise in advance if I made any wrong assumptions.
> 
> ### Expected behaviour
> 
> Result on Linux:
> ```
> A
> B
> C
> ```
> Result on Windows:
> ```
> C
> B
> A
> ```
> 
> ### Version of Vim
> 
> 9.0.242
> 
> ### Environment
> 
> Windows 10 and Debian 11 with same version of gVim.

The properties are sorted with qsort(), and we have seen before that in
edge cases it works different from qsort() on Unix.

If you give your properties a different type then you can use the
priority to fix the sorting order.

Hmm, I think we can use the ID itself as a tie breaker, since each
proprty with text has a different ID.

-- 
The Law of VIM:
For each member b of the possible behaviour space B of program P, there exists
a finite time t before which at least one user u in the total user space U of
program P will request b becomes a member of the allowed behaviour space B'
(B' <= B).
In other words: Sooner or later everyone wants everything as an option.
                                        -- Vince Negri

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
