### ISSUE TITLE
Make 'display' lastline (aka @@@) customizable

### ISSUE THREAD

**Issue by doums** [vim/vim#10963]
### Feature description

Hi,
The option `display` is used to configure the way truncated last lines, that do not fit into the editor window, are marked. When `display` includes `lastline` or `truncate`, `@@@` is put to indicate the rest of the line is not displayed.
Currently, customize that string `@@@` is not possible because it's hard-coded.
https://github.com/vim/vim/blob/adce965162dd89bf29ee0e5baf53652e7515762c/src/drawscreen.c#L2643

The purpose here is to make it customizable. For example, we could use the `fillchar` option for it.

**Comment by brammool** [comment]
Pierre Dommerc wrote:

> ### Feature description
> 
> Hi,
> The option `display` is used to configure the way truncated last
> lines, that do not fit into the editor window, are marked. When
> `display` includes `lastline` or `truncate`, `@@@` is put to indicate
> the rest of the line is not displayed.
> Currently, customize that string `@@@` is not possible because it's hard-coded.
> https://github.com/neovim/neovim/blob/master/src/nvim/drawscreen.c#L1876-L1907
> 
> The purpose here is to make it customizable. For example, we could use
> the `fillchar` option for it.

Adding an item to the 'fillchar' option makes sense.  Possibly "lastline".
It would still define one character, which should be a single screen
cell.  Otherwise it gets more complicated to implement.

-- 
John:   When I'm playing tennis with friends I always get carried away
George: You hurt your foot each time?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by doums** [comment]
Thanks @arp242 👍🏻
