### ISSUE TITLE
Markdown: Indent wrapped footnotes with 4 spaces instead of 2

### ISSUE THREAD

**Issue by john-cj** [vim/vim#10979]
Currently if you have a Markdown file with a footnote, and you format this footnote with `gww` or `gqq`, the wrapped part, if it exceeds the `textwidth` value, will be indented by 2 spaces.

```
[^footnote]: Lorem ipsum dolor sit amet.

gww =>

[^footnote]: Lorem ipsum
  dolor sit amet
```

I think it would be much better to indent them with 4 spaces instead of 2. This is because if a footnote has multiple paragraphs, all of them except the first must be indented by 4 spaces as well, no more, no less. And so indenting by 4 spaces instead of 2, even when a footnote consists of only one paragraph, makes sense. It makes it easier to add further paragraphs later.

```
[^footnote]: Lorem ipsum dolor sit amet.

gww =>

[^footnote]: Lorem ipsum
    dolor sit amet.

And then it will be easier to add further paragraphs, if you wish to do so:

[^footnote]: Lorem ipsum
    dolor sit amet.

    Lorem ipsum dolor sit
    amet.
```

**Comment by lacygoill** [comment]
This issue was addressed in this PR https://github.com/vim/vim/pull/8859
The latter was merged in the upstream filetype plugin in [this commit](https://github.com/tpope/vim-markdown/commit/82a10f4137c0778f4ebe1c56259fe159057db305).

I guess you'll have to wait for the default filetype plugin to be synchronized with upstream, or if you want an immediate fix, you could copy the updated filetype plugin on your local machine:

    $ cd ~/.vim/ftplugin/ && curl --fail --location --show-error --silent --remote-name 'https://raw.githubusercontent.com/tpope/vim-markdown/master/ftplugin/markdown.vim'
