### ISSUE TITLE
Linux: Mouse clicks on minimal vsplit on the right border are not recognized

### ISSUE THREAD

**Issue by delvh** [vim/vim#10980]
### Steps to reproduce

1. Open `test1`
2. Execute `:vsplit test3`
3. Execute `:split test2` so that it is positioned above `test1`
4. (Optional, makes no difference): Set `mouse=a`
5. Decrease the width of `test1` and `test2` to the minimum
6. Focus `test3`

These instructions can be seen in the screenshot (except for the wrong cursor position):

![image](https://user-images.githubusercontent.com/51889757/186791900-6ecedfe5-0b40-4364-82b9-04f94d5ee09d.png)

However, what isn't visible is that when clicking on the exact spot where the cursor currently is, **nothing** happens.
The same is true when trying to select `test1`, so there simply seems to be a "dead rectangle" at the right border where mouse clicks disappear into the void.

PS: Even a two-file setup produces this bug consistently.

### Expected behaviour

`test2` gets focused.

### Version of Vim

8.2.3995

### Environment

OS: `Kubuntu 22.04`
Terminal: `Konsole`
`$TERM`: `xterm-256color`
Display: `3840×2160` (4K)

**Comment by lacygoill** [comment]
Does the issue persist if you set [`'ttymouse'`](https://vimhelp.org/options.txt.html#%27ttymouse%27) to `'sgr'`?

    set ttymouse=sgr

**Comment by delvh** [comment]
Actually not.
The vsplit does indeed get focused in that case.
The only slightly weird behavior, but probably somewhat wanted is that not only does the vsplit get focused, it **also increases its width automatically**.

So, I can see two further approaches for this issue:
1. Close it as there is a workaround.
2. keep it open as still there appears to be a bug of some sort as users probably don't want to have to file an issue to learn that there is a config option to disable the faulty behavior

Which one should it be?

**Comment by lacygoill** [comment]
For some reason, it seems that Vim fails to properly detect that Konsole supports SGR-styled mouse reporting.  Instead of setting `'ttymouse'` to `sgr`, it sets the option to `xterm2`.  Usually, this kind of issue boils down to a wrong `TERM`, but that's not the reason here, since yours is set to `xterm-256color`.  Well, technically it is wrong, it should be `konsole` or some derivative, but "fixing" it doesn't seem to change the results (which is not surprising; usually, Vim supports more features when it thinks that the terminal is xterm-compatible).

When the option is set to `sgr`, these pseudo-keys are automatically set up:

    <SgrMouseRelease> ^[[<*m
    <SgrMouse>  ^[[<*M

You can find them in the output of `:set! termcap`.
I think that without those keys, Vim fails to recognize the sequences emitted by the terminal when you use the mouse on a cell beyond the 223rd.

Anyway, I guess it's a bug, but that's for the devs to decide.

**Comment by lacygoill** [comment]
Fixed by patch [9.0.0273](https://github.com/vim/vim/releases/tag/v9.0.0273)
