### ISSUE TITLE
BufEnter not triggered inside :try with buftype=nofile

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#10986]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
new somefile
set buftype=nofile
au BufEnter somefile call setline(1, 'triggered')
try
  edit
endtry
```
3. The two buffers are empty

### Expected behaviour

The top buffer has text "triggered"

### Version of Vim

9.0.0273

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

### Logs and stack traces

Regression introduced by patch 9.0.0272

**Comment by zeertzjq** [comment]
Changing the `FAIL` in fileio.c line 315 to either `OK` or `NOTDONE` seems to fix this.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Source the following file:
> ```vim
> new somefile
> set buftype=nofile
> au BufEnter somefile call setline(1, 'triggered')
> try
>   edit
> endtry
> ```
> 3. The two buffers are empty
> 
> ### Expected behaviour
> 
> The top buffer has text "triggered"
> 
> ### Version of Vim
> 
> 9.0.0273
> 
> ### Environment
> 
> Operating system: Arch Linux
> Terminal: kitty
> Value of $TERM: xterm-kitty
> Shell: fish
> 
> ### Logs and stack traces
> 
> ```shell
> Regression introduced by patch 9.0.0272
> ```

I would say this is correct.  The "new" command opens the buffer, the
following "edit" doesn't do anything, since the buffer has no file.

Perhaps we should give an error message when using ":edit"?

> Changing the `FAIL` in fileio.c line 315 to either `OK` or `NOTDONE`
> seems to fix this.

Hmm, a bit surprising.  But that seems to be OK.  

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
Actually I think changing `FAIL` to `NOTDONE` here can also fix another potential problem: If `open_buffer()` is called from `ml_append()` or `ml_replace()`, returning `FAIL` will make them fail, while returning `NOTDONE` still works. Not sure if there is a way to test this.

**Comment by zeertzjq** [comment]
I found a way to test this: #10988
