### ISSUE TITLE
[bisected] Screen flickers and leaves artifacts when cmdheight=0 and changing background from plugin

### ISSUE THREAD

**Issue by vimpostor** [vim/vim#11017]
### Steps to reproduce

1. Download and extract the minimal reproducing example [background-plug.tar.gz](https://github.com/vim/vim/files/9455502/background-plug.tar.gz) so that the plugin resides in `/tmp/background-plug` and the following two files (included in the archive) are present at `/tmp/background-plug/colors/background-plug.vim` and `/tmp/background-plug/plugin/background-plug.vim`:
```vim
" colors/background-plug.vim
hi clear
if exists("syntax_on")
	syntax reset
endif
let g:colors_name = "background-plug"

if &background == 'light'
	hi Normal guifg=#000000 guibg=#ffffff
else
	hi Normal guifg=#ffffff guibg=#000000
endif
```
```vim
" plugin/background-plug.vim
if 0
	echom "this if condition is important for the bug to trigger, even though it is never run"
endif

set background=dark
```
2. Start vim with the following configuration:
```bash
src/vim --clean -Nu <(cat<<EOF
set termguicolors
set background=light
set cmdheight=0
set rtp+=/tmp/background-plug
colorscheme background-plug
EOF
)
```

The screen will flicker when you start up vim similar to https://github.com/neovim/neovim/issues/19362, and when you quit vim, it will leave artifacts of the last vim buffer visible on the terminal.

### Expected behaviour

The screen should not flicker at startup and vim should not leave artifacts on the screen when quitting.

I have bisected the bad commit to 7a99da43d14671cc91a302bcfa34d37a35eaa28d

### Version of Vim

9.0.0333

### Environment

Operating System: Arch Linux
Terminal: Wezterm with $TERM=xterm-256color
Shell: zsh

### Logs and stack traces

A screen recording of the issue is visible at: https://asciinema.org/a/Ti1DU8g8jpppfOTSCJGYg3xs7

**Comment by vimpostor** [comment]
The weirdest thing about this bug is that the problem disappears if I remove the following never run code:

```vim
if 0
	echom "this if condition is important for the bug to trigger, even though it is never run"
endif
```

The problem also disappears if I change `echom` to `echo`.

Luckily I was able to bisect the bad commit to 7a99da43d14671cc91a302bcfa34d37a35eaa28d, so we know at least where to look for the issue.

**Comment by lacygoill** [comment]
Not sure it will help here, but a [`script(1)` log](https://github.com/vim/vim/issues/8002#issuecomment-1086671199) can be useful for issues related to flickering.

**Comment by vimpostor** [comment]
Here is the script log:
[script_log.tar.gz](https://github.com/vim/vim/files/9455897/script_log.tar.gz)

Replay with: `scriptreplay --typescript=/tmp/script_record.log --timing=/tmp/script_timing.log`

**Comment by brammool** [comment]
You could try removing the line or lines that the patch changed, below "// in case it was changed in dont_use_message_window()".
The first version set cmdline_row unconditionally, later an "if" was added.

The other change in the patch prevents a crash, thus it can't be related.

Note that with 'cmdheight' set to zero you can expect some extra redrawing, since the command line appears and disappears.

**Comment by brammool** [comment]
> From the comment it looks like that line only intends to reset
> `cmdline_row` if it was previously set in `dont_use_message_window()`,
> but when I watch that variable with `gdb`, it is set to `34` in
> `compute_cmdrow()` in `ex_getln.c`, but then set back to `Rows` in the
> offending code (`Rows` is `35` with my terminal size).
> 
> @brammool Does `compute_cmdrow()` perhaps need an offset depending on
> the value of `p_ch`?

I suspect part of the problem is that in ex_getln.c, when starting to
type a command, p_ch is changed to 1 and then a redraw is required.
Much of the code isn't prepared for a redraw when typing ":".

This is one of the many complicateions of supporting 'cmdheight' zero.

The "echomsg" inside "if 0" might have an effect when the "skip" flag
isn't checked in the right place.

Let me remove setting cmdline_row.  No test fails, perhaps it's not
needed anymore.

-- 
BODY:        I'm not dead!
CART DRIVER: 'Ere.  He says he's not dead.
LARGE MAN:   Yes he is.
BODY:        I'm not!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vimpostor** [comment]
Can confirm that patch 9.0.0337 fixes the problem. Hopefully we do not break this in the future again, it is hard to add a test for this.
