### ISSUE TITLE
Caught exception:Vim(function):E126:Missing :endfuction @ ./src/testdir/test_python3.vim

### ISSUE THREAD

**Issue by xiaoge1001** [vim/vim#11015]
### Steps to reproduce

1. wget ftp://ftp.vim.org/pub/vim/unix/vim-8.2.tar.bz2
2. The following patches have been added to ensure the successful compilation of vim and the basic functions of vim are normal:
patch 8.2.0354: Python 3.9 does not define _Py_DEC_REFTOTAL
patch 8.2.1031: build failure with Perl5.32
patch 8.2.1225: linker errors when building with dynamic Python 3.9
patch 8.2.1655: cannot build with Strawberry Perl 5.32.0
patch 8.2.1834: PyEval_InitThreads() is deprecated in Python 3.9
patch 8.2.2891: cannot build with Perl 5.34

and so on.

3. add the patch: [patch 8.2.1123: Python 3 test is old style ](https://github.com/vim/vim/commit/effb0cd)
4. execute:LC_ALL=en_US.UTF-8 make -j1 test

This problem should have been solved, because there is no problem in vim-9.0. But I have never found a solution. I checked each test function in test_python3.vim, but no function is found missing  :endfuction

### Expected behaviour

test_python3.vim is executed normally and don't throw exception.

### Version of Vim

vim-8.2

### Environment

python3-3.9.9
perl-5.34.0
gcc-10.3.1

### Logs and stack traces

```shell
1 FAILED:
   Caught exception:Vim(function):E126:Missing :endfuction @ ./src/testdir/test_python3.vim
```

**Comment by lacygoill** [comment]
I don't know how you applied the [patches.tar.gz](https://github.com/vim/vim/files/9454915/patches.tar.gz), and in which order, but I can't apply the patch [8.2.1123](https://github.com/vim/vim/releases/tag/v8.2.1123):

    $ patch -p1 </tmp/patches/patch3.txt
    patching file src/Makefile
    Hunk #1 FAILED at 2308.
    1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.rej
    patching file src/testdir/Make_all.mak
    Hunk #1 FAILED at 20.
    Hunk #2 succeeded at 44 (offset 8 lines).
    Hunk #3 succeeded at 288 (offset -20 lines).
    1 out of 3 hunks FAILED -- saving rejects to file src/testdir/Make_all.mak.rej
    patching file src/testdir/Make_vms.mms
    Hunk #2 FAILED at 115.
    Hunk #3 succeeded at 145 (offset 5 lines).
    1 out of 3 hunks FAILED -- saving rejects to file src/testdir/Make_vms.mms.rej
    patching file src/testdir/test87.in
    Reversed (or previously applied) patch detected!  Assume -R? [n]

I tried applying it in third position (to respect its version number), and in last position, none of them worked.

I can apply all the other patches.

---

    Caught exception:Vim(function):E126:Missing :endfuction @ ./src/testdir/test_python3.vim

An "n" is missing in `endfuction`.  It might be a typo, or maybe something else is going on...

---

In case, it helps, here is the list of patches including the keywords "test" and "python" in their messages:

   - [8.2.0074](https://github.com/vim/vim/releases/tag/v8.2.0074)  Python 3 unicode test sometimes fails
   - [8.2.0075](https://github.com/vim/vim/releases/tag/v8.2.0075)  Python 3 unicode test still sometimes fails
   - [8.2.0076](https://github.com/vim/vim/releases/tag/v8.2.0076)  Python 3 unicode test fails on MS-Windows
   - [8.2.0079](https://github.com/vim/vim/releases/tag/v8.2.0079)  Python 3 unicode test still fails on MS-Windows
   - [8.2.0130](https://github.com/vim/vim/releases/tag/v8.2.0130)  Python3 ranges are not tested
   - [8.2.0307](https://github.com/vim/vim/releases/tag/v8.2.0307)  Python 3 vim.eval not well tested
   - [8.2.0741](https://github.com/vim/vim/releases/tag/v8.2.0741)  Python tests fail because of changed message
   - [8.2.1120](https://github.com/vim/vim/releases/tag/v8.2.1120)  Python code not tested properly
   - [8.2.1123](https://github.com/vim/vim/releases/tag/v8.2.1123)  Python 3 test is old style
   - [8.2.1146](https://github.com/vim/vim/releases/tag/v8.2.1146)  not enough testing for Python
   - [8.2.1151](https://github.com/vim/vim/releases/tag/v8.2.1151)  insufficient test coverage for Python
   - [8.2.1767](https://github.com/vim/vim/releases/tag/v8.2.1767)  Vim9: test fails with python support
   - [8.2.1912](https://github.com/vim/vim/releases/tag/v8.2.1912)  with Python 3.9 some tests fail
   - [8.2.2187](https://github.com/vim/vim/releases/tag/v8.2.2187)  Python 3 test fails sometimes
   - [8.2.2872](https://github.com/vim/vim/releases/tag/v8.2.2872)  Python tests fail without the channel feature
   - [8.2.3485](https://github.com/vim/vim/releases/tag/v8.2.3485)  Python 3 test fails with Python 3.10
   - [8.2.3602](https://github.com/vim/vim/releases/tag/v8.2.3602)  Python3 test fails with Python 3.10 on MS-Windows
   - [8.2.4353](https://github.com/vim/vim/releases/tag/v8.2.4353)  CI does not use the latest Lua and Python
   - [8.2.4396](https://github.com/vim/vim/releases/tag/v8.2.4396)  Python3 test fails
   - [8.2.5032](https://github.com/vim/vim/releases/tag/v8.2.5032)  Python 3 test fails without the GUI

**Comment by brammool** [comment]
Hmm, taking an older version, applying some patches, this is not something we support or has something we can fix.
Maybe in interesting discussion, but not an issue that is actionable.
