### ISSUE TITLE
text property highlighting continues over breakindent

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11035]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        &lines = 24
        &columns = 80
        $'{'x'->repeat(&columns / 2)}!{'x'->repeat(&columns / 2)}'->setline(1)
        syntax on
        &signcolumn = 'yes'
        &linebreak = true
        set breakat+=!
        &wrap = true
        syntax match xTest /.*/
        highlight link xTest Comment
        prop_type_add('matchparen', {highlight: 'MatchParen'})
        prop_add(1, &columns / 2 + 1, {length: 1, type: 'matchparen'})
    EOF
    )

On the first soft-wrapped line, the highlight is applied from the cell occupied by the last character (`!`), up to the very last cell of the window.

**Expected behavior**

The highlight is applied on the cell occupied by the last character (`!`), and not further.

**Version of Vim**

9.0 Included patches: 1-353

**Screenshot**

![gif](https://user-images.githubusercontent.com/8505073/188039187-b37ea532-359e-4727-8c4f-ea33e5114715.gif)

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

It seems to be the same issue as https://github.com/vim/vim/issues/9242 which was fixed by patch [8.2.3700](https://github.com/vim/vim/releases/tag/v8.2.3700).  The latter created regressions which were fixed in patches [8.2.3706](https://github.com/vim/vim/releases/tag/v8.2.3706) and [8.2.3723](https://github.com/vim/vim/releases/tag/v8.2.3723).

---

The MRE is 100% reproducible in xterm, with 80 columns and 24 lines.

**Comment by lacygoill** [comment]
As a workaround, we can reset the `combine` attribute of the text property type:

    prop_type_add('matchparen', {highlight: 'MatchParen', combine: false})
                                                          ^------------^

---

For some reason, the issue depends on the highlight group used by the text property type.  For example, the issue occurs with `Search`, but not with `ErrorMsg`.

**Comment by brammool** [comment]
> As a workaround, we can reset the `combine` attribute of the text property type:
> 
>     prop_type_add('matchparen', {highlight: 'MatchParen', combine: false})
>                                                           ^------------^
> 
> ---
> 
> For some reason, the issue depends on the highlight group used by the
> text property type.  For example, the issue occurs with `Search`, but
> not with `ErrorMsg`.

Right, the attributes are combined, and when checking if the attributes
came from the text property this results in FALSE, because the combined
attributes are different.  I fixed it by remembering the combined
attributes.  Yet another state variable in this already very complex
loop...

-- 
Are leaders born or made?  And if they're made, can we return them under
warranty?
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
