### ISSUE TITLE
Change includeexpr for shell?

### ISSUE THREAD

**Issue by Freed-Wu** [vim/vim#11045]
An example shell script:

```
pip install -ihttps://mirrors.bfsu.edu.cn/pypi/web/simple -rrequirements.txt
```

`-rrequirements.txt` is a short form for `-r requirements.txt`. So how about `setlocal includeexpr=substitute(v:fname,'^-.','','g')` for all shell filetype (sh/bash/zsh/etc)?

**Comment by chrisbra** [comment]
this should be discussed with the respective runtime file maintainers for (sh/bash/zsh)

**Comment by arp242** [comment]
Maintainers of different shells may make different decisions, and csh, POSIX sh, bash, zsh, PowerShell, and fish are not the same shells and the syntax highlight implementations are quite different because the syntaxes are quite different.

For example for zsh, it seems to me that using the `include` and `includeexpr` for zsh modules makes much more sense than flags, so I'm not sure I'd be in favour of including that there. But bash and sh don't have this feature, so maybe it makes more sense there? Although `source` / `.` seems to make more sense than flags to me. Don't know about fish and PowerShell.

**Comment by Freed-Wu** [comment]
> Maintainers of different shells may make different decisions

I see. Maybe let them do these decision by themselves is the best method.
