### ISSUE TITLE
When using normal mode search pattern // in Ex command line two issues

### ISSUE THREAD

**Issue by Anton-Wessel** [vim/vim#11051]
### Steps to reproduce

enter my code

### Expected behaviour

item 1:
when writing a script typing CTRL-V CTRL-I should be inserted as "^I", but not reselved into a TAB character.
.
item 2:
the search limit possibilities 
/\%<Ylpattern/
/\%<Ycpattern/
should work in Ex commandline too.

### Version of Vim

vim version 8.2 (2019 Dec 12, Compiled Jan 31 2021 04:47:07)

### Environment

Kubuntu 22.04, but in the moment KNOPPIX 9.1
in Konsole window , $TERM: xterm-356color,
shell: bash

### Logs and stack traces

```shell
My code in Ex commandline is::

exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/+++ +++ +++ +++/\<CR>"|ka|exec "normal! gg\<CR>"|exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/\\%<'al./\<CR>"

this code should do:

first search the pattern /:...solved/

after match go 16 lines;

make follow-search for pattern 
/+++ .../

set the marker "a" to that linenumber;

jump to beginning of buffer;

second search the pattern /:...solved/

after match go 16 lines;

make follow-search for pattern 
/./

i.e. "." for any character in order to highlight the search region up to the limit given by marker "a";

PROBLEM:

in 

/\%<'alPATTERN/
or
/\%<'acPATTERN/

after the marker "'a", the "l" or "c" are taken as pattern and are searched for, the real given pattern after "l", "c" is ignored.

In my example this ignored pattern is ".", but this is true for any pattern.

Trying to use "{}" was of no help.

Regards

Anton_Wessel@t-online.de
```

**Comment by lacygoill** [comment]
> when writing a script typing CTRL-V CTRL-I should be inserted as "^I", but not reselved into a TAB character.

I don't understand.  It seems you make a distinction between `^I` and a tab character.  But in a terminal, Vim can't make any difference between them (unless you're using [`:help modifyOtherKeys`](https://vimhelp.org/map.txt.html#modifyOtherKeys)).

Anyway, see if any of these settings help:

    set wildcharm=9
    set wildcharm=26

Try them separately.

---

   > after the marker "'a", the "l" or "c" are taken as pattern and are searched for

Everything on a search command is part of a pattern.  That includes `'a`, `l`, `c`, ...
`\%<'a` is a full atom.  It means "before the line where the mark a is put".  It doesn't need any other character to mean something.  In particular, it doesn't need `l` nor `c`.  `l` and `c` are only necessary after `\%<123`; not after `\%<'a`.

   > the real given pattern after "l", "c" is ignored

Or maybe it's not ignored.  Maybe it fails because of the wrong `l`/`c` which is written before.

---

   > My code in Ex commandline is::

It's too long to fit on one line.  Break it on multiple lines.
This is your code:

    exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/+++ +++ +++ +++/\<CR>"|ka|exec "normal! gg\<CR>"|exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/\\%<'al./\<CR>"

Broken on multiple lines:

    exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/+++ +++ +++ +++/\<CR>"
    ka
    exec "normal! gg\<CR>"
    exec "normal! /:BLANKCHARACTER #TABCHARACTERsolved/+16;/\\%<'al./\<CR>"

First line:  You don't need `:normal` and `:execute`.  Use [`:help search()`](https://vimhelp.org/builtin.txt.html#search%28%29) instead:

    call search(':BLANKCHARACTER #TABCHARACTERsolved')
    +16
    call search('+++ +++ +++ +++')

Second line:  `:ka` is not readable.  Use `:mark a` instead:

    mark a

Third line:  You don't need `:execute`:

    normal! gg

Or use [`:help cursor()`](https://vimhelp.org/builtin.txt.html#cursor%28%29):

    call cursor(1, 1)

Fourth line:  You don't need `:normal` and `:execute`.  Use [`:help search()`](https://vimhelp.org/builtin.txt.html#search%28%29) instead:

    call search(':BLANKCHARACTER #TABCHARACTERsolved')
    +16
    call search("\\%<'al.")

This gives:
```vim
call search(':BLANKCHARACTER #TABCHARACTERsolved')
+16
call search('+++ +++ +++ +++')
mark a
normal! gg
call search(':BLANKCHARACTER #TABCHARACTERsolved')
+16
call search("\%<''al.")
```
You don't need to repeat the pattern twice.  Use a variable:
```vim
let pat = ':BLANKCHARACTER #TABCHARACTERsolved'
call search(pat)
+16
call search('+++ +++ +++ +++')
mark a
normal! gg
call search(pat)
+16
call search("\%<''al.")
```
You don't need to:

   - search for `+++ +++ +++ +++`
   - put a mark on the new line
   - jump back to the start of the buffer
   - search for your pattern again
   - jump 16 lines below again

Pass the `n` flag to `search()` so that the cursor doesn't move, and save the number given by `search()` in a variable.

    " BEFORE
    call search('+++ +++ +++ +++')
    mark a
    normal! gg
    call search(pat)
    +16

    " AFTER
    let lnum = search('+++ +++ +++ +++', 'n')

Then, in your final search, use `\%<123l` instead of `\%<'al` (after replacing `123` with `lnum`):

    " BEFORE
    call search("\%<''al.")

    " AFTER
    call search('\%<' . lnum . '.')

Which gives:
```vim
call search(':BLANKCHARACTER #TABCHARACTERsolved')
+16
let lnum = search('+++ +++ +++ +++', 'n')
call search('\%<' . lnum . '.')
```
If you need to call the code from a mapping, wrap it inside a function, and call the latter:
```vim
function! Func() abort
    call search(':BLANKCHARACTER #TABCHARACTERsolved')
    +16
    let lnum = search('+++ +++ +++ +++', 'n')
    call search('\%<' . lnum . '.')
endfunction
nnoremap <F3> :<C-U>call Func()<CR>
```
If you need to the pattern to be highlighted, put it inside the search register:
```vim
function! Func() abort
    call search(':BLANKCHARACTER #TABCHARACTERsolved')
    +16
    let lnum = search('+++ +++ +++ +++', 'n')
    let @/ = '\%<' . lnum . '.'
    call search(@/)
endfunction
nnoremap <F3> :<C-U>call Func()<CR>
```
---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by lacygoill** [comment]
I forgot `l` in a pattern:

    call search('\%<' . lnum . 'l.')
                                ^

So the last code should be:
```vim
function! Func() abort
    call search(':BLANKCHARACTER #TABCHARACTERsolved')
    +16
    let lnum = search('+++ +++ +++ +++', 'n')
    let @/ = '\%<' . lnum . 'l.'
    call search(@/)
endfunction
nnoremap <F3> :<C-U>call Func()<CR>
```

**Comment by brammool** [comment]
> item 1:
> when writing a script typing CTRL-V CTRL-I should be inserted as "^I",
> but not reselved into a TAB character.

CTRL-I is the Tab character.  Vim can make a difference if you are
mapping keys, but once inserted in the text it can only be 0x09, the Tab
character.

> item 2:
> the search limit possibilities 
> /\%<Ylpattern/
> /\%<Ycpattern/
> should work in Ex commandline too.

Not sure what you mean here.

-- 
I used to be indecisive, now I'm not sure.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Anton-Wessel** [comment]
thank you very much, but there seems to be some missunderstandings:

item 1:

In the Ex commandline mostly \x09  = TAB character  is written as "^I", and that is good, so one can discriminate it from BLANK characters by eye; My topic is to insert by typimg the same in the script file as it can be seen in the Ex command line. You ignore my intention.

item 2:

(a)

the " 'a" mark stands for the line number 872.

In

/\%<872lPATTERN/

/\%<872cPATTERN/

by "l" and "c" one can declare if linewise or characterwise. That is often needed.

(b)

Your proposal to omit "l", "c" does not work.

The the search region begins at beginning of file and ends at line given by mark a, instead of to begin at 16 lines after match-end.

/\%<872lPATTERN/

with pattern "." shows how it should work.

Yes, I can search the linenumber of line "+++ +++ +++ +++" by hand. But I have very many such constallations in my file.

To use the function search().

I use it often, but this way is not.my topic here.

A possible solution to the bug in vim could be to define delimiters for where the real pattern begins and ends (see perl "q()")

Regards

Anton Wessel.

**Comment by lacygoill** [comment]
> by "l" and "c" one can declare if linewise or characterwise. That is often needed.

As already said, that only applies to these atoms `\%123l`, `\%123c`.  This is wrong: `\%'al`.  This is wrong too: `\%'ac`.  This is not documented anywhere.

**Comment by Anton-Wessel** [comment]
addendum:

your proposal to omit "l", "c" after mark can be extended to make it work as follows:  

/\%>'b\%<'aPATTERN/

now mark b must be set to 16 lines after match-end and mark a must be set  to end of search-region.

As a result I have learned:

For using the search-limit construct

\%Y>..., \%Y<...

when Y is a real number, it can be followed 
by "l" or "c";

Y canmot be a varisble;

when Y is a mark,  it cannot be followed 
by "l" or "c";

Thanks, Regards
Anton Wessel

**Comment by Anton-Wessel** [comment]
addendum:

in my typing for you, bachslashes have been deleted, 

correcly it should be;

For using the search-limit construct

\\%Y>..., \\%Y<...

**Comment by chrisbra** [comment]
so your confusion has been resolved and this is not bug here, right?

**Comment by Anton-Wessel** [comment]
addendum:

Annotaion to my last sentence

For using the search-limit construct

\\%Y>..., \\%Y<...

The documenation says:

Lowecase marks can be used in combination with oprators.

This causes that one think, " 'a" represents a number, the line number.

Were this the case, " 'a" ought to be handled as a number  and "l", "c" shold be allowed to follow as with a number typed in by hand.

But I have to memorize: " 'a" is not a number but is a location.

Nevertheless, on that front something is to be improved in vim.

Tanks, Regards
Anton Wessel

**Comment by chrisbra** [comment]
No, those are two different things, and the documentation makes this clear. 

We have different Regex atoms, [`\%'m`](https://vimhelp.org/pattern.txt.html#%2F%5C%25%27m) for the mark `m`, which can only be combined with the `<` and `>` to match *before* or *after*  a mark. 

And then we do have the line number regexp atoms [`\%23l`](https://vimhelp.org/pattern.txt.html#%2F%5C%25l), which matches at a specific line number, which can be again combined with `<` or `>` to match again *before* or *after* a line. 

But other than that, those are totally independent regexp atoms, that cannot be combined together. A patter such as `\%'ml` will not make the pattern *linewise* but rather will match at *mark m followed by the lowercase letter l*. 


> Lowecase marks can be used in combination with oprators.

That means, you can use lowercase mark search patterns after an operator, e.g. something like `d/\%'m` to *delete from your current cursor position up to and including to mark m*. Note, this explicitly only mentions lowercase marks. That is because uppercase marks can potentially be in a different file/buffer, so operating from the current position in the current file up to the mark that is in a different file does not make any sense.

I suggest to ask regex questions on the vim-use mailinglist or at vi.stackexchange.com. Thanks.
