### ISSUE TITLE
Receive key '<80><fc>^B3' in the filter callback of the create_popup method when unsing Belgium keyboard

### ISSUE THREAD

**Issue by vds2212** [vim/vim#11109]
### Steps to reproduce

1. Create a popup window using the `create_popup` method
2. When hitting `3` on a Belgium keyboard the `filter` callback receive `<80><fc>^B3` instead of `3` with an UK keyboard

### Expected behaviour

Expect to receive `3` instead of `<80><fc>^B3`

In Vim 8.2 we used to receive `3`.

Remark: We discovered the problem when debugging problem of the `vim-clap` plugin

### Version of Vim

9.0.0316

### Environment

Operating System: Windows 10
Keyboard: Azerty Belgium

**Comment by lacygoill** [comment]
Could you bisect, and maybe get some [`log`](https://vimhelp.org/starting.txt.html#--log)?

How do you type `3` on a belgium keyboard?  Is it on the keypad?  Do you press some modifier like the Shift key?

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Create a popup window using the `create_popup` method
> 2. When hitting `3` on a Belgium keyboard the `filter` callback receive `<80><fc>^B3` instead of `3` with an UK keyboard

That looks like you get <S-3>.  You have the shift key pressed?
For me Shift-3 results in '#', is that different on a Belgian keyboard?
I can't imagine you need to keep shift pressed to get number 3.

When I press Shift-Space then I get something similar.  I can recognize
it with:  a:key == "\<S-Space>"
For you this should  work: a:key == "\<S-3"

> ### Expected behaviour
> 
> Expect to receive `3` instead of `<80><fc>^B3`
> 
> In Vim 8.2 we used to receive `3`.

We have made changes to recognize more modifiers, because users wanted
to be able to use them.  Main for things like <S-Space> and <C-Tab>.


-- 
hundred-and-one symptoms of being an internet addict:
42. Your virtual girlfriend finds a new net sweetheart with a larger bandwidth.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vds2212** [comment]
Thanks for your comment and questions.

On Azerty keyboard the numbers need the Shift key to be pressed indeed.

I suppose the Clap developer needs a way to interpret the key field of the filter callback.

Where can we find a description of the way the key argument of the filter callback is filled?
Is there a way to convert the key argument into character typed?

Best regards,
Vivian.

**Comment by lacygoill** [comment]
> Is there a way to convert the key argument into character typed?

You can convert a Vim keycode into its internal byte representation by prefixing the key with `*`:

             v
    :echo "\<*S-3>"
    <80><fc>^B3

See [`:help expr-quote`](https://vimhelp.org/eval.txt.html#expr-quote):

    \<*xxx> Like \<xxx> but prepends a modifier instead of including it in the
            character.  E.g. "\<C-w>" is one character 0x17 while "\<*C-w>" is four
            bytes: 3 for the CTRL modifier and then character "W".

---

For the other way around, someone would need to implement a `keytrans()` function.  Relevant todo item:

   > Add a "keytrans()" function, which turns the internal byte representation of a
   > key into a form that can be used for :map.  E.g.
   >     let xx = "\<C-Home>"
   >     echo keytrans(xx)
   >     <C-Home>

[source](https://github.com/vim/vim/blob/cf0995d7d7301e36c81cafa14e68782f1d3be2ad/runtime/doc/todo.txt#L985-L989)

**Comment by vds2212** [comment]
Thanks for your fast answer.

I suppose the `keytrans()` function would be useful indeed.
But to adapt the plugin code we would need a function that translate the internal representation into the character typed
(`<80><fc>^B3` into `3`).

Is that function already available?

How can we help writing the `keytrans()` function?
Is the internal key representation documented somewhere?

Best regards,
Vivian.

**Comment by zeertzjq** [comment]
I've thought about implementing such a function before, but didn't think it would be useful. I just knew that this on the TODO list. I can try implementing this.

**Comment by zeertzjq** [comment]
> I've thought about implementing such a function before, but didn't think it would be useful. I just knew that this on the TODO list. I can try implementing this.

#11114

**Comment by vds2212** [comment]
Thanks let me know when it is merged such that we can test it.

**Comment by lacygoill** [comment]
In case you want to test immediately:

    $ git clone --depth=1 https://github.com/vim/vim
    $ cd vim
    $ git remote add upstream https://github.com/vim/vim.git
    $ git fetch upstream pull/11114/head:keytrans
    $ git checkout keytrans
    $ make

**Comment by brammool** [comment]
> Thanks for your fast answer.
> 
> I suppose the `keytrans()` function would be useful indeed.
> But to adapt the plugin code we would need a function that translate
> the internal representation into the character typed
> (`<80><fc>^B3` into `3`).
> 
> Is that function already available?

We do remove the modifier when it is used to produce the key.  I'm not
sure why it doesn't happen in this case, most likely because we don't
expect Shift being used to produce a digit.  It does happen for
something like the question mark.  The function is
may_remove_shift_modifier().  I wonder if there are any negative side
effects if we add digits there.

If you can compile Vim, you could try this change in misc2.c, around
line 1550:

    && ((key >= '!' && key <= '/')
		|| (key >= ':' && key <= 'Z')
		|| (key >= '[' && key <= '`')
-		|| (key >= '{' && key <= '~')))
+		|| (key >= '{' && key <= '~')
+		|| isdigit(key)))
	return modifiers & ~MOD_MASK_SHIFT;


> How can we help writing the `keytrans()` function?
> Is the internal key representation documented somewhere?

Not in detail.  It's more useful to just try it, by pressing CTRL-K in
Insert mode and then pressing the key.

-- 
hundred-and-one symptoms of being an internet addict:
44. Your friends no longer send you e-mail...they just log on to your IRC
    channel.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vds2212** [comment]
I'll try to compile Vim and test the branch and the modification proposed.
I'll keep you posted.
