### ISSUE TITLE
no error for assigning to control flow keyword

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11103]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        var endif = 0
    EOF
    )

No error is given.

**Expected behavior**

An error is given:

    E1234: cannot use reserved keyword endif

**Version of Vim**

9.0 Included patches: 1-432

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(353)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

If we don't give any error right now, then a confusing error will be given later, whenever we try to use an `if` block:
```vim
vim9script
var endif = 0
if true
endif
```
    E1207: Expression without an effect: endif

---

If we assign to `if`, no error is given either.  Not even if we use an `if` block later:
```vim
vim9script
var if = 123
if true
    echo if
endif
```
    123

Why is it OK to assign to `if` but not to `endif`?  It seems inconsistent, and confusing.  The rules would be easier to understand if it was simply disallowed to assign to any control flow keyword.

**Comment by lacygoill** [comment]
Never mind, it's working as intended:
<https://github.com/vim/vim/blob/6de2296e5e696b894576d48239aaab0ae84486ff/runtime/doc/vim9.txt#L441>

   > Variables may shadow Ex commands, rename the variable if needed.

Although, I still think it's confusing and should be disallowed for control flow keywords.

**Comment by brammool** [comment]
> Never mind, it's working as intended:
> <https://github.com/vim/vim/blob/6de2296e5e696b894576d48239aaab0ae84486ff/runtime/doc/vim9.txt#L441>
> 
>    > Variables may shadow Ex commands, rename the variable if needed.
> 
> Although, I still think it's confusing and should be disallowed for
> control flow keywords.

Yes, it can be a bit confusing.  Although, for common command names it
will be obvious that you are shooting yourself in the foot.

The rationale is that we wanted to get rid of "let" for assignments,
just to "varname = expr".  That means we need to recognize "varname" as
a variable name, not a command.  This is tricky.  Many adjustments were
made to the code that figures out the command from the start of the line
until it worked well.

We will always add new commands later.  E.g. we recently added
"horizontal".  It is not unlikely that someone used that for a variable
name.  Then by adding the command we would break someone's script.  Or
when someone updates Vim a year later several things start breaking
because of any new commands.

We could reject some variable names such as "endif", but that quickly
becomes inconsistent and gives the user the idea that if a name is
allowed that it will work.  It's easier and probably better to give the
user the responsibility of using a good name.


-- 
He who laughs last, thinks slowest.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Yes, it can be a bit confusing.  Although, for common command names it
   > will be obvious that you are shooting yourself in the foot.

I was thinking about something like this:
```vim
vim9script
var x = 'endif'
$'var {x} = 0'->execute()
 # ...
 # much later in the code
 # ...
if true
endif
```
    E1207: Expression without an effect: endif

If the value assigned to `x` is hard to predict (e.g. it comes from the user), the code might sometimes work, and sometimes fail.  And when it fails, it might be hard to understand why (especially if the error is far away from the real cause).

---

   > We will always add new commands later.  E.g. we recently added
   > "horizontal".  It is not unlikely that someone used that for a variable
   > name.  Then by adding the command we would break someone's script.  Or
   > when someone updates Vim a year later several things start breaking
   > because of any new commands.

I understand, but even though control flow keywords are technically Ex commands, they stil have a special status in other languages.  Which Vim9 recognizes since it does not allow them to be abbreviated.  We already make an exception with regards to abbreviations.  We could have added one more exception with regards to assignments.  BTW, Python does not allow `if` to be assigned either:

    $ python -c 'if = 0'
      File "<string>", line 1
        if = 0
           ^
    SyntaxError: invalid syntax

---

   > We could reject some variable names such as "endif", but that quickly
   > becomes inconsistent and gives the user the idea that if a name is
   > allowed that it will work.

I find the current situation already inconsistent.  I'm still not sure why an `endif` assignment is able to shadow `endif` when used to end a block, while at the same time an `if` assignment does *not* shadow an `if` when used to open a block.

Anyway, I was just suggesting that we disallow the same list of Ex commands which cannot be abbreviated.  Because this restriction should already make the user understand that those commands are special.

   - `if`
   - `else`
   - `elseif`
   - `endif`
   - `for`
   - `endfor`
   - `while`
   - `endwhile`
   - `try`
   - `catch`
   - `finally`
   - `throw`
   - `endtry`
   - `def`
   - `enddef`
   - `break`
   - `continue`
   - `return`
   - `finish`
   - `var`
   - `const`
   - `export`
   - `import`

**Comment by lacygoill** [comment]
> I'm still not sure why an endif assignment is able to shadow endif when used to end a block, while at the same time an if assignment does not shadow an if when used to open a block.

OK, now I understand.  For some commands, Vim does not allow an unconditinal shadowing.  That is, it lets an expression shadow a command only when it makes sense.  That's why `if true` works even if we assigned something to `if`.  Because `{expr} true` does not make sense (it would if there was a binary operator between the 2 tokens).  So, it falls back on `{cmd} true`.

That's not so bad.  And that's what the previous adjustments probably referred to.

But then, Vim should do something similar with `endif`.  `{expr}` by itself does not make sense if the evaluation of `{expr}` has no side effect.

**Comment by brammool** [comment]
> But then, Vim should do something similar with `endif`.  `{expr}` by
> itself does not make sense if the evaluation of `{expr}` has no side
> effect.

It's a bit hard to figure out.  At least "endif->func()" could work.
We also have the warning for a statement with no effect to catch things
like this.  It's not perfect though.

-- 
Well, you come from nothing, you go back to nothing...  What have you
lost?  Nothing!
				-- Monty Python: The life of Brian

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
>    > Yes, it can be a bit confusing.  Although, for common command names it
>    > will be obvious that you are shooting yourself in the foot.
> 
> I was thinking about something like this:
> ```vim
> vim9script
> var x = 'endif'
> $'var {x} = 0'->execute()
>  # ...
>  # much later in the code
>  # ...
> if true
> endif
> ```
>     E1207: Expression without an effect: endif
> 
> If the value assigned to `x` is hard to predict (e.g. it comes from
> the user), the code might sometimes work, and sometimes fail.  And
> when it fails, it might be hard to understand why (especially if the
> error is far away from the real cause).

I don't think this is common enough to worry about.

>    > We will always add new commands later.  E.g. we recently added
>    > "horizontal".  It is not unlikely that someone used that for a variable
>    > name.  Then by adding the command we would break someone's script.  Or
>    > when someone updates Vim a year later several things start breaking
>    > because of any new commands.
> 
> I understand, but even though control flow keywords are technically Ex
> commands, they stil have a special status in other languages.  Which
> Vim9 recognizes since it does not allow them to be abbreviated.  We
> already make an exception with regards to abbreviations.  We could
> have added one more exception with regards to assignments.  BTW,
> Python does not allow `if` to be assigned either:
> 
>     $ python -c 'if = 0'
>       File "<string>", line 1
>         if = 0
>            ^
>     SyntaxError: invalid syntax

That is exactly the problem, Python doesn't mind breaking existing
scripts when adding a new keyword.  I know, because a program I wrote
suddenly failed in mysterious ways.  It took quite a bit of debugging to
discover it started because the version of Python had increased and it
added a keyword that I used in another way.  I don't want that to
happen.


>    > We could reject some variable names such as "endif", but that quickly
>    > becomes inconsistent and gives the user the idea that if a name is
>    > allowed that it will work.
> 
> I find the current situation already inconsistent.  I'm still not sure
> why an `endif` assignment is able to shadow `endif` when used to end a
> block, while at the same time an `if` assignment does *not* shadow an
> `if` when used to open a block.
> 
> Anyway, I was just suggesting that we disallow the same list of Ex
> commands which cannot be abbreviated.  Because this restriction should
> already make the user understand that those commands are special.

It still looks like a fairly arbitrary list to me.  More importantly, if
we give an error "you can't use 'endif' for a variable name", people
think that if you don't get this error it is fine.  But it isn't, it can
still interfere with a command.  And we would give an error for names
that are obviously commands, and not give an error for commands the user
might not know about.  Thus it's opposite of what would be good.

-- 
I started out with nothing, and I still have most of it.
                                -- Michael Davis -- "Tonight Show"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
