### ISSUE TITLE
unable to create explicitly typed global variable

### ISSUE THREAD

**Issue by habamax** [vim/vim#11108]
### Steps to reproduce

1. `vim -Nu NONE`
2. add:
```
vim9script
g:listvar: list<string> = ['hello', 'world']
```
3. `:source`

### Expected behaviour

Global variable should be defined.

Instead I can see `E121: Undefined variable: g:listvar` or if do it second time `E488: Trailing characters: : list<string> = ['hello', 'world']`

### Version of Vim

9.0.0439

### Environment

- Fedora36
- gnome terminal
- xterm-256color
- bash

**Comment by bfrg** [comment]
This is explained under `:h variable-types` (second paragraph).

**Comment by habamax** [comment]
Aha, so `any` is not only assumed but enforced.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. `vim -Nu NONE`
> 2. add:
> ```
> vim9script
> g:listvar: list<string> = ['hello', 'world']
> ```
> 3. `:source`
> 
> ### Expected behaviour
> 
> Global variable should be defined.
> 
> Instead I can see `E121: Undefined variable: g:test` or if do it
> second time `E488: Trailing characters: : list<string> = ['hello',
> 'world']`

You cannot specify a type for a global variable, because they can be
changed any time anywhere. And also deleted and re-created (with a
different type).  Thus you can't rely on the type much.

It probably is possible to add some type checking for global variables,
when explicitly declared.  I am not sure if it helps.  It might catch
some mistakes perhaps.

We can indeed try to give a better error message.

-- 
Never overestimate a man's ability to underestimate a woman.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
