### ISSUE TITLE
With 'nosplitscroll', windows are sometimes unnecessarily scrolled after :colder or :cnewer is executed

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11115]
### Steps to reproduce

Run `vim --clean -S test.vim`, with
```vim
set nosplitscroll
edit foo
call setline(1, range(100))
normal! G
copen
close
```
Then run `:colder`, and after the error is displayed, hit `Enter`.

**Result:** The window has been scrolled.

### Expected behaviour

No scrolling after `:colder` (or `:cnewer`) when an error occurs.

### Version of Vim

9.0.447

cc: @luukvbaal

**Comment by luukvbaal** [comment]
I'll look into it.

**Comment by luukvbaal** [comment]
This issue is fixed by calling win_fix_scroll() in restore_snapshot():

```diff
diff --git a/src/window.c b/src/window.c
index fa934749a..49f57b56b 100644
--- a/src/window.c
+++ b/src/window.c
@@ -7094,6 +7094,8 @@ restore_snapshot(
        win_comp_pos();
        if (wp != NULL && close_curwin)
            win_goto(wp);
+       if (!p_spsc)
+           win_fix_scroll(FALSE);
        redraw_all_later(UPD_NOT_VALID);
     }
     clear_snapshot(curtab, idx);
```

Not sure if this will cause issues elsewhere @brammool. I can't say I'm familiar with how that function is used but it seems it's only other use is for help windows. Don't see any weird behavior when opening/closing a help split so it seems fine.

**Comment by luukvbaal** [comment]
I'll see about adding a test for it, I assume a try/catch is needed to catch the colder "E380: At bottom of quickfix stack" error?

**Comment by brammool** [comment]
> This issue is fixed by calling win_fix_scroll() in restore_snapshot():
> 
> ```diff
> diff --git a/src/window.c b/src/window.c
> index fa934749a..49f57b56b 100644
> --- a/src/window.c
> +++ b/src/window.c
> @@ -7094,6 +7094,8 @@ restore_snapshot(
>         win_comp_pos();
>         if (wp != NULL && close_curwin)
>             win_goto(wp);
> +       if (!p_spsc)
> +           win_fix_scroll(FALSE);
>         redraw_all_later(UPD_NOT_VALID);
>      }
>      clear_snapshot(curtab, idx);
> ```
> 
> Not sure if this will cause issues elsewhere @brammool. I can't say
> I'm familiar with how that function is used but it seems it's only
> other use is for help windows. Don't see any weird behavior when
> opening/closing a help split so it seems fine.

Restoring the snapshot is supposed to take care of the scroll position.
So what happens if 'splitscroll' is off?  Do you expect restoring the
snapshot does not scroll compared to when the snapshot was taken, or
when the snapshot is restored?  It might also depend on what it was
restored for.  There are at least two reasons: closing the help window
(did 'nosplitscroll' get used then?) and when closing a window for
executing autocommands.

-- 
hundred-and-one symptoms of being an internet addict:
53. To find out what time it is, you send yourself an e-mail and check the
    "Date:" field.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by luukvbaal** [comment]
> Restoring the snapshot is supposed to take care of the scroll position.
So what happens if 'splitscroll' is off?  Do you expect restoring the
snapshot does not scroll compared to when the snapshot was taken, or
when the snapshot is restored?  It might also depend on what it was
restored for.  There are at least two reasons: closing the help window
(did 'nosplitscroll' get used then?) and when closing a window for
executing autocommands.

Yeah I guess it depends on whether the snapshot is used to restore the situation before the invisible autocmd window or the situation before opening the help window. It seems in the former case restore_snapshot and 'nosplitscroll' were working against each other. This seems to be fixed by the proposed patch, and does not seem to introduce problems for the help win case.

**Comment by bfrg** [comment]
Fixed by https://github.com/vim/vim/commit/5ed391708a62b4ebaa84dd23e32a416e5c3383d9.
