### ISSUE TITLE
character bottom padding is twice top padding？

### ISSUE THREAD

**Issue by CNMan** [vim/vim#1113]
Fira Code
![2016-09-24_082840](https://cloud.githubusercontent.com/assets/8692234/18804692/2e1a2330-8231-11e6-8b1f-dea1bd30efd6.png)

Pragmata Pro Mono
![2016-09-19_103634](https://cloud.githubusercontent.com/assets/8692234/18621501/dc855284-7e56-11e6-87a9-1783f3648387.png)

https://github.com/morhetz/gruvbox/issues/139

**Comment by vim-ml** [comment]
If you mean that there is more space below capital-letter glyphs than
above them, this is normal: indeed, descenders (as with g, j, p, q) go
below the capitals' baseline, while ascenders (as in b, d, f, h, k, l,
t) hardly go above the capitals' top line.

Instead of comparing the blank space above and below NORMAL VISUAL,
try with, let's say, fjfjfjfjfjfj. I bet you'll find that the space
above the top  of the f and below the bottom of the j aren't as
unequal as with capitals.

Best regards,
Tony.

**Comment by CNMan** [comment]
Thank you very much, i mean 2=1*2 as picture.

![2016-09-24_134920](https://cloud.githubusercontent.com/assets/8692234/18806427/c703f0e4-825e-11e6-8c66-1f890da84fff.png)

**Comment by nuko8** [comment]
As for GUI VIm, glyphs on the screen are aligned based on the font metrics which are determined by the rendering engine based on a single or multiple sets of [glyph metrics](https://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html) each of which is specified by a font face in use.

As for Vim on terminal, the terminal does those chores.

Accordingly, it's the font which does "character bottom padding is twice top padding."

So it appears to me that your issue is not an issue about Vim.  Can you clarify that?  If you are asking a question about glyph rendering in general, I'm afraid this issue tracker is a wrong place to ask.

**Comment by CNMan** [comment]
ok,i deleted `renderoptions` from vimrc and got opposite result,it is indeed a renderer issue

``` vim
if has ('win32') || has ('win64')
  if (v:version == 704 && has('patch393')) || v:version > 704
    set renderoptions=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1
  endif
endif
```

![2016-09-24_142826](https://cloud.githubusercontent.com/assets/8692234/18806612/a99e9bd4-8264-11e6-8dca-5071f23a2292.png)
![2016-09-24_142855](https://cloud.githubusercontent.com/assets/8692234/18806614/ae4fcc48-8264-11e6-8a89-8ab7b62da010.png)

**Comment by CNMan** [comment]
@brammool i found the value range：）
https://msdn.microsoft.com/en-us/library/aa970267(v=vs.110).aspx
https://github.com/vim/vim/blob/master/runtime/doc/options.txt#L5889

gamma
`The gamma level is an integer value that ranges from 1000 to 2200. The default level is 1900.`
contrast
`The text contrast level is an integer value that ranges from 0 to 6—the larger the integer value, the wider the stem. The default level is 1.`
level
`The ClearType level is an integer value that ranges from 0 to 100.`

**Comment by k-takata** [comment]
What does happen when you do `:set linespace=0`?
The default is 1 on Windows GUI.

> i found the value range：）

I don't think it can be applied to `IDWriteFactory::CreateCustomRenderingParams`.
It seems that the value of `gamma` and `level` are multiplied by 100 (maybe) when written to the registry, because the registry doesn't have a float type.
For `gamma`, see also https://en.wikipedia.org/wiki/Gamma_correction .
It doesn't take such big value.

Moreover, the newer version of the API [IDWriteFactory3::CreateCustomRenderingParams](https://technet.microsoft.com/en-us/library/security/dn890754.aspx) says:
- gamma
  Type: FLOAT
  The gamma value used for gamma correction, which must be greater than zero and cannot exceed 256.
- enhancedContrast
  Type: FLOAT
  The amount of contrast enhancement, zero or greater.
- clearTypeLevel
  Type: FLOAT
  The degree of ClearType level, from 0.0f (no ClearType) to 1.0f (full ClearType).

**Comment by CNMan** [comment]
looks better now
![2016-09-24_171716](https://cloud.githubusercontent.com/assets/8692234/18807498/6121748c-827b-11e6-9b02-43de32df0b71.png)
