### ISSUE TITLE
Following BufWritePost autocommand is skipped when `:w` is wrapped in `:try`

### ISSUE THREAD

**Issue by blueyed** [vim/vim#1114]
``` vim
augroup test_bwp
  au!
  au BufWritePost * echoerr "error"
  au BufWritePost * echom "after"
augroup END

command! WWithTry try | w | catch /EFOO/ | endtry
```

When calling `:WWithTry`, the "after" is not displayed.
But just using `:w` will display it.

This appears to not be a problem with autocommands in general, since when using `CursorMoved` both messages get displayed:

``` vim
augroup test_bwp
  au!
  au CursorMoved * echoerr "error"
  au CursorMoved * echom "after"
augroup END

command! MoveCursor try | exe 'norm k' | endtry
```

The file is loaded with `vim -Nu vim-bufwritepost-with-up.vim vim-bufwritepost-with-up.vim`.

Happens both in Vim 8.0.8 and Neovim v0.1.6-89-g2daf54e.

**Comment by ZyX-I** [comment]
This is expected: `:try` transforms `echoerr` into an exception which prevents execution of the following pieces of code, replace `echoerr` with `throw` in your second example and you will see the same result. What is your problem in the example is that you think that `norm k` triggers CursorMoved right there. It does not: try

``` VimL
augroup test_bwp
  au!
  au CursorMoved * echoerr "error"
  au CursorMoved * echom "after"
augroup END

command! MoveCursor try | exe 'norm k' | catch /error/ | echomsg v:exception | endtry | echomsg 'After'
MoveCursor
```

, you will see `After` before `error` and you will not see an exception: CursorMoved autocommand is executed outside of a `:try` block.

This is basically why you _must not_ use `:echoerr` unless you immediately surround it with `:try`: you can never tell whether code after `:echoerr` will or will not be executed (if you surround it with `try` you may always tell that it will _not_, but I do not know a way to make `echoerr` work so that it will).
