### ISSUE TITLE
Inaccurate error message when trying to Ctrl-w away from q/ or q:

### ISSUE THREAD

**Issue by Aster89** [vim/vim#11152]
### Steps to reproduce

Enter the command-line window, e.g via <kbd>q</kbd><kbd>/</kbd> or <kbd>q</kbd><kbd>:</kbd>, and then try to move away from it, e.g. via <kbd>Ctrl-w</kbd><kbd>k</kbd>. The triggered error reads like this:
> E11: Invalid in command-line window; <CR> executes, CTRL-C quits                                                                                                                                                                                      

Now, given how I got in the command-line window, i.e. without going via command-line and then pressing <kbd>Ctrl-f</kbd>, I'd expect "<kbd>Ctrl-c</kbd> quits" to mean that I'm left in normal mode where I originally pressed <kbd>q</kbd><kbd>/</kbd>. What happens instead is the "Continue in Command-line mode", as descibed in `:h E199`, so I'm left on the command line in insert mode; hard to say I've "quit" the command line window.

### Expected behaviour

So if I really wanted to "quit", the suggestion of the error message should be _CTRL-C followed by Escape quits_ or _CTRL-C leaves you in command line mode_, or something similar.

### Version of Vim

9.0

### Environment

Operating system: Archlinux (up-to-date)
Terminal: urxvt
Value of $TERM: rxvt-unicode-256color
Shell: bash

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Enter the command-line window, e.g via <kbd>q</kbd><kbd>/</kbd> or
> <kbd>q</kbd><kbd>:</kbd>, and then try to move away from it, e.g. via
> <kbd>Ctrl-w</kbd><kbd>k</kbd>. The triggered error reads like this:
> > E11: Invalid in command-line window; <CR> executes, CTRL-C quits
> 
> Now, given how I got in the command-line window, i.e. without going
> via command-line and then pressing <kbd>Ctrl-f</kbd>, I'd expect
> "<kbd>Ctrl-c</kbd> quits" to mean that I'm left in normal mode where I
> originally pressed <kbd>q</kbd><kbd>/</kbd>. What happens instead is
> the "Continue in Command-line mode", as descibed in `:h E199`, so I'm
> left on the command line in insert mode; hard to say I've "quit" the
> command line window.
> 
> ### Expected behaviour
> 
> The error message should saySo if I really wanted to "quit", the
> suggestion of the error message should be _CTRL-C followed by Escape
> quits_ or _CTRL-C leaves you in command line mode_, or something
> similar.

It would depend on how you got to the command line window.  When typing
"q:" or "q/" then quitting would mean going back to normal mode.  But
opening it from the command line with CTRL-F would mean going back to
the command line.  That's a bit unpredictable though.

First thing to do is that when using CTRL-C to go back to the command
line the screen should be redrawn to make clear that the window is
actually closed.  As opposed to editing a (nested) command line while
the window is still open.

Instead of CTRL-C we could mention ":q", which closes the window and
goes back to normal mode.  I suppose that would be used more often than
CTRL-C.  Unfortunately the message gets long and would often cause a
hit-enter prompt.  We can leave out the "<CR> executes", which isn't
very clear anyway.


-- 
I AM THANKFUL...
...for a lawn that needs mowing, windows that need cleaning
and gutters that need fixing because it means I have a home.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
