### ISSUE TITLE
Area of multiline text property is not extended well when virtual text exists

### ISSUE THREAD

**Issue by thinca** [vim/vim#11151]
### Steps to reproduce

Consider `test.vim`:

```vim
vim9script

setline(1, ['first line', 'second line', 'third line'])

prop_type_add('test', {
  highlight: 'ModeMsg',
})

prop_add(1, 1, {
  type: 'test',
  end_lnum: 3,
  end_col: 3,
  text: 'Virtual text',
})
```

Starts Vim: `vim -u NONE -i NONE -N -S test.vim`

Input `A<CR>` to add a new line.
Check the text property in line 2.

```
:echo prop_list(2)
[]
```

---

When virtual text is not set, works as expected.

```vim
prop_add(1, 1, {
  type: 'test',
  end_lnum: 3,
  end_col: 3,
  # Without virtual text
  # text: 'Virtual text',
})
```

`A<CR>`

```
:echo prop_list(2)
[{'id': 0, 'col': 1, 'type_bufnr': 0, 'end': 0, 'type': 'test', 'length': 1, 'start': 0}]
```

### Expected behaviour

The area of the text property extends as if there were no virtual text.

### Version of Vim

9.0.488

### Environment

OS: Arch Linux
Terminal: Windows Terminal (ssh from Windows), tmux 3.3a
value of $TERM: screen-256color
shell: zsh 5.9

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Consider `test.vim`:
> 
> ```vim
> vim9script
> 
> setline(1, ['first line', 'second line', 'third line'])
> 
> prop_type_add('test', {
>   highlight: 'ModeMsg',
> })
> 
> prop_add(1, 1, {
>   type: 'test',
>   end_lnum: 3,
>   end_col: 3,
>   text: 'Virtual text',
> })
> ```
> 
> Starts Vim: `vim -u NONE -i NONE -N -S test.vim`
> 
> Input `A<CR>` to add a new line.
> Check the text property in line 2.
> 
> ```
> :echo prop_list(2)
> []
> ```

It should not be possible to use "end_lnum" with virtual text, it can
only be added to one specific character in one line.

I think it's best to give an error message.

-- 
Do not trust atoms, they make up everything.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> I tried more patterns and this can be happen without virtual text.
> 
> ```vim
> vim9script
> 
> setline(1, ['first line', 'second line', 'third line'])
> 
> prop_type_add('test', {
>   highlight: 'ModeMsg',
> })
> 
> prop_add(1, 1, {
>   type: 'test',
>   end_col: len(getline(1)) + 1,
> })
> ```
> 
> Starts Vim: `vim -u NONE -i NONE -N -S test.vim`
> 
> Input: `a<CR><CR><Esc>`
> 
> ```
> :echo prop_list(2)
> []
> ```

I assume you used "a" in the first column of the first line.  So what
did you expect, that line 2 has a zero-width text property?

> This is OK: `a<CR>foo<CR><Esc>`
> 
> ```
> :echo prop_list(2)
> [{'id': 0, 'col': 1, 'type_bufnr': 0, 'end': 0, 'type': 'test', 'length': 3, 'start': 0}]
> ```

And that would be correct, right?  Thus it seems that pressing "CR" in
an empty line removes the text property.  It is OK at that point, since
there isn't anything to highlight, but when adding text to that line
later it doesn't get highlighted.

-- 
I AM THANKFUL...
...for the clothes that fit a little too snug because it
means I have more than enough to eat.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
You are adding remarks to a closed issue, this will very easily go unnoticed.
If the original problem is not fixed, re-open the issue.
If there is a related problem, please create a new issue.
