### ISSUE TITLE
Highlight VertSplit  do not function correctly

### ISSUE THREAD

**Issue by lanx-x** [vim/vim#1118]
- version: vim8.0 (+termguicolors)
- vimrc:    `set termguicolors`
- `:highlight Normal guibg=red` works well.
- `:highlight VertSplit guibg=NONE` do not affect the vertsplitbar background color.
- `:highlight VertSplit guibg=NONE cterm=NONE` works well

**Comment by nuko8** [comment]
@iCyMind 

With exactly the same settings as used in your report above, run `vim` and do `:highlight VertSplit`.  Then you'll know what colors and graphical attributes are set for VertSplit.

If you don't find `guibg=<color>` there but only `gui=reverse` or something else other than color specifications, then you'll understand that `:highlight VertSplit guibg=NONE` won't/shouldn't make sense; after all, there's been no color to be overwritten by the `:highlight` command from the beginning.

If `guibg` is set to a valid value , the command should work as expected.

**Comment by lanx-x** [comment]
Sorry， I have not expressed clearly above.

I meet this issue vim with iTerm2 3.0(truecolor support). As `:h termguicolors` says, the vim should use guibg/guifg attributes in the terminal.

When `:hi VertSplit guibg=NONE`, it do make VertSplitBar's bg transparent in GUIvim/MacVim/neovim.

But nothing happen in vim unless `:hi VertSplit cterm=NONE`.

I don't know it's a bug or not, maybe I misunderstand the "termguicolors" option.  But in my opinion, the neovim's behavior is more reasonable.

**Comment by nuko8** [comment]
> When :hi VertSplit guibg=NONE, it do make VertSplitBar's bg transparent in GUIvim/MacVim

Note that what "transparent" exactly means is that the background is painted in the same background color around the object to be painted.  Eventually, the background of the object appears as if it were made transparent.

Knowing that, you'll see why `vim` and `gvim` behave differently.

> /neovim.

I know of it, but haven't used it yet.  I have nothing to say about that.

> But in my opinion, the neovim's behavior is more reasonable.

I don't think so.  Neovim has no GUI; therefore,  the existence of `guibg` is nonsense and illogical, and the use of it is an abuse.  I wonder how you could call that "more reasonable."

> I don't know it's a bug or not, maybe I misunderstand the "termguicolors" option.

I think this issue invalid for vim because of its inaccurate description of the problem and irrational comparison with what one cannot compare with.

**Comment by k-takata** [comment]
Maybe related (or duplicate?): #981

**Comment by nuko8** [comment]
In a sense, one can say that they are related each other...

But there's a subtle difference between them.  As to the background color to be used, one comes from vim's internal (this issue) and another from the terminal (#981).

To avoid giving further mess, I intentionally refrained from quoting #981. :)

**Comment by lanx-x** [comment]
thanks for reply.

**Comment by oblitum** [comment]
> > But in my opinion, the neovim's behavior is more reasonable.
> 
> I don't think so. Neovim has no GUI; therefore, the existence of guibg is nonsense and illogical, and the use of it is an abuse. I wonder how you could call that "more reasonable."

You may stop at that since you said yourself to have never tried NeoVim. guibg is perfectly logical for NeoVim since it was first created not to exist through its first frontend, the terminal, but to be embedded by any GUI frontend. You may think of NeoVim as a core that can bring Vim mode to other editors. Hence guibg should still make perfect sense.

Second, it was Vim that started with the idea of bringing GUI colors to the terminal by means of `termguicolors`. So if that's nonsense, it started with Vim. The Vim implementation of that is not uniform as [already explained](https://github.com/vim/vim/issues/981#issuecomment-242893385), NeoVim's implementation makes more sense indeed.

> > I don't know it's a bug or not, maybe I misunderstand the "termguicolors" option.
> 
> I think this issue invalid for vim because of its inaccurate description of the problem and irrational comparison with what one cannot compare with.
