### ISSUE TITLE
vim command hangs with error operation and ctrl+C can not stop it

### ISSUE THREAD

**Issue by haojue** [vim/vim#11209]
### Steps to reproduce

Run the following command and it hangs with error operation and ctrl+C can not stop it
1. vim test.sh | grep dict
Vim: Warning: Output is not to a terminal

### Expected behaviour

Even error operation will not cause hangs with error operation or if it hangs ctrl+C can stop it. 

### Version of Vim

version 8.0.1763

### Environment

Terminal: iTerm2
uname -a: 4.18.0-240.el8.s390x #1 SMP Wed Sep 23 05:12:04 EDT 2020 s390x s390x s390x GNU/Linux

cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run the following command and it hangs with error operation and ctrl+C can not stop it
> 1. vim test.sh | grep dict
> Vim: Warning: Output is not to a terminal
> 
> ### Expected behaviour
> 
> Even error operation will not cause hangs with error operation or if
> it hangs ctrl+C can stop it. 

Well, Vim is actually working, but CTRL-C is only an interrupt, it
doesn't make Vim exit.  There is a message to notify the user, but since
you redirected output you can't see it.

You can get out by typing :qa <Enter>.
But you probably can't guess that.

I think it is safe in this situation to make CTRL-C exit, so long as
there are no changed buffers.  I'll make a patch for that.


-- 
hundred-and-one symptoms of being an internet addict:
158. You get a tuner card so you can watch TV while surfing.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
