### ISSUE TITLE
`popup_filter` eats key mapping after timeout

### ISSUE THREAD

**Issue by cykerway** [vim/vim#11219]
### Steps to reproduce

~~~vim
set nocp
noremap <Space> :echo 'hello'<CR>
function Filter(winid, key)
    return v:true
endfunction
function Create()
    call popup_create('x', {
            \'filter': 'Filter',
            \'mapping': v:false,
            \'time': 2000,
            \})
endfunction
call Create()
~~~
1. Save this file as `a.vim`.
2. Run `vim -u NONE -c "so a.vim"`.
3. Press `<Space>` *once* after 2 seconds (when the popup window timeouts).
4. No message is shown. To see the message one needs to press `<Space>` again.

### Expected behaviour

Display message `1234` on first press of `<Space>`.

FYI it works correctly if `mapping` is set to `v:true`, but it _should_ work with `v:false` too because the popup has been closed and its settings shouldn't matter.

### Version of Vim

9.0.77

### Environment

Fedora 36.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ~~~vim
> set nocp
> noremap <Space> :echo 'hello'<CR>
> function Filter(winid, key)
>     return v:true
> endfunction
> function Create()
>     call popup_create('x', {
>             \'filter': 'Filter',
>             \'mapping': v:false,
>             \'time': 2000,
>             \})
> endfunction
> call Create()
> ~~~
> 1. Save this file as `a.vim`.
> 2. Run `vim -u NONE -c "so a.vim"`.
> 3. Press `<Space>` *once* after 2 seconds (when the popup window timeouts).
> 4. No message is shown. To see the message one needs to press `<Space>` again.
> 
> 
> ### Expected behaviour
> 
> Display message `1234` on first press of `<Space>`.
> 
> FYI it works correctly if `mapping` is set to `v:true`, but it _should_ work with `v:false` too because the popup has been closed and its settings shouldn't matter.
> 
> ### Version of Vim
> 
> 9.0.77

What I see is that after the popup disappears, the first key is not
mapped.  If you type space twice you'll see the message.

The reason is that Vim goes into the function to get the next character
while the popup shows, thus key mapping is then disabled.  When the
popup disappears it's still waiting for a key, mapping will be enabled
again after returning and the next time a character is obtained.

Changing this is tricky.  I don't think there is a simple, reliable way
to handle this.  Can we live with it?

-- 
hundred-and-one symptoms of being an internet addict:
172. You join listservers just for the extra e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cykerway** [comment]
> When the popup disappears it's still waiting for a key

Is it possible to send a key when the popup disappears, just to let it return from read?

**Comment by lacygoill** [comment]
> Is it possible to send a key when the popup disappears, just to let it return from read?

As a workaround, you could feed `<Ignore>` to the typeahead buffer when the popup is closed via an exit callback:
```vim
set nocp
noremap <Space> :echo 'hello'<CR>
function Filter(winid, key)
   return v:true
endfunction
function Create()
   call popup_create('x', {
           \'filter': 'Filter',
           \'mapping': v:false,
           \'time': 2000,
           \ 'callback': {-> feedkeys("\<Ignore>")}
           \})
endfunction
call Create()
```

**Comment by cykerway** [comment]
Thanks, the workaround works in my case. I'll close this now. Please leave a comment if you decide to fix this some day.
