### ISSUE TITLE
vim9script: Type-checking in map() fails to detect correct type

### ISSUE THREAD

**Issue by dezza** [vim/vim#11229]
### Steps to reproduce

```
vim9script
def g:Bug(): list<dict<string>>
  var t = [{"pattern": 'a'}]
  # E1012: Type mismatch; expected dict<string> but got string in map()
  var t2 = map(t, "v:val['pattern']")
  return t2
enddef

def g:TypedBug(): list<string>
  var t: list<dict<string>> = [{"pattern": 'a'}]
  # E1012: Type mismatch; expected list<string> but got list<dict<string>>
  var t2: list<string> = map(t, "v:val['pattern']")
  return t2
enddef

def g:ButWorks(): list<string>
  # works
  return [{"pattern": 'a'}]->map("v:val['pattern']")
enddef
```

### Expected behaviour

That it accurately detects `list<string>` as the correct type, and does not return `but got string in map()` when it is truly `list<string>`

### Version of Vim

9.0.0590

### Environment

OS: Microsoft Windows [Version 10.0.19044.2006] (WSL: Ubuntu 22.04.1 LTS)
Terminal: Windows Terminal 1.4.2281.0
$TERM = xterm-256color
Shell: zsh

### Logs and stack traces

`:disassemble g:Bug()`
```
  var t = [{"pattern": 'a'}]
   0 PUSHS "pattern"
   1 PUSHS "a"
   2 NEWDICT size 1
   3 NEWLIST size 1
   4 SETTYPE list<dict<string>>
   5 STORE $0

  # E1012: Type mismatch; expected dict<string> but got string in map()
  var t2 = map(t, "v:val['pattern']")
   6 LOAD $0
   7 PUSHS "v:val['pattern']"
   8 BCALL map(argc 2)
   9 CHECKTYPE list<dict<string>> stack[-1] arg 1
  10 SETTYPE list<dict<string>>
  11 STORE $1

  return t2
  12 LOAD $1
  13 RETURN
```
`:disassemble g:ButWorks()`
```
  return [{"pattern": 'a'}]->map("v:val['pattern']")
   0 PUSHS "pattern"
   1 PUSHS "a"
   2 NEWDICT size 1
   3 NEWLIST size 1
   4 PUSHS "v:val['pattern']"
   5 BCALL map(argc 2)
   6 CHECKTYPE list<string> stack[-1]
   7 RETURN
```
```

**Comment by lacygoill** [comment]
Maybe the error message could be improved, but I think it's working as intended.
```vim
vim9script
def g:Bug(): list<dict<string>>
  var t = [{"pattern": 'a'}]
  var t2 = map(t, "v:val['pattern']")
  return t2
enddef
g:Bug()
```
    E1012: Type mismatch; expected dict<string> but got string in map()

`t` is declared with the type `list<dict<string>>`.  This means that all items in the list must have the type `dict<string>`.  But `map()` replaces all dictionary items (`v:val`) with their keys (`v:val['pattern']`), which are strings.  IOW, it mutates the list by changing the type of the items from `dict<string>` to `string`.  That's disallowed for a variable with a declared type.  This is documented somewhere below [`:help type-checking`](https://vimhelp.org/vim9.txt.html#type-checking):

   > One consequence is that the item type of a list or dict given to |map()| must
   > not change, if the type was declared.  This will give an error in Vim9
   > script: >
   >         var mylist: list<number> = [1, 2, 3]
   >         echo map(mylist, (i, v) => 'item ' .. i)
   > <       E1012: Type mismatch; expected number but got string in map() ~

And that's what the error message is trying to explain.  It expects the new items to have the type `dict<string>`:

    E1012: Type mismatch; expected dict<string> but got string in map()
                          ^-------------------^

But they don't.  They have the type `string`:

    E1012: Type mismatch; expected dict<string> but got string in map()
                                                ^------------^

BTW, here is a simplified MRE:
```vim
vim9script
var ld = [{k: 's'}]
ld->map((_, d) => d.k)
```
    E1012: Type mismatch; expected dict<string> but got string in map()

The solution is to make a copy first.  Either via [`mapnew()`](https://vimhelp.org/builtin.txt.html#mapnew%28%29), or via [`copy()`](https://vimhelp.org/builtin.txt.html#copy%28%29) or [`deepcopy()`](https://vimhelp.org/builtin.txt.html#deepcopy%28%29):
```vim
vim9script
var ld = [{k: 's'}]
ld->copy()->map((_, d) => d.k)
```
    no error

Applied to your function, it gives:
```vim
vim9script
def g:Bug(): list<dict<string>>
  var t = [{"pattern": 'a'}]
  var t2 = t->copy()->map("v:val['pattern']")
  return t2
enddef
g:Bug()
```
    E1012: Type mismatch; expected list<dict<string>> but got list<string>

But as you noticed, an error is still given.  It's not the same one though.  The message is different, but more importantly, it's given from a different line:  the 3rd one, not the 2nd one as originally.  Now, the issue is that you return a list of strings (remember that `map()` replaces every dictionary with one of its key, which is a string).  But you declared that the function should return a list of *dictionary* of strings.  That doesn't match.  The solution is to replace `list<dict<string>>` with `list<string>` in the declared return type of the function:

                         ✘
                 v----------------v
    def g:Bug(): list<dict<string>>

                       ✔
                 v----------v
    def g:Bug(): list<string>

Which gives this code:
```vim
vim9script
def g:Bug(): list<string>
  var t = [{"pattern": 'a'}]
  var t2 = t->copy()->map("v:val['pattern']")
  return t2
enddef
g:Bug()
```
    no error

---
```vim
vim9script
def g:TypedBug(): list<string>
  var t: list<dict<string>> = [{"pattern": 'a'}]
  # E1012: Type mismatch; expected list<string> but got list<dict<string>>
  var t2: list<string> = map(t, "v:val['pattern']")
  return t2
enddef
g:TypedBug()
```
    E1012: Type mismatch; expected list<string> but got list<dict<string>>

It's the same issue.  Make a copy before calling `map()`:

                             ✘
                           v---v
    var t2: list<string> = map(t, "v:val['pattern']")

                                ✔
                           v---------v
    var t2: list<string> = map(copy(t), "v:val['pattern']")
```vim
vim9script
def g:TypedBug(): list<string>
  var t: list<dict<string>> = [{"pattern": 'a'}]
  # E1012: Type mismatch; expected list<string> but got list<dict<string>>
  var t2: list<string> = map(copy(t), "v:val['pattern']")
  return t2
enddef
g:TypedBug()
```
    no error

---
```vim
vim9script
def g:ButWorks(): list<string>
  # works
  return [{"pattern": 'a'}]->map("v:val['pattern']")
enddef
```
This works because `[{"pattern": 'a'}]` is not assigned to a variable with a given type.  Vim has no reason to enforce the type of the list not to change.  In the help, this is explained by "if the type was declared":

   > One consequence is that the item type of a list or dict given to |map()| must
   > not change, **if the type was declared**.

**Comment by dezza** [comment]
That makes perfect sense @lacygoill thanks a lot for helping!
