### ISSUE TITLE
Wrong syntax highlighting after put

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11247]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
syn region hsBlockComment start="{-"  end="-}" contains=hsBlockComment
hi def link hsBlockComment Comment
call setline(1, ['{-', '-', '-}', '- Test'])
call feedkeys('GddPPP2jp', 'tni')  " Note: no x flag
```
3. The last two lines are not highlighted as Comment

### Expected behaviour

All lines highlighted as Comment, as after a `:redraw!`

### Version of Vim

9.0.354

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
This bug doesn't happen if the `feedkeys()` is called on startup (e.g. using `-S` to source the file). The keys need to be fed later in this case.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Source the following file:
> ```vim
> syn region hsBlockComment start="{-"  end="-}" contains=hsBlockComment
> hi def link hsBlockComment Comment
> call setline(1, ['{-', '-', '-}', '- Test'])
> call feedkeys('GddPPP2jp', 'tni')  " Note: no x flag
> ```
> 3. The last two lines are not highlight as Comment
> 
> ### Expected behaviour
> 
> All lines highlighted as Comment, as after a `:redraw!`

You have not defined any syncing.  When using a region that crosses line
boundaries you need to define syncing, otherwise Vim does not know it
has to look in previous lines for a region to start.

For this example you might want to use something like:

syn sync match hsCommentStart grouphere hsBlockComment "{-"

-- 
'Psychologist' -- Someone who looks at everyone else when
an attractive woman enters the room.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
This line is a simplified version of a line in `runtime/syntax/haskell.vim`. I guess there is a bug in haskell syntax file then.
