### ISSUE TITLE
t_8u not working correctly in wezterm

### ISSUE THREAD

**Issue by dotdash** [vim/vim#11253]
### Steps to reproduce

Run `vim -u /dev/null`

Execute
```
:let &t_8u="\e[58;2;%lu;%lu;%lum"
:let &t_Cs = "\e[4:3m"
:let &t_Ce = "\e[4:0m"
:hi CursorLine cterm=undercurl guisp=red
:set termguicolors cursorline
```

### Expected behaviour

The undercurl is shown in red.

### Version of Vim

9.0.628

### Environment

Ubuntu 22.04
wezterm
TERM=wezterm
bash

### Logs and stack traces

```shell
It seems that there's no termresponse for wezterm, so `write_t_8u_state` stays `FALSE` and `t_u8` is never used.

termprops:
`{'mouse': 'u', 'cursor_style': 'y', 'underline_rgb': 'u', 'cursor_blink_mode': 'y'}`

`v:termresponse` is empty.
```

**Comment by brammool** [comment]
Since this works with other terminals, you might want to ask the wezterm authors to fix it on their side.

**Comment by brammool** [comment]
> This is the same issue as https://github.com/vim/vim/issues/10239
> It's a regression introduced by patch [8.2.4777](https://github.com/vim/vim/releases/tag/v8.2.4777)
> 
> Since that patch, Vim waits for a termresponse before outputting `t_8u`, which from the user's point of view might be unexpected: if they've set the terminal option with an explicit value, they probably expect it to be output no matter what.  And if Vim doesn't get a termresponse, then it doesn't output `t_8u`, and underlines are not colored.
> 
> Here, `$TERM` is set with the value `wezterm`, which Vim doesn't recognize as an xterm compatible terminal.  Same issue with `alacritty` and possibly other terminals.  As a result, [`'t_RV'`](https://vimhelp.org/term.txt.html#%27t_RV%27) is not set, Vim doesn't request the terminal version, never receives a termresponse, and never outputs `t_8u`.
> 
> As a workaround, one can set `t_RV` manually:
> 
>     if &term =~ 'wezterm'
>         let &t_RV = "\<Esc>[>c"
>     endif
> 
> If we don't fix this issue, at least we might want to document how to
> enable the feature as suggested in the patch posted in [this
> comment](https://github.com/vim/vim/issues/10239#issuecomment-1107182341).

So, what would be the best solution?

- When t_8u was set by the user (in .vimrc) then always output it, no
  matter what the value of write_t_8u_state is?
- When t_RV is empty then always output t_8u, no matter what the value
  of write_t_8u_state is?

I don't think trying to support any (rarily used or not) terminal name
inside Vim is a good solution, there is a new one every month it seems.
A new terminal should at least provide a proper termcap/terminfo entry.


-- 
hundred-and-one symptoms of being an internet addict:
233. You start dreaming about web pages...in html.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dotdash** [comment]
I have terminfo entries for wezterm installed following the instructions found at https://wezfurlong.org/wezterm/config/lua/config/term.html yet things still fail (and I had to manually configure t_8f and t_8b as well). I'm not familiar with termcal/-info but if you're saying that wezterm's terminfo is wrong, I'm happy to open an issue over there as well.

**Comment by brammool** [comment]
>    > So, what would be the best solution?
> 
> [According to the spec](https://sw.kovidgoyal.net/kitty/underlines/),
> we should query the terminfo database for the `Su` boolean capability:
> 
>    > To detect support for this feature in a terminal emulator, query
>    > the terminfo database for the Su boolean capability.

The Kitty docs are in no way definitive.  The Linux man page does not
appear to mention "Su": https://man7.org/linux/man-pages/man5/terminfo.5.html
But it also doens't mention "8f" and "8b", which we do use.
There is also this IBM doc: https://www.ibm.com/docs/en/aix/7.1?topic=formats-terminfo-directory

I still have a vague plan to have the terminal provide its current and
accurate capabilities, instead of relying on some disconnected database
that always appears to be slightly wrong.  And then there is the user
setting $TERM to "xterm" because it seems to work better...

> Unfortunately, it's missing from the terminfo description of some terminals:
> 
>     # OK
>     $ infocmp -1x xterm-kitty | grep -i Su
>             Su,
> 
>     # MISSING
>     $ infocmp -1x alacritty | grep -i Su
> 
> And I don't even have a terminfo description for wezterm, even after
> [installing](https://wezfurlong.org/wezterm/install/linux.html#installing-on-ubuntu-and-debian-based-systems)
> it with a proper `.deb` package on Ubuntu.

It's a known problem that when a terminal is installed the
terminfo/termcap may not match the exact version.  Also, some terminals
have settings that can be changed dynamically.

> Until the `Su` capability is included inside more terminal
> descriptions, I guess the best solution is to output `t_8u` no matter
> what if it is set.  And to document how to set it.  From there, it's
> the user's responsibility to correctly read the documentation and set
> the option when they know that their terminal supports the feature.

We cannot rely on every user understanding how it all works and figuring
out the right settings.

>    > A new terminal should at least provide a proper termcap/terminfo entry.
> 
> I agree.  But people using a terminal with no terminal description (or
> an incomplete one) will still open issues here if they can't have
> colored underlines inside Vim.  Outputting `t_8u` unconditionally when
> it has been set would reduce the number of reported issues.

There is a reason it was implemented this way, that is why I am asking
about the two ways we might solve this without dropping the mechanism we
added because it was needed.

-- 
hundred-and-one symptoms of being an internet addict:
236. You start saving URL's in your digital watch.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
>    > The Kitty docs are in no way definitive.
> 
> I mentioned them because the feature comes from Kitty.  But OK, it's
> still too recent for terminfo to include it, and there is no guarantee
> that it does with this particular name (or at all).
> 
>    > I still have a vague plan to have the terminal provide its current and
>    > accurate capabilities, instead of relying on some disconnected database
>    > that always appears to be slightly wrong.
> 
> That would be good.  I think this is one of the most frequent issues
> that new users encounter:  a terminal option which was not set
> correctly because Vim was not able to properly detect a given terminal
> capability.

The main obstacle is to find a way for an application (like Vim) to
receive the codes.  Using stdout/stderr is bound to have problems.  We
have this with xterm when receiving keycodes, and that's only a limited
amount of data.  For a local system it could work to pass a named pipe.
But it would be important to also support remote systems (through tmux
and ssh), since then termcap/terminfo are most likely to be wrong.

>    > We cannot rely on every user understanding how it all works and figuring
>    > out the right settings.
> 
> Currently, they already have to understand how it works if they use a
> terminal which is not recognized as compatible with xterm.  Or if they
> want to set a different color for the text above the underline.  Or if
> they use tmux.
> 
> But yes, if Vim could automatically set all the terminal options with
> the right values, it would be even better.
> 
>    > There is a reason it was implemented this way, that is why I am asking
>    > about the two ways we might solve this without dropping the mechanism we
>    > added because it was needed.
> 
> FWIW, I would choose the first suggestion:  if the user has set `t_8u`
> in their vimrc, then assume that they know that their terminal
> supports the feature, and output the `t_8u` sequence no matter what
> the value of `write_t_8u_state` is.

Yes, I also think that the first suggestion is likely the best
solution.  Let me implement that and then await responses...

-- 
"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
 - Helen Rowland

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
