### ISSUE TITLE
RfC: Open access to callstack

### ISSUE THREAD

**Issue by LucHermitte** [vim/vim#1125]
It'll be nice to have an official way to access the callstack from the current function. I know for certain the information is somewhere as I've found a very dirty trick to access it: I throw a dummy exception and I decode `v:throwproint`. See:  https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/exception.vim#L51 and https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/log.vim#L250

Alas this approach is really clumsy and not always very robust as the exact message produced may know small variations, it's locale dependent, and IIRC changes may happen in the format from one vim version to the next.

In an ideal world (as far as I'm concerned in order to avoid transforming the information obtained), a `callstack()` function would return the list of call information. Each information would contain:
- "script": filename of the vimscript where the function is defined
- "pos":    absolute line number in this script file
- "fname":  function name
- "fstart": line where the function is defined in the script (not mandatory, but a necessary step to deduce the 3 first information)
- "offset": offset, from the start of the function, of the line the current call is made.

The 3 first information are what is really interesting to fill the quickfix list. The 3rd and the 5th are what we have in `v:throwpoint`.

**Comment by brammool** [comment]
Luc Hermitte wrote:

> It'll be nice to have an official way to access the callstack from the
> current function. I know for certain the information is somewhere as
> I've found a very dirty trick to access it: I throw a dummy exception
> and I decode `v:throwproint`. See:
> https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/exception.vim#L51
> and
> https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/log.vim#L250
> 
> Alas this approach is really clumsy and not always very robust as the
> exact message produced may know small variations, it's locale
> dependent, and IIRC changes may happen in the format from one vim
> version to the next.
> 
> In an ideal world (as far as I'm concerned in order to avoid
> transforming the information obtained), a `callstack()` function would
> return the list of call information. Each information would contain:
> - "script": filename of the vimscript where the function is defined
> - "pos":    absolute line number in this script file
> - "fname":  function name
> - "fstart": line where the function is defined in the script (not mandatory, but a necessary step to deduce the 3 first information)
> - "offset": offset, from the start of the function, of the line the current call is made.
> 
> The 3 first information are what is really interesting to fill the
> quickfix list. The 3rd and the 5th are what we have in `v:throwpoint`.

What do you need this for?

## 

MORTICIAN:    Bring out your dead!
              [clang]
              Bring out your dead!
              [clang]
              Bring out your dead!
CUSTOMER:     Here's one -- nine pence.
DEAD PERSON:  I'm not dead!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
2016-09-27 18:44 GMT+03:00 Luc Hermitte vim-dev-github@256bit.org:

> It'll be nice to have an official way to access the callstack from the
> current function. I know for certain the information is somewhere as I've
> found a very dirty trick to access it: I throw a dummy exception and I
> decode v:throwproint. See:
> https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/exception.vim#L51
> and
> https://github.com/LucHermitte/lh-vim-lib/blob/master/autoload/lh/log.vim#L250
> 
> Alas this approach is really clumsy and not always very robust as the exact
> message produced may know small variations, it's locale dependent, and IIRC
> changes may happen in the format from one vim version to the next.
> 
> In an ideal world (as far as I'm concerned in order to avoid transforming
> the information obtained), a callstack() function would return the list of
> call information. Each information would contain:
> 
> "script": filename of the vimscript where the function is defined
> "pos": absolute line number in this script file
> "fname": function name
> "fstart": line where the function is defined in the script (not mandatory,
> but a necessary step to deduce the 3 first information)
> "offset": offset, from the start of the function, of the line the current
> call is made.
> 
> The 3 first information are what is really interesting to fill the quickfix
> list. The 3rd and the 5th are what we have in v:throwpoint.

I like the idea, but with some modifications:
1. No 'script' or 'fstart', supply 'func' with funcref (as of
   funcref(), not function()) instead. Define `get()` arguments:
   - `get(fref, 'sid')`: script ID, number (additionally have
     sid2sfname and sfname2sid functions)
   - `get(fref, 'body')`: function body, list
   - `get(fref, 'signature')`: function signature: dictionary like
     `{'args': ['foo', 'bar'], 'varargs': v:true, 'dict': v:true,
     'closure': v:true}`
   - `get(fref, 'sline')`: line where function is defined
   - `get(fref, 'slines')`: list of list of numbers, used to translate
     body indexes (what is returned by `get(fref, 'body')`) to real script
     line numbers.
2. `offset` should be in `get(fref, 'body')` indexes (function may be
   generated and created by a single `:execute` line, in this case
   `get(fref, 'slines')` will return something like `[[42], [42], [42]]`:
   each line in body corresponds to one and the same line in script
   file).
3. `args`: a: dictionary
4. `locals`: l: dictionary
5. `script_globals`: s: dictionary, may be absent. Alternatively:
   `sid2vars()` function

Reasoning: your variant seems to be useful mostly for giving fancier
error messages, which is good for offline remote debugging (I mean,
debugging in case when bug occures only on user machine), but that’s
all. My is targeted at debugging the problem myself:
1. sid2sfname/sfname2sid functions: I always wanted to make it easier
   to access <SID> which is used in a number of places: mostly for quirks
   like defining mappings with <SID> in another file (requires manual
   <SID> expansion). This is always possible to work around, but better
   have functions.
2. body: in addition to making it easier to print Python-style
   tracebacks with access to the function body this also makes it easier
   to serialize function when I have a list. And `:function` output
   parsing does not work in general: try defining function with control
   character inside and determine where you see literal `^[` and where
   there is escape.
3. signature: again, easier to serialize. Though this time `:function`
   parsing should work fine, it would be harder to use if signature is
   needed for something, but serializing (as an example: some
   plugin-defined callback which supplies funcref as much arguments as it
   can handle like with current `map()` situation).
4. sline+slines: Only for pretty tracebacks, I do not see other purposes yet.
5. args/locals/script_globals: needed for postmortem debugging. Also
   useful for offline remote debugging (i.e. you ask user to enable some
   “verbose” mode which will serialize and record all related variables
   and this can be sent to you).
6. For optimization purposes I sometimes write code that generates a
   function and then calls it, so `funcref()` and not function name:
   function names are useless in this case because most likely function
   is a dictionary one here and it may have vanished at the point Vim
   will check for the next character and I can do anything manually (i.e.
   after function which generates something optimized have finished
   executing).

As a summary: my proposal is needed for
- fancier error messages
- postmortem debugging
- remote offline debugging
- function serialization

---

Most of the above looks like something easy to implement: information
is already there, just needs generating a VimL object without
computing anything or any modifications to code not in `f_get` or
(new) `f_callstack` (gets information about the currently processed
point). (New) `f_throwstack` (callstack at the point where exception
occures, for use in `:catch` block) should be harder (do not remember
what information survives by the point Vim enters :catch, but pretty
sure that something out of what is needed for throwstack() to work
will be missing). `slines` AFAIK is not that easy to implement right,
but I would not say it is useful enough to spend time on if it will be
hard.

Without throwstack() (which Luc Hermitte did not suggest, did he?) new
changes will be useful only for `log.vim` or similar libraries’ users,
limited to the cases when author did call logging function,
throwstack() should be useful for debugging any plugin.

**Comment by LucHermitte** [comment]
> What do you need this for?

I have two use cases nowadays:
1.  I use it to log what my scripts do just with calls to `call s:Verbose('bla %1 bli %2', mystring, mydict)`. As you see I don't fill the scriptname nor line numbers. And yet, when I ask logs to be produced in the quickfix window I can obtain things like:

```
autoload/lh/tags.vim|636| Run ctags on UpdateTags_for_All (forcing)
autoload/lh/tags.vim|158| Register: cd /home/me/dev/Optims/src/OTB && ctags  --tag-relative=yes --c++-kinds=+pf --fields=+imaSft --extra=+q   --languages=C,C++ -f tags -R
autoload/lh/tags.vim|782| Updating spellfile `/home/me/dev/Optims/src/OTB/code-symbols-spell.utf-8.add`
autoload/lh/tags.vim|1250| 107746 tag names filtered in 0.429986s
autoload/lh/tags.vim|1272| 107746 names obtained in 0.635885s
autoload/lh/tags.vim|1274| 60633 tag names uniquelly sorted in 0.122092s
autoload/lh/tags.vim|785| 60633 symbols obtained in 0.792411s
autoload/lh/tags.vim|789| spellfile built in 0.407464s from `/home/me/dev/Optims/src/OTB/code-symbols-spell.utf-8.add`
```
1. I also use it in my viml unit-testing framework to trace the stack when exceptions are thrown. Again, I fill the quickfix window.

```
tests/lh/let.vim|| SUITE <[lh-vim-lib] Testing LetIfUndef command>
tests/lh/let.vim|| function <SNR>185_UTMake[6]..lh#UT#run[5]..lh#UT#check[23]..<SNR>231_RunOneFile[11]..<SNR>231_RunOneTest[8]..<SNR>232_Test_let_if_undef_funcref[4]..lh#let#if_undef, ligne 6: Cannot set ['g:Dummyg_test function(''exists'')']: Vim(let):E704: Le nom d'une Funcref doit commencer par une majuscule : value @ function <SNR>185_UTMake[6]..lh#UT#run[5]..lh#UT#check[23]..<SNR>231_RunOneFile[11]..<SNR>231_RunOneTest[8]..<SNR>232_Test_let_if_undef_funcref[4]..lh#let#if_undef[3]..<SNR>55_BuildPublicVariableNameAndValue, ligne 4
autoload/lh/let.vim|123| called from lh#let#if_undef[6]
tests/lh/let.vim|333| called from s:Test_let_if_undef_funcref[4]
/home/me/.vim/addons/UT/ftplugin/vim/vim_UT.vim|58| called from s:UTMake[6]
tests/lh/let.vim|| SUITE<[lh-vim-lib] Testing LetIfUndef command> 10/11 tests successfully executed.
```

What will a builtin `callstack` function change? (As i'm already able to do what I need) It won't be influenced by the current locale (as `v:throwpoint` contains `line` in English, `ligne`in French, etc), and it will permit me to simplify my code.

**Comment by ZyX-I** [comment]
> I have two use cases nowadays:

Yeah, both is just a bit better errors. You could extend this to the point where it will look like Python tracebacks (printed text) (Python has one of the best error reporting I have seen) most of time (and without any help from Vim developers: e.g. use some gettext binding to your favourite language to parse Vim language files, the only other thing you need to have Python-like tracebacks is `:function` output), but not to the point where it will look like Python tracebacks (objects): they also provide access to globals and locals at the point where exception is thrown.

I do not like the original suggestion, but I do think that `callstack()` and `throwstack()` functions as well as further modifications to `get(fref, …)` are very nice to have. Though I think mistook what @LucHermitte means by `callstack()`: it is my `throwstack()` with much less information.

**Comment by LucHermitte** [comment]
> > I have two use cases nowadays:
> > Yeah, both is just a bit better errors.

It's not just about errors. The first use case is about logging what happens in complex plugins. My second use case is indeed about reporting errors.

> Though I think mistook what @LucHermitte means by callstack(): it is my throwstack() with much less information.

Indeed, I did not need as much information as what you've proposed. `callstack()` and `throwstack()` are closely related though.

**Comment by LucHermitte** [comment]
It seems that [patch 8.2.1297](https://github.com/vim/vim/commit/a5d0423fa16f18b4576a2a07e50034e489587a7d) implements this feature I'm good to close the issue.
