### ISSUE TITLE
`:help` command sometimes doesn't respect the `splitbelow` option

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11319]
### Steps to reproduce

1. Run `vim --clean -c 'set splitbelow | vsplit'`
2. Execute `:help`
3. Result: The help window is opened above the vertical split spanning the entire width.

It seems do depend on the size of the terminal window.

Screenshots before running `:help`:
![screenshot-2022-10-09_134157](https://user-images.githubusercontent.com/6266600/194754972-2ee275cd-bae1-4e1d-984b-9acc3d3ef7ea.png)

Screenshot after running `:help`:
![screenshot-2022-10-09_134201](https://user-images.githubusercontent.com/6266600/194754973-e7ca8274-a3b3-460f-9a08-db375a61d879.png)

When I go into fullscreen, the help window is opened below the left window as expected.

### Expected behaviour

I would have expected `:help` to always open the split below the left window. This used to be the case but seemed to have been changed in a recent version.

### Version of Vim

9.0.701

### Environment

Linux

**Comment by bfrg** [comment]
Okay, it seems when the window width is smaller than 80, `:help` will try to use the full width and opens the split above any vertical split.

**Comment by brammool** [comment]
I do not consider this a bug.  "splitbelow" is for normal windows, the help window isn't really normal.  E.g. if you open help and close it, the window layout is restored.  I don't think this changed recently.

**Comment by bfrg** [comment]
It seems like the `splitbelow` option is taken into account for `:help` when there aren't any vertical split.

**Comment by brammool** [comment]
> It seems like the `splitbelow` option is taken into account for
> `:help` when there aren't any vertical split.

Hmm, I suppose we could check 'splitbelow' and put the help at the
bottom instead of at the top.  For me I somehow expect help to always go
at the top.  But it does use 'splitbelow' if the window is wide enough,
thus it's inconsistent now.

-- 
"A mouse can be just as dangerous as a bullet or a bomb."
             (US Representative Lamar Smith, R-Texas)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
