### ISSUE TITLE
= does not work as expected when in lisp mode

### ISSUE THREAD

**Issue by graywolf** [vim/vim#11327]
### Steps to reproduce

1. vim -u NONE -c 'set nocp lisp ai indentexpr=1'
2. insert (if (= 0 0) and press enter
3. observe that cursor is under i
4. write 1) to finish the form
5. gg=G
6. 1) jumps one column to the right

### Expected behaviour

6. nothing happens

Documentation for 'lisp' states that it modifies = to use the same indentation algorithm. Since my equalprg is empty, I would expect no change to happen on gg=G, since it is already formatted correctly according to the indentexpr.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 22 2022 17:41:25)Included patches: 1-5000

### Environment

OS: Alpine 3.16
terminal: rxvt-unicode
$TERM: rxvt-unicode-256color
shell: 5.1.16(1)-release

**Comment by brammool** [comment]
Lisp indenting isn't very sophisticated.  I don't plan to work on this, but if someone wants to spend time on it, feel free.

**Comment by brammool** [comment]
> Would this work?

This changes behavior, also using 'indentexpr' when 'lisp' is set.

I would suggest adding a 'lispoptions' variable, which would be similar
to 'cinoptions', but with different flags.  One of these flags would
then be "use 'indentexpr' for lisp indenting".

How about the lispindent() function?  It can be used two ways: to get
the result of lisp indenting, like the "==" command would do, or to be
used in 'indentexpr' to get the indent for Lisp from the internal logic.
Perhaps an argument can select between them.


-- 
Q: How do you tell the difference between a female cat and a male cat?
A: You ask it a question and if HE answers, it's a male but, if SHE
   answers, it's a female.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > This changes behavior
> 
> Well, yes, that is the point. Current behavior is, to put it politely,
> unexpected.
> 
> First let me say that if you will insist on doing this via the
> 'lispoptions', I will do it that way, since I really want this fixed.
> But first I would like to make sure we are on the same page what the
> current behavior is.
> 
> Currently, when I compile vim from current master and start it like this:
> 
> 	./src/vim -u NONE -c 'set nocp lisp ai indentexpr=1'
> 
> and then type `(x` on the first line, `1` on the second, and `2` on the third
> line, it will end up indented like this:
> 
> 	(x
> 	 1
> 	 2)
> 
> So the 'indentexpr' *is* respected in the insert mode as far as the
> indentation goes. However, when I do `gg=G`, it will change the buffer
> to
> 
> 	(x
> 	  1
> 	  2)
> 
> So the 'indentexpr' *is not* respected for the = operator. You will
> end up with two different indentations depending on if you wrote it or
> used the = operator.
> 
> That is in my opinion quite unexpected.

Yes, this is a bug.  In open_line() there is first a check for lisp
indenting, and in this example it gets applied.  But next there is a
check for C-indenting, and because indentexpr is set this also gets
executed.  There is an "else" missing here.

> So yes, I can try to modify the patch to add 'lispoptions' that will
> allow users to pick if they want to use indentexpr for = operator
> (opt-in), while it will always be used indenting while in insert mode
> (same as now). I just want to make sure that is what you actually want
> before I embark on a journey to learn how to make new vim option.

I think that in all cases the indent used when entering text and when
using the "=" operator should be the same.  I'll make a patch for
open_line().

-- 
An indication you must be a manager:
You can explain to somebody the difference between "re-engineering",
"down-sizing", "right-sizing", and "firing people's asses".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > I'll make a patch for open_line()
> 
> Great, I can confirm that with 9.0.0754, my .vimrc stops working. Is
> there any way to get the original behavior back? I guess no, right?

You mean that 'indentexpr' is now not used when 'lisp' is set?  Well,
that is what we would need 'lispoptions' for.


-- 
ARTHUR:          What does it say?
BROTHER MAYNARD: It reads ... "Here may be found the last words of Joseph of
                 Aramathea." "He who is valorous and pure of heart may find
                 the Holy Grail in the aaaaarrrrrrggghhh..."
ARTHUR:          What?
BROTHER MAYNARD: "The Aaaaarrrrrrggghhh..."
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Thank you for patch 761, I can confirm it works as expected.
> 
> I went in a bit different direction (int b_lispo_int_inde and
> parse_lispo basically mirroring parse_cino), but I'm able to follow
> your code.  However one thing I'm unsure about. Is somewhere
> documented how does OPT_BUF(BV_xx) and
> OPT_BOTH(OPT_BUF(BV_xx)) differ and when to use which one? I went with
> OPT_BOTH (assuming from global-local that it is what I want), so I
> would like to learn why I made wrong choice.

I only did it for one item "expr" for now.  When there is more than one
item it actually needs to be parsed.  'cinoptions' uses single character
flags, which at the time was OK, but I would not do that for a new
option.  Something like "expr:1,for:4,else:s" is going to be much more
readable.  We can probably use the "s" flag and the like for a
shiftwidth, like 'cinoptions' does.

Some options are global-local, which is for backwards compatibility.
The option used to be global, but at some point we realised that it
should be local, and found this solution that makes it local without
breaking backwards compatibility.  Since 'lispoptions' is new we can
just make it local.

Please try out the current implementation.  If you want to tweak more of
Lisp indenting there is now a place to add it.

-- 
Every exit is an entrance into something else.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
