### ISSUE TITLE
Long virtual text not displayed correctly when `wrap` is disabled, and cursor is not displayed at the correct position

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11320]
### Steps to reproduce

1. Run `vim --clean test.vim -S test.vim`, with

```vim
vim9script

colorscheme habamax
set nowrap
prop_type_add('test', {highlight: 'Error'})

const opts: dict<any> = {
    type: 'test',
    text: range(50)->join(' '),
    text_align: 'after',
    text_padding_left: 2
}

prop_add(1, 0, opts)
prop_add(1, 0, opts)
prop_add(1, 0, opts)
```

2. Move the cursor to the bottom of the buffer by pressing `G`.
3. Result: The cursor does not jump to the last line.

Screenshot:
![screenshot-2022-10-09_184733](https://user-images.githubusercontent.com/6266600/194769257-afe3fc9e-4631-454e-b568-aa4b46539af2.png)

Furthermore, the 2nd and 3rd virtual lines are displayed below the first line even though `text_align` is set to `after`.

At least the issue with the cursor disappears when `wrap` is enabled.

### Expected behaviour

1. Cursor should always be drawn at the right position.
2. When there are multiple virtual text-properties with `text_align` set to `after`, they should always be drawn one after another in one line like in the following screenshot:
![screenshot-2022-10-09_190004](https://user-images.githubusercontent.com/6266600/194769816-1182aeea-d792-42ad-b5ec-8107b355764b.png)

### Version of Vim

9.0.706

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean test.vim -S test.vim`, with
> 
> ```vim
> vim9script
> 
> colorscheme habamax
> set nowrap
> prop_type_add('test', {highlight: 'Error'})
> 
> const opts: dict<any> = {
>     type: 'test',
>     text: range(50)->join(' '),
>     text_align: 'after',
>     text_padding_left: 2
> }
> 
> prop_add(1, 0, opts)
> prop_add(1, 0, opts)
> prop_add(1, 0, opts)
> ```
> 
> 2. Move the cursor to the bottom of the buffer by pressing `G`.
> 3. Result: The cursor does not jump to the last line.
> 
> Screenshot:
> ![screenshot-2022-10-09_184733](https://user-images.githubusercontent.com/6266600/194769257-afe3fc9e-4631-454e-b568-aa4b46539af2.png)
> 
> Furthermore, the 2nd and 3rd virtual lines are displayed below the first line even though `text_align` is set to `after`.
> 
> At least the issue with the cursor disappears when `wrap` is enabled.

This turns out to be a complicated problem.  Let me first fix that the
"after" properties are displayed on a separate line.  The cursor
position should also be fixed then.

However, when moving the cursor further right, causing the text to
shift left, the "after" property always shows, not skipping the start.
I'll tackle that later.


-- 
GUARD #2:  It could be carried by an African swallow!
GUARD #1:  Oh, yeah, an African swallow maybe, but not a European swallow,
           that's my point.
GUARD #2:  Oh, yeah, I agree with that...
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
