### ISSUE TITLE
A-Z keys with control modifier behave inconsistently when mapped in 'langmap'

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11395]
With the following 'langmap' option and the following mapping:
```vim
set langmap=RL
nnoremap <C-L> <Cmd>echomsg 'Ctrl-L'<CR>
```
1. In a terminal without modifyOtherKeys, pressing Ctrl-R redos a change.
2. In a terminal with modifyOtherKeys or GUI, pressing Ctrl-R triggers the Ctrl-L mapping, because 'langmap' is applied to the `R` after the modifier to changed it to `L` when matching a mapping.
3. If the Ctrl-L mapping is removed, pressing Ctrl-R redos a change.

This is inconsistent in two ways:
1. With the Ctrl-L mapping, 'langmap' is applied to the `R` in a terminal with modifyOtherKeys or GUI, but not applied to the `R` in a terminal without modifyOtherKeys.
2. Whether the Ctrl-L mapping exists affects whether 'langmap' is applied to the `R`

Not sure what is a best way to make it more consistent. The easiest and most consistent solution may be never applying 'langmap' to a key with a modifier, but this may change current behavior too much, and there may be people who rely on the current behavior.

**Comment by brammool** [comment]
> With the following 'langmap' option and the following mapping:
> ```vim
> set langmap=RL
> nnoremap <C-L> <Cmd>echomsg 'Ctrl-L'<CR>
> ```
> 1. In a terminal without modifyOtherKeys, pressing Ctrl-R redos a change.
> 2. In a terminal with modifyOtherKeys or GUI, pressing Ctrl-R triggers the Ctrl-L mapping, because 'langmap' is applied to the `R` after the modifier to changed it to `L` when matching a mapping.
> 3. In the Ctrl-L mapping is removed, pressing Ctrl-R redos a change.
> 
> This is inconsistent in two ways:
> 1. With the Ctrl-L mapping, 'langmap' is applied to the `R` in a terminal with modifyOtherKeys or GUI, but not applied to the `R` in a terminal without modifyOtherKeys.
> 2. Whether the Ctrl-L mapping exists affect whether 'langmap' is applied to the `R`
> 
> Not sure what is a best way to make it more consistent. The easiest
> and most consistent solution may be never applying 'langmap' to a key
> with a modifier, but this may change current behavior too much, and
> there may be people who rely on the current behavior.

What 'langmap' does should not depend on modifyOtherKeys or using the
GUI.  It should work the same way when using another terminal (with the
same input method and language settings).

It could be argued that if 'langmap' changes R to L, then changing CTRL-R
to CTRL-L would be OK.  But whether that happens should be controlled by
the user, doing it without asking makes it impossible to prevent it.

Although this may change current behavior, I doubt many users depend on
it, since it wasn't done intentionally.

I would think not applying 'langmap' after a modifier is a good
approximation.  Better is to see if applying the modifier to the
character results in a different character, and check if 'langmap'
handles that.  Especially for the Alt modifier, which sets the eigth bit
of characters.  That might very well be langmap'ped.  Probably can use
extract_modifiers().

Is this enough info to create a PR?


-- 
FROG: How you English say:  I one more time, mac, I unclog my nose towards
      you, sons of a window-dresser,  so, you think you could out-clever us
      French fellows with your silly knees-bent creeping about advancing
      behaviour.  (blows a raspberry) I wave my private parts at your aunties,
      you brightly-coloured, mealy-templed, cranberry-smelling, electric
      donkey-bottom biters.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
