### ISSUE TITLE
ModeChanged doesn't fire on v_CTRL-C

### ISSUE THREAD

**Issue by sedm0784** [vim/vim#11394]
### Steps to reproduce

1. Run `vim --clean`
2. Set up a ModeChanged autocommand: `au ModeChanged v:n echom "LEAVING VISUAL"`
3. Enter visual mode by pressing `v`.
4. Stop visual mode by pressing `CTRL-C`
Expected results: "LEAVING VISUAL" should be written into the `:messages` log
Observed results: Nothing is written.

At first, I presumed that this was deliberate like how `InsertLeave` is not triggered for `i_CTRL-C` but note that:

1. The latter is documented at both `:help InsertLeave` and `:help i_CTRL-C`,
2. `ModeChanged` *does* fire for `i_CTRL-C`.

If this behaviour *is* in fact deliberate, let me know, and I'll send a pull request with documentation.

Tested in 9.0.65 and 8.2.2859.

### Expected behaviour

Pressing `CTRL-C` when in visual mode should trigger `ModeChanged` autocommands.

### Version of Vim

9.0.65

### Environment

Tested on Windows and macOS.

**Comment by zeertzjq** [comment]
> `ModeChanged` does fire for `i_CTRL-C`.

I just tested and it doesn't.

**Comment by sedm0784** [comment]
Huh. I must have messed up somehow when testing it. I'm guessing this means the behaviour is deliberate. I'll suggest a documentation update in a pull request.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Set up a ModeChanged autocommand: `au ModeChanged v:n echom "LEAVING VISUAL"`
> 3. Enter visual mode by pressing `v`.
> 4. Stop visual mode by pressing `CTRL-C`
> Expected results: "LEAVING VISUAL" should be written into the `:messages` log
> Observed results: Nothing is written.
> 
> At first, I presumed that this was deliberate like how `InsertLeave` is not triggered for `i_CTRL-C` but note that:
> 
> 1. The latter is documented at both `:help InsertLeave` and `:help i_CTRL-C`,
> 2. `ModeChanged` *does* fire for `i_CTRL-C`.
> 
> If this behaviour *is* in fact deliberate, let me know, and I'll send a pull request with documentation.
> 
> Tested in 9.0.65 and 8.2.2859.
> 
> ### Expected behaviour
> 
> Pressing `CTRL-C` when in visual mode should trigger `ModeChanged` autocommands.

What happens is that the autocommand is triggered, but since CTRL-C also
means "abort" it does not get executed.  But the last mode is
remembered, thus the autocommand isn't triggered again after the abort
has been handled.

What we can do is that we skip triggering the autocommand while the
abort is being handled.  It will then soon be triggered later, since the
last mode hasn't changed.  There is a small chance that an intermediate
mode is skipped.

-- 
No children may attend school with their breath smelling of "wild onions."
		[real standing law in West Virginia, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
