### ISSUE TITLE
Since 9.0.783 `:!` no longer works to view the output from the previous `:!cmd`

### ISSUE THREAD

**Issue by dotdash** [vim/vim#11409]
### Steps to reproduce

1. Run a command like ':!rg something`
2. Press enter to return to vim
3. Run `:!` to try to see the results from the command from step 1 again

### Expected behaviour

`:!` switches from alternate screen buffer back the main screen buffer and waits for the user to press enter

### Version of Vim

9.0.801

### Environment

Ubuntu 22/04
wezterm
bash

**Comment by chrisbra** [comment]
well it seems this was on purpose, see #11397 
try to use either `<Ctrl-Z>` in normal mode (or use the `:suspend` or `:shell` ex command) to suspend vim, or use some non-sense command like `:!true`

**Comment by dotdash** [comment]
Is that the right issue number?

**Comment by k-takata** [comment]
#11372, I think.

**Comment by chrisbra** [comment]
opps, sorry, corrected it, but @k-takata already found the correct one :)

**Comment by arp242** [comment]
I think we can check if `t_ti` is empty, and no-op `:!` only if it is. If there's no alternate screen there's nothing to display. Or can just go with my original patch which doesn't clear the `prevcmd`.

**Comment by brammool** [comment]
> I think we can check if `t_ti` is empty, and no-op `:!` only if it is.
> If there's no alternate screen there's nothing to display. Or can just
> go with my original patch which doesn't clear the `prevcmd`.

Making the behavior depend on a terminal setting is rather unexpected.
t_ti might be non-empty and not switch to the alternate screen.

I believe you originally wanted to change this because accidentally
typing ":!" cleared the previous command.  Basic solution is to just
skip that and keep the rest as it was.


-- 
Wi n0t trei a h0liday in Sweden thi yer?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
> I believe you originally wanted to change this because accidentally
> typing ":!" cleared the previous command.  Basic solution is to just
> skip that and keep the rest as it was.

Yeah that's fine; I can send a patch later.

**Comment by chrisbra** [comment]
can you please check [patch 9.0.0815](https://github.com/vim/vim/commit/9c50eeb40117413bf59a9da904c8d0921ed0a6e6). I think it fixed it

**Comment by dotdash** [comment]
That patch seems to have a pretty bad bug in it, now `:!ls` segfaults, and `:!` launches a shell instead of just showing a `Press ENTER` prompt

**Comment by dotdash** [comment]
Seems to work as expected again, thanks!
