### ISSUE TITLE
Termdebug: allow disabling the "window toolbar"

### ISSUE THREAD

**Issue by N-R-K** [vim/vim#11442]
### Please describe the problem.

Currently Termdebug automatically adds the window toolbar if mouse is enabled. However I don't want this behavior since the winbar clutters the screen.

The way I'm currently coping with this is via clearing `mouse`, opening `:Termdebug` and then re-enabling `mouse=a` in a function. (I don't use mouse much, but I like to keep it enabled just in case).

### Describe the solution you'd like

Instead of assuming mouse being enabled means the user wants the window toolbar, add an option (let's say `g:termdebug_no_winbar`) which allows the user to explicitly disable the winbar.

**Comment by brammool** [comment]
> ### Please describe the problem.
> 
> Currently Termdebug automatically adds the window toolbar if mouse is enabled. However I don't want this behavior since the winbar clutters the screen.
> 
> The way I'm currently coping with this is via clearing `mouse`,
> opening `:Termdebug` and then re-enabling `mouse=a` in a function.
> 
> ### Describe the solution you'd like
> 
> Instead of assuming mouse being enabled means the user wants the
> window toolbar, add an option (let's say `g:termdebug_no_winbar`)
> which allows the user to explicitly disable the winbar.

I think we should use a dictionary with options to configure Termdebug,
instead of all separate variables.  Then it's also easier to switch
between setups.  Well, we were already switching over to using
g:termdebug_config, let's continue that.

-- 
This computer is so slow, it takes forever to execute and endless loop!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by N-R-K** [comment]
Looks like this got implemented at d13166e7. So closing this.
