### ISSUE TITLE
please create a mode change event for autocmd

### ISSUE THREAD

**Issue by MrOutput** [vim/vim#1146]
please expose mode change event

**Comment by MrOutput** [comment]
did not see insertleave

**Comment by chrisbra** [comment]
What problem are you trying to solve, that you would need such an event?

**Comment by MrOutput** [comment]
i toggle between nu and relnu in visual / not visual

**Comment by nuko8** [comment]
The reply is too brief for me to make out what problem is tried to solve. So, let me allow to give a shot in the dark in hope of somehow making the situation improved.

When a piece of text on vim is copied and pasted into another application, that can be done through two different ways each of which behaves differently one another:
1. Enter visual mode, then select the region of a piece of text to be copied. 

Behind the scenes, that puts the text into vim’s internal register which is designed to synchronize with system’s clipboard.  In this case, the line numbers won’t appear in the copied text on the clipboard because vim cannot visually select a region in such a way that it also includes line numbers.  In other words, vim knows which part on the screen should be included in and excluded from the clipboard when it does copy and paste, and works accordingly.
1. In normal mode, instead of using vim’s selection mechanism, use that of the underlying terminal or GUI to select the region of a piece of text to be copied.  

That also puts the text into system’s clipboard, but is not through the register synchronized with the clipboard.  In this case, the line numbers may appear in the copied text on the clipboard because the underlying system takes what is displayed and selected on the screen as it is, and has no idea on the fact that vim distinguishes text body from line numbers when it does copy and paste for itself.

For Case 1, toggling `nu` or `relnu` doesn’t make much sense other than appealing to one’s visual preferences because either of them won’t stand in the way of copy and paste.

For Case 2, no doubt, toggling them matters much at all, but, since the selection events in this particular case are not those of vim but those of the underlying system on which vim is working, they are usually unavailable for vim to use because vim doesn’t know what happens outside it.

Thus, even if we have vim capture mode change events, the events of Case 2 won’t trigger any expectd autocommand, thus the requested enhancement being useless.

If my reply above misses your point, please write that again but in a more specific manner so that we can get it.  A concrete use case illustrating your point could be much helpful.

**Comment by chrisbra** [comment]
I think what the OP is trying to achieve is, that whenever he enters visual mode, relativenumbering will be turned on, so that he can visually see, how many lines to select or perhaps the other way around. 

I think, it might be possible to achieve that, by setting a timer and changing the option value, depending on the mode one is.

**Comment by chrisbra** [comment]
Here is a working example:

```
function! s:ModeCheck(id)
    let vmode = mode() =~# '[vV]'
    if vmode && !&rnu
    set relativenumber
    elseif !vmode && &rnu
    set norelativenumber
    endif
endfunction
call timer_start(100, function('s:ModeCheck'), {'repeat': -1})
```

@MrOutput  is that what you want?

**Comment by MrOutput** [comment]
@chrisbra that is exactly it, thank you very much! I am not a huge fan of polling the mode however. I still think an async event that triggers on mode change would be a better solution. My use case is not the only use case. There are several cool things one could do on mode change events. In my ignorance, I couldn't imagine that adding this event would be difficult considering that the status line is already being updated on mode change.

**Comment by chrisbra** [comment]
True, but I am not sure, that some crazy commands on ModeChange could possibly confuse Vims internal state, that's why I wouldn't be so sure, it's a good idea (e.g. consider a ':startinsert' command on a ModeChanged event). And we have seen many problems with autocommands (e.g. openeing a new buffer on BufClose autocommands leading to segfaults e.g.)

**Comment by chrisbra** [comment]
Therefore, I close this issue. Having said that however, whenever someone wants to contribute a patch, that works and is tested, I am sure it will be considered for inclusion.
