### ISSUE TITLE
!!{filter} uses incorrect range when operating on a closed fold

### ISSUE THREAD

**Issue by costerwi** [vim/vim#11487]
### Steps to reproduce

1. Open the attached test file. It should open with two folded sections.
1. Position cursor in the first section (line 3)
1. Enter `!!sort` and the range of sort will be shown as `:.,.+3!sort` (four lines under cursor should be sorted).
1. When executed, this range seems to also include the remainder of the file as if closed folds are counted as a single line.

[test.txt](https://github.com/vim/vim/files/9910793/test.txt)

### Expected behaviour

I expect only the folded lines under the cursor to be sorted. I'm sure this was the behavior in older versions but I'm not sure _how_ old.

It seems that in the current versions the correct range for my expected behavior should be `:.!sort`

### Version of Vim

9.0.472, 8.0.1763

### Environment

gvim running on Mac and on RHEL8.

**Comment by chrisbra** [comment]
I believe this is expected as documented at [:h fold-behavior](https://vimhelp.org/fold.txt.html#fold-behavior):

```
For Ex commands that work on buffer lines the range is adjusted to always
start at the first line of a closed fold and end at the last line of a closed
fold.  Thus this command: >
	:s/foo/bar/g
when used with the cursor on a closed fold, will replace "foo" with "bar" in
all lines of the fold.
This does not happen for |:folddoopen| and |:folddoclosed|.
```

**Comment by costerwi** [comment]
Thank you for your comment. I'm reporting this as a bug because the behavior you quoted is _not_ happening. The range of the sort command invoked with !! in my example is not ending at the last line of the closed fold. It affects 3 lines beyond the fold which is enough to even involve the second section of folded lines.

**Comment by chrisbra** [comment]
Yes, I think this is exactly what is happening, because Vim will adjust the seconds address with the last line of the (first) fold. Adding 3, will adjust until the second last line of the file, see here: https://github.com/vim/vim/blob/1410d1841bfc4370dec1babe24c6664e06d7c9d9/src/ex_docmd.c#L4629-L4635

You can also test, on what line vim will execute anything, by using the `#` ex-cmd, e.g. `.,.+3#` will show you the line numbers on which Vim will execute the commands. 

I am not sure this can be changed, without breaking backwards compatibility.

**Comment by costerwi** [comment]
Thanks for the # ex-cmd. That's cool!

Sorry, I think I haven't been clear enough and you're missing the point. Have you tried my example using the `!!sort` on the first closed fold? Vim is incorrectly translating this into `:.,.+3!sort` but it _should_ translate into `:.!sort` so the filter only affects the lines inside the closed fold. This would match behavior of commands like `yy` or `dd` when used on closed folds.

As the manual page suggests, the "range is adjusted to always start at the first line of a closed fold and **end at the last line of a closed fold**".  The line `.+3` is not the last line inside the closed fold. It is 3 lines beyond the end of the closed fold. If the closed fold contains 8 lines then `!!sort` generates an `E16: Invalid range` because `.,.+7!sort` translated by vim is even beyond the end of the file.

In my use case I have thousands of folded lines in hundreds of sections. If I execute `!!sort` to sort the data in one of the closed folds in the middle of my file then, with the current behavior, the range spills over for thousands of lines toward the end of the file sorting everything along the way; far beyond the last line of the closed fold where I executed the command.

**Comment by chrisbra** [comment]
of course I have tried it. 

>  The line .+3 is not the last line inside the closed fold.

Okay I understand. This may be a bug, not sure

BTW: this seems to be doing it:
```
folddoclosed :exe foldclosed(".") .. ',' .. foldclosedend(".") .. 'sort'
```

**Comment by nickspoons** [comment]
I think the issue here is not how vim "operates on a closed fold", that is working correctly. The point of the issue is what `!!` does on a closed fold.

`!!` on a closed fold expands to a range which is the size of the fold, e.g. `.,.+3!`, but when vim performs the operation that range is incorrect because the range acts on closed folds as a single line.

So the suggestion is that `!!` on a closed fold should expand to `:.!` as it does on a normal line of text. When vim operates on this range `.` it actually includes the contents of the fold.  `:.#` on a closed fold prints the contents of the fold.

**Comment by chrisbra** [comment]
so perhaps this patch should do it:

```patch
diff --git a/src/ops.c b/src/ops.c
index 451545367..76e214987 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -3333,7 +3333,11 @@ op_colon(oparg_T *oap)
            stuffcharReadbuff('.');
        else
            stuffnumReadbuff((long)oap->start.lnum);
-       if (oap->end.lnum != oap->start.lnum)
+       if (oap->end.lnum != oap->start.lnum
+#ifdef FEAT_FOLDING
+               && !hasFolding(oap->start.lnum, NULL, NULL)
+#endif
+                   )
        {
            stuffcharReadbuff(',');
            if (oap->end.lnum == curwin->w_cursor.lnum)
```

**Comment by costerwi** [comment]
Yes, this works! I looked for a while but could not find where this happened in the source.

Thank you very much!! Will you issue a pull request?

Historically, I think the `.,.+3` range used to be appropriate in an older version of vim where the ex commands did not treat folded lines as a single line. I was using vim this way 20 years ago and it was working correctly. Perhaps the ex treatment of folded lines was updated in the past 20 years (which is a sensible improvement) but this `!!{filter}` was overlooked.

**Comment by chrisbra** [comment]
I'll post a proper PR with test case soon

**Comment by brammool** [comment]
> I think the issue here is not how vim "operates on a closed fold", that is
> working correctly. The point of the issue is what `!!` does on a closed fold.
> 
> `!!` on a closed fold expands to a range which is the size of the fold, e.g.
> `.,.+3!`, but when vim performs the operation that range is incorrect because
> the range acts on closed folds as a single line.
> 
> So the suggestion is that `!!` on a closed fold should expand to `:.!` as it
> does on a normal line of text. When vim operates on this range `.` it
> actually includes the contents of the fold.  `:.#` on a closed fold prints
> the contents of the fold.

Hmm, both are possible and neither are really correct, we'll have to find a
compromise.

I would say that expanding "!!" into the actual line range is useful, you can
see the actual line numbers used.  If it always becomes ":.!" then there is no
extra info, no hint you are actually going to operate on a number of lines.

On the other hand, if you would type ":.!sort" then you expect the same to
happen as with "!!sort".  Showing something else is perhaps confusing then?
That seems like something less important.

If we do go this way, we need to make sure that ":.!sort" and ":.,.+3!sort" do
exactly the same thing.  That works if we take the ".+3" part as-is, without
adjusting it for closed folds.  I think that's what the patch that Christian
suggested does, right?

I find it important that no matter what you typed, the meaning of the command
you end up using does not depend on how you got it there.  We don't want the
meaning of the range to change based on something you typed a few moments ago.
There is no indication for it, it would be quite unpredictable.

So, the only change would be that the ".+3" part is taken as the actual line
number, and not counting closed folds, since that would double-count the lines
in the closed fold, or include lines from following folds.  To cover corner
cases we can still check if the ".+3" line is in a closed fold and use to the
last line of that fold.  It does not make a difference for the example, but
does make it more consistent when typing the command.

-- 
Don't Panic!
		-- The Hitchhiker's Guide to the Galaxy

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> Historically, I think the `.,.+3` range used to be appropriate in an older version of vim where the ex commands did not treat folded lines as a single line.

+1 thumb-up
// wish not break the consistent..

**Comment by brammool** [comment]
> > Historically, I think the `.,.+3` range used to be appropriate in an
> > older version of vim where the ex commands did not treat folded
> > lines as a single line.
> 
> +1 thumb-up
> // wish not break the consistent..

Where does this "Historically" statement come from?  Any reference?

Unless someone shows otherwise, I am sure that before folds existed the
expanded range was used as-is (since there were no folds there obviously
was no adjustment for folds).  And I an quite sure that when folds were
introduced the behavior was changed at the same time, to have Ex
commands always operate on a closed fold as a whole and not a section of
it.  I do not think there was ever a situation where closed folds
existed and an Ex command would work on only part of the lines in that
closed fold.

-- 
Latest survey shows that 3 out of 4 people make up 75% of the
world's population.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
> Where does this "Historically" statement come from?

i think he meant `!!` on a closed fold line would expand the range to expected num, not the just the cur (or one line).

i tried vim v7.4.207 it is correct, the history is like his said (which NOT just a one line but expand to `range`)

**Comment by brammool** [comment]
I spent some more time on this.  It's hard to make it work without breaking backwards compatibility.  Existing code allows for adding an offset after adjusting the line number to the last line of a closed fold, so that you can operate on a closed fold minus or plus some lines.  The only solution I could think of right now is to make a difference between using ".,+number" and ".,.+number". Notice the dot before the plus.  This way at least the existing tests pass.  But for users it might be confusing.
I'll make a patch this way, but feel free to comment and suggest a better solution.

**Comment by costerwi** [comment]
Thank you for the bug fix!

Another check: `3dd` on line 3 of the example file will delete both closed folds and the "Section 2" between them (9 fewer lines). Does `3!!sort` operate on those same 9 lines?

Regarding behavior: The ability of vim to interact with closed folds as if they are a single line is extremely powerful. `dd` and `!!` are examples I use all the time and they worked consistently 20 years ago in vim. I don't especially care what range is displayed for `!!sort` on a closed fold but in my mind it is the same as `:.!sort` because I'm always treating closed folds as a single line.

**Comment by brammool** [comment]
> Thank you for the bug fix!

Note that the solution was changed in 9.0.0861.  The result should be
the same though.

> Another check: `3dd` on line 3 of the example file will delete both
> closed folds and the "Section 2" between them (9 fewer lines). Does
> `3!!sort` operate on those same 9 lines?

Yes, the count is used in a way that a closed fold counts as one line.

> Regarding behavior: The ability of vim to interact with closed folds
> as if they are a single line is extremely powerful. `dd` and `!!` are
> examples I use all the time and they worked consistently 20 years ago
> in vim. I don't especially care what range is displayed for `!!sort`
> on a closed fold but in my mind it is the same as `:.!sort` because
> I'm always treating closed folds as a single line.

When typing "!!" you will now (after path 9.0.0861) see ":.!" in the
command line.  I actually liked to see the line range, but it was
causing complications, thus I changed my mind.

Nevertheless, others might come up with aspects we haven't thought of,
thus I'm open for suggetions to make it work even better.

-- 
Light travels faster than sound.  This is why some people
appear bright until you hear them speak

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cecamp** [comment]
As I understand things, there are two mutually exclusive interpretations of :!! . Perhaps :!! for one and :!!! for the other?

**Comment by Shane-XB-Qian** [comment]
maybe a bit Confused, 
// and in the past v7.4 the range was expanded (displayed) anyway which not just the `:.!` after emit `!!` on a closed fold line.

1, in 7.4 it is e.g `:.,.+2!` (not the `:.,+2!` Note: there is no `.` before `+` though execution result looks was same)
2, now it is just `:.!` (would not expand the range, though execution result  looks was same) (which seems to compliance with `count` (vs `range`) operation e.g `3dd`)
3, now the doc in `range-closed-fold` tag, seems said if explicitly emit `:.,.+2!` then would work over closed fold end line (`+2`)

// though looks a bit confused and inconsistent. :-( but maybe we can live with it... :question: maybe.. aha..

**Comment by Shane-XB-Qian** [comment]
by the way, Now i can reproduce seg fault which cannot in #11495 
just `!!` after `vim --clean` but not input any `cmd` after `:.!`, then seg fault.
// v9.0.861

**Comment by zeertzjq** [comment]
> by the way, Now i can reproduce seg fault which cannot in #11495 just `!!` after `vim --clean` but not input any `cmd` after `:.!`, then seg fault. // v9.0.861

I can reproduce this segfault as early as v9.0.0820

**Comment by Shane-XB-Qian** [comment]
> I can reproduce this segfault as early as v9.0.0820

yea, i meant i was not sure how to stably reproduce the segfault since it was just accidently happened.

but now, seems that fix in ex_cmds.c
```c
    if (STRLEN(newcmd) > 0)
    {
	vim_free(prevcmd);
	prevcmd = newcmd;
    }
    else
	free_newcmd = TRUE;
```
for well knew v9.815 somehow had flaw which `prevcmd` is `NULL`.

~~#11533 test case for this.~~ 
update: seems difficult to make it work in ci test, i donot know how to make it be as the first cmd, though locally can reproduce.

**Comment by brammool** [comment]
> As I understand things, there are two mutually exclusive
> interpretations of :!! . Perhaps :!! for one and :!!! for the other?

Please explain.  I see only one way how :!! works.

-- 
hundred-and-one symptoms of being an internet addict:
45. You buy a Captain Kirk chair with a built-in keyboard and mouse.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
