### ISSUE TITLE
"vim -W {scriptout}" saves ^C twice

### ISSUE THREAD

**Issue by dstein64** [vim/vim#11541]
### Steps to reproduce

Launch Vim with `-W` and then type `<c-c>ZQ`.

```
vim -W tmp
# Type <c-c>ZQ
```

Inspect the contents of `tmp`.

```
vim tmp
```

### Expected behaviour

I expected a single `<c-c>` in `tmp`, such that the contents would show `^CZQ`.

Rather, there is a double `<c-c>`, as the contents shows `^C^CZQ`.

### Version of Vim

9.0.876

### Environment

OS: Kubuntu 22.04
Terminal: Konsole 21.12.3
$TERM: xterm-256color
Shell: bash 5.1.16

**Comment by zeertzjq** [comment]
This also applies to recording a macro.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Launch Vim with `-W` and then type `<c-c>ZQ`.
> 
> ```
> vim -W tmp
> # Type <c-c>ZQ
> ```
> 
> Inspect the contents of `tmp`.
> 
> ```
> vim tmp
> ```
> 
> 
> ### Expected behaviour
> 
> I expected a single `<c-c>` in `tmp`, such that the contents would
> show `^CZQ`.
> 
> Rather, there is a double `<c-c>`, as the contents shows `^C^CZQ`.

This was done intentionally, in some corner cases the extra CTRL-C is
needed to get out of Insert mode.

I could perhaps find some way to suppress the extra CTRL-C, but it might
cause serious trouble (Vim completely stuck) if we get this condition
wrong.

What is the problem caused by the extra CTRL-C?  Are you reporting it
just because it looks wrong or is there an actual problem caused by it?


-- 
hundred-and-one symptoms of being an internet addict:
70. ISDN lines are added to your house on a hourly basis

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dstein64** [comment]
> "Are you reporting it just because it looks wrong or is there an actual problem caused by it?"

There's no problem that I'm encountering.

I incidentally noticed the double `^C` and reported it here since I thought it was a bug.

I'll close this ticket since the behavior is intentional.

**Comment by dstein64** [comment]
> "What is the problem caused by the extra CTRL-C?  Are you reporting it just because it looks wrong or is there an actual problem caused by it?"

I didn't realize until now that I never responded to the question. That was an oversight—not intentional. I closed the issue at the time, presumably based on the comment that addressing the extra `<ctrl-c>` "might cause serious trouble."

To answer the question (about the problem):

I noticed the issue when looking into [vimgolf Issue #224](https://github.com/igrigorik/vimgolf/issues/224). vimgolf is a game where players solve text-editing challenges in Vim using as few keystrokes as possible. It records keystrokes by using Vim's `-W` flag. That results in `<ctrl-c>` appearing twice, which is subsequently interpreted as two key presses for scoring.

I think it would be possible to handle this in vimgolf. I proposed a solution in [PR #367](https://github.com/igrigorik/vimgolf/pull/367) that effectively replaces `<ctrl-c><ctrl-c>` with `<ctrl-c>` (in the file passed to `-W`).
