### ISSUE TITLE
ttyfast not set for some common terminal emulators

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#11549]
### Steps to reproduce

1. Use Alacritty or st as terminal emulators.
2. Check `:set ttyfast?`
3. It's `nottyfast`, even though these are software terminal emulators.

### Expected behaviour

These terminals should be `ttyfast`, just like `xterm`, `urxvt`, etc.

It also breaks selecting wrapped lines on these emulators, as documented in `:h ttyfast`.

I suggest expanding `vim_is_fastterm` to detect TERM=st and TERM=alacritty as well.

### Version of Vim

9.0.447

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Use Alacritty or st as terminal emulators.
> 2. Check `:set ttyfast?`
> 3. It's `nottyfast`, even though these are software terminal emulators.
> 
> ### Expected behaviour
> 
> These terminals should be `ttyfast`, just like `xterm`, `urxvt`, etc.

This is from old times.  You can just set 'ttyfast' in your vimrc.
 
> It also breaks selecting wrapped lines on these emulators, as
> documented in `:h ttyfast`.
> 
> I suggest expanding `vim_is_fastterm` to detect TERM=st and
> TERM=alacritty as well.

I'm wondering if we can just drop it and behave like 'ttyfast' is always
on.  Would there be any situation where having 'ttyfast' enabled causes
any noticeable trouble?

Obviously the problem with wrapping lines is much more relevant than
some drawing issues.

-- 
hundred-and-one symptoms of being an internet addict:
69. Yahoo welcomes you with your own start page

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leahneukirchen** [comment]
AFAIU NeoVim dropped ttyfast and made it default (they now have a different line wrapping bug occasionally, but that's not Vim's problem). I don't think anyone complained.

**Comment by zeertzjq** [comment]
> AFAIU NeoVim dropped ttyfast and made it default (they now have a different line wrapping bug occasionally, but that's not Vim's problem). I don't think anyone complained.

Someone indeed complained: <https://github.com/neovim/neovim/issues/1045#issuecomment-600073758>

**Comment by brammool** [comment]
> > AFAIU NeoVim dropped ttyfast and made it default (they now have a
> > different line wrapping bug occasionally, but that's not Vim's
> > problem). I don't think anyone complained.
> 
> Someone indeed complained:
> <https://github.com/neovim/neovim/issues/1045#issuecomment-600073758>

Looks like that discussion didn't end up with a conclusion.  It does
indicate that some users might want to use 'nottyfast'.

The simplest change would be to make the default for 'ttyfast' to be set
for all terminals.  Then when a user doesn't like the behavior it can be
turned off, possibly checking the value of $TERM:

	if &term =~ 'slowOne'
	  set nottyfast
	endif

Since this would only affect how the display is updated, it does sound
like a good default behavior.  The disadantage of 'nottyfast' with the
wrapping behavior is much more of a problem.

Ideally we don't need the option at all, have the display updating work
nicely without any options.  But since we can't predict what it looks
like it might not really feasible.


-- 
hundred-and-one symptoms of being an internet addict:
72. Somebody at IRC just mentioned a way to obtain full motion video without
    a PC using a wireless protocol called NTSC, you wonder how you never
    heard about it

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
