### ISSUE TITLE
`WinScrolled` is activated only after first resize due to effect of `winwidth`/`winheight`

### ISSUE THREAD

**Issue by echasnovski** [vim/vim#11576]
### Steps to reproduce

1. Create init file ('init-winscrolled-winwidth.vim' in this example') with the following contents:
```vim
let g:winscrolled_events = []
au WinScrolled * let g:winscrolled_events = g:winscrolled_events + [expand('<amatch>')]
```
2. Run `vim -u init-winscrolled-winwidth.vim`.
3. Create new window with vertical split (`<C-w>v`).
4. Switch back and forth with `<C-w>l<C-w>h`. This consumes `WinScrolled` events resulting from initial vertical split.
5. `:echo g:winscrolled_events`. It should show `['1001', '1000']`.
6. `:set winwidth=10000`. Current window should occupy maximum width, i.e. it was resized.
7. Again switch windows back and forth. Each switch leads to resizing of current window to maximum width.
8. `:echo g:winscrolled_events`. It should show `['1001', '1000', '1001', '1000']`.
9. And again switch back and forth. Each switch still resizes window.
10. `:echo g:winscrolled_events`. It now shows the same history as after previous `echo`, but it should have added two more window numbers.

**Note**: same applies to `winheight` and horizontal split.

### Expected behaviour

`WinScrolled` event is activated after any window resize, including resulting from `winwidth` and `winheight`.

### Version of Vim

9.0.813

### Environment

OS: EndeavourOS Linux x86_64, 6.0.8-arch1-1
Terminal: st
`$TERM`: `st-256color`
Shell: zsh 5.9

**Comment by brammool** [comment]
There was a discussion about this recently: When to trigger the
WinScrolled event and whether it should be triggered for each window
separately, or once when any window was scrolled or resized.

What currently happens is that after going to another window, the scroll
position and size are compared to the last time WinScrolled was
triggered.  And in your example there are no changes in that window.
The window did resize when it was not the current window.  But that
currently is not reported.

What the behavior should be depends on what users (or plugin writers)
want to use the event for.  I would think that the main reason is to
adjust the contents of some windows to the new layout.  E.g, if you are
showing some table and the space for it has increased, the information
may be made more verbose.  That would work best with one event, even
when more than one window changes.

If we do this way, one event no matter what changes, and the user/plugin
does need to know about a specific window, then winlayout() and
getwininfo() can be used to see what happened: Store the result of
winlayout() every time WinScrolled is triggered, and find the relevant
changes on the next event.

If we do trigger WinScrolled for each window, then a resize will usually
cause at least two events.  I think this is more complicated, because
the relation between the two events is hard to tell.  The plugin may
need to use both and end up doing its work twice.

I might as well make that change now, then you can try it out and
comment.


-- 
I AM THANKFUL...
...for all the complaining I hear about the government
because it means we have freedom of speech.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by echasnovski** [comment]
Thank you, Bram, for the insight!

> What currently happens is that after going to another window, the scroll position and size are compared to the last time WinScrolled was triggered.

This totally makes sense considering the observations, yes.

---

Thanks for quick patch!

My use case is an another animation plugin, but which tries to trigger animations on events (not through some mapped commands). It already has animation for cursor movement and scroll, now I am trying to add window close/open/resize support. Granted, it is for Neovim, so it'll take some more work for me to get back with more informative comments about this change.

The approach described in new documentation seems like the one I expected to be true before 9.0.0913 patch: `WinScrolled` detects scroll or resize in *any* window, not just current, just like #10628. I'll test more thoroughly later and get back to you.

That said, I'd wish to point some usefulness for `WinScrolled` and `WinResized` to be separate. Right now if plugin wants to make some automated task based on whether layout has changed or not, it should listen for `WinScrolled`, which will give a fairly lot more false positives due to actual scrolling. This comes at a price of increased computations which can be avoided in case of separate events. However, I do understand the idea of keeping implementation simpler, so there is no easy solution here.

**Comment by echasnovski** [comment]
I've checked if this issue persists with 9.0.0513 patch (specifically, with current 9.0.0515 version which also should solve #11582). Here is the result:

1.
2.
3.
4.
5. `:echo g:winscrolled_events`. It shows `['1001']` instead of previous `['1001', '1000']`. This value is updated already after vertical split.
6.
7.
8. `:echo g:winscrolled_events`. It now shows `['1001', '1001', '1001', '1001']` instead of previous `['1001', '1000', '1001', '1000']`. This output seems correct as three resizing have occurred (after `:set winwidth=10000`, after first switch, after second switch).
9.
10. `:echo g:winscrolled_events`. It now shows `['1001', '1001', '1001', '1001', '1001', '1001']` (plus two times), which also seems to be correct.

So if always having same match is ok (as it seems to be per documentation; "The pattern is matched against the |window-ID| of the first window that scrolled or resized."), I think this particular issue is fixed. Thanks!

**Comment by brammool** [comment]
> That said, I'd wish to point some usefulness for `WinScrolled` and
> `WinResized` to be separate. Right now if plugin wants to make some
> automated task based on whether layout has changed or not, it should
> listen for `WinScrolled`, which will give a fairly lot more false
> positives due to actual scrolling. This comes at a price of increased
> computations which can be avoided in case of separate events. However, I
> do understand the idea of keeping implementation simpler, so there is no
> easy solution here.

Scrolling without changing the window width/height is indeed very
common.  And when you get a WinScrolled event, figuring out that the
window widths/heights did not change isn't simple.

When we would have both WinScrolled and WinResized the question comes up
what to do when a window size changed and scrolling happened as a result
of that.  That's also very common.  To avoid surprises both would need
to be fired.  Would that by itself just work well?

An alternative is that we do keep the one WinScrolled event, and then
provide the information about what changed.  The mininal of that would
be to have a flag that is set when a window width or height changed.
Thus you would get a WinScrolled event with a flag that says no window
size changed, only scrolling happened.

A bit more advanced is to make a list of the changes, with one item per
window.  Perhaps something like:
	[{winid: 234, width: 0, height: 1, topline: 0, leftcol: 0}]

This would indicate that window 234 had a height increase of 1 and no
other changes.  When scrolling the window it could be:
	[{winid: 234, width: 0, height: 0, topline: 1, leftcol: 0}]

When only interested in size changes you would need to go through the
list.  Hmm, we could make a summary, so that you only need to check one
entry:
	[
		{winid: 0, width: 1, height: 0, topline: 1, leftcol: 0},
		{winid: 234, width: 1, height: 0, topline: 0, leftcol: 0},
		{winid: 567, width: 0, height: 0, topline: 1, leftcol: 0},
	]

I would think this is useful anyway.  There is some overhead in creating
the list with dictionaries, a small price to pay.

Keep in mind that when a sequence of events happen, only the last change
is going to reported.  When "debouncing" the event the information
may need to be added together until it's used.

-- 
From "know your smileys":
 C=}>;*{)) Drunk, devilish chef with a toupee in an updraft,
	   a mustache, and a double chin

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by echasnovski** [comment]
> When we would have both WinScrolled and WinResized the question comes up what to do when a window size changed and scrolling happened as a result of that.  That's also very common.  To avoid surprises both would need to be fired.  Would that by itself just work well?

Besides possible implementation difficulties  you outlined in [this comment](https://github.com/vim/vim/issues/10628#issuecomment-1310798189), I can't see obvious pitfalls from user-consumer point of view. If scrolled is caused by resize, then: 1) `WinResized` is fired with information about resized window(s) followed by 2) `WinScrolled` with information about how scroll(s) happened.

> Hmm, we could make a summary, so that you only need to check one
entry:

Yes, this would be useful (as long as summary is always the first entry).

Couple of thoughts out loud on data structures:
- Another possibility is to make it a single dictionary with window ids as keys. This has an advantage of allowing more direct access for any particular window of interest.
- Extra decision is needed about what to do with new/closed windows. Either not display at all or display a change from/to zero width and height.
- More complicated but potentially more useful is to provide not differences themselves, but a pair of "from"-"to" values (except possible summary entry). This will allow users to not care about accumulating all information in case of several events.

**Comment by brammool** [comment]
>  > When we would have both WinScrolled and WinResized the question comes
>  > up what to do when a window size changed and scrolling happened as a
>  > result of that.  That's also very common.  To avoid surprises both
>  > would need to be fired.  Would that by itself just work well?
> 
> Besides possible implementation difficulties  you outlined in [this
> comment](https://github.com/vim/vim/issues/10628#issuecomment-1310798189),
> I can't see obvious pitfalls from user-consumer point of view. If
> scrolled is caused by resize, then: 1) `WinResized` is fired with
> information about resized window(s) followed by 2) `WinScrolled` with
> information about how scroll(s) happened.
> 
> > Hmm, we could make a summary, so that you only need to check one entry:
> 
> Yes, this would be useful (as long as summary is always the first entry).

Yes, the summary would always come first.

> Couple of thoughts out loud on data structures:
> - Another possibility is to make it a single dictionary with window ids
>   as keys. This has an advantage of allowing more direct access for any
>   particular window of interest.

It would be a dictionary of dictionaries then.  It's a little bit less
efficient than a list, but if you just need to check one window then
it's indeed easier than going through the list to find it.

> - Extra decision is needed about what to do with new/closed windows.
>   Either not display at all or display a change from/to zero width and
>   height.

You'll get separate events for splits and closing windows.  The
WinScrolled and WinResized events always come later.  And will only
report about windows that exist at that point, thus a closed window by
itself won't trigger the event, but since the size goes elsewhere the
effect on other windows will be reported.

When a split happens, the new window would report it's current size as
the increase in width and height.

> - More complicated but potentially more useful is to provide not
>   differences themselves, but a pair of "from"-"to" values (except
>   possible summary entry). This will allow users to not care about
>   accumulating all information in case of several events.

That doesn't sound useful, if you have a width increase of 1 then you
can get the current width and you can compute the previous width.  When
triggering the event there is no clue what the consumer of the event has
last seen, it will have to keep that info anyway.

So, if we aim for the best support, while avoiding too much overhead for
the common cases, we could do:

Add the WinResized event, triggered when any window changes width or
height, providing a list of Window IDs that changed:
	[1001, 1003, 1006]
The size changes are not here to avoid overhead.

For the WinScrolled event add the information about what changed as a
dictionary of dictionaries.  This does add overhead, we assume that
using this event means the overhead is justified.  You can then also
use the WinScrolled event if you are only interested in resizing but do
want to get the information provided here.

    {
      all: {width: 0, height: 2, leftcol: 0, topline: 1, skipcol: 0},
      1003: {width: 0, height: 1, leftcol: 0, topline: 1, skipcol: 0},
      1005: {width: 0, height: -1, leftcol: 0, topline: 0, skipcol: 0},
    }

The "all" entry must have a non-zero height when any window changed
height.  Since it would be zero if we add all height changes together,
add the absolute values.

-- 
From "know your smileys":
 <|-) Chinese
 <|-( Chinese and doesn't like these kind of jokes

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by echasnovski** [comment]
> And will only report about windows that exist at that point, thus a closed window by itself won't trigger the event, but since the size goes elsewhere the effect on other windows will be reported.
>
> When a split happens, the new window would report it's current size as the increase in width and height.

That is exactly what I had in mind.

---

From a user point of view I am not sure that asymmetry between `WinResized` and `WinScrolled` provided information is useful/justified. For me a more straightforward design would be:
- `WinResized` is fired if any present window in current tabpage is resized. That is, if any window had a change in `height` or `width`. It provides somewhere the information about change in a form of dictionary of dictionaries:
```
{
  1003: {height: 0, width:  1},
  1005: {height: 0, width: -1},
}
```
- `WinScrolled` is fired if any present window in current tabpage is scrolled. That is, if any window had a change in `leftcol`, `topline`, or `skipcol`. It provides somewhere the information about change in a form of dictionary of dictionaries:
```
{
  1003: {leftcol:  0, topline:  1, skipcol: 0},
  1005: {leftcol: -1, topline: -1, skipcol: 0},
}
```

This way summaries don't seem to add much and all information is given only when it is needed.

Of course, this is purely from a user point of view. I can't say I have strong knowledge about implementation.

**Comment by brammool** [comment]
I don't care about asymmetry.  Providing a list is just much more efficient, and usually I would expect the window ID to be the only thing that matters, the size change itself might not be needed.  It's easy to keep the previous size when interested in only one window, and if the difference matters then WinScrolled can be used (at the cost of getting the event much more often).

**Comment by echasnovski** [comment]
Sure, this also makes sense. It would make even more sense if array was supplied for a more common event (`WinScrolled`) and dictionary of dictionaries for the other (`WinResized`), but it comes with a cost of not providing actual scroll data on event.
