### ISSUE TITLE
v_O does not preserve selection (even with single width characters)

### ISSUE THREAD

**Issue by doubleloop** [vim/vim#11578]
### Steps to reproduce

```sh
$echo tmp.txt
ab
cdefgh
ijk
lmnopqrst
$vim -u NORC tmp.txt
```

1) start block selection from b to p (at this point if you would yank, register should contain `b^Jdefg^Jjk^Jmnop`)
2) feed `O` note that **selected area changed**  (at this point if you would yank, register should contain `b^Jde^Jjk^Jmn`),
3) feed `O` again, selected are remained changed and differs from initial selection

### Expected behaviour

selection should remain the same (no selected character occupies more than one position on the screen)

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 19 2022 20:44:17) Included patches: 1-910

### Environment

Debian bookworm
GNOME Console 43.0
xterm-256color
zsh 5.9

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> ```sh
> $echo tmp.txt
> ab
> cdefgh
> ijk
> lmnopqrst
> $vim -u NORC tmp.txt
> ```
> 
> 1) start block selection from b to p (at this point if you would yank,
> register should contain `b^Jdefg^Jjk^Jmnop`)
> 2) feed `O` note that **selected area changed**  (at this point if you
> would yank, register should contain `b^Jde^Jjk^Jmn`),
> 3) feed `O` again, selected are remained changed and differs from
> initial selection
> 
> 
> ### Expected behaviour
> 
> selection should remain the same (no selected character occupies more
> than one position on the screen)

That is not possible, since at the top position there are not enough
characters to put the other corner.  A block is defined by the corners,
and "O" swaps both the top and the bottom corner.

If you would add some text after "ab" then it would work.  Setting
'virtualedit' to "all" also works.  I don't really see another way to
make this work.

-- 
From "know your smileys":
 [:-)	Frankenstein's monster

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
