### ISSUE TITLE
Since vim 9.0.0910 vim-lsp popups jump to different splits 

### ISSUE THREAD

**Issue by dotdash** [vim/vim#11594]
### Steps to reproduce

1. Have vim-lsp installed and an LSP that provides hover information.
2. Open a file supported by that LSP
3. Run `:LspHover --ui=float' on some item
4. Run `:split`
5. Run `:LspHover --ui=float` on some item in the new split

Instead of the popup appearing at the cursor location, the cursor jumps to the other split and the popup appears there.

### Expected behaviour

The popup from `LspHover` appears at the cursor position in both cases.

### Version of Vim

Noticed in 9.0.0924 - git bisect identified 9.0.910 as first bad commit

### Environment

Ubuntu 22/10, Kitty, xterm-kitty, bash

**Comment by brammool** [comment]
Patch 9.0.0910 fixed a problem with not using a valid window.  I guess the vim-lsp plugin somehow
depended on side effects of that problem.  There isn't really any other solution, thus it's very unlikely Vim
will be changed to handle the vim-lsp behavior.

You probably should open this issue with the vim-lsp plugin.  Only when it can't be fixed there we might have a look at the reason and see if there is another way or a workaround.

**Comment by nickspoons** [comment]
While trying to track this bug down, I traced it to this line in vim-lsp: https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/internal/diagnostics/float.vim#L45 which is:

    call deletebufline(l:doc_win.get_bufnr(), 1, '$')

I can reliably reproduce this in my own code with `call deletebufline(30, 1, '$')`, where 30 is the bufnr of a hidden buffer created by the plugin. Unfortunately, I have been unable to find reliable minimal repro steps, without using vim-lsp.

**Comment by nickspoons** [comment]
This call to `deletebufline()` from a right vertical split window causes the cursor and focus to move to the left split window.

**Comment by brammool** [comment]
> This call to `deletebufline()` from a right vertical split window
> causes the cursor and focus to move to the left split window.

I cannot reproduce it.  I used this script:

	enew
	new
	call setline(1, ['a', 'b', 'c'])
	let hidbuf = bufnr()
	hide
	call setline(1, ['right', 'window'])
	vert new
	call setline(1, ['left', 'window'])
	wincmd l

Now there is a hidden buffer "hidbuf", a window on the left and a window
on the right, cursor is in the right window.

And then type:

	:call deletebufline(hidbuf, 2)

The right window still has focus

-- 
The difference between theory and practice, is that in theory, there
is no difference between theory and practice.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
Thanks for trying Bram. As I mentioned, I haven't been able to _reliably_ reproduce it without vim-lsp either. I did manage to do it at one stage but I haven't been able to work out how.

However, with vim-lsp, it happens every time. Here is a demo where I first let vim-lsp move the cursor by hovering on an error line. Then I perform the same action with `call deletebufline(3, 1, '$')` which moves the cursor to the left window each time:

[![asciicast](https://asciinema.org/a/zI0VmnmNtKlhywhqt7G4sg8BA.svg)](https://asciinema.org/a/zI0VmnmNtKlhywhqt7G4sg8BA)

**Comment by brammool** [comment]
> Thanks for trying Bram. As I mentioned, I haven't been able to
> _reliably_ reproduce it without vim-lsp either. I did manage to do it
> at one stage but I haven't been able to work out how.
> 
> However, with vim-lsp, it happens every time. Here is a demo where I
> first let vim-lsp move the cursor by hovering on an error line. Then I
> perform the same action with `call deletebufline(3, 1, '$')` which
> moves the cursor to the left window each time:
> 
> [![asciicast](https://asciinema.org/a/zI0VmnmNtKlhywhqt7G4sg8BA.svg)](https://asciinema.org/a/zI0VmnmNtKlhywhqt7G4sg8BA)

I cannot guess what is going on here.

I wonder if that deletebufline() call may trigger another autocommand.
That behavior is not well supported.  The relevant code is in
aucmd_prepbuf():

   if (win == NULL && aucmd_win_used)
	// Strange recursive autocommand, fall back to using the current
	// window.  Expect a few side effects...
	win = curwin;

This means the aucmd_win is already being used and there is no window
for the buffer available.  It then falls back to using the current
window, which may very well cause trouble.

Assuming you can compile Vim, you can add a ch_log() call there to check
if it is reached:

   if (win == NULL && aucmd_win_used)
   {
	// Strange recursive autocommand, fall back to using the current
	// window.  Expect a few side effects...
	win = curwin;
	ch_log(NULL, "Got there");
   }

Then in the script you use, just before calling deletebufline():

	call ch_logfile('logfile', 'w')

Hopefully that will provide more information.

If we indeed have this situation, then we could use aucmd_win again,
since it has the right buffer, or create another window.  Might as well
create a list of these windows if needed.

-- 
Never eat yellow snow.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
> I wonder if that deletebufline() call may trigger another autocommand.

I'm not sure, but I get the same behaviour (cursor jumping to left window) when I prefix it with `noautocmd`:

    noautocmd call deletebufline(2, 1, '$')

I won't have time to try the suggested compile/debug steps today sorry, I'll try during the weekend.

**Comment by mityu** [comment]
Maybe reproduced.
Vim: v9.0.946

Reproduce steps:

1. Save this script to `~/repro.vim`.
```vim
let s:popupID = popup_create('foo', {})
let s:bufnr = winbufnr(s:popupID)
new
echo win_getid()
call deletebufline(s:bufnr, 1, '$')
echo win_getid()
call popup_close(s:popupID)
```

2. Run Vim with`vim -u NONE -S ~/repro.vim`.

Then, this message

```
1002
1000
Press ENTER or type command to continue
```

appeared on command line.

Note that if create popup window after `:new` command, this bug disappears.

**Comment by Shane-XB-Qian** [comment]
I can reproduce @mityu 's case too.

--
shane.xb.qian

**Comment by brammool** [comment]
> Maybe reproduced.
> Vim: v9.0.946
> 
> Reproduce steps:
> 
> 1. Save this script to `~/repro.vim`.
> ```vim
> let s:popupID = popup_create('foo', {})
> let s:bufnr = winbufnr(s:popupID)
> new
> echo win_getid()
> call deletebufline(s:bufnr, 1, '$')
> echo win_getid()
> call popup_close(s:popupID)
> ```
> 
> 2. Run Vim with`vim -u NONE -S ~/repro.vim`.
> 
> Then, this message
> 
> ```
> 1002
> 1000
> Press ENTER or type command to continue
> ```
> 
> appeared on command line.
> 
> Note that if create popup window after `:new` command, this bug disappears.

Thanks for the repro steps.  Now I could see where the problem is
caused, and it's in quite a different spot than I first suspected.
Fortunately the fix is easy.

After I submit the fix, please do watch out for similar problems.

-- 
hundred-and-one symptoms of being an internet addict:
164. You got out to buy software, instead of going out for a beer.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
Thanks Bram!
