### ISSUE TITLE
`gm` and `g^` do not remember column for vertical motion in folds

### ISSUE THREAD

**Issue by citizenmatt** [vim/vim#11596]
### Steps to reproduce

Given some text:

```
    Alice was beginning to get very tired of sitting by her sister on the bank, and
    of having nothing to do: once or twice she had peeped into the book her sister
    was reading, but it had no pictures or conversations in it, “and what is the use
    of a book,” thought Alice “without pictures or conversations?”
```

1. Create a fold of the middle two lines (`jVjzf`)
2. Position cursor on the fold
3. Type `gm`, note that `:set ruler` shows `59-1`
4. Type `k`, the cursor navigates to line 1, column 1

### Expected behaviour

When typing `gm<Up>` I expect Vim to use the current column (59) on the new line

Similarly, if using `g^`, the ruler shows `5-1` but hitting `<Up>` moves to column 1. However, `g$` shows `83-1` in the ruler and hitting `<Up>` will move to column 83 on line 1, as expected.

The column is remembered and used if typing `gm<Right>`, `g^<Right>` or `g$<Right>`. The fold is opened and the caret is correctly moved.

### Version of Vim

9.0 (2022 Jun 28, compiled Oct 19 2022 18:24:48)

### Environment

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 19 2022 18:24:48)
macOS version - x86_64
Included patches: 1-800
Compiled by Homebrew

**Comment by simmsbra** [comment]
I looked into this a bit but will leave the rest to someone else, since it will take me too much time to understand everything and create a thorough patch.
Here are my findings, though:
- I tested old versions and have concluded that this is not a regression.
- The functions that are bugged, like nv_g_home_m_cmd() in normal.c, [set w_set_curswant to TRUE](https://github.com/vim/vim/blob/523f22d57794a73495aa49f667d7f90cc9c8b5c6/src/normal.c#L5747), while a function that is not bugged (nv_g_dollar_cmd()) instead [calls update_curswant_force()](https://github.com/vim/vim/blob/523f22d57794a73495aa49f667d7f90cc9c8b5c6/src/normal.c#L5855). If you replace the statement that sets w_set_curswant to TRUE with a call to update_curswant_force(), the bug seems to be fixed.

**Comment by brammool** [comment]
Updating w_curswant every time adds over head (quite a lot for a long line).
So, the solution could be to call update_curswant_force() if "curwin->w_cline"_folded is set.
