### ISSUE TITLE
Regex search not matching but 'hlsearch' does match.

### ISSUE THREAD

**Issue by JustAnotherSapiens** [vim/vim#11617]
### Steps to reproduce

Characters matching the regex `\s\S\n\zs\S` are not recognized by the regex `\_s\zs\S` although they should.
The funny thing is that the `'hlsearch'` highlighting actually recognizes them as a valid matches.

To reproduce this:
1. Copy and paste this sample text in the vim editor:
```
 1
2
3
4
5 .
6
7
```
2. Ensure highlight search is on: `set hlsearch`
2. (Optional) For a clear visualization I recommend to execute:
```
set listchars=eol:~,space:@
set list
```
4. Run the search: `/\_s\zs\S`
5. Move through the matches in the sample text with `n` and `N` and note how neither '2' nor '6' are matched by the regex despite being highlighted.

In general, the unmatched characters follow the pattern `\s\S\n\zs\S`

This also happens with the `search()` function.

### Expected behaviour

All numbers should be highlighted AND matched by the regex. Thus, being accessible via the `n` or `N` commands in normal mode.

### Version of Vim

9.0.0916

### Environment

OS: Windows 10
This happens on the CMD, PowerShell and on GVIM.

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Characters matching the regex `\s\S\n\zs\S` are not recognized by the regex `\_s\zs\S` although they should.
> The funny thing is that the `'hlsearch'` highlighting actually recognizes them as a valid matches.
> 
> To reproduce this:
> 1. Copy and paste this sample text in the vim editor:
> ```
>  1
> 2
> 3
> 4
> 5 .
> 6
> 7
> ```
> 2. Ensure highlight search is on: `set hlsearch`
> 2. (Optional) For a clear visualization I recommend to execute:
> ```
> set listchars=eol:~,space:@
> set list
> ```
> 4. Run the search: `/\_s\zs\S`
> 5. Move through the matches in the sample text with `n` and `N` and note how neither '2' nor '6' are matched by the regex despite being highlighted.
> 
> In general, the unmatched characters follow the pattern `\s\S\n\zs\S`
> 
> This also happens with the `search()` function.
> 
> ### Expected behaviour
> 
> All numbers should be highlighted AND matched by the regex. Thus,
> being accessible via the `n` or `N` commands in normal mode.

You need to remove the "c" flag from the 'cpoptions' option to make this
work.  See ":help cpo-c" for the explanation.

Still, even then it doesn't work.  The search always starts in the first
column.  The first match found in "5 ." is then on the space, but the
"\zs" moves the start of the match to the dot.  And starting the search
from there skips over the "6".

The fix is to not use the first match start position, but advance just
one character and try for a match there.  I hope this doesn't cause a
regresssion.

-- 
hundred-and-one symptoms of being an internet addict:
144. You eagerly await the update of the "Cool Site of the Day."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
