### ISSUE TITLE
last folded search occurrence is skipped on n and N

### ISSUE THREAD

**Issue by pekcheey** [vim/vim#11614]
I'm not too sure if this is intended behavior.

But given the text delimited by ====== below 
and setting the fold as per below in the first 3 lines 
and then set search text as below.

We should see the paragraphs folded up.

Now, place the cursor on the last selected paragraph; go to the bottom (G)
then press either (n) or (N)

Actual:
We see the cursor either jump to the instance of "test" below "abc" or to the occurrence in the first paragraph.

Expected:
I would expected that the occurrence within the last paragraph be highlighted by either N or n.

```
========
:set nocompatible
:set foldexpr=getline(v:lnum-1)=~'^\\s*$'&&getline(v:lnum)=~'\\S'?'>1':1
:set foldmethod=expr
:let @/='test'
the occurrence of /[t]est/ in this paragraph is jumped to by 'n' (search forward)

the occurrence of /[t]est/ in this paragraph is jumped to by 'N' (search backward)
abc
test
def

the occurrence of /[t]est/ in this paragraph is skipped by both search forward and search backwards if it is folded up and the cursor is on this paragraph. 
klm
test
klm
========
```

after a bit of experiment, it seems that the occurrence within the current fold is skipped.  

I'd attached a short replay captured with asciiema.

**Comment by brammool** [comment]
> I'm not too sure if this is intended behavior.
> 
> But given the text delimited by ====== below 
> and setting the fold as per below in the first 2 lines 
> and then set search text as below.
> 
> We should see the paragraphs folded up.

I don't get any folds.  You can set 'foldcolumn' to easily see that.

The problem appears to be that your 'foldexpr' either returns ">1" for
a non-empty line below an empty line (would be OK to start a fold
there), and returns one otherwise.  Thus it always returns fold level
one.  You probably want to return zero for an empty line.

The second like ":set @/='test'" does not work.   I assume you meant to
do:
	:let @/ = 'test'

Not that this matters, since there aren't any folds.


-- 
hundred-and-one symptoms of being an internet addict:
142. You dream about creating the world's greatest web site.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pekcheey** [comment]
> I don't get any folds. You can set 'foldcolumn' to easily see that. The problem appears to be that your 'foldexpr' either returns ">1" for a non-empty line below an empty line (would be OK to start a fold there), and returns one otherwise. Thus it always returns fold level one. You probably want to return zero for an empty line. 

I don't get why you are not getting any folds. I got the fold-expr from 
/Applications/MacVim.app/Contents/Resources/vim/runtime/doc/fold.txt
listed below for convenience.

I'm using the last  expr below which is suppose to give us 1 paragraph per fold.

```
EXPR						*fold-expr*

The folds are automatically defined by their foldlevel, like with the "indent"
method.  The value of the 'foldexpr' option is evaluated to get the foldlevel
of a line.  Examples:
This will create a fold for all consecutive lines that start with a tab: >
	:set foldexpr=getline(v:lnum)[0]==\"\\t\"
This will call a function to compute the fold level: >
	:set foldexpr=MyFoldLevel(v:lnum)
This will make a fold out of paragraphs separated by blank lines: >
	:set foldexpr=getline(v:lnum)=~'^\\s*$'&&getline(v:lnum+1)=~'\\S'?'<1':1
This does the same: >
	:set foldexpr=getline(v:lnum-1)=~'^\\s*$'&&getline(v:lnum)=~'\\S'?'>1':1

```

> The second like ":set @/='test'" does not work. I assume you meant to do: :let @/ = 'test' Not that this matters, since there aren't any folds.

you are right. I meant :let @/='test'
I'll correct the original message. 
and make it work for a vim without .vimrc
i.e. vim -u /dev/null

**Comment by pekcheey** [comment]
[problem.cast.gz](https://github.com/vim/vim/files/10096071/problem.cast.gz)
the replay can be played with asciiema.

**Comment by brammool** [comment]
> > I don't get any folds. You can set 'foldcolumn' to easily see that.
> > The problem appears to be that your 'foldexpr' either returns ">1"
> > for a non-empty line below an empty line (would be OK to start a
> > fold there), and returns one otherwise. Thus it always returns fold
> > level one. You probably want to return zero for an empty line. 
> 
> I don't get why you are not getting any folds. I got the fold-expr from 
> /Applications/MacVim.app/Contents/Resources/vim/runtime/doc/fold.txt
> listed below for convenience.

I think I must have missed to set 'foldmethod' to "expr".

> I'm using the last  expr below which is suppose to give us 1 paragraph
> per fold.
> 
> ```
> EXPR						*fold-expr*
> 
> The folds are automatically defined by their foldlevel, like with the "indent"
> method.  The value of the 'foldexpr' option is evaluated to get the foldlevel
> of a line.  Examples:
> This will create a fold for all consecutive lines that start with a tab: >
> 	:set foldexpr=getline(v:lnum)[0]==\"\\t\"
> This will call a function to compute the fold level: >
> 	:set foldexpr=MyFoldLevel(v:lnum)
> This will make a fold out of paragraphs separated by blank lines: >
> 	:set foldexpr=getline(v:lnum)=~'^\\s*$'&&getline(v:lnum+1)=~'\\S'?'<1':1
> This does the same: >
> 	:set foldexpr=getline(v:lnum-1)=~'^\\s*$'&&getline(v:lnum)=~'\\S'?'>1':1
> 
> ```
> 
> > The second like ":set @/='test'" does not work. I assume you meant to do: :let @/ = 'test' Not that this matters, since there aren't any folds.
> 
> you are right. I meant :let @/='test'
> I'll correct the original message. 
> and make it work for a vim without .vimrc
> i.e. vim -u /dev/null

Note that when the cursor is in a closed fold, then searching will not
find another match in that fold.  That is intentional.
In the source code there is this comment in do_search():

    // If the cursor is in a closed fold, don't find another match in the same
    // fold.

I can't find a remark like that in the help, I'll add a note.

Thus I very much suspect what you are reporting is actual intended
behavior.

-- 
hundred-and-one symptoms of being an internet addict:
152. You find yourself falling for someone you've never seen or hardly
     know, but, boy can he/she TYPE!!!!!!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pekcheey** [comment]
if there is a comment to that effect then it does seems that this is intended behaviour then.

Please close the issue at your discretion. i.e. if you need this to update to update the documentation. 
perhaps under 
:help fold-behavior

```
...
Searches are skipped over the current closed fold.
Fold can therefore be use to skip over a bunch of search occurrences when performing search.
...
```

Thanks for your prompt response!
