### ISSUE TITLE
WinScrolled should not include window that do not have a snapshot

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11662]
_Instructions: Replace the template text and remove irrelevant text (including this line)_

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
1. When creating a new window, including windows that do not previously have a snapshot in `WinScrolled` `v:event` may be confusing, as the changes in values for that window are not really changes to that value.
2. When sourcing a session with multiple tabpages after the first `WinScrolled` autocommand is defined, `WinScrolled` is triggered when switching to another tabpage even though no window's viewport changed.

**Describe the solution you'd like**
```diff
diff --git a/src/window.c b/src/window.c
index 9a49cad8d..48f5c9952 100644
--- a/src/window.c
+++ b/src/window.c
@@ -2965,6 +2965,16 @@ check_window_scroll_resize(
     win_T *wp;
     FOR_ALL_WINDOWS(wp)
     {
+	if (wp->w_last_topline == 0)
+	{
+	    wp->w_last_topline = wp->w_topline;
+	    wp->w_last_leftcol = wp->w_leftcol;
+	    wp->w_last_skipcol = wp->w_skipcol;
+	    wp->w_last_width = wp->w_width;
+	    wp->w_last_height = wp->w_height;
+	    continue;
+	}
+
 	int size_changed = wp->w_last_width != wp->w_width
 					  || wp->w_last_height != wp->w_height;
 	if (size_changed)
```

**Comment by brammool** [comment]
> 1. When creating a new window, including windows that do not
> previously have a snapshot in `WinScrolled` `v:event` may be
> confusing, as the changes in values for that window are not really
> changes to that value.

When creating a new window we could set the w_last_ values to the
current values, to avoid an event to be triggered right away.  Creating
a new window triggers other events, we don't need to trigger
WinScrolled.

Nevertheless, the space for the window is taken away from other windows,
thus a WinScrolled event will be triggered anyway.  Then isn't it
expected that the new window shows up in v:event?

> 2. When sourcing a session with multiple tabpages after the first
> `WinScrolled` autocommand is defined, `WinScrolled` is triggered when
> switching to another tabpage even though no window's viewport changed.

The viewport *did* change since the WinScrolled event was added.

When the first WinScrolled or WinResized event is defined, the w_last_
values are stored for all windows in all tab pages.  That is about all
we can do.

> 
> **Describe the solution you'd like**
> ```diff
> diff --git a/src/window.c b/src/window.c
> index 9a49cad8d..48f5c9952 100644
> --- a/src/window.c
> +++ b/src/window.c
> @@ -2965,6 +2965,16 @@ check_window_scroll_resize(
>      win_T *wp;
>      FOR_ALL_WINDOWS(wp)
>      {
> +	if (wp->w_last_topline == 0)
> +	{
> +	    wp->w_last_topline = wp->w_topline;
> +	    wp->w_last_leftcol = wp->w_leftcol;
> +	    wp->w_last_skipcol = wp->w_skipcol;
> +	    wp->w_last_width = wp->w_width;
> +	    wp->w_last_height = wp->w_height;
> +	    continue;
> +	}
> +
>  	int size_changed = wp->w_last_width != wp->w_width
>  					  || wp->w_last_height != wp->w_height;
>  	if (size_changed)
> ```

This would result in new windows to not be reported in v:event.  I would
think that they are supposed to show up.

-- 
hundred-and-one symptoms of being an internet addict:
243. You unsuccessfully try to download a pizza from www.dominos.com.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
