### ISSUE TITLE
Patch 9.0.0993: LSP interaction is causing a full screen redraw

### ISSUE THREAD

**Issue by illia-bobyr** [vim/vim#11666]
### Steps to reproduce

Since [Patch 9.0.0993](https://github.com/vim/vim/commit/89469d157aea01513bde826b4519dd6b5fbceae4) my Vim is redrawing the whole screen on every LSP interaction.
I run it in an Alacritty terminal, and for a Rust LSP it is quite noticeable.

My LSP setup is:
```vim
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
```

`rust-analyzer` configured as an LSP server for Rust.

LSP is used to highlight variable references for the variable under the cursor.
Which happens when I move my cursor.
The screen is also redrawn every time I press 'n' to jump to the next search occurrence.

Maybe my terminal is not fast enough, but, unfortunately, after 9.0.0993 there is a noticeable UX regression.

I'll be glad to provide any additional details. 

### Expected behaviour

Screen is not redrawn on every LSP interaction.

### Version of Vim

9.0.1016

### Environment

OS: Ubuntu 21.10
terminal: Alacritty (head build)
value of $TERM: alacritty

**Comment by brammool** [comment]
The referenced patch redraws the screen when prop_type_delete() is used.  That is needed, because various text properties may show differently or disappear.
The plugin you are using should not call prop_type_delete() that often.  Just keep the prop type around and use it again.

Since this can't be fixed in Vim I'm closing this issue.
