### ISSUE TITLE
Map <C-`> not work in kitty

### ISSUE THREAD

**Issue by skysky97** [vim/vim#11678]
### Steps to reproduce

1. Type ":nmap <C-\`> :term\<CR>".
3. Press Ctrl+\`. 

### Expected behaviour

Expect mapping works, open the terminal window.

Kitty reports Ctrl+\` is supported: https://github.com/kovidgoyal/kitty/issues/5747.

### Version of Vim

9.0.1027

### Environment

Ubuntu 20.04 LTS
kitty 0.26.5
$TERM=xterm-kitty

**Comment by brammool** [comment]
I was going to try this out, but somehow kitty refuses to start now...

What keyboard are you using?  Where is the backtick located?

To see the escape codes, you can start Vim with "vim --log logfile".  The logfile will then contain the raw escape sequences that Vim gets.

Also check the output of "set termcap".  Entries that matter are t_TE, t_TI and t_RK

**Comment by skysky97** [comment]
@brammool  I tried again and there is something different. The mapping works fine in kitty now, but still failed in tmux. Should I tune tmux something?

> I just remember I have tested that mapping out of tmux and it is not working too. Maybe I forget to test it after I update vim to latest version.

With "vim --log logfile", it reports Ctrl+\` in tmux

```
raw key input: "`"
```

and without tmux it reports 

```
raw key input: "^[[96;5u"
```

And for "set termcap", both have the same values:
```
t_TE=^[[>4;m^[[=0;1u
t_TI=^[[=1;1u
t_RK=^[[?u
```

**Comment by zeertzjq** [comment]
This seems like a tmux problem them.

**Comment by brammool** [comment]
> @brammool  I tried again and there is something different. The mapping
> works fine in kitty now, but still failed in tmux. Should I tune tmux
> something?
> 
> > I just remember I have tested that mapping out of tmux and it is not working too. Maybe I forget to test it after I update vim to latest version.
> 
> With "vim --log logfile", it reports Ctrl+\` in tmux

If you are using tmux then it works completely differently.  First of
all make sure $TERM is set properly.  From the tmux manpage:

	The TERM environment variable must be set to ‘screen’ or
        ‘tmux’ for all programs running inside tmux.

Not sure if tmux supports this key.

> ```
> raw key input: "`"
> ```
> 
> and without tmux it reports 
> 
> ```
> raw key input: "^[[96;5u"
> ```

That looks correct, "96" is the backtick character and "5" is the Ctrl
modifier.

> And for "set termcap", both have the same values:
> ```
> t_TE=^[[>4;m^[[=0;1u
> t_TI=^[[=1;1u
> t_RK=^[[?u
> ```

That looks OK for Kitty.

-- 
hundred-and-one symptoms of being an internet addict:
266. You hear most of your jokes via e-mail instead of in person.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am closing this, as this seems to be a kitty issue.
