### ISSUE TITLE
ml_get error when resizing non-current window using python with foldmethod=expr

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#11687]
### Steps to reproduce

1. Run `vim --clean`
2. Source one of the two following files:
```vim
call setline(1, ['aaa', 'bbb', 'ccc'])
call cursor(2, 1)
set foldmethod=expr
new
wincmd w
python3 vim.windows[0].height = 5
```
```vim
call setline(1, ['aaa', 'bbb', 'ccc'])
call cursor(2, 1)
set foldmethod=expr
vnew
wincmd w
python3 vim.windows[0].width = 5
```
3. Press `j`
4. `E315: ml_get: Invalid lnum: 2`

### Expected behaviour

No ml_get error

### Version of Vim

9.0.0910

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Oh, the `w` variable is not needed:
```vim
call setline(1, ['aaa', 'bbb', 'ccc'])
call cursor(2, 1)
set foldmethod=expr
new
wincmd w
python3 vim.windows[0].height = 5
```
```vim
call setline(1, ['aaa', 'bbb', 'ccc'])
call cursor(2, 1)
set foldmethod=expr
vnew
wincmd w
python3 vim.windows[0].width = 5
```

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Source one of the two following files:
> ```vim
> call setline(1, ['aaa', 'bbb', 'ccc'])
> call cursor(2, 1)
> set foldmethod=expr
> new
> let w = win_getid()
> wincmd w
> python3 vim.windows[0].height = 5
> ```
> ```vim
> call setline(1, ['aaa', 'bbb', 'ccc'])
> call cursor(2, 1)
> set foldmethod=expr
> vnew
> let w = win_getid()
> wincmd w
> python3 vim.windows[0].width = 5
> ```
> 3. Press `j`
> 4. `E315: ml_get: Invalid lnum: 2`
> 
> ### Expected behaviour
> 
> No ml_get error

Looks like this happens because in the Python interface "curwin" is
temporarily set to another window, so that win_setheight() can be
called,  but then "curbuf" differs from "curwin->w_buffer", which is
dangerous.

Setting "curbuf" seems to fix this problem.  Setting the width has the
same thing.


-- 
    A KNIGHT rides into shot and hacks him to the ground.  He rides off.
    We stay for a moment on the glade.  A MIDDLE-AGED LADY in a C. & A.
    twin-set emerges from the trees and looks in horror at the body of her
    HUSBAND.
MRS HISTORIAN: FRANK!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
