### ISSUE TITLE
Using a negative ID for normal text-properties can lead to unexpected results

### ISSUE THREAD

**Issue by bfrg** [vim/vim#11725]
### Steps to reproduce

Run `vim --clean -S test.vim`, with

```vim
vim9script

setline(1, ['one', 'two', 'three'])
prop_type_add('test_1', {highlight: 'Error'})
prop_type_add('test_2', {highlight: 'WildMenu'})

prop_add(3, 1, {
    type: 'test_1',
    length: 5,
    id: -1
})

prop_add(1, 0, {
    type: 'test_2',
    text: 'The quick brown fox jumps over the lazy dog',
    text_padding_left: 2
})
```

Result: Instead of highlighting the word `three` on the third line, Vim inserts the text from the first virtual text.

Screenshot:
![screenshot-1](https://user-images.githubusercontent.com/6266600/208331666-9fcc544f-c309-4b0e-8879-92d3357e848d.png)

If we use a different negative ID (e.g. `-10`), everything works as expected:
![screenshot-2](https://user-images.githubusercontent.com/6266600/208331664-df3c4aef-f4ca-4931-a825-81de1ac2bdc7.png)

### Expected behaviour

It is probably best to throw an error when using negative IDs for normal text-properties since they are already used for virtual text. The help only mentions that the ID "should be positive".

### Version of Vim

9.0.1075

### Environment

Linux

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Run `vim --clean -S test.vim`, with
> 
> ```vim
> vim9script
> 
> setline(1, ['one', 'two', 'three'])
> prop_type_add('test_1', {highlight: 'Error'})
> prop_type_add('test_2', {highlight: 'WildMenu'})
> 
> prop_add(3, 1, {
>     type: 'test_1',
>     length: 5,
>     id: -1
> })
> 
> prop_add(1, 0, {
>     type: 'test_2',
>     text: 'The quick brown fox jumps over the lazy dog',
>     text_padding_left: 2
> })
> ```
> 
> Result: Instead of highlighting the word `three` on the third line,
> Vim inserts the text from the first virtual text.

The problem is that there was a tiny chance that someone had been using
negative IDs before I decided to use them for virtual text.  The space
available for storing the ID is limited, using a negative ID for virtual
text properties was an effective way of doing this.  But in case someone
did use a negative ID an error would need to be given. In the sequence
you used this error is missing.

If you would change the order then you would get an error.  I suppose I
could set a flag that a negative ID was used and refuse to add virtual
text then.  Since a negative ID would be very rare this is probably an
acceptable solution.


-- 
    [clop clop]
ARTHUR:  Old woman!
DENNIS:  Man!
ARTHUR:  Man, sorry.  What knight lives in that castle over there?
DENNIS:  I'm thirty seven.
ARTHUR:  What?
DENNIS:  I'm thirty seven -- I'm not old!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
