### ISSUE TITLE
[vim9] Type mismatch and numerical errors

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#11753]
### Steps to reproduce

Source the following script:

```vim
vim9script

def Scan(rel: list<dict<any>>): func(func(dict<any>))
  return (Emit: func(dict<any>)) => {
    for t in rel
      Emit(t)
    endfor
  }
enddef

def Sum(Cont: func(func(dict<any>)), attr: string): any
  var sum = 0.0
  Cont((t: dict<any>) => {
    sum += t[attr]
  })
  return sum
enddef

const r = [{A: 3}, {A: 2}, {A: 7}]

echo Scan(r)->Sum('A')
```

This results in:

    E1012: Type mismatch; expected float but got number

Besides, if I change the argument type of the lambda from `dict<any>` to `dict<float>` (second line of `Sum`'s body), instead of an error I get this result:

    5.928788e-323

If the values of `r` are changed to float, e.g.:

    const r = [{A: 3.0}, {A: 2.0}, {A: 7.0}]

then the result (`12.0`) is computed correctly, even with the weaker typing  of the lambda.

### Expected behaviour

The result should always be `12.0`.

### Version of Vim

9.0.1103

### Environment

macOS 13.1
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by lifepillar** [comment]
This is a simplified script that reproduces the type mismatch error:

```vim
vim9script

def Sum(v: any): float
  var sum = 0.0
  sum += <float>v
  return sum
enddef

const kk = 1

echo Sum(kk)
```

I am wondering whether my assumptions on how Vim 9 script is supposed to deal with casting from integer to float are correct. My expectation is that a value of type `number` can always be cast into a value of type `float`.

**Comment by brammool** [comment]
> This is a simplified script that reproduces the type mismatch error:
> 
> ```vim
> vim9script
> 
> def Sum(v: any): float
>   var sum = 0.0
>   sum += <float>v
>   return sum
> enddef
> 
> const kk = 1
> 
> echo Sum(kk)
> ```
> 
> I am wondering whether my assumptions on how Vim 9 script is supposed
> to deal with casting from integer to float are correct. My expectation
> is that a value of type `number` can always be cast into a value of
> type `float`.

A type cast changes the type but not the value.  This is mentioned in
the help at ":help type-casting".

In this example it actually does the opposite of what you wanted.  But
there also is a bug.

This should work:
   var sum = 0.0
   sum += v

Adding a number to a float works. And it does if we know the type at
compile time.  But in this case the type is "any" and we need a runtime
type check.  That one was checking for float.  I'll make a fix for that.

Adding the "<float>" type check will make it fail, since a number is
passed and the type is explicitly checked to be a float.  This may be a
bit unexpected, and I had been wondering whether we should actually
change the value, turning the number into a float.  Quite a few
languages do it this way.  On the other hand, it's been like this for
almost a year now, and this appears to be the first time a problem is
encountered.  So it might be better just to leave it as it is.

-- 
Sorry, no fortune today.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
>Adding the `<float>` type check will make it fail, since a number is passed and the type is explicitly checked to be a float.

Thanks for the explanation! I should have paid more attention to the help file.

Back on topic: I confirm that the type mismatch error is fixed (thanks!), but the following code, which is a slight simplification of the code I originally posted, still gives some unexpected results:

```vim
vim9script

def Scan(ll: list<any>): func(func(any))
  return (Emit: func(any)) => {
    for e in ll
      Emit(e)
    endfor
  }
enddef

def Sum(Cont: func(func(any))): any
  var sum = 0.0
  Cont((v: float) => {  # <== NOTE: the lambda expects a float
    sum += v
  })
  return sum
enddef

const x = [3, 2, 7]
const y = [3.0, 2, 7]
const w = [3.0, 2.0, 7]

echo Scan(x)->Sum()  # 5.928788e-323
echo Scan(y)->Sum()  # 3.0
echo Scan(w)->Sum()  # 5.0
```

It seems as if the values of type `number` are silently ignored. The code computes the correct sum if the type of the lambda's argument is relaxed to `any`.

For comparison, the “straightforward” version of the code above raises an error:

```vim
def Sum(l: list<float>): float
   var sum = 0.0
   for v in l
     sum += v
   endfor
   return sum
 enddef

const x = [3, 2, 7]

echo Sum(x)  # Error: passing list of numbers to a function expecting list of floats
```
Probably, also the code above should produce a similar error.

**Comment by brammool** [comment]
> >Adding the `<float>` type check will make it fail, since a number is
> >passed and the type is explicitly checked to be a float.
> 
> Thanks for the explanation! I should have paid more attention to the help file.
> 
> Back on topic: I confirm that the type mismatch error is fixed
> (thanks!), but the following code, which is a slight simplification of
> the code I originally posted, still gives some unexpected results:
> 
> ```vim
> vim9script
> 
> def Scan(ll: list<any>): func(func(any))
>   return (Emit: func(any)) => {
>     for e in ll
>       Emit(e)
>     endfor
>   }
> enddef
> 
> def Sum(Cont: func(func(any))): any
>   var sum = 0.0
>   Cont((v: float) => {  # <== NOTE: the lambda expects a float
>     sum += v
>   })
>   return sum
> enddef
> 
> const x = [3, 2, 7]
> const y = [3.0, 2, 7]
> const w = [3.0, 2.0, 7]
> 
> echo Scan(x)->Sum()  # 5.928788e-323
> echo Scan(y)->Sum()  # 3.0
> echo Scan(w)->Sum()  # 5.0
> ```
> 
> It seems as if the values of type `number` are silently ignored. The
> code computes the correct sum if the type of the lambda's argument is
> relaxed to `any`.
> 
> For comparison, the “straightforward” version of the code above raises
> an error:
> 
> ```vim
> def Sum(l: list<float>): float
>    var sum = 0.0
>    for v in l
>      sum += v
>    endfor
>    return sum
>  enddef
> 
> const x = [3, 2, 7]
> 
> echo Sum(x)  # Error: passing list of numbers to a function expecting list of floats
> ```
> Probably, also the code above should produce a similar error.

Hmm, a bit complicated.  The code currently assumes the argument types
are checked at compile time, but since the type is defined as "any" and
the function being called expects a float, a runtime type check is
required.

The easiest is to do the runtime type check always.  I'll make a patch
for that.  It adds some overhead, but it avoids bad computations, or
perhaps even a crash (e.g. when a string is expected but a number is
passed).


-- 
A parent can be arrested if his child cannot hold back a burp during a church
service.
		[real standing law in Nebraska, United States of America]

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
