### ISSUE TITLE
Can't remap esc in normal mode (kitty terminal)

### ISSUE THREAD

**Issue by mg979** [vim/vim#11811]
Maybe related to https://github.com/vim/vim/commit/dffa6ea85c82bbcb60368f38f7437c6cd89c9e55

### Steps to reproduce

This happens in kitty terminal and maybe in others, it doesn't happen in Iterm2
```
vim --clean
:nnoremap <esc> i
```

Then press `i`

### Expected behaviour

Enters insert mode

### Version of Vim

9.0.1151

### Environment

MacOs, kitty terminal

**Comment by mg979** [comment]
I tried setting

    set keyprotocol=kitty:none

and

    set keyprotocol=kitty:mok2

But that mapping still doesn't work.

I have to try the patch you just made, though, thanks.

**Comment by madjxatw** [comment]
This seems not fixed yet, currently using 9.0.1285. I also tried launching vim using `vim --clean --cmd 'set kpc=kitty:none' but still got `Kitty keyboard protocol: On `.

**Comment by mg979** [comment]
For me it worked, in the sense that my issue with `nnoremap <esc>` was fixed.

**Comment by madjxatw** [comment]
> For me it worked, in the sense that my issue with `nnoremap <esc>` was fixed.

I'm using ubuntu ppa packaged `9.0.0749+really.v9.0.1285-0york0~ubuntu20.04.1`, and <Esc> key produces `^[[27;129u`. I'm using several plugins that remap `<Esc>` and now they all fail.

**Comment by brammool** [comment]
> This seems not fixed yet, currently using 9.0.1285. I also tried
> launching vim using `vim --clean --cmd 'set kpc=kitty:none' but still
> got `Kitty keyboard protocol: On `.

It is fixed when not using a modifier, but you apparently have NumLock
pressed, which Kitty adds as a modifier to the escape sequence for Esc.
Internally K_ESC needs to be used to match what mappings expect.
Let me reopen this issue and make a fix.

After changing 'keyprotocol' it does not take effect immediately.  The
help mentions this.  To make it work do:

	let &term = &term

-- 
I AM THANKFUL...
...for a lawn that needs mowing, windows that need cleaning
and gutters that need fixing because it means I have a home.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by madjxatw** [comment]
> This seems not fixed yet, currently using 9.0.1285. I also tried launching vim using `vim --clean --cmd 'set kpc=kitty:none' but still got `Kitty keyboard protocol: On `.
> It is fixed when not using a modifier, but you apparently have NumLock pressed, which Kitty adds as a modifier to the escape sequence for Esc. Internally K_ESC needs to be used to match what mappings expect. Let me reopen this issue and make a fix. After changing 'keyprotocol' it does not take effect immediately. The help mentions this. To make it work do: let &term = &term
> […](#)
> -- I AM THANKFUL... ...for a lawn that needs mowing, windows that need cleaning and gutters that need fixing because it means I have a home. /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

Bram, thanks for pointing this out!
