### ISSUE TITLE
Keys behave unexpectedly

### ISSUE THREAD

**Issue by erzoe** [vim/vim#11821]
### Steps to reproduce

Since doing an update yesterday many keys behave weirdly when running vim in kitty: `Page Up`, `Page Down`, `Delete`, `Insert`, `F5`, `F6`, `F7`, `F8`, `F9`, `F10`, `F11`, `F12`. They all have the same effect which is equivalent to `Escape` `1` `2` `9` `~`.

Pressing Control+V in vim + kitty reveals that the keys are not identical, e.g.

- `Page Up` produces `^[[5;129~`
- `Page Down` produces `^[[6;129~`

These keys still work normally when running vim in alacritty. Therefore I first thought this was a bug in kitty but kitty's maintainer says this is a bug in vim ([see his comment](https://github.com/kovidgoyal/kitty/issues/5885#issuecomment-1383033173)).

The difference between kitty and alacritty is that kitty sends the status of num lock (the 129) while alacritty does not. In alacritty typing Conrtol+V Page Up inserts `^[[5~`.

Trying to use Shift+F5 or Control+F5 does not work in alacritty anymore, either. There

- Shift + Page Up produces `^[[15;2~`
- Control + Page Up produces `^[[15;5~`

as expected after reading [the keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-functional-keys), [the values of the modifiers](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers) and considering that alacritty seems to not send num lock to the application.

In vim + kitty Shift + Page Up produces `^[[15;130~`.

Steps to reproduce:
1.    open vim in kitty
2.    press i to start insert mode
3.    press i to insert any character
4.    press Page Up, vim leaves insert mode and makes the i upper case (and toggles the case of up to 128 more characters if there are more characters on the line).

### Expected behaviour

vim should not leave insert mode. Vim should not change the text. In case of Page Up: Vim should move upwards if it is not at the top of the file.

### Version of Vim

9.0, Included patches: 1-1182

### Environment

Operating System: Arch Linux
Terminal: Kitty

```bash
$ echo $TERM
xterm-kitty
$ echo $TERMINFO
/usr/lib/kitty/terminfo
$ tree $TERMINFO
/usr/lib/kitty/terminfo
├── kitty.termcap
├── kitty.terminfo
└── x
    └── xterm-kitty

2 directories, 3 files
$ grep kpp $TERMINFO/kitty.terminfo
	kpp=\E[5~,
$
$ kitty --version
kitty 0.26.5 created by Kovid Goyal
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18)
Included patches: 1-1182
Compiled by Arch Linux
```

### Logs and stack traces

```shell
$ kitty --config=NONE vim --clean
[014 15:19:35.712548] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.ServiceUnknown] The name org.freedesktop.portal.Desktop was not provided by any .service files
[014 15:19:35.746287] [PARSE ERROR] Unrecognized DCS code: 0x7a
[014 15:19:35.746336] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'
[014 15:19:35.769570] [PARSE ERROR] Unknown terminfo property: PS
[014 15:19:35.769668] [PARSE ERROR] Unknown terminfo property: PE
Failed to load libcanberra.so, cannot play beep sound, with error: libcanberra.so.0.2.5: cannot open shared object file: No such file or directory
[014 15:19:52.030926] [PARSE ERROR] The application is trying to use xterm's modifyOtherKeys. This is superseded by the kitty keyboard protocol: https://sw.kovidgoyal.net/kitty/keyboard-protocol/ the application should be updated to use that
[014 15:19:52.030952] [PARSE ERROR] The application is trying to use xterm's modifyOtherKeys. This is superseded by the kitty keyboard protocol: https://sw.kovidgoyal.net/kitty/keyboard-protocol/ the application should be updated to use that
[014 15:19:52.030958] [PARSE ERROR] The application is trying to use xterm's modifyOtherKeys. This is superseded by the kitty keyboard protocol: https://sw.kovidgoyal.net/kitty/keyboard-protocol/ the application should be updated to use that
```

**Comment by brammool** [comment]
The problem is that the termcap entries for PageUp and PageDown do not
indicate that modifiers may be supplied.  If you look in the older Vim
you should see in the output of ":set termcap":

	t_kN <PageDown>  <1b>[6;*~
	t_kP <PageUp>    <1b>[5;*~

Here the ";*" indicates where modifiers might appear.  With the new
version you get:

	t_kN <PageDown>  <1b>[6~
	t_kP <PageUp>    <1b>[5~

Therefore no modifiers are recognized. Vim does not know what those
escape sequences are and passes them on so that they can be mapped.
These codes come from terminfo/termcap, this is what the terminal is
expected to send.

In the older Vim the "xterm" prefix in $TERM was used to pick up the
builtin xterm termcap entries.  However, kitty is not really xterm
compatible, thus this is a workaround/hack.  This was disabled at some
point.

I am currently trying to make a proper solution for these terminals that
put "xterm" in their name to just pick up the builtin termcap entries.
This is not the way it should work, it creates problems that then have
be be solved in various ways.  This is not a good direction to continue,
it will keep giving maintenance problems.

Unfortunately, the terminfo mechanism does not provide a generic way for
key modifiers.  There are a few keys for which the shifted code can be
specificed, but that is very limited.  Including the codes for every
combination of key and modifier would blow up the list, that is not a
good solution either.

I'm afraid there is no clear solution yet.  It is disappointing to see
that several terminal emulators have appeared recently, all adding
various fancy features and/or performance, but none of them have tackled
this essential problem.  This leads to applications hard-coding key
codes and a maintenance problem all over the place.

For the time being you can add something to your vimrc:

	if &term =~ 'kitty'
	  let &t_kN = "\<ESC>[6;*~"
	  let &t_kP = "\<ESC>[5;*~"
	endif

And similarly for other keys.

I do hope we manage to find and implement a generic, long-term solution
soon.  Not only for Vim but for every application that deals with
special keys.


> The difference between kitty and alacritty is that kitty sends the
> status of num lock (the 129) while alacritty does not. In alacritty
> typing Conrtol+V Page Up inserts `^[[5~`.
> 
> Trying to use Shift+F5 or Control+F5 does not work in alacritty
> anymore, either. There
> 
> - Shift + Page Up produces `^[[15;2~`
> - Control + Page Up produces `^[[15;5~`

I'm not sure why Kitty includes the status of num-lock, it is irrelevant
for these keys.  Anyway, what you see does confirm what I said.


-- 
hundred-and-one symptoms of being an internet addict:
14. You start introducing yourself as "Jim at I-I-Net dot net dot au"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by erzoe** [comment]
Thank you very much for your helpful explanation. I have added the following to my vimrc and now the keys work again. I have commented out the if statement because this is useful in alacritty, too, for Shift+F5.

```vim
"if &term =~ 'kitty'
	" <PageUp>
	let &t_kP = "\<ESC>[5;*~"
	" <PageDown>
	let &t_kN = "\<ESC>[6;*~"
	" <Del>
	let &t_kD = "\<ESC>[3;*~"
	" <Insert>
	let &t_kI = "\<ESC>[2;*~"
	" <F5>
	let &t_k5 = "\<ESC>[15;*~"
	" <F6>
	let &t_k6 = "\<ESC>[17;*~"
	" <F7>
	let &t_k7 = "\<ESC>[18;*~"
	" <F8>
	let &t_k8 = "\<ESC>[19;*~"
	" <F9>
	let &t_k9 = "\<ESC>[20;*~"
	" <F10>
	let &t_k; = "\<ESC>[21;*~"
	" <F11>
	let &t_F1 = "\<ESC>[23;*~"
	" <F12>
	let &t_F2 = "\<ESC>[24;*~"
"endif
```

**Comment by brammool** [comment]
I could not find a way to fix this in a generic way, outside of Vim.
Patch 9.0.1220 adjusts some of the terminfo/termcap entries that are mentioned in this issue.
This is not ideal, but it should fix the problem.

**Comment by X-dark** [comment]
Thanks for the fix and the temporary workaround.

Enter key on the numpad is behaving strange as well, outputting a character that look like a forward quote:  (my browser fail to render it).

Not sure if your fix will take care of that (could not test yet) and I could not find the corresponding key when doing a set termcap

**Comment by erzoe** [comment]
> I could not find the corresponding key when doing a set termcap

The code for the keypard enter key is `t_KA`, see `:tab help terminal-key-codes`.

I found this by trying `:tab help termcap`. It was not there but at the bottom of the screen I saw some codes which looked similar so I followed them with Ctrl+]. That took me to the output codes and below those are the key codes.

**Comment by X-dark** [comment]
Thanks, this is the help page I was looking for.
I then fixed it with:

```
let &t_KA = ""
```
