### ISSUE TITLE
[vim9] Fix eval() typing with objects

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#11826]
I write this as a feature request, because I am not sure what the fate of `eval()` will be in Vim 9 script.

The following code defines a `Ref()` function that allows you to refer to a function that has not been defined yet. The code fails with `E1012: Type mismatch; expected object<Num> but got any`:

```vim
vim9script

class Num
  this.n: number = 0
endclass

def Ref(name: string): func(Num): Num
  return (arg: Num): Num => {
    return eval(name)(arg)
  }
enddef

const Fn = Ref('Double')   # <=== Fails here
Double = (m: Num): Num => Num.new(m.n * 2)

echo Fn(Num.new(4))
```

The error is due to the use of a class: for built-in types, a similar code works just fine:

```vim
def Ref(name: string): func(number): number
  return (arg: number): number => {
    return eval(name)(arg)
  }
enddef

const Fn = Ref('Double')  # OK

def Double(n: number): number
  return n * 2
enddef

echo Fn(4)  # 8
```

My question is: will `eval()` support such use cases in Vim 9 script?

**Comment by brammool** [comment]
> I write this as a feature request, because I am not sure what the fate
> of `eval()` will be in Vim 9 script.
> 
> The following code defines a `Ref()` function that allows you to refer
> to a function that has not been defined yet. The code fails with
> `E1012: Type mismatch; expected object<Num> but got any`:
> 
> ```vim
> vim9script
> 
> class Num
>   this.n: number = 0
> endclass
> 
> def Ref(name: string): func(Num): Num
>   return (arg: Num): Num => {
>     return eval(name)(arg)
>   }
> enddef
> 
> const Fn = Ref('Double')   # <=== Fails here
> Double = (m: Num): Num => Num.new(m.n * 2)
> 
> echo Fn(Num.new(4))
> ```
> 
> The error is due to the use of a class: for built-in types, a similar code works just fine:
> 
> ```vim
> def Ref(name: string): func(number): number
>   return (arg: number): number => {
>     return eval(name)(arg)
>   }
> enddef
> 
> const Fn = Ref('Double')  # OK
> 
> def Double(n: number): number
>   return n * 2
> enddef
> 
> echo Fn(4)  # 8
> ```
> 
> My question is: will `eval()` support such use cases in Vim 9 script?

This is unrelated to what eval() does, it only matters that the return
type is "any".  At compile time there is a check that the return type of
the lambda matches the return type of Ref().  This fails, because the
expected type is object<Num> while the type at compilation time is
"any".

What is missing here is that instead if failing this should use a
runtime type check, since "any" could be the desired type when executing
the code.  I'll make a patch for that.

-- 
Anyone who is capable of getting themselves made President should on no
account be allowed to do the job.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Sorry for misreporting! I confirm that the patch fixes my issue. Thanks!
