### ISSUE TITLE
[vim9] Pass a list to a function with variable arguments

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#11865]
Consider this snippet:

```vim
def F(...items: list<any>)
  echo items
enddef
```

Invoking as `F(1, 2, 3)` will pass three arguments. But `F([1, 2, 3])` (correctly) passes one argument, not three. So far, so good. There may be circumstances, however, when it may be convenient to prepare a list of arguments in advance and then invoke the function, e.g.:

```vim
const args = [1, 2, 3]
F(args)  # NOT the same as F(1, 2, 3)
```

It would be nice, imo, if a list such as `args` could be passed to a varargs function, by using for instance a syntax such as `F(...args)`.

What do you think?

**Comment by brammool** [comment]
> Consider this snippet:
> 
> ```vim
> def F(...items: list<any>)
>   echo items
> enddef
> ```
> 
> Invoking as `F(1, 2, 3)` will pass three arguments. But `F([1, 2, 3])`
> (correctly) passes one argument, not three. So far, so good. There may
> be circumstances, however, when it may be convenient to prepare a list
> of arguments in advance and then invoke the function, e.g.:
> 
> ```vim
> const args = [1, 2, 3]
> F(args)  # NOT the same as F(1, 2, 3)
> ```
> 
> It would be nice, imo, if a list such as `args` could be passed to a
> varargs function, by using for instance a syntax such as `F(...args)`.
> 
> What do you think?

Try using call().  For your example this should work:
```
  const args = [1, 2, 3]
  call(F, args)
```

This turns the list into three arguments and then back into a list
again for varargs.  Adding a new syntax to avoid that doesn't seem
necessary though.


-- 
Everybody lies, but it doesn't matter since nobody listens.
                                -- Lieberman's Law

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
Ah, right, I had forgotten about `call`!

**Comment by qeatzy** [comment]
Found this issue when search unpack variable arguments. As the previous comments stated, the answer is use `call()`.

But currently it's half solution.
It fails when first arg is an object method instead of plain function.

Here is a reproducing snippet.

```
vim9script

export class FWin # popup window, float window
    this.winid: number
    def Echo(...vals: list<any>)
        const x = len(vals) == 1 ? string(vals[0]) : string(vals)
        echo x
    enddef
endclass

var g_echoer = FWin.new()
def Echo(...vals: list<any>)
    call(g_echoer.Echo, vals)
enddef

Echo(1, 2, 3, "hello")
```
error message below. `echo v:versionlong # 9001558`
```
Error detected while compiling function <SNR>169_Echo:
line    1:
E1123: Missing comma before argument: Echo, vals)

```
