### ISSUE TITLE
Weird interaction of `autoindent` and `noshowcmd`

### ISSUE THREAD

**Issue by monkoose** [vim/vim#11877]
### Steps to reproduce

1. vim --clean +"set autoindent noshowcmd wd=1"
2.  `i<Tab>hello world<Esc>gea<CR><Esc>`
3.  After leaving insert mode with last Esc cursor jumps to the first column and then back to the column right to `world`.

Maybe related issue #11309

### Expected behaviour

Cursor doesn't jump back and forth like with `showcmd` enabled.

### Version of Vim

9.0.1182

### Environment

OS: ArchLinux
Terminal: st

**Comment by chrisbra** [comment]
I don't see this, but you are using the ['writedelay'](https://vimhelp.org/options.txt.html#%27wd%27) option, which is there for debugging and analyzing of the redrawing functionality. As such it may be expected to see the cursor jump, because internally in the C source for several features the cursor is re-positioned. 

I don't think this is a valid issue here.

**Comment by monkoose** [comment]
I have it without wd option, just add it to be more noticeable. 
What vim version are you on? Let me try it the same things on it.

**Comment by zeertzjq** [comment]
This seems to be related to the TERM environment variable. When I run Vim inside Vim's terminal inside kitty, I can reproduce this if TERM is set to `xterm-256color`, but not if TERM is set to `xterm-kitty`.

**Comment by monkoose** [comment]
@zeertzjq thanks for the investigation, should have think of it myself and test with another terminal.

**Comment by chrisbra** [comment]
It's not a bug, Vim may change the cursor positioning to perform certain actions. It's just that you normally do not see it.

**Comment by monkoose** [comment]
Wtf, I normally do see it.

You are not helping.

**Comment by chrisbra** [comment]
> Wtf, I normally do see it.

> You are not helping.

It helps if you could stay polite. Thanks.

Perhaps I am not understanding the problem right. I do not see this issue in a putty terminal and in gvim. And that fact that you need to `:set wd=1`  to make it show, makes me believe it is not an issue, since this is for debugging only.

So does this have anything to do with setting 'wd'? or not? Can you perhaps record a screen recording and make it more obvious what your problem is?

**Comment by monkoose** [comment]
> I have it without wd option, just added it to make this bug more noticeable.

**Comment by monkoose** [comment]
> I do not see this issue .... in gvim
Can confirm that it doesn't happen in gvim. But i have tested a few terminal emulators (xfce4-terminal, alacritty and my default st) - they all have this jumping issue with `vim --clean +"set autoindent noshowcmd"

**Comment by brammool** [comment]
> I have it without wd option, just add it to be more noticeable. 

It may depend on the 'ttimeoutlen' option value.

The cursor is moved when pressing Esc in Insert mode, while waiting for
more characters to arrive.  That is because the Esc could be the start
of an escape sequence.  This is a trick used to make the effect of
pressing Esc visible without knowing if it indeed was the Esc key.

When using the kitty key protocol the Esc key is sent as a special
escape sequence and this trick is not used.

Why this only happens when 'showcmd' is off I don't know yet, I'll
investigate.  Perhaps that can be fixed.

-- 
hundred-and-one symptoms of being an internet addict:
44. Your friends no longer send you e-mail...they just log on to your IRC
    channel.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
