### ISSUE TITLE
Unexpected input using Alt modifier in Kitty terminal.

### ISSUE THREAD

**Issue by adriantrunzo** [vim/vim#11913]
### Steps to reproduce

My goal is to use meta/alt key mappings in Vim. Lowercase letter mappings (e.g `<M-a>`) work just fine when using Kitty, but uppercase mappings (eg `<M-A>`) do not. I do not encounter this issue in other terminals that I have tried: macOS Terminal.app and WezTerm. In each of these three terminals, I am using the appropriate configuration to treat Alt as Meta rather than the macOS default alternate characters; `macos_option_as_alt` on Kitty, `Use Option as Meta key` in Terminal.app settings, and `send_composed_key_when_left_alt_is_pressed` in WezTerm.

While trying to troubleshoot why my mappings were not working, I noticed that Vim seems to interpret input from Kitty differently than other terminals, at least when it comes to the Alt modifier.

First in compatible mode:
1. Open Kitty with the minimal configuration `kitty -c NONE -o macos_option_as_alt=both`
2. Open Vim with `vim -u NONE -C`
3. In insert mode, enter the sequence `Ctrl-v` `Alt-b` `Ctrl-v` `Alt-B`
4. Escape back to normal mode.
5. Verify that the buffer contains `^[b^[B`.

Now repeat the above in incompatible mode and notice the final difference in the buffer content:
1. Open Kitty with the minimal configuration `kitty -c NONE -o macos_option_as_alt=both`
2. Open Vim with `vim -u NONE -N`
3. In insert mode, enter the sequence `Ctrl-v` `Alt-b` `Ctrl-v` `Alt-B`
4. Escape back to normal mode.
5. Verify that the buffer contains `ââ`.

In both WezTerm and Terminal.app, the buffer content is `^[b^[B` in both cases. The `ââ` in Kitty is odd. When I run `sed -n l` in Kitty and type `Alt-b` `Alt-B` I get the expected output `^[b^[B`. 

For an example of the mappings I am trying to achieve, here is a minimal vimrc:

```vim
set nocompatible
set ttimeout
set ttimeoutlen=100

map <Esc>b <M-b>
map <Esc>B <M-B>

nnoremap <M-b> <Cmd>bnext<CR>
nnoremap <M-B> <Cmd>bprevious<CR>
```

With that minimal config saved as `~/reproduce.vim` and running Vim as `vim --clean -u ~/reproduce.vim`, the `Alt-b` and `Alt-B` maps work just fine in macOS Terminal.app and WezTerm. In Kitty, though, only the `Alt-b` map works and `Alt-B` does nothing (that I can see).

### Expected behaviour

- I expect the sequence `Ctrl-v` `Alt-b` `Ctrl-v` `Alt-B` in insert mode in Kitty to produce `^[b^[B` and not `ââ`. 
- I expect the two mappings `<M-b>` and `<M-B>` as defined in the minimal vim configuration above to work in Kitty as well as Terminal.app and WezTerm.

### Version of Vim

9.0.1250

### Environment

OS: macOS Ventura 13.1
Terminals: Kitty 0.26.5, Terminal.app 2.13, WezTerm 20221119-145034-49b9839f
$TERM: xterm-kitty, xterm-256color, wezterm
Shell: zsh 5.8.1 (x86_64-apple-darwin22.0)

### Logs and stack traces

```shell
I am not sure how to get relevant logs for this issue, but I would be happy to provide some if given instructions.
```

**Comment by brammool** [comment]
I can reproduce getting different results depending on whether "-C" or "-N" was used.
The character you get with "-N" seems correct: 'b' with Alt applied results in â (which is decimal 226, same as 98 + 128, where 98 is 'b' and 18 is added for Alt.

I assume that for "Alt-B" you actually press both Alt and Shift, right?

I haven't found yet why using "-C" works differently.  I haven't looked at the mapping stuff yet.

**Comment by adriantrunzo** [comment]
Thanks for the reply. You are correct that for `Alt-B` I am pressing Alt+Shift+b. I have a limited understanding of how terminals handle keyboard input, but should Alt+Shift+b also produce â? I would expect a different character depending on the presence of Shift.

It's unclear to me if I am setting up the mappings correctly, so I am open to suggestions. I couldn't get Vim to recognize `<M-` mappings in any terminal without statements like `map \eb <M-b>` or `map ^[b <M-b>`, which I based on the output of `Ctrl-v`.

**Comment by brammool** [comment]
> Thanks for the reply. You are correct that for `Alt-B` I am pressing
> Alt+Shift+b. I have a limited understanding of how terminals handle
> keyboard input, but should Alt+Shift+b also produce â? I would expect a
> different character depending on the presence of Shift.

Yes, adding Shift should give a different character.  The problem might
be that Vim expects the terminal to apply Shift to the character, but
Kitty isn't doing that.  For letters it's easy to handle, but otherwise
it depends on the keyboard layout, which Vim has no knowledge about.

> It's unclear to me if I am setting up the mappings correctly, so I am
> open to suggestions. I couldn't get Vim to recognize `<M-` mappings in
> any terminal without statements like `map \eb <M-b>` or `map ^[b <M-b>`,
> which I based on the output of `Ctrl-v`. 

Some terminals have a possibility to have the Alt key prefix an Escape
character.  Vim doesn't handle that, because it is ambiguous.  Make sure
your terminal isn't configured to use Alt like that.

-- 
UPS - Unknown Package Status

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I noticed [this pitfall](https://github.com/lacygoill/vim-lg-lib/blob/87397f7efd6ef28f6d2a1d89a65d07fe3fe4b191/import/lg/mapping.vim#L266-L275) a long time ago.  It also affects a terminal in which modifyOtherKeys is enabled, as well as the GUI.

MRE:

    $ vim -Nu NONE -g +'nnoremap <unique> <M-G> <Scriptcmd>echo "M-G"<CR>' \
                      +'nnoremap <unique> <M-S-G> <Scriptcmd>echo "M-S-G"<CR>'

Gives this error:

    E227: mapping already exists for Ç

**Comment by lacygoill** [comment]
Never mind, I can reproduce even in a terminal where modifyOtherKeys is disabled.  A patch must have changed this behavior.  In any case, I don't know how to map anything to `<M-[A-Z]>` in kitty.

**Comment by lacygoill** [comment]
Neither of these work:

    $ vim -Nu NONE +'nnoremap <M-B> <Cmd>echomsg "M-B"<CR>'
    $ vim -Nu NONE +'nnoremap <M-S-b> <Cmd>echomsg "M-B"<CR>'
    $ vim -Nu NONE +'nnoremap <M-S-B> <Cmd>echomsg "M-B"<CR>'

Pressing `meta` + `shift` + `b` has no effect in kitty (but they do in xterm).

**Comment by lacygoill** [comment]
According to [`:help --log`](https://vimhelp.org/starting.txt.html#--log), here is what Vim receives in kitty when `meta` + `shift` + `b` are pressed:

    raw key input: "^[[98;132u"

And in xterm:

    raw key input: "^[[27;4;66~"

**Comment by lacygoill** [comment]
Also, in xterm, I wonder why Vim conflates `<M-B>` with `<M-S-B>`:

    $ vim -Nu NONE +'nnoremap <M-B> <Cmd>echomsg "M-B"<CR>'
    # pressing "meta + shift + b" prints "M-B"

But not `<C-B>` with `<C-S-B>`:

    $ vim -Nu NONE +'nnoremap <C-B> <Cmd>echomsg "C-B"<CR>'
    # pressing "ctrl + shift + b" prints nothing

And since Vim makes a distinction between `<C-B>` and `<C-S-B>`

    $ vim -Nu NONE +'nnoremap <C-B> <Cmd>echomsg "C-B"<CR>' \
                   +'nnoremap <C-S-B> <Cmd>echomsg "C-S-B"<CR>'
    # pressing "ctrl + b" prints "C-B"
    # pressing "ctrl + shift + b" prints "C-S-B"

Then why does it give an error when we pass the `<unique>` argument to `:map`:

    $ vim -Nu NONE +'nnoremap <unique> <C-B> <Cmd>echomsg "C-B"<CR>' \
                   +'nnoremap <unique> <C-S-B> <Cmd>echomsg "C-S-B"<CR>'

    E227: Mapping already exists for ^B

**Comment by brammool** [comment]
> According to [`:help --log`](https://vimhelp.org/starting.txt.html#--log), here is what Vim receives in kitty when `meta` + `shift` + `b` are pressed:
> 
>     raw key input: "^[[98;132u"
> 
> And in xterm:
> 
>     raw key input: "^[[27;4;66~"

Yeah, it appears Kitty doesn't apply the shift modifier to the
character.  It's easy enough to do on the Vim side for letters, but with
other keys we would have to guess what Shift does to a character.

The modifier value suggests you actually have a Meta key.  I have been
wondering if Vim should recognize this modifier and handle it like Alt.
Otherwise you can't really do anything with it.


-- 
From "know your smileys":
 :----}  You lie like Pinocchio

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Also, in xterm, I wonder why Vim conflates `<M-B>` with `<M-S-B>`:
> 
>     $ vim -Nu NONE +'nnoremap <M-B> <Cmd>echomsg "M-B"<CR>'
>     # pressing "meta + shift + b" prints "M-B"
> 
> But not `<C-B>` with `<C-S-B>`:
> 
>     $ vim -Nu NONE +'nnoremap <C-B> <Cmd>echomsg "C-B"<CR>'
>     # pressing "ctrl + shift + b" prints nothing
> 
> And since Vim makes a distinction between `<C-B>` and `<C-S-B>`
> 
>     $ vim -Nu NONE +'nnoremap <C-B> <Cmd>echomsg "C-B"<CR>' \
>                    +'nnoremap <C-S-B> <Cmd>echomsg "C-S-B"<CR>'
>     # pressing "ctrl + b" prints "C-B"
>     # pressing "ctrl + shift + b" prints "C-S-B"
> 
> Then why does it give an error when we pass the `<unique>` argument to `:map`:
> 
>     $ vim -Nu NONE +'nnoremap <unique> <C-B> <Cmd>echomsg "C-B"<CR>' \
>                    +'nnoremap <unique> <C-S-B> <Cmd>echomsg "C-S-B"<CR>'
> 
>     E227: Mapping already exists for ^B

Guessing (I haven't tried debugging this): with mappings like this, Vim
adds both a "simplified" mapping and a "precise" mapping.  The first is
used for terminals that do not pass the modifiers, only the resulting
character.  The second is used when the modifyOtherKeys or kitty key
protocol is supported.  In the first case you can't tell some key
combinations apart.

As soon as Vim knows the "precise" mappings are to be used, the
"simplified" ones are no longer used.  But you add these mappings before
Vim knows this.  So should the meaning of <unique> be adjusted assuming
a key protocol will be available?  I'm not sure (which usually means
it's probably best to leave it as it is).

-- 
From "know your smileys":
 y:-)	Bad toupee

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by adriantrunzo** [comment]
> According to [`:help --log`](https://vimhelp.org/starting.txt.html#--log), here is what Vim receives in kitty when `meta` + `shift` + `b` are pressed:
> 
> ```
> raw key input: "^[[98;132u"
> ```

@lacygoill Thank you for pointing out the `--log` option. It seems like a helpful tool for debugging my issue. Were you using the `macos_option_as_alt` Kitty setting when you captured that log input? With `macos_option_as_alt=both` and `vim -Nu NONE --log vim.txt`, I actually get the raw key inputs `[98;3u` and `[98;4u` for `Alt+b` and `Alt+Shift+b`, which seem to match [the schema described in the Kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers):

Alt+b -> `98;3u` -- 98 for `b` and `3` (1 + 0b10) for the alt modifier
Alt+Shift+b -> `98;4u` -- 98 for `b` and `4` ( 1 + 0b10 + 0b1) for the shift and alt modifiers

I can confirm Vim reports using the Kitty keyboard protocol when executing as `vim -Nu NONE`:

```
Kitty keyboard protocol: On
v  <BS>          "-d
v  <D-x>         "*d
v  <D-c>         "*y
v  <D-v>         "-d"*P
n  <D-v>         "*P
Press ENTER or type command to continue
```

Here's the relevant part of my log file, showing me pressing `i` to go into insert mode and then `Alt+b` followed by `Alt+Shift+b`:

```
  1.707207 : raw key input: "i"
  1.707278 : SafeState: reset: key typed
  1.707393 : SafeState: Start triggering
  1.707427 : raw terminal output: "[?25l[63;1H[1m-- INSERT --[1;1H[?12h[?25h"
  1.707442 : looking for messages on channels
  1.707454 : SafeState: back to waiting, triggering SafeStateAgain
  3.096433 : raw key input: "[98;3u"
  3.096513 : SafeState: reset: key typed
  3.100908 : SafeState: Start triggering
  3.100938 : setting timeout timer to 2 sec 0 nsec
  3.101062 : raw terminal output: "[?25l[0m√¢[26;100H[94m                 [28;100H                [29;96H                        [30;87H                                           [32;94H                             [33;85H                                              [35;85H                                              [36;85H                                              [37;85H                                              [1;2H[?12h[?25h"
  3.101077 : looking for messages on channels
  3.101087 : SafeState: back to waiting, triggering SafeStateAgain
  5.209017 : raw key input: "[98;4u"
  5.209109 : SafeState: reset: ins_typebuf()
  5.209163 : SafeState: Start triggering
  5.209191 : setting timeout timer to 2 sec 0 nsec
  5.209327 : raw terminal output: "[?25l[0m√¢[?12h[?25h"
  5.209345 : looking for messages on channels
  5.209372 : SafeState: back to waiting, triggering SafeStateAgain
```

It seems like Vim is not interpreting `[98;3u` and `[98;4u` correctly? Once again, I appreciate the help. I have already learned quite a bit from the replies.

**Comment by lacygoill** [comment]
> Yeah, it appears Kitty doesn't apply the shift modifier to the
   > character.  It's easy enough to do on the Vim side for letters, but with
   > other keys we would have to guess what Shift does to a character.

Supporting letters would cover most needs.  The only `M-S-` chord for which I map something in Vim uses a letter ([`<M-S-G>`](https://github.com/lacygoill/vim-window/blob/2c7cd1105ace75b9ca75f31fc52568eec5bb96cd/plugin/window.vim#L580)).

   > The modifier value suggests you actually have a Meta key.

I have a very common and cheap keyboard, and am on Ubuntu 20.04.

   > I have been wondering if Vim should recognize this modifier and handle it like Alt.
   > Otherwise you can't really do anything with it.

If it helps supporting more chords out of the box, then yes definitely.

   > Were you using the macos_option_as_alt Kitty setting when you captured that log input?

No, I'm using linux not macos, so I don't set this option.

**Comment by brammool** [comment]
>    > Yeah, it appears Kitty doesn't apply the shift modifier to the
>    > character.  It's easy enough to do on the Vim side for letters, but with
>    > other keys we would have to guess what Shift does to a character.
> 
> Supporting letters would cover most needs.  The only `M-S-` chord for
> which I map something in Vim uses a letter
> ([`<M-S-G>`](https://github.com/lacygoill/vim-window/blob/2c7cd1105ace75b9ca75f31fc52568eec5bb96cd/plugin/window.vim#L580)).
> 
>    > The modifier value suggests you actually have a Meta key.
> 
> I have a very common and cheap keyboard, and am on Ubuntu 20.04.

It doesn't depend on the price :-).  No matter if the keyboard actually
has a key labelled Meta, the configuration can change keys to mean Meta.
Perhaps the Windows key can be used as Meta key.

>    > I have been wondering if Vim should recognize this modifier and handle it like Alt.
>    > Otherwise you can't really do anything with it.
> 
> If it helps supporting more chords out of the box, then yes definitely.

Currently Vim considers the "M" modifier the same as "A".  If we
consider Meta similar to the Command key on Mac, then we could use the
"D" modifier.  Might be confusing though.  The code actually supports
the "T" modifier for Meta, but I can't find it documented in the help.
It seems it's only implemented for GTK, Motif and xterm.


-- 
From "know your smileys":
 ;-0	Can't find shift key
 ,-9	Kann Umschalttaste nicht finden

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
Well, please don't use "D" for Meta, because it's already used for Command on Mac.  We don't want to blur Command and Meta together.  The whole point of the kitty protocol is to disambiguate.

**Comment by adriantrunzo** [comment]
Hi all, I am going to close this issue in favor of https://github.com/vim/vim/issues/11936, which more succinctly describes the issue I am encountering. I've used information learned from the replies here to, hopefully, describe the problem more accurately. I have realized that with the Kitty Keyboard Protocol, I have no need for lines like `map <Esc>b <M-b>` to get Alt mappings to work.

**Comment by brammool** [comment]
> Well, please don't use "D" for Meta, because it's already used for
> Command on Mac.  We don't want to blur Command and Meta together.  The
> whole point of the kitty protocol is to disambiguate.

It turns out the "T" key was already implemented to be used for Meta.
We can use that one.  It's not mentioned in the help and I doubt anyone
is using it, but might as well use it now.

For the Kitty keyboard protocol the modifiers "super" and "hyper" are
also defined, even though I have never seen them used.  I think they
should also be handled like "meta".  I don't really want to add
modifiers that only work with one key protocol.

-- 
From "know your smileys":
 ...---...   SOS

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The character to use for the Meta key is "T".  Try these:

None of these work in kitty.  But `M` does work since the patch [9.0.1276](https://github.com/vim/vim/releases/tag/v9.0.1276).  As far as I'm concerned, the issue is now fixed, thank you very much.

   > Would it be OK to assume the US layout?  Then at least it will work for some people.

I don't know.  I guess someone with a different layout could still install their mappings, but they would have to know what is the correspoding key in a US layout.  I think [keyd](https://github.com/rvaiya/keyd) lets the user discover that key:

    $ sudo keyd --monitor

For example, on my [AZERTY keyboard](https://m.media-amazon.com/images/I/61mb9jQBcuL._AC_SL1500_.jpg), the keycap in the upper-left corner (below ESC and the function keys) has a "two superscript" marking on it.  But according to `keyd(1)`, in a QWERTY layout, that key actually produces a backtick.  So if I wanted to map something to the chord `Meta/Alt` + `Shift` + `²`, in Vim I would need to write a backtick:

    nnoremap <M-S-`> <Cmd>echomsg 'so some stuff'<CR>
                  ^
                  ✔

Not a superscript two:

    nnoremap <M-S-²> <Cmd>echomsg 'so some stuff'<CR>
                  ^
                  ✘

We would need to document this pitfall, and give [some context](https://github.com/rvaiya/keyd/issues/193#issuecomment-1103195151).

**Comment by brammool** [comment]
> I noticed [this pitfall](https://github.com/lacygoill/vim-lg-lib/blob/87397f7efd6ef28f6d2a1d89a65d07fe3fe4b191/import/lg/mapping.vim#L266-L275) a long time ago.  It also affects a terminal in which modifyOtherKeys is enabled, as well as the GUI.
> 
> MRE:
> 
>     $ vim -Nu NONE -g +'nnoremap <unique> <M-G> <Scriptcmd>echo "M-G"<CR>' \
>                       +'nnoremap <unique> <M-S-G> <Scriptcmd>echo "M-S-G"<CR>'
> 
> Gives this error:
> 
>     E227: mapping already exists for Ç

What happens here is not very logical: <M-G> differs from <M-g>.
The first one has an upper case "G", which then get Meta (Alt) applied,
thus the 8th bit is set.  That result in Ç.  <M-S-G> does the same,
since the Shift modifier doesn't change "G".

It does work if <M-G> is changed to <M-g>.  Then the simplified form,
with the 8th bit set, is ç.

Since this is illogical I thought of perhap changing <M-G> to work like
<M-g>, but that would probably cause problems for existing mappings.  I
think we need to keep it like it was.

-- 
From "know your smileys":
 :-{}	Too much lipstick

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chdiza** [comment]
> For the Kitty keyboard protocol the modifiers "super" and "hyper" are also defined, even though I have never seen them used.  I think they should also be handled like "meta".  I don't really want to add modifiers that only work with one key protocol.

"Super" is the Command key when using linux with an Apple keyboard.

The whole point of the kitty protocol, for me, is to *finally* enable using the Command key as a modifier inside non-GUI vim.  Some key protocol has to be the first.

**Comment by brammool** [comment]
I figured out that the difference in 'compatible' mode is from the 'esckeys' option, which makes sense.

I'll make a patch to apply the shift key to ASCII letters, then most of this works as expected.  I still think Kitty should have applied the shift key, since it requires knowing the keyboard layout to do this properly and Vim doesn't have this information.
