### ISSUE TITLE
repeat <ScriptCmd> mapping doesn't use right script context

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#11930]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script

        var vimdir = '/tmp/.vim'
        &runtimepath = vimdir
        vimdir->delete('rf')
        vimdir->mkdir('p')

        var lines =<< trim END
            vim9script
            import autoload 'script.vim'
            onoremap <F3> <ScriptCmd>script.Func()<CR>
        END
        $'{vimdir}/plugin/'->mkdir('p')
        lines->writefile($'{vimdir}/plugin/script.vim')

        lines =<< trim END
            vim9script
            export def Func()
                normal! V
            enddef
        END
        $'{vimdir}/autoload/'->mkdir('p')
        lines->writefile($'{vimdir}/autoload/script.vim')

        ['foo', 'bar', 'baz']->setline(1)
        nnoremap j j
        $'source {vimdir}/plugin/script.vim'->execute()
        feedkeys("d\<F3>j.j.", 'xt')
    EOF
    )

An error is given:

    E121: Undefined variable: script

**Expected behavior**

No error is given.  The 3 lines, "foo", "bar" and "baz" are deleted.

**Version of Vim**

9.0 Included patches: 1-1270

**Environment**

Operating system: Ubuntu 20.04.5 LTS
Terminal: XTerm(378)
Value of $TERM: xterm-256color
Shell: GNU bash, version 5.0.17

**Additional context**

A similar issue was fixed in patch [9.0.0387](https://github.com/vim/vim/releases/tag/v9.0.0387).
But it seems the fix only works for a single dot command; not for several consecutive ones.

**Comment by brammool** [comment]
> **Steps to reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(tee <<'EOF'
>         vim9script
> 
>         var vimdir = '/tmp/.vim'
>         &runtimepath = vimdir
>         vimdir->delete('rf')
>         vimdir->mkdir('p')
> 
>         var lines =<< trim END
>             vim9script
>             import autoload 'script.vim'
>             onoremap <F3> <ScriptCmd>script.Func()<CR>
>         END
>         $'{vimdir}/plugin/'->mkdir('p')
>         lines->writefile($'{vimdir}/plugin/script.vim')
> 
>         lines =<< trim END
>             vim9script
>             export def Func()
>                 normal! V
>             enddef
>         END
>         $'{vimdir}/autoload/'->mkdir('p')
>         lines->writefile($'{vimdir}/autoload/script.vim')
> 
>         ['foo', 'bar', 'baz']->setline(1)
>         nnoremap j j
>         $'source {vimdir}/plugin/script.vim'->execute()
>         feedkeys("d\<F3>j.j.", 'xt')
>     EOF
>     )
> 
> An error is given:
> 
>     E121: Undefined variable: script
> 
> **Expected behavior**
> 
> No error is given.  The 3 lines, "foo", "bar" and "baz" are deleted.

I suppose this is a bug, but the way it is reproduced is very
complicated.  Can you simplify this?

The code has nested modes.  It starts with "d" which goes to
operator-pending mode.

Then the F3 mapping executes an Ex command, which calls Func().  This
then does "normal! V".  This is handled like a new command (the "d"
operator is in a different context), thus starts Visual mode, selecting
the current line.  Then it goes back to the context where F3 was found.

After F3 Visual mode is active, and since the "d" operator was pending,
it now deletes the selected area, which is the current line.

Note that the second "j" causes an error, since there is only one line
at that moment.

> A similar issue was fixed in patch
> [9.0.0387](https://github.com/vim/vim/releases/tag/v9.0.0387).
> But it seems the fix only works for a single dot command; not for
> several consecutive ones.

I can fix this problem, but for a regression test it would be good to
have a simpler way to reproduce the problem.

-- 
hundred-and-one symptoms of being an internet addict:
161. You get up before the sun rises to check your e-mail, and you
     find yourself in the very same chair long after the sun has set.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I suppose this is a bug, but the way it is reproduced is very
   > complicated.  Can you simplify this?

The patch [9.0.0387](https://github.com/vim/vim/releases/tag/v9.0.0387) already contains a test for this; it just needs to be slightly amended:
```diff
diff --git a/src/testdir/test_mapping.vim b/src/testdir/test_mapping.vim
index d631274d3..b1dd4446a 100644
--- a/src/testdir/test_mapping.vim
+++ b/src/testdir/test_mapping.vim
@@ -1555,15 +1555,15 @@ func Test_map_script_cmd_redo()
   let lines =<< trim END
       vim9script
       export def Func()
-        normal! dd
+        normal! V
       enddef
   END
   call writefile(lines, 'Xmapcmd/script.vim')
   new
-  call setline(1, ['one', 'two', 'three', 'four'])
+  call setline(1, ['one', 'two', 'three', 'four', 'five'])
   nnoremap j j
   source Xmapcmd/plugin.vim
-  call feedkeys("d\<F3>j.", 'xt')
+  call feedkeys("d\<F3>j.j.", 'xt')
   call assert_equal(['two', 'four'], getline(1, '$'))
 
   ounmap <F3>
```
