### ISSUE TITLE
Allow more alignment sections in statusline

### ISSUE THREAD

**Issue by craigmac** [vim/vim#11965]
The feature has existed in Neovim since mid-2016: https://github.com/neovim/neovim/pull/4489

I want to be able to use more than one `%=` in `&statusline`, rather than just one. My stl is quite minimal and I really enjoy just having the buffer name centered in the stl. I don't know if there's functionally any purpose, just an aesthetic preference.

**Describe the solution you'd like**
Allow any number of `%=` in `&statusline` rather than one. So that: `set stl=left%=centered%=right` centers the 'centered' string.

**Describe alternatives you've considered**
Trying to fiddle around with min widths and space characters for padding but I didn't get very far.

screenshot of using it in neovim:

<img width="1920" alt="Screen Shot 2023-02-09 at 10 03 11 AM" src="https://user-images.githubusercontent.com/7416158/217849678-9955cc95-f82f-446e-8e64-71c3bf746bf5.png">

**Comment by brammool** [comment]
> The feature has existed in Neovim since mid-2016: https://github.com/neovim/neovim/pull/4489
> 
> I want to be able to use more than one `%=` in `&statusline`, rather
> than just one. My stl is quite minimal and I really enjoy just having
> the buffer name centered in the stl. I don't know if there's
> functionally any purpose, just an aesthetic preference.
> 
> **Describe the solution you'd like**
> Allow any number of `%=` in `&statusline` rather than one. So that:
> `set stl=left%=centered%=right` centers the 'centered' string.

Currently one %= item is supported, which allows for what follows to be
right-aligned.  I think what you are asking for is for supporting two %=
items, which will be replaced by white space.  What follows the second
%= will be right-aligned as before.  The amount of white space is
computed so that the text between the two %= is centered.

This sounds useful.  Perhaps someone wants to make a PR for this?

Supporting more than two %= does not appear to be useful.  I would not
know how it can be useful.

-- 
hundred-and-one symptoms of being an internet addict:
109. You actually read -- and enjoy -- lists like this.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by craigmac** [comment]
I don't know how 3+ %= would be useful myself, I'd be happy with 2 :) I don't think I have enough knowledge to port what I need from the Neovim PR, so I'll leave this open so someone else could try.

**Comment by vim-ml** [comment]
Hi,

On Fri, Feb 10, 2023 at 8:16 AM C.D. MacEachern ***@***.***>
wrote:

> I don't know how 3+ %= would be useful myself, I'd be happy with 2 :) I
> don't think I have enough knowledge to port what I need from the Neovim PR,
> so I'll leave this open so someone else could try.
>
>
>
I have created PR #11970 (https://github.com/vim/vim/pull/11970) to port
this functionality.

- Yegappan
