### ISSUE TITLE
[vim9script] "E1177: For loop on class not supported" when accessing static member via alias

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12006]
### Steps to reproduce

Source this script:

```vim
vim9script

class Meta
  static x = 1
endclass

def Foo()
  const MetaAlias = Meta

  for _ in [1, 2]
    const y = MetaAlias.x
    echo y
  endfor
enddef

Foo()
```

Vim should raise `E1177: For loop on class not supported`. Replacing the first line in the body of the for loop with `const y = Meta.x` fixes the error.

### Expected behaviour

The code shoudl run just fine and echo `1` twice.

### Version of Vim

9.0.1311

### Environment

macOS 13.2
Apple Terminal
xterm-256color
ZSH 5.8.1

**Comment by brammool** [comment]
There doesn't appear to be anything wrong with the for loop, I don't see how you can expect E1177 for this.

The real problem is ```const MetaAlias = Meta```.  What is the type of MetaAlias here?  It's not an object and we don't have a type that is a class.  I am not sure this is ever expected to work.  You could perhaps use a typedef (once that gets implemented).

I wonder why you came up with this code.  Just using "Meta.x" works, as you mention.  What do you need MetaAlias for?

**Comment by lifepillar** [comment]
>What is the type of MetaAlias here? It's not an object and we don't have a type that is a class. I am not sure this is ever expected to work.

Ok, I see. Feel free to close this issue.

**Comment by brammool** [comment]
Once something like a typedef has been implemented please check this again.  Closing for now.
