### ISSUE TITLE
vim9: keys({one: 'xxx'}) error if keys.vim imported

### ISSUE THREAD

**Issue by errael** [vim/vim#12001]
### Steps to reproduce

(Not sure if this is an error, seems unambiguous)

The following script gets `E1236: Cannot use keys itself, it is imported`.
`keys.vim` is an empty file in same directory.
If the `import` line is commented out, it works ok.

```
vim9script

import './keys.vim'
echo keys({ one: 'xxx' })
```

### Expected behaviour

No error, the `keys()` function can be accessed.

### Version of Vim

9.0.1296

### Environment

ubuntu

**Comment by errael** [comment]
> If you decide to import using a name that obscures a builtin function

As you mention, new builtin functions can be added at any time; or used in a file where is wasn't used before. `keys.vim` has been around for almost a year; one of my first vim9script files.

I guess the only sane thing is to not directly use an import file name, time to adopt a new convention, something like `import './keys.vim' as i_keys`

I already do a lot of `const SomeFunc = some_import.SomeFunc` for what I think of as global functions.

**Comment by brammool** [comment]
> > If you decide to import using a name that obscures a builtin function
> 
> As you mention, new builtin functions can be added at any time; or
> used in a file where is wasn't used before. `keys.vim` has been around
> for almost a year; one of my first vim9script files.

Right, thus an import name shadowing a builtin function name is OK,
since you can't possibly use the builtin function.  Only when a new
builtin function is added with a name you were already using, you'll
have to rename the import to be able to use the function.  That is OK,
since it's your choice when you want to do this.

> I guess the only sane thing is to not directly use an import file
> name, time to adopt a new convention, something like `import
> './keys.vim' as i_keys`

Up to you.  I don't think Vim should enforce this.

> I already do a lot of `const SomeFunc = some_import.SomeFunc` for what
> I think of as global functions.

Yes, you can do that to make the name shorter.  Again, up to you to
decide how you want to do this.

-- 
Marriage isn't a word.  It's a sentence.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errael** [comment]
Not looking for language enforcement of my conventions. Thinking out loud about dealing with the issue; someone might have some ideas. Using `as i_`  prefix is working well for me; avoids the issue and can easily find where it's in use.

> > > If you decide to import using a name that obscures a builtin function 

> > As you mention, new builtin functions can be added at any time; or used in a file where is wasn't used before. `keys.vim` has been around for almost a year; one of my first vim9script files.

> Right, thus an import name shadowing a builtin function name is OK, since you can't possibly use the builtin function. Only when a new builtin function is added with a name you were already using, you'll have to rename the import to be able to use the function. That is OK, since it's your choice when you want to do this.

> > I guess the only sane thing is to not directly use an import file name, time to adopt a new convention, something like `import './keys.vim' as i_keys`

> Up to you. I don't think Vim should enforce this.
