### ISSUE TITLE
64-bit gvim torn-off submenus won't pop up

### ISSUE THREAD

**Issue by shaggyaxe** [vim/vim#1205]
Running on Windows7 64-bit
**_Menus do tear off fine.  No problem there._**
Issue is when, **_while on a torn-off menu_**, you click on a submenu (i.e., those having ">>" next to them)

Happens for all such submenus.  But you can replicate this way:

1) gvim -N -u NONE
2) Tear off the "Edit" menu
3) Click on "Gobal Settings"
4) Nothing happens

This issue does not occur with 32-bit gvim.

I replicated with both of these:

http://tuxproject.de/projects/vim/complete-x64.exe

https://github.com/vim/vim-win32-installer/releases/download/v8.0.0051/gvim_8.0.0051_x64.zip

![clipboard01](https://cloud.githubusercontent.com/assets/1157014/19819181/7c0818ee-9d21-11e6-91f1-a1426de59fd7.png)

**Comment by k-takata** [comment]
I found that the current implementation of tearoff menu is somewhat broken.
It does something weird when creating a tearoff menu.  It calls `CreatePopupMenu()` to create a menu, then casts the returned menu handle to a 16-bit value to create a menu ID.  And later, the 16-bit menu ID is cast again to get the menu handle.  Thus the value of the menu handle is truncated and the menu won't work.  I'm surprised that this code worked on 32-bit gvim.

The following patch fixes the problem:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c35b76363a93cdbdc81ee652a3644b8ea8404e07/win32-fix-tearoff-menu.patch?at=default&fileviewer=file-view-default

**Comment by tonymec** [comment]
Works for me in gvim 8.0.1185 with GTK2 GUI on openSUSE Linux x86_64.

Best regards,
Tony.

**Comment by k-takata** [comment]
I had to say that the Windows implementation was broken.

**Comment by brammool** [comment]
Ken Takata wrote:

> I found that the current implementation of tearoff menu is somewhat broken.
> It does something weird when creating a tearoff menu.  It calls
> `CreatePopupMenu()` to create a menu, then casts the returned menu
> handle to a 16-bit value to create a menu ID.  And later, the 16-bit
> menu ID is cast again to get the menu handle.  Thus the value of the
> menu handle is truncated and the menu won't work.  I'm surprised that
> this code worked on 32-bit gvim.
> 
> The following patch fixes the problem:
> https://bitbucket.org/k_takata/vim-ktakata-mq/src/c35b76363a93cdbdc81ee652a3644b8ea8404e07/win32-fix-tearoff-menu.patch?at=default&fileviewer=file-view-default

Thanks.  I wonder if we should get rid of tear-off menus completely.
They were added because it was a feature on Motif, and then we carried
it over to other systems.  I don't think any modern GUI has tear-off
menus these days.

Does anyone actually use them?

-- 
Back up my hard drive?  I can't find the reverse switch!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> Does anyone actually use them?

I don't know.
@shaggyaxe Do you use them?

**Comment by chrisbra** [comment]
I don't use it and have never understand what the use case was.

**Comment by brammool** [comment]
Christian wrote:

> I don't use it and have never understand what the use case was.

With a normal menu you first need to click on the menu button, then move
the mouse to the right item can click there.
When a menu was torn-off it is always visible.  You can spont the item
to click right away.  Thus it's faster.

This is only useful if you click on several items in the menu in a row.
Otherwise it just occupies screen space.  This is a rare use case.
And if there is no native support, they look quite ugly.

The alternative is to put the item in the toolbar.
So I think it's fine to drop the feature from systems that don't support
them natively.

-- 
Even got a Datapoint 3600(?) with a DD50 connector instead of the
usual DB25...  what a nightmare trying to figure out the pinout
for *that* with no spex...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by shaggyaxe** [comment]
@k-takata    Yes, I do use tear-off menus a lot.  Not the newbie ones I showed to replicate the issue.  But I have a lot of menus and submenus tied to custom functions and macros.  I find them extremely useful.

I get the latest http://tuxproject.de/projects/vim/complete-x64.exe weekly, and was pleasantly surprised to see this was fixed!  :)
