### ISSUE TITLE
Calling popup_atcurosr on insert event after showing the virtualtext on the same line causes virtual text to disappear

### ISSUE THREAD

**Issue by kohnish** [vim/vim#12080]
### Steps to reproduce

I don't have a script yet, because I'm not that great with vimscript, but  

1. Show virtualtext on a line
2. Move the cursor just after the virtualtext and go to insert mode
3. Autocommand to call popup_atcurosr on insert gets triggered
4. Type something and the virtualtext should disappear in half.  
5. If I call prop_add again with the same option, it comes back and shows the both old and new virtualtext in a slightly different position.

I can reproduce this in my patched version of vim-lsc with inlayhint and signature help support, but I'm struggling to come up with a simple test script.

### Expected behaviour

virtualtext doesn't get half deactivated.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 28 2023 00:38:20) macOS version - x86_64 Included patches: 1-472

### Environment

Linux and Mac

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> I don't have a script yet, because I'm not that great with vimscript, but  
> 
> 1. Show virtualtext on a line

Do you know what kind of virtual text?  What would be the prop_add()
call arguments?

> 2. Move the cursor just after the virtualtext and go to insert mode
> 3. Autocommand to call popup_atcurosr on insert gets triggered
> 4. Type something and the virtualtext should disappear in half.  

What does that look like?  Perhaps you can make a screenshot.

> 5. If I call prop_add again with the same option, it comes back and
> shows the both old and new virtualtext in a slightly different
> position.

So the "in half" effect is gone?  Perhaps using CTRL-L to force a redraw
instead of using prop_add() has an effect?

> I can reproduce this in my patched version of vim-lsc with inlayhint
> and signature help support, but I'm struggling to come up with a
> simple test script.

I'm afraid I cannot guess what the problem is.  And we need to be able
to reproduce it so we can add a regression test.


-- 
hundred-and-one symptoms of being an internet addict:
239. You think "surfing" is something you do on dry land.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by kohnish** [comment]
I cannot seem to reproduce after refactoring the scripts, so my reproduction scenario could be wrong.  
  
I think if you can't guess what it is, it might be bug on my side, so closing this one for now. @brammool 
Thank you very much for your attention.  

There are a few highlights mechanism depending on lsp diagnostic response as well.  
But here's what used to happen, in case anybody else manage to come up with reproduction scenario.  

![01_first](https://user-images.githubusercontent.com/58531742/223526320-87871b18-3b29-4c0d-9c86-ad1f005a0a8f.png)
![02_after_input_and_escape](https://user-images.githubusercontent.com/58531742/223526317-7a5f4cdd-2436-43fd-80af-8e7da8dcb0f3.png)
![03_enable_again](https://user-images.githubusercontent.com/58531742/223526307-ed519cca-2da1-4946-b38b-3116065567bd.png)
