### ISSUE TITLE
[feature] Support after/colors

### ISSUE THREAD

**Issue by teto** [vim/vim#1211]
In order to customize colorschemes without having to override upstream files, I would like to see support for "after/colors" just like after/ft and after/syntax.
Feature wise, I got it covered with this plugin http://www.vim.org/scripts/script.php?script_id=1641 
but it would seem more consistent to have this out of the box.

**Comment by ZyX-I** [comment]
There is no support for “after/ftplugin” or “after/syntax” or whatever. _All_ “after” directories are mere entries in &runtimepath which are handled just like any other entry in a &runtimepath. What makes them somewhat special is their position (they are normally placed after all other directories), the fact that `:runtime` (C function behind it) checks directories in &runtimepath in order and the fact that when sourcing plugin, ftplugin, syntax, etc files Vim intentionally sources _all_ files it can find. This is not the case for e.g. colors or autoload, so unless you suggest to actually make `after` directory special your request looks like “make `colorscheme` source all colorscheme files in &runtimepath” and I guess this is not an option: I believe currently people customize colorschemes by simply copying them and editing a file, and sourcing original version after customized one is definitely a breaking change.

**Comment by teto** [comment]
Thank you for the detailed answer, I did no know that was the mechanism. I am not sure people customize their colorschemes by forking them, and even if this is true, that might be because there is 

> sourcing plugin, ftplugin, syntax, etc files Vim intentionally sources all files it can find.

I have a question about that, my intuition was that these were loaded on demand like if I load a "tex" file, only then "ftplugin/tex.vim" was sourced, am I wrong ?
My initial idea was, vim behavior remains the same except that it loads after/colors/{name} if it exists.
If I follow you, my proposition would then become to simply the implementation (make it more like the others): 
when doing  ":colorscheme molokai", :colorscheme loads all files "colors/{name}" in rtp and "after" gets appended to rtp in that case.
If people setup their theme  as you suggest (which I am not that sure that's true or if that's a good solution, I know I would not like to fork all the colorschemes I use), it means they put their forked colorscheme in ".vim/colors/" while having the colorschemes installed elsewhere, hence the original colorscheme would override the forked one since it would be sourced after. correct ? I can understand that being a problem.

all colorscheme files
My idea is just like in the plugin, if you do ":colorscheme molokai", vim will load the molokai colorscheme as is explained in ":h colors"

**Comment by tweekmonster** [comment]
@teto What you can do is create something like `$XDG_CONFIG_HOME/nvim/colors/molokai_custom.vim`:

``` vim
runtime colors/molokai.vim

" Overrides or additions
```

Then use `:colorscheme molokai_custom`

> My idea is just like in the plugin, if you do ":colorscheme molokai", vim will load the molokai colorscheme as is explained in ":h colors"

`:colorscheme` doesn't go into detail about what exactly happens.  You'll want to read `:h 'background'` and `:h syn-reset`, too.

Executing all `colors/*.vim` scripts wouldn't work well since all color scripts I've seen uses `syntax reset`.  If `:colorscheme` did execute all color scripts found in `&rtp`, you would effectively be using the last color script found instead of the first.

**Comment by brammool** [comment]
Hmm, seems this message wasn't sent back to the issue.  Here it is then:

It works for other files, because they bail out when the work was
already done.  E.g. for ftplugin:

```
" Only do this when not done yet for this buffer
if exists("b:did_ftplugin")
  finish
endif
```

Colorschemes don't have this, and changing that will take time (many
color schemes haven't been update in ages, might not be able to contact
the maintainer).

The solution to give your modified colorscheme a different name, and
then use ":runtime" to load the original one is simple and works right
away.  Only difference is that it's perhaps not what you expected.

I'll add some lines in the help for this.
I think that's a good solution, so closing this issue.

**Comment by ZyX-I** [comment]
> I have a question about that, my intuition was that these were loaded on demand like if I load a "tex" file, only then "ftplugin/tex.vim" was sourced, am I wrong ?

Assuming &runtimepath contains `/a,/b,/c,/d` all of the following will be sourced:

```
/a/ftplugin/tex.vim
/b/ftplugin/tex.vim
/b/ftplugin/tex/my.vim
/c/ftplugin/tex/other.vim
/d/ftplugin/tex.vim
```

. But if `/a/colors/t.vim` exists `/b/colors/t.vim` will not be sourced. I _did not_ mean it loads all files for different filetypes, I meant it loads _all_ files for _one_ filetype it may find.

> when doing ":colorscheme molokai", :colorscheme loads all files "colors/{name}" in rtp and "after" gets appended to rtp in that case.

This makes `after` directory special, while currently it is not. `after` directories do not get appended to &runtimepath, they are there initially, and they are regular runtimepath directories.

> My idea is just like in the plugin, if you do ":colorscheme molokai", vim will load the molokai colorscheme as is explained in ":h colors"

Question is not whether it will load non-molokai colorschemes. Question is whether it will load _other_ versions of the same colorscheme found in &runtimepath. Without making `after` directory special in C code it is what is going to happen.

**Comment by tweekmonster** [comment]
Thinking out loud: `after/colors/*` could be an unofficial standard adopted by theme authors without needing special attention from Vim's core.  For example:

``` vim
set background=dark
highlight clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = 'theme_name'

highlight Normal ...
" etc...

" Theme boilerplate added by author
execute 'runtime! after/colors/'.g:colors_name.'.vim after/colors/'.g:colors_name.'/*.vim'
```

There would be the expectation that `after/colors/*` shouldn't do anything that would break the main theme, of course.  I think this is basically what you are after.

However, this would allow plugins to override themes in a possibly unknown order and I can't think of a case where that would be useful.  So, it would need to also be expected that `after/colors/*` is only for the user.  Overall, this requires more mental energy than necessary compared to creating a custom theme that sources the base theme.  Even more so if this was implemented in C.

**Comment by ZyX-I** [comment]
> Thinking out loud: after/colors/\* could be an unofficial standard adopted by theme authors without needing special attention from Vim's core. For example:

I do not think this is much useful idea:
1. Requires changes to all colorschemes. At least to all popular ones. If I was an author I would not like this because there is also
2. There are loads of workarounds:
   - User can create a `foo_mod` colorscheme which sources `foo` colorscheme first.
   - User can hook ColorScheme event in the vimrc before using `:colorscheme` command and source his changes there.
   - User can fork the colorscheme.
   - User can simply write `colorscheme foo` and then `source ~/.vim/after/colors/foo.vim`, or place such changes in a `plugin/foo.vim` which will be sourced after vimrc and thus after sourcing …/colors/foo.vim. This, of course, has some downsides (e.g. subsequent `colorscheme` calls will not have changes and this may produce unexpected results if user changes colorscheme and forgets about file with modifications), but most of time it is acceptable. At least I in many cases prefer to restart Vim over reloading any files (even though framework I have created allows such things and I use this feature from time to time) and I know I am not alone (I also heard some rumors about multiple `:colorscheme` calls causing bugs).
3. There is also “chicken and egg” problem: before this convention is established users will use other workarounds, but authors are not interested in implementing this convention without requests from user. You need a group of people who will actively push this convention through authors if you want to resolve this problem.
   
   And first step would be pushing this to the Vim upstream.

> However, this would allow plugins to override themes in a possibly unknown order and I can't think of a case where that would be useful. So, it would need to also be expected that after/colors/\* is only for the user.

There is no way you can prevent plugins from overriding anything in a possibly unknown order. There is ColorScheme event which can be used in a regular `plugin/*.vim` file after all!

**Comment by tweekmonster** [comment]
@ZyX-I Sorry I didn't make it clearer in my previous message, but I 100% agree with you.  :-)

I was exercising the thought to draw the conclusion that this feature would require far more effort than it's worth for developers/designers and users.  Creating a custom theme that sources the original first is, by far, the easiest option.  It also benefits from having zero surprises or gotchas.

Without a completely new format for color schemes, there's no hope for designers to adopt/support something like this.

**Comment by teto** [comment]
Well thanks for all the great explanation. I will stick with the plugin then. Cheers

**Comment by terminatorul** [comment]
This is a shame...

Sourcing all colorscheme files in runtimepath would make Vim behave consistently with other runtime commands, and behave like all users and script authors expect, without the need for workarounds.

Having multiple copies of colors/molokai.vim in &runtimepath would be inappropriate to begin with, and should not be a deciding factor.
