### ISSUE TITLE
Errors from syntax.vim and synload.vim.

### ISSUE THREAD

**Issue by ghost** [vim/vim#12126]
### Steps to reproduce

1. Type :syntax off
2. Type :syntax on
3. Error:
```
Error detected while processing /opt/homebrew/Cellar/vim/9.0.1350/share/vim/vim90/syntax/syntax.vim[19]../opt/homebrew/
Cellar/vim/9.0.1350/share/vim/vim90/syntax/synload.vim:
line   31:
E1155: Cannot define autocommands for ALL events
line   66:
E216: No such event: c,cpp,cs,idl,java,php,datascript if (exists('b:load_doxygen_syntax') && b:load_doxygen_syntax)^I||
 (exists('g:load_doxygen_syntax') && g:load_doxygen_syntax)   | runtime! syntax/doxygen.vim | endif
```

### Expected behaviour

No error.

### Version of Vim

stable 9.0.1350 (homebrew)

### Environment

Operating System: MacOS Ventura 13.2.1
Terminal: iTerm2
Value of $TERM: xterm-256color
Shell: /opt/homebrew/bin/zsh

**Comment by brammool** [comment]
I cannot reproduce this.  Make sure you run Vim with the "--clean" argument to avoid your setup interferes.

**Comment by tonymec** [comment]
`Syntax` after `au` on these lines is supposed to be the event name mentioned as missing in these autocommands. The group name is optional, but if you previously used `:augroup` to define an autocommand group with the name `Syntax` (a bad idea IMHO since there exists an official event by this name) I imagine that it could lead to the errors you see.

Best regards,
Tony.

**Comment by tonymec** [comment]
@chrisbra : we already have this script, it is `$VIMRUNTIME/syntax/synload.vim`

Best regards,
Tony.

**Comment by chrisbra** [comment]
> @chrisbra : we already have this script, it is $VIMRUNTIME/syntax/synload.vim

I know. I wanted to see, if there are any differences
