### ISSUE TITLE
[filetype] Racket files are detected as Scheme, even though vim supports ft=racket out of the box

### ISSUE THREAD

**Issue by kakig** [vim/vim#12162]
### Steps to reproduce

1. vim -u DEFAULTS
2. :e test.rkt
3. set ft?

### Expected behaviour

filetype=racket

### Version of Vim

9.0.1337

### Environment

OS: Arch Linux
Terminal: kitty
TERM: xterm-kitty
Shell: zsh 5.9

**Comment by benknoble** [comment]
Short version: The plugin I maintain from which the ftplugin and syntax scripts (also compiler and indent I believe) has a custom ftdetect that has not yet been considered for inclusion.

Rationale: it would dramatically change the way Racket filetypes are detected. Since each Racket program starts `#lang` and the name of a language, it uses the language in the file as the filetype (with some mappings for common extensions that are really the same as their base language). Arguably it would be correct, since the Racket platform consists of a family of languages and tools to build your own, but I expect it would cause lots of consternation for folks who are happy with the Scheme or Racket filetype and have workflows built around it.

I'm not opposed to changing the rkt-style suffixes to `filetype=racket`.

**Comment by benknoble** [comment]
Basically it would amount to
```diff
- au BufNewFile,BufRead *.scm,*.ss,*.sld,*.rkt,*.rktd,*.rktl	setf scheme
+ au BufNewFile,BufRead *.scm,*.ss,*.sld	setf scheme
+ au BufNewFile,BufRead *.rkt,*.rktd,*.rktl     setf racket
```

**Comment by kakig** [comment]
Works perfectly. Should I open a pull request?

**Comment by benknoble** [comment]
(P.S. For those of you that _like_ the `#lang`-to-`filetype` idea like me, check out https://github.com/benknoble/vim-racket. It also includes the most up-to-date versions of the Racket support that ships with Vim since those were added based on that repository.)
