### ISSUE TITLE
netrw :Explore corrupts the 'plus' register

### ISSUE THREAD

**Issue by jpmv27** [vim/vim#1224]
In runtime/autoload/netrw.vim, netrw#Explore() saves the star and plus registers with
```
   sil! let keepregstar = @*
   sil! let keepregplus = @+
```
but there are several places where the plus register is restored with
```
sil! let @+ = keepregstar
```
instead of
```
sil! let @+ = keepregplus
```

I can provide a PR if desired

**Comment by cecamp** [comment]
Martin Vuille wrote:

> In runtime/autoload/netrw.vim, netrw#Explore() saved the star and plus
> registers with
> 
> |sil! let keepregstar = @\* sil! let keepregplus = @+ |
> 
> buth there are several places where the plus register is restored with
> 
> |sil! let @+ = keepregstar |
> 
> instead of
> 
> |sil! let @+ = keepregplus |
> 
> I can provide a PR if desired
> 
> Thank you -- I've now fixed this in v162b
> (http://www.drchip.org/astronaut/vim/index.html#NETRW).

Regards,
Chip Campbell

**Comment by jpmv27** [comment]
Is there a way to find out the netrw version at runtime?

**Comment by vim-ml** [comment]
On 2016-11-04, Martin Vuille wrote:

> Is there a way to find out the netrw version at runtime?

```
:echo g:loaded_netrwPlugin
```

Regards,
Gary

**Comment by cecamp** [comment]
Another way: if you haven't disabled the netrw banner, just look at the second line: it'll say something like (netrw v162b) -- v162b is netrw's version number.

**Comment by ZyX-I** [comment]
I am wondering why it needs to save/restore these registers in first place? Code that tries to save/restore X11 registers is broken by design because X11 register is a mere record “application X keeps the value of the register”, “restoring” this makes Vim own register instead (you can’t tell X server anything, but “I own the register”), and code `let keepregstar = @+` is not even able to copy Vim’s register contents correctly (NUL bytes and blockwise registers), not to mention the fact that other apps may provide things like images there.

**Comment by jpmv27** [comment]
@Gary thanks for the tip!
@cecamp thanks, but I am looking for something I can check from my .vimrc

@ZyX-I No idea, but if they are not saved and restored then they get clobbered, see #1227

**Comment by ZyX-I** [comment]
@jpmv27 This only means that there is a bug elsewhere and you just suggest writing code which hides it. Plugin should not touch any registers in general (unless the purpose of the plugin is touching registers: e.g. YankRing) because restoring register contents is generally impossible (for system registers), and usually it is easier to write code which does not touch registers then to write code which correctly restores all modified registers: do not forget that even if you are temporary yanking to register `a` you will have to at least also restore registers `0` and `"`, deleting is worse (`1`..`9` and `"`) and there are still issues with system registers with specific &clipboard setting.

I could suggest some more bullet-proof alternative to writing code which does not touch registers:
1. Function `SaveRegisters` should save `a`..`z` and `0`..`9` registers, as well as `&clipboard` value. `&clipboard` setting be modified to be empty before saving anything. All saved registers are saved using `[name, getreg(name, 1, 1), getregtype(name)]`.
2. Function `RestoreRegisters` should restore all registers (just call `call('setreg', one_of_the_saved_lists)` multiple times), then `&clipboard`. And this should be done in `finally` block.

I.e. do not bother determining which registers you really did touch, and do not allow unintentional interaction with system registers due to `&clipboard` setting. Using `getreg(, 1, 1)` and `getregtype()` allows restoring both registers with NUL bytes inside and blockwise registers.

**Comment by jpmv27** [comment]
@ZyX-I I agree and I hope that the netrw maintainer takes your suggestions to heart.
For my part, I just want to be able to yank some code, go to another file with :Explore or :Rexplore, and paste the code.
Maybe at some point I can find some time to track down the root cause in netrw.
