### ISSUE TITLE
language-mapping for :substitute

### ISSUE THREAD

**Issue by ces42** [vim/vim#12291]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
currently language-mapping only works in command-line mode when doing a search with '/' or '?', but not when entering a search patttern for :s.

**Describe the solution you'd like**
It would be nice if language-mapping could be active when entering a search for :s, :g and :v. (

**Additional context**
The conditions that should trigger `language-mapping` in command mode seem to be the same conditions that would trigger incsearch, so hopefully the code for that could be reused?

**Describe alternatives you've considered**
It seems like I could try to write a bunch of `<expr>` cnoremaps which detect whether I'm doing a `:substitute` and do the `language-mapping` in that case. Is there some vimscript function that will let me detect whether an incsearch is being performed?

**Comment by tonymec** [comment]
P.S. By setting the `lCursor` highlight to something else than the `Cursor` highlight, the colour of the cursor will tell you immediately whether or not language mappings are active at the current instant (and it will change colour instantly when you hit `Ctrl-^`).

Best regards,
Tony.

**Comment by brammool** [comment]
> currently language-mapping only works in command-line mode when doing
> a search with '/' or '?', but not when entering a search patttern for
> :s.
>
> It would be nice if language-mapping could be active when entering a
> search for :s, :g and :v. (
> 
> The conditions that should trigger `language-mapping` in command mode
> seem to be the same conditions that would trigger incsearch, so
> hopefully the code for that could be reused?

This is tricky, because a search pattern contains more than text, it
also has special regexp characters.  Automatically switching on language
mappings can be annoying.  We would probably need a way to disable it,
making it more complex.

You can use CTRL-^ to quickly switch between the modes.  Isn't that
sufficient?  You know when you are going to type text where you want to
use a language mapping.  It's a more manual, but predictable.

-- 
The most powerful force in the universe is gossip.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ces42** [comment]
I didn't know about about `ctrl-^`, so that mostly solves the problem. 

>This is tricky, because a search pattern contains more than text, it
also has special regexp characters.  Automatically switching on language
mappings can be annoying.  We would probably need a way to disable it,
making it more complex.

Given that "search mode" already uses `language-mapping` (even though searches contains regex characters) it still seems like this would be nice-to-have. It is probably not worth the extra effort though.

**Comment by chrisbra** [comment]
closing then.
