### ISSUE TITLE
Two error messages when using an invalid type as a bool argument to byteidx(), byteidxcomp(), strchars(), strcharpart()

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12352]
### Steps to reproduce

1. Running `:echo byteidx('', 0, {})` gives two error messages:
```
E728: Using a Dictionary as a Number
E1023: Using a Number as a Bool: -1
```
2. Running `:echo byteidxcomp('', 0, {})` gives two error messages:
```
E728: Using a Dictionary as a Number
E1023: Using a Number as a Bool: -1
```
3. Running `:echo strchars('', {})` gives two error messages:
```
E728: Using a Dictionary as a Number
E1023: Using a Number as a Bool: -1
```
4. Running `:echo strcharpart('', 0, 0, {})` gives two error messages:
```
E728: Using a Dictionary as a Number
E1023: Using a Number as a Bool: 4294967295
```

### Expected behaviour

Each of these only gives one error message

### Version of Vim

9.0.1510

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Hmm, now these functions return silently when using `-1` as these bools.

**Comment by zeertzjq** [comment]
I've created another PR #12358 to fix this.

**Comment by brammool** [comment]
> Hmm, now these functions return silently when using `-1` as these bools.

I mistakenly thought that -1 would only be returned after giving an
error.  Turns out this only happens for Vim9 script.

Patch 9.0.1524 takes care of a couple of these, but there are other
tv_get_bool() calls that don't check for a failure.  E.g. in
f_utf16idx().  These continue even though an error was given.
Would be good if someone can go over all these tv_get_bool() calls,
figure out what happens with invalid input, write tests and fixes them.
I don't think we need to preserve backwards compatibility of continuing
after giving an error message, that can be considered a bug.

-- 
Shift happens.
                -- Doppler

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
