### ISSUE TITLE
<abuf> in OptionSet autocmd

### ISSUE THREAD

**Issue by monkoose** [vim/vim#12418]
### Steps to reproduce

`au OptionSet * echom expand('<abuf>')`

Always returns empty string. Is there a reason for this or it is a bug?

### Expected behaviour

Return string representation of the buffer number.

### Version of Vim

9.0.1506

### Environment

OS: Linux
$TERM: st-256color

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> `au OptionSet * echom expand('<abuf>')`
> 
> Always returns empty string. Is there a reason for this or it is a bug?
> 
> ### Expected behaviour
> 
> Return string representation of the buffer number for from which
> option was set.

The "abuf" value isn't set when setting an option.  This was not
implemented, because it can be confusing.  When setting a global option
the buffer does not matter, and when setting a buffer-local option
nearly always the current buffer is used.  Not sure what would be used
when setting a window-local option.

You can see an error message when using:

	au OptionSet * verbose echom expand('<abuf>')

What do you need "<abuf>" for?  Is it worth implementing this?  Perhaps
it should only be available for setting a buffer-local option?  Although
it would require a pattern that matches this kind of option to avoid
errors.

-- 
hundred-and-one symptoms of being an internet addict:
46. Your wife makes a new rule: "The computer cannot come to bed."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by monkoose** [comment]
local options from another window/buffer can be set `setbufvar()` (with win_execute() too, but it doesn't trigger events). 

But if i'm not mistaken during `setbufvar()` current buffer temporary set to the number of the first argument, so it is still available through `bufnr()` and friends.

I just get surprised when working on a plugin, that when I tried to implement some logic aroung some events `<abus>` value. If it is somewhat hard to implement maybe documentation can be improved mentioning that `<abuf>` isn't available for `OptionsSet` event?

**Comment by brammool** [comment]
I'll add a few remarks in the help.  I don't see enough reason right now to change the implementation.  At least for a pattern that matches all options it will be unclear what to do.  When matching specific options using something like bufnr() will work and a variable like v:option_command will help deciding what to do.
