### ISSUE TITLE
Cursor ends up in not (fully) visible lastline

### ISSUE THREAD

**Issue by luukvbaal** [vim/vim#12411]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
winsize 40 8
call setline(1, ['Line' .. (' with some text'->repeat(7))]->repeat(7))
set smoothscroll scrolloff=0
norm G
```
3. Press `4<C-Y>G`
4. Note that the cursor is in the last line but it is not displayed as 'display' does not contain "lastline".
5. Type `:set display=lastline`(not necessary) and press `G4<C-Y>G` again.
6. Note that the cursor is in the last line again, which is displayed, but moving the cursor to the wrapped part of the line (press `$` or `l` repeatedly) will still not adjust the topline/skipcol and bring the cursor into the command line.

### Expected behaviour

Topline (and skipcol) should be adjusted in this case.
(Is it an intended goal of 'smoothscroll' to allow the cursor to be in a not fully displayed lastline (with "lastline" in 'display')?)

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 18 2023 12:30:36) Included patches: 1-1563

### Environment

Operating system: Arch Linux
Terminal: st
Value of $TERM: st-256color
Shell: zsh

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Run `vim --clean`
> 2. Source the following file:
> ```vim
> winsize 40 8
> call setline(1, ['Line' .. (' with some text'->repeat(7))]->repeat(7))
> set smoothscroll scrolloff=0
> norm G
> ```
> 3. Press `4<C-E>G`
> 4. Note that the cursor is in the last line but it is not displayed as 'display' does not contain "lastline".

It would be logical to add "lastline" to 'display' when 'smoothscroll' is
set.  I'll add a note in the help.

> 5. Type `:set display=lastline` and press `4<C-E>G` again.
> 6. Note that the cursor is in the last line again, which is displayed, but moving the cursor to the wrapped part of the line (press `$` or `l` repeatedly) will still not adjust the topline/skipcol and bring the cursor into the command line.
> 
> ### Expected behaviour
> 
> Topline (and skipcol) should be adjusted in this case.
> (Is it an intended goal of 'smoothscroll' to allow the cursor to be in a not fully displayed lastline (with "lastline" in 'display')?)

'smoothscroll' and 'display' are independent.  It makes a lot of sense
to have "lastline" in 'display' when 'smoothscroll' is set, but it
should also work fine without that.

Without "lastline" I suppose it is simpler, since the display should
scroll to show the whole last line.  With "lastline" we have the option
to only scroll to show the cursor position, the text after it may not be
completely visible then.  This is more complicated though, we can
perhaps simplify this be behaving like "lastline" isn't in 'display'.

Another case is when the first and last line are the same, then we can
have text missing at the start and the end.  This we must be able to
handle, one long line that doesn't fit.

-- 
It was recently discovered that research causes cancer in rats.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by luukvbaal** [comment]
> 'smoothscroll' and 'display' are independent.  It makes a lot of sense
to have "lastline" in 'display' when 'smoothscroll' is set, but it
should also work fine without that.

Agreed.

> Without "lastline" I suppose it is simpler, since the display should
scroll to show the whole last line.  With "lastline" we have the option
to only scroll to show the cursor position, the text after it may not be
completely visible then.  This is more complicated though, we can
perhaps simplify this be behaving like "lastline" isn't in 'display'.

Yes I attempted to implement it previously for when "lastline" is in 'display' but it is indeed complicated, and I wasn't sure if allowing this was an intended goal but just not implemented yet or intentionally left unimplemented. Currently the display is indeed scrolled to show the whole lastline when the cursor is moved to it (also when "lastline" is in 'display'), the bug in this issue is an exception to that. The rest of the move code does not account for this and moving the cursor does not fix the corrupted display until the cursor is brought above the topline.

**Comment by luukvbaal** [comment]
> 3. Press `4<C-E>G`

I just noticed the reproduction steps erroneously included `<C-E>`, it should be `4<C-Y>G`.

**Comment by luukvbaal** [comment]
The bug in this issue is fixed with https://github.com/vim/vim/commit/d49f646bf56b29d44bbb16e79bc877b59aab38ac. 

The case of allowing the cursor to be on a partly visible lastline could be added to the todo list. I think this would be desirable when scrolling down with `gj` and 'smoothscroll'. Currently scrolling down is not "smooth". Scrolling up works better but only if the topline is smoothscrolled to begin with. When skipcol is zero scrolling up with gk brings the whole (wrapped) line above into view at once, as opposed to just the last screenline.
