### ISSUE TITLE
WinResized autocmd not triggered for terminals created with prefix commands changing its preset

### ISSUE THREAD

**Issue by senioria** [vim/vim#12425]
## Steps to reproduce

Source the following vimscript file:

``` vim
botright term
au WinResized <buffer> echom 'WinResized'
```

Drag to resize the terminal window, and no messages is shown.

However, `term`, `topleft term`, etc., works fine.

## Expected behavior

`'WinResized'` is printed for all variants of `term` command.

## Version of Vim

9.0.1570

**Comment by brammool** [comment]
> ## Steps to reproduce
> 
> Source the following vimscript file:
> 
> ``` vim
> botright term
> au WinResized <buffer> echom 'WinResized'
> ```
> 
> Drag to resize the terminal window, and no messages is shown.
> 
> However, `term`, `topleft term`, etc., works fine.
> 
> ## Expected behavior
> 
> `'WinResized'` is printed for all variants of `term` command.

The problem here is using "<buffer>" for the autocommand.  The
WinResized event is triggered only once when several windows change
size, which normally happens.  The window and buffer for which it is
triggered is the first one that is changed.  Your new terminal window is
likely the last one.

You can remove the "<buffer>" argument and use the WinResized-event to
decide what you want to do.

-- 
hundred-and-one symptoms of being an internet addict:
56. You leave the modem speaker on after connecting because you think it
    sounds like the ocean wind...the perfect soundtrack for "surfing the net".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
let me close this. Current behaviour is explained and there is a solution for this behaviour.
