### ISSUE TITLE
[Windows][GVim] Case change in file name not reflected in the buffer name

### ISSUE THREAD

**Issue by char101** [vim/vim#12424]
### Steps to reproduce

1. Edit `TEST.txt`
2. Delete the buffer
3. Rename `TEST.txt` to `test.txt`
4. Edit `test.txt` with the same GVim instance
5. The title still shows `TEST.txt`

### Expected behaviour

Buffer name reflects the correct file name case.

### Version of Vim

9.0.1572

### Environment

Windows 10

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> 1. Edit `TEST.txt`
> 2. Delete the buffer
> 3. Rename `TEST.txt` to `test.txt`
> 4. Edit `test.txt` with the same GVim instance
> 5. The title still shows `TEST.txt`
> 
> ### Expected behaviour
> 
> Buffer name reflects the correct file name case.

Please give exact reproduction steps.  E.g. at the second step: what
command did you do?  Note that ":bdelete" and "bwipe" have different
effects.  At the third step, how did you rename the file?

-- 
ERROR 047: Keyboard not found.  Press RETURN to continue.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by char101** [comment]
> Please give exact reproduction steps. E.g. at the second step: what command did you do? Note that ":bdelete" and "bwipe" have different effects.

I use `:bd`

> At the third step, how did you rename the file?

I tried using `call rename('TEST.txt', 'test.txt')` and also renaming from Explorer.

Also something strange I experienced was that, I was using fresh install of `gvim_9.0.1572_x64.exe` to test it, when I first edit a `test.txt` file (`:ed test.txt`), the file was automatically created on disk. Usually the file was only create when it is written. It does not happen on subsequent `:ed`.

**Comment by brammool** [comment]
> > Please give exact reproduction steps. E.g. at the second step: what
> > command did you do? Note that ":bdelete" and "bwipe" have different
> > effects.
> 
> I use `:bd`

If you then use "ls!" next you will see the buffer is still there, only
unlisted.  When editing the file again Vim will recognize it's the same
and re-use the buffer entry.  This is totally normal.  Main purpose is
to avoid that the same file gets multiple entries in the buffer list,
which can cause many unexpected problems.

> > At the third step, how did you rename the file?
> 
> I tried using `call rename('TEST.txt', 'test.txt')` and also renaming
> from Explorer.

I'm not sure how MS-Windows handles this at a low level, if it keeps the
same file and only changes it's name in the directory, or that it
creates a new directory entry.  On Unix it would still be the same
inode, thus Vim will know it's still the same file.  It probably doesn't
matter anyway, since case is ignored when opening a file.  And Vim will
use the existing buffer with the name that was used the first time.

> Also something strange I experienced was that, I was using fresh
> install of `gvim_9.0.1572_x64.exe` to test it, when I first edit a
> `test.txt` file (`:ed test.txt`), the file was automatically created
> on disk. Usually the file was only create when it is written. It does
> not happen on subsequent `:ed`.

You must have something in your setup that does this, Vim only creates
the file when it's written, not when editing it.  Try starting Vim with
"--clean" to avoid files in your setup.

-- 
Keyboard not found.  Think ENTER to continue.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > If you then use "ls!" next you will see the buffer is still there,
> > only unlisted.
> 
> I think the problem is that in Windows, the comparison to the unlisted
> buffer is done based on the file path in a case-insensitive way. When
> a file with the same name is opened again, it is matched against the
> existing unlisted buffer. The problem is that, the unlisted buffer
> file name is not updated to match the new file name.

To avoid problems Vim uses the name the buffer was first created with.
Changing it later has unpredictable side effects. If you don't want this
you will have to wipe out the buffer.

-- 
"I don’t know how to make a screenshot" - Richard Stallman, July 2002
(when asked to send a screenshot of his desktop for unix.se)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by char101** [comment]
Thanks for the explanation. I guess the solution for me is to use `expand('%:p')` for the `guitablabel` and `titlestring` options.
