### ISSUE TITLE
Inconsistent popup height after setbufline()

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#12421]
### Steps to reproduce

Source this script:

```vim
vim9script

const winid = popup_create('', {
  close:       'button',
  maxwidth:    10,
  minwidth:    10,
})

const lines = ['this', 'is', 'a', 'popup']

echo 'Initial height = ' winheight(winid)

const result = setbufline(winbufnr(winid), 1, lines)

echo 'After setbufline = ' winheight(winid) ' Result =' result
```

The output is:

```
Initial height =  1
After setbufline =  1  Result = 0                                                                                                                                      
```

Note that `winheight()` still reports the height to be one after `setbufline()` has added four lines of text.

### Expected behaviour

According to `:help setline()`:

>In Vim9 script an error is given if {lnum} is invalid.

Not sure how to interpret “invalid” when the text consists of multiple lines. I would expect the behavior to be one of the following:

- an error is raised if a line to be set is beyond the current popup's height; or,
- as the height of the popup is extended, then `winheight()` should report the updated height.

### Version of Vim

9.0.1572

### Environment

macOS 13.3.1
Apple Terminal
xterm256-color
ZSH 5.9

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Source this script:
> 
> ```vim
> vim9script
> 
> const winid = popup_create('', {
>   close:       'button',
>   maxwidth:    10,
>   minwidth:    10,
> })
> 
> const lines = ['this', 'is', 'a', 'popup']
> 
> echo 'Initial height = ' winheight(winid)
> 
> const result = setbufline(winbufnr(winid), 1, lines)
> 
> echo 'After setbufline = ' winheight(winid) ' Result =' result
> ```
> 
> The output is:
> 
> ```
> Initial height =  1
> After setbufline =  1  Result = 0
> ```
> 
> Note that `winheight()` still reports the height to be one after
> `setbufline()` has added four lines of text.

I don't see a problem here.  The number of lines in the buffer and the
number of lines in the window can be different.

> ### Expected behaviour
> 
> According to `:help setline()`:
> 
> >In Vim9 script an error is given if {lnum} is invalid.
> 
> Not sure how to interpret “invalid” when the text consists of multiple
> lines. I would expect the behavior to be one of the following:
> 
> - an error is raised if a line to be set is beyond the current popup's
> height; or,

No, the number of lines in the buffer matters, not the number of lines
(height) of the window.

> - as the height of the popup is extended, then `winheight()` should
> report the updated height.

The height of the popup is not changed in the example.  However, if you
add "redraw" then the popup window height is adjusted.  The "maxheight"
and "minheight" properties can be used to control this.  It also depends
on the position and space available.  Since these computations take a
bit of time, they are only done when it's time to update the display,
not halfway a script.


-- 
hundred-and-one symptoms of being an internet addict:
51. You put a pillow case over your laptop so your lover doesn't see it while
    you are pretending to catch your breath.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
