### ISSUE TITLE
"set cm=xchacha20v2" followed by use of "set key=..."  causes segmentation fault

### ISSUE THREAD

**Issue by stmuk** [vim/vim#12433]
### Steps to reproduce

Create an encrypted file "foo" with passphrase "foo" with "set cm=xchacha20v2" set and exit

Open fresh vim and "set key=foo" and open file "foo". 

"E304: ml_upd_block0(): Did not get block 0?" is briefly flashed in red at the bottom of the screen

The encrypted fie is correctly displayed in plain text briefly before vim crashes with 

Vim: Caught deadly signal SEGV

Vim: Finished.

### Expected behaviour

I'd expect it to  behave like "set cm=blowfish2".

Note in this case the same error "E304: ml_upd_block0(): Did not get block 0?" is displayed but there is no seg fault and it's possible to edit the file and save encrypted,

### Version of Vim

9.0.1575

### Environment

Debian 11,  kitty 0.19.3,  TERM=xterm-256color, zsh

**Comment by chrisbra** [comment]
does that only happen if you use `:set key=...` I actually wonder how this is supposed to be working, because this is setting an option local to a buffer (which you haven't opened yet).

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> Create an encrypted file "foo" with passphrase "foo" with "set
> cm=xchacha20v2" set and exit
> 
> Open fresh vim and "set key=foo" and open file "foo". 
> 
> "E304: ml_upd_block0(): Did not get block 0?" is briefly flashed in
> red at the bottom of the screen
> 
> The encrypted fie is correctly displayed in plain text briefly before
> vim crashes with 
> 
> Vim: Caught deadly signal SEGV
> 
> Vim: Finished.

I cannot reproduce this exactly.  I can get it to crash in
crypt_sodium_init_(), where arg->cat_add is NULL but it is copied to
with memcpy().  I don't see "E304".

Please give exact reproduction steps, starting with how you create the
encrypted "foo" file.  Also, where you say 'open file "foo"' I get an
error, because the buffer was modified.  I had to use ":e! foo".

Note that setting the 'key' option manually is not how it should be
used.  Vim will prompt for the key when opening the file.  But Vim
should not crash when you set the 'key' option anyway.

-- 
I got a new desk stapler. It broke on the first desk I tried.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> does that only happen if you use `:set key=...` I actually wonder how
> this is supposed to be working, because this is setting an option
> local to a buffer (which you haven't opened yet).

The command sets the global value of the 'key' option, which is used to
set the buffer-local value of the new buffer.  It is not supposed to be
used this way, only the buffer-local value should be set.  And only when
Vim prompts for it, not by typing the ":set" command, since that has a
high risk of leaking the key.

-- 
hundred-and-one symptoms of being an internet addict:
69. Yahoo welcomes you with your own start page

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by stmuk** [comment]
> ### Steps to reproduce Create an encrypted file "foo" with passphrase "foo" with "set cm=xchacha20v2" set and exit Open fresh vim and "set key=foo" and open file "foo". "E304: ml_upd_block0(): Did not get block 0?" is briefly flashed in red at the bottom of the screen The encrypted fie is correctly displayed in plain text briefly before vim crashes with Vim: Caught deadly signal SEGV Vim: Finished.
> I cannot reproduce this exactly. I can get it to crash in crypt_sodium_init_(), where arg->cat_add is NULL but it is copied to with memcpy(). I don't see "E304". Please give exact reproduction steps, starting with how you create the encrypted "foo" file. Also, where you say 'open file "foo"' I get an error, because the buffer was modified. I had to use ":e! foo". Note that setting the 'key' option manually is not how it should be used. Vim will prompt for the key when opening the file. But Vim should not crash when you set the 'key' option anyway.
> […](#)
> -- I got a new desk stapler. It broke on the first desk I tried. /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

**Comment by stmuk** [comment]
I probably should have explicitly said I have "set cm=xchacha20v2" set in my .vimrc

I can reproduce the E304 warning as follows

1. no "foo" file exists
2. vim -u /dev/null --cmd "set cm=xchacha20v2" -x foo
3. enter "foo" as password twice
4. enter "foo" in file
5. hit "ZZ"
6. E304 displayed. No SEGV.

I can reproduce the behaviour fixed by  ":e! foo" but don't see it in my normal workflow since I use nerdtree plugin as my first buffer.  I've now moved my plugins directory aside, and this doesn't change the behaviour I see.

The seg fault crash then can be reproduced by
1. existing "foo" file from above
2.  vim -u /dev/null --cmd "set cm=xchacha20v2 key=foo" foo
3.  Sometimes vim crashes straight away and sometimes I have to wait a few secs but then

Vim: Caught deadly signal SEGV
Vim: Finished.

**Comment by brammool** [comment]
> I probably should have explicitly said I have "set cm=xchacha20v2" set in my .vimrc
> 
> I can reproduce the E304 warning as follows
> 
> 1. no "foo" file exists
> 2. vim -u /dev/null --cmd "set cm=xchacha20v2" -x foo
> 3. enter "foo" as password twice
> 4. enter "foo" in file
> 5. hit "ZZ"
> 6. E304 displayed. No SEGV.

Thanks, now I can reproduce the problem.

> I can reproduce the behaviour fixed by  ":e! foo" but don't see it in
> my normal workflow since I use nerdtree plugin as my first buffer.
> I've now moved my plugins directory aside, and this doesn't change the
> behaviour I see.
> 
> The seg fault crash then can be reproduced by
> 1. existing "foo" file from above
> 2.  vim -u /dev/null --cmd "set cm=xchacha20v2 key=foo" foo
> 3.  Sometimes vim crashes straight away and sometimes I have to wait a few secs but then
> 
> Vim: Caught deadly signal SEGV
> Vim: Finished.

I can reproduce this too.  It depends on 'updatetime' and timing.
But I did manage to write a test that fails without fixing the problem.

-- 
From "know your smileys":
 :^[/   mean-smiley-with-cigarette

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
