### ISSUE TITLE
gvim expands Environment Variables in path

### ISSUE THREAD

**Issue by xvim64** [vim/vim#12440]
### Steps to reproduce

1. run windows explorer
2. create "TEST_%COMSPEC%.txt"
3. open "TEST_%COMSPEC%.txt" using gvim (mouse right button --> open with --> gvim.exe)
4. gvim display the file name as "TEST_C:\Windows\System32\cmd.exe.txt", not "TEST_%COMSPEC%.txt"

TEST_%COMSPEC%.txt  -->  TEST_C:\Windows\System32\cmd.exe.txt
TEST_%USERNAME%.txt  -->  TEST_[account_name].txt
TEST_%PROMPT%.txt  -->  TEST_$p$g.txt

![001](https://github.com/vim/vim/assets/83569599/6631c6bf-1077-4baa-9a1e-b48bb5697cab)

### Expected behaviour

Open the unconverted filename itself.

### Version of Vim

9.0.1575

### Environment

Windows 10/11 x64 22h2
gvim

**Comment by k-takata** [comment]
> open "TEST_%COMSPEC%.txt" using gvim

How did you open it?

**Comment by xvim64** [comment]
> > open "TEST_%COMSPEC%.txt" using gvim
> 
> How did you open it?

mouse right button --> open with --> gvim

or

in Total Commander, Double Commander with internal association with gvim.

**Comment by brammool** [comment]
The %NAME% part is a kind of wildcard, expanding "NAME" as an environment variable.
Because of the way MS-Windows traditionally works, the application has to expand wildcards, and at that time
cannot tell the difference between literal characters and wildcard characters.
I don't think we can change this without breaking other cases or making it inconsistent.
Better avoid using this kind of file name.  Why would you want to use it?

**Comment by xvim64** [comment]
>Why would you want to use it?

When in admin in Windows, SESSIONNAME is not defined.

But not in admmin, %SEESIONNAME% is Console.

Some programs generate "%SESSIONNAME%" itself in path because SESSIONNAME is not defned.

When not in admin, I want to edit "%SESSIONNAME%.txt" itself with vim, not notepad.

But gvim edits Console.txt instead of "%SESSIONNAME%.txt" itself.

Notepad can edit "%SESSIONNAME%.txt" itself.

But gvim is not.

Can you add an option that is limited to opening files only?

like ...

set openingfiletranslateenvvar=no
(default : yes)

It will not break the way MS-Windows' Traditionally works.

And it will be useful.

**Comment by k-takata** [comment]
The `--literal` option can be used.

From PowerShell:
```
> gvim --literal TEST_%COMSPEC%.txt
or
> gvim --literal "TEST_%COMSPEC%.txt"
```

From cmd.exe:
```
> gvim --literal TEST_^%COMSPEC^%.txt
```

To make this work from Explorer, you may want to edit the registry.

**Comment by xvim64** [comment]
> The `--literal` option can be used.

Can I include '--literal' as an option in _vimrc?

The literal option will be useful.

If I have the option, there is no need to edit the registry and open powershell or cmd.

**Comment by k-takata** [comment]
> > How did you open it?
>
> mouse right button --> open with --> gvim.exe

If you install Vim Context Menu (GvimExt) from the installer, you should be able to select "Edit with Vim" instead of "Open with".
This uses the `--literal` option (even without editing the registry by yourself).

> Can I include '--literal' as an option in _vimrc?

Unfortunately, no.

Another way is to open the file from gvim:
```vim
:e TEST_\%COMSPEC\%.txt
```
If you use tab completion (`:h c_<Tab>`), `\` will be automatically inserted.

Or, you can also use the file open dialogbox:
```vim
:browse e
```

**Comment by xvim64** [comment]
> Another way is to open the file from gvim:
> 
> ```viml
> :e TEST_\%COMSPEC\%.txt
> ```

Thanks for your interest!

I have another question about searching literal strings in vim.

Is it possible to search for literal strings containing " \ + * " characters without modifying them in normal mode search '/'?

Sometimes I want to search for a long string that includes " / \ + * . [ ] " and copy it to clipboard and paste it into a search.

Is it possible to search without modifications?

I can't find the way on the internet without using vimscript.
