### ISSUE TITLE
sh.vim: syntax highlighting bug: conditional parameter expansion with quoted strings

### ISSUE THREAD

**Issue by jayaddison** [vim/vim#12450]
### Steps to reproduce

1. Create a script (here, 'sample.sh') that contains a conditional shell variable expansion that contains quoted elements in the [`word` clause](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html):

```sh
#!/bin/sh
echo ${FOO:+'one' two}
```

2. Confirm that the file is a valid script, and that the entire contents of the `word` clause are produced when the conditional `parameter` is present:

```sh
$ sh sample.sh  # variable is null/empty

$ FOO=1 sh sample.sh  # variable is non-empty
one two
```

2. Load the file in `vim` with `sh.vim` syntax highlighting enabled.

4. Observe that the expansion after the quoted string is highlighted as if it were a syntax error:

![image](https://github.com/vim/vim/assets/55152140/9d490629-f95d-4762-bdd6-c16095bcc72b)

### Expected behaviour

The entire `word` clause, including the component after the quotes, up until the closing `}` character is valid and should not appear as a syntax error.

Note that this problem is reproducible with both single-quotes and double-quotes.

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44) Included patches: 1-1378, 1499 Modified by team+vim@tracker.debian.org Compiled by team+vim@tracker.debian.org

### Environment

Debian Linux (bookworm)

**Comment by zzzyxwvut** [comment]
The obvious way to _fix_ it is (`:help ft-sh-syntax`):
```vim
:let g:sh_no_error = 1

" Issue the next command in the sample.sh buffer.
:doautocmd FileType
```

On the other hand, embedded strings are embedded strings,
whatever their arrangement is:
```shell
#!/bin/sh

echo ${FOO:+one 'two'}
echo ${FOO:+'one' two}
echo ${FOO:+one "two"}
echo ${FOO:+"one" two}
```

Therefore, `shDerefPattern` can reciprocally be sought after
`shDerefString`:
https://github.com/vim/vim/blob/71badf9547e8f89571b9a095183671cbb333d528/runtime/syntax/sh.vim#L568-L570

since `shDerefPattern` already tests for the containment of
`shDerefString`:
https://github.com/vim/vim/blob/71badf9547e8f89571b9a095183671cbb333d528/runtime/syntax/sh.vim#L560-L561

(I wonder, is there any need for `shDerefPattern` to
recursively `contain` _and_ `nextgroup` own definition?)

Consider appending to `$HOME/.vim/after/syntax/sh.vim`:
```vim
" See issues/12450.
syn region shDerefString	contained	matchgroup=shDerefDelim start=+\%(\\\)\@<!'+ end=+'+	contains=shStringSpecial	nextgroup=shDerefPattern
syn region shDerefString	contained	matchgroup=shDerefDelim start=+\%(\\\)\@<!"+ skip=+\\"+ end=+"+	contains=@shDblQuoteList,shStringSpecial	nextgroup=shDerefPattern
```

**Comment by jayaddison** [comment]
> Consider appending to `$HOME/.vim/after/syntax/sh.vim`:
> 
> ```viml
> " See issues/12450.
> syn region shDerefString	contained	matchgroup=shDerefDelim start=+\%(\\\)\@<!'+ end=+'+	contains=shStringSpecial	nextgroup=shDerefPattern
> syn region shDerefString	contained	matchgroup=shDerefDelim start=+\%(\\\)\@<!"+ skip=+\\"+ end=+"+	contains=@shDblQuoteList,shStringSpecial	nextgroup=shDerefPattern
> ```

Thanks @zzzyxwvut - that resolves the problem and is working well so far.  I'll continue using `vim` with those configuration changes in place for a while (some weeks?) to watch for any side-effects.

**Comment by jayaddison** [comment]
I haven't noticed any regressions in syntax highlighting for shell scripts since including this change.  Would it be worthwhile to open a pull request that contains the same modifications?

**Comment by zzzyxwvut** [comment]
The maintainer of the file has already been notified (see
Assignees at the top of this page).  Since there is no
public _upstream_ repository for the changed file, the best
course of action would be to generate a diff file against
the most recent published [version](https://www.drchip.org/astronaut/vim/index.html#SYNTAX_SH) of the file and to either
post it here (there is a filed issue to attach it to) or to
email it to the maintainer.

**Comment by cecamp** [comment]
I've included the requested change in syntax/sh.vim version#210.
BTW, its nice that "the maintainer of the file has already been notified" -- except that I wasn't notified (which I interpret as meaning was sent an email). I just happened upon the discussion. I really hate having to dig code out of git; it always takes me 15-20 minutes to get it, so puh-leze just email it to me.
