### ISSUE TITLE
highlight SpecialKey and NonText

### ISSUE THREAD

**Issue by Passw** [vim/vim#12472]
### Steps to reproduce

1. rm -rf ~/.vimrc
2. gvim testfile   // tesfile should contains tab,eol
4. set list  lcs=tab:→\ ,space:·,nbsp:␣,eol:¶
5. highlight SpecialKey guifg=red gui=NONE
6. highlight NonText guifg=green gui=NONE

### Expected behaviour

tab and eol should be with guifg=red
but tab with guifg=red, eol with guifg=green
![image](https://github.com/vim/vim/assets/5151456/483a1e92-11ef-417e-9621-1c8a17d51b5c)

### Version of Vim

with the latest vim downloaed via `choco install vim`

### Environment

gvim under Windows

#### vim
- `:help SpecialKey`
```
							*hl-SpecialKey*
SpecialKey	Meta and special keys listed with ":map", also for text used
		to show unprintable characters in the text, 'listchars'.
		Generally: Text that is displayed differently from what it
		really is.
```

- `:help NonText`
```
							*hl-NonText*
NonText		'@' at the end of the window, "<<<" at the start of the window
		for 'smoothscroll', characters from 'showbreak' and other
		characters that do not really exist in the text, such as the
		">" displayed when a double-wide character doesn't fit at the
		end of the line.
```

#### nvim
- `:help SpecialKey`
```
							*hl-SpecialKey*
SpecialKey	Unprintable characters: Text displayed differently from what
		it really is. But not 'listchars' whitespace. |hl-Whitespace|
```

- `:help NonText`
```
							*hl-NonText*
NonText		'@' at the end of the window, characters from 'showbreak'
		and other characters that do not really exist in the text
		(e.g., ">" displayed when a double-wide character doesn't
		fit at the end of the line). See also |hl-EndOfBuffer|.
```

vim treats both keys listed with `:map` and `listchars` as **SpecialKey**. Sometimes we want color of `listchars` lighter (since tab,eol in source code should be lighter), but with keys listed with `:map` with darker color.

Personally I prefer **nvim**'s solution to **SpecialKey** (without `listchars`) and **NonText**

**Comment by chrisbra** [comment]
I might be missing something, but Vim is exactly behaving like what is documented, isn't it? I am sure, if we change it, people will also complain, so that may not be the best idea.

**Comment by chrisbra** [comment]
yes, but there is a difference between `unprintable characters in the text` and `characters that do not really exist in the text`. So in this case it makes sense to distinguish between `NonText` and `SpecialKey`, because the `eol` char is not really there in the text.

**Comment by brammool** [comment]
> In case someone has interest in this.
> 
> Just add a link to nvim's implementation about adding new higlight ground **Whitespace** for `listchars`
> 
> [[RDY] new highlight group Whitespace for 'listchars' ](https://github.com/neovim/neovim/pull/6367)
> 
> ### nvim
> - `:help hl-Whitespace`
> ```
> 							*hl-Whitespace*
> Whitespace	"nbsp", "space", "tab", "multispace", "lead" and "trail"
> 		in 'listchars'.
> ```

This sounds like a partial solution.  Soon someone wants one of the
items to be highlighted differently.  E.g. to make "trail" look more
like an error.  For a better solution a more drastic change is needed,
that also takes care of characters displayed when 'list' is not set.
The 'listchars' option clearly has outgrown it's original purpose.

-- 
I AM THANKFUL...
...for the mess to clean after a party because it means I have
been surrounded by friends.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
