### ISSUE TITLE
File open can't show Makefiles

### ISSUE THREAD

**Issue by radlyeel** [vim/vim#12685]
### Steps to reproduce

in gvim 9.0.1189, in a directory with a Makefile (or any file with no extension, select menu item File -> Open to get the system File Open dialog box.  Note that All Files is shown as (*).  Navigate to a folder where there are, say, C files.  With All Files still selected, note that the C files do not appear.  Change the file type selector to, say, C Source (*.c,*.h).  Now C source files are visible, and Makefiles are not.  This is correct behavior.

Note that in the list of file types to show, All Files is given as (*.*).  This means that files with no extension, such as Makefile, are not shown.  

All Files should always be specified as (*, *.*)

### Expected behaviour

Selecting All Files should make all files visible, including those with no extension

### Version of Vim

gvim 9.0.1189

### Environment

Ubuntu 23.04

**Comment by chrisbra** [comment]
This seems particularly bad using the GTK3 GUI, because you cannot override the filter :/ 

![grafik](https://github.com/vim/vim/assets/244927/51890f75-86dc-4b15-a5df-c32dc848b152)


Hm, I suppose this does not only affect C files, but a lot of other file types. 

Here is a patch for the c filetype plugin @brammool :

```patch
diff --git a/runtime/ftplugin/c.vim b/runtime/ftplugin/c.vim
index 3627089ec..3acf37738 100644
--- a/runtime/ftplugin/c.vim
+++ b/runtime/ftplugin/c.vim
@@ -53,18 +53,18 @@ if (has("gui_win32") || has("gui_gtk")) && !exists("b:browsefilter")
     let b:browsefilter = "C++ Source Files (*.cpp *.c++)\t*.cpp;*.c++\n" .
          \ "C Header Files (*.h)\t*.h\n" .
          \ "C Source Files (*.c)\t*.c\n" .
-         \ "All Files (*.*)\t*.*\n"
+         \ "All Files\t*\n"
   elseif &ft == "ch"
     let b:browsefilter = "Ch Source Files (*.ch *.chf)\t*.ch;*.chf\n" .
          \ "C Header Files (*.h)\t*.h\n" .
          \ "C Source Files (*.c)\t*.c\n" .
-         \ "All Files (*.*)\t*.*\n"
+         \ "All Files\t*\n"
   else
     let b:browsefilter = "C Source Files (*.c)\t*.c\n" .
          \ "C Header Files (*.h)\t*.h\n" .
          \ "Ch Source Files (*.ch *.chf)\t*.ch;*.chf\n" .
          \ "C++ Source Files (*.cpp *.c++)\t*.cpp;*.c++\n" .
-         \ "All Files (*.*)\t*.*\n"
+         \ "All Files\t*\n"
   endif
   let b:undo_ftplugin ..= " | unlet! b:browsefilter"
 endif
```
With this patch applied, this would look like this:
![grafik](https://github.com/vim/vim/assets/244927/c1542d90-a291-4df0-8133-cce6035c075c)

Note: This doesn't seem to be a problem in the Windows UI: 
![grafik](https://github.com/vim/vim/assets/244927/eb8c415b-7742-4c14-8a33-9538539e2626)
