### ISSUE TITLE
Support 24-bit color in the new Windows console (RS2)

### ISSUE THREAD

**Issue by be5invis** [vim/vim#1270]
ref = Microsoft/BashOnWindows#345

**Comment by vim-ml** [comment]
Am 2016-11-23 08:43, schrieb Belleve Invis:

> ref = Microsoft/BashOnWindows#345 [1]

A little bit more information would be appreciated. What exactly is 
missing from the current support for the Windows console?
What needs to be done?

Simply quoting an issue which is about 256color support on windows 
console (and not about true color support) does not help.

regards,
Christian

**Comment by be5invis** [comment]
There is a code segment that shows the incoming 24-bit color support in Windows.

```C
bool EnableVTMode()
{
    // Set output mode to handle virtual terminal sequences
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (hOut == INVALID_HANDLE_VALUE)
    {
        return false;
    }

    DWORD dwMode = 0;
    if (!GetConsoleMode(hOut, &dwMode))
    {
        return false;
    }

    dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    if (!SetConsoleMode(hOut, dwMode))
    {
        return false;
    }
    return true;
}
int __cdecl wmain(int argc, WCHAR* argv[])
{   
    argc; // unused
    argv; // unused
    //First, enable VT mode
    bool fSuccess = EnableVTMode();
    if (!fSuccess)
    {
        printf("Unable to enter VT processing mode. Quitting.\n");
        return -1;
    }
    int red = 0; // set these to whatever
    int green = 0;
    int blue = 0;
    printf("\x1b[38;2;%d;%d;%dm", red, green, blue); // produces RGB foreground
    printf("\x1b[48;2;%d;%d;%dm", red, green, blue); // produces RGB background

    int index = 0;
    printf("\x1b[38;5;%dm", index); // produces xterm color table index foreground
    printf("\x1b[48;5;%dm", index); // produces xterm color table index background
}
```

**Comment by vim-ml** [comment]
That sounds like it should work when setting t_8f and t_8b correctly. 
There is even an example in the help, that should work with those codes. 
See :h xterm-true-color

Please test that before you create an issue for it and please ask user 
questions on the vim_use ml. The issue tracker is for actual issues.

Best,
Christian

**Comment by be5invis** [comment]
The key problem is that you need to call `SetConsoleMode` to enable ANSI escapes.

**Comment by jpmartin2** [comment]
This is definitely something I'd be interested in. I can confirm that just setting t_8f= (and the other similar variables) and or term= doesn't seem to work. 

I've also got a local build and tried playing around with adding ENABLE_VIRTUAL_TERMINAL_PROCESSING in the places where SetConsoleMode happens. However, I couldn't get anything working (but I'm not sure I quite understand everything that's going on here). 

Also, because of the previous lack of ansi escape code support, there's a bunch of code to translate certain escape codes to SetConsoleXXX calls. I wonder if at some point it might make sense to add support for just using the ansi escape codes if ENABLE_VIRTUAL_TERMINAL_PROCESSING can be enabled.
