### ISSUE TITLE
VIM segment fault

### ISSUE THREAD

**Issue by datonli** [vim/vim#1273]
vim thrown a segment fault !!!
![image](https://cloud.githubusercontent.com/assets/6770147/20588422/ef13610c-b24f-11e6-95eb-13b624da9abb.png)

vim version is 
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)

The core file you could find in
[core.17392.zip](https://github.com/vim/vim/files/610583/core.17392.zip)

I don't know why it's going wrong and it never happened before.

May this could help community.

**Comment by dpelle** [comment]
I see that you're using vim-7.2 from 2008.
Why do you use such an old version?
I recommend downloading or compiling a more recent version of Vim.
Many bugs were fixed over the last few years.
The latest version in git is vim-8.0.95.

Attaching a core file without its corresponding executable is also useless, but there is no need to add it, as I don't think that anybody will debug such an old version of vim. The bug was likely already fixed. If it still happens with a more recent version of vim, you need to describe the steps to reproduce it.

**Comment by chrisbra** [comment]
closing. If you can verify with a more recent version, feel free to reopen

**Comment by datonli** [comment]
@dpelle The reason I use such old vim is the only choice in working environment. Thanks for your kind explanation anyway.
