### ISSUE TITLE
Key bindding doesn't work as expected in Windows 11 with alacritty term.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#12776]
### Steps to reproduce

1. Open Alacritty
2. vim --clean
3. `:nnoremap <C-h> <C-w><C-h>`
4. :vsplit
5. Try to use <C-h> to jump to left buffer

### Expected behaviour

Normally use `<C-h>`. I tested on Pop-OS with the same terminal, bash shell and reproduce step without any error. I opened an [issue](https://github.com/alacritty/alacritty/issues/6795#issuecomment-1475077825) but they said nothing need to fix so I think maybe issue with vim.

### Version of Vim

9.1.1677

### Environment

OS: Windows 11
Shell: pwsh > 7.2

**Comment by chrisbra** [comment]
so does it work in a different terminal then? What about the gui?

**Comment by hungpham3112** [comment]
> so does it work in a different terminal then? What about the gui?

Everything is ok, the bug only in alacritty.

**Comment by hungpham3112** [comment]
Hi @chrisbra any update with this thread?

**Comment by chrisbra** [comment]
You need to provide much more information. What version of alacritty? What is $TERM set to? what does vim say about `:set term?` what happens if you map `<c-h>` to something different? Does it instead work with the backspace key or the delete key? What does `:verbose set nmap?` show? Can you provide a logfile `vim --clean --log logfile` (please only provide the mapping and pressing the key once, otherwise it will be too verbose to see). In general, please provide as much information as possible to help debug this issue.

**Comment by chrisbra** [comment]
I have now just installed [alacritty 0.12.3](https://github.com/alacritty/alacritty/releases/tag/v0.12.3) and together with [Vim 9.0.1951](https://github.com/vim/vim-win32-installer/releases/tag/v9.0.1950), I can successfully jump to the left window by pressing `<c-h>`, after `:nnoremap <C-h> <C-w><C-h>` 

Note: it doesn't work by pressing the backspace key, I believe that is because Vim uses the win32 terminal and there the backspace key does not send `<c-h>`.

**Comment by chrisbra** [comment]
not reproducible
