### ISSUE TITLE
MacVim crashes when se/set command issued without arguments

### ISSUE THREAD

**Issue by LukeOrgana** [vim/vim#1304]
I have MacVim (8.0) installed on macOS Sierra (10.12).

I have incorporated functionality into my .vimrc file to automatically save my session in ~/.vim/sessions when closing (session name can be set using :SetSession "session_filename", or if not set it is automatically saved as LastSession.vim). This works fine if I am working in a C++ project. However, I have just installed vim-latex and now when editing a latex file the save/open session functionality does not work. When closing Vim, no session file is created automatically. If I create one manually using :mksession! path/to/sessions/sessionfilename.vim, then the file is created as expected but loading this file from within Vim causes Vim to crash. I have carried out some simple debugging and it crashes upon issuing the :se[t] command without any arguments, which appears on the final line of the sessionfilename.vim file when I am working with .tex files. I have further examined this issue by just entering in the :se command on its own in Vim and it causes my MacVim window to shut down instantly, regardless of what file I am editing (cpp/tex/whatever).

I have attached my .vimrc file (which I have had to rename as vimrc.txt to upload here) and the output from running :so $VIMRUNTIME/bugreport.vim.

Thanks for your help.

[bugreport.txt](https://github.com/vim/vim/files/630022/bugreport.txt)
[vimrc.txt](https://github.com/vim/vim/files/630024/vimrc.txt)

**Comment by nuko8** [comment]
Vim is a project different from and independent of MacVim.

As shown in the issue header, if you do think the issue is specific to MacVim, the most appropriate place to file for the report should be at https://github.com/macvim-dev/macvim .

For the case where you actually think the issue is truly relevant to Vim, then please check if the same crash happens with `/usr/bin/vim` of your macOS (or, even better, with the latest version of Vim built from source by yourself or installed through a package manager), so that the people here can be convinced that the issue is actually Vim proper.

Even if that is the case, then please try to specify which plugin causes the trouble. If you succeed in specifying the one, then reporting the issue to the developer(s) of that plugin first is the fastest track to reach an answer or solution.

> Thanks for your help.

Sorry, but this is not a place to ask for help,,,

**Comment by LukeOrgana** [comment]
> Sorry, but this is not a place to ask for help,,,

Wow! I was just being polite.

It does seem to work normally in `/usr/bin/vim` . I will file a report with the developers of MacVim.
