### ISSUE TITLE
syntax is disabled after argdo

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#13058]
### Steps to reproduce

Similar to https://github.com/vim/vim/issues/4761, for example

```
vim --clean -u ~/.viminrc file1.vim file2.vim
```

with `~/.viminrc` reading

```vim
set nocompatible
autocmd VimEnter * exe 'silent argdo echo ""' | rewind
filetype plugin indent on
syntax on
" edit after @chrisbra's comment
set hidden
```

Enter `:bnext`.

### Expected behaviour

Syntax highlight should be enabled, but is not	

### Version of Vim

9.0.1632

### Environment

Opensuse 15.4, urxvt, zsh

**Comment by Konfekt** [comment]
Though `:help argdo` explains

```
Note: While this command is executing, the Syntax
			autocommand event is disabled by adding it to
			'eventignore'.  This considerably speeds up editing
			each file.
```

it does not say that syntax highlighting is permanently disabled

**Comment by chrisbra** [comment]
hm, I cannot seem to reproduce

**Comment by Konfekt** [comment]
Oh, I am sorry! I forgot 

```vim
set hidden
```

**Comment by chrisbra** [comment]
ah, I suspected something like this

**Comment by chrisbra** [comment]
I checked it again. You need to use:
```
autocmd VimEnter * `++nested exe 'silent argdo echo ""' | rewind
`` 

so that the nested autocommands executed from the VimEnter autocommands are executed. Than the syntax highlighting is kept.

**Comment by Konfekt** [comment]
Thank you very much. Would you mind explaining why `hidden` makes `++nested` necessary?

**Comment by chrisbra** [comment]
When hidden is set, the buffers are kept in memory, with all their related information, including FileType and Syntax settings. When 'hidden'  is not set, Vim will detect those after the `:bnext` command, because the buffer does not yet exist, so it will trigger the whole Filetype detection and synax option when Vim (re-) loads the file from disk. However when `'hidden'` is set this already happened during the `:argdo` command, although some of those detection autocommands have been blocked by the missing `nested` flag and therefore the syntax option are not completely initialized.
