### ISSUE TITLE
Possibly undocumented behavior with replace after visual

### ISSUE THREAD

**Issue by pierreganty** [vim/vim#13091]
### Steps to reproduce

I cannot explain the following state machine which was extracted from interacting with vim.
The machine has been trimmed to focus on the issue reported.
 
![filtered](https://github.com/vim/vim/assets/2111160/8135eeac-9266-4dd3-a650-185213bc55f2)

Consider the following sequence starting from `s0` (Normal mode):
1. `<C-v>`
2. `r` (or `gr`)
3. `<C-c>` (ends up in `s29`)
4. `g`
5. `r` (ends up in `s57`)

Once in `s57` every keystroke I tried ended up going back to Normal mode `s0`.

Note: The issue seems to be more than a decade old. Indeed, the diagram at https://rawgit.com/darcyparker/1886716/raw/eab57dfe784f016085251771d65a75a471ca22d4/vimModeStateDiagram.svg described a similar undocumented behavior already in 2012. 

### Expected behaviour

I don't know what is supposed to happen after emitting `<C-c>` from `s29` but state `s62` seems to visit unknown/undocumented parts of the editor. I am not sure if that was ever the intention of the devs to have these "states". The labelling of the nodes using `mode()` is also confusing. Explanations are welcome.

### Version of Vim

9.0.1544

### Environment

Mac OS
Terminal.app

**Comment by chrisbra** [comment]
since you found the old state diagram, did you find this discussed anywhere?

**Comment by pierreganty** [comment]
Unfortunately not.

**Comment by ychin** [comment]
Btw from cursory look, this is specific to the way Ctrl-C works. Ctrl-C is "special" in Vim, in that there are hard-coded handlers for it acting as an interrupt. For example, this behavior doesn't trigger just by adding `inoremap <C-C> <C-C>` even though semantically it should do the same thing. That's because there's an internal `ctrl_c_interrupts` variable that gets set only if Ctrl-C is unmapped, and it sets `got_int` to true when an unmapped Ctrl-C is hit.

Not sure exactly why this specific interaction happens though.

**Comment by chrisbra** [comment]
I would say that after `Ctrl-C` it should abort `nv_replace`

**Comment by chrisbra** [comment]
It happens on purpose however:

https://github.com/vim/vim/blob/e7d79eb98a30c529cf53fb4852a71b9fd1336c41/src/normal.c#L4801-L4802

Not sure what exactly should happen in that particular case.

I would think, that the following patch using would clear it after `Ctrl-C` however:
```
diff --git a/src/normal.c b/src/normal.c
index 86b8740f8..f2c8f12c3 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -4799,7 +4799,10 @@ nv_replace(cmdarg_T *cap)
     if (VIsual_active)
     {
        if (got_int)
+       {
            reset_VIsual();
+           return;
+       }
        if (had_ctrl_v)
        {
            // Use a special (negative) number to make a difference between a
```

**Comment by pierreganty** [comment]
I applied your patch and I ran the tests. There were no failing tests (except some "flaky" ones). I also re-generated the state machine, it has 6 states less and it looks fine. If it is good for you, then it is good for me.  Thank you.

**Comment by chrisbra** [comment]
I'll re-check it soon. I noticed at least on my currently installed gvim windows version, this strange state currently doesn't exist and it works as expected. So there seems to be some differences between either gui and terminal vim or terminal and Windows GUI version. Not sure yet.

**Comment by chrisbra** [comment]
Can you please check https://github.com/vim/vim/pull/13112 ?

**Comment by darcyparker** [comment]
As the creator of the original diagram, this is cool to see. https://gist.github.com/darcyparker/1886716

WRT: @chrisbra: `since you found the old state diagram, did you find this discussed anywhere?` - No, I don't believe it was ever discussed.  I wasn't sure if it was a bug at the time, and thought it could be just a state I didn't appreciate. I wrote a small note `undocumented` and moved on.  The diagram was originally shared on hacker news by Steve Losh (behind Learn Vim the Hardway)... and there was the usual hacker news discussion about vim vs emacs. But nothing substantial about the contents.

Thanks @pierreganty for putting some life back into this and the others for fixing it!
