### ISSUE TITLE
listchars: leadmultispace does not count spaces hidden by scrolling off to the side

### ISSUE THREAD

**Issue by osthomas** [vim/vim#13145]
### Steps to reproduce

Example:

`set listchars=leadmultispace:x--- | hi SpecialKey cterm=NONE gui=NONE guifg=red ctermfg=1`

```
012345678
        A
```

With the full line in view, this renders as:
```
012345678
x---x---A
```

Sidescrolling past the first column, this renders as:
```
12345678
x---x--A
```

![image](https://github.com/vim/vim/assets/8322329/f50ba94e-0dc8-4890-8318-86ee9115dabf)

left starting at column 2, right starting at column 1

### Expected behaviour

I expected `leadmultispace` to count the spaces off-screen, rendering as:

```
12345678
---x---A
```

### Version of Vim

9.0.1837

### Environment

$TERM: xterm-256color
Shell: bash

**Comment by tonymec** [comment]
Hm. The `*lcs-leadmultispace*` documentation is not very explicit. I suppose that the easiest solution would be to decide that «t'ain't a bug, it's a feature» and document in the help (maybe also under `*lcs-multispace*`) that the first character of the value applies to the first **visible** space of several.

If, OTOH, Christian prefers to treat it like an actual bug, or if you are savvy enough to delve into the code and fix it, then it would mean a patch somewhere in the C code rather than merely in the `options.txt` helpfile. But in that case, of course, beware of the risk of introducing another bug somewhere else.
