### ISSUE TITLE
Jump between words and stop at end of line

### ISSUE THREAD

**Issue by joeky888** [vim/vim#1323]
[Same question here](http://vi.stackexchange.com/questions/10602/vim-jump-between-words-and-stop-at-end-of-line)

In normal mode, <kbd>b</kbd> and <kbd>w</kbd> are jumping between words,
and I would like to stop at the end of line.

For example:
The cursor is right over here

![alt](https://i.stack.imgur.com/zDd4M.png)

When I press <kbd>w</kbd>, what I expect is

![alt](https://i.stack.imgur.com/paImG.png)

Instead, the cursor jump to the beginning of next line.

ps: I know about <kbd>e</kbd> and <kbd>$</kbd>, but that's not what I want.
What I need is something like `set iskeyword-=\n`
Because with something like `set iskeyword-=\n`,
I can use it with <kbd>C-Left</kbd> <kbd>C-Right</kbd> in insert mode as well.

Thanks.

**Comment by chrisbra** [comment]
Am 2016-12-13 11:54, schrieb j16180339887:
> Same question here [1]
> 
> In normal mode, b and w are jumping between words,
> and I would like to stop at the end of line.
> 
> For example:
> The cursor is right over here
> 
>  [2]
> 
> When I press w, what I expect is
> 
>  [3]
> 
> Instead, the cursor jump to the beginning of next line.
> 
> ps: I know about e and $, but that's not what I want.
> What I need is something like set iskeyword-=\n
> Because with something like set iskeyword-=\n,
> I can use it with C-Left C-Right in insert mode as well.
> 
> Thanks.
> 

That's what maps are for. Map b and w to a function
that stops where you want. I see a possible solution
already mentioned at vi.stackexchange.com.

Alternatively, you can ask user questions on the vim-use
mailinglist.

This forum is for issues only. Thanks.

**Comment by vim-ml** [comment]
On Tuesday, December 13, 2016 at 4:54:46 AM UTC-6, j16180339887 wrote:
> 
> In normal mode, b and w are jumping between words,
> 
> and I would like to stop at the end of line.
> 

Normally I'd say asking on vim_use would be the correct place for this question.

But then I noticed the 'whichwrap' doesn't allow changing behavior of w/b. That seems like it'd be a good feature addition! I'm not sure how it could be done and remain backwards-compatible however.

If we can assume people follow best practices and use :set whichwrap+=whatever instead of setting the full option value then just changing the defaults to include the w/b control would mostly do the trick but without that assumption behavior would change.
