### ISSUE TITLE
Build gvim on Linux - Instructions missing.

### ISSUE THREAD

**Issue by deragon** [vim/vim#1334]
Cloned the repository and managed to compile easily vim under Linux (Ubuntu 16.04 LTS).  However, I read many web pages on the web and attempted to get gvim to be built, to no avail.  My latest attempt was the following:

    ./configure \
      --with-global-runtime="${SCRIPT_PATH_ABS}" \
      --with-features=huge \
      --enable-gui=gnome2 \
      --enable-rubyinterp=yes \
      --enable-pythoninterp=yes

The output does not indicate any gnome related issues, yet the 'gvim' binary is not being built.

The documentation provided in the repository should come with instructions on how to build gvim on Linux.

**Comment by k-takata** [comment]
The `gvim` binary will not be created when you run `make`.
It is normally created (as a symlink) when you run `make install`.
If you just want to check if the GUI version works without installing, you can use `./vim -g`.

**Comment by tonymec** [comment]
To get the source, on any platform, see http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial


To compile on Unix-like platforms including Linux, see http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

There are several useful "make" targets:
* `make config` configures (from a clean source) but doesn't compile
* `make` compiles the current configuration; the compiled executable is left in the `src/` directory of the source, it is not stripped of its symbols and not installed into your `$PATH`
* `make reconfig` recomputes the configuration and compiles it. It is necessary in two cases:
** if you have changed your configuration
** if the libraries Vim needs have substantially changed, for instance after an upgrade of the OS
* `make install` (compiles if the source has changed, and) installs the executable, the runtime files, everything -- in `/usr/local/bin/` and (for version 8.0) in and under `/usr/local/share/vim/vim80/` unless you specify something else (which I do not recommend unless you are a Linux distribution).
* `make installruntime` installs only the runtime files
* `make installvimbin` installs only the executable
* and more

In all cases, I recommend to set the configuration by environment variables, not by running `configure` manually, because with environment variables you will get no bad surprises if `make` decides to recompute your configuration by running `configure` before the actual compile.

Best regards,
Tony.

**Comment by chrisbra** [comment]
It is mentioned briefly at `:h gui-x11-start`: 

    So if you call the executable "gvim", or make "gvim" a link to the executable,
    then the GUI version will automatically be used.  Additional characters may be
    added after "gvim", for example "gvim-5"

**Comment by deragon** [comment]
Ok.  Am I the first person who asked about this???  This is not intuitive.  May I suggest that the documentation within the source, a BUILD.md for instance, would explain this?  And 'make' would actually create in the src/ directory a symlink gvim -> vim to give a clue?  I had to open a bug report and bug all of you (thanks for responding!) because I could not find the information.

Should I open a new bug report to ask for better documentation?

**Comment by grochmal** [comment]
Heh.  As a unix user (pretty much exclusively for the past 10 years) I'd argue that it isn't strange at all.  We are used to behaviour of a binary depending on the executable basename.  i.e. this:

    [grochmal@haps ~]$ ls -l `which gvim`
    lrwxrwxrwx 1 root root 3 Nov 16 02:06 /usr/bin/gvim -> vim

Is the same case as with `sh`:

    [grochmal@haps ~]$ ls -l `which sh`
    lrwxrwxrwx 1 root root 4 Dec 10 18:55 /usr/bin/sh -> bash

And bash does behave differently when run as `sh` (e.g. different default PS1).  And it is `make install` for bash that creates the soft link.

On the other hand I have no clue how the Vim installation works on MS Windows.

**Comment by tonymec** [comment]
On Thu, Dec 22, 2016 at 11:31 PM, Michal Grochmal
<notifications@github.com> wrote:
>
> Heh. As a unix user (pretty much exclusively for the past 10 years) I'd argue that it isn't strange at all. We are used to behaviour of a binary depending on the executable basename. i.e. this:
>
> [grochmal@haps ~]$ ls -l `which gvim`
> lrwxrwxrwx 1 root root 3 Nov 16 02:06 /usr/bin/gvim -> vim
>
> Is the same case as with sh:
>
> [grochmal@haps ~]$ ls -l `which sh`
> lrwxrwxrwx 1 root root 4 Dec 10 18:55 /usr/bin/sh -> bash
>
> And bash does behave differently when run as sh (e.g. different default PS1). And it is make install for bash that creates the soft link.
>
> On the other hand I have no clue how the Vim installation works on MS Windows.

On Windows, it is not possible to use a single executable to run as
both a GUI and a console utility, regardless of soft or even hard
links (IIUC, both kinds are possible in modern versions of Windows),
so vim.exe and gvim.exe must be different files. But the OP was asking
about Linux.

Best regards,
Tony.
