### ISSUE TITLE
ftplugin/systemd.vim should include a finish guard before using dosini scripts

### ISSUE THREAD

**Issue by benknoble** [vim/vim#13357]
See https://vi.stackexchange.com/q/43216/10604. I wrote to enno.nagel+vim@gmail.com on the 4th of October and have received no response.

**Comment by chrisbra** [comment]
Cc @konfekt 

Can you please create a PR for this?

Thanks
Chris

Am 16. Oktober 2023, um 20:04, schrieb "D. Ben Knoble" ***@***.***>:

See https://vi.stackexchange.com/q/43216/10604. I wrote to ***@***.*** on the 4th of October and have received no response.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/vim/vim/issues/13357">https://github.com/vim/vim/issues/13357</a>", "url": "<a href="https://github.com/vim/vim/issues/13357">https://github.com/vim/vim/issues/13357</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by Konfekt** [comment]
Dear @benknoble, I checked for your mail and am sorry to say that I found it indeed in the spam folder. This never happened before.

The mentioned error

```vim
Error detected while processing BufRead Autocommands for "*/etc/systemd/*.conf"..FileType Autocommands for "*"..function <SNR>1
4_LoadFTPlugin[18]..script /usr/share/vim/vim90/ftplugin/systemd.vim:
line   12:
E174: Command already exists: add ! to replace it: Sman silent exe '!' . KeywordLookup_systemd(<q-args>) | redraw!
```

should be fixed by https://github.com/vim/vim/pull/13297.

Regarding the wrong `b:did_ftplugin` check, how about replacing

```vim
" runtime/ftplugin/systemd.vim (lines 6-9)
if !exists('b:did_ftplugin')
  " Looks a lot like dosini files.
  runtime! ftplugin/dosini.vim
endif
```

by

```vim
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

let b:undo_ftplugin = "setl com< cms< fo<"
setlocal comments=:; commentstring=;\ %s formatoptions-=t formatoptions+=croql
```

?

**Comment by benknoble** [comment]
Ah, glad to hear back @Konfekt; hope my original post wasn't too brusque 😅

I think what we imagined was adding the `if exists | finish` guard just before

```vim
" runtime/ftplugin/systemd.vim (lines 6-9)
if !exists('b:did_ftplugin')
  " Looks a lot like dosini files.
  runtime! ftplugin/dosini.vim
endif
```

**Comment by Konfekt** [comment]
Okay, so `b:did_ftplugin` is set by `dosini.vim`. Seems to work as well. I have no strong opinions and would then go with your options if noon sees any red flags.
