### ISSUE TITLE
termguicolors not work in rxvt-unicode-256color

### ISSUE THREAD

**Issue by freereaper** [vim/vim#1336]
```bash
>>> vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  6 2016 16:33:37)
Included patches: 1-124
```
* OS: ubutun14.04  
* terminal:rxvt-unicode-256color
----
confused about how __termguicolors__ works in tmux inside rxvt, but in terminal, "set termguicolors' make vim color a mess.

**Comment by chrisbra** [comment]
please ask user question on the appropriate forums. This is a bug tracker. According to https://gist.github.com/XVilka/8346728 rxvt-unicode does only support 256colors.

**Comment by nuko8** [comment]
The following note is just "for the record."

As @chrisbra wrote, the current official version of urxvt, 9.22, does not support 24-bit colors.

Meanwhile,  a series of patches for urxvt to support them was [proposed](http://lists.schmorp.de/pipermail/rxvt-unicode/2016q2/thread.html) just a half year ago and [merged](http://cvs.schmorp.de/rxvt-unicode/src/screen.C?view=log ) into the codebase later.

Note that, as written in the commit message there, the implementation is done on top of the 256-color palette, and hence colors are still approximations.

Although it looks to me that the approximation is not noticeable in practical usage, some people sensible to colors might be temped to think it as a bug of Vim and raise an issue here, which is something we want to avoid for an obvious reason.

With that caveat, the patched version of urxvt supports truecolor nearly perfectly in practice, and, since it accepts the same `t_8f` and `t_8b` for xterm, the setup enabling truecolor should be pretty straightforward.

With this note, I'd like to ask you people for this: Before raising an issue here, please make sure whether or not your issue is really a bug of Vim.
