### ISSUE TITLE
Scripts named "build" are detected as bzl 

### ISSUE THREAD

**Issue by msonnabaum** [vim/vim#1340]
I was surprised to see strange syntax highlighting on a shell script named "build", with `#!/bin/sh` for the shebang. I checked the detected filetype and it was "bzl".

I then found this setting, which sets any file named build or workspace as bzl:

https://github.com/vim/vim/blob/master/runtime/filetype.vim#L312

Considering that it also appears to be case-insensitive, that feels too ambiguous to be a default in vim. It would be great if that could either be made case-sensitive or removed and left to a bzl specific plugin.

**Comment by brammool** [comment]
Mark Sonnabaum wrote:

> I was surprised to see strange syntax highlighting on a shell script
> named "build", with `#!/bin/sh` for the shebang. I checked the
> detected filetype and it was "bzl".
> 
> I then found this setting, which sets any file named build or
> workspace as bzl:
> 
> https://github.com/vim/vim/blob/master/runtime/filetype.vim#L312
> 
> Considering that it also appears to be case-insensitive, that feels
> too ambiguous to be a default in vim. It would be great if that could
> either be made case-sensitive or removed and left to a bzl specific
> plugin.

You are using MS-Windows?  The filetype rule checks for BUILD, thus on
case-sensitive systems it should not trigger for "build".

How aobut this:

" Bazel (http://bazel.io)
autocmd BufRead,BufNewFile *.bzl,WORKSPACE setfiletype bzl
if has("fname_case")
  autocmd BufRead,BufNewFile BUILD setfiletype bzl
endif

Disadvantage: a "BUILD" file on MS-Windows won't be recognized as bzl.
I don't think it's easy to recognize a bzl file from the contents, it
looks a lot like Python.

-- 
hundred-and-one symptoms of being an internet addict:
197. Your desk collapses under the weight of your computer peripherals.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by DanGe42** [comment]
The same behavior is on MacOS because HFS defaults to case-insensitive.

**Comment by msonnabaum** [comment]
Yeah, I'm on MacOS.

@brammool Just tried your suggestion and that seems to work for me.

**Comment by chrisbra** [comment]
fixed as of 68563937f58ea2dc

**Comment by dbarnett** [comment]
Would it be possible for whoever authored those changes to apply them to https://github.com/bazelbuild/vim-ft-bzl/blob/master/ftdetect/bzl.vim to keep it in sync?

**Comment by artasparks** [comment]
This is unfortunate, since it really neuters this ftdetect declaration. BUILD is the standard name for bazel BUILD files, and now on OSX and Windows it won't be recognized correctly. https://bazel.build/versions/master/docs/build-ref.html#BUILD_files

I haven't looked in depth through the ftdetect, but what about just moving the bazel-detection after something that looks for "#!/bin/sh"?

**Comment by brammool** [comment]
Josh Hoak wrote:

> This is unfortunate, since it really neuters this ftdetect declaration. BUILD is the standard name for bazel BUILD files, and now on OSX and Windows it won't be recognized correctly. https://bazel.build/versions/master/docs/build-ref.html#BUILD_files
> 
> I haven't looked in depth through the ftdetect. What about just moving the bazel-detection after something that looks for "#!/bin/sh"?

It is unfortunate that they picked such a common name for their files.
Now it's difficult to tell the type of file from the name.

We could check for no other type being detected, near the end, and then
catch "build" and "BUILD".

-- 
ARTHUR:    Well, it doesn't matter.  Will you go and tell your master that
           Arthur from the Court of Camelot is here.
GUARD #1:  Listen, in order to maintain air-speed velocity, a swallow
           needs to beat its wings 43 times every second, right?
ARTHUR:    Please!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dbarnett** [comment]
Did we decide to stick w/ completing disabling the detection if `fname_case` is missing? It rather hobbles the filetype detection on OSX.

Is applying it w/ lower precedence still an option? Or if not, maybe we could explicitly detect and exclude files with a shebang line at the top, since BUILD files should never have that.
