### ISSUE TITLE
Inconsistent naming of GVim in source code and documentation

### ISSUE THREAD

**Issue by ghost** [vim/vim#13429]
I noticed that "GVim" is written **inconsistently** in both the source code and documentation. It's referred to as `GVim`, `Gvim`, `gVim`, and `GVIM` in various instances, which can lead to confusion and inconsistencies. 

To maintain clarity and consistency, I suggest addressing this issue by standardizing the naming convention for GVim across all relevant files and documentation. This will ensure a more professional and user-friendly experience for developers and users alike.

Please consider fixing this inconsistency and adopting a unified naming convention for GVim.

Thank you for your attention to this matter.

**Comment by k-takata** [comment]
I think this was discussed before. I don't remember the decision clearly, though.
At least, this commit b477af2260d9bc7ae7f743f0a14265d7ee12ee09 changed them to gVim (or GVim if it is at the top of the sentence).

**Comment by YuliaImbert** [comment]
Opting for `GVim` can prioritize simplicity and straightforwardness. This choice not only makes it easier for everyone to use but also ensures a more consistent and cohesive approach.

**Comment by YuliaImbert** [comment]
I believe opting for `GVim` can prioritize simplicity and straightforwardness. This choice not only makes it easier for everyone to use but also ensures a more consistent and cohesive approach.

**Comment by tonymec** [comment]
I have always used `gvim` (in all lowercase) when meaning the command, i.e. the GUI version of Vim. `Vim`, meaning any version of Vim with or without GUI, is written with a capital, as mentioned under `:h pronounce`. To mean Vim, compiled with or without GUI but used in a console and not as a GUI, I usually write `Console Vim` because just `vim` (in lowercase) would IMHO not carry enough specificity compared to `gvim` (specifically GUI) and `Vim` (with or without GUI).

One particular case is in the `|client-server-name|`, where the default server name for Unix is `GVIM` in all caps (see `:h {server}`), though it is said a few paragraphs earlier that the servername's case is ignored, i.e., `gvim` and `GVIM` are considered equal.

**Comment by tonymec** [comment]
P.S. When writing `gvim` in all lowercase, I mean the GUI version of Vim **used as a GUI.**

Best regards,
Tony.

**Comment by chrisbra** [comment]
Let's just document current usage.
