### ISSUE TITLE
screen position wrong with smoothscroll + scrolloff + split + gk

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#13528]
### Steps to reproduce

Run vim with the following command in 80×30 terminal (or taller).
```
vim --clean -S <(tee << 'EOF'
    set wrap smoothscroll scrolloff=2
    new | wincmd j
    call setline(1, 'line1')
    call setline(2, 'line2')
    call setline(3, repeat('12345678', 10 * 10))
    call setline(4, 'line4')
    exe "normal! G4\<C-e>11gk"
    echo screenpos(0, line('.'), col('.'))
EOF
)
```

Result
![image](https://github.com/vim/vim/assets/19489738/4c4a1791-58f9-4c14-a245-200c987176ae)

Anomalies
* "line1" is not drawn.
* screenpos result is all zero.
* If you manually type `gk` 11 times instead of `11gk` in the script,
  * you will see that the first `gk` moves the cursor 3 screen lines above, and the second `gk` moves it 1 screen line below; and
  * after 11 `gk`s, the cursor is displayed on the statusline of the upper window

Note: nvim HEAD (9ecb43b63) has the same problem.

### Expected behaviour

* "line1" should be shown.
* screenpos should give some reasonable value.
* The cursor should be in the proper position after each `gk`.

### Version of Vim

9.0.2100

### Environment

* Ubuntu 23.04
* GNOME Terminal 3.48.0 using VTE 0.72.0 +BIDI +GNUTLS +ICU +SYSTEMD
* `$TERM`: xterm-256color
* bash

**Comment by luukvbaal** [comment]
The display issue regressed with https://github.com/vim/vim/commit/0222c2d103ad9298bec4dc8864cd80b4e7559db1. The `screenpos()` result in this repro regressed in https://github.com/vim/vim/commit/bfe377b8f2d080e5f85c8cbecf3533456e1d6312 but I guess that might resolve itself once the display issue is fixed.

**Comment by luukvbaal** [comment]
Interestingly, reverting the condition from https://github.com/vim/vim/commit/0222c2d103ad9298bec4dc8864cd80b4e7559db1 no longer breaks the adjusted tests. I guess skipcol is recalculated elsewhere now. But I think the proper fix for this issue is resetting skipcol in `scroll_cursor_top()` instead, I think it is always necessary under these conditions:

```diff
+++ b/src/move.c
@@ -2423,7 +2423,9 @@ scroll_cursor_top(int min_scroll, int always)
        }
        check_topfill(curwin, FALSE);
 #endif
-       if (curwin->w_topline == curwin->w_cursor.lnum)
+       if (curwin->w_topline != old_topline)
+           reset_skipcol();
+       else if (curwin->w_topline == curwin->w_cursor.lnum)
        {
            validate_virtcol();
            if (curwin->w_skipcol >= curwin->w_virtcol)
```

Will write a test for this later (and might try to verify why those tests no longer regress when reverting https://github.com/vim/vim/commit/0222c2d103ad9298bec4dc8864cd80b4e7559db1, for curiosity's sake).
