### ISSUE TITLE
build system forcing -D_FORTIFY_SOURCE=1

### ISSUE THREAD

**Issue by hyder365** [vim/vim#13541]
### Steps to reproduce

Add -D_FORTIFY_SOURCE=3 to local CFLAGS, compile vim

### Expected behaviour

vim --version would return that it was built with level 3 fortification

### Version of Vim

latest

### Environment

Arch Linux

**Comment by chrisbra** [comment]
Using anything other than `FORTIFY_SOURCE=1` is not supported by the vim codebase.

**Comment by chrisbra** [comment]
It's because of the way, Vim allocates memory, which typically triggers the overflow detection: 

https://github.com/vim/vim/blob/6ffe084e6e629adcf5915286daee78058f6dd4b6/src/structs.h#L1726

It has been discussed before, you may search the mailing list for this.

**Comment by dpelle** [comment]
> More distros are moving to level 3 by default for the security benefits. 
> If vim is somehow not compatible with that, isn't it a bug?

No, it's not a bug.
-D_FORTIFY_SOURCE=1 is guaranteed to work with valid C programs.
But -D_FORTIFY_SOURCE=2 or -D_FORTIFY_SOURCE=3 can break valid programs.

See:
http://gcc.gnu.org/ml/gcc-patches/2004-09/msg02055.html

=== BEGIN QUOTE ===
The intended use in glibc is that by default no protection is
done, when the above GCC 4.0+ and -D_FORTIFY_SOURCE=1 is used
at optimization level 1 and above, security measures that
shouldn't change behaviour of conforming programs are taken.
With -D_FORTIFY_SOURCE=2 some more checking is added, but
some conforming programs might fail.
=== END QUOTE ===

We could use Flexible Array Members introduced in C99 i.e.
foo[] instead of foo[1]. That would allow use -D_FORTIFY_SOURCE=3
I think. However, not all compilers could deal with flexible array
members and Vim should build fine even with old toolchains.

**Comment by moralground** [comment]
Any chance this can be revisited so vim gets the benefit of that flag?

**Comment by chrisbra** [comment]
not unless we do a major refactor of the source.
