### ISSUE TITLE
Linking not possible SINCE Patch 8.0.0048

### ISSUE THREAD

**Issue by sfx2k** [vim/vim#1355]
With Patch 8.0.0048 there where changes in os_win32.c

With these changes I am not longer able to link gvim on Windows 7 / VS2015:

> os_win32.obj : error LNK2001: unresolved external symbol _GetProcessId
gvim.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"' : return code '0x460'
Stop.

Any ideas?

**Comment by tonymec** [comment]
Before reporting this kind of bug, it is better to first make sure that one is using the latest source, currently 8.0.142, because otherwise the bug might have been fixed in a later patch.

See http://ftp.vim.org/pub/vim/patches/8.0/README for a one-line description of every 8.0 bugfix so far.
See http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial about how to get the latest sources
See http://users.skynet.be/antoine.mechelynck/vim/compile.htm about compiling Vim on Windows
Note that https://sourceforge.net/projects/cream/files/Vim/ includes a precompiled Vim for Windows. IIUC it is a 32-bit version that runs also (thanks to the WOW64 OS module) on 64-bit OSes. At the moment it is a 8.0.118, not the very latest bleeding-edge development code but still much more recent than your 8.0.48.

Best regards,
Tony.

**Comment by sfx2k** [comment]
Hey Tony,

thanks for your reply.

Unfortunately I forgot to mention, that I have also tested it with the latest source, of course!
I tested it with different versions to find out, which Patch causes this failure.

My tests included the following versions (in this order):

8.0.0142 -> nok
8.0.0001 -> ok
8.0.0100 -> nok
8.0.0050 -> nok
8.0.0030 -> ok
8.0.0040 -> ok
8.0.0045 -> ok
8.0.0047 -> ok
**8.0.0048 -> nok**

That means, that this issue exists in the last source. With my hint to Patch 8.0.0048 I just wanted to point out, which version causes the issue.

I edited the subject. 

Regards
Sascha

**Comment by tonymec** [comment]
Ah, thanks, that's better, so the problem still exists in the latest source and patch 8.0.48 is the culprit.

I might add that I have no problem compiling Vim on Linux64 (both Huge version with, among others, GTK3 GUI and Tiny version with no GUI). This is expected since os_win32.c is a Windows-only source file. But then, how come Steve Hall could compile a Windows 8.0.118 and post it on sourceforge? Is that symbol defined somewhere in the mingw gcc libraries?

**Comment by k-takata** [comment]
I can compile 8.0.0048 or later with VS2015 without this error.

Patch 8.0.0048 uses `GetProcessId` API. The symbol name is normally `_GetProcessId@4` instead of `_GetProcessId`. This means that the function declaration is not loaded properly.
Seeing the header files of VS2015, the API is only declared if `_WIN32_WINNT >= 0x0501`.
(See: `C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\processthreadsapi.h`)
If you change `WINVER` or `_WIN32_WINNT`, make sure that they are `>= 0x0501`.

**Comment by sfx2k** [comment]
Okay,

changing _set WINVER=0x500_ to _set WINVER=0x501_ does the trick :)

Thanks a lot k-takata (and Tony of course)!
