### ISSUE TITLE
no smart indent on tsx files

### ISSUE THREAD

**Issue by mrdomino** [vim/vim#13574]
### Steps to reproduce

```
vim -u DEFAULTS
:edit foo.tsx
i{<Esc>o
```

### Expected behaviour

The new line should be indented by one level.

N.B. adding a `indent/typescriptreact.vim` file with the following contents resolves the issue:

```vim
runtime! indent/typescript.vim
```

### Version of Vim

9.0.1897

### Environment

OS: macOS 14.0 Sonoma
Terminal: iTerm2 3.4.22
$TERM: xterm-256color
shell: zsh 5.9

**Comment by chrisbra** [comment]
How about a PR then?

Am 24. November 2023, um 20:23, schrieb Jōshin ***@***.***>:

Steps to reproduce

vim -u DEFAULTS :edit foo.tsx i{<Esc>o 

Expected behaviour

The new line should be indented by one level.

N.B. adding a indent/typescriptreact.vim file with the following contents resolves the issue:

runtime! indent/typescript.vim

Version of Vim

9.0.1897

Environment

OS: macOS 14.0 Sonoma
Terminal: iTerm2 3.4.22
$TERM: xterm-256color
shell: zsh 5.9

Logs and stack traces

No response

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/vim/vim/issues/13574">https://github.com/vim/vim/issues/13574</a>", "url": "<a href="https://github.com/vim/vim/issues/13574">https://github.com/vim/vim/issues/13574</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by mrdomino** [comment]
Submitted.
