### ISSUE TITLE
Since when '.' matches "\n" in a string?

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#13608]
### Steps to reproduce

Script:

    vim9script
    var lst = ['foo', 'abc', 'bar', 'foo', 'bar']
    var str = lst->join("\n")
    set magic
    echo &magic
    echo '------'
    echo str->matchstr('foo.*bar')
    echo '------'
    echo str->matchstr('foo.*\nbar')
    echo '------'
    echo str->matchstr('fo\_.*bar')

Result:

    true
    ------
    foo
    abc
    bar
    foo
    bar
    ------
    foo
    abc
    bar
    foo
    bar
    ------
    foo
    abc
    bar
    foo
    bar

All 3 patterns have the same result. 

Question is: why `.*` matches `\n` here?

### Expected behaviour

For  `echo str->matchstr('foo.*\nbar')` :

    foo
    bar

### Version of Vim

9.0.2136

### Environment

Windows 10 64-bit

**Comment by chrisbra** [comment]
I think this has always matched for expressions (meaning it doesn't for matching in a buffer, but with a string it does)

**Comment by alexaschee** [comment]
Thanks for your reply.

I did noticed pattern.txt says `.` matches `any character` under `3. Magic`, but still.

It would be much nicer to add `(even an end-of-line)` after `any character`.

**Comment by Nickwiz** [comment]
> But `\n` is not `end-of-line`

Only expanding ...

"*Not `end-of-line`*" must not be misread as "*Not end of line*", if you get my meaning.

When using string-matching (functions) matching is done more in line with ERE. I.e. 

>[A \<period\> ( '.' ), when used outside a bracket expression, is an ERE that shall match any character in the supported character set except NUL.](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04_04)

and the ***entire string*** is treated as a byte string ~ it has no idea of what a line is. That is not though, to say there are not *lines* in that string :P, but compared to buffer-matching it is as.

In a buffer window, given text below,  `/bc\nde` matches `bc<EOL>de` both for a UNIX and DOS file, even `bc$\nde` 
_(or `bc$\r\nde` for `++ff=unix` on  a DOS buffer, but that is a different cookie)._

```
abc
def
```

```
:h key-notation

<EOL>		end-of-line (can be <CR>, <NL> or <CR><NL>,
		depends on system and 'fileformat')	<EOL>
```

There are several references marking `\n` as `end-of-line`:

```
:h /character-classes

/\n	\n	\n	end-of-line
```


```
:h white-space

\n	matches an end-of-line				/\n
	When matching in a string instead of buffer text a literal newline
	character is matched.
```

^--  NB! **When matching in a string instead of buffer ...**

```
:h /magic

Examples:
after:	  \v	   \m	    \M	     \V		matches 
		'magic' 'nomagic'
	  $	   $	    $	     \$		end-of-line
```

---

### The big whoopsie though is that one have:

```
:h string-match

4. Matching a pattern in a String			string-match

This is common between several functions.  A regexp pattern as explained at
pattern is normally used to find a match in the buffer lines.  When a
pattern is used to find a match in a String, almost everything works in the
same way.  The difference is that a String is handled like it is one line.
When it contains a "\n" character, this is not seen as a line break for the
pattern.  It can be matched with a "\n" in the pattern, or with ".".  Example:

	:let a = "aaaa\nxxxx"
	:echo matchstr(a, "..\n..")
	aa
	xx
	:echo matchstr(a, "a.x")
	a
	x

Don't forget that "^" will only match at the first character of the String and
"$" at the last character of the string.  They don't match after or before a
"\n".

```

So when using *string-matching* neither of these will work:

```
foo$\nbar
foo\_$\nbar

" or for a dos string:
foo\nbar
```

`$` is end-of pattern and `\n` is just like any other character like a,b,c or 4,2 etc. The *magic touch* of `\n` as with buffers is gone. Or put another way: _it is completely oblivious to what a line is._

It also means that one have to take care of line endings oneself if the string is not from a buffer. If one use `getline(from, to)` one get a list and do not need to worry about it.


Further as the manual states under `:h match()`: 

> The matching is always done like 'magic' is set and 'cpoptions' is empty.

Hence `set magic` is a NOP.

---

If anything, I think the manual *could be* somewhat more eager to underline the importance of *`string-match`*.


---

Some other POSIX definitions that can be of interest:

UNIX:

* Line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
  * >A sequence of zero or more non- \<newline\> characters plus a terminating \<newline\> character.
* Empty-line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_145
  * >A line consisting of only a \<newline\>
* Character string: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_92
  * >A contiguous sequence of characters terminated by and including the first null byte.

**Comment by alexaschee** [comment]
@Nickwiz:  Thank you for your detailed explanation.

Seems doing jobs in buffers is much easier, after all.

**Comment by Nickwiz** [comment]
> Seems doing jobs in buffers is much easier, after all.

Depends on the case I guess. As long as one retrieve the data from VIM buffers it is OK. Else; If one know the file-format of the data it is the same, or even simpler. All depending on case. As long as one have clear definitions on *what a line is* etc.

For arbitrary data one have for example `readfile()` which convert `\r\n` to `\n` (in literal sense) unless binary mode is used. Hence UNIX and Windows files OK, Macintoch `<CR>` files a mess, but could be remedied by a post-check.
