### ISSUE TITLE
ColorScheme autocmd not fired when setting background with default colorscheme

### ISSUE THREAD

**Issue by tomtomjhj** [vim/vim#13610]
### Steps to reproduce

```
vim --clean
:au ColorScheme * unsilent echom [g:colors_name, &background]
:if &background ==# 'dark' | set background=light | else | set background=dark | endif
:mess
```

Output: nothing

### Expected behaviour

Should print `['default', 'dark']` or `['default', 'light']`. This works correctly for non-default colorschemes.

### Version of Vim

9.0.2143

### Environment

* Ubuntu 23.04
* GNOME Terminal 3.48.0 using VTE 0.72.0 +BIDI +GNUTLS +ICU +SYSTEMD
* `$TERM`: xterm-256color
* bash

**Comment by tomtomjhj** [comment]
Hmm ok. But is `:color default` considered "loading" the default colorscheme? This triggers autocmd. And is setting `bg` after that "reloading"? 

Either way, I think ensuring that it triggers the autocmd is quite useful for customizing the colorscheme.

**Comment by chrisbra** [comment]
The [default colorscheme](https://github.com/vim/vim/blob/master/runtime/colors/default.vim) is not a normal colorscheme. It just undoes, what ever any colorscheme my have had configured and then initializes all the default highlighting groups from the C-Code here:

https://github.com/vim/vim/blob/0d0b3b19517c321b089d637919e88e49a07a3d85/src/highlight.c#L382-L421

Since `g:colors_name` is not set, it won't load the colorscheme runtime file and therefore won't trigger the ColorScheme autocommand. 

I don't want to change this, as this could lead to subtle/unforseen bugs

**Comment by tomtomjhj** [comment]
Workaround
```
au OptionSet background if get(g:, 'colors_name', 'default') ==# 'default' | doautocmd <nomodeline> ColorScheme default | endif
```
