### ISSUE TITLE
Add support for #elifdef and #elifndef to c.vim

### ISSUE THREAD

**Issue by jwakely** [vim/vim#13667]
The new C2x and C++23 standards add new preprocessing conditionals, `#elifdef` and `#elifndef`

For C the proposal was:
https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2645.pdf

For C++ the proposal was:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2334r1.pdf

They've been supported by GCC for a couple of years:
https://gcc.gnu.org/gcc-12/changes.html#c

Vim does not recognize these and so doesn't syntax highlight them.

```c
#ifdef foo
#elifdef bar
#elifndef baz
#endif
```

**Comment by chrisbra** [comment]
can you create a PR to `runtime/syntax/c.vim` ?

**Comment by jwakely** [comment]
Done, but see my comment on #13679 about whether the PR is complete or not.

**Comment by cpplearner** [comment]
The matchit plugin also needs to recognize `#elifdef` and `#elifndef`.

https://github.com/vim/vim/blob/71d0ba07a33a750e9834cd42b7acc619043dedb1/runtime/pack/dist/opt/matchit/autoload/matchit.vim#L91-L92

The built-in `[#`, `]#` and `%` do not need any change, even though they deal with `#if`/`#else`/`#endif`, because they only look for `el` and do not care about subsequent characters.

**Comment by jwakely** [comment]
Marvellous, thank you!
