### ISSUE TITLE
Feature Request: Line numbers in hex

### ISSUE THREAD

**Issue by Type1J** [vim/vim#1368]
Please add an option such as ":set numberbase=16" to allow line number bases.

**Comment by vim-ml** [comment]
2017-01-09 18:39 GMT+03:00 Jay Sistar <vim-dev-github@256bit.org>:
> Please add an option such as ":set numberbase=16" to allow line number
> bases.

Use case?

**Comment by justinmk** [comment]
This is another case in favor of the 'numberexpr' (or 'numberfunc') option I alluded to in:

https://github.com/vim/vim/pull/680

**Comment by Zapeth** [comment]
I would also be in favor of a 'numberformat' option, not because of alignment or number base issues but because of the <space> delimiter offering not enough of a distinction between the line numbers and text sections for me.

I know, the line numbers section can be colored differently but I'd still prefer a more clear distinction, like this -> http://imgur.com/a/IfsGK

**Comment by chrisbra** [comment]
this seems to be a bit niche, so closing as unplanned

**Comment by Type1J** [comment]
That's unforunate. I guess I'll just make an editor that can.

**Comment by justinmk** [comment]
@Type1J Neovim already supports this via https://neovim.io/doc/user/options.html#'statuscolumn'

**Comment by dkaszews** [comment]
> @Type1J Neovim already supports this via https://neovim.io/doc/user/options.html#'statuscolumn'
 
`set stc=%C%s%{printf('0x%X\ ',v:num)}` works great for me, looks the same as default except for hex line numbers. 

My usecase is that I am currently working on firmware with limited debug capabilities, where traces are just CRC16 of filename, line number and a single user value, all in hex. This makes it way faster to see which line the trace came from.
