### ISSUE TITLE
E340 & E315 by bufhidden=wipe and autocmd diffsplit

### ISSUE THREAD

**Issue by kawarimidoll** [vim/vim#13839]
### Steps to reproduce

I got E340 and E315 when I run the commands below (file names are not important):

```vim
edit a.txt
edit b.txt
setlocal bufhidden=wipe
autocmd BufLeave * diffsplit c.txt
bnext
quit
```

here is demo:

https://github.com/vim/vim/assets/8146876/41296bda-29dd-4e41-a9e5-a9518947f26e

when run `:bnext`, these two conflicting things seem to occur:

1. `bufhidden=wipe` wipes `b.txt`
1. `autocmd BufLeave * diffsplit c.txt` opens `c.txt` with keeping `b.txt` open

then buffers are mismatch and a strange buffer is displayed (you can see it at end of demo).

### Expected behaviour

handle these errors

### Version of Vim

Vim 9.1.0 (Compiled by Homebrew)

### Environment

OS: macOS Sonoma 14.2.1
Terminal: wezterm 20230712-072601-f4abf8fd
value of $TERM: xterm-256color
Shell: zsh 5.9 (arm-apple-darwin21.3.0)

### Logs and stack traces

```shell
E340: Internal error; if you can reproduce please report a bug
Press ENTER or type command to continue
E315: ml_get: Invalid lnum: 1
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
That is nasty. I am not sure why it doesn't crash for you, for me it crashes with a use-after-free for the buffer `b.txt`. Basically Vim doesn't expect that a another window is opened which contains a reference to the immediately later freed buffer `b.txt`. But since this is not the `curwin` it doesn't notice it when checking the side-effects of the BufLeave autocommand. 

I haven't yet figured out a way to prevent this.
