### ISSUE TITLE
wrap arglist

### ISSUE THREAD

**Issue by marcotrosi** [vim/vim#13866]
# Problem:
the `:next` `:Next` `:previous` `:Previous` commands do not wrap around the `arglist`, means when reaching the end they don't start from the opposite end.

# Wish:
would be great to get that wrapping without trickery

# Solutions:
either - an option to change the behaviour of these commands
or - as `:Next` is the same as `:previous` we could change `:Next` and `:Previous` to go into the intuitive direction (same as `:next` and `:previous`) but with wrapping

# Alternatives:
I know there are solutions like shown here https://github.com/vim/vim/issues/5451 but it's seems to have some drawbacks, and I would prefer a normal and logical built-in solution without trickery.

**Comment by chrisbra** [comment]
That is an interesting problem. POSIX requires a `:next` command, but apparently neither a `:Next` nor a `:previous` command. However, POSIX requires:

> It shall be an error if there are no more filenames in the argument list after the filename currently referenced.

So we cannot change it. 

There is currently no `:Previous` command, but we cannot create one, because capitalized commands should not exist (except for Next and Print , and I think those were errors to be introduced at all) and would hide a user command (since those should start with a capital letter). 

So I am tending to not touch it and leave it for the user to create similar user commands instead.

**Comment by marcotrosi** [comment]
Thank you for your feedback @chrisbra , I think then we can close the issue.
