### ISSUE TITLE
C syntax highlighting breaks vim

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#1389]
Hi,

when I recently opened .c file, C syntax highlighting does not work and vim's command line does not work properly (when I try to scroll, it only adds numbers to command line with actual scrolling, or if I enter :q! , it appends it to the end of CL, and after 'Enter' it closes VIM but file contents are still visible in terminal). Would you mind fixing this issue? I will look into which patchlevel caused it.

**Comment by kafeltz** [comment]
I guess there would be a million users complaining about this issue.
vim + c = broken? = world world war 3.

**Comment by zdohnal** [comment]
Yes, you are right, config issue.

**Comment by vim-ml** [comment]
On 2017-01-17, zdohnal wrote:
> Hi,
> 
> when I recently opened .c file, C syntax highlighting does not work and vim's
> command line does not work properly (when I try to scroll, it only adds numbers
> to command line with actual scrolling, or if I enter :q! , it appends it to the
> end of CL, and after 'Enter' it closes VIM but file contents are still visible
> in terminal). Would you mind fixing this issue? I will look into which
> patchlevel caused it.

As Ismael wrote, if this was a common problem, we would have heard
about it from many people long before now.  That we haven't suggests
that the problem is unique to your environment.  That doesn't mean
that it's not due to a bug in Vim, but it does mean that we will
need more information about the specifics of the problem you're
observing and the conditions under which it occurs.

To me, the most telling symptom is that the file contents are still
visible on the terminal screen after you've quit vim.  That suggests
that the terminal isn't responding to the t_ti and t_te escape
sequences.  That could be because vim doesn't know from the terminfo
or termcap database which sequences to use for t_ti and t_te, or
that it has the wrong sequences for the terminal you are actually
using.  It could also mean that the terminal you're using doesn't
support the alternate screen.

What does the following show?

    :verbose set term? t_ti? t_te?
 
As an example, in the vim instance I'm using for this reply, I see
this:

    term=screen
    t_ti=^[[?1049h
    t_te=^[[?1049l

See also:

    :help xterm-screens
    :help raw-terminal-mode
    :help 'restorescreen'

I suspect that the other symptoms stem from the same cause:  that
vim thinks it's using a terminal type different from the one it's
actually using.

Regards,
Gary

**Comment by zdohnal** [comment]
Thanks Gary for your help. When I removed plugin folder from .vim, it started to work. It seems I forgot to lock my PC and colleague installed some funny plugin, which breaks C syntax highlighting (clang-complete). I will be more cautious next time.
