### ISSUE TITLE
Fix for CVE-2023-45921 ?

### ISSUE THREAD

**Issue by TheStoryEnd** [vim/vim#13930]
### Steps to reproduce

Summary
https://yanac.hu/2024/01/26/cve-2023-45921-vim-9-0-file-handle_viminfo_register-null-pointer-dereference/

A vulnerability classified as problematic has been found in vim 9.0. Affected is the function handle_viminfo_register of the component File Handler. The manipulation leads to null pointer dereference

Is there a fix for cve-2023-45921 ?
[1] If not, what is the repair plan for vim9.0?
[2] If yes, can you indicate which submissions fix cve-2023-45921 ?

Details
No further information at this time(2024/1/29)

PoC
No further information at this time(2024/1/29)

Impact
https://yanac.hu/2024/01/26/cve-2023-45921-vim-9-0-file-handle_viminfo_register-null-pointer-dereference/

This vulnerability is traded as CVE-2023-45921. It is possible to launch the attack remotely. There is no exploit available.

### Expected behaviour

CVE fix solution or further information

### Version of Vim

vim9.0.0000

### Environment

NA

**Comment by chrisbra** [comment]
Vim 9.0 has been released in June 2022. We do not provide fixes for previous released versions. 

This particular problem has been fixed as patch (v9.0.1740)[https://github.com/vim/vim/releases/tag/v9.0.1740].

Note: I do not think this is worth a CVE. It is unclear why a CVE was assigned and who applied for it. This particular CVE is currently reserved. Once it is published, I'll plan to dispute it, because: if an attacker can modify and invalidate your .viminfo file, you have more serious problems than the mentioned crash.
