### ISSUE TITLE
default.vim that replaced rgb.txt unexpectedly requires lowercase colour names

### ISSUE THREAD

**Issue by lessthanideal** [vim/vim#13976]
### Steps to reproduce

Summary: With earlier versions of vim, colours defined in rgb.txt then used in custom colour schemes allowed uppercase letters in names.  The replacement for rgb.txt, ..\colors\list\default.vim, only works with lowercase names (although if you give the names in lowercase, they can then be mixed case as before in the custom colour scheme file).  

This isn't clear from the comments in that file, or from the error message you get when you try to define colours like this. 
 This is likely to happen upgrading from vim 8 to 9 and just copying your colour names across into the new file.  I think it is a bug since functionality has unexpectedly changed or been lost since version 8.

This is running vim 9.1 on Windows 10.

The nicest fix would be to accept the same mixed case names as before; failing that, to update the relevant help, and comments in default.vim

To reproduce:

Create a file such as \vimfiles\colors\lists\default.vim including a line defining a custom colour such as 

call extend(v:colornames, {'bobblue': '#0060ff'}, 'keep')

Ensure this colour can be used, e.g. in the standard way create a custom colour scheme file in \vimfiles\colors\test.vim including a line 

hi PreProc guifg=BobBlue

And source it in the standard way from the VIMRC file

colorscheme test

then verify this works, e.g. open \vim91\vimrc_example.vim, you don't get any errors starting gvim and you see this custom blue colour is used for the word Maintainer in the line near the top, '" Maintainer:	The Vim Project <https://github.com/vim/vim>'

Now edit the colour name in your default.vim to be BobBlue, 

call extend(v:colornames, {'BobBlue': '#0060ff'}, 'keep')

open the same file in gvim and you get this error

Error detected while processing D:\Vim\_vimrc[227]..D:\Vim\vimfiles\colors
\test.vim:
line   18:
E254: Cannot allocate colour BobBlue

### Expected behaviour

It should accept a defined colour name as BobBlue in \vimfiles\colors\lists\default.vim and use it correctly when referred to in a colour scheme file \vimfiles\colors\test.vim as BobBlue

I don't know and can't verify if the colour names were case-sensitive or case-insensitive using rgb.txt, so I don't know if a defined colour name of bobblue should work here or not.  

Ideally, the case sensitivity should match the previous version.

### Version of Vim

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan  3 2024 00:15:11) MS-Windows 32-bit GUI version with OLE support

### Environment

Windows 10 Pro 64-bit

**Comment by chrisbra** [comment]
Hm, that comes from commit e30d10253fa634c4f60daa798d029245f4eed393, patch [v8.2.3562](https://github.com/vim/vim/releases/tag/v8.2.3562).

There is the following comment:
https://github.com/vim/vim/blob/de7f5bde6c598d4da4ce5b30328eb458962ba60a/src/highlight.c#L2377-L2380

Perhaps it's enough to simply mention, that the color names should be lower-case in the `v:colornames` dictionary?

**Comment by RestorerZ** [comment]
@chrisbra ,

If `$VIMRUNTIME/colors/lists/default.vim` was supposed to be a replacement for "`rgb.txt`", then I guess it was supposed to match the color naming convention adopted in "`rgb.txt`"? And "`rgb.txt`" adopts CamelCase-like color naming convention.
For example:
 
>47 79 79 79 dark slate gray
>47 79 79 79 DarkSlateGray
>47 79 79 79 dark slate gray
>47 79 79 79 DarkSlateGrey
 
In addition, most of the examples in the documentation are also given in CamelCase similar naming.
For example:

>These extra colors are also available:
>
>Gray, Grey, LightYellow, SeaGreen, Orange, Purple, SlateBlue, Violet,
>
>\*rgb.txt\*
>Additionally, colors defined by a default color list can be used.  For more
>info see |:colorscheme|.  These colors used to be defined in
>$VIMRUNTIME/rgb.txt, now they are in |v:colornames| which is initialized from
>$VIMRUNTIME/colors/lists/default.vim.

Or in the same `$VIMRUNTIME/colors/README.txt`:
>" load the "evening" colorscheme
>runtime colors/evening.vim
>" change the color of statements
>hi Statement ctermfg=Blue guifg=Blue

Since the color schemes distributed with Vim universally use lower case color naming, no one will probably redo them, as well as `$VIMRUNTIME/colors/lists/default.vim`.

It turns out that the only acceptable variant is to specify in the documentation that now color naming is only in lower case and, accordingly, change all the examples available in the documentation and other files to comply with this instruction.

**Comment by chrisbra** [comment]
This is not the problem. Vim will internally lower case the color name before looking it up from the `v:colornames` variable. However, if you use upper case color names, they won't be found. So it doesn't change the fact, that you can use lower/upper or camel case color names, but in order to have them found, the `v:colornames` Dictionary needs to define all keys in lower case.
