### ISSUE TITLE
Mouse scroll wheel not responsive (gvim)

### ISSUE THREAD

**Issue by ronaaron** [vim/vim#13987]
### Steps to reproduce

Load gvim with any  file (e.g. a C source file of vim).
Use the mouse wheel to scroll.
Notice that scrolling stutters and/or doesn't happen for a while. When it does, it seems to "miss" scroll events.

### Expected behaviour

Previously, the mouse wheel scrolling was smooth and consistent. 

Note: on every other application on the same system (browsers, etc) the mouse wheel scrolls perfectly well. So it's neither a mouse hardware issue nor an OS specific problem.

### Version of Vim

9.1.80

### Environment

Mint 21.3, Cinnamon

**Comment by errael** [comment]
Thank you for posting this; I've noticed this intermittently starting over the last week or two. I've been wondering if it was due to a change in vim or something that changed recently on my linux/ubuntu/system76 system (which I upgrade regularly). With this issue, it now seems more likely it is gvim.

As a workaround, if I do `"*Y` to copy anything to the primary clipboard the scroll wheel starts to work properly.

**Comment by ronaaron** [comment]
Same. Oh, that's a *weird* workaround! I'll have to try it... OK, yes indeed that does work. Very weird!

**Comment by chrisbra** [comment]
Hi,
can you bisect the offending commit? Could it be the Wayland commit [v9.1.0064](https://github.com/vim/vim/releases/tag/v9.1.0064)?

**Comment by ronaaron** [comment]
Indeed

~~~
6e0a18f82bd04a45e9682523c42af9cbbc37684c is the first bad commit
commit 6e0a18f82bd04a45e9682523c42af9cbbc37684c
Author: lilydjwg <lilydjwg@gmail.com>
Date:   Mon Jan 29 20:54:28 2024 +0100

    patch 9.1.0064: No Wayland support
~~~

**Comment by chrisbra** [comment]
ping @lilydjwg

**Comment by lilydjwg** [comment]
I'm sorry about this. A patch has been sent.
