### ISSUE TITLE
If cursor on U+2500 normal "p" command behaves like "P" for visualblock-material

### ISSUE THREAD

**Issue by luchr** [vim/vim#1403]
I get the following effect in vim, gtk2vim and gtk3vim (Version 8.0.206):

1. Start `vim -u NONE -U NONE`
2. Go to Insert-Mode and insert U+2500 and leave Insert-Mode, i.e. type: `i<C-V>u2500<ESC>`
3. Start **Visual-Blockmode** and yank this one character, i.e. type: `<C-V>y`
4. Use the normal command `p`, i.e. type: `pppp`

What I get: the cursor stays at column 1 (character is inserted, but cursor does not move).

Expected: the cursor moves to the position of the last inserted character.

If you do the test above with U+2501 (instead of U+2500) then everything works as expected. Only a few codepoints show this unexpected behaviour, like U+2500, U+2600, etc.

**Comment by tonymec** [comment]
I confirm this behaviour, as follows:
- Happens for every codepoint I tested whose hex representation ends in 00, including U+0100, U+10000, etc., regardless of CJK narrow/wide status of the character in question (e.g. ⼀ U+4E00 "CJK number one" exhibits the behaviour, 丁 U+4E01 "CJK calendar sign 4" doesn't)
- Does not happen for other characters AFAICT
- Happens if yanked blockwise by Ctrl-V y but not characterwise by yl
- When yanking several consecutive characters on a single line in block mode, happens only if the last (rightmost) one is a multiple of 0x100 AFAICT
- The results of my experiments are not clear to me in multiline blockwise yanking.

Tested in gvim 8.0.211 (Huge) with GTK3 GUI.

**Comment by luchr** [comment]
I found the reason: `ops.c` in function `do_put` wrong datatype for result of `gchar_cursor` (defined in `misc1.c` is returning an `int`). Casting this `int` to an `char` is killing a lot of informations ...

I suggest the following change:

```
diff --git a/src/ops.c b/src/ops.c
index 0853fd0..7f02ab7 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -3550,7 +3550,7 @@ do_put(
      */
     if (y_type == MBLOCK)
     {
-       char    c = gchar_cursor();
+       int     c = gchar_cursor();
        colnr_T endcol2 = 0;
 
        if (dir == FORWARD && c != NUL)
```
