### ISSUE TITLE
Pasting from clipboard turns newlines into ^M (ctrl-m)

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#1404]
Hi,
I am using the latest Vim on macOS in both Terminal.app and iTerm2. With bracketed paste enabled (the default),  whenever I paste something from the clipboard,  I get `^M` (ctrl-m) instead of new lines. For example, this text:

```
for i in 12..buffer.len() {
    let prediction = coefficients.iter()
```

is pasted as follows:

```
for i in 12..buffer.len() {^M    let prediction = coefficients.iter()
```

With bracketed paste disabled, the behaviour is as in older Vim. I have `fileformat` set to `unix`, but other values do not make a difference.Using the same terminals, pasting in NeoVim (which also supports bracketed paste), produces the expected output, so I'd rule out terminal configuration problems.

**Comment by lifepillar** [comment]
I should add that `nocompatible` must be set. In other words, in `vim -u NONE` bracketed paste works fine, but in `vim -u NONE -N` I have the issue mentioned above.

**Comment by lifepillar** [comment]
Actually, it's messier than that. Execute `vim -u NONE` and paste the text above twice. You will get:

```
 in 12..buffer.len() {
    let prediction = coefficients.iter()
 in 12..buffer.len() {^M    let prediction = coefficients.iter()^M
```

and undo will be screwed up. There must be something to be ironed out in this new feature, I guess.

**Comment by brammool** [comment]
Lifepillar wrote:

> Actually, it's messier than that. Execute `vim -u NONE` and paste the
> text above twice. You will get:
> 
> ```
>  in 12..buffer.len() {
>     let prediction = coefficients.iter()
>  in 12..buffer.len() {^M    let prediction = coefficients.iter()^M
> ```
> 
> and undo will be screwed up. There must be something to be ironed out
> in this new feature, I guess.

Where do you paste from?  How do you get the text into the clipboard?
Also, how exactly do you paste?  The Mac doesn't have a middle button,
right?

-- 
"Shoot for the moon. Even if you miss, you'll land among the stars."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by olegTarassov** [comment]
Hello,

On Fedora 25 using vim 8.0.211, have the same issue where when pasting from either clipboard( copy from vim paste back into vim) or (copy from gedit and paste into vim will result in the following:
` some text then at new line ^M-`
I managed to get the paste working using the following "hack"
go into insert mode
ctrl+v
shift+insert
would result in the following:
`^[[200 then some text and newline are placed without the ^M `

For now I am downgrading to earlier version as the issue is not there.

**Comment by jun06t** [comment]
I've met the same problem after version 8.0.0211 on OSX.
As @arcadian09 says, i also downgraded to version 8.0.0208.
(because homebrew stores 8.0.0222, 8.0.0211, 8.0.0208 etc...)
This version works well.

**Comment by nuko8** [comment]
@brammool 

I guess that, instead of clicking the middle button, both @lifepillar and @jun06t pressed <kbd>command-v</kbd> in insert mode in order to paste something onto Vim from the clipboard, as <kbd>command-v</kbd> of OS X usually plays the same role as <kbd>ctrl-v</kbd> does on other platforms.

In fact, I was able to reproduce the result of @lifepillar's report that way. 

(As for the third post of @lifepillar, it looks to me that he did it in normal mode instead of insert mode for some reason. So I won't go into that further here.)

To look into the issue, I did the following small test on both iTerm.app and Terminal.app to see how these terminals respond to <kbd>command-v</kbd> in raw mode.

----

1. Select the string of the @lifepillar's example:
```
for i in 12..buffer.len() {
    let prediction = coefficients.iter()
```
and copy it into the clipboard with <kbd>command-c</kbd>.

2. On one of the terminals mentioned above, do
```
$ stty raw
$ cat -v
```

3. Press <kbd>command-v</kbd> there to paste the string onto the terminal.

----

After that, the following string, which is the same string that @lifepillar reported about Vim, appeared on the terminal:
```
for i in 12..buffer.len() {^M    let prediction = coefficients.iter()
```
Both of the terminals gave me the same result.

(To restore the state of the terminal to normal, press <kbd>ctrl-d</kbd> a few times until the shell prompt comes back, then type `stty sane`<kbd>ctrl-j</kbd> on the prompt.)

FYI, a slightly modified Step 2:
```
$ stty raw
$ printf "\e[?2004h"
$ cat -v
```
gave me
```
^[[200~for i in 12..buffer.len() {^M    let prediction = coefficients.iter()^[[201~
```
as expected.

So, it looks to me that Vim follows what the terminals do in raw mode faithfully.

**Comment by lifepillar** [comment]
@brammool As others have said, I copy/paste with cmd-c/cmd-v. I have tried different sources, like the text from this web page.

@nuko Re my third post: no, when I paste I am already in Insert mode (pasting causing Vim to switch to Normal mode, though), so please try to reproduce also that part.

**Comment by lifepillar** [comment]
@nuko …and note that my third post refers to Vim run in compatible mode (without `-N`).

**Comment by dkarter** [comment]
I can confirm running vim v8.0.0222 in tmux, which is in iTerm v3.0.13 (macOS Sierra v10.12.3).

You can reproduce the error by copying text from a pdf.

I was able to fix the problem temporarily by adding this to my vimrc:

```viml
set t_BE=0
```

**Comment by chrisbra** [comment]
you should use `:set t_BE=`

**Comment by littleylv** [comment]
Same problem with ``^M``.
Also got the problem with ``PasteStart``.

@chrisbra I add ``set t_BE=`` to .vimrc and that works.

**Comment by lifepillar** [comment]
Patch 230 fixes the new line problem, but I'd ask you again to take a look at pasting in compatible mode. That still doesn't work properly for me.

**Comment by brammool** [comment]
In compatible mode you have to make sure 'esckeys' is set.
Perhaps we should not enable bracketed paste when it isn't set.

**Comment by artyommironov** [comment]
@brammool  I'm still experiencing same issue in Vim 8.1.1027 when pasting from WebKit based web browsers on Linux, should I open new issue? Pasting to GUI apps like gtkedit, scite, LibreOffice Writer works as expected.

**Comment by hustcer** [comment]
> @brammool I'm still experiencing same issue in Vim 8.1.1027 when pasting from WebKit based web browsers on Linux, should I open new issue? Pasting to GUI apps like gtkedit, scite, LibreOffice Writer works as expected.

Same here , and my vim is: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 02 2021 02:58:09)` , have you found a workaround? @artyommironov

**Comment by lacygoill** [comment]
I suggest you open a new issue with a maximum of information, following the provided template.  In particular, the Vim version (including the exact patch level), the OS, the name of the terminal (and possibly its version), as well as a minimal example reproducing the issue.

If you use a terminal multiplexer, don't forget to provide its name and version.

**Comment by artyommironov** [comment]
@hustcer I was using vimb and vim at that time but hadn't found a workaround. As alternative, you might be interested in qutebrowser, it has vim-bindings and is not WebKit-based, so likely it doesn't have the issue.

**Comment by hustcer** [comment]
> @hustcer I was using vimb and vim at that time but hadn't found a workaround. As alternative, you might be interested in qutebrowser, it has vim-bindings and is not WebKit-based, so likely it doesn't have the issue.

Thanks, I will try it later.

**Comment by hustcer** [comment]
> I suggest you open a new issue with a maximum of information, following the provided template. In particular, the Vim version (including the exact patch level), the OS, the name of the terminal (and possibly its version), as well as a minimal example reproducing the issue.
> 
> If you use a terminal multiplexer, don't forget to provide its name and version.

It works well in native mode, but fails in the browser, especially when pasting large text. Maybe I will create an issue later.
