### ISSUE TITLE
visual mode is nearly invisible

### ISSUE THREAD

**Issue by girst** [vim/vim#14051]
### Steps to reproduce

1. use colorscheme from vim/colorschemes/legacy_colors/slate.vim
2. use any visual mode

### Expected behaviour

previously, vim reversed foreground and background when in visual mode. now, it just sets the foreground color to gray

old working behaviour:
![image](https://github.com/vim/vim/assets/11820748/3c4f4d10-e282-4e47-9c59-5c31d412d3bd)

new broken behaviour:
![image](https://github.com/vim/vim/assets/11820748/885b6eae-04b6-4edf-9931-fd6a3c4a16ed)

comparing `:hi Visual` between good and broken:

```diff
-Visual         xxx term=reverse cterm=reverse ctermbg=242 guifg=khaki guibg=olivedrab
+Visual         xxx cterm=reverse ctermfg=0 ctermbg=248 guifg=khaki guibg=olivedrab
```

I believe this regression was introduced between 9.1.031 and 9.1.076 and I think I found the relevant changes:

* https://github.com/vim/vim/commit/e6d8b4662ddf9356da53f56e363b67b524fd8825
* https://github.com/vim/vim/commit/59bafc8171b08cf326ed40ccb4ee917f9643290e

### Version of Vim

9.1.0113

### Environment

OS: Fedora 38
Terminal Gnome Terminal
$TERM: xterm-256color
shell: zsh-5.9-8.fc38.x86_64

**Comment by habamax** [comment]
We can of course fix legacy slate, but that will make it non-legacy and we already have non-legacy slate.

**Comment by chrisbra** [comment]
reversing foreground and background has caused bad visibility for certain people and filetypes, which was the reason for the whole change. You can reset your Visual highlighting by using a colorscheme highlight and then changing the visual highlighting again.

**Comment by nuclight** [comment]
After upgrading 9.0.1968 -> 9.1.0984 highlighting of **my custom colorscheme** was broken. I had in it:
```
Visual                                      cterm=reverse   guifg=#404040   guibg=DarkGrey  gui=bold
```
The problem here is that new changed defaults _override_ my settings! So it basically causes unreadable text, and worse, loses code syntax highlighting inside selection. You say that colorscheme highlight can - well, that's my own colorscheme and it don't work. The "bad visibility for certain people and filetypes" could be changed for those people, NOT the defaults for all. If Bram would alive, he wouldn't have allowed such breaking changes.

Also this version works badly with xterm i.e. renders localized help in arbitrary places of screen

![Image](https://github.com/user-attachments/assets/ab90f894-6ecc-4076-970b-b5c5ebddb447)

![Image](https://github.com/user-attachments/assets/028132a2-95ac-4bec-a1b6-32cf194462b8)
so I'll compile some older version until this bug is fixed.

**Comment by habamax** [comment]
Change your visual highlight in your custom colorscheme to include ctermfg=NONE


And please avoid attacks like “if Bram was alive he would have not…” 100s if not more people try to make vim better figuring out the balance of legacy and improvement. And while I get your frustration, let us be more problem-solving oriented.

**Comment by egberts** [comment]
`ctermcfg=NONE` isn't cutting it.

Using `lunaperche` scheme and `background=dark`.

`vim 9.1 (2024 Jan 02, compiled Feb 15 2025 09:59:04)`

**Comment by egberts** [comment]
Looks like Debian took away the `/etc/terminfo/x/xterm-truecolor`.

**Comment by egberts** [comment]
`xterm-direct`, is that the new normal?  It now works for my [vim-nftables](egberts/vim-nftables).  

But left me all-seeing dark-blueish for BASH shell file edit session.

**Comment by egberts** [comment]
## WORKAROUND ##

1. Stop using `export TERM=xterm-truecolor` (Debian 12 removed it); instead use `export TERM=xterm-direct`.

2. Start adding `set termguicolors` into your `~/.vimrc`.  (Ya think we could make that the default?) BEFORE the `colorscheme` statement.

**Comment by nuclight** [comment]
@habamax 
> And please avoid attacks like “if Bram was alive he would have not…” 100s if not more people try to make vim better figuring out the balance of legacy and improvement. And while I get your frustration, let us be more problem-solving oriented.

Problem is that defaults are NOT legacy - these are known to be good for *majority* of users. Bram had age and thus experience to understand this and more (e.g. POLA principle), in contrast to too young hipsters & zoomers. If some people have problem - then change settings for that minority - but don't break things for most others! Especially when change is in the C code which cannot be easily fixed in configs by most users in general case.

Also, as it is seen in mentioned issue [#16640](https://github.com/vim/vim/issues/16640), the justification is ridiculous - readability with new defaults became worse, not better!

Thus this ticket must be reopened and changes in the C be backed - move them to colorschemes for those "some people". BTW, who are those "some people"? Any bugs linked?

**Comment by chrisbra** [comment]
> Also, as it is seen in mentioned issue https://github.com/vim/vim/issues/16640, the justification is ridiculous - readability with new defaults became worse, not better!

Have you looked into your screen shot? The syntax highlighting changes the contrast of those green highlighted words. May be you did not notice, but I find this barely readable.

**Comment by nuclight** [comment]
On my monitor it is readable - not the best, but definitely better than on new defaults. Same for screenshot in this ticket. It is many years well established convention, on many platforms in many products, that selecting text changes it background for better visibility. New defaults break this.

**Comment by habamax** [comment]
> Problem is that defaults are NOT legacy - these are known to be good for _majority_ of users. Bram had age and thus experience to understand this and more (e.g. POLA principle), in contrast to too young hipsters & zoomers. 

What are you talking about? There are tons of people "having age and thus experience" here. Don't be rude.

> If some people have problem - then change settings for that minority - but don't break things for most others!

We try not to break things here, but this might happen if justified. Minority vs most others -- can you estimate, how many default vims out there vs how many vims using colorschemes with Visual not defining `ctermfg` and using `cterm=reverse`?

> Especially when change is in the C code which cannot be easily fixed in configs by most users in general case.

This change can be easily fixed outside of C code with a colorscheme or a simple `:highlight Visual ctermfg=NONE cterm=reverse` command in one's vimrc if they don't use colorschemes.

**Comment by nuclight** [comment]
> What are you talking about? There are tons of people "having age and thus experience" here. Don't be rude.

From the consequences of breaking things we can draw conclusion they are (in discussed are) are not. This is not "rude", objective fact can't be "rude".

> Minority vs most others -- can you estimate, how many default vims out there vs how many vims using colorschemes with Visual not defining ctermfg and using cterm=reverse?

Of course majority, as most vims are using default scheme, and e.g. mine settings were based on default scheme (just some tweaks). For the other side, where are those people for whom "it was unreadable" ? Are they in one room with us? As it is seen from starting screenshot, new defaults are clearly less readable than before.

> This change can be easily fixed outside of C code with a colorscheme or a simple :highlight Visual ctermfg=NONE cterm=reverse command in one's vimrc

For this particular change, may be. But as a symptom of general tendency, it's not. Were there at least published changes in some Release Notes, for example, like "defaults XXX was changed, you can restore old by adding YYY to vimrc" ?

**Comment by chrisbra** [comment]
Like it or not, your tone comes over as being rude. And such a tone does not make a convincing argument for your case...

Regarding the color scheme improvements, you may want to listen to the people that try to improve the default color schemes, since there were many inconsistencies, visual was being one of it (especially the low contrast with some syntax highlighting in combination with some terminals). Note Maxim is one of those people.

**Comment by nuclight** [comment]
> since there were many inconsistencies, visual was being one of it (especially the low contrast with some syntax highlighting in combination with some terminals).

Regarding arguments, it is *you* still don't giving any proofs. I *have the right* for whatever tone it be because you don't accept *real* arguments/facts - in court, judge don't care about "i don't like your tone" because it is not real argument. Show us real evidence - at least, ticket no#, number of people expecting such "problems", why it has gone unnoticed for decades, etc. Until that, it seems that just few with anecdotal experience became usurpators for majority, so this is a serious blame to them.

**Comment by chrisbra** [comment]
> in court, judge don't care about "i don't like your tone" because it is not real argument. 

You quite obviously not been to court. You are lucky.

> Show us real evidence 

You made it so far and even found the Vim issue tracker. You can find many of those discussions here or over in vim/colorschemes.
Here is one, that motivated that change: https://github.com/vim/colorschemes/issues/250 There are others, check the issue tracker.
