### ISSUE TITLE
Vim won't recognize custom colorschemes

### ISSUE THREAD

**Issue by ghost** [vim/vim#14151]
### Steps to reproduce

1. Make a colorscheme file
2. Put it in the same folder as other colorschemes

### Expected behaviour

At one time, I was able to have vim recognize a color scheme I made by just putting this code in the file and putting the file in :/usr/local/share/vim/vim90/colors/horror.vim with the other color schemes that comes with a vim installation:

let g:colors_name = 'colorscheme-name'

But now, this doesn't work. I've noticed this didn't work for GUI vim in general, but there was a time when putting 'colorscheme <name>' in your .vimrc worked like it did the same as it does for the ones that come with the installation when you use the standard terminal version of this software. I would think it would also be displayed when you enter :colorscheme[space][ctrl+d]

### Version of Vim

9.1

### Environment

Ubuntu Studio
Konsole

### Logs and stack traces

```shell
Error detected while processing /home/<username>/.vimrc:
line  136:
E185: Cannot find color scheme '<name>'
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
It seems `/usr/local/share/vim/vim90/colors/horror.vim` is not in your runtime path. Place it instead into `~/.vim/colors/` and it should work.

**Comment by ShinyNeonCalvin** [comment]
> It seems `/usr/local/share/vim/vim90/colors/horror.vim` is not in your runtime path. Place it instead into `~/.vim/colors/` and it should work.

yeah that worked, case closed and thank you sir

**Comment by vim-ml** [comment]
On 2024-03-06, ShinyNeonCalvin wrote:
> Steps to reproduce
> 
>  1. Make a colorscheme file
>  2. Put it in the same folder as other colorschemes
> 
> Expected behaviour
> 
> At one time, I was able to have vim recognize a color scheme I made by just
> putting this code in the file and putting the file in :/usr/local/share/vim/
> vim90/colors/horror.vim with the other color scheme that come with a vim
> installation:
> 
> let g:colors_name = 'colorscheme-name'
> 
> But now, this doesn't work. I've noticed this didn't work for GUI vim in
> general, but there was a time when putting 'colorscheme ' worked like it did
> the same as it does for the ones that come with the installation when you use
> the standard terminal version of this software.
> 
> Version of Vim
> 
> 9.1

Since you're running 9.1, Vim is going to look for colorschemes in
/usr/local/share/vim/vim91/colors rather than in
/usr/local/share/vim/vim90/colors.

That is one reason you should _never_ add files to or modify files
in the $VIMRUNTIME directory (e.g., /usr/local/share/vim/vim91).
Those files may be overwritten during an upgrade to a newer patch
level or may no longer be in the 'runtimepath' when Vim is upgraded
to a new release.

Any files that you add or modify should be put in your ~/.vim
directory, as Christian suggested, or in $VIM/vimfiles if you want
to make them available to all users.

Regards,
Gary
