### ISSUE TITLE
`<C-[>` still broken for certain Cyrillic keyboard layouts

### ISSUE THREAD

**Issue by wildekat** [vim/vim#14272]
### Steps to reproduce

1. Run `gvim -u NONE`
2. Enter Insert mode
3. Switch to Russian (I'm using the standard/most common [ЙЦУКЕН keyboard layout](https://en.wikipedia.org/wiki/JCUKEN))
4. Press `Ctrl+Cyrillic letter х` to attempt to exit Insert mode
5. Observe how nothing happens

### Expected behaviour

Before Vim-8.2.4807, `<C-х>` was fully equivalent to `<C-[>` / `<Esc>`, in any mode (`[` and `Х` are one and the same key).

### Version of Vim

9.1.0181

### Environment

OS: Windows 10
`$TERM`: N/A
On Windows, the issue is only present in gVim and does not seem to affect console Vim at all.

**Comment by RestorerZ** [comment]
Please take a look [here](https://github.com/vim/vim/issues/12595) and [here](https://github.com/vim/vim/pull/12752).

**Comment by wildekat** [comment]
@RestorerZ
Thanks, I've been through those threads and a number of other similar ones.

If I were to set `set_keycode_trans_strategy` to `experimental`, that would also require setting up *hundreds* of explicit `<C-*>` mappings: `<C-ц>` would have to be mapped to `<C-w>`, `<C-г>` to `<C-u>` and so on. Clearly that's not the way to go.

The problem with `set_keycode_trans_strategy == classic` is that it does not quite restore the old (pre-8.2.4807) behavior: in this mode, `<C-х>` basically does not exist, so you cannot even map it meaningfully (but thankfully all the other `Ctrl+Cyrillic letter` combinations seem to work out of the box).

**Comment by wildekat** [comment]
Sorry, my bad. It turns out <C-х> does NOT work in Vim-8.

**Comment by ant0sha** [comment]
Question is, if it is meaningful feature request then...

**Comment by wildekat** [comment]
I for one would very much like to see this implemented.
One can actually map `<C-х>` to `<C-[>` under `set_keycode_trans_strategy = experimental`, but for that solution to be viable, we would need an equivalent of `langmap` for Ctrl key bindings.

**Comment by ant0sha** [comment]
Thanks to @RestorerZ explanations in PR #14277, right way to
solve this issue seems to be to modify slightly the standard RU
keyboard layout.

Using MSFT "Keyboard Layout Creator" I created custom RU layout
(it is possible to load the existing layout as the starting
point), modified it so that the "small russian ha" (aka VK_OEM_4)
button sends ESC when pressed with CTRL: entered there
``U+001b``, generated the setup package (named my new layout in
description as "Russian - Custom with ESC on CTRL+HA"), installed
generated setup.exe (requires admin privileges), changed in
system settings which RU layout to use instead of standard one,
reboot - and it works.
