### ISSUE TITLE
&statusline eats space from expression

### ISSUE THREAD

**Issue by mhinz** [vim/vim#1431]
#### Steps:

```viml
let &stl = '%{" x"}'
" or
let &stl = '%{""}%{" x"}'
```

#### What happens?

The space before the `x` gets eaten.

#### What is expected?

The space doesn't get eaten.

#### Details

Using an expression in &statusline [sets the `itemisflag` toggle](https://github.com/vim/vim/blob/c4a249a736d40ec54794827ef95804c225d0e38f/src/buffer.c#L4146). And [here the space gets eaten](https://github.com/vim/vim/blob/c4a249a736d40ec54794827ef95804c225d0e38f/src/buffer.c#L4370-L4371).

Maybe it's good enough to snuck in a condition `opt != STL_VIM_EXPR`.

**Comment by chrisbra** [comment]
I guess this is meant to remove leading whitespace, which is okay for the usual statusline flags.
Perhaps the itemisflag flag shouldn't be set at all for STL_VIM_EXPR?  Leading whitespace it isn't removed for '%!function()' items as well, so it might make sense to just not set the itemisflag, so that it is consistent.

**Comment by kurkale6ka** [comment]
Hi,
I will just give an example where this is a problem for me: https://github.com/kurkale6ka/vim/blob/master/.vimrc#L452

I need 2 spaces before: `s:sep_r` as a workaround.
Same further down before the `return` statement.

**Comment by NoSuck** [comment]
I noticed this as well today, running 1-1176.

**Comment by caksoylar** [comment]
Ran into a similar issue today, where leading zeroes from string expressions are dropped, i.e.

```vim
let &statusline='%{"001"}'
```
results in a statusline of `1`. Can also confirm the original issue still occurs with 8.1.565.

**Comment by brammool** [comment]
> Ran into a similar issue today, where leading zeroes from string
> expressions are dropped, i.e.
> 
>     let &statusline='%{"001"}'
> 
> results in a statusline of `1`. Can also confirm the original issue
> still occurs with 8.1.565.

'statusline' defines fields which are handled in a clever way.
If you want to define a literal status line, use something like:

     let &statusline='%!"001"'


-- 
LARGE MAN:   Who's that then?
CART DRIVER: (Grudgingly) I dunno, Must be a king.
LARGE MAN:   Why?
CART DRIVER: He hasn't got shit all over him.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by caksoylar** [comment]
My use case is that I have a function `Scrollbar()` to return a string that I would like to insert into my statusline using `set statusline+=%{Scrollbar}`, which might return a string like "000000". However the return value seems to be interpreted as a number instead of a string, thus only a single "0" in the output.

I could work around the problem by having a function `Statusline()` that calls `Scrollbar()` inside and `set statusline=%!Statusline()`, but then I have to set all other fields inside this function too and lose modularity.

**Comment by mhinz** [comment]
(Closing this to prune my list of open issues that probably don't get acted on.)
