### ISSUE TITLE
search and replace in visual block mode applies to whole lines

### ISSUE THREAD

**Issue by kjyv** [vim/vim#1448]
I expect (maybe wrongly) to be able to use search and replace on the current visual selection, regardless of the method used (e.g. mouse, visual, visual line or visual block mode).
That said, while all the others behave the proper way, selecting with visual block does not. Starting with ^-v then :s/A/B/ does replace as if visual line mode was used. I've not been able to find a bug report about it (maybe many years ago) but there is even a vim plugin that fixes this. If this is not considered a bug, I wonder why consistent behaviour is not wanted or what other logic is behind the current behavior.

**Comment by jamessan** [comment]
`:substitute` is a line-wise command.  The only information it has is the start/end lines.

You can use the `\%V` [atom] to restrict the search to the visually selected region within the lines that `:substitute` is operating over.

Also, general usage questions should be asked on the [user] list, rather than via the issue tracker.

[atom]: https://vimhelp.appspot.com/pattern.txt.html#%2F%5C%25V
[user]: http://www.vim.org/maillist.php#vim

**Comment by axemaster** [comment]
I agree with kjyv this is a bug. it's a design bug. :substitute should respect intra-line range restriction. I believe the solution is to fix :substitue:, not to simply wave off the issue a by design. i.e. fix the design for usability.
The \%V is a nice work around, but the behaviour it enables I think most be would expect by default. Perhaps it could be implemented as an opt-out rather than an opt-in behaviour.
Cheers

**Comment by chrisbra** [comment]
No it is not a bug. ex  commands work linewise. changing that would be a backwards incompatible change, that is not justified because there are workarounds to change that.
