### ISSUE TITLE
vim_dev appears to be marked spam on Google Groups

### ISSUE THREAD

**Issue by benknoble** [vim/vim#14696]
![Screenshot of Groups page saying « Banned Content Warning, vim_dev has been identified as containing spam, malware, or other malicious content »](https://github.com/vim/vim/assets/22802209/772efb44-044d-4c9d-b792-58a7ce2e9aae)

**Comment by habamax** [comment]
https://groups.google.com/g/vim_use/c/skARx2yAEWc

```
Hi,
I have just been informed by an automatic email coming from Google, that
all content on the vim-dev Google Groups List
https://groups.google.com/g/vim_dev has been removed/blocked for
Spam/Malware reasons.

As usual, there is no personal contact given and they just mention I can
pursue my legal claims in court :(

Currently it is still possible to view the list, when you are logged in,
but at least publicly the archive seems no longer available. Let's hope
this list here still remains active for a while.

So if anybody has any contacts to the Google Groups team, please contact
me off-list and that would be very much appreciated. Otherwise we may
have to think about moving the lists to a different hoster. I have no
idea if there still exists alternatives to Google nowadays.

Not enough that they keep blocking my mails for spam reasons :/

Thanks,
Christian 
```

**Comment by Shane-XB-Qian** [comment]
when this happened? is it near 17 GMT yesterday?
my mailbox (or account) seems was suspicious login-ed, no sure who interesting my account. :sweat_smile:

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
It's a bit strange, Google says because of privacy laws, it cannot point out which exact message caused this issue. I mean, surely if it is malicious behavior and you can act on it, you must be able to tell what exactly is the malicious behaviour and which message caused it (and what kind of malicious behavior was found).

Interestingly we do have moderation of the first message enabled and I delete users posting spam, so I have no idea why Google thinks we are doing something wrong here. There clearly wasn't any Spam, malware or otherwise in-appropriate content (at least not that I remember).

In the mean time I found the appeal form: https://support.google.com/groups/answer/14187429?hl=en&sjid=3381091688987517087-AP where one can request the suspension to be re-checked. 

It seems I should consider to move the group hosting somewhere else. Perhaps going self-hosting again.

**Comment by Shane-XB-Qian** [comment]
> It's a bit strange, Google says because of privacy laws, it cannot point out which exact message caused this issue. I mean, surely if it is malicious behavior and you can act on it, you must be able to tell what exactly is the malicious behaviour and which message caused it (and what kind of malicious behavior was found).
> Interestingly we do have moderation of the first message enabled and I delete users posting spam, so I have no idea why Google thinks we are doing something wrong here. There clearly wasn't any Spam, malware or otherwise in-appropriate content (at least not that I remember).

i guess maybe it was due to the group-mail forwarding, perhaps it raised replying-mail-storm somehow or you knew github would forwarded mail too if one user registered 'follow' that topic or whole repo but vim-dev would forward too if was a group member;
that maybe gave google server stress, so gg thought it was a spam.

as for my mailbox, i am curious, not sure who interested my mailbox (not a google mailbox/account), seems happened at that timing too, not sure if that just was by some lucky chance, or connected, or irrelevant :sweet_smile:

-- 
shane.xb.qian

**Comment by jamessan** [comment]
vim_dev is back.

**Comment by benknoble** [comment]
@chrisbra I still think Discourse is something to consider: they have programs for open source projects IIRC, but it can also be self-hosted.

**Comment by chrisbra** [comment]
I am fine with Discourse in addition to the existing support channels. But I am not going to set it up. I am already active in too many channels. If the community wants it and needs an official ACK, then please go ahead, I might even join.
