### ISSUE TITLE
Normal-mode keys _ and g_ do not perform the "correct" behavior

### ISSUE THREAD

**Issue by Asheq** [vim/vim#14760]
The normal-mode keys `_` and `g_` do not follow the same pattern as all the other similar left-right motions.

It should be like this (notice the predictable pattern):

### Move within the buffer line
- `0`    to first character of buffer line
- `^`    to first non-blank character of buffer line
- `_`    to last non-blank character of buffer line (❌ `_` currently does something else that's not useful/redundant)
- `$`    to last character of buffer line

### Move within the screen line (when buffer line is wrapped or scrolled)
- `g0`    to first character of screen line
- `g^`    to first non-blank character of screen line
- `g_`    to last non-blank character of screen line (❌ `g_` currently does what `_` should do)
- `g$`    to last character of screen line

### Workaround

```vimscript
noremap           _                g_
noremap           g_               g$ge
```

But I think it should be fixed for everyone by default.

Here is a screen capture with the mappings. All the text is one buffer line that is wrapped. Leading spaces and trailing spaces are shown with `‿`:

https://github.com/vim/vim/assets/4657140/9e3d9d20-5c71-4c91-ab70-640c4e713bdf

**Comment by chrisbra** [comment]
Well, that would be nice, but it is not how this works. We are basically following the vi precedent here and `_` is specified to go down [a line by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html#tag_20_152_13_28). Or in [Vim documentation](https://vimhelp.org/motion.txt.html#_).  Other vi clones behave the same, e.g. nvi. 

For `g_` it's slightly different. Posix does not specify that motion so Vim has set a precedent here when it was implemented. And to go to the last non-blank on a screen-line, you can use [`g<End>`](https://vimhelp.org/motion.txt.html#g%3CEnd%3E).

Whether this is useful or not, many people are used to those motions. We cannot easily change it without breaking a lot of peoples habits. That's why you can map it to whatever motion you would like it to behave instead.
