### ISSUE TITLE
b:changedtick and b:['changedtick'] are disconnected

### ISSUE THREAD

**Issue by justinmk** [vim/vim#1477]
`b:changedtick` is a special pseudo-variable that doesn't follow the rules of Vim script. `b:['changedtick']` does not work the same way. Either `b:['changedtick']` should be an error, or it should behave the same as `b:changedtick`. The current behavior just causes confusion.

**Comment by ZyX-I** [comment]
Ref https://github.com/neovim/neovim/pull/6112/commits/d99fbc7d9ae0715999acc31ee42f92a38a971e44 from neovim/neovim#6112. If I did not make errors setting both `buf->b_changedtick` and `b:['changedtick']` at once appears to be rather easy.

**Comment by brammool** [comment]
Justin M. Keyes wrote:

> `b:changedtick` is a special pseudo-variable that doesn't follow the
> rules of Vim script. `b:['changedtick']` does not work the same way.
> Either `b:['changedtick']` should be an error, or it should behave the
> same as `b:changedtick`. The current behavior just causes confusion.

	echo b:['changedtick']
	E716: Key not present in Dictionary: changedtick

I suppose you mean one could set the variable in the dictionary.
Well, that's a user error really.  I don't care too much about that.

The only thing where it would matter is when you pass the b: dictionary
around, since the literal string "b:changedtick" is recognized.


-- 
I have read and understood the above. X________________

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
fixed as of https://github.com/vim/vim/releases/tag/v8.0.0334
