### ISSUE TITLE
Remove/modify filetype indent for asm files

### ISSUE THREAD

**Issue by zack466** [vim/vim#14791]
I feel like the current filetype indent plugin for `asm` files, which appears to have been added to the repo about a month ago, is not very helpful for assembly programming (located at `runtime/indent/asm.vim`) and should be removed or modified.

The current indenting behavior is: every line is indented except for labels (keywords that end with a colon). IMO, this is pretty much useless (and actually a little annoying) for most assembly languages - this causes comments, labels (depending on the syntax being used), assembler directives, and preprocessor macros to all be incorrectly indented.

For example, here is something I think would be reasonable in a generic assembler syntax:
```asm
#define EIGHT (1 << 3)

.data
msg db "Hello, world!"

.code

; Some documentation for this function
; Some more documentation...
foo:
    LDI R16, 0x80
    ADD R16, R16
```

The current assembly indentation would turn this to: (assuming a shiftwidth of 4)
```asm
    #define EIGHT (1 << 3)

    .data
    msg db "Hello, world!"

    .code

    ; Some documentation for this function
    ; Some more documentation...
foo:
    LDI R16, 0x80
    ADD R16, R16
```

I don't think this is the way assembly code is typically indented...

I understand that you can easily turn this behavior off (I added `autocmd FileType asm setlocal indentexpr= ` to my `.vimrc`), but I don't think it should be the default in the first place. Personally, I don't think there needs to be custom indentation behavior for `asm` files at all -- just indenting manually when needed and then letting `autoindent` figure it out is flexible and makes the most sense (and as far as I can tell, has been the default for a while). I would be interested in seeing what the general consensus is.

For context, my current use case is AVR assembly.

**Comment by ebiggers** [comment]
I ran into this too: `//`-style comments are being indented incorrectly.  I worked around this by deleting `/usr/share/vim/vim91/indent/asm.vim` from my system.

**Comment by philj56** [comment]
@zack466 Hey, sorry for the slow response.

I think that's a pretty reasonable argument; this was a originally a very minimal-effort file for my personal use. It's included in vim because at least one other person wanted it (The original PR's at https://github.com/vim/vim/pull/14383).

I don't have any particularly strong opinions on it staying in or not, so if it's annoying multiple people, it's probably best off removed. It could also be modified to be much less zealous in its indenting while still achieving my original goals, by changing the ``GetAsmIndent`` function to something like:
```vim
function! GetAsmIndent()
  let line = getline(v:lnum)

  " If the line is a label (starts with ':' terminated keyword), 
  " then don't indent
  if line =~ '^\s*\k\+:'
    let ind = 0
  else
    " If the previous line was a label, indent:
    if getline(v:lnum - 1) =~ '^\s*\k\+:'
      let ind = s:buffer_shiftwidth()
    else
      " Let autoindent handle everything else.
      let ind = -1
    endif
  endif

  return ind
endfunction
```

This would mean basically nothing gets touched apart from labels and the lines directly after them.

**Comment by chrisbra** [comment]
Hm, the `s:buffer_shiftwidth()` function seems undefined. Let me remove the indent script then if it causes problems.
