### ISSUE TITLE
optimize filetype.vim loading

### ISSUE THREAD

**Issue by yu3s** [vim/vim#14881]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
1. `cat run.sh`
```bash
#!/usr/bin/env bash

cnt=0
> startup.txt

while true
do
	vim --clean --not-a-term --startuptime startup.txt -c q
	cnt=$((cnt+1))

	if [[ "$cnt" -gt "$1" ]];then
		break
	fi
done

filetype=$(awk '/filetype.vim/ {sum += $2} END {print sum}' startup.txt)
total=$(awk '/editing files in windows/ {sum += $1} END {print sum}' startup.txt)
printf "%.1f %.1f %.3f\n" $filetype $total $(echo "$filetype/$total" | bc -l)
```
2. `sh run.sh 1000`
```
12195.6 17462.8 0.698
```

**Describe the solution you'd like**
Provides built-in command to generate specific filetype.vim, allowing users to manually replace

**Comment by chrisbra** [comment]
Wait what? Why do you want to generate a specific filetype.vim? Sorry I don't see what problem you are trying to solve here

**Comment by yu3s** [comment]
> Wait what? Why do you want to generate a specific filetype.vim? Sorry I don't see what problem you are trying to solve here

I found that loading filetype.vim took up 30% of the startup time. I hope to provide a conversion mechanism similar to dts to dtb? Or provide an option for users who are willing to reduce accuracy and improve performance. Manually operating filetype.vim is not very convenient

**Comment by chrisbra** [comment]
Well, it has to read the file and this is a large file, so it depends on your fileystem and hardware performance. Have you tried moving your $VIMRUNTIME to a memory mounted drive? That should give you better performance.
Not sure what kind of conversion mechanism you had in mind, I have never heard about dts/dtb before in such a context.

**Comment by yu3s** [comment]
> Well, it has to read the file and this is a large file, so it depends on your fileystem and hardware performance. Have you tried moving your $VIMRUNTIME to a memory mounted drive? That should give you better performance. Not sure what kind of conversion mechanism you had in mind, I have never heard about dts/dtb before in such a context.

Yes, this is the most effective method

dts: Devicetree source
dtb: Devicetree blob

**Comment by chrisbra** [comment]
Sorry, I don't think this is an actionable item here, so I am closing this.

**Comment by yu3s** [comment]
I think four interfaces need to be added, and users can combine and generate the desired filetype.vim without manual modification
```c
// input filetype.vim and output filetype.bin
unsigned char* filetype_encode(char *vim)

// input filetype.bin and output filetype.vim
char* filetype_decode(unsigned char *bin)

// input filetype.bin and path, match the output corresponding filetype.vim
char *filetype_match(unsigned char *bin, char *path)

// input filetype1.vim and filetype2.vim, output filetype.vim
char *filetype_merge(char *vim1, char *vim2)
```

**Comment by chrisbra** [comment]
So I guess, what you actually want is some kind of binary fileformat for vim9 script, since this is compiled (similar to what zsh or python are doing) Not "optimizing filetype.vim loading". 
I suppose that is a valid request, if this really provides a benefit. I mean, it's not like Vim will in majority execute Vim Scripts, but it is rather an interactive program, so I am not planning to be working on that.

**Comment by yu3s** [comment]
> So I guess, what you actually want is some kind of binary fileformat for vim9 script, since this is compiled (similar to what zsh or python are doing) Not "optimizing filetype.vim loading". I suppose that is a valid request, if this really provides a benefit. I mean, it's not like Vim will in majority execute Vim Scripts, but it is rather an interactive program, so I am not planning to be working on that.

I think the easiest optimization is to reduce the number. In extreme cases, only including c  takes less than 1ms. I just need a mechanism to automatically increase

I am not a full stack developer, and I personally prioritize startup speed. I think the current filetype.vim update is a negative optimization.

Since I'm trying this, I can accept the flaws

**Comment by clason** [comment]
If you(!) care about this and want to spend the time improving it, I would recommend looking at the way Neovim refactored the filetype detection code (but not logic!): instead of creating ~1000 autocommands on startup, we create a single one that runs a dispatch on the filename and (if necessary) contents; the relevant functions are here:
* https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua
* https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype/detect.lua
(you would obviously write these in Vim9script and keep using full Vim regex, but otherwise I would hope a 1:1 port as a starting point would save you from the significant effort we had to make).

**Comment by yu3s** [comment]
I manually generated a filetype.vim based on daily needs

```vim
vim9script noclear

if exists("g:did_load_filetypes")
	finish
endif
g:did_load_filetypes = 1

augroup filetypedetect
au BufNewFile,BufRead *.asm,*.[sS]	setf asm
au BufNewFile,BufRead *.c			setf c
au BufNewFile,BufRead *.cxx,*.c++,*.hh,*.hxx,*.hpp,*.ipp,*.moc,*.tcc,*.inl,*.C,*.H setf cpp
au BufNewFile,BufRead *.h			call dist#ft#FTheader()
au BufNewFile,BufRead .bashrc,bashrc,bash.bashrc,.bash[_-]profile,.bash[_-]logout,.bash[_-]aliases,.bash[_-]history,*.bash setf bash

au BufNewFile,BufRead [mM]akefile.am,GNUmakefile.am	setf automake
au BufNewFile,BufRead CMakeLists.txt,*.cmake,*.cmake.in		setf cmake
au BufNewFile,BufRead configure.in,configure.ac setf config
au BufNewFile,BufRead *.diff,*.rej,*.patch		setf diff
au BufNewFile,BufRead *.dot,*.gv		setf dot
au BufNewFile,BufRead *.dts,*.dtsi,*.dtso,*.its,*.keymap	setf dts
au BufNewFile,BufRead COMMIT_EDITMSG,MERGE_MSG,TAG_EDITMSG,NOTES_EDITMSG,EDIT_DESCRIPTION	setf gitcommit
au BufNewFile,BufRead *[mM]akefile*,*.mk,*.mak,*.dsp,Kbuild setf make
au BufNewFile,BufRead {.,}tmux*.conf*		setf tmux
au BufNewFile,BufRead Kconfig.*,Config.in.*	setf kconfig
au BufNewFile,BufRead $VIMRUNTIME/doc/*.txt	setf help
au BufNewFile,BufRead *.txt
	\  if getline('$') !~ 'vim:.*ft=help'
	\|   setf text
	\| endif

runtime! ftdetect/*.vim
augroup END

au filetypedetect BufNewFile,BufRead,StdinReadPost *
	\ if !did_filetype() && empty(win_gettype())
	\    && expand("<amatch>:e") =~ '\w'
	\|   exe 'setf ' .. expand("<amatch>:e")
	\| endif
```

I think it's reasonable

`sh run.sh 1000`
```
253.0 2915.9 0.087
```

**Comment by chrisbra** [comment]
Great if you found a filetype.vim that is suitable for your own needs, but perhaps at one time in the future you want to edit (or even only view) a Vim or Python or HTML file and then you won't even get syntax highlighting.
So that is of course very much dependent for everybodys use cases and as such not something that should be included here.
