### ISSUE TITLE
The comment package adds spaces to comment lines even if spaces are absent from 'commentstring'

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14905]
### Steps to reproduce

If I have `'commentstring'` set to `/*\ %s\ */`, pressing `gcc` on `string` results in `/* string */`, which is expected. However if `'commentstring'` is `/*%s*/` (which is default), I get the same result, i.e. `/* string */`. Shouldn't it be `/*string*/` instead?

### Expected behaviour

.

### Version of Vim

9.1.443

### Environment

.

**Comment by chrisbra** [comment]
The plugin does add intentionally padding around the `%s`. I suppose this is intentionally to have it look better.

**Comment by habamax** [comment]
That is supposed to work this way.

**Comment by lkintact** [comment]
I think `/*%s*/` should generate spaceless comments - what if the user doesn't need those spaces? If (s)he does, (s)he can always set `'commentstring'` to `/*\ %s\ */`. But if you disagree, maybe it would be helpful to mention that auto-padding behavior in the docs so as to avoid confusion?

**Comment by chrisbra** [comment]
Let's just document the current practice.

**Comment by nickspoons** [comment]
I must say I don't really understand the logic here. Why not just have the plugin respect `'commentstring'`? That simplifies the plugin code and gives users full control over their output. Otherwise users _cannot_ use the comment plugin to add comments with no whitespace, which they may have both functional and cosmetic reasons for.

**Comment by chrisbra** [comment]
The idea was to have a *simple* comment plugin, that works well for most use cases and produces "nice" comments. It wasn't meant to give users the chance to adjust every tiny little bit. If you have this need, you can install another one of the many plugins. 

If there is a reason (aside from aesthetics) to have comments not being white space aligned, than let's hear it and I am open for a PR, but so far this seems like a minor issue only.

**Comment by nickspoons** [comment]
Thanks Christian. After thinking a bit more about it I can also see why it doesn't make sense to pay too much attention to `'commentstring'` spacing; because the plugin needs to be able to apply to multiple lines:

```vim
function AgeOfVim()
  return systemlist('ps -o etime:1= -p ' . getpid())[0]
endfunction
```

When this is commented with `gcip` the comments are aligned, so `'commentstring'` was never going to be applied directly to the `return...` line anyway:

```vim
" function AgeOfVim()
"   return systemlist('ps -o etime:1= -p ' . getpid())[0]
" endfunction
```

Sorry for the noise, and thanks for the continued diligent work and maintainership.
