### ISSUE TITLE
can't fuzzy match a single completion candidate

### ISSUE THREAD

**Issue by habamax** [vim/vim#14912]
### Steps to reproduce

1. run barebone vim with `vim -Nu NONE`
2. `:set completeopt+=fuzzy`
3. add line `xyz`
4. on the next line type `x` and press `CTRL-N`

I would expect it to complete `xyz`. It doesn't happen.

![image](https://github.com/vim/vim/assets/234774/e062dab2-6533-4698-97c4-83c59e583302)

### Expected behaviour

xyz should be completed as withoug `fuzzy`

### Version of Vim

9.1.465

### Environment

debian 12

**Comment by habamax** [comment]
@glepnir fyi

**Comment by glepnir** [comment]
Issues description are not as detailed as we discussed in the commit section. 

1. first does fuzzy should works like `menuone` when only have one match.
2. not work when use normal completion `<C-N>/<C-p>`  reproduce step in #14910 

for question 2 a littile trouble because of `searchit` function based on regex. may need some change..

**Comment by chrisbra** [comment]
Wait, not sure I understand. We added `fuzzy` to `'completeopt'` option. That is about how vim handles the completion *menu* and *list of already existing candidates*. So my understand for `fuzzy` was, when enabled, the reduction of the list of candidates happens by fuzzy matching, but *how* the list of candidates is created is depends on what kind of completion mode was used (e.g. those of `i_CTRL-X` mappings). One may use fuzzy-completion there as well (using a custom omni-completion), but you may as well simply use regex based search of atoms inside the current buffer of make use of the dictionary. 

So given that, I would expect that `completeopt+=fuzzy` doesn't make a difference for
`x<C-N>` since the list of candidates is build using default keyword local completion (even when there is only 1 candidate).

**Comment by glepnir** [comment]
yes . normal completion is based on keyword regex. but I tried to modify `get_next_default_completion`. If I force some conditions to be skipped, it seems feasible to get fuzzy scores for `ptr` and `compl_orig_text`. not sure do we want also fuzzy on this mode

**Comment by chrisbra** [comment]
I made a small change to the doc 2a2c4fffd7e04f74b316209404767f128684a9e1 on how this should work. I hope we can make it work then as documented.

**Comment by habamax** [comment]
It is actually a bit worse. It can't complete at all if `menu` is not in `completeopt`:

[![asciicast](https://asciinema.org/a/GS6T9tPOJi5PCJRcIzXOtqMs9.svg)](https://asciinema.org/a/GS6T9tPOJi5PCJRcIzXOtqMs9)

**Comment by glepnir** [comment]
emm okay .. i am working on it.

**Comment by habamax** [comment]
Is this patch against the master branch here? `git apply` fails...

**Comment by glepnir** [comment]
> It is actually a bit worse. It can't complete at all if `menu` is not in `completeopt`:
> 
> [![asciicast](https://camo.githubusercontent.com/5dcd760824e13c3b11413bf486451f10ab257bfd2d0fb94f2a83b229b408678d/68747470733a2f2f61736369696e656d612e6f72672f612f475336543974504f4a693550434a5263497a584f74714d73392e737667)](https://asciinema.org/a/GS6T9tPOJi5PCJRcIzXOtqMs9)

my local modified for this problem.

**Comment by habamax** [comment]
applied patch manually:

1. same thing with `set completeopt=fuzzy` it doesn't complete
2. after several presses of C-n and C-p I've got segmentation fault

![image](https://github.com/vim/vim/assets/234774/79f54895-3f99-4e9e-bb1f-d2e26b42c647)

**Comment by glepnir** [comment]
oh sry .. wrong diff should be this 

```diff
diff --git a/src/insexpand.c b/src/insexpand.c
index 74be94cf4..247d4daf3 100644
--- a/src/insexpand.c
+++ b/src/insexpand.c
@@ -4143,8 +4143,8 @@ find_next_completion_match(
     {
        if (compl_shows_dir_forward() && compl_shown_match->cp_next != NULL)
        {
-           compl_shown_match = !compl_fuzzy_match ? compl_shown_match->cp_next
-                                               : find_comp_when_fuzzy();
+           compl_shown_match = compl_fuzzy_match && compl_match_array != NULL
+                       ? find_comp_when_fuzzy() : compl_shown_match->cp_next;
            found_end = (compl_first_match != NULL
                    && (is_first_match(compl_shown_match->cp_next)
                        || is_first_match(compl_shown_match)));
@@ -4153,8 +4153,8 @@ find_next_completion_match(
                && compl_shown_match->cp_prev != NULL)
        {
            found_end = is_first_match(compl_shown_match);
-           compl_shown_match = !compl_fuzzy_match ? compl_shown_match->cp_prev
-                                                  : find_comp_when_fuzzy();
+           compl_shown_match = compl_fuzzy_match && compl_match_array != NULL
+               ? find_comp_when_fuzzy() : compl_shown_match->cp_prev;
            found_end |= is_first_match(compl_shown_match);
        }
        else
```

**Comment by zeertzjq** [comment]
The patch is reverted.

**Comment by habamax** [comment]
I can't reproduce it with the latest vim though.

**Comment by zeertzjq** [comment]
Oh right, it seems to be the separate issue.
