### ISSUE TITLE
Seach counter should perhaps be placed in the far right corner

### ISSUE THREAD

**Issue by lkintact** [vim/vim#14932]
Please have a look at this image:

![search_counter](https://github.com/vim/vim/assets/24726299/f0bf950e-e3fa-48f8-a708-7a4066629c47)

The space outlined in red seems to never be used. Perhaps the search counter should be moved to the far right corner - that would give more space for long search patterns.

gVim 9.1.443.

**Comment by chrisbra** [comment]
That will make it even harder to notice the counter. I already find it at the current place hard to see when I am concentrating. Depends on monitor size of course.

**Comment by bfrg** [comment]
> That will make it even harder to notice the counter. I already find it at the current place hard to see when I am concentrating. Depends on monitor size of course.

Indeed. I've also found it annoying that I have to turn my head/eyes to the right corner in order to peak at the search count. I find it a lot easier when it's on the left side which is why I integrated it into my statusline. And it's displayed only when `hlsearch` is enabled:

![screenshot-2024-06-07_020042](https://github.com/vim/vim/assets/6266600/57fdbafd-2eaf-4b58-8d56-7840aa687cd3)

@lkintact In case you're interested. There's a plugin that displays the search count in a popup window: https://github.com/obcat/vim-hitspop.

**Comment by gdupras** [comment]
Partial commands are shown there. Do `:set showcmd` then type `y1000000a` and you get this:

![Screenshot_20240606_202034](https://github.com/vim/vim/assets/57042631/2a7bad7b-c89c-4287-9295-7bde9305b66b)

**Comment by zeertzjq** [comment]
It seems that it is shown at the bottom-right after `:set noshowcmd noruler`

**Comment by chrisbra** [comment]
closing then.
