### ISSUE TITLE
Rendering Bug with the statusline and DirectX Renderer on Windows

### ISSUE THREAD

**Issue by chrisbra** [vim/vim#1520]
I am maintaining a fancy statusline plugin, which makes use of some nice unicode glyphs on the statusline. Now I have noticed, that there are severe rendering issues when using this together with the `:set renderoptions=directx` on Windows. Here is a minimal example.
```viml
set encoding=utf-8
set laststatus=2
set bs=2
set guifont=Courier_New:h12:cANSI
set rop=type:directx
let symbols={'maxlinenr': 'M', 'linenr':'L' }
let &stl='%f %{g:symbols.linenr}%2l/%L%{g:symbols.maxlinenr}'
```
save that into c:\temp\stl_bug.vim and run this from the console:
`gvim.exe --noplugins -N -u c:\temp\stl_bug.vim c:\temp\stl_bug.vim`

The result looks like this:
![grafik](https://cloud.githubusercontent.com/assets/244927/23364802/c86c87d0-fd00-11e6-878c-a3af07095da0.png)
(this is okay and expected).

Now change that stl_bug.vim:
```viml
set encoding=utf-8
set laststatus=2
set bs=2
set guifont=Courier_New:h12:cANSI
set rop=type:directx
let symbols={'maxlinenr': "\u33d1", 'linenr':"\u2630" }
let &stl='%f %{g:symbols.linenr}%2l/%L%{g:symbols.maxlinenr}'
```
(I only changed the `:let symbols` line to use some Unicode characters)
This looks like this:
![grafik](https://cloud.githubusercontent.com/assets/244927/23364913/38bd6108-fd01-11e6-83ff-ca2b542993b3.png)
That is okay, however note how the printable characters have been moved slightly down on the line, so that the underscore and the bottom of the "g" are not completly visible.

Now move the cursor down a single line, e.g. press `j`:
![grafik](https://cloud.githubusercontent.com/assets/244927/23364980/7ab23840-fd01-11e6-9964-abfa07f78005.png)
Note how the actual linenumber and the slash moves slightly to the top left, leaving the old '/' still visible. It all get's fine, if I press `<c-l>` again (e.g. force a redraw):
![grafik](https://cloud.githubusercontent.com/assets/244927/23365036/acdb1152-fd01-11e6-8977-6ab377c63f89.png)

This is actually pretty disturbing and it took me a while to figure out, that this is caused by the directx rendering. In Vim-Airline, it makes the line numbering almost unusable, because there the actual line number is sometimes not even displayed at all, or only half of the number is displayed:
![grafik](https://cloud.githubusercontent.com/assets/244927/23365099/fa46e1f0-fd01-11e6-988e-ef0bc3596ed2.png)
Note it displays 40/403 instead of 403/403 and not even a redraw fixes this issue.

Version: 8.0.142 Windows

**Comment by rodcloutier** [comment]
Same behaviour with MacVim.

```
$ brew list --versions | grep macvim
macvim 8.0-127
```

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:51:36)
MacOS X (unix) version
Included patches: 1-329      
```

@chrisbra You might want to retarget the issue since it is not strickly Windows only.

**Comment by chrisbra** [comment]
you mean retitle? My problem is clearly caused by the renderoptions setting, which as far as i know is windows only. So I think your problem is a different (but similar) one.

**Comment by rodcloutier** [comment]
The problem is exactly the same. So it is probably something along the accelerated rendering of Unicode fonts in the status line.

**Comment by koron** [comment]
I wish that https://github.com/vim/vim/pull/4116 will fix this problem.

**Comment by mxt3** [comment]
This is supposed to be fixed by  patch 8.1.1009 (1f271ef) , but I still experience this issue. Using the minimal example outlined in the first post by @chrisbra , I get the following:
![afbeelding](https://user-images.githubusercontent.com/2456835/147956047-382329b4-cb09-46b6-88f7-f0257ab497f0.png)


Note the double slash in the line number, just like in the original issue. However, the characters seems to be always bottom aligned now (where originally the numbers also moved). Forcing redraw (`<c-l>`) indeed draws the line numbers correctly.

After resetting to GDI rendering with `set rop=`, the font is noticeably less pretty, but the issue is again gone:
![afbeelding](https://user-images.githubusercontent.com/2456835/147956186-78c24396-204c-42df-9175-8366fba352ad.png)


I am running Windows 10, 21H2. I got my (g)Vim from the latest stable version on vim.org at the time of writing.

The issue is still disturbing in that the line numbers will also get printed out wrongly at higher line numbers (e.g. 40/403 instead of 403/403)

**Comment by chrisbra** [comment]
> I am running Windows 10, 21H2. I got my (g)Vim from the latest stable version on vim.org at the time of writing.

So what is your exact vim version and can you please test with latest available version?

**Comment by mxt3** [comment]
> So what is your exact vim version and can you please test with latest available version?

As seen in the screenshots, it's vim 8.2 patch level 1-2825. So this makes the version number 8.2.2825, I guess? That is also the version number given on vim.org where I downloaded this release.

With testing the *latest* available version, do you mean building from source?
