### ISSUE TITLE
duplicate runtime/syntax vimscript for Oracle PL/SQL

### ISSUE THREAD

**Issue by jiangyinzuo** [vim/vim#15310]
I found that `runtime/syntax/plsql.vim` and `runtime/sqloracle.vim` are both for Oracle Procedural SQL (PL/SQL) language.

- https://github.com/vim/vim/blob/master/runtime/syntax/plsql.vim
- https://github.com/vim/vim/blob/master/runtime/syntax/sqloracle.vim

Should we keep just one file for PL/SQL? @lee-lindley @chrisbra

**Comment by chrisbra** [comment]
It's been a while, since I had to be working with PL/SQL and SQL Oracle scripts and there is some overlap.

Hm, no I believe sqloracle is used mostly for SQL statements (that may of course also contain plsql syntax), while `plsql` is more for scripts containing only plsql functions and definitions. 

Nowadays, I don't work with Oracle anymore, so I cannot test it, but I think it is fine to keep both versions.

**Comment by lee-lindley** [comment]
plsql.vim includes Oracle SQL syntax as well as PL/SQL and can be used for regular SQL. It is more comprehensive on Oracle keyword identification including sqlplus keywords, and has syntax highlighting enhancementss for quoted strings and double quoted identifiers. It also includes code folding while sqloracle.vim does not.

sqloracle.vim behaves differently, neither better nor worse.  If one uses SQL in multiple database types along with Oracle, it may be a better choice. It was also the default choice for a very long time. Many may prefer it.

**Comment by chrisbra** [comment]
Thanks. closing then.
