### ISSUE TITLE
Proper authorship of commits

### ISSUE THREAD

**Issue by ghost** [vim/vim#1554]
Currently @brammool is the author for all 7,027 commits on this repository. I
found this highly unusual with such a well known project.

I did some digging and see the source of the problem. @brammool is essentially
taking author credit for other peoples commits. Now this is not the case with
all pull requests, but consider #1515. The original author, @dpelle, wrote 74
lines:

https://github.com/vim/vim/pull/1515/files

Then @brammool closed the request with his commit aeb661e. However if you
compare @dpelle original commit with @brammool commit, they are almost
identical:

~~~diff
-+  if !has('unix') || !executable('patch')
++  if !executable('patch') || !has('unix')
~~~

~~~diff
-+  call setline(1, [1, 2, 3])
++  call setline(1, ['1', '2', '3'])
~~~

So @brammool essentially changed 2 lines of @dpelle original 74 line commit,
then claims authorship over the entire commit? @brammool should be making his
own commit on top of other peoples commits, otherwise he is not giving proper
attribution to their work.

http://stackoverflow.com/a/39963521

**Comment by chdiza** [comment]
"Authorship" is reflected in the commit messages, as it always has been since before Vim moved to github.  In the very example you cite, the commit message gives credit to whom it is due.

**Comment by ghost** [comment]
@chdiza “That’s the way it’s always been done” is not a good reason to keep
doing something:

http://wikipedia.org/wiki/Appeal_to_tradition

Because he is not merging other peoples commits, he is the only
person to show on contributors:

http://github.com/vim/vim/graphs/contributors

Compare this to Git (1,082 contributors):

http://github.com/git/git

Or FFmpeg (859 contributors):

http://github.com/FFmpeg/FFmpeg

In addition, doing it this way breaks being able to search commits by author.
Here are some commits by specific author with Git repo:

http://github.com/git/git/commits?author=peff

Now contrast that with Vim. Even though we know @dpelle has authored at least 1
commit, this will show none:

http://github.com/vim/vim/commits?author=dpelle

**Comment by chdiza** [comment]
> Now contrast that with Vim. Even though we know @dpelle has authored at least 1
commit, this will show none:

That's not the way that one should go about looking for authorship for Vim patches, and it never has been.  Grep the git log if you want to know those things.

Vim is only on github in the first place because googlecode shut down and a cadre of loud users browbeat Bram into putting it here rather than Bitbucket.  This repo does not follow the usual github conventions wrt workflows and such, so you need to stop expecting it to.

**Comment by vim-ml** [comment]
2017-03-13 2:09 GMT+03:00 chdiza <vim-dev-github@256bit.org>:
> Now contrast that with Vim. Even though we know @dpelle has authored at
> least 1
> commit, this will show none:
>
> That's not the way that one should go about looking for authorship for Vim
> patches, and it never has been. Grep the git log if you want to know those
> things.
>
> Vim is only on github in the first place because googlecode shut down and a
> cadre of loud users browbeat Bram into putting it here rather than
> Bitbucket. This repo does not follow the usual github conventions wrt
> workflows and such, so you need to stop expecting it to.

There are typos and I know myself that I am referred to as, at least,
`ZyX`, `Nikolay Pavlov` and `Nikolai Pavlov`. This makes searching via
git (e.g. `git log --grep` or regular search in `less`) tricky. When
one uses git or mercurial own capabilities to specify author and pulls
in original commits, at least, there is only author to blame for
typos, not Bram.

It is also possible to pull in a PR, squash it, reword the commit
message, do some fixups and git will still keep original author.

Last, but not least: both git and mercurial always allowed to specify
author on the command-line explicitly when doing `vcs commit`, even
though this variant is still prone for typos. So making “the right
thing” was possible back then on google code, just there were not much
uses for it.

PS: github vs bitbucket has nothing to do with this. Requests to
change the workflow have very long history: current workfolw is
exceptional for opensource projects and not in a good sense. And
bitbucket just has less capabilities regarding the statistics, yet it
is still able to link commits with the account. I am not entirely sure
how GH and BB will swallow authors specified with `vcs commit
--author` (`--user` for mercurial) though, but I guess they will be
fine unless there are signatures involved.

**Comment by chrisbra** [comment]
The development model with giving credit in the commit message has been proven to be working well. It might not be the right way for git or mercurial, but it even worked when vim was developed using cvs, so it is what it is. I see no sense to discuss this further.

**Comment by grepsedawk** [comment]
Why is this the case with vim? Does it make the workflow easier? Is it just to keep with tradition?
Seems like a pretty good reason to adopt neovim alone and I'd love to understand why there's pushback on using git authors properly.

**Comment by chrisbra** [comment]
> adopt neovim alone

Do whatever you want, nobody forces you to use Vim. And there has been not one single reason given to change a workflow that has been proven to be working well even before the VCS tools supported that. Or saying it differently, changing the workflow now might make switching to the next VCS tool harder.

**Comment by grepsedawk** [comment]
> nobody forces you to use Vim

Oh I'm well aware, and I really appreciate the editor as a whole, I just wanted to understand the mentality behind this commit structure.
While I disagree, I do appreciate the quick feedback.

**Comment by ghost** [comment]
> And there has been not one single reason given to change a workflow that has
> been proven to be working well even before the VCS tools supported that.

@chrisbra wrong. I have given several:

1. the vim project is knowingly misleading its users with regard with authorship
of commits

2. the vim project is knowingly taking credit for others commits

3. the vim project is failing to provide proper attribution to pull requests

this is not only unethical, but it opens up this project to legal liability.
and because of comments in the thread by you, ignorance can no longer be
claimed.

> changing the workflow now might make switching to the next VCS tool harder.

the next VCS tool? git has been around for at least 13 years https://github.com/git/git/commit/a3eb250f996bf5e12376ec88622c4ccaabf20ea8.
if you cant adjust your workflow on the scale of decades then that is your
problem, not anyone elses.

**Comment by chdiza** [comment]
@cup What @chrisbra means, of course, is that nothing remotely approaching a *good* reason has been given.  And he is right.

> the vim project is knowingly misleading its users with regard with authorship of commits

Only if the user simply *assumes*, without bothering to check, that Vim follows a certain kind of workflow.  If the user does this, it's their own fault.  Just because attributions aren't found in your favorite place doesn't mean they aren't made.

**Comment by ghost** [comment]
@chdiza the Git version-control system and GitHub Inc. would disagree with you:

> Show what revision and author last modified each line of a file

http://git-scm.com/docs/git-blame

> Specify an explicit author using the standard A U Thor <author@example.com>
> format.

http://git-scm.com/docs/git-commit

> You can find commits by a particular user with the `author` or `committer`
> qualifiers.

http://help.github.com/articles/searching-commits

> GitHub uses the email address set in your local Git configuration to associate
> commits pushed from the command line with your GitHub account.

http://help.github.com/articles/setting-your-commit-email-address-in-git

**Comment by tonymec** [comment]
So Bram Moolenar on the git master and Christian Brabandt on the Mercurial mirror are mentioned as what the respective VCS regards as the author of every single commit. OTOH, to take an example I know, on the Mozilla Mercurial every single commit is scrupulously attributed to the author of the patch, even if he had no push rights and his patch was committed by someone else. So what? It happens that I may leave Mozilla at some more or less predictable future time because I don't like how the Firefox developers are evolving their product, but I'll stay with Vim because I like the way *Vim* is evolving. Even having brammool as the author of every single git commit has some justice to it, since no single patch gets committed without his explicit review and approval (except maybe changes in some runtime packages whose responsibility has been delegated to someone else).

I don't care which particular name gets mentioned to Git or to Mercurial as the author of any particular patch. What I do care about is that bugs get fixed and that new functionality, if and when added, (a) is often worth using, and (b) doesn't make my existing ~/.vimrc, ~/.viminfo and ~/.vim/** invalid. And in the time I've known Vim, it has an excellent record in the fields I care about.

**Comment by chdiza** [comment]
> the Git version-control system and GitHub Inc. would disagree with you:
>> Show what revision and author last modified each line of a file

Yeah: *IF* that's how the project keeps track of their authors.  That is, IF a project is structured such that what `git` thinks the author is, is in fact the author.   There is no requirement that a project be structured that way, just as there is no requirement to call your main branch `master` and no requirement to accept PRs as opposed to emailed patches.

**Comment by ghost** [comment]
@chdiza also there is no requirement that Vim be called Vim. Why dont we just call it blueberries?

If you want to argue for the sake of argument that is your business - but Git and GitHub conventions are established for a reason - they work.

by shirking them you are losing functionality and gaining - nothing? just seems like laziness to fix the old system.

**Comment by fifthposition** [comment]
> also there is no requirement that Vim be called Vim. Why dont we just call it blueberries?

In one way, that's a good comparison. The name "Vim" is neither right nor wrong; it's a choice which belongs to the maintainer(s) of the tool. Git and GitHub conventions are definitely _useful_, they are definitely how Git and GitHub were meant to be used, but their use is a choice which belongs to the maintainer(s) of the tool.

As far as I know, the author attribution for Vim contributions is the same way. Authors are getting attribution, though not in the way the current VCS expects. As a user, I can argue that Vim should use the normal methods of attribution, and I can argue that Vim should be renamed Blueberries (why not? Yum!). Yet neither choice is right or wrong, and neither choice is mine to make.

**Comment by brammool** [comment]
There are different ways of doing things, and since Vim has done things in a certain way for 25 years, I tend to stick to that.  It has survived moving between different VCS systems and sites shutting down.  I'm not aware of any practical issue with current way of distributing changes.

Authors are attributed in the commit comment.  That is, if I know their name, since half the github accounts don't even have that. And if we were to move away from github and/or it shuts down, all those references to user accounts would become useless anyway.

Also, users reporting problems are just as important as the ones changing the code.  I don't think github has a mechanism for that.  I mention that in the patch comment, if possible.

So if you look at "git blame" you'll see my account, and that is correct, I'm to blame for everything in Vim.

**Comment by chrisbra** [comment]
Just one more last comment, before I shut up (and the issue is actually being closed for a reason)

@cup 

> this is not only unethical, but it opens up this project to legal liability.
> and because of comments in the thread by you, ignorance can no longer be
> claimed.

No, credit is mentioned in the commit logs which has been mentioned several times to you already. What git does provide is a **convention** which is just as good as any other. And in fact Vim is using an older convention that has been proven to be working. So as long as authorship is credited, I don't see a problem and I doubt that the law dictates that one has to use git to prove that.

What is legally right and wrong is a total other topic. A well-known German proverb is:

"In court and on the high seas, one is in god's hand"

So we can only do whatever is sensible and as long as authorship is been noted down explicitly, I doubt there is a difference to be made. After all, who says one has to trust the `git commit --author...`?

Also please do not forget, that the source does not have to be distributed via git. If you download the source tarball, one would not even know the authorship, because all the git meta information is lost. Within Vim, you can even read it in the help file for all the patches.

>     changing the workflow now might make switching to the next VCS tool harder.
> 
> the next VCS tool? git has been around for at least 13 years git/git@a3eb250.
> if you cant adjust your workflow on the scale of decades then that is your
> problem, not anyone elses.

We have been using CVS, SVN, mercurial and git. And the move to github and git was basically only done (like 3 years ago when google code shut down), because of a push from the community. If you read the discussions from back then, I believe you will come to the conclusion, that Brams preference would have been mercurial and bitbucket. 

BTW: I would really appreciate it, if you could start being more objective in your critique and stop claiming authorship is not credited. It has been shown several times and is clearly visible in the commit log.

**Comment by chrisbra** [comment]
@tonymec  Ah, I should probably use `hg import --user`. Changed that now.

**Comment by dstein64** [comment]
I noticed that the [Contributors](https://github.com/vim/vim/graphs/contributors) list on GitHub now includes 21 contributors, up from 2 a few months ago.

It appears that the updated approach for merging contributions started with commit bb01a1e on April 26, 2021.

**Comment by grepsedawk** [comment]
That's so exciting yay!

**Comment by brammool** [comment]
Somehow nobody mentioned that it's possible to take the email of the PR .patch file and use it for a local commit.  I had always used the .diff file, which doesn't contain this info.  And git has so many options that the way to add an author email was quite hard to find.  But I figured it out eventually.
Note that we do have the opposite problem sometimes: I often tweak a patch before sending it out, the author is still the PR author, even when that person didn't write the patch exactly as it is.  Oh well.
