### ISSUE TITLE
`]/` and `]*` in double slash comment

### ISSUE THREAD

**Issue by bounceme** [vim/vim#1561]
with this code:
`// i-=1 */`

the cursor will move to that star-slash even though it isn't a block comment. however

with this code:
`// i-=1 /*`

the `[/` or `[*`  is not confused 

Also, when are these normal mode mappings different? looking at the code and commentary suggests they are different in some circumstances but i have not seen that to be the case

**Comment by brammool** [comment]
Chris Paul wrote:

On 14 March 2017 at 07:08, Chris Paul <notifications@github.com> wrote:

> with this code:
> // i-=1 */
>
> the cursor will move to that star-slash even though it isn't a block
> comment. however
>
> with this code:
> // i-=1 /*
>
> the [/ or [* is not confused
>
> Also, when are these normal mode mappings different? looking at the code
> and commentary suggests they are different in some circumstances but i have
> not seen that to be the case
>

 The reason is that /* always ends a block command.  Consider this:

/*
// comment text */
*/

This is an error, the first */ ends the comment.

On the other hand, /* inside another comment doesn't create a new
comment.

-- 
hundred-and-one symptoms of being an internet addict:
124. You begin conversations with, "Who is your internet service provider?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bounceme** [comment]
Thanks, that makes sense. So is there a difference between using `[*` and `[/`  ?
