### ISSUE TITLE
Allow `cab`s in  Paste mode

### ISSUE THREAD

**Issue by nisbet-hubbard** [vim/vim#15623]
### Steps to reproduce

`:set paste`

### Expected behaviour

Currently, all abbreviations are disabled in Paste mode. Since Paste mode is mostly useful within Insert mode, however, a better default would be to only disable `iab` abbreviations.

A common use case affected by the current behaviour is any abbreviation set for `:set nopaste`, which is long enough to be abbreviated to good effect but can’t be used.

### Version of Vim

8.2.2637

### Environment

Not relevant

**Comment by chrisbra** [comment]
instead of using paste mode, you should probably make use of importing directly from a clipboard by accessing the clipboard register directly. This way, Vim knows the input comes from the system and does not need to apply auto-indent, abbreviations, macros, etc. 

When you are using paste mode, it's supposed to be used only for the time while pasting. As such I don't think, enabling command abbreviations for paste mode is such a good idea.

**Comment by benknoble** [comment]
I think allowing Paste to trigger abbreviations in `:` could reasonably be seen as a (small) security hole, although while in Paste mode you can’t trigger the command line from Insert mode… I’m not sure I understand the use case asked for after all, I guess.

**Comment by benknoble** [comment]
Ah: but you can use the paste key (I forget the option name), or use bracketed paste (automatic), or tpope/impaired's `yop` ("you only paste once") mapping that puts you in Insert mode with paste on but resets it when returning to Normal mode.

**Comment by chrisbra** [comment]
The option name is called [':h 'pastetoggle'](vimhelp.org/options.txt.html#%27pastetoggle%27).
