### ISSUE TITLE
substitute literal text command

### ISSUE THREAD

**Issue by habamax** [vim/vim#15632]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

It is difficult to substitute literal text in vim. As in `%s/hello&.[world]/world hello/g`

**Describe the solution you'd like**
Provide `:substitute! /literal text/replacement` command that would not use regex pattern in search.

**Describe alternatives you've considered**
Custom `:S` command that escapes all regex chars. Main issue -- it is not available in remote boxes.

**Comment by habamax** [comment]
> Provide :substitute! /literal text/replacement command that would not use regex pattern in search

Or `sli[teral]` command akin to `sm[magic]` and `sno[magic]`.

**Comment by chrisbra** [comment]
I have this in my vimrc for years:
```vim
" Search literally!
com! -nargs=1 Search :let @/='\V'.escape(<q-args>, '\\')| normal! n
```

You can then search literally and then just use `:s//foobar/g` to reuse the literal search string. 

Despite adding it to my vimrc (because I thought It could be useful), I think I have never had a use for it. So I am not convinced this is valuable. Also both `:s!` and `:sli` seem a bit obscure.
I am not a fan of all those `:s...` variants and `:s!` seems to be ambigious with `s!foo!bar!g`. And finally a substitute literal command is asking for a companion search literal command. 

I think the better way to handle this is to use the `\V` regex atom at the beginning of your pattern (see the above search literal command).

**Comment by habamax** [comment]
Ok, thx
