### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by AlbaroPereyra** [vim/vim#1573]
Is There a forum for this project?

I'd like to ask a question not really report an issue.

Well I do want to report an issue but, I don't see that file here.

I was wondering how the dmg version came about.

Where is the dmg version repository?

There is an error I would like to fix in the read me file(Readme_MacOSX_vim-8.0.txt)

There is a line that reads  - 11.12.x     (Sierra)

Where did the 11 come from? It is - 10.12.x (Sierra)

Please advise, as I would like to correct this in the repository.

Thanks,

**Comment by grochmal** [comment]
The `vim@vim.org` is the mailing list for the general questions.  Since you're on a Mac there is also `vim-mac@vim.org`.  The information about the lists is on the [Vim homapage](http://www.vim.org/maillist.php).

The Vim for Mac has [its own project](https://github.com/macvim-dev/macvim) which is synced to Bram's project (this project), yet I cannot find the README file you mention in there.  (I hope I'm linking the right project, never used the Mac one.)

Extra: If you are not keen on mailing lists (although they're pretty good, e.g. I got your issue because fot he mailing lists), you can also use [stack exchange](http://vi.stackexchange.com/).  That can be said to a *forum* for the Vim project.  On the other hand vi.SE is not that relevant to issues with the code, like this one.

**Comment by mattn** [comment]
please use https://groups.google.com/forum/#!forum/vim_use
