### ISSUE TITLE
Feature request: preserve current location when replacing the quickfix/loclist

### ISSUE THREAD

**Issue by jfly** [vim/vim#15839]
I explain this issue in terms of the quickfix list below, but I believe everything I say applies equally to the loclist as well.

## Problem

If I'm partway through a quickfix list, and then I do something to refresh the quickfix list, I lose my location in the list.

Here's a simple example of the issue:

1. `vim qf.vim`: You can find `qf.vim` below.
2. `source %`: This will populate (and open) the quickfix list with every line in the current file.
3. Select the Nth entry in the quickfix list (in the video below, I select entry 9, corresponding to line 9 of the buffer).
4. `source %`: This replaces the quickfix list with every line in the current file.
5. Observe how my location in the quickfix list has changed: index 1 is now selected.

<details>
<summary>qf.vim</summary>

```vimscript
" Dead simple script to convert every line in the current buffer into
" an entry in the quickfix list.
"
" This replaces the current quickfix list.
" Run with `:source %`

let qflist = []

let line_count = line('$')
for lnum in range(1, line_count)
    let line_text = getline(lnum)
    let bufnr = bufnr('%')
    call add(qflist, {'bufnr': bufnr, 'lnum': lnum, 'text': line_text})
endfor

call setqflist(qflist, 'r')

" Open the quickix list.
copen
```
</details>

And here it is in action:

[vim-2024-10-09_11.47.24.webm](https://github.com/user-attachments/assets/815d5481-f45f-4d20-b987-b1764eb2cca8)

**Describe the solution you'd like**

I think that `setqflist` should strive to preserve the current "location" in the quickfix list when the quickfix list is replaced. I say "location" rather than "index" because oftentimes you're legitimately changing/fixing things, and when you replace the list, the set of quickfix entries will be different. In other words: we know the line and column number of the currently selected entry, so when we refresh the quickfix list, I'd like for us to select the entry nearest that selected `(line, col)` rather than just selecting the very first entry in the list.

**Describe alternatives you've considered**

I could write a wrapper for `setqflist` that does the "preserve location" logic described above, but it's only useful for code *I* control that calls `setqflist`. If I'm using a plugin or some other builtin that calls `setqflist` directly, then I think the only fix is to implement this in Vim core.

**Additional context**

I originally filed this issue with Neovim: https://github.com/neovim/neovim/issues/30724, but they advised me to ask over here.

**Comment by bfrg** [comment]
In my opinion preserving the current location should be made optional since (a) it can be very time consuming to find the closest location in a larger list, and (b) the new quickfix list could be completely unrelated to the old one. In the latter case keeping the current location wouldn't make too much sense.

**Comment by justinmk** [comment]
> the new quickfix list could be completely unrelated to the old one.

Why would the "r" ("replace") flag be used in that case? That would be a mis-use of the "r" flag by the caller.

**Comment by jfly** [comment]
> (a) it can be very time consuming to find the closest location in a larger list

@bfrg, please take a look at my PR #15841. I was able to implement this by interleaving it into the existing loop. There are no additional memory allocations (just 3 ints to track the previously selected location).

I'm not an expert in c code or performance sensitive applications, but it's hard for me to imagine this is an expensive change.

**Comment by bfrg** [comment]
> Why would the "r" ("replace") flag be used in that case? That would be a mis-use (semantically) of the "r" flag by the caller.

Vim stores 10 quickfix lists. Someone might use one quickfix list for grep results, another one for LSP, a third one for build errors, and so on. If you grep for "foo" and then later for "bar", the output will be completely unrelated and I wouldn't expect Vim to automatically set the current quickfix item to what it thinks is the best one. Sure, it could be useful but not always desirable.

Keep in mind that the quickfix list is a general purpose list that stores text locations. People use it for different purposes and have different workflows. LSP diagnostics is just one use case. That's why I suggested to add a boolean option like `'auto_idx'` (or `preserve_idx`, `preserve_location`, or whatever):

```vim
call setqflist({'items': my_new_list, 'preserve_idx': 1, 'id': my_qf_id})
```

**Comment by yegappan** [comment]
In most cases this is not the desired or expected behavior.  For example, I initially search for a pattern and populate the quickfix list with the results.  I jump to a particular search match and browse around the code.  Now if I do another search for another pattern, I expect the quickfix list to jump to the first matching result.

Also, changing the current setqflist() behavior will break backward compatibility and will surprise users who have used this for a long time.

**Comment by jfly** [comment]
> If you grep for "foo" and then later for "bar", the output will be completely unrelated and I wouldn't expect Vim to automatically set the current quickfix item to what it thinks is the best one.

> Now if I do another search for another pattern, I expect the quickfix list to jump to the first matching result.

Does [my PR](https://github.com/vim/vim/pull/15841) really break this workflow? How are you doing the search? If you're using `:vimgrep`, it'll create a new quickfix list (see [this comment](https://github.com/vim/vim/pull/15841#issuecomment-2405425729)).

> Also, changing the current setqflist() behavior will break backward compatibility and will surprise users who have used this for a long time.

Yes, I understand there's a chance of that. I suspect it's low. I beleve there are other, more semantically correct ways for people to achieve the behavior they want. See my comment here https://github.com/vim/vim/pull/15841#issuecomment-2405425729, complete with obligatory XKCD reference, and my offer to (reluctantly) implement a new option for this.

**Comment by chrisbra** [comment]
> Why would the "r" ("replace") flag be used in that case? That would be a mis-use (semantically) of the "r" flag by the caller.

I don't think so. Let's say I have erroneously created a quickfix list, but just noted after visiting several entries. I would use `r` because *scratch that, let's just replace the whole quickfix list and start from the beginning* and in that case *I want the cursor to be at the start of the list*

**Comment by crwebb85** [comment]
I think another good solution is to add a "u" action flag standing for "update" instead of a new option/parameter.  It could behave like "r" in that it doesn't add the old version of the list to the list history but will leave the selected entry the same.

Personally, I have a list of todo items in my config that I could easily complete with this feature, so I would be excited to see something like any of these proposals implemented.

**Comment by bfrg** [comment]
> Does https://github.com/vim/vim/pull/15841 really break this workflow? How are you doing the search? If you're using :vimgrep, it'll create a new quickfix list (see https://github.com/vim/vim/pull/15841#issuecomment-2405425729).

Yes, `:vimgrep`, `:grep` and `:make` create a new quickfix list after every invocation. But there are also other ways to populate a quickfix list, for example, by calling the command with `system()` or `job_start()` and then setting the quickfix list with `setqflist()`. This is necessary when you want to parse ripgrep's json output since Vim's `errorformat` is not suitable for that.

**Comment by jfly** [comment]
Makes sense. I've updated the PR with a new `keep_idx` option, so the default behavior will stay the same.

**Comment by benknoble** [comment]
> This is necessary when you want to parse ripgrep's json output since Vim's `errorformat` is not suitable for that.

Though ripgrep supports `--vim` or something quite similar for Vim-parseable output (I’ve never need to use the JSON output format).

**Comment by justinmk** [comment]
> I've updated the PR with a new `keep_idx` option,

What are the pros/cons of the ["u" flag](https://github.com/vim/vim/issues/15839#issuecomment-2405791174) , instead of `keep_idx` ?

**Comment by yegappan** [comment]
> > I've updated the PR with a new `keep_idx` option,
> 
> What are the pros/cons of the ["u" flag](https://github.com/vim/vim/issues/15839#issuecomment-2405791174) , instead of `keep_idx` ?

I like the 'u' flag approach to update the current quickfix list retaining the currently selected item instead of the 'keep_idx' item.

**Comment by jfly** [comment]
Implementation-wise, I think it's about equally complicated (not complicated).

Arguably the nice thing about `keep_idx` is that it will not crash when run on old versions of vim, whereas `'u'` would. I personally would rather have things crash so I know that I need to upgrade vim, though :p That said, given that we don't have a mechanism for feature sniffing, maybe it's unfair to do the `'u'` thing, because plugin authors won't feel like they can use it for many years.

**Comment by chrisbra** [comment]
I don't have a strong opinion about it. If people prefer the `u`. Then let's use this one please

**Comment by jfly** [comment]
I prefer `u`. I've updated #15841 accordingly. Side benefit: it ended up simplifying the code a tad.
