### ISSUE TITLE
Ctrl-v<Esc> in kitty produces trailing garbage

### ISSUE THREAD

**Issue by chdiza** [vim/vim#15868]
### Steps to reproduce

In the kitty terminal, do `vim --clean` and then do Ctrl-v<Esc>.

### Expected behaviour

I expect to see "^[" (a literal escape character).

What I actually see is "^[[27u".

I bisected and this has been there since 9.0.0930.

### Version of Vim

9.1.0781

### Environment

Debian 12.6, and I also see this on Linux Mint 21.1.

**Comment by chrisbra** [comment]
That is correct. You are seeing the kitty protocol result here. You may want to try `CTRL-SHIFT-V`, not sure if this works as expected for the kitty protocol

**Comment by chdiza** [comment]
CTRL-SHIFT-V does not produce the expected result.

**Comment by nickspoons** [comment]
By default CTRL-SHIFT-V pastes from clipboard in kitty

**Comment by chrisbra** [comment]
try to map it in this case:
```
imap <f5> <C-S-V>
```
Then go to insert mode and press `<f5>` followed by your key.

**Comment by cfillion** [comment]
I get the same behavior with the foot terminal: ^V Escape writes `^[[27;129u` in the buffer. Same with the F5 to `<C-S-V>` mapping above.

It works if I start vim with `TERM=xterm-256color` instead of using foot's terminfo. I tried with kitty: spoofing xterm solves it there too.

Neovim correctly produces `^[` even on foot `TERM=foot` or on kitty with `TERM=xterm-kitty`.

**Comment by chrisbra** [comment]
yeah, seems like this feature is missing for Kittys CSI u protocol 🤷

**Comment by chdiza** [comment]
The mapping trick does not work; same output.  Also, same output if I disable the kitty mapping of <C-S-V> to copy-to-clipboard.

**Comment by chdiza** [comment]
Vim also doesn't play nice with kitty when using the numberpad on right-hand side of a keyboard.  I'll file a separate bug for that.
