### ISSUE TITLE
css background-position [runtime][syntax]

### ISSUE THREAD

**Issue by nenesses** [vim/vim#15968]
css.vim line 163:
syn match cssBackgroundProp contained "\<background\(-\(attachment\|clip\|color\|image\|origin\|position\(-[xy]\)\|repeat\|size\)\)\=\>"

to match background-position-x and background-position-y

**Comment by chrisbra** [comment]
I find it really hard what this issue is about. Should this be a patch or a bug? 

Please take your time and create a proper issue report clearly explaining what your issue is and what you are suggesting. Also please check [Contributing.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md) in particular https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files which suggests, this should be rather directed to https://github.com/vim-language-dept/css-syntax.vim or at least ping the maintainer: @jsit 

Thanks for understanding.
