### ISSUE TITLE
Please revert 8e6b503

### ISSUE THREAD

**Issue by chdiza** [vim/vim#16030]
### Steps to reproduce

Commit 8e6b503 makes latex highlighting awful.

Put this in a latex doc: `One two $34 + 18$`.

### Expected behaviour

Note that the 3 and the 1 are a different color than the 4 and the 8.  The first pair belong to TexMathNumber, and the second pair belong to TexMathZoneX.

So that commit is badly buggy, but I don't understand the motivation behind the patch in the first place.  It looks like it was accepted with no argument made in favor of it.  There is no reason for numbers to be colored differently.

### Version of Vim

9.1.0849

### Environment

Linux Mint 21.3.
Terminal: kitty

**Comment by habamax** [comment]
I might be doing something wrong, but can't see anything bad:

ft=tex
![image](https://github.com/user-attachments/assets/7bbe7b8b-ab18-487e-b5db-c0c36994ef67)

ft=plaintex
![image](https://github.com/user-attachments/assets/345d686d-bcb7-434f-b1f5-fc2b46b7d6d2)

**Comment by habamax** [comment]
and again regular `ft=tex` with default tex flavor:

![image](https://github.com/user-attachments/assets/67784c93-eba4-4d8b-8563-876575fe339b)

**Comment by chrisbra** [comment]
I also see it:
![grafik](https://github.com/user-attachments/assets/b9e256bb-2f54-4333-9448-289fe07fc1e9)

I'll revert it.

> So that commit is badly buggy, but I don't understand the motivation behind the patch in the first place. It looks like it was accepted with no argument made in favor of it. There is no reason for numbers to be colored differently.

That's a bit an unfair assessment. That commit was sitting in the PR queue (#11271) for 2 years, without any comment. Nobody commented or complained and you cannot seriously expect me to test all kind of syntax scripts before including it (especially if I am not using that particular filetype and we don't have any maintainer).  Since i did not get any negative comments I included it, when cleaning up the queue.

**Comment by k-takata** [comment]
```vim
syn match texMathNumber "\<\d\|\.\d" contained
```

Maybe the pattern should have been `"\<\d\+\>\|\.\d\+\>"` or a similar one?

**Comment by chrisbra** [comment]
when merging I also wondered about potential sign flag. Let's leave it now

**Comment by chdiza** [comment]
I certainly don't expect you to test all kinds of little things like this.  I didn't see that PR.  At the time it was made, if I'd seen it I would've assumed that Charles Campbell would shoot it down.
