### ISSUE TITLE
Error in Thesaurus logic

### ISSUE THREAD

**Issue by chew-z** [vim/vim#1611]
The built-in thesaurus function returns wrong results. Instead of list of synonyms it is returning (very log) list of fuzzy words.

Steps to reproduce the error:

- Download thesaurus file from [Moby Project](http://icon.shef.ac.uk/Moby/) 
- Convert to proper format `perl -ple 's/\r?\n|\r/\n/g' mobythes.aur > mobythes.txt`
- Point vim to mobythes.txt `set thesaurus+=/home/jsmith/mobythes.txt`
- Open new file in vim, enter insert mode, type word 'return' and press `<C-x><C-t>`

The result is a very long list of words as in the screenshot (3045 words). 

<img width="609" alt="screen shot 2017-04-01 at 20 25 15" src="https://cloud.githubusercontent.com/assets/2264679/24578757/b8c23aea-1719-11e7-8045-51e407bf81ef.png">

This is not correct result. To see what should be the correct result open mobythes.txt file in Vim and do `/^return`. You will find a line which is containing expressions (not single words) separated by commas(there is 415 of them not 3 thousand). They are synonyms to 'return' which is first word in this line. They should be presented each as a single entry.

```
return,CRT spot,DM display,Doppler signal,IF signal,IM display,RF echoes,about-face,acknowledge,acknowledgment,action and reaction,advent,advert,afford,alternate,alternation,amends,answer,answer back,answering,antiphon,arrival,
...
wheel around,winnings,witty reply,witty retort,yes-and-no answer,yield
```

Apparently Vim is returning all single words from all lines containing word `return`.  And this is wrong result.

That's it.

If you continue with these error reproduction steps and delete the last character you suddenly get much shorter list. I don't understand where these results come from. But this behaviour isn't  necessarily a bug.

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2017 20:20:13)
MacOS X (unix) version
Included patches: 1-525
```

**Comment by brammool** [comment]
The format of that file is not what is expected.  The thesaurus option expects words separated by non-word characters.  This file has comma separated terms, which can include a space.
Also, the lines are too long, Vim only supports up to 512 characters.
Also also, Vim uses all lines where the word matches, while the intention of the file is to only match the first word.

Making this work requires a different implementation of the thesaurus implementation.

**Comment by chew-z** [comment]
Oouh, that explains the _"wrong"_ results I have been getting. I am sorry.

However the idea of thesaurus is that both input and output could be multiple words. We have different synonyms for "return", "return to" and "tax return". And results could be multiple words as well (up to 7 words in Moby Thesaurus).

Narrowed down and more relevant results would make thesaurus way more useful.

Moby Thesaurusu is free and the largest. People following [guide like this](https://smileykrish.wordpress.com/2011/09/24/enable-thesaurus-in-vim/) or [this](http://www.thegeekstuff.com/2008/12/vi-and-vim-editor-3-steps-to-enable-thesaurus-option) and getting useless results. [There is some frustration bubbling on the Internet](https://www.reddit.com/r/vim/comments/55y53e/allow_spaces_in_thesaurus_entries/) about the current thesaurus login in VIM.

**Comment by brammool** [comment]
> Oouh, that explains the _"wrong"_ results I have been getting. I am sorry.
> 
> However the idea of thesaurus is that both input and output could be multiple words. We have different synonyms for "return", "return to" and "tax return". And results could be multiple words as well (up to 7 words in Moby Thesaurus).
> 
> Moby Thesaurusu is free and the largest. [There is some frustration bubbling on the Internet](https://www.reddit.com/r/vim/comments/55y53e/allow_spaces_in_thesaurus_entries/) about the current thesaurus login in VIM.

It would be a bit of work to support the comma-separated format.
Perhaps entries in 'thesaurus' could have the addition "@comma", so that
the format is specified per file.

Would also have to fix the fixed maximum line length.

-- 
hundred-and-one symptoms of being an internet addict:
255. You work for a newspaper and your editor asks you to write an
     article about Internet addiction...in the "first person."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
using the link provided in `:h thesaurus` ([https://github.com/vim/vim/issues/629#issuecomment-443293282](url)) i am encountering the error described by chew-z when this issue was initially opened:
![notworking](https://user-images.githubusercontent.com/52256543/61001938-6d020380-a315-11e9-9834-4fabad024489.png)

in order to diagnose the issue i created an extremely simple thesaurus file, and the completion seems to _mostly_ work:
![working](https://user-images.githubusercontent.com/52256543/61002744-1a294b80-a317-11e9-9e73-bd3d9794666b.png)

- is it intended that words on the lines following the line that begins with our word be in the completion list?
- `:h thesaurus` mentions "Each line in the file should contain words with similar meaning, separated by non-keyword characters (white space is preferred)."
  - does this mean that there are other "non-keyword characters" that can be used aside from white space?
  - if so, could it be possible to include phrases (with white space) in our list of similar words?
- why is the provided thesaurus file not working correctly? from what i can tell it is formatted exactly as my test thesaurus is
- if it is a matter of formatting, how exactly should the file be formatted?
 
thanks

**Comment by ghost** [comment]
poking around some more, if my file is formatted correctly, then i think my second screen shot is unintended behavior:

>     CTRL-X CTRL-T
> 
>     Works as CTRL-X CTRL-K, but in a special way. It uses
>     the 'thesaurus' option instead of 'dictionary'. If a
>     match is found in the thesaurus file, all the
>     remaining words on the same line are included as
>     matches, even though they don't complete the word.
>     Thus a word can be completely replaced.

_the remaining words **on the same line** are included as matches_

if my file is incorrectly formatted please let me know. 
if that is the issue then `h: thesaurus` is not very clear

**Comment by lacygoill** [comment]
Can this issue be closed?

Since the patch [8.2.3520](https://github.com/vim/vim/releases/tag/v8.2.3520), Vim provides [`:help 'thesaurusfunc'`](https://vimhelp.org/options.txt.html#%27thesaurusfunc%27) which gives much more control over the suggestions given by `C-X C-T`, and which can be leveraged to bypass all the issues mentioned in the OP.

There is an example at [`:help compl-thesaurusfunc`](https://vimhelp.org/insert.txt.html#compl-thesaurusfunc).  It relies on `aiksaurus(1)`.  If for some reason, the OP really want to use a file instead, here is how they can get the desired results:
```vim
vim9script

var synonyms_file: string = '/tmp/synonyms.txt'
&thesaurus = synonyms_file
var lines: list<string> =<< trim END
    return,CRT spot,DM display,Doppler signal,IF signal,IM display,RF echoes,about-face,acknowledge,acknowledgment,action and reaction,advent,advert,afford,alternate,alternation,amends,answer,answer back,answering,antiphon,arrival
    wheel around,winnings,witty reply,witty retort,yes-and-no answer,yield
END
lines->writefile(synonyms_file)

&thesaurusfunc = 'Thesaurusfunc'
def g:Thesaurusfunc(findstart: bool, base: string): any
    if findstart
        return searchpos('\<', 'bnW', line('.'))[1] - 1
    endif
    var l: list<string> = synonyms_file->readfile()
    if l->empty() | return [] | endif
    var idx: number = lines->match('^' .. base)
    if idx == -1 | return [] | endif
    var synonyms: list<string> = lines[idx]->split(',')
    return synonyms
enddef
```

**Comment by lacygoill** [comment]
I think all these todo items can be removed:

   > Many users don't like 'thesaurus' to match so many words. (#4667, #1611)
   > - when the match with the first word is partial, don't add other words on that
   >   line.
   > - support other file formats, such as comma separated.  Indicate by a prefix
   >   to the file in the 'thesaurus' option.
   > - 'threglookexp' option: only match with first word in thesaurus file.
   >   (Jakson A. Aquino, 2006 Jun 14)

lines 661-667 in `runtime/doc/todo.txt`.

`'thesaurusfunc'` can be used instead to get the same results.
