### ISSUE TITLE
compiler eslint now depends on an external formatter

### ISSUE THREAD

**Issue by johnridesabike** [vim/vim#16126]
https://github.com/vim/vim/blob/7e501f4d9986866382888e67d8f11faf5767c8f4/runtime/compiler/eslint.vim#L12

Running this `makeprg` configuration returns this message:
```
The compact formatter is no longer part of core ESLint. Install it manually with `npm install -D eslint-formatter-compact`
```

One can always install the `eslint-formatter-compact` package to use `compiler eslint` again, but it would be nice if it could work with only `eslint` installed like it did before ESLint made this change.

Here are the formatters that ESLint now includes built-in: https://eslint.org/docs/latest/use/formatters/

**Comment by chrisbra** [comment]
@romainl are you up to remove the `--format compact` thing then? Or put it behind a configuration var?

**Comment by romainl** [comment]
Well, the compiler in its current incarnation is only useful because the `compact` format is easy to parse with `errorformat`. Now that it is no longer distributed with eslint, both `makeprg` **and** `errorformat` are wrong and the compiler has become pretty much useless (unless you install that extra package).

I think that we have only one option, here: write a proper `errorformat` for the default `stylish` format. There is one [here](https://www.reddit.com/r/vim/comments/ibo5e1/sharing_some_errorformats/) (untested) that we could use with the authorization of the author of the post.

**Comment by romainl** [comment]
Actually, I just tested it and it seems to work pretty well. I asked the author to join this conversation. We will see.

**Comment by sparkcanon** [comment]
Glad my errorformat is useful. Happy for it to be used 👍🏼

**Comment by chrisbra** [comment]
then can any of you please create a PR fix please?

**Comment by romainl** [comment]
Yes, I will do in the next couple of days.
