### ISSUE TITLE
'w0', 'w$' position are wrong when screen is invalid since v8.0.515

### ISSUE THREAD

**Issue by haya14busa** [vim/vim#1613]
Hi! I updated Vim and I noticed that a test for my plugin failed with breaking and maybe unexpected behavior change of line('w0') and line('w$').

#### v8.0.515 and above (HEAD, v8.0.515)

```
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
[0, 0, 1, 0] [0, -1, 1, 0]
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
[0, 1, 1, 0] [0, 0, 1, 0]
```

#### Before v8.0.514 (v8.0.514) (Expected behavior)

```
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
[0, 1, 1, 0] [0, 1, 1, 0]
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
[0, 1, 1, 0] [0, 42, 1, 0]
```
(The number "42" depends on the terminal height )

As I showed above, line('w0') and line('w$') value changed since [v8.0.515](https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38) with `vim -e -s ...`.
(Without `-s` flag, it works as expected)

Here is the problematic line.  https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38#diff-730e42441ff982fa04a4df341a0c3e24L180
`!screen_valid(TRUE)` check changed.

We can fix this issue by simply revering this change, but it also means the problem patch 8.0.0515 fixed happens again too, so I cannot figure out how to fix it.

## Vim Version

8.0.515 and above

**Comment by brammool** [comment]
haya14busa wrote:

> Hi! I updated Vim and I noticed that a test for my plugin failed with breaking and maybe unexpected behavior change of line('w0') and line('w$').
> 
> ### How To Reproduce
> 
> #### v8.0.515 and above (HEAD, v8.0.515)
> 
> ```
> $ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
> [0, 0, 1, 0] [0, -1, 1, 0]
> $ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
> [0, 1, 1, 0] [0, 0, 1, 0]
> ```
> 
> #### Before v8.0.514 (v8.0.514) (Expected behavior)
> 
> ```
> $ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
> [0, 1, 1, 0] [0, 1, 1, 0]
> $ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
> [0, 1, 1, 0] [0, 42, 1, 0]
> ```
> (The number "42" depends on the terminal height )
> 
> As I showed above, line('w0') and line('w$') value changed since [v8.0.515](https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38) with `vim -e -s ...`.
> (Without `-s` flag, it works as expected)
> 
> Here is the problematic line.  https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38#diff-730e42441ff982fa04a4df341a0c3e24L180
> `!screen_valid(TRUE)` check changed.
> 
> We can fix this issue by simply revering this change, but it also
> means the problem patch 8.0.0515 fixed happens again too, so I cannot
> figure out how to fix it.
> 
> ## Vim Version
> 
> 8.0.515 and above

Well, in silent Ex mode there isn't really any display.  So the previous
results were already wrong.

Returning a zero line number doesn't make sense though, getpos('w0') can
return line one, which is the first line, even with an empty buffer.

Then for getpos('w$') we return the last visible line.  But there isn't
one.  This would also happen for a window that has been reduced to zero
height.  To remain consistent with tools that compute the number of
lines, it should return one less that 'w0'.  Thus the results become:

	 [0, 1, 1, 0] [0, 0, 1, 0]

No matter what you put in the buffer.  I'll make a patch for that.

It won't fix your test.  I would argue that relying on any visible
information while in silent Ex mode was wrong, since it's silent and the
display is not updated.

-- 
Two fish in a tank. One says to the other:
"Do you know how to drive this thing?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
