### ISSUE TITLE
recognize trailing comment markers in modeline instead of throwing error message

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#1648]
To set the filetype to `xml` for a file `file.xml`, append
```xml
<!-- vim:filetype=xml -->
```
to `file.xml`. With `modeline` set, `:edit file.xml` gives the error message
```vim
E518: Unknown option: -->
```

Vim should infer by the commentstring option that 
```vim
commentstring=<!--%s-->
``` 
and therefore that `-->` is the closing comment marker, and not a modeline setting.

**Comment by grochmal** [comment]
Well:

> Vim should infer by the commentstring option that

`:h commentstring`

> Currently only used to add markers for folding, see |fold-marker|.

Therefore no, it doesn't.

And according to `:h modeline`

```
There are two forms of modelines.  The first form:
	[text]{white}{vi:|vim:|ex:}[white]{options}

(...)

Examples:
   vi:noai:sw=3 ts=6 ~
   vim: tw=77 ~

The second form (this is compatible with some versions of Vi):

	[text]{white}{vi:|vim:|Vim:|ex:}[white]se[t] {options}:[text]

(...)

Examples:
   /* vim: set ai tw=75: */ ~
   /* Vim: set ai tw=75: */ 
```

you have two options, either

    

or

    

Which is more compatible anyway (the later form, that is).

Also, this probably should be in `vim_users` mailing list or `vi.stackexhange.com`.  Not an issue on github (and be closed here).

On the other hand, it could be an interesting feature to add to Vim.  But not sure if it is worth the effort that could be placed elsewhere (since this is completely workable with the options above).

**Comment by brammool** [comment]
The 'commentstring' option can only be set after detecting the filetype, thus it can't be used for the modeline.

**Comment by Konfekt** [comment]
For example, the markdown comment `[//]: # ( vim: spell:spelllang=en: )` still produces the error message:

```vim
Error detected while processing modelines:
line  309:
E518: Unknown option: )
```

**Comment by Konfekt** [comment]
I am sorry, the `set` makes the difference. I thought it was about the trailing `:`. It's fine.
