### ISSUE TITLE
guicursor hidden behavior

### ISSUE THREAD

**Issue by Shougo** [vim/vim#1657]
Vim: 8.0.586 with GTK2 GVim
Linux: Ubuntu Linux 16.04

Reproduce ways from Vim starting:

* In first, `gvim -u NONE -U NONE --noplugin`

* Next, `:set guicursor=a:blinkon0`

* You can see that the cursor exists but no blinking (intended behavior)

* Next, `:set guicursor=a:hl-None`

* You can see that the cursor is hidden (Intended behavior)

* Next, `:set guicursor=a:blinkon0`

* You can see that the cursor is hidden (Not intended behavior)

*  Next, `:set guicursor=`

* You can see that the cursor is hidden (Not intended behavior)

*  Next, `:set guicursor&`

* You can see that the cursor exists and blinking (Intended behavior)

**Comment by vim-ml** [comment]
Hi,

It's not a bug.

2017-4-25(Tue) 10:51:24 UTC+9 Shougo:
> Vim: 8.0.586 with GTK2 GVim
> 
> Linux: Ubuntu Linux 16.04
> 
> Reproduce ways from Vim starting:
> 
> 
> 
> In first, gvim -u NONE -U NONE --noplugin
> 
> 
> 
> Next, :set guicursor=a:blinkon0
> 
> 
> 
> You can see that the cursor exists but no blinking (intended behavior)
> 
> 
> 
> Next, :set guicursor=a:hl-None

Do you understand what you are doing on the setting above?
You specify `hl` and `None` highlight group names that do not exist.
That is, it means that the highlight which hidden the cursor is set.
In addition, you have not set `syntax on '.

> 
> 
> 
> You can see that the cursor is hidden (Intended behavior)
> 
> 
> 
> Next, :set guicursor=a:blinkon0
> 
> 
> 
> You can see that the cursor is hidden (Not intended behavior)

No. It's expected.
Since you are only setting blinks, the highlight setting remains the same as before. (That is, a hidden state)

> 
> 
> 
> Next, :set guicursor=
> 
> 
> 
> You can see that the cursor is hidden (Not intended behavior)

Also expected.
As usual, highlight setting is not done so it is the same as above.

> 
> 
> 
> Next, :set guicursor&
> 
> 
> 
> You can see that the cursor exists and blinking (Intended behavior)

Here, the default value including the highlight setting is set at last, so the cursor becomes visible.


See document (:h 'guicursor' and 79j)
	The 'a' mode is different.  It will set the given argument-list for
	all modes.  It does not reset anything to defaults.  This can be used
	to do a common setting for all modes.  For example, to switch off
	blinking: "a:blinkon0"


--
Best regards,
Hirohito Higashi (h_east)

**Comment by Shougo** [comment]
```
See document (:h 'guicursor' and 79j) The 'a' mode is different. It will set the given argument-list for all modes. It does not reset anything to defaults. This can be used to do a common setting for all modes. For example, to switch off blinking: "a:blinkon0"
```

OK, I get it.  I have not read the section.
It does not bug.
