### ISSUE TITLE
Bug cursor

### ISSUE THREAD

**Issue by gHashTag** [vim/vim#1673]
Why is the cursor buggy in some places?

![vim mov](https://cloud.githubusercontent.com/assets/6774813/25636537/53fdd95a-2f8a-11e7-87da-9c7c2d9153b5.gif)

**Comment by chrisbra** [comment]
Are you using a plugin that enable ligatures?

**Comment by gHashTag** [comment]
@chrisbra I don't no. My .vimrc
____________________________________
call plug#begin('~/.vim/plugged')

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'Valloric/YouCompleteMe'
Plug 'jiangmiao/auto-pairs'
Plug 'easymotion/vim-easymotion'
Plug 'altercation/vim-colors-solarized'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript' 
Plug 'jelera/vim-javascript-syntax'
Plug 'othree/yajs'
Plug 'bling/vim-airline'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/syntastic'
Plug 'mtscout6/syntastic-local-eslint.vim'
Plug 'flowtype/vim-flow'
Plug 'majutsushi/tagbar'
Plug 'elzr/vim-json'
Plug 'scrooloose/nerdcommenter'

" Initialize plugin system

call plug#end()  

" Mappings
map <C-n> :NERDTreeToggle <CR> 
map <Leader> <Plug>(easymotion-prefix)
map  <Leader>w <Plug>(easymotion-bd-w)
:imap jj <Esc>
:imap оо <Esc> 
nmap <F8> :TagbarToggle<CR>

" Color Settings
set t_Co=256
syntax enable
let g:solarized_termtrans = 1                                                   
let g:solarized_termcolors=256                                                  
set background=dark
colorscheme solarized

" JSX syntax
let g:xml_syntax_folding = 1
let g:jsx_ext_required = 0

" Airline
set laststatus=2

" Settings
set number
set expandtab
set tabstop=4
vnoremap < <gv
vnoremap > >gv
set shiftwidth=2         " в командах отступа используется # пробелов 
"Tagbar
let g:tagbar_ctags_bin='/usr/local/bin/ctags'

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
" enable syntastic for javascript files
let g:syntastic_javascript_checkers = ['eslint','flow']
let g:syntastic_javascript_flow_exe = 'flow'

**Comment by chrisbra** [comment]
well, then please try to reproduce with a minimal vimrc

**Comment by gHashTag** [comment]
Completely removed everything from vimrc and the same mistake
![vim1 mov](https://cloud.githubusercontent.com/assets/6774813/25638562/81c29554-2f91-11e7-8389-34b3a97513e3.gif)

**Comment by chrisbra** [comment]
what terminal and font is this?

**Comment by gHashTag** [comment]
macVim
ansi
font: Ayuthaya

**Comment by gHashTag** [comment]
Mmmm... This bug only this theme: http://ethanschoonover.com/solarized

**Comment by chrisbra** [comment]
could this be macvim specific? i googled around and it seems to happen with the macos font renderer. Try setting nomacligatures. However, I don't think this is a valid bug report for vim.

**Comment by nuko8** [comment]
Since this issue also applies to the GTK+ GUIs, let me leave a note on that.

Vim is written to work with monospace fonts, and computations for positioning glyphs, highlighted rectangles of selections, and the cursor are all done based on that assumption.  Therefore, when a user sets `guifont` to a font other than a monospace one, any glitch like this issue's can happen.

MacVim and the GTK GUIs leave rendering to an external framework/library which is even capable to handle non-monospace fonts.   Of course, that doesn't mean that the Vim core knows how to handle them correctly.  That's why the cursor rendering appeared to be buggy; that was actually due to a disagreement on glyph/cursor positions between the Vim core and the external framework/library.

According to `FontBook.app`, Ayuthaya is not included in the Fixed Width list ("fixed width" is a synonym of monospace).  This is the cause of that buggy cursor behavior.

So, to avoid any trouble like this issue's, please select a monospace or fixed-width font for GVim.

**Comment by gHashTag** [comment]
Changed to Monaco font and it all worked!
