### ISSUE TITLE
':hardcopy >' mistreats spaces when expanding Ex special characters (%)

### ISSUE THREAD

**Issue by alexeymuranov** [vim/vim#1682]
If i open a file named `t e s t.txt` in Vim and print it to a PostScript file with `:ha > %.ps`, instead of `t e s t.txt.ps`, i get a PostScript file named `t\ e\ s\ t.txt.ps`.

This is with Vim 8.0.85.

**Comment by chrisbra** [comment]
Hm,
I think this patch fixes it:
```patch
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index d0df1fd9f..206a230e2 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -5042,6 +5042,7 @@ expand_filename(
                && eap->cmdidx != CMD_lgrep
                && eap->cmdidx != CMD_grepadd
                && eap->cmdidx != CMD_lgrepadd
+               && eap->cmdidx != CMD_hardcopy
 #ifndef UNIX
                && !(eap->argt & NOSPC)
 #endif
```

**Comment by alexeymuranov** [comment]
So, is this fixed? In which version?

**Comment by nuko8** [comment]
@alexeymuranov 

> So, is this fixed? In which version?

No, it isn't yet.  What @chrisbra is actually doing with his post and patch is, not being pushy to anyone, to ask people to try his patch with their own environment and report back the result here.  Since the issue is related to file system and thus platform-dependent, we need to make sure as much as possible that the patch works equally well for every platform Vim supports.  For that purpose, we definitely need people's broad, voluntary cooperation as well as yours.  Though we know a post written in that way sometimes puzzles some people, and that we sometimes have  little cooperation through it, we still prefer it for the sake of brevity, as seen in common with other OSS dev communities.

@chrisbra For my macOS, I confirm that your patch works fine and fixes the issue.

**Comment by alexeymuranov** [comment]
If i understand the idea of the patch correctly, it introduces some special treatment of `:hardcopy`. This seams a bit strange to me: `:write %.backup` works correctly without such special treatment.
