### ISSUE TITLE
Undo files may have the +x bit set

### ISSUE THREAD

**Issue by LemonBoy** [vim/vim#1711]
No matter how careful `undo.c` during the creation of a new undo file, when the ACL entry is [copied](https://github.com/vim/vim/blob/master/src/undo.c#L1753,L1758) over from the original file no checks are done about the `+x` bit being set: editing an executable file has the unwanted side effect of creating an executable permanent undo file.

**Comment by brammool** [comment]
LemonBoy wrote:

> No matter how careful `undo.c` during the creation of a new undo file, when the ACL entry is [copied](https://github.com/vim/vim/blob/master/src/undo.c#L1753,L1758) over from the original file no checks are done about the `+x` bit being set: editing an executable file has the unwanted side effect of creating an executable permanent undo file.

I cannot reproduce this.  What system?

-- 
To keep milk from turning sour: Keep it in the cow.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LemonBoy** [comment]
Linux. You need the permanent undo feature to be set and a valid `undodir`.

**Comment by brammool** [comment]
> Linux. You need the permanent undo feature to be set and a valid `undodir`.

I have set 'undodir' and edit an executable text file.  The undo
file is not executable. This is on Ubuntu

-- 
How come wrong numbers are never busy?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LemonBoy** [comment]
I'm able to consistently reproduce this with the following `vimrc`:

```viml
set undodir=/tmp/undo
silent! call mkdir(&undodir, 'p')
set undofile
```

Opening an executable file, making a change and then saving the file with a breakpoint set on the call to `mch_set_acl` shows that _before_ the call is made the resulting file is `-rw-r--r--` and right _after_ the call it becomes `-rwxr-xr-x` and that matches the permissions of the file being edited.

**Comment by grochmal** [comment]
Decided to look into it and could reproduce on current Arch Linux.  That said Vim performs the correct action in the `open()` call.  I used the `vimrc` provided by @LemonBoy and edited an executable.  I have `strace`'d the calls into a file called `strace.log` and could see the following:

```
$ grep 'open(' strace.log  | grep -i creat
open(".a.out.swp", O_RDWR|O_CREAT|O_EXCL, 0600) = 6
open(".a.out.swx", O_RDWR|O_CREAT|O_EXCL, 0600) = 7
open(".a.out.swp", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW, 0600) = 6
open("a.out~", O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW, 0755) = 5
open("a.out", O_WRONLY|O_CREAT|O_TRUNC, 0755) = 3
open("/tmp/undo/%home%grochmal%tmp%a.out", O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW, 0644) = 3
```

Therefore Vim is correctly using `0644` when creating the file.  But when I go look for it:

```
$ ls -ltr /tmp/undo/
total 8
-rwxr-xr-x 1 grochmal users 2187 May 19 23:01 %home%grochmal%tmp%a.out
```

The suspicion then falls on the following that I found in the same trace (just like LemonBoy points):

```
$ grep xattr strace.log 
getxattr("a.out", "system.posix_acl_access", 0x7fff3efa75d0, 132) = -1 ENODATA (No data available)
setxattr("a.out~", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
getxattr("/home/grochmal/tmp/a.out", "system.posix_acl_access", 0x7fff3efa73d0, 132) = -1 ENODATA (No data available)
setxattr("/tmp/undo/%home%grochmal%tmp%a.out", "system.posix_acl_access", "\2\0\0\0\1\0\7\0\377\377\377\377\4\0\5\0\377\377\377\377 \0\5\0\377\377\377\377", 28, 0) = 0
```

The `\7` , `\5` and `\5` in there stand for (as expected) the `0755` permission set.  If I edit a non executable file with the same `vimrc` I get a different `xattr` update on the file.  For example:

```
$ echo yay > yay
$ $ strace -o strace2.log vim -u newvimrc yay
# (i edit the file and save it)
$ ls -ltr /tmp/undo/
total 12
-rwxr-xr-x 1 grochmal users 2187 May 19 23:01 %home%grochmal%tmp%a.out
-rw-r--r-- 1 grochmal users  529 May 19 23:23 %home%grochmal%tmp%yay
$ grep xattr strace2.log 
getxattr("yay", "system.posix_acl_access", 0x7ffebeabf860, 132) = -1 ENODATA (No data available)
setxattr("yay~", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\4\0\4\0\377\377\377\377 \0\4\0\377\377\377\377", 28, 0) = 0
getxattr("/home/grochmal/tmp/yay", "system.posix_acl_access", 0x7ffebeabf660, 132) = -1 ENODATA (No data available)
setxattr("/tmp/undo/%home%grochmal%tmp%yay", "system.posix_acl_access", "\2\0\0\0\1\0\6\0\377\377\377\377\4\0\4\0\377\377\377\377 \0\4\0\377\377\377\377", 28, 0) = 0
```

And we have the correct `\6`, `\4`, `\4` set of permissions in there.

The issue happens in `mch_copy_sec` in `os_unix.c`, since it is the only place that calls `setxattr` / `removexattr`.  I believe it happens in the call to `removexattr` since that is implemented by `gblic` as a call to `setxattr`.  i.e. [here in the github repo](https://github.com/vim/vim/blob/master/src/os_unix.c#L2870).  This happens in the `ENODATA` condition (errno) which we see in the `strace` log above.

Not sure how to fix it though.  Probably if the call to `mch_copy_sec` is removed altogether from `undo.c`, i.e. [here in the gihub repo](https://github.com/vim/vim/blob/master/src/undo.c#L1667) the problem will not happen anymore.  Yet, that will likely break SELinux.

Maybe add something like this at the top of `mch_copy_sec`:


```
     if (from_file == NULL)
	 return;

+    size = listxattr((char *)from_file, NULL, 0);
+    if (size == 0)
+	 return;
+
     for (index = 0 ; index < (int)(sizeof(smack_copied_attributes)
			       / sizeof(smack_copied_attributes)[0]) ; index++)
     {
```

Basically, when there are no extended attributes that are not the default ACL (old-school unix one, i.e. the one used by `chmod`) then bail early .  That should be most of the time on most distros.  0 return from `listxatrr` means zero extended attributes on the file, unless something very funky is being used.

But that's quite horrible and dirty.  It would stop the issue appearing on non-SElinux enabled Linux, but would make the issue exist on ACL enabled filesystems and boxes running SELinux.

The proper solution would be (probably) to go through the entire procedure of dealing with the ACL permissions, i.e. load the extended permissions into memory, modify them using the `acl_*` functions to remove the executable bits and write that to the undo file.  Yet, I do not know if this "proper" solution would actually work.  Interactions between ACL and SELinux are quite dirty in the best perspectives.  Not sure if it is worth pursuing this proper solution.

A binary under SELinux should never run if it has been modified in the first place.  Therefore, I believe that having a bug that will dump the undo file as executable under SELinux and as `0644` if not under SELinux should be fine.  The only extra issue would probably be when someone adds extra `xattr`s that are neither part of SELinux or ACL.

**Comment by CervEdin** [comment]
Is there any way to get around this?

**Comment by chrisbra** [comment]
the patch by @grochmal seems correct. can someone turn that into a proper PR please?
