### ISSUE TITLE
setglobal for buffer-local options doesn't apply to buffers opened for file arguments?

### ISSUE THREAD

**Issue by jacknagel** [vim/vim#1712]
I ran into what seems like a bug when setting the global value of a buffer-local option from my .vimrc. 

If I invoke vim this way:

```
vim -N -i NONE -u NONE -c "setglobal autoindent" -- file
```

I would expect the buffer for `file` to have `autoindent` set, but `:set autoindent?` returns `noautoindent`.

However, if I invoke vim without a file argument,
```
 vim -N -i NONE -u NONE -c "setglobal autoindent"
```

and instead open it using `:e file`, then `:set autoindent?` returns `autoindent`, as expected.

Is this a bug? The above inconsistency, as well as the following excerpts from the help, would seem to suggest that it is.

```
When editing a new buffer, its local option values must be initialized.  Since
the local options of the current buffer might be specifically for that buffer,
these are not used.  Instead, for each buffer-local option there also is a
global value, which is used for new buffers.  With ":set" both the local and
global value is changed.  With "setlocal" only the local value is changed,
thus this value is not used when editing a new buffer.

...

For buffer-local and window-local options:
        Command          global value       local value
      :set option=value      set                set
 :setlocal option=value       -                 set
:setglobal option=value      set                 -
      :set option?            -                display
 :setlocal option?            -                display
:setglobal option?          display              -
```

I'm using vim 8.0.596, and also tested 7.4.898.

Thanks.

**Comment by vim-ml** [comment]
On Thursday, May 18, 2017 at 11:54:11 AM UTC-5, Jack Nagel wrote:
> I ran into what seems like a bug when setting the global value of a buffer-local option from my .vimrc.
> 
> If I invoke vim this way.
> vim -N -i NONE -u NONE -c "setglobal autoindent" -- file
> 
> 
> I would expect the buffer for file to have autoindent set, but :set autoindent? returns noautoindent.
> 
> However, if I invoke vim without a file argument,
> vim -N -i NONE -u NONE -c "setglobal autoindent"
> 
> 
> and instead open it using :e file, then :set autoindent? returns autoindent, as expected.
> 

Per the help, "-c" runs a command "after the first file has been read (and after autocommands and modelines for that file have been processed)." So you cannot affect the first file using -c.

However, Vim also provides the "--cmd" argument, which "will be executed before processing any vimrc file." Try using that instead, it seems to work for me.

**Comment by jacknagel** [comment]
Ah. You're right about `-c` of course. I was attempting to simplify my example. However, I do still see this behavior if I use `setglobal` in a vimrc file. Given

```
$ cat vimrc
setglobal autoindent
$ vim -N -i NONE -u vimrc -- file
```

I think the buffer for `file` should have `autoindent` set, but it doesn't.

**Comment by dm1try** [comment]
@jacknagel has the issue been resolved?

**Comment by dlukes** [comment]
I think this is a consequence of how the startup sequence works (see `:help startup`). Buffers are created in step 2, before the vimrc is loaded in step 3. So there are no global values to inherit in step 2 yet.

By contrast, if you just start Vim without arguments and then do `:edit ...`, the buffer is loaded only after Vim has been fully initialized and inheriting global options works as expected.

Not sure if this is intended behavior, or a bug that users rarely hit because everyone overwhelmingly uses `set` (which sets both the global and the local value, hiding the issue) rather than `setglobal`.

It's a bit unfortunate though, because if you `:source $MYVIMRC` after applying updates, options set with `set` will override any customized local ones in the current buffer, which is probably not what you intended. `setglobal` doesn't do this and would be the better option for vimrc IMHO, if it weren't for this sequencing problem.
