### ISSUE TITLE
suggestion files on http://ftp.vim.org/vim/runtime/spell/

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#1744]
There are no suggestion files (`*.sug`) for Italian or Portuguese for example on http://ftp.vim.org/vim/runtime/spell/. 

However, at some point there was one for Portuguese, because there is one in `~/.vim/spell`. How come it was taken down? 

Are they available elsewhere?

**Comment by brammool** [comment]
Konfekt wrote:

> There are no suggestion files (`*.sug`) for Italian or Portuguese for example on http://ftp.vim.org/vim/runtime/spell/. 
> 
> However, at some point there was one for Portuguese, because there is one in `~/.vim/spell`. How come it was taken down? 
> 
> Are they available elsewhere?

There is no .sug file for Italian, because it's disabled in the .aff
file:  

	# Building the soundfold tree takes too much memory, skip it.
	NOSUGFILE

Now that I try commenting this out, it appears to work, but the
resulting file is 20 Mbyte.  That's a bit too much.

-- 
Engineers are widely recognized as superior marriage material: intelligent,
dependable, employed, honest, and handy around the house.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
