### ISSUE TITLE
Setting guifont does not affect Athena popups

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [vim/vim#1766]
I successfully set `guifont` to pick the Cyrillic font I like. It is now used for both the menus and the edited text (though, perhaps, it should be possible to specify _different_ fonts for these.)

Unfortunately, as you can see in the window-shot below, some other font is still used for _popups_ -- something, which uses ISO-8859-1 (or -15?) instead of KOI8-U -- and I can't read the darn popups.

![gvim-font-problem](https://user-images.githubusercontent.com/1486340/27039887-53ca7252-4f5d-11e7-8a8c-0116ac984801.png)

I suspect, this has to do with my using Athena-widgets (not GTk or anything). Still, I'd expect `guifont` to control it all.

Is there an X11-resource I can set while this is being investigated? Thanks!

**Comment by nuko8** [comment]
> Setting guifont does not affect Athena popups

This is because `'guifont'` doesn't do that by design; it only affects some places over which Vim should have good control, such as the text area where the user edits files.

It's true that popups are part of applications, but it's also equally true that, when they appear, they have to share the screen space with other applications in harmony and are often granted the privilege of locking the whole or part of system except events of user input devices until the user responds to them.  On account of those facts and other design considerations as well, fonts or fontsets used for Athena popups are determined through the resource management system of X11.

Accordingly, an answer to this issue is: Set up a system-wide default font appropriately in accordance with the locale in use.  

Since there're various ways of attaining that, explanations or instructions for that could be too lengthy to fit this issue tracker.  Also, since the issue itself is by no means specific to Vim,  useful information could be available somewhere else.

P.S.  The following might be enough for you to resolve the issue:
```
$ cd $HOME
$ echo "*font: FONTDESC" > .Xdefaults-`hostname`
```
where `FONTDESC` is the XLFD of a Cyrillic font.  Make sure that the charset and encoding of the font fits the locale in use.

**Comment by chrisbra** [comment]
thanks. Closing then.

**Comment by UnitedMarsupials-zz** [comment]
> it's also equally true that, when they appear, they have to share the screen space with other applications

Same is true about the entire application -- including the actual editor-area...

> and are often granted the privilege of locking the whole or part of system except events of user input devices until the user responds to them.

So?.. Different apps can and do use different fonts...

> Accordingly, an answer to this issue is: Set up a system-wide default font appropriately in accordance with the locale in use.

This method would work for edited text area as well -- and yet, the `guifont` concept exists and is the documented way of setting the font there and in those "some places" you mentioned... If the `guifont` exists and controls the font used by _some_ widgets, is it not inconsistent, that it is not used for _all_ of them?

For static configs there is no real difference, but for those, who may wish to set the variable dynamically, the current situation would seem wanting... For example, one font may be good for the laptop screen, but, when a bigger monitor is plugged into the same machine and the editor is moved into the new workspace, a different font would be preferred.

At any rate, at least, the limitations (or the deliberate design-decisions) need to be documented -- along with the X-resource hierarchy that controls the settings...

>    `$ echo "*font: FONTDESC" > .Xdefaults`

Thanks, I know, how to set X-resources, but `*font` seems too encompassing -- I was inquiring about the exact name(s) of `gvim`-specific resources. Is it `gvim*font` or `gVim*font` or `Gvim*font`, perhaps? Thank you.

**Comment by nuko8** [comment]
> At any rate, at least, the limitations (or the deliberate design-decisions) need to be documented -- along with the X-resource hierarchy that controls the settings...

You need documentation?  Indeed, it's a good habit to always consult documentation at hand first.  For that, why don't you try `:help .Xdefaults` or `:h gui-resources`?  Then you'll have an answer to

>> $ echo "*font: FONTDESC" > .Xdefaults
>>
> Thanks, I know, how to set X-resources, but *font seems too encompassing -- I was inquiring about the exact name(s) of gvim-specific resources. Is it gvim*font or gVim*font or Gvim*font, perhaps?

If you have a user question like this next time, please consider positing it to `vim_use` or other online forums available to you, since we use this issue tracker mainly for issues relevant to the development of Vim.
