### ISSUE TITLE
stdout callbacks are broken with in_io=pipe (the implicit default)

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#1811]
https://github.com/SpaceVim/SpaceVim/pull/701/files

in this commit I want to use vim8's job api to run `ag`, but when 'in_io == pipe' the out_cb will not be called.

```viml
func! Test(a, b)
echom string(a:b)
endf
```
you can test with `call job_start(['ag', 'foo'], {'out_cb' : function('Test')})`

but after I use `'in_io' : 'null'`, then it works well.

**Comment by ZyX-I** [comment]
Can you show your output of `ag foo`?

Also 8.0.658 works for me, I used

```VimL
let j = job_start(['ag', 'activated', '/var/log/messages'], {'out_cb': {j, s->execute("unsilent echomsg ".string(string(s)))}})
```

which correctly outputs

```
'Jul  2 15:42:58 zyx-desktop kernel: serial 00:07: activated'
```

**Comment by ZyX-I** [comment]
Also check whether `ag` actually outputs anything when called like

    !ag foo < <(echo -n) | cat

. If it does not then you need to go to `ag` bug tracker.

**Comment by ZyX-I** [comment]
8.0.692 also works.

**Comment by wsdjeg** [comment]
You start ag with three argv. But I test with ['ag', 'foo']. In terminal 'ag foo' will list all lines contains in current directory.

I think we I should use ['ag', 'foo', ''] instead. And I will test it tonight.

BTW , in neovim. call `jobstart(['ag', 'foo'], {'on_stdout' : function('Test')})` works well. here Test function is

```vim
fu! Test(a,b,c)
echom a:a
endf
```

**Comment by ZyX-I** [comment]
@wsdjeg This should not be relevant unless something regarding argument handling is utterly broken or there are issues with using proper working directory in which case I still would not be able to reproduce because it needs specific setup. And I asked *not* about `ag foo` in terminal, but `ag foo < <(echo -n) | cat`, the difference *is* known to be relevant in my tests.

Actually after I checked with two-argument form and

    ag foo < <(echo -n) | cat

it indeed appears to output nothing (and I confirmed that it outputs something with just `ag foo`) … in terminal. So this issue may be closed, there is no reason for output callback to be called if `ag` outputs nothing, you need to go to `ag` bug tracker now.

**Comment by ZyX-I** [comment]
Though note that my `ag` version is 1.0.2 (Gentoo amd64 (“stable”)) while latest version in portage is 2.0.0. Maybe something was fixed since then.

**Comment by ZyX-I** [comment]
For reference: Neovim uses libuv, libuv uses sockets in place of pipes:

```VimL
:" Output of ls -FGhlA /proc/self/fd
:let STDOUTCB = {j, s->map(s, {k, v->execute("unsilent echomsg ".string(string(v)))})}|let j = jobstart(['ls', '-FGhlA', '/proc/self/fd'], {'on_stdout': STDOUTCB, 'on_stderr': STDOUTCB, 'on_exit': {j->execute("unsilent echomsg 'CLOSED'")}})
'total 0'
'lrwx------ 1 zyx 64 Jul  3 15:18 0 -> socket:[140440734]'
'lrwx------ 1 zyx 64 Jul  3 15:18 1 -> socket:[140440736]'
'lrwx------ 1 zyx 64 Jul  3 15:18 2 -> socket:[140440738]'
'lr-x------ 1 zyx 64 Jul  3 15:18 3 -> /proc/14985/fd/'
'l-wx------ 1 zyx 64 Jul  3 15:18 4 -> pipe:[49941672]'
''
CLOSED
```

**Comment by wsdjeg** [comment]
ok, thanks for testing, clossing, and this should be issue of ag.
