### ISSUE TITLE
[terminal] Can not exit terminal

### ISSUE THREAD

**Issue by tracyone** [vim/vim#1870]
Can't note exit terminal with exit command or Ctrl-d.

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Vim version:

> Include patch: 1-765
huge version with gtk2 gui
acl             +file_in_path    +mouse_sgr       +tag_old_static
 +arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
 +autocmd         +float           +mouse_urxvt     -tcl
 +balloon_eval    +folding         +mouse_xterm     +termguicolors
 +browse          -footer          +multi_byte      +terminal
 ++builtin_terms  +fork()          +multi_lang      +terminfo
 +byte_offset     +gettext         -mzscheme        +termresponse
 +channel         -hangul_input    +netbeans_intg   +textobjects
 +cindent         +iconv           +num64           +timers
 +clientserver    +insert_expand   +packages        +title
 +clipboard       +job             +path_extra      +toolbar
 +cmdline_compl   +jumplist        -perl            +user_commands
 +cmdline_hist    +keymap          +persistent_undo +vertsplit
 +cmdline_info    +lambda          +postscript      +virtualedit
 +comments        +langmap         +printer         +visual
 +conceal         +libcall         +profile         +visualextra
 +cryptv          +linebreak       +python/dyn      +viminfo
 +cscope          +lispindent      -python3         +vreplace
 +cursorbind      +listcmds        +quickfix        +wildignore
 +cursorshape     +localmap        +reltime         +wildmenu
 +dialog_con_gui  +lua/dyn         +rightleft       +windows
 +diff            +menu            -ruby            +writebackup
 +digraphs        +mksession       +scrollbind      +X11
 +dnd             +modify_fname    +signs           -xfontset
 -ebcdic          +mouse           +smartindent     +xim
 +emacs_tags      +mouseshape      +startuptime     +xpm
 +eval            +mouse_dec       +statusline      +xsmp_interact
 +ex_extra        +mouse_gpm       -sun_workshop    +xterm_clipboard
 +extra_search    -mouse_jsbterm   +syntax          -xterm_save
 +farsi           +mouse_netterm   +tag_binary
COMPILE: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-u nix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/inc lude/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_ 64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
 LINK: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft 2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr  -lgpm -ldl

1，Run vim in gnome-terminal
2，terminal bash
3，type exit then enter

**Comment by mattn** [comment]
What do you mean exit? You can close the terminal with `CTRL-w c` or `CTRL-w :bdelete`

**Comment by tracyone** [comment]
@mattn I mean run exit command in terminal that is opened in vim.

You are right, I can close the terminal with CTRL-w c or CTRL-w，But I used to press ctrl-d or type `exit` instead.

<img width="647" alt="2017-07-24 10 13 14" src="https://user-images.githubusercontent.com/4246425/28527527-5a38c496-70bd-11e7-8fae-658b8c2f71ad.png">

**Comment by mkarpoff** [comment]
I noticed this as well. If this is the intended behaviour then it works fine  but not having the terminal close when the terminal is killed looks like a bug from a user stand point. Either way keep up the good work vim version 8 is amazing.

**Comment by mattn** [comment]
As far as I can see the code, the remaining terminal after exiting shell is expected behavior.

**Comment by brammool** [comment]
> As far as I can see the code, the remaining terminal after exiting
> shell is expected behavior.

This isn't done yet.  My plan is that when the job exits, the terminal
window gets turned into a buffer.  Then you can do ":quit" as usual.
Or search through the text.

It's a bit tricky, since we need to keep the color and other attributes
somehow, and we can't store these in a buffer.  Needs some more work.
Also combined with the scrollback behavior (keep text that scrolls off
the top, including the attributes).  Probably the attributes would be
dropped as soon as you make changes to the buffer.

In the end it should work nicely for:
	:term ls
and end up with a buffer containing the output of "ls".

Not so useful for an interactive command, such as a shell or Vim.
Might need an argument for that, e.g.  :term <autoclose> bash

-- 
hundred-and-one symptoms of being an internet addict:
228. You spend Saturday night making the counter on your home page
     pass that 2000 mark.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
