### ISSUE TITLE
[Terminal] Is there a way avoiding nested vim in terminal?

### ISSUE THREAD

**Issue by tracyone** [vim/vim#1896]
<img width="762" alt="2017-07-30 10 06 28" src="https://user-images.githubusercontent.com/4246425/28754200-603350b8-7573-11e7-8d1c-a98c356edc7c.png">

For now  it will nested vim session you get when trying to open a file from the terminal.

**Comment by chrisbra** [comment]
I think, recursive opening of Vim is a feature :)
You might however create a function, that instead of spawning a new Vim, opens the file in the outer Vim sesssion. Not sure, if this currently is possible. In the terminal, you can check for the `$VIMRUNTIME` environment variable to check. May be you can then use something like [nvim-remote](https://github.com/mhinz/neovim-remote)

**Comment by brammool** [comment]
You can try to use the "editexisting" plugin.
" To use add ":packadd! editexisting" in your vimrc file.
