### ISSUE TITLE
[terminal] Buffer created by :terminal does not hide when quit

### ISSUE THREAD

**Issue by benknoble** [vim/vim#1911]
According to the (WIP) docs, buffers created by `:terminal` should hide when they are closed.

**Steps to reproduce**

1. `vim -u DEFAULTS`
2. `:terminal` (*optionally* `^D` the shell)
3. `<C-w>:close<CR>`
4. `:ls` and see the buffer listed!

**Comment by brammool** [comment]
David Ben Knoble wrote:

> According to the (WIP) docs, buffers created by `:terminal` should hide when they are closed.
> 
> **Steps to reproduce**
> 
> 1. `vim -u DEFAULTS`
> 2. `:terminal` (*optionally* `^D` the shell)
> 3. `<C-w>:close<CR>`
> 4. `:ls` and see the buffer listed!

I was just starting to work on buffer behavior for terminals.
I added this to the docs (tentative):


When the buffer associated with the terminal is wiped out the job is killed,
similar to calling `job_stop(job, "kill")`

So long as the job is running: If the window is closed the buffer becomes
hidden.  The command will not be stopped.  The `:buffer` command can be used
to turn the current window into a terminal window.  If there are unsaved
changes this fails, use ! to force, as usual.

When the job has finished and no changes were made to the buffer: closing the
window will wipe out the buffer.

Before changes can be made to a terminal buffer, the 'modifiable' option must
be set.  This is only possible when the job has finished.  At the first change
the buffer will become a normal buffer and the highlighting is removed.
You may want to change the buffer name with |:file| to be able to write, since
the buffer name will still be set to the command.


There might be a few more situations to take care of...
I just implemented the behavior of the last paragraph.

-- 
Shit makes the flowers grow and that's beautiful

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by benknoble** [comment]
It's possible patch ~838 fixes this (I only have through 823 currently).

**Comment by brammool** [comment]
This should work properly now.  Please file a new issue if you still see a problem.
