### ISSUE TITLE
[terminal] ANSI yellow rendered as brown when using 256 colors

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#1914]
The ANSI code for yellow (and light grey?) is rendered differently when setting t_Co=16 and t_Co=256. I think these colors should always be passed through as is to the terminal emulator.

Test script:

```
#!/bin/bash
echo -e "\\e[0mCOLOR_NC (No color)"
echo -e "\\e[1;37mCOLOR_WHITE\\t\\e[0;30mCOLOR_BLACK"
echo -e "\\e[0;34mCOLOR_BLUE\\t\\e[1;34mCOLOR_LIGHT_BLUE"
echo -e "\\e[0;32mCOLOR_GREEN\\t\\e[1;32mCOLOR_LIGHT_GREEN"
echo -e "\\e[0;36mCOLOR_CYAN\\t\\e[1;36mCOLOR_LIGHT_CYAN"
echo -e "\\e[0;31mCOLOR_RED\\t\\e[1;31mCOLOR_LIGHT_RED"
echo -e "\\e[0;35mCOLOR_PURPLE\\t\\e[1;35mCOLOR_LIGHT_PURPLE"
echo -e "\\e[0;33mCOLOR_YELLOW\\t\\e[1;33mCOLOR_LIGHT_YELLOW"
echo -e "\\e[1;30mCOLOR_GRAY\\t\\e[0;37mCOLOR_LIGHT_GRAY"
```

**Comment by nuko8** [comment]
> I think these colors should always be passed through as is to the terminal emulator.

Which terminal emulator do you mean by "the terminal emulator", Vim's built-in terminal or the underlying terminal on top of which Vim runs?  Please note that those two terminal emulators are different entities, and that the former is not expected to be a replacement for the latter  (See [updated develop.txt](https://github.com/vim/vim/blob/master/runtime/doc/develop.txt#L144)).  As for the colors, see the discussion [here](https://github.com/vim/vim/pull/1895) also.

**Comment by leahneukirchen** [comment]
I mean the outer terminal emulator that runs vim inside.  Since vim can obviously use it's 16-color-set (as it does with t_Co=16), it also should use it for t_Co=256, such that output inside a vim :term buffer and outside of vim looks exactly the same.

**Comment by nuko8** [comment]
As I wrote, those two terminals are different in functionality (please read updated develop.txt first).  Why do they need to look exactly the same?  Isn't it confusing?

**Comment by leahneukirchen** [comment]
I think it's more confusing when one color is randomly shifted, for no good reason (if I didn't like the color of my yellow, I'd change it in my terminal emulator ... why should vim change it?).

**Comment by nuko8** [comment]
> I think it's more confusing when one color is randomly shifted, for no good reason 

There's a good reason, actually.  So please, please read the discussion on the colors mentioned above first.

**Comment by brammool** [comment]
When I run the ANSI color script in my xterm, the one that says "light yellow" shows up as bold brown.
When I run the same script inside a terminal in Vim, I expect the same thing to happen.  And it does.
Vim will setup the terminal just like the terminal it's running in.
I can't even seem to make this xterm show yellow for those ANSI escape sequences.  Need to tune some X resources probably, which I don't really want to do.

When I run the 256 color test, both in xterm directly and inside Vim, the colors are very close.  Only a few seem slightly darker, and that's probably because of the reverse engineering we need to do, we can't tell if the RGB was for a color block code or the grey ramp.

So, I think the currently implementation is fine.

**Comment by leahneukirchen** [comment]
I think this works properly since 8.0.1359.
