### ISSUE TITLE
gvim GUI language reverts to default when "syntax on" before "language message en"

### ISSUE THREAD

**Issue by Strangehill** [vim/vim#1959]
gvim, on non-English Windows XP, in my .vimrc:

```
language messages en
syntax on
```
will change the language of the gui to English, 

but this variation:
```
syntax on
language messages en
```
will still display vim messages to English, but the gui will revert to the system language.

related to this #1082  ?

**Comment by tonymec** [comment]
I think so, and in addition, it has long been there. I remember that a long time ago, when I was still on Windows at least part of the time, I found out by trial and error that

    if has('unix')
      language messages C
    else
      language messages en
    endif

had to be placed in the vimrc before sourcing the vimrc_example.vim (which sets :syntax on -- this is now at line 86 of defaults.vim). IIRC this was in Vim 6.0, I never knew Vim 5.x. (At the time, my Windows locale was "French_Belgium.1252" or something equally silly, and I have always preferred messages in English, since the time when I worked on a mainframe where French manuals, when available which wasn't always, were bad translations of obsolete versions of the English ones.)

Best regards,
Tony.

**Comment by chrisbra** [comment]
could that be because `:syntax on` triggers loading the menus?

**Comment by tonymec** [comment]
> could that be because `:syntax on` triggers loading the menus?

…which are in the messages language. Could be.

**Comment by k-takata** [comment]
`:help 'go-M'` says that:

> the ":syntax on" and ":filetype on" commands load the menu too

And `:help :filetype` also says that:

>	When the GUI is running or will start soon, the menu.vim script is
>	also sourced.  See |'go-M'| about avoiding that.

So I think this behavior is expected.
It might be better to add similar description to `:syntax-on` and/or `:syntax-enable`.

**Comment by k-takata** [comment]
How about this document patch?
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a87780f9c18ddca718edc54f00f4020d6e2ebddd/doc-menu-issue1959.patch?at=default&fileviewer=file-view-default

**Comment by chrisbra** [comment]
those backrefs "`"  are usually not used in vim help documents. I would stick to using double quotes.

**Comment by k-takata** [comment]
The usage is explicitly written in the help: `:help quotecommandquote`.

Oh, there is a mistake in my patch. I will update it later.

**Comment by chrisbra** [comment]
oh, I missed that one. thanks.

**Comment by k-takata** [comment]
Updated.
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ce1a8e272b2bcd68de71a674f39c484ab091bc17/doc-menu-issue1959.patch?at=default&fileviewer=file-view-default

**Comment by chrisbra** [comment]
I think this is fixed by https://github.com/vim/vim/commit/01164a6546b4c635daf96a1f17d1cb2d07f32a66
