### ISSUE TITLE
Vim fails to compile with error: /usr/lib/../lib64/libSM.so: undefined reference to `uuid_generate@UUID_1.0'

### ISSUE THREAD

**Issue by chriad** [vim/vim#1961]
I cloned the vim repo and used:
> ./configure --prefix=/home/muellc1b/installation/vim_install_dir

Then I use:
> make

Which results in the above mentioned error:
> [...]
> link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
> gcc -L/usr/local/lib -Wl,--as-needed-o vim objects/arabic.o objects/buffer.o
> objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o
> objects/diff.o objects/digraph.o objects/edit.o objects/eval.o
> objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o
> objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o
> objects/fold.o objects/getchar.o objects/hardcopy.o
> objects/hashtab.oobjects/if_cscope.o objects/if_xcmdsrv.o objects/list.o
> objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o
> objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o
> objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o
> objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o
> objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o
> objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o
> objects/userfunc.o objects/version.o objects/window.o objects/gui.o
> objects/gui_gtk.o objects/gui_gtk_x11.o objects/gui_gtk_f.o
> objects/gui_beval.oobjects/netbeans.o objects/channel.oobjects/charset.o
> objects/json.o objects/main.o objects/memfile.o objects/message.o-pthread
> -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0
> -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0
> -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0-lSM -lICE -lXt -lX11 -lSM -lICE-lm
> -ltinfo -lelf -lnsl-lselinux -lacl -lattr -lgpm/usr/lib/../lib64/libSM.so:
> undefined reference to `uuid_unparse_lower@UUID_1.0'
> /usr/lib/../lib64/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
> collect2: error: ld returned 1 exit status
> link.sh: Linking failed
> make[1]: *** [vim] Error 1
> make[1]: Leaving directory `/home/muellc1b/installation/vim/src'
> make: *** [install] Error 2

OS:
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release:        6.7
Codename:       Santiago

gcc:
gcc (GCC) 4.8.2

util-linux:
util-linux-ng-2.17.2-12.18.el6.x86_64

make:
GNU Make 3.81

I am not experienced in building software myself. I also find similar issues that I found uninformative.

Does it mean that I have to install the newest version of libuuid in my home directory and point the linker to that version. How would I do this?

I would appreciate your help!

**Comment by nuko8** [comment]
The cause of the link error is not due to Vim, but due to `libSM` and `libuuid`.  The `libSM` you have was seemingly built and linked against a `libuuid` the version of which is newer than that of the `libuuid` you have.  In spite of such a version mismatch, they were somehow installed together on your system, thus resulting in the link error.

So what you need to do is clear, but...

Installing shared libraries to override the ones that were already installed for system-wide use needs some technical expertise and chores to avoid various troubles such as not-found errors, crashes due to ABI incompatibility, or a risk that local installation may break the consistency of the package management system.

Accordingly, it'd be rather best for you to ask the provider (or dedicated user forums, if any) for the instructions as to how to install new `libuuid` (or, possibly, downgrade `libSM`) to avoid possible troubles.

**Comment by chriad** [comment]
Thank you for clarifying. Since this is not related to vim I will close.

I have compiled libuuid in my home but I cannot find the right way to "tell" the configure script where to look for the newer library:

```
LIBDIR="/home/muellc1b/installation/libuuid/lib"
export LDFLAGS="-L$LIBDIR"
export LD_LIBRARY_PATH="$LIBDIR:$LD_LIBRARY_PATH"
export LD_RUN_PATH="$LIBDIR:$LD_RUN_PATH"
#export CFLAGS+="-Wl,-L$LIBDIR"
export LIBS+="-luuid"
./configure --prefix=/home/muellc1b/installation/vim_install_dir

```

The configure script help point to environment variables that should be customized:

>  Some influential environment variables:
>  CCC compiler command
>  CFLAGSC compiler flags
**>  LDFLAGS linker flags, e.g. -L<lib dir> if you have libraries in a
>  nonstandard directory <lib dir>**
>  LIBS libraries to pass to the linker, e.g. -l<library>
>  CPPFLAGS (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
>  you have headers in a nonstandard directory <include dir>
>  CPPC preprocessor
>  [...]

>  **Use these variables to override the choices made by `configure'** or to help
>  it to find libraries and programs with nonstandard names/locations.

In the libuuid guide it says:

>  Libraries have been installed in:
>  /home/muellc1b/installation/libuuid/lib
> 
>  If you ever happen to want to link against installed libraries
>  in a given directory, LIBDIR, you must either use libtool, and
>  specify the full pathname of the library, **or use the `-LLIBDIR'
>  flag during linking and do at least one of the following:**
>   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
>   during execution
>   - **add LIBDIR to the `LD_RUN_PATH' environment variable
>   during linking**
>   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
>   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

Here again the error:

```
gcc   -L/home/muellc1b/installation/libuuid/lib -L/usr/local/lib -Wl,--as-needed [...] 
-pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 
-lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 
-lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   
-lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl **-luuid** -lselinux -lacl -lattr -lgpm
/usr/lib/../lib64/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
/usr/lib/../lib64/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [vim] Error 1
make[1]: Leaving directory `/home/muellc1b/installation/vim/src'
make: *** [first] Error 2
```

I would appreciate if you could comment! What am I missing in my installation atempt?

**Comment by nuko8** [comment]
Hmm, if you still want to do something more with the issue, it might be a good idea to make sure for yourself whether or not it is indeed due to the version mismatch.  (Yes, information gained through the Internet is usually useful, but sometimes it turns out to be simply wrong, you know :)

For that (I assume that your system `libuuid` is installed in `/usr/lib`), try
```
$ nm /usr/lib/libuuid.so | grep uuid_unparse_lower
$ nm /usr/lib/libuuid.so | grep uuid_generate
```
If they give `uuid_unparse_lower@UUID_1.0` and `uuid_generate@UUID_1.0`, respectively, then the issue is unlikely to be due to the version mismatch, but rather due to the characteristics of the linker.

If that is the case, run the configure script normally (I mean, run it without the stuff you added for your locally installed `libuuid`, such as `LDFLAGS`); after it is done, open `src/auto/config.mk` with Vim, and change the line `X_PRE_LIBS      =  -lSM -lICE -lXpm` to `X_PRE_LIBS      =  -luuid -lSM -lICE -lXpm`.  Then do `make`.  This might resolve the issue, I'm not sure though...

**Comment by chriad** [comment]
This actually worked! I could succesfully compile the vim executable. 

There is just one annoying thing:

Whenever I start vim I get the message:

> vim test.R
> /home/muellc1b/installation/vim_install_dir/bin/vim: /usr/prog/libuuid/1.0.3-goolf-1.5.14-NX/lib/libuuid.so.1: no version information available (required by /usr/lib64/libSM.so.6)

I hope this will not cause any problems later on. Maybe this means I should point the linker to this directory (/usr/prog/libuuid/1.0.3-goolf-1.5.14-NX/lib/) instead of the system on (/usr/lib64).

Thank you a lot nuko8!

**Comment by alaingdl** [comment]
as explain in https://github.com/gnudatalanguage/gdl/issues/752#issuecomment-628673886 and 
https://github.com/gnudatalanguage/gdl/issues/749#issuecomment-628671359 it might be due to a conflict with Anaconda prepended in the PATH.

**Comment by chriad** [comment]
! L

Sent from ProtonMail mobile

-------- Original Message --------
