### ISSUE TITLE
Alt screen in :terminal changes cursor shape

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#1967]
Steps to reproduce

1. Run vim
2. `:terminal`
3. run a program that uses the alternate screen in the terminal (e.g. `less`, `mc`)

What happens

- Terminal cursor (which is usually a block) changes to an underline, and this change persists when you quit `less`/`mc`, the shell session in vim's terminal, or vim itself

What I expect

- Terminal cursor to stay in block shape, or at least go back to block shape when you quit the program using the alternate screen.

Additional info

- I'm on Linux with gnome-terminal 3.20.2, libvte 0.44.2.

**Comment by brammool** [comment]
Marius Gedminas wrote:

> Steps to reproduce
> 
> 1. Run vim
> 2. `:terminal`
> 3. run a program that uses the alternate screen in the terminal (e.g. `less`, `mc`)
> 
> What happens
> 
> - Terminal cursor (which is usually a block) changes to an underline, and this change persists when you quit `less`/`mc`, the shell session in vim's terminal, or vim itself
> 
> What I expect
> 
> - Terminal cursor to stay in block shape, or at least go back to block shape when you quit the program using the alternate screen.
> 
> Additional info
> 
> - I'm on Linux with gnome-terminal 3.20.2, libvte 0.44.2.

Thanks for reporting.  It's caused by libvterm using "int" for a one bit
bitfield, which turns a value into -1.

-- 
No man may purchase alcohol without written consent from his wife.
		[real standing law in Pennsylvania, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mgedmin** [comment]
Fixed in 8.0.0920 (893029ab20a06da9c0cf29661c9f6e2ec5583dce).
