### ISSUE TITLE
Why Development Process of most of people's Favorite Editor is so slow??

### ISSUE THREAD

**Issue by bauripalash** [vim/vim#1992]
I'm​ seeing VIM 8 for a long time

**Comment by dertuxmalwieder** [comment]
How fast do you require a new major update and why? Which urgent features are you missing?

**Comment by bauripalash** [comment]
I mean that, I've not seen any major change in VIM since I've first use it (about end of 2015 when I was 13) now I am about 15, but it is with same look.

Though I love it 😍

**Comment by bauripalash** [comment]
Sorry, If I said anything Funny or Wrong.

**Comment by ZyX-I** [comment]
Version means nothing, it is not an indicator of the speed of development process. @brammool creates/merges new features really fast should he be convinced a feature is needed. And Vim is supposed to be highly backwards compatible, so you may see many things like `:terminal`, new viminfo format, lambdas, partials, asynchronous IO support, timers, packages, DirectX and GTK3 GUI support, … not affecting how Vim looks. There are many additions since 2015.

**Comment by chrisbra** [comment]
Vim 8 was released barely a year ago and we already have accumulated 900 patches for the terminal feature. Most patches were bugfixes, but we also still add new features. I don't see a problem here. closing

**Comment by bauripalash** [comment]
Thanks for breaking my wrong ideas.
