### ISSUE TITLE
:packadd doesn't source files from "after" directory inside "opt" directory

### ISSUE THREAD

**Issue by markonm** [vim/vim#1994]
Steps to reproduce:
1. install https://github.com/msanders/snipmate.vim to `pack/foo/opt`
2. `vim --clean`
3. `packadd` snipmate.vim
4. check `:scriptnames`
5.  `pack/foo/opt/vim-snipmate/after/plugin/snipMate.vim` is not sourced

If I move plugin to `pack/foo/start/` everything it's sourced properly.

**Comment by brammool** [comment]
> Steps to reproduce:
> 1. install https://github.com/msanders/snipmate.vim to `pack/foo/opt`
> 2. `vim --clean`
> 3. `packadd` snipmate.vim
> 4. check `:scriptnames`
> 5.  `pack/foo/opt/vim-snipmate/after/plugin/snipMate.vim` is not sourced
> 
> If I move plugin to `pack/foo/start/` everything it's sourced properly.

The "after" directory isn't explicitly used, it is added to the
'runtimepah' and directories found there found later.  Since by the time
you use your :packadd command startup already finished, Vim won't go
looking for plugins there.

I understand that you would expect a package to work the same, no matter
if they are under "start" or "opt".

-- 
I recommend ordering large cargo containers of paper towels to make up
whatever budget underruns you have.  Paper products are always useful and they
have the advantage of being completely flushable if you need to make room in
the storage area later.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by inkarkat** [comment]
`:packadd` already has logic to `:source` the added scripts from the `plugin` and `ftdetect` subdirs [here](https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3650-L3651). I think what's missing is that `after/plugin` should be considered and `:source`d, too.

**Comment by lifepillar** [comment]
But is there a valid use case for an `after` directory within a plugin? After directories are for sysadmins and personal user overrides, AFAIK (see `:help after-directories`).

SnipMate (ab)uses it to override the mappings of other plugins (SuperTab), which IMHO is an anti-pattern.

**Comment by jmdevin** [comment]
Since it's somewhat debatable whether this is a bug, I've opened #15584 to request that the functionality be added. Maybe this issue could be closed?

**Comment by chrisbra** [comment]
Let's close this one here then as duplicate
