### ISSUE TITLE
Make default keys jkl; not hjkl

### ISSUE THREAD

**Issue by TheBabu** [vim/vim#2020]
Hello,
I was wondering why we still have the default binding keys as `hjkl` instead of `jkl;`, first of all we have all 4 fingers on those keys naturally, but of course "h" is the button we have to reach for. 
I still don't understand, why this has not been changed before, this is vim, a fork of vi which is supposedly improve the already great functionality of vim. So why not have life much more easier to have the default keys as `jkl;` and not `hjkl`.
I hope you take this into considerations into future development!

**Comment by tonymec** [comment]
Not only `hjkl` is the long-established vim (and vi, and…) standard (and Bram has, IMHO rightly, an extremely high concern about backward compatibility), but in addition, AZERTY (i.e. French) keyboards have `Mm`, not `;:` on the key immediately right of the L key (see for instance http://users.skynet.be/antoine.mechelynck/other/keybbe.htm).

Each of these reasons alone would IMHO be enough not to change the default, but together they add all the more reason not to change it, all the more so because "Vi mode" of programs such as the bash shell includes `hjkl`, not `jkl:`, and there is no way any Vim developer could change _that_.

Personally I don't feel it too hard to hover my right hand over `hjkl` rather than (AZERTY) `jklm`, at least when using Vim, but admittedly I'm not a 10-finger blind-typer — usually I type with the 5 fingers of my right hand, moving the hand as necessary over the keyboard the way a pianist moves his over the piano keyboard, while my left hand may hold a book I'm typing from or even my chin.

If you prefer to use `jkl:` rather than `hjkl` you may do it with a series of mappings (4 with none of Shift, Ctrl and Alt/Meta, 4 with Shift, etc. — and then you'll notice that Vim has no way to identify keypresses on `Ctrl-:` or `Ctrl-;` because `:` and `;` are `0x3A` and `0x3B` respectively, and 7-bit ASCII did not reserve any spot for them (while with alphabetic keys, Ctrl- and Ctrl-Shift- are intentionally synonymous, and are represented by the letter byte's lower 5 bits, with the higher bits stripped away).

Best regards,
Tony.

**Comment by TheBabu** [comment]
Thank you for your response.

I understand the complexity of the issue now, and I feel like now there is really no reason to change considering the many factors here.

Thank you! (Closing Issue)
