### ISSUE TITLE
Adding options breaks arrow keys in insert mode

### ISSUE THREAD

**Issue by TheBabu** [vim/vim#2050]
Whenever I add these lines:
```
inoremap <esc> ~<bs><esc>
inoremap <cr> ~<bs><cr>
```
to my `.vimrc`, for some sort of reason I get letters whenever I use the arrow keys in insert mode...
I have the option of `set nocompatible`, and I moved it to many sections of my vimrc and still no dice...
This is my .vimrc: http://termbin.com/f53q

Thanks for any help!

**Comment by nuko8** [comment]
Will you try this?: Open a terminal, type `cat`<kbd>return</kbd> at the command prompt, press any of the arrow keys once, and see what is echoed on the terminal.  Finally, press <kbd>control+C</kbd> to quit `cat`.

Probably, you'll get a string starting with `^[` which is a visualized representation of the invisible character `<Esc>`.  The whole string represents the key code of the arrow key pressed, and that's the thing Vim receives when you press it.  Note again that the key code starts with `<Esc>`.

For Vim to interpret key codes like that correctly (including a single `<Esc>` itself),  it has to wait and see  whether `<Esc>` is followed by one or more characters (cf. `:h ttimeout`).

One of your key mappings, `inoremap <esc> -<bs><esc>`, prevents Vim from doing the above, since it asks it to apply the key mapping as soon as it receives the `<Esc>` at the head of key codes.  That's why the arrow keys stop working.

Since key mappings work like that, the arrow keys would work again by adding a new key mapping like `inoremap <Esc>x <Esc>x`, where `x` is an arbitrary key, to your existing key mappings.  But it looks quite ridiculous, and I do think it at best serves as a clumsy example of key mappings, even though it might be somehow useful to illustrate how key mappings interact with each other.

**Comment by TheBabu** [comment]
Ah I C now! Thank you for teaching me on how this works!

Closing this thread!
