### ISSUE TITLE
[terminal] background not correctly handled in terminal emulator inside vim

### ISSUE THREAD

**Issue by zhykzhykzhyk** [vim/vim#2075]
1. vim always set a background color for the terminal emulator inside, and it's not matching the outer terminal's background.
![image](https://user-images.githubusercontent.com/3477952/30241674-b1f7fc16-95ba-11e7-9409-ba7504119896.png)

2. switching to terminal normal mode cause the terminal buffer get the normal background, with the printed texts have the wrong background.
![image](https://user-images.githubusercontent.com/3477952/30241670-9fa49e70-95ba-11e7-8fbc-6ecd2ba0c2ca.png)

tested with gnome-terminal, terminator and terminology, xterm also have this problem if bg is set to 'light'.

**Comment by nuko8** [comment]
>  ... if bg is set to 'light'.

That's the root cause.  When the background color of the terminal is dark, you are supposed to set  the `'background'` option to dark.  This is rather mandatory than optional.  Here is an excerpt from `:help 'background'`:

> When set to "dark", Vim will try to use colors that look good on a dark background.  When set to "light", Vim will try to use colors that look good on a light background.  **Any other value is illegal.**
[emphasis mine]

**Comment by zhykzhykzhyk** [comment]
But setting background to dark does not get the background match the outside terminal, for example:
![image](https://user-images.githubusercontent.com/3477952/30242085-7bcfe470-95c2-11e7-8a8f-596f508d5e4a.png)

**Comment by nuko8** [comment]
Then, you are choosing the background color different from that of the terminal, right?

**Comment by zhykzhykzhyk** [comment]
No, I just used a terminal which default background is not black.

**Comment by zhykzhykzhyk** [comment]
A transparent background example
bg=light
![image](https://user-images.githubusercontent.com/3477952/30242275-019449fe-95c6-11e7-8ebb-6f3b9af7a287.png)
bg=dark
![image](https://user-images.githubusercontent.com/3477952/30242304-83ef1bcc-95c6-11e7-9a5c-4d878e425841.png)

**Comment by nuko8** [comment]
For comparison, what happens if both gnome-terminal and Vim use their default settings?

**Comment by zhykzhykzhyk** [comment]
With both vim and gnome-terminal have their default settings, vim assumes the bg is light, which is posted at very beginning. The result of setting vim bg to dark is shown in my second post. My last post shows vim terminal emulator cannot handle transparent background.

**Comment by nuko8** [comment]
I was asking because:

1. The background color varies from picture to picture: While that of the first post is dark gray, that of the second post gets reddish.  That cannot happen only by changing`'background'` from `light` to `dark`.

2. By default, `ctermbg` of `StatusLineTerm` is set to DarkGreen (`#006400`).  However, the colors shown in the pictures apparently deviate from it to the extent that environment dependency cannot explain it.

So I cannot be certain if you compared one with another appropriately.  Will you clarify them?

**Comment by zhykzhykzhyk** [comment]
The terminal of first post is terminology, gnome-terminal is used in my second post and my third post. only the third has a non-default terminal setting.

**Comment by nuko8** [comment]
IMHO, if an issue is presented that way, people are hardly able to narrow down various relevant factors to ones causing it directly, although visualization is usually helpful for them to understand issues, especially when they can't reproduce them for themselves.

Anyway, FYI, we once got a PR about gnome-terminal last May (Actually, it was about a library it depends on, that is, VTE).  That was #1677, and the pictures presented by the PR author apparently resemble yours.   

On his closing the PR (seems like the patch was'n merged), he left the following two notes:

> I found an older versions of gnome terminal and do not see the issue, so apparently it's a regression. I will investigate further.  I may also try contacting JuiceSSH's developers to see what they can do.

> On the gnome-terminal side, I found that this has been fixed in VTE. Bisecting VTE, I discovered it was only a couple of weeks ago: GNOME/vte@a26a60b

In another issue you've opened, #2076, you say
> especially on an older version of gnome-terminal

So, there's a possibility that the issue is rather due to  some recent but older versions of VTE than to Vim.  Did you examine the issue with the latest VTE which seems to have fixed #1677?  It looks to me it's worth a try.  Or, is there someone who knows about consequences about that?

**Comment by zhykzhykzhyk** [comment]
I have already tested with multiple terminal, on both linux and MacOS, with vim 8.0.1050 and 8.0.1092, all have the same problem. So I don't think it's a gnome-terminal specific problem.

To reproduce:
1. set outside terminal background to non-black (transparent or image is better)
2. In vim, use `default` color scheme
3. open terminal with `:term` and type `echo hello`
4. In terminal buffer, switch to terminal normal mode with `<C-\><C-N>`

**Comment by nuko8** [comment]
> 4.  In terminal buffer, switch to terminal normal mode with `<C-\><C-N>`

Oh my ..., this is the first time you mention it, isn't this?

I thought you had been talking about what happened with Vim in Terminal-Job mode.  Also, when I noticed the issue, it reminds me of the fact that Vim once had a glitch similar to #1677 (or yours in appearance) within a terminal in that mode, which was fixed in hours or a day.  So, that omission of `<C-\><C-N>` had been really, really muddling me up.

Anyway, then the behavior can be considered rather intentional with good reasons, and naturally, that is seen with every terminal no matter what it is.

By pressing `<C-\><C-N>`, Vim switches from **Terminal-Job** mode to **Terminal-Normal** mode (`:help Terminal-mode`).  That mode change can make the user much confused since it almost surely implies that the key bindings are going to drastically change from those commonly found with most terminal applications to those unique to Vim.  Also, Visual mode gets made available.  Leaving the background color of the job's output as-is would be helpful to distinguish it from another, and so on.  One thing and another, it would be very nice if Vim could notify the user of those changes in a clear but not distracting way.  

So, what you've been thinking an issue can be considered an attempt to visualize that particular mode change to notify the user of the resulting significant, substantial changes at a single glance.  In fact, if you press `a` or `i`to make the mode back to Terminal-Job, then the visualization is gone.

In the case where `'background'` is set to `light` for the dark background color, the resulting visuals can be too distracting.   No wonder if one thinks it an issue.  But again, the right thing to do for that is to correct the `'background'` value.

Personally, I don't think the current behavior is wrong; however, mainly from an aesthetic point of view, I can see it natural that some people would argue on that differently.   So, IMHO, answering the questions "Is there any better way than what we have now?  How can we improve it?" is probably the first step for those who think it an issue to address it.

**Comment by mattn** [comment]
BTW, did you try this?

https://github.com/vim/vim/pull/2067

**Comment by nuko8** [comment]
@mattn 

To me?  Yes, I did.  But it appeared to me that redraw got a bit sluggish due to the overload caused by unprecedentedly fast scrolling, e.g., `:term make test`.  So I didn't think it a big deal for me at that moment.  Also, I know issues like #2067 are inherently difficult for Vim to address...

**Comment by mattn** [comment]
>To me? 

To all people in this thread. The libvterm already has a mechanism for specifying the foreground color and background color with arbitrary colors. And the default value is 255 for foreground, 0 for backgound. In the case background=light, those value are swapped. AFAIK, I can't belieave vim become slowly by # 2067. However, there is a possibility that the terminal will do so.

**Comment by nuko8** [comment]
Even with that proposed patch, the issue of this thread remains the same unless a given true color for background happen to coincide with any color of the 256-color palette, or, to be approximated well to any of them to the extent that the differential can't be noticeable to human eyes, doesn't it?

So, if that's true and if that feature is included, the help document should have a note on the relation between colors specified with 24-bits, `#rrggbb`, and their actual colors resulting from 256-color palette approximation.  Honestly, I'm getting bored of explaining this sort of stuff and will leave it up to someone who is responsible for that or someone who supported our move to GitHub, so that I can do my own work to be done.

**Comment by zhykzhykzhyk** [comment]
@nuko8 I think i mentioned it's terminal normal mode in the first post.

@mattn #2067 does nothing to 256color terminals.

**Comment by jamessan** [comment]
> By pressing `<C-\><C-N>`, Vim switches from Terminal-Job mode to Terminal-Normal mode (:help Terminal-mode). That mode change can make the user much confused since it almost surely implies that the key bindings are going to drastically change from those commonly found with most terminal applications to those unique to Vim. Also, Visual mode gets made available. Leaving the background color of the job's output as-is would be helpful to distinguish it from another, and so on. One thing and another, it would be very nice if Vim could notify the user of those changes in a clear but not distracting way.

I would position this the other way.  Terminal-Job mode is the odd mode here, since it's different than the Vim modes that existed prior to the terminal implementation.  Rather than drawing attention to when a buffer is in Terminal-Job mode, highlight when it is in Terminal-Normal mode.

From that perspective, Vim already has a way to unobtrusively handle this.  It's the `'showmode'` option.  This is exactly what Neovim decided to use.  When in a terminal buffer and interacting with the terminal (aka Terminal-Job mode), the user sees `-- TERMINAL --` on the last line, just like one would normally see `-- INSERT --` when in insert mode for a normal buffer.

**Comment by jamessan** [comment]
> Rather than drawing attention to when a buffer is in Terminal-Job mode, highlight when it is in Terminal-Normal mode.

Actually, that's what is already happening.  I meant the reverse. :) Treat Terminal-Normal mode normally (since it behaves the most like Vim) and draw attention to Terminal-Job mode via `'showmode'` instead of the jarring color changes currently taking place.

**Comment by mattn** [comment]
@zhykzhykzhyk if #2067 support 256 color, your issue will be solved?

**Comment by nuko8** [comment]
> @nuko8 I think i mentioned it's terminal normal mode in the first post.
 
Indeed :)

By the way, although @brammool didn't refer to this issue directly, he seemingly gave us a solution to the issue via 238d43b32 and 49a613f84.   They look nice to me.  How about trying them, seeing if the issue is addressed to your satisfaction, and deciding what to do with this thread?  In case you still find an issue with them, I'd suggest opening a new issue dedicated to them to avoid possible confusion.

**Comment by brammool** [comment]
Kazunobu Kuriyama wrote:

> > @nuko8 I think i mentioned it's terminal normal mode in the first post.
>  
> Indeed :)
> 
> By the way, although @brammool didn't refer to this issue directly, he
> seemingly gave us a solution to the issue via 238d43b32 and 49a613f84.
> They look nice to me.  How about trying them, seeing if the issue is
> addressed to your satisfaction, and deciding what to do with this
> thread?  In case you still find an issue with them, I'd suggest
> opening a new issue dedicated to them to avoid possible confusion.

Yeah, I tried using the color of the last cell without text, and that
seems to work well.

Still have to look at using the Normal color to initialize the vterm
background color.  We might actually need another highlight group to
specify that color.

-- 
hundred-and-one symptoms of being an internet addict:
105. When someone asks you for your address, you tell them your URL.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zhykzhykzhyk** [comment]
fixed at HEAD
