### ISSUE TITLE
profile: last continued line is missing in output

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2112]
Given `t.vim`:

```vim
echom 1
echom 2
      \ 3
echom 4
      \ 5
```

Profile output (`vim -N --noplugin --cmd 'profile start prof.out' --cmd 'profile! file **' -u t.vim`):
```
SCRIPT  /test_plugin/last_line_is_continued.vim
Sourced 1 time
Total time:   0.000082
 Self time:   0.000082

count  total (s)   self (s)
                            echom 1
    1              0.000034 echom 2
                                  \ 3
    1              0.000013 echom 4

```

The last line is missing here.

Maybe a similar issue as with https://github.com/vim/vim/issues/2103#issuecomment-330051150?!

**Comment by LemonBoy** [comment]
The problem lies in the logic used to record what lines have been executed: `getsourceline` calls `script_line_start` for every "real" line of code (every 'echom' in our case) and keeps track of the lines that have been skipped by doing `this_line_number - last_line_number`. This trick works as long as your script doesn't end with a continuation line, [this](https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L4589) check prevents the code from calling `script_line_start` one last time.
I think the fix here is to remove the `line != NULL` clause in the if.
