### ISSUE TITLE
netrw 162m closes and deletes current window/buffer when opening directory

### ISSUE THREAD

**Issue by jayache80** [vim/vim#2141]
How to replicate:
Open a file in vim, either command
`vim filename.ext`
or from vim
`:e filename.ext`
Open netrw explorer in vertical split
`:Vex`
Choose a directory and open it by pressing `<enter>`

your buffer containing filename.ext is automatically deleted and the window is closed. 99% sure this is a bug with netrw but I don't know where their issues are tracked.

OS: windows, both vim and gvim behave the same
Vim Version: Various versions of 8, lately using nightly builds, present in 8.0.1130

**Comment by JamieMeyers** [comment]
I am also able to 100% reproduce with version 8.0, patches 1-272, netrw 162.

Steps to reproduce, no .vimrc present:
1.  `vim filename.ext`
1. `:set autochdir`
1.  `:tabnew`
1.  `:Explore`
1.  Go back a directory until you can pick a separate directory path. Select that directory not in the parent path.
    * For instance, If you have a tree of:
        * /a/b/c/
            * d
            * e

       and you are in /a/b/c/d, go back one directory (/a/b/c) and then enter e (/a/b/c/e).

**Expect result:**
The directory is selected.

**Actual result:**
The directory is selected, but merged with the previous tab. Additionally, if you try to use `:Explore` to open the same file, it will not open. Instead it will take you back to the last directory shown in explore.

**Comment by k-takata** [comment]
Dr. Chip posted a reply of this issue to vim_use. (I don't know why.)
https://groups.google.com/d/msg/vim_use/Zl43I4Hu3hI/GUtRkC7dAgAJ
Quoting:

> I am unable to duplicate this problem; I'm using Scientific Linux, vim
> 8.0.1257.
> 
> So, please refer to the directions in :help netrw-debug, generate a
> trace, and send it on to me.
> 
>  * run it with:   vim -u netrw.vimrc  (see attached)
>  * please use :Dsep after each command that you type (it helps me
> delineate what netrw did after each command)

**Comment by run2cmd** [comment]
I have replied to that google group ot Dr. Chip message. I'm just posting it here for record:

I found that using jayache80 method I was able to reproduce that only. I run that using no plugins to make sure that this is NETRW issue:

`$ vim -u netrw.vimrc --noplugins -i NONE -V9vimlog.log`
`:Vexp`
Now just enter any directory

I have attached vimlog from my actions as well as netrw.vimrc(uploaded as nerw.vimrc.log)
[vimlog.log](https://github.com/vim/vim/files/1509209/vimlog.log)
[netrw.vimrc.log](https://github.com/vim/vim/files/1509210/netrw.vimrc.log)

I'm using Vim 8.0.1333 on Windows

**Comment by smhc** [comment]
Can confirm. I am seeing this with autochdir and my common usage pattern of:

vim file.txt
`:tab split`
`:E`

I also experience it with:
vim file.txt
`:vs`
`:E`

The netwr window removes the split and takes over both splits/tabs.

Removing autochdir appears to mitigate it.
I was also getting issues with filetype being incorrect/empty and not being able to save a file after opening a file under these conditions - but cannot recall which file type triggered it, it may have been an earlier version of vim. (appears to be this issue: https://vi.stackexchange.com/questions/10382/strange-behavior-between-autochdir-and-netrw , perhaps it is fixed in the version I have now)

Once netrw has been used the problem no longer occurs for that session.

Problem is new as of around v8, on Linux.

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  8 2017 14:16:47)
Included patches: 1-1274
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl  -ldl

**Comment by invisibleroads** [comment]
Thank you for working on our favorite favorite favorite editor!
Unfortunately, this issue makes Vim 8 utterly unusable for me.
I was able to downgrade to Vim 7 on Fedora using the following commands:

```
DISTRIBUTION_URL=https://www.rpmfind.net/linux/fedora/linux/releases
VERSION_URL=$DISTRIBUTION_URL/25/Everything/x86_64
BASE_URL=$VERSION_URL/os/Packages/v

wget $BASE_URL/vim-minimal-7.4.1989-2.fc25.x86_64.rpm
wget $BASE_URL/vim-common-7.4.1989-2.fc25.x86_64.rpm
wget $BASE_URL/vim-enhanced-7.4.1989-2.fc25.x86_64.rpm
wget $BASE_URL/vim-X11-7.4.1989-2.fc25.x86_64.rpm

sudo dnf -y install --allowerasing *.rpm
```

**Comment by run2cmd** [comment]
I have found that Vim 8.0.1267 is free of this bug. Netrw works there normally. I'm using version for Windows and found that next released is 8.0.1272 (see https://github.com/vim/vim-win32-installer) and that one contains this bug.

So the workaround would be to downgrade to 8.0.1267.

**Comment by bashims** [comment]
I am able to reproduce this issue with the Fedora 27 build 2:8.0.1360-1.fc27. Downgrading to 2:8.0.1176-1.fc27 restored the old behavior.

**Comment by chrisbra** [comment]
you might want to try reverting https://github.com/vim/vim/commit/b0d45e7f5354375edd02afafde3bd37dac1515ff until this has been fixed and new runtime files included.

**Comment by jamessan** [comment]
Why not revert the netrw update in the repo instead?  That helps users not get broken code until Charles has time to send an update to Bram.

**Comment by chrisbra** [comment]
yeah that would work as well, but Bram would have to do it. This [stackoverflow answer](https://stackoverflow.com/a/5669428/789222) shows how to partially revert a commit.

**Comment by brammool** [comment]
I put the plugin files back to the previous version for now.  Let me know if it's better.  I know that this will also bring back a few older problems, hopefully less severe.

**Comment by cecamp** [comment]
Bram Moolenaar wrote:
>
> I put the plugin files back to the previous version for now. Let me
> know if it's better. I know that this will also bring back a few older
> problems, hopefully less severe.
>
>
Just wanted to let you know that I'll be working this problem -- but
after I give&grade final exams, so not until next week.  I started in on
one problem but found it intrroduced another, so I need to get that
fixed, too.

Regards,
Chip Campbell

**Comment by k-takata** [comment]
Hi Dr. Chip,

There are more than 20 issues related to netrw in this repository.
You can easily find them by searching the `plugin-netrw` label:
https://github.com/vim/vim/labels/plugin-netrw

Please also care about these issues.
Thanks.

**Comment by atav32** [comment]
yup, just ran `brew upgrade vim`, which put me at version 8.0.1400, and it's back to its ol' reliable self
