### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by alphaCTzo7G** [vim/vim#2157]
NA

**Comment by vim-ml** [comment]
On 2017-09-25, Dibyadeep Paul wrote:

> I posted an example screenshot below:
> 
> vim_alias

Just in case you haven't noticed by now, your screenshot didn't make
it to the mailing list.  If you have information like that that's
important to a discussion, it is better if you include that
information as text in your message, not as any sort of graphic.
It's easy to copy text from vim or gvim into a clipboard.

> Questions:
> 
>  1. What do you guys think?
> 
>  2. How easy or difficult is to remove the command aliases from VIM?

I don't think it's a good idea to remove aliases, or make any other
changes to the UI that will break scripts or otherwise frustrate
users, but I would rather discuss some concrete examples than talk
in generalities.

Regards,
Gary

**Comment by chrisbra** [comment]
I don't see how removing aliases will help users to better use Vim. I think it will rather confuse users and breaks existing scripts, if their existing commands do not work anymore.

**Comment by brammool** [comment]
Let's not change this.

**Comment by alphaCTzo7G** [comment]
Makes sense..
