### ISSUE TITLE
last search pattern concealed after invoking `matchadd()` to conceal any regex

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#2185]
- vim --version: 8.0 patches up to 1173
   - Operating system: Linux, Ubuntu 16.04
   - Terminal name: xfce4-terminal
   - $TERM: xterm-256color

Consider this minimal `/tmp/vimrc`:

    let @/ = '\cconceal'
    set hlsearch
    setlocal concealcursor=nc conceallevel=1
    call matchadd('Conceal', '.$', 1, -1, {'conceal': '_'})

After starting Vim like this:

    vim -Nu /tmp/vimrc /tmp/vimrc

The last character on every line is concealed, like expected, but the word `conceal` is also concealed. I don't understand why, as the regex passed to `matchadd()` is `.$`. It should only affect the last character on every line, not the last search pattern.

I found this issue ( [highlighting conflicts when using conceal #229](https://github.com/vim/vim/issues/229) ) which is similar but not exactly the same. The issue #229 seems to be about a conflict between different syntax highlighting mechanisms (`'hlsearch'`, `'cursorline'`, concealed characters).

But this issue is about the last search pattern which shouldn't be concealed at all.
It only happens when `'hlsearch'` is enabled.

The only solution which I found for the moment is to lower the priority of the match to `0`, so that its priority  is not greater than the one created by `'hlsearch'`:

        call matchadd('Conceal', '.$', 0, -1, {'conceal': '_'})

**Comment by lacygoill** [comment]
Lowering the priority of the match seems a good enough solution for the moment. So, I close the issue.

**Comment by sentientmachine** [comment]
Another hack work around is to use the regular expressions of the 2nd parameter passed to matchadd to have it assert: "highlight only the first instance in the string" and then make a secondary matchadd to assert "highlight only the last instance".  

Then the first match color won't be obscured by the second because they are different instances of a match.  If your regex fu is strong, there are wildcards that can enumerate the first, second, third, fourth, and nth instances of your match using a for loop and making matchadds for each, the drawback is this boggs down the snappiness of the refresh after some 30 to 60 instances.
