### ISSUE TITLE
--disable-terminal doesn't work when --with-features=huge

### ISSUE THREAD

**Issue by lindhobe** [vim/vim#2242]
While working through issue #2238, I discovered that `--disable-terminal` doesn't work when `--with-features=huge`.  Dropping back to `--with-features=big` dropped the terminal emulator without any other action being required.

**Comment by nuko8** [comment]
The following should suffice to fix the issue:  Stop overwriting`enable_terminal` if either `--enable-terminal` or `--disable-terminal` is given, and, when that is the case, rely on the value of `enable_terminal` that is to be set appropriately by `configure`:
```diff
diff --git a/src/configure.ac b/src/configure.ac
index f4650962b..939c84eb5 100644
--- a/src/configure.ac
+++ b/src/configure.ac
@@ -2035,7 +2035,7 @@ fi
 AC_MSG_CHECKING(--enable-terminal argument)
 AC_ARG_ENABLE(terminal,
 	[  --enable-terminal       Enable terminal emulation support.],
-	[enable_terminal="yes"], [enable_terminal="auto"])
+	[], [enable_terminal="auto"])
 if test "$enable_terminal" = "yes" || test "$enable_terminal" = "auto" -a "x$features" = "xhuge" ; then
   if test "x$features" = "xtiny" -o "x$features" = "xsmall"; then
     AC_MSG_RESULT([cannot use terminal emulator with tiny or small features])
```
Note that `+terminal` is default for the Huge feature set whereas `-terminal` for the rest.  So, in order to exclude the terminal feature from Huge, `--disable-terminal`, or equivalently, `--enable-terminal=no`, still needs to be passed to `configure`.
