### ISSUE TITLE
CmdlineLeave event not triggered when moving from command-line to command-line window

### ISSUE THREAD

**Issue by markonm** [vim/vim#2263]
OS: Windows
Vim: 8.0.1236

It is triggered when exiting from command-line window to normal mode with `i<cr>`. When I check `mode()` output inside command-line window it returns `n`. So even though `mode()` output is changed from `c` to `n` `CmdlineLeave` event is scheduled to fire after leaving command-line window. If we leave command-line window with `:q<cr>` CmdlineLeave event is triggered two times in a row. 

Is this intended behavior? 

I think it would be more intuitive to trigger `CmdlineLeave` immediately when moving from command-line to command-line window.

**Comment by brammool** [comment]
> OS: Windows
> Vim: 8.0.1236
> 
> It is triggered when exiting from command-line window to normal mode
> with `i<cr>`. When I check `mode()` output inside command-line window
> it returns `n`. So even though `mode()` output is changed from `c` to
> `n` `CmdlineLeave` event is scheduled to fire after leaving
> command-line window. If we leave command-line window with `:q<cr>`
> CmdlineLeave event is triggered two times in a row. 
> 
> Is this intended behavior? 
> 
> I think it would be more intuitive to trigger `CmdlineLeave`
> immediately when moving from command-line to command-line window.

I don't understand what you are doing.  Please give step-by-step
reproduction instructions.

-- 
I wonder, do vegetarians eat fruit bats?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfredl** [comment]
@xtal8 does not CmdWinEnter cover your use case?

**Comment by markonm** [comment]
## First example
1. `vim --clean -S reproduce.vim`
2. `:`
3. `<c-f>`
4. `i<cr>`

CmdlineLeave event is triggered after cursor leaves command-line window.

![2](https://user-images.githubusercontent.com/16160229/32197244-b79d3218-bdc3-11e7-9db4-8869f3375595.gif)
_Number on status line is counting how many times CmdlineLeave event is fired._




## Second example
1. `vim --clean -S reproduce.vim`
2. `:`
3. `<c-f>`
4. `:q<cr>`

CmdlineLeave event is triggered two times in a row after fourth step.

![1](https://user-images.githubusercontent.com/16160229/32197242-b76fb874-bdc3-11e7-9790-666a5895c2c2.gif)

In both cases CmdlineLeave event is not triggered after cursor leaves command-line first time.

```vim
" reproduce.vim
set laststatus=2
let &statusline=0
au CmdlineLeave :  let &statusline=str2nr(&statusline + 1)
```

@bfredl
In this case CmdWinEnter is fired after leaving command-line, I would expect CmdlineLeave  to fire before leaving command-line.

**Comment by bfredl** [comment]
But when you enter the cmdline window you have not left the  cmdline yet, rather normal mode is invoked nestedly inside cmdline mode (one could say: modes form a stack machine, not a finite state machine). You can leave cmdline window with `<c-c>` and go back to cmdline mode, so `CmdlineLeave` must not be fired  yet. The complete set of events `CmdlineEnter`/`Leave` and `CmdWinEnter`/`Leave` should already allow you to detect any state.

**Comment by chrisbra** [comment]
I think @bfredl  is correct. perhaps this should be made more explicit in the documentation?

**Comment by markonm** [comment]
@bfredl 
Thanks. That explains it. I wrongly assumed how mode changing works.

**Comment by brammool** [comment]
Björn Linse wrote:

> But when you enter the cmdline window you have not left the  cmdline
> yet, rather normal mode is invoked nestedly inside cmdline mode (one
> could say: modes form a stack machine, not a finite state machine). You
> can leave cmdline window with `<c-c>` and go back to cmdline mode, so
> `CmdlineLeave` must not be fired  yet. The complete set of events
> `CmdlineEnter`/`Leave` and `CmdWinEnter`/`Leave` should already allow
> you to detect any state.

Hmm, this depends on what you use the autocommands for.  The most recent
example was to enable and disable 'hlsearch'.  For that CmdlineLeave
should be triggered before CmdwinEnter, so that options can be set for
the command line window.  Also, from the command line window one can
edit another command line, that would result in three levels deep of
state.

I think it's a lot easier if this is seen as entering and leaving the
command line.  The command window is a separate state, from where you
can do other things (e.g. enter Insert mode).

-- 
I bought a book on hair loss, but the pages kept falling out.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by markonm** [comment]
My use case it to make live preview for substitution same as `inccommand` does in Neovim. Currrent behavior of `CmdlineLeave` complicates things as I cannot easily revert buffer to initial state when cursor moves from command-line to command-line window. 

I cannot think of a case where current behavior would be preferable.

**Comment by bfredl** [comment]
> Hmm, this depends on what you use the autocommands for.  The most recent
example was to enable and disable 'hlsearch'.  For that CmdlineLeave
should be triggered before CmdwinEnter, so that options can be set for
the command line window.  

Options can be set for the command line in CmdWinEnter. This will already implement the suggested behavior (modulo some superfluous events that don't change any observable state):
```
		augroup vimrc-incsearch-highlight
		  autocmd!
		  autocmd CmdlineEnter,CmdWinLeave [/\?] :set hlsearch
		  autocmd CmdlineLeave,CmdWinEnter [/\?] :set nohlsearch
		augroup END
```

>  Also, from the command line window one can
edit another command line, that would result in three levels deep of
state.

This nesting is part of how vim works. Similarly `i<c-r>=<c-f>i` will emit two `InsertEnter` without an intermediate `InsertLeave`. This is not a bug, there is two separate unfinished insert states (in different buffers etc) on the stack. Trying to hide (worse, partially hide) the stacking in autocmds will make keeping track of state harder, not easier. (neovim will add a `v:event.level` field, not _technically_ necessary but as a convenience)

> I think it's a lot easier if this is seen as entering and leaving the
command line. 

This is exactly how I see it. The commands currently form matched pairs that track a single invocation of the cmdline. Instead you want the two events to track every time `mode() ==# "c"` changes, which is already covered with the complete set of four events.

> I cannot think of a case where current behavior would be preferable.

I'm also going to work on inccommand-style plugins (also for `:normal`, `:global` etc). And I would like to keep track _both_ of the entire lifetime of a cmdline _and_ mode changes, all of which are currently covered by the 4 mentioned events.

If the behavior is changed, then a variable needs to be added to `CmdlineEnter` and `CmdlineLeave` to distinguish if the cmdline itself or just the mode was entered/left.
(Alternatively there could be `CmdModeEnter` in _addition_ to what there are now, but maybe you don't want to add to many similar events...)

**Comment by markonm** [comment]
Closing. Changing behavior of `CmdlineLeave` would break existing plugins.

**Comment by Integralist** [comment]
👋🏻 I came here looking to find an issue related to getting neovim's `inccommand=nosplit` feature into Vim and this is the only one that sorta looked like it fitted. If that's the case does anyone know if neovim's ability to do dynamic substitutions (i.e. replace _while_ typing) is possible in Vim and just is a matter of time, or is there some kind of restriction that prevents this feature from being implemented? Thanks!

**Comment by chrisbra** [comment]
There is [over.vim](https://github.com/osyo-manga/vim-over) and there is [traces.vim](https://github.com/markonm/traces.vim) which seem to enable something similar 🤔 ? Not sure. If you really want to leave a new feature request, please open a new issue then.

**Comment by Integralist** [comment]
Thanks @chrisbra I'll take a look at those plugins instead 👍🏻
