### ISSUE TITLE
MacBook pro with touch bar: show statusline

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim/vim#2301]
<img width="995" alt="screen shot 2017-11-07 at 4 54 31 pm" src="https://user-images.githubusercontent.com/3514015/32497066-5e425c88-c3dc-11e7-8602-5b08d9a85d55.png">

**Comment by jtoy** [comment]
this would be awesome

**Comment by chrisbra** [comment]
Does apple already provide an API on how to access the touchbar?

**Comment by nuko8** [comment]
Even on Mac, Vim is supposed to run on a terminal such as Terminal.app or iTerm except the well-known case of MacVim (running in GUI mode, not in terminal mode).

In general, when you open a terminal on macOS and then take a look at the menubar, you'll know you have the menu items dedicated to that terminal only regardless whatever command-line app you run on it.  Thus, you've never seen any menu item for Vim there when you run Vim on a terminal.

The same should hold for the touchbar; it should be used primarily by genuine macOS apps; in our case, if it has to be occupied by an app, it's the terminal that deserves that.

Obviously, MacVim in GUI mode could accommodate the proposed touchbar facility since it is designed to make it behave as a genuine macOS app.  That explains why it does have the menu items dedicated only to it on the menubar when it is launched in GUI mode (Compare: Launch MacVIm in terminal mode, say `mvim -v`, and then do `:gui`.  How does the menubar change?).

As to Vim, it's a cross-platform app and thus should avoid disturbing the platform's ground design even if the proposal turns out to be technically possible.

**Comment by vitaly-zdanevich** [comment]
For the future researches - related information about MacVim https://github.com/macvim-dev/macvim/pull/715

**Comment by chrisbra** [comment]
I am closing this, as this is clearly Mac specific.
