### ISSUE TITLE
Problem with new python ]M [M jumps and whitespace

### ISSUE THREAD

**Issue by eguendelman** [vim/vim#2303]
The new python jumps are useful, thank you!  Just one issue I came across is that if you put cursor on `foo` in attached file and use ]M it will jump to end of the following function `bar`, and that is because the blank line between the two functions actually has a space indentation (`:set list` to see).  It seems to confuse the jump function...
Thanks
[test.zip](https://github.com/vim/vim/files/1454379/test.zip)

**Comment by chrisbra** [comment]
Please contact the ftplugin maintainer. You'll find his contact data in the header of https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim

**Comment by tpict** [comment]
Thanks for filing the issue. I have written a fix: https://github.com/tpict/vim-ftplugin-python/commit/68a17679c9f595d1b366381ccb690145e29b521c

**Comment by chrisbra** [comment]
okay closing then.

**Comment by brammool** [comment]
tpict wrote:

> Thanks for filing the issue. I have written a fix:
> https://github.com/tpict/vim-ftplugin-python/commit/68a17679c9f595d1b366381ccb690145e29b521c

Please put your name on your github account, so that we know who you
are.  I can guess it's Tom Picton, but better make sure.

-- 
It is too bad that the speed of light hasn't kept pace with the
changes in CPU speed and network bandwidth. -- <wietse@porcupine.org>

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tpict** [comment]
Done!
