### ISSUE TITLE
All text is highlighted when starting a search with very magic when hlsearch and incsearch are active

### ISSUE THREAD

**Issue by Ram-Z** [vim/vim#2337]
When starting a new search none of the text is highlighted as expected. Then enable very magic (`\v`) and suddenly all text is highlighted. I'd expect this to behave the same way as starting a new search.

Steps to reproduce:
```
$ vim -N -u NONE -c "set hlsearch incsearch" /path/to/file
```

Then type:
```
/\v
```

Expected result: nothing is highlighted
Actual result: entire buffer is highlighted

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2017 13:50:55)
Included patches: 1-1176
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      +toolbar
+cmdline_compl   +jumplist        +perl/dyn        +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      +xsmp_interact
+ex_extra        +mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
```

**Comment by chrisbra** [comment]
See also this discussion on vim_dev: https://groups.google.com/forum/#!topic/vim_dev/J61pNy137Iw

I made a patch, that goes on top of the fix for #2292 

Please see those two commits: 
* https://github.com/chrisbra/vim/commit/cc87161aaafe93ffef19598f193ff680873124b7 (fixes #2292)
* https://github.com/chrisbra/vim/commit/729c55e1a81bd959c41ddd906fed27d54d0eb335 (fixes #2337, e.g. this issue mentioned here)

**Comment by chrisbra** [comment]
Sorry there was an error. Here is an update:

See also this discussion on vim_dev: https://groups.google.com/forum/#!topic/vim_dev/J61pNy137Iw

I made a patch, that goes on top of the fix for #2292 

Please see those two commits: 
* https://github.com/chrisbra/vim/commit/cc87161aaafe93ffef19598f193ff680873124b7 (fixes #2292)
* https://github.com/chrisbra/vim/commit/34535ea989cc98bbb53dedef07b17b080b757f99 (fixes #2337, e.g. this issue mentioned here)

**Comment by haya14busa** [comment]
Awesome! Thanks @chrisbra! 

I looked into the Vim source code before to fix this behavior, but I couldn't find how to fix it...

btw, will `^` or `$` are highlighted? In incsearch.vim plugin,  it suppress highlighting if the pattern is matched with zero width string, but it also turn off the highlight of `^` and `$`.

**Comment by chrisbra** [comment]
> btw, will ^ or $ are highlighted?

Interesting question. I was not sure, how is_zero_width would handle this. Trying it shows, that highlighting would be suppressed. I am unsure, whether this is correct or not.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> > btw, will ^ or $ are highlighted?
> 
> Interesting question. I was not sure, how is_zero_width would handle
> this. Trying it shows, that highlighting would be suppressed. I am
> unsure, whether this is correct or not. 

Highlighting the "$" matches is useful at least.  And then not
highlighting "^" would be unexpected.

We should really try to avoid highlighting everything, matching the
empty string.  But other empy matches are likely to be useful.

-- 
Female engineers become irresistible at the age of consent and remain that
way until about thirty minutes after their clinical death.  Longer if it's a
warm day.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Okay will fix it.

**Comment by chrisbra** [comment]
So how about the following commit:
https://github.com/chrisbra/vim/commit/36e1a98dd254a61dc4293cb3c71fc63d344edba8

This works by checking from the start of the buffer whether the last typed pattern matches with zero-width (and again one position further, so that a pattern like `\<` or `^` can still be highlighted, while e.g. `\zs` won't be highlighted.) However this might potentially slow down Vim, because we have to do the check twice.

Here are some example patterns and some gotchas:
- `\zs` won't be highlighted
- `\v` won't be highlighted
- `\<` will be highlighted
- `^` will be highlighted
- `$` will be highlighted
- `\|` won't be highlighted
- `.` will be highlighted
- `\(foo\)\|` will be highlighted

The last one might be surprising (and it is hard to fix), but I found it actually quite useful. Once you type a complex pattern and it suddenly highlights everything this gives some feedback that you either have made some error or are at a point in the pattern where it would match everything (and this shouldn't happen that often in practice to be really disturbing).

**Comment by brammool** [comment]
Christian wrote:

> So how about the following commit:
> https://github.com/chrisbra/vim/commit/36e1a98dd254a61dc4293cb3c71fc63d344edba8
> 
> This works by checking from the start of the buffer whether the last typed pattern matches with zero-width (and again one position further, so that a pattern like `\<` or `^` can still be highlighted, while e.g. `\zs` won't be highlighted.) However this might potentially slow down Vim, because we have to do the check twice.
> 
> Here are some example patterns and some gotchas:
> - `\zs` won't be highlighted
> - `\v` won't be highlighted
> - `\<` will be highlighted
> - `^` will be highlighted
> - `$` will be highlighted
> - `\|` won't be highlighted
> - `.` will be highlighted
> - `\(foo\)\|` will be highlighted
> 
> The last one might be surprising (and it is hard to fix), but I found
> it actually quite useful. Once you type a complex pattern and it
> suddenly highlights everything this gives some feedback that you
> either have made some error or are at a point in the pattern where it
> would match everything (and this shouldn't happen that often in
> practice to be really disturbing).

Thanks for that overview.  Now I wonder what problem we actually are
trying to solve.

I think we want to avoid highlighting everything while busy typing a
pattern.  But if we type a pattern and we want to see what it's going to
match, highlighting everything is useful, it shows mistakes.

How about this instead: We don't highlight the matches until after a
short delay, so it updates when the user pauses typing.  Then you won't
get all kind of fast flickering, but you do get to see all the matches
after a short pause.

This also avoids any trickery trying to guess what should be highlighted
(and showing something else after pressing Enter).


-- 
Anyone who is capable of getting themselves made President should on no
account be allowed to do the job.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> How about this instead: We don't highlight the matches until after a short delay, so it updates when the user pauses typing. Then you won't get all kind of fast flickering, but you do get to see all the matches after a short pause.

I am sorry, I don't know how to do this. You are not talking about the `char_avail()` function right? Because that is already used in the incsearch code.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> > How about this instead: We don't highlight the matches until after a
> > short delay, so it updates when the user pauses typing. Then you
> > won't get all kind of fast flickering, but you do get to see all the
> > matches after a short pause.
> 
> I am sorry, I don't know how to do this. You are not talking about the
> `char_avail()` function right? Because that is already used in the
> incsearch code.

I very recently added this for the terminal balloon in
check_due_timer().  That is probably the best place for it.  Could
perhaps use 'updatetime', but that's overloaded already.

So, if the timer feature is present, set the "incsearch_redraw_due_set"
flag and store the time in "incsearch_redraw_due".  Add code in
check_due_timer() to do the redrawing, similar to the "bevalexpr" code.
Let's see how this works with half a second delay.

Without the timer feature I suppose we'll just keep it as-is, redraw
right away.

Later we may want to generalise these internal timers. There probably
other things we want to add here.

-- 
How To Keep A Healthy Level Of Insanity:
9. As often as possible, skip rather than walk.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
is this still relevant? I have been looking into this issue again and I am wondering, if this is still relevant and needs a patch or we should close it. There is the `empty_pattern()` function now included with commit 6621605eb97cf5fbc481282fd4d349a76e1 which should theoretically alleviate this problem.

**Comment by chrisbra** [comment]
I have written a preliminary patch for using a timer for incsearch highlighting here chrisbra/vim@3b1b9cb783c4a2a6f2126fd93b786b5f3811413d

**Comment by Ram-Z** [comment]
This is significantly better with `Included patches: 1-1415` (which includes 6621605). The whole buffer isn't highlighted anymore.

There is however still a small difference between `/` and `/\v` in that the current cursor position is highlighted in the latter when it isn't in the former.

I would consider this issue closed, but since @chrisbra still has a commit against this, I'll leave it up to him to close it.

**Comment by chrisbra** [comment]
using my commit will change it how highlighting works when incsearch is set so much, that I would expect a couple of new issues coming in. However once you get used to that incsearch does not kick in immediately, but only after a small pause, it also makes sense. I leave this to Bram to decide whether we need this or not.

**Comment by chrisbra** [comment]
I am closing this. The mentioned patch breaks too many tests, so the patch is probably not correct.
