### ISSUE TITLE
--disable-nls doesn't actually disable NLS

### ISSUE THREAD

**Issue by assistcontrol** [vim/vim#2384]
configure says that you disable NLS with --disable-nls:
```
  --disable-nls           Don't support NLS (gettext()).
```

However, configure seems to ignore that command and it links against libintl.so anyway if it's present. The only way I've found to actually disable NLS is to pass `--enable-nls=no`.

I see the configure block that translates `--disable-foo` into `enable_foo=no`, so I'm not sure why `--disable-nls` isn't doing that.

**Comment by brammool** [comment]
Adam Weinberger wrote:

> configure says that you disable NLS with --disable-nls:
> ```
>   --disable-nls           Don't support NLS (gettext()).
> ```
> 
> However, configure seems to ignore that command and it links against libintl.so anyway if it's present. The only way I've found to actually disable NLS is to pass `--enable-nls=no`.
> 
> I see the configure block that translates `--disable-foo` into `enable_foo=no`, so I'm not sure why `--disable-nls` isn't doing that.

It works fine for me.

	configure .... --disable-nls 

log:
	configure:13752: checking --disable-nls argument
	configure:13906: result: yes

auto/config.mk:

	INSTALL_LANGS	= 
	INSTALL_TOOL_LANGS	=

I understand that saying "yes" for "not enabled" can be confusing.


-- 
hundred-and-one symptoms of being an internet addict:
49. You never have to deal with busy signals when calling your ISP...because
    you never log off.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by assistcontrol** [comment]
Oh! Oh geeze you're completely right, Bram. This error was encountered on FreeBSD, and it was due to the switch being coded incorrectly. Sorry for the noise!
