### ISSUE TITLE
tags-file: `call cursor(x, y)` doesn't work as a tag-address without a `"` at the end

### ISSUE THREAD

**Issue by pjrt** [vim/vim#2402]
Reading `:h tags-file-format`, it says that the address (the command used to move the cursor to the tag location) can contain a `;"` to make it backwards compatible. 

http://vimdoc.sourceforge.net/htmldoc/tagsrch.html#tags-file-format

```
{term}		;" The two characters semicolon and double quote.  This is
		interpreted by Vi as the start of a comment, which makes the
		following be ignored.  This is for backwards compatibility
		with Vi, it ignores the following fields.
```

Most tag file generating programs use `/some-search/` as the command here, and that works fine. However I can't get it to work with `call cursor`. I made a tag generating tool that uses `call cursor` as the command for moving the cursor, however I can't get it to work as the doc says it should. 

First thing I tried was generating a plain `call cursor(x, y)` since `call cursor` isn't a `vi` command (so my tool isn't vi compatible). This means I generate something like this:

```
compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7)	language:scala
```

However, when I do that and try to call `:tag compareTags` I get `E488: Trailing characters`. This means vim does care about this? So next I tried adding `:"` at the end:

```
compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7);"	language:scala
```

But I get the *same error*. Finally, I just tried:

```
compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7)"	language:scala
```

I did this because I've never heard of `;` being a comment in vimL, only `"`, and it worked! Only with that was I able to get `:tag compareTags` to work. 

Is the documentation wrong? Or am I reading it incorrectly.

**Comment by brammool** [comment]
Pedro Rodriguez Tavarez wrote:

> Reading `:h tags-file-format`, it says that the address (the command used to move the cursor to the tag location) can contain a `;"` to make it backwards compatible. 
> 
> http://vimdoc.sourceforge.net/htmldoc/tagsrch.html#tags-file-format
> 
> ```
> {term}		;" The two characters semicolon and double quote.  This is
> 		interpreted by Vi as the start of a comment, which makes the
> 		following be ignored.  This is for backwards compatibility
> 		with Vi, it ignores the following fields.
> ```
> 
> Most tag file generating programs use `/some-search/` as the command here, and that works fine. However I can't get it to work with `call cursor`. I made a tag generating tool that uses `call cursor` as the command for moving the cursor, however I can't get it to work as the doc says it should. 
> 
> First thing I tried was generating a plain `call cursor(x, y)` since `call cursor` isn't a `vi` command (so my tool isn't vi compatible). This means I generate something like this:
> 
> ```
> compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7)	language:scala
> ```
> 
> However, when I do that and try to call `:tag compareTags` I get `E488: Trailing characters`. This means vim does care about this? So next I tried adding `:"` at the end:
> 
> ```
> compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7);"	language:scala
> ```
> 
> But I get the *same error*. Finally, I just tried:
> 
> ```
> compareTags	../stags/src/test/scala/co/pjrt/stags/Utils.scala	call cursor(15, 7)"	language:scala
> ```
> 
> I did this because I've never heard of `;` being a comment in vimL, only `"`, and it worked! Only with that was I able to get `:tag compareTags` to work. 
> 
> Is the documentation wrong? Or am I reading it incorrectly.

The ;" works to terminate an address, such as a line number or search
string.  You are using an Ex command, there using a single " before a
comment works.  However, since the ;" is missing the extra fields won't
be found.  You can use

compareTags	Utils.scala	call cursor(15, 7)" ;"	language:scala

Thus put the ;" inside the comment


-- 
I got a new desk stapler. It broke on the first desk I tried.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pjrt** [comment]
Not sure I follow, so the `"` is part of the Ex command? What does `call cursor(x, y)"` mean? (I understand what `call cursor` is, just not sure what the `"` is doing).

**Comment by pjrt** [comment]
Wait, are you saying that `"` is the comment? Then what's the purpose of `;"`? And most other tags software just have `/seach/;"`.  Is the `;` part of the `/search/` command?

**Comment by brammool** [comment]
Pedro Tavarez wrote:

> Wait, are you saying that `"` is the comment? Then what's the purpose
> of `;"`? And most other tags software just have `/seach/;"`.  Is the
> `;` part of the `/search/` command?

The double quote is the start of a comment.  The rest of the line is
ignored when it is executed.

For an address ;" is used, because the semicolon ends the address.

When parsing a tags file the code specifically looks for the ;" to
locate the extra fields.

call cursor(11, 22) positions the cursor in line 11 column 22, which
should be where the tag is defined.  This is brittle, if lines are
inserted or deleted the position will change.  That's why most tags are
defined with a search string.

-- 
hundred-and-one symptoms of being an internet addict:
70. ISDN lines are added to your house on a hourly basis

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pjrt** [comment]
> When parsing a tags file the code specifically looks for the ;" to
locate the extra fields.

If that's the case, then the doc is wrong. The doc makes it seem like it is a hack to make it compatible with vi, but you are saying it is actually required (even if you never expect the tag to be called from within vi). 

> This is brittle, if lines are
inserted or deleted the position will change.  That's why most tags are
defined with a search string.

Good point, didn't think about that. Thanks.

**Comment by andymass** [comment]
I agree the behavior is either wrong or the documentation is very misleading.  The format is listed as:

 "{tagname}		{TAB} {tagfile} {TAB} {tagaddress} {term} {field}"

Where tagaddress is any ex command.  However if you actually use any ex command other than a line number or pattern, vim does not parse the terminator `;"` and instead keeps it as part of the command.  So you lose kind and any extra fields (displayed in eg, tselect)

**Comment by brammool** [comment]
> I agree the behavior is either wrong or the documentation is very misleading.  The format is listed as:
> 
>  "{tagname}		{TAB} {tagfile} {TAB} {tagaddress} {term} {field}"
> 
> Where tagaddress is any ex command.  However if you actually use any
> ex command other than a line number or pattern, vim does not parse the
> terminator `;"` and instead keeps it as part of the command.  So you
> lose kind and any extra fields (displayed in eg, tselect)

Right, the command is found but any fields are ignored.

Since the command can be anything, we need a reliable way to find the
end.  I think using |;" is specific enough.  The bar is then dropped
from the command.

-- 
ARTHUR: The swallow may fly south with the sun, or the house martin or the
        plover seek warmer hot lands in winter, yet these are not strangers to
        our land.
SOLDIER: Are you suggesting coconuts migrate?
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
