### ISSUE TITLE
heap-use-after-free in ex_vimgrep

### ISSUE THREAD

**Issue by gy741** [vim/vim#2474]
Hello.

I found a heap-use-after-free bug in vim.

Please confirm.

Thanks.

Summary: heap-use-after-free
OS: CentOS 7 64bit
Version: b254af3
PoC Download:  [free_ex_vimgrep.zip](https://github.com/vim/vim/files/1569891/free_ex_vimgrep.zip)

Steps to reproduce:
1.Download the .POC files.
2.Compile the source code with ASan.
3.Execute the following command
:  ./vim -u NONE -Z -X -e -s -S $POC -c :qa!

```
=================================================================
==24735==ERROR: AddressSanitizer: heap-use-after-free on address 0x61a000017a88 at pc 0x000000ec1a42 bp 0x7ffcb82e66f0 sp 0x7ffcb82e66e8
READ of size 4 at 0x61a000017a88 thread T0
    #0 0xec1a41 in ex_vimgrep /home/karas/vim/src/quickfix.c:4337:39
    #1 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #2 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #3 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #4 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #5 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #6 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #7 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #8 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #9 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #10 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #11 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #12 0x7f73a93f482f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #13 0x41aaa8 in _start (/home/karas/vim/src/vim+0x41aaa8)

0x61a000017a88 is located 8 bytes inside of 1216-byte region [0x61a000017a80,0x61a000017f40)
freed by thread T0 here:
    #0 0x4baa50 in __interceptor_cfree.localalias.0 (/home/karas/vim/src/vim+0x4baa50)
    #1 0xbf0b8b in vim_free /home/karas/vim/src/misc2.c:1801:2
    #2 0xe96e04 in ll_free_all /home/karas/vim/src/quickfix.c:1419:2
    #3 0xe967ba in qf_free_all /home/karas/vim/src/quickfix.c:1432:2
    #4 0x148f76a in win_free /home/karas/vim/src/window.c:4692:5
    #5 0x14abdf4 in win_free_mem /home/karas/vim/src/window.c:2572:5
    #6 0x1475d99 in win_close /home/karas/vim/src/window.c:2413:10
    #7 0x14a811e in close_windows /home/karas/vim/src/window.c:2123:10
    #8 0x50633d in do_buffer /home/karas/vim/src/buffer.c:1465:6
    #9 0x50db89 in do_bufdel /home/karas/vim/src/buffer.c:1156:15
    #10 0x89ad33 in ex_bunload /home/karas/vim/src/ex_docmd.c:5535:19
    #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #13 0x9bc1d0 in apply_autocmds_group /home/karas/vim/src/fileio.c:9719:2
    #14 0x97e56f in apply_autocmds_exarg /home/karas/vim/src/fileio.c:9270:12
    #15 0x968ac4 in readfile /home/karas/vim/src/fileio.c:389:10
    #16 0xed14da in load_dummy_buffer /home/karas/vim/src/quickfix.c:4620:20
    #17 0xec18c1 in ex_vimgrep /home/karas/vim/src/quickfix.c:4325:12
    #18 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #19 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #20 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #21 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #22 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #23 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #24 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #25 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #26 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #27 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #28 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #29 0x7f73a93f482f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291

previously allocated by thread T0 here:
    #0 0x4babd8 in malloc (/home/karas/vim/src/vim+0x4babd8)
    #1 0xbece08 in lalloc /home/karas/vim/src/misc2.c:954:21
    #2 0xbecd57 in alloc /home/karas/vim/src/misc2.c:852:13
    #3 0xe9b711 in ll_new_list /home/karas/vim/src/quickfix.c:1536:23
    #4 0xe9200f in ll_get_or_alloc_list /home/karas/vim/src/quickfix.c:1564:16
    #5 0xebfa5a in ex_vimgrep /home/karas/vim/src/quickfix.c:4203:7
    #6 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #7 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #8 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
    #9 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
    #10 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
    #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
    #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
    #13 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
    #14 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
    #15 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
    #16 0x1642d2d in main /home/karas/vim/src/main.c:429:12
    #17 0x7f73a93f482f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: heap-use-after-free /home/karas/vim/src/quickfix.c:4337:39 in ex_vimgrep
Shadow bytes around the buggy address:
  0x0c347fffaf00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fffaf40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c347fffaf50: fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffaf90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c347fffafa0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24735==ABORTING
```
=================
[Acknowledgement]
This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001, Innovation hub for high Performance Computing]

**Comment by vim-ml** [comment]
Hi,

On Mon, Dec 18, 2017 at 4:47 PM, gy741 <vim-dev-github@256bit.org> wrote:
> Hello.
>
> I found a heap-use-after-free bug in vim.
>
> Please confirm.
>

The attached patch fixes this crash. I am still trying to write a simple
test case to reproduce the crash. There are still other cases where the
buffer/window is removed while lvimgrep is processing the results
which results in a crash.

Regards,
Yegappan

>
> Thanks.
>
> Summary: heap-use-after-free
> OS: CentOS 7 64bit
> Version: b254af3
> PoC Download: free_ex_vimgrep.zip
>
> Steps to reproduce:
> 1.Download the .POC files.
> 2.Compile the source code with ASan.
> 3.Execute the following command
> : ./vim -u NONE -Z -X -e -s -S $POC -c :qa!
>
> =================================================================
> ==24735==ERROR: AddressSanitizer: heap-use-after-free on address
> 0x61a000017a88 at pc 0x000000ec1a42 bp 0x7ffcb82e66f0 sp 0x7ffcb82e66e8
> READ of size 4 at 0x61a000017a88 thread T0
>     #0 0xec1a41 in ex_vimgrep /home/karas/vim/src/quickfix.c:4337:39
>     #1 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #2 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #3 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
>     #4 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
>     #5 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
>     #6 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #7 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #8 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
>     #9 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
>     #10 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
>     #11 0x1642d2d in main /home/karas/vim/src/main.c:429:12
>     #12 0x7f73a93f482f in __libc_start_main
> /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
>     #13 0x41aaa8 in _start (/home/karas/vim/src/vim+0x41aaa8)
>
> 0x61a000017a88 is located 8 bytes inside of 1216-byte region
> [0x61a000017a80,0x61a000017f40)
> freed by thread T0 here:
>     #0 0x4baa50 in __interceptor_cfree.localalias.0
> (/home/karas/vim/src/vim+0x4baa50)
>     #1 0xbf0b8b in vim_free /home/karas/vim/src/misc2.c:1801:2
>     #2 0xe96e04 in ll_free_all /home/karas/vim/src/quickfix.c:1419:2
>     #3 0xe967ba in qf_free_all /home/karas/vim/src/quickfix.c:1432:2
>     #4 0x148f76a in win_free /home/karas/vim/src/window.c:4692:5
>     #5 0x14abdf4 in win_free_mem /home/karas/vim/src/window.c:2572:5
>     #6 0x1475d99 in win_close /home/karas/vim/src/window.c:2413:10
>     #7 0x14a811e in close_windows /home/karas/vim/src/window.c:2123:10
>     #8 0x50633d in do_buffer /home/karas/vim/src/buffer.c:1465:6
>     #9 0x50db89 in do_bufdel /home/karas/vim/src/buffer.c:1156:15
>     #10 0x89ad33 in ex_bunload /home/karas/vim/src/ex_docmd.c:5535:19
>     #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #13 0x9bc1d0 in apply_autocmds_group /home/karas/vim/src/fileio.c:9719:2
>     #14 0x97e56f in apply_autocmds_exarg
> /home/karas/vim/src/fileio.c:9270:12
>     #15 0x968ac4 in readfile /home/karas/vim/src/fileio.c:389:10
>     #16 0xed14da in load_dummy_buffer /home/karas/vim/src/quickfix.c:4620:20
>     #17 0xec18c1 in ex_vimgrep /home/karas/vim/src/quickfix.c:4325:12
>     #18 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #19 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #20 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
>     #21 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
>     #22 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
>     #23 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #24 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #25 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
>     #26 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
>     #27 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
>     #28 0x1642d2d in main /home/karas/vim/src/main.c:429:12
>     #29 0x7f73a93f482f in __libc_start_main
> /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
>
> previously allocated by thread T0 here:
>     #0 0x4babd8 in malloc (/home/karas/vim/src/vim+0x4babd8)
>     #1 0xbece08 in lalloc /home/karas/vim/src/misc2.c:954:21
>     #2 0xbecd57 in alloc /home/karas/vim/src/misc2.c:852:13
>     #3 0xe9b711 in ll_new_list /home/karas/vim/src/quickfix.c:1536:23
>     #4 0xe9200f in ll_get_or_alloc_list
> /home/karas/vim/src/quickfix.c:1564:16
>     #5 0xebfa5a in ex_vimgrep /home/karas/vim/src/quickfix.c:4203:7
>     #6 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #7 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #8 0x813fb7 in do_source /home/karas/vim/src/ex_cmds2.c:4411:5
>     #9 0x810477 in cmd_source /home/karas/vim/src/ex_cmds2.c:4024:14
>     #10 0x810596 in ex_source /home/karas/vim/src/ex_cmds2.c:3999:2
>     #11 0x847da1 in do_one_cmd /home/karas/vim/src/ex_docmd.c:2908:2
>     #12 0x82727d in do_cmdline /home/karas/vim/src/ex_docmd.c:1071:17
>     #13 0x82c835 in do_cmdline_cmd /home/karas/vim/src/ex_docmd.c:671:12
>     #14 0x1658084 in exe_commands /home/karas/vim/src/main.c:2953:2
>     #15 0x1651bc6 in vim_main2 /home/karas/vim/src/main.c:800:2
>     #16 0x1642d2d in main /home/karas/vim/src/main.c:429:12
>     #17 0x7f73a93f482f in __libc_start_main
> /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
>
> SUMMARY: AddressSanitizer: heap-use-after-free
> /home/karas/vim/src/quickfix.c:4337:39 in ex_vimgrep
> Shadow bytes around the buggy address:
>   0x0c347fffaf00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c347fffaf40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> =>0x0c347fffaf50: fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffaf90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
>   0x0c347fffafa0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07
>   Heap left redzone:       fa
>   Heap right redzone:      fb
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack partial redzone:   f4
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
> ==24735==ABORTING
>
> =================
> [Acknowledgement]
> This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001,
> Innovation hub for high Performance Computing]
>

diff --git a/src/quickfix.c b/src/quickfix.c
index 6e80ddfca..f670d805a 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -4149,6 +4149,7 @@ ex_vimgrep(exarg_T *eap)
     int		fi;
     qf_info_T	*qi = &ql_info;
 #ifdef FEAT_AUTOCMD
+    qf_info_T	*save_qi;
     qfline_T	*cur_qf_start;
 #endif
     long	lnum;
@@ -4273,8 +4274,9 @@ ex_vimgrep(exarg_T *eap)
     mch_dirname(dirname_start, MAXPATHL);
 
 #ifdef FEAT_AUTOCMD
-     /* Remember the value of qf_start, so that we can check for autocommands
-      * changing the current quickfix list. */
+     /* Remember the current values of the quickfix list and qf_start, so that
+      * we can check for autocommands changing the current quickfix list. */
+    save_qi = qi;
     cur_qf_start = qi->qf_lists[qi->qf_curlist].qf_start;
 #endif
 
@@ -4334,6 +4336,21 @@ ex_vimgrep(exarg_T *eap)
 	    using_dummy = FALSE;
 
 #ifdef FEAT_AUTOCMD
+	if (eap->cmdidx == CMD_lgrep
+		|| eap->cmdidx == CMD_lvimgrep
+		|| eap->cmdidx == CMD_lgrepadd
+		|| eap->cmdidx == CMD_lvimgrepadd)
+	{
+	    /*
+	     * Verify that the location list is still valid. An autocmd might
+	     * have freed the location list.
+	     */
+	    if (save_qi != GET_LOC_LIST(curwin))
+	    {
+		EMSG(_("E926: Current location list was changed"));
+		goto theend;
+	    }
+	}
 	if (cur_qf_start != qi->qf_lists[qi->qf_curlist].qf_start)
 	{
 	    int idx;

**Comment by dpelle** [comment]
Yegappan wrote:

> I am still trying to write a simple test case to reproduce the crash. 

I could simply the case that triggers the crash with vim-8.0.1418
to this  (perhaps we can do even simpler?):
```
$ vim -u NONE -c'au * * bw#' -c'e x' -csp -c'lvé x'
Vim: Caught deadly signal SEGV

Vim: Finished.
Segmentation fault (core dumped)
```

**Comment by dpelle** [comment]
I wrote earlier:

> I could simply the case that triggers the crash with vim-8.0.1418
> to this (perhaps we can do even simpler?):
> 
> $ vim -u NONE -c'au * * bw#' -c'e x' -csp -c'lvé x'
> Vim: Caught deadly signal SEGV

Here is a better case that crashes (without diacritics this time):
```
$ vim -u NONE -c'au * * bw#' -c'e x' -csp -c'lv x x'
Vim: Caught deadly signal SEGV

Vim: Finished.
Segmentation fault (core dumped)
```

**Comment by vim-ml** [comment]
Hi Dominique,

On Thu, Dec 21, 2017 at 4:29 AM, Dominique Pellé
<vim-dev-github@256bit.org> wrote:
> I wrote earlier:
>
> I could simply the case that triggers the crash with vim-8.0.1418
> to this (perhaps we can do even simpler?):
>
> $ vim -u NONE -c'au * * bw#' -c'e x' -csp -c'lvé x'
> Vim: Caught deadly signal SEGV
>
> Here is a better case that crashes (without diacritics this time):
>
> $ vim -u NONE -c'au * * bw#' -c'e x' -csp -c'lv x x'
> Vim: Caught deadly signal SEGV
>
> Vim: Finished.
> Segmentation fault (core dumped)
>

Thanks for the simplified test. The attached patch fixes this crash and
another crash when using lexpr. I found a few other places where this
autocmd can crash Vim. I am still working on fixing those.

Regards,
Yegappan

diff --git a/src/quickfix.c b/src/quickfix.c
index 5deaed531..c99afe32c 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -144,6 +144,7 @@ static int	qf_get_fnum(qf_info_T *qi, int qf_idx, char_u *, char_u *);
 static char_u	*qf_push_dir(char_u *, struct dir_stack_T **, int is_file_stack);
 static char_u	*qf_pop_dir(struct dir_stack_T **);
 static char_u	*qf_guess_filepath(qf_info_T *qi, int qf_idx, char_u *);
+static int	qflist_valid(win_T *wp, int_u qf_id);
 static void	qf_fmt_text(char_u *text, char_u *buf, int bufsize);
 static void	qf_clean_dir_stack(struct dir_stack_T **);
 static int	qf_win_pos_update(qf_info_T *qi, int old_qf_index);
@@ -1927,6 +1928,29 @@ qf_guess_filepath(qf_info_T *qi, int qf_idx, char_u *filename)
     return ds_ptr==NULL? NULL: ds_ptr->dirname;
 }
 
+/*
+ * Returns TRUE if a quickfix/location list with the given identifier exists.
+ */
+    static int
+qflist_valid (win_T *wp, int_u qf_id)
+{
+    qf_info_T	*qi = &ql_info;
+    int		i;
+
+    if (wp != NULL)
+    {
+	qi = GET_LOC_LIST(wp);	    /* Location list */
+	if (qi == NULL)
+	    return FALSE;
+    }
+
+    for (i = 0; i < qi->qf_listcount; ++i)
+	if (qi->qf_lists[i].qf_id == qf_id)
+	    return TRUE;
+
+    return FALSE;
+}
+
 /*
  * When loading a file from the quickfix, the auto commands may modify it.
  * This may invalidate the current quickfix entry.  This function checks
@@ -2343,14 +2367,26 @@ qf_jump_edit_buffer(
     else
     {
 	int old_qf_curlist = qi->qf_curlist;
+	int save_qfid = qi->qf_lists[qi->qf_curlist].qf_id;
 
 	retval = buflist_getfile(qf_ptr->qf_fnum,
 		(linenr_T)1, GETF_SETMARK | GETF_SWITCH, forceit);
-	if (qi != &ql_info && !win_valid_any_tab(oldwin))
+
+	if (qi != &ql_info)
 	{
-	    EMSG(_("E924: Current window was closed"));
-	    *abort = TRUE;
-	    *opened_window = FALSE;
+	    /*
+	     * Location list. Check whether the associated window is still
+	     * present and the list is still valid.
+	     */
+	    if (!win_valid_any_tab(oldwin))
+	    {
+		EMSG(_("E924: Current window was closed"));
+		*abort = TRUE;
+		*opened_window = FALSE;
+	    } else if (!qflist_valid(oldwin, save_qfid)) {
+		EMSG(_("E926: Current location list was changed"));
+		*abort = TRUE;
+	    }
 	}
 	else if (old_qf_curlist != qi->qf_curlist
 		|| !is_qf_entry_present(qi, qf_ptr))
@@ -4065,6 +4101,7 @@ ex_cfile(exarg_T *eap)
     qf_info_T	*qi = &ql_info;
 #ifdef FEAT_AUTOCMD
     char_u	*au_name = NULL;
+    int		save_qfid;
 #endif
     int		res;
 
@@ -4122,8 +4159,15 @@ ex_cfile(exarg_T *eap)
     if (res >= 0 && qi != NULL)
 	qf_list_changed(qi, qi->qf_curlist);
 #ifdef FEAT_AUTOCMD
+    save_qfid = qi->qf_lists[qi->qf_curlist].qf_id;
     if (au_name != NULL)
 	apply_autocmds(EVENT_QUICKFIXCMDPOST, au_name, NULL, FALSE, curbuf);
+    /*
+     * Autocmd might have freed the quickfix/location list. Check whether it is
+     * still valid
+     */
+    if (!qflist_valid(wp, save_qfid))
+	return;
 #endif
     if (res > 0 && (eap->cmdidx == CMD_cfile || eap->cmdidx == CMD_lfile))
     {
@@ -4149,8 +4193,11 @@ ex_vimgrep(exarg_T *eap)
     char_u	*p;
     int		fi;
     qf_info_T	*qi = &ql_info;
+    int		loclist_cmd = FALSE;
 #ifdef FEAT_AUTOCMD
+    int_u	save_qfid;
     qfline_T	*cur_qf_start;
+    win_T	*wp;
 #endif
     long	lnum;
     buf_T	*buf;
@@ -4204,6 +4251,7 @@ ex_vimgrep(exarg_T *eap)
 	qi = ll_get_or_alloc_list(curwin);
 	if (qi == NULL)
 	    return;
+	loclist_cmd = TRUE;
     }
 
     if (eap->addr_count > 0)
@@ -4274,8 +4322,9 @@ ex_vimgrep(exarg_T *eap)
     mch_dirname(dirname_start, MAXPATHL);
 
 #ifdef FEAT_AUTOCMD
-     /* Remember the value of qf_start, so that we can check for autocommands
-      * changing the current quickfix list. */
+     /* Remember the current values of the quickfix list and qf_start, so that
+      * we can check for autocommands changing the current quickfix list. */
+    save_qfid = qi->qf_lists[qi->qf_curlist].qf_id;
     cur_qf_start = qi->qf_lists[qi->qf_curlist].qf_start;
 #endif
 
@@ -4335,6 +4384,18 @@ ex_vimgrep(exarg_T *eap)
 	    using_dummy = FALSE;
 
 #ifdef FEAT_AUTOCMD
+	if (loclist_cmd)
+	{
+	    /*
+	     * Verify that the location list is still valid. An autocmd might
+	     * have freed the location list.
+	     */
+	    if (!qflist_valid(curwin, save_qfid))
+	    {
+		EMSG(_("E926: Current location list was changed"));
+		goto theend;
+	    }
+	}
 	if (cur_qf_start != qi->qf_lists[qi->qf_curlist].qf_start)
 	{
 	    int idx;
@@ -4491,6 +4552,13 @@ ex_vimgrep(exarg_T *eap)
     if (au_name != NULL)
 	apply_autocmds(EVENT_QUICKFIXCMDPOST, au_name,
 					       curbuf->b_fname, TRUE, curbuf);
+    /*
+     * The QuickFixCmdPost autocmd may free the quickfix list. Check the list
+     * is still valid.
+     */
+    wp = loclist_cmd ? curwin : NULL;
+    if (!qflist_valid(wp, save_qfid))
+	goto theend;
 #endif
 
     /* Jump to first match. */
@@ -5543,7 +5611,8 @@ ex_cbuffer(exarg_T *eap)
 #endif
 
     /* Must come after autocommands. */
-    if (eap->cmdidx == CMD_lbuffer || eap->cmdidx == CMD_lgetbuffer
+    if (eap->cmdidx == CMD_lbuffer
+	    || eap->cmdidx == CMD_lgetbuffer
 	    || eap->cmdidx == CMD_laddbuffer)
     {
 	qi = ll_get_or_alloc_list(curwin);
@@ -5614,14 +5683,6 @@ ex_cexpr(exarg_T *eap)
 #endif
     int		res;
 
-    if (eap->cmdidx == CMD_lexpr || eap->cmdidx == CMD_lgetexpr
-	    || eap->cmdidx == CMD_laddexpr)
-    {
-	qi = ll_get_or_alloc_list(curwin);
-	if (qi == NULL)
-	    return;
-    }
-
 #ifdef FEAT_AUTOCMD
     switch (eap->cmdidx)
     {
@@ -5643,6 +5704,15 @@ ex_cexpr(exarg_T *eap)
     }
 #endif
 
+    if (eap->cmdidx == CMD_lexpr
+	    || eap->cmdidx == CMD_lgetexpr
+	    || eap->cmdidx == CMD_laddexpr)
+    {
+	qi = ll_get_or_alloc_list(curwin);
+	if (qi == NULL)
+	    return;
+    }
+
     /* Evaluate the expression.  When the result is a string or a list we can
      * use it to fill the errorlist. */
     tv = eval_expr(eap->arg, NULL);
diff --git a/src/testdir/test_autocmd.vim b/src/testdir/test_autocmd.vim
index 0636c4721..d8fddffeb 100644
--- a/src/testdir/test_autocmd.vim
+++ b/src/testdir/test_autocmd.vim
@@ -1178,10 +1178,3 @@ func Test_nocatch_wipe_dummy_buffer()
   call assert_fails('lv½ /x', 'E480')
   au!
 endfunc
-
-func Test_wipe_cbuffer()
-  sv x
-  au * * bw
-  lb
-  au!
-endfunc
diff --git a/src/testdir/test_quickfix.vim b/src/testdir/test_quickfix.vim
index a09ec738e..0787e60e3 100644
--- a/src/testdir/test_quickfix.vim
+++ b/src/testdir/test_quickfix.vim
@@ -3038,3 +3038,43 @@ func Test_lfile_crash()
   call assert_fails('lfile', 'E40')
   au! QuickFixCmdPre
 endfunc
+
+" The following test used to crash vim
+func Test_lbuffer_crash()
+  sv Xtest
+  augroup QF_Test
+    au!
+    au * * bw
+  augroup END
+  lbuffer
+  augroup QF_Test
+    au!
+  augroup END
+endfunc
+
+" The following test used to crash vim
+func Test_lexpr_crash()
+  augroup QF_Test
+    au!
+    au * * call setloclist(0, [], 'f')
+  augroup END
+  lexpr ""
+  augroup QF_Test
+    au!
+  augroup END
+  enew | only
+endfunc
+
+" The following test used to crash Vim
+func Test_lvimgrep_crash()
+  sv Xtest
+  augroup QF_Test
+    au!
+    au * * call setloclist(0, [], 'f')
+  augroup END
+  lvimgrep quickfix test_quickfix.vim
+  augroup QF_Test
+    au!
+  augroup END
+  enew | only
+endfunc
