### ISSUE TITLE
vim overwrites the symbolic link file of .viminfo

### ISSUE THREAD

**Issue by Stonesjtu** [vim/vim#2506]
## description
I made a symbolic link of `.viminfo`, it's opened and interpreted as normal. But once saving to this file, the symbolic link is replaced by a normal file with new contents. I'd see this behaviour as a bug.

## reproduce snippet
```bash
cd ~
mv .viminfo /tmp/
ln -s /tmp/.viminfo
vim foo # make sure you type some commands which vim will save to .viminfo
ls -ali .viminfo # the symbolic file is changed to a normal file
```

**Comment by vim-ml** [comment]
On 2017-12-27, Kaiyu Shi wrote:
> description
> 
> I made a symbolic link of .viminfo, it's opened and interpreted as normal. But
> once saving to this file, the symbolic link is replaced by a normal file with
> new contents. I'd see this behaviour as a bug.
> 
> reproduce snippet
> 
> cd ~
> mv .viminfo /tmp/
> ln -s /tmp/.viminfo
> vim foo # make sure you type some commands which vim will save to .viminfo
> ls -ali .viminfo # the symbolic file is changed to a normal file

See

    :help 'backupcopy'

Regards,
Gary

**Comment by chrisbra** [comment]
closing then.

**Comment by timblaktu** [comment]
It wasn't clear to me what the resolution to this was, so I thought I'd follow up on this. In `h:viminfo` under `Notes for Unix:` it says:

> - The viminfo file cannot be a symbolic link.  This is to avoid security                                                                                                                                                                                                                        issues.

So, a symlinked viminfo is simply not supported, by design. I found a couple references (including this issue and [this old debian bug against vim 6](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=158657#14)) to suggestions that using `backupcopy` could work around this limitation, but I was not able to prevent vim from breaking the symlink using any permutation of backup/backupcopy/writebackup.

**Comment by chrisbra** [comment]
Yes, this is by design. I still have an old patch lying around that "removes" this feature, since this comes up once in a while: https://github.com/chrisbra/vim-mq-patches/blob/master/viminfo_resolve_symlinks

But don't think this is worth it.

**Comment by haysidney** [comment]
I run NixOS with [impermanence](https://nixos.wiki/wiki/Impermanence) which involves symlinking files from my /home ramdisk to a permanent location elsewhere. Because of this Vim security feature I'm not able to persist my .viminfo this way. Are there details anywhere of the security issue that this is preventing? Does my system being impermanent negate it?

I'm trying to disable this feature so that Vim will respect the symlink, but the patch you posted didn't seem to work for me on version 9.0.1897.

**Comment by chrisbra** [comment]
yes, you can also use `:set viminfofile` nowadays
