### ISSUE TITLE
Commands and Visual Selection will be interrupt by a window command from timer

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#2515]
Updating another window's content by `windo` or `{n}wincmd w` in a background timer will break current command (`dd`, `yy`) or visual selection.

eg:

```VimL
function! UpdateWindow()
    if &buftype == 'nofile' && &ft == 'polling'
        " request some result from a background job or network
        " populate some text into current window
    endif
endfunc

function! MyTimer(t)
    " find the right window and populate it
    noautocmd silent windo call UpdateWindow()
    " return the previous window
    noautocmd silent wincmd w
endfunc
```

Or, is it possible to change text in non-current window without a `windo` ?

a common scenario: fetching an online help page.

- A background job is started to request an online help page.
- A new buffer & a new window  are created and filled with a notify like : "requesting ..., wait"
- When job finished , the content will be replaced.

This is so common, text in another window needs to be changed in realtime to get best user experience.
and text in another window can't never be changed in vim unless switch current window / buffer. But switching window / buffer will break commands or selection in current vim version.

That's the problem for every background job.

**Comment by lacygoill** [comment]
I'm not sure this will help, but you can change the text in an arbitrary buffer with `setbufline()`. Examples:

    call setbufline(12, 34, 'hello world')

Will replace the text on the line `34` in the buffer `12` with the text `hello world`.

    call setbufline(12, 3, ['foo', 'bar', 'baz'])

Will replace the texts on the lines `3`, `4` and `5` in the buffer `12` with `foo`, `bar` and `baz`. Note that `setbufline()` can append the text even if the line address is not used, provided that the previous one is. So, suppose you have a buffer whose number is `1` and with no text in it; then this command:

    call setbufline(1, 2, 'hello')

... should successfully write `hello` on the 2nd line, even though initially there was no text on it.

See `:h setbufline()`.

Maybe you could use it to populate the buffer in which you're interested without ever changing the focused window, and thus avoid the issue you're describing.

**Comment by skywind3000** [comment]
That make sense !!
Could I read cursor position in another window without switching current window ?

**Comment by lacygoill** [comment]
I've looked at `:h function-list`, and searched for `cursor` but couldn't find a function able to read the cursor position in another window (there is `term_getcursor()` but it's specific to a terminal buffer). I may have missed it though. It can make sense: maybe the cursor only exists in the currently focused window, and nowhere else. So you would need a function which gives the position of the cursor in an arbitrary window IF you gave the focus to it right now. Again, I don't know such a function.

Maybe someone else does. In the meantime, here are a few suggestions (I haven't tested any of them, so I don't know how reliable they are):

 - instead of letting your job do its work immediately, ask it to install a fire-once autocmd (i.e. removes itself when it's executed) listening to `CursorHold` to give the focus to your window when the user doesn't do anything which could be disrupted (temporarily reduce the value of `'updatetime'` to make it happen more quickly if necessary)
 - use `getcurpos()` to save the last position of the cursor in a variable with an autocmd listening to `WinLeave` (if you need the unique ID of the window, use `win_getid()`; if you have several windows, and you need/want to save the last cursor position in a window-local variable, you can get it back with `getwininfo(your_unique_id)[0].variables.your_variable`)
 - if your window displays a quickfix buffer and all you want is scrolling the window to see its bottom, then you could use `:cbottom` (quickfix window) or `:lbottom` (location window)

**Comment by skywind3000** [comment]
I checked git blame, and found setbufline was added in 8.0.1039 and had a patch in 8.0.1274
it is very nice.

thanks for let me know it and this issue should be closed now.

**Comment by skywind3000** [comment]
btw, `:cbottom` is not enough to handle this, cbottom will scroll the quickfix window to the bottom line and just ignore the cursor position in quickfix window.

a better behavior is that:
1. if the cursor is on the last line, add lines and scroll to the lastline.
2. if the cursor is not on the last line, add lines and quit.

that's what emacs does, which is definitely better than a simple `:cbottom`, 

by default, the output will continue scroll if new line has been added.
but user may browse the text in the output window and move the cursor around,
and the scrolling must be stopped because user are reading some part of output right now.
the scrolling will resume if user move the cursor to the last line again.

I believe most of plugins will need this if they need to refresh buffers in a background job.

**Comment by chrisbra** [comment]
Wasn't the whole point of adding the `:cbottom` command to have a way to scroll the window? If you don't want it to scroll, then have your plugin provide a way to skip the `:cbottom` call.

In any case, this is a slightly different problem then what you originally posted. I am closing this. If you have suggestions for a better `:cbottom` command, please create a separate new issue about it. Thanks.
