### ISSUE TITLE
Reporting bug to vim-dev@vim.org reports error from google

### ISSUE THREAD

**Issue by pkay42** [vim/vim#2535]
Sending an email with bug report to vim-dev@vim.org returns an error:

> We're writing to let you know that the group you tried to contact (vim_dev) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
>
> If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.
>
> Thanks,
>
> Google Groups

Either :help bugs needs to be updated or the settings for the vim-dev group need to be updated to not return error messages.

Thanks

**Comment by chrisbra** [comment]
you need to be subscribed to be able to post to vim-dev. And even then, your first message is moderated.

**Comment by pkay42** [comment]
In that case, the :help bug file should be updated to explain this.  As :help bug is written, it is incorrect: one cannot send an email as directed in the help file.

Hence, this is a bug.

**Comment by micbou** [comment]
That's already the case. See the part in bold:

> 1. Send bug reports to: Vim Developers <vim-dev@vim.org>
   **This is a maillist, you need to become a member first** and many people will
   see the message.  If you don't want that, e.g. because it is a security
   issue, send it to <bugs@vim.org>, this only goes to the Vim maintainer
   (that's Bram).

**Comment by pkay42** [comment]
I am so sorry!  I missed that completely.  I believe I was reading an old page on the web that did not mention needing to be a group member.

Unfortunately, searching online for how to report a bug in vim seems to pull up old options for me; I only realized there was the github issues option from :help bug, after my email to vim-dev got bumped back.

I might put a link to "report a bug" on the vim website page, if I were running it?  It was certainly how I expected to find out how to report a bug, given how other open source projects often have such a link...

Again, apologies.

**Comment by tonymec** [comment]
Christian is perfectly right, but I'll fill it in a little:

• Anyone may read the Vim lists, for instance as Google Groups vim_use, vim_dev and vim_mac. There is also the read-only group vim_announce with low-volume news, but IIUC the other three syndicate it. All issues and pull requests for Vim on github are echoed on vim_dev (and replies to them are posted back on github by a robot) but messages sent separately to the lists, even to the vim_dev list, don't make it to github.
• In order to post to a group, you must first join that group; again, one way to do so is by becoming a member of the corresponding Google Group. Anyone can join for free, and any member may at any time select "all mail", "summary once a day", "summary for every 25 new messages" or "no mail" for each list separately, simply by browsing https://groups.google.com/forum/#!myforums (and, if necessary, logging in to Google) just like for any Google Group.
• Your first post needs to be approved by a human moderator. This is unfortunate, but it is the only way Bram & Co. found to keep these lists as spam-free as can be managed. Since the moderators are few and not paid by Vim, your first message may sit in the queue for anything from a few minutes to several hours depending on when the list moderators are doing what. It's no use repeating that first message several times: the first one is already in the queue, and if all moderators are, at that time, sleeping, shopping, working at a paying job, having lunch or dinner, making love, whatever, they won't see the second copy either until at least one of them comes back.
• Normally, once a moderator has approved you, your later messages will appear in a matter of seconds. Of course, if some spammer finds out about this, sends a first legit-looking message and then spam, he will get banned as soon as a moderator notices it.

I think that's it. Have fun!

Tony.
