### ISSUE TITLE
ch_sendraw with very large strings can cause deadlock

### ISSUE THREAD

**Issue by natebosch** [vim/vim#2548]
If you send a very large string with `ch_sendraw` vim will not do any reading on the channel until it has finished sending the string. If the other side of the channel is also single threaded and happens to be trying to send data it may block it's read. Once the pipe's buffers fill up both sides will be blocked from writing, and won't be doing any reading so we end up in deadlock.

I can work around this issue by keeping a buffer string in vimscript and repeatedly setting a timer with 0 time to write in chunks - the theory being that in between writes we can also do some reads and avoid the deadlock.

It would be nice if the chunking were built in to `ch_sendraw` so it doesn't need to be handled this way.

See a repro here: https://github.com/natebosch/vim-lsc/issues/67#issuecomment-357469091

**Comment by prabirshrestha** [comment]
@natebosch did buffer working for you? For me it still seems to hang with buffer but isn't frequent as it used to be.

**Comment by natebosch** [comment]
This has been working for me after I added chunking to both the server and client.

**Comment by prabirshrestha** [comment]
Any updates on fixing this deadlock? Would be good if vim actually fixes this instead of patching every executables to buffer write to stdout. Currently if I enable auto popup in [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) and [vim-lsp](https://github.com/prabirshrestha/vim-lsp) vim hangs every few mins due to this bug.

**Comment by brammool** [comment]
Prabir Shrestha wrote:

> Any updates on fixing this deadlock? Would be good if vim actually
> fixes this instead of patching every executables to buffer write to
> stdout. Currently if I enable auto popup in
> [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)
> and [vim-lsp](https://github.com/prabirshrestha/vim-lsp) vim hangs
> every few mins due to this bug.

The problem is in the todo list, but there is no hint for a solution
yet.

If you split the calls to ch_sendraw() it works right?
What is the maximum size that works?

-- 
"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
 - Helen Rowland

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by natebosch** [comment]
> What is the maximum size that works?

I haven't experimented to find a maximum but things have been working smoothly with a chunk size of 1024 characters which should be under the page size pretty much anywhere.

**Comment by prabirshrestha** [comment]
>If you split the calls to ch_sendraw() it works right?

This works but for plugins like vim-lsp it becomes unmaintainable since executable are owned by others so I need to keep filing bugs in their repo to support chunking. Ex: https://github.com/theia-ide/typescript-language-server/issues/33

**Comment by brammool** [comment]
> > What is the maximum size that works?
> 
> I haven't experimented to find a maximum but things have been working
> smoothly with a chunk size of 1024 characters which should be under
> the page size pretty much anywhere.

Chopping it up in blocks of 1024 is possible, but it might be quite a
bit slower.  Can you try larger sizes to see where it becomes a problem?

-- 
hundred-and-one symptoms of being an internet addict:
245. You use Real Audio to listen to a radio station from a distant
     city rather than turn on your stereo system.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by prabirshrestha** [comment]
Sees like this one is also related to buffer size. https://github.com/vim/vim/issues/2828. //cc @skywind3000

>I just can't send more than 300+ lines to a job's stdin:
```
" command "type con" will just eat data from stdin
let args = ['cmd', '/C', 'type', 'con']
let opts = { 'out_io':'null', 'err_io':'null', 'in_io':'pipe' }

let job = job_start(args, opts)

" GVim dead here.
for i in range(300)
	call ch_sendraw(job, "12341234123412341234\n")
endfor

echo "done"
```

**Comment by skywind3000** [comment]
I have a similar issue here:
https://github.com/vim/vim/issues/2828

**Comment by skywind3000** [comment]
Yes, still could be reproduced in my 8.1.204.

**Comment by prabirshrestha** [comment]
Found several threads in c and python and seems like the solution is to buffer.

>Writing to a pipe with a full buffer causes your write to block.

https://www.reddit.com/r/Python/comments/1vbie0/subprocesspipe_will_hang_indefinitely_if_stdout/?utm_source=amp&utm_medium=comment_list

https://bugs.python.org/issue9929

Seems like this is common everywhere. We could most likely go with a higher size such as 4096 but not sure if it is OS dependent.

**Comment by chrisbra** [comment]
So would it make sense to have an optional parameter to `ch_sendraw` which determines the buffer size?

**Comment by brammool** [comment]
> So would it make sense to have an optional parameter to `ch_sendraw`
> which determines the buffer size? 

That seems brittle, since someone writing a plugin would have to check
the plaftorm Vim is running on and decide on a size.

How about making the write non-blocking?

-- 
ARTHUR: Charge!
   [They all charge with swords drawn towards the RABBIT.  A tremendous twenty
   second fight with Peckinpahish shots and borrowing heavily also on the
   Kung Fu and karate-type films ensues, in which some four KNIGHTS are
   comprehensively killed.]
ARTHUR: Run away!  Run away!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
non-blocking is fine, except requiring to handle the buffer size. what will happen if the buffer size exceeds 2GB in GVim 32bits version  ?

**Comment by skywind3000** [comment]
make the pipe unwritable ? or disconnect the channel ? kill the child process ?

**Comment by prabirshrestha** [comment]
Having an optional parameter in `ch_sendraw` would be breaking change. Also seems like we cannot set the buffer size when starting the job, since in current vim it will print error when unknown args is passed. Seems like the only option is to actually fix it in vim without breaking any changes.

Here is another interesting article - https://andrewjorgensen.com/post/a-tale-of-two-pipes/
> It turns out that there is a limited buffer size for pipes. On linux you can find this limit by running cat /proc/sys/fs/pipe-max-size. Once this buffer files up and nothing on the other side is reading from the buffer the process will deadlock waiting for space in the buffer to free up. The python documenation does mention the potential to deadlock but does not go into the circumstances where a deadlock can occur.
There are a few ways to work around this issue. The first and easiest is to use subprocess.communicate instead of calling subprocess.wait(). This will continually read off of the STDOUT and STDERR pipes and buffer the messages in memory, wait for the process to finish, and return them both as a tuple once the subprocess has finished. You should be careful here as well since the log output is buffered in memory it has the potential to consume all available memory depending on the output log volume of the subprocess. This is also not suitable for long running processes where python is acting as a supervisor as you will eventually run out of memory.

As for the pipe size https://unix.stackexchange.com/a/11954/206446 for Mac and Linux. 
Mac: 16384 bytes by default
Linux: 65536 bytes since Linux 2.6.11
Windows: Couldn't find one easily. Did see some references of 4k. I can ask the console team at work if this is needed.

Here are some related links to windows deadlock on pipes.
Be careful when redirecting both a process’s stdin and stdout to pipes, for you can easily deadlock - https://blogs.msdn.microsoft.com/oldnewthing/20110707-00/?p=10223

Here is the approach .NET has taken - https://stackoverflow.com/a/2066276/157260
> if you redirect the output in .NET you can easily run into problems if you don't read the output. When the buffer runs out, writes to stdout in the child process will block. One common-ish cause of deadlock is a "parent" process waiting for the "child" to exit, and then reading the output - that won't work if the child needs the parent to read the output to free up buffer space.
.NET has made this slightly easier by allowing an event-driven approach with Process.OutputDataReceived and Process.ErrorDataReceived. This means you don't need to start two threads (one to read stdout, one to read stderr) just to keep the process from blocking...

Seems like we just need to find a good buffer size. It still won't solve the problem of unlimited memory but don't think this is normal at least in my case of language servers where we first get a header and content-length. So once we have read the full message I parse the json and throw away the buffered string. Because I'm using raw mode and know that on stdout/stderr can be called anytime I handle the cases where it may be incomplete.

Might be we can start with a 4k buffer size? I would be happy to try the patch out if anyone has it ready.

**Comment by w0rp** [comment]
I would like it if there was an option to make the `ch_sendraw` call non-blocking, and there was a way to detect if a non-blocking call could be made. (I suppose checking for a particular patch with `has` would be good enough.) [ALE](https://github.com/w0rp/ale) uses `ch_sendraw` to send messages to `tsserver`, and the calls to `ch_sendraw` can interrupt editing in Vim for a few seconds when `tsserver` is still starting up. If the messages were eventually sent in another thread, that would be nice.

**Comment by brammool** [comment]
> I would like it if there was an option to make the `ch_sendraw` call
> non-blocking, and there was a way to detect if a non-blocking call
> could be made. (I suppose checking for a particular patch with `has`
> would be good enough.) [ALE](https://github.com/w0rp/ale) uses
> `ch_sendraw` to send messages to `tsserver`, and the calls to
> `ch_sendraw` can interrupt editing in Vim for a few seconds when
> `tsserver` is still starting up. If the messages were eventually sent
> in another thread, that would be nice.

The functionality for non-blocking writes actually already exists.  But
it is currently only used for the terminal window.

I don't think we should make all channels non-blocking by default, since
it will make detecting errors difficult (writes can be postponed forever
if the connection is lost).

We can add an argument when a channel is created.  And/or when a job is
started.

We could also make it dynamic, although going from non-blocking to
blocking might be a bit tricky.  Probably needs to be done after flusing
all the output.  And I wonder if anyone would use this.  So perhaps we
can just stick with an argument

So we could add the "noblock" argument to ch_open() and job_start().

-- 
Computers are useless. They can only give you answers.
                -- Pablo Picasso

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by w0rp** [comment]
Yes, I think an optional argument for `ch_open` and `job_start` would be helpful. If those were added, I'd add a `has()` check to ALE and add them in to the two files where I open channels and start jobs.

**Comment by w0rp** [comment]
Cheers @brammool!

**Comment by prabirshrestha** [comment]
Still seems to hang for me. @natebosch Can you try disabling chunking on both your client and server and check if setting `noblock=1` solves the issue?
