### ISSUE TITLE
:promptfind dialog text box is not focused

### ISSUE THREAD

**Issue by adamnovak** [vim/vim#2563]
When I run `:promptfind`, or bind a key to that command, or use the Edit->Find menu option, in gvim 7.4.52 on Ubuntu 14.04, the find dialog that appears has the focus on the cancel button and not on the text field. So you can't invoke the find dialog and just type what you want to find; you need to manually click to focus on the text box before typing.

When the dialog appears, focus should be on the text box. Then you can just invoke the dialog (from a command or a hotkey) and immediately type what you want to find.

**Comment by nuko8** [comment]
The issue description is a bit imprecise.  Because of its implementation, that particular dialog box remembers the state of focus at the time when it is closed; therefore, if you close it with a mouse click on the cancel button, the text entry is deprived of focus and thus the dialog behaves as described above when it opens again; on the other hand, if the dialog is closed with <kbd>Esc</kbd> or the mnemonic <kbd>alt+c</kbd>, focus remains on the text entry and thus no issue is raised.  Probably, because of that, the issue has remained obscure until now.

With that understanding, the following patch should fix the issue:
```diff
diff --git a/src/gui_gtk.c b/src/gui_gtk.c
index b321da0d5..ecb15eff7 100644
--- a/src/gui_gtk.c
+++ b/src/gui_gtk.c
@@ -2193,6 +2193,14 @@ find_replace_dialog_create(char_u *arg, int do_replace)
 #endif
 	}
 	gtk_window_present(GTK_WINDOW(frdp->dialog));
+
+	/* For :promptfind dialog, always give keyboard focus to 'what' entry.
+	 * For :promptrepl dialog, give it to 'with' entry if 'what' has an
+	 * non-empty entry; otherwise, to 'what' entry. */
+	gtk_widget_grab_focus(frdp->what);
+	if (do_replace && gtk_entry_get_text_length(GTK_ENTRY(frdp->what)))
+	    gtk_widget_grab_focus(frdp->with);
+
 	vim_free(entry_text);
 	return;
     }
```
