### ISSUE TITLE
Opening files from quickfix window in new split creates new buffers [No Name]

### ISSUE THREAD

**Issue by bfrg** [vim/vim#2574]
Every time a file from the quickfix window is opened in a new split (using `<C-W><Enter>`), a new buffer called `[No Name]` is added to the buffer list. This only happens when `hidden` is set.
### How to reproduce
Open vim:
```bash
vim -u NONE some_file
```
In vim:
```vim
:set hidden
:grep! foo * -r
:copen
```
In the quickfix window select a file and press `<C-W><Enter>`, then open buffer list with `:ls`. Every time a new file is opened this way, a new `[No Name]` buffer is added to the buffer list. This does not seem to happen with `nohidden`.

### Vim version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  7 2018 12:51:54)
Included patches: 1-1428
Modified by Gentoo-8.0.1428
Compiled by benjamin@laptop
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               -ruby              +X11
+dialog_con        +menu              +scrollbind        +xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            -mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=native -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-E  -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-O1 -Wl,--as-needed  -L/usr/lib64/perl5/5.26.1/x86_64-linux/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc  -L/usr/lib64/python3.5/config-3.5m -lpython3.5m -lpthread -ldl -lutil -lm      
```

**Comment by tonymec** [comment]
I notice the line `Modified by Gentoo-8.0.1428` which seems to indicate that this build was made from sources modified by Gentoo.

Have you tried compiling from Bram's original sources? See (possibly among others):
```
    http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
    http://users.skynet.be/antoine.mechelynck/vim/compunix.htm
```
If the same problem also happens with Bram's "official" sources, or if some developer can reproduce it on a Vim built from them, then we may have something (which of course doesn't mean that snapping fingers will be enough to get a cure for it).

If the problem does **not** happen with Bram's official sources, then it should be reported wherever it is that Gentoo bugs are reported, with the mention that a Vim build compiled from Bram Moolenaar's original sources for patchlevel 8.0.1428 (or something) does not exhibit the problem.

Best regards,
Tony.

**Comment by bfrg** [comment]
I just tried it with the git version and the problem still happens.

**Comment by andymass** [comment]
It's not necessary to involve the quickfix.  It can be reproduced by using `:new`, then switching to an already existing buffer (e.g. using `:e file`).  Instead of the `[No Name]` buffer becoming the new buffer, it is simply hidden.  The only difference with `:set hidden` is that the buffers are listed.  You can reproduce with `:set nohidden` and `:ls!`.

**Comment by chrisbra** [comment]
@andymass I am not sure this is true:
`vim --clean -c ':new' -c ':e ~/.vim/vimrc' -c ':ls!'`

This will create a 2 windows, 1 window editing a `[No Name]` buffer and the other one your `.vimrc` file e.g. output of `:ls!` command is:
```
"~/.vim/vimrc" 493L, 15605C
  1  a   "[No Name]"                    line 1
  2 %a   "~/.vim/vimrc"                 line 1
```

This is expected, since after the new one would initially have a new buffer with number 2 and then the buffer (and its number) is re-used when using `: e`

**Comment by andymass** [comment]
@chrisbra sorry, I wasn't clear.  Exact steps:

    vim --clean -c ':new' -c ':e ~/.vim/vimrc' -c ':wincmd w' -c ':e ~/.vim/vimrc' -c ':ls!'

produces

    "~/.vim/vimrc" 4029 lines --0%--
      1u#    "[No Name]"                    line 1
      2 %a   "~/.vim/vimrc"                 line 1
    Press ENTER or type command to continue

The reason it's related to this issue is when typing `<c-w><cr><c-w>p<c-w><cr>` in the quickfix, vim effectively does

    :new
    :1cc
    wincmd p
    :new
    :1cc

So, although the first buffer created by `new` is converted to a real named buffer by `1cc`, the second one is not because the buffer belonging to the first error already exists and wind up with an extra `[No Name]` buffer lying around.

**Comment by tonymec** [comment]
I think this is related to the difference between "deleting" a buffer (which still remembers some metadata about it) and "wiping" it (which doesn't). Let's go through your "exact steps":
1. :new 
… opens a second, empty, window.
2. :e ~/.vim/vimrc
… edits your vimrc in this second window. There is still a first window with an empty buffer.
3. :wincmd w
… goes to the window with the empty buffer
4. :e ~/.vim/vimrc
… edits your vimrc in this first window too. The empty buffer is deleted but not wiped out; in particular, it is still the "alternate buffer" as shown by the # against its name in the output of ":ls!". Without an exclamation mark, this buffer would not be shown, because it is "unlisted" (shown by "u" in the output of :ls!).

I think this is expected behaviour.

See
    :help :bunload
    :help :bdelete
    :help :bwipeout
    :help :ls

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. Here is my handcoded `~/Session.vim` (it assumes that `'splitbelow'` is set in my vimrc):
```vim
" Vim session file
" This one was not generated by :mksession.

" e ~/.mozilla/seamonkey/eiox68r9.default/user.js
e ~/.mozilla/seamonkey/r0hh40it.frg-2018+/user.js
lcd %:h
new chrome/userChrome.css
lcd %:h
new userContent.css
new $VIM/vimfiles/keymap/russian-phonetic_utf-8.vim
cd ~
new pub/slovarj/ru-fr.css
setl keymap=russian-phonetic imi=0
lcd %:h
" new yourstyle.css
" setl imi=0
" new preferred.css
" setl imi=0
" new freeserif.css
" setl imi=0
" new windows.css
" setl imi=0
new ru-fr.abbrev.html
setl imi=0
new ru-fr.17.html
split
new ~/Session.vim
lcd ~
bot h
if exists('+switchbuf')
 set swb=useopen
 sb ~/pub/slovarj/ru-fr.abbrev.html
 wincmd w
else
 wincmd W
 wincmd W
 wincmd W
endif
new ru-fr.05.html
wincmd W
normal Nzt
```
At the moment, shortly after starting `gvim -S`, `:ls!` shows 43 buffers, the first of which is an unlisted unloaded `[No Name]` buffer and the last of which is an unlisted `help.txt` which is active (loaded in a window). A few minutes ago, before recompiling and restarting Vim, I had maybe twice as many, and buffer 1 was also `[No Name]`. Of these 43 buffers, 10 are "active" (loaded in a window), the rest are (IIUC) buffers which were never loaded in this session but for which marks are remembered in the `viminfo`. (These 10 windows don't take up too much screen space because `'winheight'` is set to 0 in my vimrc as part of my "Rolodex Vim" setup.)

I think buffer 1 is always `No Name` unless (a) you start Vim with a filename on the command-line, or (b) you start editing that empty buffer and save it with a filename. Or you might wipe it out, in which case there will be no buffer 1 (IIUC buffer numbers are not reused within the same session, or at least not if there exists any buffer, listed or not, with a higher number). This may look weird to people unaccustomed to Vim but I think it is how Vim works.

Best regards,
Tony.

**Comment by lifecrisis** [comment]
Greetings, 

I was able to triage this issue.  I thought I would post what I've discovered here.   It's relatively straightforward and only involves a little bit of tracing the code behind the `<C-W><CR>` mapping in the quickfix window.

The C function that drives the `:split` command and others like it is the `ex_splitview()` function. You can jump to it [here](https://github.com/vim/vim/blob/master/src/ex_docmd.c#L8324).

The crucial part is near the beginning.  Note the following lines:

```c
#ifdef FEAT_QUICKFIX
    /* A ":split" in the quickfix window works like ":new".  Don't want two
     * quickfix windows.  But it's OK when doing ":tab split". */
    if (bt_quickfix(curbuf) && cmdmod.tab == 0)
    {
	if (eap->cmdidx == CMD_split)
	    eap->cmdidx = CMD_new;
	if (eap->cmdidx == CMD_vsplit)
	    eap->cmdidx = CMD_vnew;
    }
#endif
```

As you can see, invoking `:split` in the quickfix window functions as though you invoked `:new` (the command is literally switched after you invoke it).  This is crucial for explaining why the `<C-W><CR>` mapping behaves the way that it does.

Tracing the code further, we go to `window.c`, where we find that `<C-W><CR>` is driven by the function call [here](https://github.com/vim/vim/blob/master/src/window.c#L526).  That function is in [quickfix.c](https://github.com/vim/vim/blob/master/src/quickfix.c#L3809).

The crucial line in the `qf_view_result()` function is the following:

```c
        vim_snprintf((char *)cmd, sizeof(cmd), "split +%ld%s",
                (long)curwin->w_cursor.lnum,
                IS_LL_WINDOW(curwin) ? "ll" : "cc");
```

See!  The code that drives the `<C-W><CR>` mapping calls the `:split` command.  This, in turn, is converted into an invocation of `:new` (see above).  This means that an entirely new buffer is created before `:cc` or `:ll` gets called in the new window.

A last note:  When `'hidden'` is not set, the buffer created by the `:new` invocation is unloaded when the buffer containing the result is displayed (so people using the defaults won't notice this).

I actually noticed this when I was working on an earlier patch.  I didn't fix it at the time because I thought I would get to it later.  I haven't gotten to it.  I also am not sure how the main guys (Bram ... @brammool , Yegappan) who work on the quickfix list code would want to handle this one.

Best,
Jason

**Comment by vim-ml** [comment]
Hi,

On Tue, Oct 30, 2018 at 11:49 AM Jason Franklin
<vim-dev-github@256bit.org> wrote:
>
> Greetings,
>
> I was able to triage this issue. I thought I would post what I've discovered
> here. It's relatively straightforward and only involves a little bit of
> tracing the code behind the <C-W><CR> mapping in the quickfix window.
>
> The C function that drives the :split command and others like it is the
> ex_splitview() function. You can jump to it here.
>
> The crucial part is near the beginning. Note the following lines:
>
> #ifdef FEAT_QUICKFIX
>     /* A ":split" in the quickfix window works like ":new".  Don't want two
>      * quickfix windows.  But it's OK when doing ":tab split". */
>     if (bt_quickfix(curbuf) && cmdmod.tab == 0)
>     {
> if (eap->cmdidx == CMD_split)
>    eap->cmdidx = CMD_new;
> if (eap->cmdidx == CMD_vsplit)
>    eap->cmdidx = CMD_vnew;
>     }
> #endif
>
> As you can see, invoking :split in the quickfix window functions as though
> you invoked :new (the command is literally switched after you invoke it).
> This is crucial for explaining why the <C-W><CR> mapping behaves the way that
> it does.
>
> Tracing the code further, we go to window.c, where we find that <C-W><CR> is
> driven by the function call here. That function is in quickfix.c.
>
> The crucial line in the qf_view_result() function is the following:
>
>         vim_snprintf((char *)cmd, sizeof(cmd), "split +%ld%s",
>                 (long)curwin->w_cursor.lnum,
>                 IS_LL_WINDOW(curwin) ? "ll" : "cc");
>
> See! The code that drives the <C-W><CR> mapping calls the :split command.
> This, in turn, is converted into an invocation of :new (see above). This
> means that an entirely new buffer is created before :cc or :ll gets called in
> the new window.
>
> A last note: When 'hidden' is not set, the buffer created by the :new
> invocation is unloaded when the buffer containing the result is displayed (so
> people using the defaults won't notice this).
>
> I actually noticed this when I was working on an earlier patch. I didn't fix
> it at the time because I thought I would get to it later. I haven't gotten to
> it. I also am not sure how the main guys (Bram ... @brammool , Yegappan) who
> work on the quickfix list code would want to handle this one.
>

Thanks for looking into this and for a very good description of the issue.
Can you try the attached patch?

Thanks,
Yegappan

**Comment by lifecrisis** [comment]
I noticed that my response to Yegappan on the mailing list did not appear here on Github as I expected.  I will re-post my response below:

> Yegappan,
> 
> Thanks for the patch.  I didn't try the code, but I looked at the diff.
> 
> It strikes me as odd that a new, empty buffer will need to be created at
> all.  Why waste a buffer number?  It seems like there should be a more
> clean solution in which the target buffer is opened in a split view
> directly without discarding an empty buffer in between.
> 
> It seems to me like this is hiding the underlying problem, rather than
> fixing it.
> 
> Maybe I'm being a little to picky?  Let me know what you think...
> 
> Thanks,
> Jason Franklin

Sorry for the redundancy...

Best,
Jason Franklin
