### ISSUE TITLE
Vertical split rendering issue with Unicode variation selector

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2599]
To reproduce:

1. `vim --clean -c 'vs'`
2. Insert one or more ▪︎ (U+25AA, BLACK SMALL SQUARE).

**Update:** you need to insert a Unicode variation selector (U+FE0E), too. To reproduce, insert `<c-v>u25aa<c-v>ufe0e`.

**Update 2:** font and terminal emulator/multiplexer matter, too (read comments below).

See screenshot. I can reproduce with Vim 8.0.1438 on macOS.

<img width="373" alt="issue" src="https://user-images.githubusercontent.com/1193314/35585162-7a54f6d0-05f7-11e8-8b67-84c9268a0cd0.png">

**Comment by lifepillar** [comment]
Maybe related to https://github.com/vim/vim/issues/721 and https://github.com/vim/vim/pull/2074? Colorcolumn is broken in the same way as the vertical split.

**Comment by nuko8** [comment]
I couldn't reproduce the issue on my macOS.

Also, the picture shown above appears to be inconsistent with the steps given for reproducing the issue.

The inconsistencies in appearance are:

1. Whereas there're black small squares on the left-hand side, there's nothing appearing on the right-hand side.   If the split is done by `:vs` at startup, then both sides will keep sharing the same buffer, and thus the right-hand side shouldn't be empty once the left-hand side gets non-empty.

2. Whereas the status line of the left-hand side indicates that the buffer was modified, that of the right-hand side does not.  If the split is done by `:vs` at startup, then both sides will have `[+]` on their respective status line simultaneously once either of the sides gets modified.

3. The first character of the status line of the left-hand side is `<`, which indicates that the two window columns were changed by making the left-hand side smaller at some point of time, that is, the vertical split line was moved to the left to an extent that the contents of the status line is truncated.  Nonetheless, the steps don't mention that.

4. By closely looking at the vertical split, we see that there's a chain line in black there, which indicates that VertSplit is correctly rendered (at least, the foreground color of that).  Then, what are those white vertical segments?  I'm wondering if the background of VertSplit is rendered differently in position from the foreground of that.  They could be wrongly rendered colorlumn, but that's not clear from the given steps since `'colorcolumn'` isn't mentioned there.

**Comment by k-takata** [comment]
This kind of problem is caused by ambiguous width characters, and often hard to fix because many factors are involved. E.g.

* `'ambiwidth'` option,
* Terminal emulator (and its settings),
* Terminal multiplexer (tmux, GNU screen, ...),
* Font, etc.

If some of them are mismatched, rendering issue may occur.

**Comment by lifepillar** [comment]
@nuko8 Your remarks are correct, but the issue can be reproduced with the steps I have mentioned. Here is a better screenshot, in which colorcolumn is also shown (so, there's a step 3: `set cc=30`):

<img width="570" alt="rendering-issue-terminal-app" src="https://user-images.githubusercontent.com/1193314/35610884-576ed4bc-0663-11e8-9d36-6c35779bf050.png">

@k-takata Thanks for your comment. In fact, I can reproduce the problem with Terminal.app, both outside tmux (screenshot above) and within tmux. Within tmux the defect looks a bit different:

<img width="570" alt="rendering-issue-terminal-app-tmux" src="https://user-images.githubusercontent.com/1193314/35610928-8023087e-0663-11e8-897f-136b9c96f8fb.png">

Using iTerm2, things are rendered correctly outside tmux, but within tmux characters overlap the vertical split (colorcolumn is ok, though), as the following screenshot shows:

<img width="600" alt="rendering-issue-iterm2-tmux" src="https://user-images.githubusercontent.com/1193314/35610971-b6a751b6-0663-11e8-9d78-5ddac721e7ef.png">

I get the same results in all cases regardless of the value of `ambiwidth`. The font I use is SF Mono.

Any idea what the mismatching settings might be?

**Comment by nuko8** [comment]
With Vim 8.0.1451 on Terminal.app with the Basic theme (According to Terminal->Preferences...->Profiles->Basic, some of the factory default settings, which I used when I took a screen shot, are: Font: SF Mono regular 11pt, Text Encoding: Unicode (UTF-8), and Unicode East Asian Ambiguous characters aren't set to wide.) on High Sierra (10.13.3), I got

![screen shot 2018-02-01 at 14 27 04](https://user-images.githubusercontent.com/13826919/35662548-0ea6dfd2-075c-11e8-9898-087e203c62fe.png)

In addition, nether `:set ambiwidth=double` nor setting Unicode East Asian Ambiguous characters to wide changed the result.  So, it seems to me that there's no issue with Vim, macOS or Terminal.app.

**Comment by lifepillar** [comment]
I can reproduce it even with Vim 8.0.1451 using exactly the same settings, profile, OS, etc… as @nuko8's. I can only fix it by using a different font: among those that I have tried, Andale Mono, Consolas, Courier New, DejaVu Sans Mono, Fira Code, Hack, Input Mono, Menlo, PT Mono seem unaffected. But Inconsolata, Iosevka, Latin Modern Mono, Luxi Mono, Monaco, Roboto, Source Code Pro, and of course SF Mono, produce the issue. I don't know why @nuko's SF Mono is ok: my version is SF Mono Regular; 13.1d0e1; 2017-05-04.

@nuko8 Can you try with different fonts? If we can rule out font issues, I will search for the culprit somewhere else.

**Comment by nuko8** [comment]
> Can you try with different fonts?

Are you sure?  Honestly, I don't feel like doing that because that's too much for me.  First of all, for every font file belonging to the font families you named, I have to check whether or not a given font file has a glyph corresponding to U+25AA.  In case it doesn't, I have to identify the fallback used as a substitute for the missing glyph.  Usually, what font is used for fallback is quite obscure and thus hard to identify.  If the font file has such a glyph, then I have to examine the actual metrics of it rather than the nominal ones.  I will have to do the same thing for fallbacks as well.

> If we can rule out font issues, I will search for the culprit somewhere else.

Trying to keep the issue open by imposing the condition that is awfully time-consuming for people to fulfill, spending their spare time, is by no means productive.  Rather, you should give us a definite way for "Others can reproduce it" instead of claiming that "I can reproduce it" with the accumulation of the circumstantial evidences which weren't disclosed when this issue was open  (Somehow, you've already known that the issue is related to the font in use.  I'm wondering, then, what made you open an issue here instead of font creators.)  Or, it might be even better for you to reinstall the OS and start all over to see if that fixes the issue.

**Comment by lifepillar** [comment]
>for every font file belonging to the font families you named, I have to check whether or not a given font file has a glyph corresponding to U+25AA

Based on the fonts I have checked, it appears that the issue occurs only when the font does not have the glyph. But I have noticed that if I insert the character with `<c-v>u25aa` instead of copy-pasting or using macOS's Emoji & Symbols panel, no rendering issue occurs.

>you should give us a definite way for "Others can reproduce it" instead of claiming that "I can reproduce it"

I think I did (I didn't initially mention which terminal I was using, but it didn't occur to me that the issue might depend on the terminal among the rest—not until @k-takata's comment). The fact that you cannot reproduce the issue using the same configuration as mine is not something I could have foreseen.

>Somehow, you've already known that the issue is related to the font in use

No, I've learned it from @k-takata's comment.

**Comment by lifepillar** [comment]
So, it turns out that the offending character is not just U+25AA, but U+25AA plus a Unicode variation selector. So, this should be reproducible in Terminal.app (at least with SF Mono):

```
:vsplit
i<c-v>u25aa<c-v>ufe0e
```

**Comment by nuko8** [comment]
> But I have noticed that if I insert the character with <c-v>u25aa instead of copy-pasting or using macOS's Emoji & Symbols panel, no rendering issue occurs.

Use `<CTRL-V>u25aa` in Insert mode instead of the Emoji & Symbols popup; the former should automatically give you a glyph appropriate to use with the terminal in use, getting one from either the font used by the terminal or the fallback, i.e., a fixed-width font chosen by the terminal (or a lower layer for rendering); the latter is designed to use with macOS's native apps which understand U+FE0E correctly to display U+25AA in text style, distinguishing it from emoji style.

For such apps, when you locate the cursor at which you want to insert a character using the popup and press `^⌘Space` then, you'll have a popup looking like

![screen shot 2018-02-02 at 14 17 22](https://user-images.githubusercontent.com/13826919/35717628-e0398ffa-0823-11e8-9017-bda2c972fa2a.png)

Then, by giving a single click to the character of your own choice, you'll get it at the insertion point.

On the other hand, when you try doing the same thing with Terminal.app, you'll see a striking contrast:

![screen shot 2018-02-02 at 14 29 07](https://user-images.githubusercontent.com/13826919/35718010-b723c0a2-0825-11e8-8424-c4d746417681.png)

The popup doesn't pop up in place nor get focus (You can see it from the difference in the highlight colors between the pictures), and a single click on a character won't insert anything into the terminal.  Simply, Terminal.app tells you that it doesn't want to accept anything from the Emoji & Symbols popup (More specifically, it tells you that it is unable to correctly handle something followed by U+FE0E).

> So, it turns out that the offending character is not just U+25AA, but U+25AA plus a Unicode variation selector. So, this should be reproducible in Terminal.app (at least with SF Mono):
>
>` :vsplit`
>`i<c-v>u25aa<c-v>ufe0e`

Accordingly, I would say this is an issue of the terminal rather than an issue of Vim.  That said, it is still doubtful whether or not that is a valid issue of the terminal.  Do people really want it to render variants of a single character using variation selectors like text viewers, word processors, or browsers?  I doubt it.

**Comment by nuko8** [comment]
FYI, MacVim in GUI mode works nicely with the Emoji & Symbols popup

![screen shot 2018-02-02 at 17 53 55](https://user-images.githubusercontent.com/13826919/35724765-491831e8-0842-11e8-82c2-114b94b974c6.png)



and free from the issue:

![screen shot 2018-02-02 at 17 44 53](https://user-images.githubusercontent.com/13826919/35724385-dd3cf3ba-0840-11e8-99a8-fb21a857bb7d.png)

This is because MacVim in GUI mode renders everything by itself, thereby free from restrictions imposed by terminals with respect to the Emoji & Symbols popup.

**Comment by lifepillar** [comment]
>On the other hand, when you try doing the same thing with Terminal.app, you'll see a striking contrast

`^⌘Space` does open a pop-up in my Terminal.app (tested in Sierra and High Sierra):

<img width="729" alt="emoji-popup" src="https://user-images.githubusercontent.com/1193314/35733239-e5557ec4-081c-11e8-9d97-3b1e630285b4.png">

Even so, Terminal.app does not handle U+FE0E well. For example, if you insert U+25AA + U+FE0E at the Bash prompt (via the Emoji & Symbols pane/pop-up), and then you repeatedly press Del, you will overwrite the prompt. This happens also in iTerm2, yet Vim inside iTerm2 (but not within tmux) has no issues.

**Comment by nuko8** [comment]
> Even so, Terminal.app does not handle U+FE0E well. 

Then the issue is that of the terminal, right?  As shown with the example of MacVim, the core part of Vim is not responsible for the issue.  Also, as you said, if Vim inside iTerm2 works well with the popup, that would leads to the same conclusion.   Nothing is left to discuss.

**Comment by chrisbra** [comment]
closing then.
