### ISSUE TITLE
Timer fails to properly update the screen

### ISSUE THREAD

**Issue by markonm** [vim/vim#2612]
Vim version: 8.0.1449

```vim
" reproduce.vim
function! Timer() abort
  call timer_start(0, { _-> matchadd('Search', '.') })
  return ''
endfunction
nnoremap <expr> <c-j> Timer()
```
```
1. vim  --clean reproduce.vim
2. :so %
3. <c-j>
4. screen is not updated until the cursor is moved
```

This fails on linux TUI vim. On gVim it works properly. It also works properly on Windows in gVim and vim.

I think changes in `redraw_after_callback` from this [commit](https://github.com/vim/vim/commit/a338adcf222b6a24e26ea5ae6a2ad27f914acb38?diff=split#diff-ceb2e2231c5d45523135ca0cfc492792L470) are the cause.

**Comment by lacygoill** [comment]
I have the same issue.

I was adding/removing a match for a short period of time, with timers, every time I move the cursor to the next occurrence of a search pattern with `n`, to get a [blinking effect](https://github.com/lacygoill/vim-search/blob/master/autoload/search.vim#L31-L39). It worked until the patch `v8.0.1449`. Now, there's no blinking anymore, the match stays active for a few seconds, before disappearing.

As said by @xtal8 , the issue seems specific to Vim in the terminal (not gVim).

---

Current environment:

 - `vim --version`:      VIM - Vi IMproved 8.0  Included patches: 1-1464
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.3
 - `$TERM`:              screen-256color
 - Shell:                zsh 5.3.1

**Comment by markonm** [comment]
Fixed by https://github.com/vim/vim/commit/acda04f5c641330cd589ca52eb61d1ab0d62385f. Thanks!
