### ISSUE TITLE
there is a minor bug with the gvim about the startup 

### ISSUE THREAD

**Issue by zalois** [vim/vim#2615]
there is too large for some screens.
how to fix it?
and may come to encounter problems of cannot correctly display the color of space character
when using list characters.
![snapshot26](https://user-images.githubusercontent.com/9462454/35774202-b31c1ba6-09a3-11e8-804a-030f07deee29.png)

**Comment by nuko8** [comment]
Is this a bug report?  If so, please tell us how to replicate the result shown by the picture.

Although I don't think I surely understood what you wrote, I somehow got an impression that you wrote two different topics in a single issue; one is about gvim's whole window size, and another is about highlight colors for `'listchars'`.  

In general, avoid opening an issue consisting of two or more different topics unless they are closely related to each other.  Choose and clarify which topic you want to discuss here, the size one or the color one.

If that is not the case, please consider adding more explanation as to how those two different topics are related to each other.

As to the color topic itself, you need to add more detailed description to it; otherwise, people will never know anything about it other than your having a problem with `'listchars'` colors.

**Comment by tonymec** [comment]
gvim normally resizes itself to to bigger than the screen. What happens if, after seeing what is shown above, you (blind-)type ``:set lines=999 columns=9999`` followed by the `[Enter]` key?

Best regards,
Tony.

**Comment by zalois** [comment]
sorry, i opening an issue consisting of two different topics.
the size of gvim start screen is still as  before  after i used the method of tonymec. 
the 'listchars' i used in vimrc is as following:
set listchars=tab:<-,eol:↓
set list
highlight spaceofEOL ctermbg=red  guibg=red
match spaceofEOL /\s\+$/
2match spaceofEOL /　\+$/
ps: it works under the version 7.4, and does not work after version 8.

**Comment by nuko8** [comment]
You're still keeping us guessing.  So, don't expect you get something you'd be content with.

As for the first topic:

In principle, any decent X client is subject to the layout policy of the window manager in use; any decent window manager won't allow X clients to get larger than the whole screen.

A notable exception is:  Depending on layout policy, there're cases where the user can overturn the principle by explicitly specifying size via resource files such as `.Xdefault` and `.Xresources` or command-line options such as `-geometry` or `-geom`.

Accordingly, It's the user who can spoil gvim and let it behave wild.  Check if you did that or not; correct resource files and/or command-line options, change the window manager to a decent one, or do whatever necessary.

As for the second topic:

I can't believe the script had worked for 7.4.  I guess what you really wanted to do was
```viml
set listchars=tab:<-,eol:↓
set list
highlight spaceofEOL ctermbg=red guibg=red
match spaceofEOL /\v(\s|　)+$/
```
Last but not least: The issue raised by you here is rather a set of user questions than a bug report.  Note that this issue tracker is for bug reports or things related to Vim development.  Please refrain from posting user questions here, or your issue gets closed immediately or neglected for a while.

**Comment by zalois** [comment]
ok, i try to overcome it. thank you all !
