### ISSUE TITLE
vim hangs upon reading the same file opened for editing

### ISSUE THREAD

**Issue by punyaslo** [vim/vim#2633]
1- open a file with content - [ vim log ]
2- try reading the the same file from ex mode command line - [ : r !vim log ]
3- Though It is not a real reading, it is a negative test scenario.
Terminal turns unresponsive.

**Comment by chrisbra** [comment]
What exactly do you expect from `:r !vim file`? That sounds silly.

**Comment by andreaswachowski** [comment]
To read a file from the ex command line, use `:r log`. If `: r !vim log` is valid at all, and if I understand it correctly, it would attempt to read the output of filtering no lines passing through `vim log`. But because `vim log` does not by itself exit (and runs in the background), the terminal hangs. You can use `CTRL-Z` to stop the foreground vim and run `ps aux`, where you will find the background vim looking something like `/bin/bash -c (vim log) >/var/...path/to/tmpfile 2>&1`.
Kill that process, type `fg` and you will be back to the original vim.

**Comment by chrisbra** [comment]
i am closing this as invalid.
