### ISSUE TITLE
UTF emojis break lines wrapping

### ISSUE THREAD

**Issue by nicolas-ivanov** [vim/vim#2647]
Consider a UTF file with an emoji in a string, for example:

```
😃1234567890 1234567890 1234567890 1234567890
```

If the string is too long for one line vim will wrap it up to the next line. 
However if there is an emoji anywhere in this string, vim will duplicate a symbol at the wrapping point:

```
😃1234567890 1234567890 1234567890 12345677
890
```

**Comment by johndorn** [comment]
What environment are you using? I'm unable to duplicate this issue with version `8.0.1522` on Ubuntu in a tmux-ed terminal.

**Comment by ZyX-I** [comment]
This looks like a usual problem with either foreign glyphs rendering or difference in opinion about glyph width between Vim and terminal emulator. In your case tmux adds another layer of possible problems, though rather limited in scope: try doing vertical split in tmux, use `xclip -o -sel clip` in *left* pane with this text in clipboard and watch the pane separator. You may need to trigger some specific lines redrawing: I see separator disappear on the *previous* line, but only after I enter copy mode, `refresh-client` command also works.

Note: by foreign glyphs rendering I mean rendering of glyphs taken from font other then currently used one. Happens when current font has no needed glyph. Known to be a rather big problem in konsole (at least in my setup, though I heard that not only mine).

So to reproduce the issue for sure you need to know not just Vim version and terminal, but

- Vim version.
- Terminal emulator and its version.
- Versions of whatever software is between Vim and terminal, if any (I mean tmux).
- Font library with version.
- Font with version.
- Versions of whatever libraries terminal emulator and intermediate software are using to determine glyph width. There are lost of candidates here: not sure, but glibc (but AFAIR not just any libc); icu (rarely used based on what I know); or one of the softwares from the above list: at least Vim has its own functions that deal with unicode, Python also goes this route (though it would not normally appear in the stack of applications that have effect on this issue).

Except for konsole where this issue may appear just because glyph is taken not from the current font I think you will see the issue if your Vim version thinks that glyph representing codepoint is two screen cells wide, while terminal thinks that glyph is one screen cell wide.

Though in any case I agree that @nicolas-ivanov has not provided any useful information, just point that providing just Vim version and the fact that you are using tmux would be just as useless if you were issue reporter.

I would also suggest to check `:echo strdisplaywidth("\U1F603")` and check where terminal will wrap if printing character and lengthy string: e.g. with

    perl -e "use utf8; use Encode; print(Encode::encode_utf8(chr(0x1F608))); print('0123456789' x ($COLUMNS/10 + 1)); print(chr(0x0A) . $COLUMNS . chr(0x0A))"

**Comment by nicolas-ivanov** [comment]
@johndorn  @ZyX-I 

* Vim version: 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
* Terminal: GNOME Terminal 3.18.3, using VTE version 0.42.5 +GNUTLS
* No tmux involved
* No idea where to find the font library and font name. I'm using the default terminal shipped in Ubuntu 16.04
* The bug is reproduced both in bash and zsh
* less viewer doesn't have the aforementioned issue

**Comment by arp242** [comment]
I cannot reproduce this issue. Also note that Vim 7.4 is also quite old.

**Comment by nicolas-ivanov** [comment]
Ok, then let's close the issues for now. Thanks for looking into it!

**Comment by Huxpro** [comment]
I have similar issues where lines with emoji symbols would mistakenly duplicate symbols in the editing position.
