### ISSUE TITLE
vim and tag not found…

### ISSUE THREAD

**Issue by aotto1968** [vim/vim#2658]
Hi, VIm support _tags_ → good, but something is missing

1. my _tags_ file
```
> grep self_test tags 
self_test       backend/backendConnector.cpp    /^bool BackendConnector::self_test()$/;"        f       class:xmrstak::BackendConnector signature:()
self_test       backend/nvidia/minethd.cpp      /^bool minethd::self_test()$/;" f       class:xmrstak::nvidia::minethd  signature:()
xmrstak::BackendConnector::self_test    backend/backendConnector.cpp    /^bool BackendConnector::self_test()$/;"        f       class:xmrstak::BackendConnector signature:()
xmrstak::nvidia::minethd::self_test     backend/nvidia/minethd.cpp      /^bool minethd::self_test()$/;" f       class:xmrstak::nvidia::minethd  signature:()
```

2. my code
```
bool BackendConnector::self_test()
{
    bool    ret;
    ret =   cpu::minethd::self_test();
#   ifndef CONF_NO_CUDA
    ret &=  nvidia::minethd::self_test();
#   endif
    return ret;
}
```

as you see, `self_test` has multiple definitions… and as you see the definition `nvidia::minethd::self_test` is valid but **vim** seems NOt be able to match the substring `nvidia::minethd::self_test` with the entry `xmrstak::nvidia::minethd::self_test` from the _ctags_ file

I find **ALL** _ctags_ entries if I search for `self_test` or **NO** _ctags_ entries if I search for `nvidia::minethd::self_test`

my simple question is… why ?

**Comment by EgZvor** [comment]
If I understand correctly this can be solved by using a pattern `:tag /nvidia::minethd::self_test`

**Comment by korney4eg** [comment]
@EgZvor I have the same problem.
It works perfectly when I use pattern search, but it doesn't when I use `^]` keybinding under the cursor.

**Comment by EgZvor** [comment]
@korney4eg `^]` is using the word under cursor. If your settings of `iskeyword` is default you only search `self_test`, so I'm not sure what exact problem you're having.

The reason for different results when matching `self_test` vs `nvidia::minethd::self_test` is in the former case Vim is using `name` field and in the latter `pattern` field. In both cases it is matched strictly, that's why you don't get anything in the latter case, you'd need to use `xmrstak::nvidia::minethd::self_test` instead. And if you want your search to be not strict you have to use `/` in any of the `:tag` commands.

**Comment by korney4eg** [comment]
Thanks for the answer @EgZvor  now I found where I can get an issue.

I needed to fix my ctags configuration.
