### ISSUE TITLE
printf cannot be used without % expressions

### ISSUE THREAD

**Issue by blueyed** [vim/vim#2687]
`printf` should require no arguments when it contains no conversion specification.

Current behavior:

```vim
:echo printf('foo')
E119: Not enough arguments for function: printf
E15: Invalid expression: printf('foo')         

:echo printf('foo', '')
E767: Too many arguments to printf()
```

**Comment by chrisbra** [comment]
Well, if you don't need a conversion specifier, do not use printf :)

**Comment by ZyX-I** [comment]
@chrisbra Such issues normally arise when developing something generic. E.g. creating custom logger is easier if you can write `let actual_msg = call('printf', a:000)` which is actually common for logging modules: for example, Python’s `logging.error` may be used like `logging.error('Failed with error code %u', code)` and AFAIR it is a port of a logger from some other language.

**Comment by k-takata** [comment]
C's `sprintf` accepts it, so I think there's nothing strange if Vim script's `printf` accepts it.

```diff
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -740,7 +740,7 @@ static struct fst
     {"pow",		2, 2, f_pow},
 #endif
     {"prevnonblank",	1, 1, f_prevnonblank},
-    {"printf",		2, 19, f_printf},
+    {"printf",		1, 19, f_printf},
     {"pumvisible",	0, 0, f_pumvisible},
 #ifdef FEAT_PYTHON3
     {"py3eval",		1, 1, f_py3eval},
diff --git a/src/testdir/test_expr.vim b/src/testdir/test_expr.vim
--- a/src/testdir/test_expr.vim
+++ b/src/testdir/test_expr.vim
@@ -131,6 +131,7 @@ func Test_option_value()
 endfunc
 
 function Test_printf_misc()
+  call assert_equal('123', printf('123'))
   call assert_equal('123', printf('%d', 123))
   call assert_equal('123', printf('%i', 123))
   call assert_equal('123', printf('%D', 123))
```

**Comment by nuko8** [comment]
> printf should require no arguments when it contains no conversion specification.

It looks to me that this requirement proposed by @blueyed is more than reducing the number of the mandatory parameters from two to one.  That may be paraphrased into something like this: If any %-less format should be permitted, `f_printf` should check whether the `fmt` parameter includes `%` specifiers or not, then decide what to do with the rest of things that follows `ftm` accordingly.

**Comment by tonymec** [comment]
It seems to me that the first parameter should be required and a string, and that there should be exactly as many additional parameters (of the right type) as there are % specifiers (other, of course, than %% which translates as a single % character and requires no value argument). Now doesn't the existing code already check the "exactly as many" requirement, causing the E767 error when there are too many? Then the only required change would be from "one or more" to "zero or more" additional arguments (i.e. at least 1 argument, rather than at least 2, including the format string) which IIUC is exactly what @k-takata 's change does.

Best regards,
Tony.

**Comment by nuko8** [comment]
Then there's nothing I have to say if the OP is satisfied with it :)
