### ISSUE TITLE
argedit is not consistent with plain edit

### ISSUE THREAD

**Issue by memeplex** [vim/vim#2713]
Scenario 1:

1. Run vim without arguments
2. Do `:edit /tmp/x`
3. Run `ls` and check that the only buffer is `/tmp/x`.

Scenario 2:

1. Run vim without arguments
2. Do `:argedit /tmp/x`
3. Run `ls` and check that now there is an extra `[No Name]` buffer.

I don't see any reason why these two variants should end up in different buffer lists.

**Comment by chrisbra** [comment]
That happens because when calling `:argedit` Vim will first call `do_arglist()` to add the buffer to the argumentlist, further down the call stack, it will call `alist_add_list()`-> `buflist_add()` and finally `buflist_new()`. However in `alist_add_list()` it does not give the flag `BLN_CURBUF` but only `BLN_LISTED`. So `buflist_new()` won't consider to replace the current buffer with the new one. 

This simple patch would fix it:
```patch
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index ae4ce337d..bbf1dca2a 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -3299,7 +3299,7 @@ alist_add_list(
        for (i = 0; i < count; ++i)
        {
            ARGLIST[after + i].ae_fname = files[i];
-           ARGLIST[after + i].ae_fnum = buflist_add(files[i], BLN_LISTED);
+           ARGLIST[after + i].ae_fnum = buflist_add(files[i], BLN_LISTED | BLN_CURBUF);
        }
        ALIST(curwin)->al_ga.ga_len += count;
        if (old_argcount > 0 && curwin->w_arg_idx >= after)
```

**Comment by brammool** [comment]
Christian wrote:

> That happens because when calling `:argedit` Vim will first call `do_arglist()` to add the buffer to the argumentlist, further down the call stack, it will call `alist_add_list()`-> `buflist_add()` and finally `buflist_new()`. However in `alist_add_list()` it does not give the flag `BLN_CURBUF` but only `BLN_LISTED`. So `buflist_new()` won't consider to replace the current buffer with the new one. 
> 
> This simple patch would fix it:
> ```patch
> diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
> index ae4ce337d..bbf1dca2a 100644
> --- a/src/ex_cmds2.c
> +++ b/src/ex_cmds2.c
> @@ -3299,7 +3299,7 @@ alist_add_list(
>         for (i = 0; i < count; ++i)
>         {
>             ARGLIST[after + i].ae_fname = files[i];
> -           ARGLIST[after + i].ae_fnum = buflist_add(files[i], BLN_LISTED);
> +           ARGLIST[after + i].ae_fnum = buflist_add(files[i], BLN_LISTED | BLN_CURBUF);
>         }
>         ALIST(curwin)->al_ga.ga_len += count;
>         if (old_argcount > 0 && curwin->w_arg_idx >= after)
> ```

A test would be nice...

-- 
hundred-and-one symptoms of being an internet addict:
82. AT&T names you Customer of the Month for the third consecutive time.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
will do. However the above patch is wrong. Hold back a while, will resubmit later

**Comment by vim-ml** [comment]
On Mi, 28 Mär 2018, Bram Moolenaar wrote:

> A test would be nice...

As mentioned before this simple patch is wrong. It turned out to be 
slightly more effort to make this work. And once this was changed a 
couple of other tests failed that would need to be adjusted or had to be 
accounted for in the source. So finally I think I have a patch that 
works correctly and is attached to this mail (only visible to the 
mailinglist, github won't receive it).

The reasoning for all the changes is in the commit message of the 
attached patch.

Best,
Christian
-- 
Dummheit ist ansteckend, Verstand wächst sich kaum zur Epidemie aus.
		-- Kazimierz Bartoszewicz
