### ISSUE TITLE
mouse scroll wheel doesn't scroll in terminal vim on windows

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim#2723]
when using `set mouse=a` the mouse clicks works but trying to scroll using the mouse scroll wheel has no effect.

**Comment by brammool** [comment]
Prabir Shrestha wrote:

> when using `set mouse=a` the mouse clicks works but trying to scroll
> using the mouse scroll wheel has no effect.

It works for me.  What is your setup?  What does this show (both in Vim
and when you run Vim in the terminal):

	echo v:termresponse

-- 
Now it is such a bizarrely improbable coincidence that anything as
mind-bogglingly useful as the Babel fish could have evolved purely by chance
that some thinkers have chosen to see it as a final and clinching proof of the
NON-existence of God.
The argument goes something like this: 'I refuse to prove that I exist,' says
God, 'for proof denies faith, and without faith I am nothing.'
'But,' says Man, 'the Babel fish is a dead giveaway, isn't it?  It could not
have evolved by chance.  It proves you exist, and so therefore, by your own
arguments, you don't.  QED.'
'Oh dear,' says God, 'I hadn't thought of that,' and promptly vanishes in a
puff of logic.
'Oh, that was easy,' says Man, and for an encore goes on to prove that black
is white and gets himself killed on the next pedestrian crossing.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by prabirshrestha** [comment]
`echo v:termresponse` shows nothing in vim.exe running in win10 cmd.exe. If I run vim.exe directly from StartMenu>Run, it still doesn't work and doesn't echo anything.

Event with `vim -u NONE` and running `set mouse=a` doesn't support scroll. Microsoft Windows [Version 10.0.16299.248]. I do have http://mridgers.github.io/clink/ installed.

**Comment by brammool** [comment]
> `echo v:termresponse` shows nothing in vim.exe running in win10
> cmd.exe. If I run vim.exe directly from StartMenu>Run, it still
> doesn't work and doesn't echo anything.
> 
> Event with `vim -u NONE` and running `set mouse=a` doesn't support
> scroll. Microsoft Windows [Version 10.0.16299.248]. I do have
> http://mridgers.github.io/clink/ installed.

I thought you were talking about the terminal window, since that's a new
feature.  But it appears you talk about running Vim in a console window.
The mouse scrolling has never worked there.  Not sure whether that would
be possible, if Vim is able to get scroll events.

-- 
Apparently, 1 in 5 people in the world are Chinese.  And there are 5
people in my family, so it must be one of them.  It's either my mum
or my dad.  Or my older brother Colin.  Or my younger brother
Ho-Cha-Chu.  But I think it's Colin.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by astra-midnight** [comment]
It might be worth bringing this up over on the new Windows Terminal repo. There's an issue tracking this for conpty and it's something they're hoping to get to soon. https://github.com/microsoft/terminal/issues/376

**Comment by car-da** [comment]
It looks like the Vim WIN32 implementation needs to be rewritten.
https://github.com/microsoft/terminal/issues/376#issuecomment-1127618074

**Comment by chrisbra** [comment]
so what exactly would be required?

**Comment by k-takata** [comment]
It looks that this has been fixed by [9.0.0775](https://github.com/vim/vim/commit/2a46f81ec7739967265759838afe7972e5f81e5e) and some related patches.
