### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by GammaPi** [vim/vim#2728]
Why not create a dev branch

**Comment by chrisbra** [comment]
This is the current development model and it has been discussed in the past. It is unlikely to be changed.

Closing.

**Comment by GammaPi** [comment]
Fine, I encountered 3 different compile error on different releases with tiny version differences on cygwin (It's ok on pure linux).

**Comment by chrisbra** [comment]
usually compile errors are fixed pretty fast. Please report them either here or at the vim-dev mailinglist. But be sure to test the latest patch level first. Thanks.

**Comment by brammool** [comment]
If we would create a dev branch, then problems like not being able to compile will only be reported very late, when we move a version to the release branch.  It's the large number of systems + combination of features that make using a dev branch problematic.

**Comment by tonymec** [comment]
@chrisbra said:

> usually compile errors are fixed pretty fast. Please report them either here or at the vim-dev mailinglist. But be sure to test the latest patch level first. Thanks.

@GammaPi : I confirm that even compile warnings, **once they have been reported,** are usually fixed as soon as Bram aka @brammool  comes back to his computer, or shortly afterwards, let's say no more than 24h after reporting (unless, of course, Bram is traveling and has poor or no Internet access). I know — I'm compiling both a Huge and a Tiny version of every new set of patches that I notice, and that has in the past let me spot quite a number of missing or misplaced `#ifdef` lines.

Of course, no error can be fixed before it is known, which is why it is important to report bugs, especially when testing new versions of the software — of any software, not only (but of course including) Vim.

Best regards,
Tony.
