### ISSUE TITLE
Unicode characters won't render correctly

### ISSUE THREAD

**Issue by parmort** [vim/vim#2738]
Unicode characters won't render properly in vim upon startup. When I source my `.vimrc` the characters render fine. I am using termite and vim version 8.0 with patches 1-1542 on arch linux. When I put the included snippet in its own file and run vim with that file as a config file, I get the same error and same 'fix'.

In my `.vimrc`

```vim
scriptencoding utf-8
set encoding=utf-8
setglobal fileencoding=utf-8

set fillchars=vert:\┃
```

Vim is compiled with `multi_byte` enabled.

**Comment by tonymec** [comment]
Works for me in gvim 8.0.1625 with GTK2-Gnome GUI: both the vertical bars in the divider (which are U+007C i.e. the same single-byte code in UTF-8 and in US-ASCII) and the page contents (even multibyte UTF-8 characters, on both sides of the vertical divider) look OK to me.

Are you sure you are not trying to read a Latin1 (or other non-Unicode) file as if it were UTF-8?

See http://vim.wikia.com/wiki/Working_with_Unicode about what to write **near the top of your vimrc** in order to be able to work in UTF-8. **CAUTION:** Changing `'encoding'` after one or more files have been read is **not** recommended, it could garble the whole contents of these files.

http://ftp.vim.org/pub/vim/patches/8.0/ gives a one-line description for every 8.0 patch so far. Glancing at those after 1542 I see nothing obvious, but who knows? Could you retry with the latest sources?

See at
    http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
    http://users.skynet.be/antoine.mechelynck/vim/compunix.htm
how I compile my own Vim on Linux.

Best regards,
Tony.

**Comment by parmort** [comment]
Thanks Tony. Unfortunately, the newly compiled version of vim (8.0.1626) has the same issue. If this helps any (I didn't mention it at the start), I get an upside-down question mark if I open a vertical split. This is all in terminal vim, however, when I tried it in gvim (8.0.1626), the same issue occurred.

[Here is my `.vimrc`](https://github.com/parvus-mortalis/dotfiles/blob/master/.vimrc). Again, if I source my `.vimrc` the unicode renders right away.

Again, thanks for the tips.

**Comment by k-takata** [comment]
This might not related to the issue, however, the line `scriptencoding utf-8` should be after setting `'encoding'`:

```vim
set encoding=utf-8
scriptencoding utf-8
```

This will matter when the default setting of the `'encoding'` is not `utf-8` (e.g. on Windows).
See: `:help :scriptencoding`

**Comment by mgedmin** [comment]
> Again, if I source my .vimrc the unicode renders right away.

This is weird.  Can you check with `:scriptnames` if your .vimrc was sourced on startup?

Can you check the values of `encoding` and `termencoding` with `:verbose set enc? tenc?` to see if some other script/plugin executed after your .vimrc overrode them?

Can you reproduce the problem if you tell vim to ignore your configuration with `vim --clean`?
Can you reproduce with a different terminal emulator?
Is your system locale correctly set to UTF-8 (check by running `locale charmap` in a shell)?

**Comment by tonymec** [comment]
Bingo! Your vertical bar is U+2503 BOX DRAWINGS HEAVY VERTICAL, which in not affected by `:help option-backslash`, not U+007C VERTICAL LINE, which is. Remove the backslash and try again.

I found this by copy-paste into gvim followed by ga on that vertical bar of yours.

Best regards,
Tony.

**Comment by parmort** [comment]
Thanks, @tonymec and @k-takata. I had to use both of those tips to solve the issue. I think it's safe to say that this is solved. Something to look into (I'm not sure myself on how to do it) would be to "fix" the vim-script syntax file. When I had the U+2503 alone, `vert:` did not color, making it seem like it was wrong. With the backslash, it was highlighted. Again, thank you!
