### ISSUE TITLE
Environment variable $TERM is not passed correctly to a job

### ISSUE THREAD

**Issue by bohrshaw** [vim/vim#2776]
`:help terminal-unix` says `$TERM` is passed to a running job.
But after `:let $TERM = 'xterm-256color' | term bash --norc`, `$TERM` in `bash` is still equal to `xterm`.

**Comment by brammool** [comment]
Bohr Shaw wrote:

> `:help terminal-unix` says `$TERM` is passed to a running job.
> But after `:let $TERM = 'xterm-256color' | term bash --norc`, `$TERM` in `bash` is still equal to `xterm`. 

The value of 'term' is passed in $TERM.  It's sort-of mentioned in the help,
I'll make it clearer.

-- 
From "know your smileys":
 :-*	A big kiss!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bohrshaw** [comment]
I got "`term` can't be changed in gvim".

**Comment by tonymec** [comment]
Indeed, 'term' in the Vim GUI is set to "builtin_gui" and cannot be changed. If you want to change which 'term' value is passed to the terminal, I think you can do it in your vimrc (which is sourced before starting the GUI) or even by setting $TERM in the shell before starting gvim.

Best regards,
Tony.

**Comment by bohrshaw** [comment]
In gvim on Linux, the 'term' value passed to the terminal is not affected by the value of $TERM whenever it's set.

**Comment by brammool** [comment]
> In gvim on Linux, the 'term' value passed to the terminal is not affected by the value of $TERM whenever it's set.

Ah, yes, in the GUI this doesn't make sense.

The reason I decided to pass 'term' in $TERM was mainly to make it easy
to run Vim inside a terminal window.  I suppose in the GUI we should
pass xterm-256color, since that's closest to what works in libvterm.

Is there a reason you would want to set $TERM to something else?

-- 
hundred-and-one symptoms of being an internet addict:
101. U can read htis w/o ny porblm and cant figur eout Y its evn listd.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bohrshaw** [comment]
> Is there a reason you would want to set $TERM to something else?

No,`xterm-256color` is enough.

**Comment by egberts** [comment]
I poked `xterm-direct`, for unlimited color.  Alas, not yet.
