### ISSUE TITLE
Vim treats Windows’ UTF-16 code unit input as Unicode code points, leaving surrogate pairs undecoded

### ISSUE THREAD

**Issue by chris-morgan** [vim/vim#2800]
This is true of input made through the emoji part of the built-in touch keyboard and through WinCompose, so I presume it to be a general issue and a bug in Vim rather than in something else.

Suppose I try to enter the character U+1F923, 🤣. Windows input is all based around UTF-16 code units, so what I believe is being sent is 0xD83E 0xDD23; Vim should be decoding this UTF-16 and so obtaining U+1F923, but it seems to be treating the input as Unicode code points instead, U+D83E U+DD23, and so I end up with `<d83e><dd23>` on screen. (Well, for gVim anyway: on Vim in Command Prompt on codepage 65001—the closest to a Unicode codepage that they have—the first half of the surrogate pair seems to go missing; but I won’t mind too much about that if it’s fixed for gVim.)

As it stands, I tend to need to enter astral plane characters in something else and then copy them back into Vim (it does treat the clipboard properly).

**Comment by ZyX-I** [comment]
If you memoize the code point you can use either `<C-v>U0001F923` (leading zeroes are not neccessary, but not entering them means that next character must not be a hex digit). There are other workarounds: e.g. you can create a mapping like `noremap! <Char-0xD83E><Char-0xDD23> <Char-0x0001F923>` to make Vim translate two surrogate pairs into what it should be.

I am not saying that this is not something which needs not be fixed, but until it is you can use one of the workarounds. Second should eliminate the need of switching applications for the time being (and you can use VimL script to generate such mappings for a certain range) and first is universal (applicable for terminal as well) (though I personally mapped away all `<C-v>{codepoint}` points for consistency reasons: if I type `<C-v>{character}` I want to see character and nothing else, even if character is `U`; using `<C-r>=` to enter characters by codepoint is far less error-prone as you can edit the codepoint).

**Comment by tonymec** [comment]
To each his or her preferences. I certainly didn't map away Ctrl-V U, Ctrl-V u and Ctrl-V x because OT1H when I want a U u or x I just hit U u or x respectively (no need for a Ctrl-V prefix), and OTOH I occasionally need to produce weird characters, known only by their hex code, and for which I won't make a mapping or a keymap entry because I won't need them repeatedly. Using the expression register with a double-quoted string containing a \x, \u or \U entry feels to me like a roundabout way of doing things. Well YMMV, and AFAICT it does. ;-)

For characters not present on my keyboard which I do need repeatedly I use keymaps (see http://vim.wikia.com/wiki/How_to_make_a_keymap): I have two homemade keymaps, one for Arabic and one for Cyrillic, both loosely based on the concerned letters' phonetic value and both with quite a number of dead keys (i.e. mappings whose {lhs} is more than one character). If I knew one or more East-Asian language I would either create some keymap for them, or else (maybe more probably) learn to use XIM (since I'm on Linux) — and find some IME which makes me feel at ease.

@chris-morgan : Surrogates should indeed never appear as such in UTF-8. If for some reason they do (and in the proper sequence of one high and one low surrogate), hopefully writing the file with 'fileencoding' set to UTF-16 then reading it back (possibly after having deleted the buffer) should get them translated into the proper UTF-8 sequence for the codepoint they represent. But that is only a workaround. The problem you see might IMHO be due to a mismatch between `'encoding'` and `'termencoding'` (though I'm told that on Windows `'termencoding'` is irrelevant because Vim knows how to get the Unicode value of whatever is input, so I could be wrong there).

What does your Vim answer if you type `:verbose set enc? tenc? fenc? fencs?` while editing such a file? And if you give the same command with no vimrc (after starting Vim as `gvim -u NONE -N`, let's say) in an empty buffer? See also http://vim.wikia.com/wiki/Working_with_Unicode

**Comment by chris-morgan** [comment]
@tonymec: `:verbose set enc? tenc? fenc? fencs?` in gVim:

```
  encoding=utf-8
        Last set from ~\vimfiles\vimrc
  termencoding=
  fileencoding=
  fileencodings=ucs-bom,utf-8,default,latin1
        Last set from ~\vimfiles\vimrc
```

And in absolutely plain gVim,

```
  encoding=latin1
  termencoding=
  fileencoding=latin1
  fileencodings=ucs-bom
```

… and then code points made of two UTF-16 code units come through as `??`. (If I `:set encoding=utf-8` then it comes through as the surrogate pair.)

fileencoding and fileencodings are not relevant as this is happening in the input layer (e.g. the same thing happens in command-line mode). Setting termencoding to utf-8, ucs-bom or utf-16le changes nothing, as expected.

I’m fairly confident that the problem is just that Vim is treating the input, which is *actually* UTF-16, as UCS-2; a very easy mistake to make, especially as it works fine until you go astral. If this is the case, then it just needs a proper UTF-16 decoding step added.

**Comment by brammool** [comment]
I'm missing a lot of information here:
- Is this in a console or in gvim?
- Vim version
- What exactly do you do to input the character?  Obviously I don't have a keyboard with an emoji key.
- What does Vim actually receive?  Requires a debugger or adding some ch_log() calls in the source code.

**Comment by chris-morgan** [comment]
This is in both gVim and console Vim—though in the latter, the first half of the surrogate pair seems to go missing.

I am using Vim 8.0.1475, but this issue has been present at least back to ~8.0.500, and I have experienced it with both 64-bit and 32-bit builds of Vim.

There are various ways of producing emoji; I have demonstrated the issue myself on these three:

- Windows’ touch keyboard (although it says “touch” in the name, it is usable with only a mouse);
- If you’re running the latest stable Windows 10 build and have en-us as your input language (or an Insider build and one of a much larger variety of input languages), press Win+. or Win+; to open the emoji panel;
- Use [WinCompose](https://github.com/samhocevar/wincompose/releases) (sample: Compose+rofl produces 🤣).

What Vim actually receives? Not certain. I don’t have a suitable build toolchain set up on this machine at present (a story briefly summarised as a warranty replacement of a laptop).

**Comment by samhocevar** [comment]
The problem lies in `src/gui_w32.c`: the `_OnChar` function calls `char_to_string` and `add_to_input_buf` regardless of the value of `ch`; but if it is a high surrogate value, the character is incomplete and it should wait for the second part of the UTF-16 sequence before converting to a string.

Another way to support Unicode above U+FFFF would be to understand the `WM_UNICHAR` message in addition to `WM_CHAR`, it’s a lot easier (though it will not work with input methods that insist on sending two-part `WM_CHAR` messages).

I am not really familiar with the Vim code but if anyone is interested, I have already implemented both these changes in Notepad++; my changes [can be seen here](https://github.com/samhocevar/fork-notepad-plus-plus/commit/21889b57ffd84847f9aab3a756c3f4a84b89fa7a).

**Comment by chris-morgan** [comment]
I’m going to see if I can compile Vim and then work on a patch based on @samhocevar’s example. (Thanks!)

**Comment by chris-morgan** [comment]
That was fairly painless—compiling really *was* “just run this one command”, and the code was easy to modify. I’m impressed and pleased.

I decided not to mess around with WM_UNICHAR; `char_to_string` seemed a straightforward place to fix things up in.

I deliberately made this laxer than @samhocevar did for Notepad++, in that I didn’t have it validate the low surrogate, but rather just include the high surrogate in the next call of `char_to_string`. Nothing should be emitting a high surrogate followed by other than a low surrogate, but hey, some things are weird, might as well try not to lose input.

Here’s my patch, which works for me in gVim. Console Vim continues to only give the low surrogate and I haven’t made any effort to investigate that.

(Bear in mind also that with `gvim -N -u NONE`, 'encoding' is latin1, and so surrogate pairs still come through as `??`; but if 'encoding' is utf-8 or utf-16le, the surrogate pair is now decoded correctly.)

```patch
diff --git a/src/gui_w32.c b/src/gui_w32.c
index 6596cf8..d551955 100644
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -497,6 +497,8 @@ static UINT	s_kFlags_pending;
 static UINT	s_wait_timer = 0;   /* Timer for get char from user */
 static int	s_timed_out = FALSE;
 static int	dead_key = 0;	/* 0: no dead key, 1: dead key pressed */
+static UINT	surrogate_pending_ch;	/* 0: no surrogate pending,
+					 * else a high surrogate */
 
 #ifdef FEAT_BEVAL_GUI
 /* balloon-eval WM_NOTIFY_HANDLER */
@@ -708,6 +710,12 @@ _OnDeadChar(
  * Convert Unicode character "ch" to bytes in "string[slen]".
  * When "had_alt" is TRUE the ALT key was included in "ch".
  * Return the length.
+ * Because the Windows API deals in UTF-16, we have to deal with surrogate
+ * pairs; this is where we choose to deal with them: if "ch" is a high
+ * surrogate, it will be stored, and the length returned will be zero; the next
+ * char_to_string call will then include the high surrogate, decoding the pair
+ * of UTF-16 code units to a single Unicode code point, presuming it is the
+ * matching low surrogate.
  */
     static int
 char_to_string(int ch, char_u *string, int slen, int had_alt)
@@ -718,8 +726,27 @@ char_to_string(int ch, char_u *string, int slen, int had_alt)
     WCHAR	wstring[2];
     char_u	*ws = NULL;
 
-    wstring[0] = ch;
-    len = 1;
+    if (surrogate_pending_ch)
+    {
+	/* We don't guarantee ch is a low surrogate to match the high surrogate
+	 * we already have; it should be, but if it isn't, tough luck. */
+	wstring[0] = surrogate_pending_ch;
+	wstring[1] = ch;
+	surrogate_pending_ch = 0;
+	len = 2;
+    }
+    else if (ch >= 0xD800 && ch <= 0xDBFF)	/* high surrogate */
+    {
+	/* We don't have the entire code point yet, only the first UTF-16 code
+	 * unit; so just keep it safe and use it in the next call. */
+	surrogate_pending_ch = ch;
+	return 0;
+    }
+    else
+    {
+	wstring[0] = ch;
+	len = 1;
+    }
 
     /* "ch" is a UTF-16 character.  Convert it to a string of bytes.  When
      * "enc_codepage" is non-zero use the standard Win32 function,
@@ -743,7 +770,6 @@ char_to_string(int ch, char_u *string, int slen, int had_alt)
     }
     else
     {
-	len = 1;
 	ws = utf16_to_enc(wstring, &len);
 	if (ws == NULL)
 	    len = 0;
```

**Comment by samhocevar** [comment]
FYI, I have reviewed the logic here and it seems good to me. The pending character is always cleared as soon as the next character is received even if the sequence is invalid, which seems to be the most reasonable course of action.
