### ISSUE TITLE
Does vim support python  integration to it?

### ISSUE THREAD

**Issue by allenzt** [vim/vim#2818]
Thanks for your hard and excellent work! I do like this it. And my doubt is as follows:
In my compiled with source code, I config paremter "--enable-python3interp=yes --with-python3-config-dir=<dir>config-3.5m-x86_64-linux-gnu". However, I find vim support python with dynamic load(+python3/dyn), So how I integrate python into vim(+python3) ? Thanks again!

**Comment by tonymec** [comment]
+python3/dyn means that Python 3 will be available in Vim if Vim can find it. It usually means having the Python3 interpreter in the $PATH.

If you have both Python2 (+python) and Python3 (+python3) enabled, they must both be dynamic and Vim will use only the one used first. To switch from one to the other you must reload Vim.

I suppose you are on Linux or on some Unix-like platform? Then below are my configure arguments, in a script which I **source** in bash before doing anything else, in the konsole tab dedicated to compiling my Huge build. You may use any part of it but of course you will want to change at least the last line to put your name there instead of mine. What I get is gvim with (among others) static Python 2. I don't run `configure` by hand, I let `make` run it, either when it thinks it's needed, or when I run `make reconfig`.
``` bash
# configure arguments for Huge gvim
# to be sourced (not executed) in bash before compiling
export CONF_OPT_GUI='--enable-gui=gnome2'
export CONF_OPT_PERL='--enable-perlinterp'
export CONF_OPT_PYTHON='--enable-pythoninterp'
export CONF_OPT_PYTHON3='--disable-python3interp'
export CONF_OPT_TCL='--enable-tclinterp'
# /usr/bin/tclsh (softlink) is correctly set
export CONF_OPT_RUBY='--enable-rubyinterp'
export CONF_OPT_LUA='--enable-luainterp'
export CONF_OPT_MZSCHEME='--disable-mzschemeinterp'
#export CONF_OPT_PLTHOME='--with-plthome=/usr/local/plt'
export CONF_OPT_CSCOPE='--enable-cscope'
export CONF_OPT_MULTIBYTE='--enable-multibyte'
export CONF_OPT_TERMINAL='--enable-terminal'
export CONF_OPT_AUTOSERVE='--enable-autoservername'
export CONF_OPT_FEAT='--with-features=huge'
export CONF_OPT_COMPBY='"--with-compiledby=antoine.mechelynck@gmail.com"'
```

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
