### ISSUE TITLE
manpager.vim - Color escape codes incorrectly displayed

### ISSUE THREAD

**Issue by loximann** [vim/vim#2823]
A vanilla Fedora 27 installation does not display man pages correctly when the command suggested in the docs is used:

    export MANPAGER='vim -M +MANPAGER -'

The man page looks like:

![image](https://user-images.githubusercontent.com/38527108/38987286-d4c2c250-43d7-11e8-9742-d176f37416ea.png)

Manually removing the escape codes fixes the issue:

    export MANPAGER='vim -M +MANPAGER +"silent %s/^[\[[0-9;]*m//g" -'
(^[ is `<C-Esc>`).

Thanks to Enno Nagel for the discussion, by the way.

**Comment by chrisbra** [comment]
Hm, I wonder where the color codes are coming from?

**Comment by tonymec** [comment]
Maybe from whatever nroff or similar filter man uses to format its output for its pager?

**Comment by chrisbra** [comment]
But that should only happen, if the output is going to be shown by a pager that understands those terminal ansi sequences. And if you set `MANPAGER="tee foobar.txt"` (e.g. the output will be redirected to a textfile no coloring should happen).
So my questions is, is this reproducible with a clean profile (e.g. a new user?) What environment variables are set? Are there any options for groff/troff that make it output color codes? On a quick manpage look I couldn't find any configuration for that, but I might have overlook something.

**Comment by loximann** [comment]
@chrisbra Yes, it is a clean profile. I have tested it on three different machines (one of them not owned by me) and they all yield the same results. I could not spot anything relevant from env, would you want to have the output anyway?

**Comment by chrisbra** [comment]
Hm, sounds a litte bit like this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=666587

We can certainly patch manpager plugin to strip those color codes. I suppose @Konfekt could fix it easily. Nevertheless you might want to open a bug report with the fedora developers, just in case to see if this is a similar bug as mentioned above.

**Comment by loximann** [comment]
Well, less works fine as manpager, it even displays colors correctly. Do you think I should still report a bug in Fedora?

**Comment by nuko8** [comment]
Usually, MANPAGER expects nroff-processed text as its input, e.g., N^HNA^HAM^HME^HE for __NAME__ (bold), and \_^Hg\_^Hi\_^Ht for git (underlined), where ^H is \<C-H>.

On the other hand, according to the screenshot, those byte strings are somehow converted into the escape sequences starting with ^[[1m and ^[[4m, respectively, where ^[ is \<Esc>.  The former renders characters in bold, and the latter does them underlined.

Perhaps, Fedora does something with the system configuration or settings of man(1) in oder to accomplish
> Well, less works fine as manpager, it even displays colors correctly.

since, by default, less(1) won't give colors to man pages; it usually does that through the environmental variables such as LESS_TERMCAP_{md,us} with the help of termcap or terminfo.

That means, if you have man(1) pass nroff output to MANPAGER instead of escape sequences, Vim will work fine for you as MANPAGER.  Isn't there any way to get Fedora's man(1) to revert to the usual behavior? 

BTW, the escape sequences in the form of ^[[ _N_ m, where _N_ is a non-negative integer, are known as SGR or Select Graphic Rendition.  So, rigorously speaking, they are more than color escape codes; among them found in the screenshot, the only sequence related to color is ^[[34m, setting the foreground color to blue.

**Comment by chrisbra** [comment]
correct, less is a bad example to test with. Try something like this:
` man man | head -100`
or try more as pager and check if you see similar escape sequences.
In any case, I would still report this to fedora, just to get some feedback from their developers. Have a look at the mentioned fedora bug, it looks quite similar.

**Comment by loximann** [comment]
head as manpager works fine. I'll file a bug over there.
Cheers, and thanks for the detailed explanations so far!

**Comment by loximann** [comment]
Forgot to mention the bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1570182

**Comment by roolebo** [comment]
FWIW, `MANPAGER='view -M +MANPAGER -'` or `MANPAGER='vim -R -M +MANPAGER -'` interpret the escape codes correctly on the latest vim from homebrew:
```
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:54:00)
macOS version
Included patches: 1-1722
Compiled by Homebrew
```

**Comment by adah1972** [comment]
@loximann I encountered the same problem and found this page during the search. This page does not list the solution, which is a regret. I found the final solution on this page:

https://stackoverflow.com/questions/29754055/force-man-to-output-ansi-codes

I.e. we can fix the ‘new’ groff (mis)behaviour by having `export GROFF_NO_SGR=1`.

**Comment by Konfekt** [comment]
The same issue occurs here as long as `GROFF_NO_SGR=1` is not set. How about proposing setting `export MANPAGER="env GROFF_NO_SGR=1 vim -M +MANPAGER -"` in `doc/filetype.txt`?

**Comment by chrisbra** [comment]
or how about this patch:

```patch
diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index cbace44c1..e51811d62 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -206,7 +206,7 @@ func <SID>GetPage(cmdmods, ...)
   endif
   let env_cmd = s:env_has_u ? 'env -u MANPAGER' : 'env MANPAGER=cat'
   let man_cmd = env_cmd . ' man ' . s:GetCmdArg(sect, page) . ' | col -b'
-  silent exec "r !" . man_cmd
+  silent exec "r ! GROFF_NO_SGR=1" . man_cmd

   if unsetwidth
     let $MANWIDTH = ''
```

Interestingly, I just noticed on my server, where I read the mail, that this:

`export MANPAGER="vim -M +MANPAGER -" `

causes a segfault in bash or col. Hmm...

**Comment by Konfekt** [comment]
Shouldn't the spaces be at `"r !GROFF_NO_SGR=1 " . man_cmd` ? Perhaps `!env GROFF...` is necessary.

**Comment by chrisbra** [comment]
Oh yes, there should be a trailing space after the GROFF_NO_SGR, you are right.

I thought about `!env GROFF` , but that would mean we need 2 `env` calls for the `env -u case` and I thought we can safe that.

**Comment by Konfekt** [comment]
> I thought about !env GROFF , but that would mean we need 2 env calls for the env -u case and I thought we can safe that.

So how about prepending`GROFF_...` in between `let env_cmd = ...` and `let man_cmd = ...`?

**Comment by Konfekt** [comment]
> I thought about !env GROFF , but that would mean we need 2 env calls for the env -u case and I thought we can safe that.

So how about prepending`GROFF_...` in between `let env_cmd = ...` and `let man_cmd = ...`?

**Comment by jamessan** [comment]
> that would mean we need 2 `env` calls for the `env -u case` and I thought we can safe that.

Why?  `env -u MANPAGER GROFF_NO_SGR=1 ...` works.

**Comment by chrisbra** [comment]
> Why? env -u MANPAGER GROFF_NO_SGR=1 ... works.

Ah indeed. I must have missed the GROFF environment variable when I looked at the output. Thanks!

**Comment by goweol** [comment]
It seems I need to patch the man.vim plugin for this issue.
However, man.vim contains the following code because some env does not support the -u option.
  let env_cmd = s:env_has_u ? 'env -u MANPAGER' : 'env MANPAGER=cat'

Will it work if I change it like below?
  let env_cmd = s:env_has_u ? 'env -u MANPAGER GROFF_NO_SGR=1' : 'env MANPAGER=cat GROFF_NO_SGR=0'

Any suggestions?
Thanks!

**Comment by goweol** [comment]
I think I was confused about something.
I will apply patch below.  I hope I did it right now.

diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index d7ce4d8ac..2dd4906bf 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -205,6 +205,7 @@ func <SID>GetPage(cmdmods, ...)
     let s:env_has_u = (v:shell_error == 0)
   endif
   let env_cmd = s:env_has_u ? 'env -u MANPAGER' : 'env MANPAGER=cat'
+  let env_cmd .= ' GROFF_NO_SGR=1'
   let man_cmd = env_cmd . ' man ' . s:GetCmdArg(sect, page) . ' | col -b'
   silent exec "r !" . man_cmd

**Comment by roolebo** [comment]
@chrisbra perhaps the ticket should be reopened, do you need a PR?

I was curious about intention of groff developers just to be clear why the environment variable has to be set. It seems Werner [changed default behaviour](https://lists.gnu.org/archive/html/groff-commit/2002-02/msg00022.html) of groff/grotty to output ANSI escape codes instead of output of backspace codes to simplify pagers. With the new default behaviour, pagers don't have to turn backspace codes into escaped codes. That allows nice formatting in `MANPAGER=cat`. 

However groff [doesn't have a dependency on terminfo](https://lists.gnu.org/archive/html/groff/2005-03/msg00106.html) so it's not really aware if output device is a terminal that support ANSI escape codes. And Vim is not a terminal device too, unless `:term` is used.

Here's a bit more background:
1. https://unix.stackexchange.com/a/243973/70189
2. https://lists.nongnu.org/archive/html/groff/2005-07/msg00013.html

It's funny that Debian and emacs disabled SGR since appearance of the feature. So in case of intermediate man page processing, like custom pager, GROFF_NO_SGR should be set.

macOS, like Debian, has disabled SGR in `troffrc`:
```
.\" Disable SGR support in grotty(1).
.if n \{\
.       do nop \X'tty: sgr 0'
.       sp -1
.       nr nl 0-1
.       nr % -1
.\}
```

**Comment by roolebo** [comment]
For the reference, the issue is resolved since v8.2.0540 (https://github.com/vim/vim/commit/d1caa941d876181aae0ebebc6ea954045bf0da24)

**Comment by peterwu** [comment]
I'm still experiencing this problem with v8.2.1941. Also, the workaround, `export MANPAGER="env GROFF_NO_SGR=1 vim -M +MANPAGER -"` doesn't work, either. So far, the only way to make it work is to break it apart like this:
```
export GROFF_NO_SGR=1
export MANPAGER="vim -M +MANPAGER -"
man man
```

or 
```
$ export MANPAGER="vim -M +MANPAGER -"
$ GROFF_NO_SGR=1 man man
```

Either of the above 2 works on my Fedora 33. VIM 8.2.1941.

I made sure the patch d1caa94 does exist in my vim install.

**Comment by Konfekt** [comment]
Please try

```vim
set filetype=man
Man man
```

This should work because https://github.com/vim/vim/commit/d1caa941d876181aae0ebebc6ea954045bf0da24 prepends `GROFF_NO_SGR=1` to the `man` command. 

However, `:MANPAGER` does not, and removing the escape codes 

```vim
"silent %s/^[\[[0-9;]*m//g"
```

as proposed at https://github.com/vim/vim/issues/2823#issue-315826113 could be necessary.

**Comment by peterwu** [comment]
Yes, the 2 VIM comands work if I first launch VIM then run them. However, this is not how manpager works in a shell environment. A user typically types `man man` at CLI and expects MANPAGER to take care of the rest.

With regard to the workaround, `export MANPAGER='vim -M +MANPAGER +"silent %s/^[\[[0-9;]*m//g" -'`, it sort of works. Based on my limited testing, it seems to work with `man man` but `man ls` gives me an `E486: Pattern not found: ^[\[[0-9;]*m`. If I ignore the error, the man page looks correct.

I tend to believe this bug is still not completely addressed, at least, `:h manpager` needs updating because it simply doesn't work as documented. We may want to add workarounds to the doc so users can temporarily get the functionality working until a permanent fix is available.

**Comment by chrisbra** [comment]
I wonder if this is some kind of a shell issue.

**Comment by peterwu** [comment]
Not sure if it's a shell issue as it has Fedora defaults but if I simply use neovim's version, export MANPAGER='nvim +Man!', everything works correctly without any aforementioned workaround.

**Comment by chrisbra** [comment]
Neovim has completely reworked the manpager plugin, it's different. Why I mentioned it, was I thought you could give us some more information on your system. So far you seem to be the only one affected since this has been closed. So is there anything special on your system?

**Comment by peterwu** [comment]
There's really nothing special here. Basically it's a fresh install of Fedora 33 workstation. :-)

btw, I just removed ALL my added stuff in .bashrc and .bash_profile leaving ONLY the suggested `export MANPAGER="vim -M +MANPAGER -"` in .bashrc and I can still reproduce the bug. 

I'm willing to run some tests here to find out the root cause. So, please guide me.

**Comment by peterwu** [comment]
It seems to me that if GROFF_NO_SGR=1 is set in the shell environment, vim manpager works correctly. My wild guess is that maybe the patched env_cmd in d1caa94 is not reached if invoked from +MANPAGER? A quick test shows : in the garbled text situation, `echo $GROFF_NO_SGR` in VIM returns nothing.

Not sure if this helps but here's the output of env on my system. 

```
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=gnome
DISPLAY=:0
GDM_LANG=en_US.UTF-8
GDMSESSION=gnome
GNOME_SETUP_DISPLAY=:1
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/722f20a4_03e2_43ed_b566_56d414e5dd26
GNOME_TERMINAL_SERVICE=:1.95
HISTCONTROL=ignoredups
HISTSIZE=1000
HOME=/home/peter
HOSTNAME=blueberry
LANG=en_US.UTF-8
LESSOPEN=||/usr/bin/lesspipe.sh %s
LOGNAME=peter
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/peter
MANPAGER=vim -M +MANPAGER -
PATH=/home/peter/.local/bin:/home/peter/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
PWD=/home/peter
QT_IM_MODULE=ibus
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1613,unix/unix:/tmp/.ICE-unix/1613
SHELL=/bin/bash
SHLVL=0
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
USERNAME=peter
USER=peter
_=/usr/bin/env
VTE_VERSION=6201
WAYLAND_DISPLAY=wayland-0
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.35ILT0
XDG_CURRENT_DESKTOP=GNOME
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XMODIFIERS=@im=ibus
```

**Comment by Konfekt** [comment]
> With regard to the workaround, `export MANPAGER='vim -M +MANPAGER +"silent %s/^[\[[0-9;]*m//g" -'`, it sort of works. Based on my limited testing, it seems to work with `man man` but `man ls` gives me an `E486: Pattern not found: ^[\[[0-9;]*m`. If I ignore the error, the man page looks correct.

This at least should be fixed by replacing `silent` with `silent!`.

**Comment by chrisbra** [comment]
or add the `e` flag to the `:s` command.

@peterwu   Can you please use the following patch:

```patch
diff --git a/runtime/ftplugin/man.vim b/runtime/ftplugin/man.vim
index e62637ae0..3970ce423 100644
--- a/runtime/ftplugin/man.vim
+++ b/runtime/ftplugin/man.vim
@@ -211,6 +211,7 @@ func s:GetPage(cmdmods, ...)
   let env_cmd .= ' GROFF_NO_SGR=1'
   let man_cmd = env_cmd . ' man ' . s:GetCmdArg(sect, page) . ' | col -b'
   silent exec "r !" . man_cmd
+  let g:man_cmd=man_cmd

   if unsetwidth
     let $MANWIDTH = ''
```

Then run the command again and in the case of your garbled Vim, please echo `:echo g:man_cmd`? Does it contain the `GROFF_NO_SGR`  setting?

So if you then use `:exe ":r !" . g:man_cmd` I assume it still returns garbeled output? Does it reproduce with `vim --clean`? If it doesn't perhaps check your shell settings.

**Comment by peterwu** [comment]
@chrisbra, 

I applied the patch, did a `$ man man`, saw garbled text and `:echo g:man_cmd` returns an `E121: Undefined variable: g:man_cmd` error.

If I launch vim first, then `:set ft=man` followed by `:Man man`, the page displays correctly and `:echo g:man_cmd` returns `env -u MANPAGER GROFF_NO_SGR=1 man 'man' | col -b`.

In order to test with vim --clean, I aliased `vim='vim --clean'`, and repeated 2 above steps, and got the exactly same results. 

Updates:
- I installed a vanilla Fedora 33 Workstation VM and was able to reproduce the bug. Also, the g:man_cmd test yielded the same results. VIM 8.2.1941
- On a vanilla openSUSE Tumbleweed VM (GNOME), the same bug and same g:man_cmd test results as on Fedora 33. VIM 8.2.1955
- On a vanilla Ubuntu 20.10 VM (GNOME), it works! It has VIM 8.2.716. I went ahead and removed the stock vim and vim-runtime packages. Then I compiled 8.2.1941 and 8.2.1955 on Ubuntu by using the source tar balls from vim github. Both worked! HOWEVER, both also failed the g:man_cmd test with the E121 error. 

So, even in a working VIM, the code that sets g:man_cmd is not hit. I'm not familiar with Ubuntu but I'd guess some settings on Ubuntu did the magic while on Fedora/openSUSE, such magic setting doesn't exist. 

I added some debugging code in man.vim and it looks like s:GetPage() is not called. 

Hope this helps narrow down the bug.

**Comment by robin-a-meade** [comment]
What do you all think of Workaround#2 mentioned in the downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1570182#c3

**Comment by peterwu** [comment]
#2 works on all the 3 distros!! I'm for it. 👍 

@chrisbra do you think we can merge this workaround ? For the sake of convenience, the code is copied below.

```
WORKAROUND #2
=============
Modify /usr/share/vim/vim81/plugin/manpager.vim


diff --git a/manpager.vim b/manpager.vim.new
index dd0d1e8..486a170 100644
--- a/manpager.vim
+++ b/manpager.vim.new
@@ -18,6 +18,9 @@ function! s:ManPager()
   " Emulate 'col -b'
   silent keepj keepp %s/\v(.)\b\ze\1?//ge
 
+  " Remove ansi sequences
+  silent keepj keepp %s/\v\e\[%(%(\d;)?\d{1,2})?[mK]//ge
+
   " Remove empty lines above the header
   call cursor(1, 1)
   let n = search(".*(.*)", "c")
```
