### ISSUE TITLE
Patch applied in 6176697203b0f168f4566597e15d8488b62ad490 is not effective

### ISSUE THREAD

**Issue by graywolf** [vim/vim#2833]
This is follow up for #2826. When I try to compile ruby with patch 1739 (which should enable `DYNAMIC_RUBY=no`), I get this error:

	gobjx86-64/if_ruby.o:if_ruby.c:(.text+0x1cd): undefined reference to `NtInitialize'
	gobjx86-64/if_ruby.o:if_ruby.c:(.text+0x8d3): undefined reference to `__imp_ruby_errinfo'

Example of actual compilation line is:

	gcc -c -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_RUBY -I g:/WS/progs/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0/x64-mingw32 -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s os_w32exe.c -o gobjx86-64/os_w32exe.o

As you can see, `-DRUBY_VERSION=25` is missing from there. When I remove 1739 and apply my original suggested patch

	$ git diff
	diff --git a/src/Make_cyg_ming.mak b/src/Make_cyg_ming.mak
	index b21a1d40a..d51b6ea89 100644
	--- a/src/Make_cyg_ming.mak
	+++ b/src/Make_cyg_ming.mak
	@@ -458,7 +458,6 @@ RUBYINC += -I $(RUBY)/include/ruby-$(RUBY_API_VER_LONG) -I $(RUBY)/include/ruby-
	 endif
	 ifeq (no, $(DYNAMIC_RUBY))
	 RUBYLIB = -L$(RUBY)/lib -l$(RUBY_INSTALL_NAME)
	-CFLAGS += -DRUBY_VERSION=$(RUBY_VER)
	 endif

	 endif # RUBY
	@@ -538,6 +537,9 @@ ifeq (yes, $(DYNAMIC_RUBY))
	 CFLAGS += -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"$(RUBY_INSTALL_NAME).dll\"
	 CFLAGS += -DDYNAMIC_RUBY_VER=$(RUBY_VER)
	 endif
	+ifeq (no, $(DYNAMIC_RUBY))
	+CFLAGS += -DRUBY_VERSION=$(RUBY_VER)
	+endif
	 ifneq ($(findstring w64-mingw32,$(CC)),)
	 # A workaround for MinGW-w64
	 CFLAGS += -DHAVE_STRUCT_TIMESPEC -DHAVE_STRUCT_TIMEZONE

I am able to compile vim just fine. But I admit I have no idea why your version is not working.

**Comment by tonymec** [comment]
Please refer to patches by version and patchlevel. The changeset number (1739 in your example) is not conserved between clones (in mine, changeset 1739 is at patchlevel 7.2.036) while the changeset ID (`6176697203b0f168f4566597e15d8488b62ad490` in this case) is conserved but is not monotonic (i.e. there is no rule to say which of two such comes before the other without walking the changesets sequentially to find them). The major-minor-patchlevel ID is human-readable, it is machine-readable (because it corresponds one-by-one to a tag in the repository) and it is monotonously increasing.

**Comment by brammool** [comment]
Gray Wolf wrote:

> This is follow up for #2826. When I try to compile ruby with patch 1739 (which should enable `DYNAMIC_RUBY=no`), I get this error:
> 
> 	gobjx86-64/if_ruby.o:if_ruby.c:(.text+0x1cd): undefined reference to `NtInitialize'
> 	gobjx86-64/if_ruby.o:if_ruby.c:(.text+0x8d3): undefined reference to `__imp_ruby_errinfo'
> 
> Example of actual compilation line is:
> 
> 	gcc -c -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_TERMINAL -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_RUBY -I g:/WS/progs/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0 -I g:/WS/progs/Ruby25-x64/include/ruby-2.5.0/x64-mingw32 -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s os_w32exe.c -o gobjx86-64/os_w32exe.o
> 
> As you can see, `-DRUBY_VERSION=25` is missing from there. When I
> remove 1739 and apply my original suggested patch

My fault, I didn't notice that CFLAGS is initialized only later.


-- 
hundred-and-one symptoms of being an internet addict:
242. You turn down a better-paying job because it doesn't come with
     a free e-mail account.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
