### ISSUE TITLE
autocmd CmdlineEnter problem

### ISSUE THREAD

**Issue by cs86661** [vim/vim#2837]
OS: windows 7 64-bit
VIM: 8.0.1733
Start: `vim --clean`
```
:au! CmdlineEnter * echomsg expand('<afile>')<CR>
? ---> echo '?'
: ---> echo ':'
/ ---> echo '\' ?!
:cd c:\<CR>
/ ---> echo 'C:\' ?!
```
I think it should echo `/` ...

**Comment by brammool** [comment]
> OS: windows 7 64-bit
> VIM: 8.0.1733
> Start: `vim --clean`
> ```
> :au! CmdlineEnter * echomsg expand('<afile>')<CR>
> ? ---> echo '?'
> : ---> echo ':'
> / ---> echo '\' ?!
> :cd c:\<CR>
> / ---> echo 'C:\' ?!
> ```
> I think it should echo `/` ...

This is because 'shellslash' is not set.  Expanding <afile> handles the
character as a file name.  I'll make a fix.

-- 
Hear about the guy who played a blank tape at full blast?
The mime next door went nuts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
