### ISSUE TITLE
Cannot allocate color 235

### ISSUE THREAD

**Issue by ghost** [vim/vim#2868]
When I start Vim 8.0.1453 on Ubuntu 18.04 LTS, I get the following error:

`Line  101:`
`E254: Cannot allocate color 235.`

This relates to the following line in my .vimrc:

`highlight LineNr ctermfg=245 ctermbg=235`

My terminal uses the following settings:
`echo $TERM`
`xterm-256color`

Any suggestions how this can be fixed?

**Comment by tonymec** [comment]
What does Vim answer to
``` vim
:verbose set term? t_Co? termguicolors?
```
? The expected values are `xterm-256color` and `256` for the first two respectively, the default for the third one (if compiled-in) is `notermguicolors`, but Vim will also tell you in which script (if any) they were last set. Not telling you for one or more of them means that it was (or they were) set either as a startup default or by manual action.

See also the black on pale-yellow list of patches near the top of http://ftp.vim.org/pub/vim/patches/8.0/ — some of the 334 changes (to date) after 8.0.1453 **might** be fixes for your problem, but none of them strikes me bang in the head as **the** obvious one.

Compiling one's own Vim (to get the latest fixes) is not very hard, especially on Linux; see http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial and http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

Best regards,
Tony.

**Comment by ghost** [comment]
Thanks for your response, Tony.

The mentioned snippet returns the following:

```
  term=xterm-256color
  t_Co=256
        Last set in ~/.vimrc
notermguicolors
```
Do you have a recommendation how to proceed from here?

**Comment by nuko8** [comment]
> Do you have a recommendation how to proceed from here?

As E254 matters only when you are using termguicolors Vim or GVim, it looks strange to get the error against notermguicolors Vim.

@AvexMedia , will you try and do `:hi LineNr` immediately after you get E254, and report back the result here?  That might give us a clue to diagnosing the issue.

**Comment by ghost** [comment]
`:hi LineNr` returns the following @nuko8:

`LineNr         xxx term=underline ctermfg=245 ctermbg=235 guifg=#3E4853 guibg=#111314`

**Comment by nuko8** [comment]
Thanks.  Then, please try:
```
$ vim --clean +'hi LineNr ctermfg=245 ctermbg=235'
```
Do you still have an E254 error with this?  What does `:hi LineNr` say this time?

**Comment by chrisbra** [comment]
I am a bit stumped, because according to what I know, E254 should only occur for color names and not color indexes.  You don't have by any chance used the index 235 as guifg or guibg attribute? Are you sure, the corresponding line in your .vimrc is correct? Are there other highlighting definitions?
BTW: Can you please set `verbose` setting to one and see if this returns some more output?

**Comment by nuko8** [comment]
@AvexMedia 

If you don't have E254 with the command I asked you to run, then that strongly indicates that there's `guifg=235` or `guibg=235` (Neither `ctermfg=235` nor `ctermbg=235`,  since both are irrelevant to E254 at any rate.) at Line 101 of one of the Vim scripts that constitute the whole of your Vim settings (Not necessarily `.vimrc` only).  If that's the case, please follow @chrisbra 's comment.  That's exactly the same as mine for the case where you don't have E254 with the mentioned command.

Honestly, I thought you would report back a result showing that `LineNr` had either `guifg=235` or `guibg=235`, but that turned out not the case.  Probably, in your settings, `gui{fg|bg}`of `LineNr` is set to 235 at Line 101 of a file unknown to us at some point of startup, and then  overwritten to `#3E4853` and `#111314`, respectively, somewhere afterwards.  The `:verbose` command would help you spot the place causing the trouble.  If it fails you, you might need to examine every relevant file at worst.

**Comment by chrisbra** [comment]
No more info. I am closing this as unreproducible.
