### ISSUE TITLE
Gnome file chooser will not display all files when a known file type is opened.

### ISSUE THREAD

**Issue by aolowin** [vim/vim#2873]
On gvim version 8.0.1453 under Gnome the Open... dialog box will not show some files in the directory depending on the type of file opened previously.

steps to reproduce:
Create a directory with 3 files: bug  bug.c  bug.txt
Open either bug or bug.txt
Use the Open... menu: all files are visible, the file filter is set to: All Files (*)
Open bug.c
Use the Open... menu: the bug file is not visible, the file filter is set to: All Files (*.*)
There is no option to set the filter to (*)
Switch the buffer to bug.txt
Use the Open... menu: all files are visible, the file filter is set to: All Files (*)

A similar problem happens if you use bug.py, the All Files is incorrectly set to (*.*) instead of *

**Comment by nuko8** [comment]
> All Files is *incorrectly* set to \*.\* instead of \*

(Italics and corrections are mine.  FYI, type in `\*` into Write to have `*` in Preview.)

FWIW, that is rather intentional.  Please have a look at the definitions of `BROWSE_FILTER_MACROS`, `BROWSE_FILTER_ALL_FILES` and `BROWSE_FILTER_DEFAULT` given [here](https://github.com/vim/vim/blob/v8.0.1790/src/vim.h#L2189-L2193); you'll see them all having the pattern `*.*` as the definition of "All Files".

As to the syntax used there, please refer to `:h browsefilter`.  If you read it, you'll come to know how to adjust the filter to your preferences globally or even buffer-wisely.  For example, if you don't want any global filter at all, you can do it with `:let g:browsefilter = "All Documents (*)\t*\n"`.

**Comment by nuko8** [comment]
> FWIW, that is rather intentional. Please have a look at the definitions of BROWSE_FILTER_MACROS, BROWSE_FILTER_ALL_FILES and BROWSE_FILTER_DEFAULT given here

See also [here](https://github.com/vim/vim/blob/c136af29c0b1939076fbae7d36afd90dce740315/runtime/ftplugin/c.vim#L42-L61) and [here](https://github.com/vim/vim/blob/c136af29c0b1939076fbae7d36afd90dce740315/runtime/ftplugin/python.vim#L108-L111), which should explain to you in a more straightforward way what happens with certain file types for the "Open..." dialog.

**Comment by chrisbra** [comment]
closing.
