### ISSUE TITLE
Issue in test function with feedkeys(), autocommands and pumvisible() in a mapping

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#2876]
I have posted this on the Vim mailing list, but I am opening an issue here because I think that this is a bug, or at least a shortcoming, of `feedkeys()` (but I may be missing something about some internal character processing in Vim).

The following test code, which is supposed to automatically trigger keyword completion upon typing `o`, fails using `vim --clean`:

```vim
let s:o_char_pressed = 0

fun! s:act_on_text_changed()
  if s:o_char_pressed
    let s:o_char_pressed = 0
    call feedkeys("\<c-x>\<c-n>", 'i')
  endif
endf

fun! Test_complete_o_tab()
  set completeopt=menu,noselect
  new
  imap <expr> <buffer> <tab> pumvisible() ? "\<c-p>" : "X"
  autocmd! InsertCharPre <buffer> let s:o_char_pressed = (v:char ==# 'o')
  autocmd! TextChangedI <buffer> call <sid>act_on_text_changed()
  call setline(1,  ['hoard', 'hoax', 'hoarse', ''])
  let l:expected = ['hoard', 'hoax', 'hoarse', 'hoax', 'hoax']
  call cursor(4,1)
  call test_override("char_avail", 1)
  call feedkeys("Ahoa\<tab>\<tab>\<c-y>\<esc>", 'tx')  " OK
  call feedkeys("oho\<tab>\<tab>\<c-y>\<esc>", 'tx')   " FAILS
  call assert_equal(l:expected, getline(1,'$'))
  call test_override("char_avail", 0)
  bwipe!
  set completeopt&
endf
```

The output is:

```
hoard
hoax
hoarse
hoax
hoXX
```

Note that the last line was not completed correctly, likely because `pumvisible()` is evaluated to `0` when expanding `<tab>` in the second call to `feedkeys()` (but not in the first—why?).

Note also that, if you replace (at least) the first occurrence of `<tab>` with `<c-p>` in the second call to `feedkeys()` then the test passes.

**Comment by vim-ml** [comment]
On Sa, 05 Mai 2018, Lifepillar wrote:

> I have posted this on the Vim mailing list, but I am opening an issue here because I think that this is a bug, or at least a shortcoming, of `feedkeys()` (but I may be missing something about some internal character processing in Vim).
> 
> The following test code, which is supposed to automatically trigger keyword completion upon typing `o`, fails using `vim --clean`:
> 
> ```vim
> let s:o_char_pressed = 0
> 
> fun! s:act_on_text_changed()
>   if s:o_char_pressed
>     let s:o_char_pressed = 0
>     call feedkeys("\<c-x>\<c-n>", 'i')
>   endif
> endf
> 
> fun! Test_complete_o_tab()
>   set completeopt=menu,noselect
>   new
>   imap <expr> <buffer> <tab> pumvisible() ? "\<c-p>" : "X"
>   autocmd! InsertCharPre <buffer> let s:o_char_pressed = (v:char ==# 'o')
>   autocmd! TextChangedI <buffer> call <sid>act_on_text_changed()
>   call setline(1,  ['hoard', 'hoax', 'hoarse', ''])
>   let l:expected = ['hoard', 'hoax', 'hoarse', 'hoax', 'hoax']
>   call cursor(4,1)
>   call test_override("char_avail", 1)
>   call feedkeys("Ahoa\<tab>\<tab>\<c-y>\<esc>", 'tx')  " OK
>   call feedkeys("oho\<tab>\<tab>\<c-y>\<esc>", 'tx')   " FAILS
>   call assert_equal(l:expected, getline(1,'$'))
>   call test_override("char_avail", 0)
>   bwipe!
>   set completeopt&
> endf
> ```
> 
> The output is:
> 
> ```
> hoard
> hoax
> hoarse
> hoax
> hoXX
> ```
> 
> Note that the last line was not completed correctly, likely because `pumvisible()` is evaluated to `0` when expanding `<tab>` in the second call to `feedkeys()` (but not in the first—why?).
> 
> Note also that, if you replace (at least) the first occurrence of `<tab>` with `<c-p>` in the second call to `feedkeys()` then the test passes.

It is a bit tricky to follow your script, since you are doing quite some 
automatic processing in combination with TextChangedI and InsertCharPre 
autocommands to add some keys into the type buffer, plus some of them 
are mapped.

However, I think I managed to find the problem.

There is a comment in edit.c:
,----
|        * If there's any pending input, grab up to INPUT_BUFLEN at once.
|        * This speeds up normal text input considerably.
|        * Don't do this when 'cindent' or 'indentexpr' is set, because we might
|        * need to re-indent at a ':', or any other character (but not what
|        * 'paste' is set)..
|        * Don't do this when there an InsertCharPre autocommand is defined,
|        * because we need to fire the event for every character.
`----

However the test for the insert char pre autocommand fires after the 
call to vpeekc(), which already changes the input typebuf. Sligthly 
re-ordering the conditions, made the test pass.

I attach the patch plus your test. Thanks for the test, this made it 
easy to convert it into the test suite.


Best,
Christian
-- 
Gesunder Menschenverstand ist das Talent, die Dinge zu sehen, wie sie
sind, und Dinge zu tun, wie sie getan werden sollten.
		-- Calvin Ellis Stowe

**Comment by lifepillar** [comment]
Your patch appears to fix the issue. If you can wait a few days, I will report back on more tests stressing similar circumstances.

>It is a bit tricky to follow your script

I know, but I could reproduce the issue only with the combination of autocommands, custom mapping and `feedkeys()` that I have used. Thanks for looking into it anyway.

**Comment by chrisbra** [comment]
> I will report back on more tests stressing similar circumstances.

If this all involves `InsertCharPre` autocommands, it should fix it.

**Comment by chrisbra** [comment]
To be honest, this kind of automation (freely mixing mappings, InsertCharPre and TextChanged autocommands) makes me a bit nervous, it looks a bit fragile. So how good does this work in practice?

**Comment by lifepillar** [comment]
>How good does this work in practice?

That's the setup of my MUcomplete plugin, which works pretty well, also according to the feedback I get. So, I'd say that this kind of automation is quite robust. The only issue I had is with testing some parts of it, but your patch should fix that, too.
