### ISSUE TITLE
Confused behavior when setting completeopt to menu,noinsert

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#2877]
Steps to reproduce:
1. Open vim with `vim -u NONE`
2. `:set completeopt=menu,noinsert`
3. Insert some text:
    ```
    abcde
    abc|
    ```
4. Type `<C-n>` to start completion after `abc`,  vim could say `only match` and does nothing.
5. Type `<C-n>` several times, the matched text `abcde` would be inserted.

Expected:

For better user experience, when using `menu` and `noinsert` and there is only one item available, vim should ignore `noinsert` and insert the only one match.

**Comment by lifepillar** [comment]
The change you propose, while sensible, would break completion plugins (mine, for example), because `noinsert` would not be guaranteed to… not insert any longer. It would be tricky for a plugin to distinguish a situation in which there is only one match hence it is inserted from a situation in which there are two or more matches hence the text is not completed.

If anything, that should be implemented by adding a new flag to `completeopt`. Although that would double the number of possible `completeopt` configurations plugins have to deal with…

**Comment by chemzqm** [comment]
@lifepillar How about ignore `menu` and show the menu with the only one complete item?

**Comment by lifepillar** [comment]
Can't you do that already with `menuone`?

**Comment by chemzqm** [comment]
@lifepillar Ok, I see, maybe the documentation should say user should not use `menu` with `noinsert` or even better echo a warning message when this happens.

**Comment by chrisbra** [comment]
I am closing this as working as expected and the suggested change would make it harder for existing completion plugins to work correctly.
