### ISSUE TITLE
CmdLineEnter, CmdLineLeave are triggered from mappings

### ISSUE THREAD

**Issue by justinmk** [vim/vim#2889]
# Actual behavior:

```
:au CmdLineEnter * echom localtime()
:nnoremap a :<CR>
```

Then typing `a` will trigger the CmdLineEnter handler.

# Expected behavior:

Given that CmdLineEnter, CmdLineLeave are mostly for interactive use-cases, it seems like an oversight to also invoke them from mappings. Also based on `:help CmdLineEnter`.

Could check `KeyTyped`:

```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 0124098da519..7a7e4537bfbd 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -418,7 +418,8 @@ getcmdline(
 
     /* Trigger CmdlineEnter autocommands. */
     cmdline_type = firstc == NUL ? '-' : firstc;
-    trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINEENTER);
+    if (KeyTyped)
+       trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINEENTER);
 
 #ifdef FEAT_CMDHIST
     init_history();
@@ -1957,7 +1958,8 @@ cmdline_not_changed:
 
 cmdline_changed:
        /* Trigger CmdlineChanged autocommands. */
-       trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINECHANGED);
+       if (KeyTyped)
+           trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINECHANGED);
 
 #ifdef FEAT_SEARCH_EXTRA
        /*
@@ -2158,7 +2160,8 @@ returncmd:
        need_wait_return = FALSE;
     
     /* Trigger CmdlineLeave autocommands. */
-    trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINELEAVE);
+    if (KeyTyped)
+       trigger_cmd_autocmd(cmdline_type, EVENT_CMDLINELEAVE);
 
     State = save_State;
 #ifdef HAVE_INPUT_METHOD
```

**Comment by andymass** [comment]
What if the user has a map like `nnoremap \b :b<space>`?  Would/should the autocmd be triggered?

**Comment by brammool** [comment]
Justin M Keyes wrote:

> # Actual behavior:
> 
> ```
> :au CmdLineEnter * echom localtime()
> :nnoremap a :<CR>
> ```
> 
> Then typing `a` will trigger the CmdLineEnter handler.
> 
> # Expected behavior:
> 
> Given that CmdLineEnter, CmdLineLeave are mostly for interactive use-cases, it seems like an oversight to also invoke them from mappings. Also based on `:help CmdLineEnter`.
> 
> Could check `KeyTyped`:

That becomes too unpredictable.  Users may map some keys, use them as
shortcuts.

However, when the whole command is generated, the user is never prompted
to type anything, I suppose the autocommands are not useful.  So perhaps
triggering could be postponed until waiting for a character to be typed?

Not sure what the actual problem is we are trying to fix here.


-- 
It's not hard to meet expenses, they're everywhere.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by justinmk** [comment]
> Not sure what the actual problem is we are trying to fix here.

It's a potential performance problem: `:` in maps will trigger `CmdLineEnter` for no reason. As I said, my assumption (and `:help CmdLineEnter`) is that CmdLineEnter is for interactive use-cases, so triggering it in mappings will make many mappings slow which previously were not.

However, I just noticed that InsertCharPre works the same way.

```
:au InsertCharPre * echom localtime()
:nnoremap a ifoo<esc>
a
```

I'll leave it up to discussion whether to close this.

**Comment by lacygoill** [comment]
> Not sure what the actual problem is we are trying to fix here.

If you have an autocmd which temporarily enables `'relativenumber'` while you're on the command-line, maybe to help you write a range:

    augroup my_cmdline
        autocmd!
        autocmd CmdlineEnter : setlocal relativenumber number | redraw
        autocmd CmdlineLeave : setlocal norelativenumber nonumber
    augroup END

It may be triggered when the command-line is entered from a mapping or an autocmd, which is distracting if you disable `'relativenumber'` by default. Because it makes the column number appear and disappear immediately afterwards, when you don't expect it (i.e. press a mapping which executes an Ex command for example).

It sometimes does on my machine if I install the previous autocmd, but I don't know exactly which mappings or other autocmds are interacting.

> So perhaps triggering could be postponed until waiting for a character to be typed?

+1. I would like that change.

**Comment by markonm** [comment]
>>    So perhaps triggering could be postponed until waiting for a character to be typed?

> +1. I would like that change.

What would happen if mapping exits command line immediately without waiting for typed character? Would `CmdLineEnter` event be skipped? What about `CmdLineLeave`, would it also be skipped? If user calls command line window via `q:`, `CmdwinEnter` event would be emitted before `CmdlineEnter`, that would mess up order of events.

Events can already be postponed until waiting for a character with the help of timers.
```vim
function! s:do_domething() abort
  echom localtime()
endfunction
au vimrc CmdlineEnter : let s:do = timer_start(0, {-> s:do_domething()})
au vimrc CmdlineLeave : call timer_stop(s:do)
```

**Comment by justinmk** [comment]
> Events can already be postponed until waiting for a character with the help of timers.

That doesn't solve the problem at all, it just creates more problems for plugin authors.  If timers were a solution we wouldn't have needed `CmdLineEnter` in the first place.

**Comment by brammool** [comment]
> > Not sure what the actual problem is we are trying to fix here.
> 
> If you have an autocmd which temporarily enables `'relativenumber'` while you're on the command-line, maybe to help you write a range:
> 
>     augroup my_cmdline
>         autocmd!
>         autocmd CmdlineEnter : setlocal relativenumber number | redraw
>         autocmd CmdlineLeave : setlocal norelativenumber nonumber
>     augroup END
> 
> It may be triggered when the command-line is entered from a mapping or an autocmd, which is distracting if you disable `'relativenumber'` by default. Because it makes the column number appear and disappear immediately afterwards, when you don't expect it (i.e. press a mapping which executes an Ex command for example).
> 
> It sometimes does on my machine if I install the previous autocmd, but I don't know exactly which mappings or other autocmds are interacting.
> 
> > So perhaps triggering could be postponed until waiting for a character to be typed?
> 
> +1. I would like that change.

For your example it would work well to postpone CmdlineEnter until
starting to wait for a character.

I assume CmdlineChanged would only be triggered after CmdlineEnter.

Although these changes seem like a good idea, I wonder if anything would
break.  Some plugin that depends on the autocmd events even when the
user is not typing the cmdline?

-- 
ARTHUR:   Ni!
BEDEVERE: Nu!
ARTHUR:   No.  Ni!  More like this. "Ni"!
BEDEVERE: Ni, ni, ni!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mg979** [comment]
I was trying to use this autocmd to check if the user left the command line without typing anything.
Maybe the autocmd could be activated on demand via `set something`? So you would do, for example:

    set cmdlineau

and somewhere else:

    au CmdlineLeave * call func() | set nocmdlineau

and the event wouldn't trigger at all if the setting is off.

**Comment by lacygoill** [comment]
Now that we have the pseudo-key `<cmd>` (since [8.2.1978](https://github.com/vim/vim/releases/tag/v8.2.1978)), I think the issue can be closed.  If we want the `Cmdline*` events to be fired, we can enter the command-line with `:`.  If we don't want them to be fired, we can enter the command-line with `<cmd>`.
