### ISSUE TITLE
Can not hide hit-enter when using timer

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#2906]
test.vim

```vim
function! Test(...) abort
  let m = "line1 11111111111\n"
  let m .= "line2 11111111111\n"
  echo m[:-2]
  let nr = getchar()
  redraw
endfunction
```

when run `call Test()`, you will not see `Press ENTER or type command to continue`
but when run `:call timer_start(2000, 'Test')`, the hit-enter will be shown

**Comment by wsdjeg** [comment]
when `:call timer_start(2000, 'Test')`, before the timer is running, just press `:` to goto cmdline mode, this issue is gone. and I have tested insert mode, also get same issue.

**Comment by brammool** [comment]
When typing commands on the command line, the hit-enter prompt is given when leaving the command line.  When a function echoes a message, the hit-enter prompt is given right away.

Anyway, it's not a good idea to output messages from a timer, it will interrupt whatever the user is doing.
This is not a bug, therefore closing.

**Comment by wsdjeg** [comment]
@brammool even if I use `set nomore` in this function , when call the timer, it still show me the hit-enter, I know use `echo` in timer is not good idea, but I think it is a issue though, It should not sow hit-enter when `set nomore`.

**Comment by brammool** [comment]
> @brammool even if I use `set nomore` in this function , when call the
> timer, it still show me the hit-enter, I know use `echo` in timer is
> not good idea, but I think it is a issue though, It should not sow
> hit-enter when `set nomore`.

The "more prompt" is for when the screen is filled with a message.
The "hit-enter prompt" is before a redraw clears a message that was just
displayed.

Without the hit-enter prompt the message would be immediately cleared,
since a timer callback can cause a redraw.  So a message without the
hit-enter prompt is useless.   If you don't want the hit-enter prompt,
then make sure there is no message.

An alternative, if you do want to do some kind of logging, write a
message to a buffer, which could be displayed in a window.

-- 
<Beeth> Girls are like internet domain names,
        the ones I like are already taken.
<honx>  Well, you can stil get one from a strange country :-P

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by wsdjeg** [comment]
> The "hit-enter prompt" is before a redraw clears a message that was just
displayed.
> since a timer callback can cause a redraw

I got it, thanks for your info.
