### ISSUE TITLE
Proposing better handling of defaults.vim

### ISSUE THREAD

**Issue by W4RH4WK** [vim/vim#2917]
Hey there,

There still seems to be some controversy about the include order of `default.vim`.

As far as I understand it, the problem is that configuration set by `default.vim` cannot be (simply) overwritten by the system-wide `/etc/vim/vimrc` file. In addition to this, `default.vim` is only sourced if the user does not have a `.vimrc` file located in her home directory.

I (and probably a bunch of other people) find this behaviour unintuitive and *invasive* which leads me to the following proposition:

Let Vim only source `defaults.vim` if neither `~/.vimrc` nor `/etc/vim/vimrc` are present.

This way, Vim will fall back to the defaults provided if *no* other configuration is found.

Each distro can decide whether to use `defaults.vim` by sourcing it in their `/etc/vim/vimrc` and whether it should override their settings or not.

This also removes the need for `skip_defaults_vim`.

**Comment by chrisbra** [comment]
I think this is a duplicate of #2042  and #2841

**Comment by W4RH4WK** [comment]
Both issues are certainly related, yet I don't think they really are duplicates. #2042 has been closed. We could close this one and add my proposal to #2042 if you think that would be better.

#2841 is more like a consequence of #2042 and would also be resolved by this.

**Comment by jamessan** [comment]
It sounds like you're proposing basically the patch that Christian's provided at https://github.com/vim/vim/issues/2042#issuecomment-332420140 which Bram essentially [dismissed](https://github.com/vim/vim/issues/2042#issuecomment-364498370) with "distributions shouldn't provide a system vimrc".

**Comment by W4RH4WK** [comment]
Indeed, I missed that when glancing over this issue. Nevertheless such duplicates will probably come it in future as it seems like lots of people have an issue with this.

Also, I don't think `/etc/vimrc` or `/etc/vim/vimrc` will vanish anytime soon --- and it probably shouldn't.

I condemn the decision that "distributions shouldn't provide a system vimrc". But if this is the way Bram wants to take, go head and close this as a duplicate. I'll be heading off to NeoVim then.

**Comment by nuko8** [comment]
I thought @jamessan 's point was primarily for those who have little choice but to rely on the settings provided by others; understandably, It's a pity that people suffer from what is not at their own choice.  However, if Neovim is a viable alternative to Vim for them, they seemingly have more discretion over how to resolve the issue than I imagined, though I'm not sure whether or not those who find it difficult to have their own `.vimrc` are easily permitted to install Neovim system-wide.  Now I'm wondering for whom the proposal is; for those who are effectively able to resolve the issue without the proposed change in accordance with their preferences, or for those who have no choice but to live with the given settings.

**Comment by jamessan** [comment]
Although the choice of ignoring the system vimrc does affect me (since I get to listen to Debian users complain about their system-wide settings being ignored), I _don't_ think that's the main problem.

Rather, I think the actual problem is that the way the new defaults were implemented is confusing to both old and new users.

The expected mechanism of overriding defaults by changing the option in your vimrc (whether it be the system or user) doesn't consistently work anymore.  For a system vimrc, it doesn't work because defaults.vim will still be loaded and therefore override the user's attempt at changing the default.  For a user vimrc, it will work but may have other side-effects due to disabling the loading of defaults.vim

The implementation also has a very narrow audience that will actually benefit from any updates, since defaults.vim is no longer sourced when a user creates their own vimrc.  This contributes to the confusion.  A new user who decides to customize Vim's behavior by creating their own vimrc now has a completely different behavior (in a negative way) than they did before creating the file.

This is in complete opposition to the prior behavior where creating a vimrc (even a blank one) would generally _improve_ the user experience by disabling `'compatible'`.

**Comment by jpmcneely** [comment]
Please see James' suggestions.  The newer behavior is NOT intuitive, and for many old-school users looks broken (30 years for me).  Personally, I would also add that on any system that uses vim for the invoked 'vi', the editor defaults should be  'compatible'.  Invoking 'vim' would seem better with all the bells and whistles.

**Comment by tonymec** [comment]
I came to Vim quite a time before `defaults.vim` was invented, so I suppose I'm among @jpmcneely 's «old-school users», yet for me nothing was broken. How come? Well, one of the lines near the top of my vimrc has long been `runtime vimrc_example.vim`. When the `defaults.vim` was introduced, the contents of the `vimrc_example.vim` were moved to it but the latter was not deleted: it became a wrapper, sourcing the `defaults.vim`. So now `:scriptnames` tells me
```
1. ~/.vimrc
2. /usr/local/share/vim/vim81/vimrc_example.vim
3. /usr/local/share/vim/vim81/defaults.vim
```
etc., while in Vim 6 or 7 `defaults.vim` wouldn't be named (it didn't yet exist, but its future code was part of `vimrc_example.vim`) and the rest was one line up in the list compared to what it is now.

Best regards,
Tony.

**Comment by tejr** [comment]
As a systems administrator for an office of Debian GNU/Linux users, `defaults.vim` is nothing but a mild annoyance. It does not improve anything for any of my users. Our office is almost completely vi users, but I am the only one who cares at all about Vim's specific extensions beyond a couple of people who know about using visual block mode for commenting stuff. They don't have vimrc files. If they did, they certainly wouldn't bother putting it on every server. They just log on to any given server, type `vi`, and start editing.

So, from their point of view, vi is broken in Debian 9. They might listen to me explain it if I tried, but they don't really care why. Most of them use 16-color PuTTY with dark backgrounds (i.e. the default), which means they get dark syntax highlighting colors that are hard to read because of how the `'background'` default is selected, and then notice "copy paste is broken too! Man, they really messed this release up!" . They do not care a whit for `'mouse'`.

If a user with no `.vimrc` types `vi`, I don't think Vim should ever (now, or in the future, with or without a system vimrc) do anything but start a `'compatible'` vi. It's just another thing to patch out with an `/etc/vim/vimrc.local` in our server setup. But at least applying the patch to skip loading it if a system vimrc file is present would fix things for this large and mostly-silent class of users who just want vi to work again.

**Comment by ilatypov** [comment]
~I agree with @jamessan that `/etc/vim/vimrc` (and its `/etc/vim/vimrc.local` friend) should be given a chance to override the default behaviour.  Using `-V9/tmp/vilog` and reviewing `/tmp/vilog` I could see that only `~/.vimrc` (or its presence) can override defaults.  For users without `~/.vimrc` such as the `root` user, the vi verbose log shows that `/usr/share/vim/vim81/defaults.vim` takes precedence as it is processed AFTER `/usr/share/vim/vimrc`.~

I now see @W4R's point about gutting the automatic inclusion of `defaults.vim` after `$VIMRUNTIME/vimrc`.  Can the former be just included first?  

The existing Debian needs `vimrc_example.vim` file as a template in `/etc/vim/vimrc.local` with the addition of the "let" statement stopping the hard-coded inclusion of `defaults.vim` **after** `/etc/vim/vimrc.local`,

```diff
 " Get the defaults that most users want.
 source $VIMRUNTIME/defaults.vim
+let g:skip_defaults_vim = 1
```

**Comment by travnick** [comment]
There is a bug in a logic or in a file name.
With current logic, the name of the file should be `destroy_global_config_with_this_one.vim`.

But looking at all the software I've used in my life, this is a bug in loading order.

If something is a default, then it's loaded at the very beginning, so anyone can use it or override a particular behaviour.

It may be hardcoded or may land as a default entry at the very beginning of `/etc/vim/vimrc`. So it's there by default, but admin is free to handle it in his own way if required.

Loading `default.vim` after the global one is a bug, nothing else.

**Comment by brammool** [comment]
I never liked allowing an admin playing ruler of the users, telling them how they should use Vim.  I would rather not load any system-dependent init file.  But some admins want to play god and want to do this, so Vim has historically supported it.

Whether the defaults.vim is loaded before or after the system init file is much more a practical question than a philosophical one.  The main reason the init file is loaded first is that it gives a chance of disabling the loading of the defaults.  Otherwise every time I add something to the defaults the admins would complain very loudly that they have to add something to their init file on thousands of systems.

Anyway, it's been like this long enough now to say it's not going to change.

**Comment by travnick** [comment]
First and foremost, admins are *responsible* for the system, they are about to set up the system in a way that it would be useful to (most of) the users. They are responsible for creating reasonable defaults. Is VIM *responsible* for any such system?
It's the admin responsibility, not the VIM one. So yes, admins are gods of the systems they maintain.

Software I know, is aware of this responsibility and uses proper hierarchy of configuration loading (top one is most important):

1. user config
2. system config
3. software defaults config

But VIM (by default) breaks this by overriding system config by its defaults. VIM plays god of all the systems, and here the VIM is the ruler of all the users and the admins - it behaves exactly in a way you do not like - it acts like that for all systems in the world where VIM is used.

The order mentioned above gives (by default) freedom to users to agree with system defaults or explicitly disagree by creating their own setup by creating a `.vimrc` file.
And there they can reload the `defaults.vim` on their own if they like to.

The order mentioned above gives (by default) freedom to admins to create system-wide defaults that fulfil users/company requirements of default VIM behaviour.

Fortunately, it's possible to fix that bug by placing @ilatypov configuration lines into `/etc/vimrc`.

Anyway, thank you for creating VIM, that's a good piece of software!
