### ISSUE TITLE
Python3.6 undefined symbol: PyTuple_Type

### ISSUE THREAD

**Issue by ghost** [vim/vim#2925]
This happens when just importing `subprocess` from inside vimrc like:
```vim
py3 <<EOF
import subprocess
EOF
```
I have build both python and vim in my home dir under .local

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/kon/.local/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: /home/kon/.local/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type
```
vim:
```
vim8.0 Included patches: 1-1850
```

python:
```
python3.6.5
```

system:
```
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

**Comment by lilydjwg** [comment]
This might be that your C extensions don't link to libpython3.6.so. I've seen this with third party extensions (like python-dbus, lxml, etc, esp. in Ubuntu). Maybe you didn't `--enable-shared` when compiling your Python?

If I guess right, your Vim is compiled with both Python 2 & 3 support. Their symbols conflict so they can't be put into the gloabl namespace, so they are made local. And libraries that don't link to libpython3.6.so won't find them.

**Comment by ghost** [comment]
i only compile vim with python3 support

you're right it seems to be something with where i install python, compiling python with `--enabled-shared` and setting `LD_LIBRARY_PATH=~/.local/lib` gives me a different error
```
Fatal Python error: PyThreadState_Get: no current thread
Vim: Caught deadly signal ABRT
Vim: Finished.
Aborted
```

**Comment by xuboying** [comment]
I met this same issue long time ago, and alwasys used system's python2 as workaround.
Now python2 is going phase out so I have to dig the issue.
Lilydgwg is correct, it seems python3's `libpython3.6m.a` not linked to vim during vim build.

By using `nm` command, PyTuple_Type can be found in the lib `libpython3.6m.a`
So the problem can be fixed by changing vim build parameter instead of python build parameter(the `--enable-shared` is causing more issues outside vim)

```
$ LDFLAGS=-L$HOME/.local/python3.6/lib LIBS=-lpython3.6m ./configure \
--enable-fail-if-missing \
--disable-perlinterp \
--disable-pythoninterp \
--enable-python3interp \
--with-python3-command=$HOME/.local/bin/python3.6 \
--disable-rubyinterp \
--enable-cscope \
--enable-gui=auto \
--with-features=huge \
--enable-multibyte \
--with-compiledby="$USER" \
--prefix=$HOME/.local/vim_py3.6
```

However, it is still needed to set a LD_LIBRARY_PATH for vim(ONLY) before vim starts, the PATH points to `$HOME/.local/python3.6/lib`, I'm not sure why this is needed.
Anyway this is samll patch for VIM only, not impact too much else. Surprise not found anyone menthion this. Hope this comment helps others.
