### ISSUE TITLE
Terminal cursor shape or color not correctly restored when closing a terminal

### ISSUE THREAD

**Issue by dpelle** [vim/vim#2942]
Cursor shape or colors is not correctly restored when killing a terminal.
This is unrelated to #2938 which is also about cursor color. 

Steps to reproduce:

1) start vim with 3 terminal windows:
```
$ vim --clean -c term -c term -c term
```
2) in the 1st (top) terminal, change the cursor color to red:
```
$ echo -ne "\033]12;red\007"
```
3) in the 2nd (middle) terminal, set the cursor color to green:
```
$ echo -ne "\033]12;green\007"
```
4) in the 3rd (bottom) terminal, set the cursor color to green:
```
$ echo -ne "\033]12;blue\007"
```
Observe that the cursor color is properly restored when
switching from one terminal to another (by clicking
in each terminal window for example). Good so far.

5) Now go in the 2nd terminal (with green cursor) and
press CTRL-D to close that terminal.

Observe that the cursor is now in the terminal where we
had set cursor color to blue, but the cursor color is actually
green (bug!).

The color cursor gets properly restored to blue when 
switching to the other terminal (the one with red cursor)
and then switching back to the other terminal where cursor
was meant to blue.

It's not specific about cursor color.  The same bug 
happens when different terminals have different cursor shape
or blinking attribute.

I can reproduce the bug with vim-8.1.10 at least in:
* xfce4-terminal 0.8.7.3
* xterm  (XTerm(330))

Interestingly, the bug does not happen with gvim (GTK3) i.e.
if I start vim with:
```
$ vim -f -g -c term -c term -c term
```

**Comment by brammool** [comment]
Dominique wrote:

> Cursor shape or colors is not correctly restored when killing a terminal.
> This is unrelated to #2938 which is also about cursor color. 
> 
> Steps to reproduce:
> 
> 1) start vim with 3 terminal windows:
> ```
> $ vim --clean -c term -c term -c term
> ```
> 2) in the 1st (top) terminal, change the cursor color to red:
> ```
> $ echo -ne "\033]12;red\007"
> ```
> 3) in the 2nd (middle) terminal, set the cursor color to green:
> ```
> $ echo -ne "\033]12;green\007"
> ```
> 4) in the 3rd (bottom) terminal, set the cursor color to green:
> ```
> $ echo -ne "\033]12;blue\007"
> ```
> Observe that the cursor color is properly restored when
> switching from one terminal to another (by clicking
> in each terminal window for example). Good so far.
> 
> 5) Now go in the 2nd terminal (with green cursor) and
> press CTRL-D to close that terminal.
> 
> Observe that the cursor is now in the terminal where we
> had set cursor color to blue, but the cursor color is actually
> green (bug!).
> 
> The color cursor gets properly restored to blue when 
> switching to the other terminal (the one with red cursor)
> and then switching back to the other terminal where cursor
> was meant to blue.
> 
> It's not specific about cursor color.  The same bug 
> happens when different terminals have different cursor shape
> or blinking attribute.
> 
> I can reproduce the bug with vim-8.1.10 at least in:
> * xfce4-terminal 0.8.7.3
> * xterm  (XTerm(330))
> 
> Interestingly, the bug does not happen with gvim (GTK3) i.e.
> if I start vim with:
> ```
> $ vim -f -g -c term -c term -c term
> ```

I can reproduce it.  Interesting...  I had trouble stepping through this
with the terminal debugger, since it also suffers from this problem.

Turns out that when switching buffers while inside terminal_loop() the
in_terminal_loop variable gets the wrong value.  It should bail out of
the loop in that case.

-- 
ARTHUR:    Be quiet!  I order you to shut up.
OLD WOMAN: Order, eh -- who does he think he is?
ARTHUR:    I am your king!
OLD WOMAN: Well, I didn't vote for you.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
