### ISSUE TITLE
Starting with some version the ++bad argument seem to have stopped working

### ISSUE THREAD

**Issue by lkintact** [vim/vim#2947]
Commands like `:edit ++bad=keep file.txt` (description at `:help ++bad`) work in Gvim ver. `8.0.586`, but don't starting with a later version. In particular, I didn't manage to find any commands in `8.1.0020` that would accept the ++bad argument, an "E474: Invalid argument" message is displayed.
(Not sure if it's a bug or the docs are a little outdated).

**Comment by chrisbra** [comment]
Yes, Patch 8.0.1660 broke it by unconditionally returning `FAIL`.

I think this patch fixes it:

```patch
commit 54a536a562be5ff5870f4ea7f03696ef8671d8b7 (HEAD -> master)
Author: Christian Brabandt <cb@256bit.org>
Date:   Wed May 23 23:04:46 2018 +0200

    Allow ++bad=keep argument again

    Patch 8.0.1660 broke it, since it would unconditionally return FAIL for
    the ++bad argument.

    Add the required return OK statement and also add a test.

diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index 82dd0491d..50e2beb7a 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -5318,7 +5318,9 @@ get_bad_opt(char_u *p, exarg_T *eap)
        eap->bad_char = BAD_DROP;
     else if (MB_BYTE2LEN(*p) == 1 && p[1] == NUL)
        eap->bad_char = *p;
-    return FAIL;
+    else
+       return FAIL;
+    return OK;
 }
 #endif

diff --git a/src/testdir/test_functions.vim b/src/testdir/test_functions.vim
index b76bc78e7..ff96ec442 100644
--- a/src/testdir/test_functions.vim
+++ b/src/testdir/test_functions.vim
@@ -532,7 +532,7 @@ func Test_getbufvar()

   " Open new window with forced option values
   set fileformats=unix,dos
-  new ++ff=dos ++bin ++enc=iso-8859-2
+  new ++ff=dos ++bad=keep ++bin ++enc=iso-8859-2
   call assert_equal('dos', getbufvar(bufnr('%'), '&fileformat'))
   call assert_equal(1, getbufvar(bufnr('%'), '&bin'))
   call assert_equal('iso-8859-2', getbufvar(bufnr('%'), '&fenc'))
```

**Comment by lkintact** [comment]
Thank you, unfortunately I lack the knowledge needed to apply the patch and can't tell if it fixes the issue.
I think I should add that the problem concerns all the `++bad` values ( 'X', 'keep' and 'drop'), not 'drop' only (which you might have thought judging by the `'Allow ++bad=keep argument again'` patch description line).

**Comment by tonymec** [comment]
To apply the patch:
1. Make sure that you have a clone of Vim's git or Mercurial source repository on your hard disk and that it is updated to the latest commit.
1. Make sure that the `patch` utility is installed on your system, with its executable in the `$PATH`
1. Make sure that the current directory is the top of that repository (the parent directory of src/, runtime/, etc.)
1. run `patch -p1 <patchfile` where `patchfile` is the filename (with directory) of the patch Christian gave
1. Compile and install Vim
1. (Optional) Run `patch -R -p1 <patchfile` from the top of the repository to remove the patch and get back to a faithful copy of the official source
1. See if your problem still appears
1. Come back here to tell us if it did or didn't.

See also:
- http://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
- http://users.skynet.be/antoine.mechelynck/vim/compile.htm (How to compile Vim on Windows). This page may be a little out-of-date, because I left Windows some time ago.
- http://users.skynet.be/antoine.mechelynck/vim/compunix.htm (How to compile Vim on Unix-like systems)

Best regards,
Tony.

**Comment by lkintact** [comment]
Thank you very much for the instruction and the links, Tony, I haven't tried them yet though :)
To other participants, sorry for digressing.
