### ISSUE TITLE
Terminal + Quickfix mode?

### ISSUE THREAD

**Issue by will133** [vim/vim#2955]
Is there a simple way to pipe the current terminal output into a quickfix buffer that you can use :cnext to jump to the line while the terminal is running?  I'm currently using AsyncRun for most of the async task but it seems like AsyncRun does not support interactive use.  It would be useful if you can run the test, go into a debugging session and has the ability to call :cnext and :cprev to move back and forth to different file locations.

**Comment by vim-ml** [comment]
Hi,

On Fri, May 25, 2018 at 2:14 PM, Will Lee <vim-dev-github@256bit.org> wrote:
> Is there a simple way to pipe the current terminal output into a quickfix
> buffer that you can use :cnext to jump to the line while the terminal is
> running? I'm currently using AsyncRun for most of the async task but it
> seems like AsyncRun does not support interactive use. It would be useful if
> you can run the test, go into a debugging session and has the ability to
> call :cnext and :cprev to move back and forth to different file locations.
>

Currently there is no built-in feature to directly feed the output from
the terminal to a quickfix list dynamically.  But you can feed a range
of lines from the terminal window in Terminal-Normal mode to a quickfix
list. You can follow these steps:

1. Press <C-W>N in the terminal window to enter Terminal-Normal mode.
2. Visually select a range of lines from the terminal window and execute
            :'<,'>cgetbuffer
    You can also run the above command by explicitly specifying the
    range (e.g 5,20)
3. This will create a new quickfix buffer with the selected lines.
4. To add to the current quickfix buffer, you can use the ":caddbuffer"
   command instead of the ":cgetbuffer" command.

- Yegappan

**Comment by chrisbra** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.
