### ISSUE TITLE
Bad layout behavior when change window layout after popup menu is shown

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3009]
I would like to show documentation of complete item on complete resolve (after user selected the complete item), and that could be done using TextChangedP, but when I tried to open a preview window, the window layout is broken:

* popup menu would be drawn in incorrect location
* Status line of preview window is not shown
* If you have split windows, the cursor would jump to wired position after completion

It could be tested by:

``` vim
set nocompatible
filetype plugin indent on
inoremap <C-l> <C-R>=MyComplete()<CR>

func! MyComplete()
  let suggestions = [{
        \"word": "foo",
        \}, {
        \"word": "bar",
        \}]
  call complete(1, suggestions)
  return ''
endfunc

autocmd TextChangedP * :call ShowPreview()

function! ShowPreview()
  execute 'pedit '.tempname()
endfunction
``` 

After open vim command like `vim -u test.vim` and start completion by type `<C-l>`, you will get
<img width="327" alt="screen shot 2018-06-14 at 1 26 52 pm" src="https://user-images.githubusercontent.com/251450/41393111-d82de232-6fd6-11e8-83f0-e29ae9527238.png">

The completion resolve is defined by [language server protocol](https://microsoft.github.io/language-server-protocol/ )

If vim could support change the info of complete item after pum visible this would no longer a problem, it would be much better if we have better alternative other than preview window for showing documentation.

Please consider fix.
Thanks.

**Comment by chrisbra** [comment]
I run Vim version 8.1 and 8.1.0055 using `vim --clean -u test.vim`, pressed i to enter insert mode and typed `<c-l>` and nothing happened.

**Comment by chemzqm** [comment]
@chrisbra start column should not be 0, I've fixed that.

**Comment by chrisbra** [comment]
I see. The problem is, when the popup is visible, the statuslines would not be updated:
https://github.com/vim/vim/blob/52d3aaeea4c85406f46e2051729e4f007f83b35e/src/screen.c#L6891-L6896

However, we can do a bit better. Since in update_screen, we know that the popup menu will be redrawn after the statuslines have been drawn, we could skip it, like this:
https://github.com/chrisbra/vim/commit/0e08d8dd38cf9cff67575c9f336b922d3d302860
See the description of the patch to know what it does and the remaining gotcha.
