### ISSUE TITLE
the 'ga' command outputs incorrect digraphs under certain circumstances

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3015]
1. Copy this text: `кириллица ъ` into a text file and save it in the cp1251 encoding.
2. Run `gvim -u NONE`, open the file, and make sure ` 'encoding'` is set to cp1251, that is the file encoding is auto-detected correctly.
3. Move the cursor over the `ъ` and hit <kbd>ga</kbd>. Gvim outputs `<ъ>  <|z>  <M-z>  250,  Hex fa,  Oct 372, Digr u'` while the digraph for `ъ` specified in `doc/digraph.txt` is `='`.

Perhaps this is relevant: while the description of the digraphs list containing `ъ` says "If your Vim is compiled with multibyte support and you are using a _multibyte_ 'encoding', Vim provides this enhanced set of additional digraphs" and cp1251 is _not_ multibyte, the correct digraph still works, that is <kbd>\<C-K\>='</kbd> produces a `ъ` in Insert mode.

OS: Win 7, 
Gvim: gvim_8.1.0055_x86.zip

**Comment by chrisbra** [comment]
I see what is happening. The digraphs character table defines the digraphs with the unicode value. The `ъ` in cp1251 value is 250. So Vim scans the digraph table for value 250 and outputs the digraphs for that character (which is a different character in the 8bit encoding cp1251 than in the utf-8 character). So you get the digraph character for the unicode character value 205, which happens to be: `'ú' U+00FA Dec:250 LATIN SMALL LETTER U WITH ACUTE (u') &uacute;`

I don't know how to fix this, because we would have to convert the current value from the current encoding) into the corresponding unicode value.

**Comment by tonymec** [comment]
If `'encoding'` had been set to `utf-8`, the digraph would have been output correctly, but then you would have had to either explicitly tell Vim the `'fileencoding'`, e.g. by reading it with `:e ++enc=cp1251 kirillica.txt`, or set that as default 8-bit `'fileencoding'` rather than the usual Latin1, e.g. with `:set fencs=ucs-bom,utf-8,cp1251`. Apparently multi-language Vim works best in UTF-8, even when reading and writing files in "national" 8-bit charsets, but then charset detection cannot be universal (I mean, Vim doesn't know how to tell different 8-bit charsets apart from each other).

Best regards,
Tony.

**Comment by lkintact** [comment]
I see. Thank you guys for replying and explaining.
