### ISSUE TITLE
Help doc update for terminal BufWinEnter autocommand

### ISSUE THREAD

**Issue by mckellyln** [vim/vim#3025]
terminal help shows this text:

After opening the terminal window and setting 'buftype' to "terminal" the
BufWinEnter autocommand event is triggered.  This makes it possible to set
options specifically for the window and buffer.  Example:
   au BufWinEnter * if &buftype == 'terminal' | setlocal bufhidden=hide | endif

But I found this au does not work, what does work for me is:

au TerminalOpen * setlocal bufhidden=hide

Is this correct ?  Should the help doc be updated ?

**Comment by chrisbra** [comment]
The BufWinEnter autocommand triggers to early, when the terminal window is created (e.g. the terminal is not setup completly when it triggers, so you command does not run). That's why we have the TerminalOpen autocommand. It should work the second time you enter the terminal however. If you have suggestions on how to improve the documentation, just mention it.

**Comment by brammool** [comment]
This was changed at some point, and I forgot to update the help.  I'll do that now:

After opening the terminal window and setting 'buftype' to "terminal" the
TerminalOpen autocommand event is triggered.  This makes it possible to set
options specifically for the window and buffer.  Example: >
   au TerminalOpen * if &buftype == 'terminal' | setlocal bufhidden=hide | endif
The <abuf> is set to the terminal buffer, but if there is no window (hidden
terminal) then setting options will happen in the wrong buffer, therefore the
check for &buftype in the example.
