### ISSUE TITLE
Length of translated strings (All, Bot, Top)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3029]
I got these strings they are 3 charaters long and displayed at the bottom right corner in Vim.
As a translator it could be nice to know if the strings have to be 3 charaters long but there are no comments.
Translating to "Alt", "Bot", "Ned" might be a little to cryptic.

    #: buffer.c:4719
    msgid "All"
    msgstr "Alt"
    
    #: buffer.c:4719
    msgid "Bot"
    msgstr "Nederst"
    
    #: buffer.c:4722
    msgid "Top"
    msgstr "Øverst"

**Comment by brammool** [comment]
> I dont see any comments in the po files for the translators.
> 
> I got these strings they are 3 charaters long and displayed at the bottom right corner in Vim.
> As a translator it could be nice to know if the strings have to be 3 charaters long.
> Translating to "Alt", "Bot", "Ned" might be a little to cryptic.
> 
>     #: buffer.c:4719
>     msgid "All"
>     msgstr "Alt"
>     
>     #: buffer.c:4719
>     msgid "Bot"
>     msgstr "Nederst"
>     
>     #: buffer.c:4722
>     msgid "Top"
>     msgstr "Øverst"

Longer strings are possible, but since they should fit in the space of
"50%" it works a lot better when they are three characters.

I would suggest to try it out: edit a long file and go to the start,
end, somewhere halfway.  And edit a short file to see "All".
Make sure the 'ruler' option is set.

-- 
hundred-and-one symptoms of being an internet addict:
83. Batteries in the TV remote now last for months.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
German uses `Alles` (All), `Ende` (Bot) and `Anfang` (Top). And I haven't heard any complaints yet. Those strings must have been there for years. I guess it is okay to have (slightly) longer strings.

**Comment by scootergrisen** [comment]
Looks like Vim hides the "Alt", "Bot", "Top" translations if there is less then 1 space between the numbers and the string.
If i open the vim.mo file and go to the end it says 553,2156-2238 which leaves very little room for the "Alt", "Bot", "Top" text.
But i guess thats not common.

**Comment by tonymec** [comment]
Maybe more common than you think.

I am presently editing a file with widely varying line lengths and a lot of Cyrillic in them (meaning UTF-8 characters of more than one byte and therefore "virtual column" differing from "column") and, like the "pseudo-default" 'statusline' value mentioned at line 7524 of options.txt, my custom one ends with %-14.(%l,%c%V%) %P (this is the value and not the :set instruction so the |option-backslash| is omitted before the space).
Putting the cursor at the end of one particularly long line gives me "5555,1496-1049 81%" which is one character longer than your example but still perfectly neat; though I admit that it leaves only 3 characters for the %P item before dropping it? or having it push the ruler leftwards? In case of problems, a custom statusline could always allocate a larger "minimum width" if desired; but I suppose that .mo files cannot change default option settings, so such a change would have to appear explicitly in the concerned user's vimrc.
Also, the problematic "long line" would have to be within one window height of the file's top, bottom, or both, in order to cause problems: elsewhere, the %P item is a 3-character percentage.

Best regards,
Tony.
