### ISSUE TITLE
en_GB.po and ja.euc-jp.po encoding

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3041]
en_GB.po:

    "Content-Type: text/plain; charset=ISO_8859-1\n"

My text editor says its "UTF-8".

ja.euc-jp.po:

    "Content-Type: text/plain; charset=euc-jp\n"

My text editor says its "ANSI".

**Comment by brammool** [comment]
> en_GB.po:
> 
>     "Content-Type: text/plain; charset=ISO_8859-1\n"
> 
> My text editor says its "UTF-8".

It's a 7 bit file, thus both are true.
 
> ja.euc-jp.po:
> 
>     "Content-Type: text/plain; charset=euc-jp\n"
> 
> My text editor says its "ANSI".

That's not an encoding name.

-- 
hundred-and-one symptoms of being an internet addict:
89. In addition to your e-mail address being on your business
    cards you even have your own domain.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tonymec** [comment]
Depending on how the charset is detected and on which subset of that charset is in use in the file, is is possible to see something other than what the author intended. For instance in Vim with `'fileencodings'` (plural) set to `ucs-bom,utf-8,latin1` which is typical for Western locales:
- Unicode files with BOM are correctly detected
- UTF-8 files are correctly detected even without a BOM
- Files containing only the characters of 7-bit US-ASCII will be detected as UTF-8 regardless of whether they were meant to be UTF-8, Latin1 or any other ISO 8859 charset, because all those charsets represent the 128 characters of US-ASCII the same way.
- Anything else will be detected as Latin1.

The first case is perfect, thanks to the BOM. The second case is also perfect. The third case doesn't harm as long as you don't use anything higher than 0x7F aka U+007F in the file's text. The fourth case is problematic for anything other than Latin1. If you know that a certain file is in euc-jp, you can open it correctly (assuming `'encoding'` is set to UTF-8) by typing
``` vim
:e ++enc=euc-jp /path/to/filename.ext
```
Similarly for any other charset. Also, if you have a file containing only the 128 characters of US-ASCII (or a subset of them) but you want to add in it some characters in the range 0x80 to 0xFF for some ISO 8859 encoding and save it as that particular encoding, you can read it first with the appropriate `++enc` (which will set `'fileencoding'` (singular) the way you want it), but if it is anything other than Latin1 aka ISO_8859-1, you wil have to repeat the `++enc` modifier at every later read of the same file.

With that same value of `'fileencodings'` (plural) mentioned above, there is a trick to make sure that a certain file will always be read as Latin1 and not as UTF-8: place in it in advance some non-ASCII bytes, for instance by underlining the main title with "divided by" signs (÷, 0xF7, digraph -: i.e. dash-colon), then make sure to save it as Latin1 (e.g. with `:w ++enc=latin1` followed by `:r` so that `:setlocal fenc?` will tell you that it is indeed Latin1.

Best regards,
Tony.

**Comment by k-takata** [comment]
> ja.euc-jp.po:
> 
> "Content-Type: text/plain; charset=euc-jp\n"
> 
> My text editor says its "ANSI".

It's obvious that your editor doesn't understand Japanese encodings at all.
I have to say that your setting of your editor is totally wrong for editing those files.

**Comment by scootergrisen** [comment]
I just checked them to see if i could find some errors or stuff like that.
