### ISSUE TITLE
`nnoremap <esc> <esc>:noh<cr>` causes vim to start in replace mode and arrow keys to type letters

### ISSUE THREAD

**Issue by dylan-chong** [vim/vim#3080]
`vim --clean +'nnoremap <esc> <esc>:noh<cr>'`

The mapping in the command mentioned above causes Vim to have the following two problems:

- Vim starts in replace mode
- scrolling with the mouse can cause random characters to be typed in

I am using vim-8.1.0100.high_sierra.bottle.tar.gz installed through homebrew

Interestingly, this problem does not happen on Mac Vim.

**Comment by chrisbra** [comment]
Yes, this confuses Vim because unfortunately, the `ESC` is used internally also to query some attributes from the terminal. See also here: https://vi.stackexchange.com/q/2614/71

**Comment by lacygoill** [comment]
Just for information, I think this issue, as well as #2216 and #2716 have all the same underlying cause; the one explained by @chrisbra.  There may be other issues with the same cause, I don't know.  Assuming this is something that could get fixed, maybe one single issue would make it easier to get updated on how to deal with the problem, as well as progresses which have been made to fix it.

OTOH, if we can't or don't want to fix this, then all these issues might as well be closed.

**Comment by lacygoill** [comment]
Actually, there is one difference here, since the sequence is sent by the terminal in response to some query on startup.  While in the other issues, the sequence is sent in response to a keypress on an arrow key.  But in both cases, the issue seems to be that `<Esc>` is wrongly parsed as an interactive keypress which can be remapped instead of being part of a byte sequence produced by the terminal.

Maybe I'm wrong though.

**Comment by brammool** [comment]
Mapping <Esc> is expected to cause problems, so don't do that.
