### ISSUE TITLE
GVim on Windows doesn't respond to scaling changes

### ISSUE THREAD

**Issue by bohrshaw** [vim/vim#3102]
I switch between two HiDPI displays and their scaling is different.
Unless I restart GVim, its scaling remains fixed after I switch displays.

**Comment by k-takata** [comment]
On Windows?
Right, Vim doesn't support per-monitor DPI now.
I haven't checked how to support it.

**Comment by k-takata** [comment]
> On Windows?

Ah, you wrote that in the title.

**Comment by Tetralux** [comment]
Suffer from this too, on Windows x64.

My primary 1440p monitor is good, my 4k secondary monitor blurs.

This can supposedly be fixed by calling `SetDPIAwareness(2)` at init time and then responding to the appropriate window message by scaling fonts, window size etc.

You can acquire the DPI of the screen your window was moved onto and the old DPI (usually 90 below 4k).
You should be able to use the difference to compute the scale factor.

I've never done it, but my 10 minute glance at it leads me to that.

**Comment by chrisbra** [comment]
how about a PR then?

**Comment by jazzdelightsme** [comment]
Documentation: https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows

**Comment by madewokherd** [comment]
Manually enabling GDI scaling works well, per https://vi.stackexchange.com/questions/16622/how-to-adjust-gvim-to-my-hidpi-display-scaling-on-windows-10, perhaps you could simply enable this in an application manifest?

**Comment by chrisbra** [comment]
so, how about a patch then?

**Comment by k-takata** [comment]
Enabling gdiScaling is just a workaround, I think.
The proper solution sould be to implement PerMonitorV2 support, but it might not be so easy.
