### ISSUE TITLE
vim unlinked python3 when the python3.6 updated to python3.7

### ISSUE THREAD

**Issue by WenT-Ethan** [vim/vim#3124]
Does someone know how to fix this?
![screen shot 2018-07-01 at 08 28 12](https://user-images.githubusercontent.com/40725981/42129771-be6572a8-7d09-11e8-9c1a-55422629a9f4.png)

**Comment by tonymec** [comment]
`This Vim cannot execute :py3 after using :python` means you tried to use both Python 2 and Python 3 interfaces in the same Vim instance. This doesn't work: you may compile Vim for both Python 2 and 3 but only dynamically (i.e. `+python/dyn +python3/dyn`) and you may use only one of them in any run of Vim.

Best regards,
Tony.

**Comment by WenT-Ethan** [comment]
First of all, thank you for your moments and answers.
I know what the errors mean, but I cannot fix it.  I tried to unlink the python2, the error still shows up, though.
Since MacOs already installed the python2 and it cannot be uninstalled.  Would you please teach me how to use only python3 run in Vim?

Thank you for your time and concern.
Best regards.
Wentong.


On Jul 1, 2018, at 09:19, Tony Mechelynck <notifications@github.com<mailto:notifications@github.com>> wrote:


This Vim cannot execute :py3 after using :python means you tried to use both Python 2 and Python 3 interfaces in the same Vim instance. This doesn't work: you may compile Vim for both Python 2 and 3 but only dynamically (i.e. +python/dyn +python3/dyn) and you may use only one of them in any run of Vim.

Best regards,
Tony.

**Comment by tonymec** [comment]
To only *use* Python3 in Vim, avoid invoking Python2 — the above errors are produced by scripts whose names are listed, apparently they are part of some "pymode" or "Python-mode" package which is not part of standard Vim. If you can find how to disable that, you can stop reading this message — unless you *want* to compile your own Vim with no Python2 interface.
To only *compile* Vim with Python 3 interface, configure it with `--disable-pythoninterp` and `--enable-python3interp`. If you still want dynamic Python you may use `--enable-python3interp=dynamic` but without Python2 this is not mandatory.

See also:
* https://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
* http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

AFAIK the above two HowTo pages also apply to compiling a non-GUI Vim or an X11 gvim on Mac OS X. For a native OSX GUI you should be using MacVim, see https://github.com/macvim-dev/macvim — and since I never used Mac computers I don't know the details.

Best regards,
Tony.

**Comment by WenT-Ethan** [comment]
Thank you for your kind advices, deeply.  😇
I will try it.

Best regards.
Wentong.


On Jul 2, 2018, at 11:44, Tony Mechelynck <notifications@github.com<mailto:notifications@github.com>> wrote:


To only use Python3 in Vim, avoid invoking Python2 — the above errors are produced by scripts whose names are listed, apparently they are part of some "pymode" or "Python-mode" package which is not part of standard Vim. If you can find how to disable that, you can stop reading this message — unless you want to compile your own Vim with no Python2 interface.
To only compile Vim with Python 3 interface, configure it with --disable-pythoninterp and --enable-python3interp. If you still want dynamic Python you may use --enable-python3interp=dynamic but without Python2 this is not mandatory.

See also:

  *   https://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
  *   http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

AFAIK the above two HowTo pages also apply to compiling a non-GUI Vim or an X11 gvim on Mac OS X. For a native OSX GUI you should be using MacVim, see https://github.com/macvim-dev/macvim — and since I never used Mac computers I don't know the details.

Best regards,
Tony.
