### ISSUE TITLE
Feature Request:  screen scroll autocmd

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3127]
According to codeLens resolve specification at https://microsoft.github.io/language-server-protocol/specification#textDocument_codeLens, I should do codeLens resolve request for the lines that currently visible, but I don't know when vim is scrolled without something like scroll autocmd.

CodLens feature makes it possible to show some additional information (like implementations and references) and code actions beside symbols.  CodeLines items should be resolved only when it's visible to improve performance.

**Comment by myitcv** [comment]
Noting also the discussion in https://groups.google.com/forum/#!msg/vim_dev/2M-JRAQkKPg/scg_V0_ZAgAJ

Specifically what I felt was related to that thread (and indeed this issue)

> The only thing I would suggest we consider at the same time is an 
event that is triggered pre/post viewport changes. And by viewport, I 
mean the information returned by getwininfo() (minus the variable 
key), along with the current window number. Current line number 
could/should be part of this. 
>
> My proposed use case here is an AST-based syntax highlighting. 
>
> I will note however that this would likely require some changes to 
matchaddpos/deletematch to make them more batch friendly. 
>
> In https://github.com/myitcv/govim/pull/24 I have simulated such a 
viewport changed event using timers (ideally I would have the new 
highlights be added in response to the pre viewport changed event). 
But the lag because of the multiple calls required to 
matchaddpos/deletepos over a channel start to become apparent.

**Comment by dstein64** [comment]
A `WinScrolled` event was added in #10102.
