### ISSUE TITLE
Gvim differentiates between CTRL-H and <BS> when it comes to mappings

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3131]
At `:help key-notation` several equivalents for keys are given, in particular it's specified that CTRL-H is equivalent to \<BS\>.

1. Run `gvim.exe -u NONE`
2. Execute `:set nocompatible`
3. Execute `:map <C-H> v`
4. Hitting <kbd>C-H</kbd> now enables Visual mode, but hitting <kbd>BS</kbd> doesn't.

If at step 3 the key or the equivalent from another pair (for example `<Tab>` and `<C-I>`, or `<CR>` and `<C-M>`) had been chosen, both would be mapped to `v`.

OS: Windows 7,
Gvim: gvim_8.1.0126_x86.zip

**Comment by brammool** [comment]
That keys are equivalent doesn't mean they are the same.  The default action (if configured properly) will have the same effect.  Whether Vim can distinguish BS and CTRL-H depends on the termcap, what the escape sequence for BS is.  The table doesn't cover these details.

**Comment by lkintact** [comment]
> The default action (if configured properly) will have the same effect.

The thing is,` <BS>` and `<C-H>` do have the same effect when not mapped, and that's what confused me - it's as if Gvim doesn't distinguish between the two when they aren't mapped, but does when they are.

**Comment by lkintact** [comment]
Thanks for the explanation. Taking into account Vim can sometimes distinguish between the two, perhaps `<C-H>` should be replaced with `<BS>` in this part of `doc/insert.txt`:
```
An example for using CTRL-G u:

	:inoremap <C-H> <C-G>u<C-H>

This redefines the backspace key to start a new undo sequence.  You can now
undo the effect of the backspace key, without changing what you typed before
that, with CTRL-O u. 
```

**Comment by nuko8** [comment]
One of the important roles that GVim has played so far is to give full-fledged text rendering to Vim in a platform-agnositc way, especially for the case where a fully capable virtual terminal emulator may not be available to the user.  

Recall that there're a lot of parameters to render text: To name a few, font family, font weight, font slant, font width, font spacing, and foreground and background colors for each glyph to draw with (IOW, the colormap supported by the underlying windowing system---that of monochrome, gray scale, static color or true color of 15, 16 or 24 bpp).  With this list, one can easily imagine that, when GVim was born about two decades ago, there was no such a terminal emulator that was as capable of making full use of those parameters for the purpose of rendering text as some of the latest terminal emulators are nowadays, and this is a historical fact.  Actually, that was the place where GVim came in, i.e., giving full-fledged text rendering to Vim in a platform agnostic way; that GUI is not only about mouse click or drag on Vim, pull-down menus on it, or popup dialogs over it.

Naturally, what people expected out of GVim those days was that it worked just like they used Vim on a fully capable, yet imaginary virtual terminal emulator.  As such, it was rather natural for them to think `<C-H>` is semantically identical to `<BS>` unless they remapped them with their explicit intention in order to take advantage of GUI where keys can be mapped more extensively than CLI.

So, for such GVim, it might be rather pointless to distinguish `<C-H>` from `<BS>` rigorously only because it can do if necessary.

That said, the importance of the role mentioned above gets less and less these days as virtual terminal emulators are making good progress in text rendering.  Someday, someone might  throw off the yoke and let GVim go for its own sake...

**Comment by lkintact** [comment]
Thank you for such an interesting Gvim historical background, nuko8.

My idea behind the suggestion to replace `<C-H>` with `<BS>` in the example above was to avoid the possible confusion one may experience when they try the example and exectue `:inoremap <C-H> <C-G>u<C-H>` only to see no effect on the action of the backspace key, while the description of the example says "this redefines the backspace key" (which is exactly what happened to me). Sorry for not expressing it in the previous post.

**Comment by tonymec** [comment]
@nuko8 : ah, interesting.

I feel though that gvim is still one step forward, so to speak, of terminal emulators. Let's count the ways:
* It can do 16777216-color rendering out of the box.
  * Maybe some terminals can too but it isn't obvious how to get them to. `'termguicolors'` (a rather new option IIUC) helps there.
  * On 256-color terminals I use CSApprox to make the Vim-in-console look like gvim (as closely as possible) rather than the opposite. The consideration of "safe" colors helps here: any color whose red, green and blue components, taken separately, are a multiple of 0x33 can be rendered exactly on a 256-color display.
* It can do bold, italic, underlined, and even wavy underlined out of the box.
  * The terminals I use cannot do italic AFAIK (though I've heard there are some that can), and I've never heard of one with wavy underline capability.
* Choosing a font, and configuring the editor to use it always, is remarkably easy in gvim (with a "modern" GUI including, but not limited to, Windows, Mac OS (MacVim?) and GTK) once you know how to do it (with `:set guifont=*`, or with `:set guifont=something` once you know the "something" to use, i.e. the particular font you want).
  * I know how to set a font in konsole but in xterm and mlterm I haven't yet bothered to find out if it is possible and how — and their default fonts are rather ugly.
* It can display any Unicode codepoint, provided only that your configured font has a glyph for it and that you set `'encoding'` to UTF-8 at startup.
  * Even in a Unicode locale — let's say `en_GB.UTF-8` — it is not always obvious to display non-Latin scripts in a terminal. The Linux non-X console is particularly troublesome in that respect AFAIK, but even in xterm-compatible terminals I have problems.
* It can identify the keys you hit without having a terminal emulator interfering with it in addition to the X11 layer.
  * This one is rather obvious. I suppose that the X11 layer (or the Mac or Windows equivalent) is unavoidable in gvim, but it is a fact that it can get, and tell apart, some keys and key combos which Vim-in-console doesn't get or cannot tell apart. You mentioned the case of `<BS>` vs. `<Ctrl-H>` but some terminals preempt quite a lot of key combos for their own use so that a program running in them never sees them. In a vimrc for both gvim and Vim-in-console it seems that the safest keys to use as the `{lhs}` of mappings without "stealing" Vim key bindings are most `<Fn>` keys, all `<Shift-Fn>` keys (`<Ctrl-Fn>` keys may or may not be available depending on the OS), and (depending on the keyboard layout, and in Normal mode only) non-ASCII "printable" keys (my Belgian keyboard has £ µ ² ³ and the accented keys of the French language, plus quite a lot of `AltGr` combos if you know how to get them, see http://users.skynet.be/antoine.mechelynck/other/keybbe.htm — however in practice I don't use these `AltGr` combos for mappings, only to produce "foreign" letters in Insert mode).
* However, to be complete, AFAIK there is one capability which gvim lacks, but where Vim-in-console can avail itself of the capabilities of a well-chosen terminal: true bidi. gvim can do either LTR or RTL but not both in the same window, while Vim running in mlterm can let the terminal handle bidirectional display, allowing LTR and RTL words to be displayed correctly even when intermixed in a single text — let's say a text in Latin script with Hebrew and/or Arabic words in it, or the opposite, or even Arabic text (RTL) with numbers in either "Western" or "Arabic-Indic" digits (both of which are LTR even in Arabic). For my uses, and by comparison to the above, this bidi capabililty (when running in mlterm) doesn't make Vim-in-console superior to gvim, it just has to be kept in mind when writing bidi text.
* And there is one thing which is extremely difficult or impossible to get in any monospace-oriented text, not only in Vim or gvim but also in all the terminals I know about: Indian-subcontinent scripts with their complex rules about character ordering and display.

Best regards,
Tony.
