### ISSUE TITLE
Tutor translation for both zh_CN, zh_TW and zh

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3136]
When having both zh_CN and zh_TW translations does it make sense to also have zh translation (without county code)?

runtime/tutor/:

    tutor.zh.big5
    tutor.zh.euc
    tutor.zh.utf-8
    tutor.zh_cn.utf-8
    tutor.zh_tw.utf-8

**Comment by chrisbra** [comment]
Is this an actual bug you are reporting here?

**Comment by k-takata** [comment]
Unlike en_US and en_GB, zh_CN and zh_TW use different characters.
Having `tutor.zh` might not be so useful. (`tutor.zh.utf-8` is a copy of `tutor.zh_tw.utf-8`, though.)

**Comment by tonymec** [comment]
Shouldn't there be also a `zh_HK` version? Or is that the same as one of the other two specific regions? Or maybe *that* is what plain `zh` is meant to be? Of course, as long as there isn't some native user of Hong Kong Chinese (some form of Cantonese, IIUC?) willing to translate into it, and maintain that translation, there's nothing much we Europeans can do…

**Comment by lilydjwg** [comment]
Hong Kong Chinese should be OK with zh_TW, although some wording may be different. Cantonese is `yue` or `yue_HK`, not `zh_HK`. Basically Hong Kong people speak Cantonese but write in Traditional Chinese formally.

I don't think the `zh` ones are very useful though. I'm not sure what `zh` should be used for because there are two kinds of Chinese characters. Vim can provide `zh_CN` as fallback for `zh_SG` and `zh_TW` for `zh_HK`.

**Comment by scootergrisen** [comment]
If tutor.zh.utf-8 is a copy of tutor.zh_tw.utf-8 then i would delete tutor.zh.utf-8.

**Comment by nuko8** [comment]
They say that, broadly speaking, Chinese consists of two different, yet closely related, language systems, Mandarin and Cantonese of which difference is more than dialect.  In addition, there're two different writing systems in Chinese characters, i.e., traditional one and simplified one. (Correct me if I'm wrong.)

So, at least, there're always four different possible ways to display a single Chinese sentence on Vim, though Vim itself doesn't know about which Chinese variant is used.

What is more, as is so often the case in cultural comparison, there can always be sensible issues causing endless dispute.  So, I think we should leave the issue to Chinese people themselves to settle because the change seemingly needs to be done most meticulously.   Fortunately, they seem to be satisfied with the status quo for now.   Then, why do we ask them for the change?

**Comment by k-takata** [comment]
> Fortunately, they seem to be satisfied with the status quo for now. Then, why do we ask them for the change?

Agree. Closing.
