### ISSUE TITLE
tutor.lv and tutor.da is using UTF-8 encoding

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3138]
https://github.com/vim/vim/blob/master/runtime/tutor/tutor.lv seem to be in UTF-8 and there is no tutor.lv.utf-8

If tutor.[ll].utf-8 should use UTF-8 encoding then what should tutor.[ll] use?

**Comment by brammool** [comment]
> https://github.com/vim/vim/blob/master/runtime/tutor/tutor.lv seem to be in UTF-8 and there is no tutor.lv.utf-8
> 
> Same for tutor.da.
> 
> If tutor.[ll].utf-8 should use UTF-8 encoding then what should
> tutor.[ll] use?

This is not totally consistent.  These days using utf-8 as the default
should be OK, it will work on most systems.

Otherwise, it's handled in tutor.vim.  Thus if there is only one tutor
available, and the current 'encoding' doesn't work for it, then it
should fall back to the English version.


-- 
Did you ever see a "Hit any key to continue" message in a music piece?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by scootergrisen** [comment]
Not so much fun for lv translator to spend time on translation just to have it fallback to english.

**Comment by scootergrisen** [comment]
If the translation is in menu_[ll].utf-8.vim.
And menu_[ll].latin1.vim says:

    source <sfile>:p:h/menu_[ll].utf-8.vim

Are the translation then not converted to UTF-8?

**Comment by scootergrisen** [comment]
What controls which file is loaded? latin1 or utf-8.
It seems latin1 is loaded when both are there but why?

**Comment by brammool** [comment]
> What controls which file is loaded? latin1 or utf-8.
> It seems latin1 is loaded when both are there but why?

Look in tutor.vim


-- 
hundred-and-one symptoms of being an internet addict:
174. You know what a listserv is.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I suppose this can be closed?

**Comment by k-takata** [comment]
I found that the command `vimtutor lv` failed to find `tutor.lv`.
I think that `tutor.lv` should be renamed to `tutor.lv.utf-8`, and `tutor.vim` needs to be adjusted for that.
I will create a PR later.
