### ISSUE TITLE
Suggestions for .1 files (man)

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3169]
I translated 3 of the files for man (files ending with .1) and here are a few suggestions for the source files (english).

In vim.1 and vimdiff.1:
This makes the text bold but also the "." becomes bold.

    .B Vim.

Perhaps this is better so that "." does not become bold?

    .B Vim\c
    .\&.

In vim.1:

    Should be a terminal known
    to

Change to:

    Should be a terminal known to

In vim.1:

    Start in read-only mode.  You will be protected from writing the files.  Can
    also be done with the "\-R" argument.

Change to:

    Start in read-only mode.  You will be protected from writing the files.
    Can also be done with the "\-R" argument.

In vim.1:

    {command} will be executed after the
    first file has been read.

Change to:

    {command} will be executed after the first file has been read.

**Comment by tonymec** [comment]
YMMV, but my writing custom is to include boundary punctuation in bold or italic text, but not in underlined text.

I suppose the rest are due to interference between continuous paragraphs and the manpage width. Now remember that the width is not necessarily 80 characters, man reformats its output according to the character width of the window where it will be displayed. For instance my konsole terminal is 174 columns by 63 lines and manpages are displayed there in justified paragraphs across the whole width (minus a right margin of maybe 6 characters). OTOH my text-only non-X11 Linux console (on Ctrl-Alt-Fn, 1<=n<=6) has 160 columns by 64 lines, and by displaying the same manpage there (I ran "man man" in both terminals) I can see that the paragraphs are still justified but to a slightly narrower text width even though the right margin is no more than 3 characters.

Breaking paragraphs in the middle will produce "short paragraphs" which won't be justified. (Joining lines which ought to belong in a single paragraph is all right.)

Best regards,
Tony.

**Comment by k-takata** [comment]
Fixed in https://github.com/vim/vim/commit/fd35811ca528de7612f9571bce20ef4c392fe5f7. Closing.
