### ISSUE TITLE
`mouse=a` option and mintty

### ISSUE THREAD

**Issue by keighrim** [vim/vim#3174]
Originally reported to mintty project. (mintty/mintty#782)
<hr>

Using mintty as the terminal emulator (on the Windows), I found vim could be mis-interpreting mouse input to move window focus to the terminal. When I move the window focus by a mouse click to mintty running vim (from any other app), vim scrolls three lines up (just like "3&lt;c-y&gt;"). 
I found that `mouse=a` option is the cause, and this doesn't happen in vim in tmux in mintty. 
The terminal type of mintty is set to `xterm-256color`.

**Comment by mintty** [comment]
Mintty 2.8.2 introduced a new feature to prevent accidental text selection on mouse-click window activation by suppressing the first mouse event after focussing a window. However, it fails to suppress the mouse release event too. While this is subject to improvement, 
vim should not interpret a singular mouse release event as a scroll-down action.

**Comment by brammool** [comment]
> Mintty 2.8.2 introduced a new feature to prevent accidental text
> selection on mouse-click window activation by suppressing the first
> mouse event after focussing a window. However, it fails to suppress
> the mouse release event too. While this is subject to improvement, 
> vim should not interpret a singular mouse release event as a
> scroll-down action.

Problem is that some terminal emulators use this code for the scroll
wheel.  Vim depends on the terminal to work properly, otherwise it's
impossible to decode the mouse events.

All this is caused by trying to fit all possible states in just a few
bits in one byte.  And different terminal emulators doing that in
different ways.  Nothing Vim can do about that.

For these bug reports it's useful to have the actual byte stream that
Vim gets.

I suggest that when you use mintty you set $TERM to "mintty".
Then we could check for the specific codes that this terminal emulator
sends.  Using something like "xterm" will cause trouble, like you
noticed.

-- 
hundred-and-one symptoms of being an internet addict:
214. Your MCI "Circle of Friends" are all Hayes-compatible.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mintty** [comment]
Hmm, I vaguely remember some very tricky quirks in the mined editor to tell these cases apart (so there's not quite nothing that could be done). But mintty shall tune behaviour then.
A curious question however is by what criteria does vim use a different mouse mode in mintty than in xterm (both having set TERM=xterm)?

**Comment by brammool** [comment]
> Hmm, I vaguely remember some very tricky quirks in the mined editor to
> tell these cases apart (so there's not quite nothing that could be
> done). But mintty shall tune behaviour then.
> A curious question however is by what criteria does vim use a
> different mouse mode in mintty than in xterm (both having set
> TERM=xterm)?

What makes you think it's different?  For xterm there is the code to
request the escape sequences from the terminal, but I don't think that
changes anything for mouse codes.  And you can switch the mouse into a
different mode (e.g. to avoid the column limit).  But it's not like Vim
detects mintty and does something different then.  There are a few
checks for when $TERM is xterm but it's not really an xterm, since users
have this habit of calling anything an xterm and then complain when
something doesn't work.

-- 
'Psychologist' -- Someone who looks at everyone else when
an attractive woman enters the room.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mintty** [comment]
> > A curious question however is by what criteria does vim use a different mouse mode in mintty than in xterm (both having set TERM=xterm)?

> What makes you think it's different?

I can either monitor the actual mouse codes after killing (-9) an application, or take a terminal log file.
Which I did, and in xterm, vim sets mouse modes 1002 (button-event mode) and 1006 (SGR format mouse report mode), while in mintty it only sets mode 1000. So there must obviously be something by which vim decides to restrict mintty from its capabilities, probably after requesting secondary device attributes, for which the escape sequence is also in the log. As mintty supports all mouse modes (except tracking mode 1001), please fix this.

**Comment by brammool** [comment]
> > > A curious question however is by what criteria does vim use a different mouse mode in mintty than in xterm (both having set TERM=xterm)?
> 
> > What makes you think it's different?
> 
> I can either monitor the actual mouse codes after killing (-9) an
> application, or take a terminal log file.
> Which I did, and in xterm, vim sets mouse modes 1002 (button-event
> mode) and 1006 (SGR format mouse report mode), while in mintty it only
> sets mode 1000. So there must obviously be something by which vim
> decides to restrict mintty from its capabilities, probably after
> requesting secondary device attributes, for which the escape sequence
> is also in the log. As mintty supports all mouse modes (except
> tracking mode 1001), please fix this.

Different behavior depending on a terminal type must be specified in
terminfo, not built into the binary.

Now, I realize terminfo is lacking features, I'm still hoping someone
can work on that, instead continuously adding hacks to Vim to work
around 'term' being set to "xterm" while it's not actually an xterm.

Another solution is if everybody stops using all these weird terminal
emulators and just use xterm.  I suspect that won't happen.

I have no idea where your specific problem is coming from, you'll have
to do some debugging.

-- 
hundred-and-one symptoms of being an internet addict:
222. You send more than 20 personal e-mails a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mintty** [comment]
> Different behavior depending on a terminal type must be specified in terminfo, not built into the binary.

That is the theory, not the practice. It has been common for decades to reuse existing terminfo entries, mainly because it is hardly feasible to get a new entry deployed to wide-spread heterogeneous systems, which is a deficiency of the terminfo mechanism.

> Now, I realize terminfo is lacking features, I'm still hoping someone can work on that, 

I am not aware that any terminfo additions would have been made recently, so I wouldn't expect anything here.

> instead continuously adding hacks to Vim to work around 'term' being set to "xterm" while it's not actually an xterm.

I maintain an editor myself and I know this is a nuisance, but it's all that can be done to satisfy (and sometimes calm) users.

> Another solution is if everybody stops using all these weird terminal emulators and just use xterm. I suspect that won't happen.

No, and you may understand that I deny this claim. I'd counter-claim that mintty is the most compatible to xterm among them, and it runs on Windows without needing X11, which is a real value-add.

> I have no idea where your specific problem is coming from, you'll have to do some debugging.

I'll get back when I've found the time. I thought you would be familiar with the respective code areas; any hint where to look?

**Comment by keighrim** [comment]
As mintty fixed this (mintty/mintty#782), I'm closing the issue.
