### ISSUE TITLE
vim language

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#3183]
Please allow vim language to be set in vimrc, for menus, error messages etc.

Currently, due to admin limitations on my windows machine, I'm running vim in many different terminals and configurations, so each time I get error messages or menus in italian, while I want them to be in english.

I've tried this solutions, but there is always some kind of permutation of terminal - update - os - permissions that make this setup fail.
https://stackoverflow.com/questions/126853/how-do-i-set-the-ui-language-in-vim

**Comment by k-takata** [comment]
The language can be set in vimrc.
However `:lang en_US` might not work on Windows. You can use `:lang C` or `:lang English` instead.

**Comment by g-i-o-r-g-i-o** [comment]
I've got windows, I've got linux and cygwin, and each one requires a different and confusing setting that requires a lot of experimentation. I've solved this problem by erasing the localization files. Thanks for the suggestions anyway.

**Comment by tonymec** [comment]
In my experience, `language messages C` works only on Unix-like systems, or at least that was the case when I was on Windows (the last time I was, it was on XP SP4). I've long been using the following snippet with no problems, but if in the meantime Windows behaviour has changed, the line to adjust is of course the one just before the `endif`.
```vim
if has('unix')
    language messages C
else " assume Windows
    language messages en
endif
```
IIRC this is one of the few settings which must come in your vimrc before it sources the `vimrc_example.vim` (which in recent Vim distributions just sources the `defaults.vim` but the latter was added recently, taking over what the former used to do). This is so that it will already be set when the `menu.vim` gets sourced.
If in addition you have a Cygwin-only Vim (as distinct from a native-Windows Vim "cross-compiled" by Cygwin or MinGW gcc) you might, if necessary (but I don't think it is), refine this code snippet by testing also for `has('win32unix')`. The placement of that test before or after `if has('unix')` might make a difference. For Mac OSX (which is a Unix-like OS), the `if has('unix')` block ought to set the required setting.

Best regards,
Tony.

**Comment by k-takata** [comment]
> In my experience, language messages C works only on Unix-like systems,

Incorrect. It works on Windows as I said in my previous comment, ~~and `language messages en` doesn't~~.

**Comment by k-takata** [comment]
For `menu.vim`, see also the following part in the help:
https://github.com/vim/vim/blob/6259e5769dd50d8a3b5b99f553bab34ff5c8a6ce/runtime/doc/gui.txt#L513-L516

Anyway, I think this is a user question rather than a bug report or feature request. Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. Closing.

**Comment by tonymec** [comment]
Well, then it has changed. On XP SP4, `language messages C`, which works on Unix, gave me an error on Windows, while `language messages en` was, **at that time**, the correct setting to override the default which, on the Windows system I had then, was `French_France.1252` or some such.

If by now `language messages C` works even on Windows, then I suppose you can use just that and not test for OS type anymore. Another possibility would be to use a try-catch construct (which didn't exist yet when I started using Vim regularly) as follows:
```vim
try
    language messages C
catch
    language messages en
endtry
```
or similar.

Best regards,
Tony.

**Comment by k-takata** [comment]
Sorry, there is a mistake in my message.
`:lang en` doesn't work on Windows 10, but `:lang mes en` does work.
Both `:lang C` and `:lang mes C` work on Windows 10.
