### ISSUE TITLE
Vim doesn't recognize tags with the minus ("-") symbol under some circumstances

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3207]
1. Create a *.txt file with these contents:
```
|tag|
|tag-minus|
|another-one|
*tag*
*tag-minus*
*another-one*

vim:filetype=help

```
2. Open the file and generate the help tags file with `:helptags .`
3. `|tag|` works - hitting <kbd>Ctrl</kbd>+<kbd>]</kbd> on it moves the cursor to `*tag*`.
`|tag-minus|` doesn't quite work - hitting <kbd>Ctrl</kbd>+<kbd>]</kbd> moves the cursor to `*tag*` when it's on the "tag" part and emits the `E426: tag not found: minus` error when it's on the "minus" part.
`|another-one|` doesn't work at all, emitting E426 errors for "another" or "one" depending on the location of the cursor.

When browsing Vim help files however, tags with hyphens work with no problems, for example  <kbd>Ctrl</kbd>+<kbd>]</kbd> on `|set-options|` at `:help options` moves the cursor to `*set-options*`.

OS: Windows 7,
GVim: 8.1.0186

**Comment by tonymec** [comment]
Are you sure you reloaded the file between creating and testing it, in order to take the modeline into account (and make Vim realize that its `'filetype'` is "help")?

If you are, try the following with the active cursor in the file in question:
```vim
:setl isk?
```
On my system, for most helpfiles the answer is
```
  iskeyword=!-~,^*,^|,^",192-255
```
but in `help.txt` (e.g. just after hitting `F1`) the answer is
```
  iskeyword=!-~,^*,^|,^"
```
because that helpfile has a slightly different modeline than all the others.

This is IIUC in keeping with the following sentence found at `:help 'iskeyword'`:
```
	For a help file it is set to all non-blank printable characters except
	'*', '"' and '|' (so that CTRL-] on a command finds the help for that
	command).
```

Best regards,
Tony.

**Comment by chrisbra** [comment]
as mentioned, check the 'iskeyword' setting. 
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. We cannot provide individual help here. Closing.

**Comment by lkintact** [comment]
@tonymec Thank you for the explanation.
@chrisbra I realize it's a bug tracker and only opened the issue because I was sure it's a bug. Sorry, should have spent more time on exploring the docs.
