### ISSUE TITLE
hidden terminal buffer type

### ISSUE THREAD

**Issue by coot** [vim/vim#3278]
When executing `:term ++hidden ls`, the `buftype` of the newly created terminal buffer is not set to `terminal`.

**Comment by coot** [comment]
The way to reproduce the issue:
```
:term ++hidden ls " or run some long running job, like http-server
```
If I do `ls` to get the buffer number and then `echo getbufvar(bufnr, "buftype")` I get "terminal"; but when I open the buffer with `:sbuffer` or `:buffer` commands `setl buftype?` shows that it was the `buftype` was reset to empty string.

**Comment by brammool** [comment]
Marcin Szamotulski wrote:

> The way to reproduce the issue:
> ```
> :term ++hidden ls " or run some long running job, like http-server
> ```
> If I do `ls` to get the buffer number and then `echo getbufvar(bufnr, "buftype")` I get "terminal"; but when I open the buffer with `:sbuffer` or `:buffer` commands `setl buftype?` shows that it was the `buftype` was reset to empty string.

This is correct.  When the job has finished the 'buftype' is reset,
because the buffer is no longer running a terminal.  You see the output
of the terminal.

However, using "cat" instead of "ls", the terminal is still running.
I can see that 'buftype' is then reset as well, which is wrong.
It happens because when the buffer is hidden the options are not
completely set yet, that happens when it enters a window.  And then
'buftype' is reset.

-- 
BLACK KNIGHT:  Come on you pansy!
    [hah] [parry thrust]
    [ARTHUR chops the BLACK KNIGHT's right arm off]
ARTHUR:        Victory is mine!  [kneeling]
               We thank thee Lord, that in thy merc-
    [Black Knight kicks Arthur in the head while he is praying]
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
