### ISSUE TITLE
terminal ++close ++hidden echos error

### ISSUE THREAD

**Issue by coot** [vim/vim#3287]
Whe I run:
```
:terminal ++close ++hidden ls
```
I get an error (doubled)
```
E813: Cannot close autocmd window
E813: Cannot close autocmd window
```

**Comment by coot** [comment]
I've been using this as a feature, to get notified that the terminal job has finished running, but there should be a better way for that.

**Comment by brammool** [comment]
Marcin Szamotulski wrote:

> I've been using this as a feature, to get notified that the terminal
> job has finished running, but there should be a better way for that.

That's not what error messages are for :-).

Problem is that unloading the terminal buffer requires putting that in a
window, otherwise autocommands may not work.  If there is only one
window then the window would be closed.  That's not what we want.

Let's see if it works if we just prevent the window from closing.

-- 
It's not hard to meet expenses, they're everywhere.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mikeboiko** [comment]
@brammool, I get the same error when running ":term ++close <cmd>" on async job, when I switch tab and then the job completes while I'm not focused on the original tab. I don't get the error is I'm focused on another window in the original tab of the async job. Should I open another issue, or is this the expected behavior?

My :version is
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2019 14:31:35)
Included patches: 1-1467

Thanks!

**Comment by brammool** [comment]
Please create a new issue with reproduction steps.  A quick test with "sleep 10" did not reveal the problem.
