### ISSUE TITLE
unnamed register bug when setting 'clipboard'

### ISSUE THREAD

**Issue by lucianposton** [vim/vim#3323]
If `'clipboard'` is set such that it contains both `autoselect` and `unnamed` (or both `autoselectplus` and `unnamedplus`), `v_p` does not use the unnamed register as expected (see `put-Visual-mode`). Instead, it seems to replace the visually selected text with the visually selected text (effectively doing nothing).

For example, suppose you have the following text and your cursor (indicated by `|`) is in the first word,

```
fo|o bar
```

if you press `yiw`, the `"` register will contain `foo` as expected e.g.

```
:reg "
--- Registers ---
""   foo
```

Now you move the cursor to `bar`,

```
foo ba|r
```

and now you press `viwp`, you expect `bar` to be replaced with the `"` register i.e. the word `foo`, but instead, `bar` is replaced with `bar`, seemingly doing nothing.

**Comment by tonymec** [comment]
IMHO this is expected. When you selected `bar` the effect of `autoselect,unnamed` was to put your new selection into both the system clipboard and the unnamed register. Therefore the unnamed register does not contain `foo` anymore. To replace the newly selected text with the previous selection (the text you previously deleted), you should IIUC have "put" from the small delete register (since the delete was less than one line):

`viw"-p`

Morality: You cannot keep your cake and eat it too.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. Sorry, after a yank it is not the small delete register but register zero: `viw"0p`

Best regards,
Tony.

**Comment by lucianposton** [comment]
Thanks for the clarification. Upon re-reading the descriptions of `autoselect` and `unnamed`, I see how this is the expected behavior.
