### ISSUE TITLE
When editing HAML files, the `expandtab` options shouldn't be always set

### ISSUE THREAD

**Issue by manueljacob** [vim/vim#3384]
Even if I set the `noexpandtab` option for HAML files in `.vim/after/ftplugin/haml.vim`, the `expandtab` option is always set when opening HAML files. The reason is that `$VIMRUNTIME/indent/haml.vim` contains a line `setlocal autoindent sw=2 et`. There is no reason for always setting the `expandtab` option for HAML files. The fact that the "obvious" way of disabling it didn't work, makes it annoying.

**Comment by chrisbra** [comment]
This needs to be taken care of by the runtime file maintainer.
ping @tpope since he is the maintainer.

**Comment by tpope** [comment]
The very good reason for setting `'expandtab'` is that when I wrote the file, tabs were a syntax error (and they're still discouraged AFAIK). That said, the Ruby ftplugin is going to start setting them (with opt out), so I'll be removing it from `indent/haml.vim`.

**Comment by brammool** [comment]
Tim Pope wrote:

> The very good reason for setting `'expandtab'` is that when I wrote
> the file, tabs were a syntax error (and they're still discouraged
> AFAIK). That said, the Ruby ftplugin is going to start setting them
> (with opt out), so I'll be removing it from `indent/haml.vim`.

Yes, if the language doesn't like tabs, setting 'expandtab' in the
ftplugin works best.  Since it also applies when not using
auto-indenting.

-- 
It's totally unfair to suggest - as many have - that engineers are socially
inept.  Engineers simply have different objectives when it comes to social
interaction.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am closing this as I think @tpope handle this with the next runtime file update.
