### ISSUE TITLE
Extra parenthesis for %a in terminal and scratch buffers

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#3388]
To reproduce:

```
vim --clean --cmd 'set laststatus=2' --cmd 'set stl=%a' --cmd 'args f1 f2'
```

Then open a terminal (`:terminal`) or edit a new buffer (`:enew`). You should see that an extra open parenthesis appears in the status line. I can reproduce it with Vim 8.1.300.

**Comment by k-takata** [comment]
This is intentional, I think. (Not sure whether it is documented.)
Here is the code for that.
https://github.com/vim/vim/blob/a449a7c6b986b8f5b28c61b8f628e69ed43ca030/src/buffer.c#L4759-L4760
Extra parentheses are added when you edit a buffer which does not exist in the arguments.
This is also the same for the title of gvim or vim with setting 'title' on.

**Comment by lifepillar** [comment]
I see. My eye was caught by the opening double parentheses, I didn't even notice that they are balanced. Guess I'll get used to it.
