### ISSUE TITLE
bufhidden of terminal buffer started with ++hidden

### ISSUE THREAD

**Issue by ghost** [vim/vim#3410]
When terminal buffer is started with `++hidden`, currently `bufhidden` is empty.
Should it be `bufhidden=hide`?

**Comment by brammool** [comment]
> When terminal buffer is started with `++hidden`, currently `bufhidden`
> is empty.
> Should it be `bufhidden=hide`?

They are really two separate things: ":term ++hidden" means the terminal
is initially hidden.  It doesn't mean that once the terminal is in a
window there is anything special about it.  The 'bufhidden' option is to
specify what happens when a buffer is leaving a window.  You can set
this for a terminal as well.  But I don't think that ++hidden implies
it.

I would expect the hidden terminal to either remain always hidden (like
what is used in Termdebug), or it's hidden initially, and you want to
look at it later, e.g. when a build command has finished.


-- 
How To Keep A Healthy Level Of Insanity:
12. Sing along at the opera.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing then.
