### ISSUE TITLE
incsearch breaks <C-r><C-w>

### ISSUE THREAD

**Issue by bstaletic** [vim/vim#3413]
Steps to reproduce:

- `vim --clean foo`
- Insert `foo bar`
- `set incsearch`
- `/foo<C-r><C-w>`

Expected:

Search pattern should be `foofoo` because the cursor is still on the word `foo`.

Actual:

Search pattern is `foobar`.

Further details:

- If the pattern was `/fo<C-r><C-w>` we would get the correct `fofoo`, because `fo` didn't reach the end of the word.
- This creates even bigger problems for `:s` and others. Here's an example (`|` is the cursor position):

```
foo|

bar baz
```

If a user does `:%s/bar/<C-r><C-w>`. the command will actually be `:%s/bar/baz`.
I'd argue that during commands, `incsearch` shouldn't be responsible for moving the cursor and that the command should be `:%s/bar/foo`. Still, even if `incsearch` moves the cursor, the command should be `:%s/bar/bar/`.

**Comment by brammool** [comment]
Boris Staletic wrote:

> Steps to reproduce:
> 
> - `vim --clean foo`
> - Insert `foo bar`
> - `set incsearch`
> - `/foo<C-r><C-w>`
> 
> Expected:
> 
> Search pattern should be `foofoo` because the cursor is still on the
> word `foo`.
> 
> Actual:
> 
> Search pattern is `foobar`.
> 
> Further details:
> 
> - If the pattern was `/fo<C-r><C-w>` we would get the correct `fofoo`, because `fo` didn't reach the end of the word.
> - This creates even bigger problems for `:s` and others. Here's an example (`|` is the cursor position):
> 
> ```
> foo|
> 
> bar baz
> ```
> 
> If a user does `:%s/bar/<C-r><C-w>`. the command will actually be `:%s/bar/baz`.
> I'd argue that during commands, `incsearch` shouldn't be responsible
> for moving the cursor and that the command should be `:%s/bar/foo`.
> Still, even if `incsearch` moves the cursor, the command should be
> `:%s/bar/bar/`.

So now we have a conflict: Some users expect the word under the current
cursor position, after the match, to be used, you expect the original
cursor position to be used.

I think the first example you give is rather synthetic: why would one
type the word under the cursor and then use CTRL-R CTRL-W to get it?

Let's make the second example a bit more realistic.  Suppose there is
some complicated word under the cursor, and you want to subsitute
matches of some other word in the file with that word:

	int SomeComplicatedName;

	for (xxx = 1; xxx < len; ++xxx)

With the cursor in SomeComplicatedName:
	:%s/xxx/<C-R><C-W>/g

Now the problem only happens when xxx starts with SomeComplicatedName.
That's very unlikely to happen.

Unless we find a more realistic example, I would rather stick to how it
works now.

-- 
How To Keep A Healthy Level Of Insanity:
15. Five days in advance, tell your friends you can't attend their
    party because you're not in the mood.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bstaletic** [comment]
> Some users expect the word under the current cursor position, after the match, to be used

I guess I don't see why. The user never sees the cursor *on the word after the match*, so I don't see how this could be useful

> Let's make the second example a bit more realistic

I just tried the example you posted with the exact variable names. What happened is `<C-r><C-w>` putting in `1` instead of `SomeComplicatedName` resulting in obviously wrong code. This is exactly the wrong behaviour that I'm talking about.

**Comment by brammool** [comment]
> > Some users expect the word under the current cursor position, after
> > the match, to be used
> 
> I guess I don't see why. The user never sees the cursor *on the word
> after the match*, so I don't see how this could be useful

This is documented:

	CTRL-R CTRL-W can be used to add the word at the end of the current
	match, excluding the characters that were already typed.

It's like using CTRL-L for a whole word.
 
> > Let's make the second example a bit more realistic
> 
> I just tried the example you posted with the exact variable names.
> What happened is `<C-r><C-w>` putting in `1` instead of
> `SomeComplicatedName` resulting in obviously wrong code. This is
> exactly the wrong behaviour that I'm talking about.

Oh, not sure what I was doing, but it indeed doesn't work.
I suppose that when the search pattern of the :s command is finished,
the cursor should be back where it started.

-- 
Now it is such a bizarrely improbable coincidence that anything as
mind-bogglingly useful as the Babel fish could have evolved purely by chance
that some thinkers have chosen to see it as a final and clinching proof of the
NON-existence of God.
The argument goes something like this: 'I refuse to prove that I exist,' says
God, 'for proof denies faith, and without faith I am nothing.'
'But,' says Man, 'the Babel fish is a dead giveaway, isn't it?  It could not
have evolved by chance.  It proves you exist, and so therefore, by your own
arguments, you don't.  QED.'
'Oh dear,' says God, 'I hadn't thought of that,' and promptly vanishes in a
puff of logic.
'Oh, that was easy,' says Man, and for an encore goes on to prove that black
is white and gets himself killed on the next pedestrian crossing.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
