### ISSUE TITLE
Build fails of 8.1.0388 on Debian and Ubuntu: unknown type name 'char_u'

### ISSUE THREAD

**Issue by fusion809** [vim/vim#3428]
Hi,

I package bleeding-edge Vim for a variety of platforms. Most of my builds for 8.1.0388 are going fine, aside from those of Debian and Ubuntu, which are failing with the log: https://gist.github.com/68e7c4a371da276e16a73f8bcc52c696. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Oops that doesn't show it in full -- https://paste.pound-python.org/show/0RKdzqyqEVmZB6XZJz6y/.

**Comment by jonathonf** [comment]
This may be related to building in a chroot/container - I see the same thing on Launchpad with [Cosmic](https://launchpadlibrarian.net/388296138/buildlog_ubuntu-cosmic-amd64.vim_2%3A8.1.0349+really.v8.1.0388-0york0~ubuntu18.10.1_BUILDING.txt.gz) and [Xenial](https://launchpadlibrarian.net/388295473/buildlog_ubuntu-xenial-amd64.vim_2%3A8.1.0349+really.v8.1.0388-0york0~ubuntu16.04.1_BUILDING.txt.gz)

**Comment by fusion809** [comment]
Ah good, I thought I was the only one, in which case I might get the reply, "Deal with it yourself, you're the one that made this mess so it's up to you to fix it!"

**Comment by mgedmin** [comment]
The 1st error message on [line 5997](https://gist.github.com/fusion809/68e7c4a371da276e16a73f8bcc52c696#file-_log-L5997) of your Gist says

> Error: configure did not run properly.  Check auto/config.log.

Have you looked in `auto/config.log`?

**Comment by fusion809** [comment]
Well this was on the OBS server, so I'll have to re-run it locally to get it. 

EDIT: Give me a mo I'm doing it, thanks for the suggestion.

**Comment by mgedmin** [comment]
The way messages on in build log are interleaved makes me suspect you're running multiple configure scripts in parallel (in different build directories hopefully?).  I wonder if vim's configure script does something that breaks this sometimes?

**Comment by fusion809** [comment]
I must admit I copied the Debian packaging files from Debian's official repos, so I'm not sure. Debian packaging confuses the .... out of me, fortunately I've managed to get by with this package for a couple of years, I think (not sure exactly, but a while). This has worked fine for a long time, it's only this recent bump that's stuffed it and @jonathonf's a more able Debian packager than me (I know because I originally based my packaging on his, I eventually ditched using his in favour of Debian's official ones) and he's hit this road bump too.

**Comment by fusion809** [comment]
For some reason the build isn't working for me locally, for reasons unrelated to Vim (namely I'm getting https://gist.github.com/912de5751617355f8898beda264356c7, giving it largely in case I look back at this at a later date), so I can't get that log for now.

**Comment by jonathonf** [comment]
If I'm reading that correctly, and without knowing how OBS works, you might want to check you're building with a current package list or update your base image so you don't need to remove those icu-related packages (e.g. build against Debian 9.5 instead of 9.0?)

**Comment by fusion809** [comment]
Unfortunately, the OBS doesn't work like that. You're given a set of build targets, which contain packages belonging to the distro at the time of its release (so the oldest packages belonging to the distro release) and for Debian 9, you only get 9.0. Rolling distros (e.g. Arch, Fedora Rawhide, Mageia Cauldron, openSUSE Tumbleweed) get package updates every week, but fixed ones don't I'm afraid. 

Have you managed to get your build to work in Launchpad @jonathonf, with its presumably newer packages? If you haven't then I'd guess this isn't related, as I've managed to get Vim to build fine against it for quite a long time, it's only this recent update that's broken it. I also build other packages against it, as do several others. 

EDIT: I'm sorry if this comes across antagonistic, I get you're trying to help and I get not everyone uses the OBS and knows how it works. So thank you, sincerely for trying.

**Comment by fusion809** [comment]
https://build.opensuse.org/package/show/home:fusion809/vim-debian shows yas the Deb-based distros I normally build Vim against successfully.

**Comment by jonathonf** [comment]
I've tested building within a pbuild chroot. `configure; make` works fine, but `debuild` triggers the issue. This makes me think it may be related to the use of a shadow directory for building...

**Comment by fusion809** [comment]
Ah. Well, at least I know if the fix goes pear-shaped I can at least manually build Vim so I can use it on Deb-based distros, although I also know there's AppImages available for gVim.

**Comment by jamessan** [comment]
> This makes me think it may be related to the use of a shadow directory for building...

All of the Debian builds use shadow directories and build in a chroot, so it doesn't seem to be something _that_ fundamental.

> The way messages on in build log are interleaved makes me suspect you're running multiple configure scripts in parallel (in different build directories hopefully?).

This shouldn't be happening anymore.  I [disabled parallelization](https://salsa.debian.org/vim-team/vim/commit/04c55b75ac6d89a3d56a00f7bb2397af1d2dea87) within the Debian build, so each flavor builds on its own, using whatever parallelization Vim's own Makefiles support.

FWIW, I have been seeing a [test failure](https://salsa.debian.org/vim-team/vim/-/jobs/40925) in GitLab's CI which doesn't reproduce in the normal Debian builds, but I haven't had time to look into it.

**Comment by jonathonf** [comment]
My current thinking is that it's related to https://github.com/vim/vim/commit/0f7683f9739087f3c7a4678c5182ed0517523b4a#diff-f57f2991a6aa25fe45d8036c51bf8b4dR2848 and how symlinks are used for shadowdirs... I have no proof though.

**Comment by jamessan** [comment]
Well, Vim's Travis builds do test [building in a shadow dir](https://travis-ci.org/vim/vim/jobs/428368822) and those still pass...

**Comment by tonymec** [comment]
I build Vim with no problems in five different shadow directories at the same time, but each of these builds is also in a different konsole tab with its own shell (i.e. its own instance of `bash`), its own configure arguments set by means of environment variables and its own redirected logfile, using
```bash
(make || echo 'exit status' $? ; date) 2>&1 |tee -a ./make.log
```
on Linux. The only problems I get are as follows:
1. sometimes there is some missing `#ifdef` in the source, and then it usually affects only some of the parallel builds.
2. When files or subdirectories have been added in the `src/` parent common to my five shadow directories, all builds fail until I create soft links to these new files and directories in each shadowdir, the latest of these were `ln -sv ../xdiff` and `ln -sv ../protodef.h`.

I never run configure directly myself, but sometimes `make` decides to run it before compiling and sometimes, including whenever I change one or more of my configuration environment variables, I run `make reconfig` instead of plain `make`. I don't use `chroot`, but maybe I should.

**Comment by jonathonf** [comment]
> all builds fail until I create soft links to these new files and directories in each shadowdir

There's a make rule which should do that for you:

https://github.com/vim/vim/blob/ab18673731522c18696b9b132d3841646904e1bd/src/Makefile#L2768

**Comment by tonymec** [comment]
@jonathonf : That's part of `make shadow` which creates a **new** shadow directory. The problem I mentioned was when running `make` again and again to make incremental builds (recompiling only what has changed, or whose dependencies have changed) in an **existing** shadow directory. Deleting and recreating my shadow directories every time would also mean rebuilding everything from scratch every time.

**Comment by jonathonf** [comment]
OK, so that sounds like you're taking a different approach to building Vim.

---

Concentrating on the item pointed out by @mgedmin,

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/xdiffi.o xdiff/xdiffi.c
In file included from xdiff/xdiff.h:111:0,
                 from xdiff/xinclude.h:53,
                 from xdiff/xdiffi.c:23:
xdiff/../vim.h:48:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
     Error: configure did not run properly.  Check auto/config.log.
          ^
```

a "failed" `auto/config.log` is here: https://gist.github.com/jonathonf/37988abb97cc5b5cc9357ec83819f50b .

Looking at `vim.h` it says that:

```
/*
 * Check if configure correctly managed to find sizeof(int).  If this failed,
 * it becomes zero.  This is likely a problem of not being able to run the
 * test program.  Other items from configure may also be wrong then!
 */
# if (VIM_SIZEOF_INT == 0)
    Error: configure did not run properly.  Check auto/config.log.
# endif
```

but I don't see any references to `sizeof(int)` in the `config.log`.

**Comment by brammool** [comment]
> OK, so that sounds like you're taking a different approach to building Vim.
> 
> ---
> 
> Concentrating on the item pointed out by @mgedmin,
> 
> ```
> gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/xdiffi.o xdiff/xdiffi.c
> In file included from xdiff/xdiff.h:111:0,
>                  from xdiff/xinclude.h:53,
>                  from xdiff/xdiffi.c:23:
> xdiff/../vim.h:48:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
>      Error: configure did not run properly.  Check auto/config.log.
>           ^
> ```
> 
> a "failed" `auto/config.log` is here: https://gist.github.com/jonathonf/37988abb97cc5b5cc9357ec83819f50b .

It looks like including "../vim.h" confuses your setup, and it loads the
wrong auto/config.h.  The configure check is:

	# if (VIM_SIZEOF_INT == 0)
	    Error: configure did not run properly.  Check auto/config.log.
	# endif

But the config.log does mention that VIM_SIZEOF_INT is 4.  Thus somehow
the auto/config.h that configure writes is not picked up by src/vim.h.


-- 
hundred-and-one symptoms of being an internet addict:
56. You leave the modem speaker on after connecting because you think it
    sounds like the ocean wind...the perfect soundtrack for "surfing the net".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jonathonf** [comment]
OK, so this partial revert of https://github.com/vim/vim/commit/0d5f21c3dfaceed08b4cdb33a73eb16f680ff49b "fixes" my build issue but probably isn't an ideal solution:

```diff
--- vim-8.1.0390.orig/src/xdiff/xdiff.h
+++ vim-8.1.0390/src/xdiff/xdiff.h
@@ -108,7 +108,7 @@ typedef struct s_bdiffparam {
        long bsize;
 } bdiffparam_t;
 
-#include "../vim.h"
+#include "vim.h"
 
 #define xdl_malloc(x) lalloc((x), TRUE)
 #define xdl_free(ptr) vim_free(ptr)
```

I end up with test failures (back to [this](https://groups.google.com/forum/#!topic/vim_use/UxVY8ussLOw)), but at least compilation succeeds now. :laughing: 

(I don't know if Debian will hit or are already having the same build issues but hopefully this is helping...)

**Comment by chrisbra** [comment]
I am confused. xdiff is in a subdirectory of the src directory. So the include `../vim.h` should be correct. So how is your directory structure?

**Comment by jonathonf** [comment]
Ah ha! I think I've found replication steps for a plain tarball:

```
wget https://github.com/vim/vim/archive/v8.1.0390.tar.gz
tar xf v8.1.0390.tar.gz
cd vim-8.1.0390
make distclean
make -C src shadow SHADOWDIR=test
make -C src/test
```

**Comment by brammool** [comment]
> Ah ha! I think I've found replication steps for a plain tarball:
> 
> ```
> wget https://github.com/vim/vim/archive/v8.1.0390.tar.gz
> tar xf v8.1.0390.tar.gz
> cd vim-8.1.0390
> make distclean
> make -C src shadow SHADOWDIR=test
> make -C src/test
> ```

OK, it appears the problem is that "xdiff" itself is linked.  We should
created the xdiff directory and link each file in it.

For some systems it proably works because the compiler looks in the
current directory.

-- 
Over the years, I've developed my sense of deja vu so acutely that now
I can remember things that *have* happened before ...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
