### ISSUE TITLE
Ctrl-Y doesn't copy modeless selection to clipboard in Normal mode

### ISSUE THREAD

**Issue by lkintact** [vim/vim#3450]
1. run `gvim.exe --clean -c "set guioptions-=aA"`
2. open a couple of new windows, put some text into them, switch to Normal mode
3. make a modeless selection of an area on the screen with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+Mouse_left_click and mouse dragging, hit <kbd>Ctrl</kbd>+<kbd>y</kbd>. The selection doesn't get copied into the clipboard.

This may be not a bug since the description at `:help modeless-selection` only mentions Ctrl-Y in regard to Insert and Command-line modes, but afair Ctrl-Y did copy modeless selection in Normal mode in earlier versions of Gvim.

OS: Windows 7,
Gvim: gvim_8.1.0401_x86.zip

**Comment by brammool** [comment]
> 1. run `gvim --clean -c "set guioptions-=aA"`
> 2. open a couple of new windows, put some text into them, switch to Normal mode
> 3. make a modeless selection of an area on the screen with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+Mouse_left_click and mouse dragging, hit <kbd>Ctrl</kbd>+<kbd>y</kbd>. The selection doesn't get copied into the clipboard.
> 
> This may be not a bug since the description at `:help modeless-selection` only mentions Ctrl-Y in regard to Insert and Command-line modes, but afair Ctrl-Y did copy modeless selection in Normal mode in earlier versions of Gvim.
> 
> OS: Windows 7,
> Gvim: gvim_8.1.0401_x86.zip

Right, CTRL-Y only works on the command line.  Otherwise the modeless
selection goes to the "current selection", which is a X11 thing.

Not sure if it's worth reserving a key sequence for copying the modeless
selection to the clipboard on MS-Windows.  There doesn't seem a need for
this.  Admittedly it's a bit strange to be able to start a modeless
selection but not being able to do anything with it.

-- 
From "know your smileys":
 :q	vi user saying, "How do I get out of this damn emacs editor?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
> Admittedly it's a bit strange to be able to start a modeless selection but not being able to do anything with it.

Fortunately I can always  add the `A` flag to `'guioptions'`. Thank you very much for the answer, I'm closing the issue.
