### ISSUE TITLE
Erratically flashing `hl-Folded` highlighting when `'rnu'` is set

### ISSUE THREAD

**Issue by vit-v** [vim/vim#3484]
In recent versions of Vim (starting with 8.1.0373?), when `'relativenumber'` is set and actions are performed in a window containing folded lines, the highlighting at the intersection of folded lines and the relative-number columns flashes erratically.

In older versions of Vim, the highlighting consistently stays where it should.

Reproduction: `echo -e "{{{1\nline 1\n{{{1\nline 2\n" | vim --clean --not-a-term -c 'se fdm=marker rnu | au VimEnter * cal timer_start(100, {id -> feedkeys("gsjgskgsO\<Esc>gsjV\<Esc>gsj")})' -`

**Comment by asmjmisc** [comment]
Hi.

I also noticed this, and filed a bug report on Red Hat's bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1632634

I didn't have time to check, but seeing as this issue is also reported here, the bug comes from upstream rather than distro patches.

**Comment by h-east** [comment]
Hi,

This issue has occurred since Vim 8.1.0374.

```
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Sep 12 23:15:48 2018 +0200

    patch 8.1.0374: moving the cursor is slow when 'relativenumber' is set

    Problem:    Moving the cursor is slow when 'relativenumber' is set.
    Solution:   Only redraw the number column, not all lines.
```

It does not occur on 8.1.0373.

--

Best regards,
Hirohito Higashi (h_east)

**Comment by dylnmc** [comment]
Something similar using gvim (on Windows): when `rnu` is set and there is a fold, if I press CTRL-L to redraw, then the Fold (using `Folded` highlight group) appears fine. As soon as I move the cursor, then the fold disappears. `:redraw` or `:exec "norm! \<c-l>"` brings it back, though.

Doesn't seem to happen in mingw with vim there (older vim because have to in mingw). WSL seems to have it, too (newer vim).

Thanks

**Comment by dylnmc** [comment]
Also, `foldcolumn` disappears
