### ISSUE TITLE
Missing icon and info in Windows uninstall

### ISSUE THREAD

**Issue by scootergrisen** [vim/vim#3485]
Suggest adding icon and info for published by, size and version in Windows control panel uninstall.
![v](https://user-images.githubusercontent.com/1836590/46112918-a5a07880-c1ec-11e8-9f20-15663479df83.jpg)

Also have the version in the version column instead of both having it as part of the name and under version column.

Using Windows 7.

**Comment by k-takata** [comment]
(I thought I saw a similar issue somewhere?)

Currently I'm working on this.
First, apply #3479, then the folllowing 3 patches:
* https://bitbucket.org/k_takata/vim-ktakata-mq/src/6f4979d4ce1a6f829acf6fbd8653cd197003e099/wip-installer-skip-gcc_s_sjlj.patch?at=default
* https://bitbucket.org/k_takata/vim-ktakata-mq/src/6f4979d4ce1a6f829acf6fbd8653cd197003e099/wip-installer-respect-nls.patch?at=default
* https://bitbucket.org/k_takata/vim-ktakata-mq/src/6f4979d4ce1a6f829acf6fbd8653cd197003e099/installer-more-info.patch?at=default

Results: https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/157/job/tnc4jcsd2k8cv8f5/artifacts

This series of patches supports:
* Adding icon, publisher and version information.
* HiDPI
* Fixing the issue I mentioned in https://github.com/vim/vim/pull/3479#issuecomment-424740679.
* Reducing the file size of the installer about 500 KB by using larger dictionary for compression.
* Preparation for mlocati/gettext-iconv-windows#8. (If this is fixed, `libgcc_s_sjlj-1.dll` becomes unnecessary.)

**Comment by k-takata** [comment]
However, I wonder if this is the right way.
Should we switch to https://github.com/gpwen/vim-installer-mui2?
If we do so, some fixes I made into the current installer should be merged into the mui2 version.
(E.g. Install both 32- and 64-bit version of gettext and iconv for GvimExt.)

The script size of the mui2 version is very large. It is 10x larger than the current version.
I think it is because it includes the functions of `dosinst.c`, however, I haven't reviewed it because of the size...

**Comment by k-takata** [comment]
After many trials, I have successfully imported @gpwen's [vim-installer-mui2](https://github.com/gpwen/vim-installer-mui2) into the latest Vim's source code.
Changes are here: https://github.com/vim/vim/compare/master...k-takata:topic/mui2?expand=1

Of course, I imported the following items which were added to the official installer, but have not added to the mui2 installer:
* Install both 32- and 64-bit gettext and iconv DLLs for GvimExt.
* Users can select if they remap the keys for Windows and change the mouse behavior.
* Accept installing into a directory which name doesn't end with "vim".
* Install winpty.
* Remove the "(self-installing)" string.

Also fixed the following items:
* Show the estimated install size in the control panel.
* Show the publisher names in the control panel.
* Support HiDPI.
* Optimize the data compression option.
* Preparation for mlocati/gettext-iconv-windows#8.
* Adjust the default `_vimrc` so that it doesn't set `'diffexpr'` if the internal diff is supported.
* Fix #3309 and #3310.

This has been built in my local account of vim-win32-installer. The results can be found at here:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/173/job/nttyjit3xv1kq2es/artifacts

**Comment by brammool** [comment]
Ken Takata wrote:

> However, I wonder if this is the right way.
> Should we switch to https://github.com/gpwen/vim-installer-mui2?
> If we do so, some fixes I made into the current installer should be merged into the mui2 version.
> (E.g. Install both 32- and 64-bit version of gettext and iconv for GvimExt.)
> 
> The script size of the mui2 version is very large. It is 10x larger
> than the current version.
> I think it is because it includes the functions of `dosinst.c`,
> however, I haven't reviewed it because of the size...

We still need dosinst.c when not using NSIS.  Duplicating the
functionality in the installer means we need to maintain two
implementations that are quite different.  I rather implement it once.
dosinst.c is old, it could be refactored to make it easier to use in two
ways.

-- 
Amnesia is one of my favorite words, but I forgot what it means.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> We still need dosinst.c when not using NSIS.

Do you mean that we need to care people who just unpack the zip archive and run the `install.exe`?
(Actually, I haven't used the `install.exe` that way...)

This was the first time I used gpwen's vim-installer-mui2, and I think that its user experience is very good compared to our current NSIS installer. (It doesn't show any noisy message boxes.)
But I think you prefer to evolve current NSIS installer gradually rather than swithing to vim-installer-mui2. Then #3479 would be the first step.

**Comment by brammool** [comment]
> > We still need dosinst.c when not using NSIS.
> 
> Do you mean that we need to care people who just unpack the zip
> archive and run the `install.exe`?
> (Actually, I haven't used the `install.exe` that way...)
> 
> This was the first time I used gpwen's vim-installer-mui2, and I think
> that its user experience is very good compared to our current NSIS
> installer. (It doesn't show any noisy message boxes.)
> But I think you prefer to evolve current NSIS installer gradually
> rather than swithing to vim-installer-mui2. Then #3479 would be the
> first step.

It should be possible to build vim.exe or gvim.exe and use install.exe
to install Vim properly, without also building the installer.  At least
with the current NSIS installer it's quite a bit of work to do that.

Since on MS-Windows installing involves making changes to the registry,
"make install" can't just copy files.  And there are a number of
choices, thus something like dosinst.c is needed.

-- 
hundred-and-one symptoms of being an internet addict:
118. You are on a first-name basis with your ISP's staff.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
If dosinst.c is an equivalent for `make install`, it lacks copying the binaries and the runtime files into a destination directory. It just register some information to the OS, and create some batch files and _vimrc, doesn't it? I think we also need a good way to copy the binaries and the runtime files from the build directory into a destination directory.

Anyway, thank you for the explanation. Now I think I understand the actual role of dosinst.c.

> Duplicating the functionality in the installer means we need to maintain two implementations that are quite different. I rather implement it once.

Not sure we can do this with keeping the user experience of gpwen's vim-installer-mui2...

**Comment by brammool** [comment]
> If dosinst.c is an equivalent for `make install`, it lacks copying the
> binaries and the runtime files into a destination directory. It just register
> some information to the OS, and create some batch files and _vimrc, doesn't
> it? I think we also need a good way to copy the binaries and the runtime
> files from the build directory into a destination directory.

Well, I have to admit I haven't used it that way.  One can also change $PATH to
where the vim.exe is, but I suppose that's not the normal way.  On the other
hand, MS-Windows does not really have a "bin" or "/usr/local/bin" equivalent.
I know it works to dump it in the Windows directory, but that is a hack.

> Anyway, thank you for the explanation. Now I think I understand the actual
> role of dosinst.c.
> 
> > Duplicating the functionality in the installer means we need to maintain two implementations that are quite different. I rather implement it once.
> 
> Not sure we can do this with keeping the user experience of gpwen's
> vim-installer-mui2...

The installer can invoke the install.exe with the right arguments.
Perhaps a console would pop up for a moment, but that can be surpressed.
We can write errors and warnings in a file, so the user doesn't have to look in
the console to check if something went wrong.

What I'm trying to avoid is that some registry manipulation in the installer is
changed/fixed/extended, and the other installer gets out of sync.

-- 
hundred-and-one symptoms of being an internet addict:
120. You ask a friend, "What's that big shiny thing?" He says, "It's the sun."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I created a new PR based on this discussion. #3501
