### ISSUE TITLE
`termguicolors` renders vim unusable

### ISSUE THREAD

**Issue by stefanfrede** [vim/vim#3500]
I don't know if this is a problem of my configuration, or a problem with vim, but the moment I set termguicolors vim gets unusable ([screenshot](https://www.frede.io/img/20180930ScreenShot.png)).

Im on `macOS Mojave` and use the `Terminal.app` with  `Vim 8.1`.

This happens with or without using Tmux.

**Comment by tonymec** [comment]
Maybe `:help xterm-true-color` could help you.

Another possibility is to use "only" 256 colors in the terminal (rather than 16777216) but approximating the GUI color scheme "as well as possible" by using the "nearest" one of the 256 colors. (If the red, green and blue components are each a multiple of 0x33 the exact same color is one of the 256. This accounts for 6↑3=216 colors; add the 16 "basic" colors and there remains 24 additional spots, used for additional shades of grey.) For this approach, see https://vim.wikia.com/wiki/Using_GUI_color_settings_in_a_terminal (which dates from the time when `'termguicolors'` didn't yet exist but there already were third-party plugins to support 256-color terminals).

This latter approach (with the CSApprox plugin) is what I use, and it suits me so well that I never felt the need to `:set termguicolors` since that option was added.

Best regards,
Tony.

**Comment by chdiza** [comment]
> and use the Terminal.app

Terminal.app does not support truecolor, so `termguicolors` will cause gibberish like that.

iTerm2.app *does* support truecolor.

**Comment by stefanfrede** [comment]
That explains it. Thanks both of you!
