### ISSUE TITLE
getchar(1) returns wrong value for ALT + simple-character (linux)

### ISSUE THREAD

**Issue by ramele** [vim/vim#3502]
How to reproduce -
:sleep 2 | echo getchar(1) . ' ' . getchar()
while sleeping type ALT-m
"237 237" is the expected output but I get "195 237" instead.

Tested with GUI on linux (RHEL). In Windows there is no such issue.

**Comment by tonymec** [comment]
This is maybe weird, but in fact it is expected:
```
		When [expr] is 1 only the first byte is returned.  For a
		one-byte character it is the character itself as a number.
		Use nr2char() to convert it to a String.
```
In UTF-8, any character above U+007F is made of more than one byte. In particular, `U+00ED LATIN SMALL LETTER I WITH ACUTE` (or Alt-m) is represented in UTF-8 as 0xC3 0xAD… and 0xC3 is 195 decimal.

Best regards,
Tony.

**Comment by ramele** [comment]
Hi Tony,

This makes sense now. I read the help several times and it is very confusing since Alt-m is returned as one byte (0xED) using getchar(0)...

Thank you,
Ramel

**Comment by tonymec** [comment]
When using getchar(0) with `'encoding'` set to UTF-8, Alt-M is returned as U+00ED which is in fact two bytes (0xC3 0xAD, as you can see by doing `g8` with the cursor on it). It would be one byte if `'encoding'` were set to Latin1 or to some other 8-byte encoding, which I suppose is the case on your Windows system; but most Linux systems have UTF-8 as default by now.

In most cases, using some construct like
```vim
if getchar(1)
        " there is something to be read, so exit the present procedure early
        " and relinquish control to where the input will be read and handled
else
        " there is nothing to be read, so do something else
        " then come back to the start of this "if" statement
endif
```
will be good enough anyway, since if `getchar(1)` is nonzero you will still have to remove the character from the waiting queue, for instance by using `getchar()` or `getchar(0)`.

See https://vim.wikia.com/wiki/Working_with_Unicode about how to systematically set `'encoding'` to UTF-8 so that all files (in any language and charset) can be read and written losslessly (though in some cases Vim may have to be told in which `'fileencoding'` to read the file, see `:help ++enc`).

Best regards,
Tony.
