### ISSUE TITLE
nomodifiable infect to new buffer

### ISSUE THREAD

**Issue by mattn** [vim/vim#3516]
```
:set readonly
:new
```
new buffer is not readonly. but
```
:set nomodifiable
:new
```
nomodifiable infect to new buffer. I think new buffer should be modifiable.

```diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 99c19f913..0d80390f3 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -4242,6 +4242,7 @@ do_ecmd(
 	    swap_exists_action = SEA_DIALOG;
 #endif
 	    curbuf->b_flags |= BF_CHECK_RO; /* set/reset 'ro' flag */
+	    curbuf->b_p_ma = TRUE;
 
 	    /*
 	     * Open the buffer and read the file.
```

**Comment by Houl** [comment]
When you say `:set`, you want to change the global value (not just the local value).  `'readonly'` is an exception ... (I think fewer exceptions are better than more exceptions?).  Users maybe stumble over 'readonly' as being exceptional at several occasions: `:view`, `-R`, etc. -- this is not the case for `'modifiable'`.
But maybe it would make sense to also set `'nomodifiable'` with `:view`, `-R` etc.?

**Comment by tonymec** [comment]
Yes, `'nomodifiable'` should normally be set via `:setlocal` (or via a modeline, which is the same thing). For instance, help files have `'nomodifiable'` set on them, but only locally, so that `:new` from a helpfile still opens a new window which is `'modifiable'` because the global default hasn't been touched by opening the helpfile.

If `view` or the equivalent `vim -R` is not enough, you can set `'nomodifiable'` globally at startup by invoking `vim -M` and then all files you view in that session will be `'nomodifiable'` (and, by default, have `[-]` on their status lines)… until or unless, of course, you use `:setl ma` on one of them. The same happens if you use `:set nomodifiable` because `:setlocal` sets only the local value, `:setglobal` sets only the global default, and plain `:set` sets both.

Best regards,
Tony.

**Comment by brammool** [comment]
the current behavior is correct.  When using :set for a buffer-local option, you are setting the default value for a new buffer.  However, 'readonly' is not using the default value, but initialized from the file protection.  A new buffer being readonly doesn't make sense, it's like creating a new file.
