### ISSUE TITLE
:make command don't run correctly

### ISSUE THREAD

**Issue by abdyek** [vim/vim#3519]
This is my makefile for learning and trying C language:

> compile: test.c                                                                 
>        clear;                           
>        gcc -c test.c;                                                              
>        gcc -o test *.o -lm;                                                        
>        ./test          
> 

and this is a line in my .vimrc file:
`map <F5> :make <cr> `

I tried this:

> int main() {
> int sayiDizisi[5];
>     int i;
>     printf("5 tane tamsayı giriniz: ");
>     for (i = 0; i<5; i++) {
>         printf(":");
>         scanf("%d", &sayiDizisi[i]);
>     }
>     return 0;
> }

and I encountered :

> gcc -c test.c;
> gcc -o test *.o -lm;
> ./test
> 5 12 32 41 43
> 5 tane tamsayı giriniz: :::::
> Press ENTER or type command to continue

Why run for loop firstly?
I think this is a bug or I failed

Vi IMproved 8.1 (2018 May 18, compiled Aug 29 2018 20:42:12)

Note: make isn't run correctly

**Comment by mattn** [comment]
`:make` command display output of make command.

1. type :make 
2. vim run make command with redirect like `make > /tmp/VI.tmp`
3. your program test read string from stdin but messages are not displayed (since it is written into VI.tmp)
4. vim display contents written in VI.tmp

So this works as expected. This is not a bug.

If you want to run your command interactively, use `:terminal make`
