### ISSUE TITLE
Error when typing or moving cursor over commented-out [](){}

### ISSUE THREAD

**Issue by flarn2006** [vim/vim#3532]
Since I was working with the code anyway I did the `git bisect` for you, and determined that this issue was introduced in patch 8.1.0112 (commit 3dddb09c98825acefa6f2d94bb369b8e00d7b3e5).

### Method 1

1. Open a file containing code in a C-like programming language, containing a parenthesis, bracket, or brace character that is commented out. Only one such character is required, but a pair works as well.
2. Move the cursor over the character.

### Method 2

1. Create a new file with syntax highlighting for a C-like language. (e.g. `vim asdf.c`)
2. Switch to edit mode
3. Type `//{`

## Expected behavior

Nothing of note should happen.

## Actual behavior

An error message appears, which can get in the way because it requires a keypress to acknowledge. If using method 2, the cursor will always be on the problematic character after the error message. As far as I can tell, as long as it is the last character on the line, it is impossible to type at the end of the line directly, as every time the cursor would appear in the right place, the error appears and moves it back onto that character, at which point anything you type will be inserted before it. Instead, one must temporarily uncomment the line, or use other roundabout methods like the "join lines" function, in order to append text to the end of the line.

**Error message:**

    Error detected while processing function <SNR>12_Highlight_Matching_Pair:
    line   97:
    E475: Invalid argument: 0
    Press ENTER or type command to continue

**Comment by tonymec** [comment]
I cannot reproduce this on Linux64 Vim 8.1.468 (Big version, with GTK2 compiled-in), not even when starting it as `vim --clean` at the bash prompt in konsole then using method 2 above.

I get no error message and the Insert-mode cursor remains after the { which is the last character on the line.

My $VIMRUNTIME/plugin/matchparen.vim has
```vim
" Last Change: 2018 Jul 3
```
as its line 3. Function `s:Highlight_Matching_Pair()` starts at line 39 and its `endfunction` statement is at line 196 (157 lines lower) but line 97 of the function, i.e. line (39+97), or line 136 of the script, could not possibly give the above error: it is the `endif` in
```vim
  if i % 2 == 0
    let stopline = stoplinebottom
  else
    let stopline = stoplinetop
  endif
```
and it is followed by an empty line then a two-line comment.

Do you still get the same error in a state-of-the-art Vim with the latest runtime files? If you don't, then the problem has been fixed (or has otherwise disppeared) since then.

Best regards,
Tony.

**Comment by tonymec** [comment]
P.S. Patch 8.1.115 is titled `the matchparen plugin may throw an error`. I suspect that it may have fixed your problem.

Best regards,
Tony.

**Comment by flarn2006** [comment]
Yep, it was the out-of-date runtime files. Thanks @tonymec!
