### ISSUE TITLE
pedit command change the buflisted option

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim#3536]
when open a buffer use pedit command, it will change the buflisted option.

reprodoce step:

```
vim foo.txt
:set buflisted
:help 
pedit foo.txt
:set buflisted?
```

you will see:

```
nobuflisted
```

**Comment by wsdjeg** [comment]
I think it is a bug, it changes the option of a buffer which has been loaded, I think maybe when use `:pedit` command to open new buffer, `set nobuflisted will be better, that will be easy to preview new file without adding then to bufferlist ( for example, tabline.vim's buffer list)

**Comment by lacygoill** [comment]
The issue is not specific to the `'buflisted'` option; it's more general.

I can reproduce with this shell command:

    $ vim -Nu NONE --cmd 'filetype plugin on | syntax on' +'h | pedit ~/.vimrc'

If `~/.vimrc` is not the path to your vimrc, replace it appropriately (e.g. `~/.vim/vimrc`).
You should see that your vimrc is highlighted with the help syntax plugin, instead of the vim one.

For some reason, after the filetype of the vimrc has been correctly detected with the value `vim` (which correctly sources the vim filetype and syntax plugins), it's detected a second time with the value `help`.

So the effects of the vim filetype/syntax plugins are undone, the help filetype/syntax plugins are wrongly sourced, and some options are wrongly set such as `'modifiable'`, `'readonly'` and `'buflisted'`.

---

I rely on `:pedit` in one of my plugins to preview some data, and I apply a substitution to remove some noise. When the command installed by my plugin is run from a help buffer, the substitution fails because `'modifiable'` is set.

For the moment, the only solution which I have found is to run this after `:pedit`:

    if &ft is# 'help' | setl ma noro ft= | endif

I empty the `'filetype'` option, because otherwise I can't undo an edition in the previewed file.

---

I think a more descriptive title for the issue would be something like:

> `:pedit` from a help buffer always sets filetype of previewed file to help

**Comment by tonymec** [comment]
This is not a bug. It is even documented:
```
:ped[it][!] [++opt] [+cmd] {file}
		Edit {file} in the preview window.  The preview window is
		opened like with |:ptag|.  The current window and cursor
		position isn't changed.  Useful example: >
			:pedit +/fputc /usr/include/stdio.h
```
IOW, after your `:pedit` command, the help buffer is still current — and its filetype is `help`, and it is not listed.

**Comment by lacygoill** [comment]
I read `:h :pedit` before posting, and I didn't find an explanation for this behavior, but I may have misunderstood something.

In particular, I didn't find anything in `:h :pedit` which explains why a help buffer is a special case.
For example, if `:pedit` is run from a shell file, then the filetype of the previewed file is not set to `help`:

    $ vim -Nu NONE --cmd 'filetype plugin on | syntax on' +'sp ~/.bashrc | pedit ~/.vimrc'

But it is if you run `:pedit` from a help buffer.

**Comment by lacygoill** [comment]
The help says that the current window and cursor position are not changed, but it doesn't say that the filetype of the previewed file will be set to `help` unconditionally (i.e. no matter its true filetype), and only if `:pedit` is run from a help buffer.

**Comment by lacygoill** [comment]
To illustrate the issue, I don't understand why my vimrc is detected as a help file in this gif:

![gif1](https://user-images.githubusercontent.com/8505073/63207674-880d2380-c0ca-11e9-939e-ebfb64d3604b.gif)

If the explanation is that the previewed file inherits the filetype of the buffer from which `:pedit` was run, then I don't understand why my vimrc is not detected as a shell file in this gif (where `:pedit` was run from a bashrc buffer):

![gif](https://user-images.githubusercontent.com/8505073/63207677-90655e80-c0ca-11e9-8f03-850a8180727d.gif)

**Comment by brammool** [comment]
> To illustrate the issue, I don't understand why my vimrc is detected
> as a help file in this gif:
> 
> ![gif1](https://user-images.githubusercontent.com/8505073/63207674-880d2380-c0ca-11e9-939e-ebfb64d3604b.gif)
> 
> If the explanation is that the previewed file inherits the filetype of
> the buffer from which `:pedit` was run, then I don't understand why my
> vimrc is not detected as a shell file in this gif (where `:pedit` was
> run from a bashrc buffer):
> 
> ![gif](https://user-images.githubusercontent.com/8505073/63207677-90655e80-c0ca-11e9-8f03-850a8180727d.gif)

Yeah, this appears to be wrong.  I had already made a note in the todo
list, noticed this when working on the popup preview window.

The code indicates this was done intentionally, but I really don't see
why.  Let's remove it.

-- 
hundred-and-one symptoms of being an internet addict:
79. All of your most erotic dreams have a scrollbar at the right side.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
