### ISSUE TITLE
pcre regex

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#3542]
Please consider adding to vim full support to **pcre regex** (the regex style supported by perl, python and 99% of programming languages).
I know that I can enable magic, and very magic, that I can use the eregex plugin, and that I can replace using perldo, but still the syntax and the integration makes every search quite difficult.

**Comment by chrisbra** [comment]
This cannot be done, since Vims regexes support features, that the pcre (or perl/python regexes) do no support, like non-fixed with look-around assertions, visual mode support, column support or setting start and end of a match (see also `:h perl-patterns`). I suggest getting used to using the Vim like regex, it is most powerful.

See also the [eregex plugin](https://github.com/othree/eregex.vim) and #99

**Comment by g-i-o-r-g-i-o** [comment]
thanks but it's difficult to remember and not mix up two different regex systems....
I'll try with the eregex plugin, also if it doesn't seem very supported anymore.

**Comment by justinmk** [comment]
Funny that no one mentioned the [LogiPat](https://github.com/vim/vim/blob/master/runtime/plugin/logiPat.vim) plugin that is now shipped with Vim. But also not surprising: it's *yet another* quirky pattern syntax to learn, and furthermore guides users away from learning Vim's own regex syntax, to the detriment of any users misguided into using LogiPat. 

In other words, an anti-feature. Incidentally, Neovim intentionally does not ship LogiPat.

**Comment by g-i-o-r-g-i-o** [comment]
> Funny that no one mentioned the [LogiPat](https://github.com/vim/vim/blob/master/runtime/plugin/logiPat.vim) plugin that is now shipped with Vim. But also not surprising: it's _yet another_ quirky pattern 

logipat seems a very good addon if I decide not to use pelre; anyway I'll try it
