### ISSUE TITLE
Pasting multiple line commands behaves differently than in the past (< vim-8.0)?

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#3545]
Hi,

I have a report in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1425811 from other user about copying/pasting multiple lines command into vim command line and automatizing some operations (such substitution of string across several files) this way in Vim - it started to behave differently since early 8.0 release according user.
Currently I don't know if the copy/paste behavior changed at that time, so it is a bug, or it is expected change.

Let's say user has three files created this way:

$ echo "aaa is bbb is ccc" > fu
$ cp fu fu2; cp fu fu3

Then opens all three files:

$ vi fu fu2 fu3

Here goes the multiple lines command:

:1,$s:aaa:qqq:
ZZ
:n

So user copies it by ctrl+shift+c and pastes it into Vi by ctrl+shift+v - according user, he should be able (older Vim was able to) to go through all files by repeated pasting - now he gets into 'insert' mode with first paste.
When I try to do the same, I ends with ':n' on vim command line. So when I press 'enter' key, multiple lines command is done and Vi opens next file. With ctrl+shift+v and pressing 'enter', I can go through all files.

Would anyone mind giving me a hint what can cause behavior what user experiences? Was it possible to do this style of copy/pasting in the past and it changed? Or is it the bug?

**Comment by chrisbra** [comment]
I think this has been changed as security measure with this patch https://github.com/vim/vim/releases/tag/v8.0.1587

**Comment by vim-ml** [comment]
Op di 16 okt. 2018 14:51 schreef zdohnal <vim-dev-github@256bit.org>:

> Would anyone mind giving me a hint what can cause behavior what user
> experiences? Was it possible to do this style of copy/pasting in the past
> and it changed? Or is it the bug?
>

Sounds like bracketed paste mode interfering somehow?

Christ van Willegen

>

**Comment by zdohnal** [comment]
I'm deeply sorry, I forgot to mention he experiences it since v8.0.314. I asked about his ~/.vimrc to see if there is anything fishy, I'll post it here as soon as I'll have it.

**Comment by rakus** [comment]
Christ is right. If I execute the described steps, I end up with the commands pasted into the file `fu`.
Then I disabled bracketed paste mode with `set t_BE=`. Now it works as the initially reporter wants.

The behavior of vim seems intentional. Here is the commit: ec2da36ca48b40c0654b32a8d2c9f52e796daa5e
> patch 8.0.0210: no support for bracketed paste    
> Problem:    Vim does not support bracketed paste, as implemented by xterm and other terminals.
> Solution:   Add t_BE, t_BD, t_PS and t_PE.

Also see `:help xterm-bracketed-paste`

BTW: disabling t_BE only works since 8.0.244

**Comment by zdohnal** [comment]
> Christ is right. If I execute the described steps, I end up with the commands pasted into the file `fu`.
> Then I disabled bracketed paste mode with `set t_BE=`. Now it works as the initially reporter wants.
> 
> The behavior of vim seems intentional. Here is the commit: [ec2da36](https://github.com/vim/vim/commit/ec2da36ca48b40c0654b32a8d2c9f52e796daa5e)
> 
> > patch 8.0.0210: no support for bracketed paste
> > Problem:    Vim does not support bracketed paste, as implemented by xterm and other terminals.
> > Solution:   Add t_BE, t_BD, t_PS and t_PE.
> 
> Also see `:help xterm-bracketed-paste`
> 
> BTW: disabling t_BE only works since 8.0.244

This way I should be able to go through the files only by pasting the command (I have ), but I need to press 'enter' key after every paste. If I add <ENTER> after ':n' and paste the command with <ENTER>, Vim will open new file called <ENTER>. Perhaps I understood something incorrectly?

**Comment by chrisbra** [comment]
Does it make a difference if you use <ctrl>r to paste the register?

**Comment by rakus** [comment]
> This way I should be able to go through the files only by pasting the command (I have ), but I need to press 'enter' key after every paste. If I add after ':n' and paste the command with , Vim will open new file called . Perhaps I understood something incorrectly?

I cannot confirm this. Do the copied commands contain a trailing newline?
For me it looks like this:
```
$ xclip -o -selection clip | xxd
00000000: 3a31 2c24 733a 6161 613a 7171 713a 0a5a  :1,$s:aaa:qqq:.Z
00000010: 5a0a 3a6e 0a                             Z.:n.
```

**Comment by zdohnal** [comment]
> Does it make a difference if you use <ctrl>r to paste the register?

I got the command into unnamed register (wrote it in insert mode and then deleted):

""   :1,$s:aaa:qqq:^JZZ^J:n^J

But then I'm unable to to execute the commad - ctrl+r " doesn't work. I have the command even in '1' register, but using this one doesn't work too.

**Comment by zdohnal** [comment]
And do I understand correctly the default value of t_BE (if it is not defined in vimrc) is taken from terminal itself yes?

**Comment by tonymec** [comment]
At startup, the values of 'term' (set from $TERM, and set again unchangeably to "builtin_gui" at GUI startup) and of 'ttybuiltin' (default on) determine where Vim will look for its t_something settings:
* The GUI always uses the builtin_gui termcap. The following applies to Console Vim:
* If there is both a builtin termcap and an external termcap/terminfo for that terminal, Vim will use the builtin one in preference to the external one if 'ttybuiltin' is on (the default), otherwise it will do the opposite.
* If only one of the two exists, Vim will use that.
* Which termcaps are built-in is a configuration option which depends on the chosen featureset: there are three possible settings shown by :version as follows:
  * -builtin_terms : no builtin termcaps
  * +builtin_terms : the most usual termcaps are built-in
  * ++builtin_terms : all termcaps known to the Vim source are built-in

See:
* :help builtin-terms
* :help +builtin_terms and :help ++builtin_terms
* :help 'ttybuiltin'
* :help 'term'

Best regards,
Tony.

**Comment by zdohnal** [comment]
> At startup, the values of 'term' (set from $TERM, and set again unchangeably to "builtin_gui" at GUI startup) and of 'ttybuiltin' (default on) determine where Vim will look for its t_something settings:

Thank you, Tony! I'll look it up.

**Comment by zdohnal** [comment]
Everyone, thank you! Setting 't_BE=' really fixed the issue for user. Again, thanks!
