### ISSUE TITLE
:terminal buffer cursor doesn't use Terminal highlight group

### ISSUE THREAD

**Issue by e4lam** [vim/vim#3546]
I would like to use a light background for editing code and a dark background for the :terminal buffer (new in vim 8.1). To do this, I've added this to my .gvimrc,
    `:highlight Terminal guibg=black guifg=white`

However, this results in an invisible cursor. The only to fix this seems to be also setting my Normal highlight group to (undesired) reverse video,
    `:highlight Normal guibg=black guifg=white`

Changing the Cursor highlight group seems to do nothing
    `:highlight Cursor guibg=black guifg=white`

This feels like a bug. Shouldn't the cursor colors in a :terminal buffer be using the Terminal highlight group?

**Comment by brammool** [comment]
> I would like to use a light background for editing code and a dark
> background for the :terminal buffer (new in vim 8.1). To do this, I've
> added this to my .gvimrc,
>     `:highlight Terminal guibg=black guifg=white`
> 
> However, this results in an invisible cursor. The only to fix this
> seems to be also setting my Normal highlight group to (undesired)
> reverse video,
>     `:highlight Normal guibg=black guifg=white`
> 
> Changing the Cursor highlight group seems to do nothing
>     `:highlight Cursor guibg=black guifg=white`
> 
> This feels like a bug. Shouldn't the cursor colors in a :terminal
> buffer be using the Terminal highlight group?

The terminal window uses the cursor color of the terminal.  You can
change it there (try running Vim).

The default uses the GUI normal colors, so that won't work if you
intentionally make the terminal use reverted colors.  I can fix that.

-- 
hundred-and-one symptoms of being an internet addict:
221. Your wife melts your keyboard in the oven.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by e4lam** [comment]
Thank you very much! And for vim in general, as a user since 1998!
