### ISSUE TITLE
in commnad line vim could not load more than one file 

### ISSUE THREAD

**Issue by termanary** [vim/vim#3559]
When I want to edit a lots of files in command line,I type : 
: edit firstfile secondfile thirdfile
vim edit a file named "firstfile secondfile thirdfile" .
If I want to edit a lots of files , do I have to restart up vim or use "edit file" many times ? 
Is there any way to solve it ?

When I want to vertical split n different files in n windows .
I read help :vs and help :sp .
But I find there is not any help about this . How could vim do this in command line ?

I know the command : "vim -O firstfile secondfile thirdfile" . Is restarting vim the only way ?

**Comment by chrisbra** [comment]
The `:e` command is documented to only take one argument, the file to be edited. If you want to edit more files, you can use e.g. `:arge` and then use `:next` to go through the argument list.

It is not a bug.

Please ask user questions on vi.stackexchange.com or on the vim-use mailinglist.

**Comment by tonymec** [comment]
@termanary : To split the Vim screen vertically and edit one file in each window you could use a sequence of ex-commands, maybe something like the following loop:
```
for f in ['file1', 'file2', 'file3', 'file4'] | exe 'vsplit' f | endfor
```
This keeps the current window unchanged and adds one additional window per new file beside it. How to replace the current window with the first (or last) new file, how to make the splits horizontal rather than vertical, or how to make each new file open on the left or right side of the preceding one (or, for horizontal splits, above or below it), is left as an exercise to the student.

See
```
:help :for 
:help :bar 
:help :exe 
:help :vsplit 
:help 'splitbelow'
:help 'splitright'
```
Best regards,
Tony.

**Comment by termanary** [comment]
@chrisbra : Thanks for help . I have read it many times and know that it is not a bug . I just look for a help . This command really helps .
@tonymec :  I did not know what the meaning of the ex-commands is in a long time . Thanks for tips .
I will read the document again .
Thanks again for your helps . I have googled but got nothing about the problem .

**Comment by termanary** [comment]
Thanks for helps.I find a maybe better way to create a new "vsplit".

```
" help function-argument
" help command-complete
" help 40.2
" command! -complete=file -nargs=* Vsplit :call VsplitFunction(<f-args>)
" function! VsplitFunction(...)
"     if a:0 == 0
"         vsplit
"     else
"         for ff in a:000
"             execute "vsplit " . ff
"         endfor
"     endif
" endfunction
```

**Comment by Houl** [comment]
The better way is `:vert all`, once you have created an argument list.

**Comment by termanary** [comment]
Yes,it is a good idea ,too .
