### ISSUE TITLE
Change ftp to https

### ISSUE THREAD

**Issue by Apromixately** [vim/vim#3580]
The download website https://www.vim.org/download.php distributes files via ftp. I think this should be switched to https.

**Comment by tonymec** [comment]
Well, here's what my browser says if I change ftp:// to https:// in order to get to https://ftp.vim.org/pub/vim/unix/vim-8.1.tar.bz2 instead of the same by ftp:

> **This Connection is Untrusted**
> 
> You have asked SeaMonkey to connect securely to ftp.vim.org, but we can't confirm that your connection is secure.
> 
> Normally, when you try to connect securely, websites will present trusted identification to prove that you are going to the right place.
> However, this website's identity can't be verified.
> 
> **What Should I Do?**
> 
> If you usually connect to this website without problems, this error could mean that someone is trying to impersonate the website, and you shouldn't continue.
> 
> [ This sounds bad, take me to my home page instead. ]
> 
> **Technical Details**
> 
> ftp.vim.org uses an invalid security certificate. The certificate is only valid for the following names: ftp.nluug.nl, ftp1.nluug.nl, ftp2.nluug.nl
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
> 
> **I Understand the Risks**
> 
> If you understand what's going on, you can tell SeaMonkey to start trusting this website's identification. Even if you trust the website, this error could mean that someone is tampering with your connection.
> 
> Don't add an exception unless you know there's a good reason why this website doesn't use trusted identification.
> 
>  [ Add Exception… ]

What **I** think you should do is not use those links at all but clone either the git source (from github) or the Mercurial source mirror (from bitbucket), and then periodically pull new changes onto your clone.

Best regards,
Tony.

**Comment by Apromixately** [comment]
@tonymec Building from source is not really an option. It's too much of a hassle even for me as a software developer.

I agree of course that the certs need to be set up correctly but that is reasonably easy to do with letsencrypt and I think providing ftp really doesn't help anyone these days.

**Comment by brammool** [comment]
> The download website https://www.vim.org/download.php distributes
> files via ftp. I think this should be switched to https.

Yeah, that should be better.  But some people might prefer the ftp:
link.  So I'll keep those as an alternative.

The links will point to https://ftp.nluug.nl, since the certificate is
for that domain, ftp.vim.org is just an alias.

Please check that I didn't make a mistake.

-- 
   GALAHAD hurries to the door and pushes through it.  As he leaves the room
   we CUT TO the reverse to show that he is now in a room full of bathing
   and romping GIRLIES, all innocent, wide-eyed and beautiful.  They smile
   enchantingly at him as he tries to keep walking without being diverted by
   the lovely sights assaulting his eyeballs.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing, as the links have been changed.
