### ISSUE TITLE
Setting toolbariconsize modifies the icons used in the toolbar

### ISSUE THREAD

**Issue by heikojansen** [vim/vim#3602]
Environment in use was KDE 5 on openSUSE Tumbleweed. The VIM versions tested were 8.1.479 as packaged by SUSE and a local build of the source as of commit d0721058f494143186f66a60151c9634031a8c96

Steps to reproduce:
- select a "Gnome" icon set in the KDE config for use in Gnome apps (just to eliminate a potential source for irritations)
- start gvim
- execute ```set toolbariconsize=huge```  to modify the toolbar

The toolbar icons change size but at the same time some icons vanish (they still take space and are clickable, but no image is shown) while others / most are replaced by some default image (the same for every affected icon).

Which icon theme is actually used is probably irrelevant, since the behavior was the same for "Adwaita", "hicolor" and "breeze" (except for a different replacement icon).

(Re-) executing ```set toolbariconsize=``` or  ```set toolbariconsize=small``` only made some more of the generic icons disappear but did not reset the toolbar.
Same goes for the sequence of ```set toolbar=tooltips``` then ```set toolbar=icons```.

**Comment by tonymec** [comment]
I think this problem is specific to GTK3. Your openSUSE gvim is compiled with GTK3 GUI, isn't it? (it should be displayed near the top of the `:version` output).

On my own-compiled Big gvim 8.1.513 with GTK2 GUI running on openSUSE 15.0, all icons are different and look appropriate to their function no matter which value (of [tiny, small, medium, large, huge, giant]) I select for the 'toolbariconsize' value; and changing the value always reeplaces all icons by ones of the newly selected size.

**Comment by heikojansen** [comment]
I cannot say if it is specific to GTK3 but you are right in that the version I tested against indeed is 3.24.1

**Comment by chrisbra** [comment]
i believe this is fixed by https://github.com/vim/vim/commit/81a4cf469a0f5c1603ac3130af9f011053854180
