### ISSUE TITLE
gvim spamming console from which it was started

### ISSUE THREAD

**Issue by feuGeneA** [vim/vim#3628]
So many repetitions of this they literally fill my 2xHD-height terminal window:
```
(gvim:600): Gtk-WARNING **: GtkNotebook 0x55923d87f190 is mapped but visible child GtkEventBox 0x55923d8841c0 is not mapped
```

I often invoke gvim from the command line and leave the process running for an extended period of time, and I do this many times over.  Unfortunately, due to this console spam, this effectively leaves my terminal useless.  So even though I have the file of interest right at my fingertips in the terminal, I jump through hoops to run gvim from some other context, if I want to continue using that terminal.  I love you vim but this is an unacceptable CLI.

**Comment by tonymec** [comment]
These messages may be useful (e.g. for debugging purposes), so rather than killing them altogether (by invoking gvim as `gvim > /dev/null` on Unix-like or as `gvim > NUL` on Windows) I'd rather log them (by invoking gvim as `(date; gvim || echo 'exit status' $? ; date) >> gvim.log` on Unix-like and something similar, perhaps less fancy if CMD.EXE isn't as powerful as bash, on Windows).

A simple way to "run gvim from some other context" is to launch it from a desktop icon. If you don't already have one, making one takes 5 minutes once and for all, or 10 if you haven't yet made shortcut icons: I'd hardly call this "jumping through hoops".

Best regards,
Tony.

**Comment by feuGeneA** [comment]
Thank you Tony @tonymec  for your constructive feedback.  I'm not interested in logging the messages, and I'm simply not willing to add in `> /dev/null` *every single time* I just want to type `gvim filename`, which is something I do many, many times a day.

Debugging messages should be disabled for end users.  In low volume I could see them being useful, but I'm pretty sure this constitutes spam:
![image](https://user-images.githubusercontent.com/7883777/48869994-26bf5a80-edad-11e8-8d0e-921379b77bf5.png)

**Comment by tonymec** [comment]
If it's a bug, it's probably a GTK bug (though I wouldn't stake my head on it); however you can still make a desktop icon for gvim. You only need to make it once, and it will run in its own context, not that of any shell you might have running. Or even simpler: if your window manager is like mine, just hit Alt-F2 and you'll get a prompt which will allow you to start gvim (or any other program, and with any arguments you want that time around) straight from the desktop context with no spamming into any terminal.

Best regards,
Tony.

**Comment by feuGeneA** [comment]
Thanks again Tony.

I do use the equivalent of alt+f2 (win/meta+r on my system). But it's still annoying.

Having to gather the target filename in my terminal is probably the biggest hoop to jump through, bigger than how gvim is launched.

This is a terrible distraction from my terminal flow, and a disappointing command line user experience from vim.

**Comment by vim-ml** [comment]
On 2018-11-21, F. Eugene Aumson wrote:
> Thanks again Tony.
> 
> I do use the equivalent of alt+f2 (win/meta+r on my system). But it's still
> annoying.
> 
> Having to gather the target filename in my terminal is probably the biggest
> hoop to jump through, bigger than how gvim is launched.
> 
> This is a terrible distraction from my terminal flow, and a disappointing
> command line user experience from vim.

A simple workaround would be to put this in your ~/.bashrc (assuming
your shell is bash):

    alias gvim='&>/dev/null gvim'

HTH,
Gary

**Comment by k-takata** [comment]
Similar issues: #1149, #1328, #2543

**Comment by brammool** [comment]
I see the same with many other GTK based programs.  It's not really a Vim problem but a GTK problem.  It seems they assume it's fine to print all kinds of messages in the terminal where a GUI program was started, even when it's in the background.
I don't think there is anything we can do in Vim to avoid this.  Perhaps file a but with the GTK project.

**Comment by fritzophrenic** [comment]
> Having to gather the target filename in my terminal is probably the biggest hoop to jump through, bigger than how gvim is launched.

As a workaround: when I want to use gvim from a terminal, and continue using that terminal, I usually launch gvim separately and then use "vim --remote-tab-silent file.x" or similar to send the file to an existing Vim instead of launching gvim directly on the file.

**Comment by juanlanus** [comment]
Any computer interactive application, whatever it is - like for example online banking or purchases like eBay, that sprouted rafts of warnings every now and then alarming its end users and forcing them to stop doing productive work to research the source, would be regarded as a low-usability UI.  
The developers of said application would feel ashamed and would take pride in fixing the issue ASAP. Or at least this is what I would do, instead of arguing along the years.  
We developers, as vim end users, should not see these warnings, and those of us who used part of our time in this thread (and its duplicates), should instead be doing productive work.
