### ISSUE TITLE
gn broken with /\zs

### ISSUE THREAD

**Issue by dylnmc** [vim/vim#3695]
### Hello

I have noticed that using `gn` is broken when the search pattern contains `\zs`. Take the folling file:

```vim
function! TestMatch1()
	echom "Change me to single quotes"
endfunction

function! TestIgnore1()
	echom "\<lt>Leave me as double quotes> "
endfunction

function! TestMatch2()
	echom "Change me to single quotes"
endfunction

function! TestMatch3()
	echom "Change me to single quotes"
endfunction

function! TestMatch4()
	echom "Change me to single quotes"
endfunction

function! TestIgnore2()
	echom "\<lt>Leave me as double quotes> "
endfunction

function! TestMatch5()
	echom "Change me to single quotes"
endfunction
```

Paste the above code into a buffer and run `:setf vim`. Now search for this:

* `/\v^function.\s+TestMatch\d+\(\)\n.*\zs".*"$`

You should see that it highlights only the double quotes following a function that matches `TestMatch\d\+`.

HOWEVER, if you type `gn` it will match from the start of **first closest match** to the end of the **second closest match**.

---
#### Shows search for `/\v^function.\s+TestMatch\d+\(\)\n.*\zs".*"$`

![screenshot from 2018-12-15 22 06 01](https://user-images.githubusercontent.com/7635158/50049546-e5715080-00b5-11e9-8b44-b3590267be2b.png)

#### Shows what happens after `gn` pressed

![screenshot from 2018-12-15 22 06 36](https://user-images.githubusercontent.com/7635158/50049547-e5715080-00b5-11e9-8e6e-42072d11e115.png)

### Use Case and Thanks

I was trying to use `:global` combined with a search that used `\zs` in order to surround patterns with `[`, `]` using tpope's vim-surround by doing something like `ysgn[` but because of this bug, I was unable to achieve this and had to use a work-around.

Thanks,
dylnmc

**Comment by chrisbra** [comment]
That is a limitation of how to handle a multi-line regex in combination with `\zs`. Basically what `gn` does is this:

1) It searches backwards for the last match of the current regular expression.

2) It searches forward for the next match of the current regular expression.

This should make clear, that the cursor will be on start of the next match, even if it was there already at the start of 1). Finally

3) it searches for the end of the current regular expression. and puts the cursor there. 

So in Vimscript, it does this:

    let pat='your pattern here'
    call search(pat, 'b')
    call search(pat, '')
    cal search(pat, 'ce')

If you do this with your multi-line pattern, you will receive the same selection.

And it is clear, that it won't work as you expected it, since at step 3, vim will search for the next line starting with `function`. So it will correctly got to line 11 instead on staying on the same line.

I think this is the expected behaviour of `gn` considering on how it works.

**Comment by Houl** [comment]
Maybe this is not the only approach, because the search highlighting works correctly ... (?).

**Comment by dylnmc** [comment]
@chrisbra If you consider [how you might make a text object that has a similar objective](https://gitlab.com/dylnmc/vim-config/blob/master/plugin/textobjs.vim#L177-211), then it seems more reasonable to:

1. search until the end of the next match (eg, with `search()` using the `e` and `c` flags or something similar)
2. search until the beginning of the match (eg, with `search()` using the `b` and `c` flags)

Is that an option for `gn` (and vice versa for `gN`)?

(In fact, it might even be possible to make an `onoremap`, `nnoremap`, and `xnoremap` for `gn` and `gN` to do just that, but I doubt that would be ideal.)

---

I also didn't understand how ...

> 1. It searches backwards for the last match of the current regular expression.
> 2. It searches forward for the next match of the current regular expression.

... is able to work. It seems to be backwards.

---

###### update

This seems to work reasonably well ...

```vim
function! s:gn(forwards)
	call search(@/, a:forwards ? 'ce' : 'ceb')
	normal! v
	call search(@/, 'cb')
endfunction

nnoremap gn :<c-u>call <sid>gn(1)<cr>
xnoremap gn :<c-u>call <sid>gn(1)<cr>
onoremap gn :<c-u>call <sid>gn(1)<cr>

nnoremap gN :<c-u>call <sid>gn(0)<cr>
xnoremap gN :<c-u>call <sid>gn(0)<cr>
onoremap gN :<c-u>call <sid>gn(0)<cr>
```

... **except** that if you're on the second line that is highlighted as I did above and use a `\zs` in the search, then it will jump over the current match to the next one ... not ideal (but still an improvement over the built-in *gn*).

[Is that another bug? :eyes:](https://asciinema.org/a/QDCgObzMVbAhhkOPEiFvcFG6p)

---

Thanks for looking into it,
dylnmc

**Comment by brammool** [comment]
> @chrisbra If you consider [how you might make a text object that has a
> similar
> objective](https://gitlab.com/dylnmc/vim-config/blob/master/plugin/textobjs.vim#L177-211),
> then it seems more reasonable to:
> 
> 1. search until the end of the next match (eg, with `search()` using the `e` flag or something similar)
> 2. search until the beginning of the match (eg, with `search()` using the `b` and `c` flags)
> 
> Is that an option for `gn` (and vice versa for `gN`)?

The solution is to have searchit() also return the end of the match.
It actually has it already, we only use another mechanism because it
isn't returned.

-- 
If you put 7 of the most talented OSS developers in a room for a week
and asked them to fix a bug in a spreadsheet program, in 1 week
you'd have 2 new mail readers and a text-based web browser.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Would it make sense to do something similar for `:global`?
```vim
vim9script
new
['aaa', 'bbbccc', '']->repeat(3)->setline(1)
global/aaa\nbbb\zsccc$/delete
```
Expected: only these lines remain:

    aaa
    aaa
    aaa

Actual: only these lines remain:

    bbbccc
    bbbccc
    bbbccc

Using `\@<=` instead of `\zs` fixes the issue:

    \%(aaa\nbbb\)\@<=ccc$
    ^^^        ^----^

Test:
```vim
vim9script
new
['aaa', 'bbbccc', '']->repeat(3)->setline(1)
global/\%(aaa\nbbb\)\@<=ccc$/delete
```
But `\@<=` can't backtrack too much.  From [`:help \@<=`](https://vimhelp.org/pattern.txt.html#%2F%5C%40%3C%3D):

   > But to limit the time needed, only the line where what follows matches
   > is searched, and one line before that (if there is one).

If it's not possible to change the behavior this late, maybe we could document the pitfall.  I couldn't find anything relevant at [`:help :global`](https://vimhelp.org/repeat.txt.html#%3Aglobal).  The help does say:

   > (for a multi-line pattern, only the start of the match matters).

But in the first example, the start of the match is `ccc` as specified by `\zs`.  So one could assume that `:global` would mark and delete the `bbbccc` lines, not the `aaa` lines.

Either the help means "only the start of the pattern matters":
```diff
diff --git a/runtime/doc/repeat.txt b/runtime/doc/repeat.txt
index 56e9ad82f..b571d3ecc 100644
--- a/runtime/doc/repeat.txt
+++ b/runtime/doc/repeat.txt
@@ -76,7 +76,7 @@ examples.
 
 The global commands work by first scanning through the [range] lines and
 marking each line where a match occurs (for a multi-line pattern, only the
-start of the match matters).
+start of the pattern matters).
 In a second scan the [cmd] is executed for each marked line, as if the cursor
 was in that line.  For ":v" and ":g!" the command is executed for each not
 marked line.  If a line is deleted its mark disappears.
```
Or we should mention that an exception is made for `\zs`:
```diff
diff --git a/runtime/doc/repeat.txt b/runtime/doc/repeat.txt
index 56e9ad82f..02d4dc0dd 100644
--- a/runtime/doc/repeat.txt
+++ b/runtime/doc/repeat.txt
@@ -75,8 +75,9 @@ NOTE [cmd] may contain a range; see |collapse| and |edit-paragraph-join| for
 examples.
 
 The global commands work by first scanning through the [range] lines and
-marking each line where a match occurs (for a multi-line pattern, only the
-start of the match matters).
+marking each line where a match occurs.  For a multi-line pattern, only the
+start of the match matters; however, if the pattern uses |/\zs| to match after
+the first line, the latter is marked (not the line where "\zs" matches).
 In a second scan the [cmd] is executed for each marked line, as if the cursor
 was in that line.  For ":v" and ":g!" the command is executed for each not
 marked line.  If a line is deleted its mark disappears.
```

**Comment by brammool** [comment]
> Would it make sense to do something similar for `:global`?
> ```vim
> vim9script
> new
> ['aaa', 'bbbccc', '']->repeat(3)->setline(1)
> global/aaa\nbbb\zsccc$/delete
> ```
> Expected: only these lines remain:
> 
>     aaa
>     aaa
>     aaa
> 
> Actual: only these lines remain:
> 
>     bbbccc
>     bbbccc
>     bbbccc

Well, I would not call that "similar", since the previous issue was
about the end of the match.  This is about the start of the match, when
it was set with \zs.

> Using `\@<=` instead of `\zs` fixes the issue:
> 
>     \%(aaa\nbbb\)\@<=ccc$
>     ^^^        ^----^
> 
> Test:
> ```vim
> vim9script
> new
> ['aaa', 'bbbccc', '']->repeat(3)->setline(1)
> global/\%(aaa\nbbb\)\@<=ccc$/delete
> ```
> But `\@<=` can't backtrack too much.  From [`:help \@<=`](https://vimhelp.org/pattern.txt.html#%2F%5C%40%3C%3D):
> 
>    > But to limit the time needed, only the line where what follows matches
>    > is searched, and one line before that (if there is one).

It would work in many cases though, like in this example.  But not
when the part before \zs matches more than one line.

> If it's not possible to change the behavior this late,

I looked into changing this, and it's not too difficult.  However, the
behavior is strange.  The pattern is tried for every line in the global
range, and when it matches it might set the mark for another line.  This
may actually be outside of the range.  Is the mark still set then?

It would not be backwards compatible, but who would use \zs with :global
right now, since it has no effect?  So it might not matter.

> maybe we could document the pitfall.  I couldn't find anything
> relevant at [`:help
> :global`](https://vimhelp.org/repeat.txt.html#%3Aglobal).  The help
> does say:
> 
>    > (for a multi-line pattern, only the start of the match matters).
> 
> But in the first example, the start of the match is `ccc` as specified by `\zs`.  So one could assume that `:global` would mark and delete the `bbbccc` lines, not the `aaa` lines.
> 
> Either the help means "only the start of the pattern matters":
> ```diff
> diff --git a/runtime/doc/repeat.txt b/runtime/doc/repeat.txt
> index 56e9ad82f..b571d3ecc 100644
> --- a/runtime/doc/repeat.txt
> +++ b/runtime/doc/repeat.txt
> @@ -76,7 +76,7 @@ examples.
>  
>  The global commands work by first scanning through the [range] lines and
>  marking each line where a match occurs (for a multi-line pattern, only the
> -start of the match matters).
> +start of the pattern matters).
>  In a second scan the [cmd] is executed for each marked line, as if the cursor
>  was in that line.  For ":v" and ":g!" the command is executed for each not
>  marked line.  If a line is deleted its mark disappears.
> ```
> Or we should mention that an exception is made for `\zs`:
> ```diff
> diff --git a/runtime/doc/repeat.txt b/runtime/doc/repeat.txt
> index 56e9ad82f..02d4dc0dd 100644
> --- a/runtime/doc/repeat.txt
> +++ b/runtime/doc/repeat.txt
> @@ -75,8 +75,9 @@ NOTE [cmd] may contain a range; see |collapse| and |edit-paragraph-join| for
>  examples.
>  
>  The global commands work by first scanning through the [range] lines and
> -marking each line where a match occurs (for a multi-line pattern, only the
> -start of the match matters).
> +marking each line where a match occurs.  For a multi-line pattern, only the
> +start of the match matters; however, if the pattern uses |/\zs| to match after
> +the first line, the latter is marked (not the line where "\zs" matches).
>  In a second scan the [cmd] is executed for each marked line, as if the cursor
>  was in that line.  For ":v" and ":g!" the command is executed for each not
>  marked line.  If a line is deleted its mark disappears.
> ```

I wonder when using \zs with :global would be useful.  If we have a good
example then we might have a reason to make it work.  If not, then
adjusting the help would be a better solution.

-- 
"The amigos also appear to be guilty of not citing the work of others who had
gone before them.  Even worse, they have a chapter about modeling time and
space without making a single reference to Star Trek!"
			(Scott Ambler, reviewing the UML User Guide)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> I wonder when using \zs with :global would be useful.  If we have a good
   > example then we might have a reason to make it work.  If not, then
   > adjusting the help would be a better solution.

I have a mapping which deletes all the lines matching the last search.  It relies on the `:global` command, and executes something like this:

    :execute 'global ;' .. @/ .. '; delete'

Most of the time it works as expected.  But if the last search is a multi line pattern containing `\zs`, it deletes unexpected lines.  I guess I should make it bail out in that case.
