### ISSUE TITLE
line2byte() gives wrong values with text properties

### ISSUE THREAD

**Issue by bfredl** [vim/vim#3718]
Create a buffer with some simple text:

    line1
    line2

Now execute commands:

    echo line2byte(3) " => 13
    call prop_type_add('mytype', {'highlight': 'Statement'})
    call prop_add(2,1,{'end_col': 5, 'type':'mytype'})
    echo line2byte(3) " => 33

Expected behavior: both `line2byte(3)` calls give the same value, as text hasn't changed.

Actual behavior: `line2byte(3)` increases, as internal text prop storage is counted.

vim version: 8.1.0635 (--with-features=huge  --enable-terminal --enable-luainterp)

**Comment by bfredl** [comment]
Another minor issue related to prop_add: `prop_add(2,1, ...)` as above highlights from the _second_ char on the line, however `prop_add(2,0, ...)` is considered an error. So either way, highlighting first char on line is not possible.

**Comment by brammool** [comment]
Bjorn Linse wrote:

> Another minor issue related to prop_add: `prop_add(2,1, ...)` as above
> highlights from the _second_ char on the line, however `prop_add(2,0, ...)`
> is considered an error. So either way, highlighting first char on line is not
> possible.

Thanks for noticing.  It was working at some point, must have changed at some
point.  There is a TODO item for a screenshot text, that would have caught
this.

-- 
hundred-and-one symptoms of being an internet addict:
43. You tell the kids they can't use the computer because "Daddy's got work to
    do" and you don't even have a job.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by sam-mccall** [comment]
I'm not sure the fix for this was correct/complete: see #5930

In particular `ml_find_line_or_offset` seems to get the right answer on line boundaries, so `line2byte()` works, but not at other offsets, so `:goto` is broken.
