### ISSUE TITLE
Do we have a user config / your config section ?

### ISSUE THREAD

**Issue by awalvie** [vim/vim#3722]
I was wondering if VIM has a show off your config or a user config section where beginner and even experienced users could take some inspiration for their own vim config and in general just share their configs around with other people ?

**Comment by chrisbra** [comment]
Not known to me. You better ask on the reddit forum or the vim-use mailinglist. This here is for bug reports only. Sorry.

**Comment by tonymec** [comment]
AFAIK, there is no central point where people list and compare their several configs.

The config I use for my Huge Linux builds can be seen at http://users.skynet.be/antoine.mechelynck/vim/compunix.htm ; since nowadays I build Vim in all five of Huge, Big, Normal, Small and Tiny featuresets, I have four additional configs which I haven't posted on the Net because I never thought they would be interesting. Even my Huge config is there only as an example from which anyone building Vim could (and should) develop his or her own config.

Best regards,
Tony.

**Comment by nuko8** [comment]
Perhaps, Vim is rather a raw material than a finished product, and that's why it attracts a lot of interest because raw materials have an infinite potential to make the users' dreams come true.  In general, raw materials are hardly sold with any instructions for proper use, don't they? :)

**Comment by tonymec** [comment]
> Perhaps, Vim is rather a raw material than a finished product, and that's why it attracts a lot of interest because raw materials have an infinite potential to make the users' dreams come true. In general, raw materials are hardly sold with any instructions for proper use, don't they? :)

If that's the case, Vim is rather unusual as raw materials go: indeed, it comes with a lot of «instructions for use», in the form of both the online help (instructions about *using* Vim) and of the comments in the Makefile (instructions about *building* Vim).

However, you talked about instructions for *proper* use. What is «proper» use of Vim? It is a well-known fact (and a fact much liked by long-time users) that in most cases there are several ways to obtain a given result with Vim, so I could argue that there is no single «proper» use of Vim, not even about using hjkl vs. ←↓↑→ to move the cursor. :wink: 

Best regards,
Tony.
