### ISSUE TITLE
Completion for ":cd" from 'cdpath'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#374]
```
The `cd` command should consider the `cdpath` setting for completion of 
relative paths.

Currently the completion appears to use only the current working directory when 
completing relative paths.

This means that `:cd foo<Tab>` should complete `foobar` if there exists 
`/path/in/cdpath/foobar` (and `/path/in/cdpath` is in `cdpath`).
```

Original issue reported on code.google.com by `dhahler@gmail.com` on 15 Jun 2015 at 6:55

**Comment by teoljungberg** [comment]
Is this something that would be considedred to get merged into vim before I or someone else puts in the effort into implementing it?

**Comment by brammool** [comment]
> Is this something that would be considedred to get merged into vim
> before I or someone else puts in the effort into implementing it?

It's always nice when completion suggests all the matching values
correctly.

-- 
TALL KNIGHT: When you have found the shrubbery, then you must cut down the
             mightiest tree in the forest ... with a herring.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teoljungberg** [comment]
I have the following custom commands with completion in viml, and I presume this should be implemented natively in C?

Any suggestions or pointers for where I can start?

**Comment by brammool** [comment]
> I have the following custom commands with completion in viml, and I
> presume this should be implemented natively in C?
> 
> Any suggestions or pointers for where I can start?

Yes, best is to implement this in C.

In vim.h you can find EXPAND_FILES_IN_PATH, which is like EXPAND_FILES
and using the 'path' option.  Similarly there would be
EXPAND_DIRS_IN_PATH instead of EXPAND_DIRECTORIES, and using 'cdpath'.
This code is in cmdexpand.c, e.g. set_context_by_cmdname().  But search
for all occurences of EXPAND_DIRECTORIES and check what needs to be done
for EXPAND_DIRS_IN_PATH.

I can't find a very good example, but parts that are needed are in the
findfile.c source file.  Probably you need to modify
ExpandFromContext(), which calls expand_files_and_dirs().  And probably
some lower level functions.

-- 
TIM: To the north there lies a cave,  the cave of Caerbannog, wherein, carved
     in mystic runes, upon the very living rock, the last words of Olfin
     Bedwere of Rheged make plain the last resting place of the most Holy
     Grail.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
