### ISSUE TITLE
DiffUpdated is not triggered when diffopt does not include 'internal'

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#3741]
The DiffUpdated event has been added in patch 8.1.0397.
Since then, when some text is changed on diff mode,
the event should be triggered.
However, if 'internal' is excluded from diffopt option,
the event does not happen.

Here is a simple step to produce the problem
on patch 8.1.0664 and also 8.1.0410.

$gvim -u NONE

Add 'abcde' in Window A.
Add 'aBCDe' in Window B.

:windo diffthis
-> 'bcd' abd 'BCD' are colored in DiffText
:autocmd DiffUpdated * echo localtime()

Then, when 'a' is deleted on Window A, a localtime is echoed.

:set diffopt-=internal

Then, nothing is echoed even when 'a' is deleted on Window A.

:set diffopt+=internal

Then, when 'a' is deleted on Window A, a localtime is echoed.

**Comment by brammool** [comment]
> The DiffUpdated event has been added in patch 8.1.0397.
> Since then, when some text is changed on diff mode,
> the event should be triggered.
> However, if 'internal' is excluded from diffopt option,
> the event does not happen.
> 
> Here is a simple step to produce the problem
> on patch 8.1.0664 and also 8.1.0410.
> 
> $gvim -u NONE
> 
> Add 'abcde' in Window A.
> Add 'aBCDe' in Window B.
> 
> :windo diffthis
> -> 'bcd' abd 'BCD' are colored in DiffText
> :autocmd DiffUpdated * echo localtime()
> 
> Then, when 'a' is deleted on Window A, a localtime is echoed.
> 
> :set diffopt-=internal
> 
> Then, nothing is echoed even when 'a' is deleted on Window A.
> 
> :set diffopt+=internal
> 
> Then, when 'a' is deleted on Window A, a localtime is echoed.

I think this is correct.  What happens is that when "internal" is
included in 'diffopt', it actually updates the diffs, since this will be
fast.  When an external diff is used, Vim doesn't actually invoke it for
small changes.  It just guesses what the effect of the change will be.
When you do :diffupdate it will actually update the diffs.

This mostly reflects what some plugins did with the FilterReadPost
event.  I don't think ther is a reason to trigger on any text change.

-- 
From "know your smileys":
 =):-)	Uncle Sam

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
