### ISSUE TITLE
vim should not warn about unsaved content when opening stdin in readonly mode

### ISSUE THREAD

**Issue by mqudsi** [vim/vim#3763]
The following should exit without a prompt:

```
shuf /usr/share/dict/words -n 200 | vim +"set readonly" -
:q<CR>
```

but currently throws error 37:

```
E37: No write since last change (add ! to override)
```

**Comment by vim-ml** [comment]
On 2019-01-04, Mahmoud Al-Qudsi wrote:
> The following should exit without a prompt:
> 
> shuf /usr/share/dict/words -n 200 | vim +"set readonly" -
> :q<CR>
> 
> but currently throws error 37:
> 
> E37: No write since last change (add ! to override)

Readonly or not, it's still true that the buffer has not been
written since it was last changed.  You would see the same message
if you ran view (or "vim -R" or "vim +'set readonly'"), made changes
to the buffer, and tried to exit with :q.

I have the following in my vimrc to avoid this problem.

    " Fix the problem where when vim reads from stdin, it marks the
    " buffer as modified so that you have to quit with :q!.
    "
    autocmd StdinReadPost * set nomodified

Regards,
Gary

**Comment by brammool** [comment]
Right, this works as intended.  Vim doesn't know whether the input can be discarded without losing valuable data.
