### ISSUE TITLE
Scrolling not working in :terminal

### ISSUE THREAD

**Issue by chrisvacc** [vim/vim#3769]
Disabled all plugins, still nothing. xterm vim and GUI vim.

(white = GUI, black = xterm)

Video of issue: https://www.youtube.com/watch?v=6bIgYrVb-Fw 

Note: scrolling in `:terminal` scrolls through my previous commands

**Comment by nuko8** [comment]
> Note: scrolling in :terminal scrolls through my previous commands

That suggests that you were in Terminal-Job mode when you tried to scroll a certain window.

Are you sure you switched to Terminal-Normal mode from Terminal-Job mode by typing CTRL-W_N before you started scrolling with the mouse?  See `:help Terminal-Mode`.  Also, please note that this issue tracker is not supposed to ask how to use Vim.

**Comment by chrisvacc** [comment]
Apologies, I thought this was an issue, not a ‘how to use vim’ question.

I can switch to NORMAL mode with ctrl+\, ctrl+n. ctrl+w, ctrl+n creates a new window

But switching to NORMAL mode works. Thanks.

**Comment by nuko8** [comment]
OK, this issue has just been closed.  So some superfluousness may have been allowed since then :)

@chrisvacc 

> ctrl+w, ctrl+n creates a new window

Right.  But it looks to me that you are confusing `CTRL-W_N` with `ctrl+w, ctrl+n`; the former conforms to the notational conventions which are used throughout `:help` manual (See `:help notation`) and is interpreted into `ctrl+w, N` (not into `ctrl-w, n`) in the notational conventions you are following, while the latter is rewritten as `CTRL-W_CTRL-N` in our notational conventions.  Try `:help CTRL-W_CTRL-N` and compare the result with those of `:help CTRL-W_N` and `:help CTRL-W_n`.  I'm sure you'll get some idea about how helpful `:help` is.

**Comment by chrisvacc** [comment]
I’ll check it out, but I just tried CTRL+W, N in other words ctrl+w, n / not ctrl+w, ctrl+n still opens a new window. ctrl+w (let go of ctrl), n ... maybe it’s a plugin. But again ctrl+\, ctrl+n works, so I’ll just use that. And yes, the vim help does seem very helpful! Especially in comparison to [useless R help](https://i.imgur.com/wNoskVe.jpg) I’m used to.

Thanks.

**Comment by k-takata** [comment]
The `N` must be upper case, not ctrl+w, n.
