### ISSUE TITLE
TextChanged is triggered if defined via BufWritePost

### ISSUE THREAD

**Issue by blueyed** [vim/vim#3772]
Given t.vim:
```vim
" Ensure no TextChanged plugin is loaded.
set noloadplugins
let g:loaded_matchparen = 1

augroup test
function! OnBWP() abort
    autocmd TextChanged * echom 'TC'
endfunction
autocmd BufWritePost * call OnBWP()
augroup END

normal! o
exe 'w' tempname()
```

Running `vim -u t.vim` results in "TC" in `:messages`.

The `TextChanged` autocommand is configured during the `BufWritePost` autocommand, which results in it being triggered although the text was not changed.

Related/similar patch: v8.0.1633 (8c64a36e4).

**Comment by brammool** [comment]
> Given t.vim:
> ```vim
> " Ensure no TextChanged plugin is loaded.
> set noloadplugins
> let g:loaded_matchparen = 1
> 
> augroup test
> function! OnBWP() abort
>     autocmd TextChanged * echom 'TC'
> endfunction
> autocmd BufWritePost * call OnBWP()
> augroup END
> 
> normal! o
> exe 'w' tempname()
> ```
> 
> Running `vim -u t.vim` results in "TC" in `:messages`.
> 
> The `TextChanged` autocommand is configured during the `BufWritePost`
> autocommand, which results in it being triggered although the text was
> not changed.
> 
> Related/similar patch: v8.0.1633 (8c64a36e4).

Is that really related to using BufWritePost ?
I would think that whenever a buffer was changed, there was no
TextChanged event, and then a TextChanged event is added, then the event
triggers very soon, because of the changes made to the buffer.

Thus your statement "the text was not changed" is incorrect, since the
"o" command did change the text.

I don't think this is a real problem.  If you want more control over the
changes you want to keep track of, use b:changedtick.  You could store
the value in your BufWritePost event.

-- 
You cannot have a baby in one month by getting nine women pregnant.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
The `o` command happens before `TextChanged` is defined.

I am checking `b:changedtick` now also additionally, but I still consider it to be a bug that an event gets emitted for something in the past (before it gets listened to).

**Comment by blueyed** [comment]
I have not checked the code, but this might be related to `TextChanged` only being looked at in the "event loop", and the above (`o` command and `BufWritePost`) might happen in the same loop?!

**Comment by brammool** [comment]
Daniel Hahler wrote:

> The `o` command happens before `TextChanged` is defined.

That is not relevant.  I don't think the help says that the change is
supposed to happen after the autocommand was defined.  It only says it's
triggered after the text changed.

From the implementation side, Vim remembers the last "changedtick" when
the event was triggered.  This is only updated when actually triggering
the event, since it can be skipped (e.g. when there is typeahead).  And
this whole part is skipped when there are no TextChanged events.

It would be possible to update the last "changedtick" when no
TextChanged events exist, but then the behavior depends on whether there
already is some TextChanged event, which you have no control over.

So if we would need to only trigger after a TextChanged event is
defined, we would need to store the value of "changedtick" for each
TextChanged autocommand.  That makes things much too complicated.

> I am checking `b:changedtick` now also additionally, but I still
> consider it to be a bug that an event gets emitted for something in
> the past (before it gets listened to).

Not really, it's doing what it is supposed to do.  I can understand you
have this expectation, but as mentioned above, meeting those
expectations is very hard.  And since you can make it work, I don't
think we need to change this.

-- 
hundred-and-one symptoms of being an internet addict:
129. You cancel your newspaper subscription.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
Ok, thanks for the explanation - closing.
