### ISSUE TITLE
cursorline option is preserved after preview

### ISSUE THREAD

**Issue by chemzqm** [vim/vim#3813]
Cursorline option seems not cleared after `:pclose`.

Step to reproduce:

* `vim -u NORC`
* Open an exist file with `pedit +setl\ cul foo`
* Close preview window by `:pclose`
* Open the file again by `:edit foo`

the cursorline appears, but since cursorline option is localed to window, I would expect it's cleared after `:pclose`.

Tested with vim 8.1.635.

**Comment by brammool** [comment]
This is intended, read the section at ":help local-options":

When editing a buffer that has been edited before, the options from the window
that was last closed are used again.  If this buffer has been edited in this
window, the values from back then are used.  Otherwise the values from the
last closed window where the buffer was edited last are used.
