### ISSUE TITLE
Command history and incsearch

### ISSUE THREAD

**Issue by eevan78** [vim/vim#3837]
Hi,
here is an issue that I spotted.

In my command history I have an Ex command that operates on a visual range ('<'>). I open a new file to edit. Visual range was never set on this file. I use :<Up> to access previously used commands, and when '<'> command comes in command line, it triggers E20. It could be related to incsearch option that is set by defaults.vim

![error](https://user-images.githubusercontent.com/27575106/51524622-f72ddc80-1e47-11e9-8b01-e4871b1daf81.png)

Vim version is 8.1.784

**Comment by brammool** [comment]
> here is an issue that I spotted.
> 
> In my command history I have an Ex command that operates on a visual
> range ('<'>). I open a new file to edit. Visual range was never set on
> this file. I use :<Up> to access previously used commands, and when
> '<'> command comes in command line, it triggers E20. It could be
> related to incsearch option that is set by defaults.vim
> 
> ![error](https://user-images.githubusercontent.com/27575106/51524622-f72ddc80-1e47-11e9-8b01-e4871b1daf81.png)
> 
> Vim version is 8.1.784

I can reproduce it.

-- 
Life would be so much easier if we could just look at the source code.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
FWIW, I handle the issue with this autocmd:

    augroup fix_E20
        au!
        au CmdlineEnter : if ! line("'<")
            \ |     call setpos("'<", [0,line('.'),col('.'),0])
            \ |     call setpos("'>", [0,line('.'),col('.'),0])
            \ | endif
    augroup END

Whenever the command-line is entered, it checks whether the visual marks are set; if they are not, it sets them on the current cursor position.

---

However, it doesn't fix the issue entirely.
The latter can be triggered by other marks, and sometimes be raised multiple times for the same command (every time you edit a command-line with an unset mark):

    $ vim -Nu NONE -i NONE +'set is'
    :'ss/p
    :'ss/pa
    :'ss/pat
    ...

Here, `E20` is raised when you insert `p`, then `a`, then `t`, ...

One way to fix the issue entirely would be to set all unset marks when the command-line is entered:

    augroup fix_E20
        au!
        au CmdlineEnter : call s:fix_e20()
    augroup END
    fu s:fix_e20() abort
        let marks = range(48, 57) + range(65, 90) + range(97, 122)
        let marks = map(marks, {_,v -> nr2char(v)})
        let marks += ['<', '>', '[', ']', '^', '.']
        let [lnum, col] = getpos('.')[1:2]
        let l:Set_marks = {_,v -> getpos("'"..v) == [0,0,0,0] && setpos("'"..v, [0,lnum,col,0])}
        call map(marks, l:Set_marks)
    endfu

But that seems too much; so instead, I'm experimenting with this:

    augroup fix_E20
        au!
        au CmdlineEnter : if ! line("'<")
            \ |     call setpos("'<", [0,line('.'),col('.'),0])
            \ |     call setpos("'>", [0,line('.'),col('.'),0])
            \ | endif
        au CmdlineChanged,CmdlineLeave : call s:fix_e20()
    augroup END
    fu s:fix_e20() abort
        if v:errmsg is# 'E20: Mark not set' && !exists('s:incsearch_save')
            let v:errmsg = ''
            let s:incsearch_save = &incsearch
            set nois
            au CmdlineLeave : ++once let &is = s:incsearch_save
            \ | unlet! s:incsearch_save
            \ | call histdel(':', histget(getcmdline()))
        endif
    endfu

It still fixes `E20` for the visual marks, but not for the other ones.
However, it prevents `E20` from being raised again and again for the same command by temporarily resetting `'incsearch'` (it should set it again when the command-line is left).

Using the same example as before:


    $ vim -Nu <(cat <<'EOF'
    augroup fix_E20
        au!
        au CmdlineEnter : if ! line("'<")
            \ |     call setpos("'<", [0,line('.'),col('.'),0])
            \ |     call setpos("'>", [0,line('.'),col('.'),0])
            \ | endif
        au CmdlineChanged,CmdlineLeave : call s:fix_e20()
    augroup END
    fu s:fix_e20() abort
        if v:errmsg is# 'E20: Mark not set' && !exists('s:incsearch_save')
            let v:errmsg = ''
            let s:incsearch_save = &incsearch
            set nois
            au CmdlineLeave : ++once let &is = s:incsearch_save
            \ | unlet! s:incsearch_save
            \ | call histdel(':', histget(getcmdline()))
        endif
    endfu
    EOF
    ) -i NONE +'set is'
    :'ss/p
    :'ss/pa
    :'ss/pat
    ...

`E20` is only raised when `p` is inserted; not afterward. So you can insert `a`, `t`, ... without being interrupted on each keystroke; and later you can press `C-b` to move to the start of the command-line, and fix the line specifier.

Besides, the code prevents the command from being saved in the history. Otherwise, when you would quit the command-line (no matter how: `Escape`, `C-c`, `Enter`) while the latter contains a command with an unset mark, it would be saved in the history. Then, when you would press `Up` to retrieve another old command, you might get back to the buggy command and `E20` could be raised again.
