### ISSUE TITLE
Unable to get text change event for a background highlighter

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#4028]
I am trying to use text properties to write a background highlighter for c/c++, it is implemented as a separated executable and will communicate with vimscript via json rpc.

But when people is editing, it is hard to know the modified text and unable to calculate what properties should be created and what properties should be removed.

Any example for this ??

**Comment by brammool** [comment]
This has not been implemented yet.  There isn't even a design yet.  It's not obvious how to do it, since it is asynchronous, thus another change can be made before an update is done for an earlier change.  And a change in one position may result in a text property change in another position (e.g. highlighting an unbalanced "if".
We don't need an issue for this, thus closing.  We can discuss solutions on the vim-dev maillist.
