### ISSUE TITLE
Substitute command modifies buffer when error is thrown inside sub-replace-expression

### ISSUE THREAD

**Issue by ggandor** [vim/vim#4161]
```vim
" aaa bbb aaa
" aaa

fun! Foo()
    throw 'error'
endfun

try
    %s/aaa/\=Foo()/g
catch 'error'
    echo 'error caught'
endtry
```

Running this will replace the matches on line 1 with an empty string, notwithstanding the error - in general, the matches on the first matching line will always be replaced by an empty string, the others remain untouched.

Experimented a little more with it: if e.g. I force an `E471` inside `Foo` (`throw` without arguments), or write some gibberish to get an `E492`, then the behavior is the same, but when I run the substitute command without a try-catch wrap, then in these cases _all_ of the matches will be substituted by a 0 (the custom error does the same as before).

A real-life case where I ran into this: <https://stackoverflow.com/questions/54619021/vim-substitutes-empty-string-when-exception-is-thrown-inside-sub-replace-express>

**Comment by brammool** [comment]
So, what is the problem?  If you use try-catch then errors will be handled differently, since that's what you asked for.

**Comment by ggandor** [comment]
Sorry if I was not clear enough: the problem is the buffer modification itself (in both cases) when - ideally - nothing should happen (since an error has been thrown, there's no proper value to substitute with, but a substitution happens anyway).

**Comment by brammool** [comment]
> Sorry if I was not clear enough: the problem is the buffer
> modification itself (in both cases) when - ideally - nothing should
> happen (since an error has been thrown, there's no proper value to
> substitute with, but a substitution happens anyway).

Well we could do something like this, but I wonder if it will cause
trouble:

--- ../../git/vim81/src/ex_cmds.c	2019-03-17 16:59:38.586201879 +0100
+++ ex_cmds.c	2019-03-24 22:26:56.525595616 +0100
@@ -5574,7 +5574,12 @@
 				    sub_firstlnum - regmatch.startpos[0].lnum,
 				    sub, sub_firstline, FALSE, p_magic, TRUE);
 #ifdef FEAT_EVAL
-		/* Don't keep flags set by a recursive call. */
+		// If getting the substitute string caused an error, don't do
+		// the replacement.
+		if (aborting())
+		    goto skip;
+
+		// Don't keep flags set by a recursive call.
 		subflags = subflags_save;
 		if (subflags.do_count)
 		{

-- 
Two percent of zero is almost nothing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by inkarkat** [comment]
In addition to not modifying the buffer, any further calls to the replacement-expression should be stopped, too. After all, that's the purpose of throwing an exception: Getting out of the current context, which here is the loop-like invocation from `:substitute`. That would save the replacement-expression from maintaining an `s:isAborted` state itself. (I actually had to implement such workarounds in some of my plugins due to the current behavior.)

So, if a replacement-expression `:throw`s an exception, there should be no further invocations from the same `:substitute` command, neither from the `/g` flag nor from additional lines in `[range]`. Previous (successful) invocations and replacements should be kept; if the exception happens on the first replacement, the buffer should not be modified by the command at all.

**Comment by brammool** [comment]
> In addition to not modifying the buffer, any further calls to the
> replacement-expression should be stopped, too. After all, that's the
> purpose of throwing an exception: Getting out of the current context,
> which here is the loop-like invocation from `:substitute`. That would
> save the replacement-expression from maintaining an `s:isAborted`
> state itself. (I actually had to implement such workarounds in some of
> my plugins due to the current behavior.)
> 
> So, if a replacement-expression `:throw`s an exception, there should
> be no further invocations from the same `:substitute` command, neither
> from the `/g` flag nor from additional lines in `[range]`. Previous
> (successful) invocations and replacements should be kept; if the
> exception happens on the first replacement, the buffer should not be
> modified by the command at all.

That already happens, since the main loop in do_sub() checks aborting().
That's also why using the try-catch or :throw only changes one line,
instead of all lines.

-- 
An actual excerpt from a classified section of a city newspaper:
"Illiterate?  Write today for free help!"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> That already happens, since the main loop in do_sub() checks aborting(). That's also why using the try-catch or :throw only changes one line, instead of all lines.

But shouldn't we undo the wrongly replaced empty line in case of an exception/error?

**Comment by brammool** [comment]
Christian wrote:

> > That already happens, since the main loop in do_sub() checks
> > aborting(). That's also why using the try-catch or :throw only
> > changes one line, instead of all lines.
> 
> But shouldn't we undo the wrongly replaced empty line in case of an
> exception/error?

What wrongly placed empty line?  With the check for aborting() nothing
is substituted.

-- 
There are three kinds of persons: Those who can count and those who can't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
