### ISSUE TITLE
Potential regression when reading tags files

### ISSUE THREAD

**Issue by mhinz** [vim/vim#4200]
**Describe the bug**

[8.1.1094](https://github.com/vim/vim/commit/5209334c551778fe6f76945f373ee14fcac96f52) introduced a small regression. Actually, I'm not sure if there's an official format for tags files, but before that patch, tags files without a trailing newline would work as well. Now, after 8.1.1094, the last line isn't read anymore if there's no newline.

**To Reproduce**

```
$ printf "foo\tfile\t100" > test.tags
$ vim -u NONE -N +'set tags=test.tags | echo taglist(".*")'
```

This echoes `[]`.

**Expected behavior**

It echoes `[{'cmd': '4', 'static': 0, 'name': 'foo', 'kind': '', 'filename': 'Xtest'}]`, like it did before 8.1.1094.

**Environment (please complete the following information):**
 - Vim 8.1.1094
 - OS: macOS 10.14.4
 - Terminal: iTerm2

**Addtional info:**

This was caught with a Nvim test that didn't add the trailing newline to the temporary tags file. Now, I expect all common tags generators to add a newline anyway, so it's up to you to decide whether this is a regression or not.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> [8.1.1094](https://github.com/vim/vim/commit/5209334c551778fe6f76945f373ee14fcac96f52) introduced a small regression. Actually, I'm not sure if there's an official format for tags files, but before that patch, tags files without a trailing newline would work as well. Now, after 8.1.1094, the last line isn't read anymore if there's no newline.
> 
> **To Reproduce**
> 
> ```
> $ printf "foo\tfile\t100" > test.tags
> $ vim -u NONE -N +'set tags=test.tags | echo taglist(".*")'
> ```
> 
> This echoes `[]`.
> 
> **Expected behavior**
> 
> It echoes `[{'cmd': '4', 'static': 0, 'name': 'foo', 'kind': '', 'filename': 'Xtest'}]`, like it did before 8.1.1094.
> 
> **Environment (please complete the following information):**
>  - Vim 8.1.1094
>  - OS: macOS 10.14.4
>  - Terminal: iTerm2
> 
> **Addtional info:**
> 
> This was caught with a Nvim test that didn't add the trailing newline
> to the temporary tags file. Now, I expect all common tags generators
> to add a newline anyway, so it's up to you to decide whether this is a
> regression or not.

This was an intentional change to check for a missing NL, which normally
means the line is too long to handle.

Well, we could detect that on EOF the NL is missing and put it back.
That would be in vim_fgets().  Not sure if this has side effects, but I
would not expect so.

Can you turn that example into a failing test?

-- 
If Microsoft would build a car...
... The airbag system would ask "are you SURE?" before deploying.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mhinz** [comment]
The following test fails for 8.1.1094 and upwards:

```diff
diff --git i/src/testdir/test_taglist.vim w/src/testdir/test_taglist.vim
index de9ca0c80..9c680f661 100644
--- i/src/testdir/test_taglist.vim
+++ w/src/testdir/test_taglist.vim
@@ -98,3 +98,13 @@ func Test_tagfiles()
   call delete('Xtags2')
   bd
 endfunc
+
+func Test_tagsfile_without_trailing_newline()
+  call writefile(["Foo\tfoo\t1"], 'Xtags', 'b')
+
+  let tl = taglist('.*')
+  call assert_equal(1, len(tl))
+  call assert_equal('Foo', tl[0].name)
+
+  call delete('Xtags')
+endfunc
```
