### ISSUE TITLE
"not in Vi" remarks in help are no longer useful?

### ISSUE THREAD

**Issue by brammool** [vim/vim#4268]
In the help files there are quite a few {not in Vi} notes.  I wonder if these are still useful, now that Vim is more or less the standard, and the original Vi is hard to find.  The help is easier to read without them.

An alternate solution would be {Vi compatible} in places where the command was already supported by Vi.  But then, is this useful?  If someone really wants to know, there probably is a place on the internet where this info can be found.

**Comment by tonymec** [comment]
Well, yes, Vim is more or less the standard, and what many Linux distros distribute under the executable name "vi" is often actually some version of Vim, possibly (if several versions are installed) a stripped-down version.

OTOH, the `{not in Vi}` notes help people who, like me, never knew Legacy Vi to realize where we come from and how much Vim is actually "improved" compared to its predecessor. I vote to keep them, IMHO they do no harm, and they add some history background which people like me would find interesting.

Best regards,
Tony.

**Comment by chdiza** [comment]
I think they should be kept.

> If someone really wants to know, there probably is a place on the internet where this info can be found

Why make a user go googling for that instead of keeping that information in the obvious place?

**Comment by lieryan** [comment]
I don't find them useful, of historical interest maybe, but never really useful. Personally, I won't miss them if they're removed completely.

If people are really interested in preserving the history in Vim's documentation, a {Vi compatible} marker makes maintaining the documentation easier than with {not in Vi}, as the original vi's feature set is nowadays effectively set in stone, while Vim's feature set keeps evolving.

**Comment by chrisbra** [comment]
regarding to finding the documentation on the internet: If I am interested to find out about vi, I usually look up vi and ex commands in the POSIX documentation:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html

But the official POSIX documentation and the actual vi implementation might still be different things and I haven't found a good resource on the internet about it. So yes, I find it valuable and I would leave them in, because I always find it interesting to see what can be expected in other vi clones.

However if it turns out to be much of a burden, I am all with Gary's suggestion and add vi compatible commands in a separate help document.

**Comment by tonymec** [comment]
Gary's comment (which seems to have been deleted :-( ) was new to me when I saw it, and it looked at the time like an interesting idea, so I agree with Chris: leave them in if it isn't too much of a burden, or move them to some new helpfile, maybe doc/vi.txt or whatever, if it is.

Best regards,
Tony.

**Comment by chrisbra** [comment]
> Gary's comment (which seems to have been deleted :-( )

No, it only went to the vim list: https://groups.google.com/d/msg/vim_dev/FBfLwwtJj8o/i5xFKAGRBgAJ

**Comment by nuko8** [comment]
IMHO, Vim has been matured enough to let those who are creating or developing vi-like or other types of text editors consider writing __{not in Vim}__ instead of {not in Vi} in their text editors'  manual to distinguish theirs from Bram's instead of legacy but still great Bill Joy's.  Maybe, removing {not in Vi} from Vim's manual would encourage people to consider a new possibility nowadays that we are now in a new phase up to a better future of vi-like text editors and encourage everyone involved to step forward further for improving __vim-like__ text editors, and that's should be beneficial to everyone these days.  Unless writing or editing new help files carries much burden to someone, I like Gary's thoughts much.

**Comment by craigmac** [comment]
Why not move all of them to a separate vi-compatibility.txt help file of some kind which just has a list of them all for quick reference if someone needs to know which ones are not compatible?

**Comment by brammool** [comment]
> Why not move all of them to a separate vi-compatibility.txt help file
> of some kind which just has a list of them all for quick reference if
> someone needs to know which ones are not compatible?

Since the list of Vi commands and features does not change, this would
be the simplest solution.  The vi_diff.txt help file is the right place,
since it already mentions differences between Vi and Vim.  It already
has a list of command line arguments.


-- 
   LAUNCELOT leaps into SHOT with a mighty cry and runs the GUARD through and
   hacks him to the floor.  Blood.  Swashbuckling music (perhaps).
   LAUNCELOT races through into the castle screaming.
SECOND SENTRY: Hey!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closed as of https://github.com/vim/vim/commit/6c60f47fb9251e686217d51cf81847e14d0dd26d

**Comment by brammool** [comment]
Wait, I only did the options so far, still a lot more commands to do.
