### ISSUE TITLE
-- INSERT -- message is not cleared after leaving insert mode

### ISSUE THREAD

**Issue by xaizek** [vim/vim#4269]
Commit cb574f415486adff645ce384979bfecf27f5be8c

    patch 8.1.0822: peeking and flushing output slows down execution
    
    Problem:    Peeking and flushing output slows down execution.
    Solution:   Do not update the mode message when global_busy is set.  Do not
                flush when only peeking for a character. (Ken Takata)

has broken clearing `-- INSERT --` message after leaving insert mode if `<esc>` is mapped in insert mode.

**To Reproduce**

1. Run `vim --clean`
2. `:inoremap <esc> <esc>jk`
3. Enter insert mode (say, `i`)
4. Leave insert mode by pressing `<esc>`

**Expected behavior**

No message on status line.

**Actual behavior**

Status line still says `-- INSERT --`.

**Environment**

 - Vim version >= 8.1.0822
 - OS: shouldn't matter
 - Terminal: shouldn't matter

**Comment by tonymec** [comment]
I confirm the problem with Vim 8.1.1165 on openSUSE Linux 15.0, in all three of gvim (GTK2), Vim in konsole and Vim in the Linux non-X terminal (Ctrl-Alt-F2). The mapping is essential, without that mapping the problem is absent. In some cases (see below) hitting the remapped <Esc> key produces a beep; "normal" mode keys work after the beep, and in gvim the cursor is the Normal-mode cursor shape, even though --INSERT-- is still displayed at the bottom. This even happens after hitting `<Enter>` several times in Insert mode then `<Up>` a few times to avoid having the remapped j (part of the {lhs} happen on the last line of the file.

Beeps are produced:
- never in konsole
- on the last line of the buffer or in an empty buffer in gvim
- even when hitting `<Up>` anywhere in Vim in the Linux console; this has the side-effect of going to Normal mode without clearing the --INSERT-- indication, as shown e.g. by the fact that hitting : makes it appear on the command-line (belatedly clearing --INSERT--), not at the cursor in the buffer. I assume that in this last case the Ctrl-[ in the ^[[A keycode for `<Up>` is remapped.

Best regards,
Tony.
