### ISSUE TITLE
Having a BufReadPre autocommand scrolls other windows on ":edit"

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4294]
```vim
autocmd BufReadPre * echom 'AU'

function! Test()
  call append(0, range(100))
  exe 'w' tempname()
  normal! 50gg
  split
  normal! 100gg
  " edit
endfunction
```

When calling `edit` at the end of the test setup (or manually) will scroll the buffer in the other window to the top.

This does not happen without the BufReadPre autocommand.

**Comment by chrisbra** [comment]
This happens, because in `do_ecmd` the memfile will be closed and the containing buffer struct will be reset prior to reloading the buffer from disk. Later in `readfile()` we call the `BufReadPre` autocommand. Part of calling the autocommands is to check the cursor position `check_lnums()` from `apply_autocmd_group`. And there we check, if the cursor position is still valid, by comparing against `curbuf->b_ml.ml_line_count` which is still 1 from `buf_clear_file` from wiping the buffer content at the beginning of `do_ecmd`. So the cursor will be set to the beginning of the window. 

Should we store the old values and try to reset it later in `readfile()` when the buffer is actually already reloaded?

**Comment by brammool** [comment]
> This happens, because in `do_ecmd` the memfile will be closed and the
> containing buffer struct will be reset prior to reloading the buffer
> from disk. Later in `readfile()` we call the `BufReadPre` autocommand.
> Part of calling the autocommands is to check the cursor position
> `check_lnums()` from `apply_autocmd_group`. And there we check, if the
> cursor position is still valid, by comparing against
> `curbuf->b_ml.ml_line_count` which is still 1 from `buf_clear_file`
> from wiping the buffer content at the beginning of `do_ecmd`. So the
> cursor will be set to the beginning of the window. 
> 
> Should we store the old values and try to reset it later in
> `readfile()` when the buffer is actually already reloaded? 

How about restoring the position in apply_autocmds_group()?
It could move the cursor back to an invalid position, but since it was
already there the same would happen when there is no matching
autocommand, thus it should be OK.  Only when the autocommand moves the
cursor we should keep it there.

-- 
A vacation is a period of travel during which you find that you
took twice as many clothes and half as much money as you needed.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
