### ISSUE TITLE
vim hangs after certain combination of input, highlight and substitution

### ISSUE THREAD

**Issue by markonm** [vim/vim#4377]
**To Reproduce**
1. Run `vim --clean -S reproduce.vim`
```vim
" reproduce.vim
set filetype=json
set columns=80
set lines=25
set conceallevel=2
set encoding=utf8
set nowrap
call setline(1, '."....":"电",')
call setline(2, '."....":"电",')
call matchadd('Conceal', 'test')
syntax enable
%s/./test                                                                          test
```
**Environment**
 - Vim version 8.1.1333
 - OS: Ubuntu 18.04.2 LTS
 - Terminal: Xfce Terminal Emulator

**Additional context**
Also happens on Windows in vim and gvim.

**Comment by brammool** [comment]
> **To Reproduce**
> 1. Run `vim --clean -S reproduce.vim`
> ```vim
> " reproduce.vim
> set filetype=json
> set columns=80
> set lines=25
> set conceallevel=2
> set encoding=utf8
> set nowrap
> call setline(1, '."....":"电",')
> call setline(2, '."....":"电",')
> call matchadd('Conceal', 'test')
> syntax enable
> %s/./test                                                                          test
> ```
> **Environment**
>  - Vim version 8.1.1333
>  - OS: Ubuntu 18.04.2 LTS
>  - Terminal: Xfce Terminal Emulator
> 
> **Additional context**
> Also happens on Windows in vim and gvim.

Well, that is a tricky corner case.  It happens because there is a wide
character that doesn't fit in the last screen column.  Vim then
displays a '>' character and puts the pointer back on that character.
But then the concealing causes the character to not be displayed, and we
get into an endless loop.

I'll fix it.  It's too much of a corner case to write a test for.

-- 
ALL:   A witch!  A witch!
WITCH: It's a fair cop.
ALL:   Burn her!  Burn her!  Let's make her into a ladder.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
