### ISSUE TITLE
Gvim for windows generates incorrect shell command lines - breaks bash

### ISSUE THREAD

**Issue by bobbogomip** [vim/vim#4418]
**Describe the bug**
Can no longer use _bash_ as my shell on Windows, as _gvim_ builds the wrong command-line. The failure happens somewhere between version 8.1 patch 978 (where everything works), and 8.1 patch 1298.

**To Reproduce**
1. Run `gvim -U NONE -u NONE`
2. Set the following options. Probably easiest to load the following text into a buffer...

    set shell=bash\ -c
    set shellcmdflag=
    set shellxquote='
    set shellquote=
    set shellredir=>
    set noshelltemp
    set shell?  shellcmdflag?  shellxquote?  shellquote?  shellredir?  shelltemp?

...and then executing that text, via buffer `a`:

    :%y a|@a

Now run a shell command

    :r !echo hello

**Expected behaviour**
A new line appears in the buffer consisting of the word `hello`

**Broken behaviour**
Gvim just sits with a flashing command-line

**Environment (please complete the following information):**
 - 8.1.837 - it works
 - 8.1.1298 - it fails
 - 8.1.1364 - it fails
 - Windows 7.1 64-bit
 - GUI
 - Cygwin 64-bit, bin folder on my `%PATH%`

**Additional context**
By changing the command to `sleep 100`, you can fire up Sysinternal's ProcessExplorer and examine the command-line that gvim has given the new bash process:

When it works:

     bash -c  'sleep 100'

When it fails:

    bash -c  bash -c 'sleep 100'

What is happening here is that the first bash starts up a second interactive bash, which never exits!

**Comment by brammool** [comment]
> **Describe the bug**
> Can no longer use bash as my shell on Windows as gvim build the wrong command-line. The failure happens somewhere between version 8.1 patch 978 (where erything works) and 8.1 patch 1298.
> 
> **To Reproduce**
> 1. Run `gvim -U NONE -u NONE`
> 2. Set the following options. Load the following text into a buffer:
> 
>     set shell=bash\ -c
>     set shellcmdflag=
>     set shellxquote='
>     set shellquote=
>     set shellredir=>
>     set noshelltemp
>     set shell?  shellcmdflag?  shellxquote?  shellquote?  shellredir?  shelltemp?
> 
> and then executing that text:
> 
>     `:%y a|@a`
> 
> Now run a shell command
> 
>     :r !echo hello
> 
> **Expected behaviour**
> A new line appears in the buffer consisting of the word `hello`
> 
> **Broken behaviour**
> Gvim just sits with a flashing command-line
> 
> **Environment (please complete the following information):**
>  - 8.1.837 - it works
>  - 8.1.1298 - it fails
>  - 8.1.1364 - it fails
>  - Windows 7.1 64-bit
>  - GUI
> 
> **Additional context**
> By changing the command to `sleep 100`, you can fire up Sysinternal's ProcessExplorer and examine the command-line that gvim has given the new bash process:
> 
> When it works:
> 
>      bash -c  'sleep 100'
> 
> When it fails:
> 
>     bash -c  bash -c 'sleep 100'
> 
> What is happening here is that the first bash starts up a second
> interactive bash, which never exits!

This must have been caused by patch 8.1.1295.  It was a workaround for
when vimrun does not exist.

You can try using:
     set shell=bash
     set shellcmdflag=-c
That mithg not make any difference.

Not sure how to make it both work.  Perhaps check if 'shellcmdflag' is
"-c" instead of "/c"?

Does it all work fine when 'shell' is "cmd.exe"?

-- 
Bypasses are devices that allow some people to dash from point A to
point B very fast while other people dash from point B to point A very
fast.  People living at point C, being a point directly in between, are
often given to wonder what's so great about point A that so many people
from point B are so keen to get there and what's so great about point B
that so many people from point A are so keen to get there.  They often
wish that people would just once and for all work out where the hell
they wanted to be.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I totally forgot about non-cmd shell.
How about this?

```diff
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -4837,20 +4837,17 @@ mch_call_shell(
 			    (msg_silent != 0 || (options & SHELL_DOOUT))
 								 ? "-s " : "",
 			    p_sh, p_shcf, cmd);
-		else
+		else if (
 # ifdef VIMDLL
-		if (gui.in_use || gui.starting)
+			(gui.in_use || gui.starting) &&
 # endif
+			STRCMP(p_shcf, "/c") == 0)
 		    vim_snprintf((char *)newcmd, cmdlen, "%s %s %s %s %s",
 					   p_sh, p_shcf, p_sh, p_shcf, cmd);
-# ifdef VIMDLL
 		else
-# endif
 #endif
-#if !defined(FEAT_GUI_MSWIN) || defined(VIMDLL)
 		    vim_snprintf((char *)newcmd, cmdlen, "%s %s %s",
 							   p_sh, p_shcf, cmd);
-#endif
 		x = mch_system((char *)newcmd, options);
 		vim_free(newcmd);
 	    }
```

**Comment by k-takata** [comment]
I slightly edited the previous patch. (cosmetic change)

**Comment by bobbogomip** [comment]
I have played with a combination of flags. The issue appears to be that the string `bash -c` (however it is encoded in vim opts) appears twice.

**Comment by bobbogomip** [comment]
8.1.1413 works for me™

Thank you
