### ISSUE TITLE
E211 warning appears every time vim/MacVim is focused

### ISSUE THREAD

**Issue by brian-armstrong** [vim/vim#4419]
It looks like the patch made for #3165 causes the E211 banner to appear every time MacVim is refocused. This is fairly annoying, I only need to know the file is deleted once. I have confirmed that reverting the change to fileio.c so that buf->b_mtime = 0; is used resolves this bug. It's unclear if there's a patch that fixes my bug but doesn't regress the other issue's functionality.

**Comment by chdiza** [comment]
This should be reported to the MacVim repo.

**Comment by brian-armstrong** [comment]
What would I report? The behavior stems from a change to this repo - are you suggesting MacVim may be misconfigured/responding incorrectly to this change?

**Comment by chdiza** [comment]
You would report exactly what you reported here.  I'm suggesting that MacVim might have to take special steps to work around this.

Also it'd help to provide the MacVim repo with exact reproduction steps.  I'm not seeing the described behavior, but I'm just guessing at what steps are supposed to bring it about.

**Comment by brammool** [comment]
> It looks like the patch made for #3165 causes the E211 banner to
> appear every time MacVim is refocused. This is fairly annoying, I only
> need to know the file is deleted once. I have confirmed that reverting
> the change to fileio.c so that buf->b_mtime = 0; is used resolves this
> bug. It's unclear if there's a patch that fixes my bug but doesn't
> regress the other issue's functionality.

Looks like there is a mismatch in using the 'autoread' option: when the
buffer does not have a local value it uses -1 instead of using the
global value.  I'll fix that.  Then please check if your problem is
fixed.

-- 
For a moment, nothing happened.
Then, after a second or so, nothing continued to happen.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brian-armstrong** [comment]
Wow, thank you for fixing this so quickly! I confirmed that this fixes the issue for me. Thank you for the quick turnaround and for maintaining this awesome editor.
