### ISSUE TITLE
[question] execute mapping with <expr> fails

### ISSUE THREAD

**Issue by doums** [vim/vim#4453]
**Question**

Sorry but this is not a bug (I think is not). For a script I working on, I need to create programmatically/dynamically some mapping. But I'm completely stuck on a problem and I fail to figure out what happens so I need explanation. For the sake of clarity I simplified my code.

I have this piece of code in my `.vimrc`:
```
function s:Test()                                     
  return '.'                                          
endfunction                                           
 
let key = 'f'
                                                                   
execute 'inoremap <expr><silent> ' . key . ' ' . s:Test()
```
After having sourced my `.vimrc` if I check the available maps with `:imap` I see that the mapping is nicely created as expected:
```
i  f           * .
```
But if I try it I get this error: `E15: Invalid expression: .`

**Environment (please complete the following information):**

-  Vi IMproved 8.1 (2018 May 18, compilé Apr 26 2019 21:55:55) Rustines incluses : 1-1186
-  Operating System: Linux x1c6 5.1.4-arch1-1-ARCH #1 SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
-  Terminator

**Comment by k-takata** [comment]
Because you add `<expr>` flag to `inoremap`, Vim tries to interpret `.` (= result of `s:Test()`) as an expression, but it is not a valid expression. So `E15` happens.
If you just want to map `key` to the return value of `s:Test()`, just remove `<expr>`.

Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with Vim. Closing.

**Comment by doums** [comment]
Ok! thank you
