### ISSUE TITLE
global marks not deleted by :delmarks

### ISSUE THREAD

**Issue by Konfekt** [vim/vim#448]
To reproduce:

Start `Vim`. Then `:e test.txt<cr>` and enter `ia<esc>`.
Hit `mM` and `ZZ`. 

Start `Vim` and enter `:delmarks M<cr>` and hit `ZZ`.

Result:
`~/.viminfo` contains `'M  1  0  ~/test.txt`
Expected:
`~/.viminfo` does not contain `'M  1  0  ~/test.txt`

**Comment by ZyX-I** [comment]
When writing viminfo Vim joins marks found in the current session and found in the file. Since there are no timestamps (e.g. like in neovim/neovim#2506) it has no way to know that mark `M` was deleted and is not the mark that comes from another Vim instance and needs to be kept for this reason.

(To be fair neovim/neovim#2506 does not keep time when mark was deleted and thus will also exhibit the same behaviour. But unlike ShaDa with viminfo you have no way to change this behaviour while still joining information from the file and from the running instance.)

**Comment by ZyX-I** [comment]
To actually delete the mark, use `:wviminfo!` (with bang). Note that this action will also delete information about file-local marks for all files which were not opened in the current Vim instance.

**Comment by Konfekt** [comment]
Okay, there should be a variant `delmarks! M` that does `wviminfo!` as this is what most users expect.

**Comment by ZyX-I** [comment]
Another possible resolution is modifying Vim source code to have “deleted” state of the mark: currently there are only two variants: “defined” and “undefined”. This way, since without timestamps Vim always prioritizes information from the current instance, it would be possible to omit writing information about deleted marks.

---

`delmarks! M` doing `wviminfo!` is very bad idea:
1. `wviminfo!` is going to purge _much_ more data then just one mark. AFAIR at writing viminfo three kinds of information are merged: global marks, file-local marks and history. `wviminfo!` purges this all, leaving only information from the current instance.
2. Writing viminfo file not at explicit `wviminfo` and not at shutdown is rather unexpected.

**Comment by Konfekt** [comment]
Ok, agreed that a default `wviminfo!` is too radical. 

Still, the possibility that another `Vim` instance set exactly the same mark is contrived since
- the swap file prevents another `Vim` instance from loading the same file, and
- even if the file was loaded, it is improbable that the user sets the mark at the same line and column.

The benefit in preventing this possibility does not outweigh the user confusion.

**Comment by ZyX-I** [comment]
@Konfekt What “exactly the same mark”?! When you do `:delmarks` all information about mark is erased, so the resulting state is
- Current Vim instance knows that mark M is unset.
- Viminfo file defines mark M.

. And this is merged.

Also
1. The swap file does _not_ prevent another Vim instance from loading the same file _at all_ because
   - Swap files can be disabled.
   - When Vim finds existing swap file it warns user and lets him choose the action, one of which is “edit the file”.
2. Nobody cares. Mark is not “deleted” it is “unset”, and Vim has no way to detect that given mark is identical to the existing one. Also you may have just as well redefined mark M to another location, then delete _it_ and _only_ then exit. So such check is pointless.

**Comment by Konfekt** [comment]
If file, line and column coincide of the mark `M` in `viminfo` and that of the Vim instance conincide. then `:delmarks` should erase the mark `M` in `viminfo`.

It does not entirely prevent it, but adds up to the unlikeliness that the mark `M` erased by `:delmarks` in one instance has in the meanwhile, with the same file, line and column, been added in another one.

**Comment by Konfekt** [comment]
I am not sure a user knows that the mark is not deleted but unset. The documentation only speaks about the deletion of marks. 

If Vim cannot check that the mark `M` in `viminfo` and `M` in the Vim instance coincide, then it cannot reliably delete `M` in Viminfo, leaving the user, like me, at loss why `:delmarks` has no effect.

**Comment by ZyX-I** [comment]
@Konfekt Any kind of writing viminfo file in `:delmarks` is unexpected, and also adds a bunch of possible errors (viminfo file not readable/writeable/contains errors/…) unexpected by script writers, makes `:delmarks` take much more time, not to mention the fact that code supporting viminfo has no such functionality as deleting a single entry. Adding “deleted” mark state in addition to “unset” makes much more sense for me.

And even in this case to reliably delete a mark you will need to make sure that at the time of writing viminfo there is only one Vim instance left: otherwise other Vim instances will resurrect the mark simply because they have read it from viminfo earlier and then nobody used `:delmarks` there. This also applies to _every_ solution which does not include
1. Adding timestamps to the marks in viminfo and currently running Vim instance.
2. Adding “deleted” state _both_ in the viminfo file and in the running instance, with timestamps attached.
3. Merging marks according to the timestamp on writing viminfo.

This is basically what ShaDa does, except for 2.

---

By the way, why do you want to delete mark at all? I _never_ needed to do this as defined, but unneeded mark does nothing bad for me.

**Comment by Konfekt** [comment]
Ok, agreed that reliably deleting a mark is much more complicated than what is implemented now and needs timestamping to concile the various Vim instances. The user should be warned about this unexpected behaviour in the documentation though.

It occurred to me since I use a CtrlP extension for a list all marks, and those global marks set years ago cluttered it.

**Comment by Konfekt** [comment]
Thanks for your efforts regarding the ShaDa replacement of viminfo in NeoVim by the way.

**Comment by chrisbra** [comment]
This has been discussed before: https://groups.google.com/d/msg/vim_dev/kre4oyzMRDU/egIH4hlIWo4J

closing.
