### ISSUE TITLE
javascript script support?

### ISSUE THREAD

**Issue by gu-fan** [vim/vim#450]
is there a plan that support javascript as vim's scripting

**Comment by vim-ml** [comment]
No, there isn't.

The only language which is guaranteed to be accepted for scripting in all
versions of Vim is vimscript. Some other languages (perl, python, python3,
ruby, tcl, mzscheme, lua) can be embedded in vimscript but they won't be
recognized unless the corresponding feature is compiled-in. If you want to
add one more embedded-script language, go ahead, the sources and
documentation are there for anyone to download. Otherwise AFAIK there are
no such plans.

Best regards,
Tony.

**Comment by mattn** [comment]
if you need, try to patch if_v8.

http://www.vim.org/scripts/script.php?script_id=2375

**Comment by chrisbra** [comment]
This issue tracker is for bugs only. If you want to ask questions, please use the appropriate mailinglist.

Having said this, patches would be welcome.

(closing as invalid.)

**Comment by gu-fan** [comment]
@mattn Thanks, I got it.
