### ISSUE TITLE
git: commits with duplicate tags

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4510]
There are two commits with duplicate tags, where the second tag looks like it should have been for the following commit:

1ad022a9b81d7829d5dc98cf5b8d0ee410558040 tag: v8.0.1367, tag: v8.0.1366
5d69da462f584a3aefb3427b127334bf9af3a4b0 tag: v8.0.1739, tag: v8.0.1738

Not sure what to do about this, but tags are not really used for releases, so could be moved?

There is also the following, but that's fine probably:

ed39e1d53cc4916c2390aea635cd8419497c1460 tag: v7.2.000, tag: v7.2

(found via `git log --reverse --format='%H %D' | grep ', tag'`)

**Comment by chrisbra** [comment]
So I think to correct it, we would need this:

```bash
git tag -f v8.0.1739  6176697203b0f168f4 && git tag -f v8.0.1367 461fe50fea245b2b1
```

that would move tag v8.0.1739 to commit 6176697203b0f168f4 and tag v8.0.1367 to commit 461fe50fea245b2b1

**Comment by brammool** [comment]
Christian wrote:

> So I think to correct it, we would need this:
> 
> ```bash
> git tag -f v8.0.1739  6176697203b0f168f4 && git tag -f v8.0.1367 461fe50fea245b2b1
> ```
> 
> that would move tag v8.0.1739 to commit 6176697203b0f168f4 and tag v8.0.1367 to commit 461fe50fea245b2b1

That works locally, but I can't push this:

 % git push origin  v8.0.1367
To github.com:vim/vim.git
 ! [rejected]            v8.0.1367 -> v8.0.1367 (already exists)
error: failed to push some refs to 'git@github.com:vim/vim.git'
hint: Updates were rejected because the tag already exists in the remote.

Perhaps the remote tags need to be deleted first?


-- 
hundred-and-one symptoms of being an internet addict:
149. You find your computer sexier than your girlfriend

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
You can push them forcibly:

```
git push origin -f v8.0.1367 v8.0.1739
```

Other people can fetch the updated tags after that by:

```
git fetch --tags
```

**Comment by brammool** [comment]
Ken Takata wrote:

> You can push them forcibly:
> 
> ```
> git push origin -f v8.0.1367 v8.0.1739
> ```

Thanks, that appeared to have worked.

> Other people can fetch the updated tags after that by:
> 
> ```
> git fetch --tags
> ```

I always wonder why git makes things so complicated.  A "git pull"
should be sufficient to get all updates.

-- 
hundred-and-one symptoms of being an internet addict:
150. You find yourself counting emoticons to get to sleep.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> git fetch --tags

This should have been:

```
git fetch --tags -f
```

`-f` is also needed for `fetch`.
