### ISSUE TITLE
set completeopt+=popup?

### ISSUE THREAD

**Issue by andymass** [vim/vim#4544]
**Is your feature request related something that is currently hard to do? Please describe.**
Now that there are popup windows, it should be possible to get completion information in a popup rather than the preview window.  This would be much more convenient than the preview window since it takes up less dedicated screen space.  Is this already planned?

**Describe the solution you'd like**
A popup which replaces the preview window for completion info.

![image](https://user-images.githubusercontent.com/6655373/59383470-f5e54980-8d2d-11e9-8921-9f4f3f97e09a.png)

The popup should be placed in the first possible space, depending on the size/aspect ratio of the popup, e.g.:
   1) to the right
   2) above
   3) below
   4) to the left

**Describe alternatives you've considered**
Plugins can already provide their own side-car popups today using the CompleteChanged event.  I assume they will do this in complex cases (e.g. using color).  But the simple case, display info in popup instead of preview, should be supported out of the box.  

**Additional context**

I noticed that there is an unimplemented feature of popup windows, which I guess is blocking this:

	flip		When TRUE (the default) and the position is relative
			to the cursor, flip to below or above the cursor to
			avoid overlap with the |popupmenu-completion| or
			another popup with a higher "zindex".
			{not implemented yet}

However, I argue that the overlap prevention should happen left/right as well.

I tried the very naïve implementation below.  It has issues, like positioning, and that multiple popups are spawned which don't go away until you close the pum (even though "moved" is set to "any").

```diff
diff --git a/src/option.c b/src/option.c
index 12a0816f3..98286b46f 100644
--- a/src/option.c
+++ b/src/option.c
@@ -3228,7 +3228,7 @@ static char *(p_fdm_values[]) = {"manual", "expr", "marker", "indent", "syntax",
 static char *(p_fcl_values[]) = {"all", NULL};
 #endif
 #ifdef FEAT_INS_EXPAND
-static char *(p_cot_values[]) = {"menu", "menuone", "longest", "preview", "noinsert", "noselect", NULL};
+static char *(p_cot_values[]) = {"menu", "menuone", "longest", "preview", "noinsert", "noselect", "popup", NULL};
 #endif
 #ifdef FEAT_SIGNS
 static char *(p_scl_values[]) = {"yes", "no", "auto", NULL};
diff --git a/src/popupmnu.c b/src/popupmnu.c
index 09faa69e8..3e5729748 100644
--- a/src/popupmnu.c
+++ b/src/popupmnu.c
@@ -702,7 +702,7 @@ pum_set_selected(int n, int repeat)
 	if (pum_array[pum_selected].pum_info != NULL
 		&& Rows > 10
 		&& repeat <= 1
-		&& vim_strchr(p_cot, 'p') != NULL)
+		&& strstr(p_cot, "preview") != NULL)
 	{
 	    win_T	*curwin_save = curwin;
 	    tabpage_T   *curtab_save = curtab;
@@ -845,6 +845,58 @@ pum_set_selected(int n, int repeat)
 		}
 	    }
 	}
+#endif
+#ifdef FEAT_TEXT_PROP
+# ifdef FEAT_QUICKFIX
+	else
+# endif
+	if (pum_array[pum_selected].pum_info != NULL
+		&& Rows > 10
+		&& repeat <= 1
+		&& strstr(p_cot, "popup") != NULL)
+	{
+	    char_u  *p, *e;
+	    list_T  *l;
+	    dict_T  *d;
+
+	    l = list_alloc();
+	    if (l == NULL)
+		return FALSE;
+	    for (p = pum_array[pum_selected].pum_info; *p != NUL; )
+	    {
+		e = vim_strchr(p, '\n');
+		if (e == NULL)
+		{
+		    list_append_string(l, p, 0);
+		    break;
+		}
+		else
+		{
+		    *e = NUL;
+		    list_append_string(l, p, (int)(e - p + 1));
+		    *e = '\n';
+		    p = e + 1;
+		}
+	    }
+
+	    d = dict_alloc();
+	    if (d == NULL)
+		return FALSE;
+	    dict_add_string(d, "pos", "botleft");
+	    dict_add_string(d, "line", "cursor-1");
+	    dict_add_string(d, "moved", "any");
+	    dict_add_number(d, "col", pum_col + pum_width + 3);
+
+	    typval_T argvars[3], rettv;
+	    argvars[0].v_type = VAR_LIST;
+	    argvars[0].vval.v_list = l;
+	    argvars[1].v_type = VAR_DICT;
+	    argvars[1].vval.v_dict = d;
+	    argvars[2].v_type = VAR_UNKNOWN;
+	    f_popup_create(argvars, &rettv);
+
+	    return FALSE;
+	}
 #endif
     }
 
```

**Comment by prabirshrestha** [comment]
As author of [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) and [vim-lsp](https://github.com/prabirshrestha/vim-lsp), I would be very happy if this was supported in vim so I don't have to duplicate this feature for asyncomplete and vim-lsp omni-func. For some LSP popup servers we need to send additional request to get the actual popup info so would be good to have a method something like this so we can call `call set_complete_popup(completed_item, '...popup text')` based off `CompleteChanged` event.

**Comment by andymass** [comment]
@prabirshrestha, what is the request/response and what do you do currently to populate the "info" field of completion menu?

**Comment by prabirshrestha** [comment]
Here is an example. Basically trying to set info for all completion items can be very expensive because server needs to do more work as well as some docs might be quite large which requires scrolling which currently vim8 doesn't support it yet since it can't focus in popup window.

![image](https://user-images.githubusercontent.com/287744/59555105-73919b00-8f62-11e9-8543-05191b8ccd27.png)

To overcome this LSP supports `completionItem/resolve`. https://microsoft.github.io/language-server-protocol/specification#textDocument_completion. There is a bit more about perf on https://github.com/sourcegraph/javascript-typescript-langserver/issues/331

I personally don't think it should be just info as I would like to get more control over the popup. We already have enough information about row/height/size from `CompleteChanged` so would be ok to manually call `popup_create`. I was thinking if vim could do most of the complex work on positioning which may or may not make sense here.

**Comment by andymass** [comment]
> vim8 doesn't support it yet since it can't focus in popup window.

Why can't you use the key callbacks?

> I was thinking if vim could do most of the complex work on positioning

I do think vim should handle automatic positioning as a generic property of a popup because it is really tedious to do from plugins and should just need to be implemented once.

**Comment by brammool** [comment]
It should be possible to put the "info" from the complete menu in a popup instead of a preview window.
Positioning may be a bit tricky, especially on a small screen and when the cursor is near the top or bottom of the screen.
It should also be possible for a plugin to show a popup depending on what entry in the completion menu is selected.  The "info" is only plain text, a popup can do much more.

**Comment by bfrg** [comment]
With 
```vim
set previewpopup=height:10,width:60
set completeopt+=preview
```
the `info` field will be displayed in a popup window, but its position is wrong. Currently the popup window appears at the cursor position, consequently, always on top of the completion popup.
I wasn't sure whether I should open a new issue for that.

**Comment by mogelbrod** [comment]
Sorry to bump an already closed issue, but I'm not sure if this one is completely implemented. Using macvim v8.1 (patches 1-2234) together with YouCompleteMe; the popup always appear on the sides of the completion menu, even in cases where it doesn't really fit:

<img width="701" alt="Screenshot 2019-12-27 at 22 43 17" src="https://user-images.githubusercontent.com/150084/71543104-910edb00-296f-11ea-9900-ba23674bdbe2.png">

I've been unable to find any way to position the popup above and/or below the menu as was described in this part of the original issue:

> The popup should be placed in the first possible space, depending on the size/aspect ratio of the popup, e.g.:
> 
> 1. to the right
> 2. above
> 3. below
> 4. to the left

The `completepopup=width:XX,height:XX` options exist, but they specify max values rather than min values. Being able to set a `minwidth` that vim then tried to accomodate for through positioning would be a great addition.

Is the flip option for create_popup() a blocker for this? And if so is there anywhere I can track its implementation? I was unable to find any issue related to it on github.

> I noticed that there is an unimplemented feature of popup windows, which I guess is blocking this:
> 
> ```
> flip		When TRUE (the default) and the position is relative
> 		to the cursor, flip to below or above the cursor to
> 		avoid overlap with the |popupmenu-completion| or
> 		another popup with a higher "zindex".
> 		{not implemented yet}
> ```

Related [issue over at YouCompeteMe](https://github.com/ycm-core/YouCompleteMe/issues/3565)

**Build used**
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:13)
macOS version
Included patches: 1-2234

**Comment by brammool** [comment]
In the example you give, where should the info popup go then?  Perhaps below the menu?  But then it looses the connection with the selected entry (assuming there normally are several entries in the menu).  Or perhaps it can overlap the menu, making sure it doesn't obscure the selected entry?
We need several examples to see what works best in general, otherwise we are optimizing for one specific example and break it for others.

**Comment by mogelbrod** [comment]
@brammool: If a `minwidth` option was added and there wasn't enough on the left nor the right of the completion menu it could be positioned above the line being edited, just like function signatures are rendered above the line after choosing a completion (with YCM at least). In this specific edge case it would mean the popup only had 2 lines available, but those two lines would be more readable. I agree that positioning it below the completions would sever the connection to the selected completion though.

Another solution would be for the plugin to simply only include the identifier (eg. exclude the signature) from the completion menu so that the popup has a better chance of fitting. I asked @puremourning about this in [the referenced YCM issue](https://github.com/ycm-core/YouCompleteMe/issues/3547#issuecomment-569510807).

**Comment by puremourning** [comment]
> just like function signatures are rendered above the line 

For the record, positioning of the signature hint popup is completely YCM code and it’s already pretty complex (attempting to avoid overlapping the PUM). If the preview popup jumped around it would be even more hectic working out what takes priority.
