### ISSUE TITLE
why can't an existing buffer (with syntax) be displayed in a popup?

### ISSUE THREAD

**Issue by andymass** [vim/vim#4595]
**Is your feature request related something that is currently hard to do? Please describe.**
I have a plugin which wants to display a few lines of the current buffer in a popup window, with syntax highlighting.  My current options are a) send a large enough number of lines to the popup for syntax highlighting to work or b) compute current buffer's syntax regions and use text properties in the popup to emulate it.  This seems slightly inefficient since it "wastes" a buffer and requires re-computation of syntax.

**Describe the solution you'd like**
I'm wondering what the reason is for the restriction that the popup window is a completely new buffer and can't display pieces of an existing buffer.  There could be a `bufnr` option to `popup_create` which re-uses an existing buffer (starting at `firstline`) instead of creating a new buffer.

**Describe alternatives you've considered**
Sending 200 to 400 lines to the popup and setting the filetype will essentially work, but it seems inefficient.

**Additional context**
This is also useful for "preview" of code definitions (like ptag except in a popup).

**Comment by brammool** [comment]
> **Is your feature request related something that is currently hard to do? Please describe.**
> I have a plugin which wants to display a few lines of the current buffer in a popup window, with syntax highlighting.  My current options are a) send a large enough number of lines to the popup for syntax highlighting to work or b) compute current buffer's syntax regions and use text properties in the popup to emulate it.  This seems slightly inefficient since it "wastes" a buffer and requires re-computation of syntax.
> 
> **Describe the solution you'd like**
> I'm wondering what the reason is for the restriction that the popup window is a completely new buffer and can't display pieces of an existing buffer.  There could be a `bufnr` option to `popup_create` which re-uses an existing buffer (starting at `firstline`) instead of creating a new buffer.
> 
> **Describe alternatives you've considered**
> Sending 200 to 400 lines to the popup and setting the filetype will essentially work, but it seems inefficient.
> 
> **Additional context**
> This is also useful for "preview" of code definitions (like ptag except in a popup).

Not sure if this can work.  At least currently the 'buftype'  is set to
"popup", meaning that it can only show in a popup window.  It's true
that practically all the properties are on the window, not the buffer.
But if we would have a buffer associated with a file in a popup window
we get a lot of questions, such as what happens if the popup is closed?
I suppose we could make the buffer hidden then.  Or only make it hidden
when it has changes.  But you don't what that for when the buffer is
only used in the popup, it should just be deleted.

Perhaps it can work if we have two ways to create a popup:
- No buffer specified, create a buffer with 'buftype' set to "popup".
- A buffer specified, then the buffer is not deleted when the popup
  closes, 'bufhidden' applies.  But if the buffer has changes it always
  becomes hidden, no prompt for saving changes.

-- 
This is an airconditioned room, do not open Windows.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
> A buffer specified, then the buffer is not deleted when the popup closes, 'bufhidden' applies.  But if the buffer has changes it always becomes hidden, no prompt for saving changes.

Ah, I do see the problem now.  I personally think it would make more sense that the user still gets a prompt to write the buffer when closing the last non-popup window which is viewing the buffer (assuming hidden/bufhidden are not applicable).  Otherwise if a plugin is displaying the current buffer, the behavior will change for closing an editor window.

**Comment by brammool** [comment]
> > A buffer specified, then the buffer is not deleted when the popup
> > closes, 'bufhidden' applies.  But if the buffer has changes it
> > always becomes hidden, no prompt for saving changes.
> 
> Ah, I do see the problem now.  I personally think it would make more
> sense that the user still gets a prompt to write the buffer when
> closing the last non-popup window which is viewing the buffer
> (assuming hidden/bufhidden are not applicable).  Otherwise if a plugin
> is displaying the current buffer, the behavior will change for closing
> an editor window.

The user has no "normal" way to close a popup window, it is most likely
closed by a plugin.  That plugin should deal with it then.  It would be
interruptive if a prompt pops up while the user has no clue why the
popup closed (e.g., when it's going to be replaced by another popup,
might even be showing the same buffer).

-- 
Back up my hard drive?  I can't find the reverse switch!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I suppose this is fixed as of 7964873afe59d0896a921b7c585167674bb784d5 so closing
