### ISSUE TITLE
Yanking into the same registry slot as the macro's currently being recorded cause macro to be yanked instead.

### ISSUE THREAD

**Issue by chakrit** [vim/vim#470]
**Steps to reproduce:**
1. `qm` - Starts a macro into `m`
2. `V"my` - Yank a line, also into `m`
3. `q` - Stops macro record.
4. `"mp` - Paste from `m`, macro gets pasted, not the yanked content.

**Expected Behavior:**
Either yanking to the same registry should be forbidden (or atleast shows a warning)

This is unintuitive. I think something needs to be done here. A comment would be appreciated.

``` sh
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  3 2015 09:51:30)
MacOS X (unix) version
Included patches: 1-903
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/System/Library/Frameworks -framework Python   -lruby.2.0.0 -lobjc    
```

**Comment by chrisbra** [comment]
Well, don't do it then.
Seriously, recording a macro means to record the keystrokes and it is perfectly valid for single throw away macros, to record that you want to have something yanked into the same register that was previously used for the macro. Regarding your possibilities:
1) Generating a Warning might not help or be annoying for users.
2) would be a backwards incompatible change and would mean, you can't easily edit the content of the macro anymore.

**Comment by chakrit** [comment]
> Well, don't do it then.

I figures someone would say this.

The point is the unintuitive-ness and time wasted head-scratching and recording a useless macro for every other vimmer who would stumble upon this over again. Of course if I know _before_ I did it I would not have done it.

**Comment by vim-ml** [comment]
On 2015-11-09, Chakrit Wichian wrote:

> ```
> Well, don't do it then.
> ```
> 
> I figures someone would say this.
> 
> The point is the unintuitive-ness and time wasted head-scratching and recording
> a useless macro for every other vimmer who would stumble upon this over again.
> Of course if I know before I did it I would not have done it.

I doubt that many other users will encounter this.  Most users will
consider that while they are recording a macro into a particular
register, it would be unwise to yank something else into that same
register.  They would choose a different register for the yank.  Or
they would wonder what would happen if they did that, try it, and
decide if the results were what they wanted.

Regards,
Gary

**Comment by jfelchner** [comment]
If one is looking at weighing the benefits of allowing such a thing, and the downsides of allowing such a thing, I think it's pretty clear that the current behavior is:

a) not very useful even if it's something that someone wants to do
b) tough thing to track down if it's done accidentally
c) not very intuitive
d) able to be achieved via VimL if the user really wants to

It seems to me as if this should throw a warning if not an outright error.

**Comment by vim-ml** [comment]
On Mon, Nov 16, 2015 at 2:33 AM, Jeff Felchner
vim-dev-github@256bit.org wrote:

> If one is looking at weighing the benefits of allowing such a thing, and the downsides of allowing such a thing, I think it's pretty clear that the current behavior is:
> 
> a) not very useful even if it's something that someone wants to do
> b) tough thing to track down if it's done accidentally
> c) not very intuitive
> d) able to be achieved via VimL if the user really wants to
> 
> It seems to me as if this should throw a warning if not an outright error.
> 
> I use register q for (throwaway) macros, other registers for
> everything else: this way I avoid conflicts. I have quite a number of
> "permanent" values stored in registers and remembered by means of the
> viminfo, so I (try to) avoid overwriting them with something else. But
> macros being what they are, and hard to get "just right" at first
> attempt, I don't regard it as "below me" to hit

```
:let @q = '<Ctrl-R>q'
```

(where <Ctrl-R> means "hit Ctrl-R") in order to edit the contents of
my latest recorded macro by hand. And if I had a need to save one or
more macros for some time, I would try to find an unused register and
put them there, maybe by let-register again.

The fact that macros use the same registers as put and yank is
well-known (at least to old-timers) and, like everything in Vim,
well-documented. It has its tested and tried uses.

Sorry if I sound disrespectful, but this thread sounds to me like
"Dear Congressperson, I just shot myself in the foot. Please pass a
law to forbid guns which let themselves be aimed other than
horizontally".

Best regards,
Tony.

**Comment by chakrit** [comment]
I understand you are all VIM elites but meager laypeople at least deserves a warning no? Or is this the normal attitude for all questions/issues of this nature? If so, please just close the issue.

**Comment by jfelchner** [comment]
Tony, all due respect, it's more like:

"Dear Congressperson, I just got off on the wrong exit because the highway wasn't clearly marked.  Please pass a law that requires road signs."

You stated yourself that "old-timers" might know things that newbies don't.  Giving someone a warning if they attempt to access a macro register that's being recorded is just a nice thing to do.  I'll refrain from an arbitrary statistic but you can't deny that almost every single time this happens to a user it is something they would _not_ want to do.

It's the same logic for why the vast, vast, _vast_ majority of people have `set backspace=indent,eol,start` in their `vimrc` files.  It's just one more thing for newbies to have to deal with, when it could just be the default and be done with it.  The "old-timers" can set it to whatever the heck they want.

So, could you say "Who cares? They'll learn." or "Not my problem." or "I have x, y, z setup that keeps this from being a problem for me so therefore it's not a problem for anyone.".  Of course.  But that doesn't mean it has to _continue_ to be a problem for new people coming to vim.

I'm not saying that macros and yanking should use different registers, I don't think that's the case at all.  Simply that when recording a macro, the register used for the macro isn't used for yanking or pasting without a warning or error.

**Comment by chakrit** [comment]
I removed point 2. if that's any help.

**Comment by chrisbra** [comment]
So how about adding some warning into the documentation that putting from the same register that is used for recording won't likely work as one would expect and perhaps also mention in the status line which register is used for recording (e.g. instead of "recording" use "recording @a" or similar, possibly with an 'shortmess' option to disable it)? Would that be an acceptable compromise?

**Comment by vim-ml** [comment]
On Mon, Nov 16, 2015 at 12:41 PM, Christian Brabandt
vim-dev-github@256bit.org wrote:

> So how about adding some warning into the documentation that putting from the same register that is used for recording won't likely work as one would expect and perhaps also mention in the status line which register is used for recording (e.g. instead of "recording" use "recording @a" or similar, possibly with an 'shortmess' option to disable it)? Would that be an acceptable compromise?

I think it would. OTOH, an are-you-sure prompt or an exception halfway
through the recording might change what is recorded and/or break
existing scripts unless coded with due attention to all possible
corner cases, so IMHO that would be much more problematic.

Best regards,
Tony.

**Comment by jfelchner** [comment]
@chrisbra That's an interesting idea. I think adding which register is being recorded would increase visibility for sure.  How about possibly just changing the message from `Recording` to `Recording (register @a modified)` or something if the macro register has been manually modified?

Just throwing out ideas here. :grinning:

Tony, I definitely don't think there should be a prompt, but I think maybe a status line warning would be appropriate?

**Comment by chakrit** [comment]
If not for this issue, that's a nice feature in and of itself. And probably helps save some head-scratching when we do stupid things as well :p

**Comment by vim-ml** [comment]
On Tue, Nov 17, 2015 at 9:21 AM, Jeff Felchner
vim-dev-github@256bit.org wrote:

> Tony, I definitely don't think there should be a prompt, but I think maybe a status line warning would be appropriate?

That's what I said in my reply to Christian.

Best regards,
Tony.

**Comment by jfelchner** [comment]
Tony, sounds good. I misread what you wrote. 👍🏻

**Comment by chrisbra** [comment]
I posted a patch here: https://groups.google.com/d/msg/vim_dev/O_NP52SplqY/mqVW-QZVBgAJ
