### ISSUE TITLE
job: exit_cb: return code -1 with "ls"

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4709]
Running `:echom job_start(["ls"], {'exit_cb': {... -> execute("echoerr ".string(a:000))}})` from the cmdline displays:
```
process 7520 run
Error detected while processing function <lambda>8:
line    1:
['process 7520 dead', -1]
```

Note the -1 there.

-1 is also displayed there when sourcing it from a file, but not when appending a command (`:source /home/user/Vcs/vim/t-job-ls.vim|filetype detect`).

This seems to be specific to `ls` (since it generates output?), `true` works as expected.

_Maybe_ related to https://github.com/vim/vim/issues/1320.

Vim 8.1.1635

**Comment by brammool** [comment]
The job has nowhere to write to.  Try adding 'out_io': 'file', 'out_name': '/tmp/output'

**Comment by blueyed** [comment]
> Try adding 'out_io': 'file', 'out_name': '/tmp/output'

That fixes it.

However, I do not think it should cause the exit code to be shadowed really, should it?
I can see that it might be useful as same kind of indicator, -1 is also returned for when jobs have been canceled: `let job = job_start(["sleep", "2"], {'out_io': 'file', 'out_name': '/tmp/output', 'exit_cb': {... -> execute("echoerr ".string(a:000))}}) | call job_stop(job)`
At least in this case it would be good to have the actual exit code there - which might depend on how the program handles SIGTERM etc.

Also it is clearly confusing that it behaves different when used in a command list (with bar), isn't it?

**Comment by brammool** [comment]
> > Try adding 'out_io': 'file', 'out_name': '/tmp/output'
> 
> That fixes it.
> 
> However, I do not think it should cause the exit code to be shadowed
> really, should it?

I don't know what you mean with "shadowed", but most likely the job
actually failed, because it tried to write to stdout and failed.  Vim
can only see that it failed, exited with a non-zero status, not why that
happened.

> I can see that it might be useful as same kind of indicator, -1 is
> also returned for when jobs have been canceled: `let job =
> job_start(["sleep", "2"], {'out_io': 'file', 'out_name':
> '/tmp/output', 'exit_cb': {... -> execute("echoerr ".string(a:000))}})
> | call job_stop(job)`
> At least in this case it would be good to have the actual exit code
> there - which might depend on how the program handles SIGTERM etc.

Vim does try to get the exit code, but it can't always get it.
This happens in mch_job_status(), using WEXITSTATUS().

> Also it is clearly confusing that it behaves different when used in a
> command list (with bar), isn't it?

Job execution is defenitely confusing.  The Vim implementation does not
attempt to be clever and passes on the burden to the user.  That allows
for a lot of flexibility and control, but also means you have to know
what you are doing.

We can add examples for cases where users would need some help.  For
"ls" it would be obvious you need to read the output.

-- 
(letter from Mark to Mike, about the film's probable certificate)
      I would like to get back to the Censor and agree to lose the shits, take
      the odd Jesus Christ out and lose Oh fuck off, but to retain 'fart in
      your general direction', 'castanets of your testicles' and 'oral sex'
      and ask him for an 'A' rating on that basis.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
closing

**Comment by blueyed** [comment]
>> Also it is clearly confusing that it behaves different when used in a
>> command list (with bar), isn't it?

> Job execution is defenitely confusing. The Vim implementation does not
> attempt to be clever and passes on the burden to the user. That allows for a
> lot of flexibility and control, but also means you have to know what you are
> doing.

Why is it behaving differently when used with another command on the same line?

**Comment by brammool** [comment]
> >> Also it is clearly confusing that it behaves different when used in a
> >> command list (with bar), isn't it?
> 
> > Job execution is defenitely confusing. The Vim implementation does not
> > attempt to be clever and passes on the burden to the user. That allows for a
> > lot of flexibility and control, but also means you have to know what you are
> > doing.
> 
> Why is it behaving differently when used with another command on the
> same line?

Perhaps because it creates a buffer, or the second command actually
consumes the output?  Hard to guess without an example.

-- 
This message contains 78% recycled characters.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
The example is in the initial comment:

This works:

> :source t-job-ls.vim|filetype detect
