### ISSUE TITLE
Odd behaviour with set path+=foo when path contains an empty string

### ISSUE THREAD

**Issue by malcolmr** [vim/vim#471]
`path` is a comma-separated list of directories, where the empty string signifies "current directory" (see `:help 'path'`.

`set path+=foo` should append a comma to the option before adding "bar" (see `:help :set+=`).

However, with Vim 7.4.899 on Linux, `set path+=foo` doesn't quite behave like that, causing the empty string to effectively drop out of `&path` if you attempt to remove and re-add an entry in some cases:

```
:set path=foo,,bar
:echo &path
foo,,bar
:set path-=bar
:echo &path
foo,
:set path+=bar
:echo &path
foo,bar
```

I would _think_ this is a bug in `set+=`, except that I'm not quite sure why `path` suggests that you should use `set path=,,` to search in the current directory rather that e.g. `set path=,`, and so it's possible I'm missing something.

**Comment by brammool** [comment]
Malcolm Rowe wrote:

> `path` is a comma-separated list of directories, where the empty string signifies "current directory" (see `:help 'path'`.
> 
> `set path+=foo` should append a comma to the option before adding "bar" (see `:help :set+=`).
> 
> However, with Vim 7.4.899 on Linux, `set path+=foo` doesn't quite behave like that, causing the empty string to effectively drop out of `&path` if you attempt to remove and re-add an entry in some cases:
> 
> ```
> :set path=foo,,bar
> :echo &path
> foo,,bar
> :set path-=bar
> :echo &path
> foo,
> :set path+=bar
> :echo &path
> foo,bar
> ```
> 
> I would _think_ this is a bug in `set+=`, except that I'm not quite
> sure why `path` suggests that you should use `set path=,,` to search
> in the current directory rather that e.g. `set path=,`, and so it's
> possible I'm missing something.

That's a bug, caused by not checking the options flags properly.
I'll make a fix.

## 

From "know your smileys":
 :-F    Bucktoothed vampire with one tooth missing

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
