### ISSUE TITLE
Option to remove insert delay after entering insert in a read-only file

### ISSUE THREAD

**Issue by zamicol** [vim/vim#472]
[According to this post](https://vi.stackexchange.com/questions/3001/remove-the-insert-delay-after-entering-insert-in-a-read-only-file?newreg=0c38c9f88ada4a5bb81576f63637f47a), there is no current way to disable insert delay after entering insert mode on a read-only file.  

Since I'm almost always aware that I'm in read-only, and I'm using ":W" `command! -bar -nargs=0 W  silent! exec "write !sudo tee % >/dev/null"  | silent! edit!`  when I want to save, there really is no need for any delay and only slows me down.  The message is fine, the delay is not.

**Comment by chrisbra** [comment]
Well, a workaround would be to simply set `:set noro` before doing your modification.

**Comment by vim-ml** [comment]
On Monday, November 9, 2015 at 12:45:38 PM UTC-6, Christian Brabandt wrote:

> Well, a workaround would be to simply set :set noro before doing your modification.

I go the opposite route and :set nomodifiable if a file is readonly when I load it, then I'm forced to take some action before making changes.

**Comment by cwfoo** [comment]
What's the point of the delay in these lines?

https://github.com/vim/vim/blob/008bff967f7fcaa6af066f71d65bfbba5ef5c7d3/src/change.c#L54-L62

Is there a good reason for the delay?

**Comment by brammool** [comment]
This is so that original Vi behavior can be kept (able to modify a buffer for a readonly file), while making sure that the user notices that there might be a problem.  As mentioned, if you are intentionally changing a buffer, first reset the 'readonly' option to let Vim know that you know what you are doing.
An option is just going to make things more complicated.  Taking away the delay is going to make it much more likely the user doesn't notice the warning and continues changing the buffer, only finding out later that the file can't be written and all changes were a waste of time.

**Comment by fdietze** [comment]
It's not a waste of time, you can always save it to another file.

A common use-case I have, is editing configuration files in /etc with vim started as a user. Saving happens with sudo write plugins or the tee trick.

Always waiting for the delay while I know what I'm doing is a bit annoying. An option to disable this behavior would be great.

**Comment by chrisbra** [comment]
Take this as a reminder to use sudoedit instead.
