### ISSUE TITLE
Border and padding of popup windows is cut off on the right side

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4747]
**Describe the bug**
Border and padding of popup windows, like after calling `popup_atcursor()`, are always cut off on the right side when the content doesn't fit on the screen.

**To Reproduce**
1. Run `vim --clean popup.vim -c "source popup.vim"`
```vim
" popup.vim
let &showbreak = '+++ '
nnoremap <silent> <space>ep
        \ :call popup_atcursor('This is a very long text to illustrate the issue...', {
        \ 'border': [1]
	\ })<cr>
```
2. Mover cursor to the right side of the window and press `<space>ep`.
3. The right border (or padding, see screenshot below) are always cut off.

**Screenshots**
![screenshot-2019-07-29_214038](https://user-images.githubusercontent.com/6266600/62077819-559aa400-b24b-11e9-97b1-94cbd623f147.png)
![screenshot-2019-07-29_214746](https://user-images.githubusercontent.com/6266600/62077824-5cc1b200-b24b-11e9-8e8a-b3e571cfdc37.png)
![screenshot-2019-07-29_214833](https://user-images.githubusercontent.com/6266600/62077825-5d5a4880-b24b-11e9-95fb-ef2425be7e22.png)

**Environment**
Vim `8.1.1773`, Gentoo Linux, xfce4-terminal

**Comment by brammool** [comment]
Does this still happen when you add a close button the the popup?

**Comment by brammool** [comment]
That requires Patch 8.1.1773

**Comment by bfrg** [comment]
With the close button everything seems fine:
![screenshot-2019-07-29_223138](https://user-images.githubusercontent.com/6266600/62080306-b082ca00-b250-11e9-8b18-de308d4cc1d0.png)

**Comment by brammool** [comment]
> With the close button everything seems fine:
> ![screenshot-2019-07-29_223138](https://user-images.githubusercontent.com/6266600/62080306-b082ca00-b250-11e9-8b18-de308d4cc1d0.png)

Yeah, so I currently made it show the right border only if it's useful.
But since when text wraps it is cut off right at the edge of the screen,
it almost looks like something is missing.

Let me remove the check for the close button.  If someone has a problem
with taking up more space we'll have to hear from them.

-- 
Article in the first Free Software Magazine: "Bram Moolenaar studied
electrical engineering at the Technical University of Delft and
graduated in 1985 on a multi-processor Unix architecture."
Response by "dimator": Could the school not afford a proper
stage for the ceremony?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Thanks for the fix. Unfortunately, it still cuts off the right border when `wrap` is off.
![screenshot-2019-07-30_204450](https://user-images.githubusercontent.com/6266600/62157105-b342f500-b30c-11e9-9385-129253b48e5c.png)
![screenshot-2019-07-30_204510](https://user-images.githubusercontent.com/6266600/62157106-b342f500-b30c-11e9-8248-0d0787ca6061.png)

**Comment by brammool** [comment]
> Thanks for the fix. Unfortunately, it still cuts off the right border when `wrap` is off.
> ![screenshot-2019-07-30_204450](https://user-images.githubusercontent.com/6266600/62157105-b342f500-b30c-11e9-9385-129253b48e5c.png)
> ![screenshot-2019-07-30_204510](https://user-images.githubusercontent.com/6266600/62157106-b342f500-b30c-11e9-8248-0d0787ca6061.png)

Yes, that was intentional.  But perhaps when "fixed" is FALSE we can do
it also when 'wrap' is off?  Considering that you mention this, you
apparently vote yes.  Like with the previous patch, we can make this
change and see if someone liked it the old way (generally users don't
complain unless they see the change).

-- 
For humans, honesty is a matter of degree.  Engineers are always honest in
matters of technology and human relationships.  That's why it's a good idea
to keep engineers away from customers, romantic interests, and other people
who can't handle the truth.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
