### ISSUE TITLE
Popup filters should override normal-mode mappings

### ISSUE THREAD

**Issue by nickspoons** [vim/vim#4759]
When interacting with popups, normal-mode mappings can interfere with popup interaction.

For a contrived example, if I have `<CR>` for some strange reason mapped to `<Nop>`:

```vim
nnoremap <CR> <Nop>
```

I now open a simple `popup_menu`:

```vim
call popup_menu(['a','b'], {})
```

I can't select an option, since the mapping is being handled before the popup filter. I would _expect_ that the Enter key here should override my normal-mode mapping.

The same thing happens with custom filter functions ([:h popup-filter](http://vimhelp.appspot.com/popup.txt.html#popup-filter)), where for example I might be entering text to filter a list, such as a buffer-selection popup. I would expect `<BS>` to be intercepted by my filter function so I can adjust my filter string, but if I have a normal-mode mapping for `<BS>` then that is executed instead.

What I would expect/prefer would be if popup filters received "raw" key strokes. If the filter returns `0` then vim can continue as normal (applying any mappings etc.).

**Comment by brammool** [comment]
Nick Jensen wrote:

> When interacting with popups, normal-mode mappings can interfere with popup interaction.
> 
> For a contrived example, if I have `<CR>` for some strange reason mapped to `<Nop>`:
> 
> ```vim
> nnoremap <CR> <Nop>
> ```
> 
> I now open a simple `popup_menu`:
> 
> ```vim
> call popup_menu(['a','b'], {})
> ```
> 
> I can't select an option, since the mapping is being handled before
> the popup filter. I would _expect_ that the Enter key here should
> override my normal-mode mapping.
> 
> The same thing happens with custom filter functions ([:h
> popup-filter](http://vimhelp.appspot.com/popup.txt.html#popup-filter)),
> where for example I might be entering text to filter a list, such as a
> buffer-selection popup. I would expect `<BS>` to be intercepted by my
> filter function so I can adjust my filter string, but if I have a
> normal-mode mapping for `<BS>` then that is executed instead.
> 
> What I would expect/prefer would be if popup filters received "raw"
> key strokes. If the filter returns `0` then vim can continue as normal
> (applying any mappings etc.).

This was still in the todo list:

	- Invoke filter with character before mapping?

Unfortunately it's not so easy, because if the filter does not consume
the key then we do want mappings to apply as usual.  And mappings might
also be used for special keys that are used by a filter.

-- 
hundred-and-one symptoms of being an internet addict:
8. You spend half of the plane trip with your laptop on your lap...and your
   child in the overhead compartment.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
> And mappings might also be used for special keys that are used by a filter.

That's true, although I can't think of many situations where the same mapping I use generally should _also_ apply to popup filters.

Perhaps a new mapping mode could be used?

```vim
" Scroll popup menus with <C-n>
pnoremap <C-n> j
```

Implementation is tricky though:

- Is there currently a popup filter in use?
  - Yes: Check for `pmaps`. Is this key or mapping intercepted by the filter?
    - Yes: Perform filter actions. Does the filter return 1?
      - Yes: Stop.

In all other cases, the _unmapped original_ key code is passed through to be checked for nmaps etc.

**Comment by nickspoons** [comment]
@brammool thanks, patches 8.1.1799 (749fa0a) and 8.1.1810 (b8350ab) work very well to allow mappings to be prevented before a popup filter.

However, when the filter returns `0` to indicate that the key has _not_ been handled, the mappings are still _not_ applied.

I suspect that the reason you haven't closed this issue is because this is still in the "to do" list, I just wanted to state it explicitly here.

**Comment by brammool** [comment]
> @brammool thanks, patches 8.1.1799 (749fa0a) and 8.1.1810 (b8350ab)
> work very well to allow mappings to be prevented before a popup
> filter.
> 
> However, when the filter returns `0` to indicate that the key has
> _not_ been handled, the mappings are still _not_ applied.
> 
> I suspect that the reason you haven't closed this issue is because
> this is still in the "to do" list, I just wanted to state it
> explicitly here.

I looked at this code, and it's not possible to use characters from the
input stream both in a mapped way and in a not mapped way.  It's simply
too complex, especially because the termcode recognition happens in
between.  You will still want cursor keys to work.  And re-mapping is
possible before and after that

Thus either mapping is enabled or not.  If the filter sometimes returns
zero it should not disable mapping.

-- 
The History of every major Galactic Civilization tends to pass through
three distinct and recognizable phases, those of Survival, Inquiry and
Sophistication, otherwise known as the How, Why and Where phases.
For instance, the first phase is characterized by the question 'How can
we eat?' the second by the question 'Why do we eat?' and the third by
the question 'Where shall we have lunch?'
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
