### ISSUE TITLE
Visual selection in popup windows exceeds into scrollbar and truncates the text when pasting the selection

### ISSUE THREAD

**Issue by bfrg** [vim/vim#4773]
This is a small visual artifact: Selecting text with the mouse will also visually select the scrollbar (see screenshot below).

The docs don't say anything about what highlight group is used for the visual selection. It looks like it uses `PmenuThumb`.

![screenshot-2019-08-04_114841](https://user-images.githubusercontent.com/6266600/62426603-34243700-b6e7-11e9-8311-7df46499e2be.png)

When selecting several lines with the mouse, Vim puts only the part that is visible in the popup window into the `*` register. When the buffer lines are longer than the popup window width, one has to make the popup window wide enough first until the entire buffer line is visible before making a selection. I'm not sure if anyone will ever need this but this is definitively different from regular windows.

**Comment by brammool** [comment]
> This is a small visual artifact: Selecting text with the mouse will
> also visually select the scrollbar (see screenshot below).
> 
> The docs don't say anything about what highlight group is used for the
> visual selection. It looks like it uses `PmenuThumb`.
> 
> ![screenshot-2019-08-04_114841](https://user-images.githubusercontent.com/6266600/62426603-34243700-b6e7-11e9-8311-7df46499e2be.png)
> 
> When selecting several lines with the mouse, Vim puts only the part
> that is visible in the popup window into the `*` register. When the
> buffer lines are longer than the popup window width, one has to make
> the popup window wide enough first until the entire buffer line is
> visible before making a selection. I'm not sure if anyone will ever
> need this but this is definitively different from regular windows.

This is not Visual selection but modeless selection.  You can only
select what you see, that is intentional.  See :help modeless-selection.

That the scrollbar is selected is a bug, I'll put that in the todo list.

-- 
I have a drinking problem -- I don't have a drink!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
