### ISSUE TITLE
Gvim only copies the last line of modeless selection

### ISSUE THREAD

**Issue by lkintact** [vim/vim#4783]
1. Create a file "1.txt" with these contents:
```
a1
b2
c3
```
2. Run `gvim.exe --clean 1.txt`
3. With <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+Left_click make a modeless selection by dragging the mouse cursor from "a" to "3" inclusive
4. Hit <kbd>:</kbd> and press <kbd>Ctrl</kbd>+<kbd>y</kbd> to put the selection into the clipboard.

Only the last line of the selection ("c3") is actually put, the other two are substituted with EOLs, which can be seen with the `:reg` command.

Vim: gvim_8.1.1824_x86.zip from https://github.com/vim/vim-win32-installer/releases
OS: Windows 10 Home 1803

**Comment by chrisbra** [comment]
This seems to be caused by patch [8.1.1534](https://github.com/vim/vim/releases/tag/v8.1.1534) (commit: bd75b5333d10e63f7a667d4b65e80d309435629e), at least I could reproduce it with https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1534 but not with the previous release https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1525
