### ISSUE TITLE
Support for "<Cmd>" in mappings (Neovim patch)

### ISSUE THREAD

**Issue by blueyed** [vim/vim#4784]
Neovim has a nice feature where you can use `<Cmd>` in a mapping to stay in the current mode (a better alternative to `vnoremap x :<C-u>…`, where you then have to handle re-entering visual mode etc).

(in the case at hand it allows for using `search` in a mapping for both normal and visual mode, https://github.com/tpope/vim-unimpaired/pull/187)

The original patch was done in https://github.com/neovim/neovim/pull/4419 by @bfredl.

Having it in Vim also would make life easier for plugin authors (in general due to its usefulness, and with regard to Neovim compatibility)

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Neovim has a nice feature where you can use `<Cmd>` in a mapping to
> stay in the current mode (a better alternative to `vnoremap x
> :<C-u>…`, where you then have to handle re-entering visual mode etc).
> 
> (in the case at hand it allows for using `search` in a mapping for both normal and visual mode, https://github.com/tpope/vim-unimpaired/pull/187)
> 
> The original patch was done in https://github.com/neovim/neovim/pull/4419 by @bfredl.

For something like this it would be nice to be pointed to the
documentation.  I can't easily figure out from the pull request what
ended up being implemented.  Apparently it's different from the original
request.

> Having it in Vim also would make life easier for plugin authors (in
> general due to its usefulness, and with regard to Neovim
> compatibility)

One complication: Since Neovim uses a different license for new code, we
can't just include a Neovim change in Vim.  We need to get the author of
the change say that this is OK to go under the Vim license.

-- 
This planet has -- or rather had -- a problem, which was this: most
of the people living on it were unhappy for pretty much of the time.
Many solutions were suggested for this problem, but most of these
were largely concerned with the movements of small green pieces of
paper, which is odd because on the whole it wasn't the small green
pieces of paper that were unhappy.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> For something like this it would be nice to be pointed to the documentation.

The documentation is in the PR -- https://github.com/neovim/neovim/pull/4419/files#diff-28587d36c24b61c33d4d01601f5974ee.

**Comment by blueyed** [comment]
The current doc: https://github.com/neovim/neovim/blob/6ebe476675923cdade0a460148209ee9f01c2fd6/runtime/doc/map.txt#L276-L303

**Comment by bfredl** [comment]
> One complication: Since Neovim uses a different license for new code, we can't just include a Neovim change in Vim. We need to get the author of the change say that this is OK to go under the Vim license.

@brammool As the author of this code, I approve this code being included in vim under the vim licence. (BTW this is true of any code I have committed to neovim, just ping me if explicit confirmation is needed for some specific case).

**Comment by brammool** [comment]
James McCoy wrote:

> > For something like this it would be nice to be pointed to the documentation.
> 
> The documentation is in the PR --
> https://github.com/neovim/neovim/pull/4419/files#diff-28587d36c24b61c33d4d01601f5974ee.

Thanks.  Yes, that looks useful.

-- 
What a wonderfully exciting cough!  Do you mind if I join you?
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Daniel Hahler wrote:

> The current doc: https://github.com/neovim/neovim/blob/6ebe476675923cdade0a460148209ee9f01c2fd6/runtime/doc/map.txt#L276-L303

"<Cmd> commands must terminate, that is, they must be followed by <CR> in the
{lhs} of the mapping definition"

Looks like that {lhs} should be {rhs}.

-- 
The only backup you need is the one that you didn't have time for.
(Murphy)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Björn Linse wrote:

> > One complication: Since Neovim uses a different license for new
> > code, we can't just include a Neovim change in Vim. We need to get
> > the author of the change say that this is OK to go under the Vim
> > license.
> 
> @brammool As the author of this code, I approve this code being
> included in vim under the vim licence. (BTW this is true of any code I
> have committed to neovim, just ping me if explicit confirmation is
> needed for some specific case).

I appreciate it.

Although just one remark like this is enough to cover all your work, we
would still have to check with you that code (and help text) was
actually written by you.  That you created the pull request is not
sufficient for that, you could have included code suggested by others.

Was there ever a discussion on the Neovim project to use a dual license
for new code?  I would be surprised if anyone would object to that, and
it makes it a lot easier to include code from Neovim into Vim.  There
would still be a gap when only the Apache license applied to new code
though.  It will be complicated to figure out what license applies to
what line of code...  But for new code it would be good to let the user
apply either the Apache or the Vim license, at his choice.  When
properly formulated that avoids blocking source to be included either
way.

-- 
hundred-and-one symptoms of being an internet addict:
29. Your phone bill comes to your doorstep in a box.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfredl** [comment]
> Although just one remark like this is enough to cover all your work, we would still have to check with you that code (and help text) was actually written by you. That you created the pull request is not sufficient for that, you could have included code suggested by others.

I guess it the depends how granular we want to go. If there is a big inclusion it should always be marked in the commit message (like "vim-patch: ..." or  "co-authored by", or "vendored library code" or something like that). But most pull requests will contain suggested changes by others of individual lines of code or documentation, it depends if one considers copyright applies to such small changes. I guess no one really bothers about that.

> Was there ever a discussion on the Neovim project to use a dual license for new code? 

I guess we should ask @justinmk about that. Once Neovim had a CLA for relicensing, but we dropped it, because we thought it was not worth the effort, and it could be interpreted as not allowing vendored code, or something.

**Comment by chdiza** [comment]
I don't get this.  Vim is a modal editor.  If you're in e.g. visual mode and want to execute an ex-mode command, you're *supposed* to switch modes first.

**Comment by blueyed** [comment]
@chdiza 
It's for mappings/plugins.
Currently you would have to use e.g. `:<C-U>exe 'normal! gv'<Bar>…` there (via https://github.com/tpope/vim-unimpaired/commit/ab7082c0e89df594a5ba111e18af17b3377d216d) to stay in visual mode.

**Comment by chdiza** [comment]
> It's for mappings/plugins.

I know that.

> Currently you would have to use e.g. :<C-U>exe 'normal! gv'\<Bar\>…

The horror!!  How will we ever be able to keep going?

**Comment by bfredl** [comment]
@chdiza Commands are not by necessity tied to interactive ex-mode, they also form the statements of Vim script. This is more comparable to executing a command in a timer (which occurs in every interactive mode already) or an autocmd, or (with a lot of restrictions, that this avoids) in a function called by `<expr>` mapping.  Using `<cmd>` in any interactive way is explicitly disabled, you have to use a complete command in a mapping, just like an autocmd has to be a complete command.

**Comment by chdiza** [comment]
> Commands are not by necessity tied to interactive ex-mode, they also form the statements of Vim script.

I know that, of course.

This is not very analogous to autocmds at all.  Unlike an autocmd, a mapping is supposed to bind a LHS to a sequence of typed keys so that it merely serves as a kind of abbreviation for typing.  If one were typing, one would and should switch modes.  So a mapping should also make you switch modes.

It's not a good idea to change the meaning of *mapping* from "basically an abbreviation" to "either an abbreviation, or something else entirely", when the sole "benefit" is that you don't have to put `<C-U>` and `gv` in a plugin line.

I could understand advocating for a new native ex mode command that does the equivalent of `norm gv` while also killing an unintentional range.  I don't understand futzing with the nature of mapping.

**Comment by chdiza** [comment]
Put another way: in a Fmap command, where F is the mapmode, it should not be possible for the RHS to be something that you could not possibly have simply typed in while in F mode.

**Comment by chdiza** [comment]
(Especially when  "F" is "v" or "n" or "i")

**Comment by bfredl** [comment]
> This is not very analogous to autocmds at all.

This was one example out of many, of commands already being executed in every mode, contrary to the claim that commands are somehow tied to ex/cmdline mode, which hasn't been true for a long time.

>  when the sole "benefit" is that you don't have to put <C-U> and gv in a plugin line.

Not sure where it was claimed this was the sole benefit. This does not only apply to visual mode.

> It's not a good idea to change the meaning of mapping from "basically an abbreviation" to "either an abbreviation, or something else entirely". Put another way: in a Fmap command, where F is the mapmode, it should not be possible for the RHS to be something that you could not possibly have simply typed in while in F mode.

But mappings can certainly do a lot of other stuff entirely. In an `<expr>` mapping you can already run a restricted subset of commands, or start a timer that 1ms later calls a function which invokes any ex command without restriction, and no mode switching involved. I just thought it was weird that a plugin couldn't do this directly by a mapping, what a timer or job event handler already can do.

My first impulse was actually to remove restrictions of the `<expr>` mechanism, but it turned out to be harder to do in practice, and would actually break internal assumptions of how mappings are implemented. `<cmd>...<cr>` could be implemented reasonably as an analogy of timers/events executing in any mode (i e when we know commands are already safe to execute). 

So the possible counter-argument against this is rather that is is redundant ("just use an `<expr>` mapping that start a timer which calls a function that runs the command oh and also evaluates to the empty string, already") not that it breaks some rule what a mapping should or shouldn't do, which it does not.

**Comment by justinmk** [comment]
> it should not be possible for the RHS to be something that you could not possibly have simply typed in while in F mode.

That's already violated by other pseudo-keys such as `<SID>`, `<cursorhold>`, etc.

If you're looking for consistency, Vim is the wrong place to look.

**Comment by brammool** [comment]
> Put another way: in a Fmap command, where F is the mapmode, it should
> not be possible for the RHS to be something that you could not
> possibly have simply typed in while in F mode.

The mode is for the user: In different modes different actions are
triggered by the same keys.  The <Cmd> mapping is for when you want to
do something no matter what mode you are in.  Ideally without changing
the state (e.g. Visual mode).   Think of opening a preview window with a
dictionary, looking up help, open a Man page, etc.  Plugin writers often
struggle with making their functionality available in several modes, and
this <Cmd> mechanism helps with it.

-- 
Give a man a computer program and you give him a headache,
but teach him to program computers and you give him the power
to create headaches for others for the rest of his life...
        R. B. Forest

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by carlobaldassi** [comment]
Disregard this, I have found a workaround based on `<expr>`, sorry for the noise...

~~Here's another example of something that, as a plugin author, I wanted to do and which I have only been able to achieve with the `<Cmd>` mechanism: I wanted to remap `<Tab>` (or rather the wildchar in general) so that under some conditions the command line is manipulated, but if those conditions aren't met then the usual wildchar behavior applies. Without `<Cmd>`, any mapping that I try (e.g. using `<C-\>e`) does not preserve the wildmenu status and I can't use `<Tab>` or `<S-Tab>` to cycle between available completions. With `<Cmd>`, i can call `feedkeys` instead, and use that either to manipulate the command line (as if the user was typing something) or fallback to feeding an un-mapped `<Tab>` or `<S-Tab>`, and that works transparently.
Example code: [here's the mapping](https://github.com/JuliaEditorSupport/julia-vim/blob/012c1086ca573cb5dd3ac00acde0adf327430c5b/autoload/LaTeXtoUnicode.vim#L476-L478) and [here's the function that gets called](https://github.com/JuliaEditorSupport/julia-vim/blob/012c1086ca573cb5dd3ac00acde0adf327430c5b/autoload/LaTeXtoUnicode.vim#L422-L467).~~

**Comment by subnut** [comment]
@brammool It seems you agree that this should be included in vim.
Then why hasn't this been included yet?

**Comment by bfredl** [comment]
@subnut I think any vim contriubutor could help with porting the patch and writing test for the vim test suite etc :)

**Comment by brammool** [comment]
I didn't see a patch for Vim yet, is it somewhere?

**Comment by lacygoill** [comment]
Fixed by [8.2.1978](https://github.com/vim/vim/releases/tag/v8.2.1978).

This todo item is no longer relevant:

https://github.com/vim/vim/blob/659bb2275e1c407709e2ac949044d6b256de5550/runtime/doc/todo.txt#L420-L421
