### ISSUE TITLE
E315 when deleting a fold with `zd`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#4834]
**Describe the bug**

While trying to remove a fold, the error `E315` is raised and some text is wrongly removed in addition to the fold marker.

**To Reproduce**

Here's a single shell command reproducing the error:

    $ vim -Nu NONE --cmd 'set fdm=marker' +"put! =['fu! Func() {{{1', 'endfu']" +'sil %y' +'wincmd w' +'exe "norm! ix\eVpzd"' -o /tmp/.a.vim /tmp/.b.vim

**Expected behavior**

The first line of the fold was originally:

    fu! Func() {{{1

After pressing `zd`, I would expect:

    fu! Func() 

But in fact, I get:

    fu! 

`Func()` has been wrongly removed.

**Screenshots**

Here's a gif reproducing the issue in an interactive usage:

![gif](https://user-images.githubusercontent.com/8505073/63246074-17007400-c262-11e9-801a-2282037431fb.gif)

**Environment**

 - Vim version: 8.1  Included patches: 1-1888
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: xterm (patch 322)

**Comment by lacygoill** [comment]
I'm not sure I did it correctly, but I tried to get a backtrace: [backtrace.txt](https://github.com/vim/vim/files/3514811/backtrace.txt)

**Comment by chrisbra** [comment]
I can reproduce it. The problem is, when the folds will be updated after the `put`, the buffer still has 1 additional line. `nv_do_put()` does already handle this condition (see [here](https://github.com/vim/vim/blob/master/src/normal.c#L9405-L9409)), but does not call `changed_lines()` and therefore the folds are not correctly updated. Later on deleting the fold markers, Vim therefore tries to access this additional line from the folds.

I tried to fix this by calling `deleted_lines(curbuf->b_ml.ml_line_count, 1);` after `ml_delete()` in `nv_do_put` (right after the above mentioned comment). However This will call `foldUpdate()` with the arguments `(top=3, bot=2)` which is wrong. This happens because deleted_lines will call `changed_lines(lnum, 0, lnum + count, -count);` and later in `changed_common()` it will call 
`foldUpdate(wp, lnum, lnume + xtra - 1);`, meaning `bot` will always be one less than top. That looks really wrong. I wonder if this should be changed to `foldUpdate(wp, lnum, lnume + abs(xtra) - 1);`.

Here is a patch, that works around this problem:

```patch
diff --git a/src/change.c b/src/change.c
index f83587d83..7fc385e8f 100644
--- a/src/change.c
+++ b/src/change.c
@@ -518,7 +518,7 @@ changed_common(
 #ifdef FEAT_FOLDING
            // Update the folds for this window.  Can't postpone this, because
            // a following operator might work on the whole fold: ">>dd".
-           foldUpdate(wp, lnum, lnume + xtra - 1);
+           foldUpdate(wp, lnum, lnume + abs(xtra) - 1);

            // The change may cause lines above or below the change to become
            // included in a fold.  Set lnum/lnume to the first/last line that
diff --git a/src/fold.c b/src/fold.c
index 4cc7a477d..c84609989 100644
--- a/src/fold.c
+++ b/src/fold.c
@@ -1813,8 +1813,8 @@ deleteFoldMarkers(
 /*
  * Delete marker "marker[markerlen]" at the end of line "lnum".
  * Delete 'commentstring' if it matches.
- * If the marker is not found, there is no error message.  Could a missing
- * close-marker.
+ * If the marker is not found, there is no error message.
+ * Could be a missing close-marker.
  */
     static void
 foldDelMarker(linenr_T lnum, char_u *marker, int markerlen)
@@ -1826,6 +1826,9 @@ foldDelMarker(linenr_T lnum, char_u *marker, int markerlen)
     char_u     *cms = curbuf->b_p_cms;
     char_u     *cms2;

+    // safety check
+    if (lnum > curbuf->b_ml.ml_line_count)
+       return;
     line = ml_get(lnum);
     for (p = line; *p != NUL; ++p)
        if (STRNCMP(p, marker, markerlen) == 0)
@@ -2741,8 +2744,8 @@ foldUpdateIEMSRecurse(
        fold_changed = TRUE;
     }

-    /* Delete contained folds from the end of the last one found until where
-     * we stopped looking. */
+    // Delete contained folds from the end of the last one found until where
+    // we stopped looking.
     foldRemove(&fp->fd_nested, startlnum2 - fp->fd_top,
                                                  flp->lnum - 1 - fp->fd_top);

diff --git a/src/normal.c b/src/normal.c
index 283ba7c4a..89996ce2f 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -9425,6 +9425,7 @@ nv_put_opt(cmdarg_T *cap, int fix_indent)
        if (empty && *ml_get(curbuf->b_ml.ml_line_count) == NUL)
        {
            ml_delete(curbuf->b_ml.ml_line_count, TRUE);
+           deleted_lines(curbuf->b_ml.ml_line_count, 1);

            /* If the cursor was in that line, move it to the end of the last
             * line. */
diff --git a/src/testdir/test_fold.vim b/src/testdir/test_fold.vim
index c0641f74e..5d2298143 100644
--- a/src/testdir/test_fold.vim
+++ b/src/testdir/test_fold.vim
@@ -764,3 +764,18 @@ func Test_address_relative_fold()

   bw!
 endfunc
+
+func Test_delete_foldmarker()
+  new
+  let expected=['fu! Func() ', 'endfu']
+  call setline(1, ['fu! Func() '.. '{{{1', 'endfu'])
+  setl fen fdm=marker
+  :%y
+  new
+  setl fen fdm=marker
+  norm! Vpzd
+  call assert_equal(expected, getline(1, '$'))
+  sil %d _
+  bw!
+  bw!
+endfunc
```

**Comment by lacygoill** [comment]
I can confirm that the patch fixes the issue. Thank you very much for the detailed explanation.

**Comment by brammool** [comment]
> I can reproduce it. The problem is, when the folds will be updated
> after the `put`, the buffer still has 1 additional line. `nv_do_put()`
> does already handle this condition (see
> [here](https://github.com/vim/vim/blob/master/src/normal.c#L9405-L9409)),
> but does not call `changed_lines()` and therefore the folds are not
> correctly updated. Later on deleting the fold markers, Vim therefore
> tries to access this additional line from the folds.

Thanks for looking into this.

> I tried to fix this by calling
> `deleted_lines(curbuf->b_ml.ml_line_count, 1);` after `ml_delete()` in
> `nv_do_put` (right after the above mentioned comment). However This
> will call `foldUpdate()` with the arguments `(top=3, bot=2)` which is
> wrong. This happens because deleted_lines will call
> `changed_lines(lnum, 0, lnum + count, -count);` and later in
> `changed_common()` it will call 
> `foldUpdate(wp, lnum, lnume + xtra - 1);`, meaning `bot` will always
> be one less than top. That looks really wrong. I wonder if this should
> be changed to `foldUpdate(wp, lnum, lnume + abs(xtra) - 1);`.

No, I think it was correct.  The problem is that when adjusting folds
and it runs into the end of the buffer, it doesn't adjust the length of
the last fold.


-- 
Where do you want to crash today?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
