### ISSUE TITLE
Popup displaying buffer cannot be scrolled if the buffer contains signs

### ISSUE THREAD

**Issue by nickspoons** [vim/vim#4882]
**Describe the bug**
Following from #4876. If a popup is opened to display part of a buffer (for example, displaying quickfix errors in a preview popup as described in the linked issue), the popup cannot be programatically scrolled if there are signs in the buffer.

Note that this only applies to buffers which are _currently_ displayed, in a window in the current tab. If the buffer is hidden or open in another tab, the popup can still be scrolled. It also doesn't matter whether the sign is actually visible - this still happens with `set signcolumn=no`.

**To Reproduce**
1. Run `vim --clean popup.vim -c "source %"`

```vim
" popup.vim
function! s:popup_filter(winid, key)
  if a:key ==# "\<c-k>"
    call win_execute(a:winid, "normal! \<c-y>")
    return v:true
  elseif a:key ==# "\<c-j>"
    call win_execute(a:winid, "normal! \<c-e>")
    return v:true
  elseif a:key ==# "\<c-u>"
    call win_execute(a:winid, 'normal! gg')
    return v:true
  elseif a:key ==# "\<c-d>"
    call win_execute(a:winid, 'normal! G')
    return v:true
  elseif a:key ==# 'q' || a:key ==# 'x' || a:key ==# "\<Esc>"
    return popup_filter_menu(a:winid, 'x')
  endif
  return v:false
endfunction

sign define POPUP_SIGN text=*
" This sign breaks scrolling the popup - try with and without it
execute 'sign place 99 line=1 name=POPUP_SIGN file=' .. expand('%')

let winid = popup_create(bufnr(), #{
\ filter: function('s:popup_filter'),
\ firstline: 20,
\ close: 'button',
\ minwidth: 60,
\ maxwidth: 60,
\ minheight: 10,
\ maxheight: 10
\})
```

2. Press `<C-j>` or `<C-k>` repeatedly to scroll the popup
3. The popup repeatedly jumps back to its original position - `<C-u>` and `<C-d>` do nothing
3. Remove the `sign place...` line and run `vim --clean popup.vim -c "source %"` again
4. The buffer in the popup can now be scrolled as expected.
   **Note:** A different but related? bug occurs on the _first_ `<C-j>`, which scrolls a few lines _up_ instead of down. After this, all scrolling works correctly.

**Expected behavior**
It should be possible to use `<C-j>`/`<C-k>`/`<C-d>`/`<C-u>` to scroll the popup buffer, just as you can when the buffer does not contain signs.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment**
 - Vim version `v8.1.1954`

**Comment by brammool** [comment]
Nick Jensen wrote:

> **Describe the bug**
> Following from #4876. If a popup is opened to display part of a buffer
> (for example, displaying quickfix errors in a preview popup as
> described in the linked issue), the popup cannot be programatically
> scrolled if there are signs in the buffer.
> 
> Note that this only applies to buffers which are _currently_
> displayed, in a window in the current tab. If the buffer is hidden or
> open in another tab, the popup can still be scrolled. It also doesn't
> matter whether the sign is actually visible - this still happens with
> `set signcolumn=no`.
> 
> **To Reproduce**
> 1. Run `vim --clean popup.vim -c "source %"`
> 
> ```vim
> " popup.vim
> function! s:popup_filter(winid, key)
>   if a:key ==# "\<c-k>"
>     call win_execute(a:winid, "normal! \<c-y>")
>     return v:true
>   elseif a:key ==# "\<c-j>"
>     call win_execute(a:winid, "normal! \<c-e>")
>     return v:true
>   elseif a:key ==# "\<c-u>"
>     call win_execute(a:winid, 'normal! gg')
>     return v:true
>   elseif a:key ==# "\<c-d>"
>     call win_execute(a:winid, 'normal! G')
>     return v:true
>   elseif a:key ==# 'q' || a:key ==# 'x' || a:key ==# "\<Esc>"
>     return popup_filter_menu(a:winid, 'x')
>   endif
>   return v:false
> endfunction
> 
> sign define POPUP_SIGN text=*
> " This sign breaks scrolling the popup - try with and without it
> execute 'sign place 99 line=1 name=POPUP_SIGN file=' .. expand('%')
> 
> let winid = popup_create(bufnr(), #{
> \ filter: function('s:popup_filter'),
> \ firstline: 20,
> \ close: 'button',
> \ minwidth: 60,
> \ maxwidth: 60,
> \ minheight: 10,
> \ maxheight: 10
> \})
> ```
> 
> 2. Press `<C-j>` or `<C-k>` repeatedly to scroll the popup
> 3. The popup repeatedly jumps back to its original position - `<C-u>`
> and `<C-d>` do nothing
> 3. Remove the `sign place...` line and run `vim --clean popup.vim -c
> "source %"` again
> 4. The buffer in the popup can now be scrolled as expected.

What happens is that "firsline" is still set, and when redrawing the
popup it may use this, instead of the topline that is changed with
CTRL-E and CTRL-Y.  You can fix it by resetting 'firstline':

function! s:popup_filter(winid, key)
  if a:key ==# "\<c-k>"
    call popup_setoptions(a:winid, #{firstline: 0})
    call win_execute(a:winid, "normal! \<c-y>")
    return v:true
  elseif a:key ==# "\<c-j>"
    call popup_setoptions(a:winid, #{firstline: 0})
    call win_execute(a:winid, "normal! \<c-e>")
    return v:true
  elseif a:key ==# "\<c-u>"
    call popup_setoptions(a:winid, #{firstline: 0})
    call win_execute(a:winid, 'normal! gg')
    return v:true
  elseif a:key ==# "\<c-d>"
    call popup_setoptions(a:winid, #{firstline: 0})
    call win_execute(a:winid, 'normal! G')
    return v:true
  elseif a:key ==# 'q' || a:key ==# 'x' || a:key ==# "\<Esc>"
    return popup_filter_menu(a:winid, 'x')
  endif
  return v:false
endfunction


>    **Note:** A different but related? bug occurs on the _first_
>    `<C-j>`, which scrolls a few lines _up_ instead of down. After
>    this, all scrolling works correctly.

This happens because 'scrolloff' is set, it defaults to 5.  Since we
don't normally use the cursor in a popup window, we should set
'scrolloff' to zero, to avoid surprises like this.

-- 
hundred-and-one symptoms of being an internet addict:
162. You go outside and look for a brightness knob to turn down the sun.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Why isn't `firstline` reset automatically after the popup window is created? If `firstline` should be set to 0 by the user once the window is created, it should be mentioned in the documentation. Otherwise it's just a matter of time until someone else stumbles upon the same issue.

I personally can't think of an example where I would need `firstline` after the popup window was created (maybe after resizing windows?). Having CTRL-L jump back to the original buffer line that was passed to `popup_create()` is a nice feature, but probably not always needed. There's always the option to add a new key to the `popup-filter` function to achieve this (e.g. CTRL-R, R as in reset):
```vim
function! s:popup_filter(winid, key)
  if a:key ==# "\<c-r>"
    call popup_setoptions(a:winid, #{firstline: 20})
    return v:true
  elseif a:key ==# "\<c-j>"
    " ... as before
  endif
  return v:false
endfunction
```
In most cases users will want to display something like a function definition in a popup window. For that `firstline` will be set to the beginning of the function. Scrolling the window up and down without constantly having to set `firstline` to 0 seems more useful than keeping the initially set `firstline` value around. At least, I can't think of the motivation behind it.

By the way, scrolling the popup window with the mouse worked perfectly fine, no matter whether or not signs were defined in the buffer. It looks like when the mouse is used for scrolling, `firstline` is reset every time, since CTRL-L won't scroll the window back to its original position when it was created. I personally would have expected a similar behavior when the popup window was scrolled using a filter function.

**Comment by brammool** [comment]
> Why isn't `firstline` reset automatically after the popup window is
> created? If `firstline` should be set to 0 by the user once the window
> is created, it should be mentioned in the documentation. Otherwise
> it's just a matter of time until someone else stumbles upon the same
> issue.

The "firstline" value is the main way how to specify what text to show
in a popup window that scrolls.  Using Normal mode commands is a bit of
a strange way.  Instead of that you could increment or decrement
"firstline".

Is there a specific reason to use Normal mode commands for the
scrolling?

> I personally can't think of an example where I would need `firstline`
> after the popup window was created (maybe after resizing windows?).
> Having CTRL-L jump back to the original buffer line that was passed to
> `popup_create()` is a nice feature, but probably not always needed.
> There's always the option to add a new key to the `popup-filter`
> function to achieve this (e.g. CTRL-R, R as in reset):
> ```vim
> function! s:popup_filter(winid, key)
>   if a:key ==# "\<c-r>"
>     call popup_setoptions(a:winid, #{firstline: 20})
>     return v:true
>   elseif a:key ==# "\<c-j>"
>     " ... as before
>   endif
>   return v:false
> endfunction
> ```
> In most cases users will want to display something like a function
> definition in a popup window. For that `firstline` will be set to the
> beginning of the function. Scrolling the window up and down without
> constantly having to set `firstline` to 0 seems more useful than
> keeping the initially set `firstline` value around. At least, I can't
> think of the motivation behind it.

The idea is that "firstline" is changed to scroll the window.
 
> By the way, scrolling the popup window with the mouse worked perfectly
> fine, no matter whether or not signs were defined in the buffer. It
> looks like when the mouse is used for scrolling, `firstline` is reset
> every time, since CTRL-L won't scroll the window back to its original
> position when it was created. I personally would have expected a
> similar behavior when the popup window was scrolled using a filter
> function.

When scrolling with the mouse "firstline" is adjusted to the top line of
the window.

-- 
hundred-and-one symptoms of being an internet addict:
166. You have been on your computer soo long that you didn't realize
     you had grandchildren.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Thank you for clearing that up. I couldn't think of another way to scroll the popup window before, and using Normal mode commands seemed like the natural choice since that's how we scroll regular windows.

When scrolling the popup window using `firstline`, how can we set an upper limit for `firstline`? If we don't set an upper limit, it will be continuously incremented on every key press. While visually the popup window will stop scrolling at the very last line of the buffer, `firstline` will still be incremented.

At the moment there's no vimscript function to obtain the number of lines of a buffer, apart from `len(getbufline(bufnr, 1, '$')`. This has been discussed [before](https://github.com/vim/vim/pull/2441#issuecomment-351711643).

The following works but the `win_execute(a:winid, 'let g:nlines = lines("$")')` looks weird:
```vim
function! s:popup_filter(winid, key) abort
    if a:key == "\<c-k>"
        let firstline = popup_getoptions(a:winid).firstline
        let newline = (firstline - 2) > 0 ? (firstline - 2) : 1
        call popup_setoptions(a:winid, #{firstline: newline})
        return v:true
    elseif a:key == "\<c-j>"
        let firstline = popup_getoptions(a:winid).firstline
        call win_execute(a:winid, 'let g:nlines = line("$")')
        let newline = firstline < g:nlines ? (firstline + 2) : g:nlines
        unlet g:nlines
        call popup_setoptions(a:winid, #{firstline: newline})
        return v:true
    elseif a:key ==# 'q'
        call popup_close(a:winid)
        return v:true
    endif
    return v:false
endfunction
```

**Comment by brammool** [comment]
> Thank you for clearing that up. I couldn't think of another way to
> scroll the popup window before, and using Normal mode commands seemed
> like the natural choice since that's how we scroll regular windows.

Well, it requires using win_execute(), that doesn't seem so natural.
 
> When scrolling the popup window using `firstline`, how can we set an
> upper limit for `firstline`? If we don't set an upper limit, it will
> be continuously incremented on every key press. While visually the
> popup window will stop scrolling at the very last line of the buffer,
> `firstline` will still be incremented.
> 
> At the moment there's no vimscript function to obtain the number of
> lines of a buffer, apart from `len(getbufline(bufnr, 1, '$')`. This
> has been discussed
> [before](https://github.com/vim/vim/pull/2441#issuecomment-351711643).

Yes, it's actually difficult to get the line count of a buffer in
another window.  It was possible to briefly jump to that window as a
workaround, but for popup windows that is not possible.

I added a "winid" argument to line() in patch 8.1.1967.  That should
make all this possible.


-- 
Did you ever see a "Hit any key to continue" message in a music piece?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
Why use "winid", isn't that unnecessarily limiting? Wouldn't "bufnum" be more generically useful here? Users might want to find the number of lines of a buffer they haven't opened a window onto yet.

For that matter, an `{expr}` like `bufname()` takes would be very useful, then you could do `line('$', '#')` to get the number of lines in the alternate buffer.

**Comment by brammool** [comment]
Nick Jensen wrote:

> Why use "winid", isn't that unnecessarily limiting? Wouldn't "bufnum"
> be more generically useful here? Users might want to find the number
> of lines of a buffer they haven't opened a window onto yet.
> 
> For that matter, an `{expr}` like `bufname()` takes would be very
> useful, then you could do `line('$', '#')` to get the number of lines
> in the alternate buffer.

A window always has a buffer, while a buffer does not have a cursor
position.  Also "w0" and "w$" only work for a window.

-- 
Living in Hollywood is like living in a bowl of granola.  What ain't
fruits and nuts is flakes.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
> A window always has a buffer, while a buffer does not have a cursor
> position.  Also "w0" and "w$" only work for a window.

Ah, good points.

Thanks for the popup updates, they're working very well!
