### ISSUE TITLE
"make test_popupwin" fails after doing "export LANG=C"

### ISSUE THREAD

**Issue by dpelle** [vim/vim#4884]
`test_popwin` fails and is very slow after doing `export LANG=C`.

*Steps to reproduce*
```
$ cd vim/src/testdir
$ export LANG=C
$ make test_popupwin
```
I see that with `export LANG=C`, popups look like this: 
```
1        +----------------------+
2        | first notification   |   
3        +----------------------+ 
```
whereas without `LANG=C`, they look like this:
```
1        ╔══════════════════════╗
2        ║ first notification   ║
3        ╚══════════════════════╝
```
... which is fine but the test do not cope with that.

I suppose that tests are slow because they timeout
waiting for the expected output.

**Environment**
 - vim-8.1.1954 
 - xubuntu-18.04.3
 - xfce4-terminal 0.8.7.4

**Comment by brammool** [comment]
Dominique wrote:

> `test_popwin` fails and is very after doing `export LANG=C`.
> 
> *Steps to reproduce*
> ```
> $ cd vim/src/testdir
> $ export LANG=C
> $ make test_popupwin
> ```
> I see that with `export LANG=C`, popups look like this: 
> ```
> 1        +----------------------+
> 2        | first notification   |   
> 3        +----------------------+ 
> ```
> whereas without `LANG=C`, they look like this:
> ```
> 1        ╔══════════════════════╗
> 2        ║ first notification   ║
> 3        ╚══════════════════════╝
> ```
> ... which is fine but the test do not cope with that.

Ah, it's because 'encoding' then defaults to latin1.  For the tests
themselves we force 'encoding' to be utf-8, but when running Vim in a
terminal this doesn't happen.

> I suppose that tests are slow because they timeout
> waiting for the expected output.

Yes, screenshots always wait two seconds until there is a match, to
account for a slow machine (like on CI).

-- 
hundred-and-one symptoms of being an internet addict:
158. You get a tuner card so you can watch TV while surfing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
