### ISSUE TITLE
Popup scrolling and color scheme

### ISSUE THREAD

**Issue by arbitrary-dev** [vim/vim#4914]
### Describe the bug

I've created an issue in a different project:
https://github.com/neoclide/coc-tsserver/issues/69

But they were unable to help me.

I believe this diagnostic view is created using popups in Vim. But I were unable to find any wiki or `:help popup` on which keys to use to scroll the popup text.

Also I'd like to know which `:hi` group does it use.

Could you be so kind to help me?

### Environment
  ```
  VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 22 2019 04:02:38)
  macOS version
  Included patches: 1-1900
  Compiled by Homebrew
  ```
 - macOS 10.13.2
 - Terminal Version 2.8 (400)

**Comment by chrisbra** [comment]
is the plugin actually using the popup window?

**Comment by brammool** [comment]
> ### Describe the bug
> 
> I've created an issue in a different project:
> https://github.com/neoclide/coc-tsserver/issues/69
> 
> But they were unable to help me.

Confusing, they mention Neovim, but clearly the popup is for Vim 8.1.

> I believe this diagnostic view is created using popups in Vim. But I
> were unable to find any wiki or `:help popup` on which keys to use to
> scroll the popup text.
> 
> Also I'd like to know which `:hi` group does it use.
> 
> Could you be so kind to help me?

Popup windows are mainly under control of the plugin writer.  Scrolling
works with the mouse (scroll wheel or clicking in the scrollbar).  There
are no key controls by default (because that would take away keys from
the main view).  The plugin author can add a filter to allow for
scrolling with keys.

The popup menu uses Pmenu by default.

-- 
hundred-and-one symptoms of being an internet addict:
227. You sleep next to your monitor.  Or on top of it.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chemzqm** [comment]
The plugin uses popup on vim 8.1 and floating window on neovim.

coc.nvim uses `CocFloating` highlight group for popup.

**Comment by chrisbra** [comment]
so it's the plugin authors responsibility to allow scrolling using the keyboard. This makes it a non-bug for Vim. @chemzqm please consider adding some filtering to your plugin so one can scroll the popup window. Thanks.
