### ISSUE TITLE
":echo 09" should raise error

### ISSUE THREAD

**Issue by ghost** [vim/vim#4921]
:echo 0xg
↓
E15: Invalid expression: 0xg

I think It's OK.

:echo 09
↓
9

It's not good because an octal number starts with a zero and 09 should take care as invalid octal number.

**Comment by brammool** [comment]
This was a bad choice a long time ago.  Unfortunately, we can't change it now without breaking things.  Perhaps we could add an option to disable using a leading zero for octal, but since we can't enable that by default it won't have much effect.

**Comment by tonymec** [comment]
```vim
:let x = 011
:echo x
        9
:let x = 08
:echo x
        8
```
IOW, as an expression in a `let` statement, a Number beginning with zero is also interpreted as octal if all its digits are in the range [0-7], as decimal otherwise. The present state of affairs doesn't produce an error in one case and not in the other. Maybe it should be better documented under `:help expr-number` but otherwise I also think the actual behaviour shouldn't change.

**Comment by k-takata** [comment]
> Perhaps we could add an option to disable using a leading zero for octal,

How about using `:scriptversion`?

**Comment by brammool** [comment]
Yes, using scriptversion for this would be good.  We might also support swiss notation at the same time: 1'000'000.00 for a million.

**Comment by chrisbra** [comment]
so I think this can be closed since using `scriptversion 4` has been introduced in 60a8de28d11595f4df0419ece8afa7d6accc9fbd
