### ISSUE TITLE
":write [z-a].txt" writes the file, but emits an E944

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5059]
1. Run `gvim --clean`
2. Execute `:write [z-a].txt`
3. Gvim creates a file with the specified name, but displays an "E944: Reverse range in character class" error.

Gvim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2151/gvim_8.1.2151_x86_signed.zip,
Windows 10 Home 1803

**Comment by brammool** [comment]
> 1. Run `gvim --clean`
> 2. Execute `:write [z-a].txt`
> 3. Gvim creates a file with the specified name, but displays an "E944: Reverse range in character class" error.
> 
> Gvim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2151/gvim_8.1.2151_x86_signed.zip,
> Windows 10 Home 1803

Normally [ and ] are not in 'isfname'.  When expanding fails it may
still work, but probably not everywhere.  You can use backslashes to
escape, but since MS-Windows uses backslash as a path separater this
often becomes confusing.  Blame Microsoft...

-- 
Lawmakers made it obligatory for everybody to take at least one bath
each week -- on Saturday night.
		[real standing law in Vermont, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lkintact** [comment]
Sorry if I don't understand something, but since "[" and "]" are in 'isfname' by default on Windows systems, shouldn't Gvim just not make any attempts to expand the `[z-a]` part and write the file as is?

**Comment by eirnym** [comment]
I agree, there's no reason to expand a filename while saving.

**Comment by markuspeloquin** [comment]
```
cmdexpand.c:1979:19: error: use of undeclared identifier 'WILD_NOERROR'
```

It looks like the flag wasn't added to vim.h.
