### ISSUE TITLE
4913 5036 5159, what document is this?How can you disable the creation of such a file?

### ISSUE THREAD

**Issue by fantastic2085** [vim/vim#5145]
4913 5036 5159, what document is this?How can you disable the creation of such a file?

**Comment by k-takata** [comment]
What are you talking about?

**Comment by fantastic2085** [comment]
4913 5036 5159 These files vim produced I want to forbid vim to produce such files

**Comment by fantastic2085** [comment]
**3.10.0-957.el7.x86_64 centos7** 

**vim --version**
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 30 2018 19:56:57)
Included patches: 1-160, 399, 402-403, 1099
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>

**Comment by k-takata** [comment]
Your Vim is too old. Please update to 8.1.xxxx and show a reproducible way using `vim --clean`.
(`--clean` is a new option since 8.0.0716. If you still need to use 7.4, try with `vim -N -u NONE -i NONE`.)

**Comment by fantastic2085** [comment]
Thank you very much!
Another question:
I added set nobackup to /etc/vimrc, but when I looked at the distributed file system log, it was still generated, only it was deleted. 
How do I disable backup files?Create a backup file first, then delete the backup file, after all, produced a backup file

**Comment by k-takata** [comment]
See `:help 'writebackup'`.

**Comment by chrisbra** [comment]
> 4913 5036 5159

You are not giving much details. However, my guess is, that are you are seeing those filenames whenever Vim writes a buffer. When Vim writes a buffer to the disk, it checks whether it is possible to write new files or not by writing arbitrary 4 digit letter files starting with 4913 (and incrementing by 123). I am not sure, why those filenames persist for you, is there anything unusual in your setup?

We had reports about those files because on Windows anti-virus software opened those files and thus prevented proper file deletion. But I suppose that is not your problem.

In any case, you could try to `:set backupcopy=yes` (not auto)
