### ISSUE TITLE
doc/map.txt seems to have a missing reference

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5168]
line 359 of doc/map.txt  is
`:lmap  :lnoremap  :lunmap  :lmapclear	    yes*       yes*	  yes*`

Apparently there should be an asterisk related to the ones appended to the `yes`es somewhere below the line, but there's none.

Vim 8.1.2244

**Comment by tonymec** [comment]
IIUC, the missing footnote is
```
Note:
    * If 'iminsert' is 1, see |language-mapping| below.
```
Best regards,
Tony.

**Comment by brammool** [comment]
Tony wrote:

> IIUC, the missing footnote is
> ```
> Note:
>     * If 'iminsert' is 1, see |language-mapping| below.
> ```

I'll add it back, thanks.

-- 
How To Keep A Healthy Level Of Insanity:
9. As often as possible, skip rather than walk.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by samad123qw** [comment]
This page contains the following errors:

error on line 1 at column 7: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

**Comment by samad123qw** [comment]
أرجو الرد على هذه المقاله /This page contains the following errors:

error on line 1 at column 7: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

**Comment by brammool** [comment]
Reported problem was fixed.  XML declaration error seems misplaced.
