### ISSUE TITLE
Is there a way to redraw a specific popup window?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5169]
Is there a way to redraw a specific popup window?

**Comment by brammool** [comment]
> Is there a way to redraw a specific popup window?

What would you need that for?

You could change a property to trigger a redraw.

-- 
How To Keep A Healthy Level Of Insanity:
10. Ask people what sex they are. Laugh hysterically after they answer.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
I wanted to implement a statusline using the popup window, as there is a `redrawstatus` command, I was thinking whether there is a way to redraw a specific popup window so that I can mimic the `redrawstatus`. Now I don't need this feature any more, thanks.

![111](https://user-images.githubusercontent.com/2705841/68107829-fcfd3600-ff20-11e9-9a08-6eb6cdb0423f.gif)

**Comment by Yggdroot** [comment]
> You could change a property to trigger a redraw.

Does this only redraw the specific popup or the whole screen?
Can `popup_setoptions(popup_getoptions())`  cause a redraw?

Thanks.

**Comment by brammool** [comment]
> > You could change a property to trigger a redraw.
> 
> Does this only redraw the specific popup or the whole screen?
> Can `popup_setoptions(popup_getoptions())`  cause a redraw?

A :redraw command only redraws what needs to be redrawn.

I do not want to redraw when calling popup_getoptions() because a "get"
function should not have such a side effect.  It is also not cheap, and
we can't know if the caller uses the lastline property or not.

-- 
hundred-and-one symptoms of being an internet addict:
38. You wake up at 3 a.m. to go to the bathroom and stop and check your e-mail
    on the way back to bed.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Yggdroot** [comment]
Thanks.
