### ISSUE TITLE
<backspace> doesn't work in insert mode

### ISSUE THREAD

**Issue by unclechu** [vim/vim#519]
Release: 7.4.962 (3f12a2421bda43a4e48c822541b75f72ee11125a)

Backspace works really strange in insert mode. After I typed something and try to remove it by backspace it just moves cursor without deleting anything, but when I go to normal mode after that it removes it.

And when I go to normal mode from insert mode and go to insert mode again I can't remove anything by backspace, I can type more text and remove it but only last typed text, I still can't remove text that I had before going to insert mode.

**Comment by chrisbra** [comment]
Can you check what is your tabstop setting and just in case the compatible and cpo setting. Please show the output of:

```
:verbose set cp? cpo? bs?
```

**Comment by unclechu** [comment]
@chrisbra 
Command I use to start (I redefine HOME for use default vim configs):

```
env HOME=/dev/null vim
```

```
:verbose set cp? cpo? bs?
compatible
cpoptions=aAbBcCdDeEfFgHiIjJkKlLmMnoOpPqrRsStuvwWxXyZ$!%*-+<>;
backspace=
```

```
ts?=8
sts?=0
sw?=8
et?=noexpandtab
```

**Comment by chrisbra** [comment]
Okay, you are starting vim in compatible mode. Use the -N argument to start it in nocompatible mode. You likely want to set your bs setting to 2. Please ask further user questions at the vim-use mailinglist. Closing as invalid.

**Comment by unclechu** [comment]
@chrisbra actually I tried this config at first: https://github.com/unclechu/vimrc2/blob/master/.vimrc where I have `nocompatible` flag and I have this bug in this mode too.

In v7.4.827 (from Fedora 22 repos) I have no this bug.

It looks like main reason of this it's that I have empty `bs` option. I built `v7.4.827` from git and I don't have anything in `bs` option, but I always have something in `bs` from vim-builds from many distros, only if I build it from sources it's empty.

Anyway it definitely looked like bug for me, and I couldn't understand that I need to ask about it in mailinglist.

**Comment by chrisbra** [comment]
distros usually source some global vimrc file. You can find out with the :scriptnames command. Read the help at `:h 'bs'` about default value of backspace option. If something is unclear about compatible and non-compatible mode, ask vim-use ml. This really does not look like a bug and note, this is wrong forum to ask user questions in the issue tracker.

**Comment by vim-ml** [comment]
On Mon, Dec 7, 2015 at 10:53 AM, Viacheslav Lotsmanov
vim-dev-github@256bit.org wrote:

> @chrisbra actually I tried this config at first:
> https://github.com/unclechu/vimrc2/blob/master/.vimrc where I have
> nocompatible flag and I have this bug in this mode too.
> 
> In v7.4.827 (from Fedora 22 repos) I have no this bug.
> 
> It looks like main reason of this it's that I have empty bs option. I built
> v7.4.827 from git and I don't have anything in bs option, but I always have
> something in bs from vim-builds from many distros, only if I build it from
> sources it's empty.
> 
> Anyway it definitely looked like bug for me, and I couldn't understand that
> I need to ask about it in mailinglist.

"Tain't a bug, it's a feature". In this case a feature which
ultimately goes back to Bram's (IMHO commendable) attention to
backward compatibility, since the default is vi-compatible.

I recommend sourcing the vimrc_example.vim at startup, for instance by having

```
    runtime vimrc_example.vim
```

somewhere near (but not necessarily exactly at) the top of one's
vimrc. This takes care of setting many "more fashionable" settings
than what used to be in fashion in vi's heyday, and in particular it
sets 'backspace' to "indent,eol,start" which suits me perfectly. My
guess is that the same 'backspace' setting would suit you too.

Best regards,

## Tony.

«I have a problem with my editor.
— Which editor is it?
— The one which came with the computer.
— Well, which version?
— Version six (VI).
— You should upgrade to version six thousand (VIM).»
