### ISSUE TITLE
Question: Can the color of textprop override the color of matchadd() ?

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5190]
Can the color of textprop override the color of matchadd() ?

**Comment by brammool** [comment]
> Can the color of textprop override the color of matchadd() ?

No, a match will override a textprop.  But we can combine them,
like syntax highlighting combines with a match.

Now that the attribute computations have been refactored I see we can
make them more consistent.  Textprop and syntax highlighting should be
handled equally.

-- 
hundred-and-one symptoms of being an internet addict:
52. You ask a plumber how much it would cost to replace the chair in front of
    your computer with a toilet.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
@brammool I believe this change has changed the documented behaviour of `prop_type_add()`. `:help prop_type_add()` states the following:

```
		   combine	when TRUE combine the highlight with any
				syntax highlight; when omitted or FALSE syntax
				highlight will not be used
```

However text properties with no `combine` property now behave as if `combine` was set to FALSE. Previously, the default value was TRUE (as the documentation suggests).

**Comment by brammool** [comment]
> @brammool I believe this change has changed the documented behaviour of `prop_type_add()`. `:help prop_type_add()` states the following:
> 
> ```
> 		   combine	when TRUE combine the highlight with any
> 				syntax highlight; when omitted or FALSE syntax
> 				highlight will not be used
> ```
> 
> However text properties with no `combine` property now behave as if
> `combine` was set to FALSE. Previously, the default value was TRUE (as
> the documentation suggests).

Yes, it turned out for a while the 'combine' property had no effect and
the text property would always be combined with the syntax.  Unless some
other highlighting was present, thus it was rather inconsistent.

I think that combining by default works best, thus I made it that way.
I'll update the documenation.


-- 
Time is money.  Especially if you make clocks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
What I mean is that the default is now _not_ to combine.

Before this commit, these lines were equivalent:

```vim
call prop_type_add('PropType', #{highlight: 'Normal'})
call prop_type_add('PropType', #{highlight: 'Normal', combine: 1})
```

However now these lines are equivalent:

```vim
call prop_type_add('PropType', #{highlight: 'Normal'})
call prop_type_add('PropType', #{highlight: 'Normal', combine: 0})
```

**Comment by brammool** [comment]
Yes, you are right.  Let's fix that.
