### ISSUE TITLE
Meta sends escape is now broken

### ISSUE THREAD

**Issue by tom-marshall** [vim/vim#5200]
In previous versions of vim, you could set xterm options for "meta sends escape" and you were then able to hold down alt and a key and it was the equivalent of hitting escape and pressing the key. For example, I am in insert mode and I hit alt-shift-o and it will open the line above the line I'm typing, taking me out of insert mode. For some reason, that no longer works. Holding down alt and hitting a key gives you different accented letters.

Here is a link to an article on vim.org which covers the alt-key option:
https://vim.fandom.com/wiki/Avoid_the_escape_key

**Comment by brammool** [comment]
> In previous versions of vim, you could set xterm options for "meta
> sends escape" and you were then able to hold down alt and a key and it
> was the equivalent of hitting escape and pressing the key. For
> example, I am in insert mode and I hit alt-shift-o and it will open
> the line above the line I'm typing, taking me out of insert mode. For
> some reason, that no longer works. Holding down alt and hitting a key
> gives you different accented letters. Please fix this as it's driving
> me absolutely insane.
> 
> Here is a link to an article on vim.org which covers the alt-key option:
> https://vim.fandom.com/wiki/Avoid_the_escape_key

Vim now uses modifyOtherKeys by default, which makes it possible to map
keys with arbitrary modifiers.  This overrules the "meta sends escape"
mode.  You can disable modifyOtherKeys with:
      let &t_TI = ""
      let &t_TE = ""

-- 
hundred-and-one symptoms of being an internet addict:
46. Your wife makes a new rule: "The computer cannot come to bed."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tom-marshall** [comment]
I had run across those 2 commands while doing a web search, so I tried entering them from within vim, but it didn't work. I've added them to my .vimrc and it does the trick. Thank you, Bram!

**Comment by antofthy** [comment]
Thank you bram for the temporary fix...

The Problem...

After upgrading to Vim-8.2 the xterm modifyOtherKeys change has caused problems for me. I use "autocmd" to read in a binary encrypted file, which is then decrypted using a password read directly from the users TTY. 

If I type non-shifted letters... the password for decryption is fine.  But if I say use 'A' That is a capital-A,  the password being entered instead of getting a 'A' gets '\e[27;2;65~'  which is the ANSI code for a Shifted A.   As you can imagine the command fails to decrypt the file being edited, if the password had any shifted characters in it!

If I use a :%!command  to do the decryption there is no problem...  The input is read right, so VIM is disabling it for that.   It only becomes a problem when I do this from a "autocmd"

I was temporarily disabling this by sending a the key sequence  '\e[>4n'  to the terminal, before trying to read the password.  Of course this only works if I have wrapper I can program around the de/encrypt command that I am using, and requires a password to be read from TTY, in an "autocmd".

**Comment by antofthy** [comment]
From a reply by @brammool  in https://github.com/vim/vim/issues/5612#issuecomment-584747235

The following can be added to the autocmd's
```vim
call modify_other_keys(v:false) " disable modifyOtherKeys
call modify_other_keys(v:true)   " enable modifyOtherKeys
```
Which I will add to my edit encrypted files vim code...
http://www.ict.griffith.edu.au/anthony/software/#encrypt.vim
