### ISSUE TITLE
gM works differently for 'wrap' and 'nowrap' if 'showbreak' is set

### ISSUE THREAD

**Issue by lkintact** [vim/vim#5219]
1. Run `gvim.exe --clean`
2. Put this text into the buffer with the `"*P` command:
`0123456789 A1 0123456789 A2 0123456789 A3 0123456789 A4 0123456789 A5 0123456789 A6 0123456789 A7 0123456789 A8 0123456789 A9 0123456789 B0 0123456789 B1 0123456789 B2 0123456789 B3 0123456789 B4 0123456789 B5 0123456789 B6 0123456789 B7 0123456789 B8 0123456789 B9`
3. Execute `:set showbreak=>`
4. Hit <kbd>9</kbd><kbd>0</kbd><kbd>g</kbd><kbd>M</kbd>. The cursor gets positioned at the "7" in "...89 B7..."
5. Execute `:set nowrap`
6. Hit <kbd>9</kbd><kbd>0</kbd><kbd>g</kbd><kbd>M</kbd> again. The cursor gets positioned at the "0" in "...B7 01...".

Gvim: https://github.com/vim/vim-win32-installer/releases/download/v8.1.2300/gvim_8.1.2300_x86.zip,
Windows 10 Home 1803.

**Comment by chrisbra** [comment]
I don't think this is an error and I believe this is mostly because the `virtcol()` changes. See how the ruler changes when going from the last character in the first screen line (`0g$`) moving over to the first column in the second screen line (`l`). This is even more apparent when using showbreak with more characters and/or `breakindent` is set.
I'll leave that as open and let Bram decide, whether this is something to fix or can be closed as works correctly.

**Comment by brammool** [comment]
Well, if Christian thinks it's OK it probably is.  gM wasn't meant for very exact positioning anyway, more to quickly go to around where you want to go.
