### ISSUE TITLE
Mismatch between emailed patch 8.1.2302 and GH version

### ISSUE THREAD

**Issue by chdiza** [vim/vim#5228]
The mailing list post about 8.1.2302 contains a diff for one of the runtime files.  The github patch contains nothing about a runtime file.

Is this an accident?

**Comment by brammool** [comment]
> The mailing list post about 8.1.2302 contains a diff for one of the
> runtime files.  The github patch contains nothing about a runtime
> file.
> 
> Is this an accident?

Two of the three changes were already in the repository.
The third one went missing because of a merge failure.
Will get fixed with the next runtime file update.

-- 
You are only young once, but you can stay immature indefinitely.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
