### ISSUE TITLE
Creation of invisible terminating newline on write

### ISSUE THREAD

**Issue by Fmstrat** [vim/vim#5318]
**Describe the bug**
When opening a file with no terminating newline and then saving, `vim` automatically creates a terminating newline as default behavior. This also means that by default, `vim` cannot create a file without newlines.

**To Reproduce**
``` bash
fmstrat@ubuntuDesktop:~$ echo -n "abc" > a
fmstrat@ubuntuDesktop:~$ cat a
abcfmstrat@ubuntuDesktop:~$ 
fmstrat@ubuntuDesktop:~$ vim a
# Just do a `:wq`
fmstrat@ubuntuDesktop:~$ cat a
abc
fmstrat@ubuntuDesktop:~$
```
This newline is not viewable (by default) in `vim`.

**Expected behavior**
By default, terminating newlines should not be included. If they are, then `vim` should replicate the behavior of many other editors and allow the cursor to access the `0` character of the next line, identifying to the user that a newline exists without the need for displaying encoded newlines or paragraph marks.

**Screenshots**
![vim](https://user-images.githubusercontent.com/971474/70236305-b161c600-1732-11ea-8bde-97bd0e998fd1.gif)

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234]: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41) Included patches: 1-1453
 - OS: Ubuntu 18.04
 - Terminal: GNOME Terminal

**Additional context**
This is important to system administrators when it concerns elements such as storing passwords in Docker or K8 secrets. As an example, we ran into a headache tracking down invalid logins from a service when in fact it was just the hidden newline in the password field when the secret was created with `vim`.

**Comment by k-takata** [comment]
See `:help 'fixeol'`.

**Comment by brammool** [comment]
This is working as intended.  Text files should always end in a newline.

**Comment by Fmstrat** [comment]
@k-takata Thank you, that will be useful on servers where we edit secrets.

@brammool Thanks for responding. While I understand you want things to work this way, what about adding the ability to access the 0 character on the next line like most editors do? That way a user knows the newline is there.

**Comment by chrisbra** [comment]
@Fmstrat note, this is traditional Unix behaviour that text files always need to end with a newline. That's why it is sometimes called line termination character, in contrast, Windows tends to call it line separator, because it separates lines (and can therefore be absent from the last line).

There are pros and cons to both behaviours and it has been discussed to no end all over the place (search for line termination or line separator in the vim_use mailinglist). However, the most convincing argument for the unix way of handling it, was that without the line termination, it may cause unexpected behaviour (try e.g. `cat file1.txt file2.txt`, where file1.txt does not contain a final newline.)

Note also, that for the usage of files as password stores, one usually uses the `chomp()` (perl) function, to get rid of the final new line and it should not be feeded to a password prompt as is. Similar functions should exists for other languages (php uses rtrim as does mysql for this matter).
