### ISSUE TITLE
Make mouse= the default

### ISSUE THREAD

**Issue by kj7rrv** [vim/vim#5348]
Mouse support is very confusing. Users expect right-clicking in a terminal to bring up a context menu, with absolutely zero exceptions. I always turn mouse off. I use vim _because_ it does not support the mouse. I'm sure many people use it for that reason.

A command-line program hijacking the mouse from the terminal is almost as bad as a GUI program not supporting the mouse. The features in the terminal emulator context menu are crucial, while mouse support is a command-line editor are not.

People who want mouse support in vim use gvim, right?

**Comment by nickspoons** [comment]
Why open a new issue? You've just said the same thing in [another issue](https://github.com/vim/vim/issues/2841#issuecomment-564719560) where this has been thoroughly discussed.

You also make a lot of claims about what "everyone" does and wants. Vim is used in an enormous variety of situations, not just your use-case.

There are also many terminal applications which can and do use the mouse - Vim is not magically adding mouse support to the terminal, it is using standard terminal functionality.

**Comment by vim-ml** [comment]
On 2019-12-11, scoopgracie wrote:
> Mouse support is very confusing. Users expect right-clicking in a terminal to
> bring up a context menu, with absolutely zero exceptions.

Right-clicking in an xterm does not bring up a context menu, nor
does it in mintty.

>                                                           I always turn mouse
> off. I use vim because it does not support the mouse. I'm sure many people use
> it for that reason.
> 
> A command-line program hijacking the mouse from the terminal is almost as bad
> as a GUI program not supporting the mouse. The features in the terminal
> emulator context menu are crucial, while mouse support is a command-line editor
> are not.
> 
> People who want mouse support in vim use gvim, right?

Wrong.  I hardly ever use gvim because:  1) I'm always working at
the command line; and 2) :sh in gvim does not give me a
full-featured terminal.  I use the mouse in vim in an xterm for
dragging window borders and for scrolling, and occasionally for
copying and pasting to and from external windows, but I usually use
y and p for that.

Regards,
Gary

**Comment by chrisbra** [comment]
this has been discussed to death, as you know, since you left your opinion at the other issue. If you do not want mouse support, you can configure vim to not use the mouse. Changing the default is going to upset the other half of the users that are happy with the current settings so it is not going to happen.

**Comment by tonymec** [comment]
> > On 2019-12-11, scoopgracie wrote: Mouse support is very confusing. Users expect right-clicking in a terminal to bring up a context menu, with absolutely zero exceptions.

> Right-clicking in an xterm does not bring up a context menu, nor does it in mintty.

Indeed. Right-clicking in xterm selects a range of lines. AFAICT the only context menu in xterm is the window manager's, obtained by right-clicking the titlebar.

But right-clicking in Vim or gvim gives me a context menu in all cases. In gvim it looks like a GTK2 popup, in vim it is a text popup, but the contents are the same in both cases, and relevant to Vim; and they aren't the same in Normal, Visual, and Insert modes. How do I get that? Simple (it's documented): `set mousemodel=popup`

> > I always turn mouse off. I use vim because it does not support the mouse. I'm sure many people use it for that reason. A command-line program hijacking the mouse from the terminal is almost as bad as a GUI program not supporting the mouse. The features in the terminal emulator context menu are crucial, while mouse support is a command-line editor are not. People who want mouse support in vim use gvim, right?

> Wrong. I hardly ever use gvim because: 1) I'm always working at the command line; and 2) :sh in gvim does not give me a full-featured terminal. I use the mouse in vim in an xterm for dragging window borders and for scrolling, and occasionally for copying and pasting to and from external windows, but I usually use y and p for that.
> Regards, Gary

I use both gvim and vim. When I'm in a shell command-line context, I may temporarily start Vim in that same terminal, more or less like Gary does. In addition I have a gvim runing more or less permanently, which I use when an edit would take me a long time, or to browse the Vim help, or for little tasks in a GUI context, for instance to get hard-to-type (by non-Vim methods) UTF-8 strings into the clipboard for pasting into a browser textarea (thanks to either a keymap or to the `|i_CTRL-V_digit|` function of `|c_CTRL-V|`).

So I use both vim and gvim quite a lot, and I find it best when they look and behave the same. I have found out how to get indistinguishably (to my eye) identical colors in both a 1677216-color gvim and a 216-color vim-in-terminal so they look the same to me. Alas, they don't act 100% the same because the terminal hijacks some keypresses (e.g. Shift-F11) which I can reliably map in gvim. About the mouse, if it didn't work in Console Vim it might drive me crazy (assuming I'm not already). At least left-cllicking moves the Vim cursor and right-clicking gives a Vim context menu in almost identical fashion in both gvim and vim.
