### ISSUE TITLE
'%{}' expression sometimes does not work for the titlestring and iconstring options

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#5383]
I have been looking for a way to know that the window is scrolled since vim does not have something like a WinScrolled event. I found that the `statusline` option can be used to check it
with a `'%{}'` expression. The `titlestring` and `iconstring` options have the same syntax as well.

I tried to show the first and last visible line numbers on those 3 options as below.

```
set title titlestring=%{EchoLnums('t')}
set icon iconstring=%{EchoLnums('i')}
set statusline=%{EchoLnums('s')}
function! EchoLnums(opt)
    echon join([a:opt, line('w0'), line('.'), line('w$'), '='], '/')
endfunction
```

Whenever scrolling the window using CTRL-Y/-U/-B and CTRL-E/-D/-F, or moving the cursor using something like j and k, the function is called for all 3 options and line numbers are successively echoed.

But, on gvim, if using a scroll bar or mouse scroll wheel to scroll the window, the function is called for the `statusline` but not for the `titlestring` and `iconstring`. More interestingly, when I tried it on nvim, everything works fine!

Do you happen to know why the function is not called for the `titlestring` and `iconstring` on gvim, but works fine on nvim?

I am using vim 8.2 and nvim 4.3 on Windows 10.

**Comment by 3N4N** [comment]
Man. Vim people don't care about Windows at all. I reported and fixed a bug in neovim (it exists in vim too), but nobody even commented other than tagging it with `platform-windows` label.

**Comment by chrisbra** [comment]
that is not true, we are also fixing windows problems here, e.g. a3d1b29bd3648716

Perhaps nobody simply knew the answer, since gvim and nvim are different projects? 

But perhaps instead of complaining, if you open a proper issue report, we may be able to fix this here as well.

**Comment by 3N4N** [comment]
@chrisbra, I'm not complaining. I myself am a Linux user. Only using Windows the past couple months strictly because of my situation. And I understand how open-source projects work. But when I stumbled upon an issue two years old and with no comments, I had to share my observation that most people working on vim and nvim projects are themselves on Linux and so Windows stuff inevitably gets backlogged. 

Again, I'm not complaining, nor would there be a basis for complaining since this is an open-source project. Sorry if my comment was disrespectful. Cause I'm a huge vim fan. Saved me in time-constrained situations more than once.

**Comment by chrisbra** [comment]
the problem here seems to be minor, most likely we just need a call to refresh those settings on scrolling. 

Considering the amount of issues here, it may have simply fell through. Were are just a few people here. Maintaining such a popular project is a huge effort. That doesn't mean we are not interested in fixing bugs or even in Windows. It's just lack of time and resources.

**Comment by chrisbra** [comment]
@rickhowe I just tried it. For me, using gtk2 and gtk3 gui, the titlestring and iconstring variables are re-evaluated on vertical mouse scrolling (i did not test horizontal scrolling as I don't have a mouse for that).

However, I do see, that the titlestring and iconstring is not updated, when dragging the scrollbars with the mouse. For that, I believe we need the following patch:

```patch
 diff --git a/src/gui.c b/src/gui.c
index 13f1fe4fa..e36c26dd0 100644
--- a/src/gui.c
+++ b/src/gui.c
@@ -4412,6 +4412,8 @@ gui_update_scrollbars(
                                            val, size, max);
        }
     }
+    // Update the title
+    maketitle();
     prev_curwin = curwin;
     --hold_gui_events;
 }
```

Note: that the iconstring setting is not supported on a windows gui.

**Comment by chrisbra** [comment]
Note: this is not related to Windows in general, it also occurs on Linux. 

I have created #9328 for fixing this
