### ISSUE TITLE
Filetypes should not set format options

### ISSUE THREAD

**Issue by g0xA52A2A** [vim/vim#5406]
**Describe the bug**
Many filetypes set local values for the `formatoptions` setting. This setting is a user preference and I don't see why filetypes should dictate this.

**To Reproduce**
Number of filetypes which set `formatoptions`

```
$ grep -lE 'formatoptions(\-|\+)=' runtime/ftplugin/* | wc -l
126
```

Number of filetypes which do not.

```
$ grep -LE 'formatoptions(\-|\+)=' runtime/ftplugin/* | wc -l
97
```

**Expected behavior**
For the `formatoption` not to change based upon filetype.

**Environment (please complete the following information):**
 - Vim version: Any
 - OS: N/A
 - Terminal: N/A

**Additional context**
I'm aware that these files have maintainers but given how common the removal of `t` and the addition of `croql` from the `formatoptions` setting is I suspect this sort of thing is simply being copy/pasted.

```
grep -hE 'formatoptions(\-|\+)=' runtime/ftplugin/* | tr ' ' '\n' | sort | grep formatoptions | uniq -c | sort -rn | head -5
    110 formatoptions-=t
     87 formatoptions+=croql
      4 formatoptions-=tcroq
      4 formatoptions+=l
      3 formatoptions+=tcqln
```

**Comment by brammool** [comment]
> **Describe the bug**
> Many filetypes set local values for the `formatoptions` setting. This
> setting is a user preference and I don't see why filetypes should
> dictate this.

It is both a user preference and bound to the language.  Many filetypes
have mandatory or preferred ways of formatting.  E.g. in a Makefile a
Tab must be used before a command.  In Python Tabs should be expanded to
avoid trouble with indenting.

Often this is a matter of taste, it needs to be discussed per filetype,
there is no one solution that applies everywhere.

Also, you can override settings you don't like or prefer otherwise.

> **To Reproduce**
> Number of filetypes which set `formatoptions`
> 
> ```
> $ grep -lE 'formatoptions(\-|\+)=' runtime/ftplugin/* | wc -l
> 126
> ```
> 
> Number of filetypes which do not.
> 
> ```
> $ grep -LE 'formatoptions(\-|\+)=' runtime/ftplugin/* | wc -l
> 97
> ```
> 
> **Expected behavior**
> For the `formatoption` not to change based upon filetype.
> 
> **Environment (please complete the following information):**
>  - Vim version: Any
>  - OS: N/A
>  - Terminal: N/A
> 
> **Additional context**
> I'm aware that these files have maintainers but given how common the
> removal of `t` and the addition of `croql` from the `formatoptions`
> setting is I suspect this sort of thing is simply being copy/pasted.
> 
> ```
> grep -hE 'formatoptions(\-|\+)=' runtime/ftplugin/* | tr ' ' '\n' | sort | grep formatoptions | uniq -c | sort -rn | head -5
>     110 formatoptions-=t
>      87 formatoptions+=croql
>       4 formatoptions-=tcroq
>       4 formatoptions+=l
>       3 formatoptions+=tcqln
> ```

Please approach the individual maintainers.  They need to make any
change and send the updated file to me.

-- 
Q: How does a UNIX Guru pick up a girl?
A: look; grep; which; eval; nice; uname; talk; date;

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by g0xA52A2A** [comment]
Oh yes I full agree with things like hard tabs for Makefiles and correct spacing for Python. I was specifically focusing on the `formatoptions` setting which is purely preferential.

Understood that this is down to the maintainers of the individual filetypes, closing.
