### ISSUE TITLE
Test suite dumps a .viminfo file in $HOME

### ISSUE THREAD

**Issue by chdiza** [vim/vim#5414]
This is Vim 8.2.55, on macOS. 

I seem to recall that this was fixed once before, which would make this a regression.

Running the vim test suite writes a ~/.viminfo file even if none was there in the first place.  As far as I can tell, it doesn't write that file until at or very near the end of the suite.  Here is perhaps a clue as to the culprit:  the viminfo file that got dumped has a file mark: `'0  1  0  /myrepos/vim/src/testdir/messages`.

I assume that if there had been a .viminfo file there already, it would've had content added to it, which is also a bug.

**Comment by brammool** [comment]
> This is Vim 8.2.55, on macOS. 
> 
> I seem to recall that this was fixed once before, which would make this a regression.
> 
> Running the vim test suite writes a ~/.viminfo file even if none was there in the first place.  As far as I can tell, it doesn't write that file until at or very near the end of the suite.  Here is perhaps a clue as to the culprit:  the viminfo file that got dumped has a file mark: `'0  1  0  /myrepos/vim/src/testdir/messages`.
> 
> I assume that if there had been a .viminfo file there already, it would've had content added to it, which is also a bug.

I can reproduce it.  It is caused by the summarize.vim script that was
added a while ago.

-- 
Seen on the back of a biker's vest: If you can read this, my wife fell off.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
