### ISSUE TITLE
[Terminal] Vim built-in terminal change gnome-terminal cursor type to Block

### ISSUE THREAD

**Issue by tuberry** [vim/vim#5418]
**Describe the bug**
Vim built-in terminal change cursor type in vim and gnome-terminal to Block.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Change gnome-terminal cursor type to Underline or I-beam;
2. Launch vim and enter vim's terminal by `:term`;
3. Exit the terminal and you can see cursor in all mode changes to Block;
4. Exit vim and you can see cursor in gnome-terminal changes to Block too;

**Expected behavior**
Restore the cursor type correctly after quitting vim's terminal.

**Environment (please complete the following information):**
 - Vim version:  8.1.2268-2
 - OS: ArchLinux
 - Terminal: GNOME Terminal

**Comment by brammool** [comment]
> **Describe the bug**
> Vim built-in terminal change cursor type in vim and gnome-terminal to Block.
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Change gnome-terminal cursor type to Underline or I-beam;
> 2. Launch vim and enter vim's terminal by `:term`;
> 3. Exit the terminal and you can see cursor in all mode changes to Block;
> 4. Exit vim and you can see cursor in gnome-terminal changes to Block too;
> 
> **Expected behavior**
> Restore the cursor type correctly after quitting vim's terminal.
> 
> **Environment (please complete the following information):**
>  - Vim version:  8.1.2268-2
>  - OS: ArchLinux
>  - Terminal: GNOME Terminal

Vim attempts to restore the cursor shape and color, but only some
terminals support getting the current state, making it difficult to
restore it.

Check the values for the termcap options:
	set t_SI t_SR t_EI

Try using xterm instead of Gnome, it should work then.

-- 
Proofread carefully to see if you any words out.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tuberry** [comment]
I've tried this [method](https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes) for the Gnome-Terminal (version ≥3.16)  which stored cursor type to `q"` and restored that when leaving. It works but causes annoying flicker in any VimEnter/VimInsertLeave events. But it's not a big deal for me since I use Block in terminal too. Please close this if It's not a bug of vim. Thanks.

**Comment by brammool** [comment]
If someone knows how to save & restore the cursor shape for Gnome-terminal, let me know.
Otherwise I don't see a reason to keep this issue open.

**Comment by chrisbra** [comment]
> If someone knows how to save & restore the cursor shape for Gnome-terminal, let me know.
Otherwise I don't see a reason to keep this issue open.

gnome-terminal is VTE based, right? So using the following should make it work:

https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-cursor-shape
https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-get-cursor-shape

that seems to be available since VTE 0.20, however I find it hard to find which gnome release includes this VTE version.
