### ISSUE TITLE
Exiting a right below terminal makes vim crash.

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#5424]
Environment:

- Debian 10 - x86
- Vim 8.2.12

Reproduce:

1. start vim and open the help in two splits, after that, open the terminal:

```bash
vim -c "h index |wincmd o|rightbelow vs|rightbelow term" -u NONE
```

It should look like this:

![exit](https://user-images.githubusercontent.com/3035071/71631630-9e181c80-2c44-11ea-9bf0-8763214d7867.png)

2. type "exit" in the terminal window and press enter

I expect this "exit" command will just close the terminal window, but the whole vim quit too.

**Comment by skywind3000** [comment]
I simplify the process to:

```bash
vim -c "h index |wincmd o|vs|term" -u NONE
```

than input "exit" and press ENTER will make vim quit.

**Comment by brammool** [comment]
If you do the same with a normal with then Vim will also exit: use ":new" instead of ":term".
Closing the last window, not counting help windows, does make Vim exit.
That is intentional.

**Comment by skywind3000** [comment]
Not exactly, If so, vim should exit after `wincmd o`, but it didn't exit.

And I try what you said, to replace ":term" with ":new":

```bash
vim -c "h index |wincmd o|vs|new|close" -u NONE
```

I found vim didn't quit any more after the ":new" window closed.

It's different from what you said.

Need reopen this issue ??

**Comment by tonymec** [comment]
> Not exactly, If so, vim should exit after `wincmd o`, but it didn't exit.
> 
> And I try what you said, to replace ":term" with ":new":
> 
> ```shell
> vim -c "h index |wincmd o|vs|new|close" -u NONE
> ```
> 
> I found vim didn't quit any more after the ":new" window closed.
> 
> It's different from what you said.
> 
> Need reopen this issue ??

`:close` fails on the last window, it intentionally won't close Vim. Close the current window with `:q` (`:quit`) or `:x` (`:exit`) instead. These close Vim if they are used in the last non-help window (barring the case when a modified window cannot be written).

Best regards,
Tony.

**Comment by skywind3000** [comment]
sorry my misunderstanding, but what can I do to make it behave like “:close” when I exit a terminal?

**Comment by brammool** [comment]
> Not exactly, If so, vim should exit after `wincmd o`, but it didn't exit.

You are not closing the last non-help window directly, you are making
the current window the only one.  Doesn't make sense to close it then.

> And I try what you said, to replace ":term" with ":new":
> 
> ```bash
> vim -c "h index |wincmd o|vs|new|close" -u NONE
> ```
> 
> I found vim didn't quit any more after the ":new" window closed.
> 
> It's different from what you said.

":close" is different from ":quit".  Partly because of this behavior, so
you can chose what you want to happe.  When quitting a shell there is no
way to chose in what way to close the window.  I think the current
behavior is the best choice.

-- 
Vi beats Emacs to death, and then again!
			http://linuxtoday.com/stories/5764.html

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by skywind3000** [comment]
Fine, I am using "term ++noclose xxx" to prevent this.
