### ISSUE TITLE
syntax: "\a" does not include characters like "ä" and that breaks syntax highlighting

### ISSUE THREAD

**Issue by mrosic** [vim/vim#545]
Steps to reproduce:
Set your locale to de_AT.UTF-8 on Debian 8 or RHEL7.
Open /var/log/messages or /var/log/syslog on Debian 8 or do "journalctl | vim -" on RHEL 7.
Type ":set syntax=messages"

What you will notice is that syntax highlighting does work for the log entries in december but doesn't work for the log entries in January.
Reason: January on Austrian is "Jänner", the abbreviated form is "Jän". The "ä" breaks the syntax highlighting because vim doesn't consider "ä" as an alphabetic character.

Details:
In
/usr/share/vim/vim74/syntax/messages.vim
we have the following line:
syn match   messagesDate        contained display '\a\a\a [ 0-9]\d *'

According to 
http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\s
"\a" is an alphabetic character [A-Za-z]. Unfortunately that doesn't seem to include "ä" which makes Austrian sysadmins sad because they don't have syntax highlighting for Log files in January due to that error. Note that for example echo -e "ä\na" | grep [a-z] will match both lines because unlike vim, grep considers "ä" to be a part of [a-z] which is exactly how it should be.

Temporary workaround:
In /usr/share/vim/vim74/syntax/messages.vim 
change
syn match   messagesDate        contained display '\a\a\a [ 0-9]\d *'
to
syn match   messagesDate        contained display '\a[a-zä]\a [ 0-9]\d *'

**Comment by brammool** [comment]
mrosic wrote:

> Steps to reproduce:
> Set your locale to de_ATUTF-8 on Debian 8 or RHEL7
> Open /var/log/messages or /var/log/syslog on Debian 8 or do "journalctl | vim -" on RHEL 7
> Type ":set syntax=messages"
> 
> What you will notice is that syntax highlighting does work for the log entries in december but doesn't work for the log entries in January
> Reason: January on Austrian is "Jänner", the abbreviated form is "Jän" The "ä" breaks the syntax highlighting because vim doesn't consider "ä" as an alphabetic character
> 
> Details:
> In
> /usr/share/vim/vim74/syntax/messagesvim
> we have the following line:
> syn match   messagesDate        contained display '\a\a\a [ 0-9]\d *'
> 
> According to 
> http://vimdocsourceforgenet/htmldoc/patternhtml#/\s
> "\a" is an alphabetic character [A-Za-z] Unfortunately that doesn't seem to include "ä" which makes Austrian sysadmins sad because they don't have syntax highlighting for Log files in January due to that error Note that for example echo -e "ä\na" | grep [a-z] will match both lines because unlike vim, grep considers "ä" to be a part of [a-z] which is exactly how it should be
> 
> Temporary workaround:
> In /usr/share/vim/vim74/syntax/messagesvim 
> change
> syn match   messagesDate        contained display '\a\a\a [ 0-9]\d *'
> to
> syn match   messagesDate        contained display '\a[a-zä]\a [ 0-9]\d *'

This should probably use [[:lower:][:upper:]] instead of \a.

Strangely [:alpha:] only works on non-multibyte characters.

## 

An indication you must be a manager:
You believe you never have any problems in your life, just
"issues" and "improvement opportunities".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Have you contacted the maintainer of the file?

**Comment by mrosic** [comment]
No, because I considered this to be a bug in vim.
From my point of view [a-zA-Z] should include characters like ä. If you tell me that this is not going to get fixed in vim or that you do not consider this to be a bug then I will contact the maintainer of messages.vim.

**Comment by vim-ml** [comment]
2016-01-03 16:10 GMT+03:00 mrosic vim-dev-github@256bit.org:

> No, because I considered this to be a bug in vim.
> From my point of view [a-zA-Z] should include characters like ä. If you
> tell me that this is not going to get fixed in vim or that you do not
> consider this to be a bug then I will contact the maintainer of
> messages.vim.

​Unlike some other languages in VimL range always meant range in current
encoding’s codepoints. So in UTF-8 [a-zA-Z] is literally​ “from U+0061 to
U+007a (inclusive) or from U+0041 to U+005A (inclusive)” and that does not
include characters like ä: vim regexes never had normal unicode support,
and locale support is rather limited and only considers locale
encoding (actually,
&encoding and not locale encoding, but unless you specify otherwise in
documentation one is derived from the other) AFAIK. I do not think this is
going to be ever fixed because making character ranges locale-dependent
changes their semantics significantly and where previously plugin author
may expect [a-zA-Z] to match all latin ASCII letters with such change this
is no longer the case. E.g. in Perl correct representation of [a-zA-Z] in
UTF-8 regex mode is something like `(?:(?=\pL)\p{Block=Basic_Latin})`: not
something one wants to write constantly.

**Comment by vim-ml** [comment]
On Sun, Jan 3, 2016 at 3:53 PM, Nikolay Aleksandrovich Pavlov
zyx.vim@gmail.com wrote:

> Unlike some other languages in VimL range always meant range in current encoding’s codepoints. So in UTF-8 [a-zA-Z] is literally “from U+0061 to U+007a (inclusive) or from U+0041 to U+005A (inclusive)” and that does not include characters like ä: vim regexes never had normal unicode support, and locale support is rather limited and only considers locale encoding (actually, &encoding and not locale encoding, but unless you specify otherwise in documentation one is derived from the other) AFAIK. I do not think this is going to be ever fixed because making character ranges locale-dependent changes their semantics significantly and where previously plugin author may expect [a-zA-Z] to match all latin ASCII letters with such change this is no longer the case. E.g. in Perl correct representation of [a-zA-Z] in UTF-8 regex mode is something like `(?:(?=\pL)\p{Block=Basic_Latin})`: not something one wants to write constantly.

Indeed. In Vim, when 'encoding' is UTF-8, or indeed most or all of the
ISO-8859 encodings (and many others), [a-zA-Z] is just a short way of
writing [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ] and
nothing else.

The one possible exception is when running on a machine with EBCDIC
encoding (such as an IBM mainframe running not Linux but zOS as its
operating system), and keeping that encoding as 'encoding' within Vim,
which IIUC is definitely not recommended. In that case, IIUC, to keep
the 52-letter alphabet shown above one whould have to abbreviate it no
more than [a-ij-rs-zA-IJ-RS-Z] because the EBCDIC alphabet is
discontinuous: there are punctuation marks between i and j, and
between r and s, and the same in uppercase. But maube I don't UC and
Vim interprets [a-zA-Z] the usual way there in order to avoid
surprising "tourists" from the papertape universe, even when working
in the punched-card universe. ;-)

Best regards,
Tony.

**Comment by vim-ml** [comment]
2016-01-03 18:38 GMT+03:00 Tony Mechelynck antoine.mechelynck@gmail.com:

> On Sun, Jan 3, 2016 at 3:53 PM, Nikolay Aleksandrovich Pavlov
> zyx.vim@gmail.com wrote:
> 
> > Unlike some other languages in VimL range always meant range in current
> > encoding’s codepoints. So in UTF-8 [a-zA-Z] is literally “from U+0061 to
> > U+007a (inclusive) or from U+0041 to U+005A (inclusive)” and that does not
> > include characters like ä: vim regexes never had normal unicode support,
> > and locale support is rather limited and only considers locale encoding
> > (actually, &encoding and not locale encoding, but unless you specify
> > otherwise in documentation one is derived from the other) AFAIK. I do not
> > think this is going to be ever fixed because making character ranges
> > locale-dependent changes their semantics significantly and where previously
> > plugin author may expect [a-zA-Z] to match all latin ASCII letters with
> > such change this is no longer the case. E.g. in Perl correct representation
> > of [a-zA-Z] in UTF-8 regex mode is something like
> > `(?:(?=\pL)\p{Block=Basic_Latin})`: not something one wants to write
> > constantly.
> 
> Indeed. In Vim, when 'encoding' is UTF-8, or indeed most or all of the
> ISO-8859 encodings (and many others), [a-zA-Z] is just a short way of
> writing [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ] and
> nothing else.
> 
> The one possible exception is when running on a machine with EBCDIC
> encoding (such as an IBM mainframe running not Linux but zOS as its
> operating system), and keeping that encoding as 'encoding' within Vim,

You can’t set &encoding to anything that is not ASCII-compatible, unless
you compiled Vim with -DEBCDIC. -DEBCDIC is AFAIK z/OS-specific and I do
not remember any complaints from z/OS users recently: if you [search](https://groups.google.com/forum/#!searchin/vim_dev/z$2FOS%7Csort:date)
for z/OS in vim-dev then the last relevant (i.e. where z/OS string is not
part of the “context” in a patch) [topic](https://groups.google.com/forum/#!searchin/vim_dev/z$2FOS|sort:date/vim_dev/cYvmgP0v9ag/TT_XSWL7yHUJ) is patch 7.3.555 from
13.06.2012, more then three years old. It is very much unlikely that
nothing has ever broken again build since then.

> which IIUC is definitely not recommended. In that case, IIUC, to keep
> the 52-letter alphabet shown above one whould have to abbreviate it no
> more than [a-ij-rs-zA-IJ-RS-Z] because the EBCDIC alphabet is
> discontinuous: there are punctuation marks between i and j, and
> between r and s, and the same in uppercase. But maube I don't UC and
> Vim interprets [a-zA-Z] the usual way there in order to avoid
> surprising "tourists" from the papertape universe, even when working
> in the punched-card universe. ;-)
> 
> Best regards,
> Tony.
> 
> ## 
> 
> ## 
> 
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
> 
> ---
> 
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.

**Comment by mrosic** [comment]
I have contacted the maintainer of messages.vim two weeks ago but I did not receive a reply.

**Comment by brammool** [comment]
mrosic wrote:

> I have contacted the maintainer of messages.vim two weeks ago but I
> did not receive a reply.

Well, I can change the line:

syn match   messagesDate        contained display '[[:lower:][:upper]][[:lower:][:upper]][[:lower:][:upper]] [ 0-9]\d *'
                                \ nextgroup=messagesHour

## 

Everybody wants to go to heaven, but nobody wants to die.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mrosic** [comment]
One year later and I've stubled upon this issue again.
However, the error is fixed in this github repository, my distro is just using an old version. 

Thank you very much Mr. Molenaar for fixing this, I think this issue can be closed.
