### ISSUE TITLE
Folds are messed up when set foldmarker={,}

### ISSUE THREAD

**Issue by hiberabyss** [vim/vim#547]
Since the `level included` syntax in markers, when `set foldmarker={,}` , the following line 

```
static long days[13] = {30, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31} ;
```

will be incorrectly recognised as `foldlevel=30`, which will mess folds up.

Can an option provided to disable the marker level included ?

**Comment by chrisbra** [comment]
Well, simply use a different foldmarker is no option for you?

**Comment by hiberabyss** [comment]
I set the foldmarker for a large cpp file, since when `set fdm=syntax` is really slow. When use other foldmarker, it can't fold correctly.

**Comment by chrisbra** [comment]
On Mo, 04 Jan 2016, Hongbo Liu wrote:

> I set the foldmarker for a large cpp file, since when `set fdm=syntax`
> is really slow. When use other foldmarker, it can't fold correctly.

Okay, but what is the reason you are not using the default foldmarker 
setting? There is a reason, why the default is '{{{,}}}' and not '{,}'

,----[ :h fold-marker ]-
| The markers can be set with the 'foldmarker' option.  It is recommended 
| to keep this at the default value of "{{{,}}}", so that files can be 
| exchanged between Vim users.  Only change it when it is required for the 
| file (e.g., it contains markers from another folding editor, or the 
| default markers cause trouble for the language of the file).
`----

Best,

## Christian

Nicht alle die ins Gras beißen sind Vegetarier.

**Comment by hiberabyss** [comment]
I don't want to create the fold myself, I would like it behaviour like `set fdm=syntax` in cpp. Since the function is defined like `void function() { ... }` in the cpp file, if use `{{{,}}}`, the function can't be recognised as a fold.

**Comment by chrisbra** [comment]
Hi Hongbo!

On Mo, 04 Jan 2016, Hongbo Liu wrote:

> I don't want to create the fold myself, I would like it behaviour like
> `set fdm=syntax` in cpp. Since the function is defined like `void
> function() { ... }` in the cpp file, if use `{{{,}}}`, the function
> can't be recognised as a fold.

Well, this is then an unwanted side effect. Possible workaround:
would be to use a foldexpression or even easier add a space between the 
brace and the number.

I wouldn't consider this a bug.

Best,

## Christian

Du bekommst einen Computervirus genau dann, wenn Du denkst, Du hättest keinen.

**Comment by hiberabyss** [comment]
The vim document says that `foldexpression` is very slow. The cpp file is in our corporation's repository, it's inconvenient to modify the file.

**Comment by memeplex** [comment]
Why don't you try to implement the fold expr and then conclude it's indeed slow (or not)? In my experience, a simple foldexpr is pretty fast. Often, folding by syntax is slow for big files, but you can implement a foldexpr that takes advantage of specific syntax information. If you do it right, it will be way faster than full syntax folding. Otherwise, don't use syntax information at all, matching `{`, `}` seems pretty easy to achieve with basic vimscript without a woeful performance.

**Comment by chrisbra** [comment]
closing. If you really must use the `{,}` as foldmarker, you should add a whitespace to avoid that the `{30` is parsed as the foldlevel.
