### ISSUE TITLE
`set listchars`: Options for the first and last chars in wrapped lines

### ISSUE THREAD

**Issue by while0pass** [vim/vim#5492]
Differentiating between wrapped and unwrapped lines gets harder, when `set nonu wrap`.

It would be great if there were additional options in `set listchars` for the first and last characters of the wrapped parts of a line. They could be `wrap_precedes` and `wrap_extends`. For instance:

```
set nonu
set wrap
set listchars=wrap_precedes:↪
" use \u21aa unicode char before the wrapped parts of a line
``` 
And this could cause a file to look like this:
```
/* ... */
void diff_invalidate(buf_T *buf);
void diff_mark_adjust(linenr_T line1, linenr_T line2, long amo
↪unt, long amount_after);
void diff_redraw(int dofold);
/* ... */
```

**Comment by while0pass** [comment]
#3820

**Comment by vim-ml** [comment]
On 2020-01-17, while0pass wrote:
> Differentiating between wrapped and unwrapped lines gets harder, when set nonu
> wrap.
> 
> It would be great if there were additional options in set listchars for the
> first and last characters of the wrapped parts of a line.

There is already a solution for the first part:

    :help 'showbreak'

Regards,
Gary

**Comment by tonymec** [comment]
As Gary said, there is the `'showbreak'` option, but even while leaving it at its empty default, I have no problem telling which lines are wrapped (and I see here in one of my files a monster line of 2274 single-width Unicode characters, or 3142 bytes in UTF-8, spreading itself on 14 screen lines). Here's how:

If you set the `eol:` item in `'listchars'`, then each line (wrapped or not) begins either at the top of the file or after one end-of-line marker and ends at the next end-of-line marker: IOW, if a screen line goes right up to the right margin without an end-of-line marker, then the same file line continues on the next screen line. I never have trouble seeing which lines are wrapped, especially since (with my `'guifont'` setting in a maximized `gvim`) most "unwrapped" lines end long before the right margin, while wrapped lines occupy several consecutive screen lines going all the way from left margin to right margin.

You could `:set lcs+=eol:$` to use the default setting; I use `eol:¶` to get a distinctive character which is normally never present in the files I write, and yet immediately recognizable. FWIW, my full setting is
```vim
if exists('+list')
  set list
  if exists('+listchars')
    set lcs=eol:¶,tab:\|_,extends:>,precedes:<,conceal:*,nbsp:·
  endif
endif
```

In addition, if you `:set cursorline` the *current* **file** line (no matter how many **screen** lines it occupies due to wrapping) will be highlighted in `CursorLine` highlighting (my custom colorscheme sets that to `guibg=#F4F4F4` which is a grey tone just a tiny wee bit darker than white, and suits me; but of course you can use any value which suits you, or use the default which is `guibg=Grey90`, a little too dark for my taste).

Best regards,
Tony.

**Comment by while0pass** [comment]
@vim-ml @tonymec thank you. `showbreak` seems a perfect match for the need.
