### ISSUE TITLE
empty search repeats the previous search, yet drops the leading empty space

### ISSUE THREAD

**Issue by MontrealSergiy** [vim/vim#5550]
**Describe the bug**

empty search repeats the previous search, yet drops the leading empty space

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim` 
2. Enter text 
 
``Test text

   pattern

   notpattern

   pattern
``
3. Go to the begining of the text

4.Search for the space followed by text 'pattern' by typing Esc, colon, / pattern enter

5. Repeat search by sending empty search Esc, colon, slash enter

6. Observe that cursor goes into the middle of  'notpattern' word

Expected behavior: repeat the search exactly, that is go to the second word pattern

**Expected behavior**

**Environment (please complete the following information):**
 - Vim version 8
 - OS: Ubuntu 18.04

**Comment by vim-ml** [comment]
On 2020-01-28, MontrealSergiy wrote:
> Describe the bug
> A clear and concise description of what the bug is.
> 
> empty search repeats the previous search, yet drops the leading empty space
> 
> To Reproduce
> Detailed steps to reproduce the behavior:
> 
>  1. Run vim
>  2. Enter text
> 
> ``Test text
> 
> pattern
> 
> notpattern
> 
> pattern
> ``
> 3. Go to the begining of the text
> 
> 4.Search for the space followed by text 'pattern' by typing Esc, colon, /
> pattern enter
> 
>  5. Repeat search by sending empty search Esc, colon, slash enter
> 
>  6. Observe that cursor goes into the middle of 'notpattern' word
> 
> Expected behavior: repeat the search exactly, that is go to the second word
> pattern
> 
> Expected behavior
> 
> Environment (please complete the following information):
> 
>   • Vim version 8
>   • OS: Ubuntu 18.04

I don't see the problem.

The :/ command causes the cursor to move to the next line containing
the latest pattern.  It will also move the cursor to the start of
that line unless 'nostartofline' is set, in which case the cursor
column will not change.

There is a line break following the / in your step 4 and I can't
tell if the whitespace between the / and pattern is significant.  In
either case,

    :/pattern

or

    :/ pattern

I get the expected behavior:  in the first case, :/ moves the cursor
to all three lines in turn; in the second case, :/ moves the cursor
to only the first and third lines, if I insert a space at the start
of every line.

I tested that using Vim 8.0.1453 on Ubuntu 18.04.

Regards,
Gary

**Comment by MontrealSergiy** [comment]
Obviosly ther is a space as it clearly mentioned in the title and I will double check with that vim version

**Comment by chrisbra** [comment]
I find it hard to read, what is actually in the buffer. Is there a space at the beginning of the lines? Does it reproduce with `vim --clean`? What does `:echo @/` show? It should contain the last search pattern as entered. Also, instead of going to command line mode and searching there, does it happen with a regular search `/`?

**Comment by MontrealSergiy** [comment]
Just tested with vim 8.2 on windows 10 and all worked fine (at the least non-graphic version)

**Comment by MontrealSergiy** [comment]
Must be some old bug from ver 8

**Comment by MontrealSergiy** [comment]
What gvim is doing I do not understand well but I imagine gvim is not supposed fully support vim features as it concentrates on GUI UX

**Comment by MontrealSergiy** [comment]
Clean option fixed it too

**Comment by vim-ml** [comment]
On 2020-01-29, MontrealSergiy wrote:
> What gvim is doing I do not understand well but I imagine gvim is
> not supposed fully support vim features as it concentrates on GUI
> UX

No, as long as they are built with the same features enabled, their
behaviors should be nearly identical, the only differences having to
do with different capabilities of the terminal or graphics
interfaces and environments.  In fact, on Unix-like systems, the
same binary can be used for both vim and gvim.

Regards,
Gary

**Comment by chrisbra** [comment]
I am closing this.
