### ISSUE TITLE
netrw confuses directories when netrw_liststyle is 3

### ISSUE THREAD

**Issue by Boobies** [vim/vim#5630]
When you have multiple directories expanded in the tree view (netrw_liststyle set to 3), netrw will try to open whatever filename you select from the last selected directory instead of the directory it is currently in. For example suppose you have the following files:

foo/file1.txt
foo/bar/file2.txt

Navigate to open foo/bar/file2.txt. Then go back to the tree view and attempt to open foo/file1.txt. It will try to open foo/bar/file1.txt instead of foo/file1.txt. The workaround is to either try to reopen it or select the correct directory in advance and only then open your file.

This bug seems super dangerous.

**Comment by Boobies** [comment]
This probably has no relevance but since I have not investigated the bug further, I'll mention that I have netrw_browse_split set to 4 and that I've opened the tree view with :Lexplore.

**Comment by lucianposton** [comment]
Seems related to https://github.com/vim/vim/issues/3276

What netrw version do you have? It should show in `:h netrw-history`.

**Comment by Boobies** [comment]
This would be netrw v162 packaged with Vim 8.1.1401 on Debian stable. If I'm not mistaken the latest in the repository is v168? I should try to see whether this is still a problem.

**Comment by cecamp** [comment]
Actually your using g:netrw_browse_split=4 is quite relevant, because without that extra setting I was unable to duplicate the issue.  I'm going to be here for only a few more days, and then I'll be out-of-touch for about two weeks, so I'll try to work on it tomorrow (Friday).

Regards,
Chip Campbell

**Comment by diegodorado** [comment]
Same issue here with netrw v168., it seems that netrw tries to load the filename of the last selected directory... the second attempt works fine

**Comment by Gankarloo** [comment]
Issue still remains with v169

**Comment by peterwu** [comment]
Same issue with v170

**Comment by eight04** [comment]
https://github.com/vim/vim/blob/1be7e215830d6ec9aa6200aac4ef34ac0ae85af5/runtime/autoload/netrw.vim#L8576-L8585
https://github.com/vim/vim/blob/1be7e215830d6ec9aa6200aac4ef34ac0ae85af5/runtime/autoload/netrw.vim#L9348-L9356

Some problems here:

1. `curdir` at L8576 is overwritten by L8585, making L8576 redundant.
2. Since `s:treedir` and `s:prevwinopen` is always set, L9348 always evaluates to true, making L8584 redundant and `s:treedir` never updates.

Seems that we can workaround this issue with the following change:
```diff
--  if exists("s:treedir") && exists("s:prevwinopen")
++  if exists("s:treedir") && exists("s:prevwinopen") && 0
```

**Comment by drakuno** [comment]
I provided a (Decho) debug log here: https://github.com/vim/vim/issues/3276#issuecomment-985086448
