### ISSUE TITLE
E685: Internal error: text property above deleted line does not continue

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5674]
**Describe the bug**

Sometimes, this internal error is raised:

    E685: Internal error: text property above deleted line does not continue

**To Reproduce**

Run this shell command:

    vim -Nu NONE +"0pu=['a', 'b', 'c']|call prop_type_add('x', {}) | call prop_add(2, 1, {'end_lnum': 3, 'end_col': 1,'type': 'x',})" +'norm! dju'

**Expected behavior**

`E685` is not raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-292
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

Here is a [backtrace](https://github.com/vim/vim/files/4233265/backtrace.txt).

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/a9d4b84d97fb74061eeb42c1433e111fb58825dc (or maybe https://github.com/vim/vim/commit/87be9be1db6b6d8fb57ef14e05f23a84e5e8bea0).

**Comment by lacygoill** [comment]
Since the issue has been fixed, this todo item is no longer relevant:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/todo.txt#L184

**Comment by brammool** [comment]
Thanks, I'll delete that line.

**Comment by poetaman** [comment]
@lacygoill @brammool  I get similar errors. How did you generate backtrace? I guess I cannot share my ``.vimrc`` and steps as they are a bit involved.

Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2021 20:47:48)
macOS version - arm64
Included patches: 1-2758
Compiled by Homebrew
```

<img width="1203" alt="Screen Shot 2021-05-11 at 6 39 10 AM" src="https://user-images.githubusercontent.com/71736629/117825439-30123b00-b224-11eb-8f20-d43d4af2291e.png">

**Comment by dpelle** [comment]
> How did you generate backtrace?

You can e.g. do it this way:
1) start vim in a terminal
2) in another terminal run: `gdb`
3) in gdb, attach to the process ID of vim started in step 1.
```
(gdb) attach 12345
```
4) Set a break point to where E685 happens and continue execution
```
(gdb) br memline.c:3549
(gdb) cont
```
5) in Vim started in step 1, reproduce the E685 error. It should reach the breakpoint in gdb.
6) in gdb, when reached the breakpoint, look at the stack using the `bt` command
```
(gdb) bt
```

Alternatively, since it's an internal error, you could rebuild vim after
uncommenting this line in `vim/src/Makefile`:
```
ABORT_CFLAGS = -DABORT_ON_INTERNAL_ERROR
```
Vim will then crash and dump core when encountering an internal error.
You can then look at the stack trace from the core dump:
```
$ gdb vim core
(gdb) bt
```
