### ISSUE TITLE
`setlocal signcolumn=no` makes vim flicker

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5704]
**Describe the bug**
`setlocal signcolumn=no` makes vim flicker, only found on gvim.

**To Reproduce**
`setlocal signcolumn=no`

**Expected behavior**
no flicker.

**Environment (please complete the following information):**
 - Vim version 8.1.2251
 - OS: Windows 10

**Comment by chrisbra** [comment]
I did not reproduce. Does it matter, if a sign was actually present?

**Comment by Yggdroot** [comment]
sorry, didn't make it clear. The sign is not present. didn't find this issue on terminal vim.

**Comment by chrisbra** [comment]
tried it with gvim 8.2.140 using `gvim --clean`. could not reproduce.

**Comment by Yggdroot** [comment]
I think it's easy to reproduce. Open a file full of text, then `set signcolumn=no`, the screen will flicker just like `:redraw!` is executed. Maybe a redraw is executed under the hood.
If the sign column is present, `set signcolumn=no` make the sign column disappear, it is reasonable that a redraw is needed. However, the sign column is not present, I don't think a redraw is needed.

**Comment by brammool** [comment]
> I think it's easy to reproduce. Open a file full of text, then `set
> signcolumn=no`, the screen will flicker just like `:redraw!` is
> executed. Maybe a redraw is executed under the hood.
> If the sign column is present, `set signcolumn=no` make the sign
> column disappear, it is reasonable that a redraw is needed. However,
> the sign column is not present, I don't think a redraw is needed.

Most options that affect the display trigger a complete redraw when the
option is set.  Also when the value didn't change.  Mainly because it's
sometimes difficult to figure out whether the display does need
updating.  E.g. when updating a window-local value where previously the
global value was used.

It could be made more clever, but it's going to be work and there will
be mistakes.  It's easier to avoid setting an option when it already has
the right value.

-- 
hundred-and-one symptoms of being an internet addict:
147. You finally give up smoking...because it made the monitor dirty.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
