### ISSUE TITLE
":close" succeeds in closing popup terminal window when terminal buffer is replaced by "term_start()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#5765]
**Describe the bug**

`:close` succeeds in closing a popup terminal window, when the terminal buffer has been replaced by `term_start()`.

**To Reproduce**

    vim -Nu NONE +'set hidden|call popup_create(term_start(&shell, #{hidden: 1}), {})|call term_start(["sh", "-c"], #{curwin: 1})'

Run this Ex command:

    :echo [win_gettype(), &bt]

The output is:

    ['popup', 'terminal']

Which confirms that it's a popup terminal window.

Finally, run `:close` to close the window; it succeeds; the window is closed.

**Expected behavior**

`:close` fails, the window is still open, and the error `E994` is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-371
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

If you remove the final `term_start()`, and try to close the window, `:close` fails and raises `E994`, which is expected:

    vim -Nu NONE +'set hidden|call popup_create(term_start(&shell, #{hidden: 1}), {})' +'close'

To be consistent, the same should happen when `term_start()` has replaced the buffer of a popup terminal window with another terminal buffer.

**Comment by lacygoill** [comment]
I've just noticed that – in this case – `:pedit` can still be used to escape the popup window:

    vim -Nu NONE +'set hidden|call popup_create(term_start(&shell, #{hidden: 1}), {})|call term_start(["sh", "-c"], #{curwin: 1})'
    :pedit

Although, it only seems to work when `E36` is raised (when the popup window is too small?).

**Comment by brammool** [comment]
> **Describe the bug**
> 
> `:close` succeeds in closing a popup terminal window, when the terminal buffer has been replaced by `term_start()`.
> 
> **To Reproduce**
> 
>     vim -Nu NONE +'set hidden|call popup_create(term_start(&shell, #{hidden: 1}), {})|call term_start(["sh", "-c"], #{curwin: 1})'

For me this results in showing an error message in the popup (I added
minwidth and minheight to see it, we should probably add a default for
these), and the terminal is in finished state.  Then you can indeed
close the popup, since it doesn't have an active terminal.

> Run this Ex command:
> 
>     :echo [win_gettype(), &bt]
> 
> The output is:
> 
>     ['popup', 'terminal']
> 
> Which confirms that it's a popup terminal window.

But the terminal is finished, right?  With a recent patch I made it
possible to close such a window, otherwise you get stuck in this state.
 
> Finally, run `:close` to close the window; it succeeds; the window is closed.
> 
> **Expected behavior**
> 
> `:close` fails, the window is still open, and the error `E994` is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-371
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**
> 
> If you remove the final `term_start()`, and try to close the window, `:close` fails and raises `E994`, which is expected:
> 
>     vim -Nu NONE +'set hidden|call popup_create(term_start(&shell, #{hidden: 1}), {})' +'close'
> 
> To be consistent, the same should happen when `term_start()` replaces
> the buffer of a popup terminal window with another terminal buffer.

If you use a valid command with the second term_start() then this
happens.

-- 
The term "free software" is defined by Richard M. Stallman as
being software that isn't necessarily for free.  Confusing?
Let's call it "Stallman software" then!
				-- Bram Moolenaar

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Thank you very much for the explanations, it makes sense now; sorry for the noise.

**Comment by lacygoill** [comment]
I didn't know that `:close` only failed when the terminal was active.
And you're right, there's an error message in the popup; to get rid of it, I should have passed a dummy `:` command:

    call term_start(['sh', '-c', ':'], #{curwin: 1})
                                  ^
                                  dummy command
