### ISSUE TITLE
jsonencode() does not work correctly with function references

### ISSUE THREAD

**Issue by ZyX-I** [vim/vim#579]
In Neovim `msgpackdump([function('tr')])` is simply a error. But in Vim trying to dump function reference _silently_ produces invalid JSON: `jsondump(function('tr'))` is an empty string, `jsondump([function('tr'), 1])` is even worse: `[, 1]`. It should be an error. Vim version 7.4.1161.

**Comment by brammool** [comment]
Nikolai Aleksandrovich Pavlov wrote:

> In Neovim `msgpackdump([function('tr')])` is simply a error. But in
> Vim trying to dump function reference _silently_ produces invalid
> JSON: `jsondump(function('tr'))` is an empty string,
> `jsondump([function('tr'), 1])` is even worse: `[, 1]`. It should be
> an error. Vim version 7.4.1161.

The question is what to do with items that can't be converted to JSON.
I have been in doubt, whether to silently drop them or give an error.

Although a missing item in an array is not according to the JSON
standard, it is very useful in practice:

```
[1,,,,8]
```

The missing items would be "undefined" in JavaScript.  In Vim they are
v:none.  Proper JSON would be:

```
[1,null,null,null,8]
```

That's more than twice as long.  Gets worse when there are more missing
items, up to five times as long.

I propose to allow this extension to JSON.  However, it should not be
created accidentally, only when intentionally using v:none as an item.

So, we should probably give an error when using a function, instead of
producing JSON that's not according to the standard.

## 

Give a man a computer program and you give him a headache,
but teach him to program computers and you give him the power
to create headaches for others for the rest of his life...
        R. B. Forest

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ZyX-I** [comment]
Fixed by 7.4.1166.
