### ISSUE TITLE
Ability to not fail test suite due to known flaky tests

### ISSUE THREAD

**Issue by jamessan** [vim/vim#5796]
It would be useful to have a way to opt-in to either ignoring failures in known flaky tests, or not running them altogether.

In Debian, we have mechanisms to run a suite of tests whenever any of a package's dependencies change so we can detect inadvertent breakage.  I've enabled this for Vim, but since I can't rely on the results of the test suite, it's not actually very useful currently.

If I had the ability to disable running the known flaky tests, or ignore their results, I'd have more confidence in relying on the aforementioned mechanism.  The inability to rely on the test suite also affects normal updates, since the test failures cause the entire build to fail (from a packaging perspective), so we need multiple retried builds to get a consistent set of Vim packages built to migrate from one release to the next.

**Comment by chrisbra** [comment]
I suppose you can set the environment variable `$TEST_FILTER` to the tests you want to have executed. This is a bit tedious, so it might make sense to add another variable to the names of tests that should be skipped.

**Comment by brammool** [comment]
James McCoy wrote:

> It would be useful to have a way to opt-in to either ignoring failures
> in known flaky tests, or not running them altogether.
> 
> In Debian, we have mechanisms to run a suite of tests whenever any of
> a package's dependencies change so we can detect inadvertent breakage.
> I've enabled this for Vim, but since I can't rely on the results of
> the test suite, it's not actually very useful currently.
> 
> If I had the ability to disable running the known flaky tests, or
> ignore their results, I'd have more confidence in relying on the
> aforementioned mechanism.  The inability to rely on the test suite
> also affects normal updates, since the test failures cause the entire
> build to fail (from a packaging perspective), so we need multiple
> retried builds to get a consistent set of Vim packages built to
> migrate from one release to the next.

When I run tests on my own system they never fail.  It's the CI
environment that causes tests to be flaky.  Probably because the machine
used is doing various other things at the same time.  Thus there are no
"known flaky tests" in general, you can only find tests that are flaky
in a specific environment.

I also keep fixing tests that fail on Travis.  Thus if you make a list
of flaky tests, how do tests ever get removed when they are no longer
flaky?

So, I would say that instead of ignoring test results, the tests should
be improved.

-- 
Microsoft: "Windows NT 4.0 now has the same user-interface as Windows 95"
    Windows 95: "Press CTRL-ALT-DEL to reboot"
Windows NT 4.0: "Press CTRL-ALT-DEL to login"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> Thus there are no "known flaky tests" in general, you can only find tests that are flaky in a specific environment.

Except for the 39 tests currently listed as flaky in runtest.vim...

> Thus if you make a list of flaky tests, how do tests ever get removed when they are no longer flaky?

The same way they got added?  When the failure is figured out and fixed, they can be removed.

> So, I would say that instead of ignoring test results, the tests should be improved.

Yes, that would be ideal, but in the meantime the false positive failures cause other problems.

**Comment by brammool** [comment]
> > Thus there are no "known flaky tests" in general, you can only find tests that are flaky in a specific environment.
> 
> Except for the 39 tests currently listed as flaky in runtest.vim...

Nearly all of those pass a first time, and even more when run a second
time.  I haven't cleaned up that list, since it's even fine to run all
tests a second time (it's only slower in case a test actually fails).

> > Thus if you make a list of flaky tests, how do tests ever get
> > removed when they are no longer flaky?
> 
> The same way they got added?  When the failure is figured out and
> fixed, they can be removed.

But that list would be on your side.  Per environment?  There would not
be any pressure on making the list smaller, and that usually means it
never gets cleaned up...

> > So, I would say that instead of ignoring test results, the tests
> > should be improved.
> 
> Yes, that would be ideal, but in the meantime the false positive
> failures cause other problems.

Do you have an overview of these tests?  How do you know they are flaky,
and not actual failures?

-- 
The software said it requires Windows 95 or better, so I installed Linux.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> But that list would be on your side.  Per environment?

Why?  It can affect anyone running the test suite and seeing failures.  This is why I suggested making this something that one opts in to.  This functionality exists in the Neovim build, and I use it when building the Debian package.  It's been quite useful.

> There would not be any pressure on making the list smaller

I don't see why that would be the case.  These flaky tests can still cause spurious CI failures for PRs and other environments where the opt-in isn't happening.  It's not unique to Debian.

> Do you have an overview of these tests? How do you know they are flaky, and not actual failures?

Every time I upload Vim to Debian, it builds on 22 different architectures.  When there are tests that fail on a small subset of these systems and don't repeatedly fail, that seems flaky to me, especially when there's not a common factor among the failing systems.

Most of the issues I've been reporting lately are flaky tests.  You've fixed them by either eliminating unnecessary state (like the ruler) or changing timing, not actually changing any functionality.  This is exactly what I mean by false-positive failures, and flaky tests.

The quick response on these has been very helpful stabilizing the tests, but sometimes it understandably takes more time to get things resolved.

**Comment by brammool** [comment]
> > But that list would be on your side.  Per environment?
> 
> Why?  It can affect anyone running the test suite and seeing failures.
> This is why I suggested making this something that one opts in to.
> This functionality exists in the Neovim build, and I use it when
> building the Debian package.  It's been quite useful.

Well, if a test normally passes in most environment, but sometimes fails
in others, I would a failure in "most" to be a real failure.  E.g., on
Travis some tests always pass on Linux, but sometimes fail on Mac.  If
one starts failing on Linux there might be someting actually wrong,
would not want to ignore that.
 
> > There would not be any pressure on making the list smaller
> 
> I don't see why that would be the case.  These flaky tests can still
> cause spurious CI failures for PRs and other environments where the
> opt-in isn't happening.  It's not unique to Debian.
> 
> > Do you have an overview of these tests? How do you know they are flaky, and not actual failures?
> 
> Every time I upload Vim to Debian, it builds on 22 different
> architectures.  When there are tests that fail on a small subset of
> these systems and don't repeatedly fail, that seems flaky to me,
> especially when there's not a common factor among the failing systems.
> 
> Most of the issues I've been reporting lately are flaky tests.  You've
> fixed them by either eliminating unnecessary state (like the ruler) or
> changing timing, not actually changing any functionality.  This is
> exactly what I mean by false-positive failures, and flaky tests.
> 
> The quick response on these has been very helpful stabilizing the
> tests, but sometimes it understandably takes more time to get things
> resolved.

The test environment needs some configuration anyway, thus I think
passing in a list of tests that, when failed, don't make the whole build
fail, would work.  Would an environment variable work best?  Something
like $TEST_MAY_FAIL with a list of test functions.

-- 
Facepalm statement #1: "I'm going to New York tomorrow, hopefully I have time
to visit the White House"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> Would an environment variable work best? Something like $TEST_MAY_FAIL with a list of test functions.

That would work, yes.

**Comment by jamessan** [comment]
Looks like this was addressed in v8.2.0423.

**Comment by brammool** [comment]
Let us know if this works for you.
