### ISSUE TITLE
When 'buftype' is nofile, it is forcibly overwritten

### ISSUE THREAD

**Issue by kuuote** [vim/vim#5807]
**Describe the bug**
Usually, display `E13: File exists` when overwriting an other file.
But if buffer type isn't file, not displayed message and will be force overwritten always.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`
2. Execute below commands

```vim
:write <any file>
:enew
:setlocal buftype=nofile
:write <any file>
```

3. Describe the error

**Expected behavior**
Display error message just like a normal file.

**Environment (please complete the following information):**
 - Vim version 8.2.402
 - OS: Arch Linux
 - Terminal: Alacritty 0.4.1

**Additional context**
Investigated this problem at vim-jp(thanks @koron)
https://github.com/vim-jp/issues/issues/1337#issuecomment-600948187
This behavior changed from vim/vim@11717bb

**Comment by brammool** [comment]
Hmm, one is not supposed to write a file where 'buftype' is "nofile".  But the help does mention that it works.  I guess users can make a mistake with this, thus requiring using ":w!" sounds reasonable.

**Comment by kuuote** [comment]
Thanks for fix it.

**Comment by lilydjwg** [comment]
This patch breaks plugins like [vim-gnupg](https://github.com/jamessan/vim-gnupg), which handle reading and writing the buffer on their own (`buftype=acwrite`). With this patch `:w` or `ZZ` always reports errors about overwriting files.

**Comment by brammool** [comment]
Please give a reproducible example.  Normally a buffer with "acwrite" buftype should not overwrite an existing file, just like a normal buffer.

**Comment by jamessan** [comment]
> Please give a reproducible example. Normally a buffer with "acwrite" buftype should not overwrite an existing file, just like a normal buffer.

Vim-gnupg uses `BufReadCmd`/`BufWriteCmd` to decrypt/encrypt the buffer of a gpg-encrypted file.  I set `buftype=acwrite` for the buffer to ensure that any write is using the autocmds I setup, to avoid writing out unencrypted data to the original file.

The high-level view is essentially:

* `autocmd BufReadCmd *.gpg exe ':r !gpg --decrypt '.expand('<afile>') | setl buftype=acwrite`
* `autocmd BufWriteCmd *.gpg exe ':w !gpg --encrypt > '.expand('<afile>')`

**Comment by lilydjwg** [comment]
I've made a minimal reproducible (and simplified) case.

Load this as a plugin (there aren't any other plugins and no ~/.vimrc):

```
function s:read()
  setl noswapfile nomodified
  let filename = resolve(expand("<afile>:p"))
  execute 'read' fnameescape(filename)
  1d_
  exe 'file' fnameescape(filename)
  set buftype=acwrite
endfunction

autocmd BufReadCmd *.test call s:read()
autocmd BufWriteCmd *.test echo "BufWriteCmd"
```

Create a xxx.test file outside Vim and then edit it with Vim. Make any changes and try to save, an E13 error will be given and the BufWriteCmd is not run.

**Comment by brammool** [comment]
> I've made a minimal reproducible (and simplified) case.
> 
> Load this as a plugin:
> 
> ```
> function s:read()
>   setl noswapfile nomodified
>   let filename = resolve(expand("<afile>:p"))
>   execute 'read' fnameescape(filename)
>   1d_
>   exe 'file' fnameescape(filename)
>   set buftype=acwrite
> endfunction
> 
> autocmd BufReadCmd *.test call s:read()
> autocmd BufWriteCmd *.test echo "BufWriteCmd"
> ```
> 
> Create a xxx.test file outside Vim and then edit it with Vim. Make any
> changes and try to save, an E13 error will be given and the
> BufWriteCmd is not run.

Thanks.  You can see that the file info includes "[Not edited]".
That means that Vim considers this file as created from scratch, in
which case you should not overwrite an existing file without "!".
Internally this is the BF_NOTEDITED flag.

I understand that several plugins relied on the old behavior, and used
the wrong mechanism because it seemed to work, even though one might
consider it a bug.

Now, going back to the previous behavior would go back to the sort-of
wrong way of doing this.  So, let's try a better way: If the BufReadCmd
succeeded then reset the BF_NOTEDITED flag.  Then :write works just like
with a normal file.

-- 
Did you ever stop to think...  and forget to start again?
                                  -- Steven Wright

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
