### ISSUE TITLE
Internal terminal doesn't get 256color

### ISSUE THREAD

**Issue by moetayuko** [vim/vim#5887]
**Describe the bug**
When `$TERM` points to either `tmux-256color` or `screen-256color`, launch the internal terminal and `$TERM` is set to `xterm` there, 256color is not available unless manually changing the environment variable. However, it works if `$TERM=xterm-256color` before launching vim.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `export TERM=screen-256color`
2. Run vim
3. Start the internal terminal `:ter`
4. `echo $TERM`

**Expected behavior**
$TERM of the internal terminal should follow the outer $TERM

**Environment (please complete the following information):**
 - Vim version: 8.2.0510
 - OS: ArchWSL
 - Terminal: windows terminal

**Comment by lacygoill** [comment]
FWIW, that's why I write this in my [`~/.zshenv`](https://github.com/lacygoill/config/blob/ef69cc9e66c9f5176072b3f43eb53efafba7fe65/.zshenv#L713-L715):

    if [[ -n "${VIM_TERMINAL}" ]]; then
      export TERM=xterm-256color
    fi

**Comment by moetayuko** [comment]
@lacygoill it looks like more of a workaround, my usecase is running vim in tmux, where `xterm-256color` is not encourged

**Comment by lacygoill** [comment]
Yes, this was only meant as a workaround, because I had the same issue in the past, and decided to handle it this way, so I thought it might help.

But you're right, `xterm-256color` is wrong in Tmux.  I think this would be better:

    if [[ -n "$VIM_TERMINAL" ]]; then
      if [[ -n "$TMUX" ]]; then
        export TERM=tmux-256color
      else
        export TERM=xterm-256color
      fi
    fi

**Comment by jamessan** [comment]
> But you're right, `xterm-256color` is wrong in Tmux.

If you mean you're running vim inside tmux and that vim has a terminal, then no `xterm-256color` is not wrong.  The applications in the vim terminal are talking to vim's terminal, not tmux.  Vim handles the translation necessary to relay the correct escape sequences to its parent terminal (tmux in this case).

**Comment by lacygoill** [comment]
> If you mean you're running vim inside tmux and that vim has a terminal, then no xterm-256color is not wrong. The applications in the vim terminal are talking to vim's terminal, not tmux. Vim handles the translation necessary to relay the correct escape sequences to its parent terminal (tmux in this case).

Ah, thank you for the correction.

That's what I thought initially, but I wasn't sure about it.
So, IIUC `$TERM` should identify the innermost terminal; and since the Vim's terminal is running inside the Tmux terminal which itself is running in the "real" terminal (xterm, urxvt, st, ...), the innermost one is Vim's terminal and `$TERM` should identify the latter.  But there's no terminal description for Vim's terminal, so inside the latter, `$TERM` should probably fall back on `xterm`.

That makes sense; thanks again.

---

Btw, I could be wrong but I think the current behavior is documented at `:h terminal-unix`:

> Environment variables are used to pass information to the running job:
>     TERM		the name of the terminal, from the 'term' option or
>                         $TERM in the GUI; falls back to "xterm" if it does not
>                         start with "xterm"

Inside Tmux, `$TERM` is `screen`, `tmux` or a derivative, and since those names don't start with `xterm`, Vim falls back on `xterm`.

**Comment by brammool** [comment]
> > If you mean you're running vim inside tmux and that vim has a terminal, then no xterm-256color is not wrong. The applications in the vim terminal are talking to vim's terminal, not tmux. Vim handles the translation necessary to relay the correct escape sequences to its parent terminal (tmux in this case).
> 
> Ah, thank you for the correction.
> 
> That's what I thought initially, but I wasn't sure about it.
> So, IIUC `$TERM` should identify the innermost terminal; and since the Vim's terminal is running inside the Tmux terminal which itself is running in the "real" terminal (xterm, urxvt, st, ...), the innermost one is Vim's terminal and `$TERM` should identify the latter.  But there's no terminal description for Vim's terminal, so inside the latter, `$TERM` should probably identify the "real" terminal, or use `xterm` as a fallback.
> 
> That makes sense; thanks again.

How about making this change:

--- a/src/os_unix.c      2020-02-26 16:15:31.096386873 +0100
+++ os_unix.c   2020-04-05 19:53:24.024132214 +0200
@@ -5493,7 +5493,12 @@
            // Use 'term' or $TERM if it starts with "xterm", otherwise fall
            // back to "xterm".
            if (term == NULL || *term == NUL || STRNCMP(term, "xterm", 5) != 0)
-               term = "xterm";
+           {
+               if (t_colors > 16)
+                   term = "xterm-color";
+               else
+                   term = "xterm";
+           }
            set_child_environment(
                    (long)options->jo_term_rows,
                    (long)options->jo_term_cols,

-- 
A special law prohibits unmarried women from parachuting on Sunday or she
shall risk arrest, fine, and/or jailing.
		[real standing law in Florida, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I've just tested the patch, and it resets `$TERM` to `xterm-color` in Vim's terminal.

I don't know whether it fixes the issue of @dianlujitao, but it doesn't fix mine.
I have a [zsh plugin](https://github.com/zsh-users/zsh-syntax-highlighting) to highlight some tokens on the shell's command-line.  It can be customized by assigning arbitrary colors to the tokens; e.g. I highlight strings with the color 137 (some kind of yellow) from the xterm palette.  It works in a regular terminal, but not in Vim; strings are highlighted in black instead of yellow, with or without the patch.

But that doesn't bother me, because resetting `$TERM` to `xterm-256color` in a Vim terminal fixes this particular issue.

**Comment by brammool** [comment]
> I've just tested the patch, and it resets `$TERM` to `xterm-color` in Vim's terminal.
> 
> I don't know whether it fixes the issue of @dianlujitao, but it doesn't fix mine.
> I have a [zsh plugin](https://github.com/zsh-users/zsh-syntax-highlighting) to highlight some tokens on the shell's command-line.  It can be customized by assigning arbitrary colors to the tokens; e.g. I highlight strings with the color 137 (some kind of yellow) from the xterm palette.  It works in a regular terminal, but not in Vim; strings are highlighted in black instead of yellow, with or without the patch.
> 
> But that doesn't bother me, because resetting `$TERM` to
> `xterm-256color` in a Vim terminal fixes this particular issue.

I don't know how much difference it makes to change from "xterm-color"
to "xterm-256color".  You can try changing the string in the patch.

-- 
Men may not be seen publicly in any kind of strapless gown.
		[real standing law in Florida, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
I can confirm that the new patch with `xterm-256color` instead of `xterm-color` fixes my issue.  Now the highlighting is identical in both Vim's terminal and a regular terminal.
I wasn't sure whether it was ok to use this value, since – I guess – it assumes that the terminal supports 256 colors, while maybe it could support fewer colors (16, 88, ...); so I thought it could cause issues on some terminals supporting fewer than 256 colors.

**Comment by jamessan** [comment]
> I don't know how much difference it makes to change from "xterm-color" to "xterm-256color"

Vim's terminal _always_ supports 256 colors, so it should advertise that to the applications.  Whether the terminal in which vim is running supports 256 colors is a separate matter, but Vim should handle that internally.

**Comment by brammool** [comment]
James McCoy wrote:

> > I don't know how much difference it makes to change from
> > "xterm-color" to "xterm-256color"
> 
> Vim's terminal _always_ supports 256 colors, so it should advertise
> that to the applications.  Whether the terminal in which vim is
> running supports 256 colors is a separate matter, but Vim should
> handle that internally.

If the outer terminal only supports 16 colors, then we cannot possibly
show 256 colors.  It's better to tell the application in the terminal,
so that it can choose the right color palette.  If Vim tries to map 256
colors to 16 it's not going to look good.

-- 
Sometimes I think the surest sign that intelligent life exists elsewhere
in the universe is that none of it has tried to contact us.     (Calvin)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by egberts** [comment]
While you're at it, can you throw in one more logic for unlimited color by setting it to `xterm-direct`?
