### ISSUE TITLE
Misleading warning when writing to a file whose mtime (but not its contents) has been changed outside of Vim

### ISSUE THREAD

**Issue by ppalka-rh** [vim/vim#5936]
**Describe the bug**
When writing to an open file whose modification time (but not its contents) has been changed outside of Vim, we get a prompt which warns us that:
   `WARNING: The file has been changed since reading it!!!`
But the actual contents of the file has not actually been changed, so the prompt/warning here is unnecessary.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean`.
2. Open and write to a file `foo.c`.
3. Do `:! touch foo.c`.
4. Do `:w`.
5. Observe the prompt/warning.

Also observe that, if between steps 3 and 4 we switch to another buffer and then switch back to `foo.c` before writing to it, then the warning goes away.  This suggests to me that the warning is also inconsistent in its current state.

**Expected behavior**
I would expect the warning to get issued only when the file's contents has been changed, and not just when the file's mtime has been changed.

(I regularly run into this warning when e.g. writing to the currently open file after performing Git operations which don't necessarily change the current file's contents but do change its mtime (e.g. rebase operations).)

**Environment (please complete the following information):**
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 11:33:51) on Fedora Linux

**Comment by chrisbra** [comment]
> I would expect the warning to get issued only when the file's contents has been changed, and not just when the file's mtime has been changed.

Well, that would mean, Vim needs to open the file, calculate a hash, do the same for the current buffer and compare both hashes. That has both memory and performance implications (think of large files and slow filesystems), so I think the current assumption, that once the mtime changes also means a change to the files content is good.

Also, by definition, the mtime records when the actual content of a file has been changed. So that assumption is valid. At least that's what Wikipedia tells me.

**Comment by dpelle** [comment]
@chrisbra wrote:

> Also, by definition, the mtime records when the actual content of a file has been changed

I agree. If mtime was changed and content was not changed, it's still suspicious
and rare enough that warning about it is legitimate in my opinion.

**Comment by pppalka** [comment]
> > I would expect the warning to get issued only when the file's contents has been changed, and not just when the file's mtime has been changed.
> 
> Well, that would mean, Vim needs to open the file, calculate a hash, do the same for the current buffer and compare both hashes. That has both memory and performance implications (think of large files and slow filesystems), so I think the current assumption, that once the mtime changes also means a change to the files content is good.
> 
> Also, by definition, the mtime records when the actual content of a file has been changed. So that assumption is valid. At least that's what Wikipedia tells me.

**Comment by ppalka-rh** [comment]
(Sorry about the misclick.)

> > I would expect the warning to get issued only when the file's contents has been changed, and not just when the file's mtime has been changed.
> 
> Well, that would mean, Vim needs to open the file, calculate a hash, do the same for the current buffer and compare both hashes. That has both memory and performance implications (think of large files and slow filesystems), so I think the current assumption, that once the mtime changes also means a change to the files content is good.

Isn't there already a precedent for doing that though?  With the `hidden` option in effect, if we switch away from the buffer for `foo.c`, change the contents of `foo.c` from another process, and switch back to `foo.c`, we get:

```
W12: Warning: File "foo.c" has changed and the buffer was changed in Vim as well
See ":help W12" for more info.
[O]K, (L)oad File: 
```

**Comment by ppalka-rh** [comment]
My point with the above is that it seems Vim already reads in another copy of the current file and compares it to the buffer's contents whenever we switch buffers (at least with the `hidden` option in effect, which basically everyone uses(?)).  It seems like it wouldn't hurt then to do the same whenever writing to the current buffer.  We can even perhaps only do it if the mtimes are different.

**Comment by chrisbra** [comment]
Oh it does indeed, just read through `buf_check_timestamp()`, which does call `buf_contents_changed()` and that does indeed compare each line (it does not calculate a hash). Wow, did learn something :)

**Comment by chrisbra** [comment]
If you see the message `W11: Warning: File ... has changed since editing started`, that means, the file must have been changed, however. See 

https://github.com/vim/vim/blob/cb711abf0f71d8c743cf73c76077f52e17732a8c/src/fileio.c#L4112-L4116

and `reason` is just set a couple of lines above to `changed`, if the buffer contents changed (or size is different):

https://github.com/vim/vim/blob/cb711abf0f71d8c743cf73c76077f52e17732a8c/src/fileio.c#L4048-L4062

**Comment by brammool** [comment]
This is intentionally a warning and not an error: Something else touched the file, so that looks fishy.  This only happens when writing, when reading it's not important enough to worry about.  So I think this is just a bit hard to understand, but works well in practice.

**Comment by iio7** [comment]
It would be really useful if this option can be disabled. Besides from the above, this is a major problem when working on text files on network shares with BOTH Samba and NFS.

This is an example of a valid annoyance with Git: http://nelsonware.com/blog/2018/07/26/eliminate-warning-the-file-has-been-changed-since-reading-it-warning-in-neovim.html

In my specific use case, I just want this behavior to stop. I write a LOT and save a lot during typing, each time I have to press "Y", and then another key to continue, it is **extremely** frustrating.

I don't want Vim to hold my hand, I know what files I have open and why.

I suspect that the issue has something to do with the fact that the write operation is updating the timestamp before Samba or NFS is finished with the file, or because that the time is delayed due to minor network latency or a slight mismatch in the time between the machines.

It's pretty difficult to fix outside of Vim, and it would just be so much easier if there is an option to disable this check.

**Comment by chrisbra** [comment]
I guess you could set the 'buftype' option, together with a custom `BufWriteCmd` autocommand.

I still think it is a valid warning, especially when changing the underlying file using `git` without vim noticing. In that case, you should probably setup a `FileChangedShell` autocommand to re-read the file.

**Comment by brammool** [comment]
Vim helps you to avoid stupid things.  That git changes a file while it's open for editing in Vim is already a problem.  Shouldn't git give a warning that you are changing a file that is in use?  Like it refuses to merge if a file has been changed?  (which I find annoying occasionally, since it's hard to overrule).
I really think the Vim warning is justified, because if you are not 100% sure you know what you are doing, you can easily do something that creates a mess and can't be undone.  Being a bit annoying on a few cases is a small price to pay.

**Comment by iio7** [comment]
No, this is definitely **not** a small price to pay. I sit all day editing files that reside on network shared storage, and I save a lot. This is such a pain in the ass that I have to patch this function out of Vim in order to not bother me. All the time, press Y and then any other key to continue.  You try do to that about a million times each day and then ask yourself if this is a small price to pay.

Furthermore, I complete fail to say why in the world my text editor has taken it upon itself to protect me from doing stupid things! So should we then now have the `rm` command ask us if we really truly want to delete set file?

This functionality either doesn't belong in Vim at all, or at least should be an option.

Please reopen this!

**Comment by cecamp** [comment]
If it bothers you enough, just go into the source and comment out  whatever you want (the test, the warning, and/or the prompt for "Do you really...". Then re-make it, of course.

**Comment by chrisbra** [comment]
so did you try the mentioned workaround of setting the buftype option with a BufWriteCmd ?

Also, are you sure, this is an actual Vim issue and not an infrastructure problem? Why is there a time difference between the client and servers? That shouldn't be there, should it? Also I wonder if the recent [nanoseconds feature](https://github.com/vim/vim/releases/tag/v8.2.3510) could interfere here. 

BTW: @brammool there doesn't seem a way to disable the nanoseconds feature via configure or feature.h and it is also not visible in `:version`

**Comment by iio7** [comment]
Yes, the workaround doesn't work.

Ideally there shouldn't be any time difference between the client and the servers, but we're talking about minor differences that is extremely hard to avoid even when you run NTP on all machines and have working batteries etc.

But really, the job of the text editor is NOT to protect users. At least not in this intrusive and obstructive way. As a help for those who need it, fine, but being able to either opt-in or opt-out is absolutely a MUST have feature.

If Vim want's to protect users, let the user decide whether he wants protecting.

**Comment by chrisbra** [comment]
> https://github.com/vim/vim/issues/5936

What exactly did you try?

> Ideally there shouldn't be any time difference between the client and the servers, but we're talking about minor differences that is extremely hard to avoid even when you run NTP on all machines and have working batteries etc.

yes I could imagine that the nanoseconds feature could cause trouble here. Can you try to run without that feature?

**Comment by andmis** [comment]
> Shouldn't git give a warning that you are changing a file that is in use?

If you are working in a Git repo and have dozens of source files open in Vim buffers (or VS Code or whatever), aren't the files all "in use"? If so, do you think Git should show a bunch of warnings in this case if you, say, switch branches?

**Comment by chrisbra** [comment]
> Shouldn't git give a warning that you are changing a file that is in use?

I don't think git can detect this. Similarly you can `rm` a file that is in use. But I agree, it's not good practice to change the worktree if you are working with a file behind Vims back. That's why you can nowadays use multiple worktrees to have different versions checked out at different places.

**Comment by andmis** [comment]
What about changing `:w! %` to never show this warning, and more generally changing `:w! path/to/file` to to not concern itself with whether `path/to/file` is open in a VIm buffer and modified-since-last-read? TBH it's anyway sort of surprising that `:w! path/to/file` does such a check...

**Comment by andmis** [comment]
FWIW: I just spent a few minutes trying and I couldn't get that to work. (Assuming you mean `let f:fcs_choice`.) I couldn't get `v:fcs_reason == time` to fire.

**Comment by chrisbra** [comment]
I used this in my sudo plugin: 

https://github.com/chrisbra/SudoEdit.vim/blob/e203eada5b563e9134ce2aae26b09edae0904fd7/autoload/SudoEdit.vim#L567-L576

**Comment by schmorp** [comment]
I have a similar issue. The problem is that documenttaion is wrong by claiming this wanring and prompt can be suppressed using an autocmd, but this does not work (in debians vim 2:9.0.1378-2):

   autocmd FileChangedShell * :

Despite the autocmd being active, I still get the prompt. So clearly there is a bug in vim, as the documentation disagrees with the actual behaviour.

**Comment by chrisbra** [comment]
Where did you see this syntax for FileChangedShell ? I think you need to set the v:fcs_choice variable explicitly.

Am 20. Oktober 2023, um 02:59, schrieb schmorp ***@***.***>:

I have a similar issue. The problem is that documenttaion is wrong by claiming this wanring and prompt can be suppressed using an autocmd, but this does not work (in debians vim 2:9.0.1378-2):

autocmd FileChangedShell * :

Despite the autocmd being active, I still get the prompt. So clearly there is a bug in vim, as the documentation disagrees with the actual behaviour.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/vim/vim/issues/5936#issuecomment-1771906325">https://github.com/vim/vim/issues/5936#issuecomment-1771906325</a>", "url": "<a href="https://github.com/vim/vim/issues/5936#issuecomment-1771906325">https://github.com/vim/vim/issues/5936#issuecomment-1771906325</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by sbrocket** [comment]
The workaround recommendations here are bad; FileChangedShell does not trigger at all on a buffer write. This is documented on that autocmd: "Mostly triggered after executing a shell command, but also with :checktime command or when gvim regains input focus." (https://vimhelp.org/autocmd.txt.html#FileChangedShell)

I also double checked that the documentation is correct. There is no call path from buf_write to the buf_check_timestamp function where FileChangedShell is implemented: https://github.com/vim/vim/blob/68dbb58d5189d1293b0f8e032af6bcb84101bd86/src/fileio.c#L4328

Looking at check_mtime, which produces this warning, and where its called in the gigantic buf_write function, there does not seem to be any existing hook that would allow the user to configure this behavior and avoid the "The file has changed since reading it" warning on a buffer write if mtime has changed: https://github.com/vim/vim/blob/68dbb58d5189d1293b0f8e032af6bcb84101bd86/src/bufwrite.c#L545

And yes, at least in the situation where I'm personally encountering this, this does seem to be relevant to the previously referenced change to use nanoseconds if available (https://github.com/vim/vim/releases/tag/v8.2.3510). It doesn't look like any configuration knobs were added in that change. Also technically, the change made there checks whether the nanoseconds part of mtime has changed but still allows the seconds field to be off by 1, though I'm sure that's relatively unlikely to occur in practice.

In the situation I'm encountering this, editing a file on a CIFS-mounted network share, the nanoseconds portion of mtime is updated ever so slightly after the file is saved. I verified this using the following Vim command to save the file and then check the mtime on the file an arbitrary number of times after the save: `:w | !date +\%H:\%M:\%S.\%N; stat %; sleep 1; stat %; sleep 1; stat %`. Here's sample output from that, showing that the mtime is updated by ~2 milliseconds a couple seconds after the file is saved.

```
16:18:20.577699988
  File: create-flatcar-vm.sh
  Size: 2081            Blocks: 5          IO Block: 1048576 regular file
Device: 0,55    Inode: 33182       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2026-02-18 16:18:20.571700900 -0800
Modify: 2026-02-18 16:18:20.573701000 -0800
Change: 2026-02-18 16:18:20.573701000 -0800
 Birth: 2026-02-18 16:18:20.562682300 -0800
  File: create-flatcar-vm.sh
  Size: 2081            Blocks: 5          IO Block: 1048576 regular file
Device: 0,55    Inode: 33182       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2026-02-18 16:18:20.571700900 -0800
Modify: 2026-02-18 16:18:20.573701000 -0800
Change: 2026-02-18 16:18:20.573701000 -0800
 Birth: 2026-02-18 16:18:20.562682300 -0800
  File: create-flatcar-vm.sh
  Size: 2081            Blocks: 9          IO Block: 1048576 regular file
Device: 0,55    Inode: 33182       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2026-02-18 16:18:20.571700900 -0800
Modify: 2026-02-18 16:18:20.571700900 -0800
Change: 2026-02-18 16:18:20.571700900 -0800
 Birth: 2026-02-18 16:18:20.562682300 -0800
```

I agree that this warning is useful in the general case, but such a small mtime difference (~2 milliseconds) from what vim thinks the mtime should be seems unsurprising for a file on a network share and not at all worth warning the user about. In the case above, mtime actually decreases slightly which seems even less worth warning the user about, though I have no idea if that behavior is typical and so would not recommend assuming that in general.

Note that this was on a CIFS share that is already mounted with `actimeo=0`, which is another commonly recommended non-working workaround for this problem. `actimeo=0` is supposed to disable attribute caching, but it looks like mtime and ctime are being updated to match atime at some point. I can't be sure on what side (client/server) or why exactly that is happening, but again, a ~2ms mtime drift on a network share does not at all seem worth warning the user about. 

This warning occurs on _every single save of a file on a CIFS share_, and thus is a nuisance. This isn't some occasional problem. The warning's behavior should be changed or, at minimum, made user-configurable.

**Comment by sbrocket** [comment]
> If you see the message `W11: Warning: File ... has changed since editing started`, that means, the file must have been changed, however. See
> 
> [vim/src/fileio.c](https://github.com/vim/vim/blob/cb711abf0f71d8c743cf73c76077f52e17732a8c/src/fileio.c#L4112-L4116)
> 
> Lines 4112 to 4116 in [cb711ab](/vim/vim/commit/cb711abf0f71d8c743cf73c76077f52e17732a8c)
> 
>     else if (reason[1] == 'h') 
>     { 
>  mesg = _("W11: Warning: File \"%s\" has changed since editing started"); 
>  mesg2 = _("See \":help W11\" for more info."); 
>     } 
> and `reason` is just set a couple of lines above to `changed`, if the buffer contents changed (or size is different):
> 
> [vim/src/fileio.c](https://github.com/vim/vim/blob/cb711abf0f71d8c743cf73c76077f52e17732a8c/src/fileio.c#L4048-L4062)
> 
> Lines 4048 to 4062 in [cb711ab](/vim/vim/commit/cb711abf0f71d8c743cf73c76077f52e17732a8c)
> 
>  	    if (stat_res < 0) 
>  		reason = "deleted"; 
>  	    else if (bufIsChanged(buf)) 
>  		reason = "conflict"; 
>  	    /* 
>  	     * Check if the file contents really changed to avoid giving a 
>  	     * warning when only the timestamp was set (e.g., checked out of 
>  	     * CVS).  Always warn when the buffer was changed. 
>  	     */ 
>  	    else if (orig_size != buf->b_orig_size || buf_contents_changed(buf)) 
>  		reason = "changed"; 
>  	    else if (orig_mode != buf->b_orig_mode) 
>  		reason = "mode"; 
>  	    else 
>  		reason = "time";

And I know this was ~6 years ago now, but this reply is a misread of the original report. W11 is not the error that the original report was complaining about. The original bug here is complaining about the warning on buffer write, not W11. Perhaps this confusion is the source of the non-working workaround recommendations, as well. Yes W11's behavior can be modified with FileChangedShell, but that is a different warning.

The warning we're complaining about here is the one implemented in src/bufwrite.c, in function check_mtime. It has no warning number like W11 and no way for the user to avoid it that I can see. The text of the warning is `WARNING: The file has been changed since reading it!!!`

Please reopen this bug. The replies here seem to be mostly based on this misunderstanding that the original report was about W11, but it is not.

**Comment by ppalka-rh** [comment]
I've been using the following local patch for many years now:

```diff
diff --git a/src/bufwrite.c b/src/bufwrite.c
index 1a1322dfc..d8debd24f 100644
--- a/src/bufwrite.c
+++ b/src/bufwrite.c
@@ -537,7 +537,8 @@ buf_write_bytes(struct bw_info *ip)
 check_mtime(buf_T *buf, stat_T *st)
 {
     if (buf->b_mtime_read != 0
-		  && time_differs(st, buf->b_mtime_read, buf->b_mtime_read_ns))
+		  && time_differs(st, buf->b_mtime_read, buf->b_mtime_read_ns)
+		  && buf_contents_changed(buf))
     {
 	msg_scroll = TRUE;	    // don't overwrite messages here
 	msg_silent = 0;		    // must give this prompt
```

By the way, it seems that my original reproducer doesn't trigger the warning anymore, and Vim nowadays more aggressively checks for buffer/file mismatches and updates the mtime accordingly.  One needs to do `:! (sleep 5 && touch foo.c)&` instead of just `:! touch foo.c`.

**Comment by sbrocket** [comment]
@ppalka-rh I appreciate that, but I’m not enthusiastic about carrying around personal binaries of vim to workaround a nuisance warning like this. This doesn’t seem totally rational in pure “effort involved” terms, I admit, but I think I’m more likely to set up my environment to avoid needing to work on network shares with vim completely. It seems like attitudes so far from maintainers are that the quirks of networked file systems aren’t worth supporting. We’ll see if my or their opinion changes.
