### ISSUE TITLE
workflow of developing

### ISSUE THREAD

**Issue by mattn** [vim/vim#594]
Vim has been developed with contributed code from the maintenars until now. However I'm thinking, because the demand is increasing after moving repository, i can see the limit of working of @brammool even though you are great. Most of contributor must ask to the original maintenar for modifying the files. Repository had moved on github but it's not seemless to get the merit of github workflow. For example, see https://github.com/vim/vim/pull/578 . I suggest to change the workflow to fix/improve the runtime files that @brammool will be possible to modify the files. Note that I'm not talking that you accept pull-request.

How do you think?

Thanks.
 mattn

**Comment by tyru** [comment]
:+1:

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> Vim has been developed with contributed code from the maintenars until
> now. However I'm thinking, because the demand is increasing after
> moving repository, i can see the limit of working of @brammool even
> though you are great. Most of contributor must ask to the original
> maintenar for modifying the files. Repository had moved on github but
> it's not seemless to get the merit of github workflow. For example,
> see https://github.com/vim/vim/pull/578 . I suggest to change the
> workflow to fix/improve the runtime files that @brammool will be
> possible to modify the files. Note that I'm not talking that you
> accept pull-request.
> 
> How do you think?

I think the problem here has nothing to do with the tools.  The problem
is that a lot of maintainers write the syntax/indent file, fix the
problems they see or get complaints about, and then retire.

Even with a simple change as replacing &sw with shiftwidth(), one still
needs to verify the resulting script works.  The maintainer should do
that.  And update his local copy, so that the next time he sends me an
update it doesn't undo this change.  Few maintainers check the
repository for the latest version that we have.

I know it's a hassle to contact each maintainer for a global change like
this.  Fortunately it doesn't happen very often.  I am grateful for
those who take up the task and spend their time on it.

Also, for me it's easiest if I just get the whole file.  A pull request
also works, but it takes more time.  And often I can't see who it is
coming from (github user names are not real names).

I also don't want to force people to use github.  It's nice for people
who have learned to use it, it's not so good for someone who just wants
to make a small fix to one file.  The github UI is also not very
polished, e.g., how do you go from a pull request to the raw diff?  I
only know the trick by editing the URL, there is no link to click on.

## 

The future isn't what it used to be.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tyru** [comment]
> (github user names are not real names)

Please use `Takuya Fujiwara` for my real name (I also changed my github profile) if you include my name (Seems the name who edited runtime files is not included? I don't know, though).

> I know it's a hassle to contact each maintainer for a global change like
> this.

Hm, sounds reasonable but it was certainly hard bit.
However, I hope some improvements like git repository.

**Comment by chrisbra** [comment]
I think there is nothing left to be done here. Closing.
