### ISSUE TITLE
Tests can fail when being re-run because they try to redefine existing functions

### ISSUE THREAD

**Issue by jamessan** [vim/vim#6079]
Although a single test script is only loaded once, there are test functions which internally define new functions.  If they don't either use `func!` to define the function or call `delfunc` at the end of the test routine, then a re-run of the test (e.g., due to flakiness) will cause the test to fail due to redefining an existing function.

One such example is `Test_term_nasty_callback`, which defines `OpenTerms` and `TermExit` unsafely.

`:vimgrep /^ \+func\%[tion]\>[^!]/ src/testdir/test_*.vim` finds a lot of potentially problematic function definitions.  I haven't verified which of them can actually cause problems.

**Comment by brammool** [comment]
James McCoy wrote:

> Although a single test script is only loaded once, there are test
> functions which internally define new functions.  If they don't either
> use `func!` to define the function or call `delfunc` at the end of the
> test routine, then a re-run of the test (e.g., due to flakiness) will
> cause the test to fail due to redefining an existing function.

Ideally every test cleans up after itself.  There are a few checks, but
not for everything.  Files are cleaned up by the Makefile (needed when a
test causes and error and doesn't get to the cleanup lines).

I just added a check that a test doesn't leave any popup windows behind
and fixed a few tests that did.  We can add more of these checks if that
is useful.

> One such example is `Test_term_nasty_callback`, which defines
> `OpenTerms` and `TermExit` unsafely.

That was just fixed yesterday.

> `:vimgrep /^ \+func\%[tion]\>[^!]/ src/testdir/test_*.vim` finds a lot
> of potentially problematic function definitions.  I haven't verified
> which of them can actually cause problems.

They should show up when a test fails a second time.  And then running
it more often won't help, thus keep failing.

In Vim9 script this will get better, as functions will be local to the
scope by default.  But it's not stable enough yet to use outside of the
"vim9" tests.


-- 
I AM THANKFUL...
...for the piles of laundry and ironing because it means I
have plenty of clothes to wear.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> They should show up when a test fails a second time. And then running it more often won't help, thus keep failing.

Right, and that's the problem.  The test, which is expected to retry, fails _any_ retry because it's incorrectly redefining local functions.

Every local function should either be declared using `func!` or have a matching `delfunc` (and I'd prefer the former since it's less to forget).  If you agree with this, I can make the changes.

**Comment by brammool** [comment]
> > They should show up when a test fails a second time. And then
> > running it more often won't help, thus keep failing.
> 
> Right, and that's the problem.  The test, which is expected to retry,
> fails _any_ retry because it's incorrectly redefining local functions.
> 
> Every local function should either be declared using `func!` or have a
> matching `delfunc` (and I'd prefer the former since it's less to
> forget).  If you agree with this, I can make the changes.

Yes.  I was meaning that when "delfunc" is missing we would find out if
it is flaky, since the retry will also fail.

I prefer using "delfunc", because then an error is given when
accidentally using the same function name again.  Which is common when
copy/pasting lines to add another test case.

-- 
hundred-and-one symptoms of being an internet addict:
101. U can read htis w/o ny porblm and cant figur eout Y its evn listd.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
