### ISSUE TITLE
wrong output of ":map" after using "mapset()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6117]
**Describe the bug**

The output of `:map` is sometimes wrong after restoring a mapping via `mapset()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +"call mapset('n', 0, {'lhs': '<C-B>', 'mode': 'n', 'rhs': 'xxx'})"

Then, run this Ex command:

    :map <C-B>

The output is:

    No mapping found

**Expected behavior**

The output is:

    n  <C-B>           xxx

**Environment**

 - Vim version: 8.2 Included patches: 1-812
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

The issue is due to the control modifier.  If I remove the angle brackets around `C-B`, the output of `:map` is correct:

    vim -Nu NONE +"call mapset('n', 0, {'lhs': 'C-B', 'mode': 'n', 'rhs': 'xxx'})"
    :map C-B
    n  C-B           xxx

**Comment by brammool** [comment]
> **Describe the bug**
> 
> The output of `:map` is sometimes wrong after restoring a mapping via `mapset()`.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     $ vim -Nu NONE +"call mapset('n', 0, {'lhs': '<C-B>', 'mode': 'n', 'rhs': 'xxx'})"
> 
> Then, run this Ex command:
> 
>     :map <C-B>
> 
> The output is:
> 
>     No mapping found
> 
> **Expected behavior**
> 
> The output is:
> 
>     n  <C-B>           xxx
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-812
>  - OS: Ubuntu 16.04.6 LTS
>  - Terminal: XTerm(322)
> 
> **Additional context**
> 
> The issue is due to the control modifier.  If I remove the angle brackets around `C-B`, the output of `:map` is correct:
> 
>     $ vim -Nu NONE +"call mapset('n', 0, {'lhs': 'C-B', 'mode': 'n', 'rhs': 'xxx'})"
>     :map C-B
>     n  C-B           xxx

It turns out that maparg() always returns the simplified form of the
mapping.  There can be another mapping for the non-simplified form, at
that then doesn't get restored.

We need to have maparg() find both mappings and return their info in the
dict.  If both were coming from the same :map command then the entries
would be the same, except for "lhs".
However, if one of them was overwritten, the arguments can be different:
	nmap <C-B> xxx
	nmap <02> yyy

In the second command <02> is entered by typing CTRL-V x02

You can check with:
	nmap <C-B>
	nmap <02>

This doesn't reflect the actual list of mapping, when listing mappings
only the not simplified form is used.  Thus maparg() actually finds the
wrong one.

-- 
Microsoft says that MS-Windows is much better for you than Linux.
That's like the Pope saying that catholicism is much better for
you than protestantism.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/9c65253fe702ea010afec11aa971acd542c35de2.
