### ISSUE TITLE
Ctrl-S mapping broken in Windows

### ISSUE THREAD

**Issue by li-ruijie** [vim/vim#6175]
Platform: Windows 10 Professional x64
vim version:  v8.2.0869 
last vim version without bug: v8.2.0834

Reproduce:
1. gvim -u NONE
2. type something
3. (I am not sure if mswin.vim is loaded by default. I think it is. If not, just sources mswin.vim here.)
4. Try to save with Ctrl-S
5. In insert mode, it inserts the ^S character. Doesn't save in Normal or Visual modes.

Simlar problems exist for Ctrl-V and Ctrl-C mappings.

**Comment by k-takata** [comment]
Please select "Remap a few keys" in the installer.

<img width="498" alt="gvim-installer-mappings" src="https://user-images.githubusercontent.com/840186/83368380-8a3f3500-a3f3-11ea-80a4-55d8f9b9949a.png">

This is not the default now, but once you select it and install Vim, the selection will be remembered when you update Vim.

Or add `runtime mswin.vim` in your `.vimrc`.

**Comment by li-ruijie** [comment]
Sorry, I cannot seem to get this working in gvim.
It works as exepected in vim but not gvim.

No matter how I map `<C-S>`, it does not get picked up.

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/ca5bc746073b6fd4b7651bc02f7a18b1b43bd4ca break `<c-s>` mappings.

**Comment by mattn** [comment]
```diff
diff --git a/src/gui.c b/src/gui.c
index 3df992148..b700bf22a 100644
--- a/src/gui.c
+++ b/src/gui.c
@@ -803,8 +803,11 @@ gui_init(void)
 	if (!p_beval)
 	    gui_mch_disable_beval_area(balloonEval);
 #endif
+
+# ifndef FEAT_GUI_MSWIN
 	// In the GUI modifiers are prepended to keys.
 	seenModifyOtherKeys = TRUE;
+# endif
 
 #if defined(FEAT_XIM) && defined(FEAT_GUI_GTK)
 	if (!im_xim_isvalid_imactivate())
```

Probably this fixes the issues.

**Comment by brammool** [comment]
> ```diff
> diff --git a/src/gui.c b/src/gui.c
> index 3df992148..b700bf22a 100644
> --- a/src/gui.c
> +++ b/src/gui.c
> @@ -803,8 +803,11 @@ gui_init(void)
>  	if (!p_beval)
>  	    gui_mch_disable_beval_area(balloonEval);
>  #endif
> +
> +# ifndef FEAT_GUI_MSWIN
>  	// In the GUI modifiers are prepended to keys.
>  	seenModifyOtherKeys = TRUE;
> +# endif
>  
>  #if defined(FEAT_XIM) && defined(FEAT_GUI_GTK)
>  	if (!im_xim_isvalid_imactivate())
> ```
> 
> Probably this fixes the issues.

It's more a workaround than a fix.  The MS-Windows GUI should send
modifiers, instead of including them into the key.  Because otherwise
you cannot make a difference between using a key with a modifier and
entering the resulting key directly.  E.g. for the difference between
CTRL-H and Backspace.

I had a quick look, but I don't see the place where the CTRL modifier is
used to turn CTRL-S into a 0x13 byte.

Let me change seenModifyOtherKeys for now, but I hope someone can fix
the problem by passing the modifier, so that all GUIs behave the same
way.

-- 
hundred-and-one symptoms of being an internet addict:
239. You think "surfing" is something you do on dry land.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
The MS-Windows GUI versions can make a difference between CTRL-H and Backspace even before seenModifyOtherKeys was introduced.

**Comment by brammool** [comment]
Ken Takata wrote:

> The MS-Windows GUI versions can make a difference between CTRL-H and
> Backspace even before seenModifyOtherKeys was introduced.

How/where is that implemented?

-- 
If you're sending someone Styrofoam, what do you pack it in?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
