### ISSUE TITLE
bug: dot-repeat of visual CTRL-A depends on current cursor position

### ISSUE THREAD

**Issue by justinmk** [vim/vim#618]
Repeating a visual CTRL-A depends on the _current_ cursor position. If the cursor is moved up, then the far lines won't get incremented by dot-repeat.

Steps to reproduce:
- insert a blank line, then some numbers:

```

1
2
```
- visually-select the numbers, then use `<c-a>` to increment
- move the cursor up to the blank line, then use `.` to repeat the increment
  - only the first number is incremented

**Comment by vim-ml** [comment]
Hi Justin,

2016-2-1(Mon) 15:46:45 UTC+9 Justin M. Keyes:

> Repeating a visual CTRL-A depends on the current cursor position. If the cursor is moved up, then the far lines won't get incremented by dot-repeat.
> 
> Steps to reproduce:
> 
> insert a blank line, then some numbers:
> 
> 1
> 2
> 
> visually-select the numbers, then use <c-a> to increment
> move the cursor up to the blank line, then use . to repeat the increment
> 
> only the first number is incremented

Same as the existing visual command of the following.

I think it is expected behavior.
Same as the existing visual command of the following.  (:h v_~  :h v_U  :h v_u)
{Visual}~
{Visual}U
{Visual}u

## Thanks.

Best regards,
Hirohito Higashi (a.k.a h_east)

**Comment by wsdjeg** [comment]
@justinmk I think there is no error,you just selet two number ,rather than whole colum.

**Comment by justinmk** [comment]
This is consistent with other visual repeat behavior, so closing.
