### ISSUE TITLE
Cannot easily setup <C-/> (ctrl slash) mapping

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6191]
**Describe the bug**

To setup `<C-/>` I need to counter-intuitively setup `<C-_>` mapping, while `<C-/>` mapping does nothing

**To Reproduce**

Create any mapping starting with: `nnoremap <C-/>`

**Expected behavior**

Mapping of `<C-/>` is created.

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: MacOS

**Comment by brammool** [comment]
Adam Stankiewicz wrote:

> **Describe the bug**
> 
> To setup `<C-/>` I need to counter-intuitively setup `<C-_>` mapping, while `<C-/>` mapping does nothing
> 
> **To Reproduce**
> 
> Create any mapping starting with: `nnoremap <C-/>`
> 
> **Expected behavior**
> 
> Mapping of `<C-/>` is created.
> 
> **Environment (please complete the following information):**
>  - Vim version: 8.2
>  - OS: MacOS

It works for me.  Where is the / key on your keyboard?
Do you need to use the shift key to get it?

-- 
hundred-and-one symptoms of being an internet addict:
10E. You start counting in hex.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by sheerun** [comment]
I have UK keyboard layout (/ is on the left of right shift, no need for pressing shift), this one: https://m.media-amazon.com/images/I/715YFjX8ZTL.jpg

It isn't issue just for me, for example please notice that tcomment plugin defines all shortcuts as <C-_> https://github.com/tomtom/tcomment_vim/blob/master/plugin/tcomment.vim#L134 it's because they actually want `<C-/>` to comment code.

Also please see this stack overflow thread: https://stackoverflow.com/questions/9051837/how-to-map-c-to-toggle-comments-in-vim

**Comment by brammool** [comment]
Are you using plain 8.2 (no patch number)?
If you get a more recent version it's probably already fixed.

**Comment by sheerun** [comment]
I'm using newest vim. It turns out this issue is similar to #6113

More explanation here: https://apple.stackexchange.com/questions/24261/how-do-i-send-c-that-is-control-slash-to-the-terminal

So it seems it just can't be solved by vim because terminal indeed sends it <C-_>

Sorry for trouble, it's sad there are so many quirks on modern terminals

**Comment by lacygoill** [comment]
> So it seems it just can't be solved by vim because terminal indeed sends it <C-_>

Actually, if your terminal supports the `modifyOtherKeys` feature, then it can send a sequence which is unique to `C-/`, and which Vim should not conflate with another keypress.  See `:h modifyOtherKeys`.

The only terminal I know of which supports `modifyOtherKeys` is xterm.  You can test it by:

   - opening an xterm terminal
   - starting Vim with `vim -Nu NONE`
   - entering insert mode
   - pressing `C-S-v` followed by `C-/`

You should get this byte sequence:

    ^[[27;6;47~

For some reason, in a mapping, Vim doesn't seem to recognize `<C-/>`, but you can use this trick:

    vim -Nu NONE +'exe "set <f20>=\e[27;6;47~"' +'nno <f20> :echom "hit ctrl-/"<cr>'

Basically, the `:set` command lies to Vim and tells it that the sequence emitted by the terminal when `<f20>` is pressed is the same as when `C-/` is pressed.  You can then write `<f20>` in your mappings instead of `<c-/>`.  I chose `<f20>` to avoid any issue with a function key which may exist on your keyboard, and which you may use from time to time.  You can replace `<f20>` with any function key up to `<f37>`, and use the shift modifier (so `<s-f1>` up to `<s-f37>` is fine).

I don't know which terminal you're using nor whether it supports `modifyOtherKeys`.  In your terminal, you can perform the same test as described previously. Although be aware of one pitfall: `C-S-v` may be bound at the terminal level to paste the contents of the clipboard; if that's the case, you may need to temporarily disable this terminal key binding.

If you're using iterm, I don't think it supports the feature yet, but it may one day.  Here are a few links which you may be interested in:

- [Support xterm's `modifyOtherKeys` option for keyboard input](https://gitlab.com/gnachman/iterm2/-/issues/5377)
- [Add support for xterm's `modifyOtherKeys`](https://gitlab.com/gnachman/iterm2/-/issues/8382)
- [New extended xterm key presets](https://github.com/gnachman/iTerm2/pull/256#issuecomment-263117368)

**Comment by tonymec** [comment]
> > So it seems it just can't be solved by vim because terminal indeed sends it <C-_>
> 
> Actually, if your terminal supports the `modifyOtherKeys` feature, then it can send a sequence which is unique to `C-/`, and which Vim should not conflate with another keypress. See `:h modifyOtherKeys`.
> 
> The only terminal I know of which supports `modifyOtherKeys` is xterm. You can test it by:
> 
>     * opening an xterm terminal
> 
>     * starting Vim with `vim -Nu NONE`
> 
>     * entering insert mode
> 
>     * pressing `C-S-v` followed by `C-/`
> 
> 
> You should get this byte sequence:
> 
> ```
> ^[[27;6;47~
> ```
> 
> For some reason, in a mapping, Vim doesn't seem to recognize `<C-/>`, but you can use this trick:
> 
> ```
> vim -Nu NONE +'exe "set <f20>=\e[27;6;47~"' +'nno <f20> :echom "hit ctrl-/"<cr>'
> ```
> 
> Basically, the `:set` command lies to Vim and tells it that the sequence emitted by the terminal when `<f20>` is pressed is the same as when `C-/` is pressed. You can then write `<f20>` in your mappings instead of `<c-/>`. I chose `<f20>` to avoid any issue with a function key which may exist on your keyboard, and which you may use from time to time. You can replace `<f20>` with any function key up to `<f37>`, and use the shift modifier (so `<s-f1>` up to `<s-f37>` is fine).
> 
> I don't know which terminal you're using nor whether it supports `modifyOtherKeys`. In your terminal, you can perform the same test as described previously. Although be aware of one pitfall: `C-S-v` may be bound at the terminal level to paste the contents of the clipboard; if that's the case, you may need to temporarily disable this terminal key binding.

Or you can use Ctrl-Shift-q instead, at least if your terminal doesn't use Ctrl-S and Ctrl-Q for flow control. In my xterm it works.
> 
> If you're using iterm, I don't think it supports the feature yet, but it may one day. Here are a few links which you may be interested in:
> 
>     * [Support xterm's `modifyOtherKeys` option for keyboard input](https://gitlab.com/gnachman/iterm2/-/issues/5377)
> 
>     * [Add support for xterm's `modifyOtherKeys`](https://gitlab.com/gnachman/iterm2/-/issues/8382)
> 
>     * [New extended xterm key presets](https://github.com/gnachman/iTerm2/pull/256#issuecomment-263117368)

**Comment by tonymec** [comment]
P.S. In Vim in konsole I see that t_TI and t_TE are set, but konsole preempts Ctrl-Shift-v for Paste and Ctrl-Shift-q for Quit (happily with an "Are you sure?" dialog). There, Ctrl-V or Ctrl-Q followed by Ctrl-/ (i.e. Ctrl-Shift-: ) gives me Ctrl-_ (U+001F INFORMATION SEPARATOR ONE) and yet _ is on a totally different key.

**Comment by sheerun** [comment]
In #6113 I've noticed that the main issue that prevents other terminals from implementing modifyOtherKeys is complete lack of documentation how it should exactly work. The only way is to read xterm source. Probably creating some kind of C library that can handle this would speed things up

**Comment by brammool** [comment]
> In #6113 I've noticed that the main issue that prevents other
> terminals from implementing modifyOtherKeys is complete lack of
> documentation how it should exactly work. The only way is to read
> xterm source. Probably creating some kind of C library that can handle
> this would speed things up

It is documented in the "Alt and meta Keys" section in
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
That is the technical explanation.

This links to a short explation for users:
https://invisible-island.net/xterm/xterm.faq.html#xterm_modother


-- 
There is a fine line between courage and foolishness.
Unfortunately, it's not a fence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> For some reason, in a mapping, Vim doesn't seem to recognize &lt;C-/>, but you can use this trick:

I was wrong.  Vim did not recognize `<C-/>` on my machine because I have to press the shift modifier to produce a slash, so this mapping did not work:

    vim -Nu NONE +'nno <c-/> :echom "hit ctrl-/"<cr>'
                       ^---^
                         ✘

But this one does:

    vim -Nu NONE +'nno <c-s-/> :echom "hit ctrl-/"<cr>'
                       ^-----^
                          ✔
