### ISSUE TITLE
Patch 863 has broken error highlighting when termguicolors is set

### ISSUE THREAD

**Issue by adah1972** [vim/vim#6207]
**Description**
Console Vim 8 versions up to 8.2.862 can show a red background on spelling errors (and other errors some plug-ins choose to highlight). The red background is gone from the terminal unless termguicolors is reset.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` in a console
2. Type a wrongly spelt word
3. Use ":set spell" to highlight the wrong spelling
4. Use ":set termguicolors" to enable true colours (in a compatible terminal)
5. Observe the red background is now gone

**Expected behavior**
Error highlighting like 8.2.862 regardless of the termguicolors setting.

**Environment**
 - Vim version 8.2.863 onwards, compiled from source, huge version
 - OS: Tested on SUSE Linux
 - Terminal: Tested on mintty

**Comment by brammool** [comment]
> **Description**
> Console Vim 8 versions up to 8.2.862 can show a red background on spelling errors (and other errors some plug-ins choose to highlight). The red background is gone from the terminal unless termguicolors is reset.
> 
> **To Reproduce**
> Detailed steps to reproduce the behavior:
> 1. Run `vim --clean` in a console
> 2. Type a wrongly spelt word
> 3. Use ":set spell" to highlight the wrong spelling
> 4. Use ":set termguicolors" to enable true colours (in a compatible terminal)
> 5. Observe the red background is now gone
> 
> **Expected behavior**
> Error highlighting like 8.2.862 regardless of the termguicolors setting.
> 
> **Environment**
>  - Vim version 8.2.863 onwards, compiled from source, huge version
>  - OS: Tested on SUSE Linux
>  - Terminal: Tested on mintty

I can reproduce it with xterm.

It looks like outputting the color for the underline (red) causes the
background color to be cleared.  If you disable the termcap entry for
underline color it works again:
	:set t_8u=

I would not call this a bug for Vim, but since apparently terminals have
this behavior, we need to work around it: If the cterm attributes do not
have "underline" or "undercurl" then do not output t_8u.

-- 
Error:015 - Unable to exit Windows.  Try the door.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
