### ISSUE TITLE
:argedit -- Bug or incorrect documentation when the file is already in argument list

### ISSUE THREAD

**Issue by gdupras** [vim/vim#6210]
**Describe the bug**
From `:help :argedit`:

    When {name} already exists in the argument list, this
    entry is edited.

This is not correct. If the file is already in the argument list, a new entry will be added to the list instead of editing that entry. This is either a bug or the documentation is incorrect. Personally I would prefer if the behavior was changed to match the documentation.

**To Reproduce**
1. vim --clean
2. :args 1.txt 2.txt 3.txt
3. :argedit 3.txt

**Expected behavior**
After doing the above steps, I expected`:args` to show

    1.txt 2.txt [3.txt]

Instead, it shows

    1.txt [3.txt] 2.txt 3.txt

**Environment:**
 - Vim 8.2.592
 - Windows 10
 - mintty 3.1.7

**Comment by nir9** [comment]
Yah It is kinda hard to understand but the docs do state in the end that it does not handle duplicates, but anyway opened a PR that fixes this issue

**Comment by nir9** [comment]
Notice this can be closed since 73a0242 was merged :)

**Comment by nir9** [comment]
Though exactly this scenario is not solved (since ```argedit``` will still add the entry) the commit does add a command that removes duplicates entries in the args list, and the docs are actually correct since if it is already open the existing entry is edited (if changes were made and not saved you will still see them when adding the same file), it is only visually in the args list that you will have duplicate files in the args list.

**Comment by gdupras** [comment]
I have not tried the patch yet but it looks good based on the documentation. Thanks!
