### ISSUE TITLE
Testing detritus left behind after `make clean`

### ISSUE THREAD

**Issue by chdiza** [vim/vim#6224]
This is on 8.2.0936, macOS 10.14.6.  If I run the test suite and then do `make clean`, and then `git status`, I find that the following file (untracked) is left behind:
```
src/testdir/sample.txt
```
I think this should either be deleted in the clean target or put into gitignore.

**Comment by chdiza** [comment]
Surprisingly that file even survives `make testclean`!

**Comment by chrisbra** [comment]
Looks like a left-over bit from  e8f5ec0d30  when the searchcount() function was included.


This patch removes it, seems it was only used for debugging.:

```patch
diff --git a/src/testdir/test_search_stat.vim b/src/testdir/test_search_stat.vim
index 7c4e13f48..54b0c4d89 100644
--- a/src/testdir/test_search_stat.vim
+++ b/src/testdir/test_search_stat.vim
@@ -73,7 +73,6 @@ func Test_search_stat()
   let stat = '\[2/50\]'
   let g:a = execute(':unsilent :norm! n')
   call assert_notmatch(pat .. stat, g:a)
-  call writefile(getline(1, '$'), 'sample.txt')
   " n does not update search stat
   call assert_equal(
     \ #{current: 50, exact_match: 1, total: 50, incomplete: 0, maxcount: 99},

```

**Comment by Shane-XB-Qian** [comment]
looks `testdir/color_ramp.txt` same, it remained if it generated, make 'distclean' or 'clean' would not help to clean it, though can be manually removed. :)

// btw: `clean celan: testclean` , typo ?

**Comment by brammool** [comment]
> looks `testdir/color_ramp.txt` same, it remained if it generated, make 'distclean' or 'clean' would not help to clean it, though can be manually removed. :)

That is intentional, so you can do "cat testdir/color_ramp.txt" to check
the colors in your terminal.

> // btw: `clean celan: testclean` , typo ?

Yes, for when you mistype: "make celan".

-- 
ARTHUR:  Then who is your lord?
WOMAN:   We don't have a lord.
ARTHUR:  What?
DENNIS:  I told you.  We're an anarcho-syndicalist commune.  We take it in
         turns to act as a sort of executive officer for the week.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
