### ISSUE TITLE
build error with vim from source on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by mptangtang** [vim/vim#6256]
**Describe the bug**
I have difficulty in building vim from source. I have tried  lots of suggested build instructions with vim. All of them failed with the following error messages:

```
/vim/vim-8.1/vim81/src$ sudo make
make[1]: Entering directory '/home/tangtang/soft/vim/vim-8.1/vim81/src/po'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/tangtang/soft/vim/vim-8.1/vim81/src/po'
make[1]: Entering directory '/home/tangtang/soft/vim/vim-8.1/vim81/src/po'
make[1]: Nothing to be done for 'converted'.
make[1]: Leaving directory '/home/tangtang/soft/vim/vim-8.1/vim81/src/po'
```
I have tried vim-8.2.0960(from github), vim-8.1(from official website). 

Instructions that I have followed includes :
https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source
https://vennbit.com/building-vim-8-from-source-on-ubuntu/

I also have switched the gcc from 8.4 to 6, 7. 

Even I use the most simplest configure instruction
```
./configure
```
All of them didn't work.

**Comment by jonathonf** [comment]
> sudo make

Firstly, this is a bad idea. There is no reason to build as root.

> make[1]: Nothing to be done for 'first'.

Secondly, this indicates that there is nothing to be done, which most likely means the build process has succeeded. Look again for the output files.

> Even I use the most simplest configure instruction... All of them didn't work.

Thirdly, generally speaking, "it doesn't work" is not a productive starting point. However, it's quite possible that you've made your files unwritable by using `sudo`.

**Comment by tonymec** [comment]
@mptangtang : These messages seem to indicate that you previously built Vim successfully, and that the source didn't change since then.

My gcc is version 7.5.0 and I always build from root because the `make install` step needs to be done as root if you want to put the resulting executable and its runtime files somewhere where every user (every login name) on your computer can use them. I think you need to log in as root and run `make install`.

Here are a couple of HowTo pages describing how I update Vim's source and build it:
1. Getting the latest sources: https://vim.fandom.com/wiki/Getting_the_Vim_source_with_Mercurial
1. Making and installing an executable Vim and its runtime files from these sources (on Linux): http://users.skynet.be/antoine.mechelynck/vim/compunix.htm

Best regards,
Tony.

**Comment by mptangtang** [comment]
> > sudo make
> 
> Firstly, this is a bad idea. There is no reason to build as root.
> 
> > make[1]: Nothing to be done for 'first'.
> 
> Secondly, this indicates that there is nothing to be done, which most likely means the build process has succeeded. Look again for the output files.
> 
> > Even I use the most simplest configure instruction... All of them didn't work.
> 
> Thirdly, generally speaking, "it doesn't work" is not a productive starting point. However, it's quite possible that you've made your files unwritable by using `sudo`.

Thank you. It did succeed.

I thought the message was error message. I made a mistake and cost me lots of time to solve it...
