### ISSUE TITLE
Ensuring backward compatibility of vim9 script

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6259]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

When Vim9 plugins will be released, or old plugins will be rewritten to vim9, they become unavailable on old versions of Vim as Vim9 script is not backward compatible with old Vim.

**Describe the solution you'd like**

Taking lead from JavaScript community, a way to transcompile Vim9 script into legacy Vim script would solve this issue, as it allows for publishing packages that work in both Vim versions, or at least two versions of packages, while maintaining code only on Vim9 version.

**Comment by Shane-XB-Qian** [comment]
let me try to answer your concern or question, pls refer the doc:
`Vim9 script and legacy Vim script can be mixed.  There is no requirement to rewrite old scripts, they keep working as before.`
as my understanding, IF you (or one plugin) were not very sensitive about the vim script performance, probably nothing need to change .. or try vim9. 
it is not very like the divided like vim vs neovim, 
the legacy vim script or vim9 script can be mixed & compatible to use.

**Comment by sheerun** [comment]
Vim9 Script and legacy Vim Script can be mixed only on Vim >= 9, not previous versions of Vim. For Vim9 Script to work on previous Vim versions you need to transcompile it to legacy Vim Script

**Comment by Shane-XB-Qian** [comment]
yea, i see, i was trying to re-edit 1st comment.
// to upgrade old vim to new version probably a easy/direct solution - if do some plugin were really rewrote by vim9 script only, and you had to use that one ..
but i believe as much similar situation on others things, e.g py2 vs py3, new plugin probably would be wrote by vim9 script, but remained ones i do not think owner would re-wrote to vim9 only ... :)

**Comment by sheerun** [comment]
Vim9 is definitely better than Python3 because it can be mixed with its previous version. It's more like ES6 vs ES5 (you can run ES5 in ES6). The issue is running vim9 plugins on legacy vim versions, as well a vim9 plugins on Neovim. Both don't support Vim9 Script yet they support legacy Vim Script so transcompiling would help. I think I'll re-open this issue when Vim9 is released.

**Comment by Shane-XB-Qian** [comment]
um, looks i got your point. and Welcome to use Official Vim and its new version ! :)
or probably neovim should not have sth diff/divided on vim core, but so far it's diff already.
// p.s: just my personal point. :)

**Comment by brammool** [comment]
I'm not sure if a "Vim9 to legacy Vim script" converter would have much use.  Since it would need to understand the most recent version of Vim9 script, the user would need to obtain the most recent converter.  Then why not get the recent version of Vim and enjoy the better speed?

Perhaps there is some use for a plugin author, wanting to make two versions available: fast version for Vim9 and regular version for legacy Vim.  However, it will be quite difficult to write this converter and maintain it, fix any reported bugs.  The usage is probably too low to justify the work.

**Comment by sheerun** [comment]
>  the user would need to obtain the most recent converter

Converter is meant for developers for publishing plugins that support legacy vim. The same way ES6 is transcompiled to ES5 to support legacy browsers

> The usage is probably too low to justify the work.

It indeed might be. But then why Vim tries to maintain backward compatibility at all? (e.g. it starts with compatible mode by default)

**Comment by Shane-XB-Qian** [comment]
many plugins actually req vim verison > 7.3 / 7.4, there was limit already. 
but vim core tried/should to maintain backward compatiblity always, though there were some not - had been happened before. -_-#
same, front developer should be not like to compatible their code with IE8 :)
again, i think those remained plugins those owner i guess they would not rewrite it to vim9 script, but new one perhaps would. **Welcome to use Official Vim and its new version ! :)** this should be easier than upgrade many general users' browsers.
**legacy vim script can keep working, perhaps that can be thought as 'compatibilty' (and this is important or must be!)**, people would thought if his/her plugins should be wrote vim9 script only .. if performance was a concern, then why not, but most remained ones i guess not, or need not.

**Comment by brammool** [comment]
Adam Stankiewicz wrote:

> >  the user would need to obtain the most recent converter
> 
> Converter is meant for developers for publishing plugins that support
> legacy vim. The same way ES6 is transcompiled to ES5 to support legacy
> browsers
> 
> > The usage is probably too low to justify the work.
> 
> It indeed might be. But then why Vim tries to maintain backward
> compatibility at all? (e.g. it starts with compatible mode by default)

Backwards compatibility means that old Vim scripts run on the latest
version of Vim.  That has always been a priority and users rely on it.

What we are talking about here is running a script using the latest
features on an older Vim.  That will always be problematic.  Only some
things that were possible before but used a different syntax could be
converted.  Things that are new, such as the import/export mechanism in
Vim9 script, cannot be done in older Vim script.  At least not with the
same semantics and/or a lot of work.

-- 
ARTHUR:        What?
BLACK KNIGHT:  None shall pass.
ARTHUR:        I have no quarrel with you, good Sir knight, but I must cross
               this bridge.
BLACK KNIGHT:  Then you shall die.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
What is the recommendation for making our scripts cross-compatible? I was modifying my vimrc and thought about using Vim9 for a function that I plan to invoke a lot, but I could not find a way to safely define a Vim9 function in my vimrc without making it complain in older Vim versions / NeoVim.

Just wrapping the `:def` under `if exists(:def)` doesn't work because seems like other Vim versions would need to parse the following lines anyway, and they get confused by the syntax. The only way I can think of is to make a new `vimrc_vim9` file that is selectively sourced. It seems non-ideal to me but the only foolproof I could think of.

**Comment by sheerun** [comment]
Vim9 Script can't run on older Vims. There is no way to use Vim9 Script and at the same be compatible with Vim 8 / Neovim, that's it

**Comment by jamessan** [comment]
> Vim9 Script can't run on older Vims.

I'm pretty sure that's understood.  I think what's being asked for is something analogous to how vim built without `+eval` knows to ignore `if 0` blocks.  Unfortunately, I don't think there's an equivalent mechanism.

**Comment by brammool** [comment]
> > Vim9 Script can't run on older Vims.
> 
> I'm pretty sure that's understood.  I think what's being asked for is
> something analogous to how vim built without `+eval` knows to ignore
> `if 0` blocks.  Unfortunately, I don't think there's an equivalent
> mechanism.

Right.  And since we can't go back to the past and change older Vim
executables, there is no way to make them parse Vim9 script.

Putting the Vim9 code in a separate file will work:

	if exists(':def') == 2
	  source vim9implementation.vim
	else
	  " legacy implementation.
	endif

For short pieces it might work to wrap the Vim9 lines in a function,
since that's only partially parsed:

	if exists(':def') == 2
	  func Vim9implementation()
	    def g:SomeStuff()
	      ...
	    enddef
	  endfunc
	  call Vim9implementation()
	else
	  " legacy implementation.
	endif

I suspect that some Vim9 syntax would not work though.

-- 
Change is inevitable, except from a vending machine.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
Ok that was actually a good trick. At least for my use cases wrapping things in a function did solve the problem. I think what happened before was that I would get `E133: :return not inside a function` errors that wrapping it in a function just mostly convinces Vim into ignoring it.

**Comment by Shane-XB-Qian** [comment]
https://github.com/vim/vim/issues/7851
