### ISSUE TITLE
"simplify()" does not reduce multiple leading path separators

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6263]
**Describe the bug**

`simplify()` does not reduce multiple leading path separators.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -es +"pu=simplify('///tmp')|%p" +'qa!'

The output is `///tmp`.

**Expected behavior**

The output is `/tmp`.

**Environment**

 - Vim version: 8.2 Included patches: 1-981
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Comment by vim-ml** [comment]
On 2020-06-15, lacygoill wrote:
> Describe the bug
> 
> simplify() does not reduce multiple leading path separators.
> 
> To Reproduce
> 
> Run this shell command:
> 
> vim -Nu NONE -es +"pu=simplify('//tmp')|%p" +'qa!'
> 
> The output is //tmp.
> 
> Expected behavior
> 
> The output is /tmp.
> 
> Environment
> 
>   • Vim version: 8.2 Included patches: 1-981
>   • OS: Ubuntu 16.04.6 LTS
>   • Terminal: XTerm(322)

This is not a bug.  The simplify() function should leave two leading
slashes alone.  The POSIX spec states:

    A pathname that begins with two successive slashes may be
    interpreted in an implementation-defined manner, although more
    than two leading slashes shall be treated as a single slash.

Regards,
Gary

----------
http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap04.html#tag_04_11
https://unix.stackexchange.com/questions/12283/unix-difference-between-path-starting-with-and

**Comment by lacygoill** [comment]
> This is not a bug.  The simplify() function should leave two leading
> slashes alone.

Although, if the specification says that more than 2 leading slashes should be treated as a single slash, then maybe this could be considered as a bug:

    echo simplify('///tmp')
    ///tmp

**Comment by vim-ml** [comment]
On 2020-06-15, lacygoill wrote:
>     This is not a bug. The simplify() function should leave two leading
>     slashes alone.
> 
> Although, if the specification says that more than 2 leading slashes should be
> treated as a single slash, then maybe this could be considered as a bug:
> 
> echo simplify('///tmp')
> ///tmp

I later thought about that, too.  I think you're probably right.
I'm not aware of any cases where more that two slashes has any
meaning, and POSIX says they should be treated as one, so it would
make sense for simplify() to collapse more than two to just one.

Regards,
Gary

**Comment by lacygoill** [comment]
Ok, so the original MWE was wrong; Vim correctly follows the [POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/) when a file path starts with 2 leading slashes, but not when a file path starts with more than 2 slashes.  I updated the OP to fix the example.

**Comment by lacygoill** [comment]
Never mind.  The spec is too complex.  I'll need to read it later to check whether this is really a bug.

**Comment by dylnmc** [comment]
@brammool I have been following this issue, and I was hoping that there could be an optional parameter to remove all forward slashes at the front except for the first one.

This is because I am using paths as keys to a dictionary, and without `simplify()` removing all leading duplicate forward slashes, there is no good option than adding unnecessary stuff. 

These are the best two ways of doing it without this optional "remove all prefixed duplicate forward slashes":

- `let foo = function({ path -> simplify(path[:0] is '/' ? '//'..path : path) }(expand(a:path)`
- `let foo = substitute(simplify(expand(a:path)), '^/\{2,}', '/', '')`

I am not a big fan of either of these happening many times per second in a loop or in a repeatedly called function. `let foo = simplify(a:path, v:true)` is much more preferable.

**Comment by vim-ml** [comment]
On 2020-06-15, dylnmc wrote:
> @brammool I have been following this issue, and I was hoping that there could
> be an optional parameter to remove all forward slashes at the front except for
> the first one.
> 
> This is because I am using paths as keys to a dictionary, and without simplify
> () removing all leading duplicate forward slashes, there is no good option than
> adding unnecessary stuff.
> 
> These are the best two ways of doing it without this optional "remove all
> prefixed duplicate forward slashes":
> 
>   • let foo = function({ path -> simplify(path[:0] is '/' ? '//'..path : path)
>     }(expand(a:path)
>   • let foo = substitute(simplify(expand(a:path)), '^/\{2.}', '/', '')
> 
> I am not a big fan of either of these happening many times per second in a loop
> or in a repeatedly called function. let foo = simplify(a:path, v:true) is much
> more preferable.

So what is the measured performance difference of

    let foo = simplify(expand(a:path)

vs.

    let foo = substitute(simplify(expand(a:path)), '^/\{2.}', '/', '')

in your application?

Regards,
Gary

**Comment by dylnmc** [comment]
As it turns out, I am using the new `readdirex()` whose dicts' `name` attributes become the keys, so it shouldn't be a problem for me since I shouldn't be using `simplify()` too frequently in a loop. I do use `simplify()` a few other places, but it is where I don't expect there to be "high traffic" so to speak.

I would suppose you're right, also, in that an additional simple-ish `substitute()` like this shouldn't be too expensive, anyway, even if it seems reasonable that `simplify()` should resolve `'/foo/bar'`, `'//foo/bar'`, and `'///foo/bar'` to the same string for this exact reason.

Thanks,
Dylan
