### ISSUE TITLE
:help netrw-browse-maps show wrong mapping for netrw-c

### ISSUE THREAD

**Issue by DiegoRenner** [vim/vim#6266]
**Describe the bug**
In the output of :help netrw-browse-maps the keybinding to change the diretory to the current one is declared to be c.
In the output of :help netrw-c however it is said that the keybinding for this is now cd which seems to be correct.

**To Reproduce**
1. Run vim 
2. Enter command :help netrw-browse-maps
3. Check keybinding for netrw-c
4. Enter command :help netrw-c
5. Check keybinding for netrw-c

**Expected behavior**
:help netrw-browse-maps should show cd as the keybinding for 
changing directory

**Screenshots**
From :help netrw-browse-maps
c    Make browsing directory the current directory        netrw-c
From :help netrw-c
netrw-c : This map's name has been changed from "c" to cd (see netrw-cd).
          This change was done to allow for netrw-cb and netrw-cB maps.

**Environment:**
 - Vim version 8.2.814
 - OS: 5.7.2-arch1-1
 - Terminal: st

**Comment by cecamp** [comment]
our environment should include information about which netrw you're using.  The latest one is netrw v170g, which you may get from my website: http://www.drchip.org/astronaut/vim/index.html#NETRW ; you'll find that address in :help netrw-debug .  Since its already been fixed, I'll close this issue.

Regards,
Chip Campbell
