### ISSUE TITLE
vim9script: cannot have linebreaks between method calls "->" in :def functions

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6306]
**Describe the bug**
Chained method calls cannot be split at the `->` operator inside `:def` functions.

**To Reproduce**
Run `vim --clean -S tmp.vim` with
```vim
vim9script
def Test(): list<string>
    let x: list<string> = range(5)
            \ ->map('string(v:val)')
    return x
enddef
echomsg Test()
```

Vim will throw the following error:
```
Error detected while processing function <80><fd>R111_Test:
line    1:
E1004: white space required before and after '-'
0
```

**Expected behavior**
When several methods are chained through the `->` operator, it is often more readable to write them on separate lines. It would be nice if this was supported in `vim9script` as well (maybe even without the preceding `\`).

**Environment**
Vim version `8.2.1023`

**Comment by brammool** [comment]
> **Describe the bug**
> Chained method calls cannot be split at the `->` operator inside `:def` functions.
> 
> **To Reproduce**
> Run `vim --clean -S tmp.vim` with
> ```vim
> vim9script
> def Test(): list<string>
>     let x: list<string> = range(5)
>             \ ->map('string(v:val)')
>     return x
> enddef
> echomsg Test()
> ```
> 
> Vim will throw the following error:
> ```
> Error detected while processing function <80><fd>R111_Test:
> line    1:
> E1004: white space required before and after '-'
> 0
> ```
> 
> **Expected behavior**
> When several methods are chained through the `->` operator, it is
> often more readable to write them on separate lines. It would be nice
> if this was supported in `vim9script` as well (maybe even without the
> preceding `\`).

If we leave out the backslash, we must know in the first line that it
continues.  For that to work reliably the -> must be in the first line:

	let x = range(5)->
	    map('string(v:val)')

This won't work:
	let x = range(5)
	    ->map('string(v:val)')

Because we have no clue that the next line is a continuation line.
That is consistent with Vim9 script allowing a line break only after an
operator.

In this specific case we could make it work to recognize the "->" in the
next line, it would require peeking at the next line.  But that doesn't
work in general, several operators can occur at the start of a line.
I'm wondering if it is more important to keep this consistent, or allow
for a few operators to be at the start of the next line.

Javascript/Typescript allows it, but then they use semicolons to
terminate a statement.  A common usage of chaining in other languages,
using a dot:

	SomeBuilder()
	    .setParam()
	    .setParam()
	    .setParam();

I know that this is what most people are used to.  When using -> and
omitting the semicolon we get:

	SomeBuilder()
	    ->setParam()
	    ->setParam()
	    ->setParam()

Problem here is that in Vim "-" is a range, the previous line, and ">" a
right shift,  Thus "->" already has a meaning.  We would have to look at
what's after the "->" to see if it was meant for chaining.  This gets
tricky...

Putting it at the end of the line works, and it's consistent, but it
looks different from what we're used to:

	SomeBuilder()->
	    setParam()->
	    setParam()->
	    setParam()

At least it's better to not allow for white space before the "->" then.

-- 
An indication you must be a manager:
You believe you never have any problems in your life, just
"issues" and "improvement opportunities".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Problem here is that in Vim "-" is a range, the previous line, and ">" a
> right shift,  Thus "->" already has a meaning.  We would have to look at
> what's after the "->" to see if it was meant for chaining.  This gets
> tricky...

How about ignoring the meaning "shift previous line", which imo is not very useful (I can't even remember if I ever wrote this command in a script), in favor of the much more useful meaning "method operator".  If one really wants to shift the previous line, can't they execute `-+->` as a workaround? Or maybe they could prepend a colon to express that the line must be interpreted as a standalone Ex command: `:->`?

There are already some differences documented at `vim9-differences`; they look like good changes which allow to write more readable code.  Wouldn't this change from legacy vimscript fall in that category of useful differences?

**Comment by lacygoill** [comment]
Possibly fixed by https://github.com/vim/vim/commit/a3b7fdc1bb227897f41b8f2958a48d0a26292ff7.
