### ISSUE TITLE
vim9script: Segmentation fault when continuation lines are added inside a :def function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6315]
**Describe the bug**
Vim crashes when a continuation line is added inside a `:def` function.

**To Reproduce**
1. Run `vim --clean -S tmp.vim`  with
```vim
vim9script
def Test(dir: string = ''): string
    let path: string = empty(dir)
            \ ? getcwd()
            \ : fnamemodify(dir, ':p:h')
    return path
enddef
echo Test('/usr/include/stdio.h')
```
2. Result:
```
Vim: Caught deadly signal SEGV
Segmentation fault
```
3. When the two backslashes are removed, Vim throws the following error:
```
 Error detected while processing function <SNR>108_Test:
 line    1:
 E1013: type mismatch, expected string but got number
```

**Environment**
Vim version `8.2.1034`

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/4813484/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/4813485/valgrind.log)
- [asan log](https://github.com/vim/vim/files/4813483/asan.log)

**Comment by brammool** [comment]
Fixed by 8.2.1037.
If you remove the backslashes, the ? and : need to go to the end of the previous line.

**Comment by bfrg** [comment]
@brammool Wouldn't it be easier to just forbid most Ex commands in `:def` functions and force users instead to use `execute` or `execute()` whenever a specific command needs to be run? It seems like it would make the parser a lot easier and the code would also look a lot cleaner.

Most commands can be replaced by functions in recent versions anyway. For example, instead of `setlocal` we can use `setbufvar()`, `setwinvar()` and `settabvar()`. Similarly, `bufadd()` and `bufload()` have been added so that we don't have to explicitly open the buffer in a window. Another example is `setqflist()` and `setloclist()` or the new sign functions. We don't need `:caddexpr` or `:sign` anymore.  Ex commands are often slower and come with some side effects. There was also a feature request (see #5632) to add a `substitute()` function.

**Comment by brammool** [comment]
I don't think so.  Most Ex commands are useful also in :def functions.  The colon is specifically problematic, since we use it to indicate an Ex command in case a variable name matches an Ex command.
In general, line continuation without a backslash only works if the previous line is incomplete, so we know the next line needs to be included.  I made an exception for "->" to see how it would go, but it won't work in general.

**Comment by bfrg** [comment]
What I meant was whenever someone needs to run an Ex command, they could still do it through `execute`, like
```vim
def Test()
    execute '%substitute ...'
enddef
```
instead of directly
```vim
def Test()
    %substitute ...
enddef
```

Since often the start and end of a range needs to be computed first, an `execute` is needed anyway:
```vim
function Test()
    " compute startline and endline
    execute startline .. ',' .. endline .. 'SomeExCommand ...'
endfunction
```
The `:substitute` command is just an example.

**Comment by brammool** [comment]
There are lots of commands that will be used in a :def function: :edit :split, you name it.  Perhaps you were thinking of Ex commands with a range? 

Using :exe is not nice, since it requires using a string, which defeats syntax highlighting.
The already existing mechanism to prefix with a colon is much more natural.
But we only want to use it where needed, otherwise you would also need to write ":let", ":if", etc.

So a possible alternative is to require prefixing a colon when using a range.  That probably works, except for when using  "cond ? expr : expr".  We could require that there is no space after the colon to  make that one work.

I'm trying to make this as easy to understand as we can, with hardly any exceptions.

**Comment by brammool** [comment]
I made a change to require prefixing a colon to a range, and only had to change three lines in the tests.  Thus it does seem doable.
