### ISSUE TITLE
character count is wrong when you use accented letters (each accented letter counts as two characters)

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [vim/vim#6394]
**Describe the bug**
Character count is wrong if you use accented letters and some symbols [àèìùò$£°..].

**To Reproduce**
1. Run `vim --clean`
2. type some random characters
3. save the file and note the number of characters
4. replace some characters with accented letters [àèìùò]
5. save the file and note that the numer of characters has increased, while it shoud be the same. The character count of the current line is wrong too.

**Expected behavior**
Replacing a characters with an accented letter should not increase the caracter count. Each accented letter is counted as two characters.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.2.1-773] 
 - OS: [e.g. Ubuntu 20.04]
 - Terminal: [any] 

**Additional context**
It is important to check if the same problem appears also with other symbols and unicode characters.
If you type gCTRL-G, it gives you a different count for characters and bytes. This could mean that vim counts utf-8 characters as two different characters. Still this means that something confusing is going on with characters and bytes which in vim are used as synonyms.

**Comment by tonymec** [comment]
The count shown by `ls -l` is the number of **bytes**, not of (Unicode) **characters**. If the file is in UTF-8, any character in the range U+0100 – U+07FF is two bytes and anything higher than that is even more.

When you save a file in Vim and it says `nnL, mmC written`, the number mm is also a count of **bytes**. IIUC, this message predates the multi_byte feature and dates from a time when Vim supported only 8-bit encodings, so at that time one byte was one character.

@brammool : Shouldn't the message be modified, to say "nnL, mmB written" (with B instead of the present C) to resolve the ambiguity?

Best regards,
Tony.

**Comment by chrisbra** [comment]
> @brammool : Shouldn't the message be modified, to say "nnL, mmB written" (with B instead of the present C) to resolve the ambiguity?

Agree.

**Comment by tonymec** [comment]
@GianniGi : to see the number of characters (and bytes and…) in the curent editfile, use `g Ctrl-G`.

Best regards,
Tony.

**Comment by g-i-o-r-g-i-o** [comment]
Thanks all for clarifying an ambiguous matter.
I think that the output of :w and the number of characters in the status line, should be a *human readable/usable value*, so the number of characters, not bytes. I often use the number of characters shown in the ruler for formatting, so seeing a wrong number causes some problems.

My suggestion:
- **in the ruler** show the number of characters **C** (counting a multibyte character as one, not as two)
- **when saving a file** show both the number of characters **C** and the number of bytes **B**

**Comment by chrisbra** [comment]
fixed by 3f40ce78f5c178d15871bd784ed878c78f0b8a44
