### ISSUE TITLE
Vim9: automatic continuation lines don't work after a lambda which includes a non-automatic continuation line

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6409]
**Describe the bug**

Automatic continuation lines don't work after a lambda, or an eval string, which includes a non-automatic continuation line.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = range(97, 122)
            ->map({_,v -> nr2char(v)
            \->toupper()})
            ->reverse()
        enddef
        defcompile
    EOF
    )

`E1050` is raised:

    Error detected while processing function <SNR>1_Func:
    line    4:
    E1050: Colon required before a range

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1145
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

This is not the same issue as #6407.
The latter is for automatic continuation lines *inside* a lambda/eval string.
This one is for automatic continuation lines *after* a lambda/eval string.

---

The issue persists if you use an eval string instead of a lambda:

    let x = range(97, 122)
    ->map('nr2char(v:val)
    \->toupper()')
    ->reverse()

Test:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = range(97, 122)
            ->map('nr2char(v:val)
            \->toupper()')
            ->reverse()
        enddef
        defcompile
    EOF
    )

---

The issue disappears if you use a non-automatic continuation line after the eval string/lambda:

    let x = range(97, 122)
    ->map({_,v -> nr2char(v)
    \->toupper()})
    \->reverse()
    ^

Test:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = range(97, 122)
            ->map({_,v -> nr2char(v)
            \->toupper()})
            \->reverse()
        enddef
        defcompile
    EOF
    )

**Comment by lacygoill** [comment]
The issue is not specific to the `->` method call operator.  You can reproduce with `+`:

    let x = range(97, 122)
    ->map({_,v -> nr2char(v)
    \->toupper()})
    + [1, 2, 3]
    ^

Test:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            let x = range(97, 122)
            ->map({_,v -> nr2char(v)
            \->toupper()})
            + [1, 2, 3]
        enddef
        defcompile
    EOF
    )

**Comment by brammool** [comment]
A line break inside a lambda is not supported yet, I'll have a look how to do that.
a line break inside a string is not allowed.

**Comment by lacygoill** [comment]
> a line break inside a string is not allowed.

 But it does work right now:

     vim -Nu NONE -S <(cat <<'EOF'
         vim9script
         def Func()
             echo range(97, 122)
             ->map('nr2char(v:val)
             \->toupper()')
         enddef
         Func()
     EOF
     )

If line breaks are not allowed in an eval string, maybe an error should be raised.

**Comment by brammool** [comment]
> > a line break inside a string is not allowed.
> 
>  But it does work right now:
> 
>      vim -Nu NONE -S <(cat <<'EOF'
>          vim9script
>          def Func()
>              echo range(97, 122)
>              ->map('nr2char(v:val)
>              \->toupper()')
>          enddef
>          Func()
>      EOF
>      )
> 
> If line breaks are not allowed in an eval string, maybe an error
> should be raised.

With the backslash it's possible, since that happens before parsing.  We
were talking about "automatic continuation lines", which happens while
parsing, then line breaks inside a string are not allowed.

It's just too easy to make mistakes with quoting, and there is always
the question of whether the line break should be included in the string
(like a raw string), whether indent should be trimmed, etc.  Let's just
stick to the two ways we have: a string that doesn't cross line
boundaries, and the here-doc style that doesn't use any quotes.


-- 
The only way the average employee can speak to an executive is by taking a
second job as a golf caddie.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
