### ISSUE TITLE
[discuss] where should put 'cursor' when popup dialog showed ?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#6453]
**Describe the bug**
not an issue, but just if someone were interesting to discuss where should the cursor put when popup dialog showed:
![image](https://user-images.githubusercontent.com/13550529/87428467-f4fba700-c614-11ea-84fb-3e2a653251e6.png)
![image](https://user-images.githubusercontent.com/13550529/87428554-1492cf80-c615-11ea-990c-e47200ccab44.png)

**To Reproduce**
1, move the cursor where the popup dialog perhaps going to show
2, show a basic popup dialog

**Expected behavior**
for now: the cursor looks floated over normal sp and the popup dialog, which seems it is **a plain same level -vs- 2 visual levels**.

**Environment (please complete the following information):**
 - vim v8.2.1206

**Additional context**
N/A

**Comment by brammool** [comment]
I think this works fine for most users.  Hiding the cursor when it's under a popup means you have no clue where it is.
Showing a different cursor style might be possible, but usually the user already knows whether the cursor is actually under or in the popup.  Of course, if you bring up a new feature someone is going to ask for it...

**Comment by Shane-XB-Qian** [comment]
ok, but just visually a little weird: 
to a popup dialog (-vs- window), if dialog was just popup right above the cursor, visually perhaps cursor should be hidden (by that dialog); 
but for now, the cursor looked like a super power sth, it can be seen whichever visual level it was .. :) :rofl:

**Comment by Shane-XB-Qian** [comment]
closing, this is more like a preference & discuss & record. thx.
// we can continue even closed.

**Comment by tonymec** [comment]
In gvim (with GTK3) the popup menu (activated by right-clicking with 'mousemodel' set to "popup") is in a different (proportional) font and hides the cursor if it happens to be in the same screen area.

In Console Vim (tested in xterm, in konsole, and even in the non-X11 Linux console) the cursor (the terminal's cursor, I suppose) remains visible even if it is within the popup.

In both cases the CurrentLine and CurrentColumn highlighting (if 'cuc' and 'cul' are on) show where the cursor is, but the ↑ and ↓ keys move the selected popup menuitem, not the cursor, and the ← and → keys have no effect, unlike what happens when there is no visible popup.

For me it's all right; even if the console's cursor remains visible, it seems obvious to me that it is temporarily "deactivated", so to say.

@Shane-XB-Qian : if you want the popup menu to hide the cursor, use gvim.

Best regards,
Tony.

**Comment by Shane-XB-Qian** [comment]
yea, it can move the cursor in/out between under normal-split-window and popup-dialog-window by h/j/k/l.
and cursor would not be hidden by that upper level popup-dialog-window ... that's why looked a little weird.

![image](https://user-images.githubusercontent.com/13550529/87503466-dccc6c00-c696-11ea-9d06-0428e6c24111.png)
![image](https://user-images.githubusercontent.com/13550529/87503480-e6ee6a80-c696-11ea-8451-e67102b5dd1c.png)

// but i did not mean this is not a good looking, just bring up a ticket record/topic which may looked strange.

@tonymec  hi, thx your suggestion, but looks i preferred tui vim. :)
