### ISSUE TITLE
vim9script: E1016: Cannot declare a global variable: g:foo

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6514]
**Describe the bug**
It is not possible to declare global variables, neither at script level nor inside a `def` function.

**To Reproduce**
Run `vim --clean -S test.vim`, with
```vim
vim9script
let g:foo: number = 10
```
Result:
```
Error detected while processing /home/benjamin/vim9-tests.vim:
line    2:
E1016: Cannot declare a global variable: g:foo
```

**Expected behavior**
No error messages when declaring global variables. According to `:h vim9` this should be allowed:
https://github.com/vim/vim/blob/0f60e80f9b6d778e460b4dc8333cd8e17c1b620b/runtime/doc/vim9.txt#L193-L198
I haven't found anything in `:help todo`.

**Environment**
Vim version `8.2.1265`

**Comment by lacygoill** [comment]
I noticed that too:
https://github.com/vim/vim/blob/0f60e80f9b6d778e460b4dc8333cd8e17c1b620b/runtime/doc/vim9.txt#L186-L188

Something looks wrong; while you can assign a value to a global variable *without* `:let`, you cannot *with* `:let`:
```vim
vim9script
let g:global = 'value'
```
    E1016: Cannot declare a global variable: g:global

I think it's like that since [8.2.1024](https://github.com/vim/vim/releases/tag/v8.2.1024) and [8.2.1028](https://github.com/vim/vim/releases/tag/v8.2.1028).

Btw, the same is true for `w:`, `b:`, `t:`, `v:`.

---

This is also true for environment variables.
```vim
vim9script
let $VAR = 'test'
```
    E1016: Cannot declare an environment variable: $VAR = 'test'

And contrary to `g:`, `w:`, ..., you can't just drop the `:let`:
```vim
vim9script
$VAR = 'value'
```
    E1050: Colon required before a range

That's because `$` is parsed as a line specifier (the address of the last line).

As a workaround, we need to use `setenv()`:
```vim
vim9script
setenv('VAR', 'test')
```
Maybe this should also be documented.

---

Regarding the issue about environment variables, it only exists at the script level; inside a `:def` function, you can simply drop `:let`, just like with a global variable:
```vim
vim9script
def Func()
    $ENVVAR = 'foobar'
enddef
Func()
```
And you can even use `:unlet`:
```vim
vim9script
def Func()
    $ENVVAR = 'foobar'
    unlet $ENVVAR
enddef
Func()
```

**Comment by bfrg** [comment]
Thank you. So the documentation is just outdated.

**Comment by brammool** [comment]
Somewhere along the way I realized that allowing the user of :let with global variables is inconsistent.  It would mean that script-local variables need to be declared with :let and then later cannot be used with :let for assigning a value, while global variables would allow :let to be used anywhere.
I consider it simpler to only use :let for declarations, and global variables are not really declared.  I hope this works best.
