### ISSUE TITLE
Vim9: cannot export several items with a single statement

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6526]
**Describe the bug**

In Vim9 script, we cannot export several items with a single statement.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        const MYCONST = 123
        let var = 'test'
        def Func()
        enddef
        export {MYCONST, var, Func}
    EOF
    )

`E1043` is raised:

    E1043: Invalid command after :export

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1287
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(356)

**Additional context**

According to `:h vim9`, we can surround several items with curly brackets to export them in a single command:
<https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/runtime/doc/vim9.txt#L673-L675>

**Comment by lacygoill** [comment]
There is a test which suggests that `E1043` is expected when trying to export one item:
<https://github.com/vim/vim/blob/40f4f7a48cae491f83bd3cdbf7e9b5a23ed870ef/src/testdir/test_vim9_script.vim#L1171>

But I didn't find any test suggesting that `E1043` was expected when trying to export *several* items.  If it is working as intended, then the documentation looks wrong.

**Comment by brammool** [comment]
Export list is not implemented yet.  I'll add a remark in the help.

I'm actually wondering if we can just leave it out.  In a longer script an export list would make it hard to see what is exported and what isn't.  It might work if it's always put at the end, but that is up to the user. Also, the Javascript mechanism "export {oneName as anotherName}" is confusing, the same thing has multiple names, even inside one file.  For import the renaming is required, because different imported items may cause a name clash.  For exporting that can't happen.

If we require the "export" to be put on where the item is declared, everything seems better.  How about dropping the plan for an export list?

**Comment by lacygoill** [comment]
Ok, I don't have enough experience in programming to have a strong opinion; so I'm fine if the feature is dropped from the help.
