### ISSUE TITLE
Vim terminal crushes (SEGV) after resizing the window

### ISSUE THREAD

**Issue by sigcyc** [vim/vim#6551]
**Describe the bug**
I want to use one window to edit code and another :term window to run python. Vim crushes after I maximize the window with text

**To Reproduce**
:term to open the vim terminal (horizontally)
run python in the vim terminal
go back to the original window
C-W _  

**Expected behavior**
The original window is maximized

**Error**
Vim: Caught deadly signal SEGV
Vim: Finished

**Environment (please complete the following information):**
 - Vim version 8.2.980
 - OS: SUSE Linux Enterprise Server
 - Terminal: both GUI and Screen
 - Python 3.7.7

**Comment by lacygoill** [comment]
> Vim version 8.2.980

Try to reproduce on master, because it may have been fixed by one of these:

- [8.2.0989](https://github.com/vim/vim/releases/tag/v8.2.0989)  crash after resizing a terminal window
- [8.2.1030](https://github.com/vim/vim/releases/tag/v8.2.1030)  reducing size of a terminal window may cause a crash

---

Possible duplicate of: https://github.com/vim/vim/issues/6273

For which 2 duplicates were already reported:

- https://github.com/vim/vim/issues/6362
- https://github.com/vim/vim/issues/6464

**Comment by sigcyc** [comment]
Thanks. The problem is fixed in the latest version.
