### ISSUE TITLE
popup_atcursor doesn't support new lines

### ISSUE THREAD

**Issue by sheerun** [vim/vim#6643]
**Describe the bug**

It seems one cannot provide string with newlines to popup_atcursor or popup_create functions

**To Reproduce**

```
call popup_atcursor("foo\nbar", {})
```

**Expected behavior**
Popup is created with multiple lines

**Environment (please complete the following information):**
 - Vim version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 01:26:07)
macOS version
Included patches: 1-1300

 - OS: macos 
 - Terminal: iterm2

**Comment by lacygoill** [comment]
Try to use a list of strings instead of a string:

    call popup_atcursor("foo\nbar", {})
                        ^--------^
                            ✘

    call popup_atcursor(['foo', 'bar'], {})
                        ^------------^
                              ✔

[`popup_atcursor`](https://vimhelp.org/popup.txt.html#popup_atcursor()) parses its first argument like [`popup_create()`](https://vimhelp.org/popup.txt.html#popup_create()), and should accept the same kind of values; see the help of both functions for more info.

**Comment by sheerun** [comment]
ok it makes sense, thank you!
