### ISSUE TITLE
Vim9: invalid command error not caught by try/catch

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6659]
**Describe the bug**

In Vim9 script, an error raised from an invalid command is not caught by a `:catch` clause inside a `:try` conditional.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            try
                invalid
                echom 'valid'
            catch
                echom 'caught'
            finally
                echom 'finally'
            endtry
        enddef
        Func()
    EOF
    )

`E476` is raised:

    E476: Invalid command: invalid

`caught` and `finally` are not echo'ed.

**Expected behavior**

No error is raised.  `caught` and `finally` are echo'ed.

**Environment**

 - Vim version: 8.2 Included patches: 1-1395
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(358)

**Additional context**

The issue disappears if `Func()` is refactored into a legacy function.
```vim
vim9script
fu Func()
    try
        invalid
        echom 'valid'
    catch
        echom 'caught'
    finally
        echom 'finally'
    endtry
endfu
Func()
```
    caught
    finally

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, an error raised from an invalid command is not caught
> by a `:catch` clause inside a `:try` conditional.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             try
>                 invalid
>                 echom 'valid'
>             catch
>                 echom 'caught'
>             finally
>                 echom 'finally'
>             endtry
>         enddef
>         Func()
>     EOF
>     )
> 
> `E476` is raised:
> 
>     E476: Invalid command: invalid
> 
> `caught` and `finally` are not echo'ed.
> 
> **Expected behavior**
> 
> No error is raised.  `caught` and `finally` are echo'ed.

The error happens when compiling the function, not when executing it.
Thus the try/catch should be around where the function is compiled.

Currently :defcompile compiles all functions in the script.  Perhaps
it's useful to compile only one function, like :disassemble does?
Then you could do:

         vim9script
         def Func()
           invalid
         enddef
	 try
	   defcompile Func
	   echom 'valid'
         catch
	   echom 'caught'
         finally
	   echom 'finally'
         endtry

There is a similar problem in test functions.  We use Check commands to
bail out if something is not supported, but still the whole function is
compiled.  We do recognize has('feature') at compile time, but not
commands or function calls.

Without the +terminal feature this works:
	def Func()
	  if has('terminal')
	     termimal
	  endif
	enddef

This doesn't:
	def Func()
	   CheckHasTerminal
	   termimal
	enddef

It's hard to think of a way around this.

-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The error happens when compiling the function, not when executing it.

Ah right.  So, it's not an issue.  I don't know how hard it would be to implement, but it would help if the error message included some information to let the user know that the error was raised during the compilation and not during the execution.  If the message gets too noisy, maybe it could be printed only when the verbosity level had been increased above some arbitrary level.

Anyway, that's a different issue, so closing.

**Comment by lacygoill** [comment]
> I don't know how hard it would be to implement, but it would help if the error message included some information to let the user know that the error was raised during the compilation and not during the execution. If the message gets too noisy, maybe it could be printed only when the verbosity level had been increased above some arbitrary level.

Actually, it's not necessary; that's the whole reason behind `:defcompile`.  There's really nothing to fix; sorry for the noise.
