### ISSUE TITLE
vim.org does not use HTTPS

### ISSUE THREAD

**Issue by kb100** [vim/vim#671]

**Comment by chrisbra** [comment]
And this is a problem because?
Closing, as this is no Vim issue.

**Comment by brammool** [comment]
The site is hosted by SourceForge, so file an issue there.

**Comment by kb100** [comment]
@brammool thanks for replying constructively, I have moved the ticket to the sourceforge tracker.

**Comment by fritzophrenic** [comment]
I assume this issue was created because it is not very safe to download plugins or installers over plain http (or FTP!), because they may have been tampered with. I'd certainly feel more comfortable if I could download from an https page (although I build my own Vim these days, and get most of my plugins from their source repository, so that's less of an issue for me).

Equally bad, the login form for plugin authors is not encrypted, so it would be easy to sniff their username and password. And the lack of a basic feature like HTTPS does not give "warm fuzzy feelings" for the password storage on the back-end. So it may be easy for an attacker to upload malicious scripts in the name of a respected plugin author.

SourceForge itself has HTTPS for its downloads and user login. I am pretty sure I've seen SourceForge-hosted sites with HTTPS downloads. Are you sure this is something for SourceForge to fix?

**Comment by kb100** [comment]
@fritzophrenic Yes that's why I created this issue. I don't know if this is something for SourceForge to fix, but the vim website ticket tracker is hosted on SF nonetheless. Apparently this repo is strictly for vim issues excluding the vim website.

**Comment by fritzophrenic** [comment]
Thanks, I found it. Somehow I've been active in the Vim community for about 7 years and didn't know (or forgot) about the website issue tracker. https://sourceforge.net/p/vimonline/bugs/104/ is the new version of this issue for anyone finding this issue in the future.
