### ISSUE TITLE
Vim allows adding and removing items from a const list

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6719]
**Describe the bug**
Vim doesn't throw any errors when a `const` list is filtered with `filter()`.

According to `:h :const`, `const` is like `lockvar 1 {name}`. Further down the help page it says that when locking a list with `lockvar 1` items cannot be added or removed from the list.

**To Reproduce**
1. Run `vim --clean -S test.vim`
```vim
function Test() abort
    const test = range(10)
    return filter(test, 'v:val % 2 == 0')
endfunction
echo Test()
```
2. Result:
```
[0, 2, 4, 6, 8]
```

**Expected behavior**
I would have expected Vim to throw an error when items are being removed from a `const` list.

**Environment**
Vim version `8.2.1464`

**Comment by brammool** [comment]
> **Describe the bug**
> Vim doesn't throw any errors when a `const` list is filtered with `filter()`.
> 
> According to `:h :const`, `const` is like `lockvar 1 {name}`. Further down the help page it says that when locking a list with `lockvar 1` items cannot be added or removed from the list.
> 
> **To Reproduce**
> 1. Run `vim --clean -S test.vim`
> ```vim
> function Test() abort
>     const test = range(10)
>     return filter(test, 'v:val % 2 == 0')
> endfunction
> echo Test()
> ```
> 2. Result:
> ```
> [0, 2, 4, 6, 8]
> ```
> 
> **Expected behavior**
> I would have expected Vim to throw an error when items are being removed from a `const` list.

It appears only the variable itself is locked, not the value.
As documented, it would work like ":lockvar 1 var".  But that still allows
modifying values in a list or dictionary.
Is it too late to change it to behave like "lockvar 2 var"?
Now that we are fixing it to match the documentation, maybe it's OK to
go one step further, even though it's not backwards compatible?

-- 
How do I set the laser printer to stun? 

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
I personally wouldn't mind if you changed it to `lockvar 2 var`. I haven't seen people using `const` too often anyway so far.

**Comment by brammool** [comment]
> I personally wouldn't mind if you changed it to `lockvar 2 var`. I
> haven't seen people using `const` too often anyway so far.

I did that, but now realize that it's not that simple.
With ":lockvar 2" behavior it's still possible to change the third
level:

    const l2 = [0, [1, 2, 3], 4]
    let l2[1][0] = 7
    const d2 = #{a: 0, b: [1, 2, 3], c: 4}
    let d2.b[1] = 8

We would actually want unlimited level for this.  But only when the
arguments are a literal value.

	let list1 = []
	const dd = #{a: list1}

	call add(list1, 'one')  " should work, right?

In general, even locking the first level could not be right:

	let someList = []
	const mylist = someList
	call add(someList, 'yes')

-- 
hundred-and-one symptoms of being an internet addict:
223. You set up a web-cam as your home's security system.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errantepiphany** [comment]
@brammool , @janlazo , @justinmk, @bfrg :
Welp the fix for this just broke a plugin I was working on. I'm okay with it, as now the behavior of const aligns with how it was documented. However, perhaps it would be nice to provide some kind of in-between? Not as loose as a "let", but not as strict as the (now fixed) "const"? To be specific, once you assign a dict or list to a variable, you can't ever change to a different dict or list, however you can still change the *contents* of that dict or list. Why? Perhaps the contents of that dict or list are lazy-loaded. In the vimscript I was working on, I had a const dict that acted as a lazy-loaded "cache". I had a global-scoped function exposed where code would ask for something, and if it was in the script-scoped const dict cache, it would get returned, but if not, it was created, added to the dict, and then returned. The dict was a const because I wanted the dict itself to not be changeable, but the contents of that dict cache were expected to grow over time. The old const behavior allowed for this up until this fix, which broke it. Again, I'm fine with that since that's how it was documented. But now I have to change from "const" back to "let", which isn't exactly what I wanted. Do you believe this to be a valid use-case/requirement (something in-between "let" and "const")? If so, I can open up a new issue.

**Comment by k-takata** [comment]
You can still use `:lockvar`.

**Comment by brammool** [comment]
Yeah, I know what you mean.  I thought this was possible, but can't actually find a way to do it.
It is currently done for some variables, e.g. function arguments.  The question is: how do we specify this?
It could perhaps be done with a flag or argument to :const, but it might get a bit obscure.
An alternative would be a new command such as :fixed or :readonly.
How do other languages do this?

It appears most languages do it the other way around: "const" only means the variable can't be changed, but a composite type can be changed.  This is actually often leading to mistakes.  Anyway, if we do this in Vim we could make a real const by locking it:
    const l = []
    add(l, 123)  # OK, list itself is modifiable
    lockvar! l
    l[0] = 99     # FAIL
But that would require two commands for a real constant.

For Vim9 we want to get closer to what other languages do, so perhaps we should use :const like Javascript/Typescript, and add something else for a "real const".  Strangely Javascript/Typescript does not support that, There are readonly arrays, but not something that applies to all types.
The simplest then would be using ":const! var".  As in "really const".  Would that work?

**Comment by brammool** [comment]
I was reading through some Typescript documentation and found that "{value} as const" is often used to change the type of a value to make it immutable.  It's not the same though, since Vim changes the value itself, while Typescript changes the type of the value.  Also, I don't like the "as const" construct.  It splits the type specification at the start of the statement and the extra parameter, they can be far apart.  The "as {xxx}" also has different semantics  in Typescript, I very much doubt it is useful to add to Vim.

Thus so far my conclusion is:
- We can make ":const" work like Typescript: only lock the variable itself, not the value.  So that a list can still be changed, but you can't assign another list.
- We could use ":const!" to also lock the value.  Typescript does not offer an equivalent and it does what we want in a simple way, lock the value so that it can't be changed, no matter how it's passed around.

Examples:
const myList = []                 # cannot assign to "myList", but can modify the list entries
const! myList = ['a', 'b', 'c']  # cannot change "myList" in any way, also when passing the value around

Comments?

**Comment by errantepiphany** [comment]
Sorry for the delayed response, @brammool . It was a long holiday weekend here. :)

I know very little about Typescript, so I can't make informed comments about it. My background is a lot more Java, so I think when I was using "const" in vimscript, what I had in my mind was more like Java's "final" keyword. With final, you can't change the variable, but if it's a composite type, you can still change it's contents (as long as it hasn't been made unmodifiable [1]). But now I have to admit that I should have read the Vim docs on how const was originally intended to behave, instead of just making assumptions based on what I was seeing with the bug.

Regrading your suggestion of ":const" vs. ":const!" (with an exclamation point), I like it a lot and I do think it makes intuitive sense. However, that being said, wouldn't it be bad to change the behavior of const at this point, after it has already been released and documented a different way? I know I'm the one in this thread bringing up the idea of having this new type of behavior, but I'm worried it would (understandably) upset some people who have already been coding with it as documented.

So, does the above mean the situation warrants an entirely new keyword? I don't know... If I'm the only one who wants this and no one else cares, probably not, LOL. Hmmm... Would it be weird to introduce a new lock "depth" for this? Perhaps a lock depth of 0 (zero)?

[1] https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/Collections.html#unmodifiableMap(java.util.Map)

**Comment by rhysd** [comment]
I sent the patch adding `:const`. As @brammool said, I intended the same behavior as JavaScript:

```javascript
const a = [];
a.push(1); // OK
a = []; // ERROR
```

And locking value recursively is sometimes confusing. For example,

```vim
function! Foo(a)
  let b = [a:a]
  lockvar! b
endfunction

let a = []
call Foo(a)
call add(a, 1) " Error E741
```

Here `a` is implicitly locked. This is very simple case so we easily understand what happens. But please imagine the place where the variable is locked (`lockvar! b` in above) is far apart from the place where the variable is used (`call add(a, 1)` in above). It would be difficult why the value is locked when seeing the E741 error. This does not happen when only the variable is locked.

I also concerned performance. `:const` should be able to be used casually as better replacement of `:let`. And sometimes we handle big dictionaries with deeply nested values. Such big dictionaries require locking many dictionaries on `:lockvar!`. I thought `:const` should not bring such a performance concern implicitly. IMO, such a thing which may introduce kind of performance concern should be explicit hence I'd prefer to using `:lockvar!` explicitly.

BTW, `as const` in TypeScript is totally different from JavaScript's `const`. It is static type-level thing and never affects runtime value.

**Comment by brammool** [comment]
@rhysd - Where did you send the patch?

Instead of ":const!" it would be nice if we can something already known from another language.  But I don't know one that works this way.  We could do something like ":locked const = ..." but is that better?
"final", "static", "readonly" all don't really mean the same thing.

About also locking nested values: that is intentional and it can be useful.  But for ":const!" we probably do not want to do that.  Thus ":const! VALUE = [1, arg]"  would mean that you can't change VALUE[1] to overwrite "arg", but "arg" itself can still be changed.  In my opinion this is intuitive.

**Comment by k-takata** [comment]
> @rhysd - Where did you send the patch?

I think he is talking about the patch 8.1.1539 (#4541).

**Comment by errantepiphany** [comment]
@brammool , isn't what you are describing an example of an existing lockvar depth? (Honestly I'm a bit confused about the difference between lockvar depth 1 and 2.) What do you think of my idea of adding a new lockvar depth of 0 (zero) to provide the ability to lock the variable, but if it is a list or dictionary, one can still add/remove items? That way it will always point to the same list or map, but the contents of it can change. Introducing a new (admittedly, special) lockvar depth for this would mean a new keyword wouldn't have to be invented. But if you think there should be, I kind of like one of your original ideas: "fixed".

**Comment by rhysd** [comment]
@brammool 

> Where did you send the patch?

As @k-takata kindly pointed, it was 8.1.1539.

> But I don't know one that works this way.

I also don't know a scripting language which has feature to lock variable or value recursively. For statically typed languages,

- const propagation in D language: https://dlang.org/articles/const-faq.html
- `readonly` in TypeScript: https://basarat.gitbook.io/typescript/type-system/readonly
- immutable in Rust: https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html

are similar features but they are done at compile time.

> About also locking nested values: that is intentional and it can be useful. But for ":const!" we probably do not want to do that. Thus ":const! VALUE = [1, arg]" would mean that you can't change VALUE[1] to overwrite "arg", but "arg" itself can still be changed. In my opinion this is intuitive.

It sounds interesting. But how can we determine the depth? I think depth is 2 for 2-dim array like `[[ arg ]]`. But if inner value is dict, what happens? Is the depth 2 for `[{ 'a': arg }]`? How about `[{ 'a': 2 }, 1, [[ arg ]] ]` where depth of items are different?

**Comment by brammool** [comment]
> @brammool 
> 
> > Where did you send the patch?
> 
> As @k-takata kindly pointed, it was 8.1.1539.

Aha, I thought you had a new patch.
 
> > But I don't know one that works this way.
> 
> I also don't know a scripting language which has feature to lock
> variable or value recursively. For statically typed languages,
> 
> - const propagation in D language: https://dlang.org/articles/const-faq.html

Transitive const is a concept that tries to fix the C++ const, which is
not all that useful.  But D is hardly used now, I don't expect more than
a few Vim users work with D code.

> - `readonly` in TypeScript: https://basarat.gitbook.io/typescript/type-system/readonly

"readonly" in TypeScript is very confusing.  It seems to make sure a
property can't be changed, but you can change it anyway (there is an
example in the page you link to).

Also, "readonly" is for properties, which we don't have yet (class
support might be added later to Vim9).

Otherwise Typescript has the Readonly type, so you can do
Readonly<list>.  But it looks like you can override with
"as {something}", and it doesn't work transitively, thus it's a hassle
to use and doesn't give a guarantee.

> - immutable in Rust: https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html
> 
> are similar features but they are done at compile time.

Right. But Vim script is interpreted, only the :def functions are
compiled.  And we want the same semantics at the script level.

> > About also locking nested values: that is intentional and it can be
> > useful. But for ":const!" we probably do not want to do that. Thus
> > ":const! VALUE = [1, arg]" would mean that you can't change VALUE[1]
> > to overwrite "arg", but "arg" itself can still be changed. In my
> > opinion this is intuitive.
> 
> It sounds interesting. But how can we determine the depth? I think
> depth is 2 for 2-dim array like `[[ arg ]]`. But if inner value is
> dict, what happens? Is the depth 2 for `[{ 'a': arg }]`? How about `[{
> 'a': 2 }, 1, [[ arg ]] ]` where depth of items are different?

It's not about depth but whether the value is a constant.  What we really
want in most cases is define a constant and know it won't ever change.
When referring to an existing variable you don't want to be able to
replace it.  But when it's a composite, such as a list, you can change
the contents.

	let cvar = [1, 2, 3]
	const dvar = [10, 11, 12]
	const! VALUES = ['a', 'b', cvar, dvar]
	VALUES[0] = 'x'  # Error
	VALUES[2] = 'c'  # Error
	VALUES[2][0] = 99  # OK, if you really want to
	VALUES[3][0] = 99  # Error, dvar is a const

	cvar[0] = 9  # OK, now VALUES has also changed

I think this will work and is mostly intuitive.  The only worry is that
there is no equivalent in another language.


-- 
ARTHUR:          But if he was dying, he wouldn't bother to carve
                 "Aaaaarrrrrrggghhh".  He'd just say it.
BROTHER MAYNARD: It's down there carved in stone.
GALAHAD:         Perhaps he was dictating.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by errantepiphany** [comment]
@brammool 

Hmmm... I don't think that's what I was looking for, but maybe what I was looking for is an undesired use case. I was wondering if we could have something like this. I'm using the keyword "fixed" because there's nothing that behaves like this currently.

let lvar = { 'foo': 'bar' }
let lvar['foo'] = 'woo' " OK; replacing a value in a composite type allowed
let lvar['bob'] = 'cat' " OK; adding a new value to a composite type allowed
let lvar = {} " OK; replacing existing variable allowed

const cvar = { 'foo': 'bar' }
let cvar['foo'] = 'woo' " ERROR; replacing a value in a composite type NOT allowed
let cvar['bob'] = 'cat' " ERROR; adding a new value to a composite type NOT allowed
let cvar = {} " ERROR; replacing existing variable NOT allowed

fixed fvar = { 'foo': 'bar' }
let fvar['foo'] = 'woo' " OK; replacing a value in a composite type allowed
let fvar['bob'] = 'cat' " OK; adding a new value to a composite type allowed
let fvar = {} " ERROR; replacing existing variable NOT allowed

As you can see, the difference with "fixed" is that you can modify the contents of the dict (same would go for list), but you can't replace the variable itself with a completely different dict. This is how "const" used to work before this fix, and what I had been depending on. The purpose I had was that the "fixed" var was a lazy-loaded cache, where the contents would grow over time, but one wasn't allowed to change the var reference to a different dict.

Was this example more clear? I'm sorry if it wasn't before. But again, perhaps a new keyword isn't necessary... Perhaps just adding a lockvar depth of 0 (zero) might make more sense.

**Comment by brammool** [comment]
The thing is that what you call "fixed" is how "const" behaves in Javascript/Typescript.
Internally Vim uses "fixed" for variables that can't be changed, also can't be "unlocked".
It would be similar to using "lockvar" with a depth of zero.

Using "const" as proposed, only making changes to the variable itself invalid, but allowing changes to the value, is how this works in most languages. Thus I don't see a problem with it.
Using "const!" would be Vim specific, thus I'm still wondering if there is a language that does the same and has a good keyword for it.

**Comment by errantepiphany** [comment]
The "const" vs. "const!" that you are proposing is starting to grow on me. Unfortunately I don't know of another language keyword that would be better. What do you think is the best path forward here?

**Comment by brammool** [comment]
There is one alternative to ":const!" that is worth considering:  <const>
`const NAMES = <const>["Peter", "Petra"]`

An advantage is that it can also be used when passing a value to a function:
`process(<const>['one', 'two', 'three'])`
Not sure how useful this is, since the list can't be used again by the caller.
When passing a variable this also creates a dilemma:
`process(<const>myList)`
Now in the process() function myList cannot be modified.  But once the function returns,
is the list mutable again?  That would require locking the list before the call, and restoring the locked state afterwards.  That's a bit complicated and might be slow.

I'm not sure how useful this is. Enforcing an argument to not be changed by a function is more a way to write clean code than having a practical advantage.  If it's really wanted, using :lockvar/:unlockvar is possible.
