### ISSUE TITLE
text pasted from global clipboard gets interpreted as insert mode command

### ISSUE THREAD

**Issue by claireanlage** [vim/vim#6732]
**Description**
if text that is pasted from global clipboard via C-Shift-v contains characters that are mapped to something with inoremap that something will be executed.

**To Reproduce**
1. Run `vim --clean` compiled with clipboard support
2. enter `:inoremap asd test <enter>`
3. write asd somewhere else with clipboard support (in your browser address bar for example) and copy the text
4. go back to vim, enter insert mode and press C-shift-v

**Expected behavior**
'asd' is inserted

**Observed behavior**
'test' is inserted

**Environment**
 - gvim 8.2.0814-3
 - Arch Linux
 - Terminal: Alacritty

**Additional context**
I suppose you could say that this _is_ expected behavior (and if so, feel free to change the bug report to a feature request). However I think that a more sensible default behavior for the clipboard would ignore key bindings (or maybe work without insert mode). In my specific case, I have `df` bound to `<esc>` in insert mode, and I noticed when pasting `0x800700df`

**Comment by lacygoill** [comment]
Try to enable the bracketed paste mode by writing this into your vimrc:
```vim
if &t_BE == ''
    let &t_BE = "\e[?2004h"
    let &t_BD = "\e[?2004l"
    let &t_PS = "\e[200~"
    let &t_PE = "\e[201~"
endif
```
See [`:h xterm-bracketed-paste`](https://vimhelp.org/term.txt.html#xterm-bracketed-paste).

**Comment by claireanlage** [comment]
thanks, that fixed it. So it's an issue with alacritty, not vim, am I understanding this correctly?

**Comment by lacygoill** [comment]
I think it depends on the value of `$TERM`.  If the latter is xterm, or some derivative (e.g. `xterm-256color`), then Vim infers that the terminal supports the bracketed paste mode, and enables it automatically for you.  Otherwise, it doesn't, and you have to do it manually.  You could "fix" the issue by resetting `$TERM` to `xterm` or some derivative, but – FWIW – I wouldn't do that.  That would mean lying to all applications running in the terminal by telling them that the latter supports anything xterm supports, which might not be always true.

**Comment by claireanlage** [comment]
I see. This can be closed by all means then.

**Comment by chrisbra** [comment]
Yes unfortunately this is expected, because vim cannot detect, that the input comes from the clipboard.

Therefore either paste directly from the clipboard by using the clipboard register or make use of the pastemode toggle which disables all the input post processing but is just a work around, that works surprisingly well.

And with modern terminals you can also make use of bracketed paste mode.
