### ISSUE TITLE
Vim9: E611: Using a Special as a Number

### ISSUE THREAD

**Issue by bfrg** [vim/vim#6737]
**Describe the bug**
There are still some cases left where Vim emits `E611: Using a Special as a Number`.

**To Reproduce**
1. Run `vim --clean -S test.vim`, with
   ```vim
   vim9script
   def Test(): list<dict<any>>
       return expand('~')->readdirex({e -> e.name[0] !=# '.'})
   enddef
   Test()
   ```
2. Result:
   ```
   E611: Using a Special as a Number
   ```

Note: Using `defcompile` didn't report the error.

**Environment**
Vim version `8.2.1483`

**Comment by brammool** [comment]
> **Describe the bug**
> There are still some cases left where Vim emits `E611: Using a Special
> as a Number`.

Yes, please keep reporting them.  Finding them in the code is quite
hard.

> **To Reproduce**
> 1. Run `vim --clean -S test.vim`, with
>    ```vim
>    vim9script
>    def Test(): list<dict<any>>
>        return expand('~')->readdirex({e -> e.name[0] !=# '.'})
>    enddef
>    Test()
>    ```
> 2. Result:
>    ```
>    E611: Using a Special as a Number
>    ```
> 
> Note: Using `defcompile` didn't report the error.

The value is checked at runtime.

This one is tricky, since the value -1 is also valid.  Thus it's both a
number and bool at the same time.

-- 
hundred-and-one symptoms of being an internet addict:
239. You think "surfing" is something you do on dry land.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfrg** [comment]
Thank you for the quick fix.

I completely forgot to check the related function `readdir()`. Unfortunately, the error still appears in `8.2.1485`:
```vim
def Test(): list<string>
    return expand('~')->readdir({e -> e[0] !=# '.'})
enddef
```

**Comment by brammool** [comment]
> Thank you for the quick fix.
> 
> I completely forgot to check the related function `readdir()`. Unfortunately, the error still appears in `8.2.1485`:
> ```vim
> def Test(): list<string>
>     return expand('~')->readdir({e -> e[0] !=# '.'})
> enddef
> ```

They have a lot in common, but two different implementations.
Let's merge them so that they use the same logic.

-- 
hundred-and-one symptoms of being an internet addict:
242. You turn down a better-paying job because it doesn't come with
     a free e-mail account.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
