### ISSUE TITLE
Joining more lines than in buffer

### ISSUE THREAD

**Issue by leahneukirchen** [vim/vim#677]
Executing `10J` in a buffer with less than 10 lines results in doing nothing.

In `ex-vi`, `nvi` and `busybox vi`, instead it joins the remaining lines of the files. (In `vile`, it says `motion failed`.)

POSIX says "This command shall be equivalent to the ex join command", but above editors actually fail with a bigger range in ex mode.

So, I guess vim is POSIX-conformant, but it would be nice to have the alternative behavior (perhaps optional), since it seems to be more consistent with `10dd` or `10cc` etc.

**Comment by brammool** [comment]
Christian Neukirchen wrote:

> Executing `10J` in a buffer with less than 10 lines results in doing nothing.
> 
> In `ex-vi`, `nvi` and `busybox vi`, instead it joins the remaining lines of the files. (In `vile`, it says `motion failed`.)
> 
> POSIX says "This command shall be equivalent to the ex join command", but above editors actually fail with a bigger range in ex mode.
> 
> So, I guess vim is POSIX-conformant, but it would be nice to have the
> alternative behavior (perhaps optional), since it seems to be more
> consistent with `10dd` or `10cc` etc.

Yeah, I agree that "10J" failing is not useful.  I also don't think
anyone relies on the failure.  Let me just change it, so that it's
consistent with "10dd" not failing.

## 

The goal of science is to build better mousetraps.
The goal of nature is to build better mice.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
