### ISSUE TITLE
Vim9: error when using bufname('%')

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6807]
**Describe the bug**

In Vim9 script, we cannot evaluate `bufname('%')` to get the name of the current buffer.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        bufname('%')
    EOF
    )

`E1030` is raised:

    E1030: Using a String as a Number

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1537
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: XTerm(358)

**Additional context**

Regression introduced in [8.2.1465](https://github.com/vim/vim/releases/tag/v8.2.1465).

---

The issue persists in a `:def` function:
```vim
vim9script
def Func()
    bufname('%')
enddef
Func()
```
    E1030: Using a String as a Number

---

As a workaround, we can omit the string argument:
```vim
vim9script
bufname()
```
But `bufname()` can accept an arbitrary string, including `'#'` (for the alternate buffer name); the workaround can't help when the string is not `'%'`.

---

The issue disappears in Vim script legacy:
```vim
eval bufname('%')
```

**Comment by lacygoill** [comment]
Here is a failing test:
```vim
vim9script
def Test_bufname()
  e somefile
  let name = bufname()
  assert_equal(name, bufname('%'))
  bw! somefile
enddef
Test_bufname()
```

**Comment by lacygoill** [comment]
There are at least 44 other functions with similar issues.  Do I post them all here, or do I open one issue per function?

**Comment by brammool** [comment]
> There are at least 20 other functions with similar issues.  Do I post
> them all here, or do I open one issue per function?

Please open separate issues, perhaps grouped for similar functions.
If you write the example in the form of a test, that makes it easier for
me.

Changing the rules for what conversions are allowed is likely to require
fixes in many places.  Especially using a string as a number, which
previously would automatically convert (resulting in zero if the string
doesn't start with a digit).

-- 
Even got a Datapoint 3600(?) with a DD50 connector instead of the
usual DB25...  what a nightmare trying to figure out the pinout
for *that* with no spex...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
