### ISSUE TITLE
Use the highlight of `debugPC` even if the cursor is not in the source-code window

### ISSUE THREAD

**Issue by YvesZHI** [vim/vim#6812]
I'm using Vim 8.2 with its feature `:Termdebug` to debug my C++ code.

It works as expected. But I'm thinking if it is possible to use the setting of `hi debugPC` even if the cursor is not in the source-code window. Because for now, if the cursor is NOT in the source-code window, the setting of highlight of the source-code window seems to become the setting of `hi CursorLine`, instead of `hi debugPC`.

The cursor is in the GDB window:
![image](https://user-images.githubusercontent.com/27804279/91704883-c169e180-ebae-11ea-8e3b-13b302666909.png)

You can see that at the bottom right cornor, there is the source-code window, I set a breakpoint at the line 29, and the line 30 is highlighted with the setting of `CursorLine` because the program is staying at the line 30.

If we move the cursor to the source-code window:
![image](https://user-images.githubusercontent.com/27804279/91705133-245b7880-ebaf-11ea-958f-a6fdc78e0338.png)

Now the setting of `debugPC` works.

In my opinion, if the setting of `debugPC` can be used even if we are working in the GDB window, it would be more helpful.

**Comment by brammool** [comment]
The cursorline highlighting overrules the sign highlighting, because otherwise it might be hard to to see the cursor line.
But in this case the cursor is always in the same line as the sign until the cursor is moved.
Maybe we can do something with the sign priority.
As a workaround you can change 'cursorlineopt' to only highlight the line number.
