### ISSUE TITLE
different behavior of vim when <silent> is used in mappings for command line mode

### ISSUE THREAD

**Issue by jdhao** [vim/vim#6832]
**Describe the bug**

Adding `<silent>` to command line mappings will cause issues.

**To Reproduce**

+ Use the following config:

```
set nocompatible
cnoremap <silent> <C-P> <C-R>"
```

to open vim: `vim -u minimal.vim test.txt`

+ Copy and line with `yy`
+ Press `:` to activate command mode. Press shortcut `<C-P>`.

Actual behavior: the copied text is not pasted. After pressing a character, the copied text is shown on the command line.

**Expected behavior**

The copied text is pasted immediately when I press `<c-p>`.

**Environment (please complete the following information):**
 - Vim version: vim 8.0, included patches: 1-1453
 - OS: Ubuntun 18.04
 - Terminal: zoc terminal. 

**Additional info**

If we remove the `<silent>` argument from the mapping, the copied text appears immediately after pressing `<C-P>`.

**Comment by lacygoill** [comment]
I think it's working as intended.  [I wrote about it a long time ago](https://github.com/lacygoill/wiki/blob/master/vim/mapping.md#which-mappings-should-never-be-defined-with-silent).

`<silent>` is useful to prevent Vim from printing an Ex command which is run after entering the command-line from the rhs of a mapping:

            v------v
        nno <silent> cd :call Func()<cr>
        fu Func()
            " ...
        endfu

To achieve this goal, I think Vim doesn't redraw the command-line, which probably explains the behavior you observe.

Besides, `<silent>` is useless for a command-line mode mapping, because you can't enter the command-line from it; you're necessarily *already* on the command-line.

However, I agree that the behavior might seem unexpected at first glance; maybe the documentation could be improved, and warn the user about using `<silent>` for a command-line mapping.  There is this excerpt:
https://github.com/vim/vim/blob/2f1228463aa9ff62814f9732561b1849e5f01f75/runtime/doc/map.txt#L210-L211

But it's about abbreviations, not mappings.

**Comment by chrisbra** [comment]
I believe the whole purpose of the `<silent>` flag is to prevent that the mapping is eschoed in the commnand line. So that is what is does and works as intended. Try adding a `<c-l>` flag to your mapping to force a redraw.
