### ISSUE TITLE
Terminal colors g:terminal_ansi_colors ingored

### ISSUE THREAD

**Issue by noscript** [vim/vim#6846]
**Describe the bug**
`g:terminal_ansi_colors` 9-16 colors ignored.

**To Reproduce**
1. Save the text file [colortable16.txt](https://github.com/vim/vim/files/5168059/colortable16.txt)
2. Run VIM:
```sh
vim -g -u NONE +'let g:terminal_ansi_colors=["#2E3436","#B80000","#4E9A06","#C4A000","#3465A4","#75507B","#06989A","#C8CCC5","#555753","#FF3333","#8AE234","#FCE94F","#729FCF","#AD7FA8","#34E2E2","#FFFFFD"]' +'term bash -c "cat ~/colortable16.txt"'
```
**Expected behavior**
![2020 09 03_13:56:09](https://user-images.githubusercontent.com/717109/92106855-9c16e680-eded-11ea-8790-49514ae68693.png)

**Actual behavior**
![2020 09 03_13:56:44](https://user-images.githubusercontent.com/717109/92106869-a1743100-eded-11ea-98e3-d45a72965322.png)

**Environment:**
 - Vim 8.2.1578
 - OS: Ubuntu 18.04
 - Terminal: GUI

**Additional context**
Culprit commit: acc770a10f65107131473ea2ab4ae5d429dfe172

**Comment by brammool** [comment]
That colortable16.txt file relies on the bold flag using another color, not just make the text bold.
This has always been a weird mechanism, and should only be used for terminals that only support 8 color codes.
Since the GUI can perfectly well produce lots of colors, using this bold-bright mechanism is not needed.
It's a bit strange that libvterm actually picks the other color index when setting the bold-bright flag, 

One can argue for either mechanism to be correct.  Therefore I'm just going to leave it as it is.
