### ISSUE TITLE
internal error when trying to use a script-local function as a popup filter without function()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#6902]
**Describe the bug**

Trying to use a script-local function as a popup filter without `function()` might raise an internal error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        call popup_create([''], #{filter: 's:filter'})
        call feedkeys('j')
    EOF
    )

`E120` is raised:

    E120: Using <SID> not in a script context: s:filter

This is expected.

`E685` is also raised:

    E685: Internal error: tv_get_number(UNKNOWN)

This is not expected.

**Expected behavior**

No internal error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-1634
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(359)

**Additional context**

I tried to get a backtrace by recompiling with `-DABORT_ON_INTERNAL_ERROR`, but Vim doesn't crash when the internal error is raised.  So I have no core from which I could extract a backtrace.

**Comment by lacygoill** [comment]
It didn't happen on 8.1.1364; it could be a regression; I'm going to bisect.

**Comment by lacygoill** [comment]
Ah no, at that time `popup_create()` didn't exist yet.  Popup filters were implemented in 8.1.1441.  At that time, an internal error was already raised, so it's not a regression.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> Trying to use a script-local function as a popup filter without `function()` might raise an internal error.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         call popup_create([''], #{filter: 's:filter'})
>         call feedkeys('j')
>     EOF
>     )
> 
> `E120` is raised:
> 
>     E120: Using <SID> not in a script context: s:filter
> 
> This is expected.
> 
> `E685` is also raised:
> 
>     E685: Internal error: tv_get_number(UNKNOWN)
> 
> This is not expected.
> 
> **Expected behavior**
> 
> No internal error is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-1634
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(359)
> 
> **Additional context**
> 
> I tried to get a backtrace by recompiling with
> `-DABORT_ON_INTERNAL_ERROR`, but Vim doesn't crash when the internal
> error is raised.  So I have no core from which I could extract a
> backtrace.

It intentionally does not abort on this error.


While reproducing this, I also notice that Vim can get stuck here.
Either because the filter function can't be found or because it causes
an error.  I'll make it that when calling the function fails the popup
is closed.  And when it causes a few errors then it is also closed.
I'll tolerate a few errors, to avoid any tiny mistake causes the popup
to close.

-- 
If cars evolved at the same rate as computers have, they'd cost five euro, 
run for a year on a couple of liters of petrol, and explode once a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
