### ISSUE TITLE
Downloading German spell suggestion file fails

### ISSUE THREAD

**Issue by AlxHnr** [vim/vim#6963]
**Describe the bug**

When enabling `spell` and setting the language to `de`, the download of the `.sug` file fails. It works with other languages, like french (`fr`) and spanish (`es`).

**To Reproduce**
Detailed steps to reproduce the behavior:

Can't be reproduced with `vim --clean` because it doesn't load all the spell plugins. I had no success with tweaking `rtp`, so I installed Vim from master (8b51b7f).

Start Vim and enter the following commands:

```vim
:setl spell spelllang=de
```

Answer `yes`, `1` and all the other questions.

Output:

```
spellfile#LoadFile(): There is no writable spell directory.
Shall I create /home/user/.vim/spell

Cannot find spell file for "de" in utf-8
Do you want me to try downloading it?

Downloading de.utf-8.spl...
"/tmp/v62mxyn/0.spl" [noeol] 5845L, 2683940B
In which directory do you want to write the file:
1. /home/user/.vim/spell
"~/.vim/spell/de.utf-8.spl" [New] 5845L, 2683941B written
Do you want me to try getting the .sug file?
This will improve making suggestions for spelling mistakes,
but it uses quite a bit of memory.

5842 fewer lines
Downloading de.utf-8.sug...
"/tmp/v62mxyn/0.sug" [noeol] 8932L, 4147728B
Sorry, downloading failed
Press ENTER or type command to continue
```

**Expected behavior**

German suggestion file gets downloaded properly.

**Screenshots**

See log above.

**Environment (please complete the following information):**
 - Tested Versions: `8.2 1-1551`, `8.2 1-1690` (current master). Can be reproduced with Neovim 0.4.4, and 0.5 nightly.
 - OS: Fedora 32 (Thirty Two)
 - Terminal: GNOME Terminal 3.36.1.1 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

**Additional context**

Works with other languages.

**Comment by chrisbra** [comment]
You can always download the file manually:

https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.sug

> "/tmp/v62mxyn/0.sug" [noeol] 8932L, 4147728B
> Sorry, downloading failed

It looks like the downloading actually succeeds. Hm, according to spellfile.vim

https://github.com/vim/vim/blob/8b51b7f0f17af149a8ce76e805050977857f9e50/runtime/autoload/spellfile.vim#L132-L137


This fails, because the second line of the buffer does not contain the pattern `VIMsug`. Can you check the downloaded file?

**Comment by AlxHnr** [comment]
The download script leaves no `.sug` file in my spell dir. Downloading it manually seems to work, but only on short words. On longer words the `z=` command can take up to 30 seconds. Example for the word _Vorstandsvorsitzender_:

```vim
:setl spell spelllang=de
iVorstandsvorsitzender<esc>z=
```

Using an older version of this `.sug` file ([see here](https://github.com/AlxHnr/vim-spell-files/tree/master/spell)) is much faster and takes less than a second.

**Comment by chrisbra** [comment]
If you have a look at the log message:

> "/tmp/v62mxyn/0.sug" [noeol] 8932L, 4147728B
> Sorry, downloading failed

I would guess, that the file is still available under /tmp/v62mxyn/0.sug (as long as you did not close vim).

> Using an older version of this .sug file (see here) is much faster and takes less than a second.

So is there a difference between those files? Is just perhaps just bigger so Vim needs to search more?

**Comment by AlxHnr** [comment]
The newer, slower suggestion file is suprisingly smaller (4.0 Mb) compared the 7.7 Mb of the older, faster file. Comparing the structure of these binary files is outside my expertise. Maybe the bigger file has some precomputed index?

**Comment by chrisbra** [comment]
What about the `VIMsug` pattern?

**Comment by AlxHnr** [comment]
Seems to be there. The first 11 bytes are identical in both files. However the working, older file contains a newline somewhere after the `VIMsug`. Both files can be grepped for `VIMsug` successfully.

**Comment by brammool** [comment]
> The download script leaves no `.sug` file in my spell dir. Downloading
> it manually seems to work, but only on short words. On longer words
> the `z=` command can take up to 30 seconds. Example for the word
> _Vorstandsvorsitzender_:
> 
> ```vim
> :setl spell spelllang=de
> iVorstandsvorsitzenderz=
> ```
> 
> Using an older version of this `.sug` file ([see
> here](https://github.com/AlxHnr/vim-spell-files/tree/master/spell)) is
> much faster and takes less than a second.

The newer German dictionary uses compounding, words made out of
concatenation of other words.  For long words the algorithm takes a long
time to score all the alternatives.  This can be improved, but it
requires for someone to dive into the code.  And first measure the
quality of the suggestions, since we don't want the improved performance
to result in much worse suggestions.  When working on this I was unable
to find a way to judge the quality of German suggestions, such
statistics were only available for English, thus that's what the
algorithm is tuned for.

My own experience is that the German word suggestions are quite good,
but can indeed be very slow.

-- 
(letter from Mark to Mike, about the film's probable certificate)
      For an 'A' we would have to: Lose as many shits as possible; Take Jesus
      Christ out, if possible; Loose "I fart in your general direction"; Lose
      "the oral sex"; Lose "oh, fuck off"; Lose "We make castanets out of your
      testicles"
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
so the slowness is expected in order to be more precise.

I guess the only remaining problem is then, why does the initial download using spellfile.vim fail for you

**Comment by rkta** [comment]
I looked into this a bit today.

The file does not remain in /tmp, it seems to be removed inside the
Nread function. The file is downloaded though.

Removing the `if getline(2) =~ 'VIMsug'` in line 132 leads to a written
file which is corrupted.

In this corrupted file `VIMsug` is not in line 1, but instead in line 4.

After line 128 `g/^/d` the buffer still contains 3 lines. Changing this
line to `g/$/d` fixes the problem.

This is obviously not a real fix, but may help find the root cause.
I'm willing to look deeper into this issue, but I'm not sure I'm able to
do so. I definitely need a push in the right direction from here.

**Comment by rkta** [comment]
Some more info:

The remaining lines from de.utf-8.spl are lines 3769, 4794 and 5571.
Looking at them with xxd shows that all three start with `0xd6`.

Here is the output from xxd (obtained by `:%!xxd` from the attached file):

```
00000000: d6ae 7501 6301 6801 0106 59d0 7201 0101  ..u.c.h...Y.r...
00000010: 73ab c301 6102 6e01 00e5 ac75 0101 076c  s...a.n....u...l
00000020: c067 0401 0865 c261 6975 c301 6e01 0102  .g...e.aiu..n...
00000030: 5919 6e01 0101 56bd 7401 0108 65d6 a401  Y.n...V.t...e...
00000040: 6301 6803 0103 03db 6901 0044 a26f 7201  c.h.....i..D.or.
00000050: 6101 7501 0100 e5ac 6202 75c3 0766 0101  a.u.....b.u..f..
00000060: 9857 6768 0103 792e 6b72 737a 0201 0106  .Wgh..y.krsz....
00000070: ba61 6c01 6901 0104 3b36 6501 6101 0103  .al.i...;6e.a...
00000080: 8c37 6e02 0108 66a9 6901 0ad6 a26f 0301  .7n...f.i....o..
00000090: 066d c761 0106 3a83 6f01 064b 2ec3 0175  .m.a..:.o..K...u
000000a0: 016b 0201 0021 816f 0102 ed65 c303 a401  .k...!.o...e....
000000b0: 00eb 17b6 bc01 6e01 6703 6501 0004 0973  ......n.g.e....s
000000c0: 0100 06fa 740a d6a8 7001 003e 9a73 0101  ....t...p..>.s..
000000d0: 00c5 d061 0175 0501 01f5 8262 0102 f115  ...a.u.....b....
000000e0: 6601 015b 5768 0100 95dc 7001 003e ce73  f..[Wh....p..>.s
000000f0: 036b 0100 2288 7301 046c 6974 0201 0d08  .k..".s..lit....
00000100: cc61 0100 120e 6508 6101 0b01 de66 696c  .a....e.a....fil
00000110: 0103 1835 6f72 75c3 0568 6c73 0100 3005  ...5oru..hls..0.
00000120: 7801 0014 7cc3 0172 0201 000a            x...|..r....
```

[remaining_lines.zip](https://github.com/vim/vim/files/5720979/remaining_lines.zip)

**Comment by chrisbra** [comment]
Thanks for looking into this. Can you provide the corrupted downloaded file? What command has been used to download the file? Does it change if you configure it to use `curl`, `wget`, etc?

Thanks.

**Comment by rkta** [comment]
It think you get me wrong. The Problem is not the download. The file was
downloaded with wget. That all went fine.

`runtime/autoload/spellfile.vim:128` tries to delete the complete buffer,
this fails!

Three lines stay in the buffer, the downloaded file is appended. So the
corrupted file contains three lines from de.utf-8.spl as the first three
lines and the complete content from de.utf-8.sug.

Changing line 128 `g/^/d` to `g/$/d` leads to a valid suggestions file.

You can also just open `de.utf-8.spl` in vim and do `:g!/^/p`.

If still needed I will provide the broken file later (not on the right
machine now).

**Comment by chrisbra** [comment]
I don't know why `:g/^/d` would fail. After all, `^` should match every line.

Would the following patch also work?

```patch
diff --git a/runtime/autoload/spellfile.vim b/runtime/autoload/spellfile.vim
index 6f9b1e0e0..557364fc0 100644
--- a/runtime/autoload/spellfile.vim
+++ b/runtime/autoload/spellfile.vim
@@ -125,7 +125,7 @@ function! spellfile#LoadFile(lang)
       let msg .= "This will improve making suggestions for spelling mistakes,\n"
       let msg .= "but it uses quite a bit of memory."
       if confirm(msg, "&No\n&Yes") == 2
-       g/^/d
+       sil %d_
        let fname = substitute(fname, '\.spl$', '.sug', '')
        echo 'Downloading ' . fname . '...'
        call spellfile#Nread(fname)
```

**Comment by rkta** [comment]
On Sun, Dec 20, 2020 at 08:28:45AM -0800, Christian Brabandt wrote:
> I don't know why `:g/^/d` would fail. After all, `^` should match every line.
That's the bug, I guess ;)

> Would the following patch also work?
Yes.

**Comment by chrisbra** [comment]
ping @brammool  for applying that patch.

**Comment by brammool** [comment]
Why would "g/^/d" do something different than "sil %d_" ?
Is it the "silent" or using the "_" register?  I doubt that.
I wonder what the real problem is.

**Comment by chrisbra** [comment]
I have no idea why the `:g` command did not work. That was @rkta's findings. FWIW: the `:g/^/d` worked for me with the provided `remaining_lines` file from [this comment](https://github.com/vim/vim/issues/6963#issuecomment-748608481)

**Comment by rkta** [comment]
On Sun, Dec 20, 2020 at 11:46:56PM -0800, Christian Brabandt wrote:
> FWIW: the `:g/^/d` worked for me with the provided
> `remaining_lines` file from [this
> comment](https://github.com/vim/vim/issues/6963#issuecomment-748608481)

This bug is related to vim running in binary mode.

This doesn't work and leads to a buffer containing three lines:
(binary mode - original code)

wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
vim -b -c ':g/^/d' -

This works and leads to an empty buffer:
(*no* binary mode - original code)

wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
vim -c ':g/^/d' -

This works:
(binary mode - match end of line)

wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
vim -b -c ':g/$/d' -

This works:
(binary mode - using :delete)

wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
vim -b -c ':sil %d_' -

**Comment by brammool** [comment]
> On Sun, Dec 20, 2020 at 11:46:56PM -0800, Christian Brabandt wrote:
> > FWIW: the `:g/^/d` worked for me with the provided
> > `remaining_lines` file from [this
> > comment](https://github.com/vim/vim/issues/6963#issuecomment-748608481)
> 
> This bug is related to vim running in binary mode.
> 
> This doesn't work and leads to a buffer containing three lines:
> (binary mode - original code)
> ```
> wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
> vim -b -c ':g/^/d' -
> ```
> 
> This works and leads to an empty buffer:
> (*no* binary mode - original code)
> ```
> wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
> vim -c ':g/^/d' -
> ```
> 
> This works:
> (binary mode - match end of line)
> ```
> wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
> vim -b -c ':g/$/d' -
> ```
> 
> This works:
> (binary mode - using :delete)
> ```
> wget -O - https://ftp.nluug.nl/pub/vim/runtime/spell/de.utf-8.spl | \
> vim -b -c ':sil %d_' -
> ```

Thanks for providing this info.  I now see that the problem is that the
remaining lines start with a composing character and "^" does not match
on that.

I think matching a composing character at the start of the line should
be OK.  Let's fix that in the regexp engine.

-- 
An alien life briefly visits earth.  Just before departing it leaves a
message in the dust on the back of a white van.  The world is shocked
and wants to know what it means.  After months of studies the worlds
best linguistic scientists are able to decipher the message: "Wash me!".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
