### ISSUE TITLE
Problems with mapping <C-SPACE>

### ISSUE THREAD

**Issue by arekmd** [vim/vim#7105]
Hi,

I'm trying to recreate my neovim config in vim.

I'm using `<C-SPACE> `to exit insert or terminal mode, and select next window in normal mode:

```
:noremap·<silent>·<C-SPACE>·<C-W><C-W>↲
:inoremap·<silent>·<C-SPACE>·<ESC>↲
:tnoremap·<C-SPACE>·<C-\><C-N>↲

```
While `<C-SPACE>` mapping works in insert-mode. It does not in normal and terminal modes.

Im using vim v8.2.1816 

 
```
EDIT: added quotes

**Comment by lacygoill** [comment]
Not sure to understand the issue, but if you want to map something to `<c-space>`, and it doesn't work by default, then press `<c-v>` followed by `<c-space>` in insert mode or on Vim's command-line, and read what is inserted.

For example, in st inside tmux, if I press `<c-v><c-space>`, Vim inserts `^@`.  So, if I want to map something to `<c-space>`, I can use `<c-@>`:

    nnoremap <c-@> :echo "c-space was hit"<cr>

Obviously, this is not perfect, since other chords might produce the same key (like `<c-@>` and `<c-space>`), and you might want to use them for different purposes.

If that's an issue, consider using a terminal which supports the modifyOtherKeys feature, like xterm, and maybe iterm.  If you do, you can use `<c-space>` directly, and without clobbering another chord:

    vim -Nu NONE +'nno <c-space> :echo "c-space was hit"<cr>'

---

Note that with the modifyOtherKeys feature, you can map a lot more chords, like `<c-;>`

    vim -Nu NONE +'nno <c-;> :echo "c-; was hit"<cr>'

Which did not seem to be possible in Neovim the last time I checked.

Also, if you need to press another modifier (like Shift) to produce a semicolon, you might need to include it explicitly:

    vim -Nu NONE +'nno <c-s-;> :echo "c-; was hit"<cr>'
                          ^^

**Comment by arekmd** [comment]
I'm using Alacritty, which do not support modifyOtherKeys at the moment. But mapping `<C-@>` fixed my problem. 

Thx for your help @lacygoill
