### ISSUE TITLE
Vim9: Inline lambda in lambda does not capture variables out of outer lambda

### ISSUE THREAD

**Issue by Bakudankun** [vim/vim#7150]
**Describe the bug**
Inline lambda in lambda does not correctly capture variables out of outer lambda.

**To Reproduce**
1. Run `vim --clean`
2. `:source` next script

```vim
func TestFunc()
  let outer = 42
  return {-> {-> outer}()}()
endfunc

def TestDef(): number
  var outer = 42
  return {-> {-> outer}()}()
enddef

echo TestFunc()
" => 42
echo TestDef()
" => 1
```

3. See the output

**Expected behavior**
The inner lambda captures variables out of outer lambda.

**Environment**
 - Vim version 8.1.1855
 - OS: Windows 10 Pro 2004
 - Terminal: Windows Terminal

**Additional context**
This does not occur if lambdas are defined separately.

**Comment by brammool** [comment]
This might be a bit difficult to make work.  I'll add it in the todo list, not sure if we can make this work.

**Comment by lacygoill** [comment]
> This might be a bit difficult to make work. I'll add it in the todo list, not sure if we can make this work.

I'm facing the same issue in a plugin.  If it can't be made to work, maybe Vim should raise an error.  Right now, `outer` is assumed to be `1` regardless of the value in the outer scope:
```vim
vim9script
def Func()
  var outer = 123
  echo {-> {-> outer}()}()
enddef
Func()
```
    1

Maybe `E1001` could be used:

    E1001: Variable not found: outer

If no error is raised, it can make debugging more difficult.  I've lost quite some time trying to understand why my text properties were not correctly applied in a popup window.

---

As mentioned in the original post, the issue disappears when the definition of the nested lambda reference is moved outside the outer lambda:
```vim
vim9script
def Func()
    var outer = 123
    var Lambda = {-> outer}
    echo {-> Lambda()}()
enddef
Func()
```
    123

However, that's not always possible.  Here is the code where I found the issue:
```vim
var lastlnum = line('$', menu_winid)
...
eval text
    ->map({i, v -> v.props->map({_, w -> call('prop_add',
        [lastlnum + i + 1, w.col] + [extend(w, #{bufnr: menu_buf})])})})
```

I can't move the definition of the nested lambda:
```vim
var lastlnum = line('$', menu_winid)
...
var Lambda = {_, w -> call('prop_add', [lastlnum + i + 1, w.col] + [extend(w, #{bufnr: menu_buf})])}
eval text->map({i, v -> v.props->map(Lambda)})
```
It would raise an error:

    E1001: Variable not found: i

That's because, here, the inner lambda refers to an argument of the outer lambda.
There might be a workaround, but I've settled on a `for` loop:
```vim
var i = 0
for d in text
    eval d.props->map({_, w -> call('prop_add',
            [lastlnum + i + 1, w.col] + [extend(w, #{bufnr: menu_buf})])})
    i += 1
endfor
```
In Vim script legacy, I try to avoid `for` loops as much as possible because they are slower than `map()`.  I thought that maybe the same was true in Vim9.  But after some quick tests, it doesn't seem to be the case.  In fact, on huge lists (10^5, 10^6, ...), it seems that a `for` loop is faster.  Besides, it makes the code more readable.

I don't think that a `for` loop can be used as a general workaround, but I doubt I'll need a nested lambda outside of functions like `map()` and `filter()`.
