### ISSUE TITLE
Vim9: var declared in a function is not local? (and other issues...)

### ISSUE THREAD

**Issue by alexaschee** [vim/vim#7170]
**Describe the bug**
In a function def block, variable name can't be identical with variable outside the block

**To Reproduce**

    vim9script

    var lst: list<number> = [0] ###

    def Count_this(str: string): number
        var lst: list<number> = [0]
        var cmd = ':%s/' .. str .. '/\=map(lst, "v:val + 1")/gen'
        :sile exec cmd
        return lst[0]
    enddef

    :echo ':: Found: ' .. Count_this('something')

Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit this script
3. :so %
4. E1054 is raised

       E1054: Variable already declared in the script: lst

**Expected behavior**
Just a clean echo:

    :: Found: 1

**Additional context**
1. If delete the line `var lst: list<number> = [0] ###` outside the `def`, then:

       E121: Undefined variable: lst
       E116: Invalid arguments for function map(lst, "v:val + 1")

2. If delete  the line `var lst: list<number> = [0]` inside the `def`, then: 

       1 match on 1 line
       :: Found: 1

but, is `1 match on 1 line` supposed to be shown here? `:sile` not working?

**Comment by lacygoill** [comment]
> E1054 is raised
>
>     E1054: Variable already declared in the script: lst

Anything declared at the script level without an explicit scope is implicitly local to the script.  So, this creates a script-local `lst` variable:

    var lst: list<number> = [0] ###

Similarly, anything declared in a `:def` function without an explicit scope is implicitly local to the function.  So this creates a function-local `lst` variable:

    var lst: list<number> = [0]

But Vim does not allow a variable name to be shadowed:

https://github.com/vim/vim/blob/334a8b4bde55e1095533f70616ac1e6ec337c62c/runtime/doc/vim9.txt#L240-L241

Hence the error that you observe.

---

> If delete the line var lst: list<number> = [0] ### outside the def, then:
>
>     E121: Undefined variable: lst
>     E116: Invalid arguments for function map(lst, "v:val + 1")

That's because local variables are not visible to string evaluation:

https://github.com/vim/vim/blob/334a8b4bde55e1095533f70616ac1e6ec337c62c/runtime/doc/vim9.txt#L662-L673

As a workaround, try using a lambda which is more readable and faster in a `:def` function (but slower at the script level).

That is, instead of writing this:

    var cmd = ':%s/' .. str .. '/\=map(lst, "v:val + 1")/gen'
                                            ^---------^
                                                 ✘

Write this:

    var cmd = ':%s/' .. str .. '/\=map(lst, {_, v -> v + 1})/gen'
                                            ^-------------^
                                                   ✔

---

> If delete the line var lst: list<number> = [0] inside the def, then:
>
>     1 match on 1 line
>     :: Found: 1
>
> but, is 1 match on 1 line supposed to be shown here? :sile not working?

Command modifiers are not implemented yet.  There is an [open issue](https://github.com/vim/vim/issues/6530) about that, and a todo item:

https://github.com/vim/vim/blob/334a8b4bde55e1095533f70616ac1e6ec337c62c/runtime/doc/todo.txt#L132

In the meantime, try to move `:silent` closer to the command.  That is, instead of writing this:

    var cmd = ':%s/' .. str .. '/\=map(lst, "v:val + 1")/gen'
    :sile exec cmd
     ^--^
      ✘

Write this:

                  ✔
                v----v
    var cmd = ':silent %s/' .. str .. '/\=map(lst, "v:val + 1")/gen'
    exe cmd

**Comment by lacygoill** [comment]
> As a workaround, try using a lambda which is more readable and faster in a :def function (but slower at the script level).

Ah no, in your case, switching to a lambda won't be enough because of the `:exe`.  Let me think of another workaround...

**Comment by lacygoill** [comment]
Try this:
```vim
vim9script
var lst: list<number> = [0] ###

def Count_this(str: string): number
    var cmd = ':silent %s/' .. str .. '/\=map(lst, {_, v -> v + 1})/gen'
    exe cmd
    return lst[0]
enddef

:echo ':: Found: ' .. Count_this('something')
```

**Comment by brammool** [comment]
As mentioned, in Vim9 script shadowing is disallowed.  This is to avoid mistakes.  Since the declarations are in one file, it should always be possible to rename one of the variables.  Shadowing global variables, which can be defined and unlet any time, is allowed.  But since you need to use the g: prefix this isn't real shadowing.

**Comment by alexaschee** [comment]
@lacygoill Thank you for your comments. Actually, I've thought of your workaround, too. This why I thought it was not a solution:

    vim9script
    var lst: list<number> = [0] ###

    def Count_this(str: string): number
        var cmd = ':silent %s/' .. str .. '/\=map(lst, {_, v -> v + 1})/gen'
        exe cmd
        return lst[0]
    enddef

    # lst[0] = 0
    :echo ':: Found: ' .. Count_this('something')
    # lst[0] = 0
    :echo ':: Found: ' .. Count_this('something')
    # lst[0] = 0
    :echo ':: Found: ' .. Count_this('something')
    # lst[0] = 0
    :echo ':: Found: ' .. Count_this('something')

lst[0] must to be set to 0 every time before Count_this is called. That's clumsy.

**Comment by lacygoill** [comment]
> lst[0] must to be set to 0 every time before Count_this is called. That's clumsy.

I'm not sure what you find clumsy, but you would just need to add one line in the function to reset the counter:

    vim9script
    var lst: list<number>

    def Count_this(str: string): number
        lst = [0]
        exe ':silent %s/' .. str .. '/\=map(lst, {_, v -> v + 1})/gen'
        return lst[0]
    enddef

If what you find clumsy is the usage of a script-local variable, then try this instead:

    vim9script

    def Count_this(str: string): number
        var lst = [0]
        getline(1, '$')
            ->join("\n")
            ->substitute(str, {-> map(lst, {_, v -> v + 1})->string()}, 'gen')
        return lst[0]
    enddef

It doesn't rely on a script-local variable, and it's about twice as fast as your original code.

Note that one could make the argument that using a substitution command to get the number of occurrences of a pattern is a hack in itself, and that it's clumsy.  A less hacky way to get the number of occurrences would be to use the [`searchcount()`](https://vimhelp.org/eval.txt.html#searchcount()) function introduced in [8.2.0877](https://github.com/vim/vim/releases/tag/v8.2.0877).

    def Count_this(str: string): number
        var search_save = @/
        @/ = str
        var total = searchcount().total
        @/ = search_save
        return total
    enddef

    echo ':: Found: ' .. Count_this('something')

Which imo is more readable, and even faster than the last snippet.

**Comment by lacygoill** [comment]
I forgot that `searchcount()` accepted an arbitrary pattern, so there's no need to temporarily mutate the search register.  The last snippet can be simplified into:

    vim9script

    def Count_this(str: string): number
        return searchcount(#{pattern: str}).total
    enddef

    echo ':: Found: ' .. Count_this('something')

**Comment by alexaschee** [comment]
Thanks a lot. That's exactly what I tried to achieve. Been trying to re-write some legacy scripts. Never thought there might be new ready-made functions. Thank you again.
