### ISSUE TITLE
patch 8.2.1636 introduced a critical bug that breaks my plugin LeaderF

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#7178]
**Describe the bug**
$ git bisect bad
6defa7bf0a8935cc44f3dc12e9c87bbb40f190b7 is the first bad commit
commit 6defa7bf0a8935cc44f3dc12e9c87bbb40f190b7
Author: Bram Moolenaar <Bram@vim.org>
Date:   Tue Sep 8 22:06:44 2020 +0200

    patch 8.2.1636: get stuck if a popup filter causes an error
    
    Problem:    Get stuck if a popup filter causes an error.
    Solution:   Check whether the function can be called and does not cause an
                error.  (closes #6902)

:040000 040000 d4ca40a5d8f0905866d61a407e2c5e73866a3595 34738af684951555dafb5e642bf2ee0a63254a5b M	src

I have not succeeded to minimize the steps to reproduce the issue, after this patch, a pressed key won't be discarded even though the the filter return 1.

Could you please find some reasons from the code of this patch? I'll try my best to minimize the steps to reproduce.

**To Reproduce**
Install https://github.com/Yggdroot/LeaderF, e.g., `Plug 'Yggdroot/LeaderF'`

Run command: `Leaderf! file --popup`, then press `o` to open a file.
We can see that after opening the file, a normal mode command `o` is also executed.

but the filter function is:

https://github.com/Yggdroot/LeaderF/blob/860c2d05b9b1acdcb3bf5cc31f1eaed06d7b71ab/autoload/leaderf/File.vim#L60-L166

it returns 1

**Expected behavior**

filter should discard the key if return 1

**Comment by lacygoill** [comment]
> We can see that after opening the file, a normal mode command o is also executed.

I can't reproduce:

    vim -Nu <(cat <<'EOF'
        set rtp-=~/.vim
        set rtp-=~/.vim/after
        set rtp^=/run/user/1000/tmp/LeaderF
        syntax enable
        au VimEnter * Leaderf! file --popup
    EOF
    )

When I press `o`, the selected file is open.  Afterward, pressing `j` correctly makes the cursor move 1 line below.  If `o` had been executed as a normal command, `j` would have been inserted in the buffer.

![gif](https://user-images.githubusercontent.com/8505073/96698282-38d91780-138d-11eb-9d10-9bb3d46514f7.gif)

Which terminal are you using?  What's the value of `TERM`?  Which OS?  Which Vim version?

**Comment by lacygoill** [comment]
> Could you please find some reasons from the code of this patch?

The reason is given in the associated bug report.  An internal error was raised when a filter function couldn't be found or caused an error.  Vim could also get stuck, which required to press `C-c`.  There were also 2 following commits which fixed similar issues:

   - [8.2.1729](https://github.com/vim/vim/releases/tag/v8.2.1729)  endless loop when ":normal" feeds popup window filter
   - [8.2.1732](https://github.com/vim/vim/releases/tag/v8.2.1732)  stuck when win_execute() for a popup causes an error

**Comment by Yggdroot** [comment]
@lacygoill Thanks, you give me the baseline of working well.

I find that it is a conflict with one of my plugins, and I digged it further, I find it's due to one line of code:
```vim
autocmd BufReadPost,BufNewFile * silent! iunmap  <buffer> <tab>
```
please have a try this:
```vim
vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/run/user/1000/tmp/LeaderF
    syntax enable
    autocmd BufReadPost,BufNewFile * silent! iunmap  <buffer> <tab>
    au VimEnter * Leaderf! file --popup
EOF
)
```

**Comment by lacygoill** [comment]
Ok, now I can reproduce.  The issue is triggered by this autocmd:

    au BufReadPost * invalid

It doesn't matter what the autocmd executes, as long it raises an error.

Here is a MWE which does not depend on the plugin:
```vim
call writefile(['some text'], '/tmp/somefile')
au BufReadPost * invalid
fu Filter(winid, key) abort
    if a:key ==# 'o'
        sp /tmp/somefile
        return v:true
    endif
    return popup_filter_menu(a:winid, a:key)
endfu
call popup_create(['TEST'], #{filter: function('Filter')})
call feedkeys("o\r\r", 'nt')
```
We're in insert mode while – I guess – you would expect to be still in normal mode.

I'm not sure this is a bug.  I think the current behavior is documented at `:h popup-filter-errors`:
https://github.com/vim/vim/blob/3da855c8e28140d9f02b1572e445f8d4f977cf64/runtime/doc/popup.txt#L923-L927

In particular, notice this sentence:

> If the filter causes an error then it is assumed to return zero.

I think it means that if an error occurs while the filter is running, the key is not discarded.  I guess you would prefer the key to be discarded.  I agree with you.

**Comment by lacygoill** [comment]
Also, in your case, the error is suppressed by `:silent!`; it's a bit unexpected for the filter to still detect and react to the error.

**Comment by lacygoill** [comment]
Simpler MWE:
```vim
vim9script
def Filter(winid: number, key: string)
    if key == 'o'
        silent! invalid
        return true
    endif
    return popup_filter_menu(winid, key)
enddef
popup_create('TEST', #{filter: Filter})
feedkeys("o\r\r", 'nt')
```

**Comment by lacygoill** [comment]
FWIW, I think I found the same issue while I was working on some plugin.  I first reported the issue here in https://github.com/vim/vim/issues/7156.

In the meantime, I found a second occurrence of this issue (i.e. `<CR>` not discarded by the popup callback); but with one difference: no error is raised.  I haven't had the time to come up with a MWE so I didn't report this second issue.  I suspect the explanation is that I run a command which raises an error from a filetype plugin, but the error is suppressed by `:silent!`.

**Comment by Yggdroot** [comment]
Firstly, it obvious that it is a bug that filter return 0 even though the error is suppressed by `:silent!`.
Secondly, in my opinion, `If the filter causes an error then it is assumed to return zero` is not reasonable. I don't know what the consideration is behind it, but it will cause unexpected behavior for plugin authors.

What exactly does the `error` mean? if there is an error, can't vim report it out and let the user fix the error, for example, by add `silent!` or something?

**Comment by tonymec** [comment]
How does your plugin detect the error?

The documentation about `:silent` says that with exclamation point, error messages are not displayed and execution is not aborted but **v:errmsg is still set** (emphasis mine).

Best regards,
Tony.

**Comment by Yggdroot** [comment]
> How does your plugin detect the error?


My plugin does not detect the error.

> The documentation about `:silent` says that with exclamation point, error messages are not displayed and execution is not aborted but **v:errmsg is still set** (emphasis mine).

Since **v:errmsg is still set** no matter whether `silent!` exists or not, so if the filter detect an error,  it should not return 0 unconditionally.

**Comment by brammool** [comment]
Using ":silent!" in a :def function is not implemented yet.  In the example above use a legacy function to make ":silent!" work.

A filter should never cause an error, because it may result in typed keys being dropped and the user being unable to do anything.
If it causes an unexpected error, it's hard to decide what to do.  Most likely the filter should no longer be used.  Letting the key get through at least allows the user to do something like type an Ex command to get out of the situation.

**Comment by lacygoill** [comment]
> In the example above use a legacy function to make ":silent!" work.

`silent!` still doesn't work even in a legacy function:
```vim
fu Filter(winid, key) abort
    if a:key ==# 'o'
        silent! invalid
        return v:true
    endif
    return popup_filter_menu(a:winid, a:key)
endfu
call popup_create(['TEST'], #{filter: function('Filter')})
call feedkeys("o\r\r", 'nt')
```
Here, `o` is not discarded because of `invalid`, even though the error is suppressed by `silent!` and the filter returns `v:true` (meaning that the key should be discarded).

**Comment by lacygoill** [comment]
> silent! still doesn't work even in a legacy function:

Sorry, it works in the sense that it does suppress the error, but it still doesn't prevent the filter from detecting the error.

**Comment by lacygoill** [comment]
> A filter should never cause an error, because it may result in typed keys being dropped and the user being unable to do anything.

Yes, but the code causing the error might not be in the filtering function itself; it might be in a complete different script.  As in the original example, the filter might fire an event which triggers an autocmd defined somewhere else.  When that happens, it's a bit unexpected for the key to pass through.  Although, as you said:

> Letting the key get through at least allows the user to do something like type an Ex command to get out of the situation.

So, I don't know if there's a good solution.  At least, it would be nice if the filter didn't detect an error which was suppressed by `silent!` or a `try`/`catch`.

**Comment by brammool** [comment]
Ah, I see.  The code was using emsg_called, so that the tests also work inside a try/endtry.  But that indeed also gets set when using ":silent!".  Hmm, we can use did_emsg, but then the tests will fail...

**Comment by lacygoill** [comment]
Thank you.  The patch fixes the issue for a legacy function, as long as the error is suppressed:
```vim
fu Filter(winid, key) abort
    if a:key ==# 'o'
        silent! invalid
        return v:true
    endif
    return popup_filter_menu(a:winid, a:key)
endfu
call popup_create(['TEST'], #{filter: function('Filter')})
call feedkeys("o\r\r", 'nt')
```
Or caught:
```vim
fu Filter(winid, key) abort
    if a:key ==# 'o'
        try
            invalid
        catch
        endtry
        return v:true
    endif
    return popup_filter_menu(a:winid, a:key)
endfu
call popup_create(['TEST'], #{filter: function('Filter')})
call feedkeys("o\r\r", 'nt')
```
The issue persists in Vim9, when we use `silent!`:
```vim
vim9script
def Filter(winid: number, key: string)
    if key == 'o'
        silent! invalid
        return true
    endif
    return popup_filter_menu(winid, key)
enddef
popup_create('TEST', #{filter: Filter})
feedkeys("o\r\r", 'nt')
```
This is expected, because command modifiers are not implemented yet.

It also persists when we catch the error with a `try`/`catch`:
```vim
vim9script
def Filter(winid: number, key: string)
    if key == 'o'
        try
            invalid
        catch
        endtry
        return true
    endif
    return popup_filter_menu(winid, key)
enddef
popup_create('TEST', #{filter: Filter})
feedkeys("o\r\r", 'nt')
```
I don't know whether this is expected.  Maybe it's related to this todo item:

https://github.com/vim/vim/blob/371806e1642bbe17792f1e0fc7abe2ae13794635/runtime/doc/todo.txt#L145

**Comment by Yggdroot** [comment]
Thank you, with this patch my plugin LeaderF backs to normal now.
