### ISSUE TITLE
when opening terminal in popup, option `border` cause cursor to shift to wrong place

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7298]
**Describe the bug**
When open a terminal in popup, and cmd is not `&shell` or `bash` and ect., if options `border` and `borderchars` are set, the cursor shifts to a wrong place.

**To Reproduce**
1. `test.vim`
Provide function to produce the bug. The function is to do something such as showing a long file in a terminal and show the result in popup. `0` for noborder and `1` for popup with border.
```vim
function! Test(mode=0)
  let path = expand('~/.zshrc')
  let cmd = 'cat '.path
  let bufnr = term_start(cmd, #{
        \ term_cols:   80,
        \ term_rows:   20,
        \ hidden:      1,
        \ norestore:   1,
        \ term_finish: 'open'
        \ })
  let opts_noborder = #{
        \ maxwidth: 80,
        \ minwidth: 80,
        \ maxheight: 20,
        \ minheight: 20,
        \ zindex: 1000,
        \ pos: 'center',
        \ scrollbar: 0,
        \ }
  let opts_border = opts_noborder
  let opts_border.border = [1, 1, 1, 1]
  let opts_border.borderchars = ['─', '│', '─', '│', '┌', '┐', '┘', '└']
  if a:mode
    call popup_create(bufnr, opts_border)
  else
    call popup_create(bufnr, opts_noborder)
  endif
endfunction
```

2. run `vim --clean`
3. run `:source ./test.vim`
4. run `:call Test(1)`

**Expected behavior**
The cursor is normal when I call `Test(0)` with no border, but with `Test(1)` the border version, the cursor is shift to the next line and sometimes to lines below the popup. Try to use `gg`, `G`, and `V` will show the problem.

**Environment (please complete the following information):**
 - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 24 2020 16:26:37) contain patch 1-1897
 - OS: Ubuntu 18.04,
 - Terminal: GNOME Terminal

**Comment by bfrg** [comment]
I'm observing a popup border for both `Test(0)` and `Test(1)`. You need to `copy()` the original dictionary before modifying it, like `let opt_border = copy(opts_noborder)`. 

I think the cursor shouldn't be stuck in the popup window in the first place once the terminal job is finished since focusing a popup window has been strictly disabled (or not implemented yet), unless a terminal job is running in a popup.

The following item is from `:help popup-terminal`:
```
- When the job ends, the popup window closes.
```

**Comment by ZhiyuanLck** [comment]
So is it impossible to correct the position of cursor unless focusing on a popup window is implemented? Is there some plan to implement this feature or it will not be considered in the short/long term?

**Comment by brammool** [comment]
> **Describe the bug**
> When open a terminal in popup, and cmd is not `&shell` or `bash` and ect., if options `border` and `borderchars` are set, the cursor shifts to a wrong place.
> 
> 
> **To Reproduce**
> 1. `test.vim`
> Provide function to produce the bug. The function is to do something such as showing a long file in a terminal and show the result in popup. `0` for noborder and `1` for popup with border.
> ```vim
> function! Test(mode=0)
>   let path = expand('~/.zshrc')
>   let cmd = 'cat '.path
>   let bufnr = term_start(cmd, #{
>         \ term_cols:   80,
>         \ term_rows:   20,
>         \ hidden:      1,
>         \ norestore:   1,
>         \ term_finish: 'open'
>         \ })
>   let opts_noborder = #{
>         \ maxwidth: 80,
>         \ minwidth: 80,
>         \ maxheight: 20,
>         \ minheight: 20,
>         \ zindex: 1000,
>         \ pos: 'center',
>         \ scrollbar: 0,
>         \ }
>   let opts_border = opts_noborder
>   let opts_border.border = [1, 1, 1, 1]
>   let opts_border.borderchars = ['─', '│', '─', '│', '┌', '┐', '┘', '└']
>   if a:mode
>     call popup_create(bufnr, opts_border)
>   else
>     call popup_create(bufnr, opts_noborder)
>   endif
> endfunction
> ```
> 
> 2. run `vim --clean`
> 3. run `:source ./test.vim`
> 4. run `:call Test(1)`
> 
> **Expected behavior**
> The cursor is normal when I call `Test(0)` with no border, but with
> `Test(1)` the border version, the cursor is shift to the next line and
> sometimes to lines below the popup. Try to use `gg`, `G`, and `V` will
> show the problem.

It looks like in this situation the border offset is added twice.
This is in update_popups().  Hmm, it's tricky to remember when the
offset is already added after updating the row and column.

-- 
hundred-and-one symptoms of being an internet addict:
248. You sign your letters with your e-mail address instead of your name.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
