### ISSUE TITLE
Vim freezes on startup

### ISSUE THREAD

**Issue by adelarsq** [vim/vim#730]
The build for Windows on [vim-win32-installer](https://github.com/vim/vim-win32-installer) freezes.

Confirmed with the last version but many others before  7.4.1707.

SO: Windows 10

Anyone with the same problem?

**Comment by k-takata** [comment]
Which do you use, gvim.exe or vim.exe?
Does it occur when running with minimal settings? Try `gvim -N -u NONE -U NONE`.
Do you use any plugins?

> Similar to: #194 #698

I don't think they are related. They are related to X.

**Comment by adelarsq** [comment]
@k-takata yes. You are right. Same problem occurs with gvim and vim, but none with minimal settings. There is something wrong with the plugins (I have 149 actived), more exactly [ultisnips](https://github.com/SirVer/ultisnips), that is using some new breaking change. The [official release](http://www.vim.org/download.php) and [Wu release](http://wyw.dcweb.cn/#download) are working fine.

Note: I did remove the link with others issues to avoid confusion in the future.

**Comment by chrisbra** [comment]
If it still freezes with the latest patchlevel, it might still be a bug lying around, that needs to be fixed then. From what patchlevel does the freezing start and can you provide an example, that exhibits the behaviour?

**Comment by adelarsq** [comment]
@chrisbra I don't know exatly. Some weeks ago did try the version in the [repository](https://github.com/vim/vim-win32-installer) and did notice the problem. But I was thinking that was something wrong with my configs.

There is something different between Wu build and this that make the editor freeze using ultisnips. I will create a minimal vimrc that reproduce the problem.

**Comment by adelarsq** [comment]
Isn't related with the startup. I had some autocommands to execute when Vim starts.

To reproduce just need the ultisnips plugin instaled and use the `:help map` command.

Anyway, the steps are shown below:
- Download and unpack the last build on https://github.com/vim/vim-win32-installer/releases
- Open gvim or vim on the unpacked folder
- Save this content on the file `C:\_vimrc`

```
set renderoptions=type:directx,renmode:5
let s:use_directx=1
set shell=$COMSPEC

set nocompatible
set encoding=utf-8 nobomb

syntax on
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

source ~/.vim/autoload/plug.vim

call plug#begin('~/.vim/plugged')

Plug 'https://github.com/SirVer/ultisnips'

call plug#end()
```
- Need [vim-plug](https://github.com/junegunn/vim-plug) and [ultisnips](https://github.com/SirVer/ultisnips) already be installed on `~/.vim/autoload/plug.vim` and `~/.vim/plugged`, respectively, since _Vim freezes installing_
- Load the file
  `:source C:\_vimrc`
- Vim freezes with
  `:help map`

**Comment by nathanhi** [comment]
It seems that we're encountering a similar problem. We're using vim on Windows from the Git distribution package. It seems to have been broken since the release of Git 2.8.0 - Git 2.7.4 was just working fine. 

There haven't been any changes in the distributed vim version since then (the hashes of the binaries are the same between both releases, the used version is 7.4.1468), but there has been an update of MSYS2 which seems to have introduced the issue. Replacing the `msys-2.0.dll` with the one from the old Git 2.7.4 package solves the problem and vim will just work fine. Vim will also only crash if set nocompatible is set in the vimrc (or if a `~/.vimrc` exists, of course).

There have been a lot of changes in MSYS2 regarding path length limitations on Windows, so I guess the problems are coming from one of those changes?

**Comment by nathanhi** [comment]
Oh, it seems that it has been in fact an issue with MSYS2, at least I found a matching (and also already fixed/closed) bug report for that in the git-for-windows project: https://github.com/git-for-windows/git/issues/711

**Comment by chrisbra** [comment]
yeah, that was an msys issue. Closing.
