### ISSUE TITLE
Half rendered emojis on macvim

### ISSUE THREAD

**Issue by adelarsq** [vim/vim#732]
Some chars on MacVim 4.7.1707 are been half rendered:
<img width="1249" alt="emoji" src="https://cloud.githubusercontent.com/assets/430272/14301870/a17d02bc-fb71-11e5-9b9e-55e5f914ba5b.png">
Chars list:

```
✊ ⭐ ⛅ ⏳ ⌛ ⏰ ⌚ ⚽ ⚾ ⬆ ⬇ ⬅ ⏪ ⏩ ⏫ ⏬ ⤵ ⤴ 🆗
Ⓜ 🆑 🆘 🆔 ⛔ ❎ ✅ 🆚 🅰 🅱 🆎 🅾 ➿ ⛎ ❌ ❓ ❔ ⭕ ➕
➗ ⚫️ ⚪️
```

**Comment by adelarsq** [comment]
Closing since has no feedback on this issue.

**Comment by crazymaster** [comment]
How about creating an issue on this repository?
https://github.com/macvim-dev/macvim

**Comment by adelarsq** [comment]
@crazymaster I did create there (https://github.com/macvim-dev/macvim/issues/267). But I think that is something about vim, since on GVim on Windows has similar problems.

**Comment by vim-ml** [comment]
2016-04-24 18:31 GMT+03:00 Adelar da Silva Queiróz <
vim-dev-github@256bit.org>:

> @crazymaster https://github.com/crazymaster I did create there (
> macvim-dev/macvim#267 https://github.com/macvim-dev/macvim/issues/267).
> But I think that is something about vim, since on GVim on Windows has
> similar problems.

​This is something about font rendering libraries (or how these libraries
are used by toolkit used by Vim GUI or terminal emulator) and how they work
with symbols borrowed from the other fonts.​ Opening issues in *vim
repositories is not going to be much helpful: Vim could fix this only by
creating some more or less dirty hacks and do this only for itself.

Basically this happens because monospace fonts used by Vim do not contain
necessary glyphs, so font rendering library has to borrow them from
somewhere. This “somewhere” is usually not a monospace font and definitely
has different glyph dimensions; and picture glyphs from non-monospace font
most of time are wider then a screen cell when taking font with the same
size. I do not know why literally nowhere I saw this borrowing tries to
resize glyph, but usually this results in one of two behaviours:
1. Glyph is displayed completely, but all screen cells to the right are
   shifted. Shifting may be seen up to the location where terminal emulator
   received “move to (X, Y) cell” command which provokes hard visual bugs when
   editing such files. Most of time shift also ends at the next blank cell.
2. Glyph is truncated like you see.

Another possible source of confusion is the case when toolkit/font
rendering library/terminal emulator/… thinks that glyph occupies two
display cells while Vim thinks it occupies one or vice versa. Looks like
you were hit also by this problem. There are always at least two places
where text width in screen cells is computed: Vim uses its own functions
for this, whatever renders the text uses its own which are not identical to
Vim’s ones (given that you may run Vim in screen in tmux in Neovim
:terminal buffer in konsole terminal emulator you may have even more places
where text width is computed, all using different functions; add such
character to a file name and use powerline with old Vim version and you
will have yet another function which computes width added to an equation
(new Vim versions have strwidth())).

**Comment by adelarsq** [comment]
@vim-ml Got it. I notice problems like this on many different versions. Since has no way to solve I will close the issue on the MacVim repository too. Thanks 👍

**Comment by vim-ml** [comment]
Hey friend, 
I've read about  some  cool things recently and  I though you might be inerested too, here is the link  <http://look.edeste.info/e4iinki>

paul
