### ISSUE TITLE
Extra blinking cursor in terminal opened in popup with borders

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7389]
It seems related to issue of #7298 

`test.vim`
```vim
function! Test()
  let winid = term_start(&shell, #{hidden: 1, term_finish: 'open'})
        \ ->popup_create(#{
        \ maxwidth: 80,
        \ minwidth: 80,
        \ maxheight: 20,
        \ minheight: 20,
        \ pos: 'center',
        \ border: []
        \ })
endfunction
```

Use above setting file and run `vim --clean -S test.vim`, then run `:call Test()` in vim.

Keep inputting some text in terminal, extra blinking cursor can be observed on the above left of the current cursor.

**Environment:**
 - Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 24 2020 16:26:37) contain patch 1-2020
 - OS: Ubuntu 18.04,
 - Terminal: GNOME Terminal

**Comment by lacygoill** [comment]
> Keep inputting some text in terminal, extra blinking cursor can be observed on the above left of the current cursor.

Not sure to have correctly understood, but if the issue is that the cursor is briefly displayed in an unexpected location while inputting text, then it's a duplicate of https://github.com/vim/vim/issues/5943 , for which there is a todo item:

https://github.com/vim/vim/blob/4a44120e3dc1d40dd7109658afd5e078360b1d8f/runtime/doc/todo.txt#L163

**Comment by ZhiyuanLck** [comment]
Yeah, it is the problem, since it has an issue I'll close it.
