### ISSUE TITLE
Vim9: should the second index in a slice be exclusive?

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7408]
This is not a bug report nor a feature request.  Just a discussion about whether it would be beneficial for Vim9 to change how the second index in a slice is parsed.

It seems that Vim9 is influenced by TypeScript (13 occurrences at `:h vim9`), JavaScript (10 occurrences) and Python (4 occurrences).  And in those languages, I *think* the second index in a slice is exclusive.

In Vim script legacy, and in Vim9, it's inclusive.  Should it be made exclusive in Vim9?  Maybe users more familiar with JavaScript and Python would like this change?

---

Note that Vim9 has already changed the meaning of indexes in a string slice.  In Vim script legacy, they describe byte indexes.  In Vim9, they describe character indexes.  See `:h expr-[:]`:

<https://github.com/vim/vim/blob/ea87069d7814497181483877651aef6d97182120/runtime/doc/eval.txt#L1215-L1216>

If it was ok to change the meaning of string indexes, maybe it's ok to change the inclusive property of the second index?  And if it's ok for a string slice, then maybe it's ok for a list slice as well?

---

To illustrate how it can simplify the code a little, consider this Vim9 snippet whose purpose is to generate all permutations of items in a list:
```vim
vim9script

def InsertItemAtAnyPosition(x: any, l: list<any>): list<list<any>>
    var ret = []
    for i in range(len(l) + 1)
        ret += [ (i == 0 ? [] : l[: i - 1]) + [x] + l[i :] ]
    endfor
    return ret
enddef

def GetAllPermutations(l: list<any>): list<list<any>>
    if len(l) == 0
        return [[]]
    endif
    var ret = []
    for x in GetAllPermutations(l[1 :])
        for y in InsertItemAtAnyPosition(l[0], x)
            ret += [y]
        endfor
    endfor
    return ret
enddef

echo range(3)->GetAllPermutations()
```
Same code in python:
```python
#!/usr/bin/python

def InsertItemAtAnyPosition(x, l):
    ret = []
    for i in range(len(l) + 1):
        ret += [ l[0:i] + [x] + l[i:] ]
    return ret

def GetAllPermutations(l):
    if len(l) == 0:
        return [[]]
    ret = []
    for x in GetAllPermutations(l[1:]):
        for y in InsertItemAtAnyPosition(l[0], x):
            ret += [y]
    return ret

print GetAllPermutations([0, 1, 2])
```
Notice how the 6th line is simpler in python:

    ret += [ l[0:i] + [x] + l[i:] ]

Compared to Vim9:

    ret += [ (i == 0 ? [] : l[: i - 1]) + [x] + l[i :] ]

That's because the second index is exclusive in Python while inclusive in Vim9.

---

I don't have a strong opinion on the matter.  Some people think that it's [counter-intuitive](https://stackoverflow.com/a/50209705/9780968).

**Comment by brammool** [comment]
Yeah, it seems that many languages make the "end" index of the slice operator exclusive.
In many situations this works fine, but there are a few corner cases where it's problematic.
Python uses "-1" to refer to the last item in [start:end].  But when used for the end, using "-1" means to exclude the last element.
To get the items from some point to the end the end index has to be omitted, which is a bit weird.

When using the slice() method this basically works the same way: when getting all items from a certain index to the end, one must omit the end index.  It cannot be expressed with a number in any way.
Well, if allowing for invalid indexes, one could use slice(start, 99999999).  That's ugly though.

**Comment by lacygoill** [comment]
I'm closing because I don't think people are really interested in this syntax detail.  It might help in certain cases, but as you said, it might cause issues in other cases.  Besides, it's not obvious there would be real benefits; and if there are, it's not obvious they would warrant the efforts necessary for the implementation.

**Comment by dnaaun** [comment]
UPDATE: A previous version of this comment had a small example demonstrating the benefit of the proposed semantics, but I didn't read completely through @lacygoill 's initial post, and it turns out I was reiterating the same point.

I'd like to vote for this new semantics, (if it's still up for debate of course). I don't see a downside to it at all. Previous cases that were written as `[i:-1]` can be written as `[i:]`, right?

**Comment by lilydjwg** [comment]
> When using the slice() method this basically works the same way: when getting all items from a certain index to the end, one must omit the end index. It cannot be expressed with a number in any way.

Python's index in slices really means offsets. So to the end one could use `[:len(x)]`. There is no way to slice to the end without knowing the length however because `0` means the start already. You cannot use negative slices to things with unknown length anyway.

>  Well, if allowing for invalid indexes, one could use slice(start, 99999999). That's ugly though.

Well Python supports this but it will definitely break some day when the object is long enough.

In Python's way, both `i` and `j` in `[i:j]` mean offsets, so it can be handled more consistently. Besides continuously slicing, `j-i` is the length of the result if both are positive and in range.

Lua, which has uncommon index meaning, also differs in this aspect. In `string.sub(s, i, j)` the `j` is inclusive. Same for `string.find`'s return values. This results in this kind of code:

```lua
function string_split(string, pat, plain)
    local ret = {}
    local pos = 0
    local start, stop
    local t_insert = table.insert
    while true do
        start, stop = string:find(pat, pos, plain)
        if not start then
            t_insert(ret, string:sub(pos))
            break
        end
        t_insert(ret, string:sub(pos, start-1))
        pos = stop + 1
    end
    return ret
end
```

The indexes have to be adjusted in multiple places. If they were offsets, no such adjustment would be needed.

**Comment by lacygoill** [comment]
I re-open the issue because there seems to be some interest on this syntax detail.

**Comment by brammool** [comment]
The main reason for making the second index inclusive is to allow for
using "-1" to refer to the last item.

Suppose you have a very long list and want to get the items at the end:
	let start = ComputeStart()
	let end = ComputeEnd()
	let result = mylist[start : end]

If "end" is used exclusive, it cannot be a negative number, since "-1"
refers to the last item, which then never can be included.

In Python the only solution is to drop the end index:

	if end == -1
		let result = mylist[start : ]
	else
		let result = mylist[start : end]
	endif

Which is similar to handling a corner case.

I'm not really sure what the best solution is, so perhaps we should just
keep it as it currently is.

We could also add a slice() method which would use an exclusive second
index, in case that's needed.  We would need to add documentation to
explain the difference between the two ways to take a slice.  Since
there is debate about what the best solution is, providing both might
actually be the best choice.

-- 
Don't drink and drive.  You might hit a bump and spill your beer.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dnaaun** [comment]
I'd vote for a single slice() method, even with the last-index-inclusive behavior. 

Regarding the example Bram just gave, how I'd go about it is:
```vimscript
result = mylist[start: len(mylist)-end]
```
Of course, one would have to modify `ComputeEnd()` to yield numbers one more than it previously did for this to work.

**Comment by lilydjwg** [comment]
> In Python the only solution is to drop the end index

In Python you can use `None` to slice to the end to avoid duplicate code. I don't really encounter this issue since when I get slice indexes as variables from other functions, I always get non-negative ones in the range `[0, len(x)]` because programs like to count forward.

Vim has things like `v:none` too so it may be used to indicate slicing to the end similarly.

> providing both might actually be the best choice.

This sounds good if the overhead / implementation isn't complex. Rust has both kinds of ranges (`x..y` and `x..=y`).
