### ISSUE TITLE
Ctrl-V U doesn't work when modifyOtherKeys is enabled

### ISSUE THREAD

**Issue by k-takata** [vim/vim#7413]
**Describe the bug**
Typing Ctrl-V U in insert mode shows `U` instead of entering the hexadecimal mode.

**To Reproduce**
1. Run `vim --clean`.
2. Type `i` to go to insert mode, then type `Ctrl-V` and `U`.
3. `U` is shown.

**Expected behavior**
An 8-digit hexadecimal value can be typed.

**Environment (please complete the following information):**
 - Vim 8.2.2081
 - OS: Windows 10
 - Terminal: mintty 3.4.3

I also heard that this also occurs on xterm.

**Additional context**
Originally reported at https://github.com/mintty/mintty/issues/1066.

**Comment by chrisbra** [comment]
I can confirm, this also happens also on xterm.

I suppose we need this patch:
```patch
diff --git a/src/edit.c b/src/edit.c
index 8c5cec3a7..c8b29fa26 100644
--- a/src/edit.c
+++ b/src/edit.c
@@ -1878,6 +1878,8 @@ get_literal(void)
     for (;;)
     {
        nc = plain_vgetc();
+       if (nc == ESC || nc == CSI)
+           nc = decodeModifyOtherKeys(nc);
 #ifdef FEAT_CMDL_INFO
        if (!(State & CMDLINE) && MB_BYTE2LEN_CHECK(nc) == 1)
            add_to_showcmd(nc);
```

Do we have tests for xterm modifyOtherkeys behaviour?

**Comment by brammool** [comment]
This must have been a problem for a while.  Apparently this isn't used much.
The cause is that in get_literal() the allow_keys flag isn't set.
Not sure if Christian's solution always works, adding a flag similar to allow_keys seems more reliable.

**Comment by brammool** [comment]
Ah, ins_ctrl_v() actually takes care of it, but then it's too late.

**Comment by Mariusz-W** [comment]
Thank you, Mr Takata, for filing the report in response to my initial report filed in the mintty project, and Thank you the vim team for a quick and constructive response.

I observed also that apparently the same issue affected inability to resize the font using mintty’s Ctrl++/Ctrl+- when editing a file in vim. Both issues afflicted vim in mintty **only when the value of ‘Terminal Type’ variable was set in mintty to any of the ‘xterm-*’ values**, not when it was set to ‘mintty’.

A temporary solution to add to ~/.vimrc

```
if &term == "xterm" || &term == "xterm-256color" || &term == "xterm-direct"
  let &t_TI = ""
endif
```

(I hope the syntax is right) 

cured the Ctrl-V U******** issue, and I noticed somewhat later that it simultaneously cured the issue with Ctrl++/Ctrl+- not working.

**Comment by Mariusz-W** [comment]
While we are talking about Ctrl-V U******** , can I ask whether we could modify this mechanism slightly by making it a bit more convenient for the user, not requiring all 8 digits to input? The first 3 (or 4 digits) are always 0 anyway. When vim registers the first non-zero digit in a string, it could be made to stop waiting for the rest after getting 5 consecutive digits, instead 8. For example, instead of typing

Ctrl-V U00020000  one would type  Ctrl-V U20000

An added convenience, especially if you have to resort to inputting those 4-byte Unicode code points quite frequently. This is precisely how printf '\U*****' handles it in Bash.

**Comment by k-takata** [comment]
The Unicode specification accepts up to U+10FFFF. So, it should accept 6 digits.

`:help i_CTRL-V_digit` says:

> As soon as you type a character that is invalid for the mode, the value before it will be used and the "invalid" character is dealt with in the normal way.

E.g. if you type "Ctrl-V U263aq", "☺q" will be input.

Hmm, typing "Ctrl-V U263ax" results in "☺" instead of "☺x". The "x" is somehow disappeared.

**Comment by Mariusz-W** [comment]
Thank you for reminding me about the last Supplemental Plane. In this case my request would be:

1) After CtrlV U , vim should stop waiting for input after reading 5 hex digits if the first nonzero digit is:

a) different from 1,

or

b) is 1 but the next digit is not 0 .

It should stop waiting for input after reading 6 hex digits if the first nonzero digit is 1 followed by 0 .

Forcing the user to input 8 digits every time I find a real inconvenience, given that there are occasions that I have to do it again and again, when I perform full Ideographic Decompositions of characters that cannot be just copied and pasted from some convenient source.

a) different from 1,

or

b) is 1 but the next digit is not 0 .

**Comment by k-takata** [comment]
> cannot be just copied and pasted from some convenient source.

I'm not sure about this, but Cygwin version of Vim can directly access the Windows' clipboard.
E.g. you can paste by `"*p`.

**Comment by Mariusz-W** [comment]
I just checked:

1) Windows Console vim binary in Windows Console,

2) Windows Console vim binary  Powershell,

3) Cygwin vim

— all three in WIndowsTerminal.

In all three cases, "*p in the command mode, properly pastes in Unicode characters from the Supplemental Planes.

Thank you for your valuable tips. Currently, this seems to be a life saver when using vim in WindowsTerminal in view of pasting Unicode characters from Supplemental Planes being broken.

A question to the vim team: is it possible for vim to recognize that it is tarted in WindowsTerminal, so that I can set certain things in .vimrc or _vimrc just for those cases when I edit files in WindowsTerminal?

**Comment by chrisbra** [comment]
> A question to the vim team: is it possible for vim to recognize that it is tarted in WindowsTerminal, so that I can set certain things in .vimrc or _vimrc just for those cases when I edit files in WindowsTerminal?

I think, checking for `$WTSESSION` should work and I just used this with vim-airline

e.g. 
```vim
if !empty($WTSESSION)
   " this is using the windows terminal
else
  " this isn't
endif
```

**Comment by Mariusz-W** [comment]
If I place

```
if !empty($WTSESSION)
  noremap  <F2>         "*p
endif
```

either in  _vimrc  or  .vimrc , then pressing F2 does nothing in Windows Console vim or Cygwin vim run in WindowsTerminal .

If I place

`noremap  <F2>         "*p`

outside of the ‘if … endif’ statement, then pressing F2 key behaves as it should: it pastes in the contents of the Windows clipboard.

**Comment by k-takata** [comment]
Shouldn't it be `$WT_SESSION`?

**Comment by chrisbra** [comment]
oh you are right, it should probably be `$WT_SESSION`

**Comment by Mariusz-W** [comment]
> 
> 
> Shouldn't it be `$WT_SESSION`?

Yes! Now it works, both with Windows Console vim and with Cygwin vim. Thank you for one more valuable tip.

**Comment by brammool** [comment]
> Thank you, Mr Takata, for filing the report in response to my initial
> report filed in the mintty project, and Thank you the vim team for a
> quick and constructive response.
> 
> I observed also that apparently the same issue affected inability to
> resize the the font using mintty’s Ctrl++/Ctrl+- when editing a file
> in Vim. This was happening only when the value of term variable was
> xterm-* , not when it was, say, mintty.
> 
> Temporary solution to add
> 
> if &term == "xterm" || &term == "xterm-256color" || &term == "xterm-direct"
>   let &t_TI = ""
> endif
> 
> (I hope the syntax is right) 
> 
> that cured the Ctrl-V U******** issue, also cured the issue with
> Ctrl++/Ctrl+- .

This would indicate that when Vim enables modifyOtherKeys, so that the
user can use more key combinations, Mintty stops recognizing the CTRL-+
key.  That is not something that Vim can fix, you will have to report
this to Mintty.

-- 
An indication you must be a manager:
You feel sorry for Dilbert's boss.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
