### ISSUE TITLE
LaTeX spell checking broken when used `\(…\)` instead of `$…$`

### ISSUE THREAD

**Issue by mowgli** [vim/vim#7457]
**Describe the bug**
I like to spell check my LaTeX files. But sometimes the spell checking breaks leading to the spelling of comments and commands getting checked but not the spelling of normal text.

I was able to get it down to when I use the LaTeX `\(…\)` instead of the plainTeX `$…$` version.

**To Reproduce**
I cannot use `vim --clean` as this would disable spell checking due to no available dictionary.

So here is my example LaTeX file:
```
\documentclass{article}

\usepackage{siunitx} % für \ang
\sisetup{%
   text-degree={\(^\circ\)},
}
\begin{document}
Irgendwelche Flascher Text
%Irgendwelche Flascher Text
\end{document}
% vim: spell spelllang=de
```

You can "fix" the bug by commenting the line `text-degree={\(^\circ\)},`.

**Expected behavior**
I expect spelling get checked in the normal text (I don't need spelling in the comments)

**Environment (please complete the following information):**
 - Vim version doesn't matter, any recent versions of vim.
```
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Nov 19 2020 07:49:24)
Inklusive der Patches: 1-1913
```
 - OS doesn't matter but I use linux (devuan or gentoo)
 - Terminal doesn't matter but I use xterm

**Comment by brammool** [comment]
@cecamp

**Comment by cecamp** [comment]
Hello -- could you provide me with a different example? I downloaded siunitx.sty from ctan, but its not happy with my current latex installation, so I cannot use your current example. However, I note that the syntax highlighting is showing a lot of red (ie. error highlighting) near text-degree={\( . As a consequence \begin{document} is not being highlighted properly.

It looks like this problem is likely due to your using a package (siunitx) and needing custom highlighting for it (ie. \sisetup). Please look at :help tex-package and try constructing some syntax highlighting for siunitx.sty. From what I can tell your \sisetup is setting up a region that attempts to use math zone highlighting but the highlighting doesn't know that, consequently mismatched curly braces result, and the rest of the file is dubiously highlighted. When you comment the \sisetup section out, please note the difference in highlighting of \begin{document}.

**Comment by mowgli** [comment]
Hi @cecamp,

it shouldn't matter if you have that package or not. I do not have an issue with compiling the file than with the spell checking.

Although, I also see that mistakes in highlighting, maybe they are related. But that is not my issue, my issue is that it breaks the spell checking.

About your assumption, If I replace the line `text-degree={\(^\circ\)},` with `text-degree={$^\circ$},`, the problem is gone. although the `^` is still highlighted in red but spell checking is working.

**Comment by cecamp** [comment]
Syntax highlighting sets up regions wherein certain syntax is recognized. Spell checking happens in some regions, not others; for example, one doesn't want spell checking in a math region.

You've run into an issue where, because of a tex "plugin" that you've added, the syntax highlighting is not matching {\(..\)} because the math syntax is not being recognized. The perceived mismatch persists over the \begin{document}, and so the normal text area is not being recognized as such. Hence, no spell checking. Try `:let g:tex_matchcheck=""` and then `:set ft=tex`. That will turn mismatched delimiter checking off; consequently, the \begin{document} is then properly recognized, and spell checking occurs where you're expecting it.
Now, if you provided some custom highlighting for the siunix.sty, presumably the math would be recognized, and the spellchecking would occur where you expect it.

**Comment by cecamp** [comment]
Sorry, I keep having problems with markdown sometimes showing backslashes and other times suppressing them.

That should be "..is not matching`{\(..\)} because`.
