### ISSUE TITLE
Syntax manual and changing buffers

### ISSUE THREAD

**Issue by KillTheMule** [vim/vim#747]
I'm on vim 7.4.769, and I have applied https://github.com/vim/vim/commit/885f24fbcae2a39ae496ffb3a1e139379be8fae1. This fixed the issue mentioned in this discussion: https://groups.google.com/forum/#!msg/vim_dev/VAHuSclzDe4/G-Ulbxc2CwAJ. It does however not fix the following, very similar issue:
- Create files:
  
  ```
  $ cat vimrc 
  filetype on
  syntax manual
  $ cat t1 
  echo 1
  $ cat t2
  echo 2
  ```
- Run Vim:
  `$ vim -N -u vimrc t1 t2`
- Set the filetype
  `:set ft=vim`
- Enable syntax in the current buffer:
  `:set syntax=ON`
- Move to the next buffer and then back again:
  `:bn | bp`
- The syntax option is still enabled in the current buffer but no syntax highlighting is performed.

If I put `set hidden` in somewhere inbetween, the issue does not occur (this is also true for the "old" issue that was patched).

**Comment by mptre** [comment]
The `FileType` autocmd-event is not triggered unless it is detected or explicitly set. Switching to a buffer with a unknown filetype will therefore not trigger the event unless `setfiletype` is called. The only work-around I found so far:

``` vim
augroup debug
  au!
  au FileType * let b:didft = 1
  au BufLeave * let b:didft = 0
  au BufEnter * if !getbufvar('%', 'didft', 0) && !empty(&ft) | exe 'setf' &ft | endif
augroup END
```

**Comment by brammool** [comment]
So, when entering a buffer that isn't loaded and the filetype is not detected but it was set manually before, syntax is not loaded.  I suppose we can fix that, as if the filetype was detected.

**Comment by mptre** [comment]
Bram,

On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:

> So, when entering a buffer that isn't loaded and the filetype is not detected but it was set manually before, syntax is not loaded.  I suppose we can fix that, as if the filetype was detected.

Here's an attempt to solve this issue. Since the did_filetype variable
is reset after the readfile function has returned I let the did_filetype
variable reflect the previous value of did_filetype. The patch also
includes a test case.

## 

:wq

diff --git a/src/buffer.c b/src/buffer.c
index 9bc24bc..1272fea 100644
--- a/src/buffer.c
+++ b/src/buffer.c
@@ -151,6 +151,19 @@ open_buffer(
    retval = readfile(curbuf->b_ffname, curbuf->b_fname,
          (linenr_T)0, (linenr_T)0, (linenr_T)MAXLNUM, eap,
          flags | READ_NEW);
-   if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)
-   {
-       /*
-        \* The FileType autocmd event was not triggered but the buffer
-        \* already has the filetype option set. Therefore trigger the
-        \* FileType event as if it where detected using the existing
-        \* filetype option.
-        */
-       did_filetype = TRUE;
-       apply_autocmds(EVENT_FILETYPE, curbuf->b_p_ft, curbuf->b_fname,
-           TRUE, curbuf);
-   }
-   keep_filetype = FALSE; /\* reset in either case */
  msg_silent = old_msg_silent;
  #ifdef FEAT_NETBEANS_INTG
    netbeansFireChanges = oldFire;
  diff --git a/src/fileio.c b/src/fileio.c
  index ed8d45b..9f3c622 100644
  --- a/src/fileio.c
  +++ b/src/fileio.c
  @@ -9496,6 +9496,7 @@ apply_autocmds_group(
  restore_search_patterns();
  if (did_save_redobuff)
      restoreRedobuff();
-   keep_filetype = did_filetype;
  did_filetype = FALSE;
  while (au_pending_free_buf != NULL)
  {
  diff --git a/src/option.c b/src/option.c
  index 8a706af..e22b97c 100644
  --- a/src/option.c
  +++ b/src/option.c
  @@ -7283,6 +7283,7 @@ did_set_string_option(
      did_filetype = TRUE;
      apply_autocmds(EVENT_FILETYPE, curbuf->b_p_ft,
                         curbuf->b_fname, TRUE, curbuf);
-       keep_filetype = FALSE;
  }
  #endif
  #ifdef FEAT_SPELL
  diff --git a/src/testdir/test_autocmd.vim b/src/testdir/test_autocmd.vim
  index 12c9848..8201142 100644
  --- a/src/testdir/test_autocmd.vim
  +++ b/src/testdir/test_autocmd.vim
  @@ -6,3 +6,23 @@ func Test_vim_did_enter()
  " This script will never reach the main loop, can't check if v:vim_did_enter
  " becomes one.
  endfunc
  +
  +func Test_filetype()
-  e a
-  setf vim
-  let g:ft = ''
-  augroup filetype
-    au!
-    au FileType \* let g:ft = expand('<amatch>')
-  augroup END
-  e b
-  bp
  +
-  call assert_equal('vim', g:ft)
  +
-  unlet g:ft
-  augroup filetype
-    au!
-  augroup END
-  augroup! filetype
  +endfunc

**Comment by mptre** [comment]
Anton Lindqvist wrote:

> Bram,
> 
> On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:
> 
> > So, when entering a buffer that isn't loaded and the filetype is not
> > detected but it was set manually before, syntax is not loaded.  I
> > suppose we can fix that, as if the filetype was detected.
> 
> Here's an attempt to solve this issue. Since the did_filetype variable
> is reset after the readfile function has returned I let the did_filetype
> variable reflect the previous value of did_filetype. The patch also
> includes a test case.

Thanks.

The did_filetype flag is a bit complicated to follow.  I think in this
condition:

> - if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)

You also need to check that did_filetype isn't set, otherwise the
Filetype event is triggered twice.  But perhaps it will then not always
trigger when you want to.  We might need another flag for that, which is
always reset before loading a buffer.  did_filetype isn't always reset,
as far as I can see.

Aren't there more places where readfile() is called where this is
needed?  I would think what we do here is related to triggering
EVENT_BUFREADPOST, which happens at the end of readfile().  Perhaps
triggering Filetype should be done there.

## 

MAN:    Fetchez la vache!
GUARD:  Quoi?
MAN:    Fetchez la vache!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mptre** [comment]
On Thu, Apr 14, 2016 at 01:07:54PM +0200, Bram Moolenaar wrote:

> Anton Lindqvist wrote:
> 
> > Bram,
> > 
> > On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:
> > 
> > > So, when entering a buffer that isn't loaded and the filetype is not
> > > detected but it was set manually before, syntax is not loaded.  I
> > > suppose we can fix that, as if the filetype was detected.
> > 
> > Here's an attempt to solve this issue. Since the did_filetype variable
> > is reset after the readfile function has returned I let the did_filetype
> > variable reflect the previous value of did_filetype. The patch also
> > includes a test case.
> 
> Thanks.
> 
> The did_filetype flag is a bit complicated to follow.  I think in this
> condition:
> 
> > -   if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)
> 
> You also need to check that did_filetype isn't set, otherwise the
> Filetype event is triggered twice.  But perhaps it will then not always
> trigger when you want to.  We might need another flag for that, which is
> always reset before loading a buffer.  did_filetype isn't always reset,
> as far as I can see.

I agree on the complexity of the statement. The attached patch uses a
separate variable to indicate if the filetype event was triggered or
not. I'm to satisfied with the solution, maybe we a more generalized way
to determine which events another event did trigger?

> Aren't there more places where readfile() is called where this is
> needed?  I would think what we do here is related to triggering
> EVENT_BUFREADPOST, which happens at the end of readfile().  Perhaps
> triggering Filetype should be done there.

I moved the logic after applying the EVENT_BUFREADPOST event.

## 

:wq

diff --git a/src/fileio.c b/src/fileio.c
index ed8d45b..71f0d24 100644
--- a/src/fileio.c
+++ b/src/fileio.c
@@ -143,6 +143,18 @@ static void vim_settempdir(char_u *tempdir);
 static char *e_auchangedbuf = N_("E812: Autocommands changed buffer or buffer name");
 #endif

+#ifdef FEAT_AUTOCMD
+/*
- \* Set by the apply_autocmds_group function if the given event is equal to
- \* EVENT_FILETYPE. Used by the readfile function in order to determine if
- \* EVENT_BUFREADPOST triggered the EVENT_FILETYPE.
- *
- \* Relying on this value requires one to reset it prior calling
- \* apply_autocmds_group.
- */
  +static int au_did_filetype INIT(= FALSE);
  +#endif
  +
   void
  filemess(
     buf_T  *buf,
  @@ -2669,8 +2681,19 @@ failed:
      apply_autocmds_exarg(EVENT_FILTERREADPOST, NULL, sfname,
                            FALSE, curbuf, eap);
  else if (newfile)
-   {
-       au_did_filetype = FALSE;
      apply_autocmds_exarg(EVENT_BUFREADPOST, NULL, sfname,
                            FALSE, curbuf, eap);
-       if (!au_did_filetype && *curbuf->b_p_ft != NUL)
-       /*
-        \* EVENT_BUFREADPOST did not trigger EVENT_FILETYPE but the
-        \* buffer already has a filetype. Trigger EVENT_FILETYPE using
-        \* the existing filetype.
-        */
-       apply_autocmds(EVENT_FILETYPE, curbuf->b_p_ft, curbuf->b_fname,
-           TRUE, curbuf);
-   }
  else
      apply_autocmds_exarg(EVENT_FILEREADPOST, sfname, sfname,
                              FALSE, NULL, eap);
  @@ -9537,6 +9560,9 @@ BYPASS_AU:
   if (event == EVENT_BUFWIPEOUT && buf != NULL)
  aubuflocal_remove(buf);
-    if (retval == OK && event == EVENT_FILETYPE)
-   au_did_filetype = TRUE;
  +
   return retval;
  }

**Comment by mptre** [comment]
Anton Lindqvist wrote:

> > > Bram,
> > > 
> > > On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:
> > > 
> > > > So, when entering a buffer that isn't loaded and the filetype is not
> > > > detected but it was set manually before, syntax is not loaded.  I
> > > > suppose we can fix that, as if the filetype was detected.
> > > 
> > > Here's an attempt to solve this issue. Since the did_filetype variable
> > > is reset after the readfile function has returned I let the did_filetype
> > > variable reflect the previous value of did_filetype. The patch also
> > > includes a test case.
> > 
> > Thanks.
> > 
> > The did_filetype flag is a bit complicated to follow.  I think in this
> > condition:
> > 
> > > - if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)
> > 
> > You also need to check that did_filetype isn't set, otherwise the
> > Filetype event is triggered twice.  But perhaps it will then not always
> > trigger when you want to.  We might need another flag for that, which is
> > always reset before loading a buffer.  did_filetype isn't always reset,
> > as far as I can see.
> 
> I agree on the complexity of the statement. The attached patch uses a
> separate variable to indicate if the filetype event was triggered or
> not. I'm to satisfied with the solution, maybe we a more generalized way
> to determine which events another event did trigger?
> 
> > Aren't there more places where readfile() is called where this is
> > needed?  I would think what we do here is related to triggering
> > EVENT_BUFREADPOST, which happens at the end of readfile().  Perhaps
> > triggering Filetype should be done there.
> 
> I moved the logic after applying the EVENT_BUFREADPOST event.

Thanks.  I think we should reset the flag earlier, before triggering any
autocommands when loading a buffer.  It's possible the user has setup
another autocommand to set filetype.

Otherwise I think this mechanism works fine.  We might still need to
find a situation where it doesn't work properly.

## 

CONCORDE: Message for you, sir.
   He falls forward revealing the arrow with the note.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
github is confusing my answers as if they were sent by mptre...

**Comment by chrisbra** [comment]
yeah, I noticed this too on the mailinglist and thought my github forward script is to blame. But as we can see here, its github's fault.

**Comment by mptre** [comment]
On Mon, Apr 18, 2016 at 01:30:46PM +0200, Bram Moolenaar wrote:

> Anton Lindqvist wrote:
> 
> > > > Bram,
> > > > 
> > > > On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:
> > > > 
> > > > > So, when entering a buffer that isn't loaded and the filetype is not
> > > > > detected but it was set manually before, syntax is not loaded.  I
> > > > > suppose we can fix that, as if the filetype was detected.
> > > > 
> > > > Here's an attempt to solve this issue. Since the did_filetype variable
> > > > is reset after the readfile function has returned I let the did_filetype
> > > > variable reflect the previous value of did_filetype. The patch also
> > > > includes a test case.
> > > 
> > > Thanks.
> > > 
> > > The did_filetype flag is a bit complicated to follow.  I think in this
> > > condition:
> > > 
> > > > -   if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)
> > > 
> > > You also need to check that did_filetype isn't set, otherwise the
> > > Filetype event is triggered twice.  But perhaps it will then not always
> > > trigger when you want to.  We might need another flag for that, which is
> > > always reset before loading a buffer.  did_filetype isn't always reset,
> > > as far as I can see.
> > 
> > I agree on the complexity of the statement. The attached patch uses a
> > separate variable to indicate if the filetype event was triggered or
> > not. I'm to satisfied with the solution, maybe we a more generalized way
> > to determine which events another event did trigger?
> > 
> > > Aren't there more places where readfile() is called where this is
> > > needed?  I would think what we do here is related to triggering
> > > EVENT_BUFREADPOST, which happens at the end of readfile().  Perhaps
> > > triggering Filetype should be done there.
> > 
> > I moved the logic after applying the EVENT_BUFREADPOST event.
> 
> Thanks.  I think we should reset the flag earlier, before triggering any
> autocommands when loading a buffer.  It's possible the user has setup
> another autocommand to set filetype.

I moved the reset to the very top of the readfile function and updated
some comments. But it might need to happen even earlier: prior calling
readfile?

## 

:wq

diff --git a/src/fileio.c b/src/fileio.c
index ed8d45b..0ddd079 100644
--- a/src/fileio.c
+++ b/src/fileio.c
@@ -143,6 +143,18 @@ static void vim_settempdir(char_u *tempdir);
 static char *e_auchangedbuf = N_("E812: Autocommands changed buffer or buffer name");
 #endif

+#ifdef FEAT_AUTOCMD
+/*
- \* Set by the apply_autocmds_group function if the given event is equal to
- \* EVENT_FILETYPE. Used by the readfile function in order to determine if
- \* EVENT_BUFREADPOST triggered the EVENT_FILETYPE.
- *
- \* Relying on this value requires one to reset it prior calling
- \* apply_autocmds_group.
- */
  +static int au_did_filetype INIT(= FALSE);
  +#endif
  +
   void
  filemess(
     buf_T  *buf,
  @@ -305,6 +317,10 @@ readfile(
   int        using_b_fname;
  #endif

+#ifdef FEAT_AUTOCMD
-    au_did_filetype = FALSE; /\* reset before triggering any autocommands _/
  +#endif
  +
   curbuf->b_no_eol_lnum = 0; /_ in case it was set by the previous read */
  
   /*
  @@ -2669,8 +2685,17 @@ failed:
      apply_autocmds_exarg(EVENT_FILTERREADPOST, NULL, sfname,
                            FALSE, curbuf, eap);
  else if (newfile)
-   {
      apply_autocmds_exarg(EVENT_BUFREADPOST, NULL, sfname,
                            FALSE, curbuf, eap);
-       if (!au_did_filetype && *curbuf->b_p_ft != NUL)
-       /*
-        \* EVENT_FILETYPE was not triggered but the buffer already has a
-        \* filetype. Trigger EVENT_FILETYPE using the existing filetype.
-        */
-       apply_autocmds(EVENT_FILETYPE, curbuf->b_p_ft, curbuf->b_fname,
-           TRUE, curbuf);
-   }
  else
      apply_autocmds_exarg(EVENT_FILEREADPOST, sfname, sfname,
                              FALSE, NULL, eap);
  @@ -9537,6 +9562,9 @@ BYPASS_AU:
   if (event == EVENT_BUFWIPEOUT && buf != NULL)
  aubuflocal_remove(buf);
-    if (retval == OK && event == EVENT_FILETYPE)
-   au_did_filetype = TRUE;
  +
   return retval;
  }

**Comment by mptre** [comment]
Anton Lindqvist wrote:

> > > > > Bram,
> > > > > 
> > > > > On Wed, Apr 13, 2016 at 01:20:48PM -0700, Bram Moolenaar wrote:
> > > > > 
> > > > > > So, when entering a buffer that isn't loaded and the filetype is not
> > > > > > detected but it was set manually before, syntax is not loaded.  I
> > > > > > suppose we can fix that, as if the filetype was detected.
> > > > > 
> > > > > Here's an attempt to solve this issue. Since the did_filetype variable
> > > > > is reset after the readfile function has returned I let the did_filetype
> > > > > variable reflect the previous value of did_filetype. The patch also
> > > > > includes a test case.
> > > > 
> > > > Thanks.
> > > > 
> > > > The did_filetype flag is a bit complicated to follow.  I think in this
> > > > condition:
> > > > 
> > > > > - if (retval == OK && !keep_filetype && *curbuf->b_p_ft != NUL)
> > > > 
> > > > You also need to check that did_filetype isn't set, otherwise the
> > > > Filetype event is triggered twice.  But perhaps it will then not always
> > > > trigger when you want to.  We might need another flag for that, which is
> > > > always reset before loading a buffer.  did_filetype isn't always reset,
> > > > as far as I can see.
> > > 
> > > I agree on the complexity of the statement. The attached patch uses a
> > > separate variable to indicate if the filetype event was triggered or
> > > not. I'm to satisfied with the solution, maybe we a more generalized way
> > > to determine which events another event did trigger?
> > > 
> > > > Aren't there more places where readfile() is called where this is
> > > > needed?  I would think what we do here is related to triggering
> > > > EVENT_BUFREADPOST, which happens at the end of readfile().  Perhaps
> > > > triggering Filetype should be done there.
> > > 
> > > I moved the logic after applying the EVENT_BUFREADPOST event.
> > 
> > Thanks.  I think we should reset the flag earlier, before triggering any
> > autocommands when loading a buffer.  It's possible the user has setup
> > another autocommand to set filetype.
> 
> I moved the reset to the very top of the readfile function and updated
> some comments. But it might need to happen even earlier: prior calling
> readfile?

I think this is fine, thanks.

## 

Yah, well, we had to carve our electrons out of driftwood we'd
find.  In the winter.  Uphill.  Both ways.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
