### ISSUE TITLE
Vim9: cannot omit v: prefix in v:none and v:null

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7495]
**Describe the bug**

In Vim9 script, we cannot omit the `v:` prefix for the special values `v:none` and `v:null`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        eval none
        eval null
    EOF
    )

`E121` is raised twice:

    E121: Undefined variable: none
    E121: Undefined variable: null

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2160
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Vim9 already lets us omit the `v:` prefix for the boolean values `v:true` and `v:false`, as documented at `:h true`.  Could it let us do the same thing for `v:none` and `v:null`?

**Comment by lacygoill** [comment]
> Could it let us do the same thing for v:none and v:null?

Rationale: I suppose Vim9 lets us omit `v:` for `v:true` and `v:false` to be more familiar to users coming from JavaScript and Python.  In those languages, I think they write `none` (and `null`?) without `v:`.

**Comment by lacygoill** [comment]
> In those languages, I think they write none (and null?) without v:.

Although, maybe there are some subtle differences between `none` in Vim9 and `none` in JavaScript/Python.  If so, maybe we want to keep `v:` to avoid users getting the wrong impression that they are equivalent.

**Comment by brammool** [comment]
> > Could it let us do the same thing for v:none and v:null?
> 
> Rationale: I suppose Vim9 lets us omit `v:` for `v:true` and `v:false`
> to be more familiar to users coming from JavaScript and Python.  In
> those languages, I think they write `none` (and `null`?) without `v:`.

Where in Vim script do you use v:none and v:null?  I would think it's
rare, mostly used in tests or perhaps when dealing with JSON directly.

None in Python has a very specific meaning, different from what it means
in Vim.  I don't think we should add "none" in Vim, it's meaning is not
clear.  One could do something like:

	var none: bool = false
	if list->empty()
	  none = true
	endif

The v:null value may useful if we implement objects.  Also, "null" is
used in more languages, thus users can be expected what it means and not
accidentlly use it for something else.

It would still raise questions about the semantics, but since we already
have v:null that isn't really new.  We currently consider a null list
to be equivalent to an empty list in most places.

-- 
Never under any circumstances take a sleeping pill
and a laxative on the same night.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Where in Vim script do you use v:none and v:null?  I would think it's rare, mostly used in tests or perhaps when dealing with JSON directly.

I admit I rarely use them.  I mostly use `v:null` to check the existence of an environment variable:

    const DIR = getenv('XDG_RUNTIME_VIM') == v:null ? '/tmp' : $XDG_RUNTIME_VIM
                                             ^----^

> The v:null value may useful if we implement objects.  Also, "null" is
> used in more languages, thus users can be expected what it means and not
> accidentlly use it for something else.

> It would still raise questions about the semantics, but since we already
> have v:null that isn't really new.  We currently consider a null list
> to be equivalent to an empty list in most places.

Understood.  `v:none` and `v:null` are very specific to Vim9.

**Comment by lacygoill** [comment]
> I admit I rarely use them.  I mostly use `v:null` to check the existence of an environment variable:

>     const DIR = getenv('XDG_RUNTIME_VIM') == v:null ? '/tmp' : $XDG_RUNTIME_VIM
>                                              ^----^

I've just realized that it could be simplified using the null coalescing operator:

    const DIR = getenv('XDG_RUNTIME_VIM') ?? '/tmp'
                                          ^^
