### ISSUE TITLE
Vim's `:compiler gcc` has an issue with `make: ***`

### ISSUE THREAD

**Issue by refaelsh** [vim/vim#7536]
It seems to be that Vim's `:compiler gcc` has a bug. It treats `make: ***` as an error and therefor opens an empty buffer named build.make when opening quickfix. Here is a [screenshot](https://i.stack.imgur.com/9ZDVh.png). And [here](https://pastebin.com/VudqY3qg) it is in text form.
It looks like a bug to me, but maybe I a m wrong.

**Comment by bfrg** [comment]
Can you post the entire output of your build command in text form?

**Comment by refaelsh** [comment]
Thank you for replying @bfrg. I've updated my original post with a link to the raw text.

**Comment by bfrg** [comment]
These are the problematic lines:
```
make[2]: *** [giter/CMakeFiles/giter.dir/build.make:284: giter/giter] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: giter/CMakeFiles/giter.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

You need to add the following to the `gcc` compiler file:
```vim
CompilerSet errorformat^=
        \%-Eg%\\=make[%\\d%\\+]:\ ***\ %#[%f:%l:\ %.%\\+]\ %m,
        \%-Eg%\\=make:\ ***\ [%f:%l:\ %.%\\+]\ %m,
```
Notice the `^=` which will _prepend_ the items to `errorformat`. You can copy the shipped `gcc` compiler file into your `~/.vim/compiler/gcc.vim` and then just add the three lines below.

It is import to prepend, or otherwise one of the other formats will match first. For example, with your current `errorformat`, Vim matches the line `make: *** [Makefile:103: all] Error 2` with `%f:%l: %m`. This results in a file name `make: *** [Makefile` which doesn't make sense. 

Notice the `%-E` which will remove the lines from the quickfix list. If you want to include them, just remove the minus signs in `%-E`:
```vim
CompilerSet errorformat^=
        \%Eg%\\=make[%\\d%\\+]:\ ***\ %#[%f:%l:\ %.%\\+]\ %m,
        \%Eg%\\=make:\ ***\ [%f:%l:\ %.%\\+]\ %m,
```
But since you're using a CMake-generated Makefile, you probably don't care about the Makefiles.

**Comment by refaelsh** [comment]
Thank you for the reply. The workaround you suggest will indeed work (i tried something very similar from a stack overflow post).
But, IMHO, it is an issue in Vim and should be fixed upstream.

**Comment by bfrg** [comment]
Well, technically this shouldn't be added to the `gcc` compiler file because it's not a `gcc` error. Ideally, there should be a separate compiler file for `make` (and `cmake`). Then users could combine them as needed.

**Comment by refaelsh** [comment]
I understand your answer @bfrg. Thank you very much! :-)
