### ISSUE TITLE
Vim9: crash when re-sourcing plugin manually

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7547]
**Describe the bug**

In Vim9 script, re-sourcing a plugin manually might make Vim crash.

**To Reproduce**

Run this shell command *twice*:

    vim -Nu NORC -i NONE -U NONE --cmd 'set rtp=/tmp/some' -S <(cat <<'EOF'
        vim9script
        var lines =<< trim END
            vim9script
            if exists('g:guard')
                finish
            endif
            g:guard = 1
            var name = ''
            set ls=2 stl=%!Stl()
            def g:Stl(): string
                return name
            enddef
        END
        mkdir('/tmp/some/plugin', 'p')
        writefile(lines, '/tmp/some/plugin/script.vim')
        redraw
        so /tmp/some/plugin/script.vim
    EOF
    )

Vim crashes.

The command needs to be run twice:

   - the first time, it writes some script in `/tmp/some/plugin/script.vim`
   - the second time, it causes Vim to source this script twice:

        * a first time *during* startup (because of `-Nu NORC` and `--cmd 'set rtp=...'`)
        * a second time *after* startup (because of `:source`)

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2202
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(362)

**Additional context**

Regression introduced in [8.2.1126](https://github.com/vim/vim/releases/tag/v8.2.1126).

Before that, Vim did not crash.  Instead, it raised this error:

    E1016: Cannot declare a global variable: g:statusline_winid

---

- [backtrace](https://github.com/vim/vim/files/5739057/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/5739058/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5739056/asan.log)

**Comment by lacygoill** [comment]
Sorry for the not so minimal example, but that's the best I could get.

For reference, I stumbled upon this after running this function (via a custom command):
```vim
def Func()
    PlugInstall
enddef
```
The `:PlugInstall` command [comes from here](https://github.com/junegunn/vim-plug/blob/8b45742540f92ba902c97ad1d3d8862ba3305438/plug.vim#L274).

I have no idea whether the reported crash is the same though.  When I started the debugging, and Vim crashed, it raised `E565`:

    Vim(argglobal):E565: Not allowed to change text or change window:                 argg | %argd

But quickly after starting removing code, the error was not raised anymore.  So, maybe there is another crash.  I'll have to check once this one is fixed.

**Comment by lacygoill** [comment]
> The command needs to be run twice:

That is, it needs to be run once, then `:q` to quit Vim, then re-run the same shell command.

**Comment by brammool** [comment]
The problem is reloading a script after a function was compiled, which accesses a script-local variable which was deleted because of the reloading.  That the function fails is to be expected, since the script-local variable was deleted.  But it should not crash.

**Comment by lacygoill** [comment]
Thank you for the explanation and the patch.  However:

> a script-local variable which was deleted because of the reloading.

This causes a fundamental issue.  A plugin might reload other plugins.  This is the case of the most popular plugin manager, [`vim-plug`](https://github.com/junegunn/vim-plug/blob/8b45742540f92ba902c97ad1d3d8862ba3305438/plug.vim#L299).

If script-local variables are deleted, when a plugin is reloaded either by another plugin or accidentally, its internal state is reset which might break it.  This is the case for my statusline plugin.  That's one of the reasons why plugin authors write a guard at the top of their scripts.  This is even documented at `:h 41.11`:

https://github.com/vim/vim/blob/4aab88d919168ce2ddf4845482f4cff9efa52b5b/runtime/doc/usr_41.txt#L2029-L2036

While this kind of guard worked in Vim script legacy, it no longer works in Vim9.  In Vim9, the script-local variables are reset, even if the guard prevents any further command from being executed, which is a bit surprising for someone who doesn't know how Vim9 works internally.  And functions don't seem to be deleted which might add to a user's confusion.  I guess it's their compiled code which is preserved.

And now, in addition, `E1149` is raised.

When reloading a script, instead of deleting all variables immediately, could Vim9 wait until it finds an assignment to a script-local variable?  This way, if there's a guard at the top, and a `:finish` causes the sourcing to be interrupted, the variables would be preserved.

Otherwise, how are we supposed to preserve the internal state of a plugin across reloads (be they voluntary or accidental)?

**Comment by lacygoill** [comment]
> In Vim9, the script-local variables are reset, even if the guard prevents any further command from being executed

For example, consider this snippet:
```vim
vim9script
var name = ''
def Func()
    # ...
enddef
```
And suppose that `Func()` alters the script-local variable `name` at runtime.  If there's no guard, when we resource, it's reset to an empty string, because of this statement:
```vim
var name = ''
```
But this is wrong if `Func()` had already altered its value, and needed this value to be preserved to keep working as expected.

And if there *is* a guard, same issue: Vim seems to delete all script-local variables right before reloading a script, so `name` is again – unexpectedly – reset to an empty string.

No matter what we do, `Func()` has no guarantee that the value of `name` won't be altered during a reload.

**Comment by lacygoill** [comment]
This makes me think that the current guard mechanism is one area where Vim9 could – significantly – improve Vim script legacy.   It was annoying to always have to write this at the top of a script:
```vim
let s:cpo_save = &cpo
set cpo&vim
```
And this at the bottom:
```vim
let &cpo = s:cpo_save
```
Vim9 has improved the situation.  `:vim9script` takes care of that automatically.

The same issue applies to a guard.  It's annoying to always have to write this at the top of a script:
```vim
if exists('g:guard')
    finish
endif
let g:guard = 1
```
This is a real pitfall which I suspect many plugin authors don't fully understand.  They think it's only required in a script under `plugin/`.  That's not true.  It might also be necessary in a script under `autoload/`, if the latter has an internal state in the form of script-local variables.  See [here for a real example](https://github.com/tpope/vim-dadbod/blob/4a2a8bc6dca50bc58885bdf2c0a153d0990d7872/autoload/db.vim#L1-L4).

I think Vim9 should automatically fix this issue.  The simplest fix would be to simply disallow reloading plugins.  In the future, if some people complain that they want to be able to reload a plugin (which they might do during the development phase), maybe an option could be added to `:source` and `:runtime`, such as `++reload`.  This option would force a reload which is normally disallowed.

**Comment by lacygoill** [comment]
> The simplest fix would be to simply disallow reloading plugins.

And not raise any error.  Here, an error would just be noise.  A plugin doesn't need to reload another plugin.  I don't know why `vim-plug` does it (it's not necessary for the `:PlugInstall` command).

The only case where reloading a plugin makes sense is for plugin authors while they're developing their code.  But if a plugin author writes a plugin in Vim9 script, we can expect they would take the time to at least briefly skim `:h vim9-differences`, where it could be documented that a Vim9 script can't be reloaded (unless with the aforementioned `++reload` option).

**Comment by lacygoill** [comment]
> The simplest fix would be to simply disallow reloading plugins.

Ah no, that's a bad idea.  I'm constantly reloading scripts while testing.  Unless, `++reload` is also implemented.

**Comment by lacygoill** [comment]
> Unless, ++reload is also implemented.

In which case it's still a good idea, because all you have to do is to tweak your custom mapping which resources a script (or install one if you didn't so far), to include `++reload`:

    nno <key> <cmd>source ++reload %<cr>

**Comment by lacygoill** [comment]
Obviously, if you use `++reload` to reload a script with an internal state implemented with script-local variables, the latter will probably get broken.  But that doesn't matter, because:

   - that's unavoidable
   - it was already like that in Vim script legacy

**Comment by brammool** [comment]
> > The simplest fix would be to simply disallow reloading plugins.
> 
> And not raise any error.  Here, an error would be just be noise.  A
> plugin doesn't need to reload another plugin.  I don't know why
> `vim-plug` does it (it's not necessary for the `:PlugInstall`
> command).
> 
> The only case where reloading a plugin makes sense is for plugin
> authors while they're developing their code.  But if a plugin author
> writes a plugin in Vim9 script, we can expect they would take the time
> to at least briefly skim `:h vim9-differences`, where it could be
> documented that a script can't be reloaded (unless maybe with the
> aforementioned `++reload` option).

I think it's quite normal to reload a Vim script file after making a
change.  I have an autocommand for when I write my .vimrc that reloads
it.  It does require a bit of care to make sure reloading works (this is
legacy Vim script) but usually it is fine.  And for this it's good to
clear everything the script has defined (user commands, functions,
script-local variables) and start with a clean slate.  E.g. if the
script was defining FuntionOne() and it's renamed to FunctionTwo() then
FunctionOne() should be gone after the reload.

Using some mechanism to bail out from the script is problematic.  Some
things may be done, e.g. setting buffer-local options.  But it conflicts
with the idea of reloading a script clears everything and starts with a
clean slate.  We can avoid that perhaps, but it should not be the
default.

The Vim9 mechanism for this is to use :import.  Then the imported script
will only be loaded if not loaded before.  Thus there is no need for a
"guard".

So what remains is scripts that intentionally bail out somewhere.  For
these everything should remain.  And probably no functions or
script-local variables will be redefined.  E.g. for a filetype plugin it
may set a few options and define a buffer-local mapping that calls a
script-local function:

	setlocal someoption=value
	command -buffer SomeCommand call s:SomeFunc()
	if exists('*s:SomeFunc')
	   finish
	endif
	func s:SomeFunc()
	   ...

I think the best is if we specify early on that this script bails out
and existing script-local functions and variables should remain.  Since
:vim9script is the first command we could use an argument, e.g.

	vim9script noclear

If "noclear" is omitted then this is where the script-local items are
cleared.  I think this makes sense.

-- 
How To Keep A Healthy Level Of Insanity:
7. Finish all your sentences with "in accordance with the prophecy".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> The Vim9 mechanism for this is to use :import.  Then the imported script
> will only be loaded if not loaded before.  Thus there is no need for a
> "guard".

Yes, but it doesn't fix the issue of an involuntary plugin reloading.  Reloading a small script to test a feature, or developing a small piece of code is one thing, but reloading an entire plugin is another.  I never want a plugin to be reloaded (I had enough weird bugs because of that).  If I want to test a change in a plugin, I simply restart Vim. I have a mapping which automates the whole process:

   - create a Vim session file
   - send a signal to the parent shell to restart Vim when Vim is quit
   - quit Vim (the shell restarts a new Vim instance)
   - source the session file on startup to restore the layout and the buffers

But I use `vim-plug` which – for some reason – reloads all plugins when you use some of its commands.  That's the only reason why I write an anti-reinclusion guard at the top of every script under `plugin/`, and of every script under `autoload/` if the latter uses script-local variables.  Even if `vim-plug` didn't reload plugins, I want the guarantee that no plugin will ever be reloaded.

> I think the best is if we specify early on that this script bails out
> and existing script-local functions and variables should remain.  Since
> :vim9script is the first command we could use an argument, e.g.
>
>        vim9script noclear
>
> If "noclear" is omitted then this is where the script-local items are
> cleared.  I think this makes sense.

Yes, this is much better than what I had in mind.  We can continue using `:vim9script` while testing or developing; then when we're finished, we simply write the `noclear` argument to avoid any issue if a plugin is reloaded involuntarily.

**Comment by lacygoill** [comment]
> Yes, this is much better than what I had in mind. We can continue using :vim9script while testing or developing; then when we're finished, we simply write the noclear argument to avoid any issue if a plugin is reloaded involuntarily.

I assumed that `noclear` would behave exactly like an anti-reinclusion guard.  If it does not, `noclear` will still fix the reported issue, however, we won't be able to rely on it to disallow a reloading.  If so, would it be possible to add another argument for `:vim9script`?  The `noreload` argument?

    :vim9script noreload

**Comment by lacygoill** [comment]
> If it does not

What I mean is that maybe `noclear` will prevent a function or variable to be reset, but not something else, like an autocmd for example.  In that case, we might want something stronger than `noclear`.

**Comment by lacygoill** [comment]
> I assumed that noclear would behave exactly like an anti-reinclusion guard.

And I was wrong.  If it did, we couldn't use it in a ftplugin.

So, `noclear` will be useful in a ftplugin, and `noreload` would be useful for the paranoids like me.

**Comment by brammool** [comment]
> > Yes, this is much better than what I had in mind. We can continue
> > using :vim9script while testing or developing; then when we're
> > finished, we simply write the noclear argument to avoid any issue if
> > a plugin is reloaded involuntarily.
> 
> I assumed that `noclear` would behave exactly like an anti-reinclusion
> guard.  If it does not, `noclear` will still fix the reported issue,
> however, we won't be able to rely on it to disallow a reloading.  If
> so, would it be possible to add another argument for `:vim9script`?
> The `noreload` argument?
> 
>     :vim9script noreload

Hmm, I wonder how often users will run into problems because the script
doesn't seem to work, and only discover this "noreload" argument after
looking around for a while.

If we only implement "noclear" then you can do what you want, it just
takes a few extra lines:

	vim9script noclear
	if exists('s:loaded') | finish | endif
	var s:loaded = true

And then you have the chance to do something before bailing out:

	vim9script noclear

	setlocal completefunc=Complete

	if exists('s:loaded') | finish | endif
	var s:loaded = true

	def g:Complete()

(better use an autoload function though)

We already have this pattern, thus users won't be surprised.

The "noclear" argument is also a bit obscure and something you need to
understand, but I don't see how we can make things work without it.

-- 
Now it is such a bizarrely improbable coincidence that anything as
mind-bogglingly useful as the Babel fish could have evolved purely by chance
that some thinkers have chosen to see it as a final and clinching proof of the
NON-existence of God.
The argument goes something like this: 'I refuse to prove that I exist,' says
God, 'for proof denies faith, and without faith I am nothing.'
'But,' says Man, 'the Babel fish is a dead giveaway, isn't it?  It could not
have evolved by chance.  It proves you exist, and so therefore, by your own
arguments, you don't.  QED.'
'Oh dear,' says God, 'I hadn't thought of that,' and promptly vanishes in a
puff of logic.
'Oh, that was easy,' says Man, and for an encore goes on to prove that black
is white and gets himself killed on the next pedestrian crossing.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> If we only implement "noclear" then you can do what you want, it just
> takes a few extra lines:
>
>     vim9script noclear
>     if exists('s:loaded') | finish | endif
>     var s:loaded = true

True, `noreload` was just to save a few lines.  It's not as important as `noclear`.
