### ISSUE TITLE
Error when mapping <C-]> and <C-[>

### ISSUE THREAD

**Issue by bowernite** [vim/vim#7578]
**Describe the bug**
When remapping `<C-]>` and `<C-]` in `.vimrc`, whenever you open up Vim you start in replace mode.

**To Reproduce**
1. Add the following to a `.vimrc` file:

```viml
nnoremap <C-[> <C-o>
nnoremap <C-]> <C-i>
```

2. Save the file
3. Open up a new file with vim, with a fresh launch (i.e. `vim .zshrc`)

**Expected behavior**
1. Vim opens up in normal mode
2. The mappings work as intended

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: macOS 10.15.6
 - Terminal: macOS Terminal.app

**Comment by lacygoill** [comment]
Duplicate of #3080.

---

`<Esc>` and `<C-[>` are indistinguishable in the terminal.  Mapping something to `<C-[>` is like mapping that same thing to `<Esc>`, which is a bad idea because `<Esc>` has a special and fundamental meaning in Vim, and because the terminal might send escape sequences which – as the name suggests – start with an Escape character.

During startup, the terminal probably sends one of these escape sequences, but Vim remaps it, which breaks the sequence.  What remains can do anything.

You could try to delay the problematic mapping:

    " ✘
    nnoremap <C-[> <C-o>

    " ✔
    call timer_start(100, {-> execute('nnoremap <C-[> <C-o>')})

But, FWIW, I would not recommend doing this.  It will probably cause other issues later.

It's not something that can be fixed in Vim:

> Mapping is expected to cause problems. It may work in some specific situations (e.g. in the GUI), but it if fails then just don't use it. It's not something that can be fixed in Vim.

[source](https://github.com/vim/vim/issues/2216#issuecomment-640062576)

**Comment by bowernite** [comment]
Got it. I'll have to find a different substitute for `<C-o>` and `<C-i>` then.

Thanks for taking the time 🙂
