### ISSUE TITLE
Vim9: no error when extending number dictionary with mixed values

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7593]
**Describe the bug**

In Vim9 script, extending a dictionary of numbers with a dictionary of mixed values (e.g. strings, booleans) doesn't raise any error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            extend({a: 1}, {b: 'x', c: true})
        enddef
        Func()
    EOF
    )

No error is raised.

**Expected behavior**

`E1013` is raised:

    E1013: Argument 2: type mismatch, expected dict<number> but got dict<any>

Because `{a: 1}` is a dictionary of numbers, while `{b: 'x', c: true}` is a dictionary of strings and booleans.  The result has the type `dict<any>` which no longer matches the original type `dict<number>` of `{a: 1}`.

**Environment**

 - Vim version: 8.2 Included patches: 1-2253
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

Regression introduced in [8.2.1996](https://github.com/vim/vim/releases/tag/v8.2.1996).

---

Same issue at the script level:
```vim
vim9script
extend({a: 1}, {b: 'x', c: true})
```
No error is raised.

Although this time, I don't think it's a regression. I think type checking never worked as expected here.

---

Patch adding a test.
```diff
diff --git a/src/testdir/test_vim9_builtin.vim b/src/testdir/test_vim9_builtin.vim
index accbca237..73a40593a 100644
--- a/src/testdir/test_vim9_builtin.vim
+++ b/src/testdir/test_vim9_builtin.vim
@@ -234,6 +234,8 @@ def Test_extend_arg_types()
   extend(res, map([1, 2], (_, v) => ({})))
   assert_equal([{}, {}], res)
 
+  assert_fails('extend({a: 1}, {b: "x", c: true})', 'E1013:')
+
   CheckDefFailure(['extend([1, 2], 3)'], 'E1013: Argument 2: type mismatch, expected list<number> but got number')
   CheckDefFailure(['extend([1, 2], ["x"])'], 'E1013: Argument 2: type mismatch, expected list<number> but got list<string>')
   CheckDefFailure(['extend([1, 2], [3], "x")'], 'E1013: Argument 3: type mismatch, expected number but got string')
@@ -241,6 +243,7 @@ def Test_extend_arg_types()
   CheckDefFailure(['extend({a: 1}, 42)'], 'E1013: Argument 2: type mismatch, expected dict<number> but got number')
   CheckDefFailure(['extend({a: 1}, {b: "x"})'], 'E1013: Argument 2: type mismatch, expected dict<number> but got dict<string>')
   CheckDefFailure(['extend({a: 1}, {b: 2}, 1)'], 'E1013: Argument 3: type mismatch, expected string but got number')
+  CheckDefFailure(['extend({a: 1}, {b: "x", c: true})'], 'E1013: Argument 2: type mismatch, expected dict<number> but got dict<any>')
 enddef
 
 def Test_extend_return_type()
```

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, extending a dictionary of numbers with a dictionary of
> mixed values (e.g. strings, booleans) doesn't raise any error.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             extend({a: 1}, {b: 'x', c: true})
>         enddef
>         Func()
>     EOF
>     )

This specific example doesn't explicitly say that it is a dictionary of
numbers.  One might argue that the type is only created after calling
extend().

A better example:

   var d: dict<number> = {a: 1}
   extend(d, {b: 'x', c: true})

Still no error is given, not even at runtime, although the dictionary
now doesn't match the type.  This can cause a crash:

   var d: dict<number> = {a: 1}
   extend(d, {b: 'x', c: true})
   for key in d->keys()
     echo d[key] + 5
   endfor


> Because `{a: 1}` is a dictionary of numbers, while `{b: 'x', c: true}`
> is a dictionary of strings and booleans.  The result has the type
> `dict<any>` which no longer matches the original type `dict<number>`
> of `{a: 1}`.

So we would need to check that extend() doesn't violate the type.  I was
aware of this problem, but not yet sure how to fix it.  Check the result
after calling extend() would be slow, especially when extending a large
dictionary.

Probably the best solution is to pass the required type to the builtin
function and let extend() check the type internally.  However, the
generic mechanism for calling a builtin function doesn't support this,
and we only need it for a few functions.

So we probably need to check when compiling that the type of the second
extend() argument is OK.

At the script level it might be more complicated.  When evaluating the
first argument we would need to pass the type together with the value.
That mechanism doesn't exist yet.  We'll need to add it, otherwise the
crash mentioned above could still happen.  Or we would always need to
check the type when getting an item from a list or dictionary, which is
inefficient.

-- 
hundred-and-one symptoms of being an internet addict:
78. You find yourself dialing IP numbers on the phone.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> This specific example doesn't explicitly say that it is a dictionary of
> numbers.  One might argue that the type is only created after calling
> extend().

I wasn't sure when I posted, but now I think you're right.  `{a: 1}` is not used in a variable declaration.  It's just an expression.  There is no reason to enforce type checking here.

---

> Still no error is given, not even at runtime, although the dictionary
> now doesn't match the type.  This can cause a crash:

>    var d: dict<number> = {a: 1}
>    extend(d, {b: 'x', c: true})
>    for key in d->keys()
>      echo d[key] + 5
>    endfor

Yes, it still crashes in a `:def` function on 8.2.2269:
```vim
vim9script
def Func()
    var d: dict<number> = {a: 1}
    extend(d, {b: 'x', c: true})
    for key in d->keys()
        echo d[key] + 5
    endfor
enddef
Func()
```
The crash started from [8.2.0730](https://github.com/vim/vim/releases/tag/v8.2.0730).

When instrumented by valgrind, Vim doesn't crash; instead, an internal error is raised:

    E685: Internal error: get_var_special_name()
    42

Not sure why `42` is echo'ed afterward.

Logs:

   - [backtrace](https://github.com/vim/vim/files/5759732/backtrace.txt)
   - [valgrind log](https://github.com/vim/vim/files/5759733/valgrind.log)
   - [asan log](https://github.com/vim/vim/files/5759731/asan.log)
