### ISSUE TITLE
Vim9: cannot install and execute custom Ex command from :def function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7618]
**Describe the bug**

In Vim9 script, we cannot install and execute a custom Ex command from the same `:def` function.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            com -nargs=1 Cmd echom <q-args>
            Cmd 123
        enddef
        Func()
    EOF
    )

`E476` is raised:

    E476: Invalid command: Cmd 123

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2298
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

No error is raised when the command is installed and executed from a legacy function:
```vim
vim9
fu Func()
    com -nargs=1 Cmd echom <q-args>
    Cmd 123
endfu
Func()
```
    123

No error is raised when the command is installed at the script level, then executed from a `:def` function:
```vim
vim9
com -nargs=1 Cmd echom <q-args>
def Func()
    Cmd 123
enddef
Func()
```
    123

No error is raised when the command is installed and executed from the script level:
```vim
vim9
com -nargs=1 Cmd echom <q-args>
Cmd 123
```
    123

No error is raised when the command is installed and executed from 2 different `:def` functions:
```vim
vim9
def Install()
    com -nargs=1 Cmd echom <q-args>
enddef
Install()
def Execute()
    Cmd 123
enddef
Execute()
```
    123

---

Regression introduced in [8.2.1156](https://github.com/vim/vim/releases/tag/v8.2.1156).

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot install and execute a custom Ex command from
> the same `:def` function.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9
>         def Func()
>             com -nargs=1 Cmd echom <q-args>
>             Cmd 123
>         enddef
>         Func()
>     EOF
>     )
> 
> `E476` is raised:
> 
>     E476: Invalid command: Cmd 123
> 
> **Expected behavior**
> 
> No error is raised.

It is expected to fail, because at compile time the command is not
defined yet, and therefore unknown.

You already mentioned several alternatives.  Another way would be to not
give an error at compile time but only when the function is executed.
However, that defies the idea of checking for valid commands at compile
time.

Defining a user command and using it right away is uncommon, thus I
don't think dropping the compile time check is a good solution.

A simple and clear way to postpone the check to until the function is
executed is using :exe:

         def Func()
             com -nargs=1 Cmd echom <q-args>
             exe 'Cmd 123'
         enddef

If this is an acceptable solution you can close the issue.

-- 
I AM THANKFUL...
...for the clothes that fit a little too snug because it
means I have more than enough to eat.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> If this is an acceptable solution you can close the issue.

It is; thank you for the explanation.
