### ISSUE TITLE
Vim9: cannot use "map()" to change type of unassigned expression

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7655]
**Describe the bug**

In Vim9 script, we cannot use `map()` to change the type of an unassigned expression.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            map([0], (_, v) => 'x')
        enddef
        Func()
    EOF
    )

`E1012` is raised:

    E1012: Type mismatch; expected list<number> but got list<string>

**Expected behavior**

No error is raised, because `[0]` was never assigned to any variable with a declared type.

**Environment**

 - Vim version: 8.2 Included patches: 1-2327
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

This is caused by [8.2.2325](https://github.com/vim/vim/releases/tag/v8.2.2325).

---

This is inconsistent with `extend()`:
```vim
vim9
def Func()
    echo extend([0], ['x', true])
enddef
Func()
```
    [0, 'x', true]

Notice that `extend()` did not complain when we changed the type of `[0]`, which is `list<number>`, into `list<any>`.  IMO, the behavior of `extend()` is correct, because `[0]` was never assigned to any variable with a declared type.  Type checking should only be concerned with the types we have explicitly written.  See also [this comment](https://github.com/vim/vim/issues/7593#issuecomment-753351473):

   > One might argue that the type is only created after calling extend().

---

This is inconsistent with what happens at the script level, where the same code does not raise any error:
```vim
vim9
map([0], (_, v) => [])
```
    ✔

---

I like type checking; it has helped me find and fix bugs in legacy code I would never have caught by myself.  But I think this is too much.  The purpose of type checking should be to check that once we say "the variable X has the type Y", the variable X keeps the type Y for its entire life.  What we do with an undeclared and unassigned expression should be of no concern to type checking.

Suppose that we want to build a custom list of dictionaries with some info about the windows in the current tabpage; for example their height and width.  We could write something like this:
```vim
vim9
def GetInfoAboutOneWindow(v: number): dict<number>
    return {height: winheight(v), width: winwidth(v)}
enddef
def GetInfoAboutAllWindows(): list<dict<number>>
    return range(1, winnr('$'))->map((_, v) => GetInfoAboutOneWindow(v))
enddef
echo GetInfoAboutAllWindows()
```
    E1012: Type mismatch; expected list<dict<number>> but got list<number>

Why does it matter that we've changed the type of `range(1, winnr('$'))`?  Which kind of error will it help us find?  It was only used temporarily in the middle of a computation to get the right expression.

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot use `map()` to change the type of an unassigned expression.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9
>         def Func()
>             map([0], (_, v) => 'x')
>         enddef
>         Func()
>     EOF
>     )
> 
> `E1012` is raised:
> 
>     E1012: Type mismatch; expected list<number> but got list<string>
> 
> **Expected behavior**
> 
> No error is raised, because `[0]` was never assigned to any variable
> with a declared type.

Does that really matter?  Compare these two:

	var l = [0]
	map(l, Func)
and:
	map([0], Func)

Do you expect them to behave differently?  That would be hard to
explain.  It can easily get more complicated:

	map(GetList(), Func)

Now you can't see where the list is coming from.  Can the item type be
changed or not?

What I did now was use the rule that map() can change the item value,
but not the type.  If you want to change the type, use mapnew().

It may not be perfect, but at least it's a simple rule.


> This is inconsistent with `extend()`:
> ```vim
> vim9
> def Func()
>     echo extend([0], ['x', true])
> enddef
> Func()
> ```
>     [0, 'x', true]
> 
> Notice that `extend()` did not complain when we changed the type of
> `[0]`, which is `list<number>`, into `list<any>`.  IMO, the behavior
> of `extend()` is correct, because `[0]` was never assigned to any
> variable with a declared type.  Type checking should only be concerned
> with the types we have explicitly written.  See also [this
> comment](https://github.com/vim/vim/issues/7593#issuecomment-753351473):

That looks like a bug, since this does give an error:
     echo extend([0], ['x'])

E1013: Argument 2: type mismatch, expected list<number> but got list<string>

Including "true" makes the argument a list<any> and passing that should
be an error, but isn't.

> This is inconsistent with what happens at the script level, where the same code does not raise any error:
> ```vim
> vim9
> map([0], (_, v) => [])
> ```

That should be fixed.  Especially when used like this:

	var l: list<number> = [0]
	map(l, (_, v) => [])

Which is similar to a previous bug that caused a crash.  It's difficult
to make it work for "[0]" and fail for "l".

> I like type checking; it has helped me find bugs in legacy code I
> would never have caught by myself.  But I think this is too much.  The
> purpose of type checking should be to check that once we say "the
> variable X has the type Y", the variable X keeps the type Y for its
> entire life.  What we do with an undeclared and unassigned expression
> should be of no concern to type checking.

The counter argument is that the rules should not depend on where a
value comes from, whether it's a literal or from a variable.  It makes
the rules hard to understand.  And also difficult to implement, we would
need to keep track where a value came from.

> Suppose that we want to build a custom list of dictionaries with some
> info about the windows in the current tabpage; for example their
> height and width.  We could write something like this:
> ```vim
> vim9
> def GetInfoAboutOneWindow(v: number): dict<number>
>     return {height: winheight(v), width: winwidth(v)}
> enddef
> def GetInfoAboutAllWindows(): list<dict<number>>
>     return range(1, winnr('$'))->map((_, v) => GetInfoAboutOneWindow(v))
> enddef
> echo GetInfoAboutAllWindows()
> ```
>     E1012: Type mismatch; expected list<dict<number>> but got list<number>
> 
> Why does it matter that we've changed the type of `range(1,
> winnr('$'))`?  Which kind of error will it help us find?  It was only
> used temporarily in the middle of a computation to get the right
> expression.

Should be no problem to use mapnew() here.


-- 
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
A: Top-posting.
Q: What is the most annoying thing on usenet and in e-mail?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
OK, fair enough.  I'll use `mapnew()`.  As a benefit, it will make the code a little more readable:  when we read `map()`, we know that the type doesn't change; when we read `mapnew()` there is a good chance that the type changes.

I keep the issue open for the other inconsistencies which were mentioned in the original post, but if you prefer that I open separate issues because it's too confusing, let me know.

**Comment by lacygoill** [comment]
I'm closing the issue because `map()` is working as intended, and the last 2 inconsistencies have now been included in the todo list:

https://github.com/vim/vim/blob/9567efa1b4a41baca9b2266f5903d5dda7ad1e88/runtime/doc/todo.txt#L41-L49
