### ISSUE TITLE
Whitespaces making Ruby syntax highlighting slow

### ISSUE THREAD

**Issue by jglauche** [vim/vim#766]
Hello,

I've encountered this bug today and it might relate to https://github.com/vim/vim/issues/282 .

I'm running vim 7.4 on Ubuntu.

To reproduce: 
create an empty test.rb file, insert
puts "Hello world" 
and hold spacebar for a while. It gets slower and slower and slower. Any cursor move will be unusably slow. 

I can edit the file normally when I turn syntax highlighting off. Also, I have tested this will all plugins disabled.

In my case this happened when a file suddenly had lots of whitespaces behind a line.

**Comment by petermlm** [comment]
I'm running vim 7.4 on my mac. I can confirm this issue.

I've seen something similar happen when I leave trailing white space in very big lines. The thing is, I have  something in my vimrc that highlights trailing white space because I hate it so much. If I try to edit a big line with trailing white space and that feature is turned on, I also get this slow behaviour.

Anyway, the cause of this bug might be related with the ruby's highlight file. By doing:

```
setf plaintext
```

The slow behaviour goes away.

**Comment by chrisbra** [comment]
please discuss with syntax script maintainer, the issue should be vim-ruby/vim-ruby#243

thanks.
