### ISSUE TITLE
":vert ba" and ":ba" reset 'scb' if there are more than 2 windows

### ISSUE THREAD

**Issue by lkintact** [vim/vim#7676]
**Describe the bug**
Executing `:vertical :ball` after `:ball` (and vice versa) resets `'scrollbind'` for the first N-2 windows if N is more than 2.

**To Reproduce**
1. Run `gvim --clean 1.txt 2.txt 3.txt` (Files: [1.txt](https://github.com/vim/vim/files/5814485/1.txt), [2.txt](https://github.com/vim/vim/files/5814488/2.txt), [3.txt](https://github.com/vim/vim/files/5814489/3.txt))
2. Execute `:ball`
3. Set `'scrollbind'` for all the windows with `:windo set scrollbind`, check that it's set with `:windo set scrollbind?`
5. Execute `:vertical :ball`. The windows get rearranged vertically
6. Execute `:windo set scrollbind?`. `'scrollbind'` for the window with `1.txt` is off.

**Expected behavior**
`'scrollbind'` for that window should be on.

**Environment**
 - Vim version 8.2.2332
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Additional context**
Same happens if it's `:vertical :ball` at step 2 and `:ball` at step 4.

**Comment by brammool** [comment]
Using :ball closes and creates windows as needed.  There is no guarantee that window-local options are preserved.
Since the commands used here change the window layout some windows will be closed and then windows are split to show the right buffers.
The 'scrollbind' option is window-local, not buffer-local, thus the closing and opening of windows cause it to be back at the default.  That is not really a bug.
