### ISSUE TITLE
Vim9: removing items from list on which we iterate gives unexpected results

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7683]
**Describe the bug**

In Vim9 script, removing items from a list on which we iterate might give unexpected results.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var l = ['a', 'b', 'c', 'd']
            for s in l
                echom l
                remove(l, index(l, s))
            endfor
        enddef
        Func()
    EOF
    )

It outputs these 2 lists:

    ['a', 'b', 'c', 'd']
    ['b', 'c', 'd']

**Expected behavior**

It outputs these 4 lists:

    ['a', 'b', 'c', 'd']
    ['b', 'c', 'd']
    ['c', 'd']
    ['d']

**Environment**

 - Vim version: 8.2 Included patches: 1-2352
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

At the script level, the exact same code prints 4 lists:
```vim
vim9
var l = ['a', 'b', 'c', 'd']
for s in l
    echom l
    remove(l, index(l, s))
endfor
```
    ['a', 'b', 'c', 'd']
    ['b', 'c', 'd']
    ['c', 'd']
    ['d']

Same thing if the `:for` loop is in a legacy function:
```vim
vim9
fu Func()
    let l = ['a', 'b', 'c', 'd']
    for s in l
        echom l
        call remove(l, index(l, s))
    endfor
endfu
Func()
```
    ['a', 'b', 'c', 'd']
    ['b', 'c', 'd']
    ['c', 'd']
    ['d']

**Comment by lacygoill** [comment]
I found this while refactoring an old plugin.  I'm not sure why I was using `remove()` in a `:for` loop.  I got rid of the loop, and replaced it with a more straightforward `filter()`, which makes much more sense.

Feel free to close the issue if it can't be fixed, or if it's working as intended.  Although, in that case, we might want to document this somewhere at `:h vim9-gotchas`, because it still looks unexpected.

**Comment by brammool** [comment]
The legacy :for implementation has code to keep a reference to the next item, so that when the current item is removed from the list we can still find the next item.  However, this adds quite a bit of overhead.  And when deleting an item further on in the list it would still be skipped.
I think that changing a list while it's been iterated over is quite rare, and doesn't justify adding overhead to make it work.  In case you know the list is going to change, it's easy enough to make a copy first.
So I tend to think that documenting the difference from legacy script is better than trying to fix it (which would add overhead on every :for statement).

**Comment by lacygoill** [comment]
Yes, I agree.  This is a corner case which doesn't warrant a fix; *maybe* just some documentation.  I say maybe because we can't document every corner case; not sure whether people would encounter this one often.  If we're removing items inside a loop, we probably would be better using `filter()`.

Just some data point: out of the 1167 functions I've refactored so far, I never encountered this issue, except in 1 function.  And even then, the code was awkward and ugly.  Using `filter()` made the code much easier to read.

**Comment by lacygoill** [comment]
Fixed by https://github.com/vim/vim/commit/98a29d00a48e15a50e2850e1a29b7d475c531b0c.
