### ISSUE TITLE
Vim9: cannot assign output of function returning boolean number to boolean variable

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7693]
**Describe the bug**

In Vim9 script, we cannot assign the output of a function returning a boolean number to a boolean variable.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            var x: bool = buflisted('')
        enddef
        defcompile
    EOF
    )

`E1012` is raised:

    E1012: Type mismatch; expected bool but got number

**Expected behavior**

No error is raised, because the output of `buflisted()` is a boolean number.

**Environment**

 - Vim version: 8.2 Included patches: 1-2365
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

At the script level, no error is raised, which is inconsistent:
```vim
vim9
var x: bool = buflisted('')
```
    no error

---

The same issue applies to `bufloaded()`, `bufexists()`, `exists()`, `assert_equal()`, ...

*If* this is a bug, should I report every affected function in a separate report?

---

I've mainly encountered this issue with `exists()`.  However, `exists()` is a special case.  If we look at the start of the help, it seems that it only returns a boolean number:

https://github.com/vim/vim/blob/e2edc2ed4a9a229870b1e1811b0ecf045b84e429/runtime/doc/eval.txt#L4287-L4288

But if we scroll down a little, we find out that it can also return the numbers `2` and `3`:

https://github.com/vim/vim/blob/e2edc2ed4a9a229870b1e1811b0ecf045b84e429/runtime/doc/eval.txt#L4321-L4328

Still, most of the time `exists()` outputs a boolean number.  So, it would be nice if we could directly save its output in a boolean variable, without having to use a ternary operator:

    var x: bool = exists(...) ? true : false
                              ^------------^

**Comment by brammool** [comment]
> In Vim9 script, we cannot assign the output of a function returning a
> boolean number to a boolean variable.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9
>         def Func()
>             var x: bool = buflisted('')
>         enddef
>         defcompile
>     EOF
>     )
> 
> `E1012` is raised:
> 
>     E1012: Type mismatch; expected bool but got number
> 
> **Expected behavior**
> 
> No error is raised, because the output of `buflisted()` is a boolean number.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-2365
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(363)
> 
> **Additional context**
> 
> At the script level, no error is raised, which is inconsistent:
> ```vim
> vim9
> var x: bool = buflisted('')
> ```
>     no error
> 
> ---
> 
> The same issue applies to `bufloaded()`, `bufexists()`, `exists()`,
> `assert_equal()`, ...
> 
> *If* this is a bug, should I report every affected function in a
> separate report?

This is actually quite tricky, since the function returns zero or one,
which may then be used as a number or a bool.  Fortunately we do have a
mechanism for that.  Now we need to find all the functions where we
should do this...

I'll leave writing tests to someone else.

-- 
In Joseph Heller's novel "Catch-22", the main character tries to get out of a
war by proving he is crazy.  But the mere fact he wants to get out of the war
only shows he isn't crazy -- creating the original "Catch-22".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
