### ISSUE TITLE
map dd "_dd makes Vim freeze

### ISSUE THREAD

**Issue by iio7** [vim/vim#7716]
This problem persists on Vim 8.2. I have tested on Arch Linux 5.10.8 and Ubuntu Bionic.

The problem is gone using `vim -u DEFAULTS`.

I have tested this on latest release of both xterm and st.

Mapping both `d` and `dd` to the black hole with:

```
map d "_d
map dd "_dd
```

Pressing "dd" to delete a line causes both Vim to freeze and use 100% CPU.

This works:

```
noremap d "_d
noremap dd "_dd
```

AFAIK "map" and "noremap" are identical.

**Comment by nickspoons** [comment]
> AFAIK "map" and "noremap" are identical.

`:map` and `:noremap` are **not** identical. `:noremap` means **no**n **re**cursive **map**.

Your mapping `:map d "_d` is causing Vim to freeze because it is causing an infinite recursive loop.

Rule of thumb: only ever use non-recursive mappings, unless you have a particular reason to want a recursive mapping (e.g. mapping to a `<Plug>` mapping provided by a plugin)

**Comment by iio7** [comment]
Sorry, I had completely misunderstood the "Overview of which map command works in which mode" in the help, as synonyms!
