### ISSUE TITLE
Vim9: variable shadowing Ex command cannot be followed by method call preceded by whitespace

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7725]
**Describe the bug**

In Vim9 script, a variable shadowing an Ex command name cannot be followed by a method call preceded by a whitespace.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        var yank = 'string'
        yank ->copy()
    EOF
    )

`E488` is raised:

    E488: Trailing characters: >copy():     yank ->copy()

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2389
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

If the whitespace is removed in front of `->`, then the code no longer raises any error:
```vim
vim9
var yank = 'string'
yank->copy()
```
    no error

---

I think this is a bug for 2 reasons:

   - the help says that a variable can shadow an Ex command; but it does not say that this shadowing is conditional:

       https://github.com/vim/vim/blob/9b6344613eecfcf77c510d7b63fcc4b7b51aefbc/runtime/doc/vim9.txt#L277

   - a shadowing conditioned on the absence of a following whitespace is confusing and error-prone

**Comment by lacygoill** [comment]
The original code might look contrived, because it doesn't do anything useful.  Here is a slightly less useless snippet, which still reproduces the issue:
```vim
vim9
var yank = 'string'
yank ->strchars()->setline(1)
```
    E488: Trailing characters: >strchars()->setline(1): yank ->strchars()->setline(1)

**Comment by brammool** [comment]
> In Vim9 script, a variable shadowing an Ex command name cannot be
> followed by a method call preceded by a whitespace.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9
>         var yank = 'string'
>         yank ->copy()
>     EOF
>     )
> 
> `E488` is raised:
> 
>     E488: Trailing characters: >copy():     yank ->copy()
> 
> **Expected behavior**
> 
> No error is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-2389
>  - OS: Ubuntu 16.04.7 LTS
>  - Terminal: xterm(363)
> 
> **Additional context**
> 
> If the whitespace is removed in front of `->`, then the code no longer
> raises any error:
> ```vim
> vim9
> var yank = 'string'
> yank->copy()
> ```
>     no error
> 
> ---
> 
> I think this is a bug for 2 reasons:
> 
>    - the help says that a variable can shadow an Ex command; but it does not say that this shadowing is conditional:
> 
>        https://github.com/vim/vim/blob/9b6344613eecfcf77c510d7b63fcc4b7b51aefbc/runtime/doc/vim9.txt#L277
> 
>    - a shadowing conditioned on the absence of a following whitespace
>    is confusing and error-prone

This is unrelated to shadowing, using another variable name has the same
error.

I don't see a good reason to forbid white space before or after the
"->".  I recall we had this to avoid confusion when using a lambda, but
that now uses "=>".

-- 
I noticed my daughter's Disney-net password on a sticky note:
"MickeyMinnieGoofyPluto".  I asked her why it was so long.
"Because they say it has to have at least four characters."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
