### ISSUE TITLE
Vim9: no error when passing number to "str2nr()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7759]
**Describe the bug**

In Vim9 script, passing a number to `str2nr()` doesn't raise any error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        def Func()
            echo str2nr(123)
        enddef
        Func()
    EOF
    )

No error is raised.

**Expected behavior**

An error is raised:

    E1234: using Number as a String

Because `str2nr()` expects a string, not a number.

**Environment**

 - Vim version: 8.2 Included patches: 1-2427
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

When a float is passed to `str2float()`, an error is correctly raised:
```vim
vim9
def Func()
    echo str2float(1.23)
enddef
Func()
```
    E806: using Float as a String

This is inconsistent.  If it's an error to pass a float to `str2float()`, it should be an error to pass a number to `str2nr()`.

---

I guess that Vim automatically coerces a number into a string when passed to `str2nr()`.  This looks wrong; Vim9 is usually very strict regarding values passed to a function.

Example:
```vim
vim9
lh grail
def Func()
    for match in getloclist('.')
    endfor
enddef
Func()
```
    E1030: Using a String as a Number: "."

Notice how Vim didn't allow `'.'` to be coerced into the number `0`, like in legacy Vim script.
Similarly, Vim shouldn't allow a number to be coerced into a string when it's passed to `str2nr()`.

**Comment by lacygoill** [comment]
After making more tests, I found 3 other issues:
```vim
vim9
echo str2float(123)
```
    123.0

An error should be raised because `str2float()` expects a string, not a number.

---

```vim
vim9
def Func()
    echo str2float(123)
enddef
Func()
```
    123.0

An error should be raised at compile time:

    E1013: Argument 1: type mismatch, expected string but got number

---
```vim
vim9
def Func()
    echo str2float(1.23)
enddef
Func()
```
    E806: using Float as a String

This error is raised at runtime.  It should have been raised at compile time:

    E1013: Argument 1: type mismatch, expected string but got float

I can open separate issues if necessary.

**Comment by lacygoill** [comment]
Regarding the last 2 issues, I guess they're part of this todo item:

> - Check many more builtin function arguments at compile time.

There are 518 builtin functions according to this:

    echo getcompletion('*', 'function')->filter({_, v -> v[0] =~# '[a-z]' && v !~ '#'})->len()

And 12 types of values according to this:

    echo getcompletion('v:t_', 'help')->len()

That's 6216 tests to conduct.  Not sure I can, but one day I'll try to write a script to automatically generate 1 small snippet for each test.  The tricky part will be to parse the results, and only keep the ones with an unexpected output.

**Comment by lacygoill** [comment]
> That's 6216 tests to conduct.

Well not exactly that number.  Some functions don't expect any argument; others accept or expect several.

**Comment by brammool** [comment]
> Regarding the last 2 issues, I guess they're part of this todo item:
> 
> > - Check many more builtin function arguments at compile time.
> 
> There are 518 builtin functions according to this:
> 
>     echo getcompletion('*', 'function')->filter({_, v -> v[0] =~# '[a-z]' && v !~ '#'})->len()
> 
> And 12 types of values according to this:
> 
>     echo getcompletion('v:t_', 'help')->len()
> 
> That's 6216 tests to conduct.  Not sure I can, but one day I'll try to
> write a script to automatically generate 1 small snippet for each
> test.  The tricky part will be to parse the results, and only keep the
> ones with an unexpected output.

Yes, this is a lot of work.  And it requires to manually check the help
for the intended usage, write a test to check the function works as
documented, and then perhaps adjust the help and/or the code.

I've been wondering about how to best write tests that take care of the
three possible situation:
-  legacy Vim script (script and function level use the same code, thus
   should not need a separate test).
-  Vim9 script at the script level (interpreted)
-  Vim9 script in a :def function (compiled)


I made an attempt in test_profile, where RunProfileFunc() can be run in
two ways, which could easily be changed to three ways.  This uses XXX
for "func" or "def", DDD for a delcaration with "let" or "var" and AAA
for an assignment: "let" or nothing.  This could be generalized.

It's probably best to test the three variants in one place, instead of
have three scripts that test all the functions.  Thus we need to
refactor test_vim9_builtin.vim at least.

Having a test file for each builtin function will result in an awful
large number of test files.  We need a way to group them somehow, not
sure yet what the best is for that.  It should be easy to find the test
file if you know the function name.

-- 
The greatest lies of all time:
  (1) The check is in the mail.
  (2) We have a really challenging assignment for you.
  (3) I love you.
  (4) All bugs have been fixed.
  (5) This won't hurt a bit.
  (6) Honey, I just need to debug this program and be home in 5 minutes.
  (7) I have just sent you an e-mail about that.
  (8) Of course I'll respect you in the morning.
  (9) I'm from the government, and I'm here to help you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
