### ISSUE TITLE
setpos() does not set position for non-current buffer

### ISSUE THREAD

**Issue by noscript** [vim/vim#7784]
**Describe the bug**
`setpos() ` ignores `bufnum` argument and sets the position for the current buffer instead.

**To Reproduce**
1. Run VIM: `vim -g -u NONE +'h options.txt | split | h eval.txt'`
2. List buffers: 
```
:ls!
  1  a   "[No Name]"                    line 1
  2u#a-  "options.txt"                  line 1
  3u%a-  "eval.txt"                     line 1
```
3. Set the cursor for non-current buffer `2` to line `100`:
```vim
call setpos('.', [2, 100, 1, 1])
```
4. List buffers again:
```
:ls!
  1  a   "[No Name]"                    line 1
  2u#a-  "options.txt"                  line 1
  3u%a-  "eval.txt"                     line 100
```

**Expected behavior**
Buffer `2` cursor position is on line `100`.

**Actual behavior**
Current buffer `3` cursor position is on line `100`.

**Environment**
 - Vim version: 8.1.2466
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by jottkaerr** [comment]
From `:help setpos()`:

		For setting the cursor and the ' mark "bufnum" is ignored,
		since these are associated with a window, not a buffer.

**Comment by lacygoill** [comment]
To set the cursor position in a different window, you can use [`:h win_execute()`](https://vimhelp.org/eval.txt.html#win_execute()):

    vim -Nu NONE -g -S <(cat <<'EOF'
        h options.txt
        split
        h eval.txt
        let id = bufwinid(2)
        call win_execute(id, ['call setpos(".", [0, 100, 1, 1])', 'redraw'])
    EOF
    )

**Comment by S0AndS0** [comment]
@lacygoill `win_execute` combo-ed with `bufwinid` works for splits in active window/tab(s), which is fantastic and I may be using it in one of the plugins I'm maintaining!

...  But `win_execute` do not so nice when `bufwinid` tries to target an inactive buffer;

```bash
vim -Nu NONE -g -S <(cat <<'EOF'
e background.txt
e foreground.txt
ls
echo "bufwinid(bufnr('background.txt')) -> " . bufwinid(bufnr('background.txt'))
echo "bufwinid(bufnr('foreground.txt')) -> " . bufwinid(bufnr('foreground.txt'))
EOF
)
```

**Output example**

```
"foreground.txt" [New]
  1 #    "background.txt"               line 1
  2 %a   "foreground.txt"               line 1
bufwinid(bufnr('background.txt')) -> -1
bufwinid(bufnr('foreground.txt')) -> 1000 
```

Hunting about in the related docs I thought maybe `win_findbuf({bufnr})` could work, and maybe it could for tabs, but tragically it returns an empty list for a background buffer;

```bash
vim -Nu NONE -g -S <(cat <<'EOF'
e background.txt
e foreground.txt
ls
echo "win_findbuf(bufnr('background.txt')) ->" . string(win_findbuf(bufnr('background.txt')))
echo "win_findbuf(bufnr('foreground.txt')) ->" . string(win_findbuf(bufnr('foreground.txt')))
EOF
)
```

**Output example**

```
"foreground.txt" [New]
  1 #    "background.txt"               line 1
  2 %a   "foreground.txt"               line 1
win_findbuf(bufnr('background.txt')) ->[]
win_findbuf(bufnr('foreground.txt')) ->[1000] 
```

> All of which I think _should_ be expected behavior :shrug: considering `win_` stuff is intended to operate on windows, and inactive buffers ain't gonna be attached to any windows.

I've toyed about in the past with doing questionable things like switching active buffer out, doing a move, and switching back.  But that feels gross and may lead to _racy_ conditions were a user of such a plugin to continue typing.

Ideally `setpos` would respect the `bufnum` option, if the buffer exists, regardless of active state; or throw an error if `bufnum` does not exist.  Because this would align with what I understand the documentation is saying;

```help
setpos({expr}, {list})					*setpos()*
		Set the position for String {expr}.  Possible values:
			.	the cursor
			'x	mark x

		{list} must be a |List| with four or five numbers:
		    [bufnum, lnum, col, off]
		    [bufnum, lnum, col, off, curswant]

		"bufnum" is the buffer number.  Zero can be used for the
		current buffer.  When setting an uppercase mark "bufnum" is
		used for the mark position.  For other marks it specifies the
		buffer to set the mark in.  You can use the |bufnr()| function
		to turn a file name into a buffer number.
		For setting the cursor and the ' mark "bufnum" is ignored,
		since these are associated with a window, not a buffer.
		Does not change the jumplist.
...
```

---

But enough complaining and wishing! (That's what [SO](https://stackoverflow.com/questions/2982501/vim-how-to-scroll-to-bottom-of-a-named-buffer) be for X-))

Near as I can tell it be the `set_position` function in `src/evalfunc.c` (by way of `f_setpos`) is where attentions oughta be focused;

```c
static funcentry_T global_functions[] =
{
/*...*/
    {"setpos",		2, 2, FEARG_2,	    arg2_string_list_number,
			ret_number_bool,    f_setpos},
/*...*/
};

/*...*/

/*
 * "setpos()" function
 */
    static void
f_setpos(typval_T *argvars, typval_T *rettv)
{
    set_position(argvars, rettv, FALSE);
}

/*...*/

/*
 * Set the cursor or mark position.
 * If "charpos" is TRUE, then use the column number as a character offset.
 * Otherwise use the column number as a byte offset.
 */
    static void
set_position(typval_T *argvars, typval_T *rettv, int charpos)
{
    pos_T	pos;
    int		fnum;
    char_u	*name;
    colnr_T	curswant = -1;

    rettv->vval.v_number = -1;

    if (in_vim9script()
	    && (check_for_string_arg(argvars, 0) == FAIL
		|| check_for_list_arg(argvars, 1) == FAIL))
	return;

    name = tv_get_string_chk(argvars);
    if (name == NULL)
	return;

    if (list2fpos(&argvars[1], &pos, &fnum, &curswant, charpos) != OK)
	return;

    if (pos.col != MAXCOL && --pos.col < 0)
	pos.col = 0;
    if ((name[0] == '.' && name[1] == NUL))
    {
	// set cursor; "fnum" is ignored
	curwin->w_cursor = pos;
	if (curswant >= 0)
	{
	    curwin->w_curswant = curswant - 1;
	    curwin->w_set_curswant = FALSE;
	}
	check_cursor();
	rettv->vval.v_number = 0;
    }
    else if (name[0] == '\'' && name[1] != NUL && name[2] == NUL)
    {
	// set mark
	if (setmark_pos(name[1], &pos, fnum) == OK)
	    rettv->vval.v_number = 0;
    }
    else
	emsg(_(e_invalid_argument));
}
```

...  Specifically, looks like the block around `// set cursor; "fnum" is ignored` is where this feature was intended.  If so, then I'd be delighted to take a crack at maybe implementing a patch, only main question I got is how to access and mutate the target buffer state?
