### ISSUE TITLE
job_start() is slow

### ISSUE THREAD

**Issue by vimpostor** [vim/vim#7789]
Hi I need to be able to asynchronously dispatch a short-lived shell command frequently. I do not care about the output, so I can use `job_start()` with no channels attached. However it seems like `job_start()` is very slow, even slower than the blocking `system()` call for short-lived shell commands, even despite the Vim help saying that `job_start()` will return immediately.

Detailed steps to reproduce the behavior:
1. Run the following command:
```bash
vim --clean -Nu <(cat<<EOF
func A()
let g:job_id = job_start('echo 1', {"in_io": "null", "out_io": "null", "err_io": "null"})
call system('echo 1')
endfunc
au VimEnter * let g:timer = timer_start(500, {-> A()}, {"repeat": -1})
EOF
)
```
2. Profile the function:
```vim
:profile start jobs.log
:profile func *
:profile file *
" Wait for a few seconds, the timer will only call A() every 500 ms
:profile pause
:noautocmd qall!
```
3. Open jobs.log and wonder why the non-blocking `job_start()` is slower than the actual blocking `system()` command:
```
FUNCTION  A()
    Defined: /proc/41092/fd/12:1
Called 59 times
Total time:   0.780584
 Self time:   0.068691

count  total (s)   self (s)
   59              0.059704 let g:job_id = job_start('echo 1', {"in_io": "null", "out_io": "null", "err_io": "null"})
   59   0.719576   0.007683 call system('echo 1')
```
Dividing the total time for the `system()` call by the count we have `0.719 s / 59 = 12 ms` for `system()`, whereas `job_start` needs `59` ms.

**Expected behavior**
`job_start` immediately returns back to the script like the documentation says, not blocking for longer than the actual command I want to run takes.

 - Vim version: 8.2.2380
 - OS: Arch Linux
 - Terminal: Konsole

Is there perhaps an alternative way to dispatch short-lived shell scripts frequently from vimscript without having a major performance impact on the vim side? Or is the only other solution to use python or lua for this purpose?
Like I said, I don't care about the command output so I was hoping there is a way to do this in vimscript.

**Comment by brammool** [comment]
It's a lot faster for me, but do see that system() is almost ten times faster than job_start().
I don't know why.

**Comment by vimpostor** [comment]
Without profiling the Vim code per se, my best guess is that fork() is 
the bottleneck, which is called in mch_job_start() (which is directly 
called from job_start()): 
https://github.com/vim/vim/blob/00385114dbd6a3d59516baa02e1ea86a1e7ee70e/src/os_unix.c#L5523

Perhaps using something like posix_spawn() would be better.
 From the man page 
(https://man7.org/linux/man-pages/man3/posix_spawn.3.html):
fork() step
        Since glibc 2.24, the posix_spawn() function commences by calling
        clone(2) with CLONE_VM and CLONE_VFORK flags.  Older
        implementations use fork(2), or possibly vfork(2) (see below).

I would expect this to perform better since this does not perform a 
fullblown fork() operation - that is at least for the glibc 
implementation.


Am Sun, Feb 07, 2021 at 05:26:06AM -0800 schrieb Bram Moolenaar:

**Comment by paul-ollis** [comment]
I am confident that that there is actually no problem to fix here.

Here are some profiling results I collected from two separate runs of 100 and
200 calls (some minor changes, but essentially the same scenario).

count  total (s)   self (s)
  200              0.247216 call job_start('echo 1', {"in_io": "null", "out_io": "null", "err_io": "null"})
  200   1.649425   0.031544 call system('true')

  100              0.123106 call job_start('echo 1', {"in_io": "null", "out_io": "null", "err_io": "null"})
  100   0.831734   0.016502 call system('true')

The above makes it clear that the value under the 'self' column is the total
for all the calls, not per-call. So from my profileing , the time per-call for
job_start is:

    0.247216 / 200, which is about 1.2 ms

And for @vimposter, job_start takes:

    0.059704 / 59, which is about 1.0 ms

So actually about 12 times quicker than the elasped time for each system call.

So @vimposter could dispatch around 1000 shell commands per second.

A note about the 'self' value for 'call system(...)'.

This appears to show that the system code is more performant since its per-self
time (for @vimposter) would be calculated as:

    0.007683 / 59, which is about 0.13 ms

This is not the case. I have instrumented the C code directly and verified that
both job_start and system are basically, equally efficient. The above
calculation does not provide a useful result.

The same discrepency shows up in my profile results, which suggest 'self'
per-call for system is about 0.16 ms. Direct instrumentation shows that
'system()' call spends 1.2 ms blocker waiting for fork() to retuen, so the
correct 'self' value should be similar to job_start(); i.e. a about 1.2 ms.

**Comment by chrisbra** [comment]
let's close it then.

**Comment by dpelle** [comment]
> The fork() system call copies all memory pages

That depends on the OS.  On Linux, fork() should be fast because pages are lazily copied later when needed thanks to COW (Copy On Write), as explain here: https://en.wikipedia.org/wiki/Copy-on-write

**Comment by vimpostor** [comment]
> On Linux, fork() should be fast because pages are lazily copied later when needed thanks to COW (Copy On Write)

I know about CoW, but the problem is that the cost of copying the page tables alone is already a problem, because Linux's page size of 4kB is simply a little bit on the small side when you are dealing with processes with e.g. 500MB of memory.

See for example https://www.cs.purdue.edu/homes/sishuai/pdf/eurosys21-odf.pdf and I also remember that there was a pretty famous thread on LKML about the very same topic, but I can't seem to find the link right now unfortunately.

**Comment by vimpostor** [comment]
Maybe I will write a patch later that replaces `fork()` with a more suitable and efficient syscall to prove the performance advantage, but I am not sure if I will get around to that due to other things keeping me busy right now...

**Comment by paul-ollis** [comment]
@vimposter. Since I have shown that job_start is in fact about 60 time faster
than you calculated and definitely not slower than system(), I think the onus
is now on you to show that there is still a problem that actually requires
fixing.

I take your point that increased memory usage will have an effect on fork(),
but what is the realistic scenario you have in mind and how often do you need
to invoke job_start?

Just for completeness, I re-ran the profiling, but with Vim using 330 MB and
even then, I could still call job_start about 100 time per second. To me, this
seems an extreme scenario. Were I faced with it, I would be looking to run some
form of server (using job_start) rather than spawning many processes.

Discussions about forking, COW, etc are all very well, but a reasonably
compelling use-case is needed before such code changes should be considered.

**Comment by chrisbra** [comment]
happy to re-open then.

**Comment by vimpostor** [comment]
> Since I have shown that job_start is in fact about 60 time faster than you calculated

We already know that benchmarking this varies very much depending on hardware, for example Bram reported that `job_start()` was 10 times slower than `system()` on his system, so I don't think your one result proves much of anything, especially due to the wrong benchmarking configuration explained above (no high memory usage).

> I think the onus is now on you to show that there is still a problem

Sure, I will do that and even do one better and write a patch, but it might take some time...

> what is the realistic scenario you have in mind and how often do you need to invoke job_start?

I think it is not unrealistic to imagine a scenario where one wants to use an external shell command every time the user types something for example, and do that without blocking the main thread. This is only possible with `job_start()`.
My actual usecase from over a year ago is already solved in another way (I use `job_start()` at startup to startup a Bash script that accepts commands on stdin and communicate with the job over channels that then dispatch the shell commands), but that is a really ugly solution if I just want to dispatch a command (I basically had to write Bash **inside** vimscript, but it works at least, you can see that ugly mess [over here](https://github.com/vimpostor/vim-tpipeline/blob/b83d430697d268a690240ec932630b8aed211aba/autoload/tpipeline.vim#L120) if you are interested).

> a reasonably compelling use-case is needed before such code changes should be considered

Well I disagree, because replacing `fork()` with a better system call is a very local code change. In fact, I think `fork()` doesn't make sense in the first place, because shortly after doing the expensive copy of the entire process space, we call `execve()` on the child process, effectively throwing away all the memory pages and hard work. The copy of the page table is unneeded after all.

**Comment by paul-ollis** [comment]
> for example Bram reported that job_start() was 10 times slower than system() on his system
Obviously I cannot be certain, but I am pretty sure that Bram followed the same method of calculation that you did. Unfortunately the calculation is wrong because (using your profile data) you need to divide 0.059704 by 59 to get the correct figure for job_start. Looking back at my comment, I think I failed to make this as clear as I could have - sorry.

> so I don't think your one result proves much of anything
My tests and results were intended to be comparable to yours, in order to illustrate that job_start is much quicker than you thought. Again, my apologies if I failed to make this suitably clear.

**Comment by vimpostor** [comment]
> Unfortunately the calculation is wrong because (using your profile data) you need to divide 0.059704 by 59 to get the correct figure for job_start. Looking back at my comment, I think I failed to make this as clear as I could have - sorry.

You are absolutely right, I didn't see that. Still I have the feeling that there is more to it, as I remember experiencing very noticable scroll stuttering when using `job_start()` on every `CursorMoved` event. I will definitely look into it, but I think you might be right that my profiling results were off by more than an order of magnitude.

**Comment by brammool** [comment]
Replacing fork() followed by some form of exec() could be useful, especially on systems where this is slow.
However, any replacement needs to be profiled/tested to verify it actually is faster.  And it will require configure checks,
because not all systems have the same function for this, and there might be subtle differences (e.g. in signal handling).

AFAIK the systems that offer a replacement have also made fork/exec quite fast already, thus spending time on changing this might not help that much.  Perhaps there is a specific system where it's slow and it can be solved (e.g. BSD based systems, I don't know) and then it can be worth it.

Besides, expecting a system to be fast enough to run a shell command on every keystroke is expecting a bit too much.  For these things it's better to start a job with a channel, and send messages back and forth.

**Comment by vimpostor** [comment]
I see, I guess we can indeed close the issue for now.
If I find out that I can get significant performance improvements, I will come back to you and post a patch.
