### ISSUE TITLE
netrw: popup with error message won't go away

### ISSUE THREAD

**Issue by gdupras** [vim/vim#7828]
**Describe the bug**
If a popup appears to display an error message, it won't go away except by doing `:call popup_clear()`.

**To Reproduce**
1. `vim --clean` or `gvim --clean`
2. `:source $VIMRUNTIME/plugin/netrwPlugin.vim`
3. `:Explore`
4. Move the cursor on a directory an press `p`.
5. An error message appears (that's fine) but does not ever disappear except by doing `:call popup_clear()` (that should not be necessary).

**Expected behavior**
The documentation says that if `g:netrw_use_errorwindow=2` then 
```
messages from netrw will use a popup window
Move the mouse and pause to remove the popup window
```

**Screenshots**
![netrw_bug](https://user-images.githubusercontent.com/57042631/107840132-453f1100-6d7e-11eb-8131-6841884e9eb5.png)

**Environment**
 - Vim version 8.2.2505
 - OS: Kubuntu 20.10
 - Terminal: Konsole

**Comment by lacygoill** [comment]
I think the issue comes from this line:

https://github.com/vim/vim/blob/31842cd0772b557eb9584a13740430db29de8a51/runtime/autoload/netrw.vim#L96

For some reason, `popup_beval()` doesn't seem to reliably close the popup when the mouse moves.  Sometimes it does; sometimes it does not.

`popup_atcursor()` would probably work better, and it wouldn't require to touch the mouse to make the error message disappear.

**Comment by lacygoill** [comment]
> `popup_atcursor()` would probably work better

Or just replacing the `mousemoved` key with the `moved` key:
```vim
let pos = screenpos(v:beval_winnr, v:beval_lnum, v:beval_col)
call popup_create(msg, #{
    \ pos: 'botleft',
    \ line: pos.row - 1,
    \ col: pos.col,
    \ moved: 'WORD',
    \ })
```

**Comment by cecamp** [comment]
I'll try the popup_atcursor solution; please get netrw v171g from my [website](http://www.drchip.org/astronaut/vim/index.html#NETRW)
