### ISSUE TITLE
Vim9: cannot break dictionary member accessed via multiple keys

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7839]
**Describe the bug**

In Vim9 script, we cannot break a dictionary member accessed via multiple keys on different lines.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var d = {a: {b: {c: 0}}}
        d
        .a
        .b
        .c =
        123
    EOF
    )

`E475` is raised:

    E15: Invalid expression: d

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2510
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(365)

**Additional context**

`.` could be considered as a binary operator whose operands are a dictionary and a key.  Under that view, we could expect to be able to break the expression before the dot, just like we can with any other binary operator like `..`, `+`, ...

> For binary operators in expressions not in [], {} or () a line break is
> possible just before or after the operator.  For example: >
>         var text = lead
>                    .. middle
>                    .. end
>         var total = start +
>                     end -
>                     correction
>         var result = positive
>                         ? PosFunc(arg)
>                         : NegFunc(arg)

Even if it's not technically an operator, it would be convenient to be able to break before `.` just like we can before `..`.

---

Same issue when using the square bracket notation:
```vim
vim9script
var d = {a: {b: {c: 0}}}
d
['a']
['b']
['c'] =
123
```
    E475: Invalid argument: 'c'] =

**Comment by brammool** [comment]
It is not related to using a dictionary member, but breaking the line inside the LHS of an assignment.
When the script is inspected to find the command to execute it needs to see the "=" to know it is an assignment.
Otherwise it could be an expression evaluation and the next line a separate command.
     foo.bar()
     ['key'] = 123
Perhaps it can work for several cases, but not in general.  We would have to check that the next line is not a valid command, which is too tricky.
