### ISSUE TITLE
vim did not like 'java' ? :-)

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#7893]
**Describe the bug** && **To Reproduce**
vim --clean -u <(cat<<EOF
echomsg systemlist('java -version')
EOF
)

// output:
[]

**Expected behavior**
['openjdk version "11.0.10" 2021-01-19', 'OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)', 'OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)']

// tried 'npm', 'apt', etc.. all looks fine, but seems just 'java' cannot..................
// though such echo for 'java' can get expected result if/when vim had startup.

**Environment (please complete the following information):**
 - v8.2.2548
 - xterm

**Comment by chrisbra** [comment]
please check your path settings please

**Comment by Shane-XB-Qian** [comment]
which 'path' was you saying? if path wrong, then it should not work in vim had startup either.

**Comment by chrisbra** [comment]
What I meant, was to check $PATH. You may also want to check the various shell options, in particular, shellredir because I suppose you should see an error message if a command is not found. Not sure why it would not include `2>&1` for you. You might also want to set the verbose option to 5, to see what command your shell is executing. And finally make sure, that you do not have any shell script laying around early in $PATH that is named `java` and does nothing. 

This all is not a vim bug, you need to check your configuration and your system.

**Comment by lilydjwg** [comment]
`java -version` outputs its version to stderr, which is not captured by default.

**Comment by chrisbra** [comment]
it should be captured if your 'shellredir' option includes `2>&1` which it does for me, but I think this depends on the $SHELL used.

**Comment by Shane-XB-Qian** [comment]
> `java -version` outputs its version to stderr, which is not captured by default.

i see, good point, thx.. but just why e.g:
`echomsg systemlist('echo "foo" 1>&2')` can work (get stderr result) in vim had startup.......

so it was intended?

**Comment by Shane-XB-Qian** [comment]
the title was a joke, :-), ahahaha..........
// should be not only 'java'..

it is more about why the behavior was different....

**Comment by chrisbra** [comment]
As said before, depending on your shell, the 'shellredir' option can be set to configure this behaviour. So I suppose this can be closed, because there is no bug here. Please ask questions on the vim-dev or vim-use ml, not here.

**Comment by Shane-XB-Qian** [comment]
@chrisbra man, which 'shell' you are talking about? i am using 'bash', and i think this is a common case for most users...
did not you see the behavior is different when vim just starting -vs- had startup?!
so you confirm it was intended and accepted by most users?

**Comment by chrisbra** [comment]
I am talking about whatever shell you as a user are using and that is also used by your vim for things like `system()`. Please have a look at the documentation, it is all there, see e.g. `:h 'shell'` and the following paragraphs.

> so you confirm it was intended and accepted by most users?

Not sure what you mean with most users. It's been like this for a long time, use the provided settings to configure it to your liking, if it doesn't do what you want. Changing it, will most likely annoy other users.

**Comment by Shane-XB-Qian** [comment]
guess you see i am using '--clean' in the example code, there is no special setting here including no any special 'shell' option.
the problem is simple: why `systemlist('echo "foo" 1>&2')` behavior/result is different when vim just starting -vs- had startup?!

i know i can redir the result as a workaround, or whatever 'shell' setting you are saying, 
but vim should not keep behavior consistent?

**Comment by vim-ml** [comment]
On 2021-02-24, Shane-XB-Qian wrote:
> guess you see i am using '--clean' in the example code, there is no special
> setting here including no any special 'shell' option.
> the problem is simple: why systemlist('echo "foo" 1>&2') behavior/result is
> different when vim just starting -vs- had startup?!
> 
> i know i can redir the result as a workaround, or whatever 'shell' setting you
> are saying,
> but vim should not keep behavior consistent?
> 
>     It's been like this for a long time, use the provided settings to configure
>     it to your liking, if it doesn't do what you want.
> 
> pls give an example? i did argue something.. but mostly just a suggest, i would
> not get benefit from this, and actually did not care if to fix or not..
> i respect you spent long time on vim, thx your effort, sorry but i saw you said
> many aggressive words in communities, it's helpless actually..

The behavior you are observing is intended.  It is explained under

    :help 'shellredir'

which says,

    The initialization of this option is done after reading the ".vimrc"
    and the other initializations, so that when the 'shell' option is set
    there, the 'shellredir' option changes automatically unless it was
    explicitly set before.

That means that 'shellredir' has not been set when your -u command
is executed and therefore is still the default ">".  Try the
following modification to your java command example.

    $ vim --clean -u <(cat<<EOF
    echomsg &shellredir
    EOF
    )
    >
    Press ENTER or type command to continue

Regards,
Gary

**Comment by Shane-XB-Qian** [comment]
@vim-ml thx Gary, that's helpful.

> so that when the 'shell' option is set there, the 'shellredir' option changes automatically unless it was explicitly set before.

looks 'shell' is '/bin/bash' which is default (here), in this case user did not set it, since started vim with '--clean' option.
but you are right, looks it was intended, just was not confirmed said it was auto changed from '>' to '2>&1', or which to which.
or did it? or should?

// but i agree this is not a bug, maximally just a wish to be enhanced/clear...

**Comment by vim-ml** [comment]
On 2021-02-24, Shane-XB-Qian wrote:
> @vim-ml thx Gary, that's helpful.
> 
>     so that when the 'shell' option is set there, the 'shellredir' option
>     changes automatically unless it was explicitly set before.
> 
> looks 'shell' is '/bin/bash' which is default (here), in this case user did not
> set it, since started vim with '--clean' option.
> but you are right, looks it was intended, just was not confirmed said it was
> auto changed from '>' to '2>&1', or which to which.
> or did it? or should?

I neglected to include that.  Sorry.  In that same vim instance,
started with --clean,

    :verbose set shell? shellredir?
      shell=/bin/bash
      shellredir=>%s 2>&1

I was running Vim 8.2.2519 on Ubuntu 20.04.2.

Regards,
Gary

**Comment by Shane-XB-Qian** [comment]
thx Gary, 
my fault, i was thinking (reading as) bash was default as '2>&1' too.

// saying this, because i saw some plugins using systemlist() to judge extra cmd version.
// so if so, the behavior looks would be varied, not stable, just a bit worry...... :-)

**Comment by chrisbra** [comment]
thanks Gary, this was exactly what I was trying to say. Guess I am not good at explaining anything and instead I am told that I am being aggressive. 

I think I will take a rest and no longer follow the tickets here, if I am being accused of being rude. I don't intend to be rude, so I can only apologize, it's just my style of writing.

**Comment by Shane-XB-Qian** [comment]
@chrisbra donot be, neednot take this too serious, i'm sorry i may say too straight too, that's my style, :cry: 
let's looking for fun.............. :+1: we're all actually just playing, not making money.... :-) sorry for the terrible joke... :-(

**Comment by brammool** [comment]
Christian wrote:

> thanks Gary, this was exactly what I was trying to say. Guess I am not
> good at explaining anything and instead I am told that I am being
> aggressive. 
> 
> I think I will take a rest and no longer follow the tickets here, if I
> am being accused of being rude. I don't intend to be rude, so I can
> only apologize, it's just my style of writing. 

You are not rude at all.  Please don't stop responding to issues!  If
you need rest or time off, you are of course encouraged to do so.  But
you contributions are very much appreciated!

Email and similar forms of communication are limited in that it's hard
to express intention and feelings.  And facts can be a bit hard.  This
requires a bit of flexibility.  Both from the reader and the writer.

The reader has to keep in mind that the message was probably meant well,
but not phrased that way.  Especially because many of us (including
myself) are not using English as a first language.  And there are also
cultural differences.

For writers it's always good to keep in mind that the reader might
possibly read things into the text that you didn't intentionally put
there.  That can be difficult, especially with technical stuff where you
have to tell someone what is wrong.  Give it a try, but we don't expect
people to be perfect.

-- 
BRIDGEKEEPER: What is your favorite colour?
GAWAIN:       Blue ...  No yelloooooww!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
