### ISSUE TITLE
Action d/c + backwards motion F/T doesn't include the cursor in the range

### ISSUE THREAD

**Issue by ghost** [vim/vim#7894]
**To Reproduce**

Given the line: `an example, which shows the issue#`
If I run: `$dF,`
I obtain: `an example#`
I expected: `an example`
Just like: `0f,d$` gives me: `an example` and not: `an example,`

**Environment**
 - vim-8.2.2489
 - Arch Linux
 - Alacritty

**Comment by chrisbra** [comment]
`F` if an exclusive motion, so it does not include the last character

**Comment by tonymec** [comment]
The F motion is `|exclusive|`, as said under `:help F`. At `:help exclusive` I read:

`When exclusive, the last character towards the end of the buffer is not included.
Linewise motions always include the start and end position.`

When moving leftwards as with F, "the last character towards the end ofthe buffer" is IIUC the one the cursor starts from, i.e. in your case the # sign.

The $ motion, OTOH, is `|inclusive|`.

The result might be different if you make sure that `'selection'` is set to `inclusive` then use vF,d instead of dF, (untested).

Best regards,
Tony.
