### ISSUE TITLE
Vim9: dictionary losing type information, plus segfault

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#7912]
Source the following example:

```vim
vim9script 

def F1(x: string): string
  return x
enddef

def F2(x: number): number
  return x
enddef

def G(g: func): dict<func>
  return { f: g }
enddef

def H(d: dict<func>): string
  return d.f('a')
enddef

echo H(G(F1)) # Correct
echo H(G(F2)) # Does not raise any error!
```

The last command prints `a`, but I would have expected it to raise a type mismatch error.

But worse, if `F2()` is modified as follows:

```vim
def F2(x: number): number
  return x + 1
enddef
```

then running the code above causes Vim to crash.

 - Vim 8.2.2550
 - OS: macOS 11.2.1
 - Terminal: Apple Terminal

**Comment by lacygoill** [comment]
> The last command prints a, but I would have expected it to raise a type mismatch error.

Possible relevant todo item:

https://github.com/vim/vim/blob/057e84afe5bd37fe272bf7cfafca629ef9da1bd3/runtime/doc/todo.txt#L51-L54

---

> running the code above causes Vim to crash.

- [backtrace](https://github.com/vim/vim/files/6057335/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6057336/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6057334/asan.log)

**Comment by lifepillar** [comment]
>The last command prints a, but I would have expected it to raise a type mismatch error.

Or, perhaps, this is expected behaviour with `func`? Stricter typing (e.g., using `func: string`) avoids this issue.

**Comment by lacygoill** [comment]
> Or, perhaps, this is expected behaviour with func?

`F2` is a funcref to `F2()`, which is a function expecting a number, and returning a number.
In `G(F2)`, `G()` receives a funcref which is a valid argument, and returns a dictionary containing a funcref to `F2()`:

    {f: F2}
     │  │
     │  └ value: funcref to F2()
     └ literal key


In `H(G(F2))`, `H()` receives the dictionary of funcrefs `{f: F2}`, which is a valid argument, and returns this expression:

    d.f('a')

Where `d` is `{f: F2}`.  Which means we can re-write the expression like this:

    {f: F2}.f('a')

`{f: F2}.f` evaluates to `F2`.  Which means we can re-write the expression like this:

    F2('a')

That should raise an error, because `F2()` expects a number, not a string, as specified in its header:

    def F2(x: number): number
              ^----^

The error should be raised at compile time.  For the same reason that this snippet raises an error at compile time:
```vim
vim9script
def F(x: number): number
  return x
enddef
def G(g: func): dict<func>
  return {f: g}
enddef
def H(d: dict<func>): string
  return F('a')
enddef
G(F)->H()
```
    Error detected while compiling ... function ...H:
    line    1:
    E1013: Argument 1: type mismatch, expected number but got string

And if for some reason, it can't be raised at compile time, then at least it should be raised later at runtime, when Vim has full knowledge of all the types.

It looks like the issue comes from the funcref which is evaluated from a dictionary member.

---

Here is yet another todo item which *might* be relevant:
https://github.com/vim/vim/blob/3650fd709807d5ac182e28d952cbd790c1ad0a6a/runtime/doc/todo.txt#L117

It refers to the issue https://github.com/vim/vim/issues/5676 which has been closed.

---

> Stricter typing (e.g., using func: string) avoids this issue.

It depends where we specify `: string`.  It works as expected if we include it in `G()`'s header:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func: string): dict<func>
    return {f: g}
enddef

def H(d: dict<func>): string
    return d.f('a')
enddef

F->G()->H()
```
    E1013: Argument 1: type mismatch, expected func(...): string but got func(number): number
    E1013: Argument 1: type mismatch, expected dict<func(...): unknown> but got number

Also in compiled code:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func: string): dict<func>
    return {f: g}
enddef

def H(d: dict<func>): string
    return d.f('a')
enddef

def Func()
    F->G()->H()
enddef
defcompile
```
    E1013: Argument 1: type mismatch, expected func(...): string but got func(number): number

It also works as expected if we include it in `H()`'s header:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func): dict<func>
    return {f: g}
enddef

def H(d: dict<func: string>): string
    return d.f('a')
enddef

F->G()->H()
```
    E1013: Argument 1: type mismatch, expected dict<func(...): string> but got dict<func(number): number>

But it no longer works in compiled code:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func): dict<func>
    return {f: g}
enddef

def H(d: dict<func: string>): string
    return d.f('a')
enddef

def Func()
    F->G()->H()
enddef
Func()
```
    no error

This very last snippet is inconsistent and looks wrong.  `E1013` should be raised at compile time.

---

Unrelated to the issue, but here's a small tip which might be useful to some people.

Try to use methods as often as possible.  For example, instead of writing this:

    echo H(G(F2))

Write this:

    echo F2->G()->H()

First, it's more readable.  But more importantly, it can help distinguish between multiple errors.  Case in point:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func: string): dict<func>
    return {f: g}
enddef

def H(d: dict<func>): string
    return d.f('a')
enddef

H(G(F))
```
    Error detected while processing ...
    line   14:
    E1013: Argument 1: type mismatch, expected func(...): string but got func(number): number
    E1013: Argument 1: type mismatch, expected dict<func(...): unknown> but got number

It's not clear which of these 2 errors applies to which function call.

Re-writing the code using methods, and splitting the methods on separate lines, might help:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func: string): dict<func>
    return {f: g}
enddef

def H(d: dict<func>): string
    return d.f('a')
enddef

F->G()
 ->H()
```
    Error detected while processing ...
    line   14:
    E1013: Argument 1: type mismatch, expected func(...): string but got func(number): number
    line   15:
    E1013: Argument 1: type mismatch, expected dict<func(...): unknown> but got number

Notice that this time, the errors are raised from different lines, which makes it easier to find the function calls to which they apply.

Also, if you try to split the lines even more, so that `F` and `G()` are on separate lines, other errors are raised:
```vim
vim9script
def F(x: number): number
    return x
enddef

def G(g: func: string): dict<func>
    return {f: g}
enddef

def H(d: dict<func>): string
    return d.f('a')
enddef

F
 ->G()
 ->H()
```
    E492: Not an editor command: F
    E1050: Colon required before a range: ->G()
    E1050: Colon required before a range: ->H()

I'm not sure but that [looks like a bug](https://github.com/vim/vim/issues/7770#issuecomment-787774799).  Maybe it will be fixed.  In any case, when we write an expression at the start of a line and Vim wrongly parses it as an Ex command, we can fix it by wrapping the expression inside parentheses:

    parentheses to make sure Vim parses "F" as an expression
    v v
    (F)
     ->G()
     ->H()

**Comment by lacygoill** [comment]
Also, even though I don't think it applies to the current issue, be aware of [one pitfall](https://github.com/lacygoill/wiki/blob/master/vim/vim9.md#which-pitfall-should-i-be-aware-of-when-storing-a-funcref-in-a-listdictionary) regarding type checking which you might encounter when storing a funcref in a list or dictionary.

**Comment by vim-ml** [comment]
Hi,

On Mon, Mar 1, 2021 at 1:16 AM lacygoill <vim-dev-github@256bit.org> wrote:

> Also, even though I don't think it applies to the current issue, be aware
> of one pitfall
> <https://github.com/lacygoill/wiki/blob/master/vim/vim9.md#which-pitfall-should-i-be-aware-of-when-storing-a-funcref-in-a-listdictionary>
> regarding type checking which you might encounter when storing a funcref in
> a list or dictionary.
>
>
> https://github.com/lacygoill/wiki/blob/master/vim/vim9.md

You have created a very useful document about the various aspects of Vim9.

Regards,
Yegappan
