### ISSUE TITLE
NONANTIALIASED_QUALITY misspelled in os_mswin.c

### ISSUE THREAD

**Issue by brouer** [vim/vim#793]
And, less important as it doesn't impair functionality, also in options.txt.

[patch.txt](https://github.com/vim/vim/files/256592/patch.txt)

**Comment by brammool** [comment]
Kim Brouer wrote:

> And, less important as it doesn't impair functionality, also in options.txt.

Thanks!

## 

"I've been teaching myself to play the piano for about 5 years and now write
most of my songs on it, mainly because I can never find any paper."
        Jeff Lynne, ELO's greatest hits

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
