### ISSUE TITLE
What is the better way to center the cursor vertially even in Insert mode or at the end line?

### ISSUE THREAD

**Issue by ZhiyuanLck** [vim/vim#7961]
I'm finding a way to keep my cursor vertically centered always. `set scrolloff=999` is good, but it **does not work when cursor is at the end line**. So I try to use auto commands
```vim
augroup AutoCenter
  autocmd!
  autocmd CursorMoved,CursorMovedI * <cmd>norm! zz
augroup END
```
It works fine even at the end line, but it has a bug: suppose the horizontal pos is 1. When mode changes from `Normal` to `Insert` via `a` **at the end of the line**, the cursor pos changes (1->2) and then autocmd is triggered, it seems that the mode goes back to `Normal` (2->1) first and after running `zz` it comes back to `Insert` (1->1). So I want to go to 2 but it goes to 1. 

When mapping keys, there is `<cmd>` to avoid changing current mode when running commands. Is it a possible way to fix this?

- Terminal: Alacritty
- OS: Ubuntu 20.04
- Vim version: 8.2.2246

**Comment by lacygoill** [comment]
Since you don't need `:norm! zz` to be executed on horizontal motions, only vertical ones, how about a guard which prevents the command from being executed while you're moving along the same line:
```vim
vim9script
augroup AutoCenter | au!
    au CursorMoved,CursorMovedI * AutoCenter()
augroup END
def AutoCenter()
    var line: number = line('.')
    if line != get(b:, 'last_line', 0)
        norm! zz
        b:last_line = line
    endif
enddef
```
The code is in Vim9 script because `CursorMoved` and `CursorMovedI` are events which are fired frequently; it makes sense to try to optimize the code.

---

Note that `<cmd>` is a pseudo-key which only makes sense in the rhs of a mapping; not in an autocmd.

---

For general questions, visit [vi.stackexchange.com](https://vi.stackexchange.com), the [Vim users mailing list](https://groups.google.com/g/vim_use), or the [`#vim` channel on freenode](https://www.vi-improved.org/).

---

As for the issue, I can reproduce, but I don't know whether it's a bug, working as intended, or an undocumented detail of implementation.
