### ISSUE TITLE
Add a fillchar for where the statusline from a split meets the vertical seperators

### ISSUE THREAD

**Issue by GordianDziwis** [vim/vim#8018]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
I got quite obsessive about getting a minimalist consistent look for my vim. One thing that keeps bugging me is this:

![image](https://user-images.githubusercontent.com/3330855/112719293-8a676e80-8ef8-11eb-98fd-25c2b65c4522.png)

As you can see next to the cursor where the statusline meets the vertical seperator there is a gap.

Here is a full screen shot for context.
![image](https://user-images.githubusercontent.com/3330855/112719227-2d6bb880-8ef8-11eb-80bc-080a3d696915.png)

**Describe the solution you'd like**
 I would like to fill it with with a half block  ` ▌` to get rid of it. Or a right half block depending on the side of the split.

**Describe alternatives you've considered**
Living with it. This would be all right, I just wanted to ask.

**Comment by matveyt** [comment]
This is not a gap. `VertSplit`, being a standard highlighting group, has its own set of attributes, including background color. In your current colorscheme `VertSplit` and `StatusLine` have different backgrounds. That's all.

**Comment by lifepillar** [comment]
If I understand correctly, the request is about using a different VertSplit symbol just ~for the cursor's line and just when the cursor is at the same height as a status line.~ for the “crossing point” between a status line and a vertical split. E.g,., instead of:

	      |
          |
    ██████|
          |
          |

which leaves some space between the right end of the status line (█) and the VertSplit symbol (`|`), have something like

          |
          |
    ██████▌
          |
          |

where the VertSplit symbol ~at the cursor's line~ where the status line ends is a half block (▌) instead of a bar (`|`).

@BonaBeavis For things to work as you expect, that would require introducing *two* symbols for the “crossing” point, in addition to VertSplit: one for each end of the status line. But using half blocks may be confusing when two status lines meet: you won't be able to distinguish a single status line in a horizontal split from two status lines in a vertical split.

If you don't like “gaps”, you might set `VertSplit`'s background color to the status line's background color as @matveyt  suggests, and optionally set the vertical separator to a space in `fillchars`.

**Comment by matveyt** [comment]
@lifepillar That'll do no good if `VertSplit` fore does not match `StatusLine` back. So it's not an option.

The only meaningful proposal would be to make (the left) StatusLine overlap VertSplit (as StatusLine at bottom currently does).

**Comment by GordianDziwis** [comment]
@lifepillar
> But using half blocks may be confusing when two status lines meet: you won't be able to distinguish a single status line in a horizontal split from two status lines in a vertical split.

This! So actually the "gap" is feature and  not a bug ^^
