### ISSUE TITLE
Adding PowerShell files to vim

### ISSUE THREAD

**Issue by heaths** [vim/vim#8041]
There was a request to add PowerShell syntax files to vim, but we also have other scripts that contribute to a complete bundle. I see other languages added compilers and other scripts, so should everything be included, and is there interest in adding PowerShell support now that it's ubiquitous across platforms?

https://github.com/PProvost/vim-ps1/issues/50 (I'm one of the maintainers)

**Comment by dkearns** [comment]
Yes, there certainly is interest and please include all files.

I've only had a very quick look but it all seems good to me.

Could you please:
* create a patch against filetype.vim to include the filetype detection from your ftdetect files?
* remove the version 6 checks from the head of the syntax files and the HiLink command usage from the end.  See the other distributed syntax files for how it's currently done just using `hi def link`.  Versions 5 and 6 of Vim are considered too old to worry about in this context.
* add a Maintainer header line to compiler/powershell.vim
* edit .github/CONTRIBUTORS so you'll get notified of any issues submitted here rather than to your repo

Thanks.

**Comment by heaths** [comment]
Will have a PR soon, but wondering if, instead of a Maintainer line, we can just include a URL to the GitHub project rather than sharing a direct email address. Easier to triage issues on GitHub and have a discussion in the open.

**Comment by brammool** [comment]
Sure, so long as a user who has comments can reach the maintainers.

**Comment by brammool** [comment]
I'll include the pull request.
