### ISSUE TITLE
Vim doesn't manage buffers properly.

### ISSUE THREAD

**Issue by Duddy67** [vim/vim#809]
Hi,

I experience a very weird problem with Vim and buffers (Ubuntu 16.04 / Vim 7.4.1689)
Let's say I have 2 files in my Download folder:

file1.txt file2.txt

1) If I run Vim from my home directory and I open the 2 files through the :Explore command 
then I check the buffers
:ls
Only the last opened file is in the list, the first one has disapeared.

2) Now if I run Vim from the Download directory and I open the 2 files through the :Explore command then I check the buffers
:ls 
the 2 files are in the buffer list.

It seems to be an erratic problem as in example 2 if I start vim this way: 
vim file1.txt 
then I open the other file through the :Explore command and check the buffers
:ls
Only the last opened file (file2.txt) is in the list, file1.txt has disapeared.

Does someone ever experienced this behavior ?

**Comment by cecamp** [comment]
If one does  :Explore filename  then, since filename is not a directory, netrw does nothing with it.  So its not clear to me what you mean by "open the 2 files through the :Explore command".

So, trying  :Explore . and then selecting a file with <cr>, returning to the directory listing by using :Rex, then selecting another file with <cr>, I don't see this behavior (using netrw v157c which you may get from http://www.drchip.org/astronaut/vim/index.html#NETRW).  Both files are listed using :ls .

Using :Lexplore and selecting the two files with <cr> also ends up with both being listed using :ls.

Using :Explore, selecting a file with <cr>, then using :Explore again and selecting the other file with <cr>, also ends up with both files being listed when using :ls.

Please elucidate!

**Comment by Duddy67** [comment]
Sorry if I was unclear.
What I mean is invoking the explore command
:Explore 
then browsing and selecting a file in the directory tree structure by pressing the Enter key.
Is that clear enough ?

**Comment by cecamp** [comment]
That is one of the tests I performed that had no trouble (although how you returned to the listing to get to the second file remains unclear: :Rex, <c-o>, :Explore .).  In any case, please try upgrading your version of netrw and see if that fixes your issue.

**Comment by Duddy67** [comment]
The latest netrw commit date is 2014-02-04 (Vim version 7.3). Since I'm using Vim 7.4 I guess I have the latest netrw version. Is that correct ?

**Comment by cecamp** [comment]
No, you don't have the latest netrw.  The latest netrw is v157c (try  :e .  and look at the top right hand corner of your display, unless you've turned the banner off -- you probably have v151).
