### ISSUE TITLE
'Search' highlight has lower priority than 'Visual'

### ISSUE THREAD

**Issue by noscript** [vim/vim#8134]
**Describe the bug**
When doing visual selection over search results, highlight of search results disappear.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim -g -u NONE +'set hlsearch'`
2. Open some text file and search for something. Results will be highlighted with yellow.
3. Start selecting the lines that contain the search results.
4. `Search` highlight is overruled by `Visual`.

**Expected behavior**
`Search` highlight is not overruled by `Visual`.

**Screenshots**
![visual](https://user-images.githubusercontent.com/717109/115548510-390c8e00-a2b0-11eb-8eec-e48de5cb944f.gif)

**Environment (please complete the following information):**
 - Vim 8.2.2650
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by brammool** [comment]
It is correct that the Visual highlighting has higher priority, since it's temporarily while search highlighting stays around.  It would also be difficult to see the Visual area if there are many search matches (e.g. whole lines).
However, I notice that the highlight is overruled, while it could be combined.  You could make Search highlight bold, then it would still be visible.
