### ISSUE TITLE
":mksession" script divides number by 0 when 'wmh' is 0

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8162]
**Describe the bug**

A session script generated by `:mksession` might divide a number by 0 when `'winminheight'` is set to 0, and a split window is maximized.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        writefile([], '/tmp/file')
        &wmh = 0
        e /tmp/file
        sp
        wincmd _
        mksession! /tmp/s.vim
        echo '/tmp/s.vim'
            ->readfile()
            ->filter((_, v) => v =~ ' / 0')
    EOF
    )

This list is printed:

    ['let s:l = 1 - ((0 * winheight(0) + 0) / 0)']

**Expected behavior**

An empty list is printed:

    []

**Environment**

 - Vim version: 8.2 Included patches: 1-2818
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(367)

**Additional context**

When instrumented by asan, the latter gives an error such as this one:

    eval.c:3051:7: runtime error: signed integer overflow: 2 - -9223372036854775808 cannot be represented in type 'long long int'

---

In Vim script legacy, dividing by 0 gives a huge number.  But in Vim9, dividing by 0 raises the error `E1154`.
If one day, the scripts generated by `:mksession` are written in Vim9 script, their sourcing will be aborted as soon as they divide a number by 0; this will be unexpected for the user, as they won't get back their entire session.

---

This patch seems to fix the issue:
```diff
diff --git a/src/session.c b/src/session.c
index 6d1ccb57e..779c2a970 100644
--- a/src/session.c
+++ b/src/session.c
@@ -459,7 +459,7 @@ put_view(
 	if (fprintf(fd, "let s:l = %ld - ((%ld * winheight(0) + %ld) / %ld)",
 		    (long)wp->w_cursor.lnum,
 		    (long)(wp->w_cursor.lnum - wp->w_topline),
-		    (long)wp->w_height / 2, (long)wp->w_height) < 0
+		    (long)wp->w_height / 2, (long)wp->w_height > 0 ? (long)wp->w_height : 1) < 0
 		|| put_eol(fd) == FAIL
 		|| put_line(fd, "if s:l < 1 | let s:l = 1 | endif") == FAIL
 		|| put_line(fd, "keepjumps exe s:l") == FAIL
```

**Comment by lacygoill** [comment]
> When instrumented by asan, the latter gives an error such as this one:

After we source a `:mksession` script generated while a split window was squashed to 0 lines.

**Comment by tonymec** [comment]
It seems that the "winsize" item of 'sessionoptions' is not needed when using Rolodex Vim as described at https://vim.fandom.com/wiki/Window_zooming_convenience#Rolodex_Vim


I personally don't use :mksession because its generated scripts are much too bulky for my taste. I do use `gvim -S` though — with a handcrafted Session.vim — when there is a session which I want to load again and again at every Vim startup. That script is much shorter — and more understandable — than a mksession script because it contains only the commands which I would type to load that session once the vimrc etc. have been handled, no need to repeat what the vimrc (or the filetype-plugins etc.) already set.


Best regards,
Tony.
