### ISSUE TITLE
Arrow keys stops working when reset(send-keys -R) is sent to parent tmux session.

### ISSUE THREAD

**Issue by kohnish** [vim/vim#8164]
**Describe the bug**
On Tmux, when you have :term running, and go to the other vim text edit session and send `clear-history`, the arrow keys stops working, but only hjkl both on Mac and Linux.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run tmux, with this option. `bind-key r send-keys -R \; clear-history`
2. Run vim
3. ~Type :term~
4. ~Press Ctrl + W twice to switch back the original vim text edit session.~
5. Send clear-history from tmux with the keybind you configured on step 1.
6. Resize terminal to cause the terminal to show vim properly again
7. Try navigating with arrow keys.(not hjkl)

**Expected behavior**
Arrow keys works as before.

**Screenshots**
None

**Environment (please complete the following information):**
 - Vim version: 8.2
 - OS: Fedora 33, Mac
 - Terminal: Tmux. (on iterm2 when on Mac, tilix on Linux)

**Additional context**
None

**Comment by brammool** [comment]
You say "Run tmux, with this option".  How?

**Comment by kohnish** [comment]
I meant to have a such configuration in `~/.tmux.conf`  
I think I can send tmux clear-history command from other session as well, or even from the :term session, let me confirm.

**Comment by lacygoill** [comment]
FWIW, I cannot reproduce with Vim 8.2.2820, tmux 3.3 (master), xterm(367), Ubuntu 16.04:

    $ tmux -Lx -f/dev/null
    $ tmux -Lx bind-key r send-keys -R \; clear-history
    $ vim -Nu NONE +'e $VIMRUNTIME/filetype.vim'
    :term
    " press C-w C-w
    " press C-b r
    " press C-l
    " press hjkl

`h`, `j`, `k` and `l` still work after using the custom tmux key binding.

![gif](https://user-images.githubusercontent.com/8505073/116748563-ec3b5c80-a9ff-11eb-857b-3b166b668ede.gif)

Note that instead of resizing the window to make Vim redraw the terminal, you can press `C-L`.

**Comment by lacygoill** [comment]
> Try navigating with cursor.(not hjkl)

Ah my bad.  You said with the cursor.  Let me test again then.

**Comment by lacygoill** [comment]
Yes, I can reproduce the issue.

**Comment by kohnish** [comment]
Sorry I overcomplicated the issue, you don't need to start :term. I must've made a bad assumption, since I send this reset command mistakenly to the vim term and noticed the issue.   
It might take time, but I'm happy to investigate issue btw.

**Comment by lacygoill** [comment]
It was already mentioned, but just to give a little more info, the issue must be caused by the `-R` flag passed to the tmux command `send-keys` which resets the terminal state:

    bind-key r send-keys -R \; clear-history
                         ^^

Its online documentation can be found [here](https://man.openbsd.org/OpenBSD-current/man1/tmux.1#send-keys), and simply says:

   > The -R flag causes the terminal state to be reset.

---

As a (temporary?) workaround, you can execute any `:!` command (even an empty one).

**Comment by kohnish** [comment]
I see. It's just a copy paste option from the internet.
Thanks for such a fast support! @lacygoill 
Trying it now.

**Comment by lacygoill** [comment]
> It's just a copy paste option from the internet.

OK, so if you don't have a particular reason to reset the terminal state, I suggest you remove the `-R` flag.

If you do have a reason, the tmux key binding still doesn't seem useful when Vim is running in the current pane, because the purpose of `clear-history` is to clear the terminal scrollback buffer, which only exists while a shell is running in the pane.

So, how about disabling it when Vim is running?

    bind-key r if-shell -F '#{m:*vim,#{pane_current_command}}' '' { send-keys -R; clear-history }

The `if-shell` command expands the format `'#{m:*vim,#{pane_current_command}}'` which should be true only when Vim is running in the current pane.  When it's true, `if-shell` executes the empty string (i.e. it does nothing); and when it's false, it executes the original command (i.e. it resets the terminal state and clear the scrollback buffer).

---

Here is why `-R` causes an issue:

The terminal is in “normal mode” when you are on the shell's command-line, and in “application mode” when you are in a TUI program such as Vim.  Depending on the mode you're in, some special keys – like the cursor ones – send different escape sequences.

For example, in normal mode, `Left` sends `^[[D` (at least it does on my machine).  This can be tested by pressing `Left` while the `cat(1)` utility is running.

But in Vim, `Left` sends `^[OD`.  This can be tested by pressing `C-v` then `Left` on Vim's command-line, or by executing `:echo &t_kl`.

For more info, see:

- <http://invisible-island.net/xterm/xterm.faq.html#xterm_arrows>
- <http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys>

Vim's help uses a different terminology.  Instead of application mode, it uses the term "keypad transmit mode".

Anyway, when the tmux key binding resets the terminal state, the latter exits keypad transmit mode.  This is confirmed by the fact that if you press `Left`, this error is raised:

    E388: Couldn't find definition

That's because `Left` didn't send `^[OD` as before, but `^[[D`.  The initial escape has no effect, since you're in Vim's normal mode; but the remaining `[D` is executed as a standalone normal command, which explains the error message (`[D` raises `E388` if it can't find any macro matching the text under the cursor).

And when you execute any `:!` command, the terminal is put back in keypad transmit mode.

Note that you could achieve the same result by writing the escape sequence which is stored in the terminal option [`'t_ks'`](https://vimhelp.org/term.txt.html#t_ks), using the `echoraw()` function (the latter requires the patch [8.2.0258](https://github.com/vim/vim/releases/tag/v8.2.0258)):

    :call echoraw(&t_ks)

Also, instead of pressing `C-L` to redraw the screen, you can also execute `:redraw!`; so in a script, you could write:

    :call echoraw(&t_ks) | redraw!

**Comment by kohnish** [comment]
Thanks for the explanation! @lacygoill  
I think this is a designed behaviour. 

Indeed `bind-key r if-shell -F '#{m:*vim,#{pane_current_command}}' '' { send-keys -R; clear-history }` is what I need. I needed to change to `*vi*`, which might be dangerous, but works. :) fedora has , vi, vim, vimx.  
  
I didn't expect such a kind support from github issue. Thank you very much.

**Comment by kohnish** [comment]
For remote session, vim should be launched like this. 

` printf '\033]2;vim\033\\' && vim && printf '\033]2;ssh\033\\'`  

with this tmux option fto avoid -R destroying vim.
`bind-key r if-shell -F '#{m:*vi*,#{pane_title}}' '' { send-keys -R; clear-history }`
