### ISSUE TITLE
`keepjumps term <cmd>` affects more than one command

### ISSUE THREAD

**Issue by zealotrush** [vim/vim#8199]
**Describe the bug**

`keepjumps` should affect only one command. But when it's used with `term`, it affects more than one command.

**To Reproduce**
1. Edit two files: `vim --clean foo bar`
2. Clear jumplist: `:clearjumps`
3. Run some shell command in a terminal buffer: `:keepjumps term ls`
4. Switch buffer: `:buffer bar`
5. Checkout the jumplist: `:jumps`

We get an empty jumplist:

```
 jump line  col file/text
>
```

**Expected behavior**

One entry in the jumplist.
```
 jump line  col file/text
   1     1    0 foo
```

**My rationale**

`keepjumps` should only affect the `term ls` command. It should not affect the following `:buffer bar` command.

If we replace the `term ls` command with `help` command, and repeat the steps above, we can get the __expected behavior__.

**Environment**

 - Vim version: 8.2.2831
 - OS: macOS 11.3.1
 - Terminal: Alacritty

**Additional context**

Probably related issue: https://github.com/vim/vim/issues/8158

**Comment by brammool** [comment]
> **Describe the bug**
> 
> `keepjumps` should affect only one command. But when it's used with `term`, it affects more than one command.
> 
> **To Reproduce**
> 1. Edit two files: `vim --clean foo bar`
> 2. Clear jumplist: `:clearjumps`
> 3. Run some shell command in a terminal buffer: `:keepjumps term ls`
> 4. Switch buffer: `:buffer bar`
> 5. Checkout the jumplist: `:jumps`
> 
> We get an empty jumplist:
> 
> ```
>  jump line  col file/text
> >
> ```
> 
> **Expected behavior**
> 
> One entry in the jumplist.
> ```
>  jump line  col file/text
>    1     1    0 foo
> ```
> 
> **My rationale**
> 
> `keepjumps` should only affect the `term ls` command. It should not affect the following `:buffer bar` command.
> 
> If we replace the `term ls` command with `help` command, and repeat the steps above, we can get the __expected behavior__.
> 
> **Environment**
> 
>  - Vim version: 8.2.2831
>  - OS: macOS 11.3.1
>  - Terminal: Alacritty
> 
> **Additional context**
> 
> Probably related issue: https://github.com/vim/vim/issues/8158

I don't think this is a bug.  When using ":buf bar" in a finished
terminal it doesn't push a position, because returning there is not
possible.  Thus it's not related to using :keepjumps, but to using ":buf
bar" in a finished terminal.

If you do this:
	vim --clean foo bar
	:clearjumps
	:term ls
	:buf bar
	:jumps

You will only see the jump for "foo", which is where the ":term ls"
command was executed.  There is no jump for ":buf bar".

-- 
The software said it requires Windows 95 or better, so I installed Linux.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zealotrush** [comment]
> > If you do this:
	vim --clean foo bar
	:clearjumps
	:term ls
	:buf bar
	:jumps
>
> You will only see the jump for "foo", which is where the ":term ls"
command was executed.  There is no jump for ":buf bar".

I got this result:

```
 jump line  col file/text
   2     1    0 foo
```

Note that there are two jumps. In fact, I also noticed that after the `:term ls` command, there was only one jump. It was the `:but bar` command that make the jump number become two. I can't say this is a bug for sure, but I do think the behavior is confusing.

**Comment by brammool** [comment]
When using the ":buf bar" command in the finished terminal, there is nothing to jump back to.  That's why no entry is added to the jump list.

**Comment by zealotrush** [comment]
> When using the ":buf bar" command in the finished terminal, there is nothing to jump back to. That's why no entry is added to the jump list.

I can get the part that no entry is added to the jump list. _The number of jumps is increased by one_, that's the part where I felt confusing.

I just repeated the test with two commands: `term ls` and `help`, each command with or without `keepjumps`. The results make me feel confused even more.

**term ls**
```
 jump line  col file/text
   2     1    0 foo
>
```

**keepjumps term ls**
```
 jump line  col file/text
>
```

**help**
```
 jump line  col file/text
   1     1    0 help.txt
>
```

**keepjumps help**
```
 jump line  col file/text
   1     1    0 help.txt
>
```

I thought the one with the `help` command would get me two jumps, one for `:help` and one for `:buffer`. It's getting complicated and out of my interests now. I think I can live with the way it is.

**Comment by brammool** [comment]
> > When using the ":buf bar" command in the finished terminal, there is
> > nothing to jump back to. That's why no entry is added to the jump
> > list.
> 
> I can get the part that no entry is added to the jump list. _The
> number of jumps is increased by one_, that's the part where I felt
> confusing.
> 
> I just repeated the test with two commands: `term ls` and `help`, each
> command with or without `keepjumps`. The results make me feel confused
> even more.
> 
> **term ls**
> ```
>  jump line  col file/text
>    2     1    0 foo
> >
> ```
> 
> **keepjumps term ls**
> ```
>  jump line  col file/text
> >
> ```
> 
> **help**
> ```
>  jump line  col file/text
>    1     1    0 help.txt
> >
> ```
> 
> **keepjumps help**
> ```
>  jump line  col file/text
>    1     1    0 help.txt
> >
> ```
> 
> I thought the one with the `help` command would get me two jumps, one
> for `:help` and one for `:buffer`. It's getting complicated and out of
> my interests now. I think I can live with the way it is.

The :help command is special.  When navigating through code files and
then branching off to help, this is not considered the main path of
editing.  Thus the jump for :help is not in the list.  In the help
window itself you can go forward and backward through the help, thus
it's like branching off.

-- 
ARTHUR:    Well, it doesn't matter.  Will you go and tell your master that
           Arthur from the Court of Camelot is here.
GUARD #1:  Listen, in order to maintain air-speed velocity, a swallow
           needs to beat its wings 43 times every second, right?
ARTHUR:    Please!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
