### ISSUE TITLE
Vim9: segmentation fault when compiling function

### ISSUE THREAD

**Issue by lifepillar** [vim/vim#8217]
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Source this script:

```vim
vim9script

def F(G: func(func): void): func(any): void
  return (Cont) => G((t) => {
    })
enddef

defcompile
```

**Edit:** fix function signature.

You should see Vim crash.

**Expected behavior**
Not sure: I get `E488: Trailing characters: })` when the new line after `{` is removed, so the script above should at least produce the same error. But is this syntax invalid? If so, how do you define a lambda without a return value?

**Environment (please complete the following information):**
 - Vim 8.2.2850.
 - OS: macOS 11.3.1
 - Terminal: Apple Terminal

**Comment by lacygoill** [comment]
- [backtrace](https://github.com/vim/vim/files/6489899/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6489900/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6489898/asan.log)

---

> But is this syntax invalid? If so, how do you define a lambda without a return value?

I think the syntax is valid.  I use it in a few places ([like here](https://github.com/lacygoill/config/blob/af7bb4ba9382914b9679b7e519b126d0e8e5200c/.vim/vimrc#L3514-L3516) for example).  The only issue is that you can't use it in a command which takes another command as an argument (like an autocmd, or a global command).

---

It does not fix the crash, but I think the return type in the header should be `func` or maybe `func(any): void`:

    def F(G: func(func): void): func
                                ^--^

**Comment by lifepillar** [comment]
>the return type in the header should be `func` or maybe `func(any): void`

You are right. I have fixed the text of the issue.

>I think the syntax is valid.

Good to know. A workaround for this issue is to use `def` instead of a lambda:

```vim
def F(G: func(func): void): func(any): void
  def H(t: any): void
  enddef
  return (Cont) => G(H)
enddef

```

**Comment by brammool** [comment]
> 1. Run `vim --clean` (or `gvim --clean`, etc.)
> 2. Source this script:
> 
> ```vim
> vim9script
> 
> def F(G: func(func): void): void
>   return (Cont) => G((t) => {
>     })
> enddef
> 
> defcompile
> ```
> 
> You should see Vim crash.
> 
> **Expected behavior**
> Not sure: I get `E488: Trailing characters: })` when the new line after `{` is removed, so the script above should at least produce the same error. But is this syntax invalid? If so, how do you define a lambda without a return value?

This runs into the problem that using the {} block for a lambda isn't
yet supported inside a lambda.  That's a bit different from before,
since it could only be an expression.  Now it can be a sequence of
commands.  This requires some work...

-- 
GALAHAD: No, please.  Please! I can defeat them!  There's only a hundred.
GIRLS:   He will beat us easily.  We haven't a chance.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
