### ISSUE TITLE
Update rust runtime files

### ISSUE THREAD

**Issue by stsewd** [vim/vim#8218]
Hi, the runtime files for rust are out of date with https://github.com/rust-lang/rust.vim

Is it ok to send a PR with the current files from https://github.com/rust-lang/rust.vim or is it something that should be done by someone else? Thanks.

**Comment by k-takata** [comment]
Creating a PR by the maintainer is preferred.
The maintainer should decide which version to be included.

> Is it ok to send a PR with the current files from https://github.com/rust-lang/rust.vim

If you have permission from the maintainer, that should be ok.
But, no progress in [this issue](https://github.com/rust-lang/rust.vim/issues/426)?

**Comment by chrisbra** [comment]
Please work with that rust team to have new and approved runtime files send here (via mail or as a pull request), but those should be approved by the maintainers.. We generally do not download runtime files from anywhere on the internet, because we do not know, whether this is safe.

see also https://github.com/rust-lang/rust.vim/issues/326

**Comment by stsewd** [comment]
Thanks for the pointers, should I close this issue then?

**Comment by chrisbra** [comment]
so let's close it, until the upstream issues are solved.
