### ISSUE TITLE
Feature request: option to disable "Kill job in" dialog

### ISSUE THREAD

**Issue by strrchr** [vim/vim#8242]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
There is no option to disable "Kill job in" dialog now.

**Describe the solution you'd like**
I want an option to disable "Kill job in" dialog now.

**Comment by k-takata** [comment]
Which dialog?

**Comment by strrchr** [comment]
When close terminal, gvim will show a yesno dialog: "Kill job in".

**Comment by chrisbra** [comment]
You can simply use `:qa!`

**Comment by brammool** [comment]
This requires more details.  Please give a step-by-step reproduction, so we can understand what you are doing.
Also mention any relevant settings.

**Comment by strrchr** [comment]
1. On windows, start gvim.
2. Input :term<CR>
3. Click close button of the main gvim window.
4. Then there is a yesno dialog.
The gvim is just fresh downloaded from https://github.com/vim/vim-win32-installer/releases/download/v8.2.2825/gvim_8.2.2825_x86_signed.exe and installed.
@brammool

**Comment by dpelle** [comment]
On Linux, gtk3 GUI, I ran:
```
$ ./vim -f -g -c term
```
Then I tried to close the window of gvim (X button of window manager decoration).
I get the dialog box with text "Kill job "!/bin/bash"? and 3 buttons:
* Yes
* No
* Cancel

That seems reasonable to me.  Although I don't know what is the difference between "No" and "Cancel" (they seem to be doing the same thing).

Do I understand that you @strrchr  want an option to automatically quit gvim without the dialog box, as if you clicked on "Yes"?

**Comment by chrisbra** [comment]
Yes, on Windows, if I click on the little `X` button, it shows this dialogue:
![image](https://user-images.githubusercontent.com/244927/119532510-3d333c00-bd85-11eb-8f00-7ba905621cc9.png)


As said before, you can simply use `:qa!` to quit Vim.

**Comment by dpelle** [comment]
Adding a option may be feature creep and dangerous (what if you have an editor running in your terminal where you'd want to save something important?).

Still, I'm curious why we have different options "No" and "Cancel" that seem to be doing the same thing. Glancing at the code in in `terminal.c` we only check `VIM_YES` and `VIM_CANCEL`.  We don't check `VIM_NO` explicitly.  This looks wrong.  
```
  1604         ret = vim_dialog_yesnocancel(VIM_QUESTION, NULL, buff, 1);                                                             
  1605         if (ret == VIM_YES)
  1606             how = "kill";
  1607         else if (ret == VIM_CANCEL)
  1608             return FAIL;
```
Can't we instead call `vim_dialog_yesno()? at line 1060 and check `VIM_YES` and `VIM_NO`?

**Comment by brammool** [comment]
I don't think an option should control this.  It's more related to what you are doing in the terminal.  We could perhaps have a ":terminal" argument that means "OK to kill this".  Like when setting 'buftype' to "nowrite", which is buffer-local.
But we can't use that option, since 'terminal' is one of the values. 

You could perhaps use an ExitPre autocommand that finds terminal windows (with some check for the state) and closes them.

**Comment by strrchr** [comment]
I tried the following, but it not works. There is still a dialog which prevent me.
autocmd ExitPre * qa!

It seems that clicking gvim close button could not trigger ExitPre.

**Comment by brammool** [comment]
> I tried the following, but it not works. There is still a dialog which
> prevent me.
> autocmd ExitPre * qa!
> 
> It seems that clicking gvim close button could not trigger ExitPre.

You need to use QuitPre, it is triggered earlier.  However, you do need
to check if Vim is going to exit if you make it use ":qa", otherwise Vim
will exit if you close any window.  Better not use ":qa" at all but
another way to close the terminal.

-- 
Mental Floss prevents moral decay!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by strrchr** [comment]
autocmd ExitPre * qa!
autocmd QuitPre * qa!
autocmd VimLeavePre * qa!
autocmd VimLeave * qa!

These still not works.
When I click the close button of gvim win32 window, it still shows me a yesno dialog: "Kill job in ...?"
When I :vsplit then :q! I found it works.
But I need silently quit gvim when I click the close button of gvim win32 window.
It seems that clicking close button of gvim win32 window could not trigger ExitPre, QuitPre, VimLeavePre  or VimLeave.

**Comment by brammool** [comment]
Ah, when using the GUI window close button, another code path is used.  I'll fix that.
