### ISSUE TITLE
crash when passing empty slice string to "fullcommand()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8256]
**Describe the bug**

Passing an empty slice string to `fullcommand()` makes Vim crash.

**To Reproduce**

Run this shell command:

    vim -Nu NONE +"eval 'xxx'[-1]->fullcommand()"

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2885
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

- [backtrace](https://github.com/vim/vim/files/6537606/backtrace.txt)
- [valgrind log](https://github.com/vim/vim/files/6537607/valgrind.log)
- [asan log](https://github.com/vim/vim/files/6537605/asan.log)

---

cc @arp242 via https://github.com/vim/vim/pull/7777

**Comment by lacygoill** [comment]
Same issue when the slice is obtained with `slice()`:

    vim -Nu NONE +"eval 'xxx'->slice(0, 0)->fullcommand()"

**Comment by lacygoill** [comment]
Unrelated, but why does `fullcommand()` abbreviate `:keeppatterns` to `:k`?
```vim
echo fullcommand('keeppatterns')
```
    k

**Comment by arp242** [comment]
The `:keep*` returning `k` seems to be due to some special handling for this in `find_ex_command()`:

    if (*p == 'k')
    {
        eap->cmdidx = CMD_k;
        ++p;
    }

Not sure if I'm calling that function incorrect; this has [been there or at least 17 years](https://github.com/vim/vim/blame/872bee557e5f8ab0e4a523a6a845868a2801b17e/src/ex_docmd.c#L3559) 🤔

Anyway, I'll have a look at both issues later.
