### ISSUE TITLE
Cannot emit <CR> in mappings

### ISSUE THREAD

**Issue by noscript** [vim/vim#8275]
**Describe the bug**
Mappings cannot emulate pressing <kbd>Enter</kbd> key.

**To Reproduce**
1. Run `gvim --clean`
2. Create a mapping
```vim
nnoremap e :exe "normal! \<cr>"<cr>
```
3. Press <kbd>e</kbd>.
4. Error `E114: Missing quote: "normal! \`

**Expected behavior**
No error.

**Environment**
 - Vim 8.2.2836
 - OS: Ubuntu 20.04
 - Terminal: GUI

**Comment by lacygoill** [comment]
Try to use `<lt>` to delay the translation of the `<cr>` keycode:

    nnoremap e :exe "normal! \<cr>"<cr>
                             ^---^
                               ✘

    nnoremap e :exe "normal! \<lt>cr>"<cr>
                             ^------^
                                ✔

**Comment by noscript** [comment]
I can confirm it works using `<lt>`. Is this expected? Neither `:normal` nor `feedkeys()` documentation mentions this.

**Comment by chrisbra** [comment]
this has nothing to do with `:normal`, quoted strings or so. I think you need to escape the key properly. This notation is mentioned at `:h <>`

**Comment by lacygoill** [comment]
> Is this expected?

Yes:

                                                     vv
    $ vim -Nu NONE --cmd 'nnoremap e :exe "normal! \<cr>"<cr>|nno | cq'
    n  e           * :exe "normal! \<CR>"<CR>
                                     ^^

In the output of the shell command, notice that `cr` has been automatically uppercased, even though – in your mapping – you wrote the keycode in lowercase.  That's because `:nnoremap` automatically translates `<cr>` into a literal carriage return.  BTW, there is no need of double quotes nor of a backslah:

                                      vv
    $ vim -Nu NONE --cmd 'nnoremap e <cr>|nno | cq'
    n  e           * <CR>
                      ^^

But this automatic translation will cause an issue when you press the mapping because it will end/validate the Ex command prematurely.  That is, this Ex command will be executed:

    :exe "normal! \

While you want this Ex command to be executed:

    :exe "normal! \<cr>"<cr>

For this to be possible, you need to prevent `:nnoremap` from translating `<cr>` into a literal carriage return, which you can do with `<lt>`:

    nnoremap e :exe "normal! \<lt>cr>"<cr>
                              ^--^

When `:nnoremap` sees `<lt>`, it automatically translates it into `<`.  Afterward, it sees `cr>`, which is an incomplete keycode; therefore, no translation.  In the end, the mappings table contains this entry:

                                                    v--v
    $ vim -Nu NONE --cmd 'nnoremap e :exe "normal! \<lt>cr>"<cr>|nno | cq'
    n  e           * :exe "normal! \<cr>"<CR>
                                     ^^

Notice that this time, `<cr>` has not been uppercased, meaning it was not translated into a literal carriage return; it's just the sequence of keys `<`, `c`, `r`, `>`.  That's not an issue though, because when you'll press your mapping, and `:exe` will be executed, Vim will have to translate `\<cr>` into a literal carriage return (on the condition that it's inside a double-quoted string).
