### ISSUE TITLE
clipboard=unnamed makes P/p behave as zP/zp

### ISSUE THREAD

**Issue by lkintact** [vim/vim#8301]
**Describe the bug:**
Setting 'clipboard' to "unnamed" makes `P` behave as `zP` and `p` as `zp`, respectively.

**To Reproduce:**
1. Run `gvim --clean`
2. Execute `:set clipboard=unnamed`
3. Put this text to the buffer:
```
a1
bc23
def456
```
4. Visual block-select the text with <kbd>Ctrl</kbd>+<kbd>v</kbd> and press <kbd>y</kbd> to yank it
5. Press <kbd>P</kbd>. The text changes to
```
a1a1
bc23bc23
def456def456
```

**Expected behavior:**
The text should become

```
a1    a1
bc23  bc23
def456def456
```

**Environment:**
 - Vim version 8.2.2914
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

**Comment by chrisbra** [comment]
I cannot reproduce this on linux

**Comment by habamax** [comment]
I can repro it on windows:

![vim-p-unnamed](https://user-images.githubusercontent.com/234774/120197227-693d3a00-c229-11eb-9cbe-5fd10fd74b76.gif)

**Comment by habamax** [comment]
It is actually not about "clipboard=unnamed" it is about pasting from `*` register, I get the same issue with `"*P`

**Comment by brammool** [comment]
I also cannot reproduce it (on Linux).  Also not with "*P

**Comment by matveyt** [comment]
Reproducible on Windows if `&virtualedit` is empty... Actually it looks even reasonable to me, although it's clearly inconsistent.

**Comment by chrisbra** [comment]
I'll have to build and check on windows later today

**Comment by chrisbra** [comment]
This is actually a bug that was there before including the `zp` feature. I think this comes from the fact that `do_put()` calls `may_get_selection()` which eventually calls `clip_yank_selection()` which calls `str_to_reg()` with a blocklen of `0`, which causes the block_size of the register to be set to zero and which basically makes `p` behave as `zp`.

I think, this patch fixes it:
```patch
diff --git a/src/clipboard.c b/src/clipboard.c
index c26349291..0b42dabda 100644
--- a/src/clipboard.c
+++ b/src/clipboard.c
@@ -2090,7 +2090,7 @@ clip_yank_selection(

     clip_free_selection(cbd);

-    str_to_reg(y_ptr, type, str, len, 0L, FALSE);
+    str_to_reg(y_ptr, type, str, len, y_ptr->y_width, FALSE);
 }
```
but not sure of the consequences.

**Comment by habamax** [comment]
>I think, this patch fixes it:

I can test it when it is in nightly build (can't build it myself on win box), idk if anyone else can do it before nightly.

**Comment by brammool** [comment]
> This is actually a bug that was there before including the `zp`
> feature. I think this comes from the fact that `do_put()` calls
> `may_get_selection()` which eventually calls `clip_yank_selection()`
> which calls `str_to_reg()` with a blocklen of `0`, which causes the
> block_size of the register to be set to zero and which basically makes
> `p` behave as `zp`.
> 
> I think, this patch fixes it:
> ```patch
> diff --git a/src/clipboard.c b/src/clipboard.c
> index c26349291..0b42dabda 100644
> --- a/src/clipboard.c
> +++ b/src/clipboard.c
> @@ -2090,7 +2090,7 @@ clip_yank_selection(
> 
>      clip_free_selection(cbd);
> 
> -    str_to_reg(y_ptr, type, str, len, 0L, FALSE);
> +    str_to_reg(y_ptr, type, str, len, y_ptr->y_width, FALSE);
>  }
> ```
> but not sure of the consequences.

Hmm, perhaps it should check the register already was a block?
It would actually not need to update the register at all, since it was
already done.

BTW: the computation of y_width in str_to_reg() looks wrong for
multi-byte characters, it uses the byte length instead of the actual
width for "maxlen".  Perhaps this isn't actually used?

-- 
Dreams are free, but there's a small charge for alterations.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> Hmm, perhaps it should check the register already was a block?

Not sure I understand. Where should this happen?

> It would actually not need to update the register at all, since it was
already done.

Well, if 'clipboard' contains unnamed, we need to fetch it from the clipboard. I think the initial intention was that we cannot really get a visual block from the system, so the blocklen parameter was set to zero. Actually, when looking at this condition in `str_to_reg()`:

```C
     if (type == MBLOCK)
          y_ptr->y_width = (blocklen < 0 ? maxlen - 1 : blocklen);
      else
          y_ptr->y_width = 0;
```

I am wondering whether the condition `blocklen < 0` should actually be `blocklen <= 0`, so that it counts the width.

> BTW: the computation of y_width in str_to_reg() looks wrong for
> multi-byte characters, it uses the byte length instead of the actual
> width for "maxlen".  Perhaps this isn't actually used?

Yes, indeed, it counts bytes. Next problem spotted :/

**Comment by brammool** [comment]
> > Hmm, perhaps it should check the register already was a block?
> 
> Not sure I understand. Where should this happen?

In your patch, when you use the previous y_width.

> > It would actually not need to update the register at all, since it was
> > already done.
> 
> Well, if 'clipboard' contains unnamed, we need to fetch it from the
> clipboard.

I would think in this situation we have just set the clipboard.
Hmm, but it could possibly be changed elsewhere in between.
Would it work that when y_width is non-zero, we know the clipboard was
filled by this Vim?  I don't think we can be sure about that:

	- Block-yank some text
	- Other program changes clipboard
	- Vim uses width of previous block-yank with current clipboard

That would be wrong, right?  We need to have some way to know that the
text in the clipboard is what Vim put there, and it didn't change.

> I think the initial intention was that we cannot really get
> a visual block from the system, so the blocklen parameter was set to
> zero. Actually, when looking at this condition in `str_to_reg()`:
> 
> ```C
>      if (type == MBLOCK)
>           y_ptr->y_width = (blocklen < 0 ? maxlen - 1 : blocklen);
>       else
>           y_ptr->y_width = 0;
> ```
> 
> I am wondering whether the condition `blocklen < 0` should actually be
> `blocklen <= 0`, so that it counts the width.

Corner case.  Better try it out instead of guessing.  Possibly we should
pass -1 at the caller side.

> > BTW: the computation of y_width in str_to_reg() looks wrong for
> > multi-byte characters, it uses the byte length instead of the actual
> > width for "maxlen".  Perhaps this isn't actually used?
> 
> Yes, indeed, it counts bytes. Next problem spotted :/

I wonder if we fix the -1 vs 0 problem and fix this computation it works
correctly?

-- 
Every exit is an entrance into something else.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> I wonder if we fix the -1 vs 0 problem and fix this computation it works correctly?

I think so. I create PR #8317 for that.
