### ISSUE TITLE
Vim9: internal error when passing void value to "abs()"

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8387]
**Describe the bug**

In Vim9 script, passing a void value to the `abs()` function gives an internal error.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
        enddef
        Func()->abs()
    EOF
    )

`E685` is raised:

    E685: Internal error: tv_get_number(UNKNOWN)

**Expected behavior**

Instead of an internal error, a regular type mismatch error is given.  Maybe this one:

    E1013: Argument 1: type mismatch, expected number but got void

**Environment**

 - Vim version: 8.2 Included patches: 1-3004
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

In a `:def` function, the exact same code gives a regular type mismatch error:
```vim
vim9script
def Func()
enddef
def Eval()
    Func()->abs()
enddef
Eval()
```
    E1013: Argument 1: type mismatch, expected number but got void

---

An internal error is also given for a value of unknown type:
```vim
vim9script
test_unknown()->abs()
```
    E685: Internal error: tv_get_number(UNKNOWN)

This time, the issue persists in compiled code:
```vim
vim9script
def Func()
    test_unknown()->abs()
enddef
Func()
```
    E685: Internal error: tv_get_number(UNKNOWN)

I don't know how to generate a value of unknown type without this testing function.  If a crash or internal error is found, and it involves `test_unknown()`, should it be reported?

**Comment by k-takata** [comment]
Closed by [8.2.3005](https://github.com/vim/vim/commit/f57b43c230c23117650c956c1f62546a34500fb6).

**Comment by lacygoill** [comment]
Although, there might still be an issue with values of unknown type:
```vim
vim9script
test_unknown()->abs()
```
    E685: Internal error: tv_get_number(UNKNOWN)

I want to try to test hundreds of builtin functions.  It seems several of them give internal errors when receiving values of unknown type.  I need to know if this is expected or needs to be reported.

**Comment by brammool** [comment]
> Although, there might still be an issue with values of unknown type:
> ```vim
> vim9script
> test_unknown()->abs()
> ```
>     E685: Internal error: tv_get_number(UNKNOWN)
> 
> I want to try to test hundreds of builtin functions.  It seems several
> of them give internal errors when receiving values of unknown type.  I
> need to know if this is expected or needs to be reported.

If you use test_unknown() it is expected that you get to internal
errors.  That's what the test facilities are for, to go through code
paths that would otherwise not be reached.

If you get an internal error without using a test function, then that's
most likely a bug.  Note that I recently made :def functions return void
instead of zero, and for lambda make the return type unknown until it is
compiled.  These changes have improved some things, but may also have
caused some bugs.

-- 
An alien life briefly visits earth.  Just before departing it leaves a
message in the dust on the back of a white van.  The world is shocked
and wants to know what it means.  After months of studies the worlds
best linguistic scientists are able to decipher the message: "Wash me!".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
