### ISSUE TITLE
.vimrc and .vim are not created while download process

### ISSUE THREAD

**Issue by ghost** [vim/vim#8419]
**Describe the bug**
While installing vim .vimrc and .vim (except .viminfo) don't appear in my home directory. I've tried both ways installing with `apt-get` and from source code.

**Environment**
 - OS: Ubuntu 20.04
 - Terminal: GNOME Terminal

**Additional context**
Actually would it be righteous enough to create these files just manually.
![Screenshot from 2021-06-21 19-30-21](https://user-images.githubusercontent.com/43008574/122796499-240ba580-d2c7-11eb-94ec-30b3028779ab.png)

**Comment by vim-ml** [comment]
On 2021-06-21, VOV4ANSKi wrote:
> Describe the bug
> While installing vim .vimrc and .vim (except .viminfo) don't appear in my home
> directory. I've tried both ways installing with apt-get and from source code.
> 
> Environment
> 
>   • OS: Ubuntu 20.04
>   • Terminal: GNOME Terminal
> 
> Additional context
> Actually would it be righteous enough to create these files just manually.
> Screenshot from 2021-06-21 19-30-21

.vim and .vimrc are optional user configuration files and not
created automatically.  See:

    :help vimrc-intro

I can't find a reference for the creation of ~/.vim.

.viminfo is created by vim when it exits.  See:

    :help viminfo

Regards,
Gary

**Comment by chrisbra** [comment]
That is not a Vim issue. I you need a pre-configured vimrc file, I think you can use `/etc/skel`, but I don't think when installing Vim (by whatever means) we should create a proper vimrc file. That is very user specific. A system administrator may however decide to prepare a .vimrc file and place it into `/etc/skel` so that it will be deployed when creating a user.

**Comment by VOV4ANSKi** [comment]
Thanks everybody for explanation!
