### ISSUE TITLE
'echoe' by channel command does not work.

### ISSUE THREAD

**Issue by AnnoyingUserName** [vim/vim#8494]
**Describe the bug**
It is OK for `echo` or `echom` by channel command, but not for 'echoe'.

**To Reproduce**
1. Run `vim --clean` or `gvim --clean`.
2. Run `$VIMRUNTIME/tools/demoserver.py`  (see `:help channel-demo`).
3. Connect to the channel in vim by `let channel = ch_open('localhost:8765')`.
4. Send messages, `["ex", "echo 'This is echo'"]`, `["ex", "echom 'This is echom'"]`, and `["ex", "echoe 'This is echoe'"]`.
5. You will find `echo` and `echom` work as expected, but `echoe` not.

**Environment (please complete the following information):**
 - Vim version IMproved 8.2 (2019 Dec 12)
 - OS: Ubuntu 18.04.5

It also appear with GVim8.2 on Windows 7.

**Comment by brammool** [comment]
> **Describe the bug**
> It is OK for `echo` or `echom` by channel command, but not for 'echoe'.
> 
> **To Reproduce**
> 1. Run `vim --clean` or `gvim --clean`.
> 2. Run $VIMRUNTIME/tools/demoserver.py  (see `:help channel-demo`).
> 3. Connect to the channel in vim by `let channel = ch_open('localhost:8765')`.
> 3. Send messages, `["ex", "echo 'This is echo'"]`, `["ex", "echom 'This is echom'"]`, and `["ex", "echoe 'This is echoe'"]`.
> 4. You will find `echo` and `echom` work as expected, but `echoe` not.
> 
> **Environment (please complete the following information):**
>  - Vim version IMproved 8.2 (2019 Dec 12)
>  - OS: Ubuntu 18.04.5
> 
> It also appear with GVim8.2 on Windows 7.

Yes, this is because error messages are suppressed.  It is expected that
the caller handles errors somehow.  This wasn't prepared for explicitly
displaying an error message.

We can make an exception if the command starts with "echoe".

-- 
hundred-and-one symptoms of being an internet addict:
69. Yahoo welcomes you with your own start page

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by AnnoyingUserName** [comment]
> We can make an exception if the command starts with "echoe".

I have read `help try`, `help catch` , and `help exception-handling`, but I still confused about handling the exception caused by channel command, Would you please show more detail about it? Thanks a lot!

**Comment by AnnoyingUserName** [comment]
Sorry, I did not notice the commit you mentioned... I have no problem anymore.

**Comment by brammool** [comment]
> > We can make an exception if the command starts with "echoe".
> 
> I have read `help try`, `help catch` , and `help exception-handling`,
> but I still confused about handling the exception caused by channel
> command, Would you please show more detail about it? Thanks a lot!

Exception handling for channel events is tricky.  It took me some time
to make the test work.  For a real plugin it might be simpler though.
Obviously, any plugin should try very hard to avoid errors, since the
user could be doing anything when a message is handled.

-- 
hundred-and-one symptoms of being an internet addict:
73. You give your dog used motherboards instead of bones

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
