### ISSUE TITLE
Changing the encryption key doesn't trigger changes in the file for `x`

### ISSUE THREAD

**Issue by fourlastor** [vim/vim#8557]
**Describe the bug**
When opening a file and changing **only** the encryption key, using `x` to save and close won't detect any change and won't update the file encryption key.

**To Reproduce**
1. Open a new file in vim
2. Add some text and set an encryption key
3. Close the file, reopen it, change only the encryption key
4. Close the file with `:x`, the encryption key isn't updated and the file is unchanged
5. Alternatively, save the file and then close it, the encryption key is updated this way

**Expected behavior**
Changing the encryption key of a file should cause `x` to detect changes and save the file before exiting

**Screenshots**

https://user-images.githubusercontent.com/1263058/125267068-5cb70180-e2fe-11eb-83d9-9c1bb1eda11f.mov

**Environment (please complete the following information):**
 - Vim version
 ```
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 10 2020 20:32:49)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
```
 - OS: macOS 10.15.17
 - Terminal: zsh

**Comment by brammool** [comment]
This is intentional.  I understand it's a bit unexpected, but Vim requires an explicit file write.
The main reason is to not accidentally write the file with a wrong key, or change the key of the wrong file.
This is explained in the help for ":X".
This is consistent with the file not being considered changed when 'cryptmethod' was changed.
