### ISSUE TITLE
Vim9: cannot always pass reltime() to reltimefloat()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8562]
**Describe the bug**

In Vim9 script, we cannot always pass the output of `reltime()` to `reltimefloat()`.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        def Func()
            []
            ->reltime()
            ->reltimefloat()
        enddef
        Func()
    EOF
    )

`E1013` is raised:

    E1013: Argument 1: type mismatch, expected list<number> but got number

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-3154
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

If the exact same code is run at the script level, no error is raised:
```vim
vim9script
[]
->reltime()
->reltimefloat()
echo 'no error'
```
    no error

Which is inconsistent.

---

The code worked fine until recently.

---

I understand the error: instead of returning a list, `reltime()` returns the number `0` when receiving an empty list as its input.  I still think this is a bug, because it forces us to handle a special case when using `reltime()` and `reltimefloat()`.

Maybe `reltimefloat()` should accept a number.  Or better yet, maybe `reltime([])` should return a list when receiving `[]` as its input:

    echo reltime([])
    []

Or:

    echo reltime([])
    [0, 0]

**Comment by brammool** [comment]
> **Describe the bug**
> 
> In Vim9 script, we cannot always pass the output of `reltime()` to `reltimefloat()`.
> 
> **To Reproduce**
> 
> Run this shell command:
> 
>     vim -Nu NONE -S <(cat <<'EOF'
>         vim9script
>         def Func()
>             []
>             ->reltime()
>             ->reltimefloat()
>         enddef
>         Func()
>     EOF
>     )
> 
> `E1013` is raised:
> 
>     E1013: Argument 1: type mismatch, expected list<number> but got number
> 
> **Expected behavior**
> 
> No error is raised.
> 
> **Environment**
> 
>  - Vim version: 8.2 Included patches: 1-3154
>  - OS: Ubuntu 20.04.2 LTS
>  - Terminal: XTerm(353)
> 
> **Additional context**
> 
> If the exact same code is run at the script level, no error is raised:
> ```vim
> vim9script
> []
> ->reltime()
> ->reltimefloat()
> echo 'no error'
> ```
>     no error
> 
> Which is inconsistent.
> 
> ---
> 
> The code worked fine until recently.

Actually, it was broken.  But since reltime() returns zero in that case,
and reltimefloat() returns 0.0, it looked like it was OK, no error was
given.  It was failing silently.

> I understand the error: instead of returning a list, `reltime()`
> returns the number `0` when receiving an empty list as its input.  I
> still think this is a bug, because it forces us to handle a special
> case when using `reltime()` and `reltimefloat()`.
> 
> Maybe `reltimefloat()` should accept a number.  Or better yet, maybe
> `reltime([])` should return a list when receiving `[]` as its input:
> 
>     echo reltime([])
>     []
> 
> Or:
> 
>     echo reltime([])
>     [0, 0]

I wonder if returning a valid "zero time" is better than returning zero.
The main problem is that the error can't be detected.

	let result = reltime(someList)
	if result == 0
	  echoerr 'invalid value'
  	endif

We could give an error instead of silently failing and returning zero.
That avoids that the error is given by what follows, reltimefloat() in
this case.  Only in Vim9 script, otherwise we break legacy plugins.

-- 
The coffee just wasn't strong enough to defend itself -- Tom Waits

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
