### ISSUE TITLE
filename-modifer :8 has been changed between 8.0 and 8.2

### ISSUE THREAD

**Issue by Grueslayer** [vim/vim#8600]
Somewhere between 8.0 and 8.2 the *filename-modifier* `:8` has been changed. The docs saying it is only working on parts of the path that already exist, BUT

in 8.0 it *appends* the rest

```
echo fnamemodify('C:\windows\newfile.txt',':p:8')
```

gives `C:\windows\newfile.txt`.

in 8.2 it *removes* the rest

```
echo fnamemodify('C:\windows\newfile.txt',':p:8')
```

gives `C:\windows`.

That breaks some existing code.

**Comment by Grueslayer** [comment]
@brammool Any news on this?

**Comment by k-takata** [comment]
Could you find which patch caused this?

**Comment by dpelle** [comment]
To @Grueslayer : does the file `C:\windows\newfile.txt` exist on your system ?
I cannot try to reproduce this bug myself as I only have Linux.

**Comment by brammool** [comment]
I hope someone who regularly uses MS-Windows can look into this. The relevant code is probably near the start of src/filepath.c.
Have you actually tried different Vim versions on the same system?  It's also possible that MS-Windows changed the behavior.
Or the removal of support for old MS-Windows systems might have affected it (using the wide API instead of the old one).

**Comment by chrisbra** [comment]
I can reproduce. I bisected to v8.1.2234 (3f39697b73f661d6900c7cf5430d967a129660d7). The logic looks right, not sure why this patch causes it :)
