### ISSUE TITLE
vim9: cannot unlet s: variable from command: "Cannot unlet s:script"

### ISSUE THREAD

**Issue by arp242** [vim/vim#8609]
For example, I stuck this in my vimrc:

    vim9script
    command! Test var s:script = 'xx' | echom s:script | unlet script

Which outputs:

    :Test
    xx
    E1081: Cannot unlet s:script

Unless I misunderstood something, I believe this should work?

As a work-around, I now use a global variable, which does seem to work:

    command! Test g:script = 'xx' | echom g:script | unlet g:script

Vim 8.2.3197

**Comment by lacygoill** [comment]
> Unless I misunderstood something, I believe this should work?

No, script-local variables cannot be deleted.  This is documented at [`:help vim9-namespace`](https://vimhelp.org/vim9.txt.html#vim9-namespace):

   > The variables at the file level are very much like the script-local "s:"
   > variables in legacy Vim script, but the "s:" is omitted.  And they cannot be
   > deleted.

I can't remember where, but I seem to remember a discussion where it was said that deleting a variable was not common in other programming languages.

---

> As a work-around, I now use a global variable, which does seem to work:

You probably don't need a global variable, which might conflict with another plugin.  But it's hard to say what is the best workaround without knowing the actual goal of the command.

FWIW, in practice, to refactor a legacy `unlet s:name`, I reassign the variable with an "empty" value (0, `""`, `[]`, `{}`, ...), and then instead of testing the existence of the variable, I check whether it's empty (or I use the null coalescing operator `??`).  As an example, [here](https://github.com/lacygoill/vim-fuzzy/blob/155b9e5041bc05be622e4997e3e0746cadd12a4a/autoload/fuzzy.vim#L1672) the variable `filtered_source` is reassigned an empty list:

    filtered_source = []

And [here](https://github.com/lacygoill/vim-fuzzy/blob/155b9e5041bc05be622e4997e3e0746cadd12a4a/autoload/fuzzy.vim#L1379), the null coalescing operator tests whether the variable is empty:

                                                   vv
    var matchlist: list<string> = (filtered_source ?? source)
        ->...

In legacy, you would probably have deleted the variable with `unlet!`:

    unlet! s:filtered_source

And you would have tested its existence with `get()`:

    let matchlist = get(s:, 'filtered_source', source)

**Comment by lacygoill** [comment]
Not sure, but, assuming it's the correct way to refactor a legacy `unlet! s:name`, we might want to document this.

**Comment by lacygoill** [comment]
> you never need `s:` in a Vim9 script.

Unless you write a user function whose name starts with a lowercase character; which is why I always start such a name with an uppercase.  As a benefit, it's easier to distinguish between user functions and builtin ones:  lowercase = builtin, uppercase = user.

**Comment by arp242** [comment]
> I can't remember where, but I seem to remember a discussion where it was said that deleting a variable was not common in other programming languages.

I guess, but a script-local variables aren't quite the same as variables in most programming languages. There's a reason you *can* delete buffer-local and window-local variables.

And it's not that uncommon people use it though:

```
[~pack]% ag 'unlet s:' | grep -v cpo
vim-lsc/autoload/lsc/diagnostics.vim:          unlet s:highest_used_diagnostic
vim-lsc/autoload/lsc/diagnostics.vim:    unlet s:file_diagnostics[a:file_path]
vim-lsc/autoload/lsc/diagnostics.vim:         unlet s:highest_used_diagnostic
vim-lsc/autoload/lsc/diagnostics.vim:  unlet s:quickfix_debounce
vim-lsc/autoload/lsc/file.vim:    unlet s:file_versions[a:full_path]
vim-lsc/autoload/lsc/file.vim:    unlet s:file_content[a:full_path]
vim-lsc/autoload/lsc/file.vim:      unlet s:file_versions[l:buffer.name]
vim-lsc/autoload/lsc/file.vim:        unlet s:file_content[l:buffer.name]
vim-lsc/autoload/lsc/file.vim:    unlet s:flush_timers[a:file_path]
vim-mundo/tests/bundled/lh-vim-lib/autoload/lh/menu.vim:    silent! unlet s:is_in_visual_mode
vim-mundo/tests/bundled/lh-vim-lib/tests/lh/topological-sort.vim:    unlet s:old_print_test
vim-mundo/tests/bundled/ut/autoload/lh/UT.vim:    unlet s:errors.crt_test
```

And in the vim runtime directory:

```
[~vim]% ag 'unlet s:' | grep -v cpo | wc -l
147
```

Especially from commands and autocmds it's somewhat common: `s:` function as temporary variable, for example to store/restore a register, winsaveview(), etc, but also just for clarity if you want:

    command Foo
        \  let s:v = 'a very long command'
        \| call foo#bar#function(s:v, 'other arg')
        \| unlet s:v

There isn't really a good way to solve this since `var` on an already define variable is an error, so you need an `if`, never mind that all `s:` variables in my vimrc now need to use unique variable names.

You could wrap all of that in a function, but meh.

**Comment by brammool** [comment]
> > Unless I misunderstood something, I believe this should work?
> 
> No, script-local variables cannot be deleted.  This is documented at
> [`:help
> vim9-namespace`](https://vimhelp.org/vim9.txt.html#vim9-namespace):
> 
>    > The variables at the file level are very much like the script-local "s:"
>    > variables in legacy Vim script, but the "s:" is omitted.  And
>    > they cannot be deleted.
> 
> I can't remember where, but I seem to remember a discussion where it
> was said that deleting a variable was not common in other programming
> languages.

The technical reason is that in compiled functions that access
script-local variables, we do not want to lookup the variable in a
dictionary, which is a bit slow, but find them directly by index.

If it's possible to delete a script variable we would also need an extra
check that it still exists.  And the function must be compiled before
deleting the variable.  You can see this creates all kinds of corner
cases.  Example:

	var text = 'example'
	def Echo()
	  echo text
	enddef
	unlet text
	defcompile  # what happens here?
	

Since most programming languages do not allow for undoing a variable
declaration, disallowing :unlet is the most natural solution.

You can use a block to have a variable with limited scope:

	{
	  var text = 'example'
	  echo text  # works
	}
	echo text    # fails

In the past :unlet was also used to free up memory, but these days
that's hardly relevant.  Unless the variable contains a lot of stuff, in
which case you can make it empty, as lacygoill suggested.


-- 
hundred-and-one symptoms of being an internet addict:
199. You read this entire list of symptoms, looking for something
     that doesn't describe you.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
> You can use a block to have a variable with limited scope:

Ah thanks, I tried using lambda functions (but couldn't get that to work) and
for some reason I didn't expect blocks to work inside commands or autocmds.

It took me a bit of trying to get the syntax right – you need to put a `|` in front of every line (including the closing `}`:

	comm Test {
		|      echom 42
		| }

So you end up with something like:

	# Call uni on current character or visual selection.
	comm -range UnicodeName {
		| var save = @a
		| if <count> == -1  | @a = strcharpart(strpart(getline('.'), col('.') - 1), 0, 1)
		| else              | exe 'normal! gv"ay' | endif
		| echo system('uni -q i', @a)[: -2]
		| @a = save
		|}

    # Format buffer on write.
    au BufWritePre *.go {
		| var save = winsaveview()
		| silent! exe 'undojoin | keepjumps :%!goimports 2>/dev/null || cat /dev/stdin'
		| winrestview(save)
		|}

Which actually doesn't look too bad, and scoping it is a better solution than let/unlet anyway.

Actually, a case could probably be made to just automatically run this in its own scope in the first place if vim9script is used(?)

**Comment by brammool** [comment]
Martin Tournoij wrote:

> > You can use a block to have a variable with limited scope:
> 
> Ah thanks, I tried using lambda functions (but couldn't get that to
> work) and
> for some reason I didn't expect blocks to work inside commands or autocmds.
> 
> It took me a bit of trying to get the syntax right – you need to put a
> `|` in front of every line (including the closing `}`:
> 
> 	comm Test {
> 		|      echom 42
> 		| }
> 
> So you end up with something like:
> 
> 	# Call uni on current character or visual selection.
> 	comm -range UnicodeName {
> 		| var save = @a
> 		| if <count> == -1  | @a = strcharpart(strpart(getline('.'), col('.') - 1), 0, 1)
> 		| else              | exe 'normal! gv"ay' | endif
> 		| echo system('uni -q i', @a)[: -2]
> 		| @a = save
> 		|}
> 
>     # Format buffer on write.
>     au BufWritePre *.go {
> 		| var save = winsaveview()
> 		| silent! exe 'undojoin | keepjumps :%!goimports 2>/dev/null || cat /dev/stdin'
> 		| winrestview(save)
> 		|}
> 
> Which actually doesn't look too bad, and scoping it is a better
> solution than let/unlet anyway.

Thanks for the examples.  Let me add something like that to the Vim9
help.

> Actually, a case could probably be made to just automatically run this
> in its own scope in the first place if vim9script is used(?)

Well, it would be possible, but it also adds some overhead.  In many
cases you would call a function, in which case the extra scope is not
needed.


-- 
panic("Foooooooood fight!");
	-- In the kernel source aha1542.c, after detecting a bad segment list

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> There's a reason you can delete buffer-local and window-local variables.

These variables are different, because anybody can write in them; my plugin can write in `w:name`, your plugin can write in `w:name`... (unless it's locked).  They're not declared, just assigned.  And I don't think they have an equivalent in other languages.

As a summary, here are the properties of variables in Vim9:

    ┌────────────────────────────┬──────────────────────────────────────────────────┐
    │                            │                    property                      │
    │                            ├──────────────────┬───────────────┬───────────────┤
    │                            │    declarable    │  assignable   │   deletable   │
    ├──────────────────┬─────────┼──────────────────┼───────────────┼───────────────┤
    │                  │ public  │        ✘         │       ✔       │       ✔       │
    │ type of variable ├─────────┼──────────────────┼───────────────┼───────────────┤
    │                  │ private │        ✔         │       ✔       │       ✘       │
    └──────────────────┴─────────┴──────────────────┴───────────────┴───────────────┘

"Public" means buffer-local, global, tab-local and window-local (and some internal ones like `v:errmsg`).

"Private" means anything else: script-local, function-local, block-local, function argument.

> And it's not that uncommon people use it though:

Yes, I agree.  I think it's a common pitfall which needs some documentation.  Maybe we should recommend making a script-local variable empty instead of deleting it.  And add a remark that it makes the code easier to read.  I very much prefer reading this:

    echo foo ?? bar

Than this:

    echo get(s:, 'foo', s:bar)

Or worse, this:

    echo exists('s:foo') ? s:foo : s:bar

If only because the null coalescing operator is not specific to Vim9.  It also exists with the exact same syntax in [C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator), [javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator), [php](https://www.php.net/manual/en/migration70.new-features.php), and [swift](https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html).  So, its knowledge can be transferred over there.

> There isn't really a good way to solve this since var on an already define variable is an error, so you need an if, never mind that all s: variables in my vimrc now need to use unique variable names.

If they all serve a similar purpose, maybe you could declare one variable at the top of your vimrc:
```vim
vim9script
var temp: any
```
Then, in your commands and autocmds, you would just (re-)assign whatever value you want:
```vim
vim9script
var temp: any
command Cmd1 temp = 123 | echo temp
command Cmd2 temp = 'string' | echo temp
Cmd1
Cmd2
```
    123
    string

Similarly, you could use a dynamic stack:
```vim
vim9script
var temp: list<any>
command Cmd1 temp->add(123) | echo temp[-1] | temp->remove(-1)
command Cmd2 temp->add('string') | echo temp[-1] | temp->remove(-1)
Cmd1
Cmd2
```
    123
    string

> You could wrap all of that in a function, but meh.

Yes, that's exactly what I do.  If only because it makes Vim compile the code, which makes it faster, but much more importantly, it gives you *some* guarantees regarding its validity:
```vim
vim9script
command Cmd echo 1 / 0
echo ':Cmd is broken, but no error is given'
```
    :Cmd is broken, but no error is given
```vim
vim9script
command Cmd Cmd()
def Cmd()
    echo 1 / 0
enddef
defcompile
```
    E1154: Divide by zero

All you need to do is temporarily write `:defcompile` at the end of your vimrc.  All your functions get compiled, and in each function all the code paths get tested.

> for some reason I didn't expect blocks to work inside commands or autocmds.

Any Ex command which is executed by another Ex command is run in the Vim9 script context; i.e. exactly like if it was written directly at the script level.  That includes commands executed by `:command`, `:autocmd`, `:global`, `:execute`, `:windo`...  As a result, they can leverage any Vim9 syntax, which includes blocks, but also `:var` declarations, and the ability to omit `s:`/`<SID>`.

The only exceptions are mapping commands.  Unfortunately, a command executed by a mapping is still run in the legacy context (with the exception of `feedkeys()` + `x` flag).  That should probably be documented.

In the future, it would be nice if it could be run in the Vim9 context; this way, we could entirely get rid of `<SID>`, which probably looks weird for a new user.

> Which actually doesn't look too bad, and scoping it is a better solution than let/unlet anyway.

I wonder whether Vim could allow us to drop the bars in this case:
```vim
vim9script
command Cmd {
    echo 'do something'
    echo 'then something else'
}
```
When it finds `{` at the end of a command/autocmd, it could look for a matching `}` and implicitly join all the lines in between with bars.  That would be really nice.  Maybe it's worth asking as a feature request?

> Actually, a case could probably be made to just automatically run this in its own scope in the first place if vim9script is used(?)

That's an interesting idea.  I always find it weird that we can declare a script-local variable from a command or autocmd.

**Comment by brammool** [comment]
It looks like this can be closed.

The idea is that variables in a local scope (inside a function, inside a block, inside a script), where you can see the declaration when writing the code, are declared at some point and remain valid until the scope is left.
Variables that are not scoped to a script, function or block, such as global variables, buffer-local and window-local variables, can be created and deleted at any place.
I think this is logical and makes a lot of sense, a good compromise between allowing variables to be created and deleted at any time (as with legacy script) and declaring variables (as is common with compiled languages).

**Comment by arp242** [comment]
Yeah, I think it makes sense, and the block scoping solves the problem/use case of self-contained commands/autocmds. Cases where people use `unlet s:var` in plugins can be rewritten without too much effort – no need to make things more complex.
