### ISSUE TITLE
prop_find() does not accept property id of -1

### ISSUE THREAD

**Issue by obcat** [vim/vim#8674]
**Describe the bug**

The prop_find() function does not accept a property id of minus one.

**To Reproduce**

1. Run `vim --clean`.

1. Source this script:

    ```vim
    call prop_find({'id': -1})
    ```

    This error is given:

    ```
    E968: Need at least one of 'id' or 'type'
    ```

**Expected behavior**

No error is given, because we passed 'id'.

**Environment**

 - Vim 8.2.3249
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Comment by obcat** [comment]
Thanks for the update!

I can confirm the errorneous error is no longer given:

```vim
call prop_find({'id': -1})
```

```
no error
```

However `prop_find({'id': -1})` finds a text property with id of `-2` instead of `-1`:

```vim
call writefile(['a B C'], '/tmp/letters.txt')
edit /tmp/letters.txt
call prop_type_add('Upper', {})
call prop_add(1, 3, {'type': 'Upper', 'id': -1})
call prop_add(1, 5, {'type': 'Upper', 'id': -2})
normal! 0
echo prop_find({'id': -1})['id']
```

```
-2
```

The patch seems to have introduced this behavior explicitly:

https://github.com/vim/vim/commit/8e3fc135e884a30620fb1c6e84986fae1467acd3#diff-34f3fee1bb72f7657aac808fd9f429f92b8d25e4b893e90f2054fc69d90a9ef6R691-R693

So I believe this is intended, but might be confusing.

**Comment by brammool** [comment]
Naohiro Ono wrote:

> Thanks for the update!
> 
> I can confirm the errorneous error is no longer given:
> 
> ```vim
> call prop_find({'id': -1})
> ```
> 
> ```
> no error
> ```
> 
> However `prop_find({'id': -1})` finds a text property with id of `-2` instead of `-1`:
> 
> ```vim
> call writefile(['a B C'], '/tmp/letters.txt')
> edit /tmp/letters.txt
> call prop_type_add('Upper', {})
> call prop_add(1, 3, {'type': 'Upper', 'id': -1})
> call prop_add(1, 5, {'type': 'Upper', 'id': -2})
> normal! 0
> echo prop_find({'id': -1})['id']
> ```
> 
> ```
> -2
> ```

Yes, this fix only worked for using -1 as a non-existing ID, but it
turns out negative IDs can actually be used.  We need a more generic
solution.


-- 
TALL KNIGHT: We shall say Ni! again to you if you do not appease us.
ARTHUR:      All right!  What do you want?
TALL KNIGHT: We want ... a shrubbery!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by obcat** [comment]
Thank you very much, but... another issue seems to have been introduced:

```vim
call prop_find({'id': 0})
```

```
E968: Need at least one of 'id' or 'type'
```

We can also use 0 for id; it's the default value of id of a textprop which is added by prop_add():

```help
		   id		user defined ID for the property; must be a
				number; when omitted zero is used
```

I'm sorry to report this again and again. I wish I could fix it myself, but I'm not familiar with C... 🥵 I'm studying it now...

**Comment by brammool** [comment]
Naohiro Ono wrote:

> Thank you very much, but... another issue seems to have been introduced:
> 
> ```vim
> call prop_find({'id': 0})
> ```
> 
> ```
> E968: Need at least one of 'id' or 'type'
> ```
> 
> We can also use 0 for id; it's the default value of id of a textprop which is added by prop_add():
> 
> ```help
> 		   id		user defined ID for the property; must be a
> 				number; when omitted zero is used
> ```

I didn't look to closely, assuming a test would catch any problem.
Turns out this wasn't tested.

> I'm sorry to report this again and again. I wish I could fix it
> myself, but I'm not familiar with C... 𐟥µ I'm studying it now...

Don't worry, it's an iterative process.  The number of ways the prop
functions can be used is limitless.


-- 
CONCORDE: Message for you, sir.
   He falls forward revealing the arrow with the note.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
