### ISSUE TITLE
Vim9: cannot use boolean numbers in list/dict of booleans

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#8732]
**Describe the bug**

In Vim9 script, we cannot use a boolean number in a list or dict of booleans.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var b: bool = 0
    EOF
    )

No error is given.  This is expected, because 0 is a boolean number.

Now, run this other shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var l: list<bool> = [0]
    EOF
    )

This error is given:

    E1012: Type mismatch; expected list<bool> but got list<number>

This is not expected.

**Expected behavior**

No error is given, because 0 is a boolean number.

**Environment**

 - Vim version: 8.2 Included patches: 1-3316
 - OS: Ubuntu 20.04.2 LTS
 - Terminal: XTerm(353)

**Additional context**

Here is yet another inconsistency.  This works:
```vim
vim9script
var d: dict<bool>
d->extend({[bufnr('%')]: has('syntax_items')})
```
This does not:
```vim
vim9script
var d: dict<bool> = {[bufnr('%')]: has('syntax_items')}
```
    E1012: Type mismatch; expected dict<bool> but got dict<number>

But – in the end – we try to set `d` with the same value; so it's confusing to get different results.

Anyway, it would be convenient for this to work, otherwise here is what we have to write:
```vim
vim9script
var d: dict<bool> = {[bufnr('%')]: has('syntax_items') ? true : false}
```
The ternary conditional operator looks weird here.  Because it's used to give boolean values after following an expression which in itself already seems to give a boolean value (`has(...)`).

**Comment by brammool** [comment]
This may seem a bit inconsistent, but I don't think we should change this.
You can use one and zero where a bool is expected, a conversion is done to the expected type.
This is done mainly because many existing functions return 0 or 1 with the meaning of false or true.
So you can use that value in a condition without explicitly converting it to a bool.

If you have a list or dict of numbers, this conversion does not take place.  Not even if all the values turn out to be zero or one.
Not even if there is only one value.  That in itself is consistent.

You don't need to use "? true : false" you can put "!!" before the value.

**Comment by lacygoill** [comment]
> This may seem a bit inconsistent, but I don't think we should change this.

OK, but something is still wrong.

This works:
```vim
vim9script
var d: dict<bool>
d->extend({k: 0})
echo d
```
    {'k': 0}

But the exact same code gives an error as soon as it gets compiled:
```vim
vim9script
def Func()
    var d: dict<bool>
    d->extend({k: 0})
    echo d
enddef
defcompile
```
    E1013: Argument 2: type mismatch, expected dict<bool> but got dict<number>

**Comment by lacygoill** [comment]
> OK, but something is still wrong.

It would be more consistent if the code gave an error at the script level, just like when it's compiled.

**Comment by lacygoill** [comment]
The patch 8.2.3222 seems to have created an inconsistency:
```vim
vim9script
var l: list<any>
def Foo(ll: list<dict<any>>)
enddef
Foo(l)
```
    E1013: Argument 1: type mismatch, expected list<dict<any>> but got list<any>
```vim
vim9script
def Foo()
    var l: list<any>
    Bar(l)
enddef
def Bar(ll: list<dict<any>>)
enddef
Foo()
```
    no error

Vim complains in the first snippet because `Foo()` expects a list whose members have the type `dict<any>`.  But when called, it receives a list whose members have the type `any`.  One could argue that it's not an error, because there is no incompatibility between the 2 types: `dict<any>` is a special case of `any`.  But OK, one could argue that the types must match exactly.

However, if the 2 types must match exactly, then why doesn't Vim complain in the second snippet?  Again, `Bar()` expects a list whose members have the type `dict<any>`; but we pass it a list whose members have the type `any`.  Why no error this time?

**Comment by brammool** [comment]
> The patch 8.2.3222 seems to have created an inconsistency:
> ```vim
> vim9script
> var l: list<any>
> def Foo(ll: list<dict<any>>)
> enddef
> Foo(l)
> ```
>     E1013: Argument 1: type mismatch, expected list<dict<any>> but got list<any>

This is not really new, except that now the right type is used.  It was
already failing when you remove list<>:

	var l: any
	def Foo(ll: dict<any>)
	enddef
	disass Foo
	Foo(l)

E1013: Argument 1: type mismatch, expected dict<any> but got number

(it says number because that is the default value).

> ```vim
> vim9script
> def Foo()
>     var l: list<any>
>     Bar(l)
> enddef
> def Bar(ll: list<dict<any>>)
> enddef
> Foo()
> ```
>     no error
> 
> Vim complains in the first snippet because `Foo()` expects a list
> whose members have the type `dict<any>`.  But when called, it receives
> a list whose members have the type `any`.  One could argue that it's
> not an error, because there is no incompatibility between the 2 types:
> `dict<any>` is a special case of `any`.  But OK, one could argue that
> the types must match exactly.
> 
> However, if the 2 types must match exactly, then why doesn't Vim
> complain in the second snippet?  Again, `Bar()` expects a list whose
> members have the type `dict<any>`; but we pass it a list whose members
> have the type `any`.  Why no error this time?

If we give the list values instead of leaving it empty, it does give an
error:

	def Foo()
	  var l: list<any>
	  l = [1, 'a', true]
	  Bar(l)
	enddef

	def Bar(ll: list<dict<any>>)
	enddef

	Foo()

E1013: Argument 1: type mismatch, expected list<dict<any>> but got list<any>

The problem is that when the list is not initialized and the member type
is "any" then the type is not set at runtime.  I can fix that.

-- 
LAUNCELOT: I am, sir. I am a Knight of King Arthur.
FATHER:    'Mm ... very nice castle, Camelot ... very good pig country....
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
