### ISSUE TITLE
Vertical helping document

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim#8744]
**Describe the bug**
I searched in [https://stackoverflow.com/questions/630884/opening-vim-help-in-a-vertical-split-window](url) the way how to open `help` document in vertical right 
and I found this one: `autocmd FileType help wincmd L `

It's actually good when open 1 time but at the second it didn't work( "in the same word")

I expected it will be good in any word in any time I press `K`

![bandicam 2021-08-10 15-13-24-365](https://user-images.githubusercontent.com/75968004/128832813-b34a39dd-04b9-44ef-9ed8-3b1852b0f213.gif)

Here is my vim version:
![image](https://user-images.githubusercontent.com/75968004/128832954-c6349b92-1951-408c-98b2-a8d825a19581.png)

Thanks for helping

**Comment by lacygoill** [comment]
> and I found this one: autocmd FileType help wincmd L

Try this instead:

    autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by Hungpro3112** [comment]
> > and I found this one: autocmd FileType help wincmd L
> 
> Try this instead:
> 
> ```
> autocmd BufWinEnter * if &buftype == 'help' | wincmd L | endif
> ```
> 
> For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

Can you explain why the code I posted above didn't work?

**Comment by lacygoill** [comment]
> Can you explain why the code I posted above didn't work?

Because `FileType` is not fired the second time you open the window.

**Comment by Hungpro3112** [comment]
> > Can you explain why the code I posted above didn't work?
> 
> Because `FileType` is not fired the second time you open the window.

 Is it in the doc or anywhere?

**Comment by lacygoill** [comment]
The `FileType` event is fired when the `'filetype'` option is set.
The `'filetype'` option is set by an autocmd which listens to `BufNewFile` and `BufRead`:

    " Vim help file
    au BufNewFile,BufRead $VIMRUNTIME/doc/*.txt	setf help

https://github.com/vim/vim/blob/b6f55bb5b4d7d03cdf47d552db20d06e41354d5f/runtime/filetype.vim#L53-L54

`BufNewFile` is fired when you edit a file that doesn't exist.  Since the help file you're reading when you execute `:help` does exist, it's irrelevant here.

`BufRead` is fired when you start editing a new buffer; which does happen when you execute a `:help` command.  But Vim does not need to re-create the buffer every single time you open the help window for the exact same help file.

So, `BufRead` is not fired the second time, because there's no need to (the buffer already exists).  Thus, the previously mentioned autocmd listening to `BufRead` is not fired; `:setf help` is not executed; `'filetype'` is not set; `FileType` is not fired again.

---

   > For more questions, visit the google mailing list, the irc channel, or vi.stackexchange.com.
