### ISSUE TITLE
Vim9 changes of v8.2.1466 affect to legacy Vim script

### ISSUE THREAD

**Issue by rbtnn** [vim/vim#8749]
**Describe the bug**
Vim9 changes of v8.2.1466 affect to legacy Vim script.

**To Reproduce**
  v8.2.2000 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1500 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1470 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1468 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1467 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1466 `echo ['a'][-2:]`  -> `['a']`
  v8.2.1465 `echo ['a'][-2:]`  -> `[]`
  v8.2.1455 `echo ['a'][-2:]`  -> `[]`
  v8.2.1440 `echo ['a'][-2:]`  -> `[]`
  v8.2.1375 `echo ['a'][-2:]`  -> `[]`
  v8.2.1250 `echo ['a'][-2:]`  -> `[]`
  v8.2.1000 `echo ['a'][-2:]`  -> `[]`

**Expected behavior**
In legacy Vim script, `echo ['a'][-2:]`  must be `[]` .
In Vim9 script, `echo ['a'][-2:]`  must be `['a']` .

**Additional context**
It caused by [this chage](https://github.com/vim/vim/commit/cc673e746ab98566556ff964d7a76f2fb46d7f84#diff-138fee0cde6911f5e743c2e464c33b1e49c2bdbfed55efdd363e45736b8c65d4L917).

Probably I think the following code will fix it:
```
	if (vim9script)
	    n1 = n1 < 0 ? 0 : len;
	else
	    n1 = len;
```

@brammool  What do you think about this?

**Comment by brammool** [comment]
Naruhiko Nishino wrote:

> **Describe the bug**
> Vim9 changes of v8.2.1466 affect to legacy Vim script.
> 
> **To Reproduce**
>   v8.2.2000 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1500 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1470 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1468 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1467 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1466 `echo ['a'][-2:]`  -> `['a']`
>   v8.2.1465 `echo ['a'][-2:]`  -> `[]`
>   v8.2.1455 `echo ['a'][-2:]`  -> `[]`
>   v8.2.1440 `echo ['a'][-2:]`  -> `[]`
>   v8.2.1375 `echo ['a'][-2:]`  -> `[]`
>   v8.2.1250 `echo ['a'][-2:]`  -> `[]`
>   v8.2.1000 `echo ['a'][-2:]`  -> `[]`
> 
> **Expected behavior**
> In legacy Vim script, `echo ['a'][-2:]`  must be `[]` .
> In Vim9 script, `echo ['a'][-2:]`  must be `['a']` .
> 
> **Additional context**
> It caused by [this chage](https://github.com/vim/vim/commit/cc673e746ab98566556ff964d7a76f2fb46d7f84#diff-138fee0cde6911f5e743c2e464c33b1e49c2bdbfed55efdd363e45736b8c65d4L917).
> 
> Probably I think the following code will fix it:
> ```
> 	if (vim9script)
> 	    n1 = n1 < 0 ? 0 : len;
> 	else
> 	    n1 = len;
> ```
> 
> @brammool  What do you think about this?

When I make your proposed change no test fails.  I guess this was not an
intentional change and only meant for Vim9 script.  Let's do it this
way and make it backwards compatible, even though the Vim9 behavior is
more what users expect.

-- 
Two cows are standing together in a field.  One asks the other:
"So what do you think about this Mad Cow Disease?"
The other replies: "That doesn't concern me. I'm a helicopter."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rbtnn** [comment]
>When I make your proposed change no test fails.  I guess this was not an
>intentional change and only meant for Vim9 script.  Let's do it this
>way and make it backwards compatible, even though the Vim9 behavior is
>more what users expect.
@brammool  I got it. Thank you for fixing it.
