### ISSUE TITLE
Vim9: E1017 when using "function dict.func()"

### ISSUE THREAD

**Issue by obcat** [vim/vim#8758]
**Describe the bug**

In Vim9 script, we cannot use the shortcut `function dict.func()` to define a dictionary function and assign it to a dictionary at the same time. It gives `E1017`.

**To Reproduce**

1. Run `vim -Nu NONE`.

1. `:source` this script:

    ```vim
    vim9script
    var mydict = {key: 'val'}
    function mydict.func()
      echo self.key
    endfunction
    mydict.func()
    ```

    `E1017` is given:

    ```
    line    3:
    E1017: Variable already declared: mydict.func()
    ```

**Expected behavior**

No error is given; `val` is echo'ed.

**Environment**

 - Vim 8.2.3344
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Additional context**

This does work as expected:

```vim
vim9script
function Func() dict
  echo self.key
endfunction
var mydict = {key: 'val', func: Func}
mydict.func()
```

```
val
```

**Comment by brammool** [comment]
This is intentional.  Dictionary functions were a hacky way of adding objects with methods.  In Vim9 script the plan is to eventually add classes.  You can do it indirectly, by defining the function first and then assigning a reference to a dict member.  With Vim9 classes (eventually) all objects will have the member function, not just the individual instance.

**Comment by obcat** [comment]
Oh, I didn't know that. Thank you for the clarification.
