### ISSUE TITLE
:vimgrep silently fails when filename pattern does not match any file

### ISSUE THREAD

**Issue by gdupras** [vim/vim#8762]
**Describe the bug**
`:vimgrep` silently fails when the filename pattern does not match any file. No error message is displayed. If the quickfix window contained anything, it is not overwritten. This bug affects Vim 8.2.3346 on Windows 10 but does not affect Vim 8.2.3354 on Kubuntu 20.04.

**To Reproduce**
1. `echo foo > test.txt`
2. `vim --clean`
3. `:vimgrep foo *.txt`
4. `:cw` (quickfix window shows "foo" in test.txt)
5. `:vimgrep foo *.bar` (I'm assuming you don't have any file ending with ".bar" in your working directory.)
6. Nothing happens. No error message. The content of the quickfix window is the same as in step 4.

**Expected behavior**
The following error message should be displayed (like it is on Linux):
```
"*.bar" [New]
Cannot open file "*.bar"
E480: No match: foo
Press ENTER or type command to continue
```
The quickfix window should be empty.

**Environment:**
 - Vim 8.2.3346
 - Windows 10
 - Vim and gVim started from cmd.exe.

**Comment by chrisbra** [comment]
there is a difference between unix and windows here. On Unix, it fails as expected, because the `*.bar` is handled normally. So even so it does not match anything, Vim will treat it as a valid filename and try to open it, which fails and then you are presented with the error message.

On Windows, Vim will try to expand the `*.bar` pattern. This fails, but since the `*` is not valid in file names, Vim will fail silently early (does not add the pattern `*.bar` to the file list in `addfile()`, because of the `FNAME_ILLEGAL`, leave the grow array un-initialized, which will then cause to return `FAIL` because of this condition: 

https://github.com/vim/vim/blob/0c359af5c0fd106d3f57cc0bb7cef1c89b5e1e10/src/filepath.c#L4017

But, since this is only about a missing error message, how about the following (minimal) patch then:

```patch
diff --git a/src/quickfix.c b/src/quickfix.c
index 4405d4b64..d7c0a88a6 100644
--- a/src/quickfix.c
+++ b/src/quickfix.c
@@ -6122,9 +6122,8 @@ vgr_process_args(
     }

     // Parse the list of arguments, wildcards have already been expanded.
-    if (get_arglist_exp(p, &args->fcount, &args->fnames, TRUE) == FAIL)
-       return FAIL;
-    if (args->fcount == 0)
+    if ((get_arglist_exp(p, &args->fcount, &args->fnames, TRUE) == FAIL) ||
+       args->fcount == 0)
     {
        emsg(_(e_nomatch));
        return FAIL;
```

This now causes a `E479: No match` on Windows, and a `E480: No match: foo` on Unix. However, you will still see the difference in quickfix lists, since on Windows this fails earlier, the current quickfix list is not discarded. I think this okay however.

**Comment by gdupras** [comment]
Thank you!
