### ISSUE TITLE
Unconditional 'pkgadd matchit' breaks tiny/small builds of vim

### ISSUE THREAD

**Issue by fjaell** [vim/vim#878]
Patch 7.4.1649 adds unconditionally

pkgadd matchit

to the example vimrc. This breaks builds with the tiny and small feature set if the default vimrc is used.

?> vi
 Error detected while processing /usr/share/vim/pack/dist/opt/matchit/plugin/matchit.vim:
line   44:
E319: Sorry, the command is not available in this version: let loaded_matchit = 1
line   45
...
following lots of similar error lines

**Comment by vim-ml** [comment]
The error on :let is due to that command not being available in builds
with -eval, i.e. in Tiny and Small builds.

One possible solution is to guard it with

if 1            " equivalent with :if has('eval')
    ...
    ...
    ...
endif

because builds without +eval treat if..endif (when at start of line)
as a nestable comment. See ":help no-eval-feature" for details.

+packages, like +eval, is included in Normal builds and higher, so the
above should be enough, unless you want to guard against the
possibility that someone might compile a build with +eval and
-packages by fine-tuning the feature.h. For this, any "packages"
command should be guarded on its own by

if has("packages")
    ...
endif

inside the "if 1" (or "if has('eval')") block.

Best regards,
Tony.

**Comment by brammool** [comment]
I'll add an "if" to avoidthis.

**Comment by brammool** [comment]
fjaell wrote:

> Patch 7.4.1649 adds unconditionally
> 
> pkgadd matchit
> 
> to the example vimrc. This breaks builds with the tiny and small feature set if the default vimrc is used.
> 
> ?> vi
>  Error detected while processing /usr/share/vim/pack/dist/opt/matchit/plugin/matchit.vim:
> line   44:
> E319: Sorry, the command is not available in this version: let loaded_matchit = 1
> line   45
> ...
> following lots of similar error lines

Well, perhaps not use a tiny version then.

But we can add an "if" to avoid the error:

```
if has('syntax') && has('eval')
  packadd matchit
endif
```

## 

"Computers in the future may weigh no more than 1.5 tons."
                                   Popular Mechanics, 1949

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
