### ISSUE TITLE
[Support] How to open a terminal and put the cursor on top

### ISSUE THREAD

**Issue by N-R-K** [vim/vim#8822]
I would like to open a terminal window and put the cursor on top. I've tried this
```sh
vim "+exe 'term ++curwin git --no-pager log --oneline --color=always' | normal gg"
```
but it doesn't quite work. The cursor remains at the bottom. I've also tried using the `TerminalOpen` autocmd as well but no dice.

**Comment by lacygoill** [comment]
Try this:
```vim
vim9script
def CursorOnTop(..._)
    term_wait(buf)
    normal! gg
enddef
var buf: number = term_start('git --no-pager log --oneline --color=always', {curwin: true, exit_cb: CursorOnTop})
```
---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by bfrg** [comment]
There's a trick to achieve this without using any `normal! gg`:
```vim
call term_start('git --no-pager log --oneline --color=always', {
    \ 'hidden': true,
    \ 'term_cols': 1000,
    \ 'term_finish': 'open',
    \ 'term_opencmd': 'buffer %d'
})
```

Setting `term_cols` to a large number will prevent Vim from wrapping the git output, meaning the output won't be wrapped at the current window width. This can be very annoying when you decide to make the window wider, since terminal buffers are not rewrapped (see #2865 and #5769). However, the `term_cols` option only works when `hidden` is set to `true`. Note that once the terminal buffer is open you can still set `wrap` like in any other buffer.

When `hidden` is set to `true`, Vim won't open the terminal buffer unless you set the `term_finish` option. Now here's the trick: when you specify `term_opencmd`, Vim won't jump to the bottom of the buffer. This is what you wanted. `term_opencmd` can be any command that opens a buffer. You could also use `vertical sbuffer %d` to open the `git log` output in a new vertical split.

See `:help term_start()` for all the details.
