### ISSUE TITLE
Nginx syntax file request

### ISSUE THREAD

**Issue by quiloos39** [vim/vim#8824]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
Currently I am using Apache syntax to display Nginx configuration and I think it's unfair for Nginx to not have seperate syntax file. I am asking for addition of Nginx syntax file.

**Describe alternatives you've considered**
Installing Nginx syntax file separately.

**Comment by chrisbra** [comment]
There seems to be a plugin available at https://github.com/chr4/nginx.vim 
Please test it out, and if it works fine, you may request and ask the maintainers to allow distribution of those runtime files with vim.

They should then send the files to Bram for distribution with Vim.

**Comment by chr4** [comment]
I've created `nginx.vim` from [the nginx sources](https://github.com/nginx/nginx/blob/master/contrib/vim/syntax/nginx.vim) and modified a little for some extra features. 

The file was modified upstream quite a bit since the release. 

Nginx seems to have a "2-clause BSD license", and I've released my changes under the GPLv3. I'm not sure how they are compatible with the Vim license, but if it can be of any help I'm willing to relicense.

**Comment by brammool** [comment]
GPLv3 has some specific conditions.  It's easier if you can use the Vim license.  It should not conflict with the other license.  In practice it hardly matters.  Using the Vim license just makes it easier for anybody distributing the files.

**Comment by chr4** [comment]
Ok. Just let me know if you consider integrating any of this into vim, I'll gladly change the license then.

**Comment by chrisbra** [comment]
If you consider changing the license for Vim, please do and send the files to Bram for inclusion. Or create a PR here. Thanks.

**Comment by chr4** [comment]
I've relicensed github.com/chr4/nginx.vim/ under the same license as Vim itself, and added a pull request: https://github.com/vim/vim/pull/8922
