### ISSUE TITLE
Vim9: unexpected type mismatch error when using variable arguments

### ISSUE THREAD

**Issue by mark2185** [vim/vim#8926]
**Describe the bug**
In vim9 script, using variable arguments doesn't work when sending an actual list, but using it through a command works okay.

**To Reproduce**
Run this shell command:
```
vim -Nu NONE -S <(cat <<'EOF'
    vim9script
    def Func(...args: list< string >): void
    enddef
    Func(['input'])
EOF
)
```

`E1013` is given:
```
Argument 1: type mismatch, expected string but got list<string>
```

**Expected behavior**
No error is given.

**Environment (please complete the following information):**
 - Vim version `8.2.3452`
 - OS: centos8
 - Terminal: Terminator

**Additional context**
Using it through a command, works:
```
command -nargs=* Command call Func(<f-args>)
```
And then
```
Command test test 
```
produces no output (which is good!)

**Comment by bfrg** [comment]
Defining a function with signature `Func(...args: list<string>): void` means the function accepts a variable number of string arguments, like `Func('one', 'two', 'three')`, but not `Func(['one', 'two', 'three'])`. The arguments itself are accessed through the list `args` inside the function, like `args[0]` etc.

If you want to pass a list of strings, you need to use `def Func(arg: list<string>)`, i.e. without the triple dots, but this won't work with `<f-args>`.

**Comment by mark2185** [comment]
Ah, that makes sense.

For some reason I thought it took a `list<string>` which was optional (probably because of `...`), but had no default value in case it was passed `v:none`.

**Comment by mark2185** [comment]
But... shouldn't this work, then?

```
vim -Nu NONE -S <(cat <<'EOF'
    vim9script
    def Func(?arg: number): void
    enddef
EOF
)
```

**Comment by bfrg** [comment]
No, `func(?{type})` is a type declaration, like:
```vim
var MyFun: func(?number) = Func
```
This means that `MyFun` can be assigned to a function with signature `Func(arg: number)` or `Func()`, i.e. the function argument is optional. Assigning `MyFunc` to a function `Func(arg: string)` would give you an error.

Example:
```vim
def Func1(x: number = 10)
enddef

def Func2()
enddef

def Func3(str: string)
enddef

var MyFun: func(?number) = Func1  " okay

MyFun = Func2  " okay
MyFun = Func3  " E1012: Type mismatch; expected func(?number) but got func(string)

```

**Comment by lacygoill** [comment]
I still think it would make sense to drop the `list` for variable arguments:

    ✘
    def Func(...varargs: list<string>)
                         ^---^      ^

    ✔
    def Func(...varargs: string)

I've made the same kind of mistakes as the OP in the past.  That is, I've frequently thought that the type was for the members of the list, and not for the list itself.  For me, this suggests that writing the type of the members is more natural, because `list` is already implied by the `...` prefix in front of the name of the variable arguments.

   > Variable arguments are defined as the last argument, with a name and have a
   > list type, similar to TypeScript.  For example, a list of numbers: >
   >         def MyFunc(...itemlist: list<number>)
   >            for item in itemlist
   >              ...


Finally, the help at [`:help vim9-variable-arguments`](https://vimhelp.org/vim9.txt.html#vim9-variable-arguments) seems to suggest that the syntax is inspired from TypeScript:

   > Variable arguments are defined as the last argument, with a name and have a
   > list type, **similar to TypeScript**.  For example, a list of numbers: >

But in TypeScript, it seems that [they write the type of the members](https://www.typescriptlang.org/docs/handbook/functions.html#rest-parameters), not the type of the list:

    function buildName(firstName: string, ...restOfName: string[]) {
      return firstName + " " + restOfName.join(" ");
    }

    // employeeName will be "Joseph Samuel Lucas MacKinzie"
    let employeeName = buildName("Joseph", "Samuel", "Lucas", "MacKinzie");

Notice that on the first line where the header of the `buildName()` function is written, they specify the type of `...restOfName` as being `string[]`.  There is no `list` in there.  Maybe that's because they came to the same conclusion; i.e. it's more natural to only write the type of the members, rather than the type of the whole list.

**Comment by lacygoill** [comment]
> Notice that on the first line where the header of the buildName() function is written, they specify the type of ...restOfName as being string[]. There is no list in there.

Actually, the trailing brackets `[]` might be their own way of expressing `list<>`.  So, maybe my suggestion isn't so good after all.  I don't know.
