### ISSUE TITLE
A separate function to return the value of `restart_edit`

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#8967]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

Currently `mode(1)` only includes `restart_edit` if in Normal mode (`niI`, `niR`, `niV`), but the value of `restart_edit` may also be useful when not in Normal mode (e.g to determine which mode `<Esc>` goes to in Visual mode, or to simulate `showmode` messages like `-- (insert) VISUAL --` in statusline).

Appending `restart_edit` to every mode where `restart_edit` can be non-empty in the return value of `mode(1)` may make the return value of `mode(1)` harder to parse, make the addition of new modes in the future more difficult, and make the documentation of `mode()` very long.

**Describe the solution you'd like**

Instead, there can be a separate function to return the value of `restart_edit`. IDK how it should be named though.

**Comment by zeertzjq** [comment]
> Maybe only return `restart_edit` when it is one of `I`, `R`, `V`, otherwise return a empty string.

Oh, it seems `restart_edit` can have some other values if `startinsert` is called from a script. Maybe returning `restart_edit` as-is if it is not `NUL` is better then?

**Comment by zeertzjq** [comment]
> > Maybe only return `restart_edit` when it is one of `I`, `R`, `V`, otherwise return a empty string.
> 
> Oh, it seems `restart_edit` can have some other values if `startinsert` is called from a script. Maybe returning `restart_edit` as-is if it is not `NUL` is better then?

Oh, I guess it will be hard to write documentation for values other than `I`, `R`, `V`.

**Comment by brammool** [comment]
We have mode() to get the main mode that Vim is in, and we can't change it much without breaking existing plugins.
We also have state(), which is used mainly to postpone work that isn't safe to do right now (e.g. in a channel callback).
Just returning the value of restart_edit is a technical look at it.  We might find more state that matters for a plugin.
To be more flexible for the future, and to avoid adding even more functions later, we could at a function that returns a dictionary with various state values.  We could for example have a flag whether we are inside a timer callback.
Not sure what to call it, since mode() and state() are already in use.

**Comment by zeertzjq** [comment]
This is not very useful, so I'll close this.
