### ISSUE TITLE
vim tab title is shortened to non recognizable names

### ISSUE THREAD

**Issue by TimDaub** [vim/vim#8998]
### Steps to reproduce

1. Limit the size of your terminal width
1. Go in vim and open a bunch of files in a directory structure
2. Notice how at one point, vim starts shortening tab titles to nonsensical short names

<img width="818" alt="Screen Shot 2021-10-14 at 13 28 51" src="https://user-images.githubusercontent.com/2758453/137309111-b8724ad3-b09c-426f-b870-12bf84218849.png">
<img width="699" alt="Screen Shot 2021-10-14 at 13 28 58" src="https://user-images.githubusercontent.com/2758453/137309119-3eb4598d-0964-4e70-a02f-c48462b55cf1.png">

Notice how "send_test.mjs" morphed to "nd_test.mjs".

### Expected behaviour

Expected behavior would be that this doesn't happen and instead tabs "scroll". Such that some tabs aren't shown, similar to how a sliding window works.

Alternatively, vim could shorten to more sensical short names. But since it's semantically not aware of which word carries the most meaning in a name, I think that approach might be naive.

### Operating system

mac os x

### Version of Vim

version 8.1.2292

**Comment by lacygoill** [comment]
> Not sure what you expect with tabs to scroll. I am not sure how this should happen in the console.

Not sure either, but I think they don't want *all* the tab pages to have a title; only the currently focused one and maybe the immediate neighbours on the left and right.  Having to display only 3 titles instead of 5 like in the screenshots would leave more space for the filenames, reducing the need to shorten the latter.

At least, that's my understanding based on this [answer](https://stackoverflow.com/a/8269948).

In any case, that's not a bug, but a feature request which can be satisfied by setting the ['tabline'](https://vimhelp.org/options.txt.html#%27tabline%27) option.  FWIW, here is [how I set mine](https://github.com/lacygoill/vim-statusline/blob/3492fa072c1f9f15bff32a5e9556ad140348e545/plugin/statusline.vim#L448-L664).  Which can be simplified/extracted into this:
```vim
vim9script
&showtabline = 2
&tabline = '%!g:Tabline()'

const MAX_TABLABELS: number = 1
const TABLABEL_MAXSIZE: number = 20

def g:Tabline(): string
    var s: string
    var curtab: number
    var lasttab: number
    [curtab, lasttab] = [tabpagenr(), tabpagenr('$')]
    var sdfe: number = min([curtab - 1, lasttab - curtab])
    var max_dist: number = MAX_TABLABELS + (sdfe >= MAX_TABLABELS ? 0 : MAX_TABLABELS - sdfe)
    for i: number in range(1, lasttab)
        s ..= i == curtab ? '%#TabLineSel#' : '%#TabLine#'
        s ..= '%' .. i .. 'T'
        var label: string
        if abs(curtab - i) > max_dist
            label = string(i)
        else
            label = ' %{g:Tabpagelabel(' .. i .. ', ' .. curtab .. ')} '
        endif
        s ..= label .. '│'
    endfor
    s ..= '%#TabLineFill#%T'
    return s
enddef

def g:Tabpagelabel(n: number, curtab: number): string
    var winnr: number = tabpagewinnr(n)
    var bufnr: number = win_getid(winnr, n)->winbufnr()
    var bufname: string = bufname(bufnr)
    if bufname != ''
        bufname = bufname->fnamemodify(':p')
    endif
    var label: string
    if n == curtab && &buftype != ''
        label = ''
    elseif bufname != '' && (n == curtab || getbufvar(bufnr, 'root_dir', '') != '')
        var cwd: string = getcwd(winnr, n)
            ->substitute('^\V' .. escape($HOME, '\') .. '/', '', '')
            ->pathshorten()
        if cwd !~ '/'
            cwd ..= '/'
        endif
        label = cwd
    else
        label = bufname->fnamemodify(':t')
    endif
    label = label[: TABLABEL_MAXSIZE - 1]
    if n != curtab
        return label
    endif
    var len: number = strcharlen(label)
    var cnt: number = (TABLABEL_MAXSIZE - len) / 2
    return repeat(' ', cnt) .. label .. repeat(' ', cnt + len % 2)
enddef
```
It doesn't print the filenames in the tabline.  They're already written in my statusline; I don't need to see them twice.  Instead, it prints the current working directory, which is automatically set to the root directory of the project associated with the displayed file.

**Comment by lacygoill** [comment]
BTW, this other feature request might be relevant: https://github.com/vim/vim/issues/8911

**Comment by TimDaub** [comment]
> At least, that's my understanding based on this [answer](https://stackoverflow.com/a/8269948).

Wow, @lacygoill that's exactly wanted I want! I'll give your script a go soon and report back here to close the issue. Thanks!
