### ISSUE TITLE
Integer overflow in getchar.c

### ISSUE THREAD

**Issue by yiyuaner** [vim/vim#9043]
In the file `getchar.c`, the function `ins_typebuf` relies on the following code to check for integer overflow ([link](https://github.com/vim/vim/blob/e30d10253fa634c4f60daa798d029245f4eed393/src/getchar.c#L1011-#L1017)):

```
newlen = typebuf.tb_len + addlen + newoff + 4 * (MAXMAPLEN + 4);
if (newlen < 0)		    // string is getting too long
{
    emsg(_(e_toocompl));    // also calls flush_buffers
    setcursor();
    return FAIL;
}
```
This assumes wrap-around behavior for signed integer overflow. However, since signed integer overflow is undefined behavior in C, I think the checking code needs to be modified. It should check for integer overflow before it happens.

**Comment by drmikehenry** [comment]
> Checking that the result is negative is undefined behavior, as signed overflows in C or C++ are undefined behavior (unlike unsigned overflow that wrap reliably).

This is the key point.  Any calculation that causes overflow, even temporarily, causes undefined behavior.  It's impossible to attempt to correct for this overflow case after-the-fact.

Range calculations like the one below are subject to overflow:

```c
  if (untrusted_value + trusted_value > MAX_VALUE) {
      // untrusted_value was too large.
  }
```

Undefined behavior occurs if `untrusted_value + trusted_value` overflows.  The recommended approach for this pattern is to make comparisons only against `untrusted_value` directly (i.e., without doing any math on it) until the range has been verified.  This is done by subtracting `trusted_value` from both sides:

```c
  if (untrusted_value > MAX_VALUE - trusted_value) {
      // untrusted_value was too large.
  }
```

This works because we know `trusted_value` does not exceed `MAX_VALUE` (either by design, or by previous range checking).

Here's the existing calculation from `getchar.c` which can overflow:

```c
  addlen = (int)STRLEN(str);
  // ...
  newoff = MAXMAPLEN + 4;
  newlen = typebuf.tb_len + addlen + newoff + 4 * (MAXMAPLEN + 4);
  // ...
  typebuf.tb_buflen = newlen;
```

Here, `addlen` is the "untrusted" value we need to validate.  `typebuf.tb_len` is trusted to not exceed `MAX_INT`; additional invariants aren't obvious.

Given that `newoff = MAXMAPLEN + 4`, the subexpression `newoff + 4 * (MAXMAPLEN + 4)` reduces to `5 * (MAXMAPLEN + 4)`; this is a compile-time constant value that fits very comfortably in an `int`, given that `MAXMAPLEN == 50` (even for 16-bit-`int` machines).  There is therefore no possibility of overflow during the calculation of this compile-time constant expression.  A static assertion validating that `MAXMAPLEN` is "small" could be added to cover the small likelihood that this value might eventually grow into the thousands.

Let `OVERHEAD` be this compile-time constant value:

```c
  int OVERHEAD = 5 * (MAXMAPLEN + 4);
  // Or, equivalently:
  // int OVERHEAD = newoff + 4 * (MAXMAPLEN + 4);
```

The range check (without overflow consideration) is then:

```c
  if (typebuf.tb_len + addlen + OVERHEAD > MAXINT) {
      // Overflow.
  }
```

Subtracting `OVERHEAD` from both sides:

```c
  if (typebuf.tb_len + addlen > MAXINT - OVERHEAD) {
      // Overflow.
  }
```

If it's not guaranteed by Vim-wide invariants, a first check should be done to ensure that `typebuf.tb_len + OVERHEAD` does not overflow:

```c
  if (typebuf.tb_len > MAXINT - OVERHEAD) {
      // typebuf.tb_len is already too large all by itself
  }
```

This check might well be unnecessary if `typebuf.tb_len` is never permitted to get that close to the limit.  (I didn't check whether other places in Vim are adjusting this value; if this is the only place, the above check would not be necessary.)

After the above check, we may subtract `typebuf.tb_len` from both sides to isolate the untrusted `addlen` value:

```c
  if (addlen > MAXINT - OVERHEAD - typebuf.tb_len) {
      // addlen is too large.
  }
```

These two checks may be combined to avoid duplicating the body of the `if` statements:

```c
  if (typebuf.tb_len > MAXINT - OVERHEAD ||
      addlen > MAXINT - OVERHEAD - typebuf.tb_len) {
      // Overflow.
  }
```

It could be useful to have a general-purpose `safe_add()` function for two `int` values, though as implemented in pull request #9067, there are some drawbacks:

- A general-purpose `safe_add()` should accommodate any range of input values, but because of the sentinel value `-1` reserved for signaling an error, it's not possible to return this otherwise-valid sum.  A signature such as the following would allow the full range of valid sums to be used:

```c
    // Return 0 on success, -1 on overflow.
    int safe_add(int a, int b, int *sum)
```

- The macros `INT_MAX` and `INT_MIN` are already defined in Standard C via the header `limits.h`, which is already included by `vim.h`.  It's not clear why they are being redefined in the pull request.  In addition, this definition of `INT_MIN` is incorrect for subtle reasons:
  
```c
    #define INT_MIN -2147483648
```

  On a two's-complement machine, the negative of `INT_MIN` can't be represented as an `int` value (it exceeds `INT_MAX`).  In C, there are no negative integer literals; instead, values such as `-2147483648` comprise two tokens (unary negation, `-`, and integer literal, `2147483648`).  On a modern machine with 32-bit `int` values, the decimal literal value `2147483648` is too large for `int`, so it promotes to be of type `long int`; afterward, `-` is applied to create a negative `long int` constant (where an `int` constant is desired).

  For this reason, these values are typically defined by `limits.h` as follows:

```c
    #define INT_MAX       2147483647
    #define INT_MIN       (-INT_MAX - 1)
```

**Comment by drmikehenry** [comment]
Depending on what's known about the `str` argument for `ins_typebuf()`, there is still a possibility of overflow in the logic of 8.2.3595 (<https://github.com/vim/vim/commit/0d5a12ea041c112b06b1aafde38846ae4cff8f4c>).

The length of `str` is stored in `int addlen`; if that length can be close to `MAX_INT`, the calculation of `extra` below could overflow:

```c
extra = addlen + newoff + 4 * (MAXMAPLEN + 4);
```

Is there code outside this function that ensures `str` is enough shorter than `MAX_INT` to prevent overflow in this calculation?

In the worst case, the length could possibly even be larger than `MAX_INT` because `STRLEN()` (a wrapper around `strlen()`) returns `size_t`; on 64-bit boxes, `size_t` is 64-bit.  I've been assuming strings are length-limited to a maximum of `MAX_INT` characters throughout Vim, based on the many occurrences of `(int)STRLEN()`; if that's not a good assumption, additional checks would be indicated to prevent strings from growing beyond `MAX_INT` characters.

When this function is called, if there is no guarantee that `addlen <= MAX_INT - (newoff + 4 * (MAXMAPLEN + 4))`, this bound must be checked to prevent overflow before computing the value of `extra`.

**Comment by brammool** [comment]
> Depending on what's known about the `str` argument for
> `ins_typebuf()`, there is still a possibility of overflow in the logic
> of 8.2.3595
> (<https://github.com/vim/vim/commit/0d5a12ea041c112b06b1aafde38846ae4cff8f4c>).
> 
> The length of `str` is stored in `int addlen`; if that length can be
> close to `MAX_INT`, the calculation of `extra` below could overflow:
> 
> ```c
> extra = addlen + newoff + 4 * (MAXMAPLEN + 4);
> ```
> 
> Is there code outside this function that ensures `str` is enough
> shorter than `MAX_INT` to prevent overflow in this calculation?
> 
> In the worst case, the length could possibly even be larger than
> `MAX_INT` because `STRLEN()` (a wrapper around `strlen()`) returns
> `size_t`; on 64-bit boxes, `size_t` is 64-bit.  I've been assuming
> strings are length-limited to a maximum of `MAX_INT` characters
> throughout Vim, based on the many occurrences of `(int)STRLEN()`; if
> that's not a good assumption, additional checks would be indicated to
> prevent strings from growing beyond `MAX_INT` characters.
> 
> When this function is called, if there is no guarantee that `addlen <=
> MAX_INT - (newoff + 4 * (MAXMAPLEN + 4))`, this bound must be checked
> to prevent overflow before computing the value of `extra`.

What we protect against here is a recursive mapping, adding a string
(which is unlikely to be very long) is added over and over again.
Eventually the result gets too long.  We can assume the string is not
extremely long itself.

It is close to impossible to have bound checks everywhere.  The
intention is to check where it might actually happen.

-- 
The question is:  What do you do with your life?
The wrong answer is: Become the richest guy in the graveyard.
				(billionaire and Oracle founder Larry Ellison)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by drmikehenry** [comment]
Thanks; this seems reasonable given your assumptions about the string.
