### ISSUE TITLE
Unexpected behavior of -c " ... | tabfirst"

### ISSUE THREAD

**Issue by greenfoo** [vim/vim#9076]
### Steps to reproduce

1. Run this: ```vim -f -c "echo | -tabnew | vertical split | 2b | wincmd l | 3b | tabnext | vertical split | 2b | wincmd l | 1b | tabdo windo diffthis | tabfirst" local.txt base.txt remote.txt```
2. Two tabs will be opened, but diff will only be enabled in the first one.

### Expected behaviour

diff should be enabled in both tabs.

In fact, if I run the same command **without the last "tabfirst"** token (like this: ```vim -f -c "echo | -tabnew | vertical split | 2b | wincmd l | 3b | tabnext | vertical split | 2b | wincmd l | 1b | tabdo windo diffthis" "$LOCAL" "$BASE" "$REMOTE"```) it works as expected, and diff mode is enabled in both tabs. If I then run ```:tabfirst```, diff mode keeps being enabled in both tabs... so it's something that only happens when running "tabfirst" from the command line with "-c"

### Operating system

Linux 5.14, sway

### Version of Vim

8.2

**Comment by lacygoill** [comment]
That's not a bug.

   > so it's something that only happens when running "tabfirst" from the command line with "-c"

Yes, because `:windo` and `:tabdo` parse a bar as part of their argument (see [`:help :bar`](https://vimhelp.org/cmdline.txt.html#%3Abar)).

So, this bar here:

    tabdo windo diffthis | tabfirst
                         ^

does not terminate `:tabdo windo diffthis`;  it just terminates `:diffthis`.

IOW, `:tabdo windo` does not execute `:diffthis` in each window; but `:diffthis | tabfirst`.

---

Use a second `-c`:

    vim -c "... | tabdo windo diffthis" -c tabfirst local.txt base.txt remote.txt
                                        ^^

or use `:execute` (to hide the bar from `:tabdo` and `:windo`):

    vim -c "... | execute 'tabdo windo diffthis' | tabfirst" local.txt base.txt remote.txt

**Comment by greenfoo** [comment]
Thanks! I should have figured that out from the documentation. Sorry for the trouble.
