### ISSUE TITLE
Python 3.9.7x64 and gVim 8.2.3582_x64

### ISSUE THREAD

**Issue by petrisch** [vim/vim#9093]
### Steps to reproduce

I have:

+python/dyn
+python3/dyn
DDYNAMIC_PYTHONDLL=\"python27.dll"
DDYNAMIC_PYTHONDLL=\"python39.dll"

And C:\Python39 as well as C:\Python27 in the PATH.
Also PYTHONPATH and PYTHON3_HOME pointing to the same path.

let g:python3_host_prog="C:/Python39"
set pythonthreedll="C:/Python39/python39.dll"
Is in my .vimrc

Still 
echo has("python") gives 1, but
echo has("python3") gives 0

### Expected behaviour

I was trying to enable Youcompleteme, which was compiling fine, but finds no python when getting startet.
Any hint, that the two versions in the title are maybe not compatible?
What's the best version to use?

### Operating system

Windows10

### Version of Vim

gVim 8.2.3582_x64

**Comment by chrisbra** [comment]
Does it look different if you first do:

```
echo has("python3")
echo has("python")
```

**Comment by k-takata** [comment]
Did you get the binary from vim-win32-installer, or compile it by yourself?
Do you use the 64-bit version of python3?

**Comment by petrisch** [comment]
@chrisbra  what do you mean, if i do the python3 first? That gives the same, why should it be different? Possible reason?

@k-takata Yes the binary, and yes python3 is 64bit.

I will try a binary from tuxproject next, but I'm still curious if this is really the problem of compatibility.

**Comment by chrisbra** [comment]
I have asked, because on some systems, it won't be possible to load both python and python3 into the same process. See e.g. this answer on stackoverflow: https://vi.stackexchange.com/questions/779/how-do-i-get-vim-to-be-able-to-run-both-python-and-python3-on-a-linux-system-in/2231#2231

I am not sure, what the situation is on Windows, so I figured asking for a different order is the easiest way to rule that one out :)

So do you need both python for Vim? Can you say where you downloaded both python versions from? BTW: I just noticed:

> let g:python3_host_prog="C:/Python39"
> set pythonthreedll="C:/Python39/python39.dll"

please use `:let &pythonthreedll="<path>". When using `:set` the `"` is considered a comment character. So please from within your vim, check the output of `:set pythondll? pythonthreedll? ` and make sure it points to the correct dll.

**Comment by petrisch** [comment]
set => let g:
Did the trick, thanks for that one. I should have seen that, I was just copy pasting it without thinking :-(

Now ycm shows up, but there are still errors.
About the two installs. I'm unshure if vim still needs python2 for some reason.
I for myself don't. So is it still, that python should point to python27 and python3 to python39?

But hey so far this can be closed, thanks much for lending me a third eye ;-)

**Comment by Konfekt** [comment]
Could 

> g:python3_host_prog

be documented? I only found in Nvim

```
#  doc/provider.txt (lines 55-59)
						*g:python3_host_prog*
Command to start Python 3 (executable, not directory). Setting this makes
startup faster. Useful for working with virtualenvs. Must be set before any
check for has("python3").  >vim
    let g:python3_host_prog = '/path/to/python3'
```

and had to resort to [recompiling](https://github.com/vim/vim/issues/19388) to make binding work in virtual environments
