### ISSUE TITLE
Cannot addmatch with special characters and word broundaries.

### ISSUE THREAD

**Issue by DasOhmoff** [vim/vim#9106]
### Steps to reproduce

Using `matchadd()` to highlight special characters with word boundaries does not seem to be working correctly, I think.

Example:
```
---%--- % ---%---
        ^
```
The command `:call matchadd('Search', '\<%\>')` does not highlight the central `%` sign.

### Expected behaviour

The central `%` should be highlighted.

### Operating system

Windows 10

### Version of Vim

gvim 8.2, 64 bit

**Comment by lacygoill** [comment]
> The command :call matchadd('Search', '\<%\>') does not highlight the central % sign.

That's because the meaning of the `\<` and `\>` atoms is determined by the buffer-local option `'iskeyword'`.

This works as you want:
```vim
vim9script
'---%--- % ---%---'->setline(1)
setlocal iskeyword+=%,-
matchadd('Search', '\<%\>')
```
---

For more info, see:

   - [`:help /\<`](https://vimhelp.org/pattern.txt.html#%2F%5C%3C)
   - [`:help /\>`](https://vimhelp.org/pattern.txt.html#%2F%5C%3E)
   - [`:help 'iskeyword'`](https://vimhelp.org/options.txt.html#'iskeyword')
   - [`:help matchadd()`](https://vimhelp.org/eval.txt.html#matchadd%28%29)

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by DasOhmoff** [comment]
Ah I see, after a `\<` and before the `\>` there has to be a keyword character. Ok thank you.
