### ISSUE TITLE
Not able to render underlined text

### ISSUE THREAD

**Issue by noscript** [vim/vim#9147]
### Steps to reproduce

4eeedc09f broke text rendering with [U+0331 combining diacritical mark](https://en.wikipedia.org/wiki/Macron_below).

```
:echo 'hello world'->str2list()->map({_, val -> list2str([val, 0x0331])})->join('')
```
Renders:
![image](https://user-images.githubusercontent.com/717109/142191264-07d4f828-01fd-424b-b314-2e05175f4366.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/717109/142191322-6c2788c0-f410-44d3-9dcd-f7150f7955f1.png)

### Operating system

Debian 11

### Version of Vim

gVim 8.2.3593

**Comment by noscript** [comment]
Listing the characters in `'guiligatures'` doesn't solve the problem, since it does not allow non-ascii characters.

That breaks my [plugin](https://github.com/noscript/taberian.vim) where I use underlined text like  `2 file.txt ᴮ13` that contains non-ascii character `ᴮ`:


![image](https://user-images.githubusercontent.com/717109/142197186-e64fe53a-81f0-42a6-8ef4-29121e9bb7ef.png)

**Comment by noscript** [comment]
I think I found a workaround:
```
let &guiligatures = list2str(range(32, 126))
```
Also I switched from  U+0331 to  U+0332. Not sure why, but `ᴮ` is now also underline correctly.

**Comment by brammool** [comment]
The workaround should not be needed, characters with a combining character should be drawn properly, no matter what 'guiligatures' is set to.

**Comment by brammool** [comment]
@dusanx

**Comment by dusanx** [comment]
On it, thanks for the heads up, I temporarily moved mailing list off vision. I'll take a look and report/fix here.

**Comment by dusanx** [comment]
@noscript can you please tell me what font is on screenshots or what font are you using for tests? I just run tests with Iosevka and Fira Code, both with forced Pango and using current ligatures code and I can't see the difference. I see on Wikipedia that 'macron below' should have 'unbroken underline when it is run together', but with any font I tested that just doesn't happen.I am also assuming running everything trough Pango is a gold standard since we can't have anything more reliable than that, so half of the tests are using Pango for everything.

Fira Code + standard ligatures code
![flig](https://user-images.githubusercontent.com/77118/142301750-a4e10387-d796-44a9-b76f-539b2fe548ae.png)

Fira Code + everything forced trough Pango
![fpango](https://user-images.githubusercontent.com/77118/142301759-1f66ce6d-47be-453d-bc80-32a454b4c0de.png)

Iosevka + standard ligatures code
![ilig](https://user-images.githubusercontent.com/77118/142301770-07fd9828-df63-4c98-9262-0d120bac00f2.png)

Iosevka + everything forced trough Pango
![ipango](https://user-images.githubusercontent.com/77118/142301777-dc0f884a-e090-4d67-bd32-29771979cdfd.png)

Thoughts?

**Comment by dusanx** [comment]
Stock gvim 8.2.3582 on Arch Linux, so stock ligatures code without any modifications: 
![2021-11-18_001758_435837524](https://user-images.githubusercontent.com/77118/142306098-0322f2ce-fa28-4250-9fb7-14b0e16852e7.png)
Hello world seems underlined properly, using 0x0332?

**Comment by brammool** [comment]
On Ubuntu, the echo command in the issue report doesn't give me any underlining while it should.
I guess the ligature change doesn't check if a composing character is following a regular ASCII character.

**Comment by tonymec** [comment]
Looking at https://www.unicode.org/charts/PDF/U0300.pdf I notice that U+0332 COMBINING LOW LINE is noticeably longer than U+0331 COMBINIG MACRON BELOW on the published chart. This makes me believe that combining U+0332 with several successive characters should produce one continuous underline but that using U+0331 should not, as when using U+0304 COMBINING MACRON to write, for example, āēx̄ȳ.

**Comment by dusanx** [comment]
> On Ubuntu, the echo command in the issue report doesn't give me any underlining while it should. I guess the ligature change doesn't check if a composing character is following a regular ASCII character.

Can you please test with added
`needs_pango = TRUE;`
just before
```
len_sum += gui_gtk2_draw_string_ext(row, col + len_sum,
					 cs, slen, flags, needs_pango);
```
so we know for sure how pure Pango renders font with your setup? To rule out font and rendering differences on different setups.

**Comment by dusanx** [comment]
@tonymec yes, 331 is half width (approximately), 332 is proper underline.

Best to test with:
`:echo 'hello world'->str2list()->map({_, val -> list2str([val, 0x0332])})->join('')`

**Comment by dusanx** [comment]
> I guess the ligature change doesn't check if a composing character is following a regular ASCII character.

This was my first thought too but then it turns out underlining utf-8 followed by ascii (as a separate strings) actually underlines ascii. Pango version? I am on Arch so everything pretty much latest.

**Comment by dusanx** [comment]
After some more tests, I definitely can't make this misbehave in any way, all with stock code from guiligatures patch. This way of underlining is font dependent, some fonts don't have combining marks, so anybody please test with few different guifonts. Also in theory can be Pango/Cairo/Harfbuzz version dependent but I can't cause any misbehavior on Arch.

Since combining marks are all over the utf-8 table it is quicker to try including 'next' character after any utf-8 than to test for all variants. Including next character will print ascii trough Pango after utf-8, not ideal. I can supply patch in day or so but that will be blind patch since everything works on this side.

0x0331 is working correctly too but on some fonts it is higher up and partially covered by letter, 0x0332 is more noticeable. With 0x0331 I had to zoom in on different fonts, partial underline was there but harder to notice.

@brammool can you please try again on Ubuntu with few different fonts and 0x0332?
@noscript  with 0x0332 output stays the same with any guiligatures setting inclding empty `:set guiligatures=` ?

Help welcome since I can't make this misbehave.

**Comment by noscript** [comment]
@dusanx Sorry for adding an extra confusion, I made a typo in the first post. Originally it was decimal `818`, then I changed it to HEX and made a typo. So it should have been `0x0332` and not `0x0331`. That's why you had dashed underline. `0x0332` gives proper solid underline with any font I tested.

So I repeated the tests with two Vim builds, the latest and Vim 8.2.3523 (the one before `guiligatures` was introduced).
```
vim -g \
  +"echo v:versionlong" \
  +"echo 'hello world 0x0331'->str2list()->map({_, val -> list2str([val, 0x0331])})->join('')" \
  +"echo 'hello world 0x0332'->str2list()->map({_, val -> list2str([val, 0x0332])})->join('')"
```

In my case the latest build doesn't give me any underline, even with `0x0331`:

![image](https://user-images.githubusercontent.com/717109/142397908-d1cd78e3-cb04-49e6-8e33-1db8be83cafe.png)

unless I also do `let &guiligatures = list2str(range(32, 126))`, then it works:

![image](https://user-images.githubusercontent.com/717109/142398049-9b2d03bf-6bf0-47bf-aa09-23d84da593db.png)

Vim 8.2.3523:

![image](https://user-images.githubusercontent.com/717109/142397616-30976b8c-8622-4554-bbd2-818a81853933.png)

**Comment by dusanx** [comment]
@noscript thanks for the input, much appreciated. With your vim -g snippet above and latest gvim on arch I am getting everything rendered correctly, independent on guiligatures.

![2021-11-18_104220_991594705](https://user-images.githubusercontent.com/77118/142401024-1101e286-cf15-4f91-a454-61530553b30b.png)

Let me prepare code to consume next character with any utf8 character, which should solve this with brute force, then I'll ask you to try compiling that branch. Sadly I can't reproduce this on my end which would make debugging much more easier.

**Comment by brammool** [comment]
> After some more tests, I definitely can't make this misbehave in any
> way, all with stock code from guiligatures patch. This way of
> underlining is font dependent, some fonts don't have combining marks,
> so anybody please test with few different guifonts. Also in theory can
> be Pango/Cairo/Harfbuzz version dependent but I can't cause any
> misbehavior on Arch.
> 
> Since combining marks are all over the utf-8 table it is quicker to
> try including 'next' character after any utf-8 than to test for all
> variants. Including next character will print ascii trough Pango after
> utf-8, not ideal. I can supply patch in day or so but that will be
> blind patch since everything works on this side.
> 
> 0x0331 is working correctly too but on some fonts it is higher up and
> partially covered by letter, 0x0332 is more noticeable. With 0x0331 I
> had to zoom in on different fonts, partial underline was there but
> harder to notice.
> 
> @brammool can you please try again on Ubuntu with few different fonts
> and 0x0332?
> @noscript  with 0x0332 output stays the same with any guiligatures
> setting inclding empty `:set guiligatures=` ?
> 
> Help welcome since I can't make this misbehave.

It must not depend on the font.  What should happen is that the
combining character is drawn on top of the preceding character.
No ligutures are to be used.  That's how Vim has always done it, since
fonts cannot be trusted to do this right.  Quite often what the font
draws is something else than just combining the two characters.  That is
why 'guiligatures' is empty by default, one needs to check that it
actually works before using it.

I added the "needs_pango = TRUE" as you mentioned.  It does not help.
What is drawn actually depends on whether the cursor is moved from left
to right or right to left over the text.  Left to right I see "hello"
without underline, right to left I see some underline in the wrong
position and garbage.

-- 
We learn from our mistakes.  Politicians don't make mistakes.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dusanx** [comment]
> It must not depend on the font. What should happen is that the combining character is drawn on top of the preceding character. No ligutures are to be used.

What I meant is that some fonts from my collection (very old SF Mono from Mac for example) don't have and don't draw (properly) 0x0331 or 0x0332. On SF Mono 331 is not visible at all and 332 looks like very short 331. All this drawing is done by overlapping _ and other character, both supplied by font, on Pango level. Of course why my Pango can combine 0x0332 as one string and 'a' as another is interesting but hard to figure out. I bet it is Pango version dependent, otherwise it will fail for me too.

I have fix in the works and will push for testing in next 48 hours or less, with any utf-8 code will consume next character to go trough Pango too, which will solve this.

**Comment by brammool** [comment]
> > It must not depend on the font. What should happen is that the
> > combining character is drawn on top of the preceding character. No
> > ligutures are to be used.
> 
> What I meant is that some fonts from my collection (very old SF Mono
> from Mac for example) don't have and don't draw (properly) 0x0331 or
> 0x0332. On SF Mono 331 is not visible at all and 332 looks like very
> short 331. All this drawing is done by overlapping _ and other
> character, both supplied by font, on Pango level. Of course why my
> Pango can combine 0x0332 as one string and 'a' as another is
> interesting but hard to figure out. I bet it is Pango version
> dependent, otherwise it will fail for me too.

On my system it's clear that with the same font and library, there is a
big difference before the patch and after it.  I suppose the font does
not have anything special for drawing the underline and it just draws
two glyphs on top of each other.


To see the text in the buffer I use:
	:call setline(1, 'hello world 0x0332'->str2list()->map({_, val -> list2str([val, 0x0332])})->join(''))

Then you can move the cursor over it to check what happens.

> I have fix in the works and will push for testing in next 48 hours or
> less, with any utf-8 code will consume next character to go trough
> Pango too, which will solve this.

Please also check how the old code handled combining characters.

I can fix the problem brute force by commenting out the "break" from the
loop in gui_gtk2_draw_string():

	    is_utf8 = *(cs + slen) & 0x80;
	    should_need_pango = (is_ligature || is_utf8);
//	    if (needs_pango != should_need_pango) // mode switch
//		break;
	    if (needs_pango)
	    {

Thus it appears the string is broken up in too small pieces.  If a
combining character is following it should probably be included.

This seems to work:

	    is_utf8 = *(cs + slen) & 0x80;
	    next_is_composing = mb_ptr2len(cs + slen) > utf_ptr2len(cs + slen);
	    should_need_pango = (is_ligature || is_utf8 || next_is_composing);
	    if (needs_pango != should_need_pango) // mode switch
		break;
	    if (needs_pango)
	    {

Not sure about drawbacks.

-- 
   [SIR LAUNCELOT runs back up the stairs, grabs a rope
   of the wall and swings out over the heads of the CROWD in a
   swashbuckling manner towards a large window.  He stops just short
   of the window and is left swing pathetically back and forth.]
LAUNCELOT: Excuse me ... could somebody give me a push ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dusanx** [comment]
`should_need_pango = (is_ligature || is_utf8 || next_is_composing);`

Nearly identical with what I am working on, thanks. I'll push as soon as I test some more.
