### ISSUE TITLE
expand('<sfile>:p:h') doesn't get script directory in vim9script

### ISSUE THREAD

**Issue by kohnish** [vim/vim#9178]
### Steps to reproduce

1. Get latest vim
2. In a random plugin file written in vim9script, add `echom expand('<sfile>:p:h')`
3. It prints you current dir instead of the vim script directory

### Expected behaviour

It print the source script file directory.

### Operating system

Fedora 35

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 04 2020 00:00:00) Included patches: 1-3640

**Comment by lacygoill** [comment]
I can't reproduce on my machine.  Can you give a minimal working example?  Where is the plugin file written?  How is Vim started?

**Comment by kohnish** [comment]
@lacygoill  
Thank you for trying to reproduce, and sorry, I should've been more concrete.  
It's from the import. So it's called like this.
Here is an example which should reproduce the issue.
~/.vim/pack/git-plugins/start/test/plugin/test.vim
```
vim9script

import * as job_handler from "./job_handler.vim"
def Main(): void
        job_handler.Show()
enddef

call Main()
```

~/.vim/pack/git-plugins/start/myplugin/plugin/job_handler.vim
```
vim9script

export def Show(): void
    echom expand('<sfile>:p:h')
enddef
```

**Comment by lacygoill** [comment]
Sorry, but I still can't reproduce.

You wrote 2 filepaths in different 2 directories:

                                  v--v
    ~/.vim/pack/git-plugins/start/test/plugin/test.vim
    ~/.vim/pack/git-plugins/start/myplugin/plugin/job_handler.vim
                                  ^------^

Which means that the `:import` command cannot succeed, because the `job_handler.vim` file is in a different directory:

    import * as job_handler from "./job_handler.vim"
                                  ^
                                  ✘

I'm going to assume that you meant `test.vim` and `job_handler.vim` to be in the same directory; let's say this one:

    ~/.vim/pack/git-plugins/start/myplugin/plugin/

And that you have this file hierarchy under `~/.vim/pack/git-plugins`:

    .
    └── start
        └── myplugin
            └── plugin
                ├── job_handler.vim
                └── test.vim

Here is a minimal example to reproduce your whole setup, as I understand it:

    cd && vim -Nu <(cat <<'EOF'
        vim9script
        echomsg getcwd()
        &packpath = '/tmp/.vim'
        var path = &packpath .. '/pack/git-plugins/start/myplugin/plugin'
        mkdir(path, 'p')

        var lines =<< trim END
            vim9script

            import * as job_handler from "./job_handler.vim"
            def Main(): void
                    job_handler.Show()
            enddef

            call Main()
        END
        lines->writefile(path .. '/test.vim')

        lines =<< trim END
            vim9script

            export def Show(): void
                echom expand('<sfile>:p:h')
            enddef
        END
        lines->writefile(path .. '/job_handler.vim')
    EOF
    )

Here is the output of this shell command on my machine:

    /home/lgc
    /tmp/.vim/pack/git-plugins/start/myplugin/plugin

In the OP, you wrote:

   > It prints you current dir instead of the vim script directory

That's not what I can see.  `getcwd()` evaluates to my current directory `/home/lgc`, while `expand('<sfile>:p:h')` evaluates to the vim script directory `/tmp/.vim/pack/git-plugins/start/myplugin/plugin/`.

**Comment by kohnish** [comment]
ok. thanks. I'll do my digging, possibly share the exact script. Thanks for looking into it.

**Comment by kohnish** [comment]
Hey @lacygoill 
I might've lied about the description. Sorry.
Could you please try this? https://github.com/kohnish/test.git
And run :Show?

**Comment by lacygoill** [comment]
The same behavior can be observed in legacy:

    vim -Nu NONE -S <(cat <<'EOF'
        function Func()
            echomsg expand('<sfile>:p:h')
        endfunction
        command Cmd call Func()
    EOF
    ) +Cmd

    /home/lgc

There are 2 issues in this code.  First, `<sfile>` can only give the name of the sourced script when it's evaluated at the script level; not inside a function:

    ✔
    echo expand('<sfile>')

    ✘
    function Func()
        echo expand('<sfile>')
    endfunction

Inside a function, `<sfile>` gives the call stack, but only for backwards compatibility reasons (since [8.2.1297](https://github.com/vim/vim/releases/tag/v8.2.1297), `<stack>` should be used instead for that).

Second, in a function, it's useless to apply modifiers to `<sfile>`:

   > Note that filename-modifiers are useless when <sfile> is
   > not used inside a script.

Since your `<sfile>` is written inside the `Show()` function, `:p:h` is useless.  If you want the path to the directory of the script, make sure to evaluate `expand('<sfile>')` at the script level:
```diff
diff --git a/plugin/test2.vim b/plugin/test2.vim
index d623598..1f00a61 100644
--- a/plugin/test2.vim
+++ b/plugin/test2.vim
@@ -1,6 +1,7 @@
 vim9script
 
+var dir: string = expand('<sfile>:p:h')
 export def Show(): void
-    echom expand('<sfile>:p:h')
+    echom dir
 enddef
 
```

**Comment by lacygoill** [comment]
It is really confusing for `expand('<sfile>')` to give a directory when it's passed filename modifiers and evaluated inside a function.  IMO, it should give the exact same output as if no modifiers had been passed.  That is, the previous shell command should output this:

    command line..function Func

And not this:

    /home/lgc

It would be more consistent.  Besides, there is nothing in the help which suggests that `:p:h` should turn the call stack into the current working directory.

**Comment by kohnish** [comment]
Obviously I missed the documentation. My apologies for taking your time. :(
Thanks for providing explanation and also solution! @lacygoill

**Comment by lacygoill** [comment]
> It is really confusing for expand('&lt;sfile>') to give a directory when it's passed filename modifiers and evaluated inside a function.

Maybe an error should be given at compile time, whenever Vim finds `expand('<sfile>')` in a function.  After all, according to [`:help <sfile>`](https://vimhelp.org/cmdline.txt.html#<sfile>), `<sfile>` is equivalent to `<stack>` in a function.  But the latter is more readable.  Allowing `<sfile>` in a function lets us write confusing code, because it looks like we get a simple file path, while in reality we get a call stack.
