### ISSUE TITLE
`exists('+cdhome')` returns 1 on Linux

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#9325]
### Steps to reproduce

1. Run `vim --clean`
2. `:echo exists('+cdhome')`
3. Prints `1`

### Expected behaviour

Prints `0`

### Operating system

Arch Linux

### Version of Vim

8.2.3781

**Comment by lacygoill** [comment]
I think you meant `'cdhome'`, and not `'cdpath'`.

**Comment by zeertzjq** [comment]
> I think you meant `'cdhome'`, and not `'cdpath'`.

Oops, typo.

**Comment by brammool** [comment]
I prefer minimizing #ifdefs and features only working in some environments, so I just added 'cdhome' for all systems.  On Unix it simply has no effect.  So you can set it in your vimrc and use it all systems without checking.

**Comment by zeertzjq** [comment]
I believe making `exists('+cdhome')` return `0` on Unix still allows using it in all system without checking.

**Comment by Shane-XB-Qian** [comment]
> I believe making `exists('+cdhome')` return `0` on Unix still allows using it in all systems without checking.

a bit confused, but perhaps similar like some options for 'mouse',  e.g 'mousefocus', existed but '{only works in the GUI}'.

**Comment by brammool** [comment]
In the past #ifdefs were often used to reduce the size of the executable.  These days we don't worry about size so much, keeping the code simple has become more important.

**Comment by dpelle** [comment]
@brammool wrote:
 
> In the past #ifdefs were often used to reduce the size of the executable.
> These days we don't worry about size so much, keeping the code simple
> has become more important.

Reducing `#ifdef` helps reducing the number of bugs, as it's hard to check
every combination of `#ifdef`.

Vim has several versions (tiny, small, normal, big, huge). So many versions
seem overkill.   Maybe we just need tiny and huge?  Tiny is generally
the one installed by default in Linux distributions.  And vim users can install
the huge one if they want.  In any cases, it's out of the scope of this PR.

**Comment by brammool** [comment]
Dominique wrote:

> @brammool wrote:
>  
> > In the past #ifdefs were often used to reduce the size of the executable.
> > These days we don't worry about size so much, keeping the code simple
> > has become more important.
> 
> Reducing `#ifdef` helps reducing the number of bugs, as it's hard to check
> every combination of `#ifdef`.
> 
> Vim has several versions (tiny, small, normal, big, huge). So many versions
> seem overkill.   Maybe we just need tiny and huge?  Tiny is generally
> the one installed by default in Linux distributions.  And vim users can install
> the huge one if they want.  In any cases, it's out of the scope of this PR.

The tiny/small/normal/big/huge choice doesn't matter too much for
complexity, it's all the individual features that can be included or
not that make it hard to test all combinations.

For "small" there are just a few things:
- jumplist
- cmdwin
- message history length

We could graduate +jumplist and always use the longer message history.
The +cmdwin feature I'm not sure about.  Some people complain that they
accidentally type "q:" instead of ":q" and don't understand what
happened.

Another thing that might help: always build the GUI with "huge".  Since
the GUI libraries are usually big anyway.  But some users might want to
disable individual features perhaps.

-- 
"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shane-XB-Qian** [comment]
```
+mouse         
+mouseshape    
+mouse_dec     
-mouse_gpm     
-mouse_jsbterm 
+mouse_netterm 
+mouse_sgr     
-mouse_sysmouse
+mouse_urxvt
+mouse_xterm
```

there is `mouseshape` but no `mousefocus` etc, i meant perhaps `mouseshape` can be graduated too?
// i am not sure very sure what's the difference actually.. :-)

and as another ticket for 'cdhome' mentioned, the term of 'unix' in 'doc' though most people knew it actually meant 'unix-like' but some not, perhaps someday we can re-word to 'unix-like' (and 'non-unix-like') uniformly.
