### ISSUE TITLE
v:true ==# 1, but not for dictionary comparison

### ISSUE THREAD

**Issue by dstein64** [vim/vim#9328]
### Steps to reproduce

```vim
:echo v:true ==# 1
```
outputs `1`.

```vim
:echo {'a': 1} ==# {'a': 1}
```
outputs `1`.

```vim
:echo {'a': v:true} ==# {'a': v:true}
```
outputs `1`.

```vim
:echo {'a': 1} ==# {'a': v:true}
```
outputs `0`.

### Expected behaviour

My expectation was that the last example would output `1` since that was the case for `:echo v:true ==# 1`, the first example above.

### Operating system

Kubuntu 21.10

### Version of Vim

8.2. Included patches: 1-2434, 3402-3403, 3409, 3428, 3487, 3564, 3581-3582

**Comment by brammool** [comment]
Yeah, this may be a bit illogical, but that's the way it works.  In the first example the right hand side is a number, thus the comparison is done on numbers, and v:true is converted to the number one, thus it's a match.
When comparing dictionaries, there is no conversion, the values must be equal.

I don't think we should change this, it's likely to cause more trouble than it solves.
In Vim9 script the first example will give an error: "Cannot compare bool with number".
Thus then it's more consistent.

**Comment by lacygoill** [comment]
> My expectation was that the last example would output 1 since that was the case for :echo v:true ==# 1, the first example above.

FWIW, I would argue that the issue is in the first command which should output `0` (or give an error).  But changing this now would probably break many existing scripts, so it's too late.

However, if you prefix your comparison command with the `:vim9` modifier, you get more reliable results:

    :vim9 echo true == 1
    E1072: Cannot compare bool with number

    :vim9 echo {a: 1} == {a: 1}
    true

    :vim9 echo {a: true} == {a: true}
    true

    :vim9 echo {a: 1} == {a: true}
    false

Notice that:

   - an error is given when comparing `v:true` and `1` because the types of the operands do not match (boolean vs number)
   - a real boolean is given when the comparison is allowed (which is less ambiguous than a boolean number)
   - there is no need to append `#` to the `==` comparison operator (the 'ignorecase' option is not used for comparators that use strings)
   - there is no need to prepend `v:` in front of `true`/`false`
   - there is no need to quote the keys in a dictionary (as long as they only use alphanumeric characters, minus characters, and underscores)
