### ISSUE TITLE
Initial keystrokes not going to terminal opened in callbacks

### ISSUE THREAD

**Issue by senioria** [vim/vim#9359]
## Steps to reproduce

1. `vim -Nu NONE -c "call timer_start(1000, { -> term_start('sh') })"`
2. When the terminal is opened, press C-C; and vim prompts that press :q to quit.

## Expected behavior

Send the keystroke to the process in the terminal.

## Environment

vim version: 8.2.3821

**Comment by brammool** [comment]
> ## Steps to reproduce
> 
> 1. `vim -Nu NONE -c "call timer_start(1000, { -> term_start('sh') })"`
> 2. When the terminal is opened, press C-C; and vim prompts that press :q to quit.
> 
> ## Expected behavior
> 
> Send the keystroke to the process in the terminal.

This happens because Vim is waiting for a command character to be typed.
Characters for the terminal are used elsewhere.

I can fix it by inserting K_IGNORE so that the loop returns and goes to
the loop to get characters for the terminal.

-- 
hundred-and-one symptoms of being an internet addict:
43. You tell the kids they can't use the computer because "Daddy's got work to
    do" and you don't even have a job.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
Fixed in patch [8.2.3828](https://github.com/vim/vim/releases/tag/v8.2.3828).
