### ISSUE TITLE
Can't set location list title inside a function

### ISSUE THREAD

**Issue by cdlscpmv** [vim/vim#9406]
### Steps to reproduce

````
function! SetLocList()
    ...
    call setloclist(0, <list>)
    call setloclist(0, [], 'r', {'title' : 'location list title'})
    lopen
endfunction
````

The new location list has ``:setloclist()`` as its title.

The title is set correctly, if ``call setloclist(0, [], 'r', {'title' : 'location list title'})`` is executed on the command-line manually after ``:lopen``.

### Expected behaviour

The opened location list should have the assigned title.

### Version of Vim

8.2.3565

### Environment

Doesn't matter.

**Comment by lacygoill** [comment]
I can't reproduce.  Neither on master nor on [8.2.3565](https://github.com/vim/vim/releases/tag/v8.2.3565):
```vim
function SetLocList()
    edit /tmp/file
    call setline(1, 'test')
    write!
    let list = [#{lnum: 1, valid: 1, col: 1, text: 'test'} ]
    call setloclist(0, list)
    call setloclist(0, [], 'r', {'title' : 'location list title'})
    lopen
endfunction
call SetLocList()
echo w:quickfix_title
```
    location list title

Try to reproduce without config.  Start Vim with one of these shell commands:

    vim -Nu NONE
    vim --clean

---

You don't want the `r` flag, but the `a` flag:

    call setloclist(0, [], 'r', {'title' : 'location list title'})
                            ^
                            ✘

    call setloclist(0, [], 'a', {'title' : 'location list title'})
                            ^
                            ✔

Otherwise, you're replacing the location list with an empty list.  See [`:help setqflist-action`](https://vimhelp.org/eval.txt.html#setqflist-action).

**Comment by cdlscpmv** [comment]
@lacygoill Thanks for the quick reply. The problem was in a plugin. My mistake, sorry. Closing the issue.
