### ISSUE TITLE
How can i run Autocmd on another opened buffer ?

### ISSUE THREAD

**Issue by aimen08** [vim/vim#9408]
I have vim open with 2  buffers split vertically, the second one is  output file or log file which gets updated outside of vim, so to achieve auto scrolling when that happens i'm doing this :

`au TextChanged output:///* normal G`(everytime the buffer change the cursor goes to the bottom)

my problem is : the scrolling only happens when i'm focusing the buffer or entering the buffer.

i tried to lookup  events other than TextChanged ,
i found this [FileChangedShellPost](https://vimhelp.org/autocmd.txt.html#FileChangedShellPost) but without luck it didn't work.

**Comment by lacygoill** [comment]
`TextChanged` is only fired when the buffer is changed from a command in the current Vim instance.

`FileChangedShellPost` is fired (for the most part):

   - after you execute a shell command with [`:!`](https://vimhelp.org/various.txt.html#%3A%21)
   - after you execute [`:checktime`](https://vimhelp.org/editing.txt.html#%3Achecktime)
   - after you focus back the Vim terminal window (if your terminal supports the focus event tracking feature, or you are in the GUI)

See [`:help FileChangedShell`](https://vimhelp.org/autocmd.txt.html#FileChangedShell):

   > Mostly triggered after executing a shell
   > command, but also with a |:checktime| command
   > or when gvim regains input focus.

Otherwise, the event is not fired, which is probably why your `:normal G` command is not executed when the file is changed outside Vim.

---

Anyway, if you're on linux and you have [inotifywait](https://man7.org/linux/man-pages/man1/inotifywait.1.html), then you can try:
```vim
vim9script
&autoread = true
command -bar AutoRead AutoRead()
def AutoRead()
  if !executable('inotifywait')
    echomsg 'missing dependency: inotifywait(1); https://man7.org/linux/man-pages/man1/inotifywait.1.html'
    return
  endif
  var file: string = expand('%')->fnamemodify(':p')
  var cmd: string = printf('while true; do inotifywait --event modify %s; done', file)
  job_start(['sh', '-c', cmd], {out_cb: function(AutoreadOutCb, [bufnr('%')])})
enddef
def AutoreadOutCb(buf: number, ..._)
  execute 'checktime ' .. buf
  var winid: number = getbufinfo(buf)
    ->get(0, {})
    ->get('windows', {})
    ->get(0)
  win_execute(winid, 'normal! G')
enddef
```
On Ubuntu, `inotifywait(1)` is provided by the `inotify-tools` package:

    $ sudo apt install inotify-tools

---

Same Vimscript code in legacy:
```vim
set autoread
command -bar AutoRead call s:AutoRead()
function s:AutoRead() abort
  if !executable('inotifywait')
    echomsg 'missing dependency: inotifywait(1); https://man7.org/linux/man-pages/man1/inotifywait.1.html'
    return
  endif
  let file = expand('%')->fnamemodify(':p')
  let cmd = printf('while true; do inotifywait --event modify %s; done', file)
  call job_start(['sh', '-c', cmd], #{out_cb: function('s:AutoreadOutCb', [bufnr('%')])})
endfunction
function s:AutoreadOutCb(buf, ...)
  execute 'checktime ' .. a:buf
  let winid = getbufinfo(a:buf)
    \ ->get(0, {})
    \ ->get('windows', {})
    \ ->get(0)
  call win_execute(winid, 'normal! G')
endfunction
```
---

You might also be interested in the [vim-autoread](https://github.com/chrisbra/vim-autoread) plugin.

---

For more info, see:

   - [`:help 'autoread'`](https://vimhelp.org/options.txt.html#%27autoread%27)
   - [`:help :checktime`](https://vimhelp.org/editing.txt.html#%3Achecktime)
   - [`:help :command`](https://vimhelp.org/map.txt.html#%3Acommand)
   - [`:help :command-bar`](https://vimhelp.org/map.txt.html#%3Acommand-bar)
   - [`:help :def`](https://vimhelp.org/vim9.txt.html#%3Adef)
   - [`:help :execute`](https://vimhelp.org/eval.txt.html#%3Aexecute)
   - [`:help :var`](https://vimhelp.org/vim9.txt.html#%3Avar)
   - [`:help bufnr()`](https://vimhelp.org/eval.txt.html#bufnr%28%29)
   - [`:help executable()`](https://vimhelp.org/eval.txt.html#executable%28%29)
   - [`:help expand()`](https://vimhelp.org/eval.txt.html#expand%28%29)
   - [`:help fnamemodify()`](https://vimhelp.org/eval.txt.html#fnamemodify%28%29)
   - [`:help function()`](https://vimhelp.org/eval.txt.html#function%28%29)
   - [`:help get()`](https://vimhelp.org/eval.txt.html#get%28%29)
   - [`:help getbufinfo()`](https://vimhelp.org/eval.txt.html#getbufinfo%28%29)
   - [`:help job_start()`](https://vimhelp.org/channel.txt.html#job_start%28%29)
   - [`:help printf()`](https://vimhelp.org/eval.txt.html#printf%28%29)
   - [`:help win_execute()`](https://vimhelp.org/eval.txt.html#win_execute%28%29)

---

For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

**Comment by aimen08** [comment]
> `TextChanged` is only fired when the buffer is changed from a command in the current Vim instance.
> 
> `FileChangedShellPost` is fired (for the most part):
> 
> * after you execute a shell command with [`:!`](https://vimhelp.org/various.txt.html#%3A%21)
> * after you execute [`:checktime`](https://vimhelp.org/editing.txt.html#%3Achecktime)
> * after you focus back the Vim terminal window (if your terminal supports the focus event tracking feature, or you are in the GUI)
> 
> See [`:help FileChangedShell`](https://vimhelp.org/autocmd.txt.html#FileChangedShell):
> 
> > Mostly triggered after executing a shell
> > command, but also with a |:checktime| command
> > or when gvim regains input focus.
> 
> Otherwise, the event is not fired, which is probably why your `:normal G` command is not executed when the file is changed outside Vim.
> 
> Anyway, if you're on linux and you have [`inotifywait(1)`](https://man7.org/linux/man-pages/man1/inotifywait.1.html), then you can try:
> 
> ```viml
> vim9script
> &autoread = true
> command -bar AutoRead AutoRead()
> def AutoRead()
>   if !executable('inotifywait')
>     echomsg 'missing dependency: inotifywait(1); https://man7.org/linux/man-pages/man1/inotifywait.1.html'
>     return
>   endif
>   var cmd: string = 'inotifywait --monitor --event modify ' .. expand('%:p')
>   job_start(cmd, {out_cb: function(AutoreadOutCb, [bufnr('%')])})
> enddef
> def AutoreadOutCb(buf: number, ..._)
>   execute 'checktime ' .. buf
>   win_execute(bufwinid(buf), 'normal! G')
> enddef
> ```
> 
> It installs an `:AutoRead` command which you can execute in the window displaying the buffer which you want Vim to automatically reload whenever the corresponding file changes, and for which you always want the cursor to be on the last line.
> 
> On Ubuntu, `inotifywait(1)` is provided by the `inotify-tools` package:
> 
> ```
> $ sudo apt install inotify-tools
> ```
> 
> Same Vimscript code in legacy:
> 
> ```viml
> set autoread
> command -bar AutoRead call s:AutoRead()
> function s:AutoRead() abort
>   if !executable('inotifywait')
>     echomsg 'missing dependency: inotifywait(1); https://man7.org/linux/man-pages/man1/inotifywait.1.html'
>     return
>   endif
>   let cmd = 'inotifywait --monitor --event modify ' .. expand('%:p')
>   call job_start(cmd, #{out_cb: function('s:AutoreadOutCb', [bufnr('%')])})
> endfunction
> function s:AutoreadOutCb(buf, ...)
>   execute 'checktime ' .. a:buf
>   win_execute(bufwinid(a:buf), 'normal! G')
> endfunction
> ```
> 
> You might also be interested in the [vim-autoread](https://github.com/chrisbra/vim-autoread) plugin.
> 
> For more info, see:
> 
> * [`:help 'autoread'`](https://vimhelp.org/options.txt.html#%27autoread%27)
> * [`:help :checktime`](https://vimhelp.org/editing.txt.html#%3Achecktime)
> * [`:help :command`](https://vimhelp.org/map.txt.html#%3Acommand)
> * [`:help :command-bar`](https://vimhelp.org/map.txt.html#%3Acommand-bar)
> * [`:help :def`](https://vimhelp.org/vim9.txt.html#%3Adef)
> * [`:help :execute`](https://vimhelp.org/eval.txt.html#%3Aexecute)
> * [`:help :var`](https://vimhelp.org/vim9.txt.html#%3Avar)
> * [`:help bufnr()`](https://vimhelp.org/eval.txt.html#bufnr%28%29)
> * [`:help bufwinid()`](https://vimhelp.org/eval.txt.html#bufwinid%28%29)
> * [`:help executable()`](https://vimhelp.org/eval.txt.html#executable%28%29)
> * [`:help expand()`](https://vimhelp.org/eval.txt.html#expand%28%29)
> * [`:help function()`](https://vimhelp.org/eval.txt.html#function%28%29)
> * [`:help job_start()`](https://vimhelp.org/channel.txt.html#job_start%28%29)
> * [`:help win_execute()`](https://vimhelp.org/eval.txt.html#win_execute%28%29)
> 
> For more questions, visit the [google mailing list](https://groups.google.com/g/vim_use), the [irc channel](https://www.vi-improved.org/), or [vi.stackexchange.com](https://vi.stackexchange.com/).

yes this seems the way to do it, but it wont work in my case since inotfiywait wont watch `output:///` for changes,  it's not file.

 there is missing `call` in `win_execute(bufwinid(a:buf), 'normal! G')`

btw thank you for the long answer , you pointed me to the right path i will keep looking at it.

**Comment by lacygoill** [comment]
> yes this seems the way to do it, but it wont work in my case since inotfiywait wont watch output:/// for changes, it's not file.

Then maybe a timer running forever and executing `:normal! G` every 1s:
```vim
vim9script
command -bar AutoScrollToBottom AutoScrollToBottom()
def AutoScrollToBottom()
  var winid: number = win_getid()
  timer_start(1'000, (_) => win_execute(winid, 'normal! G'), {repeat: -1})
enddef
```
```vim
command -bar AutoScrollToBottom call s:AutoScrollToBottom()
function s:AutoScrollToBottom()
  let winid = win_getid()
  call timer_start(1000, {-> win_execute(winid, 'normal! G')}, #{repeat: -1})
endfunction
```
See [`:help timer_start()`](https://vimhelp.org/eval.txt.html#timer_start%28%29).

> there is missing call in win_execute(bufwinid(a:buf), 'normal! G') (legacy)

I updated the snippets to fix this issue.

**Comment by aimen08** [comment]
Thank you so much . it's working like intended .
