### ISSUE TITLE
[question] next version

### ISSUE THREAD

**Issue by bounceme** [vim/vim#949]
just curious, will there be vim 8 beta releases between the 7.4 -> 8 switch?

**Comment by chrisbra** [comment]
Please use the existing mailing list to ask questions. This is no support forum here. Thanks.

**Comment by bounceme** [comment]
well I've refactored the `pangloss/vim-javascript` indent script for javascript, https://github.com/pangloss/vim-javascript/blob/develop/indent/javascript.vim and since it is fairly small and minimal, wondered whether it may be considered for inclusion in vim since https://github.com/pangloss/vim-javascript/issues/177#issuecomment-38364489 .It needs to be tested more however and one issue exists : performance, which is much slower than cindent. though it uses similar techniques as the python and clojure ones in default vim.
 As there seems to be a major release coming this could be a improvement for many people who have to find third party scripts, though I hesitate, knowing if it does happen to be included and there are bad bugs os distributions which settle on major releases will be plagued by my changes
edit: sorry, maybe I will make a new issue, or p.r. ?

**Comment by chrisbra** [comment]
in the past, before the major version was released alpha and beta releases have been made. However, since development happens in master already, you can test with the current version. If you notice some problems, you can report them here or at vim-dev. Also for inclusion of third party scripts a mail to vim-dev is probably the best idea.

**Comment by brammool** [comment]
Bounceme wrote:

> well I've made a refactored the `pangloss/vim-javascript` indent
> script for javascript,
> https://github.com/pangloss/vim-javascript/blob/develop/indent/javascript.vim
> and since it is fairly small and minimal, wondered whether it may be
> considered for inclusion in vim since
> https://github.com/pangloss/vim-javascript/issues/177#issuecomment-38364489
> .It needs to be tested more however and one issue exists :
> performance, which is much slower than cindent. though it uses similar
> techniques as the python and clojure ones in default vim.
>  As there seems to be a major release coming this could be a
>  improvement for many people who have to find third party scripts,
>  though I hesitate, knowing if it does happen to be included and there
>  are bad bugs os distributions which settle on major releases will be
>  plagued by my changes

To get your script tested by users, add it to the Vim script collection:
http://www.vim.org/scripts/index.php

Adding indent and syntax scripts is a continuous process, it doesn't
depend on a release.

Once you (and users) are happy with the script email it to me.
Since this would replace an existing indent script you'll have to
convince the existing maintainer that yours is better.

## 

   [Another hideous roar.]
BEDEVERE: That's it!
ARTHUR:   What?
BEDEVERE: It's The Legendary Black Beast of Aaaaarrrrrrggghhh!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///
