### ISSUE TITLE
packadd loads the plugin twice

### ISSUE THREAD

**Issue by kohnish** [vim/vim#9664]
### Steps to reproduce

Follow the installation guide in https://github.com/prabirshrestha/vim-lsp (vim9script lsp client) (happens with other plugins as well)
Add `echom fnamemodify(resolve(expand('<stack>:p')), ':h')` in `plugin/lsp.vim`. You see the different print message twice.

My vimrc is located in `~/.vim/vimrc`
with plugins dir in
` ~/.vim/pack/plugins/opt/`

### Expected behaviour

Print only once

### Version of Vim

8.2 Included patches: 1-4179

### Environment

Fedora 35

**Comment by lacygoill** [comment]
Append a bang to `:packadd`.  That is, in your vimrc, instead of writing this:

    :packadd some_package

Write this:

    :packadd! some_package
            ^

With a bang, only the runtimepath is updated, so that later, once your vimrc has been fully sourced, and Vim tries to source the plugins, it can find the package.

Without a bang, the package is sourced immediately.  But then later, it's sourced a second time during the step where Vim sources the plugins.

See [`:help :packadd`](https://vimhelp.org/repeat.txt.html#%3Apackadd).

**Comment by kohnish** [comment]
Oh, sorry for my noobness. It worked. Thanks a lot.
