### ISSUE TITLE
A mistake in "runtime/syntax/autoit.vim"

### ISSUE THREAD

**Issue by imbear** [vim/vim#970]
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2016 11:12:30)
> MS-Windows 64-bit GUI version
> Included patches: 1-2190

`syn match autoitConst "\STR_STRIPLEADING"`
should be
`syn match autoitConst "\$STR_STRIPLEADING"`

**Comment by cecamp** [comment]
If this change should be made to the syntax/autoit.vim file, I suggest sending the proposed changes to autoit.vim's maintainer; you can find his email addr in the autoit.vim file at line 4.  Otherwise its liable to be ignored.

**Comment by dkearns** [comment]
I've forwarded this on to the maintainer via email in case it wasn't done at the time.

**Comment by brammool** [comment]
Since it's an obvious mistake I'll include the fix.  But I'll leave this open, hoping that the maintainer picks it up.

**Comment by nitro322** [comment]
Hello. This is the first I recall hearing about this.  Thanks to @dkearns for the heads up.

I very rarely use AutoIt these days, so I'm probably not the best person to be listed as official maintainer, but happy to make this correction at least.  @brammool - how do you prefer I submit?  A pull request?  I don't have much experience with github, but think I should be able to figure that out.

**Comment by k-takata** [comment]
Fixed: https://github.com/vim/vim/commit/519cc559b08b800edc429688aece7ad6a00d41eb#diff-9a00f196a6504c0c3d0380217d305c50f6e26096847660cdbdf8cf7b3ec48c7eR936

**Comment by k-takata** [comment]
> But I'll leave this open, hoping that the maintainer picks it up.

Oh, I missed this. Reopening.

**Comment by dkearns** [comment]
> how do you prefer I submit? A pull request? I don't have much experience with github, but think I should be able to figure that out.

Thanks for attending to this.

As mentioned in other comments it was fixed by Bram yesterday so all you have to do is fix your local copy and [released version](https://www.vim.org/scripts/script.php?script_id=1239) so that the error won't accidentally be reintroduced if you send another update.

If you think it might be better maintained by someone else perhaps you could try some past contributors if there were any?  I had a very quick look at GitHub and there didn't seem to be any likely candidates.

There's a well documented history of changes here if someone wants to update it: https://www.autoitscript.com/autoit3/docs/history.htm

**Comment by brammool** [comment]
Glad the maintainer replied.  You can send me an updated version, attached to an email.  I already included the fix but you might want to adjust the header.  I'll close the issue now.
