### ISSUE TITLE
Unexpected % movement with square brackets and +

### ISSUE THREAD

**Issue by kevinoid** [vim/vim#9725]
### Steps to reproduce

1. `vim -u NONE -N`
2. Insert the following content:
    <pre>'%[' + ']'
   '[' + ']%'</pre>
3. Move the cursor over `[` at 1,3.
4. Press <kbd>%</kbd>.  **Unexpected:** Notice that the cursor jumps to 2,8 instead of 1,9.
5. Remove `+` and one space from each line leaving:
   <pre>'%[' ']'
   '[' ']%'</pre>
3. Move the cursor over `[` at 1,3.
4. Press <kbd>%</kbd>.  **Expected:** Notice that the cursor jumps to 1,7, as expected, and not to 2,6.

### Expected behaviour

The cursor would always jump between square brackets on the same line (as the `matchparen` highlighting suggests, if loaded, and as vim does without the `-N` option).

### Version of Vim

8.2.4324 (and 7.0)

### Environment

Reproduced with
* `cmd` in ConHost on Windows 10.0.19043.1466 with `%TERM%` unset.
* `bash` in `xfce4-terminal` 0.8.10 on Debian GNU/Linux testing with kernel 5.16 and `$TERM=xterm-256color`
* `bash` in `foot` 1.10.3 on Debian GNU/Linux testing with kernel 5.16 and `$TERM=xterm-256color`

**Comment by brammool** [comment]
The builti-in behavior of % is a bit simplistic, it doesn't notice the % starts inside quotes.
To do this better use the matchit plugin:
```
packad matchit
```
Since this can be done with a plugin, I don't think the builtin functionality needs to be improved.

**Comment by brammool** [comment]
> Thanks @brammool.  Could you explain a bit more why the quotes are
> relevant to the observed behavior?  I'm curious why `%` jumps between
> square brackets on different lines when `+` is present and between
> different lines when `+` is removed (but `matchparen` always
> highlights brackets on the same line).

It is not the plus that matters, it's that there is one character
between single quotes, and that is recognized like 'x' is.
As mentioned, this string detection is a bit primitive.  That's why the
plugin was added.

-- 
hundred-and-one symptoms of being an internet addict:
31. You code your homework in HTML and give your instructor the URL.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
