### ISSUE TITLE
cursor drawn in wrong position when removing text property

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9736]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        &foldmethod = 'marker'
        &lines = 24
        &number = true
        &showtabline = 2

        split
        wincmd _

        prop_type_add('Prop', {highlight: 'ErrorMsg'})
        autocmd TextChanged * prop_remove({type: 'Prop'}, line('w0'), line('w$'))

        var lines =<< trim END
            {{{xxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxx
            {{{1
        END
        var line = repeat('x', 20)
        lines += repeat([line], 26)
        lines->setline(1)
        normal! 22Gzvzbjj
    EOF
    )

The cursor is drawn in the bottom window.

**Expected behavior**

The cursor is drawn in the top window, because that's where its position really is.

**Version of Vim**

8.2 Included patches: 1-4337

**Environment**

Operating system: Ubuntu 20.04.3 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

If we press `k`, the cursor is correctly drawn in the top window.

---

In the previous command, there is no need to set `'number'`; it just makes the issue a little easier to understand.

---

Gif to illustrate:

![gif](https://user-images.githubusercontent.com/8505073/153325927-f5b7161e-6c6b-4732-8550-c48bded4b6dc.gif)

**Comment by brammool** [comment]
I managed to reproduce it only once and now I can't.  I wonder what it depends on.

**Comment by lacygoill** [comment]
I can reproduce consistently.  To be sure that I didn't miss some configuration, I've temporarily disabled all my xterm config in `~/.Xresources`, then run:

    xrdb ~/.Xresources

Then, I've started xterm right from the desktop launcher, using bash as the shell, and without config:

    xterm -e bash --norc --noprofile

Started Ubuntu 21.10 in a docker container:

    sudo docker run --interactive=true --tty=true --rm=true ubuntu:21.10

Compiled from source on 8.2.4362:

    apt update
    apt install git gcc make libncurses5-dev
    git clone --depth=1 https://github.com/vim/vim
    cd vim/
    ./configure
    make

And started Vim with `-Nu NONE -U NONE -i NONE`, and `HOME=/dev/null`:

    HOME=/dev/null ./src/vim -Nu NONE -U NONE -i NONE -S <(tee <<'EOF'
        vim9script
        &foldmethod = 'marker'
        &lines = 24
        &number = true
        &showtabline = 2

        split
        wincmd _

        prop_type_add('Prop', {highlight: 'ErrorMsg'})
        autocmd TextChanged * prop_remove({type: 'Prop'}, line('w0'), line('w$'))

        var lines =<< trim END
            {{{xxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxx
            xxxxxxxxxxxxxxxxxxxx
            {{{1
        END
        var line = repeat('x', 20)
        lines += repeat([line], 26)
        lines->setline(1)
        normal! 22Gzvzbjj
    EOF
    )

**Comment by lacygoill** [comment]
I think I have encountered the same issue today, with a simpler code:
```vim
vim9script
prop_type_add('Prop', {highlight: 'ErrorMsg'})
autocmd TextChanged * prop_remove({type: 'Prop'}, line('w0'), line('w$'))

&incsearch = true
&showcmd = true

['x'->repeat(&columns / 2)]->repeat(&lines * 2)->setline(1)
```
Press:

   - `V` to select the first line
   - `G` to jump at the end of the buffer, and select all of its lines
   - `:` to enter the command-line
   - `s/.//` to write a `:substitute` command which simply removes a character on each line of the selection
   - `Enter` to execute the `:substitute` command

The cursor ends up on the command-line; we can even scroll horizontally overe the "X substitutions on Y lines" message, which is confusing.

Gif to illustrate:

![gif](https://user-images.githubusercontent.com/8505073/167286237-0c7fe041-30f8-4d4d-a0cb-071501df8cf2.gif)

**Comment by LemonBoy** [comment]
Uhh... the problem has nothing to do with text properties, The problem is related to the use of `line()` using `w0` and `w$` as parameters, in that order.

```vim
vim9script
autocmd TextChanged * line('w0') + line('w$')
&showcmd = true
['x'->repeat(&columns / 2)]->repeat(&lines * 2)->setline(1)
```

As suggested in https://github.com/neovim/neovim/pull/18485 recomputing the botline every time the cursor moves is possibly wasteful, I don't have time ATM to check if a more targeted patch is possible, feel free to do so.

**Comment by brammool** [comment]
> Uhh... the problem has nothing to do with text properties, The problem
> is related to the use of `line()` using `w0` and `w$` as parameters,
> in that order.

Yes, but it also requires doing that at the right moment, which requires
an autocmd.

> ```vim
> vim9script
> autocmd TextChanged * line('w0') + line('w$')
> &showcmd = true
> ['x'->repeat(&columns / 2)]->repeat(&lines * 2)->setline(1)
> ```
> 
> As suggested in https://github.com/neovim/neovim/pull/18485
> recomputing the botline every time the cursor moves is possibly
> wasteful, I don't have time ATM to check if a more targeted patch is
> possible, feel free to do so.

Not recomputing botline gets tricky.  As the problematic example shows
botline is used to decide whether other things need to be updated.

I was wondering whether invalidating botline only when the cursor is on
it or below it might work.  Or only after text has changed.  It is a bit
hard to decide.  I don't think there is enough test coverage to just try
something and hope it works.

-- 
hundred-and-one symptoms of being an internet addict:
147. You finally give up smoking...because it made the monitor dirty.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
