### ISSUE TITLE
vim9-lambdas cannot be used on the RHS of mappings

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9747]
### Steps to reproduce

The new vim9-lambda syntax cannot be used on the RHS of a mapping.

1. Run `vim --clean -S test.vim`, with
```vim
vim9script
nnoremap <buffer> ]] <cmd>call range(3)->map((x, y) => 0)<cr>
```

2. Press `]]`.
3. Result: 
```
E121: Undefined variable: x
E116: Invalid arguments for function map((x, y) => 0)
```

The old syntax works as expected:
```vim
vim9script
nnoremap <buffer> ]] <cmd>call range(3)->map({x, y -> 0})<cr>
```

---

Using the new lambda syntax for a command seems to work, though:
```vim
command Test call range(3)->map((x, y) => 0)
```

### Expected behaviour

It should be possible to use the new vim9 syntax everywhere.

### Version of Vim

8.2.4342

**Comment by lacygoill** [comment]
Try to use the new [`:help <ScriptCmd>`](https://vimhelp.org/map.txt.html#%3CScriptCmd%3E) keycode:

    nnoremap <buffer> ]] <cmd>call range(3)->map((x, y) => 0)<cr>
                          ^^^
                          ✘

    nnoremap <buffer> ]] <ScriptCmd>call range(3)->map((x, y) => 0)<cr>
                          ^-------^
                             ✔

It's provided by the patch [8.2.4099](https://github.com/vim/vim/releases/tag/v8.2.4099).

---

Unrelated, but you don't need `:call` in the definition of the `:Test` command:

    command Test call range(3)->map((x, y) => 0)
                 ^--^

Because it runs in the context of the script where it's defined.  If it's defined in a Vim9 script, then `:call` is optional.

**Comment by lacygoill** [comment]
Note that the issue still persists in some cases:

   - `:help i_CTRL-R_=`
   - `:help c_CTRL-\_e`
   - `:help stl-%{`
   - `:help 'statusline'` and `:help 'tabline'` (`%!Func()`)
   - `:help input()` (3rd `{completion}` argument)
