### ISSUE TITLE
Maximum value of maxcombine changed from 6 to 8

### ISSUE THREAD

**Issue by ghost** [vim/vim#9767]
Variable 'maxcombine', maximum number of bytes in UTF-8, default is 2, maximum 6, I want this maximum to be 8.
From 2010 by UNICODE IVS.

UTF-8 is up to 8 bytes in the current standard.
For example, the example of a person's name: There are a lot of people who cannot distinguish even Japanese people, there are font restrictions, and it is enlarged.

Isn't the example good quality? 
The Japanese interpret these as personal names and have a well-organized style.
At the same time, he concluded that it was not a real person's name.
Drama for children, prevention of duplication with real names.
In Japan, a person with the same name as a drama fits a social lynching, and obituaries are buzzed on SNS.

![image](https://user-images.githubusercontent.com/99569800/153784951-184889f1-ae20-42d4-87c7-2b2dc3c377bf.png)

**Comment by ntakcat** [comment]
What is important is where did the current maximum value of 6 come from?

![image](https://user-images.githubusercontent.com/99569800/153786107-ec85d79d-3754-497a-a01a-d40c0a23c18d.png)

There are many sideways in my explanation.
There are many variants in Japanese addresses and names, and if you make a mistake between Japanese people, you will be despised as a person who lacks etiquette.

**Comment by zeertzjq** [comment]
Are there any composing characters in your example?

**Comment by k-takata** [comment]
In my understanding, 'maxcombine' is the number of code units, not bytes.
In your first sample, U+7980 U+E0100 are only two code units. No need to change 'maxcombine' to 8 in this case.

IVS is supported at least on Windows GUI with DirectWrite since [8.0.1234](https://github.com/vim/vim/commit/a6ce1ccf5c10baa5c2a25897c46961d751a21dda). See #2206 (and https://github.com/vim-jp/issues/issues/1106).
If the characters are shown in the same shape even with IVS in this environment, your font doesn't support IVS. You should use a font that support IVS.

**Comment by ntakcat** [comment]
I understand the commentary, uh, my ability has deteriorated. I'm old.
Yeah, maxCOMBINE, oh ...

Don't you call me? Don't call me ... (go quietly out of the stage)

**Comment by brammool** [comment]
The maximum is needed to limit the amount of memory used and performance for copying text around.
The thought was that nobody would need more than 6.
I wonder how many Vim users would use more than 6, if the limit would be increased.
