### ISSUE TITLE
Vim9: inconsistent rule with regard to the `s:` prefix when assigning to script-local variable in `:def` function

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9824]
Since the patch [8.2.4360](https://github.com/vim/vim/commit/a749a42ed25534c88c636e5ab6603f1f97b857a4), we cannot use the `s:` prefix when defining a script-local function:
```vim
vim9script
def s:Func()
enddef
```
    E1268: Cannot use s: in Vim9 script: s:Func()

Nor when calling a script-local function:
```vim
vim9script
def Func()
enddef
s:Func()
```
    E1268: Cannot use s: in Vim9 script: s:Func()

Nor when declaring a script-local variable at the script level:
```vim
vim9script
var s:number = 123
```
    E1268: Cannot use s: in Vim9 script: s:number = 123

But we can when assigning to a script-local variable in a `:def` function:
```vim
vim9script
var number = 123
def Func()
    s:number = 456
    echomsg s:number
enddef
Func()
```
    456

The rule(s) would be more consistent and easier to understand if `s:` was disallowed all the time, and the last snippet gave an error just like all the other ones.

**Comment by brammool** [comment]
I had this on my todo list.  I was wondering if we should disallow "s:var" completely, or only when the script is Vim9 script?
In legacy script script-local variables are declared with s:var, so perhaps a :def function should also use s:var?
Using s:var at the script level but not in a :def function looks confusing to me.

**Comment by lacygoill** [comment]
> Using s:var at the script level but not in a :def function looks confusing to me.

I guess we could allow `s:` in a `:def` function defined in a legacy script.  But we should probably still allow `s:` to be omitted, so that the rules are consistent with a `:def` function in a Vim9 script.

In a Vim9 script, rules would be easier to understand if `s:` was disallowed everywhere; unless there is some corner case that I'm missing where we can't do without it.

**Comment by brammool** [comment]
It is actually mentioned in the help:
"In :def functions the use of "s:" is optional.  This is because in legacy
script the "s:" might be needed.  Disallowing the use of "s:" only in a :def
function in Vim9 script would be a bit confusing."
However, your argument for consistency, not using "s:" in a :def function because it is used nowhere, defeats the "a bit confusing" part.  As I mentioned, in a legacy script you will see "s:" everywhere, thus using "s:" in a :def function too would not be confusing.  While in a Vim9 script "s:" is not used anywhere, thus using it in a :def function would be confusing.

**Comment by lacygoill** [comment]
> It is actually mentioned in the help:

Ah right, sorry, I didn't keep track of the rules.  So, I guess we should allow it everywhere in a legacy script, and disallow it everywhere in a Vim9 one.

**Comment by brammool** [comment]
Except in legacy functions "s:" always is needed there.  But using a legacy function in Vim9 script should be rare.
