### ISSUE TITLE
Vim9: cannot quote reference to nested function when passing it to `function()`

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#9829]
**Steps to reproduce**

Run this shell command:

    vim -Nu NONE -S <(tee <<'EOF'
        vim9script
        def Outer()
            def Inner()
                echomsg 'from Inner()'
            enddef
            function('Inner')()
        enddef
        Outer()
    EOF
    )

`E700` is given:

    E700: Unknown function: Inner

**Expected behavior**

No error is given.  `from Inner()` is echo'ed.

**Version of Vim**

8.2 Included patches: 1-4446

**Environment**

Operating system: Ubuntu 20.04.4 LTS
Terminal: xterm
Value of $TERM: xterm-256color
Shell: zsh 5.8

**Additional context**

If we remove the quotes around the reference to `Inner`, no error is given:
```vim
vim9script
def Outer()
    def Inner()
        echomsg 'from Inner()'
    enddef
    function(Inner)()
enddef
Outer()
```
    from Inner()

But we can use quotes for a function defined in another scope.  Like the global scope:
```vim
vim9script
def Outer()
    def g:Inner()
        echomsg 'from g:Inner()'
    enddef
    function('g:Inner')()
enddef
Outer()
```
    from g:Inner()

Or the script-local scope:
```vim
vim9script
def Inner()
    echomsg 'from Inner()'
enddef
function('Inner')()
```
    from Inner()

It seems inconsistent to disallow quotes only for function-local functions.

**Comment by brammool** [comment]
This will be difficult to make to work.  The string "Inner" is passed to function(), which evaluates it at runtime.
But this is in the script scope, as there is no access to function-local variables, and the "Inner" funcref is only defined inside the function.
We could probably make it work when we recognize the string constant and evaluate it at compile time.  But when it is not a string constant this would need to happen at runtime,
Since there is a simple solution, which also means a compile time error can be given for mistakes, I would prefer to leave it like this.  I'll add a note in the help.
