### ISSUE TITLE
`end` (for `endif`) doesn't indent properly in vimscript files

### ISSUE THREAD

**Issue by telemachus** [vim/vim#9877]
### Steps to reproduce

1. Open foo.vim and enter this text:
```vim
function Foo()
    if 1
        return 0
        end
    endfunction
```

### Expected behaviour

I would expect this indentation:
```vim
function Foo()
    if 1
        return 0
    end
endfunction
```

### Version of Vim

8.2.4488

### Environment

macOS (BigSur and Monterey)
iTerm2
$TERM = xterm-256color
bash 5.1.16

**Comment by telemachus** [comment]
Two notes:
+ This indents as expected on 8.2.2434 (checked on a Debian VM).
+ Maybe this is related to #9868, though that's completely a guess.

**Comment by brammool** [comment]
Although ":end" is recognized as ":endif", it is really recommended to write ":endif".
The shortest form is even ":en", which already was not recognized, for good reasons.

The original reason "end" is not triggering indenting is that some people use a variable called "ends".
We don't want to trigger indent when typing "end", at least "endi" is needed.  One step further would be require "endif",
to avoid mis-triggering on a variable called "ending".

Is there a specific reason to type "end" instead of "endif"?  

I know the shortest version of a command has always been accepted, and I don't intend to change that.
But in scripts using a longer name makes it much more readable.  Encouraging that with indenting might not be a bad idea.

**Comment by telemachus** [comment]
> Is there a specific reason to type "end" instead of "endif"?

My specific reason is that I'm dealing with scripts by other people and some are reasonably old. It's not always up to me to change the style completely. In those cases, it's unfortunate that autoindentation, `=`, and `==` no longer work as I expect. (That's how I ran into this and the related issue about `function!` to begin with: I was working with other people's scripts.)

> But in scripts using a longer name makes it much more readable. Encouraging that with indenting might not be a bad idea.

I agree that `endif` is better, and I always use it in my own scripts. But I don't always have complete control (e.g., when dealing with other people's code). Fair enough to encourage the better names, but maybe you should document that `end` (and even `en`!) is allowed by the grammar but not recognized by automatic indentation? If you say that explicitly, you may encourage people even more. Thanks for considering this.

**Comment by brammool** [comment]
There already was a remark in the help to use ":endif" instead of ":end", I can add a note that it also matters for indenting.

When working with old scripts and making only small changes then manually indenting the occasional "end" should not be a big problem.  When making bigger changes, such as adding a surrounding "if"/"endif" then updating the "end" to "endif" inside it doesn't seem a bad idea.

Thus I do not yet see enough reason to recognize "end" as "endif" for indenting.

**Comment by telemachus** [comment]
> Thus I do not yet see enough reason to recognize "end" as "endif" for indenting.

Okay. I'll close this then. Thanks for clarifying.
