### ISSUE TITLE
Vim9: functions assigned to commands are not visible

### ISSUE THREAD

**Issue by noscript** [vim/vim#9907]
### Steps to reproduce

1. Create test.vim:
```vim
vim9script

def MyFunc()
  echom "hello"
enddef

command! MyCmd MyFunc()
```
2. `vim -g --clean +'source test.vim'`
3. Execute the command:
```
:MyCmd
hello
```
4. Print command definition:
```
:command MyCmd
    Name              Args Address Complete    Definition
    MyCmd             0                        MyFunc()
```
5. Call the function assigned to the command:
```
call MyFunc()
E117: Unknown function: MyFunc                                                                                                                                  
```

### Expected behaviour

Functions assigned to commands are globally visible.

### Version of Vim

8.2.4394

### Environment

GUI

**Comment by noscript** [comment]
> How about this:
> 
> ```
> command Renamed OldName
> ```

It is a bit more complicated than this. I would not want an alias to a command, but to rename a command for real, so the old command disappears. There are plugins that define many similar commands, so using command completion becomes very difficult. So I would like to only keep some commands visible to completion and rename other commands (so that I could still use them in mappings).

With legacy vim, I could define a new command and delete the old command.

>You can do that if the command calls a global function, but I don't think you can do that if it calls a script-local one.

I can do that for any commands defined in legacy script using script id. That's a bit difficult to do but still doable.

> Alternatively, maybe we would need a new cmdarg() function, similar to maparg(). It could return the rhs of an arbitrary user-defined command.

I think that would be great solution. I could use the rhs in a new command and delete the old command.

**Comment by brammool** [comment]
So, you would load a plugin, and then delete commands it defined.
That's a bit nasty.  I can imagine Plugins are not prepared for this kind of use.

Making the function global is not desired, it should be private to the plugin.

If you would get the argument of the command and define a new command with that, it won't work, since the command is not defined in the script where the function is located.  Unlike mappings, the function name is not expanded to the <SNR> form.

The best solution I see is that the plugin provides a way to specify the command names you like.
E.g. for the "foobar" plugin set "g:foobar_that_name" to "MyCmdName".
The plugin would then need to do something like:
```
if exists('g:foobar_tat_name')
  exe 'command ' .. g:foobar_that_name .. ' ThatFunction()'
else
  command ThatCommand ThatFunction()
endif
```

More generally, using a dictionary to specify the configuration for the plugin would be a generic solution.

**Comment by noscript** [comment]
I would not call it nasty. Commands were always for users, not for plugin internals. I'm sorry if I had a wrong picture.

>The best solution I see is that the plugin provides a way to specify the command names you like.
E.g. for the "foobar" plugin set "g:foobar_that_name" to "MyCmdName".

That is a bit too much to ask from plugin developers.

**Comment by noscript** [comment]
I agree that deleting commands may still break some plugins.

**Comment by brammool** [comment]
> I would not call it nasty. Commands were always for users, not for
> plugin internals. I'm sorry if I had a wrong picture.

One of the patterns used by plugins is to check if something was already
defined, e.g. with "exists(':PluginCommand')", and bail out if it was
already defined.  If you delete the command, the plugin might do
something unpredictable.

> >The best solution I see is that the plugin provides a way to specify the command names you like.
> E.g. for the "foobar" plugin set "g:foobar_that_name" to "MyCmdName".
> 
> That is a bit too much to ask from plugin developers.

I don't think it is complicated.  Because plugins have to avoid using
the same name as other plugins, the command names may get a bit long or
hard to type.  Allowing the user to pick their own name is a very nice
thing to have.

-- 
hundred-and-one symptoms of being an internet addict:
209. Your house stinks because you haven't cleaned it in a week.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi,

On Tue, Mar 8, 2022 at 2:51 PM lacygoill ***@***.***> wrote:

> I know that introducing new options is frowned upon, considering that we
> already have a lot, but a new 'cmdignore' option would fix the real
> issue, which was described here:
>
> There are plugins that define many similar commands, so using command
> completion becomes very difficult.
>
> So, for example, if a user has 2 plugins installing a bunch of commands
> starting with the prefixes Foo and Bar, they could tell Vim that they
> don't want any of them to be suggested after pressing Tab while on the
> command-line:
>
> set cmdignore=Foo*,Bar*
>
>
>
With the support for fuzzy completion of command names (set 'wildoptions'
to 'fuzzy'),
it should be easy to complete command names ignoring case and to complete
names
after typing a few characters anywhere in the name.

Regards,
Yegappan

**Comment by lacygoill** [comment]
> With the support for fuzzy completion of command names (set 'wildoptions'
> to 'fuzzy'), it should be easy to complete command names ignoring case and to complete
> names after typing a few characters anywhere in the name.

While the new `fuzzy` value of the `'wildoptions'` is great to increase the number of suggestions, I think the OP is looking for the opposite: a way to decrease the number of suggestions, by pruning arbitrary Ex commands.

**Comment by noscript** [comment]
Yes, hiding some commands from the completion would be a solution to my original problem.

**Comment by brammool** [comment]
> I know that introducing new options is frowned upon, considering that
> we already have a lot, but a new `'cmdignore'` option would fix the
> real issue, which was described here:
> 
>    > There are plugins that define many similar commands, so using command completion becomes very difficult.
> 
> So, for example, if a user has 2 plugins installing a bunch of
> commands starting with the prefixes `Foo` and `Bar`, they could tell
> Vim that they don't want any of them to be suggested after pressing
> Tab while on the command-line:
> 
>     set cmdignore=Foo*,Bar*

I don't like doing it that way.  One option for an unknown number of
plugins, with possibly hiding some that you do want to see.

It would be better to explicitly "alias" a command.  So you would
install a new command that invokes an existing one, and then hides that
existing one.

	commandalias MyCommand PluginLongNameCommand

It would add a flag to PluginLongNameCommand to not show it for
completion.

-- 
hundred-and-one symptoms of being an internet addict:
210. When you get a divorce, you don't care about who gets the children,
     but discuss endlessly who can use the email address.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
